### ISSUE TITLE
Incorrect tooltip size when tooltip.useHTML is set to true

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#10009]
#### Actual behaviour
When chart container's width is not wide enough to display a long tooltip, the tooltip is displayed incorrectly:
![tooltip1](https://user-images.githubusercontent.com/23310742/51839328-3c02b900-2309-11e9-9263-0249f0419026.png)
![tooltip2](https://user-images.githubusercontent.com/23310742/51839333-3dcc7c80-2309-11e9-87d2-1aa5ca5c4e15.png)

Looks like the issue from the first image occurs since Highcharts 6.0.5, and the second issue since Highcharts 6.1.0

#### Live demo with steps to reproduce
jsFiddle: https://jsfiddle.net/BlackLabel/hq7g2bdm

#### Product version
Since 6.0.5 and 6.1.0 until now (7.0.2)

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
A little history breakdown:

### In v6.0.4
Everything looked good:
![skjermbilde 2019-02-07 kl 09 48 31](https://user-images.githubusercontent.com/227836/52399816-a829ad80-2abd-11e9-906d-6b0f6c7f0224.png)
![skjermbilde 2019-02-07 kl 09 49 40](https://user-images.githubusercontent.com/227836/52399843-b7a8f680-2abd-11e9-93c4-d6796a43c864.png)

### Since 6bf7ff5c83
The long tooltip lost its word-wrap and was clipped on the right side:
![skjermbilde 2019-02-07 kl 09 51 17](https://user-images.githubusercontent.com/227836/52399944-05bdfa00-2abe-11e9-9801-6f1689cf5d5b.png)

### Since 2c8cea8e44
The short tooltip (big blue slice) would extend to the full width of the chart:
![skjermbilde 2019-02-07 kl 09 58 25](https://user-images.githubusercontent.com/227836/52400258-f1c6c800-2abe-11e9-968c-18d46343ad84.png)
Returning to the small slice, the text would be word-wrapped, but it would overflow the tooltip border:
![skjermbilde 2019-02-07 kl 09 56 16](https://user-images.githubusercontent.com/227836/52400238-de1b6180-2abe-11e9-9bb7-39aa6bf6670f.png)

**Comment by TorsteinHonsi** [comment]
Demo with the fix applied: https://jsfiddle.net/highcharts/zjxwtL27/
