### ISSUE TITLE
Series gap on DST transition

### ISSUE THREAD

**Issue by OhadC** [highcharts/highcharts#10000]
#### Expected behaviour
Should not show a gap.

#### Actual behaviour
Showing a data gap.
If pointRange > gapSize, Gap should be shown only when there is no data between 2 points.

#### Live demo with steps to reproduce
https://jsfiddle.net/0r7L3ujf/6/
![image](https://user-images.githubusercontent.com/4123639/51802498-5ed29600-2253-11e9-9d4e-316bbcb9e882.png)
![image](https://user-images.githubusercontent.com/4123639/51802518-79a50a80-2253-11e9-9438-e35ebfae6917.png)

#### Product version
7.0.2

#### Affected browser(s)
Chrome latest.

**Comment by KacperMadej** [comment]
Hi @OhadC 

Thank you for contacting us about the problem.

You have forced dataGrouping, so your gapSize option will be changed according to the [API reference](https://api.highcharts.com/highstock/plotOptions.series.gapSize):

> In case when dataGrouping is enabled, points can be grouped into a larger time span. This can make the grouped points to have a greater distance than the absolute value of gapSize property, which will result in disappearing graph completely. To prevent this situation the mentioned distance between grouped points is used instead of previously defined gapSize.

When full time range is being shown only 2 points are connected because the gapSize is based on minimal point distance and there's the only one distance like that - on the time change when 1 hour is skip making the group with it the shortest.

In case of a single missing points it's better to add a null point (by default [connectNulls](https://api.highcharts.com/highstock/series.line.connectNulls) is set to `false`) instead of using the gaps.

This doesn't look like a bug.

**Comment by KacperMadej** [comment]
Grouped data has equal time intervals for points that are not equal when a time change occurs. The day with the time change has 25 hours, so more than the smallest points interval for the grouped points. The same applies for other time units for witch points are grouped (e.g. hours multiples). For smaller than our units the grouped points are not affected by the time change, so in your image plot is without a gap.

> I set gapSize to 1 hour

Data is grouped, so the 1 hour rule is not respected - instead a different time units is used that is based on grouped data and explained in API quoted in my previous comment.

**Comment by OhadC** [comment]
Ohh I get it now..
So as you explain, and as explained also in the code here: https://github.com/highcharts/highcharts/issues/7686#issuecomment-358692200
the current gapSize is: max(userGapSize, groupingSize) 
The group with the 25 Hours day have 1 hour more than the groupingSize, so it have a gap..

I don't there is a quick but clean fix for that, am I right?

Is there any way to know if a group have bigger interval than others, and do different logic based on that?

**Comment by TorsteinHonsi** [comment]
I'm tempted to call this a bug. Since we're defaulting to data grouping intervals, we should also consider the outcome of the grouping. This code takes care of the `gapSize` when grouping is enabled:

https://github.com/highcharts/highcharts/blob/8b6989dfa7811cc541c7fe6da666713f8be8610f/js/modules/broken-axis.src.js#L479-L482

The issue is resolved if we multiply the `groupingSize` by 25/24. I can't see that it would hurt other cases of gapSize either, except we may have to find a smarter formula for example when there are groups every 12h or 6h. Maybe we can compute this in the data grouping module and set a `gapSize` property to `currentDataGrouping`.

**Comment by TorsteinHonsi** [comment]
PS: Width a smaller width the chart breaks entirely: https://jsfiddle.net/highcharts/43tpbav6/2/

**Comment by KacperMadej** [comment]
@TorsteinHonsi 
About that PS - the smallest point interval is between February and March and only those 2 points are connected as everywhere else gap is placed between points. This might be also a case that will break the fix through multiply, because in this case the chart has 3 sizes of point intervals - "-1h" on one time change, "+1h" on second time change, "0h" on any other time range. The fix would resolve the problem for "0h" by not placing a gap there, but "+1h" will stay broken.

**Comment by TorsteinHonsi** [comment]
So it's basically the same problem. The solution being that when we do data grouping, the `gapSize` must equal the _largest_ distance between any to data groups.

**Comment by OhadC** [comment]
@TorsteinHonsi @KacperMadej Thank you so much!

Any idea when the fix should be coming out? 
I need it to fix a chart component that already in production.
As far as I know that's not an easy fix that I can just wrap Highcharts library with it.. Am I right...?

**Comment by TorsteinHonsi** [comment]
> If we'll use the largest distance, then a gap will never be placed, because there never will be a distance larger than the largest.

Good catch, but by using the largest distance of the `groupPositions`, we see omit this. We can leave out data points, then there will be group positions that don't have data, and those will become gaps: https://jsfiddle.net/highcharts/74q2yo5d/6/

**Comment by TorsteinHonsi** [comment]
@OhadC The fix should be out within the end of this week. 

> As far as I know that's not an easy fix that I can just wrap Highcharts library with it.. Am I right...?

Yes I'm afraid so... This is a bit interweaved.
