### ISSUE TITLE
Series don't hide when expected with boost

### ISSUE THREAD

**Issue by callumacrae** [highcharts/highcharts#10013]
Sorry if this is a duplicate, there seems to be a tonne of issues around boost and hiding series, but I couldn't find a similar one to this!

#### Expected behaviour

Hiding a series hides the series.

#### Actual behaviour

Hiding a series doesn't hide the series.

#### Live demo with steps to reproduce

https://jsfiddle.net/p2kxm7rv/

Sorry, that's a tonne of data. Couldn't replicate the bug after removing some data.

- Click GoGo Zooom to hide
- Click Konex to hide
- Click MayZing to hide

MayZing doesn't hide.

Clicking randomly on different series does all sorts of weird stuff.

Here it is in gif form:

![ezgif com-optimize 8](https://user-images.githubusercontent.com/472830/51855221-a1b06e80-2324-11e9-90b2-6fdd0eb7dcc8.gif)

#### Product version

Highcharts 6.11 and Highcharts 7

#### Affected browser(s)

All.

**Comment by KacperMadej** [comment]
Hi @callumacrae 

Thank you for reporting about the boost module issue.

@cvasseng boost issue fyi

**Comment by pawelfus** [comment]
### Simplified demo: 
https://jsfiddle.net/BlackLabel/84oukj57/1/ - simply hide and show "Series 1" a few times - markers will remain.

In short, it's caused by using boosted and not boosted series at the same time.

### Workaround
Boost all series at the same time, for example by setting `boostThreshold` to a very low value: https://jsfiddle.net/BlackLabel/9kxvands/
