### ISSUE TITLE
Histogram Binning Breaks on Certain Values

### ISSUE THREAD

**Issue by Blitz2145** [highcharts/highcharts#10025]
#### Expected behaviour
Bins produced regularly.

#### Actual behaviour
Bins produced are tiny.

#### Live demo with steps to reproduce
https://codepen.io/anon/pen/jdyEZx

See codepen for repro case, codepen based on docs example, just different data.

#### Product version
HighCharts v7.0.2

#### Affected browser(s)
Chrome 71.0.3578.98, and probably all browsers (I suppose)

**Comment by sebastianbochan** [comment]
Hi @Blitz2145,
Thank you for reporting.

The solution is set [pointRange](https://api.highcharts.com/highcharts/plotOptions.column.pointRange) param as 1.

```
  plotOptions: {
    series: {
      pointRange: 1
    }
  },
```

**Demo**:
- https://codepen.io/anon/pen/WPRZQg

FYI @Denyllon

**Comment by Denyllon** [comment]
@sebastianbochan Not really. This issue will not be resolved by setting `pointRange` equal to `1`, because that parameter should be set automatically equal to current `binWidth` value here. Furthermore, this issue is directly related with https://github.com/highcharts/highcharts/issues/9128.

It is possible to workaround it by applying the code below:
```js
(function(H) {
  H.wrap(H.seriesTypes.histogram.prototype, 'derivedData', function(proceed, baseData, binsNumber, binWidth) {
    var data = proceed.apply(this, Array.prototype.slice.call(arguments, 1));
    this.options.pointRange = this.binWidth
    return data
  })
})(Highcharts)
```

Live example: https://codepen.io/anon/pen/JxWQJJ
