### ISSUE TITLE
Can't pan after zoom in a Scatter

### ISSUE THREAD

**Issue by Maxreglez** [highcharts/highcharts#10046]
#### Expected behaviour
i want to pan in both charts.

#### Actual behaviour
Steps to reproduce
zoom in in the scatter and pan with shift and mouse.
go to the chart with lines and zoom in and pan with shift an mouse.
now the lines are not panable.
#### Live demo with steps to reproduce
https://jsfiddle.net/byfs9e54/8/

**Comment by pawelfus** [comment]
Hi @Maxreglez 

Thanks for reporting the issue. This is caused by your code in `setExtremes()` event (lines: 154-205), where you **replace** build-in panning with your own. Please, fix your `wrap()` for panning. If you want to change panning for the second chart only, then instead of changing all `Chart.prototype`, change `thisChart` only: https://jsfiddle.net/BlackLabel/oqu3519s/6/

**Comment by Maxreglez** [comment]
thanks that helps
