### ISSUE TITLE
Custom annotation - export possible only to SVG

### ISSUE THREAD

**Issue by Svancara** [highcharts/highcharts#10055]
#### Expected behaviour
Custom annotations should be exported to all available images formats.

#### Actual behaviour
Custom annotations are exported only to SVG.
Not exported to PNG, JPEG and PDF.

#### Live demo with steps to reproduce
See Highcharts demo in https://api.highcharts.com/highstock/annotations:

**Custom annotation, Fibonacci retracement** 
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/annotations/fibonacci-retracements

#### Product version
Highstock v7.0.2

**Comment by KacperMadej** [comment]
Hi @Svancara 

Thank you for reporting about the problem.

**Comment by pawelfus** [comment]
*Internal note:*
It looks like annotation that is outside the current extremes is not exported, no matter the extremes change in navigator. If an annotation is visible from the chart init, it works fine: https://jsfiddle.net/BlackLabel/fjr1pae5/

**Comment by pawelfus** [comment]
*Internal note:*
Debugging leads to `-9e9` for y-position for labels. I will continue investigating the issue tomorrow.

**Comment by pawelfus** [comment]
Directly caused by these lines:
- https://github.com/highcharts/highcharts/blob/654be6a4613fa4f03864e8b7748f4fc7b6b7875e/js/annotations/controllable/ControllableLabel.js#L215-L226
- https://github.com/highcharts/highcharts/blob/654be6a4613fa4f03864e8b7748f4fc7b6b7875e/js/annotations/controllable/ControllableLabel.js#L283-L286

@TorsteinHonsi - is is safe to change to -9999? I remember we had a discussion, but I don't remember the result..

**Comment by TorsteinHonsi** [comment]
Yes, we have -999 all over the place.
