### ISSUE TITLE
Highcharts is exported to pdf using Python (xhtml2pdf), and the discount becomes black thick lines.

### ISSUE THREAD

**Issue by duoduoObama** [highcharts/highcharts#10146]
![p1_eyifhoben n mvi84 l0](https://user-images.githubusercontent.com/30836806/52838009-17da1100-312c-11e9-9c4a-19904b76bde1.png)
![pz_i93 l b 57fm6_ ab6q](https://user-images.githubusercontent.com/30836806/52838013-1a3c6b00-312c-11e9-9092-49fd64449104.png)
I don't know why it turns into a black line, and it's very thick. I hope someone can answer it. Thank you.

**Comment by TorsteinHonsi** [comment]
Highcharts overlays a tracker object on top of lines, in order to be able to apply the `tooltip.snap` feature. It has a default stroke of `rgba(192,192,192,0.0001)`. You can see it in all charts if you apply a visible stroke to it: http://jsfiddle.net/highcharts/erhpmf2v/

Most likely, xhtml2pdf is not able to render the semi-transparency of this object, so it makes it opaque. The workaround would be to remove it before exporting.

```js
Highcharts.addEvent(Highcharts.Chart, 'getSVG', function (e) {
	e.chartCopy.container.querySelectorAll(
    	'.highcharts-tracker-line'
    ).forEach(elem => elem.remove());
});
```
[View it live on jsFiddle](http://jsfiddle.net/highcharts/erhpmf2v/6/).

**Comment by duoduoObama** [comment]
thank you vary much Solve my problem along your way, Touched to cry

**Comment by FerociousCentaur** [comment]
how did u include highcharts in pdf with xhtml2pdf...please help me with this

**Comment by sebastianbochan** [comment]
Hi @FerociousCentaur,
Please use our [support](https://www.highcharts.com/support) channels for general questions.

**Comment by FerociousCentaur** [comment]
Hi @sebastianbochan .
Thanks for ur reply.I am sorry that i commented it this way.Actually i serached internet,stackoverflow,and highchart forums but nothing helped but then i saw this post where @duoduoObama  did the same thing which i wanted to acheive so became curious.
