### ISSUE TITLE
Script error (length is NaN) when scrollbar from HighStock is used w/ Gannt chart and collapsing

### ISSUE THREAD

**Issue by flakey-bit** [highcharts/highcharts#10176]
#### Expected behaviour
Gannt chart vertical scrolling (from HighStock) should work even when all series' are collapsed.

#### Actual behaviour
On supplied JSFiddle, if the scrollbar is scrolled after collapsing "New Offices" we see script errors

`Error: <rect> attribute y: Expected length, "NaN".`

#### Live demo with steps to reproduce
https://jsfiddle.net/kr4c0wz3/

#### Product version
v7.0.3

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @flakey-bit 

Thanks for reporting, and sorry for the radio silence! @jon-a-nygaard will take a look.

**Comment by jon-a-nygaard** [comment]
One of the things going wrong here is that the broken axis is using `closestPointRange` to modify the extremes, if the new min and max is within an axis break. This does not go well because yAxis is never assigned the property `closestPointRange`.
This can be worked around in this case by setting `closestPointRange = 1` on the Axis prototype https://jsfiddle.net/jon_a_nygaard/v3p0o6zm/

Even if the demo is not throwing an error anymore, it does not seem right to me that the points within the collapse should be scrollable as in the demo above, so I will see if I can do something about that as well.

**Comment by jon-a-nygaard** [comment]
An alternative workaround is to use a container around the chart with an html scrollbar as in the following example: https://jsfiddle.net/jon_a_nygaard/ocug46rn/

**Comment by jon-a-nygaard** [comment]
The PR #10205 includes a fix which will solve the issue of the script error. It is currently in review, but if approved then it is expected to be included in the next maintenance release.

Please see #9378 to comment and follow the progress of the usability of scrollbar with gantt.
