### ISSUE TITLE
Wrong tooltip container size for multi-line tooltips with useHTML

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#10195]
#### Actual behaviour
The toolip's container is not wide enough under these circumstances:

- tooltip.outside = true
- tooltip.useHtml = true
- Tooltip contains a word that is wider than the chart
- The tooltip text uses more that 1 line

Fixing #10009 did NOT fix this bug. My fiddles use highcharts.js master.

#### Live demo with steps to reproduce
http://jsfiddle.net/kzoon/uk8canhv/24/

When the tooltip is multi line due to wrapping, the same problem occurs:
http://jsfiddle.net/kzoon/uk8canhv/25/

Single line with 1 word renders OK:
http://jsfiddle.net/kzoon/uk8canhv/27/

#### Product version
github.highcharts.com/master/highcharts.js

**Comment by sebastianbochan** [comment]
Hi @kzoon,
Thank you for reporting.

You can set the CSS styles `word-break:break-all`.

**Demo:**
- http://jsfiddle.net/BlackLabel/nshem54b/

**Comment by kzoon** [comment]
Is there any progress on this issue? 
Luckily the problem isn't fatal and doesn't occur that often, but when it does I don't have a solution. The workaround doesn't help much, as it will break smaller words in all the wrong places (see http://jsfiddle.net/kzoon/3uv8e9bo/1/)

**Comment by pawelfus** [comment]
**Workaround:**
Set `tooltip.style.width`: http://jsfiddle.net/BlackLabel/j8mqg4yx/

Removing empty space after "multiline" word works fine too: http://jsfiddle.net/BlackLabel/2uxkb35w/ (but not if we have multiple words there: http://jsfiddle.net/BlackLabel/ue41r6oa/)

Some debugging notes:
- this is how it works in HTML too: http://jsfiddle.net/BlackLabel/1o2y8hfj/
- setting `overflow: hidden` works as expected: http://jsfiddle.net/BlackLabel/os71uh58/
- it's not related to one vs multi lines, but in general to word wrapping: http://jsfiddle.net/BlackLabel/u2djLv9h/ (no `<br/>` tags) - we apply `style.width` only to labels that can be wrapped (an empty space `" "` or `"-"` must exist in a string)
- this happens because we set width for the tooltip to be the same as chart's spacing box width. In SVG when we check bounding box we get real dimensions, in HTML we get `offsetWidth` (not `scrollWidth`). We can't change this because this test will fail: http://utils.highcharts.local/samples/#test/unit-tests/axis/labels-usehtml - it's interesting that SVG labels don't cause this issue (needs further debugging).

**Comment by benelliott** [comment]
bump

**Comment by karolkolodziej** [comment]
Hi @FeBe95! 

You are right, it looks like it is solved now! Huge thanks for the investigation and for describing this 😉
