### ISSUE TITLE
x-Axis title margin changes on font size change

### ISSUE THREAD

**Issue by ShivaRam1989** [highcharts/highcharts#10202]
#### Expected behaviour
After setting the margin or y property of Title for x-axis or Title or Subtitle , if we change the font-size of any of these titles . The margin or y should be same even after changing the font-size.(for e'g, if i set the margin as 10 then once i change the font-size from 20 to 5 pixels or 5 to 20 pixels the distance between title to series should be same as before changing the font-size)
#### Actual behaviour
After setting the margin or y property of Title for x-axis or Title or Subtitle , if we change the font-size of any of these titles .The distance between title to series should is changing.

#### Product version
All Versions

#### Affected browser(s)
Google Chrome , IE , Mozilla

![image](https://user-images.githubusercontent.com/47973853/53331504-14f2d380-3917-11e9-8920-eb72a0663eba.png)

![image](https://user-images.githubusercontent.com/47973853/53331547-2c31c100-3917-11e9-8744-94a37da824c0.png)

**Comment by pawelfus** [comment]
Hi @ShivaRam1989 

Thank you for reporting the issue. Could you recreate this in jsFiddle? I have tried, and it looks fine: https://jsfiddle.net/BlackLabel/6u7mxv3f/5/

![screen shot 2019-02-25 at 12 46 26](https://user-images.githubusercontent.com/1453926/53335299-655c3800-38fb-11e9-9bed-d6f652299140.png)

Both charts above have the same margin (2px) and different font sizes (5px vs 20px).

Thanks!

**Comment by ShivaRam1989** [comment]
@pawelfus appreciate your quick response , the following is the jsfiddle to reproduce the same

https://jsfiddle.net/shivaram1989/xr9q7fs1/3/

Thanks,
Shiva

**Comment by pawelfus** [comment]
Hi @ShivaRam1989 

Your demo does not render xAxis title at all. Are you sure this is a correct demo? Regarding `chart.title`, there should be `fontSize`, not `'font-size'`: https://jsfiddle.net/BlackLabel/09xt6jLb/4/

See `style` config: https://api.highcharts.com/class-reference/Highcharts.CSSObject#fontSize

**Comment by ShivaRam1989** [comment]
@pawelfus 
Actually this behavior of title can be seen for x-axis or title or subtitle , which i mentioned in the Expected behaviour and actual behaviour sections.

I just gave demo for one you can replicate the same for all the three.

Coming to the jsfiddle you shared , you can notice the spacing between **title** to **chart border** is 23px when fontsize is 5px
Whereas the spacing between **title** to **chart border** is 40px when fontsize is 35px.

You can use tools like cropper or ruler to see the exact spacing .

Thanks for the css config thing , actually i am setting the style properties dynamically and it takes 'font-size'. I am nor sure if i am doing wrong as it works fine with that.

Thanks,
Shiva

**Comment by pawelfus** [comment]
Thanks for the details! These are my results:
- fontSize: 5px -> 8px margin
- fontSize: 35px -> 7px margin

See (zoomed-in):
![screen shot 2019-02-25 at 18 07 36](https://user-images.githubusercontent.com/1453926/53354970-4de77400-3928-11e9-8f63-58f16f9fd384.png)
![screen shot 2019-02-25 at 18 07 10](https://user-images.githubusercontent.com/1453926/53354971-4de77400-3928-11e9-8698-e5863b5f0dc3.png)

Of course, if you check edge to edge distance (instead of my bounding box to edge) it will be different, but I'm not sure if this is a bug - this is how browser renders text, keeping space for special characters (like Ń, Ź etc.), isn't it? See HTML demo: https://jsfiddle.net/BlackLabel/09xt6jLb/10/

And these are result for xAxis title:
- 5px:
<img width="533" alt="screen shot 2019-02-26 at 10 56 37" src="https://user-images.githubusercontent.com/1453926/53404097-428e5a00-39b5-11e9-93af-2cff5d9f9101.png">
<img width="533" alt="screen shot 2019-02-26 at 10 55 40" src="https://user-images.githubusercontent.com/1453926/53404098-428e5a00-39b5-11e9-9734-272a7f3ff83b.png">
- 35px:
<img width="418" alt="screen shot 2019-02-26 at 11 00 34" src="https://user-images.githubusercontent.com/1453926/53404378-d6602600-39b5-11e9-852b-e6048ea3619b.png">
<img width="547" alt="screen shot 2019-02-26 at 11 00 21" src="https://user-images.githubusercontent.com/1453926/53404380-d6602600-39b5-11e9-9249-98b7aff55a80.png">

In all cases, difference is about ~1px which may be caused by antialiasing in browser..

**Comment by ShivaRam1989** [comment]
@pawelfus 

If you are able to see the screenshots below where i highlighted the spacing between title and chart area. You may understand the real issue , it's about the space between title and chart area is not consistent when we change font size.


![image](https://user-images.githubusercontent.com/47973853/53417574-e3076d00-39fb-11e9-9db3-e096e1454adf.png)

![image](https://user-images.githubusercontent.com/47973853/53417651-07634980-39fc-11e9-8dcc-549f981c497f.png)

**Comment by pawelfus** [comment]
@ShivaRam1989 

Did you change `font-size` to `fontSize` ? I'm still using my demo I posted above: https://jsfiddle.net/BlackLabel/09xt6jLb/4/ , which gives me these results (still 1px off, which may be caused by antialiasing):

<img width="578" alt="screen shot 2019-02-27 at 12 21 45" src="https://user-images.githubusercontent.com/1453926/53486935-67a0cc80-3a8a-11e9-93bb-ef0a8a4d85e2.png">
<img width="598" alt="screen shot 2019-02-27 at 12 21 27" src="https://user-images.githubusercontent.com/1453926/53486936-67a0cc80-3a8a-11e9-98b1-3583e4c63d77.png">

**Comment by ShivaRam1989** [comment]
@pawelfus Two things i want to clear before commenting more,

1. 'font-size' is used when we try to plot dynamically from code (javascript) which looks like this ,

   text: titleObj.text ,
                verticalAlign: titleObj.verticalAlign ,
                y: 18,
                align: titleObj.horizontalAlign,
                style: {
                    'font-size': titleObj.fontSize + 'px',
                    'font-family': titleObj.fontFamily,
                    'font-weight': titleObj.isBold ? "bold" : "normal",
                    'font-style': titleObj.isItalic ? 'italic' : 'normal',
                    'text-decoration': titleObj.isUnderline ? 'underline' : 'none',
                    'color': titleObj.fontColor
                }
So , please ignore if it is fontsize or font-size thing , because with the above code font-size works fine

2.  Even with the jsFiddle you created it you can notice the spacing as shown in below image

![image](https://user-images.githubusercontent.com/47973853/53487436-941c0f00-3ab1-11e9-9dde-b4634fe0aa90.png)

So , i am not aware how you are checking the spacing between chart area and title.

Please let me know if you need further clarification.

**Comment by pawelfus** [comment]
I'm sorry, I'm still unable to replicate the issue. Let me render boxes and lines you can check: 

See:
- `fontSize`: https://jsfiddle.net/BlackLabel/09xt6jLb/23/
![screen shot 2019-02-27 at 14 31 02](https://user-images.githubusercontent.com/1453926/53493730-582a7f00-3a9c-11e9-9ffd-b8ff9afa0aaa.png)
- `font-size`: 
https://jsfiddle.net/BlackLabel/09xt6jLb/25/
![screen shot 2019-02-27 at 14 32 28](https://user-images.githubusercontent.com/1453926/53493799-89a34a80-3a9c-11e9-8148-59b548da76b2.png)

Please, inspect elements in HTML (red lines) and compare results, these are mine:
- `fontSize`: 17px and 18px
- `font-size`: 6px and 35px

Which comes back to my previous comment: https://github.com/highcharts/highcharts/issues/10202#issuecomment-467028185 - please use `fontSize` which is supported (and required, when using type definitions).

**Comment by ShivaRam1989** [comment]
Hi @pawelfus , 

Thanks for the response , below is the code i am using

        self.updateChartSubTitle = function (subTitleObj: any) {
            let currChart = genericUtilities.findHighchartById(self.view, _.get(self.firstPane(), 'chartId'));
            let subtitle = {
                text: subTitleObj.text,
                verticalAlign: subTitleObj.verticalAlign,
                y: 35,
                align: subTitleObj.horizontalAlign,
                style: {
                    fontSize: subTitleObj.fontSize + 'px',
                }
            };
            if (currChart) {
                currChart.update({ subtitle });
            }
        };

But when i use fontSize , font size is not changing, whereas when i use 'font-size' it works fine .

Am i doing anything wrong here ?

**Comment by pawelfus** [comment]
Could you show `subTitleObj` ? Thanks!

**Comment by ShivaRam1989** [comment]
Hi @pawelfus ,
Sorry my mistake default has been set as 'font-size' so it was behaving wrong.
Now it is working as expected , thanks a lot for your time and patience.
Really appreciate your efforts.

Thanks,
Shiva

**Comment by pawelfus** [comment]
Thanks @ShivaRam1989 ! I'm really glad we were able to find the reason and fix that! 

Just in case you were curious why `font-size` works (partially): you can set **any** option in `style`, we don't validate these options (except type definitions, when used), for example `test: "test"` will show up too: https://jsfiddle.net/BlackLabel/6u7mxv3f/8/

![screen shot 2019-02-27 at 16 45 04](https://user-images.githubusercontent.com/1453926/53502788-12c37d00-3aaf-11e9-816a-c12fd571bd2f.png)
