### ISSUE TITLE
Tilemaps with fixed tile size

### ISSUE THREAD

**Issue by AyanGhatak** [highcharts/highcharts#10200]
#### Expected behaviour
- The tiles should be like the regular hexagon stated in the example, irrespective of their count.

#### Actual behaviour
- For some specified configuration, it looks regular like the [example](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/series/tilemap-gridoffset), but for the others it appears distorted.

#### Live demo with steps to reproduce
https://jsfiddle.net/AyanGhatak/d3pLc5xr/embedded/result,js

#### Product version
Highmaps, Tilemap

#### Affected browser(s)
N/A.

Was exploring to try tilemap as an alternative to a simple categorical column/pie chart to a tilemap view. So clearly I dont have a position from the data. So is there a way that I could lock the size of hexagon and use the [offset coordinate system](https://www.redblobgames.com/grids/hexagons/#coordinates-offset) to render the tiles ?

Any help is appreciated. Thank you. :)

**Comment by pawelfus** [comment]
Hi @AyanGhatak 

Size of a hexagon depends on two options: `rowsize` and `colsize`. If calculated values don't meet your expectations, you can change them: https://jsfiddle.net/BlackLabel/hf3vqdwp/8/

Regarding translating tiles, that's right you don't have position for a tile, but offset won't help you - it's just a layout change (correct me if I'm wrong, please :) ). 

All layouts are possible to achieve from the offset part: https://jsfiddle.net/BlackLabel/c4jtzfn1/5/ - of course, it's not ideal, because this solution also changes order of points.

Maybe I could provide a bit more detailed answers, but I'm not sure how do you want to show pie series as tilemap series. Do you have a mockup perhaps?

**Comment by AyanGhatak** [comment]
Hey sorry for the delay in reply. Thank @pawelfus for taking a look at it. But I wanted a generic solution where I need not to specify the rowSize and colSize everytime. And I get hexbins for each of the series, colured by their aggregation.

Grafana calls this plugin as polystat, which is basically, each timeseries becomes a hexagon unit structure, and they are coloured by an aggregated value. 
Ref - https://grafana.com/plugins/grafana-polystat-panel
This view is a compact view representation of the aggregated metrics I wanna look at.

I was successful in creating a POC anyway with d3-hexbin. :) 
https://jsfiddle.net/AyanGhatak/m5ows802/embedded/result,js

I understand the usecase of Highcharts tilemap. So IMO, its like a bivariate histogram approach.
We can close this thread, incase we don't want to consider for a polystat hexbin visualisation in Highcharts right of now. Would leave that up on @pawelfus  @KacperMadej, @TorsteinHonsi . Thank you. :)

**Comment by pawelfus** [comment]
Thank you for the details @AyanGhatak ! We really appreciate this :) 

@oysteinmoseng - could you take a look?

**Comment by oysteinmoseng** [comment]
I think there are plenty of valid use cases for this, and it should be considered for a future release. I'll tag this as a feature request, but ideally we should probably file it in UserVoice so it isn't lost
