### ISSUE TITLE
Stacked column chart doesn't stack, if series are tied to different yAxes

### ISSUE THREAD

**Issue by danielbartsch** [highcharts/highcharts#10210]
#### Expected behaviour
series should stack correctly, even if they are tied to different y axes.
ie: datapoint 1 of series 1 should be under datapoint 1 of series 2

#### Actual behaviour
the series are just in front/back of each other. As seen by making the series color half transparent.

#### Live demo with steps to reproduce
http://jsfiddle.net/r57n6ohL/44/
see that on the left, the black column is completely covering the column behind.
if you remove `zIndex` in both series, the other series is completely in front of the other.

#### Product version
highcharts 7.0.3

#### Affected browser(s)
chrome

**Comment by pawelfus** [comment]
Hi @danielbartsch 

Thank you for reporting the issue. This is however expected behaviour. Series to be stacked needs to be on the same yAxis. Different yAxes can have different ranges, which would be impossible to show values and keep their heights correct - user would get wrong impression on the presented data, suggesting that two points are the same value (e.g. scales 0-10 and 0-100, points y=5 and y=50).

It's possible to show two yAxes on the same chart with stacking, but still, just one yAxis will have stacks, other will be just a copy of it's parent: http://jsfiddle.net/BlackLabel/cLb4rj1n/3/ - and this is how chart suppose to look with your data, when stacking is enabled.

**Comment by danielbartsch** [comment]
Makes sense, thanks!
