### ISSUE TITLE
Venn diagram - overlap label is not center aligned

### ISSUE THREAD

**Issue by zli-aa** [highcharts/highcharts#10247]
The label of the overlap should be centered in the overlap area, but it's not.

![image](https://user-images.githubusercontent.com/12229459/53779756-59e0c080-3f3c-11e9-9de8-8f1ad9e2a271.png)

#### Live demo with steps to reproduce

https://codepen.io/anon/pen/morxjp?&editable=true

#### Affected browser(s)

Chrome

**Comment by zli-aa** [comment]
live demo, https://codepen.io/anon/pen/morxjp?&editable=true

**Comment by sebastianbochan** [comment]
Hi @zli-aa,
Thank you for reporting about the problem.

FYI @jon-a-nygaard

**Comment by jon-a-nygaard** [comment]
A case which may be related is the following example https://codesandbox.io/s/74vny3ry7q, where the label for set D is missing.

**Comment by inabeel** [comment]
https://www.highcharts.com/demo/venn-diagram
Check this url, 'More expensive' section is beyond its section!
Please fix this

**Comment by jon-a-nygaard** [comment]
**Internal Note:** There seems to be a fault in the implementation of nelderMead, instead of optimizing the position it seems to worsen it. At the moment uncertain where precisely the fault lies, and how complicated it will be to solve it.
Another possibility of error here is the `alignment-baseline` of the text element, although this has minimal impact on the result.

**Comment by cxf0505** [comment]
https://jshare.com.cn/demos/4JeD8a/7
When a and intersection are the same, figure a is covered under figure B. If the tag item is hidden

dataLabels: {

enabled: false

}

**Comment by pawelfus** [comment]
@cxf0505 - you don't need to spam all Venn diagram tickets :)
