### ISSUE TITLE
Waterfall chart show table - intermediateSum and Sum is not displaying in table

### ISSUE THREAD

**Issue by praveenn-vbi** [highcharts/highcharts#10264]
#### Expected behaviour
Intermediate Sum and Sum will be displaying in table on selecting show table option

#### Actual behaviour
Intermediate Sum and Sum is not displaying in table on selecting show table option
![image](https://user-images.githubusercontent.com/20218070/53861266-b1009700-4009-11e9-9fbb-41ac63724f03.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/parveennp/d6vy5umh/2/

#### Product version

Highcharts JS v7.0.3 

#### Affected browser(s)
All Browser

**Comment by sebastianbochan** [comment]
Hi @praveenn-vbi,
Thank you for reporting about the problem.

**Internal note**
It looks like in the `Highcharts.Chart.prototype.getDataRows` lines:

```
while (j < valueCount) {
                  prop = pointArrayMap[j]; // y, z etc
                  val = point[prop];
```

`y` is undefined and not calculated yet. 

@PaulDalek is it not a bug in waterfall in general?

**Comment by PaulDalek** [comment]
I think it is not a bug in waterfall. This is caused by the way how the table below the chart is filled with data. In the getDataRows function y values are taken from the series.options.data. In case of sum and intermediateSum points, y values are not provided by user but are calculated based on the previous values. The solution here would be to place y values inside series.options.data but modifying options directly from the user does not sound right. What do you think @TorsteinHonsi ?

**Comment by TorsteinHonsi** [comment]
> does not sound right

Correct, we shouldn't modify the options. Probably we need some other kind of hook so that the series can return computed values.
