### ISSUE TITLE
Venn diagram - Uncaught Error: f(a) and f(b) must have opposite signs.

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#10282]
When the venn diagram is generating with three data and second and third data(which is an amount of them) are equal error  **f(a) and f(b) must have opposite signs.** occurred. 

It is noticed that this error occurred if this common value is equal to or greater than 98 (meaningless to the first data value). 

#### Live demo with steps to reproduce

[Demo](https://jsfiddle.net/BlackLabel/ad5b6m8v/)

#### Product version

Highcharts JS v7.0.3

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
FYI @jon-a-nygaard

**Comment by loveywjung** [comment]
me too,,,

**Comment by jon-a-nygaard** [comment]
Hi, thanks for reporting. I am currently looking into the issue, and will get back to you with more information as soon as possible.

**Comment by jon-a-nygaard** [comment]
Luckily this issue seems to be easy enough to fix, and I am therefore aiming to have a fix included in the next maintenance release. Currently working on a pull requests that provides the fix and tests for the issue.

Unfortunaly I do not see a way to provide a workaround for this issue, except for avoiding the issue all together by making sure that in your data `A > A∩B`.
