### ISSUE TITLE
Prerelease issue, can't load oldie-polyfills

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#10288]
Since updating the assembler, it can't handle the polyfills module being loaded before Highcharts:

http://jsfiddle.net/highcharts/b3sfxmrq/1/

**Comment by jon-a-nygaard** [comment]
Aah, since it is a module it expects Highcharts before it actually exists. I will look into it.

**Comment by jon-a-nygaard** [comment]
The problem here is that oldie-polyfills has been built as a module, and considered dependent upon Highcharts even if it is not.

I see two solutions to this problem:
1. Have the `_modules` fall back to an empty object if it can not find Highcharts. In our build step it will still be considered dependent upon Highcharts, even if it is not and will run fine without.

2. Create a seperate UMD wrap for these cases where the file is not creating a Highcharts instance, and it is also not dependent upon a Highcharts instance. I believe this would be the more correct sollution, but it will also require some additional configurations and adaptions just for a special case.

At the moment I would like to go for the simpler solution, number 1.

@TorsteinHonsi Do you know if we have more cases like this, or if this is the only one with loading issues?

**Comment by TorsteinHonsi** [comment]
> Do you know if we have more cases like this, or if this is the only one with loading issues?

I think this is the only one.
