### ISSUE TITLE
Highstock chart does not show "Reset Zoom" button when zoom type is set to "x"

### ISSUE THREAD

**Issue by LaniMoo** [highcharts/highcharts#10320]
1. Create Highstock chart
2. Disable range selector
3. Set `zoomType` to `'x'`
4. Zoom in to chart using mouse drag

#### Expected behaviour
Reset Zoom button appears.

#### Actual behaviour
Reset Zoom button does not appear.

#### Live demo with steps to reproduce
https://jsfiddle.net/lanimelrok/1gvp9s45/
If you switch the `zoomType` to `'xy'` and repeat the above steps, the Reset Zoom button appears.

#### Product version
Highstock 7.0.3

**Comment by sebastianbochan** [comment]
Hi @LaniMoo,
Thank you for reporting. This is the default functionality of Highstock, because the navigator allows you to zooming out.

Related topic:
- https://github.com/highcharts/highcharts/issues/979

**Workaround**
You can overwrite that behaviour by catching selection event and render button by API. Then catch setExtremes event to check "zoomOut" state. If there is, hide the button.

Example:
- http://jsfiddle.net/rf658xvy/

**Comment by LaniMoo** [comment]
Thank you for the workaround, @sebastianbochan. I'd prefer to use the showResetZoom() method, but is there a reason why the showResetZoom() method does not work for this scenario?

**Comment by alexkharech** [comment]
working solution for xAxis only

```css
.reset-zoom-btn {
    position: absolute;
    right: 50px;
    top: 5px;
}
```

```js
 xAxis: {
    type: "datetime",
    ordinal: false,
    events: {
      afterSetExtremes() {
        let btn = document.querySelector(".reset-zoom-btn");
        if (btn) btn.remove();

        const showBtn =
          this.chart.navigator.range !== undefined &&
          this.chart.navigator.size - this.chart.navigator.range > 0.1;
        if (showBtn) {
          btn = document.createElement("button");
          btn.innerHTML = "Сбросить масштаб";
          btn.className =
            "btn btn-default reset-zoom-btn btn-outline-secondary btn-sm";
          btn.onclick = () => {
            this.chart.zoomOut();
            if (btn) btn.remove();
          };
          this.chart.renderTo.appendChild(btn);
        }
      }
    }
  }
```

**Comment by zyura** [comment]
In Highstock 9 it is enough to remove 'beforeShowResetZoom' event from Chart class:

`Highcharts.removeEvent(Highcharts.Chart, 'beforeShowResetZoom');`

Exampl: [http://jsfiddle.net/gmdnzah4/](http://jsfiddle.net/gmdnzah4/)

I would really like to have possibility to choose the behavior with options rather than using hacks and workarounds to bring back the default functionality. Navigator is really inconvenient to use to restore the default zoom.

**Comment by KacperMadej** [comment]
If you want to see a new feature added to Highcharta then please open a [feature request](https://github.com/highcharts/highcharts/issues/new?assignees=&labels=Type%3A+Feature+Request&template=feature_request.md&title=). Commenting on a closed issue is less impactful.

**Comment by zyura** [comment]
> If you want to see a new feature added to Highcharta then please open a [feature request](https://github.com/highcharts/highcharts/issues/new?assignees=&labels=Type%3A+Feature+Request&template=feature_request.md&title=). Commenting on a closed issue is less impactful.

I'm commenting here only because of the fact that this page is in the top search results. I see a lot of people using ugly workarounds so I decided to share a better solution here (so it can be found).

This feature has been rejected many times by the Highcharts developers (see comments above) so I see no point in creating another feature request.

Although, as a paid customer, I'm deeply disappointed by the fact that sane requests get rejected.

**Comment by KacperMadej** [comment]
@zyura 
I don't discourage you from commenting on a closed issue (it's reasonable just as you have justified) - only trying to encourage proper feature request reporting to address your last text section (starting with "I would really like to have ...").

We are aiming in implementing the most popular feature requests. Less popular features are not rejected - the tickets should remain open until they will gain more popularity. I guess it doesn't do much if I only write about the general approach or strategy, so please point me to the rejected sane requests that we could check, address and possibly reopen.

This issue was opened when we were tracking feature requests outside of GitHub issues, so it was rightfully closed as not a bug.

**Comment by shunxing** [comment]
Hello 

<img width="1483" alt="Image" src="https://github.com/user-attachments/assets/47b75a38-020a-417b-80c4-67c15c442b5f" />

I still have the issue with highstock chart. The reset button doesn't get displayed https://jsfiddle.net/r4xowdt2/2/

@KacperMadej Is it a known issue ?

**Comment by KacperMadej** [comment]
Hi @shunxing 
This is known and by design as explained here: https://github.com/highcharts/highcharts/issues/10320#issuecomment-473222604
There are options listed in this thread about how to change this behavior.
If you would like for this to be changed in code you could open a feature request, but a breaking change is highly unlikely to be implemented for this - more possible seems to be an additional option or using one of the already listed workarounds as long as they rely on the public API.
