### ISSUE TITLE
addSeries with type bar draw series as column series

### ISSUE THREAD

**Issue by miguel-cagide** [highcharts/highcharts#10359]
#### Expected behaviour
I don't know if this behaviour is intended, but in a chart initialized without series data, adding series with bar type should draw bar series.

#### Actual behaviour
It draws columns

#### Live demo with steps to reproduce
https://jsfiddle.net/ux9ktzye/1/
- click on add series button

#### Affected browser(s)
At least chrome 72.0.3626.121
and firefox 65.0.2

**Comment by sebastianbochan** [comment]
Hi @miguel-cagide,
Thank you for reporting about the problem.

**Workaround**
- call `chart.update()` and set the `inverted` param as true

Demo:
- https://jsfiddle.net/BlackLabel/3y5r6uvs/

**Comment by pawelfus** [comment]
Just a word of explanation here: `bar` series is the same as `column` series, but with `chart.inverted` set to true. It would make sense to remove `bar` series (and explain this in docs), but we don't want to break backward compatibility.

**Comment by sebastianbochan** [comment]
**Internal note**
Im wondering if we should we consider it as a bug. What do you think @pawelfus @TorsteinHonsi

**Comment by TorsteinHonsi** [comment]
There are already inconsistencies, like what happens when we use a bar and a column in the same chart: http://jsfiddle.net/highcharts/ecuwzp1m/. The behaviour now is that the bar takes precedence and makes the whole chart inverted.

In order to fix this, we would make this behaviour consistent also with added, updated and removed series. So whenever there is a bar series present, the chart needs to be inverted dynamically. And opposite, if a bar series is removed, it needs to check all present series again, and un-invert the chart if needed.

I think we should do that if it doesn't lead to too much overhead. I think in principle it would be to run  `Chart.propFromSeries` again after a series is added, updated or removed.
