### ISSUE TITLE
Typescript typing for TooltipFormatterContextObject does not include some properties for 'arearange'

### ISSUE THREAD

**Issue by rorymcgit** [highcharts/highcharts#10385]
#### Expected behaviour
Include properties in TooltipFormatterContextObject for 'arearange' chart type

#### Actual behaviour
`Property 'high' does not exist on type 'Point'.ts(2339)`
`Property 'low' does not exist on type 'Point'.ts(2339)`

`TooltipFormatterContextObject.point` is of type `Point` which does not include properties `high` and `low`, although these are included in the TooltipFormatterContextObject when using 'arearange' chart type. 

`high` and `low` are very useful properties for this chart type as the y value is just the low. 
 They are also available in `TooltipFormatterContextObject.point.options` but this is typed as 'object', so the compiler complains `Property 'high' does not exist on type 'object'.ts(2339)` instead.

#### Product version
Highcharts 7.0.3

**Comment by KacperMadej** [comment]
Hi @rorymcgit 

Thank you for reporting about the problem.

_Internal note:_
fyi @bre1470

**Comment by bre1470** [comment]
Hi @rorymcgit

Which TypeScript version do you use?

**Comment by rorymcgit** [comment]
@bre1470 

3.2.4

**Comment by bre1470** [comment]
Series-specific and custom data point properties can be accessed with the next update like this: `this.point.high as number`. Note: The type cast has to be done manually.

**Comment by rorymcgit** [comment]
Thanks @bre1470 
Is that update 7.1.0? Is there a commit or PR you can reference?
Why does `this.point.high` need to be type cast `as number`, what is it typed as?

**Comment by bre1470** [comment]
We added an `any` indexer to the `Point` class in v7.1.0, so that every unknown property gets automatically casted to the any type. It is mainly for custom properties set in the `series.data` option, but can also be used for series-specific properties, that are not yet an official part of the classes.

The source reference can be found here: https://github.com/highcharts/highcharts/blob/master/js/parts/Point.js#L86

We discuss a more type-safe solution internally, but did not come to a decision about organizing different series points yet.
