### ISSUE TITLE
Update does not work with `rangeSelector.selected` option set. A second update works

### ISSUE THREAD

**Issue by futpib** [highcharts/highcharts#10457]
#### Expected behaviour

A call to `update` updates the chart. 

#### Actual behaviour

A call to `update` does not update the chart.

#### Live demo with steps to reproduce

https://jsfiddle.net/vtrdn1zh/

Removing `rangeSelector.selected` option serves as a workaround.

Calling `update` twice with the same options serves as a workaround too. 

#### Product version

Highstock JS v7.0.3 (2019-02-06)

#### Affected browser(s)

Chrome and Firefox

**Comment by sebastianbochan** [comment]
Hi @futpib,
Thank you for contacting us. 

Let me explain what is the reason of it. When you init a chart with the `commonOptions` options, Highcharts create references to all parameters. So when you try to update chart with new params which includes also the `commonOptions`, Highcharts refers to previous values. 

The solution is to use only "new options" instead of all of them.

**Demo:**
- https://jsfiddle.net/BlackLabel/1vdtLayf/4/

Im not sure if it is a bug.

**Internal note:**
What do you think @pawelfus @TorsteinHonsi ?

**Comment by pawelfus** [comment]
I think it's a bug, let's simplify the scenario: https://jsfiddle.net/BlackLabel/1vdtLayf/6/ - the `selected` option now is changed and we get the same issue. That suggests issue with no the same `commonOptions` but in general with updating rangeSelector @sebastianbochan 

*Internal note:*
In v5 it "worked" better: https://jsfiddle.net/BlackLabel/1vdtLayf/7/ - but the second update throws errors..

**Comment by futpib** [comment]
> In v5 it "worked" better
@pawelfus I actually faced this issue when updating from 6.1.3 to 7.0.3 (on 6.1.3 it worked fine).
