### ISSUE TITLE
Waterfall: Time total uses Epoch time by default

### ISSUE THREAD

**Issue by RichardCzechowski** [highcharts/highcharts#10458]
Hey all! Running into a bug that makes time waterfalls hard to use...

#### Expected behaviour
Total will be added _after_ the final data point and with a non-date category. Maybe it uses the 'name' property on the data point to name the category "Total".

#### Actual behaviour
Either you can provide a "total" category that is the same or greater than the final value, in which case you are adding data that doesn't exist, or you can add no category and Epoch time gets used by default.

#### Live demo with steps to reproduce
Go here and note the final "totals" point is epoch time
https://jsfiddle.net/6qfxk5Lj/1/

**Comment by KacperMadej** [comment]
Hi @RichardCzechowski 

You have set pointStart and pointInterval and then used x values for all points but the sum point. You could set x for the sum point to resolve the problem. The x position of the sum point is taken from the options set in the plotOptions.series.

This doesn't look like a bug.

**Comment by RichardCzechowski** [comment]
Hi @KacperMadej thanks for your reply.
> The x position of the sum point is taken from the options set in the plotOptions.series.
I'm not sure I follow this. Can you clarify or provide an example?

Here's what I've observed: (I've removed pointStart and pointInterval for clarity)

Issue: Epoch time/0 being used as default placement for total on a time/linear axis.
I believe this is wrong, since a waterfall should have the total to the right of the available data.
This should be the default placement and the "total" column should not be included in the xAxis values, since it is an aggregated data point and doesn't really have an X value on a sequential axis.

https://jsfiddle.net/n3dtsz2w/1/
<img width="487" alt="Screen Shot 2019-03-31 at 7 50 43 AM" src="https://user-images.githubusercontent.com/6431282/55290578-b55e6c80-5389-11e9-9b58-95716b9da425.png">

Okay, so let's try a string "x" or "name" value. I'd expect maybe a categorical string to work and be inserted as the final point on the xAxis. Unfortunately, that just makes the totals column not plot at all.
https://jsfiddle.net/n3dtsz2w/3/  // x value doesn't display anything
https://jsfiddle.net/n3dtsz2w/4/ // name value displays as a '0' value
<img width="572" alt="Screen Shot 2019-03-31 at 7 52 21 AM" src="https://user-images.githubusercontent.com/6431282/55290604-0ff7c880-538a-11e9-8c76-1a278c03ebc4.png">

Now let's say I provide an x value that is the same as the final date. Unfortunately that's still not right because it combines the total and the final data point on the last date.
https://jsfiddle.net/n3dtsz2w/2/
<img width="483" alt="Screen Shot 2019-03-31 at 7 51 16 AM" src="https://user-images.githubusercontent.com/6431282/55290584-cb6c2d00-5389-11e9-9e45-511b3d98be06.png">

I can't provide a date that is further in the future for the totals axis, because that data point would be misleading.

**Comment by pawelfus** [comment]
Hi @RichardCzechowski 

Thank you for the details! At this moment, to render `total` value in a waterfall series on a datetime xAxis, you need to provide `x` value further in the future. For example, on a daily dataset it should end on the last day of month: https://jsfiddle.net/BlackLabel/mnh21vfx/ Why it works that way? Because no one ever asked for a different solution :) The same applies to intermediate sums: https://jsfiddle.net/BlackLabel/mnh21vfx/1/

**Comment by KacperMadej** [comment]
X must be a number. If data has mixed set x values - set and not set, then for not set it will be started from pointStart (defaults to 0) and later iterated by pointInterval (defaults to 1). This is how data works for all series and this is not a waterfall specific case.

This is not a bug. Everything works as expected by design. If you would like for this to work differently then you could contact support for help with developing a different logic - e.g. parse data before using a chart, or use some chart options that will provide you the desired output with defined input. https://www.highcharts.com/blog/support/

If you would like for the logic to be changed, altered, modified, improved or extended with new features then you could suggest this through our UserVoice site - http://highcharts.uservoice.com/forums/55896-general The most popular ideas are implemented there.

**Comment by RichardCzechowski** [comment]
Thanks @pawelfus & @KacperMadej. I've followed up with a feature request on [UserVoice](https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/37254991-waterfall-non-numeric-total-date-xaxis-label). I'd still argue that placing the totals on the date-timeline at all is inaccurate, but I'll explore either putting it on the last day of the given interval or the last day of the supplied dataset. Thanks for the suggestions.
