### ISSUE TITLE
Gantt: last element of tickPositions is ignored

### ISSUE THREAD

**Issue by danielbartsch** [highcharts/highcharts#10470]
#### Expected behaviour
the tickpositions should be applied according to the tickPositions array. Each visible element.

#### Actual behaviour
the last tickpositions element is ignored. And the one before the last one seems to span over the area of the last one

#### Live demo with steps to reproduce
https://jsfiddle.net/z2mrpbdv/1/

uncomment infinity comment to see expected behavior (except that there's no label for february)

#### Product version
latest 7.1.0

#### Affected browser(s)
tested firefox and chrome

**Comment by pawelfus** [comment]
Hi @danielbartsch 

Thanks for choosing Highcharts Gantt! This is expected behaviour - you set tick position at the beginning of month, so it's almost the same place as end on January, so you actually cut off February. If you want to display full Feb, add this ending tick: https://jsfiddle.net/BlackLabel/rp4nx7qe/1/

**Comment by danielbartsch** [comment]
Hey @pawelfus 

I don't see how this makes sense. I have ticks for the beginning of January, and the beginning of February, but the beginning of February just isn't shown. How is this expected behaviour?

In your example the ending tick is the beginning of March. If I want to display February, I have to add March as a tick position? Does not sound right to me.

Also I have a line that starts on the beginning of January and takes until the ending of February. Yet if only setting tickpositions beginning of January and February, it looks like it only spans the whole of February.

https://jsfiddle.net/mnojkvhx/

![image](https://user-images.githubusercontent.com/19350749/55457729-1fc21780-55eb-11e9-9619-19933954200b.png)

**Comment by pawelfus** [comment]
Hi @danielbartsch 

> I don't see how this makes sense. I have ticks for the beginning of January, and the beginning of February, but the beginning of February just isn't shown. How is this expected behaviour?

By setting tick at the beginning of February, you actually want to show just 1ms from February. 1ms is quite small when comparing to full January (31 * 24 * 3600 * 1000ms). When you check DOM, you will find hidden February label.

> In your example the ending tick is the beginning of March. If I want to display February, I have to add March as a tick position? Does not sound right to me.

Sorry for the mistake in my previous post! There should be `1488322799999`, not `1488412799999`, demo: https://jsfiddle.net/BlackLabel/rp4nx7qe/3/

**Comment by danielbartsch** [comment]
Sorry for the late reply.

I still don't get it.

I have a gantt line that spans from 1st of December to 28th of February.

And if I tell highcharts that there should be ticks on the 1st of December, the 1st of January, and on the 1st of February.

But then highcharts sets the last tick (1st of February) to the end of the gantt line instead (28th of February)

My picture above describes it well I think.

You said that a tick on the 1st of February means that we only show the 1st of february. So does that mean that the rest of the chart just isn't shown, and that's what's confusing me? In that case, that makes sense.

**Comment by pawelfus** [comment]
Hi @danielbartsch 

I was creating the demo, to explain how it works: https://jsfiddle.net/BlackLabel/f5pm8qoy/ (green dot- 28th of February), when I realized you are right! In the demo above I set `xAxis.max`. Without it, we can clearly see the error you reported: https://jsfiddle.net/BlackLabel/f5pm8qoy/1/

My apologies, I was expecting the same results when setting `tickPositions` on yAxis: https://jsfiddle.net/BlackLabel/8ma3puo5/ (extremes are cut, since `tickPositions` option limits them).

@jon-a-nygaard could you take a look? It looks that grid boxes are rendered according to available space, not limited by actual start/end of period. https://jsfiddle.net/BlackLabel/f5pm8qoy/1/ - in this demo "January" should end where blue dot is rendered.

**Comment by jon-a-nygaard** [comment]
Thanks again for reporting.

I will take a look and see what causes the issue, and if we may be able to have a fix for an upcoming release.
