### ISSUE TITLE
No ticks in categorized X-axis

### ISSUE THREAD

**Issue by rachelfreya** [highcharts/highcharts#10487]
#### Expected behaviour
Categorized X-axis will include ticks.

#### Actual behaviour
There are no ticks on a categorized X-axis.

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/xaxis/tickmarkplacement-between/

#### Product version
Highcharts 7.1.0

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @rachelfreya 

This is expected change in v7.1. To enable ticks, simply set [`xAxis.tickWidth`](https://api.highcharts.com/highcharts/xAxis.tickWidth) to 1. Demo: https://jsfiddle.net/BlackLabel/g2b9kLrx/

Change-log referenece: https://www.highcharts.com/blog/changelog/ (see upgrade notes).

**Comment by franzl-hansel** [comment]
Hi,

I believe there is still a bug here, or the documentation is incorrect. When using styled mode, the .highcharts-tick class only takes effect if tickWidth is explicitly supplied and it is not set to 0.

See: https://jsfiddle.net/franzl/72k6of1a

**Comment by TorsteinHonsi** [comment]
> I believe there is still a bug here, or the documentation is incorrect.

Yes I see your point... The solution could be to always render the tick in styled mode. However the same applies to the Y axis, and this has gone unnoticed since v5: https://jsfiddle.net/highcharts/2fq3n5ox/

Maybe we should leave the functionality as is, and make a note in the docs that the styled mode needs the option in order for a tick to be rendered? Alternatively would be to render all ticks (categories and Y axis) for styled mode, but that would bloat the SVG. What do you think @pawelfus ?

**Comment by pawelfus** [comment]
My vote for this one:

> Maybe we should leave the functionality as is, and make a note in the docs that the styled mode needs the option in order for a tick to be rendered?

Then it would be the same as for minor ticks (I don't see a separate class name for minor ticks, so I might be wrong).
