### ISSUE TITLE
colorAxis labels misaligned when legend layout set as responsive rule

### ISSUE THREAD

**Issue by RainerSchwarze** [highcharts/highcharts#10491]
#### Expected behaviour

Horizontal colorAxis legend label layout set by responsive rules is properly aligned and placed.

#### Actual behaviour

Horizontal colorAxis legend label layout set by responsive rules is not properly aligned and placed. (Looks like it gets some properties from the vertical legend layout)

#### Live demo with steps to reproduce
https://jsfiddle.net/s2a9govr/

Heatmap legend is shown on right by default, and shown below chart using responsive rules. When the legend is shown below the chart, the colorAxis label placement is different to when it would be layed out that way without responsive rules.

1. run fiddle
2. observe legend on right
3. press toggle button
4. observe legend below chart; labels are inside the color axis and shifted to the right (not justified)

(compare with "normal" horizontal legend layout here: https://jsfiddle.net/a09wsekr/ )

#### Product version

Latest version

#### Affected browser(s)

Tested with chrome

**Comment by pawelfus** [comment]
Hi @RainerSchwarze 

Thanks for reporting this bug. You are right, it looks like some options are not changed with horizontal <-> vertical layout change. It's probably caused by initialization of `colorAxis` - only on init we pick different defaults for labels, on every next redraw, values are defined, so we don't change them. 

**Workaround:**
Set `colorAxis.side = 2` (or `= 1` for vertical layout) in responsive rules: https://jsfiddle.net/BlackLabel/rpaue6xL/
