### ISSUE TITLE
Add support for non-circular shapes in Venn series

### ISSUE THREAD

**Issue by gtanczyk** [highcharts/highcharts#10503]
#### Expected behaviour
A&B&C overlap should be displayed

#### Actual behaviour
![image](https://user-images.githubusercontent.com/1281113/55685215-bd06ae00-5953-11e9-964d-47e8c063931c.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/zv2epa3s/

#### Product version
Highcharts 7.1.0

#### Affected browser(s)
Tested on latest Chrome.

**Comment by sebastianbochan** [comment]
Hi @gtanczyk,
Thank you for reporting about the problem.

**Internal note**
The bug is partially related with https://github.com/highcharts/highcharts/issues/10247 

FYI @jon-a-nygaard

**Comment by jon-a-nygaard** [comment]
Hi @gtanczyk ,

The layout algorithm calculates the best approximation where the area of overlap is proportional to the area of each circle.
With the given data the algorithm can not preserve the best layout for overlap between B&C and A&C while having A&B&C overlap as well.
Decreasing the area of C, or increasing the area of B&C and A&C will make the A&B&C overlap possible.

Since there is no physical overlap between A&B&C in this case, then I believe it is correct that there is no point visible for it.

If you can elaborate more on what you would like to achieve then maybe we can provide a sort of workaround for it?

**Comment by gtanczyk** [comment]
Our expectation would be that in such case we will see ellipses instead of circles on the diagram. In fact by definition Venn diagram doesn't need to be based only on circles, but can use other shapes.

**Comment by jon-a-nygaard** [comment]
Thanks for the explanation @gtanczyk.

Currently the venn series does not have support for other shapes than circles, but I will leave this issue open as an enhancement that we may include in a future version.

**Comment by pawelfus** [comment]
Closing if favour of #14615 - please vote for that feature in #14615
