### ISSUE TITLE
column chart select bug

### ISSUE THREAD

**Issue by behnam7171** [highcharts/highcharts#10504]
#### Expected behaviour

when selecting a column( lets call it column A) and then selecting another( lets call it column B) , first column (A)  should back to it's original color.

#### Actual behaviour

when selecting a column and then selecting another, first column becomes lighter (like less opacity)

#### Live demo with steps to reproduce
https://jsfiddle.net/behnam71/nksLz09y/2/

#### Product version

7.1.0 has this problem
6.0.4 is ok

#### Affected browser(s)
chrome

**Comment by TheRealGI** [comment]
Hey @behnam7171 
I checked out your fiddle and tried it out on my other application aswell and I can reproduce your problem.

The intressting thing is, if you add the **inactive** tag in the **states**, you have access to the opacitiy which is set to 0.2 by default. Change it to 1 and your problem is solved.

It looks like that when you select another column, the selected column get the state  **inactive** which I' m not sure if this behaviour is correct.

Docu: [Inactive](https://api.highcharts.com/highcharts/series.column.states.inactive.opacity)

Solution:
`series: [{
            allowPointSelect: true,
                states: {
                		inactive: {
                    opacity: 1
                    },
                    select: {
                        color: 'red'
                    }
                },`

Regards
Dominic

**Comment by behnam7171** [comment]
I don't think this workaround logically is correct. because opacitiy: 1 is not valid value for inactive state, because end user will not understand if a column is in inactive state when he intentionally wants to see it inactive. 
You are right, switching to inactive state for previous selected column is incorrect behaviour. 
I think problem is the state management in this particular issue.

Regards, Behnam

**Comment by pawelfus** [comment]
Hi @behnam7171  and @TheRealGI 

Thanks for reporting the issue. You are both correct, it's caused by `inactive.state` which should not be applied in this particular case (column should go back to `normal` state). Workaround is disable `inactive` (by setting `opacity = 1`) state at this moment.
