### ISSUE TITLE
Wordcloud doesn't handle spaces correctly 

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#10524]
#### Expected behaviour
It shouldn't matter if words in a wordcloud contain spaces. 
A lot of valid English words contain spaces.

#### Actual behaviour
The layout algorithm treats words with spaces different from words without spaces.
Compare https://jsfiddle.net/kzoon/b7ofwjat with https://jsfiddle.net/kzoon/b7ofwjat/1
"head space" in https://jsfiddle.net/kzoon/b7ofwjat gets rendered too high compared with "headspace" in https://jsfiddle.net/kzoon/b7ofwjat/1

#### Live demo with steps to reproduce
https://jsfiddle.net/kzoon/b7ofwjat versus https://jsfiddle.net/kzoon/b7ofwjat/1

#### Product version
Highcharts  v7.0.3

**Comment by pawelfus** [comment]
Thanks for reporting @kzoon 

@jon-a-nygaard - FYI

**Comment by kzoon** [comment]
I' m planning to release a new version of my software in 1 month. Any chance of solving this issue before that time?

**Comment by jon-a-nygaard** [comment]
Hi @kzoon, 

Thanks again for reporting.

I am currently looking into the issue, and will come back to you as soon as I know more, sometime during today.

**Comment by jon-a-nygaard** [comment]
I found that the issue lies in the way the text is built internally in Highcharts. When there is more than one word in the text element it gets wrapped in tspans to handle more complex logic. This tspan does not inherit the alignment attributes set on the text element, which causes the "head space" to align itself higher.

I am working on creating a fix for this issue which I hope will be included in the next maintenance release.

In the mean time, an easy workaround is to add some additional CSS styling for `.highcharts-wordcloud-series tspan` to the site to solve the issue. Please see the following example: https://jsfiddle.net/jon_a_nygaard/g25ezrtu/

**Comment by kzoon** [comment]
Thanks for the quick action!
