### ISSUE TITLE
Inconsistent auto-cropping "…" of axis labels when label has drilldown

### ISSUE THREAD

**Issue by andi1984** [highcharts/highcharts#10531]
#### Expected behaviour
Cropping of the labels should be consistent, means: If there is not enough space for a label to be rendered completely, it should get cropped.

#### Actual behaviour
Some labels are cropped correctly, some others are not.

#### Live demo with steps to reproduce
1. Go to http://jsfiddle.net/60Lsm5r7/3/
2. You can already see that some labels are cropped correctly, some others are cropped as well, but still do not fit in the viewport and are overflowed hidden on the left hand side like "20 Language…"
3. Click on the first "11 Medical health…" drilldown
4. You can see again some labels are cropped correct and others are way too long to fit, but are not cropped with "…" at all.

#### Product version
>= 6.2, also on 7.1

#### Affected browser(s)
Chrome at least

**Comment by andi1984** [comment]
![Screen Shot 2019-04-10 at 14 43 24](https://user-images.githubusercontent.com/1077917/55879760-a5bc0080-5b9f-11e9-860c-548ed3cfe569.png)

**Comment by pawelfus** [comment]
Hi @andi1984 

Thank you for reporting the issue. 

Simplified demo: http://jsfiddle.net/BlackLabel/xa698d03/

**Workaround:**
Set [`drilldown.activeAxisLabelStyle.fontWeight`](https://api.highcharts.com/highcharts/drilldown.activeAxisLabelStyle) to `normal`.

Demo: http://jsfiddle.net/BlackLabel/dp1asm08/1/

*Internal note:*
It's caused by applying `bold` font-weight **after** rendering and breaking/wrapping/ellipsing the label. I'm pretty sure similar (or even the same) bug was already reported, but can't find it.

**Comment by sebastianbochan** [comment]
Hi @andi1984,
I also prepared a simple workaround which is based on CSS.

```
    xAxis: {
    	labels: {
      	useHTML: true,
      	style:{
           width: '150px',
           height: '18px'
        }
      }
    },
```

**Demo:**
- http://jsfiddle.net/BlackLabel/8m5ogy4n/
