### ISSUE TITLE
scrollablePlotArea does not work properly on Firefox

### ISSUE THREAD

**Issue by wchmiel** [highcharts/highcharts#10555]
#### Expected behaviour
scrollablePlotArea should work correctly on all browsers.

#### Actual behaviour
scrollablePlotArea doesn't work on Firefox.

#### Live demo with steps to reproduce
view: https://jsfiddle.net/BlackLabel/ko92esqx/show
editor: https://jsfiddle.net/BlackLabel/ko92esqx/

#### Product version
Highcharts

#### Affected browser(s)
Firefox 64.0 (macOS Mojave 10.14.3)

**Comment by sbrudz** [comment]
I hit this same issue.  The problem seems to be that the overlay uses `position: absolute` but the none of the parents specify a position, so the containing block is the body tag.  `margin: 0 auto;` causes the container div to be centered, but the overlay doesn't move because it's absolutely positioned relative to the body.  A work-around is to add `position: relative` to the `#container` div.

**Comment by alexbidule** [comment]
Same issue for us. Hopefully this will be fixed some day, without having to put this workaround in place.

**Comment by kpoliczer** [comment]
As a workaround I fixed this problem by wrapping the container which is used to render the chart with another div with style="position: relative". This works for me in FF
