### ISSUE TITLE
Bug: Border width not working for negative values

### ISSUE THREAD

**Issue by merakmarey** [highcharts/highcharts#10562]
#### Expected behaviour
Border set with serie borderWidth prop should apply to entire serie

#### Actual behaviour

Border not applied to negative values of the serie

#### Product version
https://jsfiddle.net/p8jzv7og/

#### Affected browser(s)

Chrome

**Comment by sebastianbochan** [comment]
Hi @merakmarey,
Thank you for reporting about the problem. The `borderWidth` is param typical for i.e column series. When you use line / area etc, you should declare `lineWidth` parameter.

Demo:
- https://jsfiddle.net/BlackLabel/5wkeqh98/

Docs:
- https://api.highcharts.com/highcharts/series.area.lineWidth

**Comment by merakmarey** [comment]
Corrected, however, why if borderWidth is not for area chart it does remove the border?

**Comment by sebastianbochan** [comment]
Hi @merakmarey,
The borderWidth works by accident, so you should use `lineWidth` option.

**Comment by pawelfus** [comment]
`borderWidth` doesn't work, we just don't see it because named colors are not parset to rgb(a) format. For example using both named colors you "don't" have "border" (it's there, but the colors are the same): https://jsfiddle.net/BlackLabel/jhkszvbp/ but using hex/rgb(a) colors we see "border": https://jsfiddle.net/BlackLabel/jhkszvbp/1/ 

We strongly recommend using hex/rgb(a) colors.
