### ISSUE TITLE
Disabling hover for series not working

### ISSUE THREAD

**Issue by f1ghtingfalcons** [highcharts/highcharts#10560]
#### Expected behaviour
When the option series.states.hover.enabled is set to false, hover styles and animations should not be applied to series hovered by the mouse in the plot.

#### Actual behaviour
Hovering a line or legend item will focus that series and grey out the others even when this behavior is supposed to be disabled.

#### Live demo with steps to reproduce
https://jsfiddle.net/f1ghtingfalcons/v0nuoy4t/2/

To reproduce just hover over a series. Hover states are supposed to be disabled.

#### Product version
Highcharts 7.1.1

#### Affected browser(s)
Chrome, Edge, FireFox

**Comment by sebastianbochan** [comment]
Hi @f1ghtingfalcons,
Thank you for reporting about the problem.

You should disable `inactive` state.

Demo:
- https://jsfiddle.net/BlackLabel/kmfyubct/

Please let me know if it is your requested behaviour.

**Comment by f1ghtingfalcons** [comment]
Thank you @sebaIstianbochan, that certainly fixes things for us. We have been using our config for a long while now though and this behavior only seems to have appeared recently. I would expect that setting hover states to `enabled: false` would disable hover effects, but I might just be misunderstanding this option. If this is the intended behavior of that option I'll certainly make no more fuss.

**Comment by sebastianbochan** [comment]
Hi @f1ghtingfalcons 
That is correct, its new functionality since 7.1.

Im closing this ticket as solved.

**Comment by pawelfus** [comment]
Just a word of explanation:

- `hover` state applies to the **hovered** series - e.g. line width
- new `inactive` state applies to all **other** series, that are not hovered - e.g. opacity

**Comment by olejorgenb** [comment]
It would be nice it was possible to turn off the meddling of the states on mouse hover, instead of disabling the states altogether.

We don't want the effect when hovering inside the plot (to noisy data so it would be disorienting), but it's still useful to be able to quickly trigger a highlight (programmatically). Using the states seems most suitable since setting the opacity requires a `update`. (haven't really measured the performance differences though)

Simply allowing defining arbitrary states would also solve this.

**Comment by sebastianbochan** [comment]
Hi @olejorgenb,
At this moment the inactive state is default, so you can disable it easily. 

You can create a feature request and we will consider your suggestion if other users will vote.
