### ISSUE TITLE
Update Option with New or Existing Reference Issues 

### ISSUE THREAD

**Issue by briankpw** [highcharts/highcharts#10563]
#### Expected behaviour
Option declare as new reference or using existing reference, its should be able to work well when updateFlag is set to true.

#### Actual behaviour
**Existing Reference**
If we are using back the options object (Reference), its working fine, but update twice, its come back the problem. 
[Demo](https://stackblitz.com/edit/highchart-angular-basic-if5tny?file=app%2Fviews%2Fcatalog%2Fcatalog.component.html)

If I don’t using new reference, options={}, its will causing a lot of issues. 
Animation, Drilldown, Range Selector is not working and the performance of the chart is quite slow.
 
I created one sample. 
“Click update 4 (reference object)” then “Click update 5 (reference object)” then 4, 5, 4 : You can see the chart animation is not working. 

Working Case: “Click update 2 (new object)” then “Click update 3 (new object)”, its work well.

Similar to drilldown, if don’t use options={}, its wont able to drilldown using chart instance

[Demo](https://stackblitz.com/edit/highchart-angular-chart?file=app%2Fviews%2Fcatalog%2Fcatalog.component.ts)

**New Reference**
If I use options={}, its work fine for every chart, there have some problem to this few chart.

Navigator Line chart go to third yAxis. Which is going up.
[Demo](https://stackblitz.com/edit/highchart-angular-stock-8densp?file=app%2Fviews%2Fcatalog%2Fcatalog.component.ts)

Line chart is not connecting well by the point, but regular javascript is working. 
[Demo](https://stackblitz.com/edit/highchart-angular-basic-b99dx4?file=app/views/catalog/catalog.component.ts)

#### Live demo with steps to reproduce
Demo on Top

#### Product version

highcharts 7.0.3 / 7.1.1
highcharts-angular 2.4.0

**Comment by KacperMadej** [comment]
Hi @briankpw 

Thank you for contacting us about the problem.

You are using unsorted data that is not allowed for line type series. You could use scatter series type. After update points with the same x values might not be updated correctly if the same data used, because then points are being updated. To avoid this problem you could add `id` for each point, so it will be preserved and correctly updated when needed. Demo with one series with added `id`s for points and second series showing the problem in pure JS (no Angular): https://jsfiddle.net/BlackLabel/vLrpkhg1/1/

If you have multiple problems please use separate issues (tickets) for different cases, so they could be better addressed and resolved.

As the wrong series type is being used and the problem with update could be resolved through existing options this issues doesn't look like a bug.

**Comment by briankpw** [comment]
Hi @KacperMadej 
I can change to scatter with linewidth to draw the line and create new issues.
But i consider this is option been reference or new object reference is same issues. 
Some is using reference, its work fine as the fiddle you created, but it will affect other chart too.

Here is the sample of scatterplot, that i changed, its still same error as line chart. i can use back same reference, but its make my shareable component will not be standardized, some need to use new and existing reference.
https://stackblitz.com/edit/highchart-angular-basic-gd29zg?file=app/views/catalog/catalog.component.ts

**Comment by KacperMadej** [comment]
@briankpw 
Thank you for the demo. How to recreate the problem?

**Comment by sebastianbochan** [comment]
Im closing this ticket due to inactvitation.

Please reopen if live demo and additional details will be available.
