### ISSUE TITLE
Gantt chart: Ellipsis or word wrap should work on long series datalabels

### ISSUE THREAD

**Issue by amruta30** [highcharts/highcharts#10576]
#### Expected behaviour
Long series datalabels should show ellipsis depending on the length of tasks or wordwrap should be supported.

Refer following sample examples:
![ellipsis](https://user-images.githubusercontent.com/7830487/56291029-12a43d00-6142-11e9-9b73-46cb3d85b1ba.png)

![wordwrap](https://user-images.githubusercontent.com/7830487/56291040-189a1e00-6142-11e9-93e3-c5bd31ce0ea4.png)

#### Actual behaviour
Refer below JS fiddles. It is observed that long series datalabels overflow outside the tasks. I tried setting the textOverflow ellipsis option in JS Fiddle2, still it didnt work.

#### Live demo with steps to reproduce
JS Fiddle1: https://jsfiddle.net/amrutaJgtp/hv7aem4w/
JS Fiddle2: https://jsfiddle.net/amrutaJgtp/hv7aem4w/1

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @amruta30,
Thank you for reporting about the problem. At this moment we cannot consider it as a bug, because its  default functionality in other series too. 

I set the enhancement status for this ticket which means, feature request.

I also advice you to post the idea as feature request in our [uservoice](https://highcharts.uservoice.com/) which will allow other users to vote.
