### ISSUE TITLE
Marker states inactive not working

### ISSUE THREAD

**Issue by 0z4ck** [highcharts/highcharts#10586]
#### Expected behaviour
fade other markers when it's not hovered .

#### Actual behaviour
just doesn't change.

#### Live demo with steps to reproduce
https://jsfiddle.net/d458vek2/

A2 doesn't fade when hovering A1. Is something going wrong ?

**Comment by pawelfus** [comment]
Hi @0z4ck 

This is expected behaviour. When you hover one series, all other series dim their markers. Markers within the same series don't hide. In most cases, highlighting just one bubble doesn't improve readability, see: https://www.highcharts.com/demo/bubble-3d 

If you want to change this behaviour, set `series.inactiveOtherPoints` to true:  https://jsfiddle.net/BlackLabel/h64v15ef/

**Comment by 0z4ck** [comment]
Thank you for your support. 
So, without setting `series.inactiveOtherPoints` to true,  is `series.marker.states.inactive` never handled ?  Because `series.states.inactive` is what makes other series dim with its default opacity=0.1, isn'it ?

**Comment by pawelfus** [comment]
Yes, that's correct. Unless we are forced to resolve inactive state on a marker level (e.g. networkgraph, where usually we have just one series with a lot of markers), `series.state.inactive` is enough to dim other series (where all groups: markers, dataLabels and graphs/lines/areas are handled). `inactiveOtherPoints` forces to animate every marker (according to `series.marker.states.inactive` options) but it's not a performance-wise solution - imagine animating 1k of markers, each and every one..
