### ISSUE TITLE
Chart.type update after drilldown issue

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#10597]
After drilldown, when changing series type from line (or other) to scatter, scatter has lines drawn. 

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/b6L0k7sh

1) Do drilldown and then press drillup button
2) Click scatter button to update chart.type

#### Product version
7.1.1

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
**Workaround**
Set `lineWidth` in default chart and during update.

Demo:
- https://jsfiddle.net/BlackLabel/8ut5jbof/

**Internal note**
It looks like scatter is not applied, but line type.

**Comment by bdevika** [comment]
@sebastianbochan, you are solved my issue. 

Thank you for the workaround :)

**Comment by sebastianbochan** [comment]
**Internal note**
The problem seems to be really complex.

My observations:
1. Drill down - series' options are copied to `levelSeriesOptions` including all params.
2. Drill up - new series has all options from `levelSeriesOptions` declared also as `series.userOptions`
3. During update, `typeOptions` of scatter are extracted, but overwritten by `series.userOptions`

```
            options = merge(
                typeOptions,
                plotOptions.series,
                seriesUserOptions
            );
```

Its tricky, because we should filter options during drillup.

The simpler workaround is calling `series.setOptions` with declared type.

Demo:
- http://jsfiddle.net/BlackLabel/6zpgwytq/ 

@TorsteinHonsi @jon-a-nygaard what do you think? Maybe you have any suggestion or any better idea.

**Comment by TorsteinHonsi** [comment]
Possibly, instead of copying `series.options` into `levelSeriesOptions` in step 1, we should rather copy `series.userOptions`. You can try that. Otherwise we need to somehow purge this on update.
