### ISSUE TITLE
Incorrect zIndex behaviour in stacked column chart

### ISSUE THREAD

**Issue by rolandasb** [highcharts/highcharts#10592]
#### Expected behaviour

`zIndex` should change order of the columns.

#### Actual behaviour

`zIndex` has no effect. `index` works fine, but it changes `chart.series` order as well, which is not needed in my case.

#### Live demo with steps to reproduce
https://codepen.io/anon/pen/axKdxY

#### Product version
Highcharts 7.1.1

#### Affected browser(s)
Tested on latest Safari and Chrome

**Comment by KacperMadej** [comment]
Hi @rolandasb 

`zIndex` is about layer oder - what's on top and what's under other series plots.
`Define the visual z index of the series.` - https://api.highcharts.com/highcharts/series.column.zIndex

Examples are provided in the API reference.

Since the series are not overlapping the `zIndex` option is not visible for stacked series, so everything works as it should. Please let us know if anything is still unclear, so we could provide more info.

**Comment by rolandasb** [comment]
Thanks for your answer @KacperMadej.

Is there any way to change order of the columns shown in chart without changing `chart.series` order?

**Comment by KacperMadej** [comment]
@rolandasb 
Yes, the `index` option - https://api.highcharts.com/highcharts/series.column.index
You could also check if `legendIndex` could be useful for you in any way - https://api.highcharts.com/highcharts/series.column.legendIndex

This is not a bug, so in general please contact support using other support channels as we are trying to keep the github issues for bug reports. https://www.highcharts.com/blog/support/

**Comment by rolandasb** [comment]
Yeah, regarding `index` docs say:

> [...] affecting the internal index in the chart.series array

Anyhow, my original question was answered. Thanks for the help, @KacperMadej.
