### ISSUE TITLE
Problem with Google Sheets being used as data source, and a proposed solution. 

### ISSUE THREAD

**Issue by bluecoredev** [highcharts/highcharts#10591]
This scenario involves using Google Sheets as the Data Source for Highchart Cloud. Creating one SpreadSheet per chart/data source is impractical, so clients use Sheets within SpreadSheets as data sources. 

PROBLEM
HighCharts is currently using an index-based method to identify a Sheet within a Spreadsheet. See attached. 
![cloud](https://user-images.githubusercontent.com/49792052/56435596-e0075b00-628d-11e9-9003-23f86ff48cfa.png)

SEVERAL REASONS WHY THIS IS A PROBLEM: 
1. Risk of damage to all charts is too high. Consider a SpreadSheet with 50 Sheets, each referenced as a data source for 50 different charts on highcharts cloud. If someone creates a new Sheet at index 1, either on purpose or by accident, all 50 charts will now display incorrect data.
 
2. Extremely hard to debug. Consider a SpreadSheet with 50 Sheets, each referenced as a data source for 50 different charts highcharts cloud.  If one creates a new sheet at index 19, again either by accident or on purpose, all data sources with index > 19 will display incorrect data. Imagine trying to find what the issue is, and what index caused the problem. 

3. Google reference sheets on a 0-based index, and Highcharts Cloud uses a 1-based index. If one day one of your developers decide to match google, either on purpose or by accident, all of your client's data sources will be incorrect. 

4. If a SpreadSheet has 50 sheets, and Sheet on index 8 is removed, all data sources with index > 8 are now broken. 

SOLUTION:
Use the Sheet ID instead. It is in the URL of all SpreadSheets as the gid= parameter. 
Example: 
ttps://docs.google.com/spreadsheets......fluzYmrVhVdpcNkveveEA/edit#**gid=0** (first sheet)
ttps://docs.google.com/spreadsheets....dpcNkveveEA/edit#**gid=1916146454** (another sheet within SpreadSheet)

BENEFITS: 
- Sheets and be rearranged and renamed without any problems. (MAJOR!)
- Risk of damaging data sources is now limited to one. 
- Your clients will have no problems finding the Sheet ID, all they have to do is look at the URL. 
<img width="752" alt="sheetID 1" src="https://user-images.githubusercontent.com/49792052/56436197-de3e9700-628f-11e9-9bbe-785584fb6290.png">
- The Sheet ID of the first Sheet within a SpreadSheet is 0.

HOW TO IMPLEMENT: 
You can add this feature without causing any problems to your existing clients. 

1. Rename "WorkSheet" to "Sheet Index", and put a note underneath saying the index starts at 1, not at 0 like google. 
2. Add a new field to this form called "Sheet ID", and add a modal explaining how to get the Sheet ID by just looking at the URL. 
3. When you add this field, it will be blank to all customers. 
If Sheet ID is blank, then use Sheet Index as data source. 
If Sheet ID has value, use Sheet ID as data source. 
If both have value, throw an error saying to chose one or another. 

Google does not have a getSheetByID() method, but it is easy to create one. 
https://stackoverflow.com/questions/26682269/get-google-sheet-by-id

Thank you very much for considering this change. It will greatly improve the usability of your product.

**Comment by kamilkulig** [comment]
Cloud GUI for adding spreadsheets is just a graphical representation of Highcharts JS data module API. Worksheet option is a wrap for googleSpreadsheetWorksheet API option: https://api.highcharts.com/highcharts/data.googleSpreadsheetWorksheet

**Please notice that worksheet index is not the only option** - you can define it as a worksheet id: 
![image](https://user-images.githubusercontent.com/13188589/56571832-13175a80-65be-11e9-9b89-79ef7b997ee8.png)

**Demo:** https://cloud.highcharts.com/show/AZ5w98-uW9

In my opinion, the main problem here is that finding the id is not quite easy. That’s the way I did it: 
![image](https://user-images.githubusercontent.com/13188589/56572499-78b81680-65bf-11e9-9c16-3b871f8bcb11.png)

I followed the guidance from documentation: 

> "The available id's from your sheet can be read from https://spreadsheets.google.com/feeds/worksheets/{key}/public/basic"

I think that our documentation for Cloud should clarify that (or at least redirect to Highcharts JS API (which should provide more explanation)). Furthermore, users should be aware of the danger of using worksheet index instead of id - thanks for pointing that out.


### Conclusion:

Documentation should explain how to get worksheet id. Current description doesn't specify how to find it in `https://spreadsheets.google.com/feeds/worksheets/{key}/public/basic` file.

I'll also create a ticket in our internal Cloud repo that suggests changing the name of "Worksheet" field to "Worksheet index" and adding "Worksheet id" field.

**Comment by bluecoredev** [comment]
The sheet ID comes from the gid= parameter in the URL. 

https://developers.google.com/sheets/api/guides/concepts
<img width="941" alt="sheetID" src="https://user-images.githubusercontent.com/49792052/57336128-bcd80a80-70d9-11e9-89b6-2f992fcd71f7.png">

And Highchart Cloud does not work when you put the Sheet ID in the Worksheet field. Proof: 
- Create a google sheet with 3 sheets. 
- Copy the gid= value as per Google's documentation
- paste in the worksheet field on a chart on Highchart Cloud. 

As per origininal suggestion, working with a Sheet ID is a much better way. I am not sure what this {key} value that you're using is, but it is definitely not the Sheet ID.
