### ISSUE TITLE
Color on solid gauge series not honored

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#10603]
#### Expected behaviour
When I set the color option on a series, it should get that color.

#### Actual behaviour
On solid gauges the color setting on the series is ignored. However, the color set on a point _does_ work.

This distinction doesn't make sense, as solid gauges only have 1 data point per series. 

#### Live demo with steps to reproduce
Compare http://jsfiddle.net/kzoon/wa0fd6hm/1/ with http://jsfiddle.net/kzoon/wa0fd6hm/2/

#### Product version
v7.1.1

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @kzoon 

This is caused by [`series.colorByPoint`](https://api.highcharts.com/highcharts/series.solidgauge) option - by default it's enabled in solid gauge, so color is taked from `series.colors` array, not from `series.color`.

Two solutions here:
- use `series.colors = ["red"]`
- set `series.colorByPoint = false` and use `series.color`

**Comment by kzoon** [comment]
Thanks! I never noticed that you could actually add more than one point to a solid gauge series...
