### ISSUE TITLE
Markers disappear after chart update

### ISSUE THREAD

**Issue by TatianaValeja** [highcharts/highcharts#10649]
#### Expected behaviour
When series data point has marker enabled, the marker should be present on the chart.

#### Actual behaviour
Works fine on the first load, but after the chart is updated, markers disappear and are only visible on hover.

#### Live demo with steps to reproduce
Setup: 
- Markers are disabled for the series
- Series data has some nulls
- When a datapoint is surrounded by nulls, marker is then enabled for that datapoint
- Chart series data is updated

https://jsfiddle.net/tvaleja/hxtw87dg/6/

#### Product version
Highcharts 7.1.1

#### Affected browser(s)
Only tested in Chrome

**Comment by pawelfus** [comment]
Hi @TatianaValeja 

Thanks for reporting the issue. It looks broken when using `series.update()` but it's fine with `series.setData()`: https://jsfiddle.net/BlackLabel/cpmtek57/

*Internal note:*
It's probably caused by these lines:

https://github.com/highcharts/highcharts/blob/86503150ccc534d53252da5f6da0867dba57413d/js/parts/Dynamics.js#L1219-L1224

Which destroys markers/labels (according to `series.marker.enabled` option) later without checking individual point options (`series.data[].marker.enabled`): https://github.com/highcharts/highcharts/blob/86503150ccc534d53252da5f6da0867dba57413d/js/parts/Dynamics.js#L1237-L1239

**Comment by TorsteinHonsi** [comment]
Demo with the fix applied: https://jsfiddle.net/highcharts/ny42x8q5/
