### ISSUE TITLE
dataLabels not visible in exported sunburst

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#10661]
The dataLabels are enabled but not visible in the exported **sunburst** chart.

![chart (65)](https://user-images.githubusercontent.com/23310742/57222952-c0e62880-7004-11e9-86bc-f9539253a9dd.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/s95pmyxL

#### Product version
Highcharts 7.1.1

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
**Workaround**
Disable animation in `exporting.chartOptions`

```
chart: {
        animation: {
          duration: 0
        }
}
```

Demo:
- https://jsfiddle.net/BlackLabel/nq8xhf31/

**Internal note**
Its a regression since v7.1 and related with the threat: https://github.com/highcharts/highcharts/issues/10496

Working demo: https://jsfiddle.net/BlackLabel/z74ncfdh/ (7.1).

**Comment by TorsteinHonsi** [comment]
It comes down to setting `dataLabels.defer` to true, which also causes the same problem in other series types: http://jsfiddle.net/noduy5sb/.

#### Workaround
The workaround above disables animation. A less intrusive workaround is to set `dataLabels.defer` to `undefined`: https://jsfiddle.net/txnfhcqv/

**Comment by TorsteinHonsi** [comment]
Original demo with the fix applied: https://jsfiddle.net/13L5xaqz/
