### ISSUE TITLE
Sunburst - chart is changed after update with initial options

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#10669]
#### Expected behaviour

The chart should look the same as before the update. Highcharts v 7.0.3: http://jsfiddle.net/BlackLabel/v8nht4c7/

#### Actual behaviour

The chart is changed: http://jsfiddle.net/BlackLabel/gLs4y39u/

#### Product version
Highcharts v 7.1.1

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
**Internal note**
Bisect leads me to: https://github.com/highcharts/highcharts/commit/ede7759 (also related is https://github.com/highcharts/highcharts/commit/77f28c7)

**Comment by TorsteinHonsi** [comment]
There is also a lower-level regression with `setData`: http://jsfiddle.net/dsbanu03/

This regressed in https://github.com/highcharts/highcharts/commit/98db6d3ffbb9347121ce9edc6a22f9769f16be86, and also affects this case.

**Comment by TorsteinHonsi** [comment]
Turned out this is a misconfiguration. In the original data, the id 3.0 is used twice. When using unique id's, it works as expected: http://jsfiddle.net/highcharts/em0s4j8c/.

I'll leave the issue open. We will "fix" it adding an error message for duplicate id's, at least in hierarchy series where it has consequences.
