### ISSUE TITLE
Highcharts – Stacked Area Bug, Broken artefacts

### ISSUE THREAD

**Issue by JohannesHoppe** [highcharts/highcharts#10687]
#### Expected behaviour

We display a bigger amount sensor data, with hourly values. 
The stacked areas should be displayed without artefacts.

#### Actual behaviour

When changing the extremes (eg. using the navigator) the chart displays broken artefacts.

<img width="1101" alt="Screen Shot 2019-05-08 at 16 28 12" src="https://user-images.githubusercontent.com/640639/57383430-13fbdf00-71af-11e9-80fb-69f05bd6a4b7.png">

#### Live demo with steps to reproduce
https://stackblitz.com/edit/highcharts-stacked-area-bug?file=src%2Fapp%2Fapp.component.ts

Use the navigator and scroll a bit to the left.
The areas are broken now.
Look at the console, an error is displayed, too:

```
Error: <path> attribute d: Expected number, "M Infinity 247 L I…".
```

The error happens in `Highcharts.SVGElement#dSettter` when a value like `M -Infinity 348 L -Infinity 358` comes in. The error with infinity-numbers also pops out when using other chart types (eg. `spline`). But only with stacked areas the artefacts are occurring.

#### Product version

Highstock 7.1.1

#### Affected browser(s)

Tested in latest Chrome and Firefox. Both broken.

**Comment by KacperMadej** [comment]
Hi @JohannesHoppe 

Thank you for reporting about the problem.

This is caused by using Date objects (not supported) instead of timestamps (supported and required).

Here's a demo without Angular: https://jsfiddle.net/BlackLabel/95hnew3v/

Here's a demo that is working, because timestamps are used: https://jsfiddle.net/BlackLabel/95hnew3v/1/

This doesn't look like a bug, more like [bad (not supported) data format](https://api.highcharts.com/highstock/series.area.data.x).

**Comment by JohannesHoppe** [comment]
Thank you for the quick and detailed help. The problem is solved! 👍
