### ISSUE TITLE
Export-data: document exportData event

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#10719]
#### Behaviour
Add `chart.events.exportData` to public API.
The code is in `export-data` module.

Relevant PR: https://github.com/highcharts/highcharts/pull/8479

FYI @bre1470

**Comment by bre1470** [comment]
Thank you for the ticket. I wonder, if this is really a documentation issue only or something code related. I also wonder, if `chart.events.exportData` is the best place, because the rest of the exporting options can be found under `exporting`. (I realize that the event itself gets fired on the chart instance.)

**Comment by KacperMadej** [comment]
We already have print related events fired on chart options are in chart.events, so the place looks good to me. We are already advising usage of the exportData event as a workaround on technical support and it works well, so making it official is what's this ticket is about.

What's your opinion about this @TorsteinHonsi ?

**Comment by TorsteinHonsi** [comment]
I agree, we can add it to `chart.events`.

**Comment by bre1470** [comment]
We agree - should I do the necessary modifications?

**Comment by bre1470** [comment]
Should I do the necessary modifications?
