### ISSUE TITLE
Stock Tools Custom GUI Demo not showing custom Dialogs/Popups

### ISSUE THREAD

**Issue by olivermack** [highcharts/highcharts#10788]
#### Expected behaviour

I'm not quite sure if this expectation does actually reflect the intention of the demo but when I started diving into the demo's codes I struggled to understand what's happening:
The [Stock Tools Custom GUI Demo](https://www.highcharts.com/stock/demo/stock-tools-custom-gui) should show a popup containing the two fields "Color" and "Width" as defined in the demo source codes.

At the end I need an example which shows how to integrate some sort of form where I can add some additional annotation metadata for an annotation plus some way to export the defined markers/annotations details - I thought the mentioned demo would be a good starting point - but as I said I'm struggling to get my head around what happens there.

#### Actual behaviour

The [Stock Tools Custom GUI Demo](https://www.highcharts.com/stock/demo/stock-tools-custom-gui) has defined a custom Popup in the Markup which also reflects the pattern described in the stock tools docs - but when invoking the popup it's not showing the custom popup but some default thing from which I can't figure where it's coming from.

https://github.com/highcharts/highcharts/blob/76b92282ff80a08e355ad4f532b88de94fee5508/samples/stock/demo/stock-tools-custom-gui/demo.html#L33-L42

#### Live demo with steps to reproduce

* Go to the Demo page https://www.highcharts.com/stock/demo/stock-tools-custom-gui
* Add a Text annotation
* Click on that annotation and hit the edit icon
* Review the form

You can even monitor the DOM to see that it's not the element `.highcharts-popup.highcharts-popup-annotations` where the `display` is toggled.

![RkypGZ6cK4](https://user-images.githubusercontent.com/666035/58172453-fb082900-7c98-11e9-9812-a4b235597591.gif)

#### Product version

highcharts 7.1.1 plus highstock

#### Affected browser(s)

Chrome 73.0.3683.103
Firefox 66.0.3

**Comment by olivermack** [comment]
By the way: the Stock Tools Docs part "DIALOGUE WINDOWS" at https://www.highcharts.com/docs/stock/stock-tools (sorry, no anchors available) also seems odd to me:

The shown example dialog seems also not to be rendered when opening the popup for that circle annotation

```
<div class="highcharts-popup highcharts-popup-annotations">
  <div class="highcharts-popup-wrapper">
    <label for="stroke">Color</label>
    <input type="color" name="stroke" value="#ff0000" />
  </div>
  <button>Save</button>
</div>
```

It shows some dialog with empty "Shape Options" section but not the "Color" input as expected.

![laH07GRvMV](https://user-images.githubusercontent.com/666035/58172913-28a1a200-7c9a-11e9-8cbf-eb9bdcd714c3.gif)

**Comment by sebastianbochan** [comment]
Hi @olivermack,
Thank you for contacting us. Let me answer for both parts. By default, annotation's options are extracted from defaultOptions of type.

If you could, please share your example of custom popup as jsfiddle. I will check if its possible to apply workaround or add feature with custom-fields.

**Comment by olivermack** [comment]
HI @sebastianbochan - thanks for your reply.
I don't have any example yet - but how about pointing out what's not working with the demo mentioned above? That'll do the trick for me as of now.

Here's the fiddle from the demo: https://jsfiddle.net/gvaartjes/kyd3vpwx
Any hint why the `<input type="color" name="stroke" value="#ff0000" />` is not being rendered in the popup would be great.

**Comment by sebastianbochan** [comment]
Hi @olivermack,
Will check and get back to you.

**Comment by olivermack** [comment]
Hi @sebastianbochan,

I've just tried to get my head around the annotations implementation - especially about the parts which takes care about the popup.

As far as I can assess from the codes it seems as if the `annotations-advanced` stuff is automatically creating the popup inside the charts container:

https://github.com/highcharts/highcharts-dist/blob/8c6661a7b36bbed9f9fb679610af023c96c31373/modules/annotations-advanced.src.js#L8320-L8323

I'm still pretty sure there's a way to extend the fields that are rendered there with some custom fields but I can't see how. It may be related to `annotationToFields` and its hardcoded map of `annotationsEditable`:

https://github.com/highcharts/highcharts-dist/blob/8c6661a7b36bbed9f9fb679610af023c96c31373/modules/annotations-advanced.src.js#L6454

https://github.com/highcharts/highcharts-dist/blob/8c6661a7b36bbed9f9fb679610af023c96c31373/modules/annotations-advanced.src.js#L6042-L6075

Can you give me some insights how this code plays together and if/how to customize the set of fields?

Best

**Comment by sebastianbochan** [comment]
Hi @olivermack,
Thank you for your patience, I needed to check possibilities, because the problem is a little bit more complex than looks like. 

At this moment the options are extracted from `annotations.option`and also from `navigation.annotationsOptions`. As a result you can declare your own parameter there and then add it also in `annotationsEditable.circle` array to avoid filtering params.

**Demo:**
- http://jsfiddle.net/BlackLabel/c450hoxa/

**Internal note**
@pawelfus I think that we should consider a declaration of our `annotationsEditable` array as public part of API and also add possibility to define a type of field (like color, default value, etc).

**Comment by pawelfus** [comment]
Ok, let's clarify things a bit (sorry for late reply!):

It seems that demo in docs is outdated and contains bugs. This demo suppose to be connected to one of our official demos - otherwise this may cause more issues in future. List of issues/bugs (to be fixed as soon as possible): 

Demo bugs:
- there's no `stockTools.events` option, but [`navigation.events`](https://api.highcharts.com/highstock/navigation.events)
- temporary references to popups should be stored in the same object, e.g. chart: `chart.indicatorsPopupContainer` and `chart.annotationsPopupContainer`

Core library bugs:
- default popup shouldn't show up, this is missing in the core, and can be worked around by adding lines in `showPopup`callback:
```js
          if (this.popup && this.popup.popup) {
            this.popup.popup.closePopup();
          }
```

Working demo: https://jsfiddle.net/BlackLabel/c8kdt7Lp/

Regarding extending popup fields: at this moment you can use either built-in popup with predefined fields or create your own.

**Comment by TorsteinHonsi** [comment]
@pawelfus Will you fix the demo?

**Comment by pawelfus** [comment]
@olivermack 

Updated docs (demos are not live yet): https://github.com/highcharts/highcharts/blob/docs/10788-stock-tools-docs-demos/docs/stock/stock-tools.md

Source code for demos: 
- basic GUI: https://github.com/highcharts/highcharts/tree/docs/10788-stock-tools-docs-demos/samples/stock/stocktools/basic-gui
- custom popup: https://github.com/highcharts/highcharts/tree/docs/10788-stock-tools-docs-demos/samples/stock/stocktools/custom-popup

Temporary demo fiddles:
- basic GUI: https://jsfiddle.net/BlackLabel/u6thyxd7/
- custom popup: https://jsfiddle.net/BlackLabel/5ezk92sv/
