### ISSUE TITLE
Venn diagram - setting halo effect  

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#10791]
#### Expected behaviour
 
Expect to works the same as in pie case - [Pie chart](https://jsfiddle.net/BlackLabel/jb6rtzy1/)

#### Actual behaviour

Halo isn't changing, but some circle behind the point is rendering. 

#### Live demo with steps to reproduce

[Demo](https://jsfiddle.net/BlackLabel/o9z5xwfa/)

#### Product version

Highcharts JS v7.1.1 (2019-04-09)
 

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
*Internal note*
FYI @jon-a-nygaard

**Comment by raf18seb** [comment]
Hi @Basts 
Thanks for reporting this.

Venn series inherits from Scatter - that's why it's possible to set some halo options which by default are disabled.
I think docs should be corrected because we can find halo options for Venn in API.

You can use Highcharts SVG Renderer to render similar effect as Pie chart has, but you need to consider how should it behave where the Venn points cross each other.

**Comment by jon-a-nygaard** [comment]
I agree with @raf18seb, the halo is likely an accidental feature inherited from scatter.

For me it is difficult to see how to make the halo feature work well with the venn series, and I believe it should be disabled in the code, and removed from the API.
There is another issue #10663 that is somewhat related to this one. Solving this issue, by improving a sets visibility during interactivity will be a good alternative to supporting the halo feature in my opinion.
