### ISSUE TITLE
Networkgraph Error: <image> attribute x: Expected length, "NaN".

### ISSUE THREAD

**Issue by DGK01** [highcharts/highcharts#10865]
#### Expected behaviour
No console errors, like the example https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/series-marker-symbol/

The problem is I have to setup the icons after I receive my data from the back-end using the callback 'afterSetOptions'. That's where the problem occurs. 

It doesn't happen with simple symbols. For example, if you replace the 
symbol: 'url(https://www.highcharts.com/samples/graphics/sun.png)'
with 
symbol: 'diamond'
then everything works fine.

It happens only on Chrome. On Microsoft Edge there are no console errors.

#### Actual behaviour
Error: <image> attribute x: Expected length, "NaN".

#### Live demo with steps to reproduce
https://jsfiddle.net/5v7njw08/12/

#### Product version
    "highcharts": "^7.1.1",
    "highcharts-react-official": "^2.1.3",
    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-scripts": "^2.1.8"

#### Affected browser(s)
Chrome. 
Microsoft Edge is fine.

**Comment by pawelfus** [comment]
Thanks for reporting this bug @DGK01 

**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/2Lk7rzf9/
Snippet:
```js
Highcharts.wrap(
  Highcharts.seriesTypes.networkgraph.prototype,
  'markerAttribs',
  function(proceed, point, state) {
    var attribs = proceed.call(this, point, state);

    if (isNaN(attribs.x) || isNaN(attribs.y)) {
      attribs.x = attribs.y = 0;
    }

    return attribs;
  }
);
```

*Internal note:*
Workaround is just a sanity check, but the problem is a bit more complicated - by default we first calculate plotX/plotY, then render a point, but in networkgraph order is swapped (first render points, then calculate new positions). Probably we will need to move initial positions out of the algorithm step (which seems to right thing to do anyway). Will look into this soon.

**Comment by DGK01** [comment]
Thank you @pawelfus I'll use the workaround you are posting here and I'll keep an eye to see when it is fixed.
