### ISSUE TITLE
logarithmic axis - mouse wheel zoom

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#10868]
#### Expected behaviour

As on not logarithmic yAxis - [demo](https://jsfiddle.net/BlackLabel/q2dhfsk4/)

#### Actual behaviour

Zoom doesn't work properly.

#### Live demo with steps to reproduce

[Demo - use scroll mouse to zoom](https://jsfiddle.net/BlackLabel/k5u8x41w/)

#### Product version

Highcharts JS v7.1.1 (2019-04-09)

#### Affected browser(s)

All

**Comment by Alexanovs** [comment]
Hi 
Nobody can not help me to solve this Bug?

**Comment by pawelfus** [comment]
Hi @Alexanovs 

This is a bit tricky issue - mouse wheel zoom is designed for maps (as the param suggests: `mapNavigation`), which does not have logarithmic scale. Accidentally this option works with standard charts, but since support for logarithmic is not implemented, we have this "bug". Instead I suggest to implement your own mousewheel event to deal with zooming in/out.

@sebastianbochan - could you take a look? Seems similar to #10285
