### ISSUE TITLE
Incorrect axis extremes computed for data with null values

### ISSUE THREAD

**Issue by KrishnaKumarHariprasannan** [highcharts/highcharts#10881]
#### Expected behaviour
Axis extremes are expected to be computed automatically without any explicit input from the user.

#### Actual behaviour
Automatic axis-extremes computation comes up with incorrect results when there are null values in the data, unless provided with [keys](https://api.highcharts.com/highcharts/series.line.keys)

#### Live demo with steps to reproduce
https://jsfiddle.net/8nft7wLy/2/

#### Product version
Highcharts 7.1.1

#### Affected browser(s)
Reproduced in Chrome & Firefox

**Comment by pawelfus** [comment]
Thanks for reporting the issue @KrishnaKumarHariprasannan 

This is caused by default generating points behaviour. When your create a series without x-values, then x-values are incremented by 1. See simple demos: https://jsfiddle.net/BlackLabel/4z15e6cL/ and https://jsfiddle.net/BlackLabel/4z15e6cL/1/ So in your case, all points that are `[null, something]` are incremented independently from the points that have values (e.g. `[0.123123, something]`): https://jsfiddle.net/BlackLabel/4z15e6cL/2/

However, when you set `series.keys`, we validate x-values to be numbers and invalid points are not rendered at all: https://jsfiddle.net/BlackLabel/4z15e6cL/3/

I'm not sure how this should be solved, any insights @TorsteinHonsi ?
