### ISSUE TITLE
Misalignment of stacklabels in variwide series.

### ISSUE THREAD

**Issue by ArulValan** [highcharts/highcharts#10962]
#### Expected behaviour
Stack-labels are not aligned properly in variwide chart.

#### Actual behaviour
The stacklabels should appear properly on top of series

#### Screenshot
![image](https://user-images.githubusercontent.com/30373131/59323767-ae44ca80-8cf9-11e9-8675-bc2cfe4f62ab.png)

#### Live demo with steps to reproduce

[jsfiddle](https://jsfiddle.net/BlackLabel/54e97hvt/)

#### Product version

Highcharts JS v7.1.2
#### Affected browser(s)
Google Chrome 74.0

**Comment by PaulDalek** [comment]
Thanks for reporting this @ArulValan.

**_Internal note:_**

The setOffset function that is responsible for aligning stack labels gets the pointXOffset and barW properties, which in case of column series are the same for every column. Since the width of each column is different in variwide series, the alignment of stack labels won't be correct.
