### ISSUE TITLE
Pie chart series dataLabels not working if it is an array

### ISSUE THREAD

**Issue by ghost** [highcharts/highcharts#10976]
According to https://api.highcharts.com/highcharts/series.pie.dataLabels both array and single object are supported for Pie chart type. But if I pass dataLabels as an array for Pie, then no data labels are shown.

Probably it is not supported for pie to have several datalabels, but can you please use first one of array, and not hide everything?

#### Expected behaviour
DataLabels are applied, if passed as an array

#### Actual behaviour
DataLabels are missing

#### Live demo with steps to reproduce
https://jsfiddle.net/demongd/cqzfsLep/2/
if you remove array from series.dataLabels and leave it as an object - it will be fine.

#### Product version
Highcharts v7.1.1

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Thank you for reporting this bug @DemongD

**Comment by arsinawaz** [comment]
I am also facing this issue, any update on this?

**Comment by pawelfus** [comment]
We haven't had time to prioritise this issue @arsinawaz For now, please use `dataLabels: { }` in pie series.

**Comment by arsinawaz** [comment]
@pawelfus thanks for the update, any idea when could this be resolved?

**Comment by pawelfus** [comment]
No ETA at this moment @arsinawaz

**Comment by yashTakeStock** [comment]
Still cant pass an an array for data labels

**Comment by pawelfus** [comment]
It seems we have to set `enabled=true` in the array config in `series`, demo: https://jsfiddle.net/BlackLabel/ctrgne4L/

**Comment by TorsteinHonsi** [comment]
Pie data labels as array has been supported for some months, but as Pawel says, it must be enabled per config object.

We have fixed that too since last release, now it can be enabled in `plotOptions` and arrays used on instances: https://jsfiddle.net/highcharts/sku7Lbfj/

**Comment by yashTakeStock** [comment]
I am using the latest react highcharts. The above solutions don't seem to be working. I enabled dataLabel in series and also added format:"{key}". I can see the labels only if I set dataLabel as { ... } in pie plotOptions  and if I dont have any settings for dataLabel in series, however I want to send an array so that I can have different formatting for point.name and point.y. I am trying to achieve the result shown in one of highcharts demo - https://www.highcharts.com/docs/chart-and-series-types/pie-chart - where you can see the point.y label inside and point.name outside. Below is the code I am using - I don't know where I am going wrong? 

import React from 'react';
import Highcharts from 'highcharts';
import HighchartsReact from 'highcharts-react-official';
require("highcharts/modules/accessibility")(Highcharts);

const PieChart= ({ data, category ,width="100%",height="100%"}) => {
  const counts = {};

  data.forEach(item => {
    const value = item[category];
    counts[value] = (counts[value] || 0) + 1;
  });

  const chartData = {
    series: Object.entries(counts).map(([name, count]) => ({
      name,
      y: (count / data.length) * 100, 
    })),
  };

  const options = {
    chart: {
      type: 'pie',
      panning: false,
    },
    title: {
      text: `${category}`,
    },
    series: [{
      innerSize: '60%',
      name: 'Percentage',
      colorByPoint: true,
      data: chartData.series,
      dataLabels: [{
        enabled: true,
        format: "{key}"
      }],
    }],
    tooltip: {
      pointFormat: '<b>{point.name}</b>: {point.y:.1f}%',
    },
    accessibility: {
      point: {
        valueSuffix: '%',
      },
    },
    plotOptions: {
        pie: {
          allowPointSelect: true,
          cursor: 'pointer',
          dataLabels: [{
            enabled: true,
            distance: 10,
            formatter: function () {
              return `<b>${this.point.name}</b>`;
            },
          },{ distance: -40,
           
            formatter: function () {
              return `${this.y.toFixed(1)}%`;
            },

          }],
        },
      },
    credits: {
      enabled: false,
    },
    accessibility: {
      enabled: false,
    },
  };

  return (
    <div style={{ height: height, width: width }}>
      <HighchartsReact highcharts={Highcharts} options={options} 
      containerProps={{ style: { height: '100%', width: "100%" } }} />
    </div>
  );
};

export default PieChart;

**Comment by karolkolodziej** [comment]
@yashTakeStock I was able to recreate the demo from the documentation in React- [demo](https://codesandbox.io/s/highcharts-react-demo-hooks-forked-vnkt36).

If you still have problems configuring it, [please contact our support team](https://www.highcharts.com/blog/support/), they will help you to set it up properly.
