### ISSUE TITLE
Only text inside zoom buttons (rangeSelector.buttons) is clickable

### ISSUE THREAD

**Issue by gitjul** [highcharts/highcharts#10986]
#### Expected behaviour

Whole area of zoom button should be clickable and update the zoom.

#### Actual behaviour

Only text inside of the button is clickable, the rest of the button is not.

#### Live demo with steps to reproduce

Any Highcharts demo with zoom buttons. Hover over zoom button area that isn't the text.

#### Product version

Highcharts 7.1.1

#### Affected browser(s)

All.

**Comment by pawelfus** [comment]
Hi @gitjul 

Thanks for reporting the issue, but whole buttons are clickable, please take a look: 

![clickable](https://user-images.githubusercontent.com/1453926/59494857-5ee3d300-8e8e-11e9-8086-c94cd29d07e9.gif)

https://jsfiddle.net/BlackLabel/v94yauLw/

The only thing I noticed is missing pointer cursor on the button are that is not text, which can be simply fixed in CSS.

**Comment by gitjul** [comment]
@pawelfus you're completely right, it's just the pointer, sorry! will patch in CSS, but I think this should be the default. I'd suggest to fix this small UX issue. let me know if I should open a new issue for that. 

cheers!

**Comment by gitjul** [comment]
@pawelfus is there a possibility to change this setting via the `rangeSelector.buttons` configuration, i.e. when not using the styled mode?

**Comment by sebastianbochan** [comment]
Hi @gitjul,
You can do that by [buttonTheme.states.hover](https://api.highcharts.com/highstock/rangeSelector.buttonTheme) option.

Demo:
- https://jsfiddle.net/BlackLabel/y895v1xe/
