### ISSUE TITLE
Updating data is significantly slower when xData from older data set is reused for newer data set

### ISSUE THREAD

**Issue by LaniMoo** [highcharts/highcharts#11016]
Drawing 86,400 points on a brand new chart loads fairly quickly: https://jsfiddle.net/lanimelrok/0kyvadzL/

But when switching to 86,400 points from a less granular data set, the performance worsens significantly. In this example, I am switching from hourly data to minute data: https://jsfiddle.net/lanimelrok/kc25vm30/

It looks like this only happens when Highcharts finds matching xData from the previous data. I've narrowed the drop in performance to these lines of code:

https://github.com/highcharts/highcharts/blob/5049ef3a9d24dc28c8fd4dbb52dcdca2249b8402/js/parts/Dynamics.js#L774-L777

This is a huge problem for our app because we provide data to our users in a variety of resolutions. Every time our users switch resolutions they have to wait up to 3 minutes for the charts to update.

**Comment by pawelfus** [comment]
Hi @LaniMoo 

When dealing with data, we recommend to use [`series.setData(data, redraw, animation, updatePoints)`](https://api.highcharts.com/class-reference/Highcharts.Series.html#setData). This way you can set `updatePoints=false` which drastically increases performance: https://jsfiddle.net/BlackLabel/v1hga67t/ - you definitively don't want to update/add/remove points, but you want to replace whole dataset.

**Comment by LaniMoo** [comment]
Thank you, @pawelfus. Worked perfectly.

**Comment by pawelfus** [comment]
Thanks for the confirmation! Closing the issue then.

**Comment by TorsteinHonsi** [comment]
_Internal note_
I think we should also think about a way to prevent this from happening again. It is intuitive for implementers to use `chart.update` like this, and we should make sure it performs.

One way of doing that would be to use a threshold value, for example by extending the scope for the existing [turboThreshold](https://api.highcharts.com/highcharts/series.line.turboThreshold) option to also apply to `setData`. So that when the number of points exceeds this, `Series.update` calls `setData` with the `updatePoints` option set to false. The only downside is that it introduces some inconsistencies to the implementers, so that adding 999 points will not work exacly like adding 1000 point. Alternatively we could throw a warning when crossing the threshold, but that would likely not be picked up in automated environments. On the up side, there are already changes in behaviour at this threshold, plus with this amount of points, animation on point update is skipped anyway.

What do you think @pawelfus ?

**Comment by TorsteinHonsi** [comment]
In practice, these lines

https://github.com/highcharts/highcharts/blob/bd1e8ca8bf2c56727bb62c491714ac4606b10d1a/ts/parts/Dynamics.ts#L1386-L1388

Would be replaced by 

```js
            if (options.data) {
                this.setData(
                    options.data,
                    false,
                    undefined,
                    options.data.length < this.options.turboThreshold
                );
            }
```

**Comment by pawelfus** [comment]
+this won't resolve the issue when `turboThreshold` is disabled because points are objects (+heatmap requires this workaround to work with more than 1k points), making this even harder to debug. But I agree, we should do something to speed things up.

Ideally, argument passed from `chart.update(updatePoints)` to `series.update(updatePoints)` eventually could be available in `series.setData(...args, updatePoints)` - that could resolve this issue + description in API (FAQ/knowledge base). This way user directly (instead of indirect `tuboThreshold`) controls this. However polluting args in `chart.update()`...
