### ISSUE TITLE
scrollablePlotArea's highcharts-scrollable-mask stopping at (first?) highcharts-treegrid-node-expanded/collapsed

### ISSUE THREAD

**Issue by FilipeCosta06** [highcharts/highcharts#11114]
#### Expected behaviour
When scrolling (horizontally in this case) the plotArea (using `chart.scrollablePlotArea`), it should pass behind a semi-transparent overlay/mask (85%, by default), at the yAxis labels.

#### Actual behaviour
The masks stops at the first `highcharts-treegrid-node-expanded` (or `highcharts-treegrid-node-collapsed`), meaning a `highcharts-treegrid-node-level-1` yAxis label containing sub-tasks.

I edited the background colors in the demo to make it clearer. 

Something weirder, and hopefully helpful, is that, in this fiddle, if you collapse a "Parent" node (doesn't matter which), then the `mask` properly expands to the bottom of the chart BUT if you then re-expand the node, the **last** "Parent" node won't be  included in the mask again (and if you collapse both and re-expand the first one, it will mess up the mask again, but include "1" sub-category). 

Note that, in this case, there are multiple series, but locally I'm testing with only one and have the same behaviour.

Also, for the scroll to show, I set `scrollablePlotArea: { minWidth: 2000 }` so you need to have a window size below 2000 pixels for it to appear.

#### Live demo with steps to reproduce
https://jsfiddle.net/j6e1gck4/2/

#### Product version
HighCharts/GanttCharts v7.1.2

#### Affected browser(s)
Chrome, Version 74.0.3729.169 (Official Build) (64-bit)
All ?

**Comment by KacperMadej** [comment]
Hi @FilipeCosta06 

Thank you for reporting about the problem.

It looks like order of internal functions called is not correct, because height looks like it's one step behind for each update of chart height.

As a simple workaround you could trigger recalculation of the mask after redraw using setTimeout like in the below demo: https://jsfiddle.net/BlackLabel/j8ts7nbf/

**Comment by MichaelSundhed** [comment]
Any progress on this issue?
This also happens to my project!
![image](https://user-images.githubusercontent.com/116732119/206197567-9961fe7e-f2d0-4854-a729-39915e8363c0.png)
Seems to be no workaround...

**Comment by karolkolodziej** [comment]
This ticket has been closed, could you please share a demo with that issue?

**Comment by ounique** [comment]
> Any progress on this issue? This also happens to my project! ![image](https://user-images.githubusercontent.com/116732119/206197567-9961fe7e-f2d0-4854-a729-39915e8363c0.png) Seems to be no workaround...

The same issue reproduced in my project. As far as I understand, it is happening due to using `scrollablePlotArea` property.
During the research I found out that it is caused by `highcharts-scrollable-mask` path.
As simple workaround you may apply the following styles:
```
highcharts-scrollable-mask {
    clip-path: polygon(0 0, 95% 0, 95% 100%, 0% 100%);
}
```

@karolkolodziej you may see an example of configuration below (sorry that I don't share a live demo, because my project is on angular):
```
{
    chart: {
        type: "column",
        scrollablePlotArea: {
            scrollPositionX: 1,
            minWidth: 2000
        }
    },
    colorAxis: {
        gridLineColor: "#D5DCE3"
    },
    title: {
        text: null
    },
    xAxis: {
        categories: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
        labels: {
            style: {
                color: "#000000",
                fontSize: "12px",
                fontWeight: "400",
                fontFamily: "Inter"
            }
        }
    },
    yAxis: {
        title: {
            text: null
        },
        tickInterval: 1,
        tickAmount: 8,
        labels: {
            style: {
                color: "#8F9EB4",
                fontSize: "11px",
                fontWeight: "400",
                fontFamily: "Inter"
            }
        }
    },
    legend: {
        symbolRadius: 3,
        itemStyle: {
            color: "#000000",
            fontSize: "12px",
            fontWeight: "400",
            fontFamily: "Inter"
        },
        align: "left",
        verticalAlign: "bottom",
        borderWidth: 0
    },
    tooltip: {
        shared: true,
        crosshairs: true,
        backgroundColor: "#fff",
        borderColor: "transparent",
        borderRadius: 6,
        useHTML: true,
        outside: true
    } as Highcharts.TooltipOptions,
    plotOptions: {
        column: {
            pointWidth: 13,
            groupPadding: 0.2
        },
        series: {
            borderRadiusTopLeft: "2px",
            borderRadiusTopRight: "2px"
        } as PlotSeriesOptions
    },
    series: [
        {
            name: "Tokyo",
            data: [49.9,
                   71.5,
                   106.4,
                   129.2,
                   144.0,
                   176.0,
                   135.6,
                   148.5,
                   216.4,
                   194.1,
                   95.6,
                   54.4]

        }, {
            name: "New York",
            data: [83.6,
                   78.8,
                   98.5,
                   93.4,
                   106.0,
                   84.5,
                   105.0,
                   104.3,
                   91.2,
                   83.5,
                   106.6,
                   92.3]

        }, {
            name: "London",
            data: [48.9,
                   38.8,
                   39.3,
                   41.4,
                   47.0,
                   48.3,
                   59.0,
                   59.6,
                   52.4,
                   65.2,
                   59.3,
                   51.2]

        }, {
            name: "Berlin",
            data: [42.4,
                   33.2,
                   34.5,
                   39.7,
                   52.6,
                   75.5,
                   57.4,
                   60.4,
                   47.6,
                   39.1,
                   46.8,
                   51.1]

        }
    ]
}
```

**Comment by karolkolodziej** [comment]
Thank you @ounique for the explanation!

From what I can see here the issue is with how the chart gets reflowed because, on the chart reflow, the `scrollable-mask` is being updated.
I can't replicate this issue in the [jsfildle with plain JS ](https://jsfiddle.net/BlackLabel/0h475wgs/) altho this issue is visible in the [stackblitz in Angular ](https://stackblitz.com/edit/highcharts-angular-line-ih89ei)because of how it works.

As a workaround you can apply the styling you suggested or you have to make sure that the chart reflow is correctly invoked on each window resize.
