### ISSUE TITLE
Force-Directed  Network Graph in Highcharts: Each time a node is clicked, its position moves.

### ISSUE THREAD

**Issue by leostar-eva** [highcharts/highcharts#11124]
#### Expected behaviour
After loading, there is no longer any position movement of any element in the graph. When clicking any node (regardless of whether the node is bound with the click event or not), the node position is not moved.

#### Actual behaviour
Change the color of the node by clicking on the event, and use chart.update () to update. We have tried, no matter whether the click event is added here or whether there is Chart. Update () in the click event, as long as the node is clicked, the node will move its position.

#### Live demo with steps to reproduce
https://jshare.com.cn/temp/hOtWfs

#### Product version
"highcharts": "^7.1.1"

#### Affected browser(s)
Chrome,
Not tried in other browsers.

**Comment by pawelfus** [comment]
Hi @leostar-eva 

Thank you for reporting the issue. Unfortunately your demo does not load for me, but most probably the same happens in our official demo: https://www.highcharts.com/demo/network-graph

This is caused by [`draggable`](https://api.highcharts.com/highcharts/series.networkgraph.draggable) option - once node gets mouse up & mouse down events, positioning algorithm is restarted, trying to find new, better positions. You can disable `draggable` option and you won't see this happening again: https://jsfiddle.net/BlackLabel/3oenvakc/1/

I agree, it's unnecessary to rerun algorithm when it's a simple click. Probably we should add some buffer/sensitivity for mouse move to detect if it's a drag&drop operation, or just a click. We do the same for zooming and panning.

**Comment by leostar-eva** [comment]
@pawelfus  Thanks for the answer to my question, but at the same time, I found another problem: when 'chart.update()' exists in the click event of the node to update the node, the node will still move. For example, we need to change the node's 'lineColor', 'lineWidth', 'radius', and update the node through' chart.update() '. Like this:

`point: {
          events: {
            click: function (e) {
              this.update({
				  marker: {
					...this.marker,
					...{
					  lineColor: this.commonColor // '#f73cb2'
					}
				  }
				})
            }
          }
        }`

So I wonder if I can add some judgment in 'chart.update ()', if the node only changes some appearance properties, and does not change the number of nodes and the relationship between nodes, there is no need to recalculate the position. Or you can update the appearance properties of the node in some other way. Very urgent. Thank you.
