### ISSUE TITLE
Scrollbar in heatmap y-axis is at bottom by default.

### ISSUE THREAD

**Issue by HarishSha** [highcharts/highcharts#11135]
#### Expected behaviour
Scrollbar at initial load should be on top just like scrollbar in other charts.

#### Actual behaviour
y-axis scrollbar is at bottom at initial load.

#### Live demo with steps to reproduce
http://jsfiddle.net/zwy3vhts/60/

#### Product version
Latest

**Comment by pawelfus** [comment]
Hi @HarishSha 

This is expected behaviour - all series works the same way. Categories start from bottom, so first category (with index=0, "AE") is bottom left corner. Perhaps you want to use [`yAxis.reversed`](https://api.highcharts.com/highcharts/yAxis.reversed), see demo: http://jsfiddle.net/BlackLabel/1ugLh8p5/ - now first category ("AE") is top left corner, making scrollbar to start from top.
