### ISSUE TITLE
Selection markers leave their copy in old place after zooming.

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#11132]
#### Expected behaviour
After zooming, I would like to keep only the original selected points' markers.

#### Actual behaviour
The points' markers are disabled. When selecting points we enable their markers, and then when we zoom - the points (markers) are moved, but some of old markers graphics are still shown.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/qnhae94y

Click one point - a few of them should be selected - and then zoom the chart.

#### Product version
Highcharts 7.1.2

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
The order of actions is wrong:
- select points
- update points with markers

That cause this "shadow" marker (`stateMarkerGraphic`) - marker was created on demand, and never removed/hidden because `point.update()` has already it's marker.

When you first update points with marker, then set it's selected state, you get better results: https://jsfiddle.net/BlackLabel/ez5tsnpa/

PS: You can select point by simple setting `selected: true` in point's config: https://jsfiddle.net/BlackLabel/ez5tsnpa/1/
