### ISSUE TITLE
DataLabels on Combined chart don't get the same color

### ISSUE THREAD

**Issue by Rubemlrm** [highcharts/highcharts#11140]
#### Expected behaviour
The expected behaviour is the dataLabels on pie chart have the same color.

#### Actual behaviour
For some reason there is a element of the dataSet that gets a different color than the others like we can see in this image

![image](https://user-images.githubusercontent.com/480040/60010160-19ce5680-966f-11e9-97f8-f93f41d074d7.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/v3f8md6e/

#### Product version
Highcharts 6.2.0 and Highcharts-vue 1.3.5

#### Affected browser(s)
Chrome and Firefox

**Comment by pawelfus** [comment]
Thank you for reporting the issue @Rubemlrm 

**Workaround:**
Set `pie.dataLabels.inside = false`. Demo: https://jsfiddle.net/BlackLabel/38asfxgz/

*Internal note:*
It's caused by these lines:
https://github.com/highcharts/highcharts/blob/b15f4460d74ad73169cbe015f9f16105899fb08b/ts/parts/DataLabels.ts#L1073-L1080

Which first checks `inside` option from general options, then the distance. For pie series, negative distance implies `inside` option.

**Comment by Rubemlrm** [comment]
@pawelfus thank you for the workaround, just applied that to the code and its working like a charm.
Thanks a lot =)
