### ISSUE TITLE
Stock tools - problem with responsive of area elements

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#11175]
#### Expected behaviour

All annotations should be related to an axis scale.

#### Actual behaviour

<img width="1275" alt="Zrzut ekranu 2019-06-26 o 10 59 50" src="https://user-images.githubusercontent.com/22988131/60166599-c0e2f780-9801-11e9-821a-0ad2fea2157c.png">

<img width="710" alt="Zrzut ekranu 2019-06-26 o 11 00 30" src="https://user-images.githubusercontent.com/22988131/60166620-cb9d8c80-9801-11e9-8854-8e77d7af3150.png">

In the above screenshots we can see that 'Line' and 'Label' annotations, as opposed to 'Circle' and 'Reactangle', are located correctly and keep the scale of the axes.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/7zfjy0sc/

#### Product version
Highstock v7.1.2

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
*Internal note:*
After discussion, we decided to make rectangle scalable, but circle has only one variable (radius) and two scales (xAxis and yAxis). Since there's no `ellipsis` in Renderer clasess (svg/vml), we decided to leave this annotation as is. In future we can decide to add x-circle, y-circle and basic circle, where other circles will have radius linked to the specific axis.
