### ISSUE TITLE
changing xAxis.min and xAxis.max doesn't update chart after scroll.

### ISSUE THREAD

**Issue by mosijava** [highcharts/highcharts#11183]
In [this fiddle](http://jsfiddle.net/mosijava/0j7d8Lzn/31/) change the drop down without scrolling the chart. everything works fine. 

but if you scroll you can't update the chart with this dropdown anymore.

offcourse I made it really simple. the actual use case in my program is when user want to filter data from server base on date and I can't change min-max to show them a correct chart!

**Comment by sebastianbochan** [comment]
Hi @mosijava,
Thank you for reporting. The github is our bugtracker so for general [support]() questions, please use email / forum or stackoverflow.

ps. The problem is that you declare "max" value instead of calling xAxis.setExtremes. The second issue is `new Date`, which should be replaced by `Date.UTC` to keep correct format.

Demo:
- http://jsfiddle.net/BlackLabel/17k0uvr9/

**Comment by mosijava** [comment]
Hi @sebastianbochan 
sorry for that. but I thought that it's a bug.
thank you very much for your answer.
