### ISSUE TITLE
Highmaps color axis not colored when exporting as JPEG/PNG in Edge

### ISSUE THREAD

**Issue by jcmillett** [highcharts/highcharts#11267]
#### Expected behaviour
Color axis should be colored when exported to JPEG/PNG using Edge browser.

#### Actual behaviour
Color axis is black when exported to JPEG/PNG using Edge browser.

#### Live demo with steps to reproduce
1.) Open Edge browser
2.) Navigate to Highmaps demo: https://www.highcharts.com/maps/demo/color-axis
3.) Click chart context menu, and select "Download PNG image" or "Download JPEG image"
4.) Open downloaded image, and observe color axis is not colored as it should be. It's just black.

#### Product version
Highmaps 6.1.0

#### Affected browser(s)
Edge

**Comment by jcmillett** [comment]
![highmapsColorAxis](https://user-images.githubusercontent.com/4006766/60537453-c63eb700-9cc5-11e9-85ef-5eab50f198fa.png)

**Comment by KacperMadej** [comment]
Hi @jcmillett 

Thank you for reporting about the problem.

This is due to using offline export module - without it the exported image is correct.
https://jsfiddle.net/c5zgserv/

This is a general issue with offline exporting and gradients on Edge browser.
Simple demo: http://jsfiddle.net/3c4br2Lv/1/
