### ISSUE TITLE
categories are getting divided equally even though categories have different number of bars

### ISSUE THREAD

**Issue by protimamondal** [highcharts/highcharts#11284]
#### Expected behaviour
category of x-axis should not get divided equally instead it should get divided as per the number of bars

#### Actual behaviour

There are two categories on x-axis, first one has more number of bars whereas the second one has very less like 3 bars , but the categories are getting divided equally on the x-axis because of that bar heights are getting very squeezed. Also we can see so much space before the end of first category and  and at the starting of the second category

#### Live demo with steps to reproduce
[http://jsfiddle.net/j8hc96qn/1/]()

#### Product version

Highstock JS v2.1.9

#### Affected browser(s)
Google chrome

**Comment by pawelfus** [comment]
Thanks for this report @protimamondal 

This is expected behaviour at this moment. Each category has the same height, divided equally between all series on the chart. There's no relation between number of points in category, space is always reserved.

You can try workaround posted by @Izothep : https://www.highcharts.com/forum/viewtopic.php?t=34228

**Comment by pawelfus** [comment]
Closing in favor of #11308 - please follow #11308 ticket to get updates.
