### ISSUE TITLE
Collapsing existing chart item by custom action

### ISSUE THREAD

**Issue by pelek12** [highcharts/highcharts#11339]
I'm not sure if this is a bug or request for new feature but if I try to expand/collapse some item by changing its 'collapsed' flag, nothing happens

#### Expected behaviour

Click on the 'Toggle collapse' button (from live demo) should toggle collapse state of item

#### Actual behaviour

Item stays at the same collapse state

#### Live demo with steps to reproduce

https://jsfiddle.net/rL6dyzg1/12/

#### Product version

Highcharts Gantt 7.1.2

#### Affected browser(s)

Chrome latest

**Comment by pawelfus** [comment]
Thanks for reporting the issue @pelek12 

I think the way you use `collapsed` option is the correct one. The problem is option stored in `series`, while for collapsing `yAxis` is responsible.

**Workaround:**
We have an unofficial API for collapsing:

- `chart.yAxis[0].ticks[index].toggleCollapse();`
- `chart.yAxis[0].ticks[index].collapse();`
- `chart.yAxis[0].ticks[index].expand();`

Where `index` = category index (starts from 0). See demo: https://jsfiddle.net/BlackLabel/g6tznuo9/

*Internal note:*
We should (on data update) either redraw axis, or simply call API mentioned above.

**Comment by pelek12** [comment]
Thank you for fast reply. It seems that chart.yAxis[0].ticks[index].toggleCollapse() works fine for my case.
