### ISSUE TITLE
Highcharts series showing different data for 'column' and 'line' chart for multiple Y axis

### ISSUE THREAD

**Issue by hakkim** [highcharts/highcharts#11355]
I have a higchart with two Y axis. Both are line chart for first and everything works fine. But when I change it to column chart for one Y axis item, the graph plotting in a different way. There seems some points are missing. I have a button for toggling between 'column' and 'line' chart. upon clicking the button it shows different kinds of graph, even if the data are the same for both.

#### Expected behaviour
For both 'line' and 'column' chart in second axis, the points of first axis must be the same and both the graph of first axis must be similar for both 'column' and 'line' of the second axis.

#### Actual behaviour
When the second axis is 'column' the first axis showing graph differently.

#### Live demo with steps to reproduce
https://jsfiddle.net/hakkim/30v2schq/

#### Product version
 Highcharts JS v7.1.2 (2019-06-03)

#### Affected browser(s)
Google Chrome

**Comment by pawelfus** [comment]
Hi @hakkim 

Thanks for contacting us. This is expected behaviour - the difference between the highest and the lowest column is so big that columns are getting height < 1px, thus making them invisible. You can prevent this by setting [`series.minPointLength`](https://api.highcharts.com/highcharts/series.column.minPointLength), see: https://jsfiddle.net/BlackLabel/gvm4oky5/

Additional changes are related to the `dataGrouping`.

- default [`groupPixelWidth`](https://api.highcharts.com/highstock/series.column.dataGrouping.groupPixelWidth) for columns is `10px`, while to line series is `5px`. Change it so graph will look almost the same: https://jsfiddle.net/BlackLabel/gvm4oky5/2/
- default [`approximation`](https://api.highcharts.com/highstock/series.column.dataGrouping.approximation) for column series is `"sum"`, while for line series is `"average"`, let's match them: https://jsfiddle.net/BlackLabel/bg0762cj/

In case something is not clear, or you simply have more questions, please contact our support: https://www.highcharts.com/blog/support/
