### ISSUE TITLE
Highcharts Gantt: Recently added item, when last item on chart is collapsed, breaks collapsing/expanding feature

### ISSUE THREAD

**Issue by pelek12** [highcharts/highcharts#11350]
Like in description. When last item on chart is collapsed and we try to add another one, we can’t expand both of them. Also, line between items are not displayed correctly.

#### Expected behaviour
After adding new item, we should be able to expand it. 

#### Actual behaviour

Expanding is not working, also line between items are not displayed correctly.

#### Live demo with steps to reproduce

https://jsfiddle.net/ek20us4n/

#### Product version

Highcharts 7.1.2

#### Affected browser(s)

Chrome latest

**Comment by pawelfus** [comment]
Thanks for reporting this issue @pelek12 - it seems that only last collapsed category is causing these issues.

**Workaround:**
Modify breaks manually:
http://jsfiddle.net/BlackLabel/n05fgh9b/

Snippet:
```js
function fix11350(chart) {
  var breaks = chart.yAxis[0].options.breaks,
    lastBreak = breaks[breaks.length - 1];

  if (lastBreak.to + 0.5 >= chart.yAxis[0].max) {
    lastBreak.from += 0.5;
  }
}
```

*Internal note:*
It's caused by these lines: 
https://github.com/highcharts/highcharts/blob/91df181bb32a3d8235d9e83ea527893d55d9df17/js/parts-gantt/TreeGrid.js#L57-L75

We calculate initial breaks only on init, which makes perfect sense, but we modify values a little when break would be rendered outside the current extremes. That means on `addPoint`/`setData`/`series.update` we still have old break with modified values in `axis.options.breaks`, while condition is no longer met (extremes have increased). This artificial break should be removed (e.g. on `updatedData` event?) or this `TO DO` should resolve the issue.

**Comment by pelek12** [comment]
Thanks for fast reply. For now I will apply that fix, but I will keep it in mind, that this is only temporary solution.
