### ISSUE TITLE
Animation of x-Axis without Series

### ISSUE THREAD

**Issue by FruitGLemon** [highcharts/highcharts#11380]
#### Desired Behaviour
Can you actually animate the x-Axis of a chart for smoother transition in live-charts without having the series animation between points?

#### That's how it is currently implemented
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/dynamic-update/

**Comment by pawelfus** [comment]
Hi @FruitGLemon 

Do you mean something like this: https://jsfiddle.net/BlackLabel/qgewLfyj/4/ ? As you can see, you can remove all points and graph from the chart and chart will recreate all items without animations.

Alternatively, we can disable animation for a short time by wrapping responsible methods: https://jsfiddle.net/BlackLabel/5vh4r9zt/ - this solution is a bit faster, because does not require recreating DOM elements.

**Comment by FruitGLemon** [comment]
Hi @pawelfus 

thank you for your reply. This is partly what I need. But when you add grindLines for the x-Axis the chart looks off. Also, is there a possibility to get the x-Axis to shift without always stopping for a short period, so you can get a fluent flow without interruption?

**Comment by pawelfus** [comment]
@FruitGLemon - I don't understand the issue with gridLines: https://jsfiddle.net/BlackLabel/5vh4r9zt/3/ - those looks fine. Anyway, please contact our support: https://www.highcharts.com/blog/support/ - you posted on our bugtracker :)
