### ISSUE TITLE
What is the expected behaviour of linkFormat data label prop in network graphs

### ISSUE THREAD

**Issue by l2silver** [highcharts/highcharts#11402]
#### Expected behaviour
Link format only formats text on links between nodes

#### Actual behaviour
Link formats text on nodes and link

#### Live demo with steps to reproduce
https://jsfiddle.net/wx2jphfz/2/

#### Product version
v7.1.2

#### Affected browser(s)
Chrome tested, most likely all

**Comment by pawelfus** [comment]
Hi @l2silver 

Thanks for reporting the issue. What you actually created are two dataLabels per links and nodes, you need just one dataLabels config: https://jsfiddle.net/BlackLabel/6g1yeb2v/3/ - it seems that dataLabels are hidden due to overlapping (drag&drop a node and labels will show up). Setting [`dataLabels.allowOverlap`](https://api.highcharts.com/class-reference/Highcharts.SeriesNetworkDataLabelsOptionsObject#allowOverlap) to `true` helps in this case: https://jsfiddle.net/BlackLabel/6g1yeb2v/5/

**Comment by l2silver** [comment]
Thanks! That partly did the trick, although I found that if I did not define linkFormat the links format would default to regular format, so I had to set linkFormat to "" to disable them.
