### ISSUE TITLE
Boost module - column series doesn't render properly

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#11406]
It seems that the boost module doesn't provide for pointPlacement property in column series.  

I think that this could be related to these topics:
[#6600](https://github.com/highcharts/highcharts/issues/6600)
[#6602](https://github.com/highcharts/highcharts/issues/6602)
[#7009](https://github.com/highcharts/highcharts/issues/7009)

#### Live demo with steps to reproduce

[Demo](http://jsfiddle.net/BlackLabel/5r6yutsm/) 

#### Product version

Highcharts JS v7.1.2 (2019-06-03)

#### Affected browser(s)

All

**Comment by janM37** [comment]
Hi,
Does any workaround exists for this issue ?
(reposting here the topic created on the forum : https://www.highcharts.com/forum/viewtopic.php?f=9&t=42453 )
Seeing bar/column labels is unfortunately kinda critical for my project.

Thanks again !

**Comment by pawelfus** [comment]
Hi @janM37 

Unfortunately I don't see any simple workaround for this case. Whole `pointPlacement` logic is not implemented in boost mode. The easiest solution I can think of is to edit source file:

- find `// Make sure we're not drawing outside of the chart area.` comment in `boost.src.js`
- change the line above from: `x = xAxis.toPixels(x, true)` to `x = xAxis.toPixels(x, true) + (series.index === 0 ? -1 : 1);`

That will translate column to the left by 1px first series and 1px to the right for the second series. You can translate also by `-0.5/+0.5` or even `-1/0` depending on the result you prefer. If you have more series, then depending on `series.index` you can use different translations.

**Comment by janM37** [comment]
Hi @pawelfus ,
Thanks for your answer. It indeed allows to deal with multiple series.
My issue is some exactly this one but according to your colleague @Basts it should be related.
I only deal with one serie here. It seems that boost.js removes bar labels from the chart when too many bars must be displayed. An example here (drill to third layer) :
https://jsfiddle.net/janM37/sm718rxu/

I was wondering if there was a workaround to keep bar labels while using boost.js (which considerably speeds up rendering when there are a few thousands bars).

Thanks !

**Comment by pawelfus** [comment]
@janM37 - I'm afraid that most of the extra time in non-boosted mode is caused by.. dataLabels. There's rendering and anti-collision logic involved. Please consider simple demo (1k points): http://jsfiddle.net/BlackLabel/jfu9rvbg/ - in console you can observe results:
- `< 150ms` - chart without dataLabels
- `> 1700ms` - chart with dataLabels

The general solution here is.. `cropThreshold`, which you can not change because of the other bug (correct me if I'm wrong).

**Comment by janM37** [comment]
@pawelfus Wow, I did not notice the difference was so huge. This explains a lot.
Indeed, I can't alter `cropThreshold` here for this reason, but also because I need to be able to load all the points for any not-displayed layer (I have a searchbar where you can provide bar labels, and on click it will drill to the corresponding bar and center the graph on it).

I can imagine two solutions :
- For those large layers, I introduce an intermediate layer dividing those bars into subgroups. Thus, I would need to drill once more but the rendering time would be greatly improved. Not really elegant but I guess it could work ;
- I change the graph type for these large layers for one supporting better this kind of labeled data. If you have any suggestion for that, please let me know ! 

In any case, thanks for the help, really appreciate it

**Comment by pawelfus** [comment]
Thanks for the explanation. How about a bit different solution? Instead of finding corresponding dataLabel, search for a specific category? I'm not sure about your data, so this may be out of the question.

Or something completely different: if search can be done on all not displayed layers, then when you programatically drill down and zoom in, highlight point by calling [`point.select(true)`](https://api.highcharts.com/class-reference/Highcharts.Point#select)?  You can configure selected/highlighted bar using [`series.bar.states.select`](https://api.highcharts.com/highcharts/series.bar.states.select) options.

**Comment by janM37** [comment]
Not quite sure about first option since each point = one category, so I would assume it would lead to the same result.

I'll try out the second option, I'll come back next week with my observations !

**Comment by janM37** [comment]
Hi @pawelfus !

I had time to play a bit with `point.select`. This is indeed a nice way to highlight a point ! I would however note that if the `y` of the selected bar is equal to zero, then nothing gets highlighted. In my case, it's pretty common since bars can represent absence/presence of a category. I added a time-limited blinking rectangle as well at the expected location.
I'm however not quite sure how this could boost rendering performance ?

I added extra subLayers in order to split layers with many bars. Although this alters a bit the data structure, this is not really an issue in the context of the searchbar. As expected, the perfomance was nicely improved.

Thanks again !

**Comment by pawelfus** [comment]
Great to hear that! 

You can also use other features to highlight zero-value points:

- set [`series.minPointLength`](https://api.highcharts.com/highcharts/series.bar.minPointLength) - now even points with y=0 will be rendered. Chart is no longer accurate (e.g. very small bars vs y=0 bars are not distinguishable), but you get point's graphic
- use [`chart.tooltip.refresh(chart.series[index].points[index])`](https://api.highcharts.com/class-reference/Highcharts.Tooltip#refresh) to show tooltip next to the points' graphic/category (won't work for null points)
 

Regarding your solution - I don't know how do you add this rectangle. If this is a simple `renderer.rect()` then it's fine. Alternatively you can use [`xAxis.addPlotBand(options)`](https://api.highcharts.com/class-reference/Highcharts.Axis#addPlotBand), so the whole category will be for example under an opaque rectangle.

**Comment by janM37** [comment]
The `tooltip.refresh` did the trick nicely !
I was using `renderer.rect()`, but I find the `xAxis.addPlotBand(options)` nicer.
A small demo : https://jsfiddle.net/janM37/sm718rxu/
I like it a lot.
And again, thanks for the support !

**Comment by pawelfus** [comment]
Great! My pleasure :)

Thanks for sharing demo, if you don't mind I suggest some performance improvements to consider:

1. 
```js
                x.xAxis[0].update({ min: newMin});
                x.xAxis[0].update({ max: newMax });
```

Can be replaced with `x.xAxis[0].update({ min: newMin, max: newMax });`. Every update recreates the xAxis, but you can combine all options in one config. Actually, I recommend to use even faster `x.xAxis[0].setExtremes(newMin, newMax);` - this simply changes the extremes as you need, without recreating the xAxis.

2. Don't forget to remove `plotBandH` plotBand when user searches a new phrase. I'm not sure how fast your users can be, but you can accidentally run two `setInterval`'s at the same time, trying to add/remove the same plotBand. Which leads me to third suggestion:

3. You can use CSS animation for the fill color instead setTimeout/setInterval and add/remove, for example: https://jsfiddle.net/BlackLabel/htpf4jc0/ ( I hope you don't need to supported IE6-9). It's not like you will get huge performance boost, but you decrease DOM operations (add/remove plotband's rect) which is always nice.

**Comment by janM37** [comment]
Thanks for the tips ! I observed a notable performance improvement with `x.xAxis[0].setExtremes(newMin, newMax)`. I'll go for the CSS animation as well.

Is it possible to use `x.xAxis[0].setExtremes(newMin, newMax)` when a drilldown event is triggered? In this example : https://jsfiddle.net/janM37/8c7eu9q5/
The rescaling is done correctly if I use `x.xAxis[0].update({ min: newMin, max: newMax })`. However, with `setExtremes`, it happens on the layer from which you trigger the drilldown (you can see the effect by drilling up).
I'm not quite sure why `setExtremes` is triggered before the drill, and `x.xAxis[0].update` after. Is there a way to use `setExtremes` in a similar way as `x.xAxis[0].update`, or there is no significant performance improvement justifying this ?

**Comment by pawelfus** [comment]
Using `update({ min, max })` you set initial/hard extremes. In `setExtremes(min, max)` you only change the current extremes - it's no different from user scrolling/panning action. Let's check this example: https://jsfiddle.net/BlackLabel/bxqkn5a0/ with steps:
- click on `a` point
- scroll down to the see `3` category
- click on back to root
You see extremes has changed (scrollbar's thumb is placed at the top of the track). On a drill up/down action, extremes that were set via `setExtremes()` are back to `xAxis.min` and `xAxis.max` options. I guess you need to stick to `axis.update()`..

**Comment by janM37** [comment]
OK, that's good to know !

My point was that I did not want to update the axis (or update it faster) when drilling down using the searchbar. For example, if you search from layer 1 a label located in layer 3 (2 drilldowns), layer 2 will not be displayed, thus you don't have to rescale the axis of layer 2. 
On the other side, I still want to update axis when the drilldown is activated by bar click (eg in the above fiddle, if layer 2 has only 3 bars but `xMaxGraph = 8`, you get empty zones on the graph).

I just realized the event `drilldown` has a property `e.originalEvent` equal to `undefined` if you activate a drill with `x.series[0].data[n].doDrilldown()` ; and equal to a `click` object when a user clicks on a bar.

Knowing this, I can decide if I want to update the axis while drilling down (or up). During a search, all non-displayed layers are not rescaled.

Not sure if this is really comprehensible ! But for searching a label at layer 6 with 800 bars, speed improvement is around `3s`. Great !

**Comment by KacperMadej** [comment]
@janM37 

I'm unable to find `doDrillup` in the drilldown module code. Could you provide more info for it?

In general, if you want to have a clear distinction between automated on click event run and a custom function call then you could set a custom property before the call.

**Comment by janM37** [comment]
I meant `chart.drillUp()`, sorry for the confusion.

Indeed, figured that out a bit later as well. Thanks for the support !
