### ISSUE TITLE
Pie chart taking more load time than line chart in highchart

### ISSUE THREAD

**Issue by hakkim** [highcharts/highcharts#11447]
#### Expected behaviour
Pie Chart Must load with same speed of line chart

#### Actual behaviour
Pie chart takes more time than line chart. In this example, the line chart loads in less than 1 second. But Pie chart takes around 4 seconds to load the chart.

#### Live demo with steps to reproduce
https://jsfiddle.net/hakkim/682oh5e3/8/

#### Product version
 Highcharts JS v7.1.2

#### Affected browser(s)
Google Chrome

**Comment by pawelfus** [comment]
Hi @hakkim 

Thanks for reporting the issue - this is expected behaviour, since default configs for pie charts and line series are different. To get similar results:

- disable animation `series.animation = false`
- disable dataLabels `series.dataLabels.enabled = false`

Demo: https://jsfiddle.net/BlackLabel/qspvf3zt/

Note that the difference always be there: in line series for crowded points we may disable markers. In pie series, slices are always rendered, so adding 2,5k elements requires some time. 

Anyway, rendering 2,5k points in a pie chart is bad idea. Please choose different series type :)
