### ISSUE TITLE
Unable to change color in dependency wheel "segments"

### ISSUE THREAD

**Issue by inad9300** [highcharts/highcharts#11481]
#### Expected behaviour

I am unsure whether this is a bug report, a question, or a feature request, but I seem unable to change the color of the "segments" (the things connected by lines) in dependency wheel charts.

By setting the `color` property of each point, the lines are properly colored. However, the segments are still colored using the default Highcharts colors (despite all lines coming out of any segment have the same color).

When trying to use the `color` property in the `nodes` array ([docs](https://api.highcharts.com/highcharts/series.dependencywheel.nodes)), it seems to be ignored ([fiddle](https://jsfiddle.net/jw8Lc1km/)). I would like to understand if I am doing something wrong. Nevertheless, this solution is less ideal, as it is not as straightforward to generate the chart's configuration in a data-driven way. Rather, you have to code some logic specific for this type of chart if you want to avoid hard-coding the colors for all possible points, which is something that Highcharts could automatically do.

#### Actual behaviour

Segments are colored according to Highcharts' default colors.

#### Product version

Highcharts 7.1.2.

#### Affected browser(s)

At least Chrome.

**Comment by pawelfus** [comment]
Hi @inad9300 

Thanks for reporting the issue. This is caused by including CSS files in the non-styled mode. Remove styles or set `chart.styledMode=true` and use CSS to change colors:

- removed styles: https://jsfiddle.net/BlackLabel/9d67crte/
- styled mode: https://jsfiddle.net/BlackLabel/e06f7hmc/

More about styled mode can be found in our docs: https://www.highcharts.com/docs/chart-design-and-style/style-by-css

**Comment by inad9300** [comment]
Thanks for your reply. Regarding the other part of my comment, I ended up doing the following, which I would you to consider (not exactly, of course, but as inspiration) for Highcharts:

```js
if (seriesType === 'dependencywheel' && !series.nodes) {
    const nodes = {};
    series.data.forEach(p => nodes[p.from] = p.color);
    series.nodes = Object.keys(nodes).map(id => ({id, color: nodes[id]}));
}
```

**Comment by pawelfus** [comment]
Sorry, I missed the second part of the question! 

By default, in dependencywheel, [`series.colorByPoint`](https://api.highcharts.com/highcharts/series.dependencywheel.colorByPoint) is set to true, so colors are taken from `series.colors`/`chart.colors`. We do something similar, but actually the opposite: links are colored according to nodes' color.

https://github.com/highcharts/highcharts/blob/91df181bb32a3d8235d9e83ea527893d55d9df17/js/mixins/nodes.js#L129-L130 
(in the above: point = link)

In your solution, when multiple links refer to the same node, the last color will be picked, for example:
```js
let series = {data: [{ from: 'A', to: 'B', color: 'red'}, { from: 'A', to: 'C', color: 'blue' }] };
    
const nodes = {};
series.data.forEach(p => nodes[p.from] = p.color);
series.nodes = Object.keys(nodes).map(id => ({id, color: nodes[id]}));

console.log(series.nodes[0].color); // blue;
```

I think it's better to color all outgoing links with the same color as a node, instead of coloring a node according to the last outgoing link, while all other may not match either `from` or `to` nodes.

Note: I'm only talking about default behaviour here, every chart can be customized as you did.

**Comment by inad9300** [comment]
I understand the you suggest can seem more natural. Picking the last outgoing link was only an implementation detail, though; the idea is to take any, assuming all links coming off the same node have the same color.

As I said, my motivation is data-drivenness: this way allows to have a fixed configuration (possibly stored in a database) and dynamic data; as opposed to fixed configuration, dynamic configuration and dynamic data. After all, the nodes depend on the data, so hard-coding their values makes the configuration more fragile, and it is not what users should be supposed to do. That's why I think my proposal is a better default behaviour, and something that makes sense to include in Highcharts.

Anyway, it's just an idea. I am happy with having to code some custom configuration.

**Comment by pawelfus** [comment]
Let me reopen this issue for further discussion and wait for more feedback.

@TorsteinHonsi, @jon-a-nygaard, @oysteinmoseng - any thoughts?
