### ISSUE TITLE
Scientific notation to decimal notation not working for e-7

### ISSUE THREAD

**Issue by hakkim** [highcharts/highcharts#11499]
#### Expected behaviour
The Scientific Notation has to convert to decimal notation for e-7. It is working fine for e-6

#### Actual behaviour
The Y axis labels and tooltips showing scientifici notation only

#### Live demo with steps to reproduce
https://jsfiddle.net/hakkim/s9tow54y/2/

#### Product version
Highcharts JS v7.1.2

#### Affected browser(s)
Google Chrome

**Comment by pawelfus** [comment]
Hi @hakkim 

That is expected behaviour: we simply display value of the tick that is stored in js. If you prefer other formats, please use [`yAxis.labels.formatter`](https://api.highcharts.com/highcharts/yAxis.labels.formatter), for example using [top answer from SO](https://stackoverflow.com/questions/1685680/how-to-avoid-scientific-notation-for-large-numbers-in-javascript) you can get this output: https://jsfiddle.net/BlackLabel/xud3n8t7/
