### ISSUE TITLE
Multi series export is misaligned

### ISSUE THREAD

**Issue by hakkim** [highcharts/highcharts#11509]
#### Expected behaviour
Multi series highchart with yAxis top value is misaligned while exporting to png.Exporting to the PNG must be the same as seen in the graph.

#### Actual behaviour
PNG exported is misaligned.

#### Live demo with steps to reproduce
https://jsfiddle.net/hakkim/o8s5wz3x/24/

#### Product version
Highcharts JS v7.1.2

#### Affected browser(s)
Google Chrome

**Comment by sebastianbochan** [comment]
Hi @hakkim,
Thank you for reporting about the problem.

**Comment by ppotaczek** [comment]
This issue is caused by a lack of correct container `height` style:

https://github.com/highcharts/highcharts/blob/5328469e4483436c5e38634717d66271f70a76dc/js/modules/exporting.src.js#L1156-L1165


**To workaround:**

- set `height` as a chart property:

```
    chart: {
        ...,
        height: 600
    },
```

or:

- set `height` style directly on the container:

```    
document.getElementById('container').style.height = '600px';
```

**Live demo:** https://jsfiddle.net/BlackLabel/ot2fa94v/

**Comment by TorsteinHonsi** [comment]
It's not a bug as far as I can see. The axes are positioned according to the configuration.

If the varying height is intentional, it is generally better to use percentages for the axis layout: https://jsfiddle.net/highcharts/cans8y7u/2/
