### ISSUE TITLE
DOM elements and Objects created by Highstock are not properly Garbage Collected

### ISSUE THREAD

**Issue by AntonyJos** [highcharts/highcharts#11557]
#### Expected behaviour
All the DOM elements and the Objects/Properties created by Highstock are to be removed once the destroy method is invoked.
The memory should be retained back to the state before the chart was created.

#### Actual behaviour
Some DOM elements and Objects are still found to be attached to the window

#### Live demo with steps to reproduce

1. Hit the url -> https://jsfiddle.net/zdguftne/3/
2. Navigate to the chrome developer tools, move to memory tab
3. Select the instance fiddle.jshell.net
4. Take a heap snapshot **before creation of the chart**
5. Click on "_Create Chart_" Button
6. Take a heap snapshot **After creation of the chart** after performing manual GC
7. Click on "_Destroy Chart_" Button
8. Take a heap snapshot **After Destroying the chart** after performing manual GC
9. Also, observe the timeline for the memory Allocation
10. Compare the heap snapshots taken at step 4 and step 8 

Hereby Attaching the snapshots in the zip file 
Attached files
_1.Before Creating Chart
2.After creating Chart
3.After destrying chart
4.Memory TimeLine Profiling_

[Memory Snapshots.zip](https://github.com/highcharts/highcharts/files/3466496/Memory.Snapshots.zip)

Please find the visual comparison of snapshots 1(Before Creating Chart) and 3(After destrying chart)

![Heap Snapshot Comparisons](https://user-images.githubusercontent.com/42953694/62448840-5a4ce400-b786-11e9-88e4-fa81547592cf.PNG)

Also , please have a look at the violet bar , which seems to be the memory allocation which was never freed in the below memory timeline snapshot 

![Timeline Snapshot](https://user-images.githubusercontent.com/42953694/62448926-8c5e4600-b786-11e9-9bb1-725df2555fe8.PNG)

**_Observation_**
The comparison should yield a delta of 0 which is not the case

**_Major Fault_**
The instances of the Objects or the DOM elements seems to be growing when instantiating and destroying the chart within the same container
For example, if the chart is being created in one of the pages of an application and the user keeps on navigating through the pages
Even though chart.destroy is being called, these instances seems to be increasing

#### Product version

Highstock - 7.1.2

#### Affected browser(s)

Only tested out in Google Chrome - ^74.0.x

**Comment by pawelfus** [comment]
Thanks for reporting the issue @AntonyJos 

I'm not sure if this is something in Highcharts. It seems that's Chrome caching. Let's check a simple example: https://jsfiddle.net/BlackLabel/8hdy9s42/ - in this demo we simply create `<svg><defs></defs><svg>` - after removing this element, I can still see `SVGDefsElement x3` in the memory heap snapshot.

I think it's kind of cache, because it's stored in `slow_template_instantiations_cache` in system / NativeContext (first object refers to GC and third object is similar to the highlighted one, which always one way or another refers to this `..template..`):

![Screen Shot 2019-08-05 at 16 51 10](https://user-images.githubusercontent.com/1453926/62473556-4498e800-b7a1-11e9-88c5-2f3ae2662038.png)

Increasing number of chart's created&destroy gives interesting results:
- create and destroy chart x5
- wait a few seconds, take a snapshot
- create and destroy chart x5
- wait a few seconds, take a snapshot
- wait a minute, take a snapshot
- wait five minutes, take a snapshot

Every next snapshot shows me fewer and fewer objects, decreasing the memory without any action inside the iframe.
