### ISSUE TITLE
Reflow of the chart inside table

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#1157]
Example: http://jsfiddle.net/FzXEM/ 

When resizing iframe/window chart reflow fine when makes it bigger, but doesn't reflow when makes it smaller. 

Possible workaround: use setSize() method: http://jsfiddle.net/FzXEM/1/

**Comment by onemenny** [comment]
this is very frustrating - i cannot seem to find a solution either: http://forum.highcharts.com/highcharts-usage/chart-not-responsive-in-display-table-t32424/

it should be handled automatically by highcharts and not by external JS. the proposed solution is only half way there, cause you need to consider other DOM elements along the way with their padding and margin... 

this should be fixed by highcharts and not by the users

**Comment by highslide-software** [comment]
The problem is that the chart is an SVG image and behaves like any other image inside a table cell. While expanding the table, it works well because the table cell actually expands to, so our logic picks it up and upsizes the chart image. But when contracting the table, the image sits there and blocks the cell, so it won't get smaller than the image. So our model of adapting the SVG size to the table cell makes no difference.

**Comment by onemenny** [comment]
Thanks @highslide-software 
Your answer, as usual, is something i can live with understanding the cause. very different from the "throw away" i got in your forums. 

at the end i managed to mimick the table behavior using flex and min-height styles...

**Comment by dluk** [comment]
solution for this was adding this to css:
`.highcharts-container, .highcharts-container svg 
{
    width: 100% !important;
}`
see the example: http://jsfiddle.net/FzXEM/8/

**Comment by highslide-software** [comment]
Thanks for the fix, that's a good one!

**Comment by nawlbergs** [comment]
@dluk This mostly works... but I am still having issues when I have multiple columns of charts in a table.  Id post a fiddle but my code is thiiiiick.
