### ISSUE TITLE
Unable to get property 'chart' of undefined or null reference

### ISSUE THREAD

**Issue by Mazas17** [highcharts/highcharts#11609]
#### Expected behaviour
No errors should be printed

#### Actual behaviour
Error is printed to console: "Unable to get property 'chart' of undefined or null reference"

#### Live demo with steps to reproduce
https://jsfiddle.net/95jbek74/2/

Error is printed when resizing window.

#### Product version
Highcharts v7.1.2

#### Affected browser(s)
Microsoft Edge 42.17134.1.0, Internet Explorer 11.885.17134.0

**Comment by KacperMadej** [comment]
Hi @Mazas17 

Thank you for contacting us about the problem.

This is caused by a general browser feature.
There is a difference between browsers when it comes to removing events listeners while running the event. IE and Edge will run it anyway and Chrome will remove it, so it will not run it.

Here's a simple demo: 
https://jsfiddle.net/BlackLabel/2hevysza/1/

Steps:
1. click in the result window
2. in browser console Chrome prints 1,2 on every click, while IE and Edge are printing 1,2,3 first time and 1,2 every other click

Destroying a chart is not advised as chart.update should allow any update you need.
To resolve this you could use chart.update or add the event listener after the chart is created.
This might be hard since a new chart is created in the event, but you could remove your event listener after a new chart is created and add it again, so it will always be added after the chart is created.

Could this be seen as a bug in Highcharts @pawelfus ? A simple check before calling chart.reflow to ensure that the chart was not destroyed should be enough.

**Comment by pawelfus** [comment]
@TorsteinHonsi - up to you, I think a simple additional condition would be a good idea. Of course, we should report this to MS devs anyway, maybe wait with a fix until we get some more details from them.

**Comment by KacperMadej** [comment]
It's an already reported issue in Edge: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10124881/

**Comment by TorsteinHonsi** [comment]
I agree, a simple check before calling `chart.reflow` should be added. We have similar guards other places where we risk properties being destroyed in custom events.

**Comment by iniatse** [comment]
Has this been resolved? I do not want to call update...

**Comment by sebastianbochan** [comment]
Hi @iniatse,
The issue is about error in the console, but your issue seems to be not related with that. Could you elaborate your case?

**Comment by iniatse** [comment]
I already solved it. Thx.
