### ISSUE TITLE
Tooltips not showing on scatter plot running with boost module

### ISSUE THREAD

**Issue by yansen-chandra** [highcharts/highcharts#11608]
#### Expected behaviour
When hovering mouse to the plot point should show tooltips

#### Actual behaviour
Hovering mouse to data point didnt show anything

#### Live demo with steps to reproduce
https://jsfiddle.net/p13mcLqv/1/

#### Product version
Highstock 7.1.2

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Thank you for reporting the issue @yansen-chandra 

**Simplified demo:**
https://jsfiddle.net/BlackLabel/cwf05jnd/
It seems that `{x, y}` points + axes extremes cause this issue

**Workaround:**
Use `point = [x, y]` instead of `point = {x, y}`
Demo: https://jsfiddle.net/BlackLabel/cwf05jnd/1/

Alternative workaround: increase the axes extremes

**Comment by yansen-chandra** [comment]
Hi, 
 What do you mean increase extreme, I increased to 200 for x and y and doesnt seems to work 

https://jsfiddle.net/dabpsLfx/

**Comment by pawelfus** [comment]
Hi @yansen-chandra 

Good point, it seems that setting any extremes cause the issue. Updated my previous comment, thanks!

> Is this mean that its expected behavior that when boost module kicked in the scatter chart with object plot point wont be able to display tooltip?

No, this is not an expected behaviour - issue is marked as `Type: Bug`.

**Comment by yansen-chandra** [comment]
@pawelfus thanks for the fix
May I know when will this fix be live, or any way to apply myself?

**Comment by pawelfus** [comment]
v7.1.3 was just released, we don't ETA for the next release. You can find corresponding lines in your `boost.src.js` file and modify them as in the commit.
