### ISSUE TITLE
HighStock Yaxis on opposite side miss align when left axis is not visible

### ISSUE THREAD

**Issue by hakkim** [highcharts/highcharts#11612]
Left side Yaxis is invisible on load. And my right Y-axis is overlapping with the graph. If I change the left Y-axis to visible: true, then the alignment is correct. And this issue is not there in the 'highcharts'. It happens only with 'StockChart'

#### Expected behaviour
Yaxis must be aligned on both the left side and right side. 

#### Actual behaviour
Right Yaxis is overlapping with the graph

#### Live demo with steps to reproduce
https://jsfiddle.net/hakkim/uadxth0e/11/

#### Product version
 Highcharts JS v7.1.2

#### Affected browser(s)
Google Chrome

**Comment by sebastianbochan** [comment]
Hi @hakkim,
Thank you for reporting about the bug.

**Additional info**
Lets compare two examples:
- https://jsfiddle.net/BlackLabel/z2p9kyu3/
- https://jsfiddle.net/BlackLabel/z2p9kyu3/1/ and click on series1's legend item.

The chart should be the same in both scenarios, but its not.

**Comment by hakkim** [comment]
Any updates?

**Comment by pawelfus** [comment]
This is expected behaviour: first visible yAxis in Highstock in every pane has different default options than all other. The first yAxes per pane are moved into the plotting area, while all others are rendered outside the plotting area.

You can simply change that by setting different defaults for yAxes: 

- all yAxes outside the plotting area: https://jsfiddle.net/BlackLabel/379ko56z/
- first yAxis inside, all others outside: https://jsfiddle.net/BlackLabel/z91ajdcL/

All you need to set is `yAxis.labels.x` and `yAxis.labels.align` like in my demos above.
