### ISSUE TITLE
Change mapData and data dinamically

### ISSUE THREAD

**Issue by ajmonfue** [highcharts/highcharts#11636]
#### Expected behaviour
Change `mapData` and `data` with the `update` method of the series.

#### Actual behaviour
The `mapData` doesn't change unless `hasDerivedData` is set to `true`.

#### Live demo with steps to reproduce
[Demo](https://jsfiddle.net/DiDream/64vdk30p/9)

#### Product version
Highmaps JS v7.1.2 (2019-06-03)

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Hi @DiDream 

Thank you for reporting about the problem.

If you want to use dynamic data for maps then the chart will work correctly if you will be using only data for series. You could create series data out of geojson using `Highcharts.geojson()` function.

Another problem in your demo is caused by using two extremely different maps and scales are off making new map invisible.

The workaround with `hasDerivedData` seems to be working well for this case, so thank you for sharing this solution.
