### ISSUE TITLE
Tilemap with very small values will render a broken legend

### ISSUE THREAD

**Issue by itsalwaysme** [highcharts/highcharts#11644]
EDIT: See https://github.com/highcharts/highcharts/issues/11644#issuecomment-519640663 for fix.

#### Expected behaviour

The legend should render like this https://jsfiddle.net/c5eL3x1a/

#### Actual behaviour

Legend is rendered weirdly. It's in reverse, with 1 label. Like this https://jsfiddle.net/5zocxt3v/5/

If you multiplied all the values by 100 the issue goes away so it may be related to how Highcharts handles decimal numbers?

#### Live demo with steps to reproduce

Example: https://jsfiddle.net/5zocxt3v/5/

What it should look like (Switched to older version): https://jsfiddle.net/c5eL3x1a/

#### Product version

Affects versions v7.0.2 to v7.1.2 (current).
Versions v7.0.1 and below appear to work correctly.

#### Affected browser(s)

Tested on Chrome 75.

**Comment by itsalwaysme** [comment]
So I've found that if you:

import highcharts instead of highmaps like this https://jsfiddle.net/753r90os/ and it will work with the latest version.

I've also noticed that if you use an older version like 6.1.1 and import tilemap.js before heatmap.js you will get the same bug (The newer versions will error out if you try this).

This leads me to the theory that highmaps internally is adding the Tilemap incorrectly before the heatmap.

**Comment by sebastianbochan** [comment]
Hi @itsalwaysme,
Thank you for reporting about the problem.

FYI @jon-a-nygaard

**Comment by jon-a-nygaard** [comment]
The issue does not appear when using a different series type, e.g Heatmap https://jsfiddle.net/jon_a_nygaard/25md6kqf/ 

So the issue is likely located in the Tilemap series, and not in the colorAxis/colorLegend.
Any thoughts on where it would be best to start looking @oysteinmoseng?

**Comment by pawelfus** [comment]
Bisected to commit c5049b052a

**Comment by pawelfus** [comment]
*Internal note:*
It's caused by `addEvent()` logic. `addEvent` adds an event to all Axes (Axis and ColorAxis classes) and Tilemap changes available space for Axes for `series.padding`. It's necessary only for xAxis/yAxis.

In previous versions `wrap()` used to work fine (if correct order of files was used) because we first created ColorAxis then Tilemap wrapped `setAxisTranslation()` so wrap was added only to Axis, not ColorAxis. If we switch order of files and first add `wrap()` then create ColorAxis, then we can see bug in old versions too.
