### ISSUE TITLE
Scrollable plot area - scrollbar overlaps at right side

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#11671]
#### Expected behaviour
Plot area gives way to scrollbars

#### Actual behaviour
It overlaps on the right, default spacingRight is 10px

#### Live demo with steps to reproduce
https://jsfiddle.net/highcharts/qsomL4kz/2/

#### Product version
v7.1.2

**Comment by AntonyJos** [comment]
@TorsteinHonsi , Is someone seeing to this?

**Comment by TorsteinHonsi** [comment]
Well, there is a simple workaround, to set `chart.spacingRight`: https://jsfiddle.net/highcharts/qsomL4kz/14/

**Comment by AntonyJos** [comment]
@TorsteinHonsi ,

Thanks for the workaround and prompt response.
I was already aware of this work around.

The issue lies since i have different `.highcharts-plot-background` and `.highcharts-background`
So the spacing we provide could be evidently seen.
Additionally, scrollbars also to be styled as per design, something like the below image

![highchart_margin](https://user-images.githubusercontent.com/42953694/68851729-6ee13680-06fc-11ea-8652-c8d7fdcb932b.PNG)

It would look awkward with the spacing work-around provided.

Also, below observation were made as i gave border to the highchart-container
1. The Navigator does not take in the color provided to the  highcharts-background
2. There seems to be some space in the top of the chart container wherein highcharts-background does not have an effect. (may be due to incorrect clipping co-ordinates)

https://jsfiddle.net/bfuv7say/2/

**Comment by pawelfus** [comment]
I believe `spacingRight: 12` looks nice: https://jsfiddle.net/BlackLabel/c6pj4aoz/1/ (default value for `spacingRight` equals 10px)

Regarding other points: it's not navigator, or clip, it's `highcharts-scrollable-mask`: https://jsfiddle.net/BlackLabel/c6pj4aoz/4/ - which can be set in styled mode:
```
.highcharts-scrollable-mask {
  fill: yellow;
}
```

**Comment by AntonyJos** [comment]
Thanks Pawel...This really does the trick
