### ISSUE TITLE
Solidgauge - marker symbol in legend is not working

### ISSUE THREAD

**Issue by tanmayshah95** [highcharts/highcharts#11709]
#### Expected behaviour
Marker symbol should be seen in legend if provided in series option for Solid gauge chart.
I have found a link with similar question on stack overflow and it is dated of year 2017, so it seems this property was working before.
Stackoverflow url: https://stackoverflow.com/questions/43081388/highcharts-solid-gauge-legend-symbol

#### Actual behaviour
Filled circle is seen as series symbol in legend even if marker symbol is provided.

#### Live demo with steps to reproduce
https://jsfiddle.net/6s0hjfc8/

#### Product version
Latest highcharts version 7.1.2

#### Affected browser(s)
All browsers

**Comment by pawelfus** [comment]
Hi @tanmayshah95 

Thanks for reporting. This is expected behaviour, see #10232 - as you noticed, there's no marker in solid gauge series, so rendering this marker in legend was wrong.

Don't worry, it is still possible to create a marker in legend item using separate series. Then you can use [`linkedTo`](https://api.highcharts.com/highcharts/series.line.linkedTo) option to link gauge series to this one legend item, take a look: https://jsfiddle.net/BlackLabel/rwf73udn/
