### ISSUE TITLE
highstock annotation settings is missing with the latest release

### ISSUE THREAD

**Issue by wy1713** [highcharts/highcharts#11716]
This happens on both circle and rectangle annotation
![image](https://user-images.githubusercontent.com/36648934/63299072-cdc41a80-c289-11e9-9c9e-d356cb74bfc1.png)

**Comment by pawelfus** [comment]
Thank you for reporting the issue @wy1713  

It's a regression since v7.1.1, v7.1.0 works fine: https://jsfiddle.net/BlackLabel/tqh9Lv0m/

*Internal note:*
Not able to bisect, some of the builds are broken. From the changelog, we have only one major change in annotations-advanced: 8b722f55a88fc0c346eeb951b1da6333ae737b33
