### ISSUE TITLE
Regression: negativeColor transfers to drilldown

### ISSUE THREAD

**Issue by JannesMeyer** [highcharts/highcharts#11728]
It seems that bug #4402 is back.

#### Expected behaviour
`plotOptions.series.negativeColor` only applies to negative bars

#### Actual behaviour
Clicking on a negative bar transfers its negativeColor to all drilldown bars (even positive ones)

#### Live demo with steps to reproduce
https://jsfiddle.net/o3gb9Lsd/

1. Click the red bar
2. You will see two red bars in the drilldown even though the positive one should be blue (default color)

#### Product version
Highcharts v7.1.3

**Comment by pawelfus** [comment]
Thanks for reporting! I'm not sure if this is a bug. By default, color of the drilldown series is always taken from the point that was clicked. For example here: https://www.highcharts.com/demo/column-drilldown - whichever point you click, drilldown series will automatically use that point's color. 

Of course, this is only the default behaviour - you can set specific color for each drilldown series and this will be prioritized, for example: http://jsfiddle.net/BlackLabel/qgvte7x3/2/

**Comment by JannesMeyer** [comment]
Thanks for your answer!

I would say that it's a bug because the behaviour is inconsistent. It doesn't happen when you drilldown on the positive bar:
![image](https://user-images.githubusercontent.com/704336/63418588-a5602b80-c403-11e9-81ab-ec9eee655669.png)
https://jsfiddle.net/o3gb9Lsd/

As you can see not all bars are blue even though a blue bar was drilled down. It doesn't seem to respect `plotOptions.series.color` in the same way as it respects `plotOptions.series.negativeColor`.

Furthermore, issue #4402 was deemed to be a bug in 2015. Wasn't that the same issue?

**Comment by pawelfus** [comment]
@JannesMeyer - #4402 was never acknowledged as a bug, I don't know exactly why was closed (I see no difference in behaviour between v4.1.8 and v4.1.7). @KacperMadej  - do you have some more details?

The coloring is consistent, let's use orange for the drilldown series' negative color: https://jsfiddle.net/BlackLabel/4n5vbaqs/ - you can see that `negativeColor` has the highest priority in this case. In other words, we have scenarios:

1.
- click on red column
- all drilldown points are red: first one because color is taken from the parent point, second point is red because of `negativeColor`

2.
- click on blue column
- first point is blue, because color is taken from parent point, secons point is red because of `negativeColor`

**Comment by JannesMeyer** [comment]
I'm a bit confused with that explanation.

>  all drilldown points are red: first one because color is taken from the parent point, second point is red because of negativeColor

That's not what I see. I see the first point red and the second point orange.

> first point is blue, because color is taken from parent point, second point is red because of negativeColor

I see the first point blue and the second point orange.

Apart from the color differences your general point seems to be that it's possible to override `negativeColor` in each series. Which is actually the workaround that I am currently using to achieve consistent coloring.

However this issue is more about `negativeColor` not working as expected when defined in `plotOptions.series`.

**Comment by JannesMeyer** [comment]
I have made another fiddle: https://jsfiddle.net/pbnao398/

Could you explain why the second point is red in that drilldown? (According to your logic it should be blue because a drilldown always takes the color from it's parent point)

**Comment by pawelfus** [comment]
Sorry for the confusion I made! The scenarios refer to your original demo, not the orange-one. Accidentally I made this more complicated than it is. Let me clarify things:

The demo with orange color suppose to show that `negativeColor` is always applied as the last one.

To answer this:
> I have made another fiddle: https://jsfiddle.net/pbnao398/
>
> Could you explain why the second point is red in that drilldown? (According to your logic it should be blue because a drilldown always takes the color from it's parent point)

This is scenario 2):

> 2.
> - click on blue column
> - first point is blue, because color is taken from parent point, second point is red because of negativeColor

Let me know if something is not clear

**Comment by KacperMadej** [comment]
At this point, my comment might be pointless. #4402 was fixed at the time I have tested it using Highcharts version 4.1.8, so it was fixed sometime before 4.1.8. I didn't investigate what exact version it was.

**Comment by JannesMeyer** [comment]
Thanks @pawelfus, I understand why this happens now.

I don't find it very intuitive, but if it's by design then it's not a bug.

Is there a reason why you are applying the global negativeColor to drilldown series at all? (i.e. why doesn't drilldown override the negativeColor as well as the normal color?) I think that's the main source of confusion here.

**Comment by pawelfus** [comment]
> I don't find it very intuitive, but if it's by design then it's not a bug.

I understand, that's why I don't want to close this ticket, but keep this open. I assume that #4402 was reporting exactly the same issue (I see no difference between v4.1.8 and current behaviour). If we get more reports like this one, we will try to find a way to simplify it.

> Is there a reason why Highcharts is applying the plotOptions' negativeColor to drilldown series at all? (i.e. why doesn't a drilldown operation override the negativeColor like it overrides the normal color?)

I'm afraid I might misunderstand your question here, but let me try to answer: `plotOptions.series` is a shortcut to set options for all series on a chart. Drilldown series is still a series. All options (e.g. `plotOptions.dataLabels.enabled`) works exactly the same way (demo: https://jsfiddle.net/BlackLabel/4n5vbaqs/1/). The only option for drilldown series that is inherited from the clicked point is it's color (instead of picking next color from `chart.colors` array).
