### ISSUE TITLE
SVG renderer - width/height image parameters issue

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#11756]
In the [documentation](https://api.highcharts.com/class-reference/Highcharts.SVGRenderer#image), we can find information saying that:
> The image width. If omitted, it defaults to the image file width.
> The image height. If omitted it defaults to the image file height.

Meanwhile omitting these parameters is impossible. It is a documentation mistake or this functionality fails? 

#### Live demo with steps to reproduce

[Demo](http://jsfiddle.net/BlackLabel/w7h9t52k/) where I tried to set on of those parameters to: undefined, '' - empty string, or even null.  

#### Product version

Highcharts JS v7.1.3 (2019-08-14)

#### Affected browser(s)

All

**Comment by pawelfus** [comment]
FYI @TorsteinHonsi

**Comment by raf18seb** [comment]
👍 

@TorsteinHonsi more users are asking about it.
Is it an API bug? If yes, then we could quickly improve the docs

**Comment by TorsteinHonsi** [comment]
@raf18seb I think it's a bug. It was working in v3. Not a very critical one since it has survived for so long, but it should be easy to fix by applying typechecking on x, y, width and height:

https://github.com/highcharts/highcharts/blob/883526487f394a1fa4b6b864c7d128e4ed7b0b32/ts/Core/Renderer/SVG/SVGRenderer.ts#L1270-L1278
