### ISSUE TITLE
HighChart Stacked Column - Zero serie show wrong tooltip

### ISSUE THREAD

**Issue by benda95280** [highcharts/highcharts#11795]
#### Expected behaviour
If you have 3 serie stacked, and hover a part where only one serie has data, it has to show the value of the serie hovered.

#### Actual behaviour
Hover on the serie you want where there is a 0 in a serie, it show the tooltip of another serie with 0 value.

#### Live demo with steps to reproduce
![test highchart](https://user-images.githubusercontent.com/1539408/63831681-76036e80-c96f-11e9-944f-afe569e0e3aa.png)
Script used: https://pastebin.com/dLiRHx4W
Data used: https://pastebin.com/60rE7gp7

#### Product version
7.1.3

#### Affected browser(s)
Chrome (76), Firefox (68)

**Comment by KacperMadej** [comment]
Hi @benda95280 

Thank you for reporting the problem.

I'm unable to recreate the problem (Chrome at Windows 10).
Please add the list of used Highcharts modules.

If you could create a minimal then please do.

**Comment by benda95280** [comment]
Hello, sorry for the delay.

I'm using following script:
- moment.js
- moment-timezone.js
- highcharts.js
- boost.js
- exporting.js

I'll try to reproduce on something like fiddle

**Comment by benda95280** [comment]
You will find example here :
https://jsfiddle.net/benda95280/ztvp3jru/5/

Please, take a look on the "Hover" and the  on the graphic, seems strange too.
Ex: Go in midle of Green "A faire", this is red "En retard" Showing

**Comment by KacperMadej** [comment]
When boost is enabled points that are in the same place are visible with shared tooltip because the standard tooltip will pick up only the point that is on top of other that share the same position with it. This is done for faster rendering and better performance in boost module.

You could resolve this by setting tooltip's option share to true or you could change zeros in data into nulls.

Please check if any of those solutions are working well for you.

This issue doesn't look like a bug.

**Comment by sebastianbochan** [comment]
Closed due to inactivity.
