### ISSUE TITLE
Annotation drag triggers zoom in highcharts 7.1.3

### ISSUE THREAD

**Issue by moriawan** [highcharts/highcharts#11801]
#### Expected behaviour
Annotation drag should not trigger zoom

https://jsfiddle.net/tg1wypfx/2/

#### Actual behaviour
It does

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/annotations/

#### Live demo with steps to reproduce

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/annotations/
vs
https://jsfiddle.net/tg1wypfx/2/

#### Product version
Highcharts 7.1.3

#### Affected browser(s)
Tested on
Google chrome 74.0.3729.169, 64 bit
Mozilla firefox 68.0.2 (64-bit)

**Comment by KacperMadej** [comment]
Hi @DangoDaikazoku 

Thank you for reporting the problem.

It's caused by the fix for the issue https://github.com/highcharts/highcharts/issues/10961

_Internal note:_
Regression. Worked in 7.1.2. Bisect leads to: https://github.com/highcharts/highcharts/pull/10970/commits/447623eaa83394ee7d4f20fb1317610e4d571a71
