### ISSUE TITLE
Security issues in Highstock

### ISSUE THREAD

**Issue by komalMandaliya** [highcharts/highcharts#11904]
#### Expected behaviour
possible change is to update replace with appendChild

#### Actual behaviour
Method function at line 63 in jHighstock-6.1.1/code/highstock.js gets user input for the **replace** element. This element’s value then flows through client-side code without being properly sanitized or validated and is eventually displayed to the user through function init. This may enable a DOM XSS attack.

#### Live demo with steps to reproduce
Do not have a lime demo

#### Product version
HighStock 6.1.1

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @komalMandaliya,
Thank you for reporting the bug. We advize you to use the newest 7.2.0 version. 

If problem will still be reproducible, please let us know (live demo will be really helpful).

**Comment by komalMandaliya** [comment]
Thanks @sebastianbochan .

We are licensed users of 6.1.1, would it be possible to get the fix in HighStock 6.1.1 please?

Thanks,
Komal

**Comment by KacperMadej** [comment]
@komalMandaliya 
Please check your license and in case of any doubts double-check with our Sales Department (sales@highsoft.com) about which updates are available for you. Patch for 6.1.1 was already released and it's version [6.1.2](https://www.highcharts.com/blog/changelog/#highcharts-v6.1.2). The last version of Highcharts 6 is 6.2.0 and the last version of Highcharts 6.1 is 6.1.4. Those versions might be available for you depending on your license, so please check your license and those code versions.

If the problem is visible in version 7.2.0 (current) then a fix could be added to the next release. We are releasing a new maintenance update for older main versions only in case of huge breaking errors (like badly build files that are not working at all), but this happens extremely rarely and this is not the case.

**Comment by komalMandaliya** [comment]
Hi @KacperMadej,

Thanks for the detailed reply. I checked with Sales team. I can update the 6.2 so will update and let you know of that fixes the issue.

Thanks,
Komal

**Comment by komalMandaliya** [comment]
Hi @KacperMadej ,

I only see change log here https://www.highcharts.com/blog/changelog/#highcharts-v6.2.0, could you please send me a link to download 6.2 version?

**Comment by komalMandaliya** [comment]
I found it at https://code.highcharts.com/zips/Highcharts-6.2.0.zip. Please let me know if this is not a correct source.

**Comment by pawelfus** [comment]
This is fine. You can also install Highcharts from npm package, or download files from our [cdn](http://code.highcharts.com/).

**Comment by komalMandaliya** [comment]
Thanks @pawelfus !

**Comment by pawelfus** [comment]
No problem! Should we close the ticket?

**Comment by litsoni004** [comment]
Hi @pawelfus,

I think this XSS venerability still exist in v7.2.0. please see [live demo](https://jsfiddle.net/mtp3bnou/)

![image](https://user-images.githubusercontent.com/42835967/67007986-3999f680-f106-11e9-817d-9455369b9cde.png)


![image](https://user-images.githubusercontent.com/42835967/67008050-52a2a780-f106-11e9-89fc-fc62f9eaf0e6.png)

**Comment by TorsteinHonsi** [comment]
Yes, Highcharts takes markup from the configuration and inserts it in the DOM. It is by design, so I am not sure what would be expected. Compare this with a library like jQuery, that does the same: https://jsfiddle.net/highcharts/xn0pf4L8/.

As I see it, this is not "user input", but configuration code. If you take input directly from users, for example via a form, it should be cleaned before it goes into the chart configuration.

@cvasseng Opinions?
