### ISSUE TITLE
Error: <rect> attribute height: A negative value is not valid (sankey highcharts)

### ISSUE THREAD

**Issue by dicksonarul** [highcharts/highcharts#11917]
Expected behaviour:-
Sankey Diagram for large data.

Actual behaviour:-
Sanket Diagram is not getting generated with large data in normal view but can be visible and generate properly on full screen mode.
Error: <rect> attribute height: A negative value is not valid. ("-2")
Error: <rect> attribute height: A negative value is not valid. ("-1")

 Live demo
https://jsfiddle.net/qbtc5jg0/2/

Product version
 "dependencies": {
    "@angular-devkit/build-angular": "^0.801.2",
    "@angular/animations": "8.2.1",
    "@angular/cdk": "^8.1.2",
    "@angular/common": "8.2.1",
    "@angular/compiler": "8.2.1",
    "@angular/core": "8.2.1",
    "@angular/forms": "8.2.1",
    "@angular/http": "7.0.4",
    "@angular/material": "^8.1.2",
    "@angular/platform-browser": "8.2.1",
    "@angular/platform-browser-dynamic": "8.2.1",
    "@angular/router": "8.2.1",
    "highcharts": "^7.2.0",
    "highcharts-angular": "^2.4.0",
    "highcharts-more": "^0.1.7",
  },
  "devDependencies": {
    "@angular/cli": "8.1.2",
    "@angular/compiler-cli": "8.2.1",
  }

**Comment by KacperMadej** [comment]
Hi @dicksonarul 

Thank you for reporting the problem.

As a workaround you could set the chart to be higher: https://jsfiddle.net/BlackLabel/1d028p3m/

This problem is not related to Angular nor highcharts-angular wrapper.

**Comment by dicksonarul** [comment]
Hi @KacperMadej 

Kindly let me know whether this issue/bug fixed??

Thank you.

**Comment by pawelfus** [comment]
Hi @dicksonarul 

Ticket is still open, so bug is not fixed. We haven't had enough time to prioritize this issue.

FYI @TorsteinHonsi

**Comment by Denitz** [comment]
As a temp raw solution I managed to get rid of SVG renderer error by forcing negative rect heights to any value (20 in this case):
```
                window.Highcharts.seriesTypes.sankey.prototype.translate = function () {
                    window.Highcharts.sankeyFixed.translate.call(this);

                    this.nodes.forEach((node, i) => {
                        if (node.shapeArgs.height < 1) {
                            node.shapeArgs.height = 20;
                            // Or we can completely delete the failed node:
                            //delete this.nodes[i];
                        }
                    });
                };
```

**Comment by RHCautomation** [comment]
Hi,

I think with this change (or maybe with another change since version 8) the parameter nodePadding affects not only the distance between links, but also the overall spacing. 

Due to that reason, some sankey charts have big top and bottom spacings, which waste a lot of space. This behavior was much better in version 7.

**Here is a sankey with version 7.2.0:** (don't matter about some missing values in between)
![sankey_v7](https://user-images.githubusercontent.com/32926274/79017463-aa7c1180-7b71-11ea-97b9-7d66bf778975.png)

**Here the same configuration with version 8.0.4:**
![sankey_v8](https://user-images.githubusercontent.com/32926274/79017468-ae0f9880-7b71-11ea-8579-46e5f1d81645.png)

The parameter nodePadding is set to 40 and the space between links is the same in both versions - only the top and bottom spacing is much bigger in version 8.

The red lines in the upper an lower section show the offset differences!

BR

**Comment by sebastianbochan** [comment]
Hi @RHCautomation,
Could you share a live simplified demo of your chart? It will allow us to verify your configuration and debug.

**Comment by RHCautomation** [comment]
Hi,

I created an example which is nearly identical to my application: [https://jsfiddle.net/vq5wuyd8/](https://jsfiddle.net/vq5wuyd8/)

I found out, that the problem is occured by the parameter minLinkWidth - if this value is 0, than the total chart area will be used for the sankey. The higher this value is set (normally to 1), the higher the top and bottom spacings become. 
There is also a strange behavior together width the minLinkWidth-parameter, when the height of the container is lowered (for example to 500px) - try it!

**Comment by sebastianbochan** [comment]
Thank you for details. Its a regression. I created a new ticket here: https://github.com/highcharts/highcharts/issues/13308

As I see you posted the case here: https://github.com/highcharts/highcharts/issues/7318.

Please do not duplicate of comments in multiple thread. We would like to keep consistency and avoid confusing.
