### ISSUE TITLE
yAxis.labels.enabled documentation links to xAxis.labels.enabled example

### ISSUE THREAD

**Issue by pchasco** [highcharts/highcharts#11925]
#### Expected behaviour
Should link to yAxis.labels.enabled documentation, and link text should include Y axis not X axis.

#### Actual behaviour
Link text reads "X axis labels disabled" and links to X axis example

#### Live demo with steps to reproduce
https://api.highcharts.com/highcharts/yAxis.labels.enabled

#### Product version
7.2.0-modified

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @pchasco,
Thank you for reporting. The rule of working the option is exactly the same, so we avoid duplicate of inputs.

_Internal note_
@bre1470 should we consider it as a bug ?

**Comment by bre1470** [comment]
I do not think, that each axis option needs an example for each axis. In the end they are all just an axis instance with specific settings and can be swapped. We could make the example broader, but I am not sure.

@TorsteinHonsi Maybe we should add comments to the sample to help understanding it or cover both axis? @jon-a-nygaard also suggested to describe in samples the more generic nature of options, so that beginners are not confused to apply a line option sample to a gauge series.

```
Highcharts.chart('container', {
    title: {
        text: 'X axis labels are disabled'
    },
    xAxis: { // you can replace this with yAxis or zAxis

        labels: {
            enabled: false // <-- your option
        }
    },

    series: [{
        data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
    }]
});
```

**Comment by TorsteinHonsi** [comment]
> Maybe we should add comments to the sample to help understanding it or cover both axis?

In that case we have a big task ahead of us, as this applies to all samples of extended objects. For example, many of the `yAxis` API options point to samples using the `xAxis`. So if anything, we should have a generic explanation popping up in the API that this sample is for a base object. But I fear it may be more in the way than it actually helps.
