### ISSUE TITLE
Highstock - Dynamically added and removed yAxis is unnecessarily placed in exported chart

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#11930]
#### Expected behaviour

![chart (78)](https://user-images.githubusercontent.com/22988131/64628795-5437cc00-d3f2-11e9-97cc-b84add225d3b.png)

#### Actual behaviour

![chart (77)](https://user-images.githubusercontent.com/22988131/64628768-484c0a00-d3f2-11e9-877f-ab4521a64179.png)

#### Live demo with steps to reproduce
1. Open jsfiddle: http://jsfiddle.net/BlackLabel/zuqs0bmk/
2. Export the chart

#### Product version
Highstock v7.2.0

#### Affected browser(s)
All

**Original use case:** https://github.com/highcharts/highcharts-react/issues/161

**Comment by KacperMadej** [comment]
Looks like the `remove` function in axis is not removing options for the dynamically added axis from `chart.option` due to bad `index` in the axis options.

```js
if (isArray(chart.options[key])) {
                    chart.options[key].splice(this.options.index, 1);
                }
```
The axis index in options is 2 while the `chart.options.yAxis` is an array with 2 elements (indexed from zero).

As a workaround, you could clean up the options manually after the axis has been removed.
http://jsfiddle.net/BlackLabel/zuqs0bmk/1/
