### ISSUE TITLE
Issue with pie chart rendering with 2 series and 1000 data points

### ISSUE THREAD

**Issue by gs-smuthyam** [highcharts/highcharts#11936]
#### Expected behaviour

Expecting the charts to be rendered properly

#### Actual behaviour

It doesn't plot the pie properly and also very slow

#### Live demo with steps to reproduce

https://jsfiddle.net/smuthyam/0t4Lsqnv/

#### Product version

HighCharts 7.1.2

**Comment by pawelfus** [comment]
Hi @gs-smuthyam 

Thanks for reporting the issue. Actually there's a few things you should consider:

- pie chart is misplaced because of mismatching width/height options and container's width/height: https://jsfiddle.net/BlackLabel/fnyse8hg/

- to improve performance:
  - disable [pie.animation](https://api.highcharts.com/highcharts/series.pie.animation) and [chart.animation](https://api.highcharts.com/highcharts/chart.animation)
  - disable [inactive state](https://api.highcharts.com/highcharts/series.pie.states.inactive)

Demo with all above changed: https://jsfiddle.net/BlackLabel/mev947hw/

In general, I suggest to consider different chart type, not a pie chart. Rendering 1k points in pie chart gives rather unreadable output :)
