### ISSUE TITLE
pointPlacement for columns does not work when there is one category

### ISSUE THREAD

**Issue by matt-sanders** [highcharts/highcharts#11956]
#### Expected behaviour
When creating a column chart there is the option to set a `pointPlacement` on each series to determine exactly where the point should go. This works when there are multiple categories, but it seems that when there is only one category, `pointPlacement` is ignored. The situation we have is that categories can be added dynamically, so this should work when there is one category or five.

#### Actual behaviour
`pointPlacement` is correctly used when there are multiple categories but seems to be ignored when there is only one.

#### Live demo with steps to reproduce
Example with three categories, taken from Highcharts docs: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/column-placement/ ( see also: https://www.highcharts.com/demo/column-placement )
Example with one category: https://jsfiddle.net/p5Lm0orw/

#### Product version
Highcharts - Latest stable

#### Affected browser(s)
Seems to be all

**Comment by pawelfus** [comment]
Thanks for reporting the issue @matt-sanders 

**Workaround:**
Set extremes for xAxis, demo: https://jsfiddle.net/BlackLabel/b81f405o/

Snippet:
```js
    xAxis: {
    	min: -0.49,
        max: 0.49,
        categories: [
            'Seattle HQ'
        ]
    },
```

**Comment by matt-sanders** [comment]
Thanks for the workaround @pawelfus I'll use that for now and keep an eye on this issue.

**Comment by pawelfus** [comment]
Actually there's even simpler workaround suggested in docs for [`series.pointPlacement`](https://api.highcharts.com/highcharts/series.column.pointPlacement) - we can't calculate `pointRange` (distance between two closest points) because we have only one point. In other words, instead of setting extremes, set `pointRange: 1` (which is always for **categorized** axis). Demo: https://jsfiddle.net/BlackLabel/f8s1zjcd/

**Comment by aroue2** [comment]
Hello,
It is probably already solved with the bugfix, but as I encountered this problem with a different context, I wanted to share it :
I have multiple series. Two series have datas on x = 1, and one have data on x = 3, and there is not data for x = 2. In this case, the pointPlacement: 'between' also does not work correctly
https://jsfiddle.net/1dtkyzn9/2/ In this demo, the column of the 2nd serie is not between 1 and 2.
pointRange: 1 fixes the problem here too

**Comment by pawelfus** [comment]
In your case, calculated `pointRange` equals 2 - so points are placed between ticks: 1 and 3. In other words, if you want points to be placed between ticks: 1 and 2, you need to set `pointRange`.

**Comment by aroue2** [comment]
Yes I mentionned this at the end of my comment too.
Maybe you mean what I reported is not a bug ?

**Comment by pawelfus** [comment]
Sorry, I just wanted to explain why it's necessary to set `pointRange` for your dataset. And yes, I don't think it's a bug.
