### ISSUE TITLE
Inverted histogram cuts off the first bar and leaves extra space at the bottom of the axis

### ISSUE THREAD

**Issue by wenyichen** [highcharts/highcharts#11955]
#### Expected behaviour
When inverted, the histogram should display all the bars with the same width

#### Actual behaviour
When inverted, the histogram cuts off the first bar and leaves extra space at the bottom.

#### Live demo with steps to reproduce
https://jsfiddle.net/jeq4ycwn/
Renders incorrectly with inverted set to false, correctly with inverted set to true
The bar that represents 3.10-3.92 lines up with the label such that 3.10 < 3.

#### Product version
Highcharts/Highstock 7

#### Affected browser(s)
Chrome, Firefox, Safari, did not test Edge

**Comment by pawelfus** [comment]
Hi @wenyichen 

Thanks for reporting the issue. @Denyllon - could you take a look? 

**Workaround:**
Set `series.pointPlacement = 0`, demo: https://jsfiddle.net/BlackLabel/n0mrc4xo/

**Comment by wenyichen** [comment]
Hi @pawelfus 

Nice workaround, fixed the bar cutting off for me, but there is still the issue of the alignment with the axis labels. 

![Screen Shot 2019-09-13 at 9 50 39 AM](https://user-images.githubusercontent.com/5867164/64880068-304fd280-d60c-11e9-9ffa-9d19e03e9dfe.png)

**Comment by pawelfus** [comment]
Hard to say without seeing this live. Could you create a demo? Thanks!

**Comment by Denyllon** [comment]
The problem is in the way of how the `pointPlacement` property is working with inverted chart in general, and it applies to all series types, e.g basic [column](https://jsfiddle.net/BlackLabel/oqjp2s3m/), and even [line](https://jsfiddle.net/BlackLabel/dwahgzoL/) with category axis. To make this issue much easier to understand, the `pointPlacement` positive values are always moving the points to the right side of the axis. In case when the chart is inverted (**which results in reversing xAxis**), then points should be also moved in agree with axis direction, but they are positioned in the opposite direction.

_Internal Note_
_The most possible place to fix that would be the `Series.pointPlacementToXValue` prototype function, because regardless whether the xAxis is `reversed` or not, the `pointPlacement` value is always mapped to `0.5` when user set it equal to `between`._

Live example (based on histogram) with fix applied: https://jsfiddle.net/BlackLabel/ejLa10m9/

Kind regards

**Comment by wenyichen** [comment]
Makes sense. Thanks for the fix!
