### ISSUE TITLE
Add xDecimals, xSuffix, xPrefix to tooltip

### ISSUE THREAD

**Issue by manu-st** [highcharts/highcharts#11954]
This is a feature request for adding the new fields to the tooltip options in highcarts. Currently you can provide `valueDecimals`, `valuePrefix` and `valueSuffix` to properly display the y values in a tooltip, but you do not have the option to do the same of the x values.

I would like to see added `xDecimals`, `xPrefix` and `xSuffix` to do the same as the `value` options but applied to the x values.

Thanks!

**Comment by pawelfus** [comment]
Hi @manu-st 

Thanks for sharing the idea. I recommend creating an idea on our [UserVoice](https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api). I'm not sure if additional options are needed, so I would rather gather more votes confirming users really need that.

It the meantime, did you consider using `tooltip.pointFormat` instead of `valuePrefix/Suffix/Decimals`? String formatting was greatly improved since v3, where you can format not only numbers but dates too, which wasn't possible using options above. In short, `pointFormat` is much more flexible than the options above . Simple `pointFormat: 'prefix {point.y:,.2f} suffix'` is the same as using `valuePrefix/Suffix/Decimals`.

More about formatting can be found in our docs: https://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting

**Comment by manu-st** [comment]
Indeed having the pointFormat will remove my specific need and actually I would suggest that you make `valuePrefix/Suffix/Decimals` obsolete :-)
