### ISSUE TITLE
scrollablePlotArea and title position when using setTitle

### ISSUE THREAD

**Issue by gbenthomas** [highcharts/highcharts#11966]
#### Expected behaviour
Calling chart.setTitle when using scrollablePlotArea should keep the title fixed in place

#### Actual behaviour
Chart title becomes part of scrollable area after setTitle is called. (This may be related to #11687 )

#### Live demo with steps to reproduce
https://jsfiddle.net/rgm4fbq9/

1. Click on a point to drill down
1. Notice that chart title is now all the way to the left side of the chart (scroll to the left)

#### Product version
Highcharts v7.2.0

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Thanks for reporting the issue @gbenthomas 

I think it's not related to #11687 but very similar. In this case it's caused by updating title which recreates the element, providing wrong parent (scrollable vs non-scrollable area).

**Workaround:**
Use `chart.title.attr({ text: new_text });` to update text, instead of `setTitle()`: https://jsfiddle.net/BlackLabel/463a57xd/

Snippet: 
```js
    events: {
      drilldown: function(e) {
        this.title.attr({
          text: e.point.name
        })
      },
      drillup: function(e) {
        this.title.attr({
          text: 'Browser market shares. January, 2018'
        })
      }
    }
```
