### ISSUE TITLE
Treemap color axis with 3+ stops not applied to elements.

### ISSUE THREAD

**Issue by Rojuinex** [highcharts/highcharts#12002]
#### Expected behaviour
When color axis with 3 or more stops are used with treemap the color is interpolated based off its colorValue property as in heatmap.

#### Actual behaviour
Color axis display is interpolated correctly, however the area elements do not have their colors interpolated.

#### Live demo with steps to reproduce
http://jsfiddle.net/pesa8g6d/

#### Product version
Highcharts

**Comment by pawelfus** [comment]
Hi @Rojuinex 

Thanks for reporting the issue. This is caused by using `"red"` color instead of RGB(A)/hex format. For example hex value works fine: http://jsfiddle.net/BlackLabel/4v9ynu6z/3/

You can find this in our docs for [ColorString](https://api.highcharts.com/class-reference/Highcharts#.ColorString).

**Comment by Rojuinex** [comment]
Ah! Awesome thanks!
