### ISSUE TITLE
Same X point in data series, make markers gone

### ISSUE THREAD

**Issue by PAPIONbit** [highcharts/highcharts#12019]
### Expected behavior:
More than one same dataPoint (in X [time]) in my data, just be ignored and NO effect on threshold of markers.

### Actual behavior:
If i have two or more point in same time in my data, like this:
```
[1558733406,9000000],[1558733406,9000001]
```
and i have these option:
```
plotOptions: {
   series: {
	marker: {
		enabled:undefined,
		enabledThreshold: 5,
		radius: 5
	}
   }
}
```
no any marker point will show, till i setExtreme somewhere else.

### Product version:
Highstock 7.2.0

Best Regards

**Comment by pawelfus** [comment]
Hi @PAPIONbit 

This is expected behaviour. You have two data points at the same x-value, which means there's no horizontal space for markers thus markers are disabled.

**Comment by PAPIONbit** [comment]
1. why not just ignore when both X and Y is same?
2. why still not shown and even not reachable when in same X but the second Y is enough far from the first and completely able to show?

**Comment by KacperMadej** [comment]
@PAPIONbit 

For the answers please check the relevant API reference: https://api.highcharts.com/highcharts/plotOptions.series.marker.enabledThreshold

If you want the chart to behave differently then you could suggest an enhancement suggestion using our UserVoice: https://highcharts.uservoice.com/forums/55896-general

**Comment by PAPIONbit** [comment]
I think you didn't got the exactly "issue", so i explain better.
when you have these points like :
```
[1000],[1]
[2000],[1]
...
[10000000000],[1]
[10000000001],[1]
...
[88888888888],[1]
[99999999999],[1]
```
Default Highstock never care how much horizontally they can be close or far between 1 billion points in **data**, Highstock just draw with **same distance** but **different xAxis labels**.
So **drawing behavior** target and **enabledThreshold** depend **not to data**. should depend to how much area and possibility in **view** to show.
Now i say why when it is still possible to show in :
1.  Same **X&Y** points like **[10],[1]** and next **[10],[1]**, and never reachable, why effective? why just not ignore like not reachable?
2.  Same **X** point like **[10],[1]** and next **[10],[9]** exist, and never reachable, and able to draw, why not just draw it, and let it be reached too? (We know the line will be draw as a vertical line)

about second question, it could be suggested in uservoice too, because as you informed the reference just talk about horizontal things. but i preferred suggest it here as a GitHub user.

Best Regards

**Comment by KacperMadej** [comment]
You are right - I didn't understand the case fully and I'm afraid I still do not fully understand it. Please help me by providing more details:

1. If you zoom to place where the overlapping points are not visible then markers are enabled:
https://jsfiddle.net/BlackLabel/1su54dw0/
What do you mean by "not reachable"? You could add jitter to make them appear not in the same place. The feature is implemented for scatter series type - https://api.highcharts.com/highstock/plotOptions.scatter.jitter Would this feature help in your opinion?
Do you want to disable makers only for those points and allow them for the others?

2. It's explained in the shared API reference:
> horizontal distance

so the code works correctly (as it was designed and documented). Are you suggesting that is could work differently to create charts that will be better?

General note:
You are asking a lot of questions about why the code works as it does. The answer is because it was designed like that. If you would like us to change the design then you will be asking for a change in a correctly working code, so this is an enhancement suggestion or new feature idea. Those should go through UserVoice (you post it, community votes for it, we implement it). If you insist on posting this on GitHub then please break each new feature request into a separate and new issue, so we could track them more precisely.

**Comment by PAPIONbit** [comment]
Look at this please :
https://jsfiddle.net/PAPIONbit/anbd6zkp/14/
(Try to click on them)

### Expected behavior:
**A** or **B**
**A)** the point just be ignored when data are loading
**B)** the point be reachable

+ It is same when something like :
```
		xAxis: {
			ordinal: false,
```
will be used too.
so we can expect one of the A or B happen instead.

### Also:
I know the **way of calculation is not a loop**, and it is just by multiplying length of points and pixels of them depend to width of the area and with adding threshold.

But we have a main loop for drawing, isn't this better that we just change the way like this? :
In the drawing loop, when we got any marker point that horizontally or vertically, touch each other, we hide all.

+ About **General note**, when my addressee is a professional like you guys, the lowest expectation was around one day wait before closing.

Best Regards
