### ISSUE TITLE
Y-Axis does not scale properly when all values are the same and below 1

### ISSUE THREAD

**Issue by wat3rcool** [highcharts/highcharts#12060]
#### Expected behaviour

When drawing a line chat, the Y-Axis should have a proper scaling so the line is actually showing something meaningful. 

#### Actual behaviour

The Y-Axis seems to stick to the default 0 to 5 scaling despite all values are between 0 and 0.1. The line is then floored to the bottom and has near to no meaning anymore. The Scaling should be something like 0 to 0.1 in this case, not 0 to 5.

Scaling is fine for value bigger than 1

#### Live demo with steps to reproduce
https://jsfiddle.net/s8fm5267/

#### Product version
Highcharts 7.1.1.

#### Affected browser(s)
all

**Comment by wat3rcool** [comment]
https://jsfiddle.net/s8fm5267/  -> Look at the Temperature "curve".

**Comment by pawelfus** [comment]
Hi @wat3rcool 

Thanks for reporting the issue. The problem here is that all values are exactly the same - all we know is just one value 0.06 (for min and max values). To calculate extremes, `tickInterval` etc we need at least two values, for example: https://jsfiddle.net/BlackLabel/up0xeLof/

There's an additional case here - when using multiple yAxes we try to align ticks to avoid messy ticks. You can set [`chart.alignTicks`](https://api.highcharts.com/highcharts/chart.alignTicks) to false to observe different behaviour: https://jsfiddle.net/BlackLabel/up0xeLof/4/ (and https://jsfiddle.net/BlackLabel/up0xeLof/5/).

To resolve the above problems I suggest to set [`yAxis.minRange`](https://api.highcharts.com/highcharts/yAxis.minRange) - that way Highcharts will try to adapt extremes to the `minRange` option, even when all values are the same, take a look: https://jsfiddle.net/BlackLabel/up0xeLof/8/

Alternative solution is to use [`yAxis.tickPositioner`](https://api.highcharts.com/highcharts/yAxis.tickPositioner) where you can implement your own logic if build-in solutions don't meet your requirements.

**Comment by wat3rcool** [comment]
hm, I didn't think about chart.alignTicks that this could mess the result up here. Thanks for the suggestions!
