### ISSUE TITLE
Impossible to hide the tooltip once the chart is updated using .update() method

### ISSUE THREAD

**Issue by jk171505** [highcharts/highcharts#12069]
#### Expected behaviour
tooltip disappears on mouse out - stickyTracking = false works

#### Actual behaviour
`stickyTracking: false` works only if chart is not updated. Once updated using `chart.update()` while tooltip is visible (hover over the data point), the `stickyTracking: false` doesn't works anymore, which means it's impossible to hide the tooltip anymore.
video: https://d.pr/v/6uipI6

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/5m609gxe/

#### Product version
highcharts

#### Affected browser(s)
chrome, brave, safari, firefox

**Comment by jk171505** [comment]
The problem is not only in the tooltip.
If the boost module is enabled, the mouseOver and mouseOut point events are fired endlessly while moving the mouse over the plot area:
https://codesandbox.io/s/highcharts-react-demo-v3gd5
video: https://d.pr/v/TnR4gD

**Comment by pawelfus** [comment]
Thanks for reporting the issue @jk171505 

**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/7qrnLajy/

Plugin:
```js
(function(H) {
  H.wrap(
    H.Series.prototype,
    'destroy',
    function(proceed, ...args) {
      var chart = this.chart,
        hoverSeries = chart.hoverSeries;

      chart.hoverSeries = null;
      proceed.apply(this, args);
      chart.hoverSeries = hoverSeries;

    }
  );
})(Highcharts);
```

*Internal note:*
It's most probably caused by nullifying `chart.hoverSeries` on `series.update()`:

https://github.com/highcharts/highcharts/blob/f80aa30967ae429ada701dea80efa52d351ed21d/ts/parts/Series.ts#L5069-L5072

Which later is checked:
https://github.com/highcharts/highcharts/blob/f80aa30967ae429ada701dea80efa52d351ed21d/ts/parts/Pointer.ts#L1559-L1583

We can add `keepEvents` flag to the nullifying condition above.

**Comment by jk171505** [comment]
Thanks. I tried to add this plugin to react wrapper, and it doesn't work:
https://codesandbox.io/s/highcharts-react-demo-v3gd5

**Comment by jk171505** [comment]
Disregard my last update. It's codesandbox playing with me - `save` didn't` work, I had to refresh the window to see updated code working.

**Comment by jk171505** [comment]
Well, unfortunately, this plugin works as long as the boost module isn't applied:
https://codesandbox.io/s/highcharts-react-demo-v3gd5

so, still 2 issues:
1. tooltip always visible
2. endless mouseOver / mouseOut point's event fired

**Comment by pawelfus** [comment]
This is one of the boost module limits - in boosted mode, `stickyTracking` is always set to true (docs should be updated accordingly).

**Comment by jk171505** [comment]
Can you recommend any workaround? - somehow the halo is triggered and disappears on mouseOut...

**Comment by pawelfus** [comment]
Hmm.. what do you want to workaround? Boost mode + `stickyTracking`? I'm afraid if that could be easily workarounded then it would be implemented in the core of the boost module..


It seems that halo is not displayed at all since v7.1.3 in boost mode: https://jsfiddle.net/BlackLabel/sub3t9pj/4/ (I think it's an unrelated issue). In v7.1.2 halo disappears as well as tooltip's position is wrong. Now it's fixed by updating tooltip's position on data update

**Comment by jk171505** [comment]
I'm not following... so you are able to precisely detect mouse position in boost mode, on Canvas, to trigger tooltip to display appropriate point data, but you are not able use this information to detect if the tooltip should be displayed at all?

**Comment by pawelfus** [comment]
@jk171505 - I want to say that logic behind `stickyTracking` can not be simply ported to Canvas (I might be wrong of course). You mention only tooltip visibility, but there's more (states, events etc) that must be synced too. If you only need to show/hide tooltip, you can use this workaround: https://jsfiddle.net/BlackLabel/bkoj5ec2/

In line no. 31 you can change distance (10px in my demo) from cursor to the point to hide/show tooltip.
