### ISSUE TITLE
Useless spaces in class attribute, because new behavior of browsers

### ISSUE THREAD

**Issue by PAPIONbit** [highcharts/highcharts#12064]
### Expected behavior:
By adding or removing **classes** that happen like hover, just name of the new class be add or removed.

### Actual behavior:
But adding **new classes** for **second time** or more, Highstock make more and **more space** in **class attribute**, like when you move your mouse in 1 minute and just open Elements tab in developer tool of chrome, you will see a big useless **white-space**. like this:
![image](https://user-images.githubusercontent.com/47592258/65603966-782f0c00-dfb3-11e9-8af5-dc7fafa053c0.png)

### Product version:
Highstock 7.2.0

### Where is the BUG?
With pleasure, I found the bug and dedicated it to its creators:
The problem is in **highstock.src.js** in line number **3864** in **addClass** function:
```
var currentClassName = this.attr('class') || '';
```
but i think it better to be :
```
var currentClassName = (this.attr('class') || '').replace(/\s+$/,'');
```
+ I hope the solution be best. because it can be changed in **removeClass** function too

Best Regards

**Comment by pawelfus** [comment]
Thanks @PAPIONbit !

*Internal note:*
While it may be a good idea to prevent extra spaces from adding to class name, we should probably remove empty space in the first place: 
Demo: https://jsfiddle.net/BlackLabel/en4x9m1h/ - in console we can see extra space: `"highcharts-series highcharts-series-0 highcharts-line-series highcharts-color-0 "`

This is a direct result of v5 implementation (styled mode) when `highcharts-color-{n}` was implemented: 

https://github.com/highcharts/highcharts/blob/6d807952574237c77d9b8c92232090a9877552da/ts/parts/Series.ts#L5648-L5666

Instead of postfixing classnames with spaces, we can prefix them.

**Comment by PAPIONbit** [comment]
Yes, you are right.
I think it is more than 10 items that type of deciding for them is wrong. like this:
```
item.legendGroup = renderer
                        .g('legend-item')
                        .addClass('highcharts-' + series.type + '-series ' +
                        'highcharts-color-' + item.colorIndex +
                        (itemClassName ? ' ' + itemClassName : '') +
                        (isSeries ?
                            ' highcharts-series-' + item.index :
                            ''))
                        .attr({ zIndex: 1 })
                        .add(legend.scrollGroup);
```
So i think when the addClass function completely depend to spaces. we should :
- A) addClass 2 time when have 2 classes to add, instead of putting spaces in strings
or
- B) Deiced even more strict to put space or not, before sending arguments
or
- C) Change type of arguments of addClass function to Array
or
- D) Just fix it now, with even more careful Regex like this :
```
/(^\s+)|(\s+$)|(\s\s)/g
```

**Comment by TorsteinHonsi** [comment]
I think the problem is not initially setting a group of classes. In that case the spaces are resolved. The problem is when toggling classes with `addClass` and `removeClass`. See http://jsfiddle.net/highcharts/a1qy6bcL/.
