### ISSUE TITLE
Utils functions missing on the main instance for Highmaps

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#12087]
#### Expected behaviour
Those are set for Highcharts in here:
https://github.com/highcharts/highcharts/blob/master/js/masters/highcharts.src.js#L41-L57

Similar or the same could be set for Highmaps or Highmaps master (for the build) could be changed to match other products, so to extend the functionality of Highcharts with other modules/parts.

Which one would be better?
@oysteinmoseng 

#### Actual behaviour
Other products handle this well because they extend main Highcharts, but Highmaps is not the case.
https://github.com/highcharts/highcharts/blob/master/js/masters/highmaps.src.js

#### Additional comments
The lack of `spalt` on the main instance makes the motion plugin fail hard on Highmaps.

#### Workaround
Use the Highcharts + map module instead of Highmaps

**Comment by oysteinmoseng** [comment]
Gut feeling is I would pull this logic into its own file and reference it from the master for both Highcharts and Highmaps. Thoughts @TorsteinHonsi @jon-a-nygaard

**Comment by jon-a-nygaard** [comment]
> pull this logic into its own file and reference it from the master for both Highcharts and Highmaps

Something like that is probably a good option. The main object here for me is at least to avoid doing the extending of Highcharts object in the actual parts files, because that will make them all dependent upon the Highcharts object and more tightly coupled.

> The lack of `spalt` on the main instance makes the motion plugin fail hard on Highmaps.

This is a sign that the motion plugin is loading `splat` from the Highcharts object, it should load it by importing it from `parts/Utilities.js`. This is likely a slip when I added the export of the `splat` function.

**Comment by TorsteinHonsi** [comment]
> This is likely a slip when I added the export of the splat function.

I think the problem is rather that the whole block copying from U to H is missing in the Highmaps master. So I support Øystein in having a separate file for this, so we don't make the same mistake over.

**Comment by khlieng** [comment]
Fixed since 7.2.1 (#12312).
