### ISSUE TITLE
series.update shadow does not change shadow without disabling it first

### ISSUE THREAD

**Issue by anajavi** [highcharts/highcharts#12091]
#### Expected behaviour
Shadow should change color with series.update({shadow: { color: 'blue}}).

#### Actual behaviour
series.update({shadow: false}) must be called first and then series.update({shadow: { color: 'blue}}).

#### Live demo with steps to reproduce
https://jsfiddle.net/wnrq1tfy/1/

'update'  button should change color, but does not.
'update with disable' button disables shadow before updating color.

#### Product version
Highcharts 7.2.0

#### Affected browser(s)
Chrome 77

#### Original issue
https://github.com/whawker/react-jsx-highcharts/issues/232

**Comment by sebastianbochan** [comment]
Hi @anajavi,
Thank you for reporting about the problem.

**Comment by TorsteinHonsi** [comment]
The issue comes from the following block. If a shadow exists from before, it doesn't recreate it. Instead, it should check if the options have changed, and (only) if they have, rebuild the shadows.

https://github.com/highcharts/highcharts/blob/4ed5692a7de4e70d6b2e258350d80bd7ef34f276/ts/parts/SvgRenderer.ts#L2703-L2708
