### ISSUE TITLE
Markers disappearing

### ISSUE THREAD

**Issue by bingyou-chen** [highcharts/highcharts#12106]
I have below 2 examples where first one produces expected behavior and second one does not. 
In second example, the markers of the line disappear unexpectedly.
2 examples use exactly the same code except for line 57 where the value of x is different.

In my actual use cases, I intend to draw a few lines, each with markers and labels. for each line, I need to let different markers have different sizes. 
Other than this issue reported, I also observe labels of point missing. (thought might come from same cause)

Could you advise? thanks.

#### Expected behaviour
![image](https://user-images.githubusercontent.com/55996309/65902423-fbee5b80-e3ec-11e9-8543-09dca8c94c97.png)

#### Actual behaviour
![image](https://user-images.githubusercontent.com/55996309/65902446-0a3c7780-e3ed-11e9-8569-d9993704a205.png)

#### Live demo with steps to reproduce
**Example 1 (expected behavior):**
https://jsfiddle.net/bingyou/mkq45xa9/14

**Example 2 (unexpected behavior):**
https://jsfiddle.net/bingyou/mkq45xa9/15

#### Product version
Refer to the jsfiddle example, don't think it works even in latest version.

#### Affected browser(s)
not working in Chrome, not sure about other browsers

**Comment by pawelfus** [comment]
Hi @bingyou-chen 

Thank you fore reporting the issue. This is expected behaviour: when two markers are too close to each other (in horizontal space) then we automatically hide them. This can be controlled by [`series.marker.enabled`](https://api.highcharts.com/highcharts/series.line.marker.enabled) option, take a look: https://jsfiddle.net/BlackLabel/b5zntsw8/

Similar case for dataLabels: when two dataLabels overlap, we hide one of them. You can force rendering them by setting `series.dataLabels.allowOverlap` to true.

**Comment by bingyou-chen** [comment]
it works for me, thank you!
