### ISSUE TITLE
StockTools indicators menu is not scrollable with mapNavigation.enabled: true

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#12100]
#### Expected behaviour
It should be possible to scroll over stockTools indicators menu.

#### Actual behaviour
When `<script src="https://code.highcharts.com/maps/modules/map.js"></script>` is added, and mapNavigation is enabled, scrolling over stockTools menu is no working. Instead of scroll, the whole chart is zooming.

#### Live demo with steps to reproduce
https://jsfiddle.net/185m2nsx/4/

**Comment by TorsteinHonsi** [comment]
Sorry for the mess, I approved the PR and merged it, then regretted and opened it again.

I don't think the Popup class should be concerned with what the `mapNavigation` is configured for. Instead, I think a cleaner solution would be to have a general class name to prevent mousewheel zooming.

If the popup container had a class name like `highcharts-no-mousewheel`, we could modify `MapPointer.onContainerMouseWheel` to do nothing when the target is inside that container.

We already do a check for `chart.isInsidePlot`. If we add an additional condition, we should have a general, decoupled solution. Something like this (not tested):

```js
        if (chart.isInsidePlot(
            e.chartX - chart.plotLeft,
            e.chartY - chart.plotTop
        ) && !this.inClass(e.target, 'highcharts-no-mousewheel')) { // Popups, #12100
            chart.mapZoom(
```

**Comment by karolkolodziej** [comment]
@TorsteinHonsi 
Your solution will solve only one part of the issue here. 
Adding the second check to that if and class `highcharts-no-mousewheel` to the popup will indeed prevent the map from scrolling when the popup is shown.
However, the popup will not be scrollable because `MapNavigation.prototype.updateEvents` method is fired at the beginning 
 and this method unbinds the `mousewheel` event which efficiently blocks the scrolling of the popup div.
I'm not sure if we can make it work without the code inside `Popup.ts` or am I missing something?
