### ISSUE TITLE
Axis flashing when updating with spacing option

### ISSUE THREAD

**Issue by voliva** [highcharts/highcharts#12137]
If chart has `spacing` option defined, then any axis that have any option defined will flash when calling `chart.update()`

```js
const options = {
  xAxis: {
    plotLines: [{ // Can be anything, but at least 1 property needs to be present
      color: '#FF0000',
      width: 2,
      value: 5.5
    }]
  },
  chart: {
    spacing: [ // Specifically needs spacing set to reproduce the issue
      5, 5, 5, 5
    ],
  },
}
```

#### Expected behaviour
When calling `chart.update(options)` axis should not flash.

#### Actual behaviour
When calling `chart.update(options)` axis fade out and in again.

#### Live demo with steps to reproduce
https://jsfiddle.net/gh2ucoy8/

#### Product version
v7.1.1 and up (previous version 7.1.0 is working fine)

#### Affected browser(s)
Only tested in Chrome 77

**Comment by pawelfus** [comment]
Thanks for reporting the issue @voliva 

*Internal note:*
Bisected to commit 3ad430a353

**Comment by pawelfus** [comment]
*Internal note:*
Labels and grid lines should be preserved (or in general: Ticks), like other axis items (e.g. line, title, plotLines/Bands etc.). Check how others are saved, and why Ticks are not.

**Comment by sebastianbochan** [comment]
After deep debugging I found a reason of problem. All elements (like title, ticks etc) are re-rendered during update (because we destroy and init axis), but some of them are not animated by default (like `axis.title` or `axis.plotLine`) so it looks like only ticks are wrong.

In the `renderTicks` method we have this kind of animation: 
https://github.com/highcharts/highcharts/blob/2aef02113d9a157bb621200cb795f3b58a8a1a04/ts/parts/Axis.ts#L7199-L7203
which is triggered each time when update chart. It does not make sense, because extremes are not chage.

My idea is to current compare extremes with old, if are the same, skip animation.

We can do that by:
       ```
 const slideInTicks = axis.chart.hasRendered && isNumber(axis.oldMin) &&
            (axis.oldMin !== axis.min || axis.oldMax !== axis.max);
```

@TorsteinHonsi / @pawelfus what do you think?

**Comment by TorsteinHonsi** [comment]
The change in the bisected commit is that the box the chart now has to be updated, which again seems to trigger an Axis update. I don't understand why an axis update is required, so the first debugging step should be to find out why that happens. Normally, when the size of the chart changes, the axis is simply marked `isDirty`, and ticks are computed again.

I would start there. Next, the `slideInTicks` thing happens because the ticks have been destroyed during Axis.update, which I think shouldn't happen. Instead of creating new ones, it should reuse the existing ones. Plus it only happens on the X axis, not the Y axis. 

But again, start by finding out why we need axis.update.

**Comment by sebastianbochan** [comment]
@TorsteinHonsi,
The lines:
https://github.com/highcharts/highcharts/blob/ab39ff9ed515cf00e3a8e9bb607dd46fdd1168f0/ts/parts/Dynamics.ts#L903-L913

trigger setSize, which iterates on each axis and set the `isDirty` flag by default. As a result axis is re-rendered and ticks are also recalculated.

Maybe we should check the extremes there or should we focus on` slideInTicks` only, like I suggested. 

ps. the flashing issue appears on both axes (see my demo).

**Comment by TorsteinHonsi** [comment]
Hmm. It's complex. In the demo, all the chart options are set again. By setting the `xAxis` and `yAxis` options, `chart.redraw` delegates to `Axis.update` for both axes. And since the `spacing` is set, the axis is then marked dirty and rendered again. I feel that there is something wrong about how `Tick.isNew` works, but I can't grasp it.

**Comment by TorsteinHonsi** [comment]
Breaking it down to rule out `spacing`. If we do `Axis.update` without `redraw`, then `chart.setSize` in succession, the same thing happens: https://jsfiddle.net/highcharts/7sub6n18/.
