### ISSUE TITLE
Offline PDF generation

### ISSUE THREAD

**Issue by KevinFernandes** [highcharts/highcharts#12157]
#### Product version
7.2.0

Application in Angular 7.

I am trying to export to PDF on the client only so I have included the "export" and "offline-export" modules.  When I select the "PDF" export option, it still hits the internet to donwload "svg2pdf.js" and "jspdf.js".

I have tried to include both of these through npm installs and adding them to my angular.json "scripts" section but now I get a different error "TypeError: et.advancedAPI is not a function".  It seems that something is still missing or maybe the versions I have are not right.

What is the correct way to get true client-side PDF generation?
What libraries/modules do I need to import/include in order to get it to work?
Are there particular versions of these libraries I should have rather than latest?
What is the proper way to do this import? (using angular.json or an import for example)

**Comment by KacperMadej** [comment]
Hi @KevinFernandes 

Thank you for reporting the problem.

Both libraries are expected to be found on the window object that is used for the Highcharts instance, so if you have installed the needed, 3rd party libraries manually, you should make sure those are accessible for offline-exporting module on the window object.

In the module, the relevent code look like this:
`if (win.jsPDF && win.svg2pdf) {`

The default and current (since it is based on Highcharts version) path for the 3rd party libraries is set in options as:
`libURL: 'https://code.highcharts.com/7.2.0/lib/',`
API reference: https://api.highcharts.com/highcharts/exporting.libURL

The error you are getting is not describing the problem enough for me to suggest anything more. Please check the source of the error and in case it refers to a minified file try using the not minified version of it. For Highcharts modules the required change is modifying files ends from `.js` to `.src.js`.

**Comment by KevinFernandes** [comment]
Sorry been a way fir a few days.

With further testing/research it seems the issue is with the version jsPDF that I installed.  I installed "jspdf" but what was actually needed was "jspdf-yworks".

It would be nice if your documentation could describe what "exactly" is needed on a local installation to allow offline PDF generation.

What I found is that "jspdf-yworks" and "svg2pdf.js" are required.  There may be other third party libraries required depending on the features/functions you are trying to export - this was all I needed.

Moreover, if you are using Angular (7+ in my case), adding the "jspdf.min.js" and "svg2pdf.min.js" to the "scripts" section of the angular.json file, will indeed include them and exporting will work, though this results in the files being bundled with the application (making it bigger for something that is probably not used often).
Instead, include them in a separate folder in your "dist" and specify the "libURL" in the export section so they are pulled in on demand.  One caveat to the "libURL" solution though is the names of the files are different than what Highcharts is looking for; you will have to rename them to remove the "min" in their names.

**Comment by pawelfus** [comment]
Thanks! We have direct links to jsPDF and svg2pdf github in our documentation for client side export:  https://www.highcharts.com/docs/export-module/client-side-export and in our API docs: https://api.highcharts.com/highcharts/exporting.libURL - do you think changing to `yWorks/jsPDF` will do the trick?

Why did you install `jsPDF` instead of `yWorks/jsPDF`?
