### ISSUE TITLE
Column filled with pattern disappears after reflow

### ISSUE THREAD

**Issue by dhilgarth** [highcharts/highcharts#12152]
#### Expected behaviour
After reflowing the chart as a reaction to a resize of the container, all columns should remain visible

#### Actual behaviour
Columns with a pattern fill disappear

#### Live demo with steps to reproduce
https://stackblitz.com/edit/angular-highcharts-392f9c
* 4 columns are visible. Two red with pattern, two blue without pattern
* Resize the window
--> The two red columns disappeared. Hovering over the blue columns to show the tooltip and then moving the mouse to where the red columns should be will make them re-appear.

#### Product version
highcharts: 7.2.0
highcharts-angular: 2.4.0

#### Affected browser(s)
Tested with Chrome 77 and Firefox 69

**Comment by sebastianbochan** [comment]
Hi @dhilgarth,
It looks like similar to the known bug https://github.com/highcharts/highcharts/issues/12053

@oysteinmoseng could you confirm?

**Comment by dhilgarth** [comment]
I did however see this issue also with v7.0.6 of Highcharts.

**Comment by oysteinmoseng** [comment]
No, this seems to be an unrelated issue. The pattern definition being referred to is deleted from the DOM on window resize, and reinserted on mouse hover. I think there might be some logic looking for unused patterns and removing them, so that could be at play here.

Are we able to reproduce this in a jsFiddle without Angular?

**Comment by oysteinmoseng** [comment]
Turns out the pattern garbage collector looking for patterns in use is looking for SVG fill attributes like `fill="url(#...`. In your demo the fill attribute is `fill="url(https://angular-highcharts-392f9c.stackblitz.io/#highcharts-pattern-0-170de4bb61efed1d4)"`.

Absolute URLs should be okay in these, so we need to change the GC code to look for those patterns as well.
