### ISSUE TITLE
EcmaScript-module loading not working on Edge

### ISSUE THREAD

**Issue by havarde** [highcharts/highcharts#12160]
#### Expected behaviour
I expect Highcharts to load the es-module correctly and show a chart in Edge, when the same code works correctly in Chrome.

#### Actual behaviour
When running the supplied example, no chart is showing, and these error-messages are shown in the console-window:

`SCRIPT5007: SCRIPT5007: Unable to get property 'prototype' of undefined or null reference
DateTimeAxis.js (39,1)

0: Unable to get property 'prototype' of undefined or null reference
DateTimeAxis.js (38,1)
`

#### Live demo with steps to reproduce
https://jsfiddle.net/highcharts/rtcx6j3h/
(press Run)

#### Product version

I am using Highcharts ES-module from:
https://code.highcharts.com/js/es-modules/masters/highcharts.src.js

#### Affected browser(s)
Microsoft Edge 44.18362.387.0
Microsoft EdgeHTML 18.18362

**Comment by KacperMadej** [comment]
Hi @havarde 

Thank you for reporting the problem.

There's no problem when using Edge 42.17134.1.0 (EdgeHTML 17.1734), so it might be the browser problem. I will try to update the browser and test this further.

**Comment by KacperMadej** [comment]
Looks like Edge in version 44.18362.387.0 imports in an async way and fails when trying to load `DateTimeAxis` when `Axis` wasn't loaded yet. Maybe this could be resolved by adding the dependency to the `DateTimeAxis` part for the `Axis` part. It should be there anyway since `DateTimeAxis` is trying to access and use `Axis` from the `Axis` part.
