### ISSUE TITLE
chart not rendered to full width

### ISSUE THREAD

**Issue by ninamor** [highcharts/highcharts#12184]
#### Expected behaviour

I have a stockChart with rangeSelector. When switching between the selector buttons, the rendering of the chart is not consistent and sometimes it does not fill the entire chart width.

for example, this flow:
- click on the "Weekly" button, you'll see the chart is not rendered to full with
- click on "Monthly" -> same result here
- click on "Weekly" again -> now the chart is rendered as expected

https://jsfiddle.net/kkulig/4wgcbk5n/

highcharts version 7.1.2
it was only tested on chrome browser.

**Comment by pawelfus** [comment]
Hi @ninamor 

Thanks for reporting the issue. This is expected behaviour - when you change dataGrouping only, we don't change extremes. Your dataset spans up to 3rd of November, so we don't change that extremes. See #5329 - http://jsfiddle.net/4owLxnew/3/ - this is the reasoning behind this behaviour.

**Comment by ninamor** [comment]
@pawelfus is this not going to be fixed? Is there a way I can re-calculate the extremes when switching between the ranges?

**Comment by pawelfus** [comment]
I'm not saying it won't be fixed. Undecided means it's not decided if this will be fixed.

You can take full control over buttons using `buttons[index].events.click`, take a look: https://jsfiddle.net/BlackLabel/dxr2yvej/
