### ISSUE TITLE
Points change x coordinates after removing other point.

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#12195]
#### Expected behaviour
When removing the point, I would like all other points to keep the original x coordinates.

#### Actual behaviour
Let's take the last point (red with x: 5). After removing some other points, our red point changes its coordinate to 4.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/sx8wyonp
Click the first button 5 times and the second button 4 times.

There are different combinations that also spoil it.

#### Product version
Highcharts 7.2.0

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
**Workaround:**
Set `pointRange: 1`, demo: https://jsfiddle.net/BlackLabel/b6c5rf3y/

*Internal note:*
Even when not setting `pointRange`, we should consider this as a bug, because first series' columns have wrong width: 
![Screen Shot 2019-10-11 at 14 11 17](https://user-images.githubusercontent.com/1453926/66650492-08ff1c00-ec31-11e9-8e40-291be1630418.png)

Demo: https://jsfiddle.net/BlackLabel/md36v4w0/ - simply click a button

**Comment by khlieng** [comment]
Fixed since 8.2.0.
