### ISSUE TITLE
Intermitent issue with draggable points in gantt chart when loading using requirejs

### ISSUE THREAD

**Issue by ionutb** [highcharts/highcharts#12214]
#### Expected behaviour
In the Gantt chart, the user should be able to resize a task using draggable points that are placed on the left and right side of the rectangle that represents the task.

#### Actual behaviour
Sometimes the draggable points are not positioned correctly. They are displayed in the top center of the rectangle that represents the task  as opposed to the left/right side 

#### Live demo with steps to reproduce
The issue **only occurs when using requirejs (AMD)** for loading the highchart library 
https://codepen.io/adrian-ionut-beschea/pen/yLLOKJJ

You can see in the screenshots below 
Correct rendering: 
https://i.imgur.com/8FXjvlg.png

Incorrect rendering: 
https://i.imgur.com/btiWl2S.png

#### Product version
 Highcharts JS v7.2.0 (2019-09-03)
Highcharts Gantt JS v7.2.0 (2019-09-03)
 

#### Affected browser(s)
Chrome Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by sebastianbochan** [comment]
Hi @ionutb,
Thank you for reporting about the problem.

FYI @jon-a-nygaard

**Comment by jon-a-nygaard** [comment]
Thanks again @ionutb for reporting the issue. This seems to be a clear bug, and we will aim to have it fixed in one of the upcoming maintenance releases.

**Internal Note:** Not exactly sure what causes it ATM, but I would start looking for missing `@module` tags. Potentially it could also be missing ES6 imports, or import path errors.

**Comment by TorsteinHonsi** [comment]
@oysteinmoseng Any idea?

**Comment by oysteinmoseng** [comment]
Yes, I am guessing this is a module load order issue. Draggable points needs to be loaded after the gantt module in order to set up the correct positions for the `xrange` series. Otherwise it will default to the column positions, which is probably what is happening here.

This is not something we can easily fix on our side, because we are dealing with optional dependencies here, and RequireJS does not have a great structure for handling that. We should look into if there are workarounds or hacks where we can specify optional dependencies for modules.

@ionutb The easiest fix will be to split up the loading in multiple steps to trick RequireJS into loading in a specific order: https://stackoverflow.com/questions/11581611/load-files-in-specific-order-with-requirejs/16362754#16362754. Would you be able to try this and report back if you are still experiencing issues?

**Comment by ionutb** [comment]
@oysteinmoseng Thanks for the tip! I can confirm that your suggested workaround worked. 
Here is the updated codepen https://codepen.io/adrian-ionut-beschea/pen/poJoWWE
