### ISSUE TITLE
Multi series Pie chart showing circle with the latest version

### ISSUE THREAD

**Issue by babababa118** [highcharts/highcharts#12222]
#### Expected behaviour
It should not show the outer level circles. It used to work fine in older version 7.1.2, the issue is with newer version 7.2.0

![image](https://user-images.githubusercontent.com/56626814/66897848-80f48a00-f015-11e9-8bff-d6e152746bb3.png)

#### Actual behaviour
Shows up circle for second and third level

#### Live demo with steps to reproduce
https://jsfiddle.net/6cp4xmjo/ 

#### Product version
7.2.0

#### Affected browser(s)
All browsers

**Comment by pawelfus** [comment]
Hi @babababa118 

Thanks for reporting the issue. This is expected behaviour: since v7.2 we added empty graph that is rendered when total sum of the slices equals zero. You can control this border by setting [`pie.color`](https://api.highcharts.com/highcharts/series.pie.color) and [`pie.borderWidth`](https://api.highcharts.com/highcharts/series.pie.borderWidth). 

Demo: https://jsfiddle.net/BlackLabel/voytcu7L/

**Comment by babababa118** [comment]
Hi @pawelfus 

Thanks for your inputs.

The solution provided works fine on load, but hover over the pie chart brings back the border, is there any solution for that.

In below URL hover over the chart

Demo: https://jsfiddle.net/BlackLabel/voytcu7L/

**Comment by pawelfus** [comment]
Thanks for pointing this out! It seems that accidentally (?) we have two options to control the same: `borderWidth` and [`lineWidth`](https://api.highcharts.com/highcharts/series.pie.lineWidth).

Demo with disabled both: https://jsfiddle.net/BlackLabel/bdw9p8xe/

**Comment by babababa118** [comment]
Hi @pawelfus,

Appreciate your help.
