### ISSUE TITLE
Regression using Boost since Highcharts 7.1.3

### ISSUE THREAD

**Issue by jbeaslas** [highcharts/highcharts#12249]
#### Expected behaviour

Display the same thing, with or without boost.

#### Actual behaviour

Column bars doesn't have the same width + crash using phantomjs:
TypeError: undefined is not a constructor (evaluating 'c.eachAsync')

#### Live demo with steps to reproduce
7.1.3: https://jsfiddle.net/jbeaslas2/cv1nyo0q/
It works without boost or using version 7.1.2

#### Product version
7.1.3 and 7.2.0. It works without boost or using version 7.1.2

#### Affected browser(s)
all

**Comment by pawelfus** [comment]
Hi @jbeaslas 

Thanks for reporting the issue, but this is expected behaviour. Let me explain:

- when you change version of Highcharts (e.g. from v7.1.3 to v7.1.2) then you need to change **all modules** versions too: https://jsfiddle.net/BlackLabel/kgph54w6/ - the error you see in console is caused by mismatching versions
- when entering boost mode, columns always have 1px width, see docs: https://www.highcharts.com/docs/advanced-chart-features/boost-module#caveats

**Comment by jbeaslas** [comment]
Hi @pawelfus, ok sorry, so I disable boost for this kind of chart.
