### ISSUE TITLE
chart's xAxis render incorrect

### ISSUE THREAD

**Issue by yanxuequan** [highcharts/highcharts#12257]
#### Expected behaviour
![image](https://user-images.githubusercontent.com/16508918/67273258-ad664580-f4f0-11e9-9f39-b4b72e9b93c6.png)
This picture is rendered correctly

#### Actual behaviour
![image](https://user-images.githubusercontent.com/16508918/67273441-033aed80-f4f1-11e9-8c4b-dbf6f045458d.png)
This picture is rendered incorrectly

#### Live demo with steps to reproduce

https://yanxuequan.github.io/issueDemo
#### Product version

 Highcharts JS v7.2.0 (2019-09-03)
#### Affected browser(s)
all
![image](https://user-images.githubusercontent.com/16508918/67273191-90317700-f4f0-11e9-8de1-aa49bb27b306.png)

**Comment by Denyllon** [comment]
Hi @yanxuequan ,

Thank you for reporting the issue. It's directly related with https://github.com/highcharts/highcharts/issues/12174, and caused by the fact, that the `xAxis.minRange` value is not calculated again on data updates. You can manually reset the mentioned value before setting new series data. Please take a look on the example below:

https://jsfiddle.net/BlackLabel/syqx61me/17/

Kind regards!

**Comment by yanxuequan** [comment]
@Denyllon ,

**Comment by yanxuequan** [comment]
@Denyllon ,
Thank you for your help.
