### ISSUE TITLE
X axis is not getting updated on changing pointStart

### ISSUE THREAD

**Issue by artemean** [highcharts/highcharts#12275]
#### Expected behaviour
BarChart: The start value on X axis must updated when `plotOptions.series.pointStart` was updated.

#### Actual behaviour
When dynamically updating `plotOptions.series.pointStart` and updating the chart with new data the X axis is not getting updated, it stays with the initial value.

#### Product version
Highcharts 7.1.2

#### Example
https://stackblitz.com/edit/react-jrd9mx

My options are like this:
```javascript
const options = {
    plotOptions: {
        series: {
            pointStart: firstXAxisValue, // receives new value on each update
            stacking: 'normal',
            pointPadding: 0.1,
            groupPadding: 0,
            shadow: false
        }
    },
    tooltip: {
        formatter: createTooltipFormatter(), // custom formatter
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        borderColor: '#444444',
        borderRadius: 3,
        style: {
            padding: 0,
            fontFamily
        },
        shared: true
    },
    xAxis: {
        labels: {
            step: 1,
            formatter() {
                if (this.isFirst || this.isLast) return this.value;
                return null;
            }
        },
        tickInterval: 1,
        title: {
            text: 'Years'
        },
        minorTicks: false,
        crosshair: false
    }
}
```

**Comment by pawelfus** [comment]
Hi @artemean 

Thanks for reporting the issue. Please use `pointStart` on a `series` level, not `plotOptions`: https://stackblitz.com/edit/react-cojgum

*Internal note:*
It's probably caused by updating data-like options in `plotOptions`. Such changes doesn't seem to be picked up, the same happens with `pointInterval`: https://stackblitz.com/edit/react-cojgum

**Comment by 77xi** [comment]
same issue

> Hi @artemean
> 
> Thanks for reporting the issue. Please use `pointStart` on a `series` level, not `plotOptions`: https://stackblitz.com/edit/react-cojgum
> 
> _Internal note:_
> It's probably caused by updating data-like options in `plotOptions`. Such changes doesn't seem to be picked up, the same happens with `pointInterval`: https://stackblitz.com/edit/react-cojgum

same issue。please add some description if we cannot use dynamic pointStart on plotOptions

**Comment by sebastianbochan** [comment]
Hi @77xi,
Could you share a live demo of your chart and elaborate the reason of not using dynamic pointstart option ?

**Comment by 77xi** [comment]
> Hi @77xi,
> Could you share a live demo of your chart and elaborate the reason of not using dynamic pointstart option ? It will allow us to understand your problem, better.

ok, demo is https://jsfiddle.net/yxuecheng/wt6casok/7/

**Comment by sebastianbochan** [comment]
Hi @77xi,
I run your demo in the mobile Chrome (iOS version) and did not notice the performance problem (I also use legend to show/hide a series).

Please let me know about your browser / platform details.

**Comment by 77xi** [comment]
> Hi @77xi,
> I run your demo in the mobile Chrome (iOS version) and did not notice the performance problem (I also use legend to show/hide a series).
> 
> Please let me know about your browser / platform details.

emm, Mac 10.15.2 Chrome 79

**Comment by sebastianbochan** [comment]
I will test it in this configuration and get back to you.

**Comment by mateuszkornecki** [comment]
A user has reported a similar problem on the forum. After a short investigation, I found out that updating pointInterval and pointStart is not working since 7.1.0, so it looks like a regression for me. Moreover updating through plotOptions works on the previous versions only till you don't update it through series, after that it will stop working.

**Related forum thread:** https://www.highcharts.com/forum/viewtopic.php?f=9&t=43321
**Live demo (7.0.3):** https://jsfiddle.net/BlackLabel/kup95L2h/

**Comment by mateuszkornecki** [comment]
_Internal note:_
Bisected to commit 1d1b0da0ad
