### ISSUE TITLE
HighChart not showing last index in the x-axis tick label

### ISSUE THREAD

**Issue by aditya-padhi-kbl** [highcharts/highcharts#12277]
#### Expected behaviour
I am expecting HighChart to show the first and last indexed element  of array in the x-Axis

#### Actual behaviour

The last indexed element is not showing up & tick label changes as per the width of the container.
#### Live demo with steps to reproduce
https://jsfiddle.net/zutsqahx/5/

#### Product version

Version:- 6.2.0
#### Affected browser(s)
All Browsers

**Comment by pawelfus** [comment]
Hi @aditya-padhi-kbl 

Thanks for reporting the issue. You posted on our bug tracker, in case of similar problems, please contact first our support: https://www.highcharts.com/blog/support/ (email/forum/SO).

In general, this is expected behaviour if you have too many labels on xAxis and not enough space to render them all. Then we increase `tickInterval` to prevent labels overlapping.
