### ISSUE TITLE
Datas not displayed in column serie when xAxis have min and max and there are lots of columns

### ISSUE THREAD

**Issue by aroue2** [highcharts/highcharts#12293]
I created a column chart with 50+ datas which have a xAxis minimum and maximum. Only a small part of all datas are showed at once. When they are lots of datas in a serie, some columns are not displayed. In the examples I give below, reducing the amount of objects in datas or changing xAxis max to a bigger value or setting xAxis min to 0 can make appear columns.

#### Expected behaviour
The chart displays the data

#### Actual behaviour
The chart does not display the data

#### Live demo with steps to reproduce
https://jsfiddle.net/djp4mf2z/1/ : Minimized example, in this one, if you remove an empty object from data array, the graph shows something. Also, if the 50 empty objects are placed after the real data, then it will be displayed.
https://jsfiddle.net/rvy6Lw0c/1/ : A bit more complex example where the amount of objects in datas make disapear some columns, but not all. Try to remove first 10 objects in datas to see all columns appear in the range

#### Product version
Highcharts v7.2.0

#### Affected browser(s)
At least Firefox and Google Chrome

**Comment by pawelfus** [comment]
Hi @aroue2 

This is expected behaviour, controlled via [`series.cropThreshold`](https://api.highcharts.com/highcharts/series.column.cropThreshold) option: https://jsfiddle.net/BlackLabel/f5mukx6L/. Points that are **outside** extremes are not created when number of points exceeds `cropThreshold`. In your case `min=1530522877051` and "missing" point's `x=1530396000000`, so point is outside the extremes.

It's not part of API, but setting `Highcharts.seriesTypes.column.prototype.cropShoulder = 1;` allows you to render one extra column for every extreme: https://jsfiddle.net/BlackLabel/Ldbvw91a/

**Comment by sebastianbochan** [comment]
Close due to inactivity.
