### ISSUE TITLE
Regression for drilldown charts

### ISSUE THREAD

**Issue by brunoscopelliti** [highcharts/highcharts#12295]
## Live demo with steps to reproduce
Live demo is public at: https://stackblitz.com/edit/js-x5y7y6

To reproduce:
1. Drilldown into a data series (eg. Animals)
2. Click on the label (exactly the label, not the graphic) of one of the subseries (eg. Dogs)

```
Error in /turbo_modules/highcharts@7.2.0/highcharts.js (50:104)
Cannot read property 'call' of null
```

#### Product version
It seems a regression occurred in version 7.1.3.
Version 7.1.2 works fine. Version 7.2.0 is affected as well.

#### Affected browser(s)

I can reproduce this in Chrome, but not in Firefox.

**Comment by pawelfus** [comment]
Thanks for reporting @brunoscopelliti 

*Internal note:*
Bisected to commit c21be3a7a6 @jon-a-nygaard 
jsFiddle demo: https://jsfiddle.net/BlackLabel/1vuts8qk/
This null callback is assigned here: https://github.com/highcharts/highcharts/blob/9afbaa14af3255e1b70be0d5574a009ff2472bdd/ts/modules/drilldown.src.ts#L1454

**Comment by jon-a-nygaard** [comment]
**Internal Note:** The issue appears because Highcharts now recognizes that the browser supports touch, and therefore tries to fire the event handler. Should use `removeEventListener` instead of a `null` callback, which would probably also solve the TypeScript error which is hidden by the `any` cast.
