### ISSUE TITLE
Gantt how to remove empty y-axis label container when y-axis labels are disabled

### ISSUE THREAD

**Issue by matsomo** [highcharts/highcharts#12291]
#### Expected behaviour
Setting tickLength: 0 on yAxis should hide the y-axis label container (assuming they're the reason for the container width)

#### Actual behaviour
An empty container still remains which creates an unwanted padding to the left of the chart

#### Live demo with steps to reproduce
https://jsfiddle.net/vencb6uj/

#### Affected browser(s)
Chrome, FireFox, Edge, Opera

**Comment by pawelfus** [comment]
Hi @matsomo 

This is caused by `grid` options. Please disable [yAxis.grid](https://api.highcharts.com/gantt/yAxis.grid.enabled), see: https://jsfiddle.net/BlackLabel/sd0n4jb9/2/

PS: In case you have more questions, please contact our support: https://www.highcharts.com/blog/support/ - you posted on our bug tracker. Thanks!
