### ISSUE TITLE
Hide y Axis label Title

### ISSUE THREAD

**Issue by guptavirendra** [highcharts/highcharts#12327]

**Comment by pawelfus** [comment]
Hi @guptavirendra 

I'm closing the issue because of missing info. Please update required fields and let us know. 

**Note:**
You posted on our bug tracker, so if this is a question, please use other support channels: https://www.highcharts.com/blog/support/

PS: yAxis title is controlled via [`yAxis.title.text`](https://api.highcharts.com/highcharts/yAxis.title.text) option.
