### ISSUE TITLE
Drawing bugs with Edge browser and mouse over

### ISSUE THREAD

**Issue by MartijnFLC** [highcharts/highcharts#12322]
A column chart does not always work good after mouseover in Microsoft Edge.
I explain here two problems, but I think they have the same cause, so I created one bug report.

#### Expected behaviour
The mouseover effects are always shown in the same way and the bars are also always in the same position

#### Actual behaviour
- Initial mouseover does not show labels or mouseover effects at all
- On some computers (I know that is hard...) after mouseover whole bars disappear or get drawn in wrong positions (don't start at 0 when they should) or even in our case totally outside of the graph. I tried already for a few days to understand how to exactly reproduce this, but I don't see a direct logic in Windows version, Edge version or even Highcharts version. Just some computers have a lot of bugs and other only the first example.

#### Live demo with steps to reproduce
https://www.highcharts.com/demo/column-negative
- Use Microsoft Edge.
- Move the mouse over the first bar --> no tooltip gets shown and not other blue bars change color.
- (depending on the computer) move left and right, up and down, over all the bars until bars start to disappear or drawn in wrong versions

#### Product version
First explained problem tested in newest version: 7.2.1. Not tested in other versions.
Other hard to reproduce problem reproduced in 5.0.6 and 7.2.1

#### Affected browser(s)
Microsoft Edge
First explained problem reproduced in 18.18362. Not tested on other versions.
Second explained problem found in 16.16299, 17.17134 and Surface Pro 3 tablet (not sure which version). Reproduced on Windows 1709 and 1803 with a Geforce. But not all computers with exactly these versions have the bug...

**Comment by KacperMadej** [comment]
Hi @MartijnFLC 

Thank you for reporting the problem.

It looks like Edge (tested in version 44.18362.387.0) is not handling series clipping correctly.
Maybe something is not loaded correctly or is wrongly clipped for events because the shapes are visible, but not active for mouse events - I'm not able to trigger hover or click through mouse events for any point unless a different event is registered for the chart e.g. legend item hover.

As a workaround, you could set `series.clip` to `false`. Demo: https://jsfiddle.net/BlackLabel/75tqbpuy/

This looks like a browser issue. Maybe the problem will be resolved after Edge will switch to Chromium. I will try to create a simpler (and Highcharts-free) demo for the problem, report to MS (if this is not reported yet), and I will leave a new comment here with more info.

**Comment by KacperMadej** [comment]
I'm unable to recreate a simple and Highcharts-free demo for the issue without dynamic changes that are quite complex and will require more time to recreate in vanilla JS.

**Comment by MartijnFLC** [comment]
Thank you for the quick support. I tried Edge based on Chromium beta and I can't find bugs in the bars so far.

**Comment by TorsteinHonsi** [comment]
Related to #8744?

**Comment by MartijnFLC** [comment]
> 
> 
> Related to #8744?

I think it is. I personally cannot reproduce any bug on my pc, but when I was able to reproduce my own reported bug on another pc the behaviour 'feels' the same.
