### ISSUE TITLE
Highstock -stock tools - hidePopup callback doesn't work

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#12341]
It seems that hidePopup callback doesn't work. 

[API](https://api.highcharts.com/highstock/navigation.events.hidePopup)

#### Live demo with steps to reproduce

[Demo](https://jsfiddle.net/BlackLabel/p8wd2vhx/)

#### Product version

Highcharts JS v7.2.1 (2019-10-31)

#### Affected browser(s)

Chrome, Firefox

**Comment by pawelfus** [comment]
Bug in docs, should be `closePopup`, not `hidePopup`: https://jsfiddle.net/BlackLabel/vqo6Lcy4/

**Comment by otsybulsky** [comment]
Hi! I use highcharts in Angular
```
export interface NavigationEventsOptions {    
  deselectButton?: Function;    
  hidePopup?: Function;
  selectButton?: Function;     
  showPopup?: Function; 
}

```

How i can use closePopup for Angular?

**Comment by KacperMadej** [comment]
Hi @otsybulsky ,

TS definitions are based on the fixed jsdoc documentation problem (see the above commit) so the problem for Angular will be resolved after updating the Highcharts package to the next version (currently the fix is planned to be a part of the next release). If you want to resolve the problem for the current or previous versions of Highcharts then you could add the missing definitions by extending the exiting and used interface. "Extending Highcharts in TypeScript" have the general idea explained with code examples: https://www.highcharts.com/docs/advanced-chart-features/highcharts-typescript-beta#extending-highcharts-in-typescript

**Comment by laventnc** [comment]
are we sure this is fixed? closePopup still isn't fired when clicking the close button ('x' in the top right)

**Comment by pawelfus** [comment]
Hi @laventnc 

We are sure, the bug reported here is fixed: `hidePopup` callback didn't work, because there was no such event and that was a bug in docs.

Regarding `closePopup` and clicking close ("X") button - it seems to be broken, reported separate issue: #14280 - thanks for reporting this!
