### ISSUE TITLE
issue in highcharts Venn diagram intersection 

### ISSUE THREAD

**Issue by babatech** [highcharts/highcharts#12354]
#### Expected behaviour
Hi,
I'm having problem with venn diagram.
There should be intersection between circle when two data set have some intersecting value  
for example:
```
data: [{
            sets: ['Good'],
            value: 2
        }, {
            sets: ['Fast'],
            value: 7
        }, {
            sets: ['Good', 'Fast'],
            value: 9,
            name: 'More expensive'
        }]
```
this example data should have two circles and one intersecting area

#### Actual behaviour
But the Venn diagram rendered, have two circle with one circle as union of other other circle
even if the intersection value is modified as lower or greater then its existing value the circle have same behavior   

#### Live demo with steps to reproduce
https://jsfiddle.net/sshakoor/9Lwm2s6c/

#### Product version

highcharts 7.1.2 with vuejs
#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @babatech,
Thank you for reporting the bug.

FYI @jon-a-nygaard

**Comment by jon-a-nygaard** [comment]
Hi @babatech,

Based on the data you provide above and in the example, I would say that this behaves as expected.
The reason behind this is as follows:

- In the following data, the `value`defines the area of `Good` as `2`: `{ sets: ['Good'], value: 2 }`
- In the following data, the `value`defines the area of `Fast` as `7`: `{ sets: ['Fast'], value: 7 }`
- In the following data, the `value` defines the area of overlap/intersection between the two sets `Good` and `Bad` as `9`.
This means that the area of intersection between the two sets is larger than the two individual sets themselves: `{ sets: ['Good', 'Fast'], value: 9,  name: 'More expensive' }`
- When the area of intersection between two sets is equal to (or larger than) the area in (at least) one of the sets, the two sets is overlapping a 100%, as seen in the live demo.

If you disagree with this behavior, then it will be great if you can elaborate some more on how you would expect the intersection to look like, and how the sets should position themselves to each other based on your provided data.

Also if you would like to work around this behavior, then you can set `venn.data[].value` to define the set areas and overlaps, and then add a custom property on `venn.data[]` that you display in a custom `tooltip.pointFormat`. See https://jsfiddle.net/jon_a_nygaard/wnx6L8a4/

**Comment by babatech** [comment]
Hi @jon-a-nygaard 

Thanks for answering my issue. 
I'm using venn diagram to make a visual display of Max. 1000 records with 4 categories, 
the record are also overlap with other categories

For example with my fiddle data. ( https://jsfiddle.net/sshakoor/9Lwm2s6c/ )
I have total 18 records, from which
- 9 have both category (Good, Fast)
- 2 record have category Good 
- 7 record have Fast 

`tooltip.pointFormat` fiddle was helpful to make a work around. Thanks.

I have found another issue with Venn diagram 
see this fiddle:
https://jsfiddle.net/sshakoor/wxcm5L19/1/

in this example data: i have three categories (good, best, fast)
total records are 11, from which
4 is good
4 is best
1 is best and good
1 is best and fast
1 is good and fast

but in diagram i only see two circle ( best,  good) and only one intersection between visible circles
let me know if you need more information about my explanation

**Comment by jon-a-nygaard** [comment]
Hi @babatech,

> I have total 18 records, from which
9 have both category (Good, Fast)
2 record have category Good
7 record have Fast

Based on the data above, I believe the following example displays something similar to what you would like to achieve: https://jsfiddle.net/jon_a_nygaard/bu4dphxe/


> in diagram i only see two circle ( best, good)

This is because there is no set defined with the name `"BOOLEAN"`.
When the area of an individual set is not defined, it will also discard the given areas of overlap because it has no set to calculate it from. Adding a set named `"BOOLEAN"` with a `value` solves this, as seen in https://jsfiddle.net/jon_a_nygaard/8mqwonLp/

**Comment by babatech** [comment]
Hi @jon-a-nygaard 

Thanks for your reply.
the first fiddle is perfect for my use case, 

for second fiddle,
the Venn chart didn't have intersection of `BOOLEAN` and `SEMANTIC`,
even if we make `BOOLEAN` value to 2, and `BOOLEAN` have one intersection with `SEMANTIC` & one with `MACHINE_LEARNING` e.g. https://jsfiddle.net/sshakoor/f5j6rsx9/6/
the `BOOLEAN` circle still have separate individual area, but the `BOOLEAN` contain value 2 and both are intersection with other category.

**Comment by jon-a-nygaard** [comment]
What is happening in both these cases is that given the input data, it is mathematically impossible to calculate a 100% correct layout (with circles as shapes), where all the areas of overlap is equal to the input values. So the algorithm calculates a layout that has a minimum of loss. A sort of finding the best case scenario.

A simplified example of this can be seen at https://jsfiddle.net/jon_a_nygaard/n061utze/. Here `B` and `C` should ideally have zero overlap, but given the other values for area of overlap it is mathematically impossible. The resulting display is what the algorithm finds is as close to `A=B=C=2`, `A∩B=1`, `A∩C=1` and `B∩C=0` as possible.

I see that this part is not clearly mentioned in the current API and documentation, so I will add some more information to these about this.

> the Venn chart didn't have intersection of `BOOLEAN` and `SEMANTIC`

Since "SEMANTIC" is completely overlapping "BOOLEAN", in the resulting layout, there is no intersection points between them (the borders of the circles are not crossing each other).

The current assumption is that in cases when the overlap is 100%, it is better to show the original set, than displaying an intersection that is equal to the area of the smallest set. Here is a simplified example of this scenario: https://jsfiddle.net/jon_a_nygaard/hzc5k9t1/

We are of course open to suggestions if you (or someone else reading this) has thoughts on how to better visualize these scenarios.

**Comment by TorsteinHonsi** [comment]
Closing this as inactive. Please reopen if new information comes up.
