### ISSUE TITLE
Adding zones to a series stops negativeColor from applying for negative values

### ISSUE THREAD

**Issue by pg1671** [highcharts/highcharts#12396]
#### Expected behaviour
When I have a series with negative values and have defined a negative value colour I would expect negative values to be displayed in this color when there is a zone defined.

#### Actual behaviour
As soon as a zone is added the negative colour is removed and it just uses the series color.
My example has an empty zone entry, removing this brings the negative color back.

#### Live demo with steps to reproduce
https://jsfiddle.net/1vh8ygwd/

#### Product version
Highcharts.js 7.2.1

#### Affected browser(s)
Chrome 78

**Comment by pawelfus** [comment]
Hi @pg1671 

Thanks for reporting the issue. It seems that documentation is missing. In general, you can consider zones as multiple `negativeColor` options and zones are replacing `negativeColor` option. Basic config that works similar to `negativeColor`: `zones: [{ value: 0, color: 'red' }]`: https://jsfiddle.net/BlackLabel/2jwb7kvm/1/

Any comment @TorsteinHonsi ?

**Comment by TorsteinHonsi** [comment]
Yes, you're right Pawel. Behind the scenes, `negativeColor` is just a shorthand for a zone of value 0. I'll update the docs.

**Comment by pg1671** [comment]
Thanks for updating your comments on this.  I am still unable to get the effect I am looking for.

I really like the use of the negativeColor option to show values below zero in red and above in blue. 
<img width="671" alt="Screen Shot 2020-07-31 at 8 07 39 pm" src="https://user-images.githubusercontent.com/616457/89025071-8be09700-d369-11ea-8a95-915affb567bb.png">

But I also want to style the last segment of the series line with dots when that period is still active (the current month) and not complete.
<img width="669" alt="Screen Shot 2020-07-31 at 8 04 05 pm" src="https://user-images.githubusercontent.com/616457/89024931-491ebf00-d369-11ea-8d18-c078534309ff.png">

I cannot combine these 2 options.

If I try to set the dashStyle in the series data on the last segment it does not work.

Is it possible to use zones to configure both? It doesn't seem to be possible to target x axis and y axis with seperate zones as the zoneAxis variable is set on the series and is not associated with the zones so there is no way to specify which zones are applicable to which axis.

Also I would want to keep the gradient backgrounds if possible rather than just setting a color.

Cheers

**Comment by pawelfus** [comment]
That's correct, only one `zoneAxis` per series is supported.

Regarding gradients, those are supported, take a look: https://jsfiddle.net/BlackLabel/5fwa7j2c/

**Comment by pg1671** [comment]
Thanks @pawelfus .. then is it just not possible to achieve what I outlined above?

One zone targeted the X axis to apply the dots to the final segment of the line and another zone on the y axis to apply the positive and negative colouring.

It would be great if zones on the x axis didn't override the negativeColor features that apply to the y axis.

**Comment by pawelfus** [comment]
With current implementation of zones it might be hard to achieve. Your case is rather simple, but for example placing a zone in the middle of graph would require quite a lot of math to calculate this (unless we decide to change API). Not to mention which zone would have priority? When one zone is changing dash style and the other color - it is fine, but when both set color it becomes tricky.

Anyway, for now, it's possible to achieve something similar to what you outlined, but it won't be perfect, take a look: https://jsfiddle.net/BlackLabel/5fwa7j2c/2/ - the idea is to use two series, one with different dash style, and link them. It works better for `area` instead of `areaspline` (where area follows crooked path, instead of bezier one) because we don't draw curved line between just two points. Second issue is "disconnection" between series - it's a result of a browser's antyaliasing. We can control this in CSS (`shape-rendering`): https://jsfiddle.net/BlackLabel/5fwa7j2c/4/

> It would be great if zones on the x axis didn't override the negativeColor features that apply to the y axis.

I suggest to create a feature request to support xAxis and yAxis zones at the same time.

**Comment by pg1671** [comment]
thanks @pawelfus .. I will take a look at your solution with linked series and will add a feature request.

**Comment by dartess** [comment]
Hey guys.

I run into a problem that relates to this issue. So as not to open a new issue, I'll try to ask you here.

Gradients don't seem to respect the zones they are defined for. I would like to make the gradient go to zero visibility at line 0. However, the gradient goes along the entire graph, which is clearly noticeable with a strong skew. To demonstrate this, I have produced two charts: https://jsfiddle.net/oqbw5ptj/

Any ideas on how to make both gradients transparent at zero, regardless of the data?

**Comment by pawelfus** [comment]
Hi @dartess 

Gradients in SVG are defined in relation to the bounding box or to pixel positions defined by the user. Zones use clip-paths, so the visibility at a specific number won't work out of the box (because the whole shape is rendered and taken into calculation for gradient rendering). It is possible to use [userSpaceOnUse](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/gradientUnits) units, but we still have to provide pixel position of the y-value (zero in your case). 

In this case, I suggest using `chart.load` event and update that pixel position when chart is created, demo for you: https://jsfiddle.net/BlackLabel/jud5pcnb/

What now remains is a question where the start of the gradient should be. We have a few options here, but I think two are the most likely used:
- (a) gradient starts at min value of the series and ends at the max of the series (https://jsfiddle.net/BlackLabel/m28sn7cz/4/)
- gradient starts at min value of the axis and end at the max value to the axis (https://jsfiddle.net/BlackLabel/m28sn7cz/3/)

With the configs above it might not be obvious where the difference is. Using two series is more clear, please take a look:
- (a): https://jsfiddle.net/BlackLabel/m28sn7cz/5/
- (b): https://jsfiddle.net/BlackLabel/m28sn7cz/6/

With screens:
![Zrzut ekranu 2023-11-16 o 15 51 15](https://github.com/highcharts/highcharts/assets/1453926/77a19351-b18d-4b3a-8bdc-bf29e8562e22)
![Zrzut ekranu 2023-11-16 o 15 51 20](https://github.com/highcharts/highcharts/assets/1453926/9593ddc9-211d-4e66-9706-5d63edb5de04)

**Comment by dartess** [comment]
@pawelfus you are awesome! Thanks!!
