### ISSUE TITLE
Docs: Missed closing html tags

### ISSUE THREAD

**Issue by ihnatmoisieiev** [highcharts/highcharts#12409]
#### Expected behaviour
Adding closing tags to the docs.

#### Actual behaviour
Warnings about requiring `end` tag in Xcode.

#### Live demo with steps to reproduce

Please see https://github.com/highcharts/highcharts-ios/issues/255 for more info.
#### Product version

7.2.1

**Comment by sebastianbochan** [comment]
@bre1470 should we consider it as a bug?

**Comment by bre1470** [comment]
I would argue that this is a bug. The question is, where and how it should be solved.
- The simplest way would be, to remove the angle brakets.
- We can also add the closing tags to the inline markdown code.
- We can try to escape it in markdown style so that Xcode becomes happy.
- We can also digest the tags, when the iOS wrapper is compiled.
- Or we could report it as a bug to Apple, because Xcode clearly does not get it - and wait centuries for a fix.

**Comment by bre1470** [comment]
@TorsteinHonsi What should we do about invalid HTML in doclets?

**Comment by bre1470** [comment]
Not completely solved.
