### ISSUE TITLE
Lost symbol height in spline and line chart

### ISSUE THREAD

**Issue by aoilti** [highcharts/highcharts#12427]
#### Expected behaviour
setting `symbolHeight = 20`  in legend. expected render symbol height is 20px

#### Actual behaviour
It's only 8px

#### Live demo with steps to reproduce
https://jsfiddle.net/aoilti/z9antpkL/8/

#### Product version
7.2.1

#### Affected browser(s)
chrome 78.0.3904.97

**Comment by pawelfus** [comment]
Hi @aoilti 

Thanks for reporting the issue. This is expected behaviour, as per [`legend.symbolHeight`](https://api.highcharts.com/highcharts/legend.symbolHeight) docs:

> The pixel height of the symbol for series types that use a rectangle in the legend. Defaults to the font size of legend items.

Line/Spline series don't use rectangle in legend, but line with a marker. Size of the marker in legend reflects the size of markers in the series: https://jsfiddle.net/BlackLabel/rpo9wx2a/ (but can not be larger than half of `symbolHeight`: https://jsfiddle.net/BlackLabel/rpo9wx2a/2/)
