### ISSUE TITLE
Color is undefined when datalabels formatter

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#12454]
#### Expected behaviour
No errors

#### Actual behaviour
Error in the console `Cannot read property 'color' of undefined`

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/5r4go81h/

#### Product version
7.2.1

#### Affected browser(s)
Chrome

**Comment by TorsteinHonsi** [comment]
The problem is when `dataLabels` is defined as an array, and specified in `plotOptions.line`. Putting the same config in `series` instance or in `plotOptions.series` works, as does it if we define it as a single object.

**Comment by TorsteinHonsi** [comment]
The problem comes from this line:

https://github.com/highcharts/highcharts/blob/fccbd474954486f6f4378e8379fb1cf543bfd7f3/ts/parts/Chart.ts/#L479

On this line, the default single object of `plotOptions.line.dataLabels` is replaced by the array config from the user options.

Below that line, we have custom adaptations for merging tooltip options, so we may have to do something similar with the data labels object/arrays.

Alternatively, we refactor `merge` so we return an array whenever any array is attempted merged with an object. This may also relieve us of workarounds around similar cases, like `xAxis` and `yAxis` that can be objects or arrays. What do you think @oysteinmoseng ?

**Comment by oysteinmoseng** [comment]
@TorsteinHonsi My gut feeling is that this is not logic that belongs in `merge` (or that a developer would expect happen behind the scenes when calling `merge`), but agree that we might want to extract the logic to a generic function to avoid having to repeat it for cases like `xAxis/yAxis`. We could maybe even consider a `mergeOptions` function that can deal with certain options being arrays, as this could be useful in other places in the code where we merge options too

**Comment by aaron-hanson** [comment]
> The problem is when `dataLabels` is defined as an array, and specified in `plotOptions.line`. Putting the same config in `series` instance or in `plotOptions.series` works, as does it if we define it as a single object.

I wonder if this is the same cause as my error [here?](https://github.com/highcharts/highcharts/issues/9491#issuecomment-565769809)
