### ISSUE TITLE
Chart update is missing to draw series

### ISSUE THREAD

**Issue by muperi** [highcharts/highcharts#12473]
We have 3 series before calling chart update. We call chart update with 3 series again ( 2 old, 1 new). However one series is missing from the chart. We expect all 3 series to be rendered.

https://jsfiddle.net/zh5xq0do/

**Comment by sebastianbochan** [comment]
Hi @muperi,
Thank you for reporting about the problem. 

Its not a bug. The reason of the problem are references. When you init the chart references to series are initialized and during update you use different order of series (sorting by ids). As a result reference to Chicago is lost and cannot be updated by Boston. It's caused by  `oneToOne` option.

Changing order solves the problem:
- https://jsfiddle.net/BlackLabel/rck5tdep/

The second solution is disable `oneToOne` option.

Demo:
- https://jsfiddle.net/BlackLabel/g95oqrxy/
