### ISSUE TITLE
Highstocks navigator trends do not show properly when hiding an element from legends

### ISSUE THREAD

**Issue by mahyarmot** [highcharts/highcharts#12479]
#### Expected behavior
Having a Highstock chart with **multiple series**, **navigator** and **legends**; When navigator series are not set, it is expected the trend of first active legend is shown on navigator and by disabling that (first legend) the navigator should show the next active item automatically.

#### Actual behavior
By clicking and disabling the **first** legend, the navigator chart is gone and disappears, that makes the navigator empty. However, clicking other legends do not affect the navigator.

#### Live demo with steps to reproduce
https://jsfiddle.net/5jy3rhLw/1/

#### Product version
Latest HighCharts 7

#### Affected browser(s)
Chrome 74, Firefox 60Navigart

**Comment by pawelfus** [comment]
Hi @mahyarmot 

Thanks for reporting! This is expected behaviour, let me explain: by default, only first series creates a copy itself in the navigator. You can enable this for all series, take a look: https://jsfiddle.net/BlackLabel/w4k5103m/ - any series that is hidden from legend is also hidden from the navigator. So clicking other series, while those are enabled in navigator, does affect navigator.
