### ISSUE TITLE
setSize won't render the same chart when set to the exact same size

### ISSUE THREAD

**Issue by Llorx** [highcharts/highcharts#12483]
#### Expected behaviour
Render the same exact result each time when the same exact parameters are set.

#### Actual behaviour
Renders a different chart (changes the amount of Y axis ticks).

#### Live demo with steps to reproduce
http://jsfiddle.net/wo04Lc3x/1/
Steps:
 - See the amount of Y ticks the chart has on first render.
 - Click the setSize button which will reset the chart size to the same size.
 - Note how the chart has changed Y axis ticks.

I guess that happens when Y axis is set to dirty: http://jsfiddle.net/b3g1yu6c/1/

#### Product version
Highcharts 7.2.1 (latest)

#### Affected browser(s)
Chrome?

**Comment by pawelfus** [comment]
Hi @Llorx 

Thanks for reporting the issue, but this is expected behaviour. When chart is created some space is reserved (for titles, axes labels etc.). If the difference between real space and the predicted one is big enough, then axes extremes and sizes are recalculated to fit better. If the difference is small enough, we don't resize axes, simply to save some resources.

When you call `setSize()` you force axes to recalculate (just like the difference would be big enough) resulting in different layout.

If you want specific design, I suggest to set [`yAxis.tickAmount`](https://api.highcharts.com/highcharts/yAxis.tickAmount).

PS: For me, resizing doesn't change anything:
![resize](https://user-images.githubusercontent.com/1453926/69442043-281ebc80-0d4c-11ea-94e0-be1e3a03871d.gif)

**Comment by Llorx** [comment]
Hm, maybe only happens in Chrome? I've tested it in Chrome under 2 different computers, both Windows (7 and 10):
![2019-11-22_17-38-08](https://user-images.githubusercontent.com/702490/69443546-e5aaaf00-0d4e-11ea-9d48-3c2f92fb8b65.gif)

So the way to go here is to force a Chart redraw (or setSize, so everything goes dirty) after each change? So it will always be rendered the same way.

The problem with this is that calling `setSize()` after each `update()` (or `setData()` or whatever) is eating double resources, as is recalculating everything two times. If I `update()` but set `redraw` to `false`, this still happens the first time I call `setSize()` or `redraw()`, so I stillneed to call another `setSize()` so everything can fit together properly.

Is there a cheaper way of doing that? Maybe an internal call hack/workaround?

**Comment by pawelfus** [comment]
I rather expect fonts rendering in Windows vs OSX. For example 760px works similar to your case: http://jsfiddle.net/BlackLabel/of8k5nag/

What you may consider is setting fixed margins: http://jsfiddle.net/BlackLabel/dqsok4re/ - this should help. Additionally, with disabled [`Axis.labels.reserveSpace`](https://api.highcharts.com/highcharts/xAxis.labels.reserveSpace) (and `Axis.title.reserveSpace`) you get better control over plotting area's size. I think it's much better than hacking source code (and if you don't want to use `Axis.tickAmount`).

Regarding hack/workaround, I don't see  anything simple. Related lines are here:
https://github.com/highcharts/highcharts/blob/ba62771439cd5d728fad3202b5cbb7f4db8d60ad/ts/parts/Chart.ts#L2537-L2555 - so instead of `chart.setSize()` you can call `chart.render()`.

**Comment by Llorx** [comment]
Hm, great tips. Going to fiddle with those options. Thank you!
