### ISSUE TITLE
highcharts 关系图-力导图（allowPointSelect: true）选中一个节点状态改变，再选中下一个节点，上个节点状态没改变

### ISSUE THREAD

**Issue by hello-mingtian** [highcharts/highcharts#12513]
#### Expected behaviour
选择一个节点状态变成选中状态，选择另一个节点这个节点状态变成选中状态，上个节点变成未选中状态

#### Actual behaviour
选择一个节点状态变成选中状态，选择另一个节点这个节点状态变成选中状态，上个节点还是选中状态

#### Live demo with steps to reproduce
https://jshare.com.cn/temp/VIEbro

#### Product version
Highcharts7.2.0

**Comment by jon-a-nygaard** [comment]
It seems that the previously selected point in the network graph is not deselected when a new one is selected. I created a basic example where I compared the `allowPointSelect` behavior between column and networkgraph series: https://jsfiddle.net/jon_a_nygaard/z5g8wqf7/

Can you @pawelfus confirm if this is a bug or expected behavior?

**Comment by pawelfus** [comment]
This is bug, thanks for reporting @hello-mingtian
