### ISSUE TITLE
Big bubbles lost borders after hovering and de-hovering on a small bubble in the Split Packed bubble chart

### ISSUE THREAD

**Issue by bli** [highcharts/highcharts#12537]
#### Expected behaviour
After hovering the mouse to focus on a small bubble and then moving the focus away from it to return to the initial state, the border of the big bubbles should appear again.

#### Actual behaviour
The bubbles of the big bubbles disappear after hovering the mouse to focus on a small bubble and then moving the focus away from it.

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/packed-bubble-split/

1. Wait until the bubbles settle down to their final positions. Note that there is a border around each big bubble.
2. mouse over on one of the small bubbles to bring focus on it
3. Click outside the bubbles (e.g. the chart title) to move the focus away from the small bubble
4. Note that the borders around the bubbles are gone.

#### Product version
Highcharts latest version in master branch

#### Affected browser(s)
Tested in Latest Chrome Version 78.0.3904.108 (Official Build) (64-bit)

**Comment by pawelfus** [comment]
Thanks for reporting this bug @bli 

### Simplified demo

https://jsfiddle.net/BlackLabel/qkLpb9xt/

### Workaround

Set `plotOptions.packedbubble.lineWidth = 1`, demo: https://jsfiddle.net/BlackLabel/hbmwL057/

*Internal note:*
It happens after simulation ends, because on every simulation step, `lineWidth` is reset to default values from options. Once simulation ends `series.setState(state)` changes `lineWidth` according to `series.lineWidth` or `series.states.STATE.lineWidth`. FYI @Izothep

**Comment by bli** [comment]
Thanks @pawelfus 
The workaround works for me.

**Comment by raf18seb** [comment]
The same happens with `parentNodeOptions.marker.fillOpacity` after hovering the point - `fillOpacity` doesn't return to its original value: https://jsfiddle.net/BlackLabel/9rasmy7x/

**Comment by KacperMadej** [comment]
Currently, the issue is being investigated. However, there is no ETA for the fix yet.
The issue has a workaround but if the temporary solution doesn't work for you please leave a comment.
