### ISSUE TITLE
Checkboxes in legend navigation

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#1253]
Example: http://jsfiddle.net/cdw53/1/

As we can see, check boxes are not hidden.

**Comment by gleb-svechnikov** [comment]
Is it fixed? I still see this bug in 4.2.4

**Comment by TorsteinHonsi** [comment]
As far as I can see, the checkboxes are hidden successfully in 4.2.4. Can you provide a live demo? Any specific browser?

**Comment by gleb-svechnikov** [comment]
Well may be I missunderstood your previuos comment.  I though fix #1253 will not requre to use hack **itemWidth: -1** anymore. Hack breaks legend layout when you use border. Here is your modified example http://jsfiddle.net/gleb_svechnikov/m6btx3hs/

**Comment by TorsteinHonsi** [comment]
I'm not familiar with that hack... Are you using it to make the checkbox appear to the left of the symbol?

**Comment by gleb-svechnikov** [comment]
> I'm not familiar with that hack...
But I've found it in you previous comment(from Nov 16, 2012) in this example http://jsfiddle.net/highcharts/gTfXb/25/.
Yes I use in order to aligh checkbox to the left.

**Comment by TorsteinHonsi** [comment]
> I've found it in you previous comment(from Nov 16, 2012)

Okay, can't believe I've forgotten that :D

Anyway, if we override the `positionCheckboxes` function, we can place the checkbox next to the symbol. See http://jsfiddle.net/highcharts/m6btx3hs/2/. It seems like it would be easy to add an option for the left position of the checkbox, so that we can do this without modifying the source code. How would this work for you?

**Comment by gleb-svechnikov** [comment]
Yes thank you, but in you jsfiddle checkboxes are not working, but it doesn't mateter so much for this question.
