### ISSUE TITLE
Avoid fading series in Styled Mode

### ISSUE THREAD

**Issue by sprengerjo** [highcharts/highcharts#12565]
After upgrading from version 7.1.2 to 7.1.3 we have issues with fading series in our charts.

#### Expected behaviour
Series do not fade, since we set state.opacity to 1 for each series. 

Having option to disable inactive state, when hovering?

#### Actual behaviour
State opacity can only be changed via CSS.

#### Live demo with steps to reproduce
7.1.2: https://jsfiddle.net/3L1qb7j5/3/
7.2.1: https://jsfiddle.net/3L1qb7j5/1/

#### Product version
7.2.0 and 7.2.1

#### Affected browser(s)
tested in chrome and mozilla

**Comment by sebastianbochan** [comment]
**Internal note**
It also does not work in non-styled mode:
- https://jsfiddle.net/BlackLabel/cpy0tvr1/

**Comment by pawelfus** [comment]
Hi @sprengerjo 

In `styledMode` all options are controlled via classes and CSS, not configured in the chart. For example to disable inactive state in CSS set:
```css
.highcharts-series-inactive {
  opacity: 1;
}
```

Demo: https://jsfiddle.net/BlackLabel/jck4shtn/

**Comment by beckerei** [comment]
@pawelfus We figured out that this now works only over classes.

But actually we do not want to trigger inactive states when hovering over a series. Our uses cases differ and we want to set series active when other things happens.
So it would be really nice to control if the series is set to inactive when hovering over another.

Which would rather be an enhancement request. Or even  better: This already exists and we are unable to find the option.

**Comment by pawelfus** [comment]
Class name `highcharts-series-inactive` must stay there just like other classes (e.g. `highcharts-series`, `highcharts-color-N` or `highcharts-hover-series`).

I don't know exactly the other things to happen, but I believe you can create custom class names in CSS, then use these names on DOM elements. Pseudo-code:

```css
.my-style {
  opacity: 0.2
}
```

```js
Array.prototype.forEach.call(
  document.getElementsByClassName('highcharts-series'),
  function (series) { series.classList.add('my-style'); }
);

```

**Comment by beckerei** [comment]
Yes, you can totally control it with different factors like setting additional classes.
But Highcharts already has states build in, I could make sense to give users more control over when a series has a state. E.g. for hover it's easy to decide: a series is in hover state if it's being hovered, all other series are not in hover state.
But with active/inactive it gets more interesting. As far as I understand the behaviour is not controllable and default is: hovering a series makes this series active, and all other inactive. (?)

I'd prefer to have more control over when a series is active, especially since there is a public interface ([setState](https://api.highcharts.com/class-reference/Highcharts.Series#setState)) which lets me change the state of a series.
So there is still want to control opacity of inactive series, but the series should not become inactive when others are hovered. Instead I want to disable this behaviour in order to be able to control whether a series is active or inactive.

**Comment by pawelfus** [comment]
> As far as I understand the behaviour is not controllable and default is: hovering a series makes this series active, and all other inactive.

That's correct. The inactive state is the opposite of hover state. Perhaps you can consider `select` state instead.

> I'd prefer to have more control over when a series is active, especially since there is a public interface (setState) which lets me change the state of a series.

You are not the only one and we agree with you. There is a separate ticket for that: #12156
