### ISSUE TITLE
Highlighting of points disappears when updating yAxis on mouseover event over point in chart

### ISSUE THREAD

**Issue by vodess** [highcharts/highcharts#12569]
#### Expected behaviour
Highlighting of points works exactly the same way as without any yAxis modification.

#### Actual behaviour
Highlighting of points somehow disappears when attempting to change some styles of an yAxis and hovering over a point in such modified chart. It looks like it is there for a millisecond, but then it's gone.

#### Live demo with steps to reproduce
https://jsfiddle.net/8k1zqd3x/27/
First chart in the demo contains yAxis.update call with some styling modifications. There is no permanent highlight in this scenario, as per this picture:
![image](https://user-images.githubusercontent.com/15703819/70157316-a6b51b80-16b5-11ea-9b38-2be3f134ed50.png)

Second chart has yAxis.update code commented out, the highlight feature works properly:
![image](https://user-images.githubusercontent.com/15703819/70157378-c4828080-16b5-11ea-896c-aecc5cf612ec.png)

#### Product version
Highcharts 7.2.1

#### Affected browser(s)
all

**Comment by pawelfus** [comment]
Thanks for reporting this issue @vodess 

Bisected to commit 5e23ec237b 

FYI @jon-a-nygaard

**Comment by pawelfus** [comment]
*Internal note:*
Most likely issue comes from these lines: https://github.com/highcharts/highcharts/commit/5e23ec237b2992a85ea2d57ab544340b6952d374#diff-6a484c602b63f88ee9f97efd254ee22fR299-R303

Perhaps, when `hoverPoint` is the same, we don't need to fire these events.

**Comment by sebastianbochan** [comment]
_Internal note_
After deep debugging it looks like more complex issue, because of two problems here:
1. The setState is always triggered with "move" param, which causes the issue with halo.
https://github.com/highcharts/highcharts/blob/1ae472ded0517e4352fa82948e6e447e3b25f3c4/ts/parts/Pointer.ts#L1837

Its related with commit https://github.com/highcharts/highcharts/commit/e3f4302fd4b16009f8fcdd08fec535557c814e7c and bug https://github.com/highcharts/highcharts/issues/2500

Its a regression, but Im not sure how to detect the "move". My idea is to check the extremes on axis, but it sounds as workaround, not solution.

2. When we trigger:
     2.1 `setState('hover')`
     2.2 `axis.update({});`

     Then hover marker is lost. 

@TorsteinHonsi any ideas?

**Comment by TorsteinHonsi** [comment]
No... I guess we need to go to the offending commits and see why it now fails. Checking the extremes of the axis indeed seems like a workaround - we should have to add new conditions, just find out what made it work earlier, and why that was lost.
