### ISSUE TITLE
Wobbling Of Markers When Streaming

### ISSUE THREAD

**Issue by sebimarkgraf** [highcharts/highcharts#12579]
#### Expected behaviour
When the current moving window is moved and markers are activated they stay in a stable position 
to the corresponding line.

#### Actual behaviour
Markers behave different to lines in regard to anti aliasing it seems. Markers jump between pixels and lines are anti aliased.

#### Live demo with steps to reproduce
https://jsfiddle.net/rshbnw72/
Visible when the chart is updated fast enough. May be necessary to zoom in on the markers to see the effect. 
Same thing happens on the axis ticks.

#### Product version
Tested in Highcharts 7.2.1

#### Affected browser(s)
Tested with Chrome and Firefox

**Comment by pawelfus** [comment]
Thanks for reporting the issue @Sintifo 

This is actually caused by rounding pixel position for markers (and ticks) - we always render them at full pixel (e.g. `10`, never `10.4523423`). For a line we don't do that. This is needed to prevent from blurred markers/ticks.

If you don't need `ordinal` xAxis and `dataGrouping` features (which may be true for a live data), you may consider using `boost` module: https://jsfiddle.net/BlackLabel/1gzkemvL/ (vs: https://jsfiddle.net/BlackLabel/7vw6onhb/ )

I'm not sure what we can do here, any suggestions @TorsteinHonsi ?

**Comment by Sintifo** [comment]
@pawelfus The boost module does not allow to change the line width and other styling options. But I understand the motivation to render at full pixels and will stick to the boost module.

Thanks for your answer!

**Comment by Llorx** [comment]
I noticed a small inconsistency with this. When you mouseover the marks, they are redrawn at the correct positions.

There's more info here: https://github.com/highcharts/highcharts/issues/12614
