### ISSUE TITLE
Series not visible after 1.) zooming and 2.) adding

### ISSUE THREAD

**Issue by janitza-pawe** [highcharts/highcharts#12605]
#### Expected behaviour
When adding a chart series after zooming into a chart the added chart series is rendered and visible for our customers. 
#### Actual behaviour
A second series is not visible on the chart when adding it. The problem occurs when zooming into the chart using the mouse wheel.

##### Reproduction:
1. zoom into the chart using the mouse wheel
2. click "Add 2nd series"
3. the chart does not show the second series on the second Y-Axis

#### Live demo with steps to reproduce
https://codesandbox.io/s/highcharts-react-demo-7052z

#### Product version
    "highcharts": "7.2.1",
     Highstock JS v7.2.1 (2019-10-31)
    "highcharts-react-official": "^2.2.2",

#### Affected browser(s)
Firefox, Chrome, Edge

**Comment by ppotaczek** [comment]
Hi @janitza-pawe,

Thank you for reporting!
___
_Internal note:_

Issue reproduced without the React wrapper: http://jsfiddle.net/BlackLabel/vrm3ebhs/

**Comment by pawelfus** [comment]
Hi @janitza-pawe 

This is caused by using `yAxis: 1` for the first series. `mapNavigation.enableMouseWheelZoom` works only with the first yAxis and only first yAxis will be zoomed. Switch order of series (and yAxes) and you will see the result: https://codesandbox.io/s/highcharts-react-demo-eoz44 

`mapNavigation` was implemented to support, well, map navigation, not stock navigation. While it's possible to use that in Highstock, some of the features might not work out of the box.

Could you create an idea on our [UserVoice](https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api) to add proper mousewheel integration for Highstock? Thanks!
