### ISSUE TITLE
Not working synchronized charts for tooltip.shared=true

### ISSUE THREAD

**Issue by IlchenkoAnton** [highcharts/highcharts#12645]
#### Expected behaviour
Сhart tooltips synchronized

#### Actual behaviour
After adding tooltip.shared = true, not working synchronized charts. Console error appears:

Uncaught TypeError: (a || []).forEach is not a function
    at c.Pointer.applyInactiveState (highcharts.src.js:21546)
    at c.Tooltip.refresh (highcharts.src.js:20485)
    at w.Highcharts.Point.highlight ((index):140)
    at HTMLDivElement.<anonymous> ((index):119)

#### Live demo with steps to reproduce
https://jsfiddle.net/17dmpuL4/1/

#### Product version
Highcharts>=7.1.2

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @IlchenkoAnton,
Thank you for reporting an issue. When the `tooltip.shared` option is used, tooltip's core expects array of points instead of a single point also in the `tooltip.refresh()`, which is in the demo.

The solution is wrap `this` (point) into array.

Fixed demo:
- https://jsfiddle.net/BlackLabel/w7xhb5tf/

Can we close we ticket as solved?

**Comment by IlchenkoAnton** [comment]
Hi @sebastianbochan,

Thanks for your reply. Yes, the ticket may be closed.
