### ISSUE TITLE
Chart.update() api is not resizing the chart when font-size of axis label is changed

### ISSUE THREAD

**Issue by tejaspchordiya** [highcharts/highcharts#12683]
#### Expected behaviour
Chart.update() api should resize the chart, when options to change the font-size of axis label are passed.

#### Actual behaviour
Chart.update() api is NOT resizing the chart, when options to change the font-size of axis label are passed.

My observation:
Case 1: When we pass yAxis.title.text with updated text and font-size, then chart get resized.
Case 2: When we keep yAxis.title.text as it is and update the font-size, then chart is not getting resized.

#### Live demo with steps to reproduce
Case 1: [Demo](https://jsfiddle.net/fasvbegq/3/)
Case 2: [Demo](https://jsfiddle.net/fasvbegq/2/)

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @tejaspchordiya,
Thank you for reporting the problem. It looks like more complex problem, with the reserveSpace method, then I expected.

_Workaround:_
Set spacing param like here: https://jsfiddle.net/BlackLabel/fv2q6nc9/ (click on yAxis)

**Comment by tejaspchordiya** [comment]
Thanks for your reply.

The workaround that you have suggested is not ideal and very specific. We cannot calculate spacing attribute values based on the font-size provided by the user.

**Comment by pawelfus** [comment]
I'm not sure if this is a bug. Options should be called `fontSize` not `font-size`. Working demo: https://jsfiddle.net/BlackLabel/kahLne63/

**Comment by tejaspchordiya** [comment]
My bad!
Thanks @pawelfus for clarification. Now, it is working as expected.

But then, how do font style passed in this [Demo](https://jsfiddle.net/58w4go7b/1/) works?

**Comment by pawelfus** [comment]
Because we don't filter out options that are incompatible. See this: https://jsfiddle.net/BlackLabel/2rdghvac/ - in CSS styles you can find `highcharts-are-cool: 1`

`font-size` per se is a valid CSS style, so when applied to the DOM element - it has an effect. Then we get bounding box of the element and reserve required space. This works just fine unless you want to update this title/text.

What happens next we cache the bounding box according to some properties (e.g. `fontSize`, not `font-size`) to improve performance. So later when text is updated and the most important properties don't change (e.g. text and font's size), we use cached bounding box instead of forcing browser to calculate a new one.

**Comment by tejaspchordiya** [comment]
Oh. Now, I get it.
Thanks for explaining.
