### ISSUE TITLE
Moving the Navigator handles cause axis label to appear outside of chart

### ISSUE THREAD

**Issue by amerikan** [highcharts/highcharts#12716]
#### Expected behaviour

When resizing the Navigator handles, the chart labels should NOT be shown if data is not visible.

#### Actual behaviour

![Screen Shot 2020-01-03 at 8 59 04 PM](https://user-images.githubusercontent.com/179356/71760028-e6655380-2e6b-11ea-9622-18bab3e3d2e6.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/v0k2f8o7/

Slowly drag the left handle to the left side in the navigator and pay attention to the chart labels.

You'll be able to see the behavior as shown below:

![Screen Shot 2020-01-03 at 9 00 37 PM](https://user-images.githubusercontent.com/179356/71760050-35ab8400-2e6c-11ea-8a57-5f89ab427d33.png)

#### Product version
In the jsfiddle Highstock JS v8.0.0 (2019-12-10) is used. This is true also for v6.2.0 which I am using.

#### Affected browser(s)
Tested on Firefox 71.0

**Comment by pawelfus** [comment]
Thanks for reporting the issue @amerikan 

It's caused by ordinal xAxis. Did you consider disabling [`xAxis.ordinal`](https://api.highcharts.com/highstock/xAxis.ordinal) option? Take a look: https://jsfiddle.net/BlackLabel/trv8o7su/

Just a word of explanation: these labels shouldn't be visible because are pointing something outside the plotting area, not because data is not visible. There's no direct relation between xAxis label and dataset. If you need this, you should use [`xAxis.tickPositioner`](https://api.highcharts.com/highstock/xAxis.tickPositioner), for example like this: https://jsfiddle.net/BlackLabel/cu8fd20b/
