### ISSUE TITLE
(Parliament chart) Table rendering broken if column header has the . character 

### ISSUE THREAD

**Issue by sitamshrijal** [highcharts/highcharts#12730]
#### Expected behaviour

 Table should be correctly rendered.

#### Actual behaviour

Adding a `.` character in the column header breaks the table rendering.

#### Live demo with steps to reproduce
https://jsfiddle.net/mubkhnt2/

![Screenshot from 2020-01-07 17-17-13](https://user-images.githubusercontent.com/16517773/71893054-a86d7580-3172-11ea-9710-8e7a0b2a1651.png)

#### Product version
Latest version (CDN highcharts.js)

#### Affected browser(s)

Google Chrome, Mozilla Firefox

**Comment by sebastianbochan** [comment]
Hi @sitamshrijal,
Thank you for reporting about the bug. The issue is more complex and related directly with the `export-data` module.

**Workaround**
Use the dot HTML entity.

Demo:
- https://jsfiddle.net/BlackLabel/nt429emj/

_Internal note_
It looks like the problem is in the line 

https://github.com/highcharts/highcharts/blob/f21e6c5ac8004407c8e3fec728e5c21c211ea667/js/modules/export-data.src.js#L371

**Comment by TorsteinHonsi** [comment]
The underlying problem is that in the demo, [series.keys](https://api.highcharts.com/highcharts/plotOptions.series.keys) is not used as it is designed for. The keys are supposed to point to properties in the data point configuration.

In the demo, they are used for general table headers. A regular chart with this configuration will not work: https://jsfiddle.net/highcharts/z0pdfL6u/

Then the case with the `.` making a difference is because we are parsing deep options like `dataLabels.color` to be used in the keys.
