### ISSUE TITLE
Patterns Not Coloring correclty on upgrade

### ISSUE THREAD

**Issue by IgorFIE** [highcharts/highcharts#12745]
#### Expected behaviour
I should be able to upgrade from highcharts version 7.2.0 to 8.0.0 and the patterns maintain the same coloring.

#### Actual behavior
Something must have changed that affected the way coloring was working on the patterns

#### Old Version
https://jsfiddle.net/panintelligence/3wpkczL4/6/

#### New Version
https://jsfiddle.net/panintelligence/b9um4gkd/8/

**Comment by IgorFIE** [comment]
Also shouldn't the pattern:color be the general color of the area and the path:fill being the color of the path? Because I should be able to define a pattern with only the background color without color on the fill.

##### Actual
https://jsfiddle.net/panintelligence/h8fLr7aq/

##### Expected
![Screenshot from 2020-01-08 16-20-19](https://user-images.githubusercontent.com/17085338/71995648-d1edd600-3232-11ea-9b7b-29218c766590.png)

**Comment by KacperMadej** [comment]
Hi @IgorFIE 

Thank you for reporting the problem.

The option that works is now backgroundColor.
API: https://api.highcharts.com/class-reference/Highcharts.PatternOptionsObject#backgroundColor
Demo: https://jsfiddle.net/BlackLabel/nf5qrwvd/3/

Docs should be improved because the description for path is misleading and it would be nice to have a "since version X" label next to the backgroundColor option (but I'm not sure if this is supported for the class reference.

Related commit: https://github.com/highcharts/highcharts/commit/236b134dd48f9f145eacf6932a40fec35e86c38c

**Comment by IgorFIE** [comment]
Hi @KacperMadej 

Now I get it , I need to do that change then.

thanks for the help!
