### ISSUE TITLE
SetData does not preserve Axis Extremes

### ISSUE THREAD

**Issue by nithyarajan** [highcharts/highcharts#12769]
#### Expected behaviour
SetData alters only the data associated with the series and other axis options are not altered

#### Actual behaviour
SetData alters the data associated with the series and alters axis min and max setting 

#### Live demo with steps to reproduce
https://jsfiddle.net/tkuvarc7/1

#### Product version
Highstock v8.0.0

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @nithyarajan,
Thank you for contacting us. The calculation of axis' extremes is based on data i.e when you have y points: 2 and 3, extremes are 0 and 5, but when you have points like 1000 and 3000 - extremes are relative - 0 and 5000. It is related with fact that chart shows full range of points.

If you need to edit it and set static extremes, you can set min/max/tickPositions or use method like tickPositioner.

All of them are documented here:
- https://api.highcharts.com/highstock/yAxis

Demo:
- https://jsfiddle.net/BlackLabel/01u6y3v4/

**Comment by nithyarajan** [comment]
I don't think I was clear with explaining the issue. 

In the fiddle example (https://jsfiddle.net/tkuvarc7/1), a chart is rendered with just one single series. The min/max of the xAxis is defined to be a subset and you can see that it is from Aug 2014 to Sep 2015. The navigator is set to this interval onload. 

Once the button click to dynamically change the data points is invoked (Series:setData), the already predefined xAxis extremes/min/max are lost. The redraw on setData brings back all data points to the view and not just the ones between Aug 2014 and Sep 2015. The navigator at that point shows the complete range of the series. Shouldn't the min and max of the xAxis be retained? I don't see this behavior called out explicitly in the documentation

Also, this behavior was noticed when I upgraded highstock to v8.0.0 from v4.2.3. It used to work well with v4.2.3

**Comment by sebastianbochan** [comment]
Hi @nithyarajan,
Thank you for the details. You can achieve that in a simple way: using setExtremes.

I prepare you a demo:
- https://jsfiddle.net/BlackLabel/j9ho4man/

Let me know it it worked properly..

**Comment by nithyarajan** [comment]
@sebastianbochan I exactly have a similar workaround within my code to take care of the problem. But shouldn't this be the default behavior? Atleast it was and it changed. 

Would this be taken care in the future release?

**Comment by pawelfus** [comment]
Hi @nithyarajan 

Let me explain what actually happens and why you see this result. Your max is set outside the dataset and range (max - min) is ~5.5year:

```
> new Date(1578805200000) // xAxis.max
< Sun Jan 12 2020 06:00:00 GMT+0100
>
> new Date(MSFT[MSFT.length - 1][0]) // last point
< Thu Aug 20 2015 00:00:00 GMT+0200
>
> (1578805200000 - 1408546000000) / (365 * 24 * 3600 * 1000) // years
> 5.398883815322171
```

Once you enable rangeSelector, then you will see that max extreme in the top right input: https://jsfiddle.net/BlackLabel/2eng50jf/

Now, when you change the dataset, navigator keeps the range and displays new dataset with the same range of ~5.5 years. Since the dataset is shorter (~4years) the whole dataset is displayed.

Could you explain what you need to achieve @nithyarajan ? Perhaps you don't want to use `min` and `max` options? Other options to get the same result:
- use `xAxis.range`: https://jsfiddle.net/BlackLabel/zgkt5oxf/3/
- use only `xAxis.min`: https://jsfiddle.net/BlackLabel/zgkt5oxf/2/
- use `xAxis.max` that is set within the dataset (e.g. `MSFT[MSFT.length - 1][0]`): https://jsfiddle.net/BlackLabel/zgkt5oxf/1/

> But shouldn't this be the default behavior? Atleast it was and it changed.

Just checked old major versions (4.2, 5.0, 6.2, 7.2) and all of them work the same way. Could you tell us the version when it changed? Perhaps that was a bug in a particular release.

> Would this be taken care in the future release?

I agree with @sebastianbochan - I'm convinced this is not a bug, but the config specification cause this.

**Comment by nithyarajan** [comment]
Thanks @pawelfus. I think the problem was indeed the dataset that I was using. I tried to create a new dataset instead of the ones that was used in the examples and it worked without issues : https://jsfiddle.net/v1gLd0rs/ . Thanks for pointing the issue. 

I am using the min and max so that the range selected would always be between 9 am to 6 pm in https://jsfiddle.net/v1gLd0rs/ even with the new data being set. If there is a better option to achieve the result, please do let me know. 

Now I am convinced this is not a bug.

**Comment by pawelfus** [comment]
If you want particular window of time to be displayed on init, then yes, `min` and `max` options are a way to go.
