### ISSUE TITLE
Point.update does not work sometimes for the point added dynamically by series.addpoint

### ISSUE THREAD

**Issue by nagin** [highcharts/highcharts#12768]
When I add a point to Highstock dynamically by series.addPoint and get reference to added point by from series.data and update this point with new value does not get updated some times.

For example 
series.addPoint([x, y], true, false); where x is last value of series and say y=20

then get reference to  added point as such 
data =   series.data;
lp = data[data.length-1];
lp.update({y:30});
then y value of added point does not get updated.
 
Following is simple jsfiddle to demonstrate this.
If you select range in 1M then every thing works fine.
Now change range to 10M , then y value of point is not updated

https://jsfiddle.net/L0vqdx41/3/

**Comment by sebastianbochan** [comment]
Hi @nagin,
Thank you for reporting about the problem. The issue is caused by [dataGrouping](https://api.highcharts.com/highstock/series.line.dataGrouping). When the granulity of data increases, points are grouped to keep the good performance. So when you add new points, the value is calculated (i.e as average of group of points) and not visible.

The solution is disable the dataGrouping, but please be aware of performance decreasing.

**Comment by nagin** [comment]
Thank you for quick response. Yes , you are right. If I disable data grouping  then it works.
But even after disabling data grouping, if I scroll chart to left some what (means chart is not at the end) then added points are not getting updated (if I scroll to the end again  after a while). What could be reason for this. Is there any config needed?

**Comment by sebastianbochan** [comment]
So you need to update the last point of visible area, not full range? 
Correct me if Im wrong.
I also advise you to contact with our [support](http://www.highcharts.com/support) for this kind of questions. We use github for reporting bugs only.

**Comment by nagin** [comment]
No. I want to update last point added to chart, which may not be visible, if I  scroll to left. 
I will try to get answer from support.
Thank you.
