### ISSUE TITLE
Incorrect table data in export-data module

### ISSUE THREAD

**Issue by madepiet** [highcharts/highcharts#12767]
#### Behaviour
Table data is created incorrectly when some points are missing and x values are not defined.

#### Live demo
https://jsfiddle.net/BlackLabel/m5nqw8ye/

#### Working example
It is working fine when we define x value, see demo: 
https://jsfiddle.net/BlackLabel/mqshbk4z/

#### Product version
Highcharts 8.0.0

**Comment by sebastianbochan** [comment]
_Internal note_
The category should affect the display of the table, not only numeric index.
FYI @oysteinmoseng

**Comment by sebastianbochan** [comment]
_Internal note_
The problem is here:

https://github.com/highcharts/highcharts/blob/8f8996cecffde017f13fc1e1ce79b25649623556/ts/modules/export-data.src.ts#L602-L604

We should use `name` instead of `point.x`, so we have two options here:
1. set `plotOptions.series.exportKey` 
- demo: http://jsfiddle.net/BlackLabel/1c3x0v7p/
2. edit the condition which can be tricky and a little bit risky (Im not able to predict all use-cases of the exporting).

```
if ((series.xAxis && series.xAxis.hasNames) || !series.xAxis || series.exportKey === 'name') {
      key = name as any;
}
```

@oysteinmoseng what do you think?

**Comment by oysteinmoseng** [comment]
Passing the ball to @TorsteinHonsi I think - we have talked before about needing to refactor how the export data is handled, needing information for each series type on what to export and how. (This could also be shared with a11y.) Is this something we need to take into account here, or can we do a quick fix?

**Comment by TorsteinHonsi** [comment]
Without diving too deep into the problem, I think option 2, making an intelligent guess based on `series.xAxis.hasNames`, seems like the way to go. 

Plus, the export-data module has pretty good test coverage, so we should be relatively safe.
