### ISSUE TITLE
Network Graph

### ISSUE THREAD

**Issue by DevSooop** [highcharts/highcharts#12781]
#### Expected behaviour
I would like to keep the arrow on the same node when I drag node (rotation only from left to right of the link)

#### Actual behaviour
when I rotate nodes, the all link is rotated (it rotate left to right but also top to bottom)

#### Live demo with steps to reproduce
https://jsfiddle.net/oe2td3xj/

#### Product version
V8.0.0

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @DevSooop 

Thanks for reporting the issue. This is actually expected behaviour: connection line is always rendered from the left to the right, because link label use that path as a base to follow.

You can change how path is rendered, take a look: https://jsfiddle.net/BlackLabel/zmb165er/

**Plugin:**
```js
(function(H) {
  H.seriesTypes.networkgraph.prototype.pointClass.prototype.getLinkPath = function() {
    return [
      'M',
      this.fromNode.plotX,
      this.fromNode.plotY,
      'L',
      this.toNode.plotX,
      this.toNode.plotY
    ];
  };
})(Highcharts);
```

But this breaks rendering link labels:
![Screen Shot 2020-01-14 at 10 20 52](https://user-images.githubusercontent.com/1453926/72330903-9a11e300-36b7-11ea-9364-477589086857.png)

**Comment by DevSooop** [comment]
Dear @pawelfus ,

Thanks for your answer. Is there any other workaround or a way to rotate only labels ?
d3 use lines instead of paths, that is maybe why I managed to make it work.

Sincerely,
DevSooop

**Comment by pawelfus** [comment]
Hmm.. doesn't d3 use canvas instead of SVG? 

Anyway, you can use different paths for connections and labels rendering, but that will decrease the performance (doubles the amount of paths in DOM): https://jsfiddle.net/BlackLabel/0zeombLg/

Note that I changed `querySelectorAll` to exclude extra paths for labels.

Plugin:
```js
(function(H) {
  // Store original method that renders path from left to right
  H.seriesTypes.networkgraph.prototype.pointClass.prototype.getL2RLinkPath = H.seriesTypes.networkgraph.prototype.pointClass.prototype.getLinkPath;


  H.seriesTypes.networkgraph.prototype.pointClass.prototype.getLinkPath = function() {
    return [
      'M',
      this.fromNode.plotX,
      this.fromNode.plotY,
      'L',
      this.toNode.plotX,
      this.toNode.plotY
    ];
  };

  H.seriesTypes.networkgraph.prototype.pointClass.prototype.getDataLabelPath = function(dataLabel) {
    var renderer = this.series.chart.renderer;

    // Don't change paths for nodes
    if (this.isNode) {
      return this.graphic;
    }

    if (!this.dataLabelPath) {
      this.dataLabelPath = renderer
        .path()
        .addClass('highcharts-link-textpath')
        .add(dataLabel);
    }

    this.dataLabelPath.attr({
      d: this.getL2RLinkPath()
    });

    return this.dataLabelPath;
  }
})(Highcharts);
```

**Comment by DevSooop** [comment]
Dear @pawelfus ,

Thanks a lot for this, I limit nodes to 50 and it doesn't seems to reduce performances that much so it is perfect for me !
Thanks for the query selector.

d3 can use both but I used SVG.

I wish you a good day!

Sincerely,
DevSooop

**Comment by pawelfus** [comment]
Yes, with ~50 nodes that won't be a problem. Thanks!
