### ISSUE TITLE
Hidden Technical Indicators show when linkedTo series legend is toggled

### ISSUE THREAD

**Issue by BakersBakers** [highcharts/highcharts#12790]
#### Expected behaviour

If a technical indicator series is set to visible: false then the technical indicator should not show when its linkedTo series legend is toggled.

#### Actual behaviour

When you toggle the linkedTo series legend off and on the technical indicator is shown even though its explicitly set to visible: false

#### Live demo with steps to reproduce

https://jsfiddle.net/bakerbakerbaker/a8t5uhks/2/

#### Product version

Highstock latest

#### Affected browser(s)

Chrome

**Comment by sebastianbochan** [comment]
Hi @BakersBakers,
Thank you for reporting about the bug. I cannot agree that is the bug, because its default functionality in Highcharts / Highstock core.

Demo:
- https://jsfiddle.net/BlackLabel/pwv93f0e/

Please elaborate in which circumstances the indicator will be visible (when is hidden and cannot be show by the legend).

**Comment by BakersBakers** [comment]
We toggle the technical indicators from our own menu and then redraw the chart making use of the visible property on the series

**Comment by sebastianbochan** [comment]
As a workaround you can try to manipulate the `lineWidth` param.

Demo:
- https://jsfiddle.net/BlackLabel/yv1cqL64/
