### ISSUE TITLE
Gantt : range selector 'All' button disabled when it should be selected

### ISSUE THREAD

**Issue by ghost** [highcharts/highcharts#12835]
Normal behavior : When loading a chart with a serie lasting 3 months, on the range selector it does select 3 months and all is disabled, which is normal. If the serie lasts 4 months, it selects 'All'.
Error : But if the serie duration is above 3 months and under or equal to 3.1 months, then no range selector will be activated and 'All' will be disabled.

#### Expected behaviour
The button of the range 'all' should be selected.

#### Actual behaviour
The range button 'all' is disabled.

#### Live demo with steps to reproduce
https://jsfiddle.net/yvqu4et3/1

#### Product version
Latest : Highcharts Gantt JS v8.0.0 (2019-12-10)

#### Affected browser(s)
Firefox, IE, Chrome

**Comment by pawelfus** [comment]
Hi @aroue2 

Thanks for reporting the issue, but this is how chart is rendered using your demo:
![Screen Shot 2020-01-23 at 11 58 16](https://user-images.githubusercontent.com/1453926/72979013-bad4e980-3dd7-11ea-9473-8c41caa94785.png)

osx + chrome

**Comment by aroue2** [comment]
Oh yes the '3 months' button is selected when loading the page. I don't know why I thought no button was selected. But there is still a problem because the 'All' button should be highlighted instead of '3m'.
Indeed, when we load this graph with 3.1 month, '3m' is selected and 'All' is disabled. However, if we click once on '3m', we see the graph changing, as well as the 'from' date in the range selector input.
Now, we can click on 'All' and the dates will change again for the ones printed when loading the chart.
So to conclude, when loading the chart with a duration of 3.1 months, it displays all the 3.1 months but it thinks there are only 3 months and thus does not activate (and select) the 'All' button, until we click once on the '3m' button.

**Comment by pawelfus** [comment]
I think I can explain what happens. To highlight a button with a variable-length range (year or month) we check if given extremes (start and end points in your case) are within the given range:
- for a year it's between 365 and 366 days multiplied by `count` option (+/- one hour)
- for a month it's between 28 and 31 days multiplied by `count` option (+/- one hour)

So when you set 3.1 months it's (according to calculations in demo) 30 * 3.1 -> 93 days. That nicely fits our approximated range for 3M button.

Now when you click on the 3M button we need to set exact range - we can't set something between 28 and 31 days. We simply get the max value and jump to other months (like max: `Date.UTC(2018, 11, 1)` gives min: `Date.UTC(2018, 8, 1)`).

We can nicely observe the behaviour here: https://jsfiddle.net/BlackLabel/qd5cspmo/ - just drag&drop left handle in navigator: 3M button will remain highlighted.

@TorsteinHonsi - should be consider this as a bug?

**Comment by matthias-jauernig** [comment]
@pawelfus this still does not answer the question, why the "All" button is disabled at the beginning and gets enabled when "3m" is selected. As of today 4 years later, we still have the same problem with the current Highcharts version.

**Comment by pawelfus** [comment]
Hi @matthias-jauernig 

The short answer is: "All" button is enabled only when clicking on it would change extremes.

A bit longer explanation:
On initial rendering, the selected range is a full range: `8038800000.288086` in milliseconds. When you click "1m" and go back to "3m", then a different range is selected: `7948800000`. 

And our (maybe too strict?) logic for disabling the "All" button is: if the other button is selected and is displaying full range, then "All" is disabled. With fixed ranges (eg hour, day, week) it is less surprising: https://jsfiddle.net/BlackLabel/gnxcrw85/1/ "All" gets enabled when "3w" is not selected. Selecting "3w" disables the "All" button because clicking on "All" won't change extremes.

Perhaps we could narrow down the case when we disable the button to buttons with fixed-length (ms, s, h, day, week) only? What do you think @TorsteinHonsi ?

Reopening the issue for the further discussion.

**Comment by matthias-jauernig** [comment]
Thanks for explanation, @pawelfus. The prefered behavior imho would be that the "All" button is enabled everytime, because everytime there is a range of "All" dates.

**Comment by TorsteinHonsi** [comment]
> Perhaps we could narrow down the case when we disable the button to buttons with fixed-length (ms, s, h, day, week) only?

@pawelfus Sounds good to me

**Comment by pawelfus** [comment]
This behaviour will change in the next version. `All` button will be selected instead: https://jsfiddle.net/BlackLabel/8fea9Ldy/1/
