### ISSUE TITLE
Column (Bar) Filled with pattern disappears when we click on another chart in the same page. PATTERN FILL

### ISSUE THREAD

**Issue by rammohan201** [highcharts/highcharts#12840]
#### Expected behavior
I want each chart to behave on its own, Pattern Fill columns should not be dependent on any other chart, pattern filled column should display even after chart reflow or update or legend toggle of other column, 

#### Actual behavior
my application page has multiple charts of same type rendered in different accordions. It is an angular application, I have three bars in a chart, one of them is having pattern fill, I am facing issue with pattern filled bar. technically, chart components are independent, but some how, pattern fill is displaying in other charts only if first chart is opened. If I close the first chart by collapsing the accordion, pattern filled column is not displaying, I tried adding id to pattern, when I clicked on legend of another column to hide and show, then pattern filled column is not displaying again, legend symbol is not displaying. Please let me know what I am doing wrong?

I referred to below existing similar issues and updated highcharts version to 8.0.0 but even then issue is not resolved.

https://github.com/highcharts/highcharts/issues/12053
https://github.com/highcharts/pattern-fill/issues/32

#### Live demo with steps to reproduce
https://stackblitz.com/edit/angular-highcharts-uk7qzx

In this demo, I added two charts, Chart 1 is hidden by default, we can see 2nd Chart by default, and it is not showing pattern filled column.
Then click on Show/Hide Chart1 button, then we can see pattern filled column displaying in two charts. 
Then hide first chart by clicking on Show/Hide Chart1 button, then we can see pattern filled column not displaying.

why 2nd chart's pattern filled column is dependent on first one? 
why hiding 1st chart is impacting 2nd chart's pattern filled column?

#### Product version
8.0.0

#### Affected browser(s)
Chrome, IE 11, Mozilla

**Comment by pawelfus** [comment]
Hi @rammohan201 

Thanks for reporting the issue. This is caused by using the same pattern for different charts. When creating multiple charts with the same patterns' ID's all points actually refer to the first patterns (because of the first matching ID). When you hide first chart, you hide also the pattern and it seems that hidden pattern can't be use on a visible element.

I'm not sure what we can do with this issue, any ideas @oysteinmoseng ? Built-in patterns are generated with unique ID per chart.

Workaround is to use separate ID's per charts if you want to use a patterns that is hidden. For example: https://stackblitz.com/edit/angular-highcharts-v86vbt?file=app/app.component.ts

**Comment by rammohan201** [comment]
@pawelfus, Thanks for responding, I tried with different Ids for each chart, initially loaded charts worked fine but after couple of reflows, patern fill never rendered again.

**Comment by pawelfus** [comment]
Does this happen in the demo I posted above? Could you provide exact steps to recreate the issue? So we will be able to debug this. Thanks!

**Comment by rammohan201** [comment]
@pawelfus , it is not happening in your demo.I followed same steps, it's not working consistently for me. I will try to show gif of issue I am facing

**Comment by rammohan201** [comment]
when we click on machine 2 grayed out legend, striped legend symbol of machine 3 is never displaying.
![hightcharts-pattern-fill-issue](https://user-images.githubusercontent.com/12894116/73244356-bfcadc00-41cf-11ea-9278-81929c7717cd.png)

**Comment by pawelfus** [comment]
You are right, it's missing, thanks for pointing this out!

@oysteinmoseng could you take a look? Summary:
- demo: https://stackblitz.com/edit/angular-highcharts-wyyzgz?file=app/app.component.ts 
- click on "Machine 2" -> pattern is hidden
- debugging leads to this method: https://github.com/highcharts/highcharts/blob/master/ts/modules/pattern-fill.src.ts#L707 - Where `usedIds` are defined like this:

```
0: "ttps://angular-highcharts-wyyzgz.stackblitz.io/#custom-pattern-2"
1: "ttps://angular-highcharts-wyyzgz.stackblitz.io/#custom-pattern-2"
2: "ttps://angular-highcharts-wyyzgz.stackblitz.io/#custom-pattern-2"
3: "ttps://angular-highcharts-wyyzgz.stackblitz.io/#custom-pattern-2"
4: "ttps://angular-highcharts-wyyzgz.stackblitz.io/#highcharts-pattern-0-17658816b141298670"
```
But pattern name is `"highcharts-pattern-0-17658816b141298670"`.

**Comment by rammohan201** [comment]
I am seeing strange behavior, I waited around 1210 seconds, I did not do any action, pattern fill disappears. Please see below GIF.
![pattern-fill-disappears](https://user-images.githubusercontent.com/12894116/73266616-3c27e400-41fd-11ea-95fc-942f626042c6.gif)

**Comment by oysteinmoseng** [comment]
Okay, so it looks like the garbage collector for patterns is not picking up that the pattern is used, due to the URL being in the ID. Since this is being ran on redraw, any action that triggers a chart redraw could cause this.

@pawelfus do you have time to look at the issue? Basically it sounds like we need to make it pick up that `https://angular-highcharts-wyyzgz.stackblitz.io/#highcharts-pattern-0-17658816b141298670` is the same as `#highcharts-pattern-0-17658816b141298670`.
