### ISSUE TITLE
Axis labels in polar chart suppressed (regression Highcharts 7)

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#12894]
#### Expected behaviour
All axis labels in a polar chart  are rendered when  there is enough space

#### Actual behaviour
Some axis labels in a polar chart  are suppressed when  there is enough space

#### Live demo with steps to reproduce
See https://jsfiddle.net/kzoon/urxLt091
When you set the chart height slightly higher (320), all labels are rendered and it is clear that they would have fit in the original:  https://jsfiddle.net/kzoon/urxLt091/4/

#### Product version
This is a regression in Highcharts version 7
In 6.2.0 the labels were rendered OK: https://jsfiddle.net/kzoon/kwsd765f/

This problem was reported in production by one of my customers. So I need to provide a fix/work around for version 7.1.2 as soon as possible.
All I could think of was setting padding: 0 (didn't work) or allowOverlap: true (does work, but labels will actually overlap)
Any suggestions?

**Comment by pawelfus** [comment]
Could you attach some screenshots? I am not able to recreate this (Chrome Version 79.0.3945.130). Demos:
- first demo:
![Screen Shot 2020-02-05 at 12 19 58](https://user-images.githubusercontent.com/1453926/73837487-e2817400-4811-11ea-9d2f-d5379e44db36.png)
- second demo:
![Screen Shot 2020-02-05 at 12 20 12](https://user-images.githubusercontent.com/1453926/73837490-e3b2a100-4811-11ea-8fe9-e306a2c9ff21.png)
- v6.2 demo:
![Screen Shot 2020-02-05 at 12 20 06](https://user-images.githubusercontent.com/1453926/73837491-e44b3780-4811-11ea-9fbd-9641a6838106.png)

**Comment by kzoon** [comment]
Here is my screenshot of  the problem (https://jsfiddle.net/kzoon/urxLt091)
![Annotation 2020-02-05 123414](https://user-images.githubusercontent.com/1461707/73838410-e7472780-4813-11ea-96a5-b10297bcc56a.png)

Maybe in order to reproduce, you need to set   chart height a little bit lower that the 300 I userd

**Comment by pawelfus** [comment]
Yes, I cna see it now, thanks!

This is caused by adding `allowOverlap` option to axes in polar chart. In v6 there was no such option: https://jsfiddle.net/BlackLabel/zr20va4h/

Unfortunately, I can not provide any non-invasive workaround at this moment. Issue comes from a private method, not available to overwrite. It's possible to overwrite whole overlapping logic, but this most likely will cause other bugs.. Something like this: https://jsfiddle.net/BlackLabel/tfc5yqxn/ (workaround in lines 39-45).

*Internal note:*
Bisected to commit 0a5d555a3e

This is caused by trying to compare bounding boxes with different `text-anchor`. As long as all labels in a collection use the same value it's fine, because comparison simply does not take into account that value. This issue applies to both, `renderer.text()` and `renderer.label()`.

Simplified demo: https://jsfiddle.net/BlackLabel/wL2v4uhd/ - one of top labels is missing.

**Comment by kzoon** [comment]
Thanks Pawel for your quick reply.

Am I correct to understand that I can revert to the exact behavior of Highcharts 6 by applying allowOverlap: true in Highcharts 7? That sounds like an attractive option for me. 

By the way: I think that allowOverlap: true on axis labels is not documented in the API. I was afraid to use an undocumented feature...

**Comment by pawelfus** [comment]
I won't say exactly the same behaviour (many other changes were done between v6 and v7 that can affect the chart's layout), but disabling this option will prevent from hiding labels.

I'm not sure why it's undocumented, though. Most probably experimental feature to gather issues, like the one you have just reported.
