### ISSUE TITLE
Coordinate bug on Malaysia map

### ISSUE THREAD

**Issue by limbs92** [highcharts/highcharts#12904]
#### Expected behaviour
I think there is a problem with the Malaysian map coordinates.
I found the bug while trying to get a map point in the 'Jitra' area.

#### Actual behaviour
The 'longitude'(lon) part of the above capture needs to be noted. The Longitude value of 'jitra1' and 'jitra2' is little different, but it appears to be a big difference on the map.

As I checked, I found bugs in three cities: Jitra, George Town and Sungai Petani. The rest of the cities were marked on the right coordinates.

#### Live demo with steps to reproduce
https://jsfiddle.net/j78uk3qL/1/

#### Product version
Highcharts 6.7.0
Highmaps 6.7.0

**Comment by pawelfus** [comment]
Thanks for reporting. It looks like an issue with projection. @KacperMadej - could you take a look?

**Comment by KacperMadej** [comment]
This is a map bug - the hitzone had the wrong size for the left (west) side of the map.

This could be fixed with a few lines of custom code added manually (as a workaround) like in the below demo:
https://jsfiddle.net/BlackLabel/b831hnt5/2/

```js
Highcharts.maps['countries/my/my-all']['hc-transform']['my-all-west']
  .hitZone.coordinates = [
    [[-2000,9999],[4350,9999],[4350,-999],[-2000,-999],[-2000,9999]]
  ];
```

This is a map collection issue, so I will close the issue here and move the case to here: https://github.com/highcharts/map-collection-dist/issues/56
