### ISSUE TITLE
Map with overlaid pie charts navigation doesn't work correct in mobile version

### ISSUE THREAD

**Issue by pragmatos** [highcharts/highcharts#12924]
#### In mobile version pies are not sync
You can open https://www.highcharts.com/maps/demo/map-pies in emulation mode(F12)
Try do some navigation with map

**Comment by KacperMadej** [comment]
Hi @pragmatos 

Thank you for reporting the problem.

Navigation (zooming and panning) works fine for me on Android version 7.0 when using Chrome web browser.
Please provide more details about the problem - how to recreate it, what software are you using for it - OS and browser with versions.

What I was able to observe was that the tooltip's text is not positioned correctly - see screenshots below:

![Screenshots](https://user-images.githubusercontent.com/8960408/74229187-2cf76a80-4cc2-11ea-9ea8-6c3f72fc4982.jpg)

Is this the problem you wanted to report?

**Comment by pragmatos** [comment]
Hi @KacperMadej 

Navigation by map doesn't work correct. Please, see attached .gif
![Media1](https://user-images.githubusercontent.com/15641426/74310299-8c628280-4d75-11ea-949c-3f0597b8d2f3.gif)

Thanks

**Comment by KacperMadej** [comment]
Thank you for the detailed info. This looks like a bug in the demo.

**Comment by Izothep** [comment]
It looks that all we need to do is to add pie to the map group, so it will handle touch event similarly:
https://jsfiddle.net/be9jptgx/1/

Internal note:
I have tested this behaviour trying to call translate on touchmove instead of above approach. Unfortunately, it looks that in case of mobile point positions are correctly recalculated only after touch ends. On touch move these positions won't be recalculated correctly.
