### ISSUE TITLE
Align center doesn't seem to be completely centered in plotlines

### ISSUE THREAD

**Issue by abbas1994** [highcharts/highcharts#12920]
#### Expected behaviour
The plot line should intercept the text with 3 A's on either side.

#### Actual behaviour
The plot lines intercepts the text close to the center, but not quite the center

#### Live demo with steps to reproduce
https://jsfiddle.net/uryaxbqc/

![image](https://user-images.githubusercontent.com/4054574/74145307-5d71d280-4bf6-11ea-81bd-decdc74f1475.png)

**Comment by pawelfus** [comment]
Hi @abbas1994 

This is caused by default value for `plotLines[].label.x`, set it to 0 and the issue will be gone: https://jsfiddle.net/BlackLabel/8rvzaues/

We should add more detailed description in [`plotLines[].label.x`](https://api.highcharts.com/highcharts/xAxis.plotLines.label.x), right now it's a bit enigmatic: 
> Default varies by orientation.

Actually it's:
- x=4 for horizontal axes (xAxis or yAxis in inverted chart)
- x=10 for vertical axes (yAxis or xAxis in inverted chart)

Similar for `y` option:
- y=10 for horizontal axes
- y=-4 for vertical axes

And for plotBands:
- x=0 for horizontal axes
- x=10 for vertical axes
- y=16 for horizontal axes
- y=6 for vertical axes

**Comment by TorsteinHonsi** [comment]
I think this is a bit lazy design - it would be better if `x` and `y` were 0 by default, and we used `padding` to place the label relative to the line. Similar to data labels: http://jsfiddle.net/highcharts/LLExL/14416/

**Comment by abbas1994** [comment]
Thanks, seems to do the job!
