### ISSUE TITLE
Docs: Broken link for "Disabled inactive state by setting opacity" demo

### ISSUE THREAD

**Issue by mateuszkornecki** [highcharts/highcharts#12943]
#### Actual behaviour
Visit this page: https://api.highcharts.com/highcharts/series.line.states.inactive and click on  ["Disabled inactive state by setting opacity"](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/series-states-inactive-opacity)

The following error will appear:
```
Invalid Github Response
Github responded with unexpected status code: 403 (Forbidden), please try again later.
```

#### Product version
Docs
#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Thanks! It will be fixed in the next release.

Correct URL: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/series-states-inactive-disabled

*Internal note:*
Demos are taken directly from master branch, while API is generated when new version is released. Related PR: https://github.com/highcharts/highcharts/pull/12704
