### ISSUE TITLE
mouseOut may not work with fast mouse movement

### ISSUE THREAD

**Issue by otsybulsky** [highcharts/highcharts#12998]
#### Expected behaviour
mouseOut event must work regardless of the speed of the mouse

#### Actual behaviour
When a browser opens in a small window and i moves the mouse very quickly from left to right through the chart, mouseOut event often does not work. 

#### Live demo with steps to reproduce
[standard sample](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/series-point-events-mouseover/)

[Screen record with freezing effect](https://gofile.io/?c=bH1A9D)

#### Product version
latest

#### Affected browser(s)
Chrome: 80.0.3987.116
MacOSX: 10.15.3

**Comment by pawelfus** [comment]
Hi @otsybulsky 

Thanks for reporting the issue. This is caused by browser events, if you move your mouse really fast, browser will not fire `mouseout` event, for example: https://jsfiddle.net/BlackLabel/wdL5ykav/

`moueover` and `mouseout` are logged in the console:
![out](https://user-images.githubusercontent.com/1453926/75048618-0f4bb180-54c9-11ea-8394-83f9e7f1b3f0.gif)

If that ever changes in the browser, then it will automatically be changed in Highcharts lib.

Note that also depends on mouse's polling rate (perhaps there's specific name for this parameter, that I'm not aware of). While basic mice report 100-200 times their position per second (100-200Hz), gaming ones report ~500 times (500Hz). For example Macbook pro's touchpad has ~124Hz rate. That means if you move low-cost mouse (or touchpad) fast enough then your device may not send even one position update event to the system..

**Comment by otsybulsky** [comment]
This effect seems to be active if the mouse moves quickly out of the browser window. Moving quickly outside the block works well. I think i can only periodically check that the mouse is inside the window. But this should do the user code when needed. Thank you for help!
