### ISSUE TITLE
windbarbs render issue with negatives

### ISSUE THREAD

**Issue by cgalvarino** [highcharts/highcharts#13007]
#### Expected behaviour
Wind barbs render properly with positive x values, but when they are negative, their positions are no longer accurately "onSeries".

E.g. positive:
![image](https://user-images.githubusercontent.com/180985/75075856-c0a01680-54cc-11ea-99d1-301e86b67263.png)

And now for the negative:
![image](https://user-images.githubusercontent.com/180985/75075895-da415e00-54cc-11ea-8c96-fc19676de42a.png)

And it changes again after a show/hide:
![image](https://user-images.githubusercontent.com/180985/75075923-e4635c80-54cc-11ea-93ab-4d58636bcfbd.png)

#### Live demo with steps to reproduce
Working positive x fiddle, https://jsfiddle.net/ztnsgoj6/.
Buggy negative x fiddle, https://jsfiddle.net/vhd3w2n8/.

#### Product version
Highcharts v8.

#### Affected browser(s)
Tested on Chrome

I may attempt to fix this on my own, but for now FYI!

Thx for such a great product.

**Comment by GregJWilliams** [comment]
What is the case for negative values?  
Can't happen with wind speed (ie.  wind blows, doesn't suck)
Can't happen with time (that should always/usually be positive since some reference time)
Can't happen with vector mag (that'll be 0-max not negative)

Maybe true for an individual u or v component of a vector, but we'll never be plotting that by itself.


Separately, are we able to drop the arrowhead?  (wind barbs don't have those)
How much leeway have we got with these symbols?  (should be as close to the map and wind profile barbs as possible)

**Comment by sebastianbochan** [comment]
Hi @cgalvarino,
I agree with @GregJWilliams and really curious how wind can blow with negative value. Could you elaborate your use case?

**Comment by cgalvarino** [comment]
I'll see if I can put together a more realistic example -- please standby.

FWIW I wasn't trying to express wind speeds as negative.  In the crude demos, the y-axis was showing speed (as positive) while the x-axis was the one I was tinkering w/.

**Comment by cgalvarino** [comment]
Going to close this out to get rid of the negative vibe.  See what I did there?

**Comment by cgalvarino** [comment]
https://github.com/highcharts/highcharts/issues/13013
