### ISSUE TITLE
Pie - no animation after update with less data

### ISSUE THREAD

**Issue by mateuszkornecki** [highcharts/highcharts#13022]
#### Expected behaviour
The chart should animate when you update the series with less data. 
The animation should look the same as when we are updating the series with data in which some points were replaced with null.

#### Actual behaviour
The chart does not animate.

#### Live demo with steps to reproduce
Steps to reproduce: 
- Click on the update button (observe that there is no animation)
- Then click on the "back to initial data" button
- Finally, click on the "update with null" button  (that's how animation should look like)
https://jsfiddle.net/BlackLabel/jwf92yep/

#### Product version
Highcharts JS v8.0.0 (2019-12-10)

**Comment by pawelfus** [comment]
That's expected behaviour. `series.update({ data })` works the same way as `series.setData(data)`, so from description: https://api.highcharts.com/class-reference/Highcharts.Series#setData

> Note the difference in behaviour when setting the same amount of points, or a different amount of points, as handled by the updatePoints parameter.

Which is explained:

> When this is true, points will be updated instead of replaced whenever possible. This occurs 
> a) when the updated data is the same length as the existing data,
> b) when points are matched by their id's, or
> c) when points can be matched by X values.
> This allows updating with animation and performs better. In this case, the original array is not passed by reference. Set false to prevent.

The first and the second button don't match any of requirements above. If you simply set `id` for points, so Highcharts will actually understand which point should take which value, then it works as you expect, demo: https://jsfiddle.net/BlackLabel/u3bjc4m1/
