### ISSUE TITLE
v8.0.2bug："venn"  can't be render

### ISSUE THREAD

**Issue by wjhcc2018** [highcharts/highcharts#13084]
#### Expected behaviour
Correctly apply colours to a drawing
#### Actual behaviour

![QQ图片20200305134138](https://user-images.githubusercontent.com/6789138/75951477-128e6680-5ee7-11ea-80fa-3251cbdf1cbd.png)
![QQ图片20200305134714](https://user-images.githubusercontent.com/6789138/75951789-e1626600-5ee7-11ea-8e1c-ff73262417a7.png)

#### Product version

"highcharts": "8.0.1",
    "highcharts-3d": "^0.1.7",
    "highcharts-grouped-categories": "^1.1.3",
    "highcharts-regression": "^2.0.1",
    "highcharts-vue": "^1.3.5",

**Comment by sebastianbochan** [comment]
Hi @wjhcc2018,
Thank you for reporting about the problem. Perhaps, the issue is caused by using Highcharts.Color constructor which should be called by `new`.

Refs:
- https://www.highcharts.com/blog/changelog/
- https://github.com/highcharts/highcharts/issues/13053

Could you update your Highcharts version to 8.0.2 too ? The 8.0.1 is not up-to-date and contains some other problems.

**Comment by wjhcc2018** [comment]
@sebastianbochan  Thanks for your reply.but，I can never  reply it again
