### ISSUE TITLE
pyramid3d render error when width is much larger

### ISSUE THREAD

**Issue by wjhcc2018** [highcharts/highcharts#13099]
#### Expected behaviour
equal scaling
#### Actual behaviour
![QQ图片20200306180343](https://user-images.githubusercontent.com/6789138/76073610-d89b8e00-5fd4-11ea-9378-865b6b150582.png)

#### Live demo with steps to reproduce

https://jshare.com.cn/temp/BPGrXQ
#### Product version

"highcharts": "8.0.2",
    "highcharts-3d": "^0.1.7",
    "highcharts-grouped-categories": "^1.1.3",
    "highcharts-regression": "^2.0.1",
    "highcharts-vue": "^1.3.5",

**Comment by KacperMadej** [comment]
Hi @wjhcc2018 

Thank you for reporting the problem.

This is a known limitation caused by the optimization of the code for better general performance.
The chart that you have created is a rather edge case and the chart won't be very readable or useful for data presentation so it was never optimized.

As a workaround, you could process your data and have more points with equal or similar values to get a better looking 3D pyramid. Demo: https://jsfiddle.net/BlackLabel/6tsqahzw/
