### ISSUE TITLE
https://jshare.com.cn/temp/BCGGiq The bullet diagram shows only the red color of the first stage, only the 300, not the blue color of the second stage and the yellow color of the third stage

### ISSUE THREAD

**Issue by weixingcai** [highcharts/highcharts#13112]

**Comment by sebastianbochan** [comment]
Hi @weixingcai,
Thank you for reporting. Its not a bug, because you declare ranges (0-1500: red, 1500-2250: blue, etc), but your point is 275. As a result only first range is displayed (red). 

For example all ranges are visible when you use data like below: 
```
series: [{
		data: [{
		   y: 2750
                 }]
             }]
```

The solution is declare the `yAxis.max = 3000` value.

For the [support](https://www.highcharts.com/support) questions, please use other channels like forum / stackoverflow or email.

ps. Please use our report bug template. It will allow us to understand problem, better.
