### ISSUE TITLE
Cannot disable highlights in Network Graph

### ISSUE THREAD

**Issue by JohanBrodinSinch** [highcharts/highcharts#13144]
#### Expected behaviour
In the network chart it shall be possible to disable highlights. With many nodes the performance is very bad with highlight turned on which is default.

#### Actual behaviour
Adding the opacity below to the chart do not turn off highlights (which it does in other charts)

    plotOptions: {
        networkgraph: {
            keys: ['from', 'to'],
            enableSimulation: false,
        },
        series: {
          states: {
            inactive: {
              opacity: 1
            }
          }
        }
    },

#### Live demo with steps to reproduce
https://jsfiddle.net/JohanBrodin/go3z7Lyf/16/

#### Product version
Latest 8.0.4

#### Affected browser(s)
Tested on Chrome

**Comment by sebastianbochan** [comment]
Hi @JohanBrodinSinch,
The github is our bug tracker, so for general [support](http://www.highcharts.com/support) questions please use other channels like email / stackoverflow or forum.

ps. you should disable inactive state by [enabled option](https://api.highcharts.com/highcharts/plotOptions.networkgraph.states.inactive).

Demo:
- https://jsfiddle.net/BlackLabel/w2yut7vq/

**Comment by JohanBrodinSinch** [comment]
Hi Sebastian,

Thank you for your quick replay and it is working fine with your suggestion. The reason I thought this was a bug is that opacity works fine disabling highlights in e.g. scatter chart.  I would have expected a consistant behaviour.

/Johan

**Comment by pawelfus** [comment]
Hi @JohanBrodinSinch 

Let's me explain:
Networkgraph is a bit different. In scatter series you use `series.states` because `inactive` state is applied to other series. In networkgraph it's set for the nodes within the same series (unless you use multiple disconnected series in networkgraph). So to disable it (using `opacity`) you should use  [`series.marker.states.inactive`](https://api.highcharts.com/highcharts/series.networkgraph.marker.states.inactive), not `series.states.inactive`.

Anyway, we recommend using `enabled` instead of `opacity` to disable inactive state, because it's faster: instead of setting `opacity` to every node and link, you simply disable the entire state.
