### ISSUE TITLE
The lollipop series - data issue

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#13202]
The suggested data configurations options in the [documentation](https://api.highcharts.com/highcharts/series.lollipop.data) don't work in the lollipop series. The only one which works correctly is an array of y values:

`data: [0, 5, 3, 5]`

The array of objects or an array of arrays doesn't work. 

#### Live demo with steps to reproduce

Demo: https://jsfiddle.net/BlackLabel/bgtLk79s/

#### Product version
Highcharts JS v8.0.4 (2020-03-10)

**Comment by Basts** [comment]
FYI @raf18seb @sebastianbochan

**Comment by raf18seb** [comment]
@Basts Thanks for reporting. The mapping for naming is wrong when inherits from dumbbell series.

**Workarounds:** 
- in case of array of arrays, you can define `series.keys` property: https://jsfiddle.net/BlackLabel/wvr16y4p/
- in case of array of objects, use `low` instead of `y`: https://jsfiddle.net/BlackLabel/5p0n9hoc/
