### ISSUE TITLE
Highcharts Datasorting on line chart, problem on the connections between each point

### ISSUE THREAD

**Issue by vegaelce** [highcharts/highcharts#13212]
#### Expected behaviour
Using the Datasorting option with a type line chart would have the same behaviour than for a column type.

#### Actual behaviour
Points are well placed on the charts but line that connect each point seems to take the initial order (and not the sorted order)

#### Live demo with steps to reproduce
https://jsfiddle.net/vegaelce/jn9c7ubw/

#### Product version
Highcharts 8.0.4

#### Affected browser(s)
all

**Comment by ppotaczek** [comment]
Hi @vegaelce,

The data sorting feature does not affect to the order of points and that's why the line is drawn in this way (the nearest points in the data array are connected). The feature calculates only `x` values for points. 

For now, if you want to use line series in the way you describe, you need to sort data manually.

**Docs:** https://www.highcharts.com/docs/advanced-chart-features/data-sorting

Best regards!
