### ISSUE TITLE
Chart zoom changes while panning on mobile devices

### ISSUE THREAD

**Issue by madepiet** [highcharts/highcharts#13238]
#### Actual behaviour
Scrollbar resets the zoom on mobile devices, I can observe the problem only if the scroll is exactly in this position:
![mobile](https://user-images.githubusercontent.com/39968065/78110018-9a8a6200-73fa-11ea-9519-d0b049c98512.png)

#### Live demo with steps to reproduce
When you open this demo on your phone, by swiping to the right from the full screen, then from the right edge to the left, the graph will constantly increase to 31 Mar, then when you try to swipe to the left from the position presented in the picture the zoom out will fire off.

Live demo:
https://jsfiddle.net/BlackLabel/me82Lcrz/show

#### Product version
Highcharts v8.0.4

#### Affected browser(s)
Chrome on Android | 80.0.3987.149

**Comment by madepiet** [comment]
In case when the right border of the navigator is on the line of 31 of March:
- If you trying to move the chart to the right - chart zoom is changed instead of panning.
![1](https://user-images.githubusercontent.com/39968065/78120081-a6315500-7409-11ea-823d-8b3463c221e5.png)

- You can't zoom out chart correctly with multi-touch on the chart - the right border of the navigator is sticky to the point of 31 of March.
![2](https://user-images.githubusercontent.com/39968065/78120228-d7aa2080-7409-11ea-88cb-1da19a31ffe9.png)

**Comment by sebastianbochan** [comment]
Live steps to reproduce:
 
![steps](https://user-images.githubusercontent.com/2115686/78120501-5dc66700-740a-11ea-8b4f-86a5cc21f8f7.gif)

Reproducible in Chrome + mobile emulator.

The pinch event is triggered instead of panning (also when use two fingers). The `followTouchMove` does not solve the problem too.

**Comment by KimViktor** [comment]
Is there any updates on this issue?

**Comment by sebastianbochan** [comment]
At this moment we do not have ETA for this ticket.

**Comment by karolkolodziej** [comment]
This issue is heavily connected with the `ordinal` axis- #2406.
The panning under the hood uses the `axis.toValue()` method to calculate the new extremes based on how many pixels we pan.

- That method returns incorrect values of the new extremes- changing it only by 10px resets the extremes
Demo: http://jsfiddle.net/BlackLabel/vm0zLewo/
- For the range where we don't use the ordinal it works correctly. However, after a few clicks we hit a wall where the ordinal begins.
Demo: http://jsfiddle.net/BlackLabel/2jrsma9g/
