### ISSUE TITLE
Incomplete problems are displayed when the data in data is long

### ISSUE THREAD

**Issue by weixingcai** [highcharts/highcharts#13239]
# Description of the feature

Incomplete problems are displayed when the data in data is long

# Library related to the feature

https://jshare.com.cn/temp/HdGT6o

# Proof of Concept/ Live example for the feature

https://jshare.com.cn/temp/HdGT6o

**Comment by sebastianbochan** [comment]
Hi @weixingcai 
Thank you for reporting. The github is our bug tracker, so for general [support](https://www.highcharts.com/support) questions please use stackoverflow, email or forum.

1. Please use proper template when you create a ticket (bug instead of feature request).
2. Please use or support channels
3. Let me know if you have any problems with an access to forum / stackoverflow or email.

Im closing the ticket as duplicate of https://github.com/highcharts/highcharts/issues/13157
