### ISSUE TITLE
Time series chart: invalid chart on Safari iOS

### ISSUE THREAD

**Issue by Amro77** [highcharts/highcharts#13242]
Use any web desktop browser 
navigate to https://quran-lights.firebaseapp.com/
login with email: highcharts@quranlights.com
password: 1234567

note charts with label light days per month, dark days per month at the bottom of the page
(this is the correct rendering)

use iOS safari browser <any version but i just tested it o iOS 13>, 
repeat above steps and notice the difference in rendering, here is the bug.

Highcharts 8.0.0 <you can get all info from index.html>

**Comment by sebastianbochan** [comment]
Hi @Amro77,
The github is our bug tracker, so for general [support](http://www.highcharts.com/support) questions please use other channels (stackoverflow / forum or email).

**Comment by Amro77** [comment]
I provided you with bug regeneration steps and you closed the issue without even investigating it!
Nice one.

**Comment by pawelfus** [comment]
Hi @Amro77 

We would really appreciate if you could follow our template for reporting bugs. You posted your whole page, with a vague description of what exactly is wrong (we are working remotely because of corona virus, we don't have access to every device we usually have in the office). If you contact our support team, they will help you with debugging and simplifying demo - reducing issue just to the one chart, with minimal config, instead of ten charts. Sorry for the troubles!
