### ISSUE TITLE
Switching from non-compared to compared does not work

### ISSUE THREAD

**Issue by monzonj** [highcharts/highcharts#13251]
#### Expected behaviour
When the property `plotOptions.series.compare='compare'` is set, the chart should go into compare mode

#### Actual behaviour
This only works if the compare is set on first load, doesn't work if you dynamically update the chart with 'compare'

#### Live demo with steps to reproduce
https://jsfiddle.net/npxyvg6t/3/

#### Product version
Highstock JS v8.0.4 (2020-03-10)

#### Affected browser(s)
Tested in Chrome and Firefox

**Comment by pawelfus** [comment]
Thank you for reporting the issue @monzonj 

**Workaround:**
For initially created series, set compare options in `series` instead of `plotOptions`:
```js
series: [
  {
    compare: 'percent',
    compareBase: 100
  },
  { ... },
  { ... }
]
```
Demo: https://jsfiddle.net/BlackLabel/9bmaxfwz/

**Comment by Izothep** [comment]
I have made some debugging on my end and it looks that the issue is caused by not updating already created series with global options (set in `plotOptions`). 

Another workaround is to "manually" update existing series `compare` option before calling general `chart.update`:
https://jsfiddle.net/BlackLabel/fuh7nwbd/1/

As I can see, the workaround is very similar to one proposed by @pawelfus

**Comment by monzonj** [comment]
> Thank you for reporting the issue @monzonj
> 
> **Workaround:**
> For initially created series, set compare options in `series` instead of `plotOptions`:
> 
> ```js
> series: [
>   {
>     compare: 'percent',
>     compareBase: 100
>   },
>   { ... },
>   { ... }
> ]
> ```
> 
> Demo: https://jsfiddle.net/BlackLabel/9bmaxfwz/

This solution worked for me! Thank you.
