### ISSUE TITLE
Urgent: Bubble Chart DataLabel Missing when bubble is moved

### ISSUE THREAD

**Issue by hartbert95** [highcharts/highcharts#13256]
#### Expected behaviour
All the bubble should display with the proper data labels.

#### Actual behaviour
Sometime bubble data label will disappear when screen resolution changed/bubble is moved

#### Live demo with steps to reproduce
https://stackblitz.com/edit/highchart-angular-chart-p4rhsj

1. Click on Catalog Menu (Codebase: app/views/catalog)
2. Click Render chart
3. Move Bubble 6 to the left of bubble 4 
4. Bubble 4 data label will disappear.

Original
![image](https://user-images.githubusercontent.com/40552612/78515179-68f10c80-77e7-11ea-8c06-3b615e00f8cd.png)

After Bubble Move: 
![image](https://user-images.githubusercontent.com/40552612/78515197-82925400-77e7-11ea-945f-cd6819ac5bfd.png)

#### Product version
Product Version: 8.0.4

#### Affected browser(s)
Chrome

**Comment by Izothep** [comment]
Hi @hartbert95! Thank you for reporting your issue with packed bubble graph.

Actually, the problem you experience is caused by `allowOverlap` feature. By default, dataLabels will hide in case of overlapping. API:
https://api.highcharts.com/highcharts/series.packedbubble.dataLabels.allowOverlap

It is possible to disable this feature by setting `allowOverlap` to `false`. Live example:
https://stackblitz.com/edit/highchart-angular-chart-snnou3?file=app/app.component.ts

**Comment by hartbert95** [comment]
Hi @Izothep , Thanks for your feedback. its work prefectly now.
