### ISSUE TITLE
Urgent: Issue On Update Color when bar clicked

### ISSUE THREAD

**Issue by hartbert95** [highcharts/highcharts#13284]
#### Expected behaviour
When Click on the bar, the previous bar will be change to yellow color and selected bar will change to red color.

#### Actual behaviour
When click on the bar, the chart mess up. its only happen on 8.0.4, if we use 7.1.2, its work fine.
Also when the xAxis type is category, it will have the issue, if datetime or not specified, it will working fine.

#### Live demo with steps to reproduce
To access the chart
1. Click Catalog on the top meu
2. Click render chart
3. click on the bar
4. Codebase: App/views/catalog

https://stackblitz.com/edit/highchart-angular-chart-hnjebu?file=app%2Fviews%2Fcatalog%2Fcatalog.component.ts

#### Product version
Highchart v8.0.4

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @hartbert95,
Thank you for contacting us. The problem is not a bug, but incorrect configuration of data. Instead of using `"projectId"` you should declare `"name"` which is unique for categories.

Fixed demo:
- https://stackblitz.com/edit/highchart-angular-chart-n62eqf?file=app/views/catalog/catalog.component.ts

ps. for the support cases, please use other channels like forum / stackoverflow or email.
