### ISSUE TITLE
Missing table data in export-data module for bubble charts

### ISSUE THREAD

**Issue by weltall** [highcharts/highcharts#13293]
#### Expected behaviour

Directly from the highchart samples https://www.highcharts.com/demo/bubble on the main site i'd expect an export (view data table, export csv and xlsx) should export all the data from the series. Including at least name, x, y, z

#### Actual behaviour
What happens is some of the data is not exported. Specifically the x column, at least, is skipped and we get only the name, y and z column as it can be seen here:
![image](https://user-images.githubusercontent.com/1127663/78909782-4cbdcb80-7a84-11ea-996a-331a94de2eed.png)

#### Live demo with steps to reproduce
 https://www.highcharts.com/demo/bubble try to use export-data.js functionalities from the menu.

#### Product version
highchart 8.0.4

#### Affected browser(s)
Seems to affect all (i tried firefox and chrome last version, ie 11, edge

**Comment by pawelfus** [comment]
Hi @weltall 

Thank you for reporting this bug.

**Workaround:**
Set `series.keys = ['x', 'y', 'z']`
Demo: https://jsfiddle.net/BlackLabel/v12gdtb9/

**Comment by Basts** [comment]
After digging into this issue below are proposals of solutions which I would discuss. The main problem is with this line https://github.com/highcharts/highcharts/blob/master/ts/modules/export-data.src.ts#L536 -> `pointArrayMap = keys || series.pointArrayMap || ['y']` and `series.pointArrayMap` which in this case doesn't include the 'x'.

1. Leave it as it - by default when point doesn't have the `name` property the 'x' value is rendered under the `category` header, but the user has control of what should be displayed in the table by defining the `keys`. Demo: http://jsfiddle.net/BlackLabel/oksp4L7t/

2. Create a function which will check if data has defined name in the series (this functionality could be change - it is just a proposal). It is easy to see what I have in mind in the demo (line 68-83 and 92-94). 

Demo: http://jsfiddle.net/BlackLabel/mog4d9wc/

@oysteinmoseng @TorsteinHonsi

**Comment by sebastianbochan** [comment]
Im close to solution from point 1, which seems to be more optimal and does not require overwriting methods or create one one.

**Comment by TorsteinHonsi** [comment]
I think the logical problem here is that we assume that `name` is a replacement for `x`, which is usually true in category axes. But in the OP example, the X axis is not a category axis, and the name and the x value are two different dimensions.

Can you try a simple solution where you apply the current name-for-x replacement _only_ if the axis is a category axis? Let's see how that affects the rest of the unit tests.

**Comment by Basts** [comment]
@TorsteinHonsi 
Thank you for your suggestion. 

Could you confirm if this a result which you want to achieve? Demo: http://jsfiddle.net/BlackLabel/js8k176f/

* If xAxis is NOT a category type -> use x value for the first rows

* If xAxis is a category type -> use the name for the first rows and SHOW the x value in the rows (I think that this is the main reason why ticket has been opened). Or x value should be hidden for the category axis and the user has the ability to control the visibility of it by using `keys` property?

Please uncomment the `xAxis.type` to see what I had in mind.

With this solution there are a few problems:
1. Changing type to `category` changes the xAxis readability which might be not a wanted result,
2. Some tests will require the changes if this solution will be accepted, like: https://github.com/highcharts/highcharts/blob/master/samples/unit-tests/export-data/basics/demo.js#L50

**Comment by TorsteinHonsi** [comment]
I think it should be the other way around.

1. If `xAxis` is NOT a category type. Add separate columns for `name` and `x`. Currently it shows `name || x`.
2. If `xAxis` is a category type. Show `name || x` like we currently do. Because in this scenario, `x` in reality is just the index of the category.

**Comment by Basts** [comment]
@TorsteinHonsi 

Thank you for a response, you are right - it makes more sense.

May I ask you to test this demo to check if this is a functionality which should I implement?

Demo: http://jsfiddle.net/BlackLabel/36L402wj/

1. `xAxis` is NOT a category and point doesn't have the name -> don't render the `Category` column, just show `x and y`, 
2. `xAxis` is NOT a category and point have defined name -> render the `Category` column with defined name and show `x and y`,
3. `xAxis` is a category type -> show `name || x` like currently we do,

This solution would require some changes in the tests because depending on config the `Category` column will be rendered or not.
