### ISSUE TITLE
Annotation lingers when zoomed

### ISSUE THREAD

**Issue by HonorSprenVG** [highcharts/highcharts#13298]
note: this seems related to #7826, however it is observed in version 7.1.1
#### Expected behaviour
1. When an annotation is added to a combination chart
2. and the user zooms in on that chart
3. then the user clicks on the legend to hide the series that the annotation is linked to 
4. the annotation is hidden as well

#### Actual behaviour
1. When an annotation is added to a combination chart
2. and the user zooms in on that chart
3. then the user clicks on the legend to hide the series that the annotation is linked to 
4. the annotation continues to display
note, if the series is hidden prior to zooming, the annotation becomes invisible as expected. 

#### Live demo with steps to reproduce
https://jsfiddle.net/Kaorie/c28e9dsv/
steps:
1. click on a point or column to select
2. click the "addAnnotation" button
3. hide, then un-hide the appropriate series to confirm that the annotation hides as expected
4. with both series displayed, zoom in on a section of the chart containing the annotation
5. hide the appropriate series
6. observe that the annotation is not appropriately hidden

#### Product version
from my package-lock.json file:
    "angular-highcharts": {
      "version": "6.2.6",
      "resolved": "https://registry.npmjs.org/angular-highcharts/-/angular-highcharts-6.2.6.tgz",
      "integrity": "sha512-KSNDsvopSsnvKlHvFcP99qJqOnSAJwj9M9fWDn8lzYqTtpZpUA6KWzPGW8cxg+EBuCIICvnsPoapV6LRRL+c0w=="
    },
    "highcharts": {
      "version": "7.1.1",
      "resolved": "https://pkgs.dev.azure.com/eysbp-helix/_packaging/Helix-release/npm/registry/highcharts/-/highcharts-7.1.1.tgz",
      "integrity": "sha1-jEQz451efb3AZGhdlUgYGjXhLBk="
    },
    "highcharts-angular": {
      "version": "2.4.0",
      "resolved": "https://pkgs.dev.azure.com/eysbp-helix/_packaging/Helix-release/npm/registry/highcharts-angular/-/highcharts-angular-2.4.0.tgz",
      "integrity": "sha1-z6hhyK5gJ0CApau/1AV6MjyOoA8=",
      "requires": {
        "tslib": "^1.9.0"
      }
    },

#### Affected browser(s)
confirmed that this is an issue in chrome, edge, ie, and firefox

**Comment by pawelfus** [comment]
Hi @HonorSprenVG 

This is expected behaviour: annotation is hidden when extremes on the chart are not set. When you zoom-in, you can observe that xAxis and yAxis labels are still visible, so hiding series does not affect an annotation. When you zoom out, you won't see the extremes on axes, so annotation is hidden.

Instead of linking an annotation to xAxis and yAxis, you can link your annotation to the specific point, using `point.id`. Simple example: https://jsfiddle.net/BlackLabel/v3qt4zg8/ - note that all points require unique ID. You can also notice the code is simplified.

**Comment by HonorSprenVG** [comment]
Thanks for the assist.
