### ISSUE TITLE
is it possible to set highstock navigator's xAxis.type = category like Highcharts.chart?

### ISSUE THREAD

**Issue by 016** [highcharts/highcharts#13321]
Hey, thx for your work, highcharts are amazing...., but I have a problem with highstock.navagator.xAxis.type

#### Say I have data like this
[{'2020-01-01', 12}, {'2020-01-02', 44}, ...]

#### Problem
if I use "Highcharts.chart.xAxis.type='category' ", it will show "2020-01-*" as xAxis, it's working for both Highcharts.chart and Highcharts.stockChart, but's it's not working for Highcharts.stockChart.navigator

#### More Detail
first. I can't find Highcharts.stockChart.navigator.xAxis.type in the api, and if I set it to 'category', will not working
Second. the this.value in navigator.xAxis.lable.format are 0, 5, 10, 15 ...., so somehow the value is wrong...

I know I can format the date to unix unix timestamp or set categories to fix it, but I am thinking maybe it's a bug, the xAxis in navigator should the same with xAxis in Highcharts.chart

I am new to the highcharts, so if anything I forgot in config plz let me know, if it's a bug, plz fix it.

thx for your working.

**Comment by pawelfus** [comment]
Hi @016 

Welcome in Highcharts! :) It's really nice to see that you did check our API (there's no `navigator.xAxis.type` option, so it's always `'datetime'` type). You can imitate categorized xAxis, but it won't work 100% as category axis, useful options:
- https://api.highcharts.com/highstock/navigator.xAxis.tickInterval
- https://api.highcharts.com/highstock/navigator.xAxis.units
- https://api.highcharts.com/highstock/navigator.xAxis.ordinal
- https://api.highcharts.com/highstock/navigator.xAxis.labels.formatter

And you can think of categorized xAxis as a datetime xAxis with 1 ms = 1 category.

In case of further problems, or if you find a bug, but you are not sure if that's expected behaviour, then please use our other support channels (Forum, StackOverflow, contact us directly): https://www.highcharts.com/blog/support/

**Comment by 016** [comment]
@pawelfus hey, thx for your response, right now I am using unix timestamp as date now, it's working good, the api links are useful thx again. just hope you guys can upgrade this point in the future.

btw, I tested navigator.xAxis.categories, it's working too, so somehow use it can solve the problem.

**Comment by pawelfus** [comment]
I'm glad to hear that!
