### ISSUE TITLE
Custom patterns turn black filling after chart export in Safari 

### ISSUE THREAD

**Issue by hakansemerci** [highcharts/highcharts#13327]
There are several points:
- Custom color patterns
- Export PNG/JPEG
- Safari browser only

#### Expected behaviour
The patterns should continue showing properly after export

#### Actual behaviour
The patterns are lost and turn black filling on hover after export
![image](https://user-images.githubusercontent.com/31401102/79438635-13311700-7fd4-11ea-82be-98bd362e9eb6.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/hakansemerci/0d9ob1xf/44/
- Open fiddle in Safari
- Export to PNG or JPEG using burger menu
- Hover over the chart or legend 
- Alternately, click on a legend to hide category then click again to show it

#### Other info / Workarounds
Does not reproduce on Highcharts 6.2.0
Works well on Chrome, Firefox
Does not reproduce when patternIndex is used

#### Product version
Highcharts 8.0.4

#### Affected browser(s)
Safari 13.1

**Comment by shayanlinux** [comment]
We appreciate it if a workaround (e.g., a patch that we can apply without upgrading HighCharts) is also provided as remediation.

**Comment by sebastianbochan** [comment]
Hi @shayanlinux,
Thank you for reporting about the problem.

_Internal note_
Can be related with https://github.com/highcharts/highcharts/issues/8658 too.
FYI @oysteinmoseng

**Comment by oysteinmoseng** [comment]
@shayanlinux Here is a workaround: Simply add `Highcharts.Chart.prototype.updateContainerScaling = function () {};` before creating the chart. This assumes you are not creating charts inside containers with CSS scale transforms or CSS zoom.

**Internal note**: This is pretty obscure, but seems to be caused by calling `getSVG()` and creating a duplicate chart, but only after [this commit](https://github.com/highcharts/highcharts/commit/d047224fe6acbbce045ae0b85321d69c04636cbb). Maybe a caching issue with Safari?

**Comment by Izothep** [comment]
After some deeper investigation, it looks that the problem is related directly to caching issue when creating (and next destroying) graph via `getSVG` method. 

Possible solution is to create copy of data on export, using approach similar to:
`seriesOptions.data = H.extend([], true, seriesOptions.data);`

But it looks to be the Safari issue more than Highcharts.
