### ISSUE TITLE
Markers are partially or completely clipped off the top of charts

### ISSUE THREAD

**Issue by zlabz** [highcharts/highcharts#13348]
#### Expected behaviour
The chart size should correctly take the height of the markers into account so they are not clipped off the top

#### Actual behaviour
Markers are are partially or completely clipped off the top of charts

#### Live demo with steps to reproduce
see attachments

#### Product version
latest version

#### Affected browser(s)
Chrome
![Annotation 2020-04-20 102923](https://user-images.githubusercontent.com/4699273/79781097-d45fd180-82f1-11ea-9b4d-d2b0eb5cbc5d.png)

![picturemessage_2xq2u0fo f4d](https://user-images.githubusercontent.com/4699273/79780975-9e225200-82f1-11ea-8055-389ee2d33cad.png)

**Comment by sebastianbochan** [comment]
Hi @zlabz,
Thank you for reporting. When I run our demos, I was not able to reproduce the problem.

Could you update my demo: https://jsfiddle.net/BlackLabel/85yksj76/ with your simplified code? It will allow me to debug and find a solution.

**Comment by sebastianbochan** [comment]
Hi @zlabz,
Thank you for details on support channel.

I simplified your use case here:
- https://jsfiddle.net/BlackLabel/d2gopm5y/

Flag are clipped to plotarea.

This is default functionality like i.e in bubble charts: https://jsfiddle.net/BlackLabel/zf7Lngq1/.

If you would like to show the whole shapes "out of plotarea", you should use the [clip](https://jsfiddle.net/BlackLabel/zf7Lngq1/) option (set it as false).

Demo:
- https://jsfiddle.net/BlackLabel/krxqo5h4/

Summarising, I would not consider it as a bug, because of default functionality.

**Comment by zlabz** [comment]
Thanks.  The clip flag helps.
