### ISSUE TITLE
Axis-title is not accessible to narrator issue. 

### ISSUE THREAD

**Issue by v-abkhot** [highcharts/highcharts#13346]
#### Expected behaviour
While focus is on graph x-axis and y-axis tile should accessible for narrator

#### Actual behaviour
While focus is on graph x-axis and y-axis tile is not accessible for narrator

**Comment by sebastianbochan** [comment]
HI @v-abkhot,
Thank you for reporting.

FYI @oysteinmoseng

**Comment by v-abkhot** [comment]
when can we expect bug fix ?

**Comment by oysteinmoseng** [comment]
@v-abkhot This is actually by design, since our user testing with screen reader users has shown that exposing the axis titles with no context is not intuitive. Instead, the axis information is available in the information region before the chart, which causes less confusion and helps the screen reader users decide whether or not to dive deeper into the charts.

The downside is that some low vision users might expect to be able to hover over the axis titles to read them, but this goes for any of the labels in a chart. Unfortunately this is one of the situations where we have to find a compromise.
