### ISSUE TITLE
Draw a chart without any series

### ISSUE THREAD

**Issue by madepiet** [highcharts/highcharts#13340]
#### Expected behaviour
The ability to display xAxis and yAxis and operate on min and max values without having to declare an empty series.
![1](https://user-images.githubusercontent.com/39968065/79586321-3d1c3380-80d1-11ea-8a72-079edeaf65bb.png)

#### Actual behaviour
We are unable to display axes and set min and max without declaring `series: [{}]`

Related with: https://github.com/highcharts/highcharts/issues/2408

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/mrgpavkd/

#### Product version
v8.0.4

**Comment by pawelfus** [comment]
There's already an option to control that: https://api.highcharts.com/highcharts/chart.showAxes - https://jsfiddle.net/BlackLabel/mrgpavkd/2/

Good starting point: `axis.setScale` does not set `min` and `max` because the condition is not met (axis is not dirty, linked, aligned to others, forced to redraw etc).
