### ISSUE TITLE
Highcharts maps from SVG sources is not working

### ISSUE THREAD

**Issue by madepiet** [highcharts/highcharts#13386]
#### Expected behaviour
Correct site operation - the ability to generate maps.

#### Actual behaviour
Incorrect site operation - no possibility of generating maps, errors in the console.
https://www.highcharts.com/studies/map-from-svg.htm

#### Product version
v8.0.4

#### Affected browser(s)
All

**Comment by Denyllon** [comment]
This tool was just moved from this repository to a separate one, and also has been fixed in https://github.com/highcharts/highcharts/commit/b52a2ae8524c80c7782841c783148015e6b89ad2. Here is the link to the new site: https://highcharts.github.io/map-from-svg

Related to https://github.com/highcharts/highcharts/issues/6654

As Torstein mentioned in the above issue, the old site has a redirection set, but will be active until the next release.
