### ISSUE TITLE
Dynamic change of timezone offset works only once

### ISSUE THREAD

**Issue by vodess** [highcharts/highcharts#13390]
#### Expected behaviour
When timezoneOffset property is changed, it should be reflected in the chart, for example the x axis should shift accordingly.

#### Actual behaviour
In provided example the x axis shifts only after first change of the timezoneOffset option. Any other changes are ignored.

#### Live demo with steps to reproduce
[Demo](https://jsfiddle.net/0onk4xap/3/)
The Change timezone offset button toggles the offset from 360 to 60.

![image](https://user-images.githubusercontent.com/15703819/80503465-306dca00-8972-11ea-8fec-5e726ea9e9f0.png)

![image](https://user-images.githubusercontent.com/15703819/80503654-7591fc00-8972-11ea-8b14-b8f0b45f761a.png)

![image](https://user-images.githubusercontent.com/15703819/80503814-b12cc600-8972-11ea-89c8-0116b9e628ee.png)

#### Product version
Highcharts 8.0.4

#### Affected browser(s)
all

**Comment by sebastianbochan** [comment]
Hi @vodess,
Thank you for reporting. Let me explain how setOptions works. `Highcharts.setOptions()` applies options for all charts before init. After that you cannot update them "on tle fly", because overwrites global settings of a chart. If you would like to change, you need to destroy chart and create a new one.

This is default functionality, so we cannot consider this problem as a bug.

**Comment by vodess** [comment]
Hi @sebastianbochan,

thank you for looking into this. 
Indeed, you're right, when I replaced the setOptions call with update one, it works well. The problem I'm facing is therefore maybe in the wrapper library highcharts-angular. I will make some more investigation and report an issue in the sub repo if needed.

I believe you can close this one for now.

**Comment by sebastianbochan** [comment]
Thank you for the feedback!
