### ISSUE TITLE
Regression: Reset zoom button appears on dragging random elements

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#13426]
#### Expected behaviour
No reset zoom button when not zooming

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/studies/puzzle/
=> Drag one of the items, and the button pops up

#### Product version
Pre-production, v8.0.4 worked, bisected to dbc2aec5e186d63b8216314ac2b16828904b9398

@Denyllon

**Comment by TorsteinHonsi** [comment]
Any progress?

**Comment by Denyllon** [comment]
Yes, I should push suggested changes by the end of day tomorrow. The problem required a deeper understanding of calculating `paddedMin` and `paddedMax` logic, because it caused unexpected trigger of panning action. Basically, the problem exists for a while, and showing the reset zoom button when panning just make the problem came to light.
