### ISSUE TITLE
No animation in another chart produced by the same code.

### ISSUE THREAD

**Issue by max0x7ba** [highcharts/highcharts#13454]
There is page https://max0x7ba.github.io/atomic_queue/html/benchmarks.html with two column charts displayed by the same piece of code with animations enabled, but chart data is different. The charts change the scale when clicking on the chart background by switching type from linear to logarithmic and back. The 1st chart changes the scale with animation, the 2nd one has no animation. What am I doing wrong that the 2nd chart has no animation, please?

#### Expected behaviour
Animation in both charts when changing scale.

#### Actual behaviour
Only one chart displays animation.

#### Live demo with steps to reproduce
https://max0x7ba.github.io/atomic_queue/html/benchmarks.html

Click on "Scalability on Intel i9-9900KS" chart background to change scale and observe animation.
Click on "Scalability on Intel Xeon Gold 6132" chart background to change scale and observe no animation.

#### Product version
`<script src="https://code.highcharts.com/highcharts.js"></script>`

#### Affected browser(s)
Google Chrome for Linux, Google Chrome for Android, Firefox for Linux, all versions since 2019. The project came into existence in 2019.

**Comment by pawelfus** [comment]
Hi @max0x7ba 

Thanks for choosing Highcharts! This is caused by [`animationLimit`](https://api.highcharts.com/highcharts/series.column.animationLimit) option. By default it equals to 250 per chart (first chart has ~150 points, the second one 250+). Increase that value to allow animation (note that animating e.g. 10k points may be laggy on old PC's or low-end mobile devices).
