### ISSUE TITLE
"rangeSelector.inputEditDateFormat" is broken in Firefox

### ISSUE THREAD

**Issue by quickdrawmcballs** [highcharts/highcharts#13474]
#### Expected behaviour
Changing the value of "inputEditDateFormat" to something other than the default (ex: '%m-%d-%Y') should allow the user to change "From" or "To" input (in the new specified format) and work as intended (i.e. trigger the setExtremes Event and zoom in)

#### Actual behaviour
The text entered by the user will revert to the chart min/max or simply default to previous value.  The afterSetExtremes event shows that the user entered values are ignored.

#### Live demo with steps to reproduce
From a Firefox browser, load this [demo](https://www.highcharts.com/stock/demo/data-grouping) into [JSFiddle](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/data-grouping/)

- In the Javascript panel, add the following to rangeSelector section: "inputEditDateFormat: '%m-%d-%Y'"
- reload the chart
- change the "From" input value
-- BUG Occurs here

#### Product version
"highcharts": "8.1.0",

#### Affected browser(s)
Firefox 76.0 and Firefox 68.8.0esr

**Comment by pawelfus** [comment]
Hi @quickdrawmcballs 

Thank you for reporting the issue. This is caused by Firefox's missing support for `%m-%d-%Y` format. Open JS console an type:
> Date.parse('07-01-2017')
< NaN

In Chrome, the result is:
> Date.parse('07-01-2017')
< 1498860000000

If you want to use custom format that is not supported by some browsers, then please use [`rangeSelector.inputDateParser`](https://api.highcharts.com/highstock/rangeSelector.inputDateParser).
