### ISSUE TITLE
Chart data not visible if series is updated with less data after manually moving with the navigator.

### ISSUE THREAD

**Issue by prdatur** [highcharts/highcharts#13505]
#### Expected behaviour

After updating the series data (removing data), the chart should be visible with the new data.

#### Actual behaviour

The chart data is not visible, also the navigation is empty, after manual zooming/moving with the navigator the chart data becomes visible again.
This only happens if the navigator was manually moved/zoomed before.

**Edit**:
Just to provide more information:
workingData = The data is still within the "old" visible range.
errorData = The old visible range has no data anymore.

So it seems that, after moving / zooming the navigator a "manual" moved flag is set on the navigator and therefore it does not adjust the visible range to the new boundaries and want's to display the old data which is now empty.

#### Live demo with steps to reproduce
http://jsfiddle.net/ab5p6u9x/1/

Without moving the navigator it works as expected.

Click on "update with working data" -> chart data is visible as expected
Click on "update with error data" -> chart data is visible as expected

move or zoom the navigator 1m.

Click on "update with working data" -> chart data is visible as expected
Click on "update with error data" -> chart data is **NOT** visible which is the error.

#### Product version
Highstock JS v8.1.0 (2020-05-05)

#### Affected browser(s)
All, Tested in Firefox linux + win, Chrome linux + win, Chromeium linux.

**Comment by sebastianbochan** [comment]
Hi @prdatur,
Thank you for reporting. The reason of the problem is that you remove series, but not reset extremes on xAxis, as a result navigator still keep the old extremes.

You have two solutions:
1) Call the `xAxis.setExtremes()` after addSeries
2) use `setData`

Demo:
- http://jsfiddle.net/BlackLabel/ftoyv4g7/

**Comment by prdatur** [comment]
Hi @sebastianbochan 
Thanks for answering, I can understand that the above recommendations could fix the problem, but I still think this is a core problem. Otherwise it should also not work if the navigator left without changing.
The extremes are also set while just loading the chart, through the navigator selectedRange, so it is also bounded within a specific time range the same as manually moving the navigator. 
Removing / Adding series works perfectly, only if the navigator range is manually changed it has the issue. 
So it should work in both variants the same, display all the time **nothing** or display all the time **everything correct** with the respect of boundaries given by available data.
Additional if the chart is loaded with the _working_ data, it also bounds the extremes to the less data on the right side. If your answer would be strict, the chart would need to display half of the data empty.

By the way, your demo shows another bug. If you click on "error data" it set's the data correctly with less points, clicking on complete data, it displays the complete data again (correct), if you then click on the "error" data again, it will **NOT** remove the data, instead it will extend the navigator range a bit to the left.

**Comment by sebastianbochan** [comment]
Hi @prdatur,
Thank you for the feedback. 

Im not sure if we can consider it as a bug, because it looks like that extremes set by user (on navigator) have the highest priority and are not "reset" when data is updated. So when data is updated, the extremes are still "remembered" and user should take care about new extremes.

@TorsteinHonsi what do you think? Should we consider it as a bug?

**Comment by prdatur** [comment]
Just a short additional info, as @sebastianbochan said, setting the extremes with the navigator will mark it has "changed by user", which then should also be set if the user clicks on the navigator buttons.

As a developer we see navigator options as possible "preset" of ranges which will be set on clicking on that navigator button and it will be the same as if the user would resizes and moves the navigator manually to exact the same range, also highcharts shows this, if a user resizes it to 1 month and a navigator button exists with 1 month range it will be highlighted.

I would completely understand if I would set the extremes in code manually, because the developer choosed to set the extremes, he has to consider possible required data updates which are not anymore in range.

**Comment by TorsteinHonsi** [comment]
Internally moving the range selector or navigator causes the `userMin` and `userMax` Axis properties to be set. 

We could consider resetting these properties if the new data is outside the range of `userMin` and `userMax`, though I'm not sure what consequences it would have. 

In essence, the problem described in this issue is the same as setting a min and max outside the data range, like here https://jsfiddle.net/highcharts/dc9y4gfn/ . Which is obviously not good practice, but not a bug either. So I'm leaning towards the conclusion that this is not a bug and that the implementer should reset the extremes programmatically like Sebastian suggests.

**Comment by prdatur** [comment]
Your example is what I wrote in the last comment in the last sentence. If a developer setting the min / max or other properties manually then the developer also need to handle possible out of range data and reset the min max if required.

However I still think it should be handled differently if a user changes something or if the developer is setting some options. 

You said "it is the same" but that shouldn't be the same. What should be same is the range change with the navigator and a click on a navigator button. Those actions are the same, because the **user** chooses a range manually, just in a different way, one with a preset and one without.

But I understand if a "fix" would need to many code / core changes, then it would be extremly helpfull to document this within the docu, maybe at the navigator documentation. So other developers will know that a navigator bar change is not the same as a navigator button change and that the developer needs to fix extremes.

Maybe it would be a good practice text to let developer know that every time data changes they are required to verify that the current extrmes (no matter how it was set) is not out of range, because we can not check if the user has changed the range by button or by the "bar".

What you think?
