### ISSUE TITLE
softThreshold not working as expected

### ISSUE THREAD

**Issue by drmrbrewer** [highcharts/highcharts#13538]
From [the docs](https://api.highcharts.com/highcharts/plotOptions.series.softThreshold):

> if `softThreshold` is `false`, a series of 0, 1, 2, 3 will make the Y axis show negative values according to the `minPadding` option.

But in the following example the `minPadding` option doesn't have any effect (the Y axis does *not* go negative as promised) despite having set `softThreshold` to `false` and using the exact same series data as per the docs: http://jsfiddle.net/hw81jcvt/

BTW to me this option is named the wrong way round.  For me, if a threshold is "soft" (i.e. `softThreshold` is `true`) then the series should be able to cross over the threshold, because the threshold is soft not hard.  A hard threshold is one that cannot be crossed.  But this option is the other way round: 

> When `softThreshold` is `true`, the series will not cause the Y axis to cross the zero plane

**Comment by pawelfus** [comment]
Hi @drmrbrewer 

Thanks for reporting the issue.

*Internal note:*
It works fine with other values for `threshold`, eg: http://jsfiddle.net/BlackLabel/8srpqLak/ - perhaps it's a bug with falsy value (0).

**Comment by drmrbrewer** [comment]
@pawelfus I'm not so sure about that.  Maybe it works in your example because the data already crosses the threshold?  See the following example with non-zero threshold but with data that still lies only above the threshold... minPadding is ignored... axis doesn't go negative (or even below threshold): http://jsfiddle.net/4urmoq6t/

**Comment by TorsteinHonsi** [comment]
Setting the `threshold` to `null` also fixes the problem: http://jsfiddle.net/highcharts/mstv7epg/1/

**Comment by Izothep** [comment]
**Internal Note:**

I believe that the issue is related to below part of code:

```
// Adjust to hard threshold
if (!softThreshold && defined(threshold)) {
    if ((axis.dataMin as any) >= (threshold as any)) {
        thresholdMin = threshold;
        minPadding = 0;
    } else if ((axis.dataMax as any) <= (threshold as any)) {
        thresholdMax = threshold;
        maxPadding = 0;
    }
}
```
It looks that removing lines where `maxPadding` and `minPadding` are set to 0 will solve the problem. However, I am not sure if it was not intended.

**Comment by TorsteinHonsi** [comment]
Removing that code fixes this problem, but the consequence is that the hard threshold is not respected in default configurations of series types like area and column, where `softThreshold` is false by default.

In the OP, the `threshold` is actually set to 0, and that is why the `softThreshold` is overridden. Remove the `threshold` option, and the chart works like expected.

> BTW to me this option is named the wrong way round

The word is _soft_ because the threshold depends on the data:

> When this is true, the series will not cause the Y axis to cross the zero plane (or [threshold](#plotOptions.series.threshold) option) unless the data actually crosses the plane.

It does not cause the Y axis to cross the threshold _unless_ the data actually crosses. 

### Suggestion
I suggest that we add this to the description of the `softThreshold` in the API.

"Setting the `threshold` option to a number will override the `softThreshold`."

Do you agree, @drmrbrewer and @Izothep ?

**Comment by drmrbrewer** [comment]
@TorsteinHonsi I guess it might be factually correct but it still doesn't address the overall issue I have with the interaction between these various settings.  Maybe I'm misunderstanding the intention here, but it just seems to be non-intuitive.  If I want to have a variable y axis scaling, but also have the ability to set padding, and also set a specific threshold, then we have a situation where the padding applies if the data crosses the threshold but suddenly it doesn't if the data is all above the threshold.  This isn't great when the data is real-time and dynamic and you don't know where it will lie in relation to the threshold.

**Comment by TorsteinHonsi** [comment]
Thanks for replying!

First a little history to understand what the intention of the `softThreshold` is. When we published Highcharts Cloud some years ago, we would see a lot of line charts used for data that could not be negative. Imagine for example a stock price history, and a chart [looking like this](https://jsfiddle.net/highcharts/dzsf67eh/) with the Y axis having negative values. Clearly not optimal. So we created this default setting that if the data didn't cross the threshold, the axis shouldn't cross the threshold either. And it is a soft threshold because if the data is, for example 1001, 1002, 1003, no threshold is applied. It is only applied in the case when the data is close to the threshold, but not crossing it.

> If I want to have a variable y axis scaling, but also have the ability to set padding, and also set a specific threshold, then we have a situation where the padding applies if the data crosses the threshold but suddenly it doesn't if the data is all above the threshold. 

I guess what we haven't foreseen is why you would use a `threshold` in this case. Can you explain that a bit? If you use a threshold but still want to set a padding - what is the threshold for?

**Comment by drmrbrewer** [comment]
> Imagine for example a stock price history, and a chart [looking like this](https://jsfiddle.net/highcharts/dzsf67eh/) with the Y axis having negative values. Clearly not optimal.

But if the data *can* go negative (e.g. temperature in deg C) then the viewer would not find the negative start to the y axis surprising, because they know that temperature can drop below zero, even if a stock price cannot.  So if your plot was temperature, I would argue that it looks fine as it is.  As a stock price, it is not fine.

> If you use a threshold but still want to set a padding - what is the threshold for?

Example:

https://jsfiddle.net/pvgLcyq4/

Just like any other curve that does not rely on a threshold, I want to be able to have a variable axis scale, and the ability to control the positioning using padding.  The above places the curve nicely centred vertically, and this will be the case regardless of the data.

Except that if you change the first line to `addPoint = false` then suddenly the axis scaling completely flips over to a new regime... just because the data no longer dips slightly under the threshold.  This behaviour is driving me crazy.  I can work around it with custom tick positioners, but it's a pain because I'd rather rely on the default logic for positioning of ticks because otherwise it gets messy.  It seems like it *should* just work out of the box.

**Comment by TorsteinHonsi** [comment]
Sorry for the late reply. It was a bit hard to wrap my head around this one, but I think it boils down to area and column charts having the wrong default value, and hence the implemention was wrong. They should not have `softThreshold`: false by default - it should be true for all series. We'll see if the change affects the visual tests.

In the mean time, can you check the proposed solution with your use cases? http://jsfiddle.net/highcharts/qctn4jgL/

> So if your plot was temperature, I would argue that it looks fine as it is. As a stock price, it is not fine.

Yes, that's why we made it an _option_. The thing with options is that we need to pick a sensible default based on what we know. So when we have a data series like that, we assessed it safer to apply a soft threshold at 0. After all, a temperature axis thresholding at 32F is better than a stock (or any unsigned data type, which is very common) axis going below zero. It's a compromise.

**Comment by TorsteinHonsi** [comment]
@drmrbrewer I know it has been a long wait, but some feedback on this would be much appreciated.

**Comment by drmrbrewer** [comment]
@TorsteinHonsi the behaviour seems a bit better for the main use case I have in mind.

The following is the version with the 'fix'... toggle the "below threshold" data point on/off...

https://jsfiddle.net/tL4s6k2j/

Compare that to the behaviour with the current 'stock' version of highcharts:

https://jsfiddle.net/60wrspuv/

With the 'stock' version, the y axis range jumps regardless of whether `softThreshold` is `true` or `false`... i.e. I cannot guarantee that the data series will honour the axis padding values.  

At least with the `fix` version I can set `softThreshold` to `false` and be sure that the series will be positioned at all times based on the axis padding values, regardless of where the data sits relative to the `threshold`.

**Comment by TorsteinHonsi** [comment]
> When softThreshold is set to true, the series does jump around based on the data, but keeping softThreshold set to false avoids this for me.

That's how it is intended. Thanks for testing!

**Comment by drmrbrewer** [comment]
Out of interest, will this fix be in the next release, or is there more testing/verification to do before that?

**Comment by pawelfus** [comment]
Most likely it will be part of the next release (each PR is must pass all tests). There will be some additional testing before releasing too, so fix might be reverted, but if that happens, we rather hot fix it instead of reverting.

**Comment by drmrbrewer** [comment]
OK thanks.  BTW I think the copyright notice in each code file needs updating to refer to `2009-2020` rather than `2009-2018`:

![image](https://user-images.githubusercontent.com/9009792/85955743-b5785e00-b978-11ea-993c-7b64ae7f1b89.png)
