### ISSUE TITLE
Responsive chart error

### ISSUE THREAD

**Issue by RuslanAktaev** [highcharts/highcharts#13544]
#### Expected behaviour

I have two series and two yAxis respectivly. If chart width smaller than 500px, only one vertical axis remains, and both of series are connected to it. When I increase the display, the second yAxis appears, and second series should be connected to it. 

#### Actual behaviour

When I reduce the display width, all works properly, but when I increase it, I get an error `#18`:
It seems like series haven't been updated.

![image](https://user-images.githubusercontent.com/24316558/82228419-e792ab00-994a-11ea-8e97-9e5fb056f8b2.png)

#### Live demo with steps to reproduce

http://jsfiddle.net/rsaktaev/pywqu6ot/

Please try to reduce the display, then increase it. Am I doing something wrong?
#### Product version

Hightcharts 8.1

**Comment by sebastianbochan** [comment]
Hi @RuslanAktaev,
Thank you for reporting. It looks like a problem similar to  known bugs which have been already reported in our repo here: https://github.com/highcharts/highcharts/issues/13020 and https://github.com/highcharts/highcharts/issues/13427.

_Internal note_
The setResponsive funtion uses `chart.update()` with oneToOne param, so maybe the problem is there?

**Comment by RuslanAktaev** [comment]
@sebastianbochan thanks for the answer! I fixed problem by adding to the rule.

```
     {
         title: {
         text: ''
      }
                  
```

http://jsfiddle.net/rsaktaev/pywqu6ot/9/
