### ISSUE TITLE
Missing label on pie chart with small values

### ISSUE THREAD

**Issue by cole** [highcharts/highcharts#13579]
#### Expected behaviour

All points in the series have visible data labels.

#### Actual behaviour

Some points below a certain threshold are completely hidden, with no labels.

#### Live demo with steps to reproduce
https://codepen.io/colem/pen/gOaEavd

(two points with a value of 2, "Another Equity Class" and "Short-Term", are not visible)

#### Product version
Highcharts 8.1.0

#### Affected browser(s)
Chrome, Firefox.

I feel like there's a good chance I'm missing a default cutoff threshold, somewhere in the options documentation, but I haven't been able to find it.

**Comment by sebastianbochan** [comment]
Hi @cole,
Thank you for reporting. Let me explain why slices and datalabels are missing. 

1. The slices are not show because of really small y values, which are calculated and transformed to width less then 1px. As a result we are not able to draw the slice.

2. Datalabels are missing due to not enough space (overlapping, cropping etc) and missing points (point 1.)

**Solution:**
You can create a single slice (i.e OTHERS) and apply the drilldown option. It will increase readability and user-experience. 

Demo:
- https://www.highcharts.com/demo/pie-drilldown

**Questions:**
I would like to know how threshold should work, could you elaborate?

**Comment by cole** [comment]
I see, thanks for your response and the suggestion. That is probably the best option for us, I'll look into it further.

I understand why the points aren't drawn, and I see that if I make the container slightly larger the data labels do appear even if the points aren't visible. I would expect though that if I set `dataLabels.allowOverlap` to true, the labels would be drawn, though? That doesn't seem to happen.

Re: a threshold setting... I think what I was thinking there was an option to specify the minimum percentage or absolute value to include labels for. showValuesAbove: "1%" or something. As you point out though I'm not sure how you would draw a point smaller than 1px, if that were to be specified.

**Comment by sebastianbochan** [comment]
At this moment I think that the drilldown is the best option.

Regarding to the `showValuesAbove` I suggest to create a new ticket (template feature request) and if will be voted by other users we will consider to add this feature to the core.

ps. Can I close this ticket?

**Comment by cole** [comment]
@sebastianbochan I think you can close, yes. I'm not sure if that feature is worth adding, but if it's something that would be helpful for us I'll open a feature request 🙂.

**Comment by sebastianbochan** [comment]
We always recomend to create a feature request, because other users can vote for that. If something is popular its a clue for us, what should be implemented in the future.
