### ISSUE TITLE
Gauge and dataLabels.borderWidth

### ISSUE THREAD

**Issue by alkoval** [highcharts/highcharts#13595]
Type gauge.
Set dataLabels.borderWidth to 0 and turned off the title when hovering over the chart. 
If you click on the chart, then change the tab and go back, dataLabels.borderWidth becomes visible.

#### Expected behaviour
dataLabels.borderWidth not visible

#### Actual behaviour
dataLabels.borderWidth visible

#### Live demo with steps to reproduce
https://jsfiddle.net/wm27p6kq/1/
video: https://yadi.sk/i/Gt6trWq0sSVvXg

#### Product version
Highcharts JS v8.1.0 (2020-05-05)

#### Affected browser(s)
Google Chrome

**Comment by sebastianbochan** [comment]
Hi @alkoval,
Thank you for reporting. Could you share your Chrome and OS details, because I was not able to reproduce it.

OSX: 10.14.6 (18G103)
Chrome: 83.0.4103.61

**Comment by pawelfus** [comment]
Tested with:
- Chrome: 83.0.4103.97 (Official Build) (64-bit)
- OSX: 10.13.6 (17G11023)

Most likely caused by accessibility plugin.

**Comment by alkoval** [comment]
Hi @sebastianbochan 
OSX: Windows 10 x64, build 19041.264
Chrome:  83.0.4103.97 (Official Build), (64 bit)

Before switching browser tabs, you need to click on the value of the graph in the center.

**Comment by oysteinmoseng** [comment]
The gauge point is given a focus border, probably due to a focus event fired by the browser that Highcharts picks up. I'll look into it.

**Comment by oysteinmoseng** [comment]
We can not avoid displaying the focus border, as it is needed for accessibility, and if the chart receives focus it is correct to display this. What we should do is introduce a new option for whether or not to display focus borders for the data points, for cases like this where the border can be argued to be unnecessary.

The major issue here is actually that the focus border is not around the data point (gauge needle) at all - because of the way `SVGElement.getBBox()` is calculated. The rotation of the needle element is not taken into account, and this causes issues.

For a quick fix, here is a workaround that stops the displaying of the focus border for data points:
https://jsfiddle.net/kvzwgj0e/1/

**Comment by khlieng** [comment]
Fixed since 8.2.0.
