### ISSUE TITLE
Updating chart.parallelCoordinates: true doesn't work since 8.1.0

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#13608]
#### Expected behaviour
Worked fine in 8.0.4. I expect the chart working when we update the chart with
```
chart: {
      parallelCoordinates: true
}
```

#### Actual behaviour
The chart disappears after update.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/pubng3mz/

#### Product version
8.1.0 (worked fine in 8.0.4)

**Comment by ktakahashimtb** [comment]
Hello Highcharts Team,

I spent some time trying to figure out how this is failing and just want to share what I found (this may have been already figured out, but just in case it can be helpful).

This appears to be failing because wrong values are assigned to `ParallelAxisAdditions.position` in `afterSetOptions` event handler, which results in creating wrong % values for left axis position, and eventually assiging wrong `axis.left` values and wrecking lots of computations.

I see the wrong position assignment happens here (this is not the latest version on master, but when the bug was probably introduced): https://github.com/highcharts/highcharts/commit/cfb4da67c2a1cc70c90ce2897aed170f3bff4c9a?diff=split#diff-7750bf26c0f4297c2a42ecc593f4943aR201

Because 'init' event happens prior to this, new ParallelAxisAdditions objects are created, which do not carry the previous position. Since `parallel.position` is `udefined` at the line from the link above, chart.yAxis.length is assiged to `parallel.position`. Unlike when the chart is created first time, `chart.yAxis.length` no longer chages incrementally from 0, but always the number of yAxis.  So instead of positions being [0, 1, 2, ...,  N-1], it is  now [N, N, N, N ....].

I experimented updating the code this way, which seems to address the issue, or at least the graph does not break after the update.
```
  parallelCoordinates.position = pick(
      parallelCoordinates.position,
      chart.yAxis.indexOf(axis) >= 0 ? chart.yAxis.indexOf(axis) : chart.yAxis.length
  );
```

Best regards,
Kei

**Comment by bre1470** [comment]
Hello @ktakahashimtb ,
Thank you for your help in finding a solution. I looked yesterday into it, but just figured out that something is getting wrong with the position in `afterSetOptions` and the chart functions are lacking some expected counter value in `parallelInfo`. I will keep your idea in mind.

**Comment by bre1470** [comment]
Thank you ones more, @ktakahashimtb ! I could not figure out a better cut down solution for it, so I applied yours to the PR.

**Comment by ktakahashimtb** [comment]
Thank you @bre1470 and @raf18seb for having this issue fixed in a couple days! 🎉  Now, can I ask when the next release (with this fix) is planned 😃 ?

**Comment by sebastianbochan** [comment]
@ktakahashimtb at this moment we do not have ETA of text release, but should be within a few weeks.

**Comment by ktakahashimtb** [comment]
Thank you for the answer @sebastianbochan !
