### ISSUE TITLE
Highmaps: Series data labels are not evidently seen when color and textOutline style is not set. 

### ISSUE THREAD

**Issue by amruta30** [highcharts/highcharts#13627]
#### Expected behaviour
If the series data labels color and text outline style is not set, Highmaps should apply the contrast color correctly i.e. it should check if due to the long string of labels/small size of map bubbles the data labels overlap the white color of map -> Black color should be applied to those labels.
I have referred: https://api.highcharts.com/highcharts/series.column.dataLabels.color also.
I think instead of applying WHITE color directly, the color should be calculated and applied taking these factors into consideration.

#### Actual behaviour
It observed that, for highmaps when series data labels is ON and color, text outline style is not set - WHITE colored data labels are shown. If the data labels are long string or the map bubble size is too small, the WHITE labels are not evidently seen on the white colored background map.

#### Live demo with steps to reproduce
v6.1.1 : https://jsfiddle.net/amrutaJgtp/btm37kno/2/
Latest version: https://jsfiddle.net/amrutaJgtp/btm37kno/3/

#### Product version
All versions

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @amruta30 

My apologies for the late reply. The example you provided is exactly the reason why `textOutline` should be used. Imagine a very simple use case: bubble with diameter=20px and text with width=40px. That means half of the text will be outside the bubble, while the other half will stay within. Like this: https://jsfiddle.net/BlackLabel/ayj0gfro/

![Screen Shot 2020-06-09 at 12 04 12](https://user-images.githubusercontent.com/1453926/84134759-5b573d80-aa49-11ea-8ade-58c494dcbca9.png)

Instead of implementing the logic you suggested, we compare contrast color only with the underlying point, not the surroundings. From [docs](https://api.highcharts.com/highmaps/series.mapbubble.dataLabels.style.color): 
> The default color setting is "contrast", which is a pseudo color that Highcharts picks up and applies the maximum contrast to the underlying point item, for example the bar in a bar chart.

In `mapbubble` series, the underlying point item is of course bubble-marker. 

*Note:*
In your example `textOutline` **is set to 0px**. That's why it's not visible, see demo: https://jsfiddle.net/BlackLabel/Lyfropjv/ (line 77).
