### ISSUE TITLE
Unable to use innerSize in pie series if gauge series is also used

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#13629]
#### Expected behaviour
http://jsfiddle.net/BlackLabel/ab1woy3n/1/

#### Actual behaviour
It is not possible to apply the `innerSize` option in a pie series.

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/ab1woy3n/

#### Product version
Highcharts v8.1.0

#### Affected browser(s)
All
___
_Internal note:_
Broken since v8.0.1

**Comment by chivuandrei** [comment]
https://github.com/ppotaczek this is happening only when ussing series 'pie' and 'gauge'. Other than this is working fine.

**Comment by ppotaczek** [comment]
Bisect leads me to: https://github.com/highcharts/highcharts/commit/5876f04e2899606be943313d03d80431ecd9c685 @PaulDalek

**Comment by PaulDalek** [comment]
This behavior is caused by the following `if` statement from the `getCenter` function of the `CenteredSeriesMixin`:

```
if (chart.angular) {
    positions[3] = 0;
}
```

The `getCenter` is mostly used for gauges and polar charts but it is also used for the pie series. The angular series don't need the `innerSize` set that way but the pie series does. If only one of the series is angular the above condition will be true therefore the `innerSize` will be set to 0 in a pie series too. I'll do the necessary correction. Meanwhile here's a simple example with a workaround:

#### Workaround
http://jsfiddle.net/BlackLabel/hbzvpuxn/
