### ISSUE TITLE
series.pie.color is not changing color

### ISSUE THREAD

**Issue by jychiao** [highcharts/highcharts#13646]
#### Expected behaviour
According to [docs](https://api.highcharts.com/highcharts/series.pie.color), the color of the border in an empty pie chart should be customizable. If I provide a valid hex code, the color of this border should change.

#### Actual behaviour
The border for an empty chart remains `#cccccc` regardless of what I provide this option.

#### Live demo with steps to reproduce
This is the example included in docs: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/pie-emptyseries/

The color `#c0ffee` should be a mint-like color, but you can see the border is not respecting the provided hex code.

#### Product version
Highcharts latest version (8.1.0)

#### Affected browser(s)
Reproduced on Mac: Chrome, FF, Safari

**Comment by sebastianbochan** [comment]
Hi @jychiao,
Thank you for reporting.

FYI @madepiet

**Comment by madepiet** [comment]
Workaround:

Highcharts v8.1.0
https://jsfiddle.net/BlackLabel/219m0c7L/

Current Master (different CSS class):
https://jsfiddle.net/BlackLabel/ejcfapym/

**Comment by madepiet** [comment]
Internal note:
I would like to consult about this property because it would only be responsible for the color for an empty pie? We can easily set this using the CSS options, while for options with an existing data series we use pie.borderColor (which make much sense for me):
https://api.highcharts.com/highcharts/plotOptions.pie.borderColor

@sebastianbochan  @TorsteinHonsi  any thoughts?

**Comment by jychiao** [comment]
Thanks for the workaround; we don't currently use styled mode, but we went forward with patching the function in the source code to return something other than `#cccccc`.
