### ISSUE TITLE
Custom marker get lost when using exportChart function

### ISSUE THREAD

**Issue by linzhu02** [highcharts/highcharts#13649]
#### Expected behaviour
I used the default sample provided from highcharts demo which has two image urls as marker labels. I am expect to see them on exported png, jpg and pdf files. 

#### Actual behaviour
As you can see in my live demo below, the marker was removed on export 

#### Live demo with steps to reproduce
https://jsfiddle.net/of8kvb1q/

![monthly-average-temperat (7)](https://user-images.githubusercontent.com/26882605/83836421-5ef16a00-a6c1-11ea-9ce8-732c3c92f1a3.png)

**Comment by sebastianbochan** [comment]
Hi @linzhu02,
Thank you for reporting. The problem is caused by call export chart before load all images (as markers). As a result the export server does not have an information about images. You should call the exporting in callback and wrap in setTimeout to be ensure that chart is initialized.

Demo:
- https://jsfiddle.net/BlackLabel/jy2s7xq3/

Im not sure if we should consider it as a bug.

**Comment by pawelfus** [comment]
That's not a bug. Instead of calling `chart.exportChart()` right after rendering a chart, `chart.events.load` event should be used: https://jsfiddle.net/BlackLabel/34b7gscf/

From [docs](https://api.highcharts.com/highcharts/chart.events.load):

> Fires when the chart is finished loading. Since v4.2.2, it also waits for images to be loaded, for example from point markers.
