### ISSUE TITLE
No changing in the tooltip x-axis format after setting another decimalPoint seperator

### ISSUE THREAD

**Issue by xyphez** [highcharts/highcharts#13677]
#### Expected behaviour
After setting  `decimalPoint: ','` it is expected to change all output numbers format for all chart regions.

#### Actual behaviour
No changing in the tooltip x-axis format is observed, while y-axis format is changed.

#### Live demo with steps to reproduce
https://jsfiddle.net/g78vduwp/

**Comment by pawelfus** [comment]
Hi @xyphez 

Thanks for reporting the issue. This is caused by extra options available for `y`-values: 
- https://api.highcharts.com/highcharts/tooltip.valuePrefix
- https://api.highcharts.com/highcharts/tooltip.valueSuffix
- https://api.highcharts.com/highcharts/tooltip.valueDecimals

These options replace `{point.y}` under the hood with `{point.y:,.f}` - and there's no equivalent option for `x`-values. Demo with the same config applied to `point.x`: https://jsfiddle.net/BlackLabel/ya75j1w3/ 

This applies to all other named values (e.g. arearange: `point.low` and `point.high`, ohlc: `point.open`, `point.high`, `point.low` and `point.close`). Only `x`-value is unformatted.

**Comment by xyphez** [comment]
Thanks.
