### ISSUE TITLE
Broken Link Found In Chart Markup

### ISSUE THREAD

**Issue by Ewallye** [highcharts/highcharts#13707]
#### Expected behaviour
Since the user is given the associated menu containing the "View Data Table" and that the current link is simply navigates the use to the Getting Started page, simply remove the link and the associated <h4> from the markup .

#### Actual behaviour
Only when using the screen reader and navigating line by line (using the down arrow key and not tab) is there a link in an H4 of "View as a data table".  The issue is that when the link is selected the user is incorrectly navigated to the Getting Started page instead of triggering the table, which is confusing.

#### Live demo with steps to reproduce
None

#### Product version
https://www.highcharts.com/demo/accessible-line

#### Affected browser(s)
None

**Comment by sebastianbochan** [comment]
Hi @Ewallye,
Thank you for reporting.

FYI @oysteinmoseng

**Comment by oysteinmoseng** [comment]
Hi @Ewallye, could you explain how you are triggering the link without seeing the data table? I am not able to reproduce this

**Comment by Ewallye** [comment]
As mentioned in the Actual Behavior section, I was using JAWS (Job Access With Speech) screen reader reading the page in line by line reading mode.  This is done accomplished using the down arrow key to read a page line by line just as if I was reading the page visually (top to bottom, left to right).  When reading the markup of the chart, I encountered the link in the H4 heading section.  You will not encounter the link via tab since there is a tabindex of -1 applied to the div.

**Comment by oysteinmoseng** [comment]
@Ewallye Thank you, does this happen with a particular browser? VoiceOver is triggering the link correctly for me.

That being said, there is no reason why this link should not just be a button, and that will likely solve the issue.

**Comment by Ewallye** [comment]
@oysteinmoseng Since the functionality is found in the menu, is there really any need for this control at all?  It seems that presenting the control in the menu section would suffice.

**Comment by oysteinmoseng** [comment]
@Ewallye You can certainly remove it (use the [beforeChartFormat](https://api.highcharts.com/highcharts/accessibility.screenReaderSection.beforeChartFormat) option), but in our user testing we found screen reader users sometimes preferred early access to the table. The table is a familiar format to many screen reader users. Generally the idea is that if a user is looking for the table it is because they find the chart confusing, so we ensure it is easy to find straight away - versus navigating through the chart and having to find it in the menu.
