### ISSUE TITLE
Dragable annotations not working on touch devices

### ISSUE THREAD

**Issue by PadWorks** [highcharts/highcharts#13736]
#### Expected behaviour
Annotations should be moved on touch devices when option draggable is set.

#### Actual behaviour
Dragging of annotations is not possible on touch devices (tested on Windows10, Apple and Android devices)

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/annotations/draggable/

#### Product version
Highcharts .NET v8.0.4 and v8.1.2

**Comment by KacperMadej** [comment]
Hi @PadWorks 

Thank you for reporting the problem.
This is a bug and probably a part of https://github.com/highcharts/highcharts/issues/13420

_Internal note:_
After remote debugging of Chrome on Android:
For a touch device (Android) an event is emitted and nothing happens here:
https://github.com/highcharts/highcharts/blob/af5fdee7fecda154d0bec897788f17d6ee1aa477/ts/annotations/eventEmitterMixin.ts#L204

because it doesn't match the added event here:
https://github.com/highcharts/highcharts/blob/af5fdee7fecda154d0bec897788f17d6ee1aa477/ts/annotations/eventEmitterMixin.ts#L128

Those two don't match, but I am not sure which one should be fixed - @Izothep ?

**Comment by Izothep** [comment]
@KacperMadej Removing 

```
addEvent(emitter, H.isTouchDevice ? 'touchmove' : 'drag', emitter.onDrag); 
```

and using 

```
addEvent(emitter, 'drag', emitter.onDrag); 
```

Is not causing issues on iOS devices. Could you please confirm on Android? If yes, the solution is to change this simple line.

**Comment by KacperMadej** [comment]
@Izothep 
Works fine on Adroid ( tested useing https://jsfiddle.net/BlackLabel/wrdo2s8L/ ) 👍 
Adding the label for the issue.
