### ISSUE TITLE
Datetime format x-axis doesn't work as intented when zoomed in using zoom option in highcharts

### ISSUE THREAD

**Issue by bellevie6** [highcharts/highcharts#13732]
#### Expected behaviour
I would like to see the axis break into hh:mm along with the date format when zoomed in in xrange chart. This work fine in column-range chart. Image 1 
![Image 1](https://user-images.githubusercontent.com/67031623/84842364-c381c280-aff9-11ea-80ac-5a8105c2ecac.jpg)

#### Actual behaviour
When I zoom in, the axis goes blank and displays only dates in xrange As shown in fiddle.

#### Live demo with steps to reproduce
https://jsfiddle.net/z1eqg28f/

#### Product version
Highcharts version 8.1.2

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @bellevie6 

Thanks for reporting the issue. This is expected behaviour - by default, `tickInterval` does not go below the closest distance between two points. In your case this distance is 1day, so this is the calculated [`minTickInterval`](https://api.highcharts.com/highcharts/xAxis.minTickInterval). You can change that value: https://jsfiddle.net/BlackLabel/9qegw7bL/
