### ISSUE TITLE
export server is not reachable anymore

### ISSUE THREAD

**Issue by mkhfse** [highcharts/highcharts#13734]
#### Expected behaviour
download chart information as csv or xls file

#### Actual behaviour
GET https://www.highcharts.com/blog/studies/csv-export/download.php 404
Ooops! That page can’t be found.

#### Live demo with steps to reproduce
https://www.highcharts.com/blog/studies/csv-export/download.php

#### Product version

https://code.highcharts.com/8.0.0/highcharts.js
https://code.highcharts.com/8.0.0/modules/exporting.js

Tested also with the new version 8.1.2.

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Hi @mkhfse 

Thank you for reporting the problem.

To export to CSV you could use export-data module. More info and demos in the API reference: https://api.highcharts.com/highcharts/exporting.csv

Why are you using that PHP site? Was it linked in some documentation or was it suggested somewhere? I am asking because it would be good to fix the source.

**Comment by mkhfse** [comment]
Hello KacperMadej,

thanks for the fast response. 

We did now change it and use the new export-data module for exporting.
This is working fine.

Before we did implement it with Highcharts.post e.g:
https://www.highcharts.com/forum/viewtopic.php?t=30935
