### ISSUE TITLE
update method does not work with new series data

### ISSUE THREAD

**Issue by nickwinger** [highcharts/highcharts#13788]
#### Expected behaviour
Should display the new data

#### Actual behaviour
Only updates the navigator below, but also the navigator is broken as the range controls are missing.
The actually line chart data does not get displayed

#### Live demo with steps to reproduce

just create a highStock chart, and first pass in a series with no data

after that put a new series with data on the same chart instance and call updateFlag = true.

#### Product version

latest

**Comment by pawelfus** [comment]
Hi @nickwinger 

Thanks for reporting the issue. I don't understand the part with `updateFlag=true` - there's no such argument in [`chart.addSeries`](https://api.highcharts.com/class-reference/Highcharts.Chart#addSeries) method. See: http://jsfiddle.net/BlackLabel/6tekbrwa/

We just received report that since v8.0.1 there's a bug with empty series in Highstock, see: #13437 - could you try my workaround posted there? Maybe it's the same issue but with different error?

**Comment by nickwinger** [comment]
Hi pawel,

yes you are right, I am in the wrong repo, the updateFlag is in highcharts-angular.
The highcharts-chart component has a update binding, internally it calls:
`this.chart.update(this.optionsValue, true, this.oneToOne || false);`
So, it's the update method (not updateFlag) that is not working when the series before had no data.

**Comment by nickwinger** [comment]
i have made a jsFiddle for reproduction:
http://jsfiddle.net/nickwinger/pk5rdq6g/2/

the first time you press the "add series" button it does not work (like my bug says) the second time it works...

**Comment by pawelfus** [comment]
Thank you for the demo @nickwinger 

Simplified demo: https://jsfiddle.net/BlackLabel/n6b5h4o9/ - it seems that updating `rangeSelector.selected` causes the issue when no data was available upon chart init.

**Workaround:**
Demo:
- http://jsfiddle.net/BlackLabel/6h5sujav/
- http://jsfiddle.net/BlackLabel/ps24ao6q/

Plugin:
```js
(function(H) {
  H.wrap(
    H.Axis.prototype,
    'setExtremes',
    function(proceed) {
      var args = Array.prototype.slice.call(arguments, 1);

      if (isNaN(args[0])) {
        args[0] = undefined;
      }

      if (isNaN(args[1])) {
        args[1] = undefined;
      }

      return proceed.apply(this, args);
    }
  );
})(Highcharts);
```

*Internal note:*
Bisected to commit 1e3115bc1e

Happens because of these lines:
```
		newMin += rangeOptions._offsetMin;
		newMax += rangeOptions._offsetMax;
```

`newMin` and `newMax` are undefined, increasing them makes them NaN's. While undefined are fine when setting extremes, NaN's are unacceptable.

**Comment by nickwinger** [comment]
hmm, the workaround does not work on my side, the navigator updates, but in the chart are still no lines :-/

**Comment by pawelfus** [comment]
@nickwinger 

Could you test pre-released fixed version? Just to make sure it's fine in your case too. Tested with your demo: http://jsfiddle.net/BlackLabel/6znuLh12/ - seems to be fine. File can be downloaded from here: https://github.highcharts.com/dd01cd8/highstock.js

**Comment by nickwinger** [comment]
@pawelfus 
it's still completly broken on my side. The chart does not update, only the navigator, but you cannot navigate inside the navigator.

**Comment by pawelfus** [comment]
I know @nickwinger - I think I have pinpointed the real issue there. I will work on this tomorrow.

Regarding your imports - it's wrong. You should use one of these:

- load Highcharts + Stock module:
```
import * as Highcharts from 'highcharts';
import * as Stock from 'highcharts/modules/stock';

Stock(Highcharts);
```

- load Highcharts Stock only (Highcharts Stock includes Highcharts):

```
import * as Highcharts from 'highcharts/highstock';
```

**Comment by nickwinger** [comment]
ok, thanks for pin pointing that out
