### ISSUE TITLE
Module datagrouping.js causing proximate legend to render incorrectly.

### ISSUE THREAD

**Issue by garybrain** [highcharts/highcharts#13813]
#### Expected behaviour
When a user using the mouse click on a legend item to hide/show it should move the positions around.

#### Actual behaviour
The legend items collapse on top of each other.

#### Live demo with steps to reproduce

force set to false.
Expected behaviour: https://jsfiddle.net/garybrain/bz8ohmuc/2/

Forced to true due to the  amount of data provided, but the same thing happens with larger sets of data.
Actual behaviour: https://jsfiddle.net/garybrain/bz8ohmuc/3/

#### Product version
Highcharts 8.1.2

#### Affected browser(s)
all

**Comment by pawelfus** [comment]
Thank you for reporting this bug @garybrain - it's indeed caused by `dataGrouping`. Proximate legend requires at least one point, but when points are grouped we destroy them to free the memory (usually `dataGrouping` is used with many points so we do that to increase the performance).

*Internal note:*
I think `proximatePositions()` should consider this use case too: when `points` are missing, but yAxis is available we simply will use default (hidden) position.

**Comment by garybrain** [comment]
HI, just a quick Q, I use Highcharts with the modules datagrouping.js which comes with the highcharts download. 

Are these modules usable even thought I don't have highstock ( which I see you assigned this too ).

Thanks

G.

**Comment by pawelfus** [comment]
Highcharts Stock license is necessary - it's a bug in downloadable package, this module (and apparently some others) shouldn't be in Highcharts package. Created new issue for that: #13832

**Comment by garybrain** [comment]
Hi, is there a way to add the ability to purchase these modules separately. I only use Highcharts but would love to have the datagrouping.js due to the size of data used ( date based graphs ).

Thanks

G.

**Comment by pawelfus** [comment]
I suggest to contact our Sales team: https://www.highcharts.com/blog/contact/
