### ISSUE TITLE
Chart breaks when using boostThreshold

### ISSUE THREAD

**Issue by nagdevbharat** [highcharts/highcharts#13851]
#### Expected behavior
The chart should have connected markers.

#### Actual behaviour
Implementing boost module breaks the chart.

#### Live demo with steps to reproduce
https://jsfiddle.net/x259e0am/44/
- Change boostThreshold to 0 and it will connect the series

#### Product version
Highchart: 6.1.0

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Thanks for reporting the issue, but in order to use option `connectNulls` you should set y-value as null. See: https://jsfiddle.net/BlackLabel/k9ntfgeb/

It seems fine when chart is not in a boosted-mode, but it's not the config we recommended, neither documented, for line series. I don't think we should change it for, because other devs might use it the same way. Sorry for the inconvenience!

**Comment by nagdevbharat** [comment]
Hello @pawelfus ,
Thanks for the details. In my project, boost module was removing points from the plot the demo was representation of that.
I solved it with the async loading demo by loading whole data at once and then just adding points.
However, in that I found another issue related to zoom in.
Here is the fiddle: https://jsfiddle.net/pzevqha2/6/
If I zoom in multiple times then click on reset zoom it doesn't reset actually I am not sure why.

Please take a look at this. Also in the console, it returns Highcharts 15 error. 

Hope these details help.

**Comment by pawelfus** [comment]
I'm not able to recreate this. Note that data is loaded from our server, so maybe your internet connection had some problems?

Regarding Error 15 - it's caused by adding first point in the middle of the dataset. Change 1998 to 1997 and will be fine: https://jsfiddle.net/BlackLabel/fxzg7tba/

If you find any other issues, please contact our support first: https://www.highcharts.com/blog/support/ - thanks!
