### ISSUE TITLE
Updating tickInterval fails for bar charts 

### ISSUE THREAD

**Issue by sssttteeewwwaaarrrttt** [highcharts/highcharts#13897]
#### Expected behaviour
Using the chart.update function to change the tickinterval should work in a bar chart, just like it does in a column chart. 

#### Actual behaviour
Chart fails to render. 
Uncaught TypeError: b.toPrecision is not a function

#### Live demo with steps to reproduce
[https://jsfiddle.net/Lej248fz/3/](jsFiddle)
Click the tickInterval buttons to see the chart successfully change tickInterval.
Click the bar button to change the chart type to bar, then click the tickInterval buttons and watch the chart fail.  

#### Affected browser(s)
Only tested on Chrome and Firefox, but issue affects both.

**Comment by pawelfus** [comment]
Hi @sssttteeewwwaaarrrttt 

Thanks for reporting the issue. This is caused by using `string` for `tickInterval` option. Should always be number. See fixed demo: https://jsfiddle.net/BlackLabel/w3nuqLfv/

It seems that `string` works fine for column, but it's an accident. We would rather not remove that, because we may break existing charts that use that option for column series only.

PS: To update chart <-> bar series, use `chart.inverted` option: https://jsfiddle.net/BlackLabel/w3nuqLfv/1/
