### ISSUE TITLE
Unnecessary Space in Highstock-Chart

### ISSUE THREAD

**Issue by nickwinger** [highcharts/highcharts#13935]
# Description of the feature

We want to be able to show very small charts.
Even if scrollbar and many other things are enabled: false, there is still a white gap at the bottom (see screenshot).
It would be good, if we can get rid of that padding, or that it is an option. e.g. padding-bottom: false

# Library related to the feature

![image](https://user-images.githubusercontent.com/9943675/87939658-a9c01900-ca98-11ea-9e2d-eac0911eee81.png)

# Proof of Concept/Live example for the feature

----

**You can vote for this feature by a adding thumbs-up reaction to this post.**

**Comment by pawelfus** [comment]
Hi @nickwinger 

We have an option: [`chart.spacingBottom`](https://api.highcharts.com/highstock/chart.spacingBottom). Which by default is set to 15px. Setting it to 0 decreases the padding, see: https://jsfiddle.net/BlackLabel/nw0oeLkr/

**Comment by nickwinger** [comment]
Hi @pawelfus ,

thanks for pointing me to that Design Document, i have overseen this.
Works as expected, i also put marginBottom to 0 and now it looks as we want it:
![image](https://user-images.githubusercontent.com/9943675/88050325-e5b9b380-cb56-11ea-8219-6418a6731462.png)

However, i also tried spacingTop: 0, and marginTop: 0 and then suddenly i get more space instead of less:
![image](https://user-images.githubusercontent.com/9943675/88050399-0a159000-cb57-11ea-90c5-b17ac090e3f3.png)

**Comment by pawelfus** [comment]
Maybe you have some CSS padding for the container? It's hard to say, I'm not able to debug from the screenshots - which by the way look almost the same to me :) Anyway, it works fine in my demo: https://jsfiddle.net/BlackLabel/nw0oeLkr/1/ - I suggest to set, for debugging only, 1px border around the chart's container to see what's causing this.

In general, for a very small charts, we suggest to check our Sparklines demo: https://www.highcharts.com/demo/sparkline - these charts have barely any extra info, except the lines and markers.

Anyway, I'm closing this issue since suggested `padding-bottom: false` is already implemented as `spacingBottom: number`. If you find any bugs, please report separate issue. If you have any problems with debugging, contact our support first: https://www.highcharts.com/blog/support/
