### ISSUE TITLE
SMA volume in stock tools is not visible in high price ranges

### ISSUE THREAD

**Issue by bre1470** [highcharts/highcharts#13950]
#### Expected behaviour
The stock tools demo allows adding the SMA indicator to AAPL line chart. Alternative to price can volume be referenced. The volume thought is much lower than the price and in the default price view not visible.

#### Actual behaviour
SMA volume should get its own (hidden axis), so that the volume is visible in every view.

#### Live demo with steps to reproduce
https://www.highcharts.com/demo/stock/stock-tools-gui

#### Product version
Highstock 8.1.2

#### Affected browser(s)
all

**Comment by pawelfus** [comment]
Im not sure if I understand the issue. SMA should have exactly the same axes as the linked parent series. It's an overlay type of the technical indicator.

I might understand what you are referring too:
![sma](https://user-images.githubusercontent.com/1453926/88296368-e2612c00-ccfe-11ea-8535-6573500c66e3.gif)

After zooming in, we can observe correct line. Before zooming line is too low, is that correct @bre1470 ? If that's the case, then it's caused by wrong `series.dataGrouping.approximation` setting (by default, for columns it's `sum` while for lines it's `average`). `series.dataGrouping.approximation` should be inherited similar to the `series.yAxis` option:

https://github.com/highcharts/highcharts/blob/3898d58a4965967c45c1bbf3c5b8537c1e5cffdc/ts/Stock/StockToolsBindings.ts#L307-L309

This makes sense only for `sum`/`average` option in parent series, not for `range`, `ohlc`, `averages`, `open`, `close`, `high`, `low`, `windbarb` approximations, neither for `averages` or `ichimoku-averages` approximation in the indicator options (e.g. you can't use `sum` approximation on BollingerBands tech indicator).

**Comment by bre1470** [comment]
Yes, I actually did not noticed the line at first and I find it not very useful in the default, unless you use the tooltip. I just thought, that as an indicator it might be not necessary to use the same axis, if the values differ in such an extreme.

If you believe, the problem of usability can be solved with `series.dataGrouping.approximation` option, the issue should kept open. Otherwise sorry for the confusion and it is fine for me, if there is no real solution for it and the issue gets closed.

**Comment by pawelfus** [comment]
Okay, thanks for the clarification! Let's keep this open then.
