### ISSUE TITLE
Max vegative value

### ISSUE THREAD

**Issue by iniatse** [highcharts/highcharts#13953]
Hello,

there is an option to set the maximum positive value (`yAxis.max`), but I could not find an option to set the maximum negative value. How can I set the maximum negative value? If that feature does not exist, could you please add it?

**Comment by pawelfus** [comment]
Hi @iniatse 

Before creating a ticket on GitHub, please contact our support first: https://www.highcharts.com/blog/support/

PS: The option is called `min`.

**Comment by iniatse** [comment]
`min` does not do what I describe in the OP. `min` sets a minimum, but that is not what I want.

**Comment by iniatse** [comment]
Furthermore if you look at the link that you posted you see that:

> To request a feature, please submit a request to our GitHub issue tracker

**Comment by pawelfus** [comment]
If `x/yAxis.min` is not an option you want to use, then please provide details how `maximum negative value` should work. You mentioned `yAxis.max` which sets max extreme on the yAxis (it's not the "max positive" value, but just max value: https://jsfiddle.net/BlackLabel/ankqt2bu/). If you could follow our feature request template then would avoid any confusion.. Perhaps you don't want to use `yAxis.min` but simply [`yAxis.floor`](https://api.highcharts.com/highcharts/yAxis.floor)? Which sets:
> The lowest allowed value for automatically computed axis extremes.

Regarding this:

> Why exactly do you close this issue and not even wait for the response?

Because what you asked sounds exactly like options we already have and we can always reopen the issue if that will be necessary. At this moment I still consider your feature request as a question to our API which should be asked on stackoverflow or our forum. I might be wrong, though, so we can still reopen this.
