### ISSUE TITLE
Animation failure

### ISSUE THREAD

**Issue by zChanges** [highcharts/highcharts#13987]
Turn on animation: true
When the updated data `series.data` is time stamp and different, the animation has no effect
```ts
    // updata
      {
        name: '1',
        data: data.map((_, index) => {
          return {
            x: dayjs(dayjs().valueOf()).subtract(index, 'minute').valueOf(), // No animation
            // x: +_[0] * 1000, // With animation
            y: Math.random() * 100
          }
        }),
        type: 'areaspline'
      },
```
#### Expected behaviour
Update x data with animation effect

#### Actual behaviour
Animation failure

#### Live demo with steps to reproduce
https://stackblitz.com/edit/angular-ivy-mwwzu3

#### Product version
 "highcharts": "^8.1.2",
 "highcharts-angular": "^2.4.0",

**Comment by pawelfus** [comment]
Thanks for reporting the issue @zChanges 

This is expected behaviour. We animate the line according to related points with it's x-values (we make an `xMap` that allows us, on a low level, animate the path). When everything changes, we can't match these elements in a result there's no animation. At this moment, it's possible to add `point.id` to every point, but that will animate only markers: https://stackblitz.com/edit/angular-ivy-3bqy73

**Workaround:**
It's not a perfect workaround, may not work with discontinuous dataset (gaps, null points).
Demos:
- angular: https://stackblitz.com/edit/angular-ivy-3bqy73
- basic: https://jsfiddle.net/BlackLabel/mj4h28ru/

Plugin:
```js
(function(H) {
  H.wrap(
    H.Series.prototype,
    'getGraphPath',
    function(proceed) {
      var graphPath = proceed.apply(this, Array.prototype.slice.call(arguments, 1));

      if (graphPath.xMap) {
        graphPath.xMap = [];
        this.points.forEach(function(p) {
          graphPath.xMap.push(Highcharts.pick(p.options.id, p.x));
        })
      }

      return graphPath;
    }
  );
})(Highcharts);
```
*Internal note:*
When generating `xMap`, consider using `point.id` (if available), so there will be a way to get this animation. Current animations:
- without id's: https://jsfiddle.net/BlackLabel/bo1z0dfa/ (observe different animation when calling `point.update()` manually - but this is expected, I made the connection `old_point` <-> `new_point` using indexes in my for-each)
- with id's: https://jsfiddle.net/BlackLabel/bo1z0dfa/1/ (all three animations are the same, we only need to animate the path)

@TorsteinHonsi - do you see any possible problems with using `point.id` when generating `xMap`?

**Comment by zChanges** [comment]
@pawelfus 
Thank you very much for the answer, it solved my problem perfectly

**Comment by pawelfus** [comment]
Thanks! Let's keep this open
