### ISSUE TITLE
Chart.update doesn't work on noData options

### ISSUE THREAD

**Issue by stevenzhangpolycom** [highcharts/highcharts#13982]
#### Expected behaviour
Calling chart.update() like so
```javascript
chart.update({
   noData: {
        style: {
            color: 'red'
        }
    },
    subtitle: {
        text: 'Updated The Chart'
    }
  }
})
```
should change the noData text from its previous color to red and add a subtitle to the chart with the specified text.

#### Actual behaviour
Calling chart.update() akin to the aforementioned snippet does nothing to the noData text, but does add the subtitle properly...

#### Live demo with steps to reproduce
https://jsfiddle.net/r2Ly5vfa/
* Click "Change noData color" button

#### Product version
Tested on Highcharts 7.2.1 and latest (8.1.2 at the time of writing)

#### Affected browser(s)
Firefox, Chrome

**Comment by sebastianbochan** [comment]
Hi @stevenzhangpolycom,
Thank you for reporting. The problem is caused by two reasons:
- no redraw function (so you need to destroy and create a new label)
- missing merge with userOptions (declared i.e during update)

https://github.com/highcharts/highcharts/blob/e06fb000fa9fc2ad816a9c5ec4f29e311d90bf9b/ts/Extensions/NoDataToDisplay.ts#L190-L191

**Workaround**:
- https://jsfiddle.net/BlackLabel/rxvnzyuh/
