### ISSUE TITLE
Exported chart with moved annotations shows each moved annotation twice

### ISSUE THREAD

**Issue by LimpEmu** [highcharts/highcharts#14011]

**Comment by pawelfus** [comment]
Hi @LimpEmu 

Thanks for reporting the issue. This is expected behaviour: `load` callback is called when exporting chart too. To prevent this from happening, you can check `forExport` flag: https://jsfiddle.net/BlackLabel/d0aqejov/

Snippet: 
```js
  if (this.options.chart.forExport) {
    return;
  }
```

**Comment by LimpEmu** [comment]
Perfect, I got it to work with the additional complexities of our chart! Now I do have to figure out **why** it works this way, some parts of Highcharts remain mysterious to me. Thank you very much for your help!

**Comment by pawelfus** [comment]
When exporting a chart, new chart is created (using original options and `exporting.chartOptions`). That means, if `load` is called on chart load, then the same will happen when exporting chart. Why it works that way? Because it's a common use case to use for example `chart.renderer` to draw additional elements on chart and expect the same things rendered when exporting chart.  And why it duplicates annotations? Because `addAnnotation()` works the same way as for example `addSeries()`. Both methods make configs persistent in chart options (for example if someone uses `addSeries()`, then series is expected to be rendered in exported chart anyway). I hope that clears a little :)

**Comment by LimpEmu** [comment]
Thank you for your follow-up! 
Yes, I understand that highcharts is re-rendering the chart for export, and I take advantage of load: by modifying the chart slightly for printing. And after mulling over it, I do realize how using `return;` works. Thank you again!
