### ISSUE TITLE
v:8.1.0:area color  wrong when set color with transparency

### ISSUE THREAD

**Issue by wjhcc2018** [highcharts/highcharts#14095]
#### Expected behaviour

color can set myself transparency

#### Actual behaviour
when i set color:'rgba(237,235,255,0.3)'  but it's render color rgba(127,79,255,0.75)

Transparency fixed write dead

**Transparency is 0.3**:
![image](https://user-images.githubusercontent.com/6789138/90729144-b08cb680-e2f8-11ea-8d2e-b8b78b6c391c.png)
**Transparency is 0.75**:
![image](https://user-images.githubusercontent.com/6789138/90729356-095c4f00-e2f9-11ea-9bea-9ff1c7c9de0a.png)

#### Live demo with steps to reproduce

live demo:https://codesandbox.io/s/boring-moon-3wlig?file=/src/components/HelloWorld.vue

**Comment by pawelfus** [comment]
Thank you for reporting the issue @wjhcc2018 

This is expected behaviour, default [`fillOpacity`](https://api.highcharts.com/highcharts/series.area.fillOpacity) is set to `0.75`. 

@bre1470 could you take a look? Doclet seems to be fine: 

https://github.com/highcharts/highcharts/blob/4832c0f62/js/parts/AreaSeries.js#L60-#L78

**Comment by bre1470** [comment]
The area series uses `fillColor` to change the area. `color` affects the point marker (the little dot). I will update the color doclet for area to link to fillColor.
