### ISSUE TITLE
softThreshold property is not working as expected

### ISSUE THREAD

**Issue by mynameiswhat1** [highcharts/highcharts#14111]
Hello,
I have found the following issue:

#### Expected behaviour 

From the [Highcharts api documentation for the softThreshold](https://api.highcharts.com/highcharts/plotOptions.series.softThreshold) property, it is expected that "When this is true, the series will not cause the Y axis to cross the zero plane (or threshold option) unless the data actually crosses the plane."

Given the property description and the fact that in previous versions of Highcharts (lower than 7.1.0) this property was working as expected, I expected that my chart was created in the following way after version 7.1.0:
![noIssue](https://user-images.githubusercontent.com/25388696/91035527-4e84c780-e5fe-11ea-8f61-f7fa1ca9ffda.PNG)

#### Actual behaviour

However, after[ version 7.1.0 of Highcharts](https://www.highcharts.com/blog/changelog/#highcharts-v7.1.0) onwards I have found that this is not the case, since regardless of the softThreshold property being set to true, I find that for a series with only 0 values, the Y axis starts at -0.5 and ends at 0.5, as is visible in the following image:

![issue](https://user-images.githubusercontent.com/25388696/91035505-4d539a80-e5fe-11ea-9214-0bbc8d426725.PNG)

I expected chart Y axis to start at 0 and end at 0.5. Since this property was working as expected in previous versions of Highcharts and stoped working after version 7.1.0, in my opinion, this is a loss of functionality and a issue.

#### Live demo with steps to reproduce

- Fiddle with softThreshold property working as expected with Highcharts version 7.0.3: [https://jsfiddle.net/mb70qd5o/](https://jsfiddle.net/mb70qd5o/)

- Fiddle with softThreshold property **NOT** working as expected, with Highcharts version 7.1.0: [https://jsfiddle.net/mb70qd5o/2/](https://jsfiddle.net/mb70qd5o/2/)

#### Product version

All versions after, and including, 7.1.0.

#### Affected browser(s)

At least Chrome Version 84.0.4147.135 (Official Build) (64-bit)

Thank you very much

**Comment by pawelfus** [comment]
Hi @mynameiswhat1 

Thanks for reporting the issue, but this is expected behaviour. In v7.0.3 setting `minRange` did not work properly for flat datasets. 

In your case, that means:
- if `min` and `max` are not set, `minRange` will extend the range both ways, to the min and to the max: https://jsfiddle.net/BlackLabel/bofam5ck/
- setting only one of `min`/`max` will extend one extreme only: https://jsfiddle.net/BlackLabel/bofam5ck/1/

That means, `softThreshold` works as described: it's not the series (with `minPadding` option) that is causing yAxis to cross the zero plane, but it's another option: `minRange`.

Alternatively, instead of `minRange`, consider using `softMin` and `softMax` only: https://jsfiddle.net/BlackLabel/bofam5ck/2/

**Comment by mynameiswhat1** [comment]
Hello @pawelfus, 
Thank you for your reply. Your suggestion works. Consequently, this issue can be closed.
Best regards
