### ISSUE TITLE
can't draw polar with highstock

### ISSUE THREAD

**Issue by darkspr** [highcharts/highcharts#14139]
#### Expected behaviour
can't draw polar with highstock
no polar in chart(highstock)
![image](https://user-images.githubusercontent.com/13914976/91507699-00c2d480-e908-11ea-91d0-5e4bc07c02b6.png)
![image](https://user-images.githubusercontent.com/13914976/91507674-f1438b80-e907-11ea-8dd2-84414c09f0dc.png)

**Comment by pawelfus** [comment]
That's correct @darkspr 

`polar` option is not directly supported in Stock (e.g. using with RangeSelector or Navigator/Scrollbars). However, you still can create polar charts using Highcharts Stock library, because the Highcharts lib is included. Notice the API defines options available for constructor:

![Screen Shot 2020-08-28 at 09 02 37](https://user-images.githubusercontent.com/1453926/91531589-52ba2900-e90d-11ea-86f7-ce49bd3849fc.png)

And `Highcharts.chart()` is available too, demo for you: https://jsfiddle.net/BlackLabel/vdyeg14h/
