### ISSUE TITLE
Property linkedTo not working for series in pie Chart

### ISSUE THREAD

**Issue by LoganDupont** [highcharts/highcharts#14161]
#### Expected behaviour
In the documentation it is mentioned that when two series are linked, only the first one appears in the legend. 
https://api.highcharts.com/highcharts/series.pie.linkedTo

#### Actual behaviour
Both series are visible in the legend

#### Live demo with steps to reproduce
https://jsfiddle.net/mnq5xzuw/1/

#### Product version
Highcharts v8.0.0

#### Affected browser(s)
/

**Comment by pawelfus** [comment]
Thanks for reporting again @LoganDupont 

It's a bug in API. As described in option, `linkedTo` option links **series**. In pie chart, every legend item is related to **a point**, not a series. There's no simple option like `linkedTo` for points though. To achieve the same effect, you need to use [`series.pie.point.events.legendItemClick`](https://api.highcharts.com/highcharts/series.pie.point.events.legendItemClick).

Simple example for you: https://jsfiddle.net/BlackLabel/h91dgmsr/

PS: It's better to use `point.id` instead of `point.index`, because you don't have to worry about your data being unsorted or is missing some points: https://jsfiddle.net/BlackLabel/h91dgmsr/1/

**Comment by LoganDupont** [comment]
Okay, thanks. Just one remark @pawelfus as class [Highcharts.Point](https://api.highcharts.com/class-reference/Highcharts.Point) doesn't contain the `setVisible` function. Should I create a new issue for this?

**Comment by pawelfus** [comment]
Created: #14167 - thanks for pointing this out!

**Comment by pawellysy** [comment]
unstale
