### ISSUE TITLE
Instead of circle path is getting added for empty pie chart series

### ISSUE THREAD

**Issue by SharunSomani** [highcharts/highcharts#14174]
#### Expected behaviour
For empty pie circle should be added <g class="highcharts-series-group" data-z-index="3"><g data-z-index="0.1" class="highcharts-series highcharts-series-0 highcharts-pie-series highcharts-color-0" transform="translate(0,0) scale(1 1)"><circle>

#### Actual behavior
<g class="highcharts-series-group" data-z-index="3"><g data-z-index="0.1" class="highcharts-series highcharts-series-0 highcharts-pie-series highcharts-color-0" transform="translate(0,0) scale(1 1)"><Path classname='highchart-empty-series' getting added

#### Product version
<!--- Highcharts, Highstock or Highmaps plus version number --8.2.0>

**Comment by PaulDalek** [comment]
Thanks for reporting @SharunSomani

The actual behavior is intended and it works correctly. The reason why a path element is used is because a pie series doesn't always need to be a full circle, as you can set such options as `startAngle` and `endAngle`. Take a look at the example below. In case you provide more details about how this is a wrong behavior (along with a live example), we can reconsider to reopen it again.

#### Live demo
https://jsfiddle.net/BlackLabel/p7anxhcb/

**Comment by SharunSomani** [comment]
As per the documentation
color: Highcharts.ColorString, Highcharts.GradientColorObject, Highcharts.PatternObject
The color of the pie series. A pie series is represented as an empty circle if the total sum of its values is 0. Use this property to define the color of its border.

In styled mode, the color can be defined by the colorIndex option. Also, the series color can be set with the .highcharts-series, .highcharts-color-{n}, .highcharts-{type}-series or .highcharts-series-{n} class, or individual classes given by the className option.

Defaults to #cccccc.
Try it
Empty pie series

**Comment by SharunSomani** [comment]
https://api.highcharts.com/highcharts/plotOptions.pie Please refer to the link with version 8.1.0 it is behaving correctly . It happened when I upgraded the version

**Comment by PaulDalek** [comment]
@SharunSomani 

Yes, previously it behaved like that but it was changed for reasons I have mentioned in my previous comment.

> A pie series is represented as an empty circle if the total sum of its values is 0.

And it still is, if the `startAngle` and `endAngle` properties have their default values. The only difference now is that the `path` element is created instead of the `circle`.

For more information, please visit the link to the issue: https://github.com/highcharts/highcharts/issues/13229.
