### ISSUE TITLE
Variwide within range - zoom not working properly

### ISSUE THREAD

**Issue by raghava2121** [highcharts/highcharts#14182]
#### Expected behaviour
After zooming between 21.25 and 22.00  should render properly.
https://jsfiddle.net/raghava_2121/rq3mfc4L/9/

![7138A6F8-569E-4B19-8AC1-DEF6C8903E6F_1_105_c](https://user-images.githubusercontent.com/6311517/92358657-74828f80-f107-11ea-9e82-756136988b06.jpeg)

#### Actual behaviour
After zoomin graph doesn't display the selected range with colour.
 
#### Live demo with steps to reproduce
https://jsfiddle.net/raghava_2121/rq3mfc4L/13/

#### Product version
Highstock 

#### Affected browser(s)
google chrome

**Comment by KacperMadej** [comment]
Hi @raghava2121 

Thank you for reporting the problem.

This looks connected to #3136 (because one of the possible workarounds is the same).

**Workarounds:**

1. Set `Highcharts.seriesTypes.variwide.prototype.cropShoulder = 1;` (not a part of API)
Demo: https://jsfiddle.net/BlackLabel/yeo1d657/1/

2. Set `getExtremesFromAll: true` for the series (API reference: [getExtremesFromAll](https://api.highcharts.com/highcharts/series.variwide.getExtremesFromAll))
Demo: https://jsfiddle.net/BlackLabel/yeo1d657/2/

3. Increase `cropThreshold` to a value higher than the number of points - e.g. 3000 for the demo.
Demo: https://jsfiddle.net/BlackLabel/yeo1d657/3/

**Comment by raghava2121** [comment]
Thanks for the solutions. That works well 💯

**Comment by Reema-Sharma1** [comment]
we are using highcharts production and we would like to see this bug getting fixed. is it possible to prioritize this issue?

**Comment by karolkolodziej** [comment]
Let's reopen this since it still doesn't work. In the meantime, I will try to ask the team to prioritize it 😉 

By the way, have you tried using the workaround provided by Kacper?
