### ISSUE TITLE
Map with overlaid pie charts: colorAxis auto-calculates max from all available series, not only map-series

### ISSUE THREAD

**Issue by bl99** [highcharts/highcharts#14199]
Hi

I am not sure if this is a Highcharts/-maps bug or just related to the [Map with overlaid pie charts example](https://www.highcharts.com/demo/maps/map-pies). Already reported it here: https://www.highcharts.com/forum/viewtopic.php?f=14&t=44849&p=159289#p159289

#### Expected behaviour
Maps with overlaid pie charts and colorAxis so far (with HC 6.1.1) automatically calculated the colorAxis min/max from the data-series displayed in the map. On pie mouseover, the marker for pie-value is NOT shown on colorAxis.

#### Actual behaviour
colorAxis seems to auto-calculate its max value from ALL available data-series (also those series used for pie-charts)
On pie mouseover, the marker for pie-value is shown on colorAxis. Map features change color after mouseover.

#### Live demo with steps to reproduce
https://jsfiddle.net/ahpL42bm/

(fiddle copied from [Map with overlaid pie charts example](https://www.highcharts.com/demo/maps/map-pies), just removed dataClasses from colorAxis. Uncomment min/max to see expected behaviour)

#### Product version
Highcharts / Highmaps 8.2.0 (worked with 6.1.1)

#### Affected browser(s)
at least Firefox, Chrome, Edge

best regards,
lib

**Comment by PaulDalek** [comment]
Hi @bl99

Thank you for reporting this. This behavior isn’t a bug. Since v7.2.0 the `colorAxis` can be used for a bigger number of series (`pie` is among them). Also, multiple color axes are supported now as well. In your example both, `map` and `mappie` use the same `colorAxis`. You can disable it for `pie` by simply setting the `colorAxis` property (https://api.highcharts.com/highcharts/plotOptions.series.colorAxis) to `false`.

Demo
https://jsfiddle.net/BlackLabel/pcvuja1g/

**Comment by bl99** [comment]
Hi Paul - Thank you for the feedback, it helped to solve our problem.
