### ISSUE TITLE
Highchart pattern fill not working

### ISSUE THREAD

**Issue by akash18m** [highcharts/highcharts#14211]
Hey,
I am trying to plot a column chart with patterns but not able to plot the graph when I import from **highcharts/modules/pattern-fill**. But when I import the same from **highcharts-pattern-fill** module it is working fine.

#### Expected behaviour
Column chart with patterns should be plotted

#### Actual behaviour
Column with pattern is not getting rendered.

#### Live demo with steps to reproduce
https://codesandbox.io/s/angry-pine-57vbl?file=/src/App.js 
Please check and see if this is a bug or am I missing something.

**Comment by akash18m** [comment]
Hello again,

I have been trying out few things and after reading docs, I figured out that old **defs: { pattern: somePattern }** does not work with new pattern-fill module. We have to define pattern inside series object only. 
https://codesandbox.io/s/inspiring-wind-0kvct?file=/src/App.js is the sandbox link with working solution. Please confirm if this is expected behaviour and close the ticket.

Thanks 😄

**Comment by PaulDalek** [comment]
Hi @akash18m

Thank you for reporting this. The options structure used in the first demo works with the [old pattern fill plugin](https://github.com/highcharts/pattern-fill). To make use of the current pattern fill functionality (available since v6.1.0) the pattern options must be set in the `color` section. You can still use the `defs` option to create a pattern but in case when the styled mode is applied (more information can be found here: https://www.highcharts.com/docs/chart-design-and-style/pattern-fills). Also, in case of similar problems, try to contact our support first as it is a big chance (as here) that the behavior you're encountering isn't a bug.
