### ISSUE TITLE
rangeSelector buttons click events does not return the event.xAxis and event.yAxis values on devices and simulators 

### ISSUE THREAD

**Issue by richie50** [highcharts/highcharts#14224]
#### Expected behaviour
Touch event should return exact same properties as mouse event. Unless there is a specification somewhere that says otherwise 

#### Actual behaviour
Event properties does not match

#### Live demo with steps to reproduce

https://jsfiddle.net/92x3dq8y/3/  Try to render this on mobile with chrome , firefox or safari dev tools

**Comment by pawelfus** [comment]
Hi @richie50 

Thanks for reporting the issue. It's interesting issue, in general `xAxis` and `yAxis` are not available on my osx+latest chrome: https://jsfiddle.net/BlackLabel/kxpsn7m2/1/ (see `undefined` in console, accessing these arrays throws errors). However, expanding `MouseEvent` in dev tools object shows `xAxis` and `yAxis`.

I think it's a general bug, because passed on `Event` is incorrect: it looks like original browser event (and probably is), while should be our Event that wraps `MouseEvent` interface in a structure similar to other events (e.g. `chart.events.selection`: https://jsfiddle.net/BlackLabel/3r1mkqnv/).

**Comment by TorsteinHonsi** [comment]
I'm not sure whether to call it a bug. The first thing it what Pawel says, that I don't think it's actually a difference between touch and mouse. The other thing is that we don't specify in the docs what properties are available on the event arguments object, so it is not necessarily a bug that `xAxis` is there or not.

The **cause** of the issue is event propagation. Once the RangeSelector button click event has triggered, the event propagates up and fires the click event on the chart container itself. And the internal handler for container clicks adds information about `xAxis` and `yAxis` coordinates. This [can be verified](https://jsfiddle.net/highcharts/1n23f46k/) by calling `e.stopPropagation` from the button click event, then the `e.xAxis` property will not be assigned later on.
