### ISSUE TITLE
time.useUTC doesn't update the second time

### ISSUE THREAD

**Issue by stantalid** [highcharts/highcharts#14230]
#### Expected behaviour
useUTC should get updated every time.

#### Actual behaviour
useUTC is updated only the first time.

#### Live demo with steps to reproduce
https://jsfiddle.net/aunvoq4f/2/

#### Product version
Highcharts 8.0.4

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Thank you for reporting the issue @stantalid 

**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/d832n9mw/

Plugin:
```js
(function(H) {
  H.addEvent(
    H.Chart,
    'afterUpdate',
    function(event) {
      if (event.options.time) {
        H.merge(true, this.options.time, event.options.time);
      }
    }
  );
})(Highcharts);
```

*Internal note:*
Debugging leads me to one conclusion: every class with `update()` also updates self options in the chart instance. However, `Time` extension has no access to chart instance (thus no access to `chart.options.time`). It works for the first time only because it's a change from global Time to chart-initiated one.
