### ISSUE TITLE
Preformance issue with react bubble chart

### ISSUE THREAD

**Issue by vitaly87** [highcharts/highcharts#14237]
when you have grouping and 100 nodes then have performance issue, 

see example

https://jsfiddle.net/j5nxpv7d/

**Comment by PaulDalek** [comment]
Hi @vitaly87

Thank you for reporting this feature. The reason why you encounter poor performance and the long waiting time is because you set the `enableSimulation` property to false, which disables the animation of the whole simulation process. In case of small data sets it might work faster (https://jsfiddle.net/BlackLabel/o6j8fnpe/) but in case when data is bigger, it’s a better idea to show the simulation.

**Comment by vitaly87** [comment]
@PaulDalek  can we have any eta for this bug?

**Comment by PaulDalek** [comment]
@vitaly87 

As for now, I cannot provide you any ETA for this issue. We will take a closer look at it next week.
