### ISSUE TITLE
indicators Left and right will automatically fetch the day after or the day before if the data is empty

### ISSUE THREAD

**Issue by notbucai** [highcharts/highcharts#14248]
**Chinese translation, excuse me** [中文翻译，见谅]

indicators Left and right will automatically fetch the day after or the day before if the data is empty. [如果数据为空，左侧和右侧的指示器会在次日或前一天自动取数据。]

#### Expected behaviour
Expected data such as left and right null should be ignored [期望当前数据为空自动忽略而不是连接下一天数据] 

![image](https://user-images.githubusercontent.com/32786133/93713273-497b4f80-fb8d-11ea-808e-5e445a80dcba.png)

#### Actual behaviour
【实际会链接下一天】
![image](https://user-images.githubusercontent.com/32786133/93713269-3ff1e780-fb8d-11ea-93b6-56a571c0b080.png)

#### Live demo with steps to reproduce

template: https://jshare.com.cn/indicator/RSdgr8/15
#### Product version

Highstock JS v8.1.2 

#### Affected browser(s)
all

**Comment by pawelfus** [comment]
Hi @notbucai 

Thank you for reporting the issue. Unfortunately jshare is not working right now (502 Bad gateway). I believe your demo is the same as this one: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/indicators/sma/ ?

This is expected behaviour, line series render one point before and after the visible range. For example simple line series: https://jsfiddle.net/BlackLabel/v14wt0qj/1/

If you don't want this, use this workaround:
```js
Highcharts.seriesTypes.sma.prototype.cropShoulder = 0;
```
Demo: https://jsfiddle.net/BlackLabel/v14wt0qj/2/

**Comment by notbucai** [comment]
Thank you. This solves my problem
