### ISSUE TITLE
Screen reader order issues with stacked bar chart

### ISSUE THREAD

**Issue by obe-financial-com** [highcharts/highcharts#14255]
#### Expected behaviour
Each stacks should be  read in order while navigating through keyboard.

#### Actual behaviour
stacks are read starting from top right most stack, but not in correct order.

#### Live demo with steps to reproduce
https://jsfiddle.net/Osheen/uqk1x2jy/5/

#### Product version
8.2.0

#### Affected browser(s)
Chrome

**Comment by PaulDalek** [comment]
Hi @obe-financial-com 

Thank you for reporting this issue.

FYI @oysteinmoseng

**Comment by oysteinmoseng** [comment]
Screen readers will follow the DOM order here.

Workaround: Set [`yAxis.reversedStacks = false`](https://api.highcharts.com/highcharts/yAxis.reversedStacks). Example: https://jsfiddle.net/oysteinmoseng/c5vkpuw7/

**Comment by obe-financial-com** [comment]
@oysteinmoseng Thank you.
But while navigating using left and right arrow keys the order seems to be random.
What would be the possible reason for that?

**Comment by oysteinmoseng** [comment]
@obe-financial-com This is due to a [known issue](https://github.com/highcharts/highcharts/issues/14009) with inverted charts. The best workaround at this time is to use [serialized keyboard navigation](https://jsfiddle.net/1grvbeas/), where left/right behaves the same as up/down and go through point by point from the first to the last series. Apologies for the workarounds here, the keyboard navigation will be addressed in a future refactoring of the functionality.

**Comment by obe-financial-com** [comment]
ok . Thank you for the response @oysteinmoseng .

**Comment by VivianSi233** [comment]
@oysteinmoseng I found bug is not repro on latest highcharts https://www.highcharts.com/demo/highcharts/bar-stacked. **Could you please provide the highcharts version that you fixed this bug?** Bug is repro on our products because it is using highcharts V9.0.0.
