### ISSUE TITLE
Line graph date alignment issue with value 

### ISSUE THREAD

**Issue by crazyforbusiness** [highcharts/highcharts#14272]
#### Expected behaviour
Data and date on x axis should be aligned with each other. 

#### Actual behaviour
Data and date is not aligned.  
Check link for reference - https://prnt.sc/uouzin

**Comment by pawelfus** [comment]
Hi @crazyforbusiness 

Thanks for reporting the issue. This is expected behaviour: daily xAxis ticks are rendered at 00:00:00.000, while your data might have values at specific hours. You can observe this behaviour here: https://jsfiddle.net/BlackLabel/yor4kz53/ - first two points are rendered exactly at daily ticks, while the last two are not.

**Comment by karolkolodziej** [comment]
Closing as it is not a bug.
