### ISSUE TITLE
Highcharts boost mode problem 

### ISSUE THREAD

**Issue by benzmarkus** [highcharts/highcharts#14282]
#### Expected behaviour
Highcharts with activated boost mode is quite fast and highlighting if hovering over a serie is working.

#### Actual behaviour
Highcharts with activated boost mode is not fast and quite slow when deactivating series. Hovering over sieries is not working in boost mode if the user totally zoomed out.

Problem 1)
After loading all series are selected and the chart is on zoom level 0. I would say after deactivating some series the responsiveness of the chart get worse or freeze/hangs. I would say that removing points should make it faster. Sometimes it's fast and the responsiveness is ok during deactivation of all series. When I activate on series after another it hangs/freeze again.

Problem 2)
After loading all series are selected and the chart is on zoom level 0. Hovering over a series should highlight it. If i deactivate "category9" and "category10" (at zoom level 0) and hover over a serie the chart tries some highlighting but wrong.
This feature only works if I zoom in to reduce the number of points(arround 100 points are visible for example). On zoom level 0 it is not working. 

#### Live demo with steps to reproduce
https://stackblitz.com/edit/highcharts-boost-problem?file=src/app/app.component.ts

#### Product version
Highcharts version 8.0.0

#### Affected browser(s)
Chrome and all others

**Comment by pawelfus** [comment]
Hi @benzmarkus 

Thank you for reporting the issue.

Problem 1)
Consider setting [boost.seriesThreshold](https://api.highcharts.com/highcharts/boost.seriesThreshold). In your demo, only some of the series are in the boost mode. Demo: https://stackblitz.com/edit/highcharts-boost-problem-mg1aw4?file=src%2Fapp%2Fchart.ts

Problem 2)
Highlighting is disabled for series in boost mode. You see this "wrong" highlighting, because it's applied only to series that are not in boost mode. In my demo above you will see that all series are not highlighted at all (all series are in boost mode).
