### ISSUE TITLE
Range selector btns - out of the chart

### ISSUE THREAD

**Issue by miloszwojcik** [highcharts/highcharts#14292]
#### Expected behaviour
Range selector btns should gracefully come back to its previous position. 

#### Actual behaviour
Range selector btns are out of the screen. 

#### Live demo with steps to reproduce
https://jsfiddle.net/py04xj2g/2/

`Use toggle btn in the responsive mode` 

#### Product version
cdn

<img width="364" alt="Screen Shot 2020-10-02 at 10 09 11" src="https://user-images.githubusercontent.com/33060899/94902124-fca24d80-0497-11eb-8e35-e2255fec2206.png">

<img width="750" alt="Screen Shot 2020-10-02 at 10 08 23" src="https://user-images.githubusercontent.com/33060899/94902258-29566500-0498-11eb-9fe8-b595d3d9e36c.png">

**Comment by PaulDalek** [comment]
Hi @miloszwojcik

Thank you for reporting this issue. As for now you can disable `chart.animation` in order to prevent the misalignment.

**Demo**
https://jsfiddle.net/BlackLabel/q8Lw1abh/

_Internal note_
The `buttonGroup` of the `rangeSelector` is incorrectly aligned because of the small `width` when the `chart.animation` is enabled (the `render` function of the `RangeSelector` prototype).
