### ISSUE TITLE
Missing x-axis labels after series update

### ISSUE THREAD

**Issue by JelleVisser** [highcharts/highcharts#14293]
#### Expected behaviour
I initialized a column chart with data attached to it. The type of the `xAxis` is set to `category`. Then I update the series with new data that has different length and values in there. I expect the chart to update and display the new data using the correct `xAxis` labels.

#### Actual behaviour
I initialized a column chart with data attached to it. The type of the `xAxis` is set to `category`. Then I update the series with new data that has different length and values in there. The `xAxis` labels don't full get updated. Towards the end they seem to be using the index of the point instead of the value.

#### Live demo with steps to reproduce
https://stackblitz.com/edit/highcharts-xaxis-issue
Click the update button and you'll see that not all the x-axis labels get correctly updated (until you filter in legend or click it again atleast)

#### Product version
    "highcharts": "8.1.2",
    "highcharts-angular": "2.8.0",

#### Affected browser(s)
Chrome 85.0.4183.121
Firefox 80.0

---

Since this current data example actually contains dates converted to strings before passing it into the chart I also tried to not convert beforehand and use the `type: datetime`. Then it does properly update which is good. 

I just wonder why using `type: category` makes the updating fail here. Since Highcharts should be able to handle that as far as I knew.

**Comment by PaulDalek** [comment]
Hi @JelleVisser 

Thank you for reporting this issue. The behavior that you encounter is expected and it is caused by the [`cropThreshold`](https://api.highcharts.com/highcharts/series.column.cropThreshold) property. If you set it to higher or equal value than the number of points in a series, labels will display as expected.

**Demo**
https://stackblitz.com/edit/highcharts-xaxis-issue-efjhcy
