### ISSUE TITLE
Interface SeriesOptions.type should be optional?

### ISSUE THREAD

**Issue by BrianLaughlan** [highcharts/highcharts#14321]
![image](https://user-images.githubusercontent.com/8556999/95455904-d3d5f880-096e-11eb-9181-21d95f7feb75.png)

As mentioned in the description: 
`so unless the chart is a combination of series types, there is no need to set it on the series level.`

So the property `type` on `SeriesOptions` should be optional and not required? 

#### Product version
Highcharts v8.2.0

**Comment by KacperMadej** [comment]
Hi @BrianLaughlan 

Thank you for contacting us about the problem.

This is not an optional property by design - it is needed and required for TS. `type` could be set for the chart in JS, but TS needs `type` to be set on individual series level. (Mentioned in the API reference here: https://api.highcharts.com/highcharts/chart.type)

`type` is needed for the TS to know which series type the options are for. Some series types have different options or differently restricted properties, so to have TS tips and errors showing up correctly it is needed for TS to know which series type is it.

In general, we are using GitHub issues for bug reports and feature requests, so if you are not sure if a case is one of those types please contact technical support first. https://www.highcharts.com/blog/support/

This is not a bug and the issue will be now closed. However, if you would like for this issue to be reopened then please elaborate and leave a comment.
