### ISSUE TITLE
Pattern Fill - custom pattern fills with black

### ISSUE THREAD

**Issue by mikrotron** [highcharts/highcharts#14348]
#### Expected behaviour
When applying a custom pattern fill I should have the ability to control the fill color.

#### Actual behaviour
No matter what I do, the fill colour always appears to be black.

#### Live demo with steps to reproduce
https://codesandbox.io/s/pattern-fill-test-b78w0

- I've specified a custom pattern in the `defs` (it's actually using the path for `highcharts-default-pattern-5`).  
- I've tried a number of things, but it seems like adding `fill` to the `path` definition _should_ apply the fill background, but the chart still renders with a black fill.
  - https://github.com/highcharts/pattern-fill/blob/master/pattern-fill-v2.js#L87-L90  
- I'm not _sure_ but this seems to be specific to the `pattern-fill` v2 add-on, since I see the same behaviour when comparing very similar fiddles that were prepared by the HighCharts team:
  - White/transparent fill:
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/series/pattern-fill-pie
  - Black fill:
http://jsfiddle.net/highcharts/gqg618eb/

#### Product version
I'm using the latest versions:
```
    "highcharts": "7.2.0",
    "highcharts-pattern-fill": "3.0.3",
    "highcharts-react-official": "3.0.0",
```

#### Affected browser(s)
I've only been trying this in Chrome.

**Comment by PaulDalek** [comment]
Hi @mikrotron

Thank you for reporting this issue. First of all, in your demo you are using the old [pattern fill plugin](https://github.com/highcharts/pattern-fill). Use the [new module](https://code.highcharts.com/modules/pattern-fill.js). Secondly, this was a [bug](https://github.com/highcharts/highcharts/pull/12243) that was fixed in v7.2.1 by introducing a new option, `backgroundColor`.

**Demo**
https://jsfiddle.net/BlackLabel/mLz5anu8/
