### ISSUE TITLE
datalabels mispositioned for column range with stacking

### ISSUE THREAD

**Issue by pomack** [highcharts/highcharts#14359]
#### Expected behaviour
When using columnrange without stacking, the bars and data labels are in the right location. When we add stacking, the bars are overlaid properly. The datalabels should be attached to the correct endpoints of the bars.

#### Actual behaviour
When we add stacking, the data labels are flipped such that the values on the left end of the bar show up on the right end of the bar and vice versa.

#### Live demo with steps to reproduce
https://jsfiddle.net/pomack/r3f5wL0x/

#### Product version
Highcharts 8.2.0

#### Affected browser(s)
All (tested in Chrome and Safari)

**Comment by PaulDalek** [comment]
Hi @pomack,

Thank you for reporting this issue. It seems that the order of data labels is reversed by default in the stacked `columnrange` series. To resolve this you can [align](https://api.highcharts.com/highcharts/series.columnrange.dataLabels.align) labels explicitly.

**Demo**
https://jsfiddle.net/BlackLabel/oxe0v7zL/

**Comment by TorsteinHonsi** [comment]
Officially, the column range series [doesn't have a `stacking` option](https://api.highcharts.com/highcharts/plotOptions.columnrange.stacking). Since the points already have `low` and `high` values set, stacking logically doesn't make sense. Instead, what we see in the original demo is a side effect of the column series' stacking logic, which turns off stacking.

I think what @pomack wants to achieve is better done with `grouping`, and applying the data labels `inside`: https://jsfiddle.net/highcharts/7vhc8jo6/

If so, the actual bug is that `stacking` has an effect on the column range in the first place. Since it is not supported, it should not make a difference.

**Comment by pomack** [comment]
Thanks @TorsteinHonsi I didn't know about the `grouping` option, that works for me.
