### ISSUE TITLE
Highcharts issue Cannot read property 'attr' of undefined

### ISSUE THREAD

**Issue by ShrinivasNawgire** [highcharts/highcharts#14388]
Getting cannot read property 'attr' of undefined in Highcharts
I have used Highcharts library in Angular7 project, when trying to redraw chart it is throwing  attr undefined issue

**Comment by pawelfus** [comment]
Hi @ShrinivasNawgire 

Thanks for reporting the issue. However, could you please:
- check if you use official wrapper. If yes, then please report this bug here: https://github.com/highcharts/highcharts-angular 
- if you don't use official wrapper, please recreate issue without angular (just vanilla JS) in jsFiddle. Then create new issue and follow our bug-report template

Thanks!
