### ISSUE TITLE
An extra line is added if the maximum number of the x-axis matches the number of elements in a bar chart.

### ISSUE THREAD

**Issue by AngelCastellanosSegundo** [highcharts/highcharts#14380]
#### Expected behaviour
The correct number of elements is displayed if a limit is set on the x-axis in a bar chart.

#### Actual behaviour
An extra line is added if the maximum number of the x-axis matches the number of elements in a bar chart.

#### Live demo with steps to reproduce
Just run the example https://jsfiddle.net/Angel_Castellanos/3s761urL/2/

#### Product version
Highcharts 4.2.7 (latest version in the demo)

#### Affected browser(s)
All browsers

**Comment by pawelfus** [comment]
Hi @AngelCastellanosSegundo 

Thank you for using Highcharts! This is expected behaviour: when you sen `xAxis.max` to be higher than the amount of categories, extra categories will be filled with indexes. For example: https://jsfiddle.net/BlackLabel/pnq706xs/

Note that categories are indexed from 0, not from 1, so setting `xAxis.max = 7` creates 8 elements on the chart: 0, 1, 2, 3, 4, 5, 6, 7 categories. Demo: https://jsfiddle.net/BlackLabel/mg03bv49/

**Comment by AngelCastellanosSegundo** [comment]
The problem we have is that the number of categories is dynamic, depending on the data we have. We have to add the limit to the x-axis to avoid hiding the names (as happens if it is not limited and too much data is included). In this case, there is a possibility that the number of data coincides with the limit of the x-axis.

**Comment by AngelCastellanosSegundo** [comment]
For example, we don't want this:
https://jsfiddle.net/Angel_Castellanos/6379fwvt/1/

We want this
https://jsfiddle.net/Angel_Castellanos/sbdyphq6/2/

**Comment by pawelfus** [comment]
Set `max` conditionally then, for example: https://jsfiddle.net/BlackLabel/L4tvagq8/

**Comment by AngelCastellanosSegundo** [comment]
If in your example you leave only 8 categories, the error occurs again.

**Comment by pawelfus** [comment]
Good point, that should be the condition: https://jsfiddle.net/BlackLabel/L4tvagq8/1/
