### ISSUE TITLE
Boost connected null works when zooming out and then back again, but not the first time.

### ISSUE THREAD

**Issue by remlov** [highcharts/highcharts#14386]
#### Expected behaviour
From the docs, boost line series is represented by 1 pixel wide bars.

#### Actual behaviour
When zooming in, the bars are presented as documented, if I zoom out and then back in again, they are connected (preferred behavior).

#### Live demo with steps to reproduce
https://codepen.io/remlov/pen/yLJJZPy
Zoom in, zoom out, then zoom back in again.

#### Product version
Highcharts JS v8.2.0

#### Affected browser(s)
Google Chrome 86
Firefox 81.0.2
![Peek 2020-10-20 09-17](https://user-images.githubusercontent.com/338085/96599163-402cf200-12b5-11eb-8c4c-885bbb039035.gif)

 Is this something that we can surface the first time we zoom in? Connected lines seems to work partially.

**Comment by PaulDalek** [comment]
Hi @remlov

Thank you for reporting this issue. The reason why the points of the `area` series are connected is because when you zoom in to a specified range, the number of visible points is lower than the value of the [`boostThreshold`](https://api.highcharts.com/highcharts/series.area.boostThreshold) (by default it is 5000 for the `area` series) which results in turning off the boost mode. If you want to keep the boost effect on series you can set the `boostThreshold` or `seriesThreshold` to 1.

**Demo**
https://jsfiddle.net/BlackLabel/eqfudzt5/
