### ISSUE TITLE
Extra ticks with double y axes 

### ISSUE THREAD

**Issue by HighchartUser** [highcharts/highcharts#14399]
#### Actual behaviour

When i change container hight from 300 px to 700px . It automatically add  two extra ticks 
Note : I got this issue only when AlignTicks = True!! 

![image](https://user-images.githubusercontent.com/73242371/96745352-58406680-13c6-11eb-89cd-c738e05920d0.png)

![image](https://user-images.githubusercontent.com/73242371/96745885-e4528e00-13c6-11eb-8b5f-a76c0438c51d.png)

#### Live demo with steps to reproduce

Demo => https://jsfiddle.net/0okcqy2m/17/
This chart has two axes. The second axis contains a **copy of the first serie**
#### Product version

Highcharts 8.1.1
#### Affected browser(s)
chrome 85.0.4183.121

**Comment by pawelfus** [comment]
Hi @HighchartUser 

Thanks for being Highcharts User! :) And for reporting this issue. This issue comes from the fact we are trying to match yAxis extremes for both axis, adding to the second axis extra tick(s) and increasing extremes. In this particular case it's unnecessary.

**Simplified demo:**
https://jsfiddle.net/BlackLabel/pLv5r48o/

**Workaround:**
Set `xAxis.tickAmount`: https://jsfiddle.net/BlackLabel/pLv5r48o/1/
