### ISSUE TITLE
Line disappears after adding to series more than once

### ISSUE THREAD

**Issue by HardlyMirage** [highcharts/highcharts#1439]
If you dynamically add points to a series more than once, the line / spline disappears, and you can only see the datapoints.

See this example based off of Basic Line Example
http://jsfiddle.net/Hycnq/

Test in Chrome / Windows 7

**Comment by leongaban** [comment]
Hi sorry to comment on a closed Issue, but this keeps happening to me, and I don't know why. No idea where to look, what to look for, why a graph would go away in a charting library :( Please help! 

[chart](http://oi67.tinypic.com/30naix4.jpg)

http://oi67.tinypic.com/30naix4.jpg

I have a stock price line that disappears, I check my chartObject and the Series is still there, the Array of points which are in Numbers is still there, when I hover over the chart I see the points of the line highlighted! However the Line is no where to be seen :(

This happens when I resize the window, when I change Tickers ie: new data for the Price line, when I change timespans, when I add or remove Area graph data :(

Sorry just 2 straight long weeks of frustration.

**Comment by KacperMadej** [comment]
@leongaban Let's continue on [Stack Overflow question](http://stackoverflow.com/questions/35345791/price-line-disappears-in-highchart), because we use github for reporting bugs and SO (among [other support channels](http://www.highcharts.com/support)) for support.

Thank you and have a nice day.

**Comment by leongaban** [comment]
Sorry @KacperMadej! Btw we finally figured it out, and wanted to share since this has been the most frustrating bugs I've run into in years.

It was a tooltip function

```
    tooltip: { 
        // pointFormatter: tooltipFormatter,
        shared: true
    }
```

```
function tooltipFormatter(that) {
    if (this.color === "#4C73FF" && this.y > 0) {
        this.y = '$' + this.y.formatMoney(2);
    } else if (this.y > 999) {
        this.y = this.y.formatCommas();
    }
    return '<span style="color:' + this.color + '">\u25CF</span> ' + this.series.name + ': <b>' + this.y + '</b><br/>';
}
```

http://stackoverflow.com/questions/35345791/price-line-disappears-in-highchart/35492459#35492459

**Comment by KacperMadej** [comment]
@leongaban  Glad to hear that your problem is resolved. Thank you for sharing your solution and code.
