### ISSUE TITLE
Range input changes date when losing focus (blur)

### ISSUE THREAD

**Issue by nunoarruda** [highcharts/highcharts#14416]
#### Expected behaviour
1. Click inside the "To" input (focus)
2. Click outside the "To" input (blur)
3. Nothing should happen because nothing was modified

#### Actual behaviour
1. Click inside the "To" input (focus)
2. Click outside the "To" input (blur)
3. The "To" date changes from `Jan 4 1970` to `Jan 3 1970`
![hc-range-input-bug](https://user-images.githubusercontent.com/1189149/97023735-754f7380-1545-11eb-93f0-99cfa3779789.gif)

#### Live demo with steps to reproduce
https://jsfiddle.net/nunoarruda/ys9qzubn/22/

This issue seems to happen only with the following set of options:
```
time: {
    timezoneOffset: 420
},
xAxis: {
    minRange: 3600 * 1000 // one hour
},
series: [
    {
      pointInterval: 24 * 3600 * 1000,
      data: [1, 2, 3, 4, 5]
    }
]
```

#### Product version
Highstock JS v8.2.2 (2020-10-22)

#### Affected browser(s)
All of them

**Comment by PaulDalek** [comment]
Hi @nunoarruda

Thank you for reporting this issue. This is a regression (the latest working version is 6.2.0). The internal `updateExtremes` function sets the new extremes incorrectly.

**Demo**
https://jsfiddle.net/BlackLabel/wn8huycp/

_Internal note_
Bisect led to this commit: https://github.com/highcharts/highcharts/commit/793866c5e0fa1989963cc042d7d60fb59c53a2b1

FYI @TorsteinHonsi

**Comment by TorsteinHonsi** [comment]
_Internal note_
The offending commit only added the functionality to always update the extremes. The real issue is probably related to date parsing and time zones.

Check out this case too: https://jsfiddle.net/e29juqhs/
* Change the _to_ date to 1970-01-10, then hit Enter => The date now jumps to 01-08.
* The input still has focus. Now click anywhere outside the input. => The date now jumps to 01-07.
