### ISSUE TITLE
Histogram- inaccuracy in calculating binWidth and binsNumber

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#14425]
#### Expected behaviour
Introduce a mechanism preventing inaccuracy in this calculation.
As a workaround, manually apply bins number which divides range easily.
Demo: https://jsfiddle.net/BlackLabel/0ufxmzd6/

#### Actual behaviour
In the example given below, for the default settings (`binsNumber: "square-root"`) there are 7 bins.
Further calculations don't give a nice number `1/7 ~ 0.142857142857142...`
As a result of that, the last column doesn't contain the full number `21`.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/3468xavw/

#### Product version
Highcharts JS v8.2.2

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
The same happens when setting `binsNumber` to `3` (or `6`, `7`, `9`, `11` ... - so any `1/X` which will produce recurring decimal fraction). Demo: https://jsfiddle.net/BlackLabel/0ufxmzd6/2/

It seems points are placed correctly in the last bin (correct y-value for the bin), so probably we need to fix where the bin ends.

FYI @Denyllon

**Comment by Denyllon** [comment]
As we all know, dealing with decimal numbers (natively in JS, without any 3rd party libraries) is not so easy, and produces a bunch of generic, rounding nature errors which sometimes cannot be predictable. The problem is that even Highcharts built-in `correctFloat` utility is not able to operate on them correctly, and sometimes returns wrong/unexpected results.

For now, since all data points are correctly distributed between the bins, I think that sufficient compromise while getting rid of this problem, would be to set the last bin's end on the dataMax of the series on which histogram is based on.

Demo with workaround: https://jsfiddle.net/BlackLabel/8p4Lkfct/
