### ISSUE TITLE
Update the component „SimpleRisk“

### ISSUE THREAD

**Issue by Creovafix** [highcharts/highcharts#14429]
I am testing Highcharts in our company environment in order to use it productivelly a.s.a.p. Of course, after a purchase.
 
One part of testing was security check done by our IT security colleagues. They did not find any significant issues. But there is a request to update the component „SimpleRisk“" on version 3.5.1. There are some old libraries which should be updated as well. See attached pictures, please.

![simplerisk](https://user-images.githubusercontent.com/73342728/97182191-8219d480-179c-11eb-9489-95125deeba86.jpg)

![libraries](https://user-images.githubusercontent.com/73342728/97182209-8940e280-179c-11eb-81e3-ba606fcc5e52.jpg)
[Highcharts-1.0-Oct-16-2020-08-58-53-_00_00.zip](https://github.com/highcharts/highcharts/files/5439255/Highcharts-1.0-Oct-16-2020-08-58-53-_00_00.zip)

Can you implement recent versions in Highcharts, please? Can you let me know when Highcharts with at least „SimpleRisk“ update can be available, please? I hope your answer will satisfy our IT security in order to allow a purchase of Highcharts.
 
Thank you in advance.

**Comment by pawelfus** [comment]
Hi @Creovafix 

Thanks for considering Highcharts!

We are not authors of `SimpleRisk` component. I suggest to contact authors ans ask them.

Kind Regards,
Paweł

**Comment by Creovafix** [comment]
Hello Pawel,
I understand that SimpleRisk is not your product but it is a component of Highcharts. Then, I think, is correct that you as manufacturer will put up-to-date component(s) in your product. I as user of the application have no chance to do it. It is in your code. See attached picture, please.
![simplerisk](https://user-images.githubusercontent.com/73342728/97967091-08e23900-1dbd-11eb-95db-98d08a8e581b.png)

Be so kind and update reported components in order to make Highcharts safer, please. I think your customers will appreciate it.

P.S. We as an OEM manufacturer also use components from other producers. It is up to us to use up-to-date components or SW in our final products without regards that those components are not produced by us. E.g. control units or anything else. We can not say to our customers - update or replace it yourself. It is our product so it is our task. Thanks that we can guarantee that our products are safe and secure. You should do the same, please.

**Comment by pawelfus** [comment]
Hi @Creovafix 

I'm sorry for the confusion. Let me explain:

> I understand that SimpleRisk is not your product but it is a component of Highcharts.

We don't use it, SimpleRisk is not a component of Highcharts.

Just double checked the package you attached in your first post. I don't know how to interpret these security CSV files, but for me it seems someone created a package (?) names Highcharts 1.0 (?) including Highcharts v8.1.2 and all security errors are related to `jQuery` (XSS) or `SimpleRisk` (CSRF). Highcharts does not need jQuery or SimpleRisk to work correctly.

Could you tell us how or where do you use Highcharts? And how the screenshot above is related to the issue? Thanks for your help!

> Be so kind and update reported components in order to make Highcharts safer, please. I think your customers will appreciate it.
> 
> P.S. We as an OEM manufacturer also use components from other producers. It is up to us to use up-to-date components or SW in our final products without regards that those components are not produced by us. E.g. control units or anything else. We can not say to our customers - update or replace it yourself. It is our product so it is our task. Thanks that we can guarantee that our products are safe and secure. You should do the same, please.

I completely agree with you. It is up to the product provider to fix all security issues.

**Comment by Creovafix** [comment]
May we make Skype/Teams session in order to explain it, please? If yes, let me know your e-mail address, please.

**Comment by pawelfus** [comment]
@Creovafix If you have license with Active Advantage, you can contact us via Skype (but chat only). However I believe you can explain it here..

**Comment by Creovafix** [comment]
Hello Pawel,

I evaluated Highcharts in order to decide if we will buy it. I did the following steps:

1.     Download ZIP file from Support > Download page

2.     Unzip files in our intranet web server

3.     Create test page with Highcharts using our data. Example attached.

Our IT security checked the content of the ZIP file and then asked for reported actions. The question is reported components are used/active when we use only HTML page with a reference to the selected chart?

            Kind regards

                        Jan

Ing. Jan Vesecký, FIE – Procesní a systémová integrace – podpora vývoje produktu a správy dat | Process and system integration – Product development and data management support
ŠKODA AUTO a.s., tř. Václava Klementa 869, 293 01 Mladá Boleslav II, Czech Republic
T +420 326 8 17576
jan.vesecky@skoda-auto.cz<mailto:jan.vesecky@skoda-auto.cz>, www.skoda-auto.com<http://www.skoda-auto.com/>

[cid:image001.png@01D6B28C.88C75A20]

**Comment by pawelfus** [comment]
Thank you for the details @Creovafix 

Our ZIP package contains some demos that use jQuery. We are constantly updating these old demos to use vanilla JS. Anyway, you don't want to unzip all files in your webserver. Unzip package locally and copy to your server the distribution files from the folder `code`. You probably will not use all files, but for the security check you may want to copy them all.

>  Create test page with Highcharts using our data. Example attached.

Could you attach it here, on GH? Attaching in email does not attach anything on GH.

Thank you

**Comment by Creovafix** [comment]
[status.31.08.2020_hch.zip](https://github.com/highcharts/highcharts/files/5487757/status.31.08.2020_hch.zip)

**Comment by Creovafix** [comment]
As I see, reported issues with SimpleRisk is in folder code/lib/canv.js + canvg.src.js + rgbcolor.js

**Comment by pawelfus** [comment]
Thank you for the demo, I see nothing wrong with it

> As I see, reported issues with SimpleRisk are in folder code/lib/canvg.js + canvg.src.js + rgbcolor.js

The libs you reported are optional dependancies (see: https://www.highcharts.com/docs/getting-started/optional-dependencies). `security.csv` from your first post reports only issues in jQuery and SimpleRisk. Other files mentions libraries like Phaser or dc.js, which are definitively not related to Highcharts usage and the website you send me above. I don't see any issue report related to canvg/rgbcolor in the attached package (only a screenshot is showing them, but I don't see any issues reported there).

Could you ask your IT security colleagues to provide more details? What kind of vulnerabilities they have found?


PS: This is the `security.csv` file I mean:

Used by | Component id | Version id|Origin id|Component name|Component version name|Component origin name|Component origin id|Component origin version name|Vulnerability id|Description|Published on|Updated on|Base score|Exploitability|Impact|Vulnerability source|Remediation status|Remediation target date|Remediation actual date|Remediation comment|URL|Security Risk|Project path
----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----
|7a777763-ac31-4919-8f49-52e373f3af41|1f3eaebb-67a2-4037-b2e2-d0abc4606cb4|e63d1f91-f2b7-43ca-8a86-71e3f04ff533|jQuery|2.0.0|unknown||2.0.0|BDSA-2017-2930 (CVE-2015-9251)|jQuery is vulnerable to cross-site scripting (XSS) due to the way it processes certain types of Ajax requests. This can allow potential attackers to execute arbitrary code on the target system.|6.3.18|26.5.20|4.3|8.6|2.9|BDSA|NEW|||||MEDIUM|FIE - Highcharts 1.0
|7a777763-ac31-4919-8f49-52e373f3af41|1f3eaebb-67a2-4037-b2e2-d0abc4606cb4|e63d1f91-f2b7-43ca-8a86-71e3f04ff533|jQuery|2.0.0|unknown||2.0.0|BDSA-2015-0567|jQuery versions which make of use of an unpatched UglifyJS parser are vulnerable to arbitrary code execution through crafted JavaScript files.|6.3.18|15.4.20|4.3|3.1|6.4|BDSA|NEW|||||MEDIUM|FIE - Highcharts 1.0
|7a777763-ac31-4919-8f49-52e373f3af41|1f3eaebb-67a2-4037-b2e2-d0abc4606cb4|e63d1f91-f2b7-43ca-8a86-71e3f04ff533|jQuery|2.0.0|unknown||2.0.0|BDSA-2014-0063|jQuery is vulnerable to cross-site scripting (XSS) due to lack of validation of user-supplied input. This could allow an attacker to inject arbitrary web scripts and steal a victim's session cookies.|23.5.18|15.4.20|4.3|8.6|2.9|BDSA|NEW|||||MEDIUM|FIE - Highcharts 1.0
|7a777763-ac31-4919-8f49-52e373f3af41|1f3eaebb-67a2-4037-b2e2-d0abc4606cb4|e63d1f91-f2b7-43ca-8a86-71e3f04ff533|jQuery|2.0.0|unknown||2.0.0|BDSA-2019-1138 (CVE-2019-11358)|"An improper input validation vulnerability has been discovered in JQuery. An attacker could exploit this vulnerability to execute cross-site scripting (XSS) attacks| trigger a denial-of-service (DoS) condition| or gain unauthorized access to the application."|23.4.19|23.4.19|4.3|8.6|2.9|BDSA|NEW|||||MEDIUM|FIE - Highcharts 1.0
|7a777763-ac31-4919-8f49-52e373f3af41|1f3eaebb-67a2-4037-b2e2-d0abc4606cb4|e63d1f91-f2b7-43ca-8a86-71e3f04ff533|jQuery|2.0.0|unknown||2.0.0|BDSA-2020-0686|It was discovered that jQuery could allow for cross-site scripting (XSS) vulnerabilities to be introduced if `jQuery.htmlPrefilter` method is used. Attackers could exploit XSS vulnerabilities to execute JavaScript code in a target's browser by tricking them into accessing the vulnerable page. This would allow an attacker to steal an administrator's session tokens or execute arbitrary code on their behalf by sending the link to an unsuspecting user or waiting for them to discover it.|14.4.20|3.10.20|4.3|8.6|2.9|BDSA|NEW|||||MEDIUM|FIE - Highcharts 1.0
|7a777763-ac31-4919-8f49-52e373f3af41|1f3eaebb-67a2-4037-b2e2-d0abc4606cb4|e63d1f91-f2b7-43ca-8a86-71e3f04ff533|jQuery|2.0.0|unknown||2.0.0|BDSA-2020-0955 (CVE-2020-11022)|It was discovered that jQuery could allow for cross-site scripting (XSS) vulnerabilities to be introduced if Document Object Model (DOM) manipulation methods are used. Attackers could exploit XSS vulnerabilities to execute JavaScript code in a target's browser by tricking them into accessing the vulnerable page. This would allow an attacker to steal an administrator's session tokens or execute arbitrary code on their behalf by sending the link to an unsuspecting user or waiting for them to discover it.|1.5.20|1.6.20|4.3|8.6|2.9|BDSA|NEW|||||MEDIUM|FIE - Highcharts 1.0
|7a777763-ac31-4919-8f49-52e373f3af41|1f3eaebb-67a2-4037-b2e2-d0abc4606cb4|e63d1f91-f2b7-43ca-8a86-71e3f04ff533|jQuery|2.0.0|unknown||2.0.0|BDSA-2020-0964 (CVE-2020-11023)|It was discovered that jQuery could allow for cross-site scripting (XSS) vulnerabilities to be introduced if certain HTML is passed to Document Object Model (DOM) manipulation methods. Attackers could exploit XSS vulnerabilities to execute JavaScript code in a target browser by tricking them into accessing the vulnerable page. This would allow an attacker to steal an administrator's session tokens or execute arbitrary code on their behalf by sending the link to an unsuspecting user or waiting for them to discover it.|1.5.20|1.6.20|4.3|8.6|2.9|BDSA|NEW|||||MEDIUM|FIE - Highcharts 1.0
|b95ffaf0-544c-4f24-b112-313ec6bd4e13|df22d236-9575-44a1-acc0-fe0c843a0a3f|48363be0-f1ce-4fee-a575-4d730fbddf55|SimpleRisk|20170614-001|unknown||20170614-001|CVE-2017-10711|"In SimpleRisk 20170614-001| a CSRF attack on reset.php (aka the Send Password Reset Email form) can insert XSS sequences via the user parameter."|24.7.17|10.8.17|4.3|8.6|2.9|NVD|NEW||||https://nvd.nist.gov/vuln/detail/CVE-2017-10711|MEDIUM|FIE - Highcharts 1.0

**Comment by pawellysy** [comment]
Closed due to inactivity
