### ISSUE TITLE
Circular stacking diagram ball problem

### ISSUE THREAD

**Issue by weixingcai** [highcharts/highcharts#14439]
#### 
The small balls do not stack and are not outside the big ones

#### 
The spheres are stacked on top of each other, outside of the larger spheres

#### Live demo with steps to reproduce
https://jshare.com.cn/public/E0GmQv
![微信截图_20201027215808](https://user-images.githubusercontent.com/48822299/97311639-87ac1300-189f-11eb-92b3-4f978f88ca17.png)

**Comment by pawelfus** [comment]
Thank you for reporting the issue @weixingcai I don't see any reliable workaround right now, except for setting `minSize` to number, instead of a string (percentage value).

*Simplified demo:*
https://jsfiddle.net/BlackLabel/kj2v5r13/1/

*Internal note:*
Only four iterations of the simulation are run. Temperature diff between last two iterations is quite low, might be the reason?
FYI @Izothep

**Comment by Izothep** [comment]
Hi @weixingcai! 

Thank you for reporting the issue.

As a workaround, it should be possible to slightly change the `layout.step` method for forcing first few iterations of simulation:
https://jsfiddle.net/9kjvh8L0/
