### ISSUE TITLE
Spurious line with xAxis.max in stockchart

### ISSUE THREAD

**Issue by govinda18** [highcharts/highcharts#14431]
#### Expected behaviour
Should not show any line at the end with `xAxis.max` being set.

#### Actual behaviour
![image](https://user-images.githubusercontent.com/25079291/97277033-f7011300-185d-11eb-84f9-0d7fb5d9c352.png)

A straight line is drawn at the end which should not be there. I tried to reproduce this with a smaller data set as it would not be possible to paste the entire data set in the fiddle. 

https://jsfiddle.net/5f6n20as/ - The line here is pretty small but it gets bigger and bigger with increase in data size.

Not sure if it is a bug or something I have done wrong. Can you please look into this and let me know? 

Thanks.

#### Product version
Highstock JS v8.2.2 (2020-10-22)

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @govinda18 

Thank you for reporting the issue. Do you mean this line?
![Screenshot 2020-10-27 at 10 15 02](https://user-images.githubusercontent.com/1453926/97281143-73372e80-183d-11eb-8ece-30006171ccac.png)

If yes, then this is expected behaviour. You have a point with `x` value higher than `xAxis.max`. That line is reaching that point, you cna see this by removing `xAxis.max`.
![Screenshot 2020-10-27 at 10 15 15](https://user-images.githubusercontent.com/1453926/97281145-74685b80-183d-11eb-8f2a-0d93ab66af11.png)

**Comment by govinda18** [comment]
The point I added is intentional actually. What I don't understand here is that since I have set `xAxis.max`, what I expect is the line should just end at that position and nothing beyond that point should be visible. You can see that the xAxis.max is equal to the last second point being rendered.

Have I got the meaning of `xAxis.max` wrong here?

**Comment by pawelfus** [comment]
You understand this correctly, however line has it's own width (2px by default) which is why you see it partially (part of the line is still within the plotting area). You can observe this better by increasing `lineWidth`: https://jsfiddle.net/BlackLabel/pqbs5hv6/

**Comment by govinda18** [comment]
Thanks pawelfus. I kind of understand this. So basically since the line is taking such a sharp drop and with large number of points, it is like rendering two points at the same x(very very close x). Thanks. Closing the issue.
