### ISSUE TITLE
In pie chart the centre of the pie is fading

### ISSUE THREAD

**Issue by aditya-padhi-kbl** [highcharts/highcharts#14447]
Hi Team,

I was experimenting with the pie chart and came across an use case where the centre of the pie was fading.
#### Expected behaviour

Centre of the pie should not fade.
#### Actual behaviour
Centre of the pie is fading

#### Live demo with steps to reproduce
https://jsfiddle.net/guf9514y/

#### Product version
HighChart Version:- 7.2.1

#### Affected browser(s)
Chrome, Firefox, Safari

**Comment by PaulDalek** [comment]
Hi @aditya-padhi-kbl

Thank you for reporting this issue. This behavior is not a bug and it is caused by the [`borderWidth`](https://api.highcharts.com/highcharts/series.pie.borderWidth) option which by default is set to 1. Set it to 0 to see the expected result.

**Demo**
https://jsfiddle.net/BlackLabel/o09ecvub/

**Comment by aditya-padhi-kbl** [comment]
> Hi @aditya-padhi-kbl
> 
> Thank you for reporting this issue. This behavior is not a bug and it is caused by the [`borderWidth`](https://api.highcharts.com/highcharts/series.pie.borderWidth) option which by default is set to 1. Set it to 0 to see the expected result.
> 
> **Demo**
> https://jsfiddle.net/BlackLabel/o09ecvub/

Thank-You @PaulDalek for the quick response.
