### ISSUE TITLE
Legend set width and height problem

### ISSUE THREAD

**Issue by weixingcai** [highcharts/highcharts#14445]
#### Expected behaviour
Legend should not overlap there should be a gap between the top and bottom

#### Actual behaviour
The legend overlaps

#### Live demo with steps to reproduce
https://jshare.com.cn/public/K0GmLr
![11111](https://user-images.githubusercontent.com/48822299/97402497-9e00b000-192d-11eb-8d86-986875f2fdaa.png)

**Comment by PaulDalek** [comment]
Hi @weixingcai

Thank you for reporting this issue. In order to prevent symbols from overlapping, you can use [`itemMarginBottom`](https://api.highcharts.com/highcharts/legend.itemMarginBottom) and [`itemMarginTop`](https://api.highcharts.com/highcharts/legend.itemMarginTop) options and set them with a higher values.

**Demo**
https://jsfiddle.net/BlackLabel/zxvmuk1d/

**Comment by weixingcai** [comment]
https://jshare.com.cn/public/M0GmLg

![22222](https://user-images.githubusercontent.com/48822299/97423364-11181f80-194a-11eb-9350-19289f624c20.png)

When itemMarginBottom and itemMarginTop are set, their height and text cannot be aligned

**Comment by PaulDalek** [comment]
@weixingcai

You can correct the position of a legend symbol by manually modifying its y position on load event.

**Demo**
https://jsfiddle.net/BlackLabel/08dte5fh/
