### ISSUE TITLE
Treemap color format with drilldown

### ISSUE THREAD

**Issue by hihajdus** [highcharts/highcharts#14457]
#### Expected behaviour
When I set parent color in solid, hex or rgb color format, the children's color shouldn't visible in the main view.

#### Actual behaviour
When I set the parent color to hex or rgb, the children's color is visible in the parent view. 
However, when I set the parent color to a solid, for example Color: "red", the color of the children is not visible in the main view.

#### Live demo with steps to reproduce
[https://jsfiddle.net/BlackLabel/1Lho0mx2/1/](https://jsfiddle.net/BlackLabel/1Lho0mx2/1/)

#### Product version
Highcharts v8.2.2

**Comment by sebastianbochan** [comment]
Extra demo:
- https://jsfiddle.net/BlackLabel/pLe1ht45/

**Comment by pawelfus** [comment]
This is expected behaviour: opacity of the parent node is controlled via [`series.opacity`](https://api.highcharts.com/highcharts/series.treemap.opacity) options.

This does not apply to named colors ("red", "blue" etc) - this is not a supported format for color, see [docs](https://www.highcharts.com/docs/chart-design-and-style/colors).

**Comment by sebastianbochan** [comment]
You are right, my fault, sorry!
