### ISSUE TITLE
export PNG leads callback prop to be executed with a "broken" chart

### ISSUE THREAD

**Issue by sinanmert** [highcharts/highcharts#14454]
#### Expected behaviour
The **chart** parameter from the **callback** prop after exporting to PNG is having same content as before.

#### Actual behaviour
The **chart** parameter from the **callback** prop after exporting to PNG is somewhat broken or not complete.
![Highcharts Bug](https://user-images.githubusercontent.com/6482654/97553303-90066a00-19d5-11eb-8ec4-95c218d784ef.gif)

#### Live demo with steps to reproduce
https://codesandbox.io/s/highcharts-react-simple-chart-forked-5niu7?file=/demo.jsx

1. Initial load of Highcarts Graph
2. Check the console and the content of the parameter **chart**
3. Click "Download PNG image"
4. Check the console and the content of the parameter **chart** again

#### Product version
Reproducible in Version 8.0.4 and latest. Other not tested. 

#### Affected browser(s)
Chrome, Edge. Others not tested.

**Comment by PaulDalek** [comment]
Hi @sinanmert

Thank you for reporting this issue. The `chart` from the second run of the `callback` is like that because it isn’t the same `chart` as the one rendered in the container div. It is a copy of it, created in the process of exporting (see the `getSVG` function of the [exporting module](https://code.highcharts.com/modules/exporting.src.js)). After acquiring the SVG, it is destroyed (that’s why it’s empty).
