### ISSUE TITLE
Updating Stockchart dynamically

### ISSUE THREAD

**Issue by govinda18** [highcharts/highcharts#14479]
#### Expected behaviour
Should respect the datetime type for xAxis.

#### Actual behaviour
On updating stock chart dynamically, the time stamp is rendered. However the tooltip works fine. Note that the time stamp is also rendered in correctly. Another thing I noticed was that removing `xAxis.categories` works just fine.

#### Live demo with steps to reproduce
https://jsfiddle.net/4skwz0yj/2/

#### Product version
Highstock JS v8.2.2 (2020-10-22)

#### Affected browser(s)
Chrome

**Comment by PaulDalek** [comment]
Hi @govinda18

Thank you for reporting this issue. The reason why labels of the `xAxis` look like this is because you added the `categories` array on the update. Categories are counted from 0 and are distributed every 1. Since there are only three categories, the rest of the labels will be numeric. You can easily see what I’m talking about when you add an additional first point `[0, 0]` (https://jsfiddle.net/BlackLabel/q4uv9wes/). You don’t need to add categories in order to change the format of dates, you can do it through the [`dateTimeLabelFormats`](https://api.highcharts.com/highstock/xAxis.dateTimeLabelFormats).

**Demo**
https://jsfiddle.net/BlackLabel/7tpd8zfs/
