### ISSUE TITLE
Histogram bins start must be correlated with xAxis min value

### ISSUE THREAD

**Issue by aleksandr-kovalenko** [highcharts/highcharts#14489]
#### Expected behaviour
Bins must be 2-3, 3-4, 4-5

#### Actual behaviour
Bins are 1.5-2.5, 2.5-3.5, 3.5-4.5
xAxis min equals to 2 and as a result we get first bin truncated

#### Live demo with steps to reproduce
https://jsfiddle.net/ptq7fu2c/

#### Product version
 Highcharts JS v8.2.2 (2020-10-22)

#### Affected browser(s)
Chrom v.86.0.4240.111

#### Preliminary analysis
Need to use xAxis min/max values if they are defined during calculating bins in https://github.com/highcharts/highcharts/blob/master/js/Series/HistogramSeries.js#L115
If it is intended behaviour then may be it is possible to create separate property in options to switch to the way of calculating bins described in this report.

**Comment by PaulDalek** [comment]
Hi @aleksandr-kovalenko

Thank you for reporting this issue. The minimum value in the `data` array is 1.5, therefore the first bin will start from this value. Setting `min` to 2 will cut the first bin because of that. If you get rid of the 1.5 value, bin will start form 2. The property that controls the width of a bin is [`binWidth`](https://api.highcharts.com/highcharts/series.histogram.binWidth).

**Demo**
https://jsfiddle.net/BlackLabel/q273pmxe/
