### ISSUE TITLE
Issue with crisp : false for column in case of DST and other scenario

### ISSUE THREAD

**Issue by ashishwin8** [highcharts/highcharts#14491]
We were wondering why crisp : false is not default in your code.

But crisp : false option is buggy as spacing between columns is not absolute zero, even after setting all properties to zero.

If you zoom following screen shot, you will see fine line is shown everywhere except between 27 Oct and 28 Oct.
Another serious issue we found during testing is when we use crisp: false, it does NOT work in case of DST data

DST Fallback occurred for US time zones last Sunday 1-November-2020

Here is the fiddle showing the gap for the 7 days where DST fallback happened
http://jsfiddle.net/9fseLu84/

Gap is visible between 1-Nov and 2-Nov.
Note : DST is switched on 1-Nov, so it was 25 hour long day

Issue is seen with 7.2.1 as well as 8.2.2 (latest as of today)
<img width="687" alt="hc_crisp_spacing_issue" src="https://user-images.githubusercontent.com/71814824/98224280-4db2cf00-1f79-11eb-9fcf-ca9ea70160a3.png">
<img width="428" alt="hc_crisp_dst_spacing_issue" src="https://user-images.githubusercontent.com/71814824/98224369-691dda00-1f79-11eb-9ac8-ffb6f7d9c41a.png">

**Comment by pawelfus** [comment]
Hi @ashishwin8 

Thank you for reporting this issue(s). Let me explain them:

- Crisp: when `crisp` is set to false, we let **browser** handle the antyaliasing. We have no control over it, it makes columns blurry, overlapping etc or not. That is why, by default, we decided to set `crisp=true`, and round columns to the nearest full pixel. In many scenarios, columns are not tightly packed, and sharp rendering the highest higher priority.

- DST: Columns in Highcharts share the same width, which is calculated (or translated to pixel width) from the two closest points in your dataset (24hours in your dataset, for every point). If you want variable-width columns, then use [`variwide`](https://api.highcharts.com/highcharts/plotOptions.variwide) series.

**Comment by ashishwin8** [comment]
Hi Paweł,

Thanks for the response.


  1.  This is the response we got for our problem http://jsfiddle.net/j4kdLhq6/<https://urldefense.proofpoint.com/v2/url?u=http-3A__jsfiddle.net_j4kdLhq6_&d=DwMFaQ&c=Hlvprqonr5LuCN9TN65xNw&r=SWUcUPuxwiUGRX-aitZj4ns5kPr656UinE2QHpALpvo&m=TE-2yOp-F2RE9wMRBcJ58GuYtFY-qN3Nfj7xnq6wEe4&s=BgI00opzJ8RBz4W6miZyLcNnY0vHPnuPQ-33597MsyE&e=>

[cid:image002.jpg@01D6B3B2.375ADAA0]

As per your response then setting crisp : false is not right solution for this problem

This is the response we got for original ticket. Let us know the right solution for the problem.

>> I've investigated the issue more deeply and this is a known problem of rendering. For example, we have a 100px wide plot area and three columns to render. So each column will >> have 33.33 px and there will be little gaps between all columns or we will have all columns 33 px wide and 1 empty pixel. The first solution can be achieved by disabling the
>> series.crisp option. Check the API and demo posted below.
​
>> API: https://api.highcharts.com/highcharts/series.column.crisp<https://urldefense.proofpoint.com/v2/url?u=https-3A__api.highcharts.com_highcharts_series.column.crisp&d=DwMFaQ&c=Hlvprqonr5LuCN9TN65xNw&r=SWUcUPuxwiUGRX-aitZj4ns5kPr656UinE2QHpALpvo&m=8v7Gt2Y7Yo-mRCZ84n96FIORlGs-ktk3-oFqktRt-Eo&s=6kWDHtT70u3_UxSd9YW89ukxPHLwrwnqM7NiH62w9bo&e=>
>> Demo: http://jsfiddle.net/BlackLabel/40cdejLz/<https://urldefense.proofpoint.com/v2/url?u=http-3A__jsfiddle.net_BlackLabel_40cdejLz_&d=DwMFaQ&c=Hlvprqonr5LuCN9TN65xNw&r=SWUcUPuxwiUGRX-aitZj4ns5kPr656UinE2QHpALpvo&m=8v7Gt2Y7Yo-mRCZ84n96FIORlGs-ktk3-oFqktRt-Eo&s=CAk8OSa_vIGfBQfFYXAW6J-xnqrNaylox-76KdFgON8&e=>


  1.  We don’t want variable width columns.

As we are showing “day” worth of data, all columns should have sane width.
              This is the fiddle http://jsfiddle.net/9fseLu84/

[cid:image004.jpg@01D6B3B2.375ADAA0]

Let us know what is the right solution for these two problems

Thanks,
Ashish

**Comment by pawelfus** [comment]
Could you answer directly on GitHub? I don't see any images you attached to the mail. Thank you!

> As per your response then setting crisp : false is not right solution for this problem
>
> This is the response we got for original ticket. Let us know the right solution for the problem.

1. I'm afraid there is no "right" solution to this, web dev is struggling with this issue since I remember. If you have any proposition how to handle sub-pixel rendering, let us know. Browsers developers (and me personally too) will be more than happy! Nice explanation of the issue can be found [here](https://johnresig.com/blog/sub-pixel-problems-in-css/).

In Highcharts, you can use one of the solutions:
- `crisp: false` -> render columns exactly as they are, and let browser handle rendering. As a side effect, that renders blurry columns. And results may vary between browsers, depending on implementation
- `crisp: true` -> let Highcharts round column widths' (and x-position) to the nearest full pixel width. That might leave some space between columns. But columns will better (clear, not blurry).


2. Regarding the second issue (DST):
> 1.  We don’t want variable width columns.
>
> As we are showing “day” worth of data, all columns should have sane width.
>              This is the fiddle http://jsfiddle.net/9fseLu84/

I am sorry, I am a bit confused here. If you don't want variable width column, then this is the expected result: http://jsfiddle.net/9fseLu84/ - all column have the same width (because every column has value of 24hours) and there is 1px gap between two columns where day lasted 25hours. Could elaborate what do you mean? Thanks!

**Comment by pawellysy** [comment]
Closing - Stale
