### ISSUE TITLE
Vuetify Dialog API  - Mouse hover incorrect response

### ISSUE THREAD

**Issue by 7arsandre** [highcharts/highcharts#14497]
#### Expected behaviour
When the mouse is located at coordinates [X,Y], the chart "thinks" that the mouse is located at [X, Y+N]. 
I've added a gif showing the issue:
![Screen-Recording-2020-11-05-at-2](https://user-images.githubusercontent.com/20848327/98293250-46f27f00-1fae-11eb-8197-5096d2cdb6f9.gif)

#### Actual behaviour
Expects the chart reflecting the exact position of the mouse.

#### Live demo with steps to reproduce
```
<template>
  <v-layout>
    <v-dialog v-model="visible">
      <div>
        <highcharts :options="analyticsChart"></highcharts>
      </div>
    </v-dialog>
  </v-layout>
</template>
```

#### Product version
```
"highcharts": "^8.1.2",
"highcharts-vue": "^1.3.5",
...
"vuetify": "^2.3.7",
```

#### Affected browser(s)
This issue is present both within Chrome and Firefox

**Comment by pawelfus** [comment]
Hi @7arsandre 

Thank you for reporting this issue. Could you recreate this in jsFiddle or stackblitz? We will check this. Thanks!

**Comment by 7arsandre** [comment]
Thanks for the fast response @pawelfus

v.8.2.2 checked out and didn't seem to make any difference.
I will recreate this issue in either jsFiddle or stackblitz and come back to you 😊

**Comment by pawelfus** [comment]
Thank you for checking v8.2.2! Waiting for the demo, this looks like a bug.

**Comment by KacperMadej** [comment]
Any updates @7arsandre ?
Without a live demo, the issue might be closed due to inactivity.

**Comment by sebastianbochan** [comment]
Closed due to inactivity.

**Comment by WaldemarEnns** [comment]
To this bug remains, I have the exact same issue. I am using:

* highcharts 8.2.2
* highcharts-vue 1.3.5
* vue 2.6.11
* vuetify 2.2.17

For me this bug appears in a vuetify dialog `VDialog` - so as soon as the dialog opens (and it includes the chart) the hover issue as described in the issue description, appears.

@7arsandre a quick reminder for you, to provide a reproduction link/demo.

**Comment by PaulDalek** [comment]
Hi @WaldemarEnns

Thank you for contacting us. Please, provide us with a live demo that recreates this behavior, otherwise it is going to be hard to indicate what is causing the issue. Thanks!

_Internal note_
It might be related to #2299.

**Comment by WaldemarEnns** [comment]
@PaulDalek I will try but at least on JSFiddle it's not possible to load `highcharts-vue` as a CDN because `highcharts-vue` only exists as a package to be installed by npm, yarn or other node package managers. What else would be a valid reproduction resource for you? A public repo maybe?

**Comment by PaulDalek** [comment]
@WaldemarEnns

You can use CodeSandbox or StackBlitz editor to create a minified example. Here is a simple demo: https://codesandbox.io/s/highcharts-vue-demo-ttner?file=/src/main.js which you can start with.

**Comment by WaldemarEnns** [comment]
> @WaldemarEnns
> 
> You can use CodeSandbox or StackBlitz editor to create a minified example. Here is a simple demo: https://codesandbox.io/s/highcharts-vue-demo-ttner?file=/src/main.js which you can start with.

Thanks a lot,  @PaulDalek . I was able to reproduce the bug, here is the codesandbox link:
https://codesandbox.io/s/begyk?file=/src/App.vue

Could you have a look and verify the bug?

**Comment by Denyllon** [comment]
Hello @WaldemarEnns 

We've verified the example you provided us with, and yes, we are able to reproduce described issue.
The problem comes from the Vuetify's `<v-dialog>` initial transition.

As the Highcharts `Chart.updateContainerScaling` method is triggered before the `<v-dialog>` animation ends, the chart's container scale is calculated for initial element dimensions (before transition).
Unfortunately, Vuetify does not have any kind of 'after animation callback', so that we would know the exact time after when the dialog's animation ends.
I think a sufficient workaround here can be a manual `Chart.updateContainerScaling` call after certain time, for example inside of the `chart.events.load` handler.

```js
  computed: {
    chartOptions() {
      return {
        chart: {
          type: "line",
          step: true,
          events: {
            load() {
              setTimeout(() => this.updateContainerScaling(), 500)
            }
          },
          title: {
            enabled: false,
          },
          backgroundColor: "white",
        },

// ...
```

Demo example: https://codesandbox.io/s/highcharts-vue-demo-forked-522w8
API Reference: https://api.highcharts.com/highcharts/chart.events.load

Kind regards!

**Comment by WaldemarEnns** [comment]
Oh yes, I assumed that it‘s caused by the dialog transition. Also looked for any kind of animation API on the v-dialog component but couldn‘t find one either. But I wasn‘t sure.

Thank you very much for the example, I guess I will use a timeout for now but will also request a new feature on the Vuetify repo ;)

Thank you guys a lot!
Kind regards,

Waldemar

**Comment by Denyllon** [comment]
Sure thing. I've seen a few already reported issues there (with workarounds and patches included), which should match your request.

**Comment by WaldemarEnns** [comment]
@7arsandre have a look if you have a similar problem and if you can fix it in the same way [as described](https://github.com/highcharts/highcharts/issues/14497#issuecomment-759605762).

**Comment by lexanth** [comment]
@Denyllon This is really handy. I've got the same issue in react with a blueprint dialog (https://blueprintjs.com/docs/#core/components/dialog) - fortunately it does have an `onOpened` callback so I can use that.

`updateContainerScaling` isn't mentioned in https://api.highcharts.com/class-reference/Highcharts.Chart#toc34 - is it safe to use as an API, or should we use `update` or `reflow` (or add it to the documentation and typescript typings)?

**Comment by lexanth** [comment]
Looks like `updateContainerScaling` has been removed in highcharts 9 by https://github.com/highcharts/highcharts/pull/14810 - `reflow` should do the trick instead.
