### ISSUE TITLE
Can drag navigator's drag-bar beyond the minimum x-axis range of stockchart

### ISSUE THREAD

**Issue by ktakahashimtb** [highcharts/highcharts#14505]
#### Expected behaviour

Navigator's handle stops when the resized range goes smaller than the minimum range.

#### Actual behaviour

Navigator's handle does not stop, and the chart zooms in beyond the limit.

#### Live demo with steps to reproduce

In the jsfiddle below, grab the one of the navigator dragbars and shrink the range.

https://jsfiddle.net/ktakahashimtb/qf5bumtg/

Normally, navigator won't allow the zoomed range to go beyond the minimum limit, but in this case it allows it to go beyond the limit.

This appears to happen only when the first series contains only a single data point.

Inside the highstock code, this looks to be due to `axis.minRange` being set to `NaN` in `Axis.prototype.adjustForMinRange` function.  The code figuring out `closestDataRange` should probably skip the series with a single data point.  I think this will be very clear once stepping though the code under this scenario.

![image](https://user-images.githubusercontent.com/50112353/98418675-70b0b200-2051-11eb-97fb-ff938c05a579.png)

I found that I can get around this problem by explicitly setting xAxis.minRange.

#### Product version
Highstock v.8.2.2

#### Affected browser(s)

Chrome, Firefox, Safari, Edge

**Comment by PaulDalek** [comment]
Hi @ktakahashimtb 

Thank you for reporting this issue. Yes, you are right. The `closestDataRange` results in `NaN` when there is only one point in a series. It only happens when such a series is first in line. The workaround would be to change the order of series, set the `minRange` explicitly or correct the code of the `adjustForMinRange` function.

**Demos**
https://jsfiddle.net/BlackLabel/vkabmfhw/ - setting the `minRange`
https://jsfiddle.net/BlackLabel/ne28bprg/ - modifying the `adjustForMinRange`
