### ISSUE TITLE
Ease extensibility of Navigator

### ISSUE THREAD

**Issue by panthony** [highcharts/highcharts#14512]
Hello there 👋 

This might be out of the scope of "feature" so if I'm in the wrong place feel free to close it. I merely wanted to give some feedback around navigator extensibility.

# Description of the feature

Provides a `drawElements` function (in the same spirit as `renderElements`) such as:

```js
 Navigator.prototype.drawElements = function (zoomedMin, zoomedMax, inverted, verb) {
            navigator.drawMasks(zoomedMin, zoomedMax, inverted, verb);
            navigator.drawOutline(zoomedMin, zoomedMax, inverted, verb);
            if (navigator.navigatorOptions.handles.enabled) {
                navigator.drawHandle(zoomedMin, 0, inverted, verb);
                navigator.drawHandle(zoomedMax, 1, inverted, verb);
            }
}
```

## Context

I had to extend the navigator by tweaking how some elements are rendered (ex: outline) or by **adding** a new elements in it.

Adding a new element is really easy:
 - override "renderElements"
 - call original function
 - add new elements

But drawing the added element is more difficult there is no function that I can easily overrides

I can either:
 - override `render` but in this case I'll keep drawing elements after `rendered=true` (& reposition of scrollbar etc.) 
 - duplicate `render` logic & inject mine at the appropriate place - but I might miss a fix or a tweak in render with future updates.

# Library related to the feature

Highcharts Stock

**Comment by pawelfus** [comment]
Hi @panthony 

Thank you for sharing the idea. Did you consider using [`chart.events.load`](https://api.highcharts.com/highcharts/chart.events.load) and [`chart.events.redraw`](https://api.highcharts.com/highcharts/chart.events.redraw) (or in general [`chart.events.render`](https://api.highcharts.com/highcharts/chart.events.render)) events from the chart? Instead of overwriting internal methods (that might change in future).

You don't have to use config per chart, but instead use `Highcharts.addEvent(Highcharts.Chart, 'redraw', redrawCallback);`, so every chart created later will execute your callback. Take a look: https://jsfiddle.net/BlackLabel/uat0gkc5/1/

**Comment by panthony** [comment]
Hi @pawelfus !

I was not aware of the events approach 👍 

I gave it a try with both `render` and `redraw`, unfortunately I encountered the following issues:

- Changing the x/y of an element (here "share" in navigator) does not appear to be working (or it gets reset behind me):

- Changing the navigator's outline path works on first draw but not on following updates

https://jsfiddle.net/4fvcm2t5/

The intended display is something like that:

![Capture d’écran 2020-11-09 à 16 46 43](https://user-images.githubusercontent.com/230462/98563215-32163400-22ab-11eb-9729-daf6f4637e9b.png)

**Comment by pawelfus** [comment]
Thank for the demo! My apologies, I missed the part where you mention tweaking elements and focused on **adding** them. 

In case of editing navigator elements, I agree with you, it would be better to extend one method, for example `drawElements`. Here, take my vote! :) 

PS: You see both issues because redrawing navigator is done without rendering whole chart.

**Comment by panthony** [comment]
@pawelfus No worries !

I actually talked about adding new element because my first implementation of the blue border was by adding a dedicated `<path>` element in `navigatorGroup`.

I later found out that I could achieve the same result visually simply playing with `stroke` on existing masks elements.
