### ISSUE TITLE
Heatmap.marker.lineWidth does not work

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#14525]
#### Expected behaviour
Config:
```js
series: [{
  marker: {
    lineWidth: 10
  },
  ...
}]
```
Should change heatmaps line width

#### Actual behaviour
Option is not set.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/oah3wu70/

#### Workaround
Use `series.borderWidth`, or set it to `null`: https://jsfiddle.net/BlackLabel/oah3wu70/1/

We can not use this workaround (or configure it in any way) in mobile wrappers (`borderWidth` is not available) - it seems to be a bug in doclets. `borderWidth` and `animation` seems to show parent's value in API, instead of using in-file defined ones. Animation should be disabled (`animation=false`): https://api.highcharts.com/highcharts/series.heatmap.animation

FYI @Denyllon

**Comment by Denyllon** [comment]
Well, it looks like the bug in the demo, because there is the `borderWidth` property set within `heatmap` config, which actually overwrites the `lineWidth: 10` statement. It's fully intentional, because the `borderWidth` is used to keep backward compatibility for the old heatmap configurations. If we remove it, then all works correctly: https://jsfiddle.net/BlackLabel/htjab2L6/
