### ISSUE TITLE
In the print chart option, respect the exporting options (captions)

### ISSUE THREAD

**Issue by KurveLauren** [highcharts/highcharts#14559]
# Description of the feature

Currently, only the title and subtitle can get exported on the print chart, but not the caption. Would it be possible to also allow the caption to be included in the print chart option? The use case for us is the use of filters on graphs. When we add filters to the graph they are inputted into captions so when you export the graph you can see what filters are applied to the graph, but the print chart doesn't respect those captions. Unlike when you export as a PNG, SVG, etc, it allows you to have the captions on the export.

# Library related to the feature

Highcharts

# Proof of Concept/Live example for the feature

Two images attached: The PDF (Print Chart Behaviour) is the current functionality, it exports the title and subtitle but not the caption. The PNG (Export as PNG Behaviour) contains the title, subtitle, and the caption. The ask would be to enable to the Print Chart Behaviour to be the same and allow to include the caption so you cannot see them.

[Print Chart Behaviour.pdf](https://github.com/highcharts/highcharts/files/5531663/Print.Chart.Behaviour.pdf)
![Export as PNG Behaviour](https://user-images.githubusercontent.com/74253218/98962379-9405b200-24d4-11eb-996f-29263bfebdab.png)

----

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by PaulDalek** [comment]
Hi @KurveLauren

Thank you for contacting us. Could you please provide a live example where this behavior occurs? From what I have checked, the [`caption`](https://api.highcharts.com/highcharts/caption) is visible on both, Print and PDF.

**Demo**
https://jsfiddle.net/BlackLabel/e0thL4s2/

**Comment by KurveLauren** [comment]
Thank you for the speedy response! 
The issue appears when a caption is added through exporting.chartOptions. Here is an example of the behaviour: https://jsfiddle.net/rwq13fkj/2/

**Comment by PaulDalek** [comment]
@KurveLauren

The `exporting.chartOptions` applies only when the chart is actually exported, so on print they won’t take effect. To display `caption` only on print you can use the [`matchMedia`](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia) to apply a listener that changes the visibility of `caption`. You could also use the Highcharts’ [`beforePrint`](https://api.highcharts.com/highcharts/chart.events.beforePrint) and [`afterPrint`](https://api.highcharts.com/highcharts/chart.events.afterPrint) events but in the example the `matchMedia` is used in order to prevent from timeouts that are set in the `chart.print` function.

**Demo**
https://jsfiddle.net/BlackLabel/kfbrjzy4/
