### ISSUE TITLE
tickInterval on x-axis does not get respected after initial render

### ISSUE THREAD

**Issue by StevenSerrien** [highcharts/highcharts#14597]
#### Expected behaviour
tickInterval should not change after updating the chart via `chart.update({}, true)` or resizing the browser by a pixel.

#### Actual behaviour
When setting the tickInterval to `Monthly`, the x-axis will skip months in order to have enough breathing room between each label on the x-axis. However, when calling `chart.update({}, true)` or resizing the browser just 1px, it suddenly adds the previously skipped months, resulting in a very dense x-axis.

I think this is a bug, since a simple update or resize, should not readd the ticks that it previously skipped due to own logic.

#### Live demo with steps to reproduce
https://jsfiddle.net/StevenSerrien/qp4agz2b/19/show

#### Product version
Tested on 7.1.2 and the latest available version.

#### Affected browser(s)
Tested on Chrome, but apparent on all.

**Comment by pawelfus** [comment]
Hi @StevenSerrien 

Thank you for reporting this issue!

**Simplified demos:**
- For maxOS: https://jsfiddle.net/BlackLabel/ozjy7bw6/4/
- For other systems: https://jsfiddle.net/BlackLabel/ozjy7bw6/2/

**Issue details:**
This is caused by default fontSize (12px) that is being picked up on chart init. At that point, we don't have DOM elements so we don't know what is set in CSS. In that case we assume 12px is the default font-size. On the next redraw (browser resize, `chart.update()` etc) correct font-size is used to check for overlapping labels.

Depending on OS, the issue may not be visible (thus two simplified demos above):
- Chrome 87.0.4280.66, Windows 8.1 (x64) - works fine
- Chrome 87.0.4280.66, macOS 10.15.7 - broken

**Workarounds:**

In theory, we can workaround issue by setting `font-size: 12px`, but it's not a good idea to force layout change in chart because of this bug, demo: https://jsfiddle.net/BlackLabel/ozjy7bw6/3/

Alternatively we can update chart right after rendering, but animation will be missing: https://jsfiddle.net/BlackLabel/ozjy7bw6/5/

Or mark xAxis as "dirty", so `chart.redraw()` will redraw this axis: https://jsfiddle.net/BlackLabel/ozjy7bw6/6/ (not using official API).

**Comment by StevenSerrien** [comment]
@pawelfus - Thank you very much for replying so extensively with very helpful demo's!
I'll take a look and check what option that you provided we can use! 😇

**Comment by pawelfus** [comment]
Thanks, it seems I did not save the demo, fixed the demo above 👍

**Comment by StevenSerrien** [comment]
> Thanks, it seems I did not save the demo, fixed the demo above 👍

Looks good! Thanks for the update, everything clear now.
Is this a bug that can be fixed or should we use the workarounds you provided since it is not feasible to fix anyway - since you don't know the font-size beforehand. 

If not, we can close this issue 👍

**Comment by pawelfus** [comment]
In general, initial rendering might be different from every subsequent rendering. You can find my (quite long, sorry!) explanation here: https://github.com/highcharts/highcharts/issues/13451#issuecomment-625734460

In your case, it's a bug. In theory we could just render a label, before reading the font-size. However every node (related to label) must be already in place (just in case someone set CSS selector that requires this structure) - and that might not be the case, we need to check this first. In your case, we can somehow workaround the issue, or one may accept that difference between initial rendering and after a redraw - chart still looks ok, it's not completely broken/unreadable.

For now I would say let's keep it open 👍 

PS: When working with fonts, there's another issue that might not be fixable: using asynchronously loaded fonts. See related issue: #8508 - in short, you render a chart before fonts are loaded and browser applies fonts after chart creation. The same may happen if browser finishes loading CSS after chart was created.
