### ISSUE TITLE
Offline PDF export fails when a plot line is outside the axis boundaries

### ISSUE THREAD

**Issue by dk1m** [highcharts/highcharts#14595]
#### Expected behaviour
Exporting a PDF offline (without the Highcharts export server) should work when using a plot line that is outside the axis boundaries.

#### Actual behaviour
Nothing happens. An error can be found in the console.

#### Live demo with steps to reproduce
https://jsfiddle.net/0zt8743q/

Repro steps:
1. Load fiddle
2. Click the export button
3. Click "Download PDF document"
4. Notice that nothing happens. (error in console)
5. If you change the value of the plot line to `1602979200000` (which is inside the x-axis boundaries), the export will work.

#### Product version
Highcharts 8.2.2. It works in 6.1.4.

#### Affected browser(s)
Firefox 82.0.2, Chrome 86.0.4240.198, Safari 13.0.4

The offline export of PNG, JPEG, and SVG work fine. It's just the PDF that doesn't work.

**Comment by pawelfus** [comment]
Thank you for reporting this issue @dk1m 

Standalone, Highcharts unrelated issue: https://jsfiddle.net/BlackLabel/suydzvjb/

**Workaround:**
Do not render empty paths, demo: https://jsfiddle.net/BlackLabel/8gk7Ldjs/

Plugin:
```js
(function(H) {
  H.wrap(
    H.Axis.prototype,
    'getPlotLinePath',
    function(proceed) {
      var path = proceed.apply(this, Array.prototype.slice.call(arguments, 1));

      if (path === null) {
        path = [
          ['M', 0, 0]
        ];
      }
      return path;
    }
  )
})(Highcharts);
```

Potential side effects:
- some paths animation might be strange (not tested)

*Internal note:*
Bisected to commit c6cfe0e000 - but at that time we did not render plotLines outside the extremes. Since those are rendered as empty paths, it seems svg2pdf.js has some kind of a bug. 

svg2pdf v2.0.0+, looks fine: https://jsfiddle.net/BlackLabel/w4m80upf/ - however API has changed quite a lot, diving into async: https://jsfiddle.net/BlackLabel/na4zdeu8/3/

**Comment by dk1m** [comment]
Thanks for the quick response, @pawelfus! Any ideas on when this might be fixed? Our company has an active Advantage membership, if that matters. If you're confident in the workaround, I'll use that for now so that we can upgrade to 8.2.2. If not, I'll just hold off for a proper fix.

**Comment by pawelfus** [comment]
Updated the workaround above (see plugin code above - changes are done only for the exported chart, where animation is turned off), eliminating side-effects: https://jsfiddle.net/BlackLabel/8gk7Ldjs/2/

My workaround is one of the possible solutions to be implemented in the core. It might get into the core like #7090 

Another workaround, inspired by #7090: https://jsfiddle.net/BlackLabel/8gk7Ldjs/4/ (removes empty paths). Personally, I think this one is better, because it does not focus on `plotLines` only, but on all paths that may generate the issue.
```js
(function(H) {
  H.wrap(H.Chart.prototype, 'getChartHTML', function(proceed) {
    proceed.call(this);
    this.container.querySelectorAll('path').forEach(function(node) {
      const path = node.getAttribute('d');

      if (
        path === void 0 ||
        path === null
      ) {
        node.remove();
      }
    });
    return this.container.innerHTML;
  });
})(Highcharts);
```

We will discuss this issue on our next meeting, so we will be able to provide ETA.

**Comment by pawelfus** [comment]
*Internal note:*
First, let's check compatibility with older browsers if we can upgrade svg2pdf to v2.0.0. If not (because of TS or async/awaits), then focus on working around the issue in the module (by removing "empty" paths).
