### ISSUE TITLE
Legend Item Colors in Solid Gauge

### ISSUE THREAD

**Issue by MiroLiska** [highcharts/highcharts#14612]
#### Expected behaviour
The legend used for solid gauge chart should have properly colored items.

#### Actual behaviour
The legend used for solid gauge chart have all items gray. Solid gauge like apple watch definitively needs the legend with colors - when printed or exported into PDF, we have no idea anymore which color means what, mouse hovering will not help me.

#### Live demo with steps to reproduce
https://jsfiddle.net/wax4zhop/

#### Product version
Highcharts 8.0.4

**Comment by PaulDalek** [comment]
Hi @MiroLiska

Thank you for reporting this issue. This topic was raised before (take a look here: #10232). In short, setting the `colorByPoint` wil resolve this.

**Demo**
https://jsfiddle.net/BlackLabel/Lteh718n/

**Comment by MiroLiska** [comment]
Thank you

This looks much better than the solution I have received from your support:

https://jsfiddle.net/BlackLabel/hqamb9yp/

Best regards

Miro

**Comment by MiroLiska** [comment]
Hi

I am a bit confused that the workaround is considered to be a final solution on your side (closed as 'not a bug'). Why is the default value for colorByPoint set to false in solid gauge? Why do I need to set for series the color again? For me is the proper solution that the legend simply works for solid gauge without any workarounds. In my opinion, the default behavior (gray legend) is of no use to anyone.

**Comment by pawelfus** [comment]
Hi @MiroLiska 

Let me answer, one by one:

> I am a bit confused that the workaround is considered to be a final solution on your side

This is not a workaround. This is expected behaviour, you can configure to fit your needs.

> (closed as 'not a bug')

You are right, this should be labeled with the `duplicate` flag. Let me change that.

> Why is the default value for colorByPoint set to false in solid gauge?

Default value is set to `true`. I don't know why, the decision was made 6-7 years ago. I guess readability is the reason: https://jsfiddle.net/BlackLabel/zsahevo3/1/

> Why do I need to set for series the color again?

Because you want different legend items per point, I guess. If not, then you can get just one legend item: https://jsfiddle.net/BlackLabel/Lteh718n/1/ 

> For me is the proper solution that the legend simply works for solid gauge without any workarounds. In my opinion, the default behavior (gray legend) is of no use to anyone.

Thank you for you opinion. This grey legend item is shared across all series types with `colorByPoint` option supported. What other color you would prefer to see, when rendering for example 1000columns, each different color? Or two solid-gauge points, each with radial gradient fill? We are open for suggestions.

Note that the default value for solid-gauge's `colorByPoint` is unlikely to change, because that would produce regression errors in many existing charts. We don't want to break anyone's chart on purpose.. But you can create new issue (`Feature request`) suggesting that change. If your idea will become popular, we will consider changing this.

**Comment by pawelfus** [comment]
Just an additional word of explanation: you don't have to set color per point and per series, simply use [`colors`](https://api.highcharts.com/highcharts/colors) option: https://jsfiddle.net/BlackLabel/4rsug80y/2/

**Comment by MiroLiska** [comment]
Hi

I am talking about solid gauge, there are no columns there, I think. Changing the default value would be only in solid-gauge.src.js, for var solidGaugeOptions. It would surely cause regression for all solid gauge instances, that's true. However, I still believe that if anyone needs a grey legend, it is a special situation and not vice versa.
Maybe 'colorByPoint' is a wrong option to play with, maybe the legendItem colorizing should by patched for solid-gauges based on a different condition. Or do you consider gray legend good as default? Or maybe I am missing something :(

**Comment by pawelfus** [comment]
>  Or do you consider gray legend good as default?

If series contains multiple points, each with a different color, then gray color is as good as any other.

Based on that, we could check number of points in a series, and if there is only one point, use that point's color in legend. But this still could cause regressions, adding/removing points to/from series would change legend's color that one may consider buggy. For new users that would be unexpected behaviour, even if we explain this in API options. I'm not saying that current behaviour is as is, and can't be improved.

Alternatively, we could change default value for `colorByPoint` in the major release, that will reduce number of broken charts, I hope..

**Comment by MiroLiska** [comment]
**Solid gauge** series with multiple points seems to be a special situation to me. In your demos, you have two solid-gauge charts, both of them using single data point per series, so I have considered it rather 'standard'. That's where I am probably wrong. Obviously, most of solid gauges are using multiple points, I did not know this.
