### ISSUE TITLE
Vertically-resizing operations require a second redraw to stabilize

### ISSUE THREAD

**Issue by javolio** [highcharts/highcharts#14625]
#### Expected behaviour
Changing the size of the chart (e.g. by changing showInLegend or by floating it) should not take multiple redraw events to stabilize the chart.

To put it another way, asking a chart to redraw without changing the configuration should not change the rendered result (zoom/pan/etc. interaction notwithstanding).

#### Actual behaviour

In some cases, such as updating a series' showInLegend such that the legend changes height, or setting the legend to floating or not, the chart will visually update but then update again when asked to redraw or when performing the same update a second time. The chart is changing representation without a change of configuration.

I've only observed this happening when there are multiple co-aligned y-axes, with startOnTick and endOnTick.

Changing the chart's height itself (chart.height) does not seem to cause this issue.

#### Live demo with steps to reproduce
Demo: https://jsfiddle.net/nafo9d1b/4/

Use the buttons below the chart to interact. Most interactions will require two activations to stabilize--pressing the button once will change the chart, and pressing it again or pressing Redraw will change it again, but further presses will elicit no response.

#### Product version
Highcharts JS v8.2.2

#### Affected browser(s)
• Chrome
• Safari
• In Firefox, the Legend Floating change produces the bug, but changing the legend height via showInLegend does not
• No others were tested

**Comment by pawelfus** [comment]
Thank you for reporting this bug @javolio 

**Workaround:**
Call `chart.redraw()` right after updating legend: https://jsfiddle.net/BlackLabel/xeksmLj8/

*Internal note:*
This is caused by these lines:

https://github.com/highcharts/highcharts/blob/1fb4389ed90df0c5fd3500b1c7821f1fe0b72e9f/ts/Core/Chart/Chart.ts#L742-L750

Where first extremes (scale) are calculated, then margins (to make space e.g. for legend). That means yAxis uses wrong `len`/`height` (old) to calculate extremes. We can't simply change order of this: to correctly calculate margins we need to know how much space is needed for axes' labels.
