### ISSUE TITLE
Feature request: not hide plotlines when axis' series is hidden

### ISSUE THREAD

**Issue by thyagorafaell** [highcharts/highcharts#14634]
# Description of the feature
Hi,

I have a chart that has only one axis and one series, and in that axis, I have two plotLines.
The problem is: when I hide my series, automatically the axis is also hidden, so the plotLines related to axis are hidden too.

After contact the support team, I was informed that it is the expected behavior and was given an [workaround](https://jsfiddle.net/BlackLabel/kjm2Lwxr/).
It worked well on my charts, but didn't fit on my co-worker's charts, anyway, he found an alternative solution.

However, we would appreciate if Highcharts had a feature in to avoid the axis and plotlines being hidden when the lone series is not visible.

# Library related to the feature
Highcharts

# Proof of Concept/Live example for the feature

### Currently behavior:
![plotlines-currently-behavior](https://user-images.githubusercontent.com/3964505/99966996-fa60bf00-2d75-11eb-8d2e-1babb92636f8.gif)

### Requested behavior:
![plotlines-requested-behavior](https://user-images.githubusercontent.com/3964505/99967060-12384300-2d76-11eb-80fc-f6e0b8d9f8a4.gif)

**Comment by pawelfus** [comment]
Hi @thyagorafaell 

Thank you for sharing the idea! This happens because yAxis, when hiding "Series 1", does not have any extremes. To avoid that, simply set [`yAxis.min`](https://api.highcharts.com/highcharts/yAxis.min) and [`yAxis.max`](https://api.highcharts.com/highcharts/yAxis.max): https://jsfiddle.net/BlackLabel/kjm2Lwxr/1/

If you can't change `min` and `max`, you can change this behaviour using [`chart.ignoreHiddenSeries`](https://api.highcharts.com/highcharts/chart.ignoreHiddenSeries) option: https://jsfiddle.net/BlackLabel/kjm2Lwxr/3/

Alternatively, use [`yAxis.tickPositioner`](https://api.highcharts.com/highcharts/yAxis.tickPositioner) to handle this case: https://jsfiddle.net/BlackLabel/kjm2Lwxr/2/
