### ISSUE TITLE
Treemap : Color axis ticks dont work properly when only min and tickInterval is set

### ISSUE THREAD

**Issue by amruta30** [highcharts/highcharts#14644]
#### Expected behaviour
Color axis should show appropriate ticks and tick labels for all cases when min, max, tickInterval are defined.
Please let us know if any other option also needs to be set in such case.

#### Actual behaviour
For treemap, when we define color axis with options of min and tickInterval, only the 1st and last tick labels are seen for color axis. While it is observed that correct ticks and tick labels are seen when tickinterval is not defined or when all min, max, tickInterval are defined. 

#### Live demo with steps to reproduce
Color axis with tickInterval and min defined: https://jsfiddle.net/amrutaJgtp/wLz8mtfs/
Color axis without tickInterval defined: https://jsfiddle.net/amrutaJgtp/wLz8mtfs/1/
Color axis with tickInterval, min and max defined: https://jsfiddle.net/amrutaJgtp/wLz8mtfs/2/

#### Product version
v8.1.2

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @amruta30 

Thank you for reporting this issue. This is caused by trying to render too dense ticks on the colorAxis. In your first demo, you set `tickInterval`=10 000, while max=20 000 000+. That means, you try to render 2 000 ticks on a ~200px colorAxis. That gives more than 10 ticks per pixel. In this case, instead of freezing the browser, we render first and last tick only.

In your case, simply increase `tickInterval`, for example 5 000 000 looks good: https://jsfiddle.net/BlackLabel/rLu7o5b3/1/

Your third demo "works fine" because you render only 0 - 60 000 range, leaving the rest of 20 000 000 scale out. I said it "works fine", because the colors are wrong: all values are off the scale, so every point has the same color, max color.
