### ISSUE TITLE
StockChart-Line is broken with initial Data

### ISSUE THREAD

**Issue by nickwinger** [highcharts/highcharts#14683]
#### Expected behaviour
StockChart-Line should draw a smooth line from the beginning

#### Actual behaviour
On start, the StockChart-Line is broken, after a while it corrects itself, but also gets broken again

#### Live demo with steps to reproduce
https://stackblitz.com/edit/ionic-v4-angular-tabs-9lww7n?file=src/app/chart/chart.component.ts

#### Product version

latest (8.2.2)

#### Affected browser(s)
Chrome Windows (maybe also other Browsers)

**Comment by nickwinger** [comment]
seems like it has something to do with the order of the timestamp in the data ?!?

**Comment by pawelfus** [comment]
Hi @nickwinger 

This is caused by [`gapSize`](https://api.highcharts.com/highstock/series.line.gapSize) and [`gapUnit`](https://api.highcharts.com/highstock/series.line.gapUnit) options. You have set `gapSize=4` in your config. Two closest points are 154ms apart, which means if distance between two points is 616+ ms then these points won't be connected. And this is the case for the most of your dataset.

It "corrects" itself after a while because `dataGrouping` turns on, and group points into 1s groups. Then `gapSize` is 4seconds, which is fine for your dataset.

**Comment by nickwinger** [comment]
ok, but i still don't fully understand and how to solve this.
if you look at this modified version:
https://stackblitz.com/edit/ionic-v4-angular-tabs-uysps4?file=src/app/tab1/tab1.page.ts

it just does sorting the series data (by the timestamp) and then it immediately works.
although the gapSize is the same as before.
So what's the point here ?
Isn't the data sorted internally ? if not, how can i enable dataGrouping right from the start ?
I think this cannot be the wanted behaviour that a chart first looks broken and then "it fixes itself".
why it kicks in and isn't there from the beginning ?

**Comment by pawelfus** [comment]
> ok, but i still don't fully understand and how to solve this.

Don't worry! I will try to explain this in details, see below:

> it just does sorting the series data (by the timestamp) and then it immediately works.
> although the gapSize is the same as before.
> So what's the point here ?
> Isn't the data sorted internally ?

Your second demo throws warning about unsorted data: [error 15](https://www.highcharts.com/errors/15/). We do not sort data internally, data should be sorted ascending by x-values (not descending as if your second demo). It does not work correctly: `gapSize` is ignored and all points are connected.

> how can i enable dataGrouping right from the start ?

`dataGrouping` is enabled by default in Highcharts Stock, but it is applied only when the conditions are met (see: [docs](https://www.highcharts.com/docs/stock/data-grouping)). You can still force dataGrouping: https://api.highcharts.com/highstock/series.line.dataGrouping.forced

> I think this cannot be the wanted behaviour that a chart first looks broken and then "it fixes itself".

With the given config and the dataset, on init, the chart is not broken. The same will happen if your dataset will be monthly (e.g. 12points), but you will decide to add two points in the middle, with a 1h distance between them. All points, except the two extra ones, will be disconnected because of the `gapSize` option. Then if you add 1000 points, `groupPixelWidth` threshold will be crossed, and `dataGrouping` will kick in. These two extra points will be grouped into 1month (or 3months etc) and `gapSize` again will be checked. All points will be nicely connected (unless you will be missing some points between them).

> why it kicks in and isn't there from the beginning ?

Because conditions are not met. After a while, you added enough points to apply dataGrouping on the series.

Let us know if anything is not clear!

**Comment by nickwinger** [comment]
ok, thanks, so i close this one.
