### ISSUE TITLE
Heatmap colors conflict with marker fill in styled mode

### ISSUE THREAD

**Issue by murthyvitara** [highcharts/highcharts#14690]
#### Expected behaviour
Colors specified in the colors-axes are used in version 6.2.0.
https://jsfiddle.net/krvd79ut/1/

#### Actual behaviour
Color-axes colors are only reflected in legend, heatmap colors are overriden by marker fill property,

#### Live demo with steps to reproduce
https://jsfiddle.net/Lt2a3fuh/10/

#### Product version
Highcharts 8.1.2

**Comment by PaulDalek** [comment]
Hi @murthyvitara

Thank you for reporting this issue. In fact, colors in the first demo are taken from the CSS stylesheet and not from the `colors` array because you use the styled version scripts. As a workaround, you could set an adequate color per a specific color's class in CSS in order to achieve the expected effect. As for the issue it seems it's a regression.

**Simplified demos**
https://jsfiddle.net/BlackLabel/mvhtgx4k/ - v6.2.0
https://jsfiddle.net/BlackLabel/ak4cm0g3/ - v8.2.2

_Internal note_
Bisected to commit: https://github.com/highcharts/highcharts/commit/3bf74f3f96d3db0c81249fc338ef6e1397d436a1
