### ISSUE TITLE
Updating each datapoint color dynamically

### ISSUE THREAD

**Issue by SoftDevDanial** [highcharts/highcharts#14704]
So in my program i want to change each color point and the line. For the line , i use the series.color and each point i use data.color which is working fine when initially setting it. However, when updating the color for each point, im not sure if the chart is redrawing it every time i update the color point by using series[0].options.data[i].color = someColor . Using this, i achieve what i want but somehow the chart becomes slow which im not fully sure if its because of this line of code but i highly suspect because this line of code redraws the chart for every data. Looked online and they say to use series.data.update() but it doesnt change all the point colors but only change the color that is presented currently on the graph. So if i have 200 points but on the graph presented only has 20, the series.data only has 20 points. So how do i change each points color and not let it redraw() because that is what im suspecting. My data isnt that a lot comparted to other people where they have millions and thousands. The data i tested probably had <100 * 3yaxis so probably around 300 data. Max estimated data i tested is around 800 where i add more axis. 

#### Live demo with steps to reproduce
https://jsfiddle.net/56ymLc2f/28/
A simple fiddle too hopefully let you guys to have a picture on the problem
Apparently, the column doesnt update in this fiddle which im not sure why thats happening but in my end updating the column using the code in the fiddle does change the column color

#### Product version

 Highstock JS v8.2.2 

** Recap in case no one understands, i tried updating each _point color_  by setting the value directly using the "=" and it works but somehow have a performance impact which im not fully sure its because of this code but highly suspect it is. So any solutions to setting each point color for any series type since i want to standardize it in my code if possible**

**Comment by pawelfus** [comment]
Hi @SoftDevDanial 

Thanks for choosing Highcharts!

To update **one point**, use `point.update()` as you found the answer online. To update **all points at once** I suggest to use [`series.setData()`](https://api.highcharts.com/class-reference/Highcharts.Series#setData).

Alternatively, you can keep using `point.update()`, but you need to increase [`series.cropThreshold`](https://api.highcharts.com/highcharts/series.line.cropThreshold) then. 

PS: We use GitHub issues as feature requests/bug reports. For questions, please use other [support channels](https://www.highcharts.com/blog/support/). Thanks! :)

**Comment by SoftDevDanial** [comment]
> To update one point, use point.update() as you found the answer online. To update all points at once I suggest to use series.setData().

If i use point, only the points present on the chart will be updated. Lets say i have 500 points but only 20 are shown , the point object only has those 20 points only when i want to change all 500 of the points color.  If i use series.setData , then i would not be able to update each points color because there are some points that will have different color.

> PS: We use GitHub issues as feature requests/bug reports. For questions, please use other support channels. Thanks! :)

I was planning to email the highcharts team or ask in forum but after some thought and testing, i thought that it was considered a bug or a feature to be implemented where i can update each data (  500 data but 20 are shown . Update each 500 data) settings such as color or x or y etc. But if it turns out not to be a bug or a feature request then i do apologize

Thanks for the quick reply btw !

**Comment by SoftDevDanial** [comment]
@pawelfus 
To make it more clear, im creating a stock indicator which has 2 line series and 1 column series, which has both positive and negative color(indicator name  is MACD). Yes, you have it in your indicator module but that is with your own calculations etc where in my case i have an api that supplies those data and i just plot it in the highstock graph. So some indicators like this MACD one has a column where theres positive and negative color column. So what i did was to set each data color(not the series one but each datapoint color) so the ones that are positive will get green color and negative will get red color. Doing so achieves my desired result but somehow i feel a performance impact which im not fully sure if its because of the color settings since it happens when i update the color(probably because it redraws everytime i change each datapoint color). How i did it is by implicitly set the color to the new color(chart.series[0].options.data[i].color = newColor). You can refer to the fiddle because its a simplified version of it. I also added the comments on what i did in case other stuff affected it

**Comment by pawelfus** [comment]
Hi @SoftDevDanial 

> If i use point, only the points present on the chart will be updated. Lets say i have 500 points but only 20 are shown , the point object only has those 20 points only when i want to change all 500 of the points color.

I know, that's why I said above that you can increase `series.cropThreshold` value if you want to keep using `point.update()`.

> If i use series.setData , then i would not be able to update each points color because there are some points that will have different color.

This is not true. The same data format is supported by `setData()` as the one used in initial config, for example:
```js
series.setData([
  { x: 100, y: 200, color: '#dedede' },
  { x: 200, y: 400, color: 'rgb(200, 100, 100)' },
  { x: 300, y: 100, color: 'rgba(100, 200, 100, 0.1)' },
  ...
]
```
Of course, when dealing with point options as object, pleas keep in mind [`turboThreshold`](https://api.highcharts.com/highcharts/series.line.turboThreshold) option (you may want to increase/disable it).

Regarding MACD implementation: Did you consider simply using [`negativeColor`](https://api.highcharts.com/highcharts/series.line.negativeColor)? It does exactly what you need and you don't need to manage which point should have which color.

**Comment by SoftDevDanial** [comment]
> I know, that's why I said above that you can increase series.cropThreshold value if you want to keep using point.update().
I see. Yep after reading the api over and over , i finally understood it. Somehow i thought of something else when read about it

> This is not true. The same data format is supported by setData() as the one used in initial config, for example:
But to use setData() and change all the data, wouldn't i need to set the series.cropThreshold first? What i mean by my sentence was i thought i couldnt change all the data at first with setData() since i didnt know about cropThreshold.  

> Regarding MACD implementation: Did you consider simply using negativeColor? It does exactly what you need and you don't need to manage which point should have which color.
wait a minute, somehow i missed this part in the api although i opened the column api quite a lot of times already. After reading this, opened it up and on the first try i saw it.😳 This is really helpful

Thanks a lot! Apologies for not using other support channels because i thought this was a bug or a feature request.

Btw, when i implicitly set each color in the highstock object ( series[0].data[i].color = colorChange) , does it redraw the chart everytime? Because there was a noticable performance impact on my end which i think its because of my implicitly setting it. If there's not any redraw after setting it, then it's probably because of me looping over each data and series and setting each one of it. Probably should consider using negativeColor instead of setData and changing the cropThreshold.

**Comment by pawelfus** [comment]
Don't worry! 

This: `series[0].data[i].color = colorChange` may, or may not work. It's not something you should change in the first place :) `series.data` is a read only array (see: https://api.highcharts.com/class-reference/Highcharts.Series#data). We don't redraw chart if you change anything inside this array. Perhaps you use some wrapper that does it for you, it's hard to say.

Just to sum up:

- use `negativeColor` if you can. `negativeColor` also works with [`dataGrouping`](https://api.highcharts.com/highstock/series.column.dataGrouping)
- use `point.update()`, when you want to update only certain points with new color (`point.color` has higher priority than `negativeColor`). That is faster than using `setData()` that updates all points. Don't forget to use `chart.redraw()` after all update operations, see details here: [`chart.redraw()`](https://api.highcharts.com/class-reference/Highcharts.Chart#redraw). If your dataset is big enough, consider increasing `cropThreshold`, but that might decrease the performance.
- if setting `cropThreshold` is not acceptable (e.g. rendering 10 000 columns makes no sense if user can see, at the same time, only 20 of them), then use `setData()`. Don't forget increasing `turboThreshold` (not `cropThreshold`). You need to do this anyway, because you want to provide `color` option per point.

**Comment by SoftDevDanial** [comment]
Ohhh ok. Thanks @pawelfus. Big Help you have been!
