### ISSUE TITLE
categories not align issue for multi axis

### ISSUE THREAD

**Issue by lundi326** [highcharts/highcharts#14721]
#### Expected behaviour
Every boxplot align to categories center

#### Actual behaviour
All boxplot not align to center by default. It could align to center if add property ''centerInCategory: true,', but could only help for one plot, not all of them. Please refer to the post. 
https://www.highcharts.com/forum/viewtopic.php?f=9&t=45453&p=161858#p161858

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/cvnkb8rd/

#### Product version
8.2.0

#### Affected browser(s)
Chrome Windows

**Comment by PaulDalek** [comment]
Hi @lundi326

Thank you for contacting us and reporting this issue. To set each point in a center of a corresponding category use the [`grouping`](https://api.highcharts.com/highcharts/series.boxplot.grouping) property (set it to false) instead of the `centerInCategory`.

**Demo**
https://jsfiddle.net/BlackLabel/tz823gLc/
