### ISSUE TITLE
Pie - allowOverlap:true does not work

### ISSUE THREAD

**Issue by wchmiel** [highcharts/highcharts#14760]
#### Expected behavior
`allowOverlap` should work correctly or should not be listed as a pie series option: https://api.highcharts.com/highcharts/series.pie.dataLabels.allowOverlap

#### Actual behaviour
`allowOverlap` has no effect

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/ycj4avpn/

**Comment by TorsteinHonsi** [comment]
Pie series run their own anticollision logic, so `allowOverlap` wouldn't make a difference, because the labels don't overlap in the first place.

What we see is that the labels in the top left are removed from the algorithm in an early stage, because it prioritizes labels for the greatest slices. In the next run, when laying out the labels, it determines that the distance between labels and slices is too great, so it doesn't show them (values 33, 32, 31 etc in the demo).

To fix this particular case, we would need to not only sort labels by the value of the slices, but also allow some random labels for lower ranked slices.

**Comment by KacperMadej** [comment]
**Possible workaround**:
It's possible to get something close to the `allowOverlap: true` effect with a small wrapper. Overlapping detection of the labels is used in the pie's anticollision logic, hence a workaround: https://jsfiddle.net/BlackLabel/ycj4avpn/1/
Scaling size in getBBox results in more densely packed labels: https://jsfiddle.net/BlackLabel/ycj4avpn/2/
(Similar to API supported reduced [padding](https://api.highcharts.com/highcharts/series.pie.dataLabels.padding): https://jsfiddle.net/BlackLabel/ycj4avpn/3/)
