### ISSUE TITLE
StyledMode: Updating `colorIndex` does work only once

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#14773]
#### Expected behaviour
Color updated every time

#### Actual behaviour
Only the first update works, all other updates add a class name, but never remove the old one

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/pt3eock9/3/

#### Product version
v8.2.2

#### Affected browser(s)
All

Ticket from #14761 PR, what's missing:
- [ ] build TS, include JS
- [ ] run tests
- [ ] create test
- [x] https://github.com/highcharts/highcharts/pull/14761#issuecomment-740010724

**Comment by TorsteinHonsi** [comment]
The fix is quite simple - the PieSeries override should call `graphic.addClass` with the `replace` parameter, just like the parent (`LineSeries`) does. The `addClass` function works correctly.

https://github.com/highcharts/highcharts/blob/f9c3bd971ae6536e6d01b58b0619fdd6be8d4f12/ts/Series/Pie/PieSeries.ts/#L955

Should be 

`graphic.addClass(point.getClassName(), true);`
