### ISSUE TITLE
Stacked column chart looks odd when there are more than 50 series

### ISSUE THREAD

**Issue by geekboy0801** [highcharts/highcharts#14789]
I had to draw column chart where more than 1000 items are stacked. But looks like there's bug in highcharts.

![1](https://user-images.githubusercontent.com/40581883/101770323-46a45100-3b23-11eb-8ac9-350b09636c8c.JPG)

#### when there are 49 series (with boost enabled)
https://jsfiddle.net/rskn8wy2/4/

#### when there are 50 series (with boost enabled)
https://jsfiddle.net/rskn8wy2/3/

**Comment by PaulDalek** [comment]
Hi @geekboy0801 

Thank you for contacting us and reporting this issue. This is not a bug but a normal behavior. The reason behind it is the `seriesThreshold` property set to 50 by default. Then the boost feature kicks in. As for the one pixel columns, this is also an expected behavior ([more info](https://www.highcharts.com/docs/advanced-chart-features/boost-module#caveats)).

**Demo**
https://jsfiddle.net/BlackLabel/sm43tf1u/
