### ISSUE TITLE
Scatter3D chart - issue after changing title of Z axis

### ISSUE THREAD

**Issue by audriusstonkus** [highcharts/highcharts#14793]
#### Expected behaviour
Label on Z axis changes

#### Actual behaviour
Label disappears, axis gets distorted

#### Live demo with steps to reproduce
https://jsfiddle.net/stonaudr/ozr28pjc/

#### Product version
Highcharts 8.2.2

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Thank you for reporting this bug @audriusstonkus 

It seems to be a more general issue: using `zAxis.update()` is broken: https://jsfiddle.net/BlackLabel/L1pcqvr0/1/

*Internal note:*
Bisected to commit 7fe8513fcf
Could you take a look @bre1470 ?

**Comment by bre1470** [comment]
@Pawelfus I am unable to understand the issue or find a difference between both fiddles. Is it possible to make a screenshot, what happens or should not happen? Or give a guide what to do to reproduce the issue?

**Comment by KacperMadej** [comment]
@bre1470 

Here are demos with a matching update, but the issue is the same:
 - https://jsfiddle.net/BlackLabel/L1pcqvr0/2/
 - https://jsfiddle.net/BlackLabel/f1cjbg6u/

Steps:
1. click the button under the chart to fire update
2. compare both (both demos) charts' z axes

![3d-z-update](https://user-images.githubusercontent.com/8960408/102603269-d9944b00-4122-11eb-9a66-98c9981e8323.jpg)

**Comment by bre1470** [comment]
@KacperMadej Thank you!
