### ISSUE TITLE
Chart yAxis's gridLine cover the chart's plotBorder when chart is updated

### ISSUE THREAD

**Issue by yulai841415** [highcharts/highcharts#14798]
#### Expected behaviour

plotBorder show normally
#### Actual behaviour
plotBorder top not show

#### Live demo with steps to reproduce
Demo: https://jshare.com.cn/public/S0Gzub

#### Product version
version 7.2.0

#### Affected browser(s)
Chrome

**Comment by PaulDalek** [comment]
Hi @yulai841415 

Thank you for contacting us and reporting this issue. The `yAxis` gridlines are displayed above because they have the same `zIndex` (see the `zIndexSetter` funciton) as the plot border. As as workaround you can overwrite the `drawChartBox` to increase the default `zIndex` of the plot border.

**Workaround**
https://jsfiddle.net/BlackLabel/n2dxbmqk/
