### ISSUE TITLE
Invalid handling of legend proximate with many series

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#14809]
#### Expected behaviour
legend proximate should handle the situation where there are more legend items then can be displayed gracefully

#### Actual behaviour
Some legend items get rendered on top of each other and a pager is displayed that doesn't work

#### Live demo with steps to reproduce
Fiddle: http://jsfiddle.net/kzoon/L10xropy/

#### Product version
Latest

#### Affected browser(s)
All

I am aware that using proximate layout in this situation doesn't make much sense. However, I can't control the number of series that my users select. If he selects more series than the layout can display, the situation should be handled gracefully.

Is suggest not rendering more legend items than actually fit, or making the pager work in this circumstance.

**Comment by PaulDalek** [comment]
Hi @kzoon 

Thank you for contacting us and reporting this issue. Could you provide us with a simplified example where such a situation occurs? Thanks.

**Comment by kzoon** [comment]
Sorry, I used the wrong URL. Reproduce: http://jsfiddle.net/kzoon/L10xropy/

**Comment by PaulDalek** [comment]
@kzoon

Thank you for the demo. The position of some legend items are incorrectly positioned because the y position is set to `NaN`.

**Simplified demo**
http://jsfiddle.net/BlackLabel/6dz31xc0/

_Internal note_
After the call of the `distribute` function inside the `proximatePositions`, some boxes don’t have the `pos` property, therefore the second value (the y position of the item) of the `_legendItemPos` array is later calculated to `NaN`.
