### ISSUE TITLE
Customization of tooltip inside angular not possible

### ISSUE THREAD

**Issue by mfechner** [highcharts/highcharts#14827]
#### Expected behaviour
The array `this.points` should have an element for each line (series) of the graph so you can create a tooltip that have all values including some additional calculations.

#### Actual behaviour
The array (in formatter, this.points) consists in an Angular app only of one element, the second or more series is not present.

#### Live demo with steps to reproduce
This was also discussed in detail here:
https://www.highcharts.com/forum/viewtopic.php?p=162424&sid=8f2a5f3616b2de043c7bbcd593b4f57c#p162424

A stackblitz example is here, after it is loaded, you must comment line 105 in file app.components.ts (`//mTZ();`).
https://stackblitz.com/edit/highcharts-angular-basic-line-qcsk52

You can find it also as github repo:
https://github.com/mfechner/highcharts-angular-custom-tooltip

To see it, just open the console in Stackblitz and hover the mouse over the dots in the graph.
As two series are added to the graph, I would expect 0 and 1 displayed in the console for each point you touch with the mouse courser.

#### Product version
```
    "highcharts": "8.2.2",
    "highcharts-angular": "2.8.2",
```

#### Affected browser(s)
Tested with Chrome 87.0.4280.88.

**Comment by KacperMadej** [comment]
Hi @mfechner ,

Thank you for reporting the problem.

This is not related to Angular. Demo in vanilla JS: https://jsfiddle.net/BlackLabel/cfd9sz6p/1/
The x values are already mixed in the demo so the issue and the solution will be more visible.
X must be a number and when it is a date-time object those don't compare correctly between each other when `===` is used.

> x: number
The x value of the point. For datetime axes, the X value is the timestamp in milliseconds since 1970.

API reference: https://api.highcharts.com/highcharts/series.line.data.x

**Comment by mfechner** [comment]
Dear @KacperMadej ,

thanks a lot for you answer. I converted the timestamp using `getDate()` to miliseconds and now it works perfectly fine.
