### ISSUE TITLE
Cancel rendering

### ISSUE THREAD

**Issue by Liorkooznits** [highcharts/highcharts#14828]
Hi,

In my app, the arguments used to configure the chart is updating very often.
Is there anyway to cancel the chart rendering if one of the configuration is being updated?

Thanks,
Lior

**Comment by KacperMadej** [comment]
Hi @Liorkooznits 

The GitHub issues in this repo are used as our bug tracker. Your issue is not a bug report. The issue will be closed.
Please contact technical support through one of the available channels: https://www.highcharts.com/blog/support/

The [`chart.update`](https://api.highcharts.com/class-reference/Highcharts.Chart#update) has a `redraw` argument - when set to false the rendering be canceled. To trigger rendering after that you could use [`chart.redraw`](https://api.highcharts.com/class-reference/Highcharts.Chart#redraw). More info in the linked API references.
