### ISSUE TITLE
Column series display incorrect values with axis breaks

### ISSUE THREAD

**Issue by racoleman** [highcharts/highcharts#14833]
#### Expected behaviour
A column series on a chart with an x-axis break should behave the same as a line series: columns between `from` and `to` should be removed.

#### Actual behaviour
The columns between `from` and `to` are shifted to the `from` x position. The last column in the break ends up on top, resulting in an incorrect y value for that position.

#### Live demo with steps to reproduce
Adapted from the [docs example](https://api.highcharts.com/highcharts/xAxis.breaks):
https://jsfiddle.net/ug7xhofL/

#### Product version
Highcharts 8.2.2

#### Affected browser(s)
Tested in Chrome 87

**Comment by KacperMadej** [comment]
Hi @racoleman 

Thank you for reporting the problem.

All columns from the gap are pushed to the beginning of the gap: https://jsfiddle.net/BlackLabel/5cnypdmt/1/ (marked hoverable point from the middle of the gap) 

Regression since version 8.0.0.
Bisected to commit 65d82368dd 
The last working version was 7.2.2: https://jsfiddle.net/BlackLabel/5cnypdmt/

Because `broken-axis` is a core part of Stock - fyi @pawelfus
