### ISSUE TITLE
[Line Chart] [with data label] Window narrator reading incorrect state of legends

### ISSUE THREAD

**Issue by v-vibsingh** [highcharts/highcharts#14837]
#### Expected behavior
In narrator mode when legend is highlighted with tab the narrator should read `Hide Tokyo Button ON` when legend button is enabled and vice versa.

#### Actual behavior
In narrator mode when legend is highlighted with tab the narrator is reading `Hide Tokyo Button OFF` when legend button is enabled and vice versa.

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/line-labels

1. Open above mentioned link
2. Selecting Result console of `jsfiddle`
3. Turn ON narrator by pressing `CTRL + Windows Key + Enter Key`
4. Press Tab key to reach on legend of chart
5. Hearing the issue as it says `Hide Tokyo Button OFF` on `Tokyo` legend button.

#### Product version
Highcharts v8.2.2 (on Demo page)
Highcharts v8.1.2 (on Project webpage)

#### Affected browser(s)
Edge Version 87.0.664.66 (Official build) (64-bit)

#### Screenshot
![image](https://user-images.githubusercontent.com/76475047/102878849-e391b300-446e-11eb-82e5-9d609f13c596.png)

**Comment by KacperMadej** [comment]
Hi @v-vibsingh 

Thank you for reporting the problem.

IMHO this is working correctly - when a button for hiding series is turned off then the series is visible, so the description is correct. Would it be more intuitive if the message were "Show Tokyo Button ON" when the series is visible? 

It is possible to change the description through the API options: https://api.highcharts.com/highcharts/lang.accessibility.legend.legendItem

However, the button state for the narrator is not changeable through the API.

A11y issue - FYI @oysteinmoseng

**Comment by v-vibsingh** [comment]
Hi @KacperMadej 

Currently the `visible legend button (Tokyo)` message is `"Hide Tokyo Button OFF"`.
https://www.highcharts.com/demo/line-labels

 If the `legend button (Tokyo) is visible` then should have message of `"Hide Tokyo Button ON"` because it would tell about the legend button which is currently visible (ON) and give more sense about the `visible legend button (Tokyo)` and vice versa.

When the legend button is visible the `aria-pressed="false"`, narrator read `OFF` instead of `ON`.

**Comment by KacperMadej** [comment]
I imagine this could be argued both ways, but the point is that you require this to work as you have described and this is all that matters for me in this issue.

@oysteinmoseng is our Head of Accessibility and should be able to provide more info on the case. (Due to the winter holiday season, it might take a bit longer than usual.)

**Comment by oysteinmoseng** [comment]
Hi @v-vibsingh - this is by design. `ON` read by narrator indicates that the button is pressed - i.e. that the "Hide series" button is pressed, and the series is hidden.

I think however that we should do as Kacper suggests: Change the ARIA logic to be pressed by default, and change the text to `"Show ..."`. This will break backwards compatibility, but will be more intuitive for Narrator users.

Also note that you can change the text of the label using this API option, if this is of help in your case: https://api.highcharts.com/highcharts/lang.accessibility.legend.legendItem.
