### ISSUE TITLE
Incorrect labels position in drilldown when Gantt module is activated

### ISSUE THREAD

**Issue by vlcr** [highcharts/highcharts#14868]
#### Expected behaviour
![image](https://user-images.githubusercontent.com/17763177/103531930-90662a00-4e8a-11eb-8baf-c17b337248ad.png)

#### Actual behaviour
![image](https://user-images.githubusercontent.com/17763177/103531962-a4119080-4e8a-11eb-8231-25c7debbd11e.png)

Data labels are initially rendered correctly. **After entering a deeper level of dropdown, data labels are in the incorrect position.** The effect stays even after returning back to the root level.

#### Live demo with steps to reproduce
https://codesandbox.io/s/highcharts-react-demo-forked-tcltb?file=/demo.jsx

1. Uncomment line no. `15` from `demo.jsx` to turn on the Gantt module.
2. Save & refresh the demo project
3. Click on the label of given month to go deeper into the drilldown.
4. **Check how new labels are positioned. (x axis)**
5. Click on the button to go back to root level
6. **Check how the position of labels changed. (x axis)**

#### Product version
Highcharts v8.2.2

#### Affected browser(s)
- Chrome v89.0
- Safari v14.0
- Firefox v84.0

**Comment by PaulDalek** [comment]
Hi @vlcr

Thank you for contacting us and reporting this issue. This behavior occurs because the different value of the [`align`](https://api.highcharts.com/highcharts/xAxis.labels.align) option is set. Setting it to `right` in both axes labels' options will resolve the problem.

**Simplified demo**
https://jsfiddle.net/BlackLabel/80L7pwsx/

**Comment by vlcr** [comment]
Hello @PaulDalek, thanks for a quick response.

>  This behavior occurs because the different value of the align option is set.

I don't believe I'm setting `align` option explicitly in my example. 🤔 

>  Setting it to `right` in both axes labels' options will resolve the problem.

I'd like to keep `align` value as `undefined` to benefit from the automatic calculation [provided by Highcharts](https://api.highcharts.com/highcharts/xAxis.labels).

I've edited your demo to illustrate the problem: https://jsfiddle.net/xuqL1az2/
Could you please review the issue once again?

**Comment by PaulDalek** [comment]
@vlcr

Thank you for more information. It seems that the problem comes from the `afterSetAxisTranslation` event which is added in the gantt script. When the drilldown action is executed, the event is triggered and `align` is set to `left`. I agree, it is a bug, as it shouldn’t interfere with labels like that in a non-gantt chart. As a workaround you can explicitly set a value of the `align` but in case you don’t want to do that, you can remove the initial `afterSetAxisTranslation` event from the `Axis` prototype and add it again in a slight modified version (for example by adding a conditional that is checking if this is a gantt chart).

**Workaround**
https://jsfiddle.net/BlackLabel/xzd8bf9q/

_Internal note_
Performing a drilldown action on a non-gantt chart results in triggering the `onAfterSetAxisTranslation` event which in some cases explicitly sets the `align` to `left` causing wrong labels alignment. It concerns the datetime type of x values.
