### ISSUE TITLE
Slower chart creation with newer versions

### ISSUE THREAD

**Issue by plamens** [highcharts/highcharts#14865]
I am bumping the version of highcharts we are using from 7.1.1 to 8.2.2. We are also using the exporting and accessibility modules.

#### Expected behaviour
I expect that chart creation will take roughly the same amount of time with the new version.

#### Actual behaviour
Highcharts.chart() takes ~3x more time measured in the bare fiddle and ~5x more in our app.
Please check the thread I posted about this in the forums: https://www.highcharts.com/forum/viewtopic.php?f=9&t=45524

#### Live demo with steps to reproduce
7.1.1 https://jsfiddle.net/plamens/sk4wcxq2/1/
8.2.2 https://jsfiddle.net/plamens/bsnw3ohk/1/

#### Product version
7.1.1 and 8.2.2

#### Affected browser(s)
Tested with Chrome 87

**Comment by PaulDalek** [comment]
Hi @plamens 

Thank you for contacting us and reporting this issue. I was able to simplify your example and recreate mentioned behavior. The rendering times looks like this:

**v7.1.1:** ~70ms (https://jsfiddle.net/BlackLabel/k4631trb/)
**v8.2.2:** ~230ms (https://jsfiddle.net/BlackLabel/n51vog98/)

It seems that the accessibility module is responsible for increasing the rendering time. It is because the markers are required for the a11y, therefore they are all rendered as well (see the responsible commit below). Disabling the `accessibility` feature or not using the `marker.enabled` property (by default, in case of such points density, markers won’t be visible by default) improves the performance.

**Simplified demo**
https://jsfiddle.net/BlackLabel/eju0g76x/

_Internal note_
@oysteinmoseng Is there some way to increase the performance in such cases?

Bisect led to this commit: https://github.com/highcharts/highcharts/commit/bb616ce60377e5fdeb9872461a86ad40f1835993

**Comment by oysteinmoseng** [comment]
Markers are only forced enabled when these points need to be available to screen reader users. There is a threshold here, set by the [accessibility.series.pointDescriptionEnabledThreshold](https://api.highcharts.com/highcharts/accessibility.series.pointDescriptionEnabledThreshold) option. This threshold is looked at for each individual series, so if you have a lot of series close to the threshold you will see a performance difference. You can lower the threshold for better performance: https://jsfiddle.net/0cfhqz1s/.

Perhaps we should have an overall threshold as well for the total number of data points in the chart.
