### ISSUE TITLE
Highstocks: Current Price Indicator Label disappearing sometimes

### ISSUE THREAD

**Issue by rogerwalt** [highcharts/highcharts#14879]
#### Expected behaviour
When I enable the current price indicator, I expect to see the label showing the current price at all times.

#### Actual behaviour
The label showing the current price disappears and reappears when I change the view in the navigator. It also disappears and reappears when changing the view using the range selector.

#### Live demo with steps to reproduce
http://jsfiddle.net/rogerwa/5bvpgdfr/9/
1. Enable current price indicators, notice that the current price indicator label works fine.
2. Select 3m in the range selector. Notice that the current price indicator label disappears, depending on the window size.
3. Move the time window using the navigator below, and notice that the current price indicator label disappears and reappears.

#### Product version
Highstock v8.2.2

#### Affected browser(s)
Chrome v87
Firefox v84

**Comment by KacperMadej** [comment]
Hi @rogerwalt 

Thank you for reporting the problem.

The source of the problem seems to be the `compare: 'percent',`. If the indicator gets hidden when the raw value is outside of the axis range (even if the percentage value is within the range).

Minimal demo: https://jsfiddle.net/BlackLabel/ex5fbv16/1/
Add the indicator via GUI --> the line is plotted correctly on the axis, but the label is hidden.
Compare with:  https://jsfiddle.net/BlackLabel/ex5fbv16/2/
Add the indicator via GUI --> it's visible that the line is plotted twice - 1st for the raw value and 2nd for the data point position.

**Workaround**: force show the label - https://jsfiddle.net/BlackLabel/ex5fbv16/3/

**Comment by rogerwalt** [comment]
Hi @KacperMadej 

We were able to use the workaround, thanks for your answer.

Cheers,
Roger
