### ISSUE TITLE
Highcharts: Current Price Indicator for multiple series

### ISSUE THREAD

**Issue by rogerwalt** [highcharts/highcharts#14888]
#### Expected behaviour
I expect the current price indicator to indicate the current price for every series.

#### Actual behaviour
When using the current price indicator from the stock-tools bar, the current price indicator is only displayed for one series.

#### Live demo with steps to reproduce
http://jsfiddle.net/rogerwa/5bvpgdfr/9/

1. Enable the current price indicator from the stock toolbar.
2. Notice that only one label and one red line is displayed instead of 3 each.

#### Product version
Highstock v8.2.2

#### Affected browser(s)
Chrome v87
Firefox v84

**Comment by KacperMadej** [comment]
Hi @rogerwalt 

Thank you for reporting the problem.

The feature is not fully/clearly described in our documentation, so I see how there might be different expectations for this feature. IMHO the tool works as designed and only documentation should be improved.

Another option would be to either change how this stock tool works (to meet your requirements), add some option to have this work both ways, or add a new tool like in the workaround below.

@rogerwalt Please let me know how would like to see this issue resolved.

Stock tools are limited here by the price indicator which is limited by axis because it allows only a single crosshair label.

**Workaround**: define custom stock tool (docs: https://www.highcharts.com/docs/stock/stock-tools) that will work as needed. Demo: http://jsfiddle.net/BlackLabel/Ld6cb4uk/

I had to disable `compare: 'percent'` due to another issue #14879
I had to use multiple axes due to the axis crosshair label limit.

**Comment by JustinPhung** [comment]
Hi @KacperMadej,

i am working together with @rogerwalt.
We could implement the current Price Indicator as suggest in the workaround.

That's why in my opinion this issue is resolved.

Thank you!

**Comment by pawelfus** [comment]
We will improve logic for showing/hiding price indicators:

- button will toggle price indicators for all series (price series, volume series, and technical indicators)
- to solve a potential issue with multiple overlapping price indicators, we will resolve it by assigning the same color to the price indicator as the main series has (e.g. if the series has an orange color, the price indicator's line and the label will have an orange stroke and fill)
