### ISSUE TITLE
Prototype pollution

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#14883]
#### Expected behaviour
Prototype pollution should not be possible through JSON-compliant chart options.

#### Actual behaviour
It goes unfiltered through the merge function.

#### Live demo with steps to reproduce
https://jsfiddle.net/highcharts/k86dr5qg/

#### Product version
v8.2.2

#### Affected browser(s)
Chrome, Firefox…

**Comment by Gipxy** [comment]
May i know this fixed in which version ?
I run Nexus scan for 9.0.0, but still got this issue. Detail:

EXPLANATION
The highcharts package is vulnerable to Prototype Pollution. The merge function in Utilities.js does not properly check to ensure that object prototypes are not being altered. An attacker can exploit this by changing the __proto__ or constructor property and therefore all subsequent objects.

DETECTION
The application is vulnerable by using this component.

RECOMMENDATION
We recommend upgrading to a version of this component that is not vulnerable to this specific issue.

Note: If this component is included as a bundled/transitive dependency of another component, there may not be an upgrade path. In this instance, we recommend contacting the maintainers who included the vulnerable package. Alternatively, we recommend investigating alternative components or a potential mitigating control.

ROOT CAUSE
highcharts.8.2.2[4.2.1, 9.0.0)
ADVISORIES
Project:https://github.com/highcharts/highcharts/issues/14883
CVSS DETAILS
Sonatype CVSS 3:7.5
CVSS Vector:CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N

**Comment by KacperMadej** [comment]
Broken in v8 - https://jsfiddle.net/BlackLabel/ewq0uojr/
Fixed since v9.0.0 - https://jsfiddle.net/BlackLabel/ewq0uojr/1/

Could you share the source of the es-modules file? I am unable to track the problematic part of the code.

**Comment by DanielJRutledge** [comment]
Are there plans to release an 8.x version with this fix?

**Comment by KacperMadej** [comment]
No, but we probably could make such plans - marking the issue up for an internal discussion.
The issues will be updated as soon as anything changes (probably next week).

**Comment by TorsteinHonsi** [comment]
> Are there plans to release an 8.x version with this fix?

Version 8.x in general doesn't run filtering on chart options, so it is required that the implementer filters any content coming from an untrusted source. In v9 we changed our policy to aim for stopping XSS vectors coming from **strings within the chart options**. Functions (formatters and event handlers) not included. This required a major refactoring on how HTML and pseudo HTML=>SVG is handled, and it will not be backported. While we could do patches for som individual XSS vectors, it will not change the fact that you need to do filtering before adding configs to Highcharts.

**Comment by KacperMadej** [comment]
I have checked the first and the last item on the list and both have code that is altering prototypes but those are done by design - a new class is created or an existing class is edited using the prototype. Both are internal changes and are looking as intended. Code could be changed to avoid this type of prototype edits but those are not security issues.

**Comment by JunQuann** [comment]
I see, thanks so much for the quick response :) 
Just to check, does this apply to the rest of the items on the list?

**Comment by KacperMadej** [comment]
As far as I can tell after checking the files - yes.
