### ISSUE TITLE
Stacking area is changing connecting nulls behavior

### ISSUE THREAD

**Issue by melloc01** [highcharts/highcharts#14882]
#### Expected behaviour
Stacking modifier should not change connectNulls behavior

#### Live demo with steps to reproduce
Can be seen at: https://jsfiddle.net/kv95w0hc/

#### Product version
Highcharts, tested from @7.0.3 and above

**Comment by BernardoFBBraga** [comment]
It seems that the boolean value is inversed, setting connectNulls to true has the opposite effect in the area chart

**Comment by melloc01** [comment]
That's weird. Just confirmed that @BernardoFBBraga.

`stacking=true` + `connectNulls=true` **does not connect nulls**

**Comment by PaulDalek** [comment]
Hi @melloc01 

Thank you for contacting us and reporting this issue. First of all, I just wanted to explain the behavior when the `connectNulls` is set to true. It gives an impression that there is a break because the differences between numeric and null values are really small (1) compared to the x gap between numeric values (10000). In case the interval between points is the same, the generated chart looks like this: https://jsfiddle.net/BlackLabel/9ba2wf5n/ (more info can be found here #2069). So, in your case this can be used as a workaround to display the gap correctly. As for the issue itself it looks like a bug. It occurs when there are multiple yAxes. Also, it concerns the last series in a stack only (https://jsfiddle.net/BlackLabel/y269pvmf/).

**Workaround**
https://jsfiddle.net/BlackLabel/x16k49ry/

_Internal note_
Found this related old issue #5524 where Jon provided the fix that never got merged. It’s v4 era but it might be useful. Example: https://jsfiddle.net/BlackLabel/1c30ovqr/.

**Comment by melloc01** [comment]
Nice, thanks for that @PaulDalek 
True, my dataset actually made me think the nulls points weren't connecting.

My scenario is that the users can add/remove series on demand, so, it is not an option to make the stacking series come first since the users have control over it.

I could just add a "ghost" series after adding a stacking one but that sounds so wrong that I'd not consider that a workaround hehe

It'd be nice to have the old fix patched in new versions, how likely is that to happen?

**Comment by PaulDalek** [comment]
@melloc01

I have applied the `getStackPoints` modification from the proposed fix and it seems it works well with the newest version. As for the ETA for this fix, it is hard to say now but we will look into it.

**Workaround**
https://jsfiddle.net/BlackLabel/a4eLpfbc/

**Comment by melloc01** [comment]
That's great @PaulDalek  :smile: 

Sorry if it looked like I asked for an ETA, just wanted to know if it was possible, at some point, to bring that fix to a new version. It seems it is :tada:

Thanks again :muscle:
