### ISSUE TITLE
Always continue line to end (not start) of interval step

### ISSUE THREAD

**Issue by XRochen** [highcharts/highcharts#14903]
# Description of the feature
I want to use Highcharts for time series that can have gaps (for missing/unrecorded interval steps). When I plot such a time series, Highcharts draws the line up to the start of the last valid point before a gap.
![image](https://user-images.githubusercontent.com/77274780/104177536-383ea300-5409-11eb-9a21-91864a6a1ebe.png)

However, since the value is valid for the entirety of the interval step (in this case for an entire day), the line should continue to the end of the foregone interval step.
![image](https://user-images.githubusercontent.com/77274780/104177252-c6665980-5408-11eb-9e35-02a3020d520d.png)

The same also applies to the end of the time series. Adding artificial values is not an option, as time series with a one-step-wide gap would suddenly have that gap incorrectly filled. If I understand correctly from [my Stack Overflow post](https://stackoverflow.com/questions/65394070/completely-plot-line-for-a-day-before-a-gap), there is currently no option to do this, so I'm requesting this feature to be added.

# Library related to the feature
Highcharts Stock

# Proof of Concept/Live example for the feature

----

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by PaulDalek** [comment]
Hi @XRochen

Thank you for contacting us and suggesting this enhancement. Right now the line won’t be rendered as expected simply because there are no values for Nov. 9th and Nov. 25th. As a workaround you can add additional points that will extend the line. Although, it won’t look the same, you can also set the [`step`](https://api.highcharts.com/highstock/series.line.step) option to `center` to achieve a similar look (the marker will still indicate the proper value but it will add the visual effect closer to the one presented in the second image). Finally, there is a possibility to shift points by setting [`pointPlacement`](https://api.highcharts.com/highstock/series.line.pointPlacement) along with [`pointRange`](https://api.highcharts.com/highstock/series.line.pointRange) options.

**Demos**
https://jsfiddle.net/BlackLabel/z8jqf3wm/ - additional values
https://jsfiddle.net/BlackLabel/y6tm8hj5/ - the `step` property set to `center`
https://jsfiddle.net/BlackLabel/L8jwn4s0/ - using `pointPlacement` and `pointRange` options.

**Comment by XRochen** [comment]
@PaulDalek Thanks for the numerous and useful suggestions. Unfortunately, it appears that none of them 100% fit my problem. The one with additional values comes close visually, but as I noted above, gaps may be only one unit wide, meaning that an added value would effectively fill the gap. It might also ambiguous to have a point for Nov-9 when there actually was no recorded value for that date. The cleanest solution I can think of would be a new option that defines whether a value's validity ends with the interval step's start or just before the next step. The latter would be used for my problem. I'm not familiar enough with the codebase yet to submit a PR.

**Comment by PaulDalek** [comment]
@XRochen

Ok, I see. There is also another solution that concerns using nulls. In case when the `gapSize` is set to one day, you can add another, null point in a place where the gap should be and set it’s x to half of the current day. With the `connectNulls` set to false there will be a gap even if the difference between actual points is one day.

**Demo**
https://jsfiddle.net/BlackLabel/mw3seatk/

**Comment by XRochen** [comment]
Thanks @PaulDalek this seems to work. However, I still feel like this is more of a workaround and a native implementation (which would not show a separate fake data point) would still be appreciated.

**Comment by PaulDalek** [comment]
@XRochen

Sure, it is still labeled as an enhancement. We will observe it and decide based on the popularity of this feature whether to implement it.
