### ISSUE TITLE
Split outside tooltip w/ followPointer creates flashing/hiding tooltip

### ISSUE THREAD

**Issue by ckifer** [highcharts/highcharts#14906]
I've searched issues and can't find anything that mentions this. Might be semi related to [#9590](https://github.com/highcharts/highcharts/issues/9590)
#### Expected behaviour
Tooltip is rendered normally no matter the `followPointer` or `followTouchMove` settings

#### Actual behaviour
Tooltip flickers on move but disappears entirely while just hovering

#### Live demo with steps to reproduce
https://jsfiddle.net/wy19gumq/71/

#### Product version

v8.2.2

#### Affected browser(s)
Chrome (latest)
* Disappears entirely in Chrome 
Safari (latest)
* Stays on screen but gets cut off in Safari
Potentially more

**Comment by KacperMadej** [comment]
Hi @ckifer 

Thank you for reporting the problem.

The split tooltip has multiple boxes pointing to points and an axis label. Those elements are fixed in position, so how would you see this working with `followPointer: true`?

The easy solution will be to fix the flickering and ignore the option as it seems like it doesn't have any logic implemented - so to render normally. If you would like to propose a different solution please let us know.

**Workaround**: there is no implemented logic for a split tooltip with followPointer and working code is the one without the followPointer setting - https://jsfiddle.net/BlackLabel/81emLob7/

**Comment by ckifer** [comment]
Hi @KacperMadej 
Yeah this works in my case, I just wanted to make sure the issue was documented for those looking for the issue in the future.

Thanks!
