### ISSUE TITLE
The chart does not reflect any data changes a second time

### ISSUE THREAD

**Issue by krema** [highcharts/highcharts#14918]
#### Expected behaviour

The chart should reflect or redraw the chart when data changes with setData() a second time.

#### Actual behaviour

The chart does not reflect any data changes a second time.

#### Live demo with steps to reproduce
https://jsfiddle.net/kremakro/n3yecbtv/ 

Steps to reproduce:
1. Click on button "Set Data After"
2. Click on button "Set Data Before"

#### Product version
Highcharts JS v8.2.2 (2020-10-22)

#### Affected browser(s)
MS Edge

**Comment by PaulDalek** [comment]
Hi @krema

Thank you for contacting us and reporting this issue. This is not a bug. The reason why the data is not updated is because upon clicking the ‘Set Data After’ data is mutated ([more info](https://developer.mozilla.org/en-US/docs/Glossary/Mutable)). To prevent this, simply set the series’ data with a copy of the ‘before’ array.

**Demo**
https://jsfiddle.net/BlackLabel/t3d5anpj/
