### ISSUE TITLE
RSI indicator on the line type chart.

### ISSUE THREAD

**Issue by miloszwojcik** [highcharts/highcharts#14930]
#### Expected behavior
Add an RSI Indicator line to the chart

#### Actual behaviour
Add a blank series.

#### Live demo with steps to reproduce
https://jsfiddle.net/12hnszkg/9/

Replicate.

Add an RSI indicator from the indicators list. Note nothing happens. You should get a new series on the chart. This happens only on the line type chart. On ohlc it's working fine. 

The issue might also exist in other indicators like: PSAR, NATAR, KETLNER CHANNEL, VWAP, VOLUME BY PRICE, MONEY FLOW INDEX, ACCUMULATION/DISTRIBUTION

**Comment by KacperMadej** [comment]
Hi @miloszwojcik 

Thank you for reporting the problem.

Some indicators require OHLC data format because some parts of the data are used for the indicator calculations. **RSI requires close value.**

It is possible to create custom technical indicators as explained in the docs here: https://www.highcharts.com/docs/stock/custom-technical-indicators

**Workaround**: a demo with modified RSI to work with line series data - https://jsfiddle.net/BlackLabel/rps7f9to/

**Comment by sebastianbochan** [comment]
Hi @miloszwojcik,
You should declare a [useOhlcData](https://api.highcharts.com/highstock/series.line.useOhlcData) option.

Demo:
- https://jsfiddle.net/BlackLabel/h24nb6Lu/

**Comment by miloszwojcik** [comment]
I think this would be much more efficient if we could operate just on the line data [open date, value] and use the RSI. 
RSI just needs `[open date, close value]` so I'm confused why ohlc is required in this case. Does RSI indicator in high charts necessarily need some other values than  `[open date, close value]`?

**Comment by pawelfus** [comment]
Hi @miloszwojcik 

RSI does not need more information, only the close values. We can assume that the only value provided in a line series is what a user wants to use for calculations. Nice catch, thanks!

You mentioned other technical indicators:
- PSAR requires high and low values
- NATR is based on ATR, which needs high and low values
- Keltner Channel is based on ATR, also requires high and low
- VWAP does not require OHLC data, should work with line and OHLC series
- Volume by Price, requires only close values, could be improved too
- in MFI we use `(H+L+C)/3` to calculate the typical price
- Accumulation/Distribution requires low, high, and close values

Note we have only `useOHLC` option, instead of multiple `useHLC`, `useOC` etc options. It is more likely to use technical indicators that require different values (for example SMA based on OPEN and MFI) and it could create bugs for developers that don't know (and don't want to know) which technical indicator requires which values.

**Comment by pawellysy** [comment]
The VBP already works for line type series: https://jsfiddle.net/BlackLabel/7zkdqpgy/
So does VWAP: https://jsfiddle.net/BlackLabel/y6k2zabt/
