### ISSUE TITLE
Solidgauge with max 0 and value 0 does not render properly

### ISSUE THREAD

**Issue by loriepisicchio** [highcharts/highcharts#14947]
#### Expected behaviour
I'm using solidgauge to render some figures and related quotas.
When setting an activity gauge with max 0 and value 0, the rendered gauge should be fully filled

#### Actual behaviour
When setting an activity gauge with max 0 and value 0, the rendered gauge should is half filled

#### Live demo with steps to reproduce
https://jsfiddle.net/7o10xngc/

#### Product version

Highcharts 8.2.2

#### Affected browser(s)
Firefox (84.0.2 (64-bit)), Chrome (Version 87.0.4280.141 (Official Build) (64-bit))

**Comment by PaulDalek** [comment]
Hi @loriepisicchio

Thank you for contacting us and reporting this issue. The gauge is rendered that way because even though the `min` and `max` are set to 0, they are -0.5 and 0.5. As a workaround to display 0 as you expect you can set the `tickPositions` array with only one value (0) and set the `threshold` property to -1 in a series with 0 value.

**Workaround**
https://jsfiddle.net/BlackLabel/v4du5m2j/

**Comment by loriepisicchio** [comment]
Thanks, the workaround solves my issue. Actually, only setting `threshold` to -1 was enough (no need to change `tickPositions`

**Comment by PaulDalek** [comment]
@loriepisicchio

Since the behavior isn’t really a bug, I closed this issue. In case of any further technical questions like this one, you can alway contact our [support](https://www.highcharts.com/blog/support/).
