### ISSUE TITLE
Accessibility module included & point y value null leads to errors in browser console

### ISSUE THREAD

**Issue by kemusag** [highcharts/highcharts#14966]
#### Expected behaviour
No errors in console. 

#### Actual behaviour
In case the accessibility module is included, there is a error (or multiple errors) in the console when selecting a point whose y value is null programmatically:
Error: <rect> attribute y: Expected length, "NaN".

In addition, the point that is added in the DOM has a y value of NaN.

![image](https://user-images.githubusercontent.com/77784146/105348348-84979900-5be8-11eb-95d7-a6acaad74776.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/L8kaxdpw/20/

Rerpo steps:

1. Open attached jsfiddle
2. Open browser dev tools
3. Click on the button and check the console afterwards (not the console in jsfiddle but the actual browser console)

#### Product version
I was able to reproduce it in Highcharts 8.1.2 and 8.2.2

**Comment by PaulDalek** [comment]
Hi @kemusag 

Thank you for contacting us and reporting this issue. It happens when the value of a point is null and the dummy point for the accessibility purpose is created. It eventually leads to setting a `y` attribute with `NaN` value.

**Workaround**
https://jsfiddle.net/BlackLabel/ayb1v4on/

_Internal note_
Bisected to commit: https://github.com/highcharts/highcharts/commit/eed89c07951c530c03dde7afb8230a075d04370d
