### ISSUE TITLE
Pattern fill fails to render when <base> tag is present and window.location is manipulated via history.pushState

### ISSUE THREAD

**Issue by goransle** [highcharts/highcharts#14973]
#### Expected behaviour
Should render as it does in the latest release: http://jsfiddle.net/goransle/kdpswnb6/

#### Actual behaviour
Pattern fills fails to render.

#### Live demo with steps to reproduce
http://jsfiddle.net/goransle/mr4jqa3e/

#### Product version
Current master

#### Affected browser(s)
Latest Chrome + Firefox

**Comment by goransle** [comment]
Additional info: bisected to commit f639b8c, which does not change anything directly related.

**Comment by khlieng** [comment]
This "regression" happened because the layout-forcing getBoundingClientRect() was removed from chart.render which probably used to delay chart load just enough for the pushState to happen after the pattern loading, the pattern would still have the wrong URL on the next redraw and disappear (without the other PR).
