### ISSUE TITLE
Bubble chart borders

### ISSUE THREAD

**Issue by DK-Unit4** [highcharts/highcharts#14991]
#### Expected behaviour
The api says that series for bubble has borderWidth and dashStyle

#### Actual behaviour
In fact those has no effect. Instead series.marker.lineWidth  sets the border width, but dashStyle - I hasn't found a way how to make to work

#### Live demo with steps to reproduce
http://jsfiddle.net/Kumlander/s08ewyxo/17/
here I set both series and series' marker settings: you can see that series levels has no influence on the result

#### Product version
Latest

#### Affected browser(s)
All
![bubble](https://user-images.githubusercontent.com/38954233/105740924-5c8a9b80-5f42-11eb-8c45-28356351fbd7.PNG)

**Comment by PaulDalek** [comment]
Hi @DK-Unit4 

Thank you for contacting us and reporting this. The `dashStyle` applies only to the `graph` when set in the `series` section. There is no `dashStyle` for markers, though it is easy to apply. You can simply add an `afterRender` event that will trigger at the end of the `render` series.

**Demo**
https://jsfiddle.net/BlackLabel/6cxpa1ny/

**Comment by DK-Unit4** [comment]
Thank you for you answer. 

Could I double check
there is https://api.highcharts.com/highcharts/6.0.3/series.bubble.dashStyle serie for bubble charts setting in api called dashStyle but it doesn't work, right?
There is also https://api.highcharts.com/highcharts/6.0.3/series.bubble.borderWidth border width setting and it also doesn't have any effect on bubble charts, right?

instead you suggest to work it around using markers (thanks for the work around) by adding this (I need different borders for different bubble series)
series: [{
    type: 'bubble',
    name: 'bubble',
    data: [1, 2, 3, 4, 5],
    marker: {
        radius: 20,
        lineWidth: 2,
        lineColor: '#ff0000',
        dashStyle: 'dash'
   

thanks

**Comment by PaulDalek** [comment]
@DK-Unit4 

The [`dashStyle`](https://api.highcharts.com/highcharts/series.bubble.dashStyle) refers to dash style used for the graph element, not the markers. As I mentioned in my previous message, there is no such an option for markers but it is easy to apply it (the workaround above).

**Comment by DK-Unit4** [comment]
Sorry, I do not understand you
the following links has no reference to markers
https://api.highcharts.com/highcharts/6.0.3/series.bubble.dashStyle 
https://api.highcharts.com/highcharts/6.0.3/series.bubble.borderWidth 
and those do not work for me, so why you talk about markers? Do I miss something?

**Comment by PaulDalek** [comment]
@DK-Unit4 

Sorry if I wasn't clear enough. The `bubble` series originates from the `scatter` (the bubble points are created the same way). As you probably noticed, most of the graphical options of a bubble can be set through the `marker` section, just like in line or scatter series. In the `scatter`, as well as in the `bubble` series you can enable a connecting line (the `graph`) by setting the [`lineWidth`](https://api.highcharts.com/highcharts/series.bubble.lineWidth). The `dashStyle` from the series section will apply only to it (https://jsfiddle.net/BlackLabel/fj3kw5za/). That's why I mentioned `markers`. If you want to, you can of course modify the previous workaround demo to use `series.dashStyle` value and not the one from the `marker` series to apply it for the line, as well as for the points.
