### ISSUE TITLE
Panning on mouse pointer devices doesn't work for async server loaded charts

### ISSUE THREAD

**Issue by mediafreakch** [highcharts/highcharts#15012]
#### Expected behaviour

1. Open the demo below on a desktop computer
2. **Zoom into any area** on the chart using your mouse 
3. Now hold "Shift" key and drag your mouse left or right

I would expect the chart to pan left/right and load more data when finished.

#### Actual behaviour

Cannot pan left/right on desktop

#### Live demo with steps to reproduce

https://jsfiddle.net/ghc0mzoq/

#### Product version
Highstock 8.2.2

#### Affected browser(s)
Any

Is there a way to achieve panning on desktop using the `panKey` option along with async loaded data from the server?

I know the user could use the navigator, but panning is useful especially when focussing on a very narrow time window. That becomes very clumsy in the navigator

**Comment by PaulDalek** [comment]
Hi @mediafreakch 

Thank you for contacting us and reporting this. The reason why panning cannot be performed is because the visible x range is the full available range, no matter which button of the `rangeSelector` is clicked. The demo that you sent is an example of a lazy loading approach which means that every time xAxis extremes are changed, a new set of data from a selected range is loaded. This is useful in case you have a huge amount of data and performance might be a problem. Here is an example where the whole data is loaded at once, therefore you can pan through the chart: https://jsfiddle.net/BlackLabel/drwoxmz3/.

**Comment by mediafreakch** [comment]
@PaulDalek Ok so if I understand correctly there is no way to achieve panning with lazy loaded data?

**Comment by PaulDalek** [comment]
@mediafreakch 

Yes, for the reasons mentioned in my previous comment.
