### ISSUE TITLE
Click on xAxis not working anymore

### ISSUE THREAD

**Issue by summer11sky** [highcharts/highcharts#15031]
#### Expected behaviour
When clicking on xAxis values, a function is called, which is not working anymore with the new Highcharts JS v9.0.0 (2021-02-02).

#### Product version
Highcharts JS v9.0.0 (2021-02-02)

**Comment by KacperMadej** [comment]
Hi @summer11sky 

Please add a live demo for the problem.

**Comment by summer11sky** [comment]
Hi @KacperMadej 
 Here is a live demo in CodePen: https://codepen.io/summer11sky/pen/oNYXEjE

Thank you!

**Comment by khlieng** [comment]
This is intentional and part of the new improved security, javascript gets stripped from `href` and `src`.

**Comment by KacperMadej** [comment]
>Highcharts Basic v9.0.0 (2021-02-02):
>Improved security by filtering all HTML configuration strings and abstract syntax trees through allow lists before inserting into the DOM.

(https://www.highcharts.com/blog/changelog/)

A hard-coded deny list `'background', 'dynsrc', 'href', 'lowsrc', 'src'` is used as well as an allow list based on `AST`'s [`allowedAttributes` array](https://github.com/highcharts/highcharts/blob/bfb7411d76a8c3d06663f6663cc42e5f43ed3f73/ts/Core/Renderer/HTML/AST.ts#L124-L189).

It is possible to extend the `allowedAttributes` list but there is no official API for this and the array is not easily accessible.
`Highcharts._modules['Core/Renderer/HTML/AST.js'].allowedAttributes.push('onclick');`

You could use `onclick` attribute like in this demo: https://codepen.io/Blacklabel/pen/BaQNrdp

**Comment by TorsteinHonsi** [comment]
Instead of hacking the allow list, I would rather recommend to separate the click handlers from the config. 

See https://codepen.io/TorsteinHonsi/pen/RwoWPqd for how to add behavior programmatically outside the config.

**Comment by TorsteinHonsi** [comment]
Since https://github.com/highcharts/highcharts/pull/15120, the allow list will be exposed and easy to override.

`href="javascript:...` is considered potentially harmful, so it will not be allowed by default. To allow JS execution from `href` attributes, the `allowedReferences` can be modified like so:

`Highcharts.AST.allowedReferences.push('javascript:')`;

**Comment by KacperMadej** [comment]
Hi @drmrbrewer 

We have [debugger](https://www.highcharts.com/docs/advanced-chart-features/debugger-mode) that could show the warning. 
Would this be helpful?
Alternatively, using a similar code as in the debugger module, it could be possible to catch the warning and add some custom code to deal with it.

Right now there is a problem - the warning is not picked up by the debugger module, but this is reported here: https://github.com/highcharts/highcharts/issues/15188

Please let us know if you have a better solution in mind.

**Comment by drmrbrewer** [comment]
@KacperMadej the problem is that I'm not seeing any warnings even in the console.  Does the debugger just expose (prominently on the chart) what is anyway shown in the console?  When I first tried v9 I did see some highcharts warnings in the console about some obsolete table-related html tags, which I dealt with by replacing them with more compliant equivalents, but now I'm seeing formatting issues with other elements of my chart, without any warnings or other indications in the console about what highcharts is (I am assuming) filtering out silently because of this new feature.

**Comment by KacperMadej** [comment]
In short: There shouldn't be any silent filtering. Maybe you could create a live demo for this?

More: A warning level console log should show up when AST has blocked something (duplicates of the same error are blocked to prevent console overload). Something like `Highcharts warning: Invalid attribute 'security-risk' in config` - [demo](https://jsfiddle.net/BlackLabel/Ltokcnmz/). The debugger module shows an error in a chart if the error could be traced back to the chart - if something goes south before a chart or its renderer is created then you won't see the error in the chart - only in the console.

**Comment by drmrbrewer** [comment]
I dunno, so many things in my chart break when I try use version 9 that I don't know where to start.  Maybe I'm unfairly targeting this HTML filtering feature, but I can't see anything else major in version 9 that could cause such mayhem.  Most often, even going to a new major version, and it works without change or only very minor changes.  This time, not.  I'll see if I can figure out what the culprit is and produce a demo.

Is there any way of completely disabling AST, just to rule that out?

**Comment by KacperMadej** [comment]
Unfortunately, there is no option to easily disable that module. However, disabling filtering of tags and attributes via a super ugly hack is short:  https://jsfiddle.net/BlackLabel/64u50cqy/1/ (the title has both).

**Comment by drmrbrewer** [comment]
So a lot of my problems related to [this issue](https://github.com/highcharts/highcharts/issues/15228), which was causing axis ticks to go missing, and corresponding tick labels too... i.e. unrelated to AST.

But I've also posted [this issue](https://github.com/highcharts/highcharts/issues/15235) which may relate to AST and this new html filtering?

**Comment by KacperMadej** [comment]
It's related - I will get more details and post a comment on the issue about trimmed characters in the chart title.

**Comment by Pascal76** [comment]
missing attributes for me:

Highcharts.AST.allowedAttributes.push('border');
Highcharts.AST.allowedAttributes.push('align');
Highcharts.AST.allowedAttributes.push('bordercolor');
Highcharts.AST.allowedAttributes.push('zIndex');
Highcharts.AST.allowedAttributes.push('bgcolor');

**Comment by KacperMadej** [comment]
@Pascal76 
Please open a new issue for this as this is an issue about something else and your problem will be probably lost here.

**Comment by summer11sky** [comment]
The "allowedAttributes" worked. Thank you for the help!

**Comment by cnighswonger** [comment]
A year later, this "feature" still causes silent failures when attempting to add onClick to html passed out to subtitles via the text option. See [this thread](https://www.highcharts.com/forum/viewtopic.php?p=173976) for more details.

Hours of searching failed to produce even a reference to this isssue on github. It would seem that @TorsteinHonsi 's [response ](https://github.com/highcharts/highcharts/issues/15031#issuecomment-778148724)should feature prominently in the documentation AND that there should be a console warning at least indicating that the attribute has been stripped/sanitized.

Silent fails waste a bunch of time.

Thanks for an otherwise fantastic tool!

**Comment by cnighswonger** [comment]
Hey @raf18seb,

> Actually, there is extended information about it in our documentation, e.g. here: https://www.highcharts.com/docs/chart-concepts/security

Hopefully that will eventually index in various search engines. That would have been great a day or so ago.

> And the console warning indicating that the attribute has been stripped also in the console:
> 
> ```
> highcharts.src.js:230 Highcharts warning: Invalid attribute 'onclick' in config
> ```

This was my bad. Warning display was off in my console... go figure.

You've pretty much covered it above. But adding the link above to the warning above might be a help.

Thanks for taking time to respond!

**Comment by raf18seb** [comment]
@cnighswonger,

> Hopefully that will eventually index in various search engines. That would have been great a day or so ago.

I thought about the same, so I found a few Forum threads, edited some posts and added the docs URL even before reading your last answer :) I hope this will help and will be easier to find.

> This was my bad. Warning display was off in my console... go figure.

It happens to the best!

I created a ticket about adding more info to the console warning: https://github.com/highcharts/highcharts/issues/17015
