### ISSUE TITLE
Mappoint gets overlapped

### ISSUE THREAD

**Issue by muvvalabharatha** [highcharts/highcharts#15057]
Hi,
I am using highcharts/highmaps ( _"custom/world"_ map) to display certain details at two locations which have a different purpose as **_mappoint_**. Then I will add different **_mapline_** that should show me multiple connecting lines between the two mappoints.

[Click to see sample demo](https://jsfiddle.net/vyshnavimuvvala/tk9yfw57/13/)
But I am able to visualize only a single mappoint and a single mapline. I guess all the points/lines overlapped on one another, finally displaying one detail among all the given data.

I am unable to find any alternative approach to the requirement, which allows me to visualize all the available points at a location either on mouse over or click functionality like a Overlapping Marker Spiderify approach.

Please suggest if there is any approach that can help us to achieve the requirement.

Thanks,
Muvvala Bharatha

**Comment by PaulDalek** [comment]
Hi @muvvalabharatha 

Thank you for contacting us and reporting this. Yes, you are right, all of the points are overlapping because of the same lat/lon values. It's not a bug. When it comes to joining lines, the case is the same as the `arcPointX` and `arcPointY` are the same for each `path`. You could try to modify these factors to make `paths` look a little different from each other. Also, you can try to use [marker clusters](https://www.highcharts.com/docs/advanced-chart-features/marker-clusters) but each point must have a different lat/lon to reveal separate points from a cluster on zooming.

**Demo**
https://jsfiddle.net/BlackLabel/sk7v4xwj/ - different paths
https://jsfiddle.net/BlackLabel/t7L28faz/ - using marker clusters
