### ISSUE TITLE
X-axis custom intervals for charts xrange

### ISSUE THREAD

**Issue by yulai841415** [highcharts/highcharts#15064]
hi~
Thank you for opening my issue.

It is expected to be able to customize the x-axis interval of the chart. At present, the labels of the x-axis of the graph generated by the default method will display incompletely and fold lines. When calculating according to the "day" method, the interval is always two days. It is expected that the setting of the interval can be customized here.

For example, as shown in the demo in the link, it is expected that the x-axis labels will not be folded, and all the last labels will be displayed. At present, the display form of "week" has not taken effect. How to achieve the above effect~

demo:https://jshare.com.cn/public/C0Gn1m

**Comment by KacperMadej** [comment]
Hi @yulai841415 

Thank you for reporting the problem.

You could set axis.units to allow only 1-day and prevent 2-day tick intervals.
```
	xAxis: {
		type: 'datetime',
		dateTimeLabelFormats: {
			day: '%Y-%m-%d',
			// week: '%Y-%m-%d'
		},
		units: [[
				'millisecond', // unit name
				[1, 2, 5, 10, 20, 25, 50, 100, 200, 500] // allowed multiples
		], [
				'second',
				[1, 2, 5, 10, 15, 30]
		], [
				'minute',
				[1, 2, 5, 10, 15, 30]
		], [
				'hour',
				[1, 2, 3, 4, 6, 8, 12]
		], [
				'day',
				[1]
		], [
				'week',
				[1]
		], [
				'month',
				[1, 3, 6]
		], [
				'year',
				null
		]]
	},
```

The bug here is docs are wrong:

API reference: https://api.highcharts.com/highcharts/xAxis.units
(units as in the code snippet above)

The defaults in the code:
https://github.com/highcharts/highcharts/blob/e9bf7208d3b90c7adab59042a2fe9038e5eaa4bd/ts/Core/Axis/DateTimeAxis.ts#L122-L146

(Notice the difference in 3 out of the last 4)
