### ISSUE TITLE
SVG filtered out of tooltip HTML

### ISSUE THREAD

**Issue by harrismd** [highcharts/highcharts#15076]
#### Expected behaviour
SVG graphics render in tooltips when useHTML is true

#### Actual behaviour
SVG graphics are filtered out of the HTML and are not displayed in the tooltip.

#### Live demo with steps to reproduce
https://jsfiddle.net/mharrisqb/9wrbn7fz/
Simply hover over the chart and notice there is no blue circle to the left of the text "Series 1" and no black diamond to the left of the text "Series 2".

#### Product version
Highcharts 9.0.0

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Hi @harrismd 

Thank you for reporting the problem.

In the browser console you should be able to find a warning - `(highcharts.src.js:518) Highcharts warning: Invalid tagName 'svg' in config`. The behavior is by design:

> Improved security by filtering all HTML configuration strings and abstract syntax trees through allow lists before inserting into the DOM.

(v9.0.0 - first point - https://www.highcharts.com/blog/changelog/)

See the related issue for more info: https://github.com/highcharts/highcharts/issues/15031

**Comment by harrismd** [comment]
Shall we change this to a feature request then? Highcharts used to support <SVG> graphics in HTML tooltips. It was removed in version 9. We'd like it back.

**Comment by harrismd** [comment]
I would argue that supporting `<svg>` in HTML is just as important as supporting `<img>`.

**Comment by Yash2737** [comment]
Issue for me, cannot render svg html directly
