### ISSUE TITLE
Line drawn incorrectly with series clipping disabled

### ISSUE THREAD

**Issue by govinda18** [highcharts/highcharts#15128]
#### Expected behaviour
On resizing the output pane, the line should be drawn correctly.

#### Actual behaviour
Line goes missing on resizing the output pane. Markers are drawn but line is not. 

#### Live demo with steps to reproduce
[https://jsfiddle.net/vmfop43L/](https://jsfiddle.net/vmfop43L/)

Resize the output pane to reproduce the issue. Note that when `series.clip` is enabled, it works fine.

#### Product version
Highstock v9.0.0

#### Affected browser(s)
Chrome

**Comment by PaulDalek** [comment]
Hi @govinda18

Thank you for contacting us and reporting this. Yes, it looks like this bug occurs since v7.1.2 and only when Highcharts Stock script is loaded (with Highcharts, series being clipped correctly). It also has something to do with the `animation` as when set to `false`, it works correctly.

**Workaround**
https://jsfiddle.net/BlackLabel/da4p51u8/ - `animation` set to `false`

_Internal note_
Resizing the chart results in an incorrect clipping. Might be related to #14549.

**Demo**
https://jsfiddle.net/BlackLabel/4dgsb9nz/
