### ISSUE TITLE
Gantt chart Export Y-axis overlapping issue into chart issue

### ISSUE THREAD

**Issue by Sreejithga** [highcharts/highcharts#15131]
#### Expected behaviour

The Gantt chart export should work with no overlapping

#### Actual behaviour

Gantt chart export produces images with the Y Axis text overlapping into chart area

#### Live demo with steps to reproduce

https://jsfiddle.net/sreejithga/tw5ms9da/1/

#### Product version
Highcharts Gantt JS v9.0.0 (2021-02-02)

#### Affected browser(s)
Chrome

Added the image below highlighting the overlap issue when exported using the export icon (3 lines) in the chart.
![image](https://user-images.githubusercontent.com/53110553/107920794-f1534880-6f86-11eb-901d-20d265d856ef.png)

**Comment by PaulDalek** [comment]
Hi @Sreejithga 

Thank you for contacting us and reporting this. It seems that the Open Sans font is not found on the server, therefore the default font is used which causes categories to fall out of the grid. To resolve this, you should set the `fontFamily` with multiple fonts that are available and in case the first one is not found, another one will be used and so on. You can also set your own server and install a required font. [Here](https://github.com/highcharts/node-export-server#installing-fonts) you will find how to do it.

**Demo**
https://jsfiddle.net/BlackLabel/y2e6hwgv/

**Comment by Sreejithga** [comment]
HI @PaulDalek  thanks for your kind revert. I understand what you mean, but I'm still facing this issue in my environment. 

"You can also set your own server and install a required font. Here you will find how to do it."

As per the documentation, I've copied the ttf files to Windows/Font folder, still its not working.

When the highcharts is rendered in the HTML page, it shows Open Sans, but when exported also it shows Open Sans but the overlap issue exists.

Please assist.

**Comment by KacperMadej** [comment]
@Sreejithga 
If you are installing the fonts make sure that you have set up the exporting server and your chart is using it. In case the font installed on your export server is not working as expected please report the bug on the export server repository, if the problem is not reported there already - https://github.com/highcharts/node-export-server/issues

Exporting to SVG seems to be working correctly - which format are you using?

-----------

The exported chart is scaled up by default for better print quality, so fixed widths of labels given in pixels might not be scaling correctly every time and might cause a forced, through the used chart options, overlap of some elements.

This issue seems to be a general exporting problem visible even with default fonts.
Minimal demo: https://jsfiddle.net/BlackLabel/j45dnoc6/1/
Exported to PNG: 
![chart (74)](https://user-images.githubusercontent.com/8960408/108253342-f61c2600-7159-11eb-9427-be2cc0962e12.png)
Rednered in Chrome/Win10:
![gantt-not-exported-on-win10](https://user-images.githubusercontent.com/8960408/108253394-046a4200-715a-11eb-90ef-43ea848c12b3.jpg)

There is something wrong with the font or width calculation even for the default font family. In the exported image the first dataLabel overlaps with the point.
