### ISSUE TITLE
Regression in map drilldown - data labels should fade in

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#15133]
#### Expected behaviour
On drill down, data labels should fade in slowly after the chart has zoomed

#### Actual behaviour
Data labels appear abruptly before the chart has zoom-animated

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/demo/map-drilldown/

#### Product version
A regression in v7.0.0. Worked as intended in v6.2.0.

**Comment by khlieng** [comment]
Did some poking. The opacity fading part of this broke in 7.1.0, because of `inactiveOtherPoints`, there is no fading in of data labels on drilldown for all series that are not `inactiveOtherPoints`. And the deferred part of it broke in 8.2.0 when `defer` was introduced and the `setTimeout` in `drawDataLabels` got removed.
