### ISSUE TITLE
No tooltip for large data formatter in line chart

### ISSUE THREAD

**Issue by tahirgrt** [highcharts/highcharts#15143]
#### Expected behaviour

When using formatter, the tooltip is customized and it take huge space, the tooltip should be shown with scrollbar in line chart (with split: true option)

#### Actual behaviour

When using tooltip formatter, custom data with huge space is provided (in case of line chart), the tooltip is not shown at all. 

#### Live demo with steps to reproduce

https://jsfiddle.net/j0bykdeo/

#### Product version

Tested in v7, v8 and v9.
#### Affected browser(s)
Every browser.

**Comment by PaulDalek** [comment]
Hi @tahirgrt 

Thank you for contacting us and reporting this. There is no such an option for a tooltip that can be set through API but you can easily achieve what you want by simply using some CSS. Take a look at the demo below.

**Demo**
https://jsfiddle.net/BlackLabel/kfz2dncv/

**Comment by tahirgrt** [comment]
I think you have understood the issue correctly. According to your demo, if I will change the chart type to 'line', you can see that nothing is shown. 
Can you look into this example https://jsfiddle.net/jgsq50rw/.

**Comment by PaulDalek** [comment]
@tahirgrt 

I think that using a split `tooltip` with a scrollbar doesn’t make any sense. The reason why the tooltip is empty is because when the `split` is set to `true`, it is expected that the formatter returns an array (more info [here](https://api.highcharts.com/highcharts/tooltip.formatter)). To make it work with line series simply get rid of the `split` option as it doesn’t make sense here anyway.

**Demo**
https://jsfiddle.net/BlackLabel/hLk2964t/
