### ISSUE TITLE
Data labels hidden in bar chart stacked to percent & limited axis 

### ISSUE THREAD

**Issue by tomassatinsky** [highcharts/highcharts#15145]
#### All data labels visible when possible
![image](https://user-images.githubusercontent.com/31855226/107964791-f4136500-6fa9-11eb-9a35-e9750921a19f.png)

#### Actual behaviour
Labels of the last cropped bar are hidden
![image](https://user-images.githubusercontent.com/31855226/107964855-0d1c1600-6faa-11eb-90f2-b2da264446f3.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/tpk392x0/

#### Product version
Introduced in Highcharts 8.0.1

#### Affected browser(s)
Tested in Chrome, last version

**Comment by PaulDalek** [comment]
Hi @tomassatinsky

Thank you for contacting us and reporting this. It’s a regression since `v8.0.1`. As a workaround you can force data labels to be displayed in the center of each column by setting the `inside` property to `true`.

**Workaround**
https://jsfiddle.net/BlackLabel/but462j0/

_Internal note_
Bisected to this commit https://github.com/highcharts/highcharts/commit/b7a44f29e4c573852ddb29d57cbc57fafad00194

**Comment by tomassatinsky** [comment]
Thank you @PaulDalek. The workaround works and has no adverse side-effect. But still, does it mean a bug with workaround is not a bug and is going to be closed?

**Comment by khlieng** [comment]
@tomassatinsky this got closed because it has been fixed in #15148.

**Comment by tomassatinsky** [comment]
I see, I missed that. Thanks!
