### ISSUE TITLE
Slowness on Gantt

### ISSUE THREAD

**Issue by AnanditaP** [highcharts/highcharts#15168]
#### Expected behaviour

- Load
- Selecting Range
- Expand/Collapse

Should be rendered in 2-3 seconds

#### Actual behaviour
Actual Time it is taking to respond -
- Load (15-20 seconds - sometimes browsers stop responding and display pop up to wait/cancel)
- Selecting Range (6-8 seconds)
- Expand/Collapse (10 seconds)

#### Live demo with steps to reproduce
https://jsfiddle.net/hsc9uaow/

**Note:**
xAxis labels have range 20-22 in years. (2008-2031)
This issue replicates only when size of data is large.
Time mentioned in seconds above is for basic Gantt. When Gantt chart is customized, 3-5 seconds are added to the existing.

**Comment by KacperMadej** [comment]
Hi @AnanditaP 

Thank you for reporting the problem.

The demo crashes for me and I am not able to open it at all - could you add some code error to prevent it from running?
(e.g. wrong Highcharts src in the HTML section)

**Comment by AnanditaP** [comment]
Hi,

The problem is about crashing only. we are able to see the chart when it loads but we are unable to perform any activity such as selecting ranges, using navigator, expand/collapse. It takes a lot time to respond. Page keeps on loading and it doesn't allow us to perform any action one after other.
It happens only when large amount of data is provided.

**Comment by KacperMadej** [comment]
JSFiddle is crashing when trying to process the options in the demo for me. Performance of both JSFiddle and Highcharts depends on the client-side machine, so something that fails and crashes for me might show as slow or ok for someone else. I have managed to open the demo and copy code from it to a stand-alone HTML site with JS script and it works - slow, but without crashes.

Looks like the grid layout for x-axes with the default options is causing the huge performance drop. The next issue is the number of `plotBands` in the demo. In a zoomed-out chart density of the `plotBands` is so high that they all visually merge into a single grey-ish useless background noise. What is the expected result of marking every weekend in a 20 years range?

With both issues resolved the demo is here: https://jsfiddle.net/BlackLabel/z1ysh2vc/

**Comment by LMprasadkulkarni** [comment]
Hi @KacperMadej as mentioned by @AnanditaP I am facing the similar kind of issues, https://jsfiddle.net/w986qdno/12 here is the working example of it. 
I have added console.time for redraw and load events to understand the time taken for respective operations. It almost varies from 5 secs to 15 secs. Do the following steps to reproduce
1. hover over any span and wait for it to turn red
2. now hover out of the span to an empty area and wait for it to turn grey again
3. also try to hover on any span and switch to some other span and observe the time taken for changing their colors

**Comment by KacperMadej** [comment]
Without a browser console closed, it takes about 150-300ms. With the browser console opened the time is roughly doubled.
Still, the performance is not so bad, but again - this is a client-side script so depends on the client machine.

I am not sure how this demo helps with the original problem. Points have hover states and executing `chart.redraw` is not needed for this - in case some key info is missing here, please add it. For better performance avoid re-rending the whole chart and change the visual properties of a point using CSS.

The original issue was not active (see my pending question from my previous comment) for a long enough time for me to close this issue due to inactivity. In case you would like to see this issue reopened please leave a comment with more info.
