### ISSUE TITLE
In iPad, Legend disable and enable of series1, disables series2 and does not restore even on click outside of the chart container.

### ISSUE THREAD

**Issue by kamineel** [highcharts/highcharts#15160]
#### Expected behaviour
Moving the cursor away from the legend area and out of chart container should show all the series in their respective solid colors with original opacity. (Same as in the browser mode)

#### Actual behaviour
When a series in a chart is disabled and enabled from the legend all the other series plots are dimmed. It does not show up in solid color even after clicking outside the chart container.

#### Live demo with steps to reproduce
Problem Simulation: 
1.	Open fiddle https://jsfiddle.net/qszxe6ar/4/ in ipad mode in chrome browser
2.	Disable Series1 and enable it back.
3.	Series 2 is in disabled state. Even if I click outside the chart container, Series 2 is still in disabled state. (Refer screenshot below)

This happens in iPad devices, can also be seen in Chrome simulator mode of iPad.

#### Product version
![iPad Legend disable and enable](https://user-images.githubusercontent.com/6358934/108190885-80ec2900-7138-11eb-980b-83060fce15b3.png)
Highcharts 8.1.2

#### Affected browser(s)
iPad Safari and other touch devices.

**Comment by KacperMadej** [comment]
Hi @kamineel 

Thank you for reporting the problem.

This is a regression and the last working version is 7.1.2.
Broken since 7.1.3 - bisected to https://github.com/highcharts/highcharts/commit/48eea858be59a2b70dcd6b094c0ab2eb3910b984

The problem is also visible in an Andorid running touch device and could be recreated without touch support.
Minimal demo to run without the touch device: https://jsfiddle.net/BlackLabel/a8gubck2/
Steps:
1. open browser console
2. click the 1st series item in the chart legend (to hide the series)
3. get stopped by the debugger and notice that the 2nd series is showing normally
4. unfreeze yourself from the debugger stop and click the 1st series item again (to show the series)
5. get stopped by the debugger and notice that the 2nd series is inactive
6. additionally: after resuming **if no mouse event will be registered** by the chart then the problem will be still visible
