### ISSUE TITLE
Security reported by nexus IQ

### ISSUE THREAD

**Issue by Gipxy** [highcharts/highcharts#15190]
#### Expected behaviour
No security issue
#### Actual behaviour
Got the high risk security from Nexus IQ:
"The highcharts package is vulnerable to Prototype Pollution. The merge function in Utilities.js does not properly check to ensure that object prototypes are not being altered. An attacker can exploit this by changing the __proto__ or constructor property and therefore all subsequent objects."

#### Product version
9.0.1

**Comment by Gipxy** [comment]
Can give priority for this issue ? We are considering to buy the highstock chart, but got this issue when try to scan by Nexus IQ

**Comment by KacperMadej** [comment]
Hi @Gipxy 

Thank you for reporting the problem.

Could you share more details about the problem - how to recreate this? which files were tested?

**Comment by aarjithn** [comment]
Getting same issue with nexus sonatype with v9.0.1 even though SNYK reports no issues.
Adding few more details from error log

> **Explanation**
The highcharts package is vulnerable to Prototype Pollution. The merge function in Utilities.js does not properly check to ensure that object prototypes are not being altered. An attacker can exploit this by changing the __proto__ or constructor property and therefore all subsequent objects.
**Detection**
The application is vulnerable by using this component.
**Recommendation**
We recommend upgrading to a version of this component that is not vulnerable to this specific issue.
Note: If this component is included as a bundled/transitive dependency of another component, there may not be an upgrade path. In this instance, we recommend contacting the maintainers who included the vulnerable package. Alternatively, we recommend investigating alternative components or a potential mitigating control.
**Root Cause**
highcharts-9.0.1.tgz <= package/es-modules/highcharts.src.js[7.2.2, )
**Advisories**
Project: `https://github.com/highcharts/highcharts/issues/14883`

**Comment by KacperMadej** [comment]
Could you share more details about the problem - how to recreate this? which files were tested?

You are probably getting an error because some unused file has the wrong version.
Make sure that the source of the error points to the files you are using or help us track the source.

**Comment by aarjithn** [comment]
We run a self hosted instance of nexus iq which does the sonatype scan of npm packages in use and flag this. I'm not sure how to reproduce this outside of such a nexus environment.
That said, I think this is an issue with sonatype than highcharts (Utilities.js does have a guard now) so we have waived this alert.

Also - our security team pointed out the bug fix #14883 is not mentioned in https://www.highcharts.com/blog/changelog for v9. Could this be added now?

**Comment by Gipxy** [comment]
My mistake, this was the issue in version 8 and fixed already in version 9.0.1. Thank you

**Comment by KacperMadej** [comment]
As the main issue here seems to be resolved we only have the missing change log info, so keeping the issue open for this reaon.

**Comment by KacperMadej** [comment]
The changelog update could be tracked here: https://github.com/highcharts/highcharts/pull/15431
The main issue is resolved - closing.
