### ISSUE TITLE
Tooltip not shown when using multiple fixed tooltips in Highstock

### ISSUE THREAD

**Issue by muenchto** [highcharts/highcharts#15227]
#### Expected behaviour
When using multiple tooltips that are fixed by a custom positioner, I expect to see tooltips of all series. If they don't fit (vertically, on the y axis), I expect them to be shown in a second "column".

#### Actual behaviour
Tooltips that do not fit (on the y axis) are hidden.

#### Live demo with steps to reproduce
https://jsfiddle.net/ksnd1v2w/9/

Note that this fiddle is based on the demo example of fixed tooltips in Highstock: https://www.highcharts.com/demo/stock/stock-tools-gui
I added multiple series and reduced the hight in order to show the effect. 

#### Product version
Highstock v8.2.2

#### Affected browser(s)
Chrome v88

**Comment by KacperMadej** [comment]
Hi @muenchto 

Thank you for letting us know about the problem.

The second column should be a part of the custom positioner implementation - your positioner should place the elements (labels) of the tooltip and the placement should be final - not later changed by default code. Full placement should depend only on the positioner - the bug here is that the point labels of the tooltip are not placed as calculated by the positioner.

_Internal note:_
In case positioner is used the tooltip labels should be placed as defined in the positioner. We should prevent the default distribution logic that moves and hides the labels to avoid overlap. Positioner, if given in the chart options, should handle this.

**Comment by muenchto** [comment]
Hi @KacperMadej 

thanks for the swift reply!

I get you and I have already started to implement a positioner that takes care of depending on which tooltip it is. I had to use undocumented attributes, though.. I it still does not work. 

Here is the fiddle:
https://jsfiddle.net/oh5t16q7/20/

Would be great if you could affirm that the distribution logic is somehow overriding my positioner - or even better, find the bug in my positioner :)

Have a great weekend!

**Comment by KacperMadej** [comment]
Distribution logic overrides positioner - all items after being sorted by rank and if any one of them is exceeding the total height (no matter the position) then the default algorithm assumes there is no way to fit those ones under another (so doesn't fully respect positioner).

As a workaround, you could use a shared tooltip instead of the split one - https://jsfiddle.net/BlackLabel/uho2sbn6/
The axis label will no longer be there, but you will be able to use `tooltip.formatter` and render all tooltip data as needed.
