### ISSUE TITLE
Pie chart center coordinates are off when showing labels

### ISSUE THREAD

**Issue by nulle** [highcharts/highcharts#15240]
#### Expected behaviour
Getting pie chart center coordinates with `series.center` was suggested in multiple forum topics, including but not limited to [this](https://www.highcharts.com/forum/viewtopic.php?t=32580) and [this](https://www.highcharts.com/forum/viewtopic.php?t=33098), so, I would expect it to return correct coordinates in all cases. 

#### Actual behaviour
`series.center` coordinates are sometimes way off.

#### Live demo with steps to reproduce
https://jsfiddle.net/nulle/sf0z5gy4/
Initially, center (marked with a red circle) is correct.
When labels are turned on (button), chart is resized (expected), but center coordinates are now off.
After turning labels off, the center coordinates are correct again.

#### Product version
9.0.1 (also older)

#### Affected browser(s)
Probably all (using Chrome 88.0.4324.192 on MacOS)

**Comment by KacperMadej** [comment]
Hi @nulle 

Thank you for reporting about the problem.

The forum posts are rather old and might have worked better at the time of writing. The used property `series.center` is not a part of API and is used internally. The charts are looking fine, so I don't think that there is a bug here that should be fixed.

For custom code and code modifications instead of `series.center` you could use `x` and `y` values of `shapeArgs` of any point - those are looking like place correctly in both cases: https://jsfiddle.net/BlackLabel/o0g52xj7/ 
However, those are also internal and not a part of public API, so related code might be changed even through a maintenance update.

**Comment by nulle** [comment]
This will work in my case. Thanks @KacperMadej !

**Comment by pawellysy** [comment]
Closing - Stale
