### ISSUE TITLE
Chart not updating on first click in highcharts react

### ISSUE THREAD

**Issue by zhenming91** [highcharts/highcharts#15253]
Goal : To hide and show legend with on click of a button

#### Expected behaviour
Expected : When clicked for the first time, legend should hide.

#### Actual behaviour
Reality : The legend does not hide on first click. The legend only hide upon second click.

#### Live demo with steps to reproduce
https://stackblitz.com/edit/react-r29nue?file=index.js

#### Product version
    "highcharts": "8.2.2",
    "highcharts-react-official": "3.0.0",

#### Affected browser(s)

Chrome

**Comment by khlieng** [comment]
This happens because you wont be able to see the updated state of `showLegend` until the next time your render function runs, so you need to do this: https://stackblitz.com/edit/react-eqx1b6?file=index.js

Some other alternatives:
* https://stackblitz.com/edit/react-jx8lpn?file=index.js
* https://stackblitz.com/edit/react-ryufjm?file=index.js

**Comment by zhenming91** [comment]
Thank you.
