### ISSUE TITLE
Highstock navigator calculate wrong range on changing limits also xAxis label

### ISSUE THREAD

**Issue by PAPIONbit** [highcharts/highcharts#15278]
#### Expected behaviour
When navigator range change or move:
1. The lowest range limit be till 2 points / or any clear rule.
2. It really show what it limited to show.
3. It don't force xAxis to show not important labels.

#### Actual behaviour
1. It force limits to something not clear.
2. By changing and moving it possible show you something that is not in your selected range.
3. On move/change xAxis labels mix to each other or you will see so many not important labels or suddenly just one label.

As this example (movie):

https://user-images.githubusercontent.com/47592258/110217684-a4e69300-7eca-11eb-9f1f-664838b1f663.mp4

#### Live demo
https://jsfiddle.net/PAPIONbit/0p4oxs5y/

+ I am not sure if there is no way and should be like this or it is a serious bug so please explain it what is the problem.

#### Product version
Highstock 9.0.1

**Comment by KacperMadej** [comment]
Hi @PAPIONbit 

Thank you for contacting us.

The minimal range of an axis is defined and controlled by [Axis.minRange](https://api.highcharts.com/highstock/xAxis.minRange).

The xAxis in a Stock chart is [`ordinal`](https://api.highcharts.com/highstock/xAxis.ordinal) by default, so points are distributed equally regardless of actual x values of points. This usually works well for stock-type data, but in some edge cases, it might look strange or even bad - like in your demo.

A solution here would be to set `minRange` and turn off `ordinal` - demo: https://jsfiddle.net/BlackLabel/chpo56Lb/
In case your problem is not resolved and you have a real case scenario that was simplified for the purpose of reporting this issue please share more details about your original problem.

In general, if you are not sure if a behavior is a bug please contact technical support first - https://www.highcharts.com/blog/support/

**Comment by PAPIONbit** [comment]
Hi @KacperMadej
Thank you for your attention and explanation.
I knew about `ordinal`, and it was exactly the point that why navigator range should not work well with `ordinal`.
Actually my original example is in [Persian Date](https://en.wikipedia.org/wiki/Iranian_calendars) ([Jalali calendar](https://en.wikipedia.org/wiki/Jalali_calendar)) and also dynamic and customized.
![image](https://user-images.githubusercontent.com/47592258/111033925-a400b480-8428-11eb-8ac7-aef5f3f19e4e.png)
(So i think not useful to share)

1,2. Not exact/clear navigation range: I got that by changing `minRange` i can make it more accurate and it look enough for a stock data, but still i think the navigator should work different on that situation (because when user want to change the range by handles it work almost well and force the user to go from the possible points) so it is kind of bug:
- When user `drag` whole of navigator mask, one side of mask that can not be sync with user selected part should stay in the point and just the other side come with his move.
 - When user `click out` of the mask for jumping scroll to the part, instead of refusing to scroll, it have to just sync the range itself to the clicked part.

3. About xAxis labels: still i am confused why on changing navigator range, it should show something not depend or important as extra label or closest label.
![image](https://user-images.githubusercontent.com/47592258/111034624-c0522080-842b-11eb-889c-79a9cabd38a7.png)
This problem exist in both images.
In this one, difference between the 2 points is about 1 month but suddenly it show Hour:Minute instead of Day.Month.
