### ISSUE TITLE
a11y: highlight problem when using NVDA

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#15303]
#### Behaviour
Tabbing through the chart with default NVDA (NonVisual Desktop Access) screen reader options doesn't match a11y module highlights.

#### Live demo with steps to reproduce

Live demo: https://jsfiddle.net/BlackLabel/gf3aLb10/

Steps:
1. open NVDA,
2. tab to the chart's legend with the first series highlighted by the a11y module - reads ok in NVDA,
3. press arrow down to go to the next series in the legend - the reader read correctly, but the a11y module highlight is not updated,

The highlight in (3) works correctly with NVDA disabled.

FYI @oysteinmoseng 

#### Product version
Highcharts: 9.0.1 (current)
NVDA: 2020.4

#### Related links
source: https://www.highcharts.com/forum/viewtopic.php?f=9&t=46061&p=164813#p164796

#### Affected browser(s)
Tested only in Win10/Chrome

**Comment by oysteinmoseng** [comment]
This is because down arrow in NVDA (at least when not in forms mode) only moves the virtual cursor, and does not pass the arrow down keyboard event to the page. Most screen readers highjack keyboard input from the page, and have their own keyboard shortcuts. Highcharts as such is never informed that the down arrow key is pressed, and there is nothing we can do about this (*).

You can use "pass through" keys to make the screen reader pass keys through to the page, and different screen readers will have different combinations for doing this. Alternatively entering forms mode will let some screen readers pass through the relevant keys.

In practice, this does not seem to be an issue, since screen reader users are generally familiar with their screen reader of choice, and often do not navigate using the methods of traditional keyboard navigation. Note that navigating a Highcharts chart with a screen reader does not have to be done with Tab/arrow key navigation at all. The individual elements of the chart are accessible in the DOM, and can be navigated with a screen reader without ever giving focus to the chart.

_(*) It would be possible for us to take over all keyboard navigation for the charts and effectively disable the screen reader shortcuts, but this comes with a whole host of other problems, and so far we have decided that this is not the best approach for usability. It would mean that a user would have to learn our keyboard navigation and not be able to use the navigation familiar to them with their screen reader. It would also remove all of the screen reader's custom navigation possibilities - like moving to the next heading on the page._

**Comment by manoj4099** [comment]
Hi All- For Hight Chart Map with counties bubbles- Having same issue- Not able to moves within list of countries and not able to select countries when NVDA is ON.  If use Alt+ arrow keys then NVDA user able to moves to the countries list and pressing ALT+ENTER key or ALT+Space Bar then user is able to select countries

**Comment by oysteinmoseng** [comment]
Hi @manoj4099, could you provide some more information?

1. A demo of the chart with the issue (jsFiddle link or codepen)
2. How are you trying to navigate with NVDA? Are you using down-arrow for next element and going through, or other methods? How would you expect to be able to navigate?
3. Do you have Layout Mode enabled in NVDA?

**Comment by manoj4099** [comment]
Hi @oysteinmoseng A chart chart map is implemented in a application where user can select countries and data gets filtered. Note - By-default - All countries data is showing. Team took reference from https://www.highcharts.com/blog/tutorials/best-chart-accessibility-practices/ to make the map accessible but there is an issue when NVDA is ON

Exact issue : It occurs only when we switch on NVDA and try navigating else it works fine when we navigate through keyboard without switching on NVDA.

User is not able to navigates in countries using right/Left/up/down arrow keys when NVDA is ON 

Instead of just using arrow keys, use alt+arrow keys(Left/right/up/down) to navigate to the countries and Use Alt+Enter keys or Alt+Space Bar to select countries, will work as expected.

**Comment by oysteinmoseng** [comment]
In that case, see [my reply above](https://github.com/highcharts/highcharts/issues/15303#issuecomment-796670885) - arrow keys will not work the same when a screen reader is running because of the way screen readers work. The good news is that this behavior is generally expected by users. We will be looking more into custom navigation modes for our charts, but until then there is not much we can do about this unfortunately.

**Comment by manoj4099** [comment]
Thanks for the Update!

**Comment by patrickhlauke** [comment]
A late rejoinder on this thread, sorry, but: adding a `role="application"` signals to screen readers that they should be passing keystrokes to the page (as in "the application is handling these") rather than consuming them for their own commands. I have to admit that the current keyboard experience using highcharts with NVDA or JAWS running is ... very confusing at the moment

**Comment by oysteinmoseng** [comment]
Hi Patrick, good timing! We have been doing some usability testing with `role="application"` lately with promising results, and expect to be going in this direction with Highcharts, at least as an option, or in a hybrid fashion as you suggest. Like you say, the current UX often gets confusing, and also breaks down for charts where nonlinear navigation is preferred.

**Comment by oysteinmoseng** [comment]
Note: If you want to try out `role="application"` on the SVG, that's easily doable as follows: https://jsfiddle.net/homgxnc7/show. In our experience, though, `role="application"` needs to be accompanied with a lot of hand-holding guidance for the user to avoid confusion, at least with more complex navigation models.

**Comment by patrickhlauke** [comment]
once https://github.com/highcharts/highcharts/issues/20990 is fixed it might make it slightly less confusing overall. that sort of stuff was compounding the problem
