### ISSUE TITLE
Zoom on column chart categorical X-Axis with many series does not display the proper subset of bars

### ISSUE THREAD

**Issue by cnurrenbergmtb** [highcharts/highcharts#15300]
#### Expected behaviour
Zooming on a selection of bars will increase the zoom level and display the desired selection.

#### Actual behaviour
Zooming in on a selection of bars that brackets the tick-mark for that category displays the full single category range. If the selection does not bracket the tick-mark, no bars are visible.

The axis min and max appear to be set to the correct selection on the x-axis, but the full category being displayed does not make sense given the small range and selection.

#### Live demo with steps to reproduce
https://jsfiddle.net/sc431508/14/

Invisible bars case:
1) Zoom in on the Feb category.
2) Zoom in on a selection of bars that does not encompass the tick mark
3) no bars will be visible despite appearing to select bars in the range.
4) If you continue to scroll / zoom on the right-most sections of the graph, you will scroll past other categories without seeing a single bar. 

Zoom doesn't appear to work increase zoom:
1) Zoom in on the Feb category.
2) Zoom in on a small selection of bars that does encompass the tick mark
3) The full category is still visible despite the `minRange` being set to a single bar's width. Other values for `minRange` do not seem to affect the zoom level.

#### Product version
Highcharts, Highstock 8.1.2

#### Affected browser(s)
Chrome

**Comment by KacperMadej** [comment]
Hi @cnurrenbergmtb 

Thank you for contacting us about the problem.

With multiple column series that are placed on the same x value, some columns look like placed on different x values. When zooming into a column you are selecting xAxis range and zooming to that range - the columns could look like placed on different x values in different viewed axis ranges. It shows better is the xAxis has more ticks: https://jsfiddle.net/BlackLabel/cqtzevmk/

Another feature of the chart that shows is additional axis padding extending axis min and max - extra range without ticks on both ends of the xAxis to make space for columns placed on edge. In case you zoom into a range <1, 2> then columns in placed "around" 1 and 2 needs to be shown, so the visible range is extended.

If you want to get precise zoom into single columns then you need to set a precise x value for each column. In general, a chart like in this demo: https://jsfiddle.net/BlackLabel/cqtzevmk/1/ should be closer to the one you are looking for.

For precise zooming, a series with points having x and y defined like line, scatter, or area series type will look and work better. A column point has defined x and value (with is stored in y property), but from the chart, data, and data visualization point of view those are not the same and because of this are shown differently.

The behavior is by design so there is no bug here. The main goal is to let you make charts you want to make, so please let me know if there is anything unclear and what would be an ideal solution for your case.

**Comment by cnurrenbergmtb** [comment]
Hello @KacperMadej,

Thanks for looking into this further.  We are not able to add additional x-coordinates for clustered bars in this case, although it does appear that it would fix the behavior in this jsfiddle. 

However, this particular cluster configuration is considered an extreme edge case by our standards; we already have alternate ways to display similar types of data sets with different column chart configurations that make more sense from a data-visualization perspective. So we are fine closing this issue since it is not deemed to be a bug by your design.
