### ISSUE TITLE
Markers for annotations are never reused

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#15315]
#### Expected behaviour
Use again the same marker if `id` is set and used multiple times.

#### Actual behaviour
A new marker definition is added to `defs` every time a marker is used. Even if the option for marker has already been used and the marker exists.

Highcharts Stock Stock-Tools are using this so FYI @pawelfus 

#### Live demo with steps to reproduce
Compare the same marker used 6 times and 1 time.
https://jsfiddle.net/BlackLabel/85afxyub/1/

#### Product version
v9.0.1

**Comment by pawelfus** [comment]
Thanks! What's worse, every `annotation.update()` creates a new definition show up: https://jsfiddle.net/BlackLabel/85afxyub/7/

Could you check if it's not a regression? Perhaps something with AST?

**Comment by KacperMadej** [comment]
@pawelfus 
Might be a regression, but I couldn't find anything significantly useful.
v7.0.0 is the first version with updates for annotation and the worst part happens there already.
The main issue is probably a regression done in between 7.1.1 and 7.1.2. Bisected to https://github.com/highcharts/highcharts/commit/04b5ad945ee1b994a15ea9b74dccdee151417058
However, the commit doesn't look like it could do anything related to the issue.

Not related to AST.
AST was added in v9 and the last v8 fails the tests the same way - https://jsfiddle.net/BlackLabel/85afxyub/8/

**Comment by dugokontov** [comment]
Not sure if it is related to this bug, or is it a different one. Nevertheless, updating annotation object will remove all but first label for that annotation.

Here is the example: https://jsfiddle.net/xn5dquwz/. It will update annotations after 2 seconds, and only the first annotation will remain, while others are removed from object.

Workaround for this bug is to pass existing definition for the labels to the update function:

```ts
const annotation: Annotation; // defined somewhere
annotation.update({
  labels: annotation.options.labels, // make a deep copy, but you get a point
  // other updates
});

```
