### ISSUE TITLE
Scatter chart hangs with animation set

### ISSUE THREAD

**Issue by govinda18** [highcharts/highcharts#15320]
#### Expected behaviour
Interactions should work fine

#### Actual behaviour
Scatter plots hangs when animation is set.

#### Live demo with steps to reproduce
https://jsfiddle.net/kmph4atj/2/

Observable on zooming in - 
![Gif](https://s4.gifyu.com/images/zoom3.gif)

#### Product version
Highstock 8.1.2

#### Affected browser(s)
Chrome

**Comment by KacperMadej** [comment]
Hi @govinda18 

Thank you for reporting the problem.

Zoom is very slow due to the animation option in a chart - without it works faster. This is by design and is documented:

> When zooming on a series with less than 100 points, the chart redraw will be done with animation, but in case of more data points, it is necessary to set this option to ensure animation on zoom.

API reference: https://api.highcharts.com/highcharts/chart.animation

Minimal demo: https://jsfiddle.net/BlackLabel/yte9gp3d/2/

A solution, no `chart.animation`: https://jsfiddle.net/BlackLabel/yte9gp3d/3/
