### ISSUE TITLE
Waterfall dataLabel not always properly aligned when inside: false and negative values

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#15334]
#### Expected behaviour
Align data properly for `inside: false` and negative values.

#### Actual behaviour
When in the waterfall series `dataLabel.inside: false` and the sum has negative values, data labels are rendered incorrectly.
Adding `max` to `yAxis` makes some of the labels (sum) disapear. 

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/zarg8cfh/

#### Product version
 Highcharts JS v9.0.1 (2021-02-15)

#### Affected browser(s)
All

**Comment by kolman** [comment]
Just an idea: Function `Series.prototype.alignDataLabel` in DataLabels.ts takes the point.plotY and then determines whether it is visible (`isInsidePlot = chart.isInsidePlot(plotX, Math.round(plotY), inverted)`), but for negative values the `point.plotY` is the top of the column, the zero point. For negative values, the bottom of the column should be considered, because that represents the actual value.

**Comment by kolman** [comment]
Any update on this?

**Comment by KacperMadej** [comment]
As a workaround, you could force the isIndisePlot function check to always return true - demo: https://jsfiddle.net/BlackLabel/zarg8cfh/1/

**Comment by amang95** [comment]
Is this going to stay as a workaround or are we getting a fix rolled out and have an official option or prop to be set to trigger this behavior?

**Comment by KacperMadej** [comment]
For now, the workaround could be used and since the issue is open and labelled as a bug we are planning to prepare a proper fix for the problem. Currently, there is no ETA for the fix.
