### ISSUE TITLE
Cumulative sum

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#15361]
# Description of the feature
Similar to `compare` option. The cumulative sum should render a sum according to the first point within the visible range:

```
SUM[0] = P[0]
SUM[i] = SUM[i - 1] + P[i]
```

# Library related to the feature
Highcharts Stock

# Proof of Concept/Live example for the feature
n/a

# To do's:
- [x] - new series/options implementation
- [x] - update [SCSS](https://github.com/highcharts/highcharts/blob/master/css/highcharts.scss) (in case of new styled-mode options) and the [list](https://github.com/highcharts/highcharts/blob/master/docs/chart-design-and-style/style-by-css.md) (if necessary)
~- [x] - add to [Stock Tools'](https://www.highcharts.com/demo/stock/stock-tools-gui) button list of series types~
- [x] - official [demo](https://www.highcharts.com/demo/stock) (this will cover visual test too)
~- [ ] - official [general documentation](https://www.highcharts.com/docs/stock/candlestick-chart)~ - separte ticket: #16060
- [x] - update [API](https://api.highcharts.com/highstock/) (series/options description)

----

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by laventnc** [comment]
I posted the original feature recommendation, very happy to see it's taking off. Wanted to share a bit of info I've gathered through the different iterations, [here's a link to my current version](https://jsfiddle.net/nlaventis/jwea6sd4/2/).

- I ended up needing to store the original series returns in order to efficiently respond to date-range changes
- This creates a lot of issues in terms of updating the series' actual data
  - The relationship between series.update and series.setData caused issues as the difference between data updating when the date range changes & when the actual series' data is updated
  - _I believe the best solution would be to treat it like an indicator series, where you define the hidden series as raw return data and link a cumSum type series to it_
 - Adding series to a chart became much more complex as you need to calc the cumSum over the active date range
 - Capturing xAxis.setExtremes to trigger a re-calc of the cumSum is satisfactory; however, I've noticed that this event fires more often than expected (this is what I'm currently using).
 - The relationship with the navigator has been a particular issue... You either disable navigator.adaptToUpdatedData or you end up with a changing, often misleading, series visible
 - Series with different sets of dates (x values) forced me to apply the following logic in `CumSum.setExtremes( evt )`:
   1. find the index of each series' dates that is closest to the event's min/max property
   2. get the StartIndexOffset (using the logic from the navigator plugin) if `evt.trigger === "rangeSelectorButton"`
   3. slice the original series' returns from the matching start & end index, fill with zeros what's outside that range (otherwise the xAxis will decrease to the active date range), and calculate the cumulative sum over the target range of values.

You'll noticed I have a lot logic with returnType and calcReturns/getCumReturns... this was because I also wanted the ability to show a compound sum (as this is a more accurate measure of return for investments in instruments like stocks).

Really happy to see that this is being added as I've spent the last year or so figuring it out to some success. Happy to answer any questions you might have!

**Comment by raf18seb** [comment]
Hi @laventnc, thanks for sharing your thoughts!

This feature is already in a very advanced stage - after some small code polishing, it will be merged with master and released in the next Highcharts version.

You can test the feature on branch here in this demo: https://jsfiddle.net/BlackLabel/yf7rqnt8/

**Comment by raf18seb** [comment]
@laventnc,

as you can see, the new option `cumulative` can be set on the series config, e.g.:
```js
plotOptions: {
  series: {
    cumulative: true
  }
}
```

You can also turn on/off the cumulative sum on a specific series using the `series.setCumulative(true/false)` method or you can do the same for all the axis' series at once by using the `axis.setCumulative(true/false)` method.

Feel free to share with us all your thoughts, suggestions and (especially) bugs, if any found. Any info about what can be improved/added is welcome.
