### ISSUE TITLE
export-data - CSV - allowHtml option

### ISSUE THREAD

**Issue by AnaelMobilia** [highcharts/highcharts#15391]
# Description of the feature
Add an option for the export-data modules allowing usage of HTML in CSV export.
This options will convert htmlentities ("& rarr;" on my case on the series label) to the equivalent character.
For an Excel Export, the html character is correctly rendered.

# Library related to the feature
Highcharts / export-data

# Proof of Concept/Live example for the feature

![image](https://user-images.githubusercontent.com/6187125/112282830-c47e0980-8c87-11eb-9106-67412eb78bb9.png)
Live demo -> http://jsfiddle.net/z6t0dsqu/1/
----

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by KacperMadej** [comment]
Hi @AnaelMobilia 

Thank you for submitting the feature request.

As a workaround and PoC, you could check and use this demo: http://jsfiddle.net/BlackLabel/1m547aLr/

In [`exportData`](https://api.highcharts.com/highcharts/chart.events.exportData) event `dataRows` could be edited to modify data for the table view and in exported files. HTML entities could be un-escaped there.

**Comment by AnaelMobilia** [comment]
Thanks @KacperMadej !
Is Highcharts core modules exposition a lasting thing ? (In another terms can I use this in production or will it break on next major version ?)

If this feature is implemented, I think it will be great to remove HTML tags too.
I updated your PoC with a basic regexp => http://jsfiddle.net/tkrvbw8q/1/

**Comment by KacperMadej** [comment]
Here's a demo based on API, so it won't break until a major version update will introduce a breaking change - and to be honest here the probability is practically zero because backward compatibility always was and still is very important in Highcharts:
http://jsfiddle.net/BlackLabel/smy1jbkp/

The above demo is based on API and custom code independent from any internal Highcharts code.

In general, everything not in the public API might be broken after any version update because we don't track custom modifications like this. The safest approach is to use a fixed version instead of using the newest code from CDN (so without a version number in the URL - more info on code.highcharts.com).

PoC demos are provided for testing and to be used as a workaround while waiting for the proper feature implementation.
