### ISSUE TITLE
Navigation menu style is not applied

### ISSUE THREAD

**Issue by diogen737** [highcharts/highcharts#15407]
#### Expected behaviour
Standard CSSObject `borderRadius` and `width` properties to have an effect.

#### Actual behaviour
CSSObject.borderRadius property just does nothing when applied to the navigation menu. 
```
navigation: {
    menuStyle: {
        borderRadius: 5,
    },
}
```
Possible workaround: replace `borderRadius: 5` with `'border-radius': '5px'` which is working but looks like a hack.

As for the width - CSSObject says `width?: number;`. When using number this also does nothing. However in the jsfiddle I can use string value `width: '300px'` and it works. So its either .d.ts bug or wrong CSS properties application.

#### Live demo with steps to reproduce
https://jsfiddle.net/z13b7ocy/1/

#### Product version
Highcharts 9.0.1

#### Affected browser(s)
All

**Comment by khlieng** [comment]
You can also use `borderRadius: '5px'`, but otherwise this is just how CSS works, a unit is required in these cases. The type of `width` on master is `string|0` which fits the spec, and it looks like it was `string` in 9.0.1. There are currently some non-CSS uses  of `CSSObject` which is probably why `borderRadius` has a `string|number` type.

**Comment by diogen737** [comment]
@khlieng thanks for the reply. Looks like all the typings are ok on master, waiting for the release :)
