### ISSUE TITLE
Unable to change plot area border radius

### ISSUE THREAD

**Issue by diogen737** [highcharts/highcharts#15405]
#### Expected behaviour
Although it's possible to set border for the whole chart, I can't see an option that would change actual plot area border radius.

#### Actual behaviour

When zooming the chart in you can see that actual plot area border radius is unchanged.

![Screenshot_2021-03-25_16-56-34](https://user-images.githubusercontent.com/25563221/112503391-296e5800-8d8b-11eb-827d-b88958f73a9b.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/z2Lsmbpt/2/

#### Product version
Highcharts 9.2.0

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Hi @diogen737 

Thank you for reporting the problem.

You have changed the chart's border options and not the plot area border options. Neither one of them affect the clipping of the chart or series plot - those are options for the background of the chart or plot area.

One way could be to set CSS border-radius for the SVG and adjust the position of the legend (`colorAxis` is inside of it) and credits. Tooltip might sometimes land on an edge or so close that it gets clipped, so tooltip could be set to `outside: true`.
Demo: https://jsfiddle.net/BlackLabel/74xtks1L/1/

This issue is not a bug, so it will be closed but feel free to comment in case of further questions.
For technical support see https://www.highcharts.com/blog/support/
