### ISSUE TITLE
Boxplot charts : On deselecting legends, x axis categories don't readjust

### ISSUE THREAD

**Issue by hokage29** [highcharts/highcharts#15429]
#### Expected behaviour
For box plot charts with series separated out to show legends for individual datasets (representing each candle stick), if we try to deselect any legend, the corresponding candlestick should be hidden along with it's x-axis category and both should reappear on selecting back. This is useful for scenarios where the categories are string values and often match the legends.

#### Actual behaviour
Instead, if we try to deselect a particular legend in the middle of the series, the corresponding candlestick is hidden successfully but the x axis category linked to it still remains and shows an empty space in between (and so on for deselecting others). This issue is for all the legends except for the ones at either ends.
Ideally, the categories should readjust like in the case for the legends at the ends.

#### Live demo with steps to reproduce
template: https://jsfiddle.net/hokage29/odm73p5x/6/
Steps: Deselect Feb, Mar and Apr sequentially in the above example. Jan and May works fine.

**Comment by KacperMadej** [comment]
Hi @hokage29 

Thank you for reporting the problem.

This looks like a feature request, so I will add the proper label to the issue.

Short description: auto-hide empty categories.

Solution/workaround: Use names instead of x values for the points and toggle data when visibility is toggled (legend item clicked). Demo: https://jsfiddle.net/BlackLabel/juy7tcz6/
