### ISSUE TITLE
Cannot add image or icon in menu item since Highcharts 9.0.0

### ISSUE THREAD

**Issue by jasonclg** [highcharts/highcharts#15449]
#### Expected behaviour
Image/icon was allowed to be added in the menu item in Highcharts 8.2.0.

#### Actual behaviour
It's no longer supported. HTML tags will be converted to text.

#### Live demo with steps to reproduce
https://jsfiddle.net/5sra4ufe
In HTML, comment line 1&2 and uncomment line 3&4 to compare the behavior in Highcharts 8.2.0.

#### Product version
Highcharts [9.0.0, 9.0.1]

**Comment by KacperMadej** [comment]
A workaround, that might work for some cases, is to use CSS and prepend or append content - https://jsfiddle.net/BlackLabel/jpc4gard/2/

_Internal note:_
`useHTML` could be added

**Comment by wergeld** [comment]
I am not sure this should be a feature request. Using font awesome icons has been possible on highcharts menu options since version 5 at least. This is existing functionality that was removed in v9 without notice - would this not be a bug?

**Comment by jordandev** [comment]
Yeah this change broke our menus...

**Comment by KacperMadej** [comment]
The introduction of AST and a more strict, secure, and consistent approach to setting any texts in a chart caused this issue to show up. The fact this worked before was just a happy coincidence and was not by design. If HTML should be supported for something then there should be an option `useHTML` to enable it. Those are rather strong arguments for me and this is why the issue was label as a feature request. I am adding a regression label since this was working before.

I could change this into a bug if you are still more convinced that this is a bug and not a future request (please let me know in a comment). @wergeld

**Comment by wergeld** [comment]
@KacperMadej If this was done in effort for more security, I am all for it - our clients are state workforce systems and we tighten down a lot of our code as well. Put me in the camp of making this a feature. Having icons to represent what the graph buttons do is a great way to allow certain segments of the population with low/no reading skills to still use our systems. We have external export controls in HTML for each chart and use the export menu to handle things like sorting or setting the compare (for stock charts).

I am assuming there is no timeline for release of this so, in the meantime we will remove our FA icons from the menu items.
