### ISSUE TITLE
Refresh issue while scrolling highcharts gantt chart

### ISSUE THREAD

**Issue by sanoopsp** [highcharts/highcharts#15453]
I have created highcharts gantt chart with 200+ rows. The Y-axis labels/names are getting disappeared when I do vertical scrolling.

#### Expected behaviour
The Y-axis labels/names should be visible all the time

#### Actual behaviour
The Y-axis labels/names are getting disappeared on vertical scrolling
<img width="324" alt="GanttChart" src="https://user-images.githubusercontent.com/82077904/113818005-c7ebb780-9794-11eb-80df-c251d136fe9f.PNG">

#### Live demo with steps to reproduce
https://jsfiddle.net/Pratap_chauhan/2wn8g4ap/16/

Just do vertical scrolling.

#### Product version
"@angular/common": "~11.2.6",
"@angular/core": "^11.2.6",
"highcharts-angular": "^2.10.0",
"highcharts-custom-events": "^3.0.10",

#### Affected browser(s)
Chrome Version 89.0.4389.114 (Official Build) (64-bit)

**Comment by karolkolodziej** [comment]
_Internal note:_
Regression introduced in v8.2.2.
In 8.2.0 works fine: https://jsfiddle.net/BlackLabel/p2L8vh4m/

**Comment by sanoopsp** [comment]
We are using npm package ("highcharts-angular": "^2.10.0",) of highcharts 
Then what is the equivalent version on npm package.

**Comment by KacperMadej** [comment]
A partial workaround: remove `columns:[]` from `yAxis.grid` to get only some lines missing and keep all (at least this is what I got when testing) axis labels when scrolling up and down - https://jsfiddle.net/BlackLabel/wxsp8uma/

**Comment by sanoopsp** [comment]
> _Internal note:_
> Regression introduced in v8.2.2.
> In 8.2.0 works fine: https://jsfiddle.net/BlackLabel/p2L8vh4m/

It is worked. Thanks for your support.

**Comment by LMprasadkulkarni** [comment]
Hi @karolkolodziej @KacperMadej 
I am trying to create a gantt chart with a huge amount of data, currently it has approximately 2500 records , but in the future it may increase.

Issues that I am facing are as follows 

1. It takes almost 30 secs to 1 min to load the chart 

2. When click on any of the spans, I need to highlight the span as well as corresponding yaxis label , it takes almost similar time 

3. When I hover over spans , I need to highlight the span as well as corresponding yaxis label , It is also problematic , lags and doesn't work properly

4. When I expand or collapse any of the hierarchy, it should automatically adjust the height and should not take excess space, but it takes too much time to expand and collapse with such large volume of data

I have provided a sample example of JSFiddle , it does not have click and hover features , but you can judge the overall behaviour from expand collapse and load time
JSFiddle Link :- https://jsfiddle.net/w986qdno/9/

Now,
I tried one solution from my side where in yaxis options I provided max as some constant number and scrollbar options, it reduces the load time significantly because it creates only required number of yaxis labels in dom , also it reduces time required for click, hover, expand collapse operations times significantly but it has its own problems as follows,
1. When I Scroll using the highcharts scrollbar by clicking down or up arrow / click on scroll bar, sometimes it doesn't render some of the yaxis labels.
2. Mouse Wheel scroll doesn't work.
3. When I Collapse some non root hierarchy, it should bring yaxis labels up which were below the last visible label on screen,  but it doesn't 
4. scroll bar doesn't appear in jsfiddle (it was appearing on my local)
I have created JSFiddle for the above example also
JSFiddle Link :- https://jsfiddle.net/w986qdno/10/

Please have a Look and help me to solve the above issues.
the Main issue which is linked to the current issue is labels are missing on scroll
I am using following versions
"highcharts": "9.0.1"
"highcharts-react-official": "^3.0.0"
and it is still creating the same issue mentioned in above github link as well as similar issue is given in https://github.com/highcharts/highcharts/issues/15723 this open github issue.
--
Thanks and Regards
Prasad Kulkarni

**Comment by KacperMadej** [comment]
@LMprasadkulkarni 
This is not related to the reported bug.
Please contact technical support - https://www.highcharts.com/blog/support/

**Comment by LMprasadkulkarni** [comment]
I am using max in the yaxis option and on scrolling sometimes labels are missing, it was on of the above mentioned problem, thats why i added all the issues that I am facing currently

**Comment by KacperMadej** [comment]
Multiple issues should have multiple tickets - one for each. If you are unsure if a problem is a bug please contact technical support first. Have you tried the suggested partial workaround for this issue? If it doesn't work please post a minimal live demo for the problem and we will check if there is a workaround that could help for now - before a proper fix will be implemented.

**Comment by LMprasadkulkarni** [comment]
@KacperMadej I will make seperate issues for others, lets keep this issue for labels missing problem.
I have tried that partial solution and it does not work, here is the JSFiddle link for it https://jsfiddle.net/w986qdno/10.
Here I am using 'max' in yaxis options as well as I have added a 'scrollbar' also. But in JSfiddle the scrollbar for yaxis is not visible , which is visible on my local. when I scroll using that scrollbar sometimes it removes some labels from yaxis.

**Comment by LMprasadkulkarni** [comment]
I have updated JSFiddle with highcharts version 9.0.1 which I am currently using, in that yaxis scrollbar is appearing , but the label missing issue is still there on scroll. Can you please help me with this issue urgently? @KacperMadej @karolkolodziej here is the link of jsfiddle https://jsfiddle.net/yfow07Lb/

**Comment by KacperMadej** [comment]
The scrollbar is missing for axes in Gantt between v9.1.0-9.1.2 - scrollablePlotArea should be used instead.
API reference: https://api.highcharts.com/gantt/chart.scrollablePlotArea
Related PR that should fix the problem: https://github.com/highcharts/highcharts/pull/15898

Thank you for the above demo. Unfortunately, I am unable to find any workaround for this.
Maybe @karolkolodziej  will have more info.
