### ISSUE TITLE
center columns && multiple x-axis

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#15503]
#### Expected behaviour

The columns with the null values should be centered.

#### Actual behaviour

The `centerInCategory` doesn't work properly if the config includes multiple x-axis.

#### Live demo with steps to reproduce

Demo: https://jsfiddle.net/BlackLabel/4hs0d2yx/
It's easy to notice wrong positioning for the Feb and Mar categories.

**Comment by KacperMadej** [comment]
There is something wrong [with](https://jsfiddle.net/BlackLabel/4hs0d2yx/3/) or [without](https://jsfiddle.net/BlackLabel/4hs0d2yx/4/) `centerInCategory`.

Column series placed on different x-axes are placed and have widths based on all column series in the chart instead of using only the column series on the same x-axis. Notice the one overlapping category (2020 and Jan) that shows all column series - https://jsfiddle.net/BlackLabel/4hs0d2yx/6/

Also bad: stacking makes space for 2 stacks from 2 different x-axes - https://jsfiddle.net/BlackLabel/4hs0d2yx/5/

**Workaround**: add yAxis, clear groupPadding, and use centerInCategory - https://jsfiddle.net/BlackLabel/4hs0d2yx/8/

**Comment by Kanatorabo** [comment]
I've reached the limit with the workaround. There is more strange behavior with the reserved space. When I add a line series to this scenario the arrangement of the column is very strange (e.g Jun/Sep). 

Fiddle from above: https://jsfiddle.net/Kanatorabo/hakvse79/
Fiddle without the second Axis: https://jsfiddle.net/Kanatorabo/mLz7wd5s/5/
