### ISSUE TITLE
Highcharts column chart on iPad not receiving click

### ISSUE THREAD

**Issue by davidahopp** [highcharts/highcharts#1551]
Currently we are using Highcharts JS v2.3.5 (2012-12-19), on an iOS v6.1 device.

On the iPad, when using the column chart, the click event is not being properly triggered on the first click of the column. The first click triggers the mouseover, and a second click then triggers the click event.

I was able to reproduce this issue on the column demo page http://www.highcharts.com/demo/column-drilldown.

Thank you for looking into this,
David

**Comment by dipapazacharias** [comment]
I am using latest version of highcharts (6.0.7) and taping on legend item on iPad safari does not trigger 
plotOptions.series.events.legendItemClick properly (for example a series goes off and on immediately, instead of hiding, and vice versa). It works only on holding tap for a while, or with double tapping. Can you look into it, or is there a workaround?

**Comment by pawelfus** [comment]
Hi @dipapazacharias 

Could you recreate issue in jsFiddle? We will take check this.

**Comment by abuzaforfagun** [comment]
@dipapazacharias I am getting same problem with highchart 6.1.0

**Comment by KacperMadej** [comment]
Hi @abuzaforfagun 
Please recreate issue in jsFiddle, provide more info about the problem you have. This an old issue with a rather new comment (@dipapazacharias 's question) that seems to hit a dead end after Paweł's comment.
