### ISSUE TITLE
Draggable points way that user be able to drag the point into right-most part of X coordinate. The way it works in mobile UIs, when something is dragged over areas that has horizontal scrolls.

### ISSUE THREAD

**Issue by garagataya-pinedev** [highcharts/highcharts#15514]
Hello, our designer made a chart that should have 1500px and a horizontal scroll (as it doesn't fit within mobile screen obviously). You can see this situation in the code (https://jsfiddle.net/bkzyeod5/)

But this gets us to an issue with user experience. It would be cool if it worked this way: when user drag the point to the right edge of the screen, scrolling starts working automatically. The way that user be able to drag the point into right-most part of X coordinate. The way it works in mobile UIs, when something is dragged over areas that has horizontal scrolls.

I would appreciate an advice if this is possible at all?

**Comment by KacperMadej** [comment]
Thank you for submitting the feature request.

This is possible - PoC: https://jsfiddle.net/BlackLabel/k0n9g163/

Instead of the no-longer-maintained plugin, I have used the official module for draggable points.
Instead of scrolling the whole chart, I have used [`scrollablePlotArea`](https://api.highcharts.com/highcharts/chart.scrollablePlotArea).
For scrolling, in [`drag`](https://api.highcharts.com/highcharts/series.bubble.point.events.drag) function I am adjusting `chart.scrollingContainer.scrollLeft`.

Adjust panning/scrolling zone with `panZone` in JS line No.31 - in the demo set to `50`. This is a pixel margin that triggers the scrolling - the same for both the left and right sides.
