### ISSUE TITLE
same value stacks overlapping

### ISSUE THREAD

**Issue by python2911** [highcharts/highcharts#15581]
I'm not able to see all values. in my example I'm not able to see Joe's value.
Please find below fiddle for more details.

thanks in advance.

https://jsfiddle.net/17pchfsm/1/

**Comment by KacperMadej** [comment]
Hi @python2911 

If `minPointLength` is set to a high enough value it will cause points to overlap.
Here you cannot see any other than the last one - https://jsfiddle.net/BlackLabel/tzL16f9x/

A solution here could be to not use `minPointLength` for stacked data because of the overlap.

Another chart or series type might be a better fit for this type of data if you need to have all values shown.
- logarithmic axis: https://jsfiddle.net/BlackLabel/tzL16f9x/1/
- dual axes: https://jsfiddle.net/BlackLabel/tzL16f9x/2/ 

For technical support see https://www.highcharts.com/blog/support/
