### ISSUE TITLE
StockTools GUI doesn't render correctly in a wrapper with multiple charts

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#15593]
#### Expected behaviour
Inside wrappers add StockTools GUI the same as in the JS (same height as the chart with additional pagination).

#### Actual behaviour
Inside wrappers, StockTools GUI pagination is missing and it occupies too much space, which results in overlaping.

#### Live demo with steps to reproduce
Correct JS: https://jsfiddle.net/BlackLabel/g40s5vzo/
Angular: https://stackblitz.com/edit/highcharts-angular-stock-gui-5byr8x
Vue: https://codesandbox.io/s/highcharts-stockgui-tools-see-whats-happen-with-large-toolbar-20pbm
React: https://codesandbox.io/s/stocktools-gui-hrmbi

#### Product version
Highstock JS v9.0.1 (2021-02-15)

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
**Workaround:**
Add `chart` class name to the container, for example: https://stackblitz.com/edit/highcharts-angular-stock-gui-hgxywf?file=src%2Fapp%2Fapp.component.ts

Snippet:
```
<highcharts-chart
  [Highcharts]="Highcharts"
  [constructorType]="'stockChart'"
  [options]="chartOptions"
  class="chart"
>
</highcharts-chart>
```

*Internal note:*
The same happens when we remove the `chart` class name in jsFiddle demo: https://jsfiddle.net/BlackLabel/g40s5vzo/1/
