### ISSUE TITLE
Missing definitions in Chart.Legend

### ISSUE THREAD

**Issue by natc711** [highcharts/highcharts#15603]
#### Expected behavior
Show the type of all the property in Legend

#### Actual behavior
Does not show the type of all the property in Legend

#### Live demo with steps to reproduce
https://jsfiddle.net/n792e5fw/
You can see many properties in the console log of chart.legend
but only show minimal ones in actual documentation. Thus throwing errors in typescript.
![image](https://user-images.githubusercontent.com/60890905/116448104-ba22d280-a826-11eb-8e81-143296dc2c34.png)

#### Product version
highcharts 9.0.1
highcharts-react-official 3.0.0

**Comment by KacperMadej** [comment]
Hi @natc711 

Thank you for reporting the problem.

Not all properties of the Legend class are public and a part of the public API - this is by design.

If you need to customize the code you could extend the public API as explained in docs here: https://www.highcharts.com/docs/advanced-chart-features/highcharts-typescript-declarations#extending-highcharts-in-typescript
