### ISSUE TITLE
Highstock - Grouped X Categories Plugin Module not working with highstock - required highcharts to be defined error in browser console

### ISSUE THREAD

**Issue by roshniadatia** [highcharts/highcharts#15647]
#### Expected behaviour
Highstock should show grouped X categories similar to highcharts as the features of highcharts are in highstock. Currently unable to use highstock and highcharts in the same application when using this plugin

#### Actual behaviour

Using the following JS plug in: https://blacklabel.github.io/grouped_categories/grouped-categories.js with highstock.JS doesnt work. You need to include highcharts.JS in the code but then the following error appears: https://www.highcharts.com/errors/16/

Highcharts already defined in the page
This error happens if the Highcharts namespace already exists when loading Highcharts or Highstock.

This is caused by including Highcharts or Highstock more than once.

Keep in mind that the Highcharts.Chart constructor and all features of Highcharts are included in Highstock, so if using the Chart and StockChart constructors in combination, only the highstock.js file is required.

#### Live demo with steps to reproduce

https://stackoverflow.com/questions/67388638/highstock-group-x-axis-plugin-blacklabel-not-working-on-highstocks-library-hi

Error can be seen on the console browser. 
Seems to still work on JS Fiddle if I include the Highcharts.JS file as well but not during development locally. Error appears and chart does not populate: 
http://jsfiddle.net/MauricioSO2021/fc0pznvk/

Bug is - the plugin should only require Highstock.JS and still work. Shouldnt need Highcharts.JS if the features of highcharts are included in highstock.

#### Product version

Highstock.JS

<script src="https://code.highcharts.com/stock/highstock.js"></script>

#### Affected browser(s)
All Browsers

**Comment by raf18seb** [comment]
Hi @roshniadatia 

The error 16 occurs when you're loading both `highcharts.js` and `stock/highstock.js` modules. The Highcharts library is already included in Stock so there's no need to load `highcharts.js`. It is working fine with the Stock module only: https://jsfiddle.net/BlackLabel/opjqes4b/

Of course, the grouped-categories module works only with a categorized xAxis. When you are creating a stock chart (with a "stockChart" constructor), you can use only a datetime axis, so the grouped-categories module won't work. That's why you need to use the "chart" constructor. However, as I said before, you can still load the `stock/highstock.js` module that includes all the basic Highcharts features.
