### ISSUE TITLE
[Regression] Incomplete type definition for SVGRenderer

### ISSUE THREAD

**Issue by udinkar** [highcharts/highcharts#15668]
**Issue**
SVGRenderer class is missing the following members:
- g
- path
- text
- rect

Notes:
1) This is not a complete list of missing members. It seems like everything except the constructor definition is missing.
2) This issue was not present in v8.0.1. I believe, this is a regression somewhere between v8.0.1 and v8.1.1.

**Product version**
Highcharts v8.1.1

**Effects**
Typescript compilation errors

**Workaround**
Declaration merging on the highcharts consumer side

**Comment by KacperMadej** [comment]
Hi @udinkar 

Thank you for reporting the problem.

The list you have provided is a list of methods of SVGRenderer - e.g. [g](https://api.highcharts.com/class-reference/Highcharts.SVGRenderer#g).

I am not able to recreate the problem - please add a live demo with steps required to recreate the problem.

If the problem is not visible in a newer version of Highcharts then the solution will be to upgrade, so you might check a newer version of Highcharts too.

**Comment by udinkar** [comment]
Thanks @KacperMadej, this is a type definition issue only. No issue in the actual implementation.
I believe v9.1.0 doesn't have this issue. Thanks.
