### ISSUE TITLE
Highcharts chart.update method reorders data

### ISSUE THREAD

**Issue by atmgrifter00** [highcharts/highcharts#15697]
#### Expected behaviour

Calling 'chart.update' using the current set of options (including the series data) results in no change to the displayed data.

#### Actual behaviour

At least with series of type 'scatter' rendering with lines, calling 'update' with the same data Highcharts was initialized with will render completely differently (out of order data).

#### Live demo with steps to reproduce
Open the following demo:
[Update bug](https://codepen.io/atm_grifter/pen/RwpWrLr)

Note the way the data is rendered:
![image](https://user-images.githubusercontent.com/26874831/117713582-766f8780-b19b-11eb-9bc6-801ed311756c.png)

Now press the 'Use Update' button, which just calls 'update' with the current options. Note the way it is rendered:
![image](https://user-images.githubusercontent.com/26874831/117713715-a1f27200-b19b-11eb-9d18-10b3e03f1ada.png)

#### Product version
v9.1.0

#### Affected browser(s)
All?

**Comment by KacperMadej** [comment]
Hi @atmgrifter00 

This is because, due to optimization, when on update the series data is trying to update existing points by searching by x, and if doesn't find a match it adds a new point. After the points are added, the old points that were not updated are removed. This changes the order. On [series.setData](https://api.highcharts.com/class-reference/Highcharts.Series#setData) it is possible to disable point update (`updatePoints` flag in the function call argument). On `chart.update` there is no option to do the same. Another solution is to set `id` for each point, so they will be updated correctly (the search for the points to update prioritizes `id` over `x`) - demo: https://codepen.io/Blacklabel/pen/ExWKamE

Closing as answered question, but if you any further questions please let us know.

**Comment by atmgrifter00** [comment]
This seems less than ideal. To me, this means if I want to draw a circle (of possibly extremely high fidelity from a number of values perspective), that if I want to change the rendering from lines to points (trivially done using 'update'), I must either provide the data some arbitrary uniquifying identifier (a headache on its own, let alone memory bloat), or provide the entire data set again, which hasn't changed.

**Comment by KacperMadej** [comment]
> Why isn't the data, in its original order, maintained in the Highcharts current state?
It is. Series data is not even copied but used directly (for better performance with a bigger data set).

>  I would think a call to 'update' could recognize that the data isn't present, and just pull the data, in its original form, to use.
Yes, this happens when data is removed - in your demo it wasn't (the delete was commented).

In short: a series has data in the update, so let's go point by point and check if anyone needs to be added/removed/updated. Finding out if the point is the same is based on an order by `x` and scatter doesn't require and in your demo doesn't have data sorted by `x` in ascending order.

Would you like me to change the issue to a feature request about better scatter data update to avoid the problem you have described and count my previous answer as a temporary workaround before a proper feature will be implemeted?

**Comment by atmgrifter00** [comment]
I am totally fine with this being a feature request (or really just closing out, pointing to the workaround of just removing the data explicitly from the options), and it is _super_ minor, since, as you pointed out, when you use the line I had commented out in the demo, I get the behavior I want). Sorry, I should have included how trivial the workaround is, which seems like a totally acceptable thing to do. It's more of a discoverability problem than anything else for a user.

**Comment by TorsteinHonsi** [comment]
I am also undecided - I mean, probably our match-by-x algorithm isn’t optimal, as in this case I would expect all the points to be matched. It probably picks the first match over and over again, so subsequent points of the same X are always matche to the first existing X of that same point?
