### ISSUE TITLE
Incorrect text position in tooltip

### ISSUE THREAD

**Issue by balkarov** [highcharts/highcharts#15701]
This is reproduced when use the fontFamilty in tooltip.

#### Expected behaviour
![image](https://user-images.githubusercontent.com/6030335/117782711-8eeaab00-b24a-11eb-9432-9de135e2f0b7.png)

#### Actual behaviour
![image](https://user-images.githubusercontent.com/6030335/117782609-75496380-b24a-11eb-8228-8006843b884c.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/h4rqobu2/

#### Product version
Highcharts 9.1

#### Affected browser(s)
Google Chrome 89.0.4389.128

**Comment by TorsteinHonsi** [comment]
Demo broken down to the Renderer: https://jsfiddle.net/highcharts/ugvm5w8f/

@khlieng In the TextBuilder we already analyze the line height in order to get the SVG text layout right, so I have created a modified fix that caches the first line's height in that loop, and applies it in the `updateBoxSize` function. Should be more effective both in terms of performance and bytesize. Plus we can avoid visual diffs on the default tooltips, though there will be some legitimate diffs on non-default tooltips. Let's see how the visual tests go.

Demo with the fix applied: https://jsfiddle.net/highcharts/ugvm5w8f/1/
