### ISSUE TITLE
Text and Bar in Gantt chart is misaligned when scrolled

### ISSUE THREAD

**Issue by Sreejithga** [highcharts/highcharts#15723]
#### Expected behaviour
When scrolled in Gantt chart, scrolling should happen so that the bar and text aligns in the same line

#### Actual behaviour
When scrolled in Gantt chart, scrolling happens but the bar and text misaligns, kindly provide a solution for this, if you need a jsfiddle, I shall provide one.

#### Product version

Highcharts 8.0.0
#### Affected browser(s)
Chrome
![2021-05-16 09_35_05-Window](https://user-images.githubusercontent.com/53110553/118386806-12314580-b62b-11eb-9a06-9b52f3355120.png)

**Comment by KacperMadej** [comment]
Hi @Sreejithga 

Thank you for reporting the problem.

Please add a live demo.

**Comment by Sreejithga** [comment]
Hello, here is the JSFiddle link, I could not replicate the exact same issue that I reported here in the fiddle , but an other one which I'm facing in our environment as well. Text going hidden issue, only bar shows sometimes when you scroll. In the screenshot below, as you scroll, sometimes the text goes hidden like you dont see 'Project B' in the screenshot.

https://jsfiddle.net/sreejithga/pLba0w49/6/

![image](https://user-images.githubusercontent.com/53110553/120096390-3c5f2900-c13c-11eb-8a57-6a25f5c03fa5.png)

**Comment by KacperMadej** [comment]
Highcharts version before 8.2.2 had the issue you have reported originally and later it was fixed, but it seems like a new problem was added: https://github.com/highcharts/highcharts/issues/15453
If the referenced issue is the same then it would make this issue a duplicate. Please let me know if this issue could be closed as a duplicate or if you have more info.

**Comment by LMprasadkulkarni** [comment]
Hi @karolkolodziej @KacperMadej 
I am trying to create a gantt chart with a huge amount of data, currently it has approximately 2500 records , but in the future it may increase.

Issues that I am facing are as follows 

1. It takes almost 30 secs to 1 min to load the chart 

2. When click on any of the spans, I need to highlight the span as well as corresponding yaxis label , it takes almost similar time 

3. When I hover over spans , I need to highlight the span as well as corresponding yaxis label , It is also problematic , lags and doesn't work properly

4. When I expand or collapse any of the hierarchy, it should automatically adjust the height and should not take excess space, but it takes too much time to expand and collapse with such large volume of data

I have provided a sample example of JSFiddle , it does not have click and hover features , but you can judge the overall behaviour from expand collapse and load time
JSFiddle Link :- https://jsfiddle.net/w986qdno/9/

Now,
I tried one solution from my side where in yaxis options I provided max as some constant number and scrollbar options, it reduces the load time significantly because it creates only required number of yaxis labels in dom , also it reduces time required for click, hover, expand collapse operations times significantly but it has its own problems as follows,
1. When I Scroll using the highcharts scrollbar by clicking down or up arrow / click on scroll bar, sometimes it doesn't render some of the yaxis labels.
2. Mouse Wheel scroll doesn't work.
3. When I Collapse some non root hierarchy, it should bring yaxis labels up which were below the last visible label on screen,  but it doesn't 
4. scroll bar doesn't appear in jsfiddle (it was appearing on my local)
I have created JSFiddle for the above example also
JSFiddle Link :- https://jsfiddle.net/w986qdno/10/

Please have a Look and help me to solve the above issues.
the Main issue which is linked to the current issue is labels are missing on scroll
I am using following versions
"highcharts": "9.0.1"
"highcharts-react-official": "^3.0.0"
and it is still creating the same issue mentioned in above github link as well as similar issue is given in https://github.com/highcharts/highcharts/issues/15723 this open github issue.
--
Thanks and Regards
Prasad Kulkarni

**Comment by KacperMadej** [comment]
@LMprasadkulkarni 
I have replied to your other comment with the same content. Reposting like this will be considered spam - please avoid this.

**Comment by KacperMadej** [comment]
Closing the original issue due to inactivity.
