### ISSUE TITLE
the columns will have a rounded bevel shape for stackedbar

### ISSUE THREAD

**Issue by vidyaflorency** [highcharts/highcharts#15763]
# Description of the feature
Stacked columns color scheme and shape:

Color scheme: each stacked column will be a shade of blue, whereas the bottom column will be darker and each column stacked above will have a lighter shade of blue than the previous one.

Avoid colors schemes that might compromise the document’s legibility when printed in black & white.

Shape: the columns should have a rounded bevel shape.

# Library related to the feature
High Charts

# Proof of Concept/Live example for the feature

![Capture](https://user-images.githubusercontent.com/68862993/118987542-f89f3f00-b945-11eb-90fe-5dc6182d1075.PNG)

Very Important

**Comment by KacperMadej** [comment]
Hi @vidyaflorency 

Thank you for submitting the feature request, but it seems like this feature could already be achieved using existing chart options.

A rounded border could be used for bevel shape. Demo: https://jsfiddle.net/BlackLabel/tdp1y0wb/2/
API reference: [borderRadius](https://api.highcharts.com/highcharts/series.column.borderRadius)

For the colors, linear gradients could be used. Demo: https://jsfiddle.net/BlackLabel/tdp1y0wb/3/
Docs for more info: https://www.highcharts.com/docs/chart-design-and-style/colors#linear-gradients

**Comment by vidyaflorency** [comment]
Hi All,

The requirement is a Bavel-shaped stacked bar chart. I need bavel shape can
you please help me with this.

*Thanks & Regards*

*K.Vidya Florency*

**Comment by KacperMadej** [comment]
This exact style is not available - but this seems like a good enough reason to keep this feature request open.

You could get close to the design with some overlapping gradients from partially transparent copies (I was not able to get close enough to create a decent demo for this) of the same series or you could try getting this style through [filters](https://www.highcharts.com/docs/chart-design-and-style/gradients-shadows-and-patterns).

It's hinted on [SO that the filters might do the trick](https://stackoverflow.com/questions/40652940/svg-bevel-effect-for-all-edges).
