### ISSUE TITLE
Match a compare percent y axis [left] to the price y axis [right]

### ISSUE THREAD

**Issue by t-cardozo** [highcharts/highcharts#15821]
# Description of the feature
I want to be able to have a compare percent left y axis and price right y axis.

# Library related to the feature
Highcharts Stock

# Proof of Concept/Live example for the feature
I've managed to get it to add 2 candlestick series, 1 for price and 1 for percent compare and assigned the each to their own y Axis, to achieve this result.
https://ibb.co/VwTPW9T

Tried my best to replicate the code, but it's not overlapping here in the jsfiddle example for some reason.. https://jsfiddle.net/5zrhc80a/11/

While this works perfectly fine on my codebase, the real problem starts when I start adding other series like bb's
https://ibb.co/rwhcZwL

As you can see, the scaling starts messing up. I am not sure if my workaround is the right way to approach this problem. I've also tried adding the data to bb series instead of using linkedTo but then the params stop working.. i've noticed this happening to other series as well, the params only work when linkedTo is used for some reason.

I hope this helps, please let me know if I can provide any other info, i also posted here waited a few days before coming here.
https://www.highcharts.com/forum/viewtopic.php?f=12&t=46644

Thank you
Troy

----

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by KacperMadej** [comment]
Hi @t-cardozo 

Thank you for submitting the feature request.

The main problem is caused by the y-axes trying to align by default. `chart.alignTicks` should be set to `false`.
The next issue is that the values of the axes might be of different values and ticks will not be picked in the same way causing different axis range - this could be prevented by setting `startOnTick` and `endOnTick` to `false`.
The last serious obstacle here seems to be for me the `gridLines` overlap - fixed by disabled lines (line in your images) or by using a different color.

Demo: https://jsfiddle.net/BlackLabel/zch9s6yw/

Notes: the main series is still duplicated (although hidden) so this is not an optimal solution performance-wise.

**Comment by t-cardozo** [comment]
Hi @KacperMadej
Thank you very much for responding, 
Unfortunetly i've tired all the things you have suggested, but it doesn't solve the problem with i start adding bollingers/ma etc. 

please look at this example you've made as i've purposely unhidden the hidden candlestick, as you can see the overlapping isn't right.. If you zoom in you can see the overlapping is very off in some places.
https://jsfiddle.net/du8jaLr3/5/

I've also tried creating an new axis and assigning the bollinger to that but i had similar results.. 

Thanks
Troy

**Comment by pawelfus** [comment]
Hi @t-cardozo 

Thanks for the details!

I think we can implement this in a bit different way. I assume you only want to display additional yAxis with a crosshair label, right? If that's the case, instead of duplicating dataset, I suggest creating an additional yAxis, which will be linked to the first one. Then modify what's rendered in labels and crosshair, something like this: https://jsfiddle.net/BlackLabel/6c394ny8/

The only requirement is `crosshair.snap: false` (`true` requires real points). What do you think?

**Comment by t-cardozo** [comment]
Hi @pawelfus
Thank you so much for the reply and your solution worked wonderfully!
However one final thing though, while it does behave as intentional, the axis labels aren't similar to how compare percent works..

I was hoping to see the 0% at all times.
![image](https://user-images.githubusercontent.com/42764828/120478081-d13d7d00-c3ef-11eb-95d5-0af08950c926.png)

My colleague suggested I use your method but reverse it, so instead of working with price axis and creating a percent axis, i do the opposite.. Do you think this will work? or is there something else I can do?

I highly appreciate you all taking your time to help me with this matter!

Regards
Troy

**Comment by pawelfus** [comment]
Thanks, great to hear it works!

That's correct, you can swap the logic here. Start with `compare`, then create price yAxis. I think this is the easiest solution right now

> I was hoping to see the 0% at all times.
You can add `0%` using `tickPositioner`, for example: https://jsfiddle.net/BlackLabel/6c394ny8/4/ - but as you can see, this will cause labels to overlap.

> is there something else I can do
You can completely replace build-in `tickPositioner` to calculate nice, round ticks, take a look: https://jsfiddle.net/BlackLabel/6c394ny8/5/ - as you can see, now the ticks won't align. You can disable lines for the left axis to increase the readability. If you want to align them, then we go back to the solution that Kacper explained

**Comment by t-cardozo** [comment]
Thank you so much pawelfus!

The second solution you have suggested should be perfectly fine, as long as the crosshair is aligned I have no problems!
Thank you so much for taking the time to make all those fiddles.

Also thanks for trying KacperMadej
Regards
Troy
