### ISSUE TITLE
When updating options in state, no data text color does not update

### ISSUE THREAD

**Issue by kwin555** [highcharts/highcharts#15842]
#### Expected behaviour

![image](https://user-images.githubusercontent.com/30914512/120860017-aa478e00-c54a-11eb-9d50-5206e5a3d464.png)
![image](https://user-images.githubusercontent.com/30914512/120859861-6fddf100-c54a-11eb-86cc-e01ec2b462df.png)

#### Actual behaviour

![image](https://user-images.githubusercontent.com/30914512/120860123-cf3c0100-c54a-11eb-8b1c-9db56a2df8d0.png)
#### Live demo with steps to reproduce

![image](https://user-images.githubusercontent.com/30914512/120859980-9865eb00-c54a-11eb-9dac-5d8e301ec173.png)

#### Product version
react wrapper 3.0.0

#### Affected browser(s)
chrome

**Comment by raf18seb** [comment]
Hi @kwin555!

Seems to work fine in the newest Highcharts (9.1.1): https://stackblitz.com/edit/react-tfbyhx?file=index.js
There was a bug, but it's fixed since 8.2.0. Please, double check whether you are using the newest Highcharts version (or any version higher than 8.2.0).

Working demo: https://stackblitz.com/edit/react-tfbyhx?file=index.js
