### ISSUE TITLE
Highstock Bollinger Bands broken in compare mode 'percent'

### ISSUE THREAD

**Issue by muenchto** [highcharts/highcharts#15867]
#### Expected behaviour
Bollinger Bands should make sense in compare mode 'percent' i.e. have middle line and top/bottom lines forming a band around the original data.

#### Actual behaviour
Bollinger Bands move the bottom and top lines  in compare mode 'percent' a lot above the original data, making no sense at all.

#### Live demo with steps to reproduce
This is the official example for bollinger bands, I only added the plotOption 'compare: 'percent'': https://jsfiddle.net/qsa8o4hf/3/

#### Product version
highcharts stock
"highcharts": "^8.2.2",
"highcharts-angular": "^2.9.0",

#### Affected browser(s)
Chrome Version 91.0.4472.77

**Comment by raf18seb** [comment]
Hi @muenchto, thanks for reporting the problem.

**Comment by karolkolodziej** [comment]
_Internal note:_
The other lines are not visible because the `MultipleLinesMixin` `translate` method only calculates the values for the main line. Adding the `modifyValue` function for each line point solves the issue.

However @muenchto as we dive deeper into that issue fundamental questions arise. 
To which value, each point should be compared?

1. Top and bottom-line points are compared against the first visible points from the middle line.
Demo: http://jsfiddle.net/BlackLabel/e7Ld9xpr/

2. Each line point is compared to its' first point.
Demo: http://jsfiddle.net/BlackLabel/5yvu2g1c/

3. Or maybe it should work differently?

I was wondering if you could help us decide which approach makes the most sense.

**Comment by muenchto** [comment]
Thanks @karolkolodziej  for taking care of this bug! We really appreciate it.

I consulted with subject matter experts and they advised to use option one.
