### ISSUE TITLE
Base series not computed before indicator series

### ISSUE THREAD

**Issue by govinda18** [highcharts/highcharts#15892]
#### Expected behaviour
Base series should always be computed before indicator series - https://jsfiddle.net/8uvr5kLq/2/

#### Actual behaviour
If the indicator series is passed before base series, it is mis-computed -https://jsfiddle.net/8uvr5kLq/1/. This might be problem when nesting level is increased, or an indicator is linked to multiple series (for example diff).

#### Live demo with steps to reproduce
Shared above

#### Product version
Highstock JS v9.1.1

#### Affected browser(s)
Chrome

**Comment by KacperMadej** [comment]
Hi @govinda18 

My apologies for the late reply.
Thank you for reporting the problem.

Linking to multiple series is not implemented, so it might cause issue - more info in https://github.com/highcharts/highcharts/issues/15881

(fyi: @raf18seb - related / duplicate / any comments?)

**Comment by raf18seb** [comment]
Hi,

I don't see any reason why this should be implemented. It is enough to change the order of the series (like in the demo in the first post).

I am closing the ticket now, but feel free to reopen with a comment describing why we should implement this and why taking care of the series order is not enough.

**Comment by pawelfus** [comment]
> Maybe @pawelfus would have more insights about it?

That is expected behaviour (see console warning in the second demo). However, there's a chance we can improve this. Right now, series are linked on init, then recalc-events are bound to the linked parent. If the linked parent is not found, we assume the series is missing. I see two potential solutions here:

1. Attach recalc-events on `afterLinkSeries` event (and remove `linkSeries()` from indicators init). This event may happen multiple times, but attach this only the first time linked parent is found. This shouldn't affect performance, either initial calculations (if necessary).
2. If the linked parent series is not found, create an event to listen to when all series are initialized. Then run the same logic as in `indicator.init()` to try again. 

Let me reopen the ticket, we will check if one of the options will be suitable. 

Note: The same problem has `flags` series (linked parent must be defined before `flags` series, otheriwse flags will be rendered on Axis).
