### ISSUE TITLE
Spline chart dataLabel overlapping when the value is similar.

### ISSUE THREAD

**Issue by gooners006** [highcharts/highcharts#15994]
#### Expected behaviour
If the value is similar and allowOverlap:false, the other labels should be display, not hidden

#### Actual behaviour
The other labels is hidden 

#### Live demo with steps to reproduce
 series.data[series.data.length - 1].dataLabels = {
                 allowOverlap: false,
                 enabled: true,
                 align: "left",
                 verticalAlign: "middle",
                 overflow: true,
                 crop: false,
                 x: 3,
                 formatter: function() {
                     // return `<span style="color:${this.color};padding:10px;margin:10px">${this.series.name}`;
                     // return `<div align="center" style="padding-left: 0.20em; padding-right: 0.20em; padding-bottom: 0.30em; padding-top: 0.35em; background-color: rgba(255,255,255,0.6); border: 0.05em solid ${this.color}; line-height: 17px; border-radius: 0.5em; color: ${this.color}; font-weight: 400; font-size: 20px;">${this.series.name}</div>`;
                     return `<div style="display:flex"><div align="center" style="padding-left: 0.20em; padding-right: 0.20em; padding-bottom: 0.30em; padding-top: 0.35em; background-color: rgba(255,255,255,0.6); border: 0.05em solid ${this.color}; line-height: 17px; border-radius: 0.5em; color: ${this.color}; font-weight: 400; font-size: 10px;">${this.series.name}</div><span class="spanny" style="color:${this.color};padding:10px;margin:10px"></div>`;
                 },
             };

![image](https://user-images.githubusercontent.com/37095499/124441726-2d584000-dda6-11eb-8ec8-0ed226408e31.png)

#### Product version

Highchart 9.1.2
#### Affected browser(s)
Chrome

**Comment by raf18seb** [comment]
Hi @gooners006,

If you want to show both dataLabels (even when they overlap), you should set the `allowOverlap` property to `true` instead of false.
If your dataLabels are close, but they don't visually overlap, you can decrease its padding to make them less sensitive.
More info: https://api.highcharts.com/highcharts/series.spline.dataLabels.allowOverlap

GitHub is our bugs and features tracker only so, in case of any further questions, please continue on other dedicated support channels, more info: https://www.highcharts.com/blog/support/
