### ISSUE TITLE
Data Compression Support - Base Date to Shorten Timestamps

### ISSUE THREAD

**Issue by aionescu-zz** [highcharts/highcharts#1602]
Highcharts can "compress" very well the data by using "regular intervals" for time series (since only the start timestamp and the interval is required).

The problem is with irregular intervals :(.

Please add support for "Base Date to Shorten Timestamps".
See an example how AnyChart is doing it:
http://www.anychart.com/products/stock/docs/users-guide/index.html?data-set-input-data-settings.html#timestamp-units-cuttting

It's very efficient, and it cuts for many of our charts the transferred data to ~70%.

Thank you very much.

**Comment by oysteinmoseng** [comment]
This is still a relevant enhancement, as `pointStart` only takes effect if no x values are provided.

**Comment by aadrian** [comment]
@TorsteinHonsi IMHO automatically closing issues by bot scripts is not very nice :( .

**Comment by pawelfus** [comment]
Hi @aadrian 

Sorry for that! In general, for enhancements I suggest to use our [UserVoice](https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api) - the most popular ideas have higher chance to get into the core (or as a plugin) than old tickets (2013) from github.

**Plugin:**
Demo: http://jsfiddle.net/BlackLabel/q639d1bj/

API: 
Requires `pointIntervalUnit` option **without** `pointInterval`:
```js
  series: [{
    data: [
      [1, 1],
      [3, 3],
      [5, 2],
      [11, 4]
    ],
    pointStart: Date.UTC(2013, 5, 1),
    // Supported formats:
    // - millisecond
    // - second
    // - hour
    // - day
    // - month
    // - year
    pointIntervalUnit: 'day'
  }]
```

Plugin:
```js
(function(H) {
  H.Series.prototype.autoIrregularIncrement = function(point) {
    var options = this.options,
      time = this.chart.time,
      pointIntervalUnit = options.pointIntervalUnit || 'millisecond',
      x = H.pick(options.pointStart, 0),
      irregularName = {
        'day': 'Date',
        'month': 'Month',
        'year': 'FullYear'
      } [pointIntervalUnit],
      fixedTime = {
        millisecond: 1,
        second: 1000,
        minute: 60 * 1000,
        hour: 3600 * 1000,
      } [pointIntervalUnit],
      date;

    if (fixedTime) {
      x += point.x * fixedTime;
    } else if (irregularName) {
      date = new time.Date(x);
      time.set(irregularName, date, time.get(irregularName, date) + point.x);
      x = date.getTime();
    }

    return x;
  };


  H.wrap(
    H.Point.prototype,
    'applyOptions',
    function(proceed, options, x) {
      var point = proceed.apply(this, [options, x]),
        series = point.series,
        seriesOptions = series.options;

      if (
        H.defined(seriesOptions.pointIntervalUnit) &&
        !H.defined(seriesOptions.pointInterval)
      ) {
        if (typeof x === 'undefined') {
          point.x = point.options.x = series.autoIrregularIncrement(point);
        } else {
          point.x = x;
        }
      }

      return point;
    }
  );
})(Highcharts);
```

*Internal note:*
Can be implemented in a similar way in core (just modifying `autoIncrement` instead of creating new method).

**Comment by TorsteinHonsi** [comment]
@aadrian 
> IMHO automatically closing issues by bot scripts is not very nice :( .

I agree this is not fortunate, and ideally we would have the time to regularly go over all older issues and handle them manually. But that's a huge task. So we have made the bot as friendly as we could, as you see it only enters a notification the first time, then any comment or action of the issue will prevent the bot from closing it.

**Comment by aadrian** [comment]
@TorsteinHonsi any news on this issue? Browsers do not get as fast as the amount of data grows each year, and this feature would really have the biggest impact on cutting the transfered data.

**Comment by TorsteinHonsi** [comment]
Hey @aadrian , I think I found a nice way to do this with minimal overhead and a comprehensive API change. Just added a setting, `pointStartAsBase`, that instructs the Point and Series that X values should be relative to `pointStart` instead of absolute. This way backwards compatibility is kept too. The incrementation is also subject to `pointIntervalUnit`, allowing for maximum compression of the data.

See the [live demo](https://jsfiddle.net/highcharts/pa7zxy9h/).

What do you think?

**Comment by aadrian** [comment]
> What do you think?

@TorsteinHonsi it looks fantastic, but if I see correctly, it can compress **only** regular intervals (plus missing values) ?

See http://6.anychart.com/products/stock/docs/users-guide/data-set-input-data-settings.html#timestamp-units-cuttting how that trick allows irregular intervals "inside the mask" or "interval unit" _(highlighted with red)_ .  

_Using their approach we stream MBs of data, e.g. as CSV to a chart (without the need of complicated serverside or clientside logic)_

**Comment by TorsteinHonsi** [comment]
> but if I see correctly, it can compress only regular intervals (plus missing values) ?

Maybe I am misunderstanding here, but the [live demo](https://jsfiddle.net/highcharts/pa7zxy9h/) demonstrates irregular intervals (weekdays only, skipping weekends). That's the whole idea of the new option, because regular intervals are already supported by `pointStart`, `pointInterval` and `pointIntervalUnit`.

**Comment by aadrian** [comment]
> Maybe I am misunderstanding here, but the live demo demonstrates irregular intervals (weekdays only, skipping weekends).

On a first sight, to me the example was looking like a regular interval with missing data support :) .
 
If I change the type to "**line**" in your example, than indeed it's visible: the dots are connected - this is fantastic !
