### ISSUE TITLE
Highstock rangeSelector not showing selected button if navigator false and xAxis endOnTick true

### ISSUE THREAD

**Issue by TheBryanMac** [highcharts/highcharts#16050]
#### Expected behaviour
With a config combination of config properties: navigator enabled is false AND the xAxis endOnTick true. The Range Selector buttons should show which button is currently selected. And when selecting a different button (user interactively) it should highlight the button as active.

#### Actual behaviour
If the config options are: navigator enabled is false AND the xAxis endOnTick true. This unique combination seems to disable the visual button selection but it still does have the correct one selected. Selecting buttons interactively will also not highlight (but does still change the range).

`navigator: {enabled: false}, xAxis: {endOnTick: true}`

#### Live demo with steps to reproduce
https://jsfiddle.net/fjux4zp6/

#### Product version
Highstock 9.1.2

#### Affected browser(s)
Chrome, Edge

**Comment by raf18seb** [comment]
Hi @TheBryanMac, thank you for reporting the problem.

Simplified demo: https://jsfiddle.net/BlackLabel/jeL3rzpv/

**Comment by kamil-musialowski** [comment]
I'm not entirely sure whether it should be classified as a bug. 
When we set the endOnTick to true (which is only possible when we disable the navigator, so that the endOnTick option is not forced to be false), then we force Highcharts to always end xAxis on tick - which sometimes may lead to extending the xAxis to a longer period, rather than only 3 months, 6 months, etc. - depending on the actual data.

Therefore, the functionality of showing the desired period by clicking on rangeSelector options works fine, however, I don't think it would be the right decision to set the button state to active, since the true xAxis range may be for example 6 months and 2 weeks if the endOnTick is enabled.

@pawelfus Could you please share your thoughts about this one?

**Comment by pawelfus** [comment]
I don't see a great solution for this. `endOnTick` option extends the axis, then the button checks the extremes if it should get the selected state. Because the `endOnTick` option extremes don't match, we don't set the selected state. The same happens when you select 6m and then resize the browser:
![endontick](https://github.com/highcharts/highcharts/assets/1453926/561caa1f-4d29-4e1a-81e4-6f4bc51b4e07)

**Comment by kamil-musialowski** [comment]
Thank you for the insight. In that case, I would vote for the "not a bug" status.
