### ISSUE TITLE
Panning on ordinal Axis is broken

### ISSUE THREAD

**Issue by pawellysy** [highcharts/highcharts#16068]
#### Expected behaviour
When panning, everything should be smooth. 

#### Actual behaviour
Panning causes some strange behaviour, including fireing the dataGrouping. 

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/d1ps4n3g/
Try to pan to the right (towards higher values)
#### Product version
v9.1.2
#### Affected browser(s)
all

**Comment by jackytanjq** [comment]
Hello,
Can I know if there are any updates for this issue?

Because it seems like this is related to this issue I have at the moment:
[https://www.highcharts.com/forum/viewtopic.php?f=12&t=50766](url)

Was wondering if there is a fix or workaround to solve the issue.

**Comment by pawelfus** [comment]
Let me prioritize the issue. I'm not able to predict the ETA, but we will try to come up with a workaround in the first place.

Meanwhile, could you try enabling [`dataGrouping.groupAll`](https://api.highcharts.com/highstock/series.candlestick.dataGrouping.groupAll) option? Perhaps it will help with dataGrouping behaviour (panning still might cause issues).

**Comment by jackytanjq** [comment]
Just tried enabling [`dataGrouping.groupAll`](https://api.highcharts.com/highstock/series.candlestick.dataGrouping.groupAll) in the JSFiddle below:
[https://jsfiddle.net/jackytanjq/m0kfw7n1/1/](url)

It appears to have somewhat improved the scrolling but still not consistent.
Will use this in the meantime. 

Thank you.

**Comment by pawelfus** [comment]
*Internal note:*
It works even better with WiP for other bug: https://jsfiddle.net/BlackLabel/ovtk1qzd/ - perhaps the last thing to check is whether the number of moved units is correct. My guess is approximation loses its effectiveness when pointRange is ~5min, and the gaps are counted in hours. Needs further debugging

**Comment by jackytanjq** [comment]
Thank you for the workaround @pawelfus.

Just tested the workaround on Highstock JS v9.3.2 (2021-11-29).
Replaced this: 
`H._modules['Core/Axis/NavigatorAxisComposition.js'].prototype.toFixedRange`
With this:
`H._modules['Core/Axis/NavigatorAxis.js'].AdditionsClass.prototype.toFixedRange`

The number of candlesticks while panning is now much more consistent _(may fluctuate by 1 candlestick)_.
But **when panned to the extremes of the X-axis**, the number of candlesticks may increase and stays that way until the zoom is changed.

Overall this fix has helped to solve the main issue but not perfect.
Because in our system, we will show the current number of candles to the user and they can visually see the number of candlesticks changing as they pan around the chart.

Example below:
[https://jsfiddle.net/jackytanjq/4o7nrm18/](https://jsfiddle.net/jackytanjq/4o7nrm18/)
![PanCht_NumCandle_Inconsistent](https://github.com/highcharts/highcharts/assets/7489622/7beb7ff1-cb80-45be-8876-4b1aea6435a3)

**Comment by pawelfus** [comment]
Hi @jackytanjq 
Thank you for the details. Our panning does not promise the number of points in `points` array will be constant. I can improve it, to apply panning only when the mouse move changes extremes at least by one candle, something like this: https://jsfiddle.net/BlackLabel/0Lbncaed/ 

Note: I recommend using `xAxis.afterSetExtremes` to check the number of points. And check only visible points (see changes in config). The number of points still can vary at the ends, though.

**Comment by jackytanjq** [comment]
Hello @pawelfus ,
Thank you very much for the prompt fix!
