### ISSUE TITLE
Replace moment.js with something more modern.

### ISSUE THREAD

**Issue by annitya** [highcharts/highcharts#16070]
# Description of the feature
moment.js is a bit [eol-ish](https://momentjs.com/docs/#/-project-status/).
Have you considered upgrading to something a bit more modern?

# Library related to the feature

moment.js

----

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by KacperMadej** [comment]
Hi @annitya 

Thank you for submitting the feature request.

If "something more modern" will match the API of moment.js then you could set it up directly or with some additional interface through the existing option - https://api.highcharts.com/highcharts/time.moment

**Comment by RagingRoosevelt** [comment]
This seems like maybe a more serious issue now that moment.js is now in end-of-life?

**Comment by heklp** [comment]
DayJS is a almost drop-in replacement which maps to native-functionality. Might save some time :)

**Comment by annitya** [comment]
DayJS is a almost drop-in replacement which maps to native-functionality. Might save some time :)

**Comment by KacperMadej** [comment]
@annitya
Thank you for sharing this good alternative.

> If "something more modern" will match the API of moment.js then you could set it up directly or with some additional interface through the existing option - https://api.highcharts.com/highcharts/time.moment

DayJS works with the current code version - [demo](https://jsfiddle.net/BlackLabel/6mpjaLbc/).
The original demo for context - https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/time/gettimezoneoffset/

**Comment by TorsteinHonsi** [comment]
@annitya 
Just a little clarification - the `time.moment` option applies only if we are using the `time.timezone` option. [My PR](https://github.com/highcharts/highcharts/pull/20309) addresses that, so that moment.js is no longer required internally in Highcharts.

The `time.getTimezoneOffset` callback however is a different matter. It can use anything that returns the number of milliseconds of offset from UTC, including moment.js and DayJS like Kacper showed. Kacper's demo works without the `time.moment` option too: https://jsfiddle.net/highcharts/6w2vs9o3/
