### ISSUE TITLE
Map with overlaid pie charts is not working for Angular apps

### ISSUE THREAD

**Issue by kim-spotinst** [highcharts/highcharts#16078]
#### Expected behaviour
Running the example from your [map-pies demo](https://www.highcharts.com/demo/maps/map-pies) in an Angular 11 app

#### Actual behaviour
Getting errors:
Property **'seriesTypes'** does not exist
Type '{ mappie: { borderColor: string; borderWidth: number; tooltip: { headerFormat: string; }; }; }' is not assignable to type 'PlotOptions'. 
**I could not fine "mappie" under the PlotOptions in the documentation as well as under the series types.**

#### Live demo with steps to reproduce
[stackblitz demo](https://stackblitz.com/edit/highcharts-angular-map-4raknk?file=src%2Fapp%2Fapp.component.ts
)

#### Product version
`"highcharts": "9.1.2"`

**Comment by KacperMadej** [comment]
Hi @kim-spotinst 

For technical support see https://www.highcharts.com/blog/support/

The error is from TypeScript and you are using methods outside of the public API and TS definitions, so you could either add the missing definitions or cast to `any` to suppres the errors. Try unchecking the IVY in the sandbox options to get more info about the TS problems. It should be possible to run the code even if there are TS errors because the produced JS code should work. This is a bad practice as long as the functions or methods you are using are a part of API - this is not the case.

You are using `highcharts-angular` and yet you have not initialized the chart correctly - the setup for the charts container is not correct. Please compare with [a working demo](https://stackblitz.com/edit/highcharts-angular-map?file=src%2Fapp%2Fapp.module.ts) and in case of further questions reach out to our technical support as we are trying to use GitHub issues for bug reports (and feature requests).
