### ISSUE TITLE
Cannot augment Navigator in TypeScript

### ISSUE THREAD

**Issue by mediafreakch** [highcharts/highcharts#16094]
#### Expected behaviour

I'm referring to https://www.highcharts.com/docs/advanced-chart-features/highcharts-typescript-declarations#extending-highcharts-in-typescript .

From what I understand I should be able to do the following:

```
// NavigatorExtension.ts
import * as Highstock from "highcharts/highstock";

declare module "highcharts/highstock" {
  interface Navigator {
    showLoading(text: string): void;
    hideLoading(): void;
  }
}

Highstock.Navigator.prototype.showLoading = function (text) {
  const navigator = this;
  const chart = navigator.chart;
};

Highstock.Navigator.prototype.hideLoading = function () {};
```

#### Actual behaviour

Yields an error: `TS2339: Property 'Navigator' does not exist on type 'typeof import("...")'`

#### Live demo with steps to reproduce

https://codesandbox.io/s/cannot-augment-navigator-in-highstock-j982h

#### Product version

9.1.2

#### Affected browser(s)

\-

**Comment by KacperMadej** [comment]
Hi @mediafreakch 

Thank you for reporting about the problem.

The error is correct. Navigator is a Highcharts Stock feature (but also available in Gantt), so you need to import the correct module or a version of the Highcharts core already extended with the missing module (e.g. 'highcharts/highstock').

In case this doesn't resolve you problem please add a live demo.

**Comment by mediafreakch** [comment]
@KacperMadej  Thx for your response. I incorporated your feedback and updated the issue with a live demo because it still doesn't work.

**Comment by KacperMadej** [comment]
@mediafreakch 
I apologize for the long reply time and for not providing better info in my first comment.

`Navigator` is not a part of API, so it is not defined in TS. Here's a screenshot with the required changes and description below:

![image](https://user-images.githubusercontent.com/8960408/128382192-3f7ff94c-3de7-49e2-b05c-4d399d31ad35.png)

1. Use `class` instead of `interface` - you're later accessing `prototype`.
2. Module to declare is `"highcharts/highcharts"`. In the peeked TS definitions from the stock module's .d.ts file, the main module is extended so that one should be used even though you are trying to add a Stock class.
3. Since this is a new class all members/methods must be defined - added `chart`.

Please let me know if this helps with resolving the problem.

**Comment by mediafreakch** [comment]
Thank you, that worked.
