### ISSUE TITLE
Panning affects yAxis.endOnTick and yAxis.startOnTick

### ISSUE THREAD

**Issue by pawellysy** [highcharts/highcharts#16096]
#### Expected behaviour
Panning enabled shouldn't impact the height of the chart

#### Actual behaviour
When panning is enabled the chart is smaller, and doesn't fill whole element.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/L87uadqs/

#### Product version
v9.1.2

#### Affected browser(s)
all

**Comment by raf18seb** [comment]
The issue exists since v8.1.0 (vertical panning was added). Neither the chart's heights nor the plotAreas' sizes don't change - but the `yAxis.minPadding` and the `yAxis.maxPadding` change. `chart.margin` doesn't change anything.

Simplified demo: https://jsfiddle.net/BlackLabel/dy5rqg94/

@KacperMadej what do you think?

**Comment by KacperMadej** [comment]
It looks to me that `startOnTick` and `endOnTick` are affected: https://jsfiddle.net/BlackLabel/dy5rqg94/1/

As seen in code:
https://github.com/highcharts/highcharts/blob/72a8dcbb49a6f16e081717ae87969dde287363f0/ts/Core/Axis/Axis.ts#L5702-L5705

IMO docs should have more info about this issue

**Comment by ashleyryan** [comment]
Hello, I'm the original report of this issue on the forums. In my case, I actually want the vertical height behavior - is there a way to replicate it without using vertical panning once the issue is fixed?

It was unintentional, but we like the behavior of the chart taking up all vertical height. We don't care about panning in this instance, so happy to remove panning when this issue is resolved, but I would like to keep the behavior.

**Comment by raf18seb** [comment]
@ashleyryan so you would like the series and plotarea to fit as much as possible, right? In this case set `yAxis.minPadding: 0`, `yAxis.maxPadding: 0`, `series.clip: false` and optionally `chart.margin: 0` (or a small but positive number to see the markers that goes beyond the chart).

Is this what you have been trying to achieve?: https://jsfiddle.net/BlackLabel/yu3510kq

**Comment by ashleyryan** [comment]
Yes, exactly @raf18seb! I don't want the behavior to break when this panning issue is fixed, thank you!

**Comment by gustavoittner** [comment]
Hi, any update on this issue?
