### ISSUE TITLE
Tooltip lags when number of zones are large

### ISSUE THREAD

**Issue by rdp1414** [highcharts/highcharts#16138]
#### Expected behaviour
Tooltip shouldn't lag this much as it does in reproducer.

#### Actual behaviour
When number of zones are large (200 zones), there is significant lag in tooltip.

#### Live demo with steps to reproduce
Reproducer of above bug - See [fiddle](https://jsfiddle.net/ptmvua28/2/).

#### Product version
Highcharts version `9.1.2`

#### Affected browser(s)
Chrome

**Comment by raf18seb** [comment]
Hi @rdp1414, thanks for creating the ticket.

We have never thought about the need of improving the performance in zones because there is no practical use case of using 200 random zones in one graph. You'll get the same effect using just a few of them.

See the demo with 4 zones: 
![image](https://user-images.githubusercontent.com/23310742/128167645-715826ce-0db0-400f-924f-74384ace322d.png)

And a demo with 200 zones: 
![image](https://user-images.githubusercontent.com/23310742/128167694-0f301c5f-9f26-43c1-a3f9-c19d36a6cd43.png)

**Comment by TorsteinHonsi** [comment]
Hi again @rdp1414,

The reason for the lag is that for each zone, we are creating a copy of the graph with clipping set to the zone area. So in this case we end up with 200 paths and clips, resulting in a very complicated SVG and causing slow rendering. 

As Rafal pointed out, the Highcharts zones are not intended for dealing with this number of zones. May I ask what the use case is? Depending on the use case, an alternative approach would be to create a gradient for the series color: https://jsfiddle.net/highcharts/15kef7rb/

**Comment by rdp1414** [comment]
Hello @TorsteinHonsi,

Yes, having such large number of zones is an extreme use-case, so, the associated tooltip lag won't be much of a concern for us. And if at all we end up in such a rare situation, we will try to make gradient for series color alternative work.
