### ISSUE TITLE
X axis labels seem to take y values when number of data points are greater than 1000

### ISSUE THREAD

**Issue by rdp1414** [highcharts/highcharts#16137]
#### Expected behaviour
X axis labels should take correct category vales.

#### Actual behaviour
* X axis labels seem to take y values when number of data points are greater than 1000 - See [fiddle](https://jsfiddle.net/9zrhyapv/2/). 
* It mysteriously does work when 'x' key is explicitly passed - See [fiddle](https://jsfiddle.net/js5m69tp/). I couldn't find any references in highcharts documentation which can explain why this works.

I wish to know/understand the below points:
1. Is there any workaround with the first fiddle?
2. Why does passing `x` key explicitly works as shown in second fiddle?

#### Live demo with steps to reproduce
Mentioned above

#### Product version
Highcharts version `9.1.2`

#### Affected browser(s)
Chrome

**Comment by raf18seb** [comment]
Hi @rdp1414,

here is the answer: https://api.highcharts.com/highcharts/series.line.turboThreshold

Let's discuss this demo: https://jsfiddle.net/BlackLabel/Lkde4wvn/
```js
Highcharts.chart('container', {

  xAxis: {
    type: 'category',
    categories: [
      "AAA",
      "BBB",
      "CCC",
      "DDD",
      "EEE",
      "FFF",
      "GGG",
      "HHH",
      "III",
      "JJJ",
      "KKK"
    ]
  },

  series: [{
    keys: ['y', 'name'],
    turboThreshold: 10,
    data: [ // 11 values
      [0, "A0"],
      [2, "A1"],
      [4, "A2"],
      [6, "A3"],
      [8, "A4"],
      [10, "A5"],
      [12, "A6"],
      [14, "A7"],
      [16, "A8"],
      [18, "A9"],
      [20, "A10"]
    ]
  }]

});
```

In short, when we have 11 points and `turboThreshold` is set to 10, then `series.keys: ['y', 'name']` tells that numbers 0, 2, 4, 6, ... should be treated as `y`. However, in the same time, `turboThreshold` tells that the data array should be in format of `[x, y]`, so it takes numbers 0, 2, 4, 6, ... as x.

I wouldn't consider it as a bug. The simplest solution it setting `turboThreshold` to a higher number than the number of points. Another solution would be to define data in format `[x, y]` instead of `[y, name]` and define `xAxis.categories` array.

For further questions, please contact our support (GitHub is our bugs and features tracker only). More info: https://www.highcharts.com/blog/support/
