### ISSUE TITLE
Highcharts (styledMode): filter: url(#drop-shadow) not working

### ISSUE THREAD

**Issue by madepiet** [highcharts/highcharts#16147]
#### Expected behaviour
Correct operation of options / improved `defs` or documentation for `filter: url(#drop-shadow)`.

#### Actual behaviour
Highcharts Documentation: 
https://www.highcharts.com/docs/chart-design-and-style/gradients-shadows-and-patterns

_"For a simple drop shadow, the built-in `#drop-shadow` filter can be used."_
But when we try to apply `filter: url(#drop-shadow)` in CSS the `highcharts-graph` disappears.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/zp9287dy/

#### Workaround
Currently, it happens after initializing the chart, so after turning off the options for `glow`, then setting the options for a specific series (in the case of the following demo: `filter: url(# drop-shadow-0)`) - the series shows after hovering and rendering the tooltip: https://jsfiddle.net/BlackLabel/Law87bvm/

#### Product version
v9.1.2

**Comment by raf18seb** [comment]
Hi @madepiet,

The shadow filter isn't working because the defs for it are missing. See a working demo: https://jsfiddle.net/BlackLabel/4gdsxLkf

If you think that the docs article is unclear or a live example with shadow should be added there, please reopen the ticket and vote up (👍) this comment - we'll be happy to add it.
