### ISSUE TITLE
Error when using ES Module to create funnel or pyramid chart

### ISSUE THREAD

**Issue by alvarezguille** [highcharts/highcharts#16184]
#### Expected behaviour
Funnel chart is drawn

#### Actual behaviour
JS Exception
>Uncaught ReferenceError: Highcharts is not defined
    at obj.alignDataLabel (funnel.src.js:366)

https://github.com/highcharts/highcharts/blob/v8.1.2/js/modules/funnel.src.js#L366

#### Live demo with steps to reproduce
https://jsfiddle.net/alvarezg/rwb6e8s1/

#### Product version
Highcharts/Highstock + Funnel module
Versions 8.1.2-8.2.2

**Comment by KacperMadej** [comment]
Hi @alvarezguille 

Thank you for reporting the problem.

The issue was fixed somewhere between 8.1.2 and the current version (9.1.2) as the problem doesn't happen now: https://jsfiddle.net/BlackLabel/39mqj1fa/

The solution is to update to a newer version of code that has this issue fixed.
Closing as resolved.

**Comment by alvarezguille** [comment]
Thanks for the answer @KacperMadej 
We noticed that it was fixed in latest, and we are evaluating the upgrade to HC9 but so far we found that we are blocked by https://github.com/highcharts/highcharts/issues/15913
Could a fix for this be backported?

**Comment by KacperMadej** [comment]
@alvarezguille 
Yes, the problematic function could be overwritten to resolve the wrong reference to the unaccessible variable - demo: https://jsfiddle.net/BlackLabel/omzk8q32/
