### ISSUE TITLE
Tree Map : Data Point color is lost when point is selected and chart is redrawn

### ISSUE THREAD

**Issue by diipak-bisht** [highcharts/highcharts#16218]
#### Expected behaviour
Color provided for data point should be shown

#### Actual behaviour
Color is resetting to "Gray" for selected point when chart is redrawn

#### Live demo with steps to reproduce
https://jsfiddle.net/diipak/duqjgwx6/3/

#### Product version
v9.1.2

#### Affected browser(s)
all

**Comment by KacperMadej** [comment]
Hi @diipak-bisht 

Thank you for reporting the problem.

This is a bug because the colors from the series data options should not be used when `styledMode` is turned on.
For setting color in `styledMode` use CSS to set colors for the points as mentioned in [this API reference](https://api.highcharts.com/highcharts/series.treemap.color).

If you want to keep the colors in order after update then the number of points should match and when you call setData with [{}] you are adding an empty point that uses the color index and doesn't do much more.
Demo emulating as the chart should work (without the empty point): https://jsfiddle.net/BlackLabel/03sywemk/
Demo with used CSS to style the points: https://jsfiddle.net/BlackLabel/03sywemk/1/

The above demo should be a solution for your problem, but let's keep the issue open as the behavior visible here is a bug.
