### ISSUE TITLE
#13158 Issues on expand/collapse in highcharts ganttchart

### ISSUE THREAD

**Issue by debarghyawoodside** [highcharts/highcharts#16267]
#### Expected behaviour
Expand/Collapse should work fine in ganttchart

#### Actual behaviour
 There are two issues in the ganttchart.
This is my original gantt chart.
![Original](https://user-images.githubusercontent.com/68955318/131235767-8daf6d42-18bf-4e3d-a25b-17a53b1a9c88.png)

Now when I do a collapse & reexpand on the gantt chart the chart becomes corrupted.

Also the milestones do not show up again.
Please also check that just after collapse, the parent node is present,the milestones stopped coming in parent level but as uniqueNames are set as true, they should come in parent level before collapsing.
.

![Issue](https://user-images.githubusercontent.com/68955318/131235773-83ceaa4d-7b61-4e9a-9707-544941ae342e.png)

#### Live demo with steps to reproduce

Due to some security issue, I will not have access to jsfiddle...Please find the configuration & test data below.
[ganttChartConfig.txt](https://github.com/highcharts/highcharts/files/7071774/ganttChartConfig.txt)
[JsonOutput.txt](https://github.com/highcharts/highcharts/files/7071776/JsonOutput.txt)

#### Product version
Highcharts Version - 8.2.2

#### Affected browser(s)

All browsers

**Comment by raf18seb** [comment]
Hi @debarghyawoodside,

The .txt configs you provided are not enough to create your chart, see demo: https://jsfiddle.net/BlackLabel/shcqgmap/
To investigate the issue, we need a simplified demo showing it. Please, find a way to access the jsFiddle and provide more information.

**Comment by debarghyawoodside** [comment]
Please in your demo itself, the expand/collapse is not working.

This is the initial screen...

![image](https://user-images.githubusercontent.com/68955318/133366458-79730df8-a6b5-4074-89ad-c00e248e9393.png)

This is first time clicking on the collapse icon which is fine...

![image](https://user-images.githubusercontent.com/68955318/133366516-8de1028d-4e89-426c-a030-610cc06e1a0c.png)

This is again expanding the same element which corrupts the chart...

![image](https://user-images.githubusercontent.com/68955318/133366559-ecfa7e55-ccbe-4841-946e-a6683157856c.png)

Please look into it as it can be reproduced in your demo itself.

**Comment by raf18seb** [comment]
You're right, I was able to reproduce the issue in the above demo.
For the future - please, share simplified demos/code, because:
-  it saves our time (it's hard to debug and find the cause when the code or data is very extended)
- you can usually find a cause on your own during the simplifying process. Remove unnecessary code piece by piece and test whether the issue still occurs or not. This way, I was able to find the lines that caused your issue.

The problem is with the 2 data points with the same ids. See a simplified demo: https://jsfiddle.net/BlackLabel/erysk61h/
`PMO` points have the same id. When you define unique ids (ids should always be unique by definition), the chart is working fine.
Working demo: https://jsfiddle.net/BlackLabel/nyqxw48d/

Closing as resolved and not a bug.
