### ISSUE TITLE
Line chart y-axis range is not computed correctly if the data point values are large numbers with small differences

### ISSUE THREAD

**Issue by chihiroxc** [highcharts/highcharts#16275]
#### Expected behavior
Data points [238863224762451, 238863224762452, 238863224762453, 238863224762453] can be shown correctly.

#### Actual behaviour
Only the first data point is shown.
![image](https://user-images.githubusercontent.com/71873562/131466347-c40696d0-382d-4018-8d77-bcc415d1e0de.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/6dam1fjr/

#### Product version
Highcharts JS v9.2.2 (2021-08-24)

#### Affected browser(s)
Can be repro on Chrome/Edge, other browsers should be affected too.

**Comment by raf18seb** [comment]
Hi @chihiroxc, thanks for reporting the problem. Seems like a bug.

A little bit simpler demo: https://jsfiddle.net/BlackLabel/skx6frtj/

**Comment by KacperMadej** [comment]
The default precision is 14 and the numbers used are beyond the supported number precision.
Axis min and max are rounded to the same number - `238863224762450`.
There needs to be some room for the default tick positioner logic calulations so 14 is used instead of the JavaScipt Number precision limit.

If you need to work with numbers that big you might consider using tickPositions array or maybe a different axis type would work better. Some examples:
- categories: http://jsfiddle.net/BlackLabel/w7s4xgpt/
- label format: http://jsfiddle.net/BlackLabel/w7s4xgpt/1/

I am not sure if this is a bug in Highcharts because this is based on the JavaScript Number precision limit.
@TorsteinHonsi ?

**Comment by TorsteinHonsi** [comment]
@KacperMadej If I understand the issue correctly, this happens because we set 14 as the number precision in the `correctFloat` function? That means that we should probably not do this operation for numbers larger than a certain threshold, as it will correct the floats wrongly and basically throw out the baby with the bathwater.

This fix seems to work: 
```ts
function correctFloat(num: number, prec?: number): number {
    if (num > 1e14) {
        return num;
    }
    return parseFloat(
        num.toPrecision(prec || 14)
    );
}
``` 

https://github.com/highcharts/highcharts/blob/ddb0bcbad4433a1a4eb3607c05129d9b5cc69cae/ts/Core/Utilities.ts#L1142-L1146

**Comment by chihiroxc** [comment]
> The default precision is 14 and the numbers used are beyond the supported number precision.
> Axis min and max are rounded to the same number - `238863224762450`.
> There needs to be some room for the default tick positioner logic calulations so 14 is used instead of the JavaScipt Number precision limit.
> 
> If you need to work with numbers that big you might consider using tickPositions array or maybe a different axis type would work better. Some examples:
> 
> * categories: http://jsfiddle.net/BlackLabel/w7s4xgpt/
> * label format: http://jsfiddle.net/BlackLabel/w7s4xgpt/1/
> 
> I am not sure if this is a bug in Highcharts because this is based on the JavaScript Number precision limit.
> @TorsteinHonsi ?

**Comment by chihiroxc** [comment]
@KacperMadej  Thanks for providing the workaround. But the workaround doesn't suit us very well. We are using highcharts to display customers' data and it's not a very good solution to do such workaround in our product codes. The data points  `[238863224762451, 238863224762452, 238863224762453, 238863224762453]` are all JavaScript safe numbers, it's weird that highcharts can't compute y-axis correctly, if I change one of the numbers to a bigger one the issue is gone. Like http://jsfiddle.net/wmce259g/

**Comment by chihiroxc** [comment]
@TorsteinHonsi Thank you!
