### ISSUE TITLE
MACD wrong

### ISSUE THREAD

**Issue by vinnng** [highcharts/highcharts#16289]
#### Expected behaviour
when i show indicator macd, i think it's like work in other trade soft.

#### Actual behaviour
macd on aug 30, 2021
hightcharts show :  1.3132 / 1.5598 / -0.2466
other soft of all , example tradeview : 1.56 / 1.56 / 0

#### Live demo with steps to reproduce
highcharts data : https://www.highcharts.com/demo/stock/macd-pivot-points
tradeview : https://www.tradingview.com/chart/?symbol=NASDAQ%3AAAPL

#### Product version
9.2

#### Affected browser(s)
chrome , ms edge ...

**Comment by KacperMadej** [comment]
Hi @vinnng 

Thank you for reporting the problem.

The difference is in index of the OHLC data used - by default in Highcharts Stock index 0 is used (so Open value) and tradingview is using Close (so index 3). Here's a demo that seems to differ only due to precision of the calculations: https://jsfiddle.net/BlackLabel/mboy0w2x/

**Comment by KacperMadej** [comment]
Closing as resolved and due to inactivity.
