### ISSUE TITLE
Axis title doesn't break a much without chart title

### ISSUE THREAD

**Issue by kemusag** [highcharts/highcharts#16301]
#### Expected behaviour
If a small chart has a title, there seems to more space. An axis title with spaces breaks after each word.

#### Actual behaviour
Small charts without a title have less space. The same title will break less often. As a result, the words are overflowing.

#### Live demo with steps to reproduce
https://jsfiddle.net/gptseyxn/2/
Click the 'small' button and you'll see the problem.
You can adjust the title (I added a comment there) and try again, then it will work better.

**Comment by raf18seb** [comment]
Hi @kemusag, thanks for creating the ticket.

I'm not sure whether we should treat it as a bug. Note, that the chart is so small, that the plotarea height is 0 and the series are not even displayed.
Is there a reason or a real case for that chart to be so small?

As a workaround, you can always set a higher `chart.spacingTop` like in this demo: https://jsfiddle.net/BlackLabel/a7f041bc/

**Comment by kemusag** [comment]
Hi,
It is a rare scenario that I observed due to resizing of surrounding elements. So yes, it can be a real case.
I think it is a bit odd and it was confusing to me that the behavior on how the axis title is splitted changes. This might lead to weird effects in other situations, which is why I thought I should report it.

Thanks for the workaround though!

**Comment by TorsteinHonsi** [comment]
The difference happens here:

https://github.com/highcharts/highcharts/blob/f931b1adca66d79258b3cfebaf1b48669e736489/ts/Core/Axis/Axis.ts#L3167-L3169

Laying out the axes is done in a recursive way, because the placement of one axis depends on the labels/titles of the other, which depends on the placement of the first, which depends on its labels/titles, etc. To save processing time, these recalculations of labels is only done if the size of the axes is significantly affected by the other axis. So in this case, it seems that `axis.len` is not up to date with the current axis length.
