### ISSUE TITLE
legend item spacing incorrect for empty-name

### ISSUE THREAD

**Issue by ochristensen** [highcharts/highcharts#16398]
#### Expected behaviour
legend rows should be spaced the same regardless of name

#### Actual behaviour
providing a blank name for data leads to the legend row icon being "compressed" against the next row.

#### Live demo with steps to reproduce
https://jsfiddle.net/zenzizen/maj9hosg/7/ pie chart
https://jsfiddle.net/zenzizen/maj9hosg/14/ scatterplot

#### Product version
Highcharts & Highstock latest

#### Affected browser(s)
All presumably; checked Firefox, Brave and Chrome

**Comment by raf18seb** [comment]
Hi @ochristensen! Thanks for creating the ticket.

The legend item's height is defined by its BBox height which is calculated based on the text height. When there's no text, then `bBox.height = 0` and the `legend.symbolHeight` is taken which, by default, is equal to the text's font size - **which is smaller than the BBox text height**. That's why the distance between the elements is not constant when the text is missing.

```js
item.itemHeight = bBox.height || legend.symbolHeight;
```

Let me explain the above on a simple example. When the `legend.itemStyle.fontSize` equals to e.g. `8px`, then:
- when there is **no** text, then the `bBox.height` is 0 and the `legend.symbolHeight` is 8, so the `item.itemHeight` is 8
- when the text exists (`series.name` is defined), then the `bBox.height` is 13 - that's why the items spacing is not equal

I'm not sure whether we should treat it as a bug. If you know the font size you are using, then you can simply define the `legend.symbolHeight`, see demo: https://jsfiddle.net/BlackLabel/3bq8xmyj/

Any thoughts @TorsteinHonsi? Should we treat it as a bug?

**Comment by ochristensen** [comment]
thanks for the quick reply Rafał - I figured it was bounding box related given there was no text to measure; background for this is that we allow plotting "missing" values as a distinct category and the legacy backend code that generates our data provides literally an empty string for the name - we can workaround this by inserting a zero-width space as the series name in the front end, but it would be nice if they were consistent heights out-of-the-box regardless.

**Comment by TorsteinHonsi** [comment]
@raf18seb It may not be a critical bug, but I do think there's an easy fix, so I suggest we fix it. Since `symbolHeight` comes directly from font size, it is a mistake using it as a replacement for `bBox.height`, which better corresponds to the line height than the font size. We already have a computed value for the line height that we can fall back on. So instead of

https://github.com/highcharts/highcharts/blob/c230c4d6289620429ed71f5dd94a804431e399a1/ts/Core/Legend/Legend.ts#L805-L807

We can do

```ts
        legend.itemHeight = item.itemHeight = Math.round(
            item.legendItemHeight ||
            bBox.height ||
            (legend.fontMetrics && legend.fontMetrics.h)
        );
```
