### ISSUE TITLE
VBP indicator recalculates only for the first main series update

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#16397]
#### Expected behaviour
I expect the VBP to always follow the main series, no matter how many data updates are.

#### Actual behaviour
VBP recalculates only for the first update. The next main series data updates don't change the VBP indicator.

#### Live demo with steps to reproduce
Click the first button - VBP is recalculating.
Click the second button - VBP is **not** recalculating (but should).
Click the third button - VBP is **not** recalculating (but should).

https://jsfiddle.net/BlackLabel/t1hp89ud/

#### Product version
Highcharts Stock 9.2.2

**Comment by pawelfus** [comment]
**Workaround:**
Force algorithm recalculation after updating data:
Demo: https://jsfiddle.net/BlackLabel/t1hp89ud/3/

Snippet:
```js
          chart.series[0].points[16].update({
            open: 60,
            high: 220,
            low: 55,
            close: 220
          }, false);
	  chart.series[2].recalculateValues(); // recalc
	  chart.redraw(); // redraw
```

*Internal note:*
Most probably it's caused by binding indicator to the xAxis extremes change, not to the data change. However, that doesn't explain why the first update triggers a recalculation. It doesn't matter if we update extremes on yAxis on every update: https://jsfiddle.net/BlackLabel/t1hp89ud/1/
