### ISSUE TITLE
Highcharts: Line chart not drawing lines correctly

### ISSUE THREAD

**Issue by GewoonSibrand** [highcharts/highcharts#16452]
#### Expected behaviour
Draw clean lines from point to point.

#### Actual behaviour
Weird looking lines with filled in blocks.
 

#### Live demo with steps to reproduce
Note: Make the chart field atleast 1200px width.
Screenshot of issue:
https://imgur.com/a/z5OG2F6

Fiddle of issue:
https://jsfiddle.net/cqht9g4L/

#### Product version
Highcharts 9.1.2

#### Affected browser(s)
Chrome Version 94.0.4606.71 (Official Build) (arm64)  (MacBook Pro)

It seems to be working fine on Safari.

**Comment by KacperMadej** [comment]
Hi @GewoonSibrand 

I am unable to recreate the problem.
Here's your demo but with a fixed width of 2500px: https://jsfiddle.net/BlackLabel/o70kev5p/ 

You have reported the version as 9.1.2 while your demo is using the current 9.2.2 - please check if the problem is resolved for the current Highcharts version for you and if not please add your OS version and info about your screen being a retina or not retina.

**Comment by KacperMadej** [comment]
Fixed since Chrome v96
