### ISSUE TITLE
data range in Firefox browser it is impossible to select month or year because of closing calendar popup

### ISSUE THREAD

**Issue by andry-93** [highcharts/highcharts#16556]
#### Expected behaviour
Datapicker doesn't close

#### Actual behaviour
Problem in Calendar picker in Firefox browser it is impossible to select month or year because of closing calendar popup.

#### Live demo with steps to reproduce
Link to random example:
[Link](http://jsfiddle.net/5CRTa/1/)

#### Product version
highcharts: 9.3.0,
highcharts-react-official: 3.1.0,

#### Affected browser(s)
Firefox Browser

**Comment by tw2as** [comment]
the issue still exists on highcharts ver. 10. Please fix.

**Comment by kamil-musialowski** [comment]
As stated in #18751, the issue is caused by Firefox bug which is already available in beta version of the browser, and will be available for standard browsers on 9th May, 2023.

For now, here is the Highcharts workaround that can be used before the Firefox update: https://jsfiddle.net/BlackLabel/em914op5/

**Comment by kamil-musialowski** [comment]
I can confirm now that the Firefox 112.0 update fixes the mentioned input issue, therefore this ticket will be closed.
