### ISSUE TITLE
Wrong tick positions on datetime axis in xrange chart with multiple series

### ISSUE THREAD

**Issue by heivo** [highcharts/highcharts#16585]
#### Expected behaviour
The tick positions should be independent of the number of series in an xrange chart and should apply `tickInterval` and `tickPixelInterval` settings (if present).

#### Actual behaviour
When adding more series the tick positions change and have too much distance. Under certain conditions no ticks at all are drawn.

#### Live demo with steps to reproduce
xrange chart with 3 series: https://jsfiddle.net/o5cuhky8/

![image](https://user-images.githubusercontent.com/12901858/140041089-60d8d2cf-a78a-4416-8278-3dd96d740a6e.png)

xrange chart with 1 series (working as intended): https://jsfiddle.net/o5cuhky8/1/

![image](https://user-images.githubusercontent.com/12901858/140041155-9adc2c3a-8f64-460d-ab81-ff813890bd24.png)

#### Product version
Highcharts 9.2.2

#### Affected browser(s)
Chrome, Firefox

**Comment by raf18seb** [comment]
Hi @heivo, thanks for creating the ticket!

I don't think it's a bug. The ticks are calculated properly. When you're adding points and changing the x distance between them, you also change the `xAxis.minRange`.
If you'd like to control the ticks number/positions, you can set the `tickInterval` and it's also working fine, see demo: https://jsfiddle.net/BlackLabel/05w83xm9/

**Comment by heivo** [comment]
@raf18seb Thank you for your response.

I don't know how exactly the additional series affect the minRange: all 3 bars stop at almost the same time, so why does this lead to fewer ticks rendered?

Can you also provide an example with working `tickPixelInterval` please? That doesn't seem to work.

**Comment by raf18seb** [comment]
The `minRange`, by definition, is the difference between the 2 closest points, so when you're adding new series (points), the `minRange` might change. The `minRange` affects the ticks' positions.

Indeed, the `tickPixelInterval` is not working with this dataset. This is because Highcharts usually tries to put the ticks on rounded data, e.g. hourly ticks or at midnight and noon (like in the above example).
In general, this can be controlled by many properties, e.g. mentioned `tickInterval` or [tickPositions](https://api.highcharts.com/highcharts/xAxis.tickPositions)

**Comment by heivo** [comment]
Thank you for your explanations @raf18seb, I'll try to work around this using `tickInterval` then.
