### ISSUE TITLE
Draggable variwide chart - First element of chart is not draggable on Y axis

### ISSUE THREAD

**Issue by ChristophKubik** [highcharts/highcharts#16596]
#### Expected behaviour
Every datapoint of the variwide chart should be draggable on the y axis when the module is enabled.

#### Actual behaviour
The first datapoint is not draggable at any circumstances. Even if there is only one element in the chart, it is not draggable as it is the first datapoint.

#### Live demo with steps to reproduce
https://jsfiddle.net/Gistiv/k2xvhyo0/96/

#### Product version
Found on 8.2.2 and is still present in 9.3.0 as you can see in the fiddle

#### Affected browser(s)
Reproduced with chrome, edge and firefox

**Comment by raf18seb** [comment]
Hi @ChristophKubik, thanks for reporting the issue!

**`Internal note`:**
The problem is with this line: https://github.com/highcharts/highcharts/blob/36fe728c4e26ba56a62351db52d8e3bb36c3a06b/ts/Extensions/DraggablePoints.ts#L2501

The first point's `x`'s coordinate starts from -0.5 on a category xAxis, it should be valid here for a categorized xAxis.
This code solves the issue:
```js
// Correct left edge value depending on the xAxis' type
const minEdge = point.series.xAxis.categories ? -0.5 : 0;
if (!path || pos.x < minEdge || pos.y < 0) {
    return;
}
```
