### ISSUE TITLE
StockChart - stacked area with null values - incorrect lines at on end values

### ISSUE THREAD

**Issue by Muhahe** [highcharts/highcharts#16616]
#### Expected behaviour
Im expecting that stockchart, that contains area type series, that are stacked and contains null values will display correct values all the time

#### Actual behaviour
When i try to create stockchart, that contains area type series, that are stacked and contains null values. Then null value on the end displays incorrect line. It seems that line is pointing to start of chart
![image](https://user-images.githubusercontent.com/1909172/140885642-99706e39-ff90-4114-9869-c30e6621130e.png)

It seems like when connectNulls is set to true, and null value is out of view (due to rangeviewer) than line is drawed to something unexpected...

#### Live demo with steps to reproduce
live demo: https://jsfiddle.net/decax4f0/1/

When you open live demo, the chart you can observe, that seria A (blue) and serie C (green) incorrectly interpolates last null values, and line is heading to start of chart (or somewhere close to that).

#### Product version
Highstock JS v9.3.1 (2021-11-05)

#### Affected browser(s)
Chrome 95.0.4638.69
Firefox 94.0.1

**Comment by raf18seb** [comment]
Hi @Muhahe, thanks for reporting a bug!

Workaround: disable [xAxis.ordinal](https://api.highcharts.com/highstock/xAxis.ordinal): https://jsfiddle.net/BlackLabel/qno71dfg/

`Internal note:`
Worked fine in 9.1.2, broken since 9.2.0.
Simplified demo: https://jsfiddle.net/BlackLabel/ehLn2bs1/
Looks like a regression of https://github.com/highcharts/highcharts/commit/ca33c11fd40ff474b8ed723990938ad02d88be69

**Comment by Muhahe** [comment]
Thanks @raf18seb

workaround works like a charm!
