### ISSUE TITLE
Arearange points on shared tooltip are not accessible after redraw

### ISSUE THREAD

**Issue by samuelroland** [highcharts/highcharts#16656]
#### Expected behaviour
With an arearange series, the range info should always be visible in the shared tooltip, even after data change (and points should be present in this.points).

#### Actual behaviour
With an arearange series, the range info (low and high values) are visible in the shared tooltip only before a redrawn, and disappear right after.

#### Live demo with steps to reproduce
- Hover a point
- See tooltip with range
- Wait 2s for the next update
- See that range has disappeared in the tooltip (and that the tooltip has moved to the top, which is strange)

Demo: https://jsfiddle.net/samuelroland/6eq9cosm/

#### Product version
9.3.1

#### Affected browser(s)
Firefox  94.0.1, Chrome 96.0.4664.45, Edge 95.0.1020.53

**Comment by raf18seb** [comment]
Hi @samuelroland,

thank you for reporting the issue.

The tooltip has moved because the `shared` option didn't work - the tooltip has been displayed only for one point of the line series and has moved above that one point.

`Internal note:`
Worked fine in 7.2.1, broken since 8.0.0 (unable to bisect)
