### ISSUE TITLE
Numbers disappear when setting matrix width

### ISSUE THREAD

**Issue by Phrrancis** [highcharts/highcharts#16663]
#### Expected behaviour
When the width of a chart is expanded by 100% or reduced to 50%, the numbers on the bars shouldn't be affected

#### Actual behaviour
When setting a matrix to 50% width, some (seemingly random) numbers in graphs disappear.
##

https://user-images.githubusercontent.com/60043467/142193616-a845be63-6e1a-441b-91d2-641522ff4ecf.mov

#### Product version

Hightcharts 9.3.1
#### Affected browser(s)
Chrome on Windows pc
FireFox on MacOS

**Comment by raf18seb** [comment]
Hi @Phrrancis, thank you for creating the ticket.

Could you check whether setting [dataLabels.overflow](https://api.highcharts.com/highcharts/plotOptions.series.dataLabels.allowOverlap) to `true` helps? If not, could you provide a simple jsFiddle demo showing the issue?

it looks like the dataLabels might overlap a little - that's why they're being hidden.

**Comment by Phrrancis** [comment]
@raf18seb  we tested with `dataLabels.allowOverlap` to` true ` it overlaps, but looks like a temporal fix we could use. Thank you

I'll close this ticket if there's nothing left to add
