### ISSUE TITLE
Force-directed graph variation

### ISSUE THREAD

**Issue by OmerWow** [highcharts/highcharts#16701]
Hi,

I'm currently using D3 but really considering switching to Highcharts, it seems great!.
However, I have one major chart in my site that I'm not sure if Highcharts supports (or how much work it will be to implement for me).

I saw that you're supporting force-directed graphs, but do you support this kind of variation?: https://observablehq.com/@d3/mobile-patent-suits
As you can see, it's a fork of the main force-directed graph example which is very similar to the one you have on your site.

Also, I noticed that the performance of the force-directed graph example on your site (https://www.highcharts.com/demo/network-graph) have terrible performance on my machine (brave browser, latest version, mbp 13.3" 2020).
I don't get this performance issues in any other example in your site or on similar example using D3.

**Comment by raf18seb** [comment]
Hi @OmerWow, thanks for being interested in Highcharts!

> I saw that you're supporting force-directed graphs, but do you support this kind of variation?: https://observablehq.com/@d3/mobile-patent-suits

The main difference between our basic networkgraph chart and the one from the link you provided is the links being curved (and 2 links between two nodes).
The function responsible for links rendering (`getLinkPath`) can be easily extended/changed to render basically anything you want.
Here is a sample demo showing it (curved links instead of straight): https://jsfiddle.net/BlackLabel/3wuvoeaj/

> Also, I noticed that the performance of the force-directed graph example on your site (https://www.highcharts.com/demo/network-graph) have terrible performance on my machine (brave browser, latest version, mbp 13.3" 2020).

This is mainly caused by the dataLabels positioning logic. The performance is better when the dataLabels are disabled.
In some cases (with or without dataLabels), the performance can be improved in others ways, but it depends on a specific use case so I'm not able to prepare a simple example for you at this moment.


Additional links' shapes/options sound like a good feature so let's keep this ticket open.
In case of any further questions (not strictly related to bugs/features), please contact our support on one of ours dedicated support channels: https://www.highcharts.com/blog/support/
