### ISSUE TITLE
Projection Orthographic does not rotate map, when maps container is larger.

### ISSUE THREAD

**Issue by RobertRochonCodi** [highcharts/highcharts#16722]
#### Expected behaviour
Projection Orthographic should rotate world map, no matter what container height is.

#### Actual behaviour
Projection Orthographic does not rotate world map when height of container is bigger than ~680px;

#### Live demo with steps to reproduce

template: https://jsfiddle.net/RobertRochon/97y0eb2L/1/

When we have the demo `Built in projection` we had #container height set to 500px.
When height is modified to more than ~680px, rotation does not work and standard map navigation is working.

#### Product version

Highcharts Maps 9.3.2

#### Affected browser(s)
Tested on:
Google Chrome - 95.0.4638.54
Firefox - 94.0

**Comment by raf18seb** [comment]
Hi @RobertRochonCodi, thank you for reporting a bug.

**Comment by TorsteinHonsi** [comment]
@raf18seb There's a condition in the MapView that's flawed. The idea is that when we're loading the whole globe, panning should rotate it, but when only loading a limited area (for example when projecting a single country in the ortho projection), panning should behave like with other projections - just translate the map around.

The problem with this condition currently is that we apply it when `minZoom < 3`. But `minZoom` again depends on the size of the playing field.

https://github.com/highcharts/highcharts/blob/e7983c78b905f52cc6d400b23ea3eb780e723767/ts/Maps/MapView.ts#L166-L173

Just below that code we actually use the size of the playing field, which is `Math.min(chart.plotWidth, chart.plotHeight)`. So to fix this issue, it should be enough to store that size (`plotSize`) in a constant, then use it first in the condition instead of 3. I think just multiplying `plotSize` with some constant should work, otherwise we need to correct it with `getScale` too.

I suggest one of the Maps team members give it a go. Invest max two hours, then if it doesn't work, come back to me and we'll figure it out.
