### ISSUE TITLE
Popup: when adding custom indicator with parameter which name consists a number the popup doesn't display parameter name.

### ISSUE THREAD

**Issue by pawellysy** [highcharts/highcharts#16753]
#### Expected behaviour
The custom indicator should have all of the properties listed in the popup. 

#### Actual behaviour
When adding the custom indicator with a parameter which name consists of a number, the popup in stock tools doesn't display its name

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/y49rxmw3/1/
open the indicators popup
check that one of the indicator's parameters don't have the label

#### Product version
v9.3.2

#### Affected browser(s)
all

**Comment by pawelfus** [comment]
*Internal note:*
It is caused by filtering out arrays' indexes (e.g. `params.periods: [x, y]` is rendered as "Periods: [input] [input]", not "Periods: 0: [input] 1: [input]"). Probably we can simply improve regexp here: https://github.com/highcharts/highcharts/blob/446534e1e318cb993c119f263dcd50e15ba2219c/ts/Extensions/Annotations/Popup.ts#L242

To filter out only indexes
