### ISSUE TITLE
parallel channel in Highstock does not work in logarithmic mode

### ISSUE THREAD

**Issue by anoosurf** [highcharts/highcharts#16769]
#### Expected behaviour
when drawing a parallel channel the chart should take into accoun the logarithmic scale and appear parallel to end user even in that case.. that is how stock trader would use

#### Actual behaviour
when in logarithmic mode, it gets skewed which is incorrect

#### Live demo with steps to reproduce
https://jsfiddle.net/anoosurf/uzwvrhjt/3/

#### Product version
highcharts /highstock 9.3.2

#### Affected browser(s)
![image](https://user-images.githubusercontent.com/4696146/145222165-3b7eac35-4706-4263-a238-22cbfc323054.png)

**Comment by raf18seb** [comment]
Hi @anoosurf, thank you for reporting a bug!

**Comment by pawelfus** [comment]
**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/o93v7quz/
Plugin:
```js
(function(H) {
  H.wrap(
    H.Annotation.types.tunnel.prototype,
    'getPointsOptions',
    patch16769
  );

  function patch16769(proceed, ...args) {
    const points = proceed.apply(this, args),
      yAxisIndex = points[0].yAxis,
      yAxis = this.chart.yAxis[yAxisIndex];

    // In case of log axis, translate the bottom left point again
    if (yAxis && yAxis.logarithmic) {
      // Get the height in pixels
      const h = yAxis.toPixels(points[2].y) - yAxis.toPixels(points[1].y),
      // Get the pixel position of the last point
        y3 = yAxis.toPixels(points[0].y) + h;

      // Set the new value
      points[3].y = yAxis.toValue(y3);
    }

    return points;
  }

})(Highcharts);
```

*Internal note:*
It's caused by using `height` to control all bottom points. We simply add height value to the first two points' values in `heightPointOptions()`. Even though it's mathematically correct, visually we can observe the skew. For example this demo: (tunnel has height=20)
![Zrzut ekranu 2021-12-10 o 12 30 10](https://user-images.githubusercontent.com/1453926/145567886-6799c4f9-8f87-4ae1-b39b-8640c94ad155.png)
