### ISSUE TITLE
Radial gradient for 'one-value' series

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#1677]
Example: http://jsfiddle.net/2Gzkd/

In 2.3.5 doesn't work either.

**Comment by KacperMadej** [comment]
If `gradientUnits="userSpaceOnUse"` will be set for a radialGradient, then gradient is set for straight lines, but `cs, cy, r` will have to be different and gradient will not be relative to an element that uses it - it will be relative to . ([related SO question](http://stackoverflow.com/questions/21638169/svg-line-with-gradient-stroke-wont-display-straight))

Examples with comparison: 
http://jsfiddle.net/h4jk4adc/
http://jsfiddle.net/h4jk4adc/1/

**Comment by reiniermujica** [comment]
I could fix this like the legend
` Highcharts.addEvent(Highcharts.Chart, 'render', function render() {
      this.series.forEach((series) => {
        if (series.graph) {
          const pathDef = series.graph.attr('d').split(' ');
          pathDef[5] = parseFloat(pathDef[2]) + 0.0001;
          series.graph.attr({ d: pathDef });
        }
      });
    });`

**Comment by reiniermujica** [comment]
I fix this issue with the same code 
``` 
Highcharts.addEvent(Highcharts.Chart, 'render', function render() {
      this.series.forEach((series) => {
        if (series.graph) {
          const pathDef = series.graph.attr('d').split(' ');
          pathDef[5] = parseFloat(pathDef[2]) + 0.0001;
          series.graph.attr({ d: pathDef });
        }
      });
    });
```

**Comment by eltonjude** [comment]
In Pie Charts the connector that the library draws between the data labels and and corresponding Slice suffers from this problem. In the fiddle you will see that the lines for Tue and Fri do not show up.
https://jsfiddle.net/3gtd1y05/1/

Support suggested that I could manipulate the data such that we do not end up with an exactly straight line (in the fiddle there is a comment which tells you which value to change and to what). While this solution works in a static demo scenario, it does not scale to real use cases inside an application; and the fact that we are manipulating the data itself won't fly.

Since this issue is happening to an element of the library, it is my opinion that the library should add a workaround to combat the SVG issue. There are two things that the library could do:

1. Use solid color for the connector (cheap)
2. Make the label placement algo realize that the connector is going to be a horizontal line and change one of its end points by a pixel so as to not generate a horizontal line.

**Comment by karolkolodziej** [comment]
I created a separate feature request with a description of your issue.
Also, I added a demo with a suggested solution.
If that is what you have been looking for please upvote this idea https://github.com/highcharts/highcharts/issues/17029
