### ISSUE TITLE
Highcharts 9.3.2 creates wrong svg content

### ISSUE THREAD

**Issue by puschlj** [highcharts/highcharts#16790]
We are updating Highcharts component in our project from 8.2.2 to 9.3.2. 

For export we use a server side c# code, which uses Aspose.SVG component,

Older version of Highcharts output can be converted by this component, while loading the output of newer version into the component gives an exception.

We found out that the root cause might be that the older versions output differs from newer version. The difference can be found in Expected and Actual behavior block

#### Expected behavior
part of svg file:

```
  <text x="5" data-z-index="1" y="16" style="color:#666;cursor:pointer;font-size:11px;font-weight:bold;fill:#666;">
                <tspan x="5" y="16" class="highcharts-text-outline" fill="#FFFFFF" stroke="#FFFFFF" stroke-width="2px" stroke-linejoin="round" style="">(4)Csütörtök</tspan>
                <tspan x="5" y="16">(4)Csütörtök</tspan>
            </text>
```

#### Actual behavior
part of svg file:

```
  <text x="5" data-z-index="1" y="16" style="color:#666;font-size:11px;font-weight:bold;fill:#666;">
                <tspan class="highcharts-text-outline" fill="#FFFFFF" stroke="#FFFFFF" stroke-width="2px" stroke-linejoin="round" style="">
                    (4)Csütörtök
                    <tspan x="5" y="16">​</tspan>
                </tspan>
                (4)Csütörtök
            </text>

```
#### Live demo with steps to reproduce
Export to SVG on each site

8.2.2: http://jsfiddle.net/46dLuc73/1/
9.3.2: http://jsfiddle.net/46dLuc73/

#### Product version
Highcharts 9.3.2

#### Affected browser(s)
Edge (chrome based) current version, 
Chrome current version,
Firefox current version

**Comment by raf18seb** [comment]
Hi @puschlj, thank you for contacting us with your issue.

This change is caused by this PR: https://github.com/highcharts/highcharts/pull/14979
I'm not sure whether we should consider it as a bug. It works fine in Highcharts, but fails with a 3rd party library.

As a workaround, could you set `dataLabels.useHTML: true` and see if it helped? Demo: https://jsfiddle.net/BlackLabel/7r62wsnq/

@TorsteinHonsi, what's your opinion on this matter?

**Comment by TorsteinHonsi** [comment]
I'm not sure whether it's a bug either. I can't see any visual difference in the browsers, and the SVG is valid. So probably the bug lies in your SVG converter.

#### Workaround
That said, it is probably quite easy to work around it. Using HTML like suggested above can be a workaround, but HTML is often scrapped by SVG converters. A more precise approach may be to disable the `text-outline` in exported charts. Unfortunately I am not able to test it (so I am not sure if the text outline is actually the problem), but try this:

https://jsfiddle.net/highcharts/rs4zgemd/
```js
            "plotOptions": {
                "series": {
                    "dataLabels": {
                        "style": {
                            "textOutline": "none"
                        }
                    }
                }
            }
```

Another approach that you can craft the way you want, is to sanitize the SVG before passed to the export: https://jsfiddle.net/highcharts/kjdvho68/

**Comment by puschlj** [comment]
Thank you for the quick answer. It seems like that the "textOutline": "none"
setting is resolving my issue.

Torstein Hønsi ***@***.***> ezt írta (időpont: 2021. dec.
16., Cs, 14:21):
