### ISSUE TITLE
PlotLines on xAxis not achieved for Histogram and Variwide charts.

### ISSUE THREAD

**Issue by sakshi1eQ** [highcharts/highcharts#16833]
#### Expected behaviour

Plotlines for Histogram and Variwide charts should be plotted similar to that of the column chart as shown in this fiddle: https://jsfiddle.net/sakshiKorade/ea945zp6/

#### Actual behaviour

Not able to achieve same plotLines behaviour on Histogram and Variwide. Please suggest work around for this.

Histogram fiddle: https://jsfiddle.net/sakshiKorade/eb0fx6ka/9/
Variwide fiddle: https://jsfiddle.net/sakshiKorade/j82eb5fn/62/

#### Product version
All

#### Affected browser(s)
All

**Comment by raf18seb** [comment]
Hi @sakshi1eQ, thank you for creating the ticket.

It's because Variwide and Histogram xAxis values are not strictly related to the columns' indexes. In other words, the 3rd Variwide column is not placed on `x: 2` position.

I suggest rendering your own plotLines using the Highcharts SVG Renderer tool.
Demo: https://jsfiddle.net/BlackLabel/txrf9Lc7/

Now you can use config like this:
```js
xAxis: {
    type: 'category',
    customPlotLines: [{
      color: 'red',
      width: 2,
      value: 0,
      zIndex: 4
    }, {
      color: 'blue',
      width: 7,
      value: 2,
      zIndex: 4
    }]
  },
```

I wouldn't consider it as a bug so I'm closing the ticket (GH is our bugs and features tracker only).
