### ISSUE TITLE
Property 'showInLegend not working for Variwide chart

### ISSUE THREAD

**Issue by sakshi1eQ** [highcharts/highcharts#16840]
#### Expected behaviour

According to the documents, if property 'showInLegend' is set true then the legend should be visible

#### Actual behaviour

No legend shown for Variwide

#### Live demo with steps to reproduce

Refer this fiddle: https://jsfiddle.net/sakshiKorade/vL3orj27/

#### Product version
All

#### Affected browser(s)
All

**Comment by raf18seb** [comment]
Hi @sakshi1eQ! Thank you for writing to us with your issue.

The `series.showInLegend` legend is working properly and its value is `true` by default. But it will not be shown in the legend because you disabled it via `legend.enabled: false`.
It's working fine when you reenable the legend, see demo: https://jsfiddle.net/BlackLabel/vs7oau20/

Let me close the ticket as not a bug and resolved, but feel free to share any further insights.
