### ISSUE TITLE
Inconsistent positioning of x axis labels

### ISSUE THREAD

**Issue by Artur-** [highcharts/highcharts#16849]
We have an example of a dashboard view in https://start.vaadin.com/app/?preset=dashboard-view&keep-preset that contains an area chart among others. We use a screenshot comparison test to ensure that the view keeps working and looks correct. When opening the page, you can see that the x-axis texts are slightly animated from top down, which I understand is Highchart's standard behavior.

#### Expected behaviour

The x-axis texts should always end up in the same y position. When I open the page now I see that the `<text>` element for e.g. "Jan" is
```
<text x="71.00000000000455" text-anchor="middle" transform="translate(0,0)" y="347" opacity="1">Jan</text>
```

In almost all cases it has `y=347`

#### Actual behaviour
Sometimes when loading the page, the text seemingly stops a bit too early and ends up at `y=345` instead. The two pixel difference is hard to see but the image comparison sees it quite clearly..

#### Live demo with steps to reproduce
https://start.vaadin.com/app/?preset=dashboard-view&keep-preset

Unfortunately there is no reliable way to reproduce this. It seems to reproduce more often when downloading and running a new application from start.vaadin.com. The only difference between these should be where in the browser viewport the charts is placed. It is however always consistently placed in the viewport and reproduces by either opening it in many tabs or refreshing enough times.

#### Product version
Highcharts 9.2.2

#### Affected browser(s)
I have only ever seen this in Chrome because that is where the automated tests are run. Additionally it seems that this behavior has started with Chrome 94 (I am only 99% certain about this)

**Comment by Artur-** [comment]
I tried debugging it a bit in the browser but was unable to find the code that actually updates the `y` value

**Comment by Artur-** [comment]
This is what the result of our screenshot test looks like 
![diff](https://user-images.githubusercontent.com/260340/148076838-866a37fc-87be-4b0c-a888-4f24e8c49d34.gif)

**Comment by raf18seb** [comment]
Hi @Artur-, thank you for creating the ticket with your issue.

Unfortunately, I wasn't able to find a cause. I thought it might be something with `flex` set over the chart's container and I tried to reproduce your div structure in a simple demo: https://jsfiddle.net/BlackLabel/bq01hrjx/, but everything works fine (x-axis labels don't move).

Could you simplify your app (by removing all the unnecessary stuff)? It usually helps to find a cause. There must be something in your app causing this because the problem doesn't occur in a simplified, basic demo.

**Comment by Artur-** [comment]
Now when looking more closely, it seems like the problem is that the animation does not always start. Some times the labels remain in the initial position, most of the time they are animated down a few pixels. I will post a reproduction project once I get all the extra stuff removed

**Comment by Artur-** [comment]
Seems like it is also related to having a pie chart in the same view being rendered at the same time

**Comment by Artur-** [comment]
Create a test case here https://github.com/Artur-/charts-animation-issue

```
npm install
npm run serve
```

If you open http://localhost:8000/dev/index.html?delay=50 you will see that the area chart labels do not animate
If you open http://localhost:8000/dev/index.html?delay=0 they will animate

The delay is the time between adding the series to the area chart and the pie chart

**Comment by longmatthewh** [comment]
@raf18seb @Artur- I'm not yet sure if this is related, but we've also seen our snapshot tests from time-to-time...it could be animation-related. As shown in the screenshot below, our snapshot is expecting one of the points in the path to be `187.5`, but it was `187.4995620366649` in the test and failed. I'm going to consider adding a delay to these snapshot tests and seeing if that fixes things.

<img width="975" alt="Screen Shot 2022-01-05 at 2 28 47 PM" src="https://user-images.githubusercontent.com/3958577/148277264-8b21743f-30c8-487d-aba0-06bf01abf8d1.png">

**Comment by Artur-** [comment]
After digging a bit deeper it seems like the issue is at least partly related to using `<vaadin-chart>` and not Highcharts directly. What seems to take place is: 
1. Render an empty chart
2. Use `addSeries` to add 4 series
3. Call `redraw` which starts animating the series and the labels
4. Wait 50ms
5. Update xaxis to have `crosshair: true`
6. Call `redraw` again. This ends up in `Tick.prototype.renderLabel` which calls `attr` and not `animate` on the "new" labels and apparently ends up setting y to the current value (345) and not the value it should end up at (347)

**Comment by raf18seb** [comment]
Hi, sorry for the late reply. And thanks for providing a demo app showing the issue.

I was able to simplify your code and this is a minimal code needed to reproduce the issue in your app (only one chart with a basic config):
```js
import '@vaadin/charts';
import { html, LitElement } from 'lit';

export class TheView extends LitElement {

  constructor() {
    super();
  }

  render() {
    return html`
      <vaadin-chart type="area">
        <vaadin-chart-series .values=${[2, 3, 2, 4]}></vaadin-chart-series>
      </vaadin-chart>
    `;
  }

  async connectedCallback() {
    super.connectedCallback();
  }
}

customElements.define("the-view", TheView);
```


Here the y-axis' labels are jumping instead of x-axis' labels. The x-axis' labels stopped jumping when I removed categories (changed to linear axis type).
![vaadin-animation-issue](https://user-images.githubusercontent.com/23310742/148749018-e696df7d-5802-4ccc-85c1-e4451de8c64d.gif)


Unfortunately, it seems like a Vaadin app bug, not Highcharts, because the same simple pure JavaScript chart is working fine.
I suggest contacting Vaadin support to confirm this.
I'll leave the ticket open, just in case, until you get the confirmation from Vaadin.
