### ISSUE TITLE
Stacked area with logarithmic scaling does not render area when in boost mode

### ISSUE THREAD

**Issue by jherns** [highcharts/highcharts#16850]
#### Expected behaviour
When a stacked area graph using logarithmic scaling is in boost mode, the area should be rendered properly

#### Actual behaviour
When a stacked area graph using logarithmic scaling is in boost mode, the area is not rendered at all.

#### Live demo with steps to reproduce
https://jsfiddle.net/4zxcLe6n/32/

#### Product version
Highcharts v9.3.2 (latest)

#### Affected browser(s)
All browsers

**Comment by raf18seb** [comment]
Hi @jdhernley,

Thank you for reporting a bug.

**Comment by TorsteinHonsi** [comment]
_Internal note_

It fails also with column charts. The reason is probably that the low value of the stacked point is computed to 0, and 0 doesn't exist on a logarithic scale. It should be converted to the axis minimum. For non-stacked points we seem to handle this correctly, so presumably the code relevant code is already there somewhere in the Boost module.
