### ISSUE TITLE
Question: How to override Highcharts module functionality in Swift (How to use Highcharts.wrap() in Swift)

### ISSUE THREAD

**Issue by joeytat** [highcharts/highcharts#16863]
The reason asking this is because our web devs have rewrite some of the default behavior, like change how tooltip refresh,
move and hide. We would also like to implement the same feature on the iOS side.

Could we do some equivalent stuff on the iOS side with Swift?

```javascript
 Highcharts.wrap(Highcharts.Tooltip.prototype, "refresh", function (
    proceed,
    point,
    event,
    click
  ) {
    if (click) {
      proceed.apply(this, Array.prototype.slice.call(arguments, 1))
    }
  } as WrapProceedFunction)
```

**Comment by raf18seb** [comment]
Hi @joeytat!

GitHub is our bugs/features tracker only. With any support questions, please contact us on one of ours dedicated support channels, more info: https://www.highcharts.com/blog/support/
Also, please do not duplicate questions on different support channels, because if we don't catch this, it duplicates our developers' work. Thank you for understanding!

You'll get the answer soon here: https://www.highcharts.com/forum/viewtopic.php?f=9&t=47978
