### ISSUE TITLE
We are trying to display 20k as 20,000 when using Highcharts export

### ISSUE THREAD

**Issue by Daniil-Kandasoft** [highcharts/highcharts#16870]
#### Expected behaviour
We are trying to display 20k as 20,000 y axis label when using Highcharts export 

    chart: {
        type: "column",
        marginTop: 10,
        height: "48%",
    },
    exporting: {
        enabled: false,
    },
    credits: {
        enabled: false,
    },
    title: false,
    xAxis: {
        categories: child.results.years,
    },
    yAxis: {
        min: 0,
        reversedStacks: false,
        title: false,
        labels: {
        format: "${text}",
        //NOTE: formatter functions don't work in pdf
        //TODO: find a way to change 'k' in label to ',000'
        // formatter: function () {
        //   return "$" + this.axis.defaultLabelFormatter.call(this);
        // },
        },
    },
    plotOptions: {
        column: {
        stacking: "normal",
        },
    },
    series: child.results.chartMapping,
    };

#### Actual behaviour
Label formatter and `{numericSymbols: null}` work in browser but don't work when we export.

#### Affected browser(s)
any

**Comment by raf18seb** [comment]
Hi @Daniil-Kandasoft,

Thank you for contacting us with your question. For the future, for this kind of questions, please use our other support channels, because **GitHub is our bugs and features tracker only**.
More info: https://support.highcharts.com/

To change the options while exporting, use [exporting.chartOptions](https://api.highcharts.com/highcharts/exporting.chartOptions).
