### ISSUE TITLE
Highmaps: Script error is seen on hover of map series when we have map and mapbubble series if shared tooltip is ON

### ISSUE THREAD

**Issue by amruta1eq** [highcharts/highcharts#16896]
#### Expected behaviour
Error should not be seen when user tries to view tooltip on highmap.

#### Actual behaviour
Plot highmap using map and mapbubble series with tooltip enabled. On hover of the series, script error is seen on console.

Uncaught TypeError: Cannot read properties of undefined (reading 'pos')
    at h.b.searchPoint (highmaps.src.js:38031)
    at highmaps.src.js:26988
    at Array.forEach (<anonymous>)
    at b.findNearestKDPoint (highmaps.src.js:26984)
    at b.getHoverData (highmaps.src.js:27154)
    at b.runPointActions (highmaps.src.js:27829)
    at b.onContainerMouseMove (highmaps.src.js:27458)

#### Live demo with steps to reproduce
https://jsfiddle.net/amrutaJgtp/4q7ysh8k/1

#### Product version
Latest version v9.3.2

#### Affected browser(s)
All

**Comment by raf18seb** [comment]
Hi @amruta1eq, thanks for creating the ticket!

The error occurs because of `tooltip.shared` option enabled which is not documented and valid option in Highcharts Maps.
However, in my opinion, it shouldn't throw an error (it started in v9.3.0 when axes were removed from Maps), so I'll classify this as a bug - it's very easy to fix.

Workaround 1: disable `tooltip.shared`: https://jsfiddle.net/BlackLabel/7ogdvwqh/
Workaround 2 and potential core fix: https://jsfiddle.net/BlackLabel/d3hryzq9/
