### ISSUE TITLE
Gibberish axis label in stock chart

### ISSUE THREAD

**Issue by govinda18** [highcharts/highcharts#16905]
#### Expected behaviour
Axis labels should appear clear

#### Actual behaviour
Axis label for 3 jan in the below reproducer appear to be overlapping with something

![image](https://user-images.githubusercontent.com/25079291/150373594-29460459-8f87-4401-8661-427aef1c23a2.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/ohtzumLj/

#### Product version
Highstock

#### Affected browser(s)
Chrome

**Comment by raf18seb** [comment]
Hi @govinda18, thank you for reporting!

Simplified demo: https://jsfiddle.net/BlackLabel/v2p7dkgq/
It's not a bug, because it works fine (axis is broken so both labels are moved to the same place and overlap), but it could definitely work better. I'm tagging it as a feature request.

It could be easily solved by adding `xAxis.allowOverlap` logic like requested in this ticket: https://github.com/highcharts/highcharts/issues/16889

Demo with a workaround: https://jsfiddle.net/BlackLabel/7ohue1gm/
