### ISSUE TITLE
Network graph 

### ISSUE THREAD

**Issue by tushar32** [highcharts/highcharts#16988]
#### Expected behaviour
Hi guys,
I want to develop a network graph having one node in a center and other nodes revolving around it. 
Every node connected to center node with **different length**

#### Actual behaviour
We need to develop exactly simillar to this.
![Screenshot from 2022-02-11 18-27-12](https://user-images.githubusercontent.com/30208305/153598434-21e28103-d5c9-4ac6-85dc-52047ae4539e.png)

**Comment by pawellysy** [comment]
Hello @tushar32 thanks for contacting us!

I'm sorry, (maybe I'm missing something) But how is it different from the current NetworkGraph implementation? Can't you just create a set of data, where each node is connected to the central node? 

https://jsfiddle.net/BlackLabel/2qm7x4tp/

**Comment by tushar32** [comment]
Or is there any other way to achieve this?

Let me know please.

**Comment by pawellysy** [comment]
@tushar32 You can try to tweak some layout parameters, which are listed here: https://api.highcharts.com/highcharts/series.networkgraph.layoutAlgorithm

The current `Networkgraph` implementation lets you create the layout, which bases on forces between nodes. 

Check this demo, which looks a bit more like what you wanted to achieve: https://jsfiddle.net/BlackLabel/2qm7x4tp/2/
Please, try to adjust the parameters provided in the link above, so that the chart looks more like what you are trying to achieve.

**Comment by tushar32** [comment]
Thansk for the solution. I can try that. But meanwhile I tried using another way using scatter chart.
I used this.renderer.path to draw line from center node to every node. This is how it is more controlled. 

But as you can see it exceeds than the parent div. I tried giving width but nothing happening.

**FYI: I am using highchart- react-official**
![Screenshot from 2022-02-17 12-32-56](https://user-images.githubusercontent.com/30208305/154423013-45cee5f6-0c0f-4eac-aa14-f964619fa79a.png)

**Comment by pawellysy** [comment]
Thanks for your input!
But since this topic exceeds normal feature requests, and GitHub is our bugs and features tracker only, please contact us on one of our dedicated support channels.

More info here: https://www.highcharts.com/blog/support/
Thanks for understanding!
