### ISSUE TITLE
Boost module not working when using StockChart

### ISSUE THREAD

**Issue by RickRosendaal** [highcharts/highcharts#17002]
#### Expected behaviour
Using the boost module in combination with a Highcharts StockChart increases the performance by drawing (sections) using WebGL, displaying (sections) using an HTML image tag instead of an svg.

#### Actual behaviour
The boost module doesn't kick in, and the entire chart is drawn using svg as if the boost module was never enabled resulting in a unusably slow chart.
When switching the type to the default "chart" instead of "stockChart", the performance is immediately increased and the chart is drawn as expected.

#### Live demo with steps to reproduce
Two of the official Highcharts boost Samples from the Highcharts boost module docs:
1: https://www.highcharts.com/samples/highcharts/boost/line-series-heavy-stock
2: https://www.highcharts.com/samples/highcharts/boost/line-series-heavy-dynamic

Link to the docs: https://www.highcharts.com/docs/advanced-chart-features/boost-module#samples

#### Product version
NPM package Highcharts - Version: 9.3.3
Affected chart type: Highstock / stockChart

#### Affected browser(s)
All

**Comment by pawellysy** [comment]
Hello @RickRosendaal, thank you for reporting the issue!
It is a regression. 
Works fine in v9.1.2 -> https://jsfiddle.net/BlackLabel/fomsntd3/1/
But is broken in v9.2.0 -> https://jsfiddle.net/BlackLabel/fomsntd3/2/

`Internal Note`
Bisected to commit ac1067e0ab04c42452b04c2b0eb4e599426ba60d
@karolkolodziej

**Comment by karolkolodziej** [comment]
These changes and behaviour are intended. 
As described in the `getSeriesBoosting` method: 
```
If the data is going to be grouped, the series shouldn't be boosted.
```

This is true for `stockChart` where the data grouping is enabled by default.
Data grouping doesn't have to be applied, it can be only enabled, and the boost won't kick in.
In order to solve this, disable the data grouping for each series- [demo](https://jsfiddle.net/BlackLabel/rkx3a9sL/).

To do:
- [ ] Inform in the documentation about the fact that data grouping disables the boost.
- [ ] Update demos.
