### ISSUE TITLE
Spider Chart Sizing Causes Overlapping Labels

### ISSUE THREAD

**Issue by jsokol** [highcharts/highcharts#17037]
#### Expected behaviour
I created a spider chart report that displays a bunch of different data points.  I expected it to expand to fill whatever area was necessary for the words to not overlap.

#### Actual behaviour
The spider chart gets condensed into the same area and the words overlap so it looks bad.  HighSoft support said that this overlapping issue happens because of the responsive mechanism.  They suggested removing the responsive section to make it work, but said it is probably a bug that we should report to you here.

#### Live demo with steps to reproduce
[https://jsfiddle.net/rd1jbxao/](https://jsfiddle.net/rd1jbxao/)

#### Product version
Latest HighCharts version from your CDN.

#### Affected browser(s)
Tested in Chrome, but I believe this issue is not browser specific.

**Comment by pawellysy** [comment]
Hello @jsokol, thanks for creating the issue!

It seems, that your responsive rules config is not correct. The rules property should be an array, whereas you defined it as an object. 
Here is a demo without an error in the console: https://jsfiddle.net/BlackLabel/bt23powd/2/

Does this work for you? 

PS: When reporting a bug, please copy the version number either from Highcharts.version object or from the CDN page, since it is constantly changing :)

**Comment by jsokol** [comment]
In your screenshot you show 26 items on the chart, but only 16 labels.  So not all of the data is represented there.  I'm looking to have each of the labels displayed and have the chart grow to the appropriate size to represent them.  This is not working.  My current options appear to either be to truncate the report to less labels or have the appropriate number of labels and have them all overlap.  This definitely seems like a bug to me.
