### ISSUE TITLE
Stock tools GUI annotation should go to new step on mouseDown

### ISSUE THREAD

**Issue by pawellysy** [highcharts/highcharts#17041]
#### Expected behaviour
When creating Annotation via the stock tools module, the mouseDown should end the current step and go to the next step, or finish adding an annotation.

#### Actual behaviour
When creating an annotation, pressing and dragging the mouse, the annotation is not created and some events below are triggered, like dragging a pane.

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/stock-tools-gui

Select an annotation to be added via stock tools GUI, and instead of clicking, hold the mouse down and drag the cursor.
The annotation should add on `mouseDown`

#### Product version
v9.3.3.

#### Affected browser(s)
all

**Comment by raf18seb** [comment]
Hi @pawellysy, thanks for creating new ticket!

I wouldn't consider this as a bug because:
- years ago, when annotations were not in Highcharts core yet (it was an external plugin), it was implemented this way and users were reporting some problems on mobile devices.
- now, user is able to choose annotation, then drag/pan to correct position and view (by keeping a mouse down), then add an annotation just the way it works now

It works this way without any problems and I wouldn't consider it as a bug.

If anyone would like to change or improve the current behavior - we are always open to any suggestions. Feel free to leave your comment with a description of how you would like it to work below.

**Comment by davidfloyd91** [comment]
thanks @pawellysy, and hi @raf18seb, i understand it may not make sense to make this change for all users, but we've had users express confusion due to the current behavior. would it be possible to provide a workaround to achieve the onMouseDown behavior described in the issue? perhaps a configuration that would achieve that result, or a wrapper function we could include in our code, something like that?

**Comment by pawellysy** [comment]
@davidfloyd91 unfortunately there is no such workaround at the moment :(
