### ISSUE TITLE
setExtremes/afterSetExtremes e.trigger returns undefined when called internally

### ISSUE THREAD

**Issue by cnighswonger** [highcharts/highcharts#17055]
#### Expected behaviour

e.trigger should always return a valid value even when called internally.

ie. When calling series.addPoint, e.trigger should be set to 'addPoint' so that the callback can take action based on the trigger.

#### Actual behaviour

e.trigger is undefined when called internally.

#### Live demo with steps to reproduce

Notice in the console in the demo below that when the callback is triggered by a nav or range selector action, e.trigger is set accordingly. However, when the callback is triggered by the internal redraw after series.addPoint, e.trigger is set to undefined.

https://jsfiddle.net/chris_kdd/kngcr3by/3/

#### Product version

Highstock JS v9.3.3 (2022-02-01)

#### Affected browser(s)
All

**Comment by pawellysy** [comment]
Hello @cnighswonger, thanks for creating the issue!

The `series.addPoint()` is different than changing the extremes by panning or using a navigator. 
The `series.addPoint()` method only sometimes triggers changing the extremes. If you add the point as a first or last point of the series, and the axis' range is fully extended, the extremes change, but in any other scenario, the extremes remain the same.
 It is different than changing the extremes via navigator or panning since those events always trigger the axis' range change. 

Apart from that, you can always detect this change yourself e.g. by setting some variable and checking its value. 

Here is an example workaround: https://jsfiddle.net/BlackLabel/Lbmj5a16/

**Comment by cnighswonger** [comment]
Hello @pawellysy,

> The `series.addPoint()` is different than changing the extremes by panning or using a navigator. The `series.addPoint()` method only sometimes triggers changing the extremes. If you add the point as a first or last point of the series, and the axis' range is fully extended, the extremes change, but in any other scenario, the extremes remain the same. It is different than changing the extremes via navigator or panning since those events always trigger the axis' range change.

Could you point me to the API documentation which explains this? I don't think it exists at present, but maybe I have missed it.

IMHO, every action which results in extremes being changed should be addressed in the API docs with detail like you have given above. This is an especially critical issue given that updating extremes can (and often does) cause recursion. Locating the cause is often difficult given that there are a number of methods which trigger an extremes update but do not "announce" it via e.trigger. Methods that sometimes do and sometimes don't update extremes complicate the matter more. Through documentation would go a long way towards reducing debug time and/or helping to avoid the problem to begin with.

> Apart from that, you can always detect this change yourself e.g. by setting some variable and checking its value.
> 
> Here is an example workaround: https://jsfiddle.net/BlackLabel/Lbmj5a16/

Thanks for workaround. This should be added to the API documentation as well. Perhaps a list of all possible targets for setExtremes would be of benefit as well. Again, I do not find chart.pointAdded anywhere in the API docs nor do various search engines return information on it. Maybe I have overlooked it.

Kind regards,
Chris

**Comment by cnighswonger** [comment]
Fiddling around with this a bit more, I see that you are suggesting adding a flag for every possible trigger of setExtremes which does not set e.trigger. I think that this is a klungy solution which requires the developer to have extensive knowledge of the internal workings of the HighCharts libraries. If so, this seems to be an unsustainable solution, and I would request that either this bug report be reopened or that it be marked as an enhancement request.

Kind regards,
Chris

**Comment by pawellysy** [comment]
> Could you point me to the API documentation which explains this? I don't think it exists at present, but maybe I have missed it.

This change of the axis' extremes is done by the navigator. Here is the API Reference: Could you point me to the API documentation which explains this? I don't think it exists at present, but maybe I have missed it.


> I see that target.chart.pointAdded is a variable created on the fly. How would one handle multiple triggers not already handled by e.target? For example: If more than one method which does not set e.trigger is triggering the extremes update, how could one distinguish between them?

It depends on what you want to achieve. When adding a new point via your own custom code, you can handle all the other changes, as well as even call any event yourself with all of the options defined. It is hard to pinpoint an exact solution for your issue, but you can contact us via our official support channels [(listed here)](https://www.highcharts.com/blog/support/) where we will try to find the best solution for you. 

>IMHO, every action which results in extremes being changed should be addressed in the API docs with detail like you have given above. 

In most cases when the `e.trigger` is not defined in `afterSetExtremes`, the extremes' change is caused by rerendering of the chart. When axis extremes are not defined in the config, they are calculated based on the series' min/max values, which might change when adding/ removing a series, changing the visibility of them, and some other data manipulations. It is mentioned in the API here: https://api.highcharts.com/highcharts/xAxis.max and all of the other changes are natural logical continuations. It could be mentioned in some general docs, e.g. here: https://www.highcharts.com/docs/chart-concepts/axes


Would that work for you? 
Then I could add a new feature request to update the docs with the description of the axes' extremes.

**Comment by cnighswonger** [comment]
> > Could you point me to the API documentation which explains this? I don't think it exists at present, but maybe I have missed it.
> 
> This change of the axis' extremes is done by the navigator.

A link is missing there.

Do you refer to the extremes update triggered by series.addPoint or by some navigator action?

> > I see that target.chart.pointAdded is a variable created on the fly. How would one handle multiple triggers not already handled by e.target? For example: If more than one method which does not set e.trigger is triggering the extremes update, how could one distinguish between them?
> 
> It depends on what you want to achieve. When adding a new point via your own custom code, you can handle all the other changes, as well as even call any event yourself with all of the options defined. It is hard to pinpoint an exact solution for your issue, but you can contact us via our official support channels [(listed here)](https://www.highcharts.com/blog/support/) where we will try to find the best solution for you.

Okay.
 
> > IMHO, every action which results in extremes being changed should be addressed in the API docs with detail like you have given above.
> 
> In most cases when the `e.trigger` is not defined in `afterSetExtremes`, the extremes' change is caused by rerendering of the chart. When axis extremes are not defined in the config, they are calculated based on the series' min/max values, which might change when adding/ removing a series, changing the visibility of them, and some other data manipulations. It is mentioned in the API here: https://api.highcharts.com/highcharts/xAxis.max and all of the other changes are natural logical continuations. It could be mentioned in some general docs, e.g. here: https://www.highcharts.com/docs/chart-concepts/axes

I've read and reread all of those docs, but thanks for pointing me to them again. I'm pretty sure that I have a good understanding of the basics of what the docs indicate triggers setExtremes/afterSetExtremes. My point is that the docs do not detail enough about what triggers/calls result in undef. and examples of how to handle them in general. Your fiddle was very helpful in several ways. It is just not scalable if one needs to handle multiple causes of e.target == undefined. Though I suppose that we could write an extension of some sort to call to set a var indicating which of our actions triggered the call to begin with.

Still, being able to pass in something like:

```chart.redraw(true, 'triggeredByFoo')```

might be cleaner.

So we could have this: ```redraw( [animation], [trigger] )``` Where ```trigger``` is an optional string used to set e.trigger.

This could be extended to other methods which trigger a redraw.

At any rate, your proposed workaround does offer one solution.

> Would that work for you? Then I could add a new feature request to update the docs with the description of the axes' extremes.

Any addition to the current docs would be helpful, I believe.

Thanks.

**Comment by pawellysy** [comment]
Sorry! Here is the link: https://api.highcharts.com/highstock/navigator.adaptToUpdatedData

> Still, being able to pass in something like:
`chart.redraw(true, 'triggeredByFoo')`
might be cleaner.
It might, but I think that this would need to be extended to all of the redraw calls to follow the correct structure, and I honestly think that it is a bit overcomplicated, and might be solved much easier. 
I will reopen the ticket though, and we will see if there will be more requests to add such a feature. Apart from that please, reach out to us via support channels, so that we could suit the solution for your needs. 



PS: I will create a new issue to add a part of the docs about axis extremes.
