### ISSUE TITLE
Heatmap causes dual y-axes to not align

### ISSUE THREAD

**Issue by GeoffArmstrong** [highcharts/highcharts#17071]
#### Expected behaviour
Dual y-axes should align, should use the same gridlines, by default.

#### Actual behaviour
In this case, y-axes do not align.

#### Live demo with steps to reproduce
[Here is a JSFiddle that demonstrates the issue](https://jsfiddle.net/mrmills/2yhfr9xb/)

#### Product version
Originally found in product that uses Highstock 9.12
JSFiddle above uses current version of Highcharts (code.highcharts.com/highcharts.js)

#### Affected browser(s)
Seen in Chrome and Edge, but does not seem to be related to those

#### Suggested method to fix
The problem seems to be in Axis.prototype.setAxisTranslation where transA and transB are being set incorrectly on heatmap's y axis. This seems to be because heatmaps have a pointRange through their colsize, but this is interfering with the calculation of the y axis translation (it should only affect the x axis on a heatmap).

I applied the following hotfix code which fixes my particular case by changing how y-axes are calculated.

Original code in Axis.setAxisTranslation:
```
                axis.translationSlope = axis.transA = transA =
                    axis.staticScale ||
                        axis.len / ((range + pointRangePadding) || 1);
                // Translation addend
                axis.transB = axis.horiz ? axis.left : axis.bottom;
                axis.minPixelPadding = transA * minPointOffset;
```

Patched code that only applies pointRangePadding and minPointOffset on horizontal axes.
```
                axis.translationSlope = axis.transA = transA =
                    axis.staticScale ||
                        axis.len / ((range + (axis.horiz ? pointRangePadding : 0)) || 1);
                // Translation addend
                axis.transB = axis.horiz ? axis.left : axis.bottom;
                axis.minPixelPadding = axis.horiz ? transA * minPointOffset : 0;
```

A comprehensive fix would do this properly (this particular patch would probably break Gantt charts, for instance).

**Comment by pawellysy** [comment]
Hi @GeoffArmstrong, thanks for creating the issue!

**Comment by raf18seb** [comment]
Hi @GeoffArmstrong!

You were very close. This is coming from the fact that both axes have different axis pointRange and it's actually set from `rowsize`, not `colsize`: https://github.com/highcharts/highcharts/blob/be9e354d4b9be46bcbda0043c87dfae129e365b2/ts/Series/Heatmap/HeatmapSeries.ts#L502

Your workaround (https://jsfiddle.net/BlackLabel/9cs3dray/) is feasible, but I don't like that the extremes so calculated so strangely - why max is 160 when the heatmap ends at 72?
![image](https://user-images.githubusercontent.com/23310742/158012326-bce047ad-b383-4ddf-bbcb-8bf8217f09ff.png)
 

I would rather override (or, being more specific: stop overriding) the default `axisPointRange` - it makes more sense to me and the extremes make more sense: https://jsfiddle.net/BlackLabel/0ufwxd8a/
![image](https://user-images.githubusercontent.com/23310742/158012488-b6e4f4d8-526d-4416-960c-a5ec19ead9b9.png)


However! I don't think it's a bug, to be honest. Our both workarounds make the `yAxis.min` and `yAxis.max` to start/end in the middle of a cell - that's why the `axisPointRange` is set to `rowsize` in the first place on the heatmap series init. Your demo is working fine because the `rowsize` is set to 36, when your first point starts with `y: 18`, but it would break most of other heatmaps.
That's why I'm leaving it as undecided for this moment.

**Comment by GeoffArmstrong** [comment]
Hi @raf18seb,

> I don't like that the extremes are calculated so strangely - why max is 160 when the heatmap ends at 72?

I didn't force any maximum values. Those maximums were what Highcharts chose. I gave it a heatmap on one y-axis, and a line series on a different y-axis, and said both y-axes should start at zero. So why is Highcharts choosing 160 as a maximum? Why does it have one zero floating off in space? I don't know. I have to set rowsize and colsize on the heatmap series so Highcharts knows how big to make the heatmap pieces. And sure, I'd like to have the heatmap piece anchored at the bottom left (e.g. (0, 0)) rather than in the middle (e.g. (1800000, 18)) but in the code, heatmap pieces just seem to like to be anchored in the middle, so that's why the y-coordinate of the heatmap piece that goes from 0 to 36 gets a value of 18.

Ideally, I should be able to use my original code, with no workarounds, and Highcharts should give me reasonable y-axes that share ticks and include the given heatmap data rectangles, and that's not happening, so that's why I see it as a bug.

For now, setting `(chart.yAxis[0] as any).axisPointRange = 0;` after the initialization seems to be a workable fix.
