### ISSUE TITLE
Columns of column chart float above x-axis when using datetime y-axis

### ISSUE THREAD

**Issue by robbertbrak** [highcharts/highcharts#17084]
#### Expected behaviour

In a column chart, it is expected that the bottom of each column starts on the x-axis.

#### Actual behaviour

In some cases, when using a datetime y-axis, the columns of a column chart float 20 or 30 pixels above the x-axis.

#### Live demo with steps to reproduce

See the following JSFiddle: https://jsfiddle.net/robbertbrak/xnd6mwhq/1/

#### Product version

Highcharts v10.0.0, but this bug is also present in most older versions of Highcharts.

#### Affected browser(s)

Not browser dependent. It can be reproduced in Firefox, Chrome, Safari.

#### Notes

This is related to https://github.com/highcharts/highcharts/pull/9344.

The issue can be fixed by added `Math.max(1, ...)` around the `time.get('Date', ...)` expression here: https://github.com/highcharts/highcharts/blob/master/ts/Core/Time.ts#L745.

**Comment by robbertbrak** [comment]
Screenshot illustrating the issue:

<img width="924" alt="image" src="https://user-images.githubusercontent.com/734581/158124967-2f1e05e5-427e-4921-8cce-2215d0645943.png">

**Comment by raf18seb** [comment]
Hi @robbertbrak,

thank you for reporting a bug.

**Comment by robbertbrak** [comment]
@raf18seb: I noticed that you added the label "Status: Has workaround". Could you share what the workaround is?

**Comment by TorsteinHonsi** [comment]
> the sensible default seems to be false instead of true.

I agree for this case. I am not sure how representative it is though. We could consider making it `false` instead of `true` for all datetime axes. But there would also be downsides:

* We would risk changing the behaviour of charts already in production for clients - for example those having a datetime y-axis showing hours of the day where the threshold should be midnight.
* The default would become more complicated. Like `false` for x-axes, but `true` for y-axes except datetime types.
