### ISSUE TITLE
Scrollbar is not working properly for number-series chart when logarithmic scale is enabled on X axis

### ISSUE THREAD

**Issue by PurvaK17** [highcharts/highcharts#17104]
#### Expected behaviour
Scrollbar should work properly for number-series chart when logarithmic scale is enabled on X axis. Scrollbar is not seen to be moving using cursor

#### Actual behaviour
Scrollbar is not working properly for number-series chart when logarithmic scale is enabled on X axis

#### Live demo with steps to reproduce
https://jsfiddle.net/wjk8391L/2/

**Comment by pawellysy** [comment]
Hi @PurvaK17 Thank you for reporting this bug!

Simplified demo: https://jsfiddle.net/BlackLabel/3kevr901/

**Comment by raf18seb** [comment]
I wouldn't consider it as a bug. Scrollbar is included in Highcharts Stock only. Highcharts Stock xAxis is a `datetime` type only. So the scrollbar feature was designed to work with a `datetime` axis only.

**Comment by pawellysy** [comment]
@raf18seb scrollbar can be used on the yAxis tho
 https://jsfiddle.net/BlackLabel/yg8h01u5/1/

**Comment by raf18seb** [comment]
Right!

**Comment by jiigen3343** [comment]
Coming over from #22800 I want to add my comments on why I think at least for y scales we need scrolling on logarithmic scales, even if there was reluctance in the past.
 
Our use case; we have a boxplot of multiple data sets that the end user wants to compare on the same plot. Sometimes those data sets differ in magnitude enough that if they do not use a log scale one or more of the boxes is not very usable because it is crushed to almost zero height by the other data set, so a log transform can help the visualization.
 
At the same time, we also use a scatter series to plot outliers above and below the boxplot but since the points can be dense and the plot has been put through a log transform zooming in to get a clearer picture of these outliers is something we want to provide. If we can zoom in, then we need to be able to pan around afterwards.
 
So in our use case we have a logarithmic y-scale and a categorical x, we are really not a stock chart but to access scrollbars we need to use Highstock. We are actually using the scrollbars to pan around in the users data after a zoom (our user design group hates (optional key) + click + drag to pan so while that might work it is not really a solution I can use).
 
Here is a rough example adapted from the documentation boxplot example: https://jsfiddle.net/ybp8g9sd/1/
 
As mentioned in the duplicate bug I have tracked the issue down to:
 
https://github.com/highcharts/highcharts/blob/master/ts/Core/Axis/ScrollbarAxis.ts#L104
 
as well as the default scroll changed handler:
 
https://github.com/highcharts/highcharts/blob/master/ts/Core/Axis/ScrollbarAxis.ts#L178
 
The Issue on the getExtremes side is the units for the data min and max and the users options if they exist will be in non-linear units (real data units), but the rest of the values will be in linear units (units after the log transform). Since those values go into Math.min/Math.max calls and thier magnitudes are so different it will not work.
 
The opposite will be true in the changed handler. The final call to axis.setExtremes expects values in non-linear units, but all of the values it uses to compute it are in linear units.
 
Currently we have provided our own implementations of these functions to work around the issue, but would love to not have to handle this as overriding some of this feels odd.
 
Sorry for the wall of text but I wanted to make my case for why we feel this is an important use case.
