### ISSUE TITLE
Bug with multi-series and range selector

### ISSUE THREAD

**Issue by govinda18** [highcharts/highcharts#17118]
#### Expected behaviour
Year to date should start from the current year

#### Actual behaviour
Year to date with multi-series chart seems to take the last date of the previous year as well. This causes some issues when you try to process a few things based on set extremes.

![image](https://user-images.githubusercontent.com/25079291/159629964-ebaf06aa-1422-4fc7-bd99-09ac35311fbd.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/4afbqujg/

#### Product version
Highstock v10.0.0

#### Affected browser(s)
Chrome

**Comment by govinda18** [comment]
I think the issue is with ordinal. Setting it to false seems to fix the issue - https://jsfiddle.net/onx8y9uk/. But I have weekdays data and I want it true.

For now, I can work around it using breaks I think (not sure if it will cause issues with my setExtremes events).

**Comment by raf18seb** [comment]
Hi @govinda18, thank you for reporting a bug!

Simpler demo: https://jsfiddle.net/BlackLabel/3vrfcdxb/

**Comment by TorsteinHonsi** [comment]
@raf18seb @pawelfus Will you prioritize this?

**Comment by karolkolodziej** [comment]
I'm not sure if this should be classified as a bug.

From what I can see it looks like the issue is connected with the `column` series and the [pointPlacement](https://api.highcharts.com/highstock/series.column.pointPlacement) property.
[I tested that with two line series ](https://jsfiddle.net/BlackLabel/ygv20tu7/) and it works correctly out of the box.

Also by setting `pointPlacement` property, we can avoid that issue- [demo](https://jsfiddle.net/BlackLabel/504mdtfx/).
With that, no additional padding is added to the axis.

The fact that `ordianal: false` works, in this case, is just a coincidence caused by some math rounding.

@TorsteinHonsi  any thoughts?

**Comment by pawelfus** [comment]
Hi @govinda18 

Could you provide us with a little more details? What do you mean by processing things based on extremes? In the demo you created, the extremes are correct:
```js
> new Date(Highcharts.charts[0].xAxis[0].getExtremes().min)

Sat Jan 01 2022 01:00:00 GMT+0100 (czas środkowoeuropejski standardowy)
```

The issue is not related to the `ordinal` xAxis, as Karol said. Creating a chart with a specific dataset will show the issue, for example: https://jsfiddle.net/BlackLabel/38hn9fsw/1/ And it's directly caused by space reserved by columns, to prevent them from being cut off on the edges

In the demo above, you can observe an "extra" hoverable point for linear series. This happens because we render two extra points to show the continuity of the line, so users could see there are points outside the visible range. We don't do this for column series, thus column series does not show an extra point.

It is possible to work around the issue: the line series can behave the same way as the column series, rendering only visible points.

Plugin:
```js
Highcharts.seriesTypes.line.prototype.cropShoulder = 0;
```

Demo with the plugin: https://jsfiddle.net/BlackLabel/au9jorpx/

Let us know if the plugin solves the issue, thank you

**Comment by govinda18** [comment]
Thanks a lot @pawelfus - I understand the issue now. 

So we were internally adding a custom indicator on set extremes, computed on selection but taking an index just before the min, basically something like `const minIndex = _.findIndex(series.data, (point) => point[0] > xMin) - 1;`. Usually only the points after xMin were visible and this worked fine - but now that I think about it, we should be doing `const minIndex = _.findIndex(series.data, (point) => point[0] >= xMin)` instead. 

However, this breaks the continuity of the line (iiuc this is the reason why highcharts renders two extra points). This will be the case only when the extremes set start on a null point (weekend for this year).

I will think a bit more and check internally with my team on what exactly should be the behaviour here. Thanks for the plugin though - I think should be good to close as I feel this the reply above should suffice our usecase.

If you have any thoughts on how to handle set extremes and indicator series updates more elegantly, they would be really helpful.

Thanks.

**Comment by govinda18** [comment]
Also, one more thing I wanted to check on. Can adding this plugin have some potential issues in the visualization like the series is not drawn at the start.

If so, can you please provide some hints on the cases where it may break

**Comment by pawelfus** [comment]
> Also, one more thing I wanted to check on. Can adding this plugin have some potential issues in the visualization like the series is not drawn at the start.
> 
> If so, can you please provide some hints on the cases where it may break

No, the issue shouldn't be related to the plugin. There is one case when the plugin will change rendering: cropped points no longer affect the extremes: https://jsfiddle.net/BlackLabel/38hn9fsw/5/

> If you have any thoughts on how to handle set extremes and indicator series updates more elegantly, they would be really helpful.

I don't know the details of the indicator, but you may want to use `series.cropStart` (it's index of the first point on the chart, so it might be the same value as `minIndex - so it should be faster).

**Comment by govinda18** [comment]
Thanks @pawelfus. That was helpful. Closing this
