### ISSUE TITLE
Highcharts 10 proj4 chart option no longer works

### ISSUE THREAD

**Issue by mjchang** [highcharts/highcharts#17139]
#### Expected behaviour
Highcharts v10 works with proj4 passed as a chart option. This was previously working in v9. The [changelog](https://www.highcharts.com/changelog/#highcharts-v10.0.0) does not mention anything about this option no longer being supported.

#### Actual behaviour
Hovering over the map causes a `r.proj4 is not a function` error.

#### Live demo with steps to reproduce

In this example, the chart has proj4 passed in as options but when you hover over the map, you can reproduce the above error.
https://codesandbox.io/s/highcharts-react-simple-chart-forked-9k4hcq?file=/demo.jsx

- If you comment in the that sets `window.proj4`, hovering over the chart works as expected
- If you downgrade to highcharts v9.3.3, the chart hover works as expected without `window.proj4` set

#### Product version

Highcharts 10
React Highcharts 3.1

#### Affected browser(s)
All

**Comment by raf18seb** [comment]
Hi @mjchang, thank you for reporting the issue!

Simplified pure JS demo: https://jsfiddle.net/BlackLabel/o5spbnyL/

The problem is where `proj4` is being taken from `window` object, where it should be taken from a variable declared on top of this function's body.
Here: https://github.com/highcharts/highcharts/blob/53b04dca4c74d0092f691ce36a3c9a7a6ddeba90/ts/Extensions/GeoJSON.ts#L387

The funny fact is that the `transformFromLatLon` works fine, the problem occurs only in the `transformToLatLon` method.

Workaround: https://jsfiddle.net/BlackLabel/q4gdorxa/

**Comment by SpoorthySrinivas** [comment]
I would like to work on this issue
