### ISSUE TITLE
Exporting in Styled Mode: fails on Chrome (iPad & iPhone)

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#17140]
#### Expected behaviour
Exporting works fine.

#### Actual behaviour
Impossible to download a file using Chrome on iPad or iPhone (Sarafi works fine).

#### Live demo with steps to reproduce
https://www.highcharts.com/samples/highcharts/css/exporting

#### Product version
Highcharts 10.0.0

#### Affected browser(s)
Chrome (iPad or iPhone)

@edw1n could you please provide your current versions of iOS/ipadOS? Thanks in advance!

Continuation of https://github.com/highcharts/highcharts/issues/16791
And related to this PR https://github.com/highcharts/highcharts/pull/16902

**Comment by edw1n** [comment]
@raf18seb 

Thanks for raising this issue.

the bug can be reproduced on  iOS 15.3.1 / iPadOS 15.4

thanks.
Edwin

**Comment by svensigmond** [comment]
This issue can be closed as it seems to be a duplicate of: https://github.com/highcharts/highcharts/issues/16483

**Comment by karolkolodziej** [comment]
Let's keep this issue open because we tried to make sure if that is correct what you are saying and we came to a few conclusions:
- On iOS 15.4.1 and Highcharts v10.0.0, v.10.1.0, and 10.2.0 this issue was not replicable at all (tested in Chrome and Safari)
- On iOS 15.6 this issue is still visible both on Safari and Chrome
