### ISSUE TITLE
Line series animation is desynchronized when zones are applied 

### ISSUE THREAD

**Issue by bm64** [highcharts/highcharts#17147]
#### Expected behaviour
Line and markers in line series should animate simultaneously when zones are applied.

#### Actual behaviour
Line and markers animation seems to be desynchronized when zones are applied.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/kj8n9q2d/

#### Product version
Highcharts v10.0.0

#### Affected browser(s)
N/A

**Comment by raf18seb** [comment]
Hi @bm64, thanks for creating the ticket!

Zones animation has never worked. It's because the multicolor line is created from multiple elements and they are all destroyed and recreated as a new elements when updating the series.
Points were also destroyed before v7.1.0 so there was no animation at all.

Since v7.1.0 and this PR: https://github.com/highcharts/highcharts/pull/10256, points are kept and can be animated. You can disable point's animation e.g. by setting `keepPoints` flag in the `series.update()` method to `false`. To do that, you can e.g. set ```js
Highcharts.seriesTypes.line.prototype.hasDerivedData = true;
```

Demo: https://jsfiddle.net/BlackLabel/yrakxphg/

Now the behavior is consistent and synchronized. However, the animation of a series with zones will obviously not work.
I'm closing the ticket because of the above.
