### ISSUE TITLE
"hasGroupedData" with multiple series does not return the right status

### ISSUE THREAD

**Issue by ernstfabian** [highcharts/highcharts#17141]
#### Expected behaviour
Returning "true" or "undefined" when calling "hasGroupedData" on a series, depending if the data is currently beeing grouped.

#### Actual behaviour
When two or more series are displayed, it always returns "true" once it returned "true" at least once.  
When there is only one series inside the graph it works as expected - returns "true" when the data is beeing grouped and "undefined" when zoomed in far enough where grouping is not applied. Also returns back to "true" when you reset the zoom and back to "undefined" when zoomed in again.

#### Live demo with steps to reproduce
[Stackoverflow](https://stackoverflow.com/questions/71687888/highcharts-get-if-data-is-currently-beeing-grouped-with-multiple-series)
[https://jsfiddle.net/Itsearnest/ho0a4zw9/](https://jsfiddle.net/Itsearnest/ho0a4zw9/)

#### Product version
Highstock v10.0.0 

#### Affected browser(s)
Tested on Firefox, Chrome and Edge

**Comment by karolkolodziej** [comment]
Works well in version 9.1.2: https://jsfiddle.net/BlackLabel/jfg1zh8a/

Internal note: 
Bisected to commit 2f23d6afab

The `getGroupPixelWidth` in the `applyGrouping` method returns a value greater than zero when it shouldn't. 
Then based on that knowledge the grouping is being applied.

Before the `getGroupPixelWidth` the `groupPixelWidth` is reset but only for the current series.
Because of that `getGroupPixelWidth` falsely take the `groupPixelWidth` from the previously calculated series.
Where previously means previous extremes and different arrangement of points unrelated to the current state of chart and series.
https://github.com/highcharts/highcharts/blob/53b04dca4c74d0092f691ce36a3c9a7a6ddeba90/ts/Extensions/DataGrouping.ts#L1173-L1182

The suggested fix is to apply code from the snippet below before the group pixel calculation.
```
series.forEach(function(series) {
   series.groupPixelWidth = void 0;
})
```
