### ISSUE TITLE
Legend title is visible when there is no data in chart 

### ISSUE THREAD

**Issue by rrimmana** [highcharts/highcharts#17167]
#### Expected behaviour
Legend title should not be show when chart has no data
Behavior should be similar to Legend items/ series names.
#### Actual behaviour
Legend title is shown even when no data is present in chart

#### Live demo with steps to reproduce

[http://jsfiddle.net/L7cnkg98/](https://urldefense.com/v3/__http:/jsfiddle.net/L7cnkg98/__;!!Obbck6kTJA!OT680xgTU3IRhrL-UAlI0SNq2mc1VHurzfGS9RIciAx0mbOLIzj_p_EVt44HJ1px$)
#### Product version

Latest version
#### Affected browser(s)
chrome,FF, edge

**Comment by pawellysy** [comment]
Hello @rrimmana, thanks for reporting this bug.

Simplified demo: http://jsfiddle.net/BlackLabel/tpc7ugx2/2/

##### Workaround
http://jsfiddle.net/BlackLabel/tpc7ugx2/3/

`internal note`

The legend group has no visibility attribute. Probably, instead of hiding the `legend.box` we could replace it with `legend.group`.

https://github.com/highcharts/highcharts/blob/fcad6ce86501a29c021b343ed997ec3c57005dd1/ts/Core/Legend/Legend.ts#L1203
