### ISSUE TITLE
Wrongly positioned shadows while using the offline export.

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#17170]
#### Expected behaviour
Properly position the shadows while using offline exporting.

#### Actual behaviour
After exporting the chart to PDF via offline exporting, `dataLabels` are shifted and shadows are incorrectly positioned.

#### Live demo with steps to reproduce
Export the chart to PDF and compare the result with the chart.
https://jsfiddle.net/BlackLabel/23ks15d0/

Workaround (disabling the shadows): https://jsfiddle.net/BlackLabel/jtr6382u/

#### Product version
 Highcharts JS v10.0.0 (2022-03-07)

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
Here's the issue broken down to svg2pdf [Svg2pdf Playground](http://raw.githack.com/yWorks/svg2pdf.js/master/index.html?svg=%253Csvg%2520viewBox%253D%25220%25200%2520300%2520150%2522%2520xmlns%253D%2522http%253A%252F%252Fwww.w3.org%252F2000%252Fsvg%2522%253E%250A%2520%2520%253Ctext%2520font-size%253D%252220px%2522%2520y%253D%252220%2522%2520x%253D%252220%2522%253E%250A%2520%2520%2520%2520%253Ctspan%2520fill%253D%2522silver%2522%253E%250A%2520%2520%2520%2520%2520%2520Hello%252C%2520world%21%250A%2520%2520%2520%2520%2520%2520%253Ctspan%2520y%253D%252220%2522%2520x%253D%252220%2522%253E%25E2%2580%258B%253C%252Ftspan%253E%250A%2520%2520%2520%2520%253C%252Ftspan%253E%250A%2520%2520%2520%2520Hello%252C%2520world%21%253C%252Ftext%253E%250A%253C%252Fsvg%253E).

As we see, in the browser implementations of SVG, the absolutely positioned `tspan` with x and y coordinates and a zero width space causes the text cursor to be reset to the beginning of the `text` element, causing subsequent text to be laid out on top of the existing text. The svg2pdf implementation fails to reset the cursor position. 

It also fails to render the `&ZeroWidthSpace;` character, which may be because of missing support in the PDF built-in font files. But this specific character could potentially just be skipped.

**Comment by karolkolodziej** [comment]
The issue has already been [reported here](https://github.com/yWorks/svg2pdf.js/issues/192).
