### ISSUE TITLE
Broken links in your API

### ISSUE THREAD

**Issue by vivactis** [highcharts/highcharts#17213]
Hello,

For information, there are some broken links in : 
https://code.highcharts.com/mapdata/

For example :
https://code.highcharts.com/mapdata/custom/world-robinson.topo.json
https://code.highcharts.com/mapdata/custom/world-robinson-lowres.topo.json
https://code.highcharts.com/mapdata/custom/world-robinson-highres.topo.json

Best regards,

**Comment by raf18seb** [comment]
Hi @vivactis, thank you for reporting the issue!

**Comment by KacperMadej** [comment]
Fixed by removing the links that were wrong (TopoJSON for World's map with projections: Robinson & Eckert).

[TopoJSON world maps](https://code.highcharts.com/mapdata/) (multiple resolutions available) can have projection defined on the chart level via [mapView.projection](https://api.highcharts.com/highmaps/mapView.projection). Robinson projection can be added as a custom definition - [demo](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/mapview/projection-custom-d3geo).
