### ISSUE TITLE
Highcharts column chart horizontal axis can not set gradient color using crosshair

### ISSUE THREAD

**Issue by LQS5858** [highcharts/highcharts#17220]
#### Product version

    "highcharts": "^8.1.2",

**Comment by pawellysy** [comment]
Hello @LQS5858, thanks for creating the issue. 
Unfortunately, we can't investigate the issue without access to your chart configuration. Could you please create a live demo, where your issue is reproduced so that we could debug it? 

You can start here: https://jsfiddle.net/BlackLabel/9b1p5vkn/

PS: When reporting the bug, please use our template :)
