### ISSUE TITLE
highstock can't set crosshair gradient

### ISSUE THREAD

**Issue by LQS5858** [highcharts/highcharts#17242]
#### Live demo with steps to reproduce

https://jsfiddle.net/Ricardo_lqs/362bsLyh/9/
#### Product version

 Highstock JS v10.0.0 (2022-03-07)

**Comment by pawellysy** [comment]
Hello @LQS5858, thanks for contacting us with your issue.
I guess this is a feature request to be able to add the gradient to the crosshair. Currently, this feature is not available through the API.

#### Workaround

As a workaround, you can overwrite the position of the crosshair, so that it is not a vertical line. This causes the gradient to show. 
https://jsfiddle.net/BlackLabel/m5kg1frp/1/
