### ISSUE TITLE
Highcarts XAxis Label Categories "step" seems to be buggy

### ISSUE THREAD

**Issue by LionyxML** [highcharts/highcharts#17262]
#### Expected behaviour
I would like my categories label to be shown in a step of 400 (of 1260 datapoints).

#### Actual behaviour
If I set step to: 400, it only seems to work if I resize the entire chart to a screen bigger then 1400px:

![image](https://user-images.githubusercontent.com/16169950/167223247-e9410d71-59d3-4a58-a2f8-ca4659150ff6.png)

If I decrease the width under that, this happens:
![image](https://user-images.githubusercontent.com/16169950/167223322-f263fdeb-01d7-4b8b-b59f-75c983da93de.png)

Only the first value is shown.

If step is 0 or undefined it "works" in automatic steps:
![image](https://user-images.githubusercontent.com/16169950/167223404-80b3c890-1961-4bdc-b8de-8d0707fbd3ea.png)

I also have a dataset with 5000+ points that I have no monitor space to even begin to show the second step :(

I also noticed that "step" seems to work ok with something around 600 points.

I spend my entire Friday on it. Any help? Please tell me I am doing something really silly :)

#### Live demo with steps to reproduce
https://jsfiddle.net/k6gfy3cr/

#### Product version
Highcharts 10.1.0

#### Affected browser(s)
Google Chrome 101.0.4951.54

**Comment by pawellysy** [comment]
Hi @LionyxML, thanks for your question. 
Unfortunately, this repository is used as a bug/feature request tracking tool. With the support questions such as yours, please contact us via one of our support channels listed here: https://www.highcharts.com/blog/support/
Thank you for your understanding!

PS: When dealing with x/y data, where the x coordinate is a simple date, using the category xAxis type is an antipattern. A better solution is to pass the x value as a js timestamp (value of milliseconds passed since 1/1/1970) and then use the xAxis.labels.formatter to parse this value to the correct form. Here is an example: https://jsfiddle.net/BlackLabel/vhujnm3p/1/

**Comment by LionyxML** [comment]
@pawellysy thanks a lot!

I'll keep the support channels in my bookmarks. Meanwhile, your example implementation helped me a lot! It works and works faster. Thanks again!
