### ISSUE TITLE
Gannt headers not aligning properly

### ISSUE THREAD

**Issue by daniel-tabarcea** [highcharts/highcharts#17269]
#### Expected behaviour
Years in headers do not overlap 

#### Actual behaviour
Years 2018 and 2019 are overlapping 

#### Live demo with steps to reproduce
~https://jsfiddle.net/dnltbrca/afo0hu98/39/~
https://jsfiddle.net/dnltbrca/afo0hu98/43/

#### Product version
Highcharts 10

#### Affected browser(s)
Chrome 101

**Comment by pawellysy** [comment]
Hello @daniel-tabarcea, thanks for reporting the bug!
Simplified demo: https://jsfiddle.net/BlackLabel/t8q2jhLw/1/

**Comment by TorsteinHonsi** [comment]
I'm not sure I fully understand by the bug report. See https://jsfiddle.net/highcharts/ofurestp/

One potential problem is that both of the rows in the top rows show years, while we would expect that the first shows years and the second rows shows some more granular time unit, like quarters or months. What happens currently is that the top row shows two-year spans while the second row shows single years. It is correct, but perhaps not intuitive.

Another potential problem is that 2018 label in the second row is overlapping its cell.

Please advice on how you expect this to work.

**Comment by daniel-tabarcea** [comment]
I must've posted the wrong fiddle revision, apologies. 
https://jsfiddle.net/dnltbrca/afo0hu98/43/
This is the bug we're seeing. 
The fact that we're configuring two separate headers to show years is indeed quite odd, but we would expect the years in the header to overlap perfectly.

**Comment by TorsteinHonsi** [comment]
Thanks for the clarification @daniel-tabarcea ! One possible workaround is to [set the second row to always display months.](https://jsfiddle.net/highcharts/9rm7kuqn/). But by hard coding that you will loose the dynamic adaptation to different time spans.

To be honest I am not sure how to deal with this. What happens is that the bottom row is the primary X axis. This axis uses ticks of one year because that is the best match for its `tickPixelInterval` setting. The secondary axis (top row) is then programmed to render decades, as of #11427. However, since we're only looking at a small time range around 2020, the first decade is cropped to 2018-2019, and the second decade is just the first half of 2020. 

> we would expect the years in the header to align. IE, not to have 2018 and 2019 on top of each other.

The logic in play is that for the top row, since we're showing a range of years, the starting year renders at the beginning of the cell. While in the bottom row, each cell is one year, so it is centered.
