### ISSUE TITLE
Maps: mappoint's fill color is black when its value is NaN

### ISSUE THREAD

**Issue by wjaspers** [highcharts/highcharts#17279]
#### Expected behaviour
Highcharts 9.2.2 used the minimum color axis value for invalid values

#### Actual behaviour
Highcharts 10+ generates NaN for color axis values when data is invalid

#### Live demo with steps to reproduce
https://jsfiddle.net/Lhdes4gp/1/

#### Product version
HighMaps

#### Affected browser(s)
Any

**Comment by raf18seb** [comment]
Hi @wjaspers, thanks for creating the ticket.

It's hard to call it a bug. In general, `NaNs` are invalid values and using them might lead to unexpected behaviors.
We cannot say that the `NaNs` behavior was working "correctly" in 9.2.2, because you shouldn't use `NaN` values in the first place. Furthermore, this behavior wasn't documented anywhere and, in my humble opinion, using min colorAxis color for points with `NaN` values is more confusing than helpful.
Based on all of the above - I don't think we should add the logic to the core that would handle `NaN` values in the colorAxis.

What's interesting, I think the `NaN` points shouldn't be displayed at all - it should be an empty region similarly if we put a `null` value.
See this behavior in the Highcharts: https://jsfiddle.net/BlackLabel/vsoh9e51/
And compare to the Highcharts Maps: https://jsfiddle.net/BlackLabel/prnve3th/

So I'd say the bug here in Maps is that the `NaN` point shouldn't be created at all and should be treated similarly to a `null` point.

@KacperMadej please correct me if I'm wrong.

**Comment by wjaspers** [comment]
> It's hard to call it a bug.
Agreed. When I tested this with a jsfiddle, it became more apparent that `NaN` shouldn't get there in the first place. 

> using min colorAxis color for points with NaN values is more confusing than helpful.
I agree here. We happened to have a mistake where NaN was produced, and in 9.2 the minimum colorAxis value was shown.

> So I'd say the bug here in Maps is that the NaN point shouldn't be created at all and should be treated similarly to a null point (or, to be more precise, the mapData point's fill color shouldn't be set when its value is NaN).
:+1:

**Comment by KacperMadej** [comment]
I would call this visual indication for a bad value (NaN) an accidental feature, but seriously - there's now `fill="rgb(NaN,NaN,NaN)"` for those NaN values which is not so great.

Point's (for map series' point) validation is done like:
https://github.com/highcharts/highcharts/blob/22a44a87ba48211d01822e75f41135c50bdcb6ed/ts/Series/ColorMapMixin.ts#L59-L71

As Rafał wrote: 
>  NaNs are invalid values

Yes, so `isValid` should return `false` for points with `value` of `NaN`.
