### ISSUE TITLE
Bubble series bounded by z=0 causes points to disappear

### ISSUE THREAD

**Issue by cebamps** [highcharts/highcharts#17280]
#### Expected behaviour
Points in bubble series with z = 0 should be handled as any other point when computing the range of z values used for rendering.

#### Actual behaviour
When plotting multiple bubble series, a series whose minimum z value is 0 causes the computation of the global `z` scale to fail. This results in points falling out of the range and not being plotted at all.

I believe the issue is in those lines: https://github.com/highcharts/highcharts/blob/v10.1.0/ts/Series/Bubble/BubbleSeries.ts#L469-L470  If the running `zMin` or `zMax` is 0, the running minimum/maximum is forgotten and replaced with the current series' minimum/maximum in the loop.

#### Live demo with steps to reproduce
https://jsfiddle.net/5ns2ozma/

#### Product version
Highcharts v10.1.0

#### Affected browser(s)
Firefox, Chrome

**Comment by pawellysy** [comment]
Hello, @cebamps thanks for reporting this bug as well as a great demo and thorough debugging.
You are right, the issue is connected to the lines you pinpointed. 

### Workaround
Overwrite the `getRadii` method to use `pick` instead of the logical OR operator: https://jsfiddle.net/BlackLabel/7doLnme8/2/
