### ISSUE TITLE
Pie data labels get cut off when using multiline data labels 

### ISSUE THREAD

**Issue by arsinawaz** [highcharts/highcharts#17286]
#### Expected behaviour
It should show the data labels without getting cut off when using multi line data labels using formatting

#### Actual behaviour
Data labels get cut off when using multi line data labels using formatting
![image](https://user-images.githubusercontent.com/6444617/168025484-9595cc0e-aba1-417e-a03b-6e52e6323c6a.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/sf08wegz/5/

#### Product version
 Highcharts JS v10.1.0 (2022-04-29)

#### Affected browser(s)
Tested in
- Google Chrome Version 100.0.4896.127 (Official Build) (64-bit)
- Firefox 100.0 (32 bit)

**Comment by raf18seb** [comment]
Hi @arsinawaz, sorry for the late reply.

Could you provide a jsFiddle demo showing your issues? Thanks in advance.
In general, the pie's size should decrease to make a room for the dataLabels. You can also use a negative `dataLabels.distance` value to move them to the middle of a pie.

**Comment by arsinawaz** [comment]
Hi @raf18seb, 
I had added the fiddle when reporting the issue but for some reason it got removed.
Anyway here is the fiddle
https://jsfiddle.net/sf08wegz/5/

**Comment by raf18seb** [comment]
@arsinawaz thank you for sharing your demo.
Simplified version: https://jsfiddle.net/BlackLabel/07ome59y/

As I said in my previous comment:
> In general, the pie's size should decrease to make a room for the dataLabels.

In other words: Highcharts tries to make space for dataLabels by decreasing the pie's size. 

Now I can see that the size didn't decrease and didn't make a room for the dataLabels because you set it rigidly to `100%`. See demo with uncommented size: https://jsfiddle.net/BlackLabel/07ome59y/1/

So, unfortunately, you need to either remove `size: '100%'` and get a smaller pie, or you can move your dataLabels using the negative `distance` like in this demo: https://jsfiddle.net/BlackLabel/07ome59y/2/ or you can move your dataLabels manually using the `dataLabels.x` and `dataLabels.y` properties.

Unfortunately, there's no universal way.
