### ISSUE TITLE
Variwide fully draggable X, including resize

### ISSUE THREAD

**Issue by kweg-bcg** [highcharts/highcharts#17302]
# Description of the feature
Have the option for fully dragable X, including resize

# Library related to the feature
Highcharts variwide module

# Proof of Concept/Live example for the feature
<img width="609" alt="Zrzut ekranu 2022-05-17 o 14 23 10" src="https://user-images.githubusercontent.com/105722088/168810310-f7aac278-d423-4c0f-96c1-babd2c2b8367.png">
basically exact same behavior as with other drag and drops, hover over element shows handles and user is able to resize the element.

edit: better phrasing the feature
----

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by raf18seb** [comment]
Hi @kweg-bcg, thank you for creating a feature request ticket.

This seems like a nice feature. Dragging X isn't working in Variwide as expected because it only changes a specific column's position not adjusting other columns. Simplified demo of actual wrong behavior: https://jsfiddle.net/BlackLabel/ndtkfcpq/
