### ISSUE TITLE
Not showing a clean break at start/end of a polar chart (areaspline)

### ISSUE THREAD

**Issue by drmrbrewer** [highcharts/highcharts#17303]
Consider the following polar chart:

https://jsfiddle.net/dh31m7L6/

There seems to be an attempt to join the end point to the start point to create a complete curve.  This is fine, but just not what I want.  I'd like a clean break between start and end, without any attempt to wrap around.

It seems possible to create a clean break at the start/end by adding a null data value at the end:

https://jsfiddle.net/95ch0pw4/

OK so far.  But now switch to an `areaspline` series type:

https://jsfiddle.net/t9y08rhq/

Even with a `null` value added, there is no clean break.  It seems to have reverted to a form more similar to the first chart, with the curve at the final point bending around towards the first point, but the intermediate fill/curve is not the same.

I'd like a clean break with `areaspline`, i.e. with the fill starting at the first point and stopping at the final point, bounded by straight radial lines from the centre outwards, i.e. similar to the second example above with the fill bounded by the radial gridlines at 0 and 315 degrees.

Is this what is meant to happen with the final example above?  Is it even possible?

**Comment by raf18seb** [comment]
Hi @drmrbrewer,

We already have this options, it's called `series.connectEnds`, see demo without area: https://jsfiddle.net/BlackLabel/pmoaybxg/ and with area: https://jsfiddle.net/BlackLabel/xsezywoq/

API Reference: https://api.highcharts.com/highcharts/series.spline.connectEnds

It's not clearly visible in the above area chart because of the data values, but it looks much clearer when we change the first point's value to a higher number, see demo: https://jsfiddle.net/BlackLabel/y4Lr7n5b/

If you don't like the above effect, you can always use the `areasplinerange` series type, see demo: https://jsfiddle.net/BlackLabel/9x1ds7oh/

I'm closing this ticket as resolved.

Please remember that our GitHub is for tracking bugs and features only. If you have questions and you're not 100% sure whether something is a bug or not, then it would be better to contact our support engineers first on one of our dedicated support channels listed here: https://www.highcharts.com/blog/support/
Thank you for understanding.
