### ISSUE TITLE
Support `chart.minMargin` similar to `chart.margin` flexible after a certain threshold

### ISSUE THREAD

**Issue by rdp1414** [highcharts/highcharts#17342]
## Use Case
We use `highcharts` in variety of cases and one of them is:
1. Width of chart is kept around `400-450px`.
2. Pace a button at top-right position of chart:
    * We place a button at top-right position absolutely, but it overlaps with chart - See [fiddle](https://jsfiddle.net/nb3g264a/1/). 
    * To avoid overlap, we set [chart.marginTop](https://api.highcharts.com/highcharts/chart.marginTop) to some value - See [fiddle](https://jsfiddle.net/nb3g264a/2/).
3. Place legend at top of Chart - See [fiddle](https://jsfiddle.net/nb3g264a/3/). 

Till now, works well for less number of series with short series name.

## Problem
1. For long series names (and multiple series) legend overlaps with chart's plotarea and containing title, subtitle - See [fiddle](https://jsfiddle.net/4tjv2a9h/).
2. One might think that setting `marginTop` to `null` will shift chart's plotarea to prevent overlap, it does work - See [fiddle](https://jsfiddle.net/4tjv2a9h/1/).
3. But doing the above, causes overlap with top-right button for our base use cases - See [fiddle](https://jsfiddle.net/Lt0nkmyf/).

## Propose `minMargin` feature
Set `chart.minMarginTop` to `40` instead of `chart.marginTop` which behaves in a away of `chart.marginTop: null` (i.e. flexible and accommodate) after and over `40px` and set a hard min margin limit to `40` - See [fiddle](https://jsfiddle.net/jqLf0w1t/).

### Library related to the feature
Highcharts / Highcharts Stock / Highcharts Map.

**Comment by TorsteinHonsi** [comment]
Thanks for the proposal @rdp1414 !

I see the value for this particular use case, but implementing such an option would raise some questions, possibly leading to bloat: 
- If we have `chart.minMarginTop`, in order to be consistent we should also follow up with `minMarginRight`, `minMarginBottom`, `minMarginLeft`.
- And possibly `maxMargin` for the same four values.
- What about `chart.margin`?
- What about `chart.spacing`?

We could find workarounds for those questions, like for example simplifying the API to only support `chart.minMargin: [number, number, number, number]`. But still I a hesitant to work it into the core, because it doesn't seem to be frequently requested. That may of course change. 

For now I propose you implement this with a snippet:
```js
Highcharts.addEvent(Highcharts.Chart, 'getMargins', function () {
	if (this.options.chart.minMarginTop) {
		const diff = this.options.chart.minMarginTop - this.plotTop;
        if (diff > 0) {
        	this.plotTop += diff;
            this.plotHeight -= diff;
        }
    }
});
```

See it live on [jsFiddle](https://jsfiddle.net/highcharts/4ytdpbkn/). As far as I can see it works well with your use case.

**Comment by rdp1414** [comment]
Thank you Torstein for suggesting a solution. Let me try to make the solution work in my project.
