### ISSUE TITLE
Overscroll with multiple yAxis causes visual glitches when adjusting navigator

### ISSUE THREAD

**Issue by chunick** [highcharts/highcharts#17386]
#### Expected behaviour
For stock charts with multiple yAxis and an overscroll > 0, the navigator should be able to zoon in/out smoothly for the entire chart time span.

#### Actual behaviour
![bug-demo](https://user-images.githubusercontent.com/46545800/173410860-95654388-8c09-4b5e-9246-cc91bbeef07b.gif)

The width of the navigator rapidly increases and decreases as you scroll past the last data point, causing a flashing effect.
#### Live demo with steps to reproduce
https://jsfiddle.net/j7wgf5L6/

#### Product version
Highcharts/Highstock v9.3.0 and up

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
It's not related to the `overscroll` option. It's a general issue with redrawing a chart when yAxis labels show up and hide. When yAxes are hidden, it works fine: https://jsfiddle.net/BlackLabel/cotk3zu7/ (PS: there are two different values for `overscroll`, is this intentional?) Or just one yAxis with different labels' widths: https://jsfiddle.net/BlackLabel/cotk3zu7/1/ (scroll to the middle).

Everything is related to dynamic margins, so the solution is to use fixed margins, for example: https://jsfiddle.net/BlackLabel/8kmjpohs/

A workaround could be to disable the `scrollbar.liveRedraw` so we won't see it: https://jsfiddle.net/BlackLabel/mzy2v867/

*Internal note:*
Tried to set a fixed width for the navigator (when dragging one of the handles): https://jsfiddle.net/BlackLabel/hanrzfy3/ - it works, however, the xAxis still adapts to extremes, just like the top one.

**Comment by chunick** [comment]
The two different overscroll values in the demo was unintentional. I would like to keep the live redraw feature, and fixed margins is not possible due to our charts having a dynamic number of series.

**Comment by gbenthomas** [comment]
Is there a possible workaround to make the y axis margins fixed while scrolling only? i.e. don't auto scale the y axes when scrolling with live redraw

**Comment by pawellysy** [comment]
@gbenthomas, I don't really understand what you mean. What are the margins, that you mention? And what do you exactly mean by `auto scale`? Could you please elaborate a bit more, and maybe share the demo, where there is something wrong? I

**Comment by gbenthomas** [comment]
> @gbenthomas, I don't really understand what you mean. What are the margins, that you mention? And what do you exactly mean by `auto scale`? Could you please elaborate a bit more, and maybe share the demo, where there is something wrong? I

I was referring to @pawelfus's comment that "Everything is related to dynamic margins, so the solution is to use fixed margins, for example: https://jsfiddle.net/BlackLabel/8kmjpohs/"

Since we can't use fixed margins all the time (as @chunick mentioned, we can't fix the margins since we have a dynamic number of series and the margins can change based on the current y axis scale due to auto scaling), I was asking if there was a workaround to use fixed margins or "lock" the margins *only* when scrolling with the navigator. 

Wouldn't disabling y axis min/max auto scale (to prevent dynamic margins) when scrolling with the navigator fix this?

**Comment by pawellysy** [comment]
It might be one of the workarounds. If manually setting min and max of y Axis work for you, then It seems reasonable to implement it like this. The same thing works for setting both yAxes opposite option to false. Does it work for you?

**Comment by gbenthomas** [comment]
Unfortunately, we can't set the min/max manually all the time or only use opposite: false (the user in our app can change all of these settings). I was asking if there was some workaround code you can provide for a way to "lock" the min/max at the time you start scrolling with the navigator and then "unlock" (goes back to automatically setting min/max) after you stop scrolling (on mouse up) on the navigator.

**Comment by pawellysy** [comment]
Unfortunately, there is no default way of implementing it. You can try doing that with some custom wrap.
Here is an article, where you can read more about custom wraps: https://www.highcharts.com/docs/extending-highcharts/extending-highcharts
or contact us via other available support channels ([listed here](https://www.highcharts.com/blog/support/))
But there is another workaround with [scrollbar.liveRedraw=false](https://jsfiddle.net/BlackLabel/mzy2v867/2/)
Does this work?
