### ISSUE TITLE
Crash in Highcharts (v9.2.0 onwards)

### ISSUE THREAD

**Issue by krispy-visokio** [highcharts/highcharts#17383]
#### Expected behaviour

Create a scatter view with a datetime axis. Allow a small chart width.

#### Actual behaviour

When the width is small, a crash occurs

#### Live demo with steps to reproduce

Open this fiddle to see the crash

https://jsfiddle.net/chrisvisokio/o59a0k67/

#### Product version

Crash occurs in 9.2.0 onwards. It works in 9.1.2.

**Comment by karolkolodziej** [comment]
Thank you @krispy-visokio for reporting that issue!

This issue is already fixed. Changes are available on the master branch. 
Soon they should be included in the next release.
Demo with master branch: https://jsfiddle.net/BlackLabel/r6u73281/

_Internal note:_
Broken by commit 3433ef9279 then fixed by commit a7ab03128b
