### ISSUE TITLE
Space is reserved for yAaxis labels with align: 'right' even when labels are not enabled

### ISSUE THREAD

**Issue by drmrbrewer** [highcharts/highcharts#17397]
The following demo has two x axes and two y axes:

https://jsfiddle.net/tm5rjfu7/

The `axis.visible` and `labels.enabled` properties of the *second* x/y axes are controlled by the two variables at the top.

When the second x/y axes are visible, but with labels disabled (as per the above demo), the space for the second y axis closes up, but space for the second x axis is *still reserved*, despite the labels being disabled.

Of course, it's possible to set `axis.visible` to `false` to close up the space even on the second x axis, but the inconsistency between x and y axes regarding whether space is reserved for disabled labels seems like a bug?

**EDIT** I have now realised that it's *not* possible simply to set `axis.visible` to `false` to close up the space because this will have a knock-on effect on features that are attached to this axis, like `plotBands`:

`axis.visible: true`: https://jsfiddle.net/L3vfo2p1/ --`plotBands` visible 👍
`axis.visible: false`: https://jsfiddle.net/L3vfo2p1/1/ -- `plotBands` gone 👎

I can see now that there is a [documented difference](https://api.highcharts.com/highcharts/xAxis.labels.reserveSpace) between x and y axes in terms of `reserveSpace`... but even setting `reserveSpace` explicitly to `false` doesn't solve my problem:

https://jsfiddle.net/L3vfo2p1/2/

The space for the labels of the second x axis is still there, despite `labels.enabled: false` and `labels.reserveSpace: false`?

**Comment by raf18seb** [comment]
Hi @drmrbrewer, thanks for bringing this topic up.

I think it's working fine. In your specific case, the labels on the y axis need space to be rendered when the labels on the x axis don't need additional space because you set `xAxis.labels.x: 0` and `xAxis.labels.y: 0` (the labels are not displayed below x axis line so they don't need additional space. See demo with and without `x: 0, y: 0`:
With `x: 0, y: 0` (labels don't need additional space): https://jsfiddle.net/BlackLabel/6nr537uk/
Without `x: 0, y: 0` (labels need additional space so the space is added): https://jsfiddle.net/BlackLabel/oxgq8zrn/

The same with y axis if you change `yAxis.labels.align: 'left'/'right'`:
Align right (default): https://jsfiddle.net/BlackLabel/9ygn60uo/
Align left: https://jsfiddle.net/BlackLabel/82qy1sr4/ (doesn't matter if labels are enabled or disabled, the space is not needed so Highcharts doesn't add space

So I think it's not a matter of inconsistency between y and x axes, but it's a matter of a fact whether a space is actually needed or not.

Does it make sense? 🤔

**Comment by raf18seb** [comment]
Oh, I thought about the `offset` in the first place, but then unnecessarily dug into it deeper and indeed maybe missed the basics.
Please try to set [xAxis.offset](https://api.highcharts.com/highcharts/xAxis.offset) to 0: https://jsfiddle.net/BlackLabel/obf9v0rx/

**Comment by drmrbrewer** [comment]
OK thanks, that's another workaround to use.  But should the blank space be reserved for the xAxis labels (even when disabled)?  It doesn't happen on the yAxis so this is inconsistent and confusing... i.e. why do I need space reserved for labels I have explicitly disabled and said I don't want space reserved (`labels.enabled: false` and `labels.reserveSpace: false`)?  Is it expected or a bug?

**Comment by raf18seb** [comment]
I still think this is a reasonable behavior caused by a default `labels.align` value (explained in my previous comment).

Consider this demo (the only added code is `align: 'left'`, line 61). Now toggle the `labelsEnabled` variable to `false`/`true` - no space reserved, both axes behave the same: https://jsfiddle.net/BlackLabel/auxm508j/
Now toggle the `offset` variable to `0`/`null` (line 4), still consistent behavior: https://jsfiddle.net/BlackLabel/v6qcbr43/

So the only inconsistent behavior is when the default `yAxis.labels.align` is set to `right` - **in your opinion, `align` value should not be taken into consideration while calculating the space for labels - because the labels are hidden anyway.**

I'm not sure whether consider it as a bug. We should either gather more feedback or let @TorsteinHonsi decide.

**Comment by raf18seb** [comment]
I've just read it all again, reconsidered and I'm about to agree - I'm more thinking it is actually a bug - the space should not be reserved when labels are disabled regardless of the `labels.align` value.

Thanks for this conversation and clarifying!

**Comment by drmrbrewer** [comment]
> when it comes to the x-axis - the behavior is correct and the space 
> is reserved by the `offset`, not because of labels enabled/disabled

aaaah.  This is the insight that I didn't have... thanks for the clarification!
