### ISSUE TITLE
Elliot 3 Line's Labels edited to blank or number will hit error upon saving

### ISSUE THREAD

**Issue by jackytanjq** [highcharts/highcharts#17425]
#### Expected behaviour
The Labels of the Elliot 3 Line and Elliot 5 Line will show the edited value respectively.

#### Actual behaviour
The Elliot 3 Line and Elliot 5 Line will show a random number when the edited label's value is blank.
And if the edited label is a number (without brackets), the drawing will disappear from the chart.

#### Live demo with steps to reproduce
![Highcharts_Elliott3Ln_InvalidEdits](https://user-images.githubusercontent.com/7489622/174923831-953009b7-a539-4039-b1bb-d6d0783bc724.gif)

Steps to reproduce:
1) Draw an Elliot 3 Line.
2) Edit any of the Labels for the Elliot 3 Line.
3) Press save and observe the drawing's changes.

#### Product version
Highstock v10.1.0

#### Affected browser(s)
N/A

**Comment by raf18seb** [comment]
Hi @jackytanjq, thank you for reporting this.

When an input is empty, it fires the default labels formatter which returns the point's `y` value. You can define your own formatter that will return an empty string instead of `point.y`, like this:
```js
navigation: {
    annotationsOptions: {
        labelOptions: {
            formatter() {
                return '';
            }
        }
    }
},
```

When it comes to the second problem - an annotation disappears because it's not redrawn due to an error in the console. In short: the value in the input must be a string, not a number. I'm classifying it as a bug because parsing can be done on the Highcharts side.

As a workaround, please use `'3'` instead of `3`.
