### ISSUE TITLE
chart-update-moving-bar-incorrectly

### ISSUE THREAD

**Issue by joelsherriff** [highcharts/highcharts#17438]
#### Expected behaviour

using chart.update() with similar, but not Exactly the same, values,  the changed value (bar) is updated in it's correct place.

More detail and a workaround at https://stackoverflow.com/questions/72736226/chart-update-moving-bar-incorrectly, but the jsfiddle demonstrates the issue.

#### Actual behaviour

Value (bar) is re-ordered and layered on top of the first identical value in the series.

#### Live demo with steps to reproduce
https://jsfiddle.net/wxpe6v2r/28/

#### Product version
9.3.3, but reproduced in 10.0

#### Affected browser(s)
Chrome

**Comment by raf18seb** [comment]
Hi @joelsherriff, thank you for reporting the issue.

Simplified demo: https://jsfiddle.net/BlackLabel/zqv96n5w/

`Internal note:`
Looks like a regression after https://github.com/highcharts/highcharts/commit/8919d7399b29f11f603176fb2f0bc9779a4b16f9
It will be hard to find the cause because the above commit is huge.

Worked fine in 8.0.0, broken since 8.0.1.

Workaround: update your series' data values without updating `xAxis.type: 'category'` (the xAxis is already `category` type): https://jsfiddle.net/BlackLabel/245wjme3/

**Comment by karolkolodziej** [comment]
The https://github.com/highcharts/highcharts/commit/8919d7399b29f11f603176fb2f0bc9779a4b16f9 introduced to Point object: 
```TS
public name: string = void 0 as any;
```
and now the fist condition in the if statement is allways giving true while not allways it should do that.
```TS
        if (
            'name' in point &&
            typeof x === 'undefined' &&
            series.xAxis &&
            series.xAxis.hasNames
        ) {
            point.x = series.xAxis.nameToX(point);
        }
```
