### ISSUE TITLE
Org chart link opacity is not applied

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#17484]
This issue is more relevant since node opacity is changing on hover starting from https://github.com/highcharts/highcharts/pull/17448 . I didn't have time to report it before the release, but I think org charts should behave like sankey and dependency wheel.

#### Expected behaviour
In sankey and dependency wheel series, the link opacity is reduced for remote links when hovering a node. This doesn't happen with the org chart.

#### Actual behaviour
The link opacity does not change on hover

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/blog/data-type/
* Hover the top node (Data Type)
* Expected the links between the second and third level to dim.

#### Product version
10.2.0

**Comment by wiksien** [comment]
I want to try to fix this issue.

**Comment by pawellysy** [comment]
Hello @wiksien, sorry, but this issue is already assigned to one of our team members and is part of the process of internally scheduled development work. If you still want to contribute to highcharts, feel free to select any other reported issue (If this is your first issue, consider using selecting one with the `Good for beginners` label). Thanks!
