### ISSUE TITLE
Problem with non-latin characters in exporting

### ISSUE THREAD

**Issue by IVIR3zaM** [highcharts/highcharts#1751]
when we have any non-latin characters in our chart, in PDF,PNG and JPEG exported files some characters turned to an rectangle. but in SVG format everything is ok.
EXAMPLE: http://jsfiddle.net/IVIR3zaM/fpS8b/1/

**Comment by GeorgeAppleton** [comment]
Hi, I know this is an old issue but I've been unable to get any eastern characters working with the export server I've set up. Trying mainly Chinese and Thai characters. Thai characters show a tofu and Chinese characters just don't appear. Any advice would be appreciated @gvaartjes 

So far I've installed pretty much every font in existence and all of the Noto fonts. I've tried specifying them in every way but I've had little luck with non-latin characters.

**Comment by sebastianbochan** [comment]
@cvasseng any comments?

**Comment by GeorgeAppleton** [comment]
Hi, I actually just fixed it, what are the chances of fixing it now since I was going at it for several days last week too. The fix for anyone else who finds this: when launching the server I passed character encoding to UTF-8 as a css resource. I had previously assumed it was already encoded to UTF-8. It now works with no issue for me

--resources {"css": "@charset 'UTF-8'"}
