### ISSUE TITLE
Timeline chart: Datalabels' width not using all available space

### ISSUE THREAD

**Issue by scebotari66** [highcharts/highcharts#17632]
#### Expected behaviour
I have a timeline chart, with dataLabels' "allowOverlap" config set to `false`, and no explicit width specified. The width of the visible data labels should stretch to fit its content when there is available space.

#### Actual behaviour
 It seems that the width is calculated based on the available space, but there are data labels that are too narrow, when clearly there is more space around them to use (notice in the screenshot bellow, data labels numbered 48, 49, 99, 100 are too narrow).
![image](https://user-images.githubusercontent.com/329976/186098118-85c8d3cb-5ccb-4777-b1b4-481021581a71.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/scebotari66/cesj6k75/

#### Product version
Highcharts JS v10.2.0 (2022-07-05)

#### Affected browser(s)
All

**Comment by karolkolodziej** [comment]
Thank you @scebotari66 for reporting that!

By default, the width of the data label is limited by the number of visible points and the series length.
https://github.com/highcharts/highcharts/blob/88a7857ef217e38e33f7d530d0839e71b20c4be0/ts/Series/Timeline/TimelineSeries.ts#L322-L324
The assumption is that the points are more or less equally spaced thus the width of the label is consistent thought out the series (except for the first and last point where the plot area is the limiting factor).

Considering what I said I'm not sure if that is a bug because for the most common scenario (where points are equally spaced) this works well.
However, in the demo below I prepared a wrap of the `alignDataLabel` where you can adjust that width slightly.

Demo: https://jsfiddle.net/BlackLabel/bmg7uc0v/

**Comment by scebotari66** [comment]
Thanks for the clarifications @karolkolodziej. I tried to tweak the `alignDataLabel` method, but with no luck.

> The assumption is that the points are more or less equally spaced thus the width of the label is consistent thought out the series

I think there are many situations where this is not the case. Events oftentimes occur randomly, and not at a particular interval. In our app, for example, the events are amassed at the beginning of the axis (the user updates often the record after its creation, but then the updates become less often).

![image](https://user-images.githubusercontent.com/329976/186662832-59ba37b4-016b-4ed9-8bd8-19807bdd787a.png)

Ideally, when "allowOverlap" is set to false, the width of data labels should be calculated based on the number of visible labels and the distance between their corresponding points.

Also, when for example I zoom the chart so that only two points are visible, the `alignDataLabel` method is called for every point in the chart, and not just for the zoomed ones. And the `visiblePointsCount` takes into account all the chart points, not just the zoomed ones. So the width of the labels does not change in any way when I zoom over two points and there is plenty of space for the labels to stretch.

![image](https://user-images.githubusercontent.com/329976/186666301-30233ffe-be05-4743-aab9-4eb72ed762a6.png)

**Comment by karolkolodziej** [comment]
Ok, you are right! It might be optimized better.
Let's not treat it as a bug but rather as an enhancement of something that already exists.
