### ISSUE TITLE
Annotation not working in areaRange chart

### ISSUE THREAD

**Issue by praveenkumar-r** [highcharts/highcharts#17663]
Annotaion not working in areaRange chart.
Please find my codepen which contains all data
https://codepen.io/praveenkumar-r/pen/NWYVJjP

**Comment by pawellysy** [comment]
Hi @praveenkumar-r, thanks for creating this ticket.
I am sorry, but you posted a demo, where there are 16k lines, and I don't really know which annotation you mean, that is not working as well as how exactly it is not working. Please, simplify the demo, so that is only relevant information left, and please try explaining your problem more thoroughly. Thanks!

**Comment by praveenkumar-r** [comment]
Hi, basically i need 
![image](https://user-images.githubusercontent.com/811916/187234808-fac0b5c8-4f06-44a5-878c-dfbd4393b4f3.png)
Line with marker on the area range chart.
I was able to bring line, but not able to bring circle above it with A,B,C markers and also we need to have a tooltip for that marker as well.
An i simplified the chart, please help me on this

**Comment by pawellysy** [comment]
Could you share the demo of this simplified chart?

**Comment by praveenkumar-r** [comment]
https://codepen.io/praveenkumar-r/pen/NWYVJjP

**Comment by pawellysy** [comment]
From what I noticed, this is not a bug, I would rather describe it as a regular support question. Sorry, but we treat GitHub as a feature/bug tracking tool. For these kinds of questions please contact us via our dedicated support channels, which you can [find listed here](https://www.highcharts.com/blog/support/). 
Thanks for understanding!
