### ISSUE TITLE
Missing data in Windows browsers, but shows in Linux browsers.

### ISSUE THREAD

**Issue by jejanes** [highcharts/highcharts#17701]
#### Expected behaviour
All data points are created on time series chart.

#### Actual behaviour
Missing data points at end of series.

#### Live demo with steps to reproduce
The fiddle: https://jsfiddle.net/7rca5gxj/

Highcharts forum topic: https://www.highcharts.com/forum/viewtopic.php?f=9&t=49410

#### Product version
Highcharts v8.1.2

#### Affected browser(s)
All major Windows browsers. Tested with Firefox v104.0.1, Chrome v104.0.5112.102, Opera v90.0.4480.54, and Edge v105.0.1343.25. Linux browsers do not seem to be affected.

**Comment by raf18seb** [comment]
Hi @jejanes, thank you for contacting us with your issue.

Simplified demo: https://jsfiddle.net/BlackLabel/p46bg9dr/

The markers are not displayed because their `point.isInside` flag is `false` due to the fact that the `point.plotY` is calculated incorrectly.

The bug is still visible in v9.3.1, but it works since v9.3.2. Because of this, I'm closing the ticket as resolved.

Suggested solution is to use newer version of Highcharts where the bug is fixed. If you need to use an older version, then you can use this workaround (flagging all points `point.isInside: true` is not a perfect workaround, but all your data is between 0 and 100 so it will work for your specific case): https://jsfiddle.net/BlackLabel/onxaq86w/

```js
(function(H) {
  H.wrap(H.Series.prototype, 'isPointInside', function(p, point) {
    if (this.chart.options.chart.workaroundOnlyForThisChart) {
      return true;
    } else {
      return p.apply(this, Array.prototype.slice.call(arguments, 1));
    }
  });
}(Highcharts))
```
