### ISSUE TITLE
'tooltip.outside: true' rendering issue for heatmap and treemap in Stock charts

### ISSUE THREAD

**Issue by vitaliy-kretsul** [highcharts/highcharts#17720]
#### Expected behaviour
Tooltips rendered normally for given two chart types

#### Actual behaviour
Tooltips are either not visible at all, or are displayed partially and broken

#### Live demo with steps to reproduce
(hover over top left sector of chart to see partially visible broken tooltips)
https://jsfiddle.net/Cortez/hntrxmzw/ (Treemap)
https://jsfiddle.net/Cortez/f854x6ge/ (Heatmap)

#### Product version
Highstock v10.2.1

#### Affected browser(s)
Google Chrome 105.0.5195.102

**Comment by pawellysy** [comment]
Thanks for reporting this issue!

simplified demo: https://jsfiddle.net/BlackLabel/cy7wrdht/2/

The problem is that the tooltip breaks, when it has both `outside: true`, and `split: true` defined. In stock charts, the default value for tooltip.split is true. 
I am not really sure if the tooltip.split option makes sense for treemap though. Maybe the fix would be to disable the split option for tooltip, when dealing with those kinds of series?

#### Workaround
Set tooltip.split to false: https://jsfiddle.net/BlackLabel/cy7wrdht/1/

**Comment by vitaliy-kretsul** [comment]
@pawellysy 
Thank you very much for this workaround!
Just wanted to add that same problem happens for me with bubble and scatter charts as well.
Hope this will be fixed in future releases!
