### ISSUE TITLE
Columns edges overlap neighboring columns on certain window sizes

### ISSUE THREAD

**Issue by vitaliy-kretsul** [highcharts/highcharts#17763]
#### Expected behaviour
Columns aligned and not touching each other on any reasonable window size

#### Actual behaviour
Columns edges overlap neighboring columns on certain window sizes:
![Screen Shot 2022-09-14 at 11 45 07 AM (1)](https://user-images.githubusercontent.com/12032710/191478963-544f0832-fb10-4b9b-8fa0-54cd763d6da4.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/Cortez/pnuqw9gj/

#### Product version
Highcharts v10.2.1

#### Affected browser(s)
Google Chrome 105.0.5195.125

**Comment by karolkolodziej** [comment]
Hi @vitaliy-kretsul, thank you for contacting us!

Please use the `groupPadding`([API](https://api.highcharts.com/highcharts/series.column.pointPadding)) property to set the padding between columns and avoid overlaping- [demo](https://jsfiddle.net/BlackLabel/16wn5cgh/).

**Comment by vitaliy-kretsul** [comment]
@karolkolodziej 
Thanks for your input on this.
I would say that while it is possible to control this using `groupPadding` property, it is still a non-expected behavior. Columns should not overlap with default `groupPadding` value on any screen size. What do you think?

**Comment by karolkolodziej** [comment]
I'm still not convinced because it is a pretty data-specific issue.
In the case of a datatime axis with uneven distances between points the column width is calculated based on the closest points which might cause sometimes the columns to overlap.

This might be overwritten by the [pointRange](https://api.highcharts.com/highcharts/series.column.pointRange) property - [demo](https://jsfiddle.net/BlackLabel/2zs0vj3w/).

Could you please try this one?

**Comment by vitaliy-kretsul** [comment]
@karolkolodziej 
Not sure if I fully follow the logics in the demo. 
`pointRange: 14 * 24 * 3600 * 1000` - why 14? The interval between points is 7 days. It is a weekly data.

**Comment by karolkolodziej** [comment]
Let's reopen it and see if anyone else has a similar issue. 
If that is the case, we will think about a solution for that 😄
