### ISSUE TITLE
When combining column and series data, the column width is very, very thin and could be wider

### ISSUE THREAD

**Issue by Oidlichtnwoada** [highcharts/highcharts#17782]
#### Expected behaviour

The columns are displayed as thick, as they would be without the line (enabling/disabling of the line series leads to a change of column thickness)

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/42490916/192316707-2dc94f4b-5254-4e32-bc36-24eef1028f8e.png">
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/42490916/192316766-e98cd945-1cde-4ff8-b253-6a8f642c6b73.png">

#### Actual behaviour

The columns should keep the same size, no matter if the line series is displayed or not

#### Live demo with steps to reproduce
[Demo](https://jsfiddle.net/oidlichtnwoada/1xv9pt36/14/)

#### Product version
10.2.0

#### Affected browser(s)
Microsoft Edge (Chromium-based)

**Comment by Oidlichtnwoada** [comment]
@TorsteinHonsi do you know someone who could help me?

**Comment by karolkolodziej** [comment]
In this case, you can try to manipulate the [pointPadding](https://api.highcharts.com/highcharts/series.column.pointPadding), [groupPadding](https://api.highcharts.com/highcharts/series.column.groupPadding) or [pointWidth](https://api.highcharts.com/highcharts/series.column.pointWidth) properties- [demo](https://jsfiddle.net/BlackLabel/d1L4eh6w/).

For future reference, our GitHub channel is treated as a bug/feature tracking tool. For these kinds of questions, please get in touch with us via[ dedicated support channels.](https://www.highcharts.com/blog/support/.)

**Comment by TorsteinHonsi** [comment]
Yes of course, we have a support team ready to help you. 

That said, the width of the columns is based on the _least_ distance between any of your data points. In your data set, the next-last point is at 17:00, but the last point is at 17:04 hours. So only four minutes there, and that's the reason for the narrow columns. There are two possible solutions:

* Strip off the last point from the data set. This is probably what you'd expect anyway, since the value is `null`: https://jsfiddle.net/highcharts/mhfbtrs7/
* Or, preserve the data set and set the `pointRange to one hour: https://jsfiddle.net/highcharts/mhfbtrs7/1/

**Comment by TorsteinHonsi** [comment]
> In this case, you can try to manipulate the [pointPadding](https://api.highcharts.com/highcharts/series.column.pointPadding), [groupPadding](https://api.highcharts.com/highcharts/series.column.groupPadding) or [pointWidth](https://api.highcharts.com/highcharts/series.column.pointWidth) properties- [demo](https://jsfiddle.net/BlackLabel/d1L4eh6w/).

Hard coding the `pointWidth` doesn't work well with responsive designs: https://jsfiddle.net/highcharts/j3uqcpya/. It is better to fix the base problem like I describe above.

**Comment by Oidlichtnwoada** [comment]
@TorsteinHonsi @karolkolodziej Thank you two so much, perfect support from your side, meant a world to me ^^
