### ISSUE TITLE
Removing series and adding it again results in different y-axis scale

### ISSUE THREAD

**Issue by mcayland** [highcharts/highcharts#1781]
Hi all,

We are experimenting with using HighCharts 3.0.1 in a dynamic graphing module and have come across a bug when redrawing the same dataset twice on a page. What happens is that the y-axis scale changes depending upon whether or not the dataset is initially rendered within the page, or whether it is later dynamically updated via Javascript.

To reproduce:

1) Visit the jsFiddle at http://jsfiddle.net/wmSm8/7/
2) Note the units/gridlines for the y axis
3) Click the "Update" button to reload the axis & series
4) Notice that the y-axis has different units/gridlines

On another note, it seems that if all series have been removed and another series is dynamically added to the chart, the counters.color and counters.symbol values are not reset to zero. This can be seen by clicking the "Update" button multiple times.

The JS code example given in the jsFiddle is a little long-winded in that it removes the entire y-axis rather than just calling setData(), however the graphing component that we are developing and testing with HighCharts is truly dynamic in that multiple Y axes and series can be added on the fly and dynamically updated via AJAX.

The issue can be consistently reproduced using the above jsFiddle on our development environment of Debian Wheezy (Firefox 10.0.12).

Many thanks,

Mark.

**Comment by mcayland** [comment]
Is there any progress on this at all? We're still getting this raised as a bug report against our production system, time and time again.

**Comment by highslide-software** [comment]
It has to do with the order of drawing the axis labels - as [we say in the docs](http://api.highcharts.com/highcharts#yAxis.tickPixelInterval), the  default `tickPixelInterval` determins the _approximate_ tick layout. In this case it means it can change after redraw, because we have more information about the length of the axis. 

Valid workarounds are to set a fixed `chart.marginBottom` ([see demo](http://jsfiddle.net/highcharts/wmSm8/11/)), or a `tickInterval` option.

The underlying problem is that the space taken by labels on the X axis affects the the tick interval on the Y axis, which in turn affects what ticks are drawn, which in turns affects the X axis etc.
