### ISSUE TITLE
when chart size is less and Axis line width is more, console error occurs

### ISSUE THREAD

**Issue by sathish151198** [highcharts/highcharts#17823]
#### Expected behaviour
when chart size is less and Axis line width is more, console error should not occur

#### Actual behaviour
when chart size is less (say height < 100px, width < 100px) and Axis line width is more, console error occurs.
<img width="487" alt="image" src="https://user-images.githubusercontent.com/105407774/193976908-cb50d7af-ca5f-416f-aa84-29b1517a9b06.png">

#### Live demo with steps to reproduce
[Demo](https://jsfiddle.net/sathish1511/kf54dspw/1/)

#### Product version
Highcharts v9.1.2

#### Affected browser(s)
Version 106.0.5249.62 (Official Build) (64-bit)

**Comment by pawellysy** [comment]
Hello @sathish151198 thanks for reporting this bug!

**Comment by sathish151198** [comment]
> Hello @sathish151198 thanks for reporting this bug!

Is there any quick solution to fix this bug?

**Comment by pawellysy** [comment]
@sathish151198, sorry but this is a bit of an edge case, where a lot of errors are thrown, and it is hard to create a workaround for all of those cases. apart from that, there is really no point in creating such a small chart with this line width, so maybe instead of creating a small chart, you should go for making it invisible, when necessary. 

Feel free to reach out to our available support channels, where our support engineers will help you to tweak the chart to your needs.
