### ISSUE TITLE
Map with overlaid pie charts, pie charts are visible outside chart plot area

### ISSUE THREAD

**Issue by pkExec** [highcharts/highcharts#17849]
#### Expected behaviour
Pie charts should stay within plot area.

#### Actual behaviour
![Capture](https://user-images.githubusercontent.com/7925305/195778644-f4912d24-7d4b-4ebf-bf5c-24ddaa8a60da.JPG)

#### Live demo with steps to reproduce
1. Go here: https://www.highcharts.com/demo/maps/map-pies
2. Zoom a bit. 
3. Pan the map, you'll see pie charts move outside chart plot area (overlaying legend items/credits etc).

#### Product version
Highcharts JS v10.2.1

#### Affected browser(s)
I assume all. Tested on Chrome, Firefox, Edge.

**Comment by pawellysy** [comment]
thanks @pkExec for reporting this issue!
FYI @KacperMadej

**Comment by pawellysy** [comment]
`Internal note`
Each series group should have the same clip-path as a main series.

**Comment by magdalena-gut** [comment]
@pkExec The issue occurs due to the `clip `option - by default set to `true` in maps, and to `false` in the pie series. Since the zooming is enabled, the `clip` should be enabled as well. 

To fix this behavior, only `clip: true` needs to be set on the pie series.
Demo: https://jsfiddle.net/BlackLabel/soh9cwqa/

@KacperMadej I believe we shouldn't change the default clipping for the pie series, so my suggestion would be just to improve the official demo.

**Comment by KacperMadej** [comment]
@magdalena-gut Sounds great. Let's improve that demo with `clip: true` for `plotOptions.pie`.
