### ISSUE TITLE
Line display in empty range with xAxis.ordinal = false and gapSize

### ISSUE THREAD

**Issue by TBoendergaard** [highcharts/highcharts#17840]
#### Expected behaviour
The line shouldn't display in the empty range.

#### Actual behaviour
The chart displays the line after zooming in the empty range. It disappears after zooming on some data.

#### Live demo with steps to reproduce
To reproduce select 9.01.2010 - 10.01.2010 range with no data.
[Demo](http://jsfiddle.net/TBoendergaard/tpqn0orc/)

#### Product version
highcharts stock 8.2.2 + highcharts-react-official 3.0.0

#### Affected browser(s)
Firefox

**Comment by pawelfus** [comment]
Hi @TBoendergaard 

Thank you for reporting the issue. This is expected behaviour with this config. [`gapSize`](https://api.highcharts.com/highstock/series.line.gapSize) works together with [`gapUnit`](https://api.highcharts.com/highstock/series.line.gapUnit) option. With default (`"relative"`) value for `gapUnit`, the graph will be broken when the distance between two points is greater than `gapSize` value multiplied by the closest distance between two points. That means when you select 9.01.2010 - 10.01.2010 range, you get exactly two points (one before `min` and one after `max`) and the closest distance is.. equal to the distance between them. As the result, you can see the line connecting these two points.

The same happens when you select the range for example 05.01.2010 10:00 - 05.01.2010 11:00 - the line will be displayed (even when two points are outside the extremes).

If you want to change this, then use `gapUnit` and `gapSize`, for example, set it to one day: http://jsfiddle.net/BlackLabel/catn2reh/ 

Let us know if anything is not clear, thanks!

**Comment by TBoendergaard** [comment]
Hi! Thank you so much for the clear and fast answer! This solves my problem.
