### ISSUE TITLE
Polar chart throws Maximum call stack size exceeded exception

### ISSUE THREAD

**Issue by TomBetcke** [highcharts/highcharts#17891]
#### Expected behaviour
Polar chart should not throw exceptions

#### Actual behaviour
Throws "Maximum call stack size exceeded" exception

#### Live demo with steps to reproduce
https://jsfiddle.net/mcbj8k5x/1/

#### Product version
10.2.1

#### Affected browser(s)
Tested with Chrome

**Comment by karolkolodziej** [comment]
Hi @TomBetcke! 
Thank you for reporting this issue.

_Internal note:_
Regression introduced in v10.2.0, unable to bisect.

_Workaround:_ 
- Instead of using the `bar` series please use `column` and invert the chart- [demo](https://jsfiddle.net/BlackLabel/r5ju7mz8/).
- Use the older version till 10.1.0- [demo](https://jsfiddle.net/BlackLabel/4b6noqg7/).

**Comment by hubertkozik** [comment]
This bug is fixed in the latest release of Highcharts v11.0.1.
