### ISSUE TITLE
Area charts dont render when using ES6 modules

### ISSUE THREAD

**Issue by peterchavasse** [highcharts/highcharts#17899]
#### Expected behaviour
It should be possible to create an area chart (or areaspline chart) using ES6 modules

#### Actual behaviour
Currently, an exception is thrown resulting in no areas being drawn

#### Live demo with steps to reproduce
[jsfiddle](https://jsfiddle.net/t0y1crqf/14/)

#### Product version
Highcharts 10.2.1

#### Affected browser(s)
All browsers affected

#### Possible fix...
[https://github.com/highcharts/highchart ... es.ts#L334](https://github.com/highcharts/highcharts/blob/master/ts/Series/Area/AreaSeries.ts#L334)

add a check for stacking 

ie.  stacks = stacking && yAxis.stacking.stacks[this.stackKey]

**Comment by karolkolodziej** [comment]
Hi @peterchavasse!

In your demo the `StackingAxis` composition is missing.
After adding that it works well- [demo](https://jsfiddle.net/BlackLabel/0dLp3ura/).

**Comment by pawellysy** [comment]
Normally, The compose method is fired with the parameter of `Series` generic class. Since `AreaSeries` is extending the LineSeries, you have to fire the compose method with `LineSeries` : https://jsfiddle.net/BlackLabel/tqd1u4z6/3/

Since this is not a matter of any bug, and we treat our GitHub repository as issue/feature tracking tool, please reach out to us via our available support channels, which you can find here: https://www.highcharts.com/blog/support/
