### ISSUE TITLE
Heat map 

### ISSUE THREAD

**Issue by rlagreid** [highcharts/highcharts#17914]
We have implemented the Highcharts heatmap in Polarion as a risk heat map.
We are using an, as far as we can see, undocumented feature of the heatmap.

We are defining each cell in the heat map twice. The first definition gives the value to be displayed in the cell and the second defines the colour of the cell.
E.g.

{x:0,y:2, value:"$x0y2"},//value
{x:0,y:2, value:1 },//color:green

The result is a heat map that displays the risk items in the correct cell according to the multiple of the likelihood and impact.
There is only one issue with the map.
When hovering over the cells all cells containing risk items turns black.
Is there a way to overcome this?

![Heatmap](https://user-images.githubusercontent.com/14754293/199468720-2dfdaec4-dcc9-443e-aead-e4f71a214fb4.PNG)
![Hover](https://user-images.githubusercontent.com/14754293/199468724-2384584b-063b-4653-a18d-9c2017deee3f.PNG)

**Comment by pawellysy** [comment]
Hello @rlagreid, thanks for reaching out to us.
Unfortunately, we treat GitHub as a feature/bug tracking tool, and your question is neither. With this kind of question, please reach out to us via[ our available support channels](https://www.highcharts.com/blog/support/), where our support engineers will help you with your chart configuration :)

PS: Please attach the jsfiddle demo with your message, so that your issue is resolved faster. Thanks!
