### ISSUE TITLE
What happened after Highcharts made a 3d pie chart and added startAngle?

### ISSUE THREAD

**Issue by bruce-zhang932** [highcharts/highcharts#17962]
#### Expected behaviour
I hope the starting angle of 3d pie chart changes

#### Actual behaviour
A bug has occurred
![image](https://user-images.githubusercontent.com/11385973/201059239-def1f9da-de25-401a-8fb5-bbba7a85d258.png)
After I add the startAngle attribute, a bug will appear. If I remove it, it will be OK. What is the reason?

#### Live demo with steps to reproduce
https://jshare.com.cn/edit/public/gynjyyko

#### Product version
v10.1.0

#### Affected browser(s)
All browsers

**Comment by pawellysy** [comment]
Hello @bruce-zhang932 thanks for reaching out to us!
When I deleted the part of wrap everything seems to be working in order.
https://jsfiddle.net/BlackLabel/8kqgobw7/#save
 Did you create this wrap yourself, or you found this demo somewhere?

**Comment by bruce-zhang932** [comment]
@pawellysy I found the demo online. I added the startAngle modification based on the project requirements.

**Comment by pawellysy** [comment]
Could you post the link of the website, where you found the demo?

**Comment by bruce-zhang932** [comment]
@pawellysy https://blog.csdn.net/weixin_48186771/article/details/119419910

**Comment by pawellysy** [comment]
@bruce-zhang932, it seems, that you found the modified piece of code on some blog, which is a custom implementation. This is not a highcharts bug, because if I delete the custom part of the code, everything works correctly. So What can you do, is contact us via [available support channels](https://www.highcharts.com/blog/support/) where our support engineers will be more than happy to help you with your chart. Thanks!
