### ISSUE TITLE
Series points error

### ISSUE THREAD

**Issue by KamilKubik** [highcharts/highcharts#17991]
#### Expected behaviour
After adding a new series with `visible: false` property, setting a `color.patternIndex` property on another series, and viewing it in the full screen, I should be able to exit the full screen by clicking it in the menu.
 
#### Actual behaviour
After adding a new series with `visible: false` property, setting a `color.patternIndex` property on another series, viewing it in the full screen and trying to exit the full screen by clicking it in the menu, the `TypeError: undefined is not an object (evaluating 'a.points.forEach')` error occures.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/r5kbh7ef/

Steps: 
1. Add a new, hidden series by clicking the 'Add series' button.
2. Set the pattern moode in menu
3. Set the full screen in menu
4. Try to exit the full screen from the menu

#### Product version
Highcharts v10.3.1

**Comment by pawellysy** [comment]
Hello @KamilKubik, thanks for reporting this issue!
Simplified demo: https://jsfiddle.net/BlackLabel/r5kbh7ef/1/


Unfortunately, it is impossible to workaround, since this part of code is added via `addEvent`.
Possible fix would involve checking series' visibility here: https://github.com/highcharts/highcharts/blob/50153697968454519cc4c8b221fe385de8375316/ts/Extensions/PatternFill.ts#L637-L651
