### ISSUE TITLE
Area chart with both cumulative and stacking renders chart with hickup

### ISSUE THREAD

**Issue by wardpeet** [highcharts/highcharts#18010]
#### Expected behaviour
The chart should not have the weird color overlay

#### Actual behavior
![image](https://user-images.githubusercontent.com/1120926/203161104-04501b90-bb03-41dc-b75d-094dbd7e65a8.png)
![image](https://user-images.githubusercontent.com/1120926/203161272-7be57c23-5324-4125-930d-70bd0dd587da.png)

#### Live demo with steps to reproduce

https://jsfiddle.net/wardpeet/d6sr7tuc/2/

#### Product version

Highstock@10.3.1

#### Affected browser(s)
Chrome

**Comment by pawellysy** [comment]
Thanks for reporting this issue!

**Comment by wardpeet** [comment]
Any pointers on where this bug could live? I'm happy to take a stab at it

**Comment by pawellysy** [comment]
@wardpeet, from what I've noticed, the stacking Axis does not consider the fact, that there could be a cumulative option enabled, and gets the bottom part of the position as not cumulated.

Here is the simplified demo:  https://jsfiddle.net/BlackLabel/qc0ka7sx/

The issue is probably located in this method: https://github.com/highcharts/highcharts/blob/5d97e939b895a4bd86a5c9067089462e02e52934/ts/Core/Axis/Stacking/StackingAxis.ts#L348
