### ISSUE TITLE
Maps zoom displaces map points

### ISSUE THREAD

**Issue by kamil-musialowski** [highcharts/highcharts#18017]
#### Expected behaviour
Map points should not change their position (relative to the map) while quick scrolling. It should be simultaneous (or at least go back to the correct position after zoom). It's easier to reproduce it on the touchpad. 

#### Live demo with steps to reproduce
1. Scroll quickly to see how points and labels can't keep up with the main map zoom level.
https://jsfiddle.net/BlackLabel/07f8g6pL/

![image (3)](https://user-images.githubusercontent.com/105275628/203349696-8de80a45-4aa5-4b2b-b182-a09fd03a73fd.png)
![image (4)](https://user-images.githubusercontent.com/105275628/203349699-1cd9bd23-537d-4ad8-922e-70b86741a6d0.png)

#### Product version
Highmaps 10.3.1 (latest)

**Comment by ori007a** [comment]
Not only point and labels, but also the bubble on bubble map
https://www.highcharts.com/demo/maps/map-bubble
or each series that should be alien to the main map is not synced to the map on fast scrolling or using the API zoomTo on map load complete.

**Comment by KacperMadej** [comment]
@kamil-musialowski 
Scrolling quickly is random and really allows me to recreate the problem. There should be a stable and reliable way of recreating the problem to debug the problem source and use it for later tests. If you are able to add such a live demo then it would be great.

**Comment by TorsteinHonsi** [comment]
I assume the problem is with animation. 

Can you confirm that you don't experience the problem if we turn off animation? https://jsfiddle.net/highcharts/fwk27mgd/

I see two possible solutions:
**1. Avoid multiple simultaneous animations**
The mousewheel handler sets a property, `isAnimating`, and a timeout that sets it to false. Then the next mousewheel handler, if `isAnimating` is true, aborts mission.

**2. Disable animation**
If the first one failse. When the [Pointer calls zoomBy](https://github.com/highcharts/highcharts/blob/030a47e565fb296cd688d099da1f73ca6e49f41c/ts/Maps/MapPointer.ts#L151-L161), make sure it does so with the `animation` set to false. But this also makes the experience less smooth.
