### ISSUE TITLE
stickyTracking doesn't work well in many case especially with candlestick chart

### ISSUE THREAD

**Issue by PrachiS2G** [highcharts/highcharts#18085]
#### Expected behavior
the tooltip should only be visible when hovering on the points of the series and should fade away when we are on the other part of the chart 

#### Actual behavior
See this video - here it shows once I hover on the series and the tooltip is active then even if I hover on the remaining part it doesn't fade away and stays there until I move the cursor out of the chart

![tooltip](https://user-images.githubusercontent.com/97212900/205630450-0b6d1ede-0be4-41f2-970f-5c3f32000069.gif)

#### Live demo with steps to reproduce
[](https://jsfiddle.net/6phvtwm5/)

#### Product version
this is stock chart

#### Affected browser(s)
chrome, firefox

**Comment by karolkolodziej** [comment]
Hi @PrachiS2G, thank you for contacting us!

As you can read in the [API](https://api.highcharts.com/highcharts/series.line.stickyTracking):
>  When `stickyTracking` is false and `tooltip.shared` is false, the tooltip will be hidden when moving the mouse between series. Defaults to true for line and area type series, but to false for columns, pies etc.

In the candlestick series, the tooltip split is set to `false` ([split takes precedence over shared](https://api.highcharts.com/highstock/tooltip.shared)) thus the tooltip will not be hidden.
In order to make it work, you have to set split to false - [demo](https://jsfiddle.net/BlackLabel/87wo1paf/).
