### ISSUE TITLE
Drilldown problem with React 18

### ISSUE THREAD

**Issue by brunouber** [highcharts/highcharts#18084]
#### Expected behaviour

When user clicks on one of the series label the chart updates, and details about the selected item are rendered.

#### Actual behaviour

The chart is updated, but it shows the same data, just with different colors.

#### Live demo with steps to reproduce

https://codesandbox.io/s/pedantic-feynman-q1pyem?file=/src/App.js

- We need to know the state of the chart (drilldown, or not) outside the chart itself... for this reason we set the two events `events.drilldown`, `events.drillall`... everything works fine if we just remove this events.

- Everything works fine if we rollback to legacy react-dom render api (even when using react18).

- When we memoize the option before passing down to Highcharts everything works fine (see ChartWorking.js in the demo).
 
#### Product version

highcharts 10.3.2
highcharts-react-official 3.1.0
react 18 (only when using the new createRoot api)

**Comment by bm64** [comment]
Hello @brunouber and thanks for contacting us with your issue.

It behaves like that, because in your demo `drillupall` and `drilldown` callbacks invoke function that updates state and triggers re-render of Chart component with the initial options object. To prevent that behaviour is necessary to use useMemo hook (exactly like in your working example) or useState hook: https://codesandbox.io/s/withered-star-7unito. To change initial options object on chart update, you'd have to pass new set of options as a component props. Docs reference: https://github.com/highcharts/highcharts-react#optimal-way-to-update
