### ISSUE TITLE
chart.plotOptions.series.dataLabels.style.color: contrast value does not work starting in version 10.2

### ISSUE THREAD

**Issue by prolarcorp** [highcharts/highcharts#18142]
#### Expected behaviour
automagically change color of data label based on background color

#### Actual behaviour
data label is always black color

#### Product version
>= 10.2

#### Affected browser(s)
All

**Comment by bm64** [comment]
Hello @prolarcorp! Please recreate the issue in this demo: https://jsfiddle.net/BlackLabel/2Lg9bzf4/

**Comment by KacperMadej** [comment]
Demo: https://jsfiddle.net/BlackLabel/2Lg9bzf4/2/

The difference: 
![image](https://user-images.githubusercontent.com/8960408/212652375-22a8ce45-93b3-4127-90cf-cc586b742455.png)

The top is `style: { color: 'contrast' }` and the bottom is `color: 'contrast'`.
The API reference says that `style.color` should be used since `color` deprecation in 10.3 but the results are not the same and the deprecated option (`color`) looks better (higher contrast).

**Comment by GaryGen** [comment]
From what I understand, this doesn't have to do with the deprecated style.color since it also occurs with style.dataLabels.style.color.

The issue appears to be the new "enforced contrast rules" in the accessibility support in 10.2. Specifically, if the difference between the background color and the font color are algorithmically determined to not have enough contrast, text outlines are used to provide contrast.

I've been getting support for this issue here: https://www.highcharts.com/forum/viewtopic.php?p=185266#p185266.
My example is here: https://jsfiddle.net/GaryGen/m8ovs04f/9/

The problem with this approach is that the text outlines often make the font unreadable, as shown in the example above. Worse, there is no direct way of turning it off, even with the accessibility module not loaded. The suggestion for overcoming it was to turn textOutline off.

I'm definitely not against accessibility or approaching it algorithmically. However, the approach needs to make the font more readable, not less readable. The typical approach I've seen is to use a solid shape of contrasting color in the background rather than trying to emphasize the outline. In addition, any algorithmic approach solution to issues should have a way to be turned off or customized to account for times when it does not meet customer needs.

Best Regards,
-Gary Geniesse

**Comment by TorsteinHonsi** [comment]
Regarding Kacper's demo

> The API reference says that style.color should be used since color deprecation in 10.3 but the results are not the same and the deprecated option (color) looks better (higher contrast).

It is because `dataLabels.color` is used (and hard coded) in the theme file, thus taking precedence. So it not really a bug.

@GaryGen 
> The problem with this approach is that the text outlines often make the font unreadable, as shown in the example above

Yes but that's because of an unfortunate configuration in the theme. In that example, both the background and the `dataLabels.style` are set to a dark value. If `contrast` were used for the data labels, as default and as recommended, the label text would be light. A more typical example is this https://jsfiddle.net/highcharts/8z3e65uq/, where the text color is already in maximum contrast, and the `textOutline` just enhances it against the background.

> Worse, there is no direct way of turning it off, even with the accessibility module not loaded. The suggestion for overcoming it was to turn textOutline off.

Setting `textOutline` to `none` _is_ the way to turn it off, though I agree that this is not very well covered in our documentation.

> The typical approach I've seen is to use a solid shape of contrasting color in the background rather than trying to emphasize the outline

Yes I've also seen that. The text outline approach in my (subjective) experience improves the legibility 90% of the time, but 10% of the times it gets worse. Often times because of bad configuration, like the above example, but nevertheless. I did a small experiment with this. Here's a small snippet that applies a contrast background and a fixed opacity to the labels:
* On a column chart. Notice that the background is changed based on the text color (which again responds to the column color): https://jsfiddle.net/highcharts/8z3e65uq/1/
* On a line chart. As you can see, the downside with this is that it is more visually disturbing. https://jsfiddle.net/highcharts/L097xhf1/

All in all, I think we should consider at least making `backgroundColor: 'contrast'` an option, and implementing `backgroundOpacity`. 

@oysteinmoseng FYI

**Comment by GaryGen** [comment]
@TorsteinHonsi Thanks for the thorough reply and consideration.

I think my biggest confusion was that the visibility of the outline appeared to be unrelated to the color property I was changing. (I understand it IS related, but it visually appears arbitrary.) Since I need to support dynamic styling, I know my customers are expecting that if they change the font color property, only the font color will appear to change.

I'll set textOutline to None as suggested and look forward to this feature having more configurability.

Thanks again!
