### ISSUE TITLE
Cannot render 50 or more series with specified colors and enabled boost

### ISSUE THREAD

**Issue by rdp1414** [highcharts/highcharts#18145]
As suggested by [michal.f](https://www.highcharts.com/forum/memberlist.php?mode=viewprofile&u=40740&sid=d278d440396aaa4a62ceb26bcd979a73) in forum [Topic#50030](https://www.highcharts.com/forum/viewtopic.php?f=9&t=50030), I'm logging this bug issue. 

Chart points are not rendered when:
1. Boost module is enabled.
2. Color is specified in input.
3. Number of series is greater than or equal to 50.

Our business-use-case involves displaying more than 50 series with specific colors. Can you please fix the bug / give us some workaround / tell me if I'm doing anything wrong here?

#### Expected behaviour
All series with data points with "grey" color should be correctly rendered.

#### Actual behaviour
None of the data-points are rendered.

#### Live demo with steps to reproduce
https://jsfiddle.net/bqghn513/

#### Product version
Highcharts version `10.3.2`

#### Affected browser(s)
Chrome

**Comment by karolkolodziej** [comment]
Hi @rdp1414!

From what I can see this issue is only visible for the color `grey` as a workaround you can use different spelling `gray` -[demo](https://jsfiddle.net/BlackLabel/sjxc02wn/).

_Internal note:_
`grey` can be added to the `defaultHTMLColorMap`. 
https://github.com/highcharts/highcharts/blob/6a3d1f235046ef7228ab61e894898a6ec2ddcede/ts/Extensions/Boost/NamedColors.ts#L82
