### ISSUE TITLE
Limits conflicting with trendlines

### ISSUE THREAD

**Issue by Sirpattalot** [highcharts/highcharts#18163]
#### Expected behaviour
Trendlines (and the series items they're linked to) should display accurately when using limits (min and max properties).

#### Actual behaviour
When using limits on the yaxis, trendlines disappear in some cases. In other cases, the data which the trendline is tied to (via linkedTo property) shows at the wrong position on the chart (despite the data values on hover being correct)

#### Live demo with steps to reproduce
https://codepen.io/patflynn/pen/WNKNraq

#### Product version
"highcharts": "^9.1.1",
"highcharts-vue": "^1.4.0",

#### Affected browser(s)
Tested with Chrome

**Comment by bm64** [comment]
Hello @Sirpattalot and thanks for contacting us with your issue.

The trendline disappears correctly, because it is simply out of the axis range when extremes are set. It behaves like that because you didn't change `yAxis` for `Val1_trend`, and even though it is linked to `Val1` series, which belongs to second yAxis, the trendline's yAxis remains the first, default one. Demo with adjusted yAxis: https://jsfiddle.net/BlackLabel/nzc13ohf/

I'm closing this ticked for now, but if I have overlook something or if there is anything you want to add feel free to reopen it.
