### ISSUE TITLE
highchart column chart negative stack labels overlap with axis labels

### ISSUE THREAD

**Issue by adityapachpor978478** [highcharts/highcharts#18192]
When there are negative stack labels for a column chart, they overlap with axis labels for considerably large values.

Here's a fiddle to recreate the problem.
<https://jsfiddle.net/adityapachpor/0fekodq3/2/>
The value "-450" overlaps with axis label here

**Comment by bm64** [comment]
Hello @adityapachpor978478 and thanks for contacting us!

It doesn't seem to be a bug - overlapping is caused by `overflow` option. As you can read in API, `overflow: allow` allows stack labels to be displayed outside plot area: https://api.highcharts.com/highcharts/yAxis.stackLabels.overflow. Set the option to `justify` and the issue should be gone: https://jsfiddle.net/BlackLabel/xbkfrn0q/
