### ISSUE TITLE
VBP Overlay Indicator Doesn't Work After Resize

### ISSUE THREAD

**Issue by wagnerga** [highcharts/highcharts#18238]
#### Expected behaviour
I expect to be able to resize browser, trigger state changes, and re-render without app crashing

#### Actual behaviour
App crashes when resizing and re-rendering VBP indicator series

#### Live demo with steps to reproduce
https://codesandbox.io/embed/highcharts-react-example-forked-9o6l9p?fontsize=14&hidenavigation=1&theme=dark

#### Product version
highcharts: 10.3.2
highcharts-react-official 3.1.0

#### Affected browser(s)
Chrome

**Comment by karolkolodziej** [comment]
Hi @wagnerga.

In your example, you are basically calling the `chart.update` method with the same data.
In order to avoid that, please keep your chart options in the state or use `useMemo`. 
You can also disable the `allowChartUpdate` - [docs](https://github.com/highcharts/highcharts-react#options-details).

Internal note:
The VBP should not be calculated if there is no `volume` series- [demo](http://jsfiddle.net/BlackLabel/cwqx5o89/).

**Comment by pawelfus** [comment]
*Internal note:*
If there's no `volume` series, then our error should be thrown, not a JS error
