### ISSUE TITLE
Map SVG line colour doesn't cycle through defined colours when set for individual lines

### ISSUE THREAD

**Issue by FusionSnowball** [highcharts/highcharts#18246]
#### Expected behaviour
If there a more lines in the data than there are colours defined I expected it to cycle through the colours array and reuse colours, as it does for series colours.

#### Actual behaviour
The last colour in the array is used for all lines where the array index is greater than the number of array items. Only happens when the colours are set on individual lines, if set at series level it cycles as expected.

#### Live demo with steps to reproduce
https://jsfiddle.net/god0Lpr5/28/ 

In the example there are 3 colours defined and 6 flight routes. I expected to see each colour used twice but red and green are used once and everything else is blue.

#### Product version
10.3.2

#### Affected browser(s)
Chrome 108

**Comment by pawellysy** [comment]
Hello @FusionSnowball, thanks for reaching out to us with your issue!
In my opinion everything is working in order. You are manually passing the colors to the chart's config, and when you are referring to the colors array, which has only 3 items in it, then you are passing `undefined` as a value of color, which defaults to the first color. What you can do is to use the `colorByPoint` property of the series: https://jsfiddle.net/BlackLabel/h5vra68u/

I will mark it as a bug in the API documentation, because this property is missing. Thanks!

`internal note` 
The `series.mapline.colorByPoint` property is missing from the API, but is working as shown in the demo above.
