### ISSUE TITLE
Error #15 on barchart

### ISSUE THREAD

**Issue by maxburs** [highcharts/highcharts#18299]
#### Expected behaviour
Charts described in error 15 match charts that need sorting

#### Actual behaviour
Column charts required sorting

#### Live demo with steps to reproduce
https://jsfiddle.net/genuine_smiles/b4tchxdk/1/

#### Product version
Latest

#### Affected browser(s)
N/A

While debugging an issue related to our column charts rendering oddly, I found that column charts points need sorting. We were already sorting for the 2 chart types described in the error. I'm worried other charts require sorting that I'm unaware of.

Error 15
> ### Highcharts expects data to be sorted
> This happens when creating a line series or a stock chart where the data is not sorted in ascending X order.
> 
> For performance reasons, Highcharts does not sort the data, instead it requires that the implementer pre-sorts the data.

From here: https://assets.highcharts.com/errors/15/

**Comment by bm64** [comment]
Hello @maxburs and thanks for contacting us.

Exactly as the error says, Highcharts expect your data to be sorted: https://jsfiddle.net/BlackLabel/8u9ozvkg/
I know that the error says that `This happens when creating a line series or a stock chart...` but that's also the case for column and many other series. There are few series that don't require pre sorted data, e.g. scatter series: https://jsfiddle.net/BlackLabel/shpcw5zq/

**Comment by maxburs** [comment]
@bm64 Is it documented anywhere which series do or don't need sorting?

**Comment by pawellysy** [comment]
The only types, that don't require sorting are: 
- Scatter
- Pie
- XRange

And series, which are not using cartesian coordinates, like sunburst, treemap, sankey, etc.

Generally, I'd advise handling sorted data, because it makes all calculations easier. Feel free to reach out to us [via support channels](https://www.highcharts.com/blog/support/), in case of any further questions! Thanks
