### ISSUE TITLE
Sunburst: {point.parent} should return parent name, not parent id

### ISSUE THREAD

**Issue by peterthoeny** [highcharts/highcharts#18300]
# Description of the feature

When adding a tooltip like the following, `{point.parent}` returns the cryptic parent id instead of the human readable parent name:
```
{point.name}: {point.value} (parent {point.parent})
```

In your Sunburst demo at https://www.highcharts.com/demo/sunburst, "Northern America" shows "1.2" for `{point.parent}`, I think it is more logical to get "America" instead. Same for data labels `.format` and `.formatter`.

Ideally, `{point.parent}` would be changed to `{point.parent.id}` and `{point.parent.name}` to get the id and name, respectively.

If you are concerned about compatibility, use `{point.parent}` for parent id, and add a `{point.parentName}` for the parent name.

# Library related to the feature

Highcharts / Sunburst

# Proof of Concept/Live example for the feature

In https://www.highcharts.com/demo/sunburst, go to "EDIT IN JSFIDDLE", and change the tooltip to:
```
    tooltip: {
        headerFormat: '',
        //pointFormat: 'The population of <b>{point.name}</b> is <b>{point.value}</b>'
        pointFormat: '<b>{point.name}</b>: <b>{point.value}</b>, parent: {point.parent}'
    }
```

----

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by pawellysy** [comment]
Hi @peterthoeny, thanks for reaching out to us!
I'm afraid at this point, there is no way of making this change because this is a part of our setup, where `point.parent` is an id, not a name. You can find an easy workaround to this issue though by accessing `parentNode` both in the formatter function and in the format field by 
`pointFormat: '{point.node.parentNode.name}'`
or 
`pointFormatter: () => this.node.parentNode.name`

Closing, since we for sure won't implement this change with this easy workaround. 
Thanks for the suggestion though. 😉

**Comment by peterthoeny** [comment]
This does not work for me. From what version on is `{point.node.parentNode.name}` available?

**Comment by pawellysy** [comment]
Hi! This property was added in v10.3.0, but either way, if you want to have access to this property, you need to update the version of Highcharts. 
Added in this PR: https://github.com/highcharts/highcharts/pull/17017
