### ISSUE TITLE
Mozilla Firefox and Safari wrong label events triggering

### ISSUE THREAD

**Issue by Khavrolev** [highcharts/highcharts#18344]
#### Expected behaviour
If mouseover, mouseout and click events set some React state, mouseover and mouseout events are NOT triggered INFINITY times in Mozilla Firefox and click event is triggered properly in Safari

#### Actual behaviour
If mouseover, mouseout and click events set some React state, mouseover and mouseout events are triggered INFINITY times in Mozilla Firefox and click event is triggered NOT properly in Safari

#### Live demo with steps to reproduce
I've created [test repo](https://github.com/Khavrolev/highchart-firefox) with a simple project, also I've deployed that project [on Github Pages](https://khavrolev.github.io/highchart-firefox/):

1) Open the console.
2) Hover your cursor on xAxis label (Test1 or Test2)
3) Look at the console and logs. It works fine in Chrome and Edge, but not in Mozilla Firefox and Safari

https://user-images.githubusercontent.com/43345369/214075035-9f04edd2-57e4-40af-b9c7-ccc7b64f7839.mp4

https://user-images.githubusercontent.com/43345369/214076536-831f07e1-0b42-4a92-b695-3f220759f830.mp4

#### Product version
"highcharts": "^8.1.2",
"highcharts-custom-events": "^3.0.10",
"highcharts-react-official": "^3.0.0",

#### Affected browser(s)
Mozilla firefox, Safari

**Comment by bm64** [comment]
Hello @Khavrolev and thanks for contacting us.

As you can read in our React Wrapper docs: https://github.com/highcharts/highcharts-react#optimal-way-to-update
A good practice is to keep all chart options in the state. Otherwise charts options declared as a variable are being created every time you set state, which leads to unnecessary updates and infinite loop in effect. I'm not sure though why this is an issue  in Mozilla Firefox / Safari and in Chrome / Edge not, but I guess it has something to do with how those browsers register those events. Anyway, a solution to this issue and a correct way to use Highcharts React Wrapper, is to keep a chart options in useState / useMemo hook: https://stackblitz.com/edit/react-cvagrw?file=index.js
