### ISSUE TITLE
Tooltip not displaying while hovering on the plotband for type gauge

### ISSUE THREAD

**Issue by sathish151198** [highcharts/highcharts#18347]
#### Expected behaviour
when we hover over the plotband for type gauge, the tooltip is  should be displayed

#### Actual behaviour
While hovering on the values or target line, the tooltip is getting displayed. But when we hover over the plotband for type gauge, the tooltip is not getting displayed

<img width="356" alt="image" src="https://user-images.githubusercontent.com/105407774/214214939-682b4b73-3e35-4bbb-b77f-bf007e0ea7e0.png">

Tooltip is not working when we hover over the above highlighted region. 
#### Live demo with steps to reproduce[
]

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/gauge-speedometer/

#### Product version

Highcharts v9.1.2
#### Affected browser(s)
Version 109.0.5414.75 (Official Build) (64-bit)

**Comment by pawellysy** [comment]
hi, @sathish151198, thanks for reporting this issue!

The plotBand displayed on the gauge demo is generally an inactive representation. 
The gauge series has only 1 point, represented by a dial, and when hovering over it, the tooltip is displayed. I don't understand what should be in the tooltip's content when hovering over the gauge since all information is on the xAxis.

Could you elaborate, on what would you like to display in the tooltip? In my opinion, it is redundant.

**Comment by sathish151198** [comment]
We would like to display the actual value and target value in the tooltip. Is this possible?

**Comment by pawellysy** [comment]
You can create the custom tooltip like in the forum thread here: https://www.highcharts.com/forum/viewtopic.php?t=45482
Sorry, but we treat GitHub as a feature/ bug tracking tool, so for further support please reach out to us via [available support channels](https://www.highcharts.com/blog/support/)(e.g. forum shared above). Thanks!

Closing, since we won't implement this
