### ISSUE TITLE
Line that connects points gets messed up when updating chart

### ISSUE THREAD

**Issue by rodrake1** [highcharts/highcharts#18400]
#### Expected behaviour
When I have a line chart or a scatter chart with points connected by a line, I expect the line to remain the same if I update the chart properties like line color or title without changing the series data.

#### Actual behaviour
When I update, for example, the title, the line that connects points changes in the wrong way, messing up the chart, even if data was not changed.

#### Live demo with steps to reproduce
https://stackblitz.com/edit/highcharts-angular-optimal-way-to-update-tkditv?file=src/app/app.component.html

#### Product version
Highcharts v9.1.2

#### Affected browser(s)
Chrome v109.0.5414.120

**Comment by bm64** [comment]
Hello rodrake1 and thanks for reporting the issue.

I wasn't able to recreate the issue in plain Highcharts without angular: https://jsfiddle.net/BlackLabel/0v1rgheb/
I saw that you did create another ticket in highcharts-angular repository: https://github.com/highcharts/highcharts-angular/issues/339 so I'm closing this one as most likely the issue is strictly related to the wrapper.

**Comment by rodrake1** [comment]
Thanks, @bm64 for the workaround!
