### ISSUE TITLE
Tooltip for windbarb ignore `xDateFormat` when grouping is enabled

### ISSUE THREAD

**Issue by ishikawa915** [highcharts/highcharts#18424]
For windbarb, when grouping is enabled, `tooltip.xDateFormat` is ignored and the default format is used.

#### Expected behaviour

Tooltip shows datetime as I set in `tooltip.xDateFormat`.

#### Actual behaviour

Tooltip ignores `tooltip.xDateFormat` and uses default format.

#### Live demo with steps to reproduce

Demo
- https://jsfiddle.net/ishikawa915/52p3nLk6/

Steps to reproduce
1. Open the demo and check tooltip.
    Datetime is displayed in the format `'%k:%M'`.
2. Set `series.windbarb.dataGrouping.enabled` to true.
3. Run the code. Now grouping is enabled and windbarb is not overlapped.
4. Check tooltip for windbarb.
    Datetime is not formatted as I set in `tooltip.xDateFormat`. Default format is used.

I also try to set `series.windbarb.tooltip.xDateFormat`, but nothing changed.

#### Product version

v10.3.3

#### Affected browser(s)

- Chrome
- Firefox
- Edge

**Comment by karolkolodziej** [comment]
@ishikawa915 Thank you for contacting us and properly describing your issue!

I went through your steps and I don't see that problem.
When the `grouping` is enabled, the tooltip has the same format as without that grouping- [demo](https://jsfiddle.net/BlackLabel/zhd98uyq/).

Could you please explain what am I missing here?

**Comment by karolkolodziej** [comment]
When you are using the `grouping` there is a separate `headerFormatter` that bypasses the `xDateFormat`.

In order to configure the tooltip for grouped data, you have to declare `dateTimeLabelFormats` ([API](https://api.highcharts.com/highstock/series.windbarb.dataGrouping.dateTimeLabelFormats)). 
Inside you have to declare an array for each timespan.
In your case, if data is grouped into `hours` that should be enough - [demo](https://jsfiddle.net/BlackLabel/z0jm9d1b/).
