### ISSUE TITLE
For windbarb, `Highcharts.PointOptionsObject` is empty when grouping is enabled

### ISSUE THREAD

**Issue by ishikawa915** [highcharts/highcharts#18425]
I try to show wind direction instead of wind speed in tooltip.
I implemented it by using `tooltip.pointFormatter`.
In `pointFormatter`, wind direction can be referenced by `Highcharts.PointOptionsObject`.
So I pass wind direction to method in order to convert angle to ordinal directions.
However `Highcharts.PointOptionsObject` is empty when grouping is enabled.

#### Expected behaviour

`Highcharts.PointOptionsObject` has option values.

#### Actual behaviour

`Highcharts.PointOptionsObject` is empty.

#### Live demo with steps to reproduce

Demo
- https://jsfiddle.net/ishikawa915/mjrxau3z/

Steps to reproduce
1. Open the demo and check tooltip for windbarb. It shows wind direction.
2. Set `series.windbarb.dataGrouping.enabled` to true.
3. Run the code. Now grouping is enabled and windbarb is not overlapped.
4. Check tooltip for windbarb. It does not show wind direction.
    (convert method returns `--` when value is not ordinal directions)
5. When you uncomment `console.log(this.options)` in pointFormatter, you will see empty object.

#### Product version

v10.3.3

#### Affected browser(s)

- Chrome
- Firefox
- Edge

**Comment by karolkolodziej** [comment]
Hi! 

This is not the fault of Highcharts. 
You have to round the grouped value in order to find it in the direction array.
It might look like this but I will let you finally decide how this value should be rounded- [demo](https://jsfiddle.net/BlackLabel/4qLfck0z/).

If you have a similar question, please get in touch with our [support team](https://www.highcharts.com/blog/support/) first.
We use GH mostly for tracking bugs and features and this is neither of these.

**Comment by ishikawa915** [comment]
Thank you for your quick response.
I understand how to deal with my issue.
And I will contact support team first when I face a issue.
