### ISSUE TITLE
Allow axis label animation to be disabled separately

### ISSUE THREAD

**Issue by FeBe95** [highcharts/highcharts#18429]
# Background & reasoning
Currently the animations of a chart can be set via the `chart.animation` property. This setting enables or disables multiple independent animations at once. For example, whenever you toggle a series in the legend the following animations are triggered:
- The (de-)selected series is smoothly shown / removed from the chart area
- The old axis labels fly out and the new labels fly into the chart area

In my case the latter animation is triggered because the label formatter only incorporates data from the visible series and thus the texts change upon toggling a series. Take a look at this example:
https://jsfiddle.net/FeBe95/c1z7w6fj/

The percentages do change but it doesn't make sense to have the labels fly in and out. Currently there is no way to disable this animation separately and keep the animation of toggling a series. Setting `chart.animation` to `false` disables both animations. 

# Proposed solution
In the source code there already is a seperate check whether to perform the axis animation. Though it currently only depends on the `axis.tickInterval` and `axis.labels.step` properties:
https://github.com/highcharts/highcharts/blob/ac0b014a021c8ec7017bef2b19caf119418c32a3/ts/Core/Axis/Tick.ts#L216-L217

The new feature could be implement as follows:
- Introduce a new boolean `axis.labels.animation` property
- Take this property into account for the check, in addition to `axis.tickInterval` and `axis.labels.step`

# Further thoughts
I thought about some workarounds but they seem unnecessarily complicated and might not even work:
- Use HTML labels, a data-percentage attribute on the span and a CSS ::after pseudo selector to display the percentage. The text content of the label should stay the same and thus the animation should not be triggered (?).
- Use the annotation module and place the calculated percentages manually next to the labels. Update the annotations when any series is toggled.

# Library related to the feature
Highcharts

----

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by TorsteinHonsi** [comment]
Thanks for writing!

This animation shouldn't happen, and I consider it a bug. If the bug were fixed you wouldn't need to disable animation.

See the minimal demo: https://jsfiddle.net/highcharts/ygo7c4xn/. By toggling one of the series, the label gets a new text and is animated in and out.

_Internal note_
The problem comes from here:

https://github.com/highcharts/highcharts/blob/56f742e80ff9bf3c13b328f5eb49c7336e8d03d2/ts/Core/Axis/Tick.ts#L768-L779

The logic looks for a label with the same text, and does't consider that the text may change for the same tick. I see two possible solutions:
1. Check for `tick.pos` instead of `tick.label.textStr`. However that may break the logic around `xAxis.uniqueNames`. Tests will reveal that.
2. If number 1 fails, the other approach is to find out why it animates out of the plot area and back in to the left, when it should just crossfade in place. The tick position never changes.
