### ISSUE TITLE
The chart update method does not have set animations to true by default.

### ISSUE THREAD

**Issue by karolkolodziej** [highcharts/highcharts#18450]
#### Expected behaviour
As [API documentation](https://api.highcharts.com/class-reference/Highcharts.Chart#update) states, the animation should be enabled by default while performing the chart update.

#### Actual behaviour
In my case, I would like to disable all the animations and only perform them while updating the chart.
When performing chart updates with only specifying one argument, the chart does not animate.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/h6dvsLf0/

#### Product version
 Highcharts JS v10.3.3 (2023-01-20)

#### Affected browser(s)
All

#### Suggested fix
```TS
    public update(
        options: Partial<Options>,
        redraw?: boolean,
        oneToOne?: boolean,
        animation?: (boolean|Partial<AnimationOptions>)
    ): void {
        animation = pick(animation, true);
```

**Comment by Vazonik** [comment]
The fix causes many unit tests that use the update method to fail. I guess some positions are checked in these tests, so they probably won't be able to fully animate before the test conditions are met. Does it make sense to change them or should the documentation be changed instead? @TorsteinHonsi

**Comment by TorsteinHonsi** [comment]
Okay, this is a documentation issue rather than a behaviour issue. When you set `chart.animation: false` in the configuration options, you turn it off by default for all updates. 

> In my case, I would like to disable all the animations and only perform them while updating the chart.

@karolkolodziej `chart.animation` is not the way to do that, because `chart.animation` only works when updating the chart. See the [description in the docs](https://api.highcharts.com/highcharts/chart.animation). If you mean the entrance animation of the data series, you correctly disabled those by setting `series.animation`.

#### Suggested fix
Update the docs for `Chart.update`. It actually defaults to `undefined`. When `undefined`, it applies the animation that is set in the `chart.animation` option, which in turn defaults to `true`.

Check the docs for [chart.animation](https://api.highcharts.com/highcharts/chart.animation). Is it correct that it defaults to undefined? I think it actually defaults to true. Check the implementation.
