### ISSUE TITLE
Datetime x-axis min/max not respected in mixed column & line chart

### ISSUE THREAD

**Issue by awonihlgard** [highcharts/highcharts#18503]
#### Expected behaviour

The x-axis should start and end on the specified min and max values.

#### Actual behaviour

When both the column and line series are shown in the chart the x-axis starts and ends on the expected values, but when the
column serie is deselected the x-axis becomes wider and does not respect the specified min and max values.

#### Live demo with steps to reproduce

https://jsfiddle.net/4jrso5pz/3/

Deselect the column serie to reproduce the issue (note that the issue does not occur if the column chart is removed entirely from the config).

#### Product version

Highcharts 10.3.2

**Comment by awonihlgard** [comment]
Another reproduction that looks broken even when all series are selected: https://jsfiddle.net/ecqk3jph/2/

Note what happens when the line serie i deselected

**Comment by karolkolodziej** [comment]
Hi @awonihlgard!

There is a difference in `pointPlacement` ([API](https://api.highcharts.com/highcharts/series.line.pointPlacement)) between the line and column series.
In order to change this behaviour, please set them as the same for both series- [demo](https://jsfiddle.net/BlackLabel/gja0w5h1/).
