### ISSUE TITLE
Legend item does not scale correctly when using font style with rem units

### ISSUE THREAD

**Issue by apokryfos** [highcharts/highcharts#18520]
#### Expected behaviour
I would expect the legend item icons to scale proportionally to the legend text size when using a style like e.g.
```
font: "1rem Arial, \"Liberation Sans\", Freesans, sans-serif",
```

#### Actual behaviour
The legend icon keeps its default size unless we also specify:

```
fontSize: '1rem'
```

#### Live demo with steps to reproduce
https://jsfiddle.net/846tfykc/

#### Product version
Might affect more but at least affects versions 8+

#### Affected browser(s)
Chromium (also Chrome, Edge) and Firefox

I think the issue is that in the absense of a `fontSize` option in the legend `itemStyle`, it uses a default of 12px font size to calculate the size of the legend icons.

**Comment by bm64** [comment]
Hello @apokryfos and thanks for reporting the issue.

It looks like `renderItem` method checks only `fontSize` property to get font metrics and ignores `font` property:
https://github.com/highcharts/highcharts/blob/831766b7e843d30dbec960f7088b2aed24aee4de/ts/Core/Legend/Legend.ts#L729-L735

As a workaround you can overwrite `renderItem` method and pass `undefined` for the first parameter in renderer.fontMetrics, which will result in getting font size from the DOM instead of options (line 86): https://jsfiddle.net/BlackLabel/qtszv5fo/

**Comment by TorsteinHonsi** [comment]
This will be fixed with Highcharts v11, see https://github.com/highcharts/highcharts/pull/18580#issuecomment-1446220545
