### ISSUE TITLE
Zooming and Panning in Orthographic Projection

### ISSUE THREAD

**Issue by magdalena-gut** [highcharts/highcharts#18542]
#### Current behavior
Panning after zooming resets the zoom to the default. The issue only occurs with orthographic projection.

#### Live demo with steps to reproduce
Zoom the chart and then rotate the globe.
https://jsfiddle.net/BlackLabel/8wu2167a/

#### Expected behavior
https://jsfiddle.net/BlackLabel/hqzu9sLo/

#### Last working version
10.1.0

**Comment by magdalena-gut** [comment]
The 10.0.0 vesrion (and 10.1.0 as well) doesn't seem stable too:
![OrthographicPanning](https://user-images.githubusercontent.com/91164859/220404658-b8a2d32c-a68b-4989-a2c5-1d41a2b40392.gif)

**Comment by hubertkozik** [comment]
It seems, that the bug is not related to Orthographic projection, but to `mapView.update` method, which is overwriting the actual zoom of the map. The issue is reproducible on every projection, but only orthographic is firing the `mapView.update` to set a proper new projection rotation - that's why we have discovered this bug.

Demo with the issue on another projection: https://jsfiddle.net/BlackLabel/hae9wmz4/
Steps: 
1) Zoom in by using the plus button.
2) Click the button under the map chart - the map will be zoomed out, but it shouldn't.

**Comment by hubertkozik** [comment]
Also, there is a problem, that you cannot rotate the world, when there are few series shapes, like in this demo: https://jsfiddle.net/BlackLabel/c6szh74d/

I think it also should be covered in this issue.
