### ISSUE TITLE
overscroll has no effect if min/max is set

### ISSUE THREAD

**Issue by gruuschesdevelopmenthq** [highcharts/highcharts#18616]
#### Expected behaviour
Loading the whole chart range but having the inital zoom level on e.g 1 month + having e.g 1 week of empty data points on the right that create some space (overscroll).

#### Actual behaviour
Overscroll has no effect if min/max is set on xAxis.
Furthermore if min/max is not set and the user starts to move in the chart the overscroll gets removed, which is good. But if the user goes back in the initial position at the end of the chart, the overscroll is never shown again. This should be persisted.

#### Live demo with steps to reproduce
overscroll with min/max set and no effect of space: https://jsfiddle.net/mpu2xv7q/15/
overscroll with min/max deactivated and space is there:  https://jsfiddle.net/mpu2xv7q/17/

#### Product version
├── highcharts-react-official@3.1.0
├── highcharts@10.3.3

#### Affected browser(s)
Firefox
Chromium
Chrome
Waterfox
Duckduckgo

**Comment by bm64** [comment]
Hello @gruuschesdevelopmenthq.

I've checked the first fiddle but it seems to work correctly. The overscroll is not really visible, because `xAxis.max` value is set almost where data ends. The timestamp of the last point is `1640908800000` and your max is equal to `1640995200000`. The difference between those two timestamps is equal to `86400000`, which is one day, and that space is actually visible. Try to increase max value and you'll see the overscroll: https://jsfiddle.net/BlackLabel/pycha9td/ (Remember that Date.UTC expects monthIndex to be an integer between 0 (January) and 11 (December)
