### ISSUE TITLE
Gantt dataLabels rendered with useHTML render above the tooltip

### ISSUE THREAD

**Issue by kamil-musialowski** [highcharts/highcharts#18610]
#### Expected behaviour
Tooltip should be rendered on top of a HTML `dataLabels` (it should cover it)

#### Actual behaviour
HTML `dataLabels` are rendered above the tooltip

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/8n4zcmrg/

Hover over the orange point to see how tooltip does not cover the `dataLabels`

#### Product version
Highcharts Gantt v10.3.3

**Comment by karolkolodziej** [comment]
This issue is not related to Gantt but it's a general limitation of the MTML and SVG mix -[demo](https://jsfiddle.net/BlackLabel/vc73wu2t/).

As a  workaround, you can set a pure HTML tooltip- [demo](https://jsfiddle.net/BlackLabel/vrm57gqj/).
Similar issue with more details: https://github.com/highcharts/highcharts/issues/9935
