### ISSUE TITLE
Support momentary events in the x-range chart

### ISSUE THREAD

**Issue by timmy-wright** [highcharts/highcharts#18679]
# Description of the feature

Currently events on an x-range chart have to have both a start and end date. However:
* If the end date is missing, the item is not shown
* If the end and start date are the same, the item is not shown

Sadly, the data we are graphing has events that occur at a time, as well as events that take time to process (we are visualising the a kubernetes cluster and it's messy). 

Currently we're using vis-timeline. But we love highcharts more and want to migrate.

# Library related to the feature
Highcharts -- x-range chart

# Proof of Concept/Live example for the feature

Here is how it renders in vis-timeline. The middle event is one with no endtime

![image](https://user-images.githubusercontent.com/7540034/225501284-e0932bbc-6117-40e9-a988-f088d4d4409b.png)

Here is the data we're using for that timeline if it helps:
```
[
  {
    "StartTime": "2022-10-10T10:10:00.000Z",
    "EndTime": "2022-10-10T10:11:00.000Z",
    "Content": "Item 1"
  },
  {
    "StartTime": "2022-10-10T10:11:30.000Z",
    "Content": "Item 2"
  },
  {
    "StartTime": "2022-10-10T10:12:00.000Z",
    "EndTime": "2022-10-10T10:13:00.000Z",
    "Content": "Item 3"
  }
]
```

----

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by TorsteinHonsi** [comment]
Thanks for your suggestion!

The scope of the x-range _series type_ is to visual a range between two points in time - that's what it does. In order to render single a point in time, you have some options:

* Use the flag series from the Highcharts Stock package: https://www.highcharts.com/docs/stock/flag-series
* Use a gantt chart with milestones https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/gantt/gantt/milestones

* Or use other series types with single data points, for example scatter.

**Comment by drtimwright** [comment]
Thanks - we need both data points and ranges on the same line. It looks like the gantt chart might be able to do this - the example given has each gantt item on a different line, but I'm assuming that's configurable so it could be a goer!
