### ISSUE TITLE
Using Web Components inside the tooltip does not properly size the tooltip's box.

### ISSUE THREAD

**Issue by troyvassalotti** [highcharts/highcharts#18676]
#### Expected behaviour

Using the `headerFormat`, `pointFormat`, `pointFormatter`, or `footerFormat` options of `tooltip` to place web components inside the tooltip would create a tooltip that is sized to fit the content.

#### Actual behaviour

The final size of the content within the web component is not taken into account and as such the tooltip's rendered size is smaller than it should be, with the web component overflowing the container.

#### Live demo with steps to reproduce

https://jsfiddle.net/w7b3xfzp/3/

#### Product version

Highcharts v10.3.3

#### Affected browser(s)

Firefox, Edge, Chrome, most likely Safari though I can't test that browser.

#### Update

Tested this again with a custom web component and it appears the issue is isolated to the use of Shadow DOM. See this fiddle where a web component is used without the Shadow DOM: https://jsfiddle.net/7qgu9mdz/7/

**Comment by troyvassalotti** [comment]
Thanks @bm64, I appreciate the workaround. Since those additional style settings required in the workaround also result in the arrow indicator being removed from the tooltip box, is there currently a known way of recreating that arrow pointing to the data point?

**Comment by bm64** [comment]
Hello @troyvassalotti 

In case where SVG part of the tooltip is disabled, you need to recreate callout arrow yourself. There are few approaches how to do that. You can add custom callout shaped element and position it dynamically or use positioner callback to position whole tooltip so that it points to selected point: https://jsfiddle.net/BlackLabel/f25Lhz3b/
