### ISSUE TITLE
Navigator in a stacked area graph with negative data does not match the plot

### ISSUE THREAD

**Issue by alrahemtulla** [highcharts/highcharts#18696]
#### Expected behaviour
Navigator should match the plot when using stacked negative data

#### Actual behaviour
In highstock v10.3.3, the navigator and the plot do not match when stacking negative data.
Notice that when you change the highstock version to v10.3.2 in the fiddle, the navigator matches the plot.
An obvious workaround would be to set `navigator.series.threshold: 0`, but we shouldn't need to do that to match the plot, especially since we did not need to do that prior to highstock v10.3.3.

#### Live demo with steps to reproduce
https://jsfiddle.net/uL1nmvdz/1/

#### Product version
Highstock v10.3.3

#### Affected browser(s)
Chrome

**Comment by Vazonik** [comment]
After investigation, we concluded that this is not a bug, but the intended behaviour.
To change it set `navigator.series.threshold: 0`. @pawelfus

**Comment by pawelfus** [comment]
This is unrelated to Stock, rather a question of whether `threshold: null` should work for `stacked` series. Highcharts demos:

- v10.3.2: https://jsfiddle.net/BlackLabel/y5edp9o8/
- v10.3.3: https://jsfiddle.net/BlackLabel/y5edp9o8/1/

Navigator has [`series.threshold`](https://api.highcharts.com/highstock/navigator.series.threshold) set to null. Redirecting the question to @TorsteinHonsi 
___
Longer explanation:
In v10.3.2, `threshold: null` was ignored. It was ignored because of a simple mistake in code:
```ts
let threshold: null | number,
    value: number;

threshold = 4;
value = Highcharts.pick(Highcharts.isNumber(threshold) && threshold, yAxis.min); // returns 4, good

threshold = null;
value = Highcharts.pick(Highcharts.isNumber(threshold) && threshold, yAxis.min); // returns FALSE, wrong

// Later in code:
let pixel = yAxis.translate(value, ....); // value equals false which means value gets casted to 0
```
