### ISSUE TITLE
Zoom - Bad Performance

### ISSUE THREAD

**Issue by i-frs** [highcharts/highcharts#18725]
#### Expected behaviour

Zooming on grouped data should ungroup the data and have consistent performance, regardless of zoom level.

#### Actual behaviour

Slowdown of Highstock when zooming in on grouped data

#### Live demo with steps to reproduce
https://jsfiddle.net/freseb/cu6mkf07/

Use the mouse wheel to zoom in. There is a noticeable loss of performance the more you zoom - although the number of points remains the same / decreases. 

#### Product version
Highstock v10.3.3

#### Affected browser(s)
(Latest) Chrome & Firefox

**Comment by karolkolodziej** [comment]
Hi @i-frs!
I see that you took most of the functionality from https://github.com/highcharts/highcharts/pull/18468

Could you please comment under that PR and express your concerns?
It will be probably easier for @DJTechnoo to explain everything!

For now, I'm closing this issue since it involves a bunch of custom code that is not yet integrated into the core.
But we definitely are going to take a look into that under the PR.
