### ISSUE TITLE
Datetime x axis displaying unexpected ticks/spacing

### ISSUE THREAD

**Issue by itorras13** [highcharts/highcharts#18743]
#### Expected behaviour

I expect only the months of February, March,  and April to appear as the categories

#### Actual behaviour

It displays weeks instead of months for categories if the union of category values for each series is empty

#### Live demo with steps to reproduce
http://jsfiddle.net/jvkp0u76

If you uncomment the one data line in the second series you will see the expected result. Seems like if there is a common value between the series it displays correctyl.

With line commented
<img width="655" alt="Screenshot 2023-03-27 at 3 16 33 PM" src="https://user-images.githubusercontent.com/5544496/228079327-7144572b-1446-4395-9a7e-959ff5599f14.png">
With line uncommented
<img width="657" alt="Screenshot 2023-03-27 at 3 16 48 PM" src="https://user-images.githubusercontent.com/5544496/228079368-b1288d22-87aa-4bd7-ad87-e82f49ce07e7.png">

#### Product version
Latest version of highcharts

#### Affected browser(s)
Tested on chrome (Version 111.0.5563.110)

**Comment by bm64** [comment]
Hello @itorras13 

The demo that you linked doesn't seem to show the issue. Please check it.
By looking at the images I can tell that they look correct. In datetime axis ticks are computed automatically to fill available axis space. In the second image you can see less ticks because points are thick and consume a lot of space, which results in no ticks between the points. Please try `minTickInterval` option which allows you to define minimum distance between ticks: https://api.highcharts.com/highcharts/xAxis.minTickInterval

Also you might want to try categories axis: https://jsfiddle.net/BlackLabel/p6doq2cr/
API reference: https://api.highcharts.com/highcharts/xAxis.categories

Please let me know if any of these things helped you with resolving the issue.

**Comment by bm64** [comment]
@itorras13 I'm closing the issue for now, but feel free to reopen it if you need.
