### ISSUE TITLE
DST adjustment is not working every time

### ISSUE THREAD

**Issue by adityapachpor978478** [highcharts/highcharts#18764]
Hello, 
I've prepared 2 demo for charts for "America/Los_Angeles" timezone,
in 2022 when clocks are shifted forward, the adjustment can be seen in charts, however, for the same timezone in 2023, this adjustment is not visible.
The clock forward reference links are also specified along with snippets.

2022 DST adjustment working fine, 2AM to 3AM span is not observed in chart
On 13 March 2022, clock is turned forward 1 HR at 2AM
https://www.timeanddate.com/time/change/usa/los-angeles?year=2022
https://jsfiddle.net/adityapachpor/waqbzuvk/1/

2023 DST adjustment is not working, 2AM to 3AM span observed in chart
On 12 March 2023, clock is turned forward 1 HR at 2AM
https://www.timeanddate.com/time/change/usa/los-angeles?year=2023
https://jsfiddle.net/adityapachpor/ge8wzykv/6/

**Comment by bm64** [comment]
Hello @adityapachpor978478 and thanks for contacting us.

I think the issue is caused by outdated moment cdn:
`<script src="https://cdnjs.cloudflare.com/ajax/libs/moment-timezone/0.5.13/moment-timezone-with-data-2012-2022.min.js"></script>`
It looks like this CDN works for 2012-2022 years, it weird it doesn't throw any warn in the console.

Please try to replace with this one and let me know if it works correctly:
`<script src="https://momentjs.com/downloads/moment-timezone-with-data-1970-2030.js"></script>`
Demo: https://jsfiddle.net/BlackLabel/a0nzshmq/
