### ISSUE TITLE
Unable to zoom till the very last date point

### ISSUE THREAD

**Issue by rdp1414** [highcharts/highcharts#18863]
#### Expected behaviour
The very last date point, which is `31 March` in this case should be visible when zooming to very right-end.

#### Actual behaviour
That very last date point is dropped in the zoomed view.

#### Live demo with steps to reproduce
https://jsfiddle.net/jpzn082e/

#### Product version
Highstock `v10.3.3`

#### Affected browser(s)
Chrome

**Comment by karolkolodziej** [comment]
Hi @rdp1414!

It is a regression introduced in **v9.3.0.**

_Internal note:_
- Unable to bisect.
- Disabling the `ordinal` solves the issue- [demo](https://jsfiddle.net/BlackLabel/kwbxnfu3/).
- Needs further investigation but I would start with making sure that `toValue` returns a correct value: https://github.com/highcharts/highcharts/blob/e40bc86b5cc05d8debb66a0032fb6bf6191ba2a2/ts/Core/Pointer.ts#L537-L540

**Comment by pawelfus** [comment]
**Workaround:**
Demo: https://jsfiddle.net/BlackLabel/vu1br0wd/

*Internal note:*
Simplified demo: https://jsfiddle.net/BlackLabel/vu1br0wd/2/ (see console: `toValue()` returns the wrong value, should be the same). With workaround works fine: https://jsfiddle.net/BlackLabel/vu1br0wd/3/

> Needs further investigation but I would start with making sure that toValue returns a correct value:

Good point @karolkolodziej ! The bug lies there, in fact, has two heads:
- this condition is wrong (the left is correct, the right part should skip `axis.left`):
https://github.com/highcharts/highcharts/blob/82f37e912adacc5c86446ca2a41197d7ee2730e8/ts/Core/Axis/OrdinalAxis.ts#L475 
- this is looking for an exact position in the array, while should approximate for ordinal (third argument should be set to `true`):
https://github.com/highcharts/highcharts/blob/82f37e912adacc5c86446ca2a41197d7ee2730e8/ts/Core/Axis/OrdinalAxis.ts#L1436-L1439 

The workaround is based on those changes (removing `axis.left` and adding `true` to arguments).

@kamil-musialowski could you help me with this a little? We need to run tests and check if this doesn't solve other regressions: #17730, #16996, #16616, and the one you are working on (with Annotations)

**Comment by pawelfus** [comment]
Hello @rdp1414 

Thank you for testing! Could you please try this? Demo: https://jsfiddle.net/BlackLabel/fts87Leu/1/

*Internal note:*
Classic JS rounding errors:
```ts
> 667785600000 * 1.01e-9
< 674.4634560000001
```
Added `correctFloat()` - now it's better. However, there's still issue with `>=` and `>` when comparing indexes. I would love to change that, however this: https://github.com/highcharts/highcharts/commit/9aa0b12dab8009115826a5214208fafb99f978f5 - will break.. (demo: https://jsfiddle.net/BlackLabel/o1jyu7dt/1/ - add y-measue annotation to the chart - annotation is not rendered - perhaps we should review solution for #16316)

**Comment by rdp1414** [comment]
Hello @pawelfus ,

After implementing, the solution you offered in your last update in our charts, our Testing team pointed out an issue.

So, we keep some space towards the right-side of the chart using `chart.marginRight` option where we put some financial information text. In the demo which you gave in the last update, 
> Hello @rdp1414
Thank you for testing! Could you please try this? Demo: https://jsfiddle.net/BlackLabel/fts87Leu/1/

If you add `chart.marginRight: 60` to your demo fiddle, and try zooming - You'll see that the last date point is dropped. Demo https://jsfiddle.net/ysk1a6m4/. See gif:
![margin-right-zoom](https://user-images.githubusercontent.com/48443806/235635879-fbe07ae7-7426-478d-99df-a09b592093f0.gif)

**Comment by kamil-musialowski** [comment]
Hi @pawelfus, of course I'll help!

Tested with the addition of `axis.left` removal, `true` as a third `findIndexOf()` argument and  `correctFloat()` fix.

OP demo still seems to not work for me with `chart.width: 800` but works with 400.

#18459 - no improvement,
#17730 - no improvement,
#16996 - no improvement,
#16616 - no improvement

**Comment by pawelfus** [comment]
We will continue work on this next week
