### ISSUE TITLE
Series color is not reflected in the legend in the Gantt chart

### ISSUE THREAD

**Issue by wavewalker5357** [highcharts/highcharts#18874]
#### Expected behaviour
Series labels in the legend in the Gantt chart can show colors based on the series color in the chart.

#### Actual behaviour
The series label in the legend in the Gantt chart doesn't reflect the series color in the chart so the label always shows grey color.

#### Live demo with steps to reproduce
Here's an idea how it works dine with button, not the legend
[]
![Screenshot 2023-01-19 173222](https://user-images.githubusercontent.com/4416014/234294498-1ecc2ef1-4035-4932-9a6e-9d52466d8f4e.png)
(https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/gantt/demo/download-pdf#&togetherjs=EkuxIC8rLz)

#### Product version
Highcharts 10.2

**Comment by wavewalker5357** [comment]
> Hello @wavewalker5357, thanks for reaching out to us!
> In the demo you shared, the color of the button is set manually through CSS.
> Could you share the demo with the config, where you have the same chart as in the image above? Thanks!

Here's a similar example with the legend enabled, without the button: https://jsfiddle.net/L7h26k3e/1/

**Comment by pawellysy** [comment]
Hello @wavewalker5357, thanks for your patience.
The color in legend in any series is set by the following function
```js
getColor() {
    if (this.chart.styledMode) {
        this.getCyclic('color');
    } else if (this.options.colorByPoint) {
        this.color = "#cccccc" /* Palette.neutralColor20 */;
    } else {
        this.getCyclic('color', this.options.color ||
            defaultOptions.plotOptions[this.type].color, this.chart.options.colors);
    }
}
```

As you can see, if the series has a `colorByPoint` option enabled, then the color of the series is set as `#cccccc` as default. 
If you want to change this color, you need to set the `colorByPoint: false` for the series, which is set to true by default for some series, like `xrange` or `gantt`.


Here is the demo, with this option enabled: https://jsfiddle.net/BlackLabel/mzauLd1n/2/

For future, please reach out to us via our available support channels first, so that our support engineers could help you with your chart configuration :)

**Comment by wavewalker5357** [comment]
It works fine! Thanks for the provided solution :)
