### ISSUE TITLE
Multiple SVG filters with the same id when multiple charts

### ISSUE THREAD

**Issue by jakubSzuminski** [highcharts/highcharts#18920]
#### Actual behaviour
Each drop-shadow filter has the same id (when we create multiple charts we will get multiple elements with the same ID).

#### Live demo with steps to reproduce
**Demo:** https://jsfiddle.net/BlackLabel/1qo079ue/
Two charts, each one of them has a filter with the same id (see console log).

#### Product version
Highcharts 11

Reported by the forum user in this topic: https://www.highcharts.com/forum/viewtopic.php?f=9&t=50781&p=185907#p185907

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

We need to use a unique key like we do for other references to elements in `defs`, for example for [textPath](https://github.com/highcharts/highcharts/blob/df9b7029f0d6b2cab574e9a50cea2cd69bd30a13/ts/Core/Renderer/SVG/SVGElement.ts#L1890), [gradients](https://github.com/highcharts/highcharts/blob/df9b7029f0d6b2cab574e9a50cea2cd69bd30a13/ts/Core/Renderer/SVG/SVGElement.ts#L996) and [clip rectangles](https://github.com/highcharts/highcharts/blob/df9b7029f0d6b2cab574e9a50cea2cd69bd30a13/ts/Core/Renderer/SVG/SVGRenderer.ts#L1673).

This unique key should then be applied in the `shadowDefinition` function:

https://github.com/highcharts/highcharts/blob/df9b7029f0d6b2cab574e9a50cea2cd69bd30a13/ts/Core/Renderer/SVG/SVGRenderer.ts#L604

Note that we want to retain caching, so that we don't end up repeatedly producing new definition elements with the same properties in the same chart.
