### ISSUE TITLE
`dataLabels` in sunburst aren't positioned properly when `useHTML` is enabled

### ISSUE THREAD

**Issue by jedrzejruta** [highcharts/highcharts#18953]
#### Expected behaviour

All data labels appear inside nodes on corresponding positions.

#### Actual behaviour
Some data labels are positioned on top-left corner of the chart, outside of plot area.

#### Live demo with steps to reproduce
[https://jsfiddle.net/BlackLabel/9fy7wrvg/](https://jsfiddle.net/BlackLabel/9fy7wrvg/)

#### Product version
v11.0.0, works fine in v10.3.3

**Comment by jedrzejruta** [comment]
_Internal note:_
`git bisect` pointed to [fc06888](https://github.com/highcharts/highcharts/commits/fc0688820f93056923197cc6c6c901a958e16e80) as the first bad commit.

**Comment by TorsteinHonsi** [comment]
#### Workaround

Set `dataLabels.rotationMode` to `auto`, which was the default prior to v11: https://jsfiddle.net/highcharts/ouhr7daj/

#### Suggested fix
Since v11 the default rotation mode is `circular`, which will introduce text paths when there is space for it. But HTML doesn't support text paths. So we need to check `useHTML` before running this rotation mode, and if it is true, we do the `auto` rotation mode instead.
