### ISSUE TITLE
Sankey doesn't draw properly when specifying node columns without column 0

### ISSUE THREAD

**Issue by FusionSnowball** [highcharts/highcharts#18983]
#### Expected behaviour
When specifying column numbers on nodes if there are no nodes in column zero I expect the rest of the chart to be drawn normally with an empty space where column zero would be.

#### Actual behaviour
Where there are no nodes in column zero, nodes in all columns appear as small circles with no data flows between them.

#### Live demo with steps to reproduce
Sankey with nodes in column zero: https://jsfiddle.net/vk7taofj/2/ 
Same Sankey with no nodes in column zero: https://jsfiddle.net/vk7taofj/1/ 

#### Product version
Highcharts 11.0.1

#### Affected browser(s)
Chrome 113

**Comment by karolkolodziej** [comment]
Hi @FusionSnowball!

Could you please explain in this[ simplified example ](https://jsfiddle.net/BlackLabel/uyozdj14/)how you expect the nodes to be placed if you move the `China` node to column `1`? Also could you please explain/draw how they should be connected? I'm afraid I don't understand the issue here.

**Comment by karolkolodziej** [comment]
Thank you for the additional feedback! For now, this is not possible to implement.
Let's treat this as a feature request.

**Comment by karolkolodziej** [comment]
yes, adding a dummy node is a valid and the simplest workaround in this case.
