### ISSUE TITLE
A negative number with space is treated as text in data module.

### ISSUE THREAD

**Issue by Vazonik** [highcharts/highcharts#19017]
#### Expected behaviour
Text describing a number containing a space as a thousand separator should be treated by the data module as a number regardless of whether it is positive or negative.

#### Actual behaviour
Text describing a number containing a space as a thousand separator is not treated by the data module as a number when it is negative.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/9rh4uz2v/

#### Product version
Highcharts v11.0.1

#### Workaround
https://jsfiddle.net/BlackLabel/v5ndkfgh/

**Comment by AmoghAnantha** [comment]
Hi Vazonik,
#19017:
**You can use beforeParse callback function now,
Solution : https://jsfiddle.net/tse1zyu6/3/**

beforeParse: [Highcharts.DataBeforeParseCallbackFunction](https://api.highcharts.com/class-reference/Highcharts#.DataBeforeParseCallbackFunction)Since 6.1.0
A callback function to modify the CSV before parsing it. Return the modified string.

Defaults to undefined.

Try it
[Modify CSV before parse](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/line-ajax/)

**Comment by Vazonik** [comment]
Hi @AmoghAnantha, thanks for the suggestion. However, `beforeParse` works only for CSV, and the problem is general in the data module, e.g. for tables:
- wrap workaround:  https://jsfiddle.net/BlackLabel/rcy4d1vk/
- `beforeParse`: https://jsfiddle.net/BlackLabel/ngf945s8/
