### ISSUE TITLE
`oneToOne` update does not work correctly for different number of series

### ISSUE THREAD

**Issue by jakubSzuminski** [highcharts/highcharts#19019]
#### Actual behaviour
When updating the chart with `chart.update(newSeriesConfig, true, true)` the `series.data` is not updated correctly.

#### Live demo with steps to reproduce
**Demo:** https://jsfiddle.net/BlackLabel/hpot92dr/
1. Click the "first" button
2. Click the "second" button
3. Click the "first" button again

The series is not updating from second -> first config.

#### Product version
Highcharts 11

#### Affected browser(s)
All (?)

This might be a bigger problem for framework & wrapper users as all chart updates are `oneToOne`.

**Comment by AmoghAnantha** [comment]
Hi Jakub Szuminski,
#19019
Solution:
By creating chart object inside the event listener basically creates new chart whenever a button is clicked with updated data.
https://jsfiddle.net/x1m2kuny/

**Comment by bm64** [comment]
Hello @jakubSzuminski and @AmoghAnantha 

The issue stems from a process known as data mutation in JS. Follow given reproduction steps and see in the console how the data gets mutated: https://jsfiddle.net/BlackLabel/xjd14gsr/

The intended way to handle situation like this is to set `allowMutatingData` to `false`: https://jsfiddle.net/BlackLabel/enfz13jh/ 
or work on deep copies of config objects rather than on original data.
