### ISSUE TITLE
Border radius of columns applies to the top for negative values when `series.column.zoneAxis = 'x'`

### ISSUE THREAD

**Issue by jakubSzuminski** [highcharts/highcharts#19028]
#### Actual behaviour
Changing the `series.column.zoneAxis` property to `x` makes the `series.column.borderRadius` not apply correctly for the columns of negative value.

#### Live demo with steps to reproduce
**Demo:** https://jsfiddle.net/BlackLabel/edqbfunh/
1. Open the demo
2. See how the border radius is applied
3. Comment the `zoneAxis: 'x'` line

#### Product version
Highcharts 11

#### Affected browser(s)
All?

**Comment by hubertkozik** [comment]
Also, the tooltip is rendering wrongly for column series if you set `zoneAxis: 'x'`.
**Demo:** https://jsfiddle.net/BlackLabel/jcf120hp/

**Comment by TorsteinHonsi** [comment]
_Internal note_

When the `zoneAxis` is `x`, `point.negative` is not true in this location:

https://github.com/highcharts/highcharts/blob/9ff918be0104d77d0b1981e11e0daaa2c4c89ecd/ts/Extensions/BorderRadius.ts#L462-L463

Subsequently, the corner rounding is not flipped. 

The tooltip is probably the same root cause, the `point.negative` is not true. So we want to find out why.

**Comment by hubertkozik** [comment]
Yes, `point.negative` is wrongly calculated for Column Series. I have prepared a PR with the solution and I'm just waiting for CI to pass :)
