### ISSUE TITLE
Highchart.com along with "No data to display" appears on the chart

### ISSUE THREAD

**Issue by pranayjoshicse** [highcharts/highcharts#19044]
#### Expected behaviour
Highchart.com along with "No data to display" appears on the chart should not be displayed and the chart should get rendered.

#### Actual behaviour
While using highcharts in a normal manner, we are intermittently getting "No data to display".

We are using no-data-to-display.js plugin to display a message when no data is visible, and we are overriding its "No data to display" with  "No data available"
It seems like the high-chart library fails to initiate properly due to some unknown reason and it shows "No data to display" message.

#### Live demo with steps to reproduce
Intermittent

#### Product version
v9.3.2

#### Affected browser(s)
All

![no data to display](https://github.com/highcharts/highcharts/assets/4028717/6ed53f3d-2f3a-44de-b461-2d3abea04fa7)

**Comment by bm64** [comment]
Hi @pranayjoshicse 

The `Highcharts.com` text in the bottom right corner can be disabled with `credits.enabled` property set to `false`: https://api.highcharts.com/highcharts/credits

When it comes to `No data to display`, most likely it appears due to some chart misconfiguration. We use github strictly as a but / feature request tracking tool, so please visit our other support channels where our team will help you with finding out what exactly causes the issue: https://www.highcharts.com/blog/support/
