### ISSUE TITLE
Stack Labels rotation is not respected if useHTML = true

### ISSUE THREAD

**Issue by vassil-velichkov** [highcharts/highcharts#19060]
#### Expected behaviour
https://jsfiddle.net/vassil_velichkov/2ypq375v/2/

#### Actual behaviour
https://jsfiddle.net/vassil_velichkov/2p4vrL7w/2/

#### Product version
Highcharts Highcharts 7.1.2 - 11.0.1 (works fine with 7.1.1)
https://jsfiddle.net/vassil_velichkov/2p4vrL7w/5/

#### Affected browser(s)
Google Chrome 113

**Comment by karolkolodziej** [comment]
Hi, @vassil-velichkov.
Thank you for reporting the issue! 

To be precise the rotation in this case is broken since v7.1.3.

_Internal note:_
The `label` method with `useHTML` doesn't support rotation- [demo](https://jsfiddle.net/BlackLabel/x5f6pvga/). 
And as far as I can see `DataLabel.ts` handles the `rotation` differently, see that ternary operator:
https://github.com/highcharts/highcharts/blob/2b3fed7ef378f6a0d233f2bc39094207e591df78/ts/Core/Series/DataLabel.ts#L714-L735

@TorsteinHonsi do you think the `Stacking` should work similarly as the `DataLabel` or the `label` method needs to be changed? I'm in favour of the first option.

**Comment by TorsteinHonsi** [comment]
> I'm in favour of the first option.

@karolkolodziej Yes, that would probably be simpler to achieve. Before doing that though, are you able to pinpoint the exact commit that broke it? Maybe there is some other unintended effect that should be considered.

**Comment by karolkolodziej** [comment]
I was not able to properly bisect but it is most likely this PR: https://github.com/highcharts/highcharts/pull/11237
Rotation was mentioned there but not with the `useHTML` flag.
