### ISSUE TITLE
Area charts with NaN value do not render actual area (just line is rendered)

### ISSUE THREAD

**Issue by deser** [highcharts/highcharts#19148]
I'm upgrading from 7.2.0 to the latest (11.1.0). One issue appeared, which seems to me to be buggy behavior. 
I know, NaN is unexpected value type. But the issue happens only in area chart type, all other charts, even having NaN in series data, are rendered correctly.

@TorsteinHonsi , the behavior has been changed here - https://github.com/highcharts/highcharts/commit/e70baaba67d36aa89b2f724fcf7b9c1e04b0b02f#diff-781d34161016cd83d4211d594c56c68a8c1802de3c17eae5158ebef0f2b5e881L1888 (line 1888 if it doesn't scroll automatically).
I just want to make sure that the change is intentional. Or probably the bug has been introduced there.  

#### Expected behaviour
Area charts containing NaN values render area

#### Actual behaviour
Only line is rendered in case there's NaN in data

#### Live demo with steps to reproduce
https://jsfiddle.net/vpe87cx1/40/
There are 2 identical charts there with 1 difference: last series data point varies from NaN to null. 

#### Product version
11.1.0

#### Affected browser(s)
Latest

**Comment by karolkolodziej** [comment]
Hi @deser! 

Unfortunately the `NaN` is not a valid value for X values- [simplified demo](https://jsfiddle.net/BlackLabel/pohmfncs/).
However in this case I would expect the same behaviour as it is with null values -[demo](https://jsfiddle.net/BlackLabel/2q56uzpe/).
What do you think @TorsteinHonsi

**Comment by TorsteinHonsi** [comment]
@karolkolodziej I agree it's a bug. A simple fix is to perform a stricter numeric test by changing this:

https://github.com/highcharts/highcharts/blob/2decde36d887bf37433c71461e0300ec4685e144/ts/Core/Series/Point.ts#L741C8-L743

Into 

```ts
    public isValid(): boolean {
        return isNumber(this.x) && isNumber(this.y);
    }
```

I haven't run tests on it though, so it may break something else. But this makes sense because it will also handle other invalid cases of `this.x`, like `undefined`, Infinity, -Infinity, strings etc.

**Comment by deser** [comment]
Can we change the label, seems it is decided :)
