### ISSUE TITLE
 Troubleshooting Pie Chart Display Issues Caused by End of Line Characters in CSV

### ISSUE THREAD

**Issue by arqambinrehan-ignishealth** [highcharts/highcharts#19154]
Expected behaviour
Pie chart should display correctly regardless of its labels content.

Actual behaviour
Pie chart skips the values which has end of line character.

Live demo with steps to reproduce
https://jsfiddle.net/arqambinrehan/anrgf85h

The fiddle has 2 examples: one working and one that doesn't. The only difference is one label has end of line char and other does not.

Product version
11.1.0 (fiddle references https://code.highcharts.com/highcharts.js)

Affected browser(s)
All

**Comment by bm64** [comment]
Hi @arqambinrehan-ignishealth 

The problem is due to the newline characters in one of the not working CSV values. Our parser reads these as new rows (\n). You can fix this by adjusting the lineDelimiter property from \n to a different character. You will also need to add that character at the end of each CSV row: https://jsfiddle.net/BlackLabel/tdwjL912/
