### ISSUE TITLE
need to render docx charts as images

### ISSUE THREAD

**Issue by dhananjay9490** [highcharts/highcharts#19214]
# Description of the feature

# Library related to the feature

# Proof of Concept/Live example for the feature

----

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by bm64** [comment]
Hello @dhananjay9490 

Unfortunately I have to close the ticket due to lack of information / description of the feature. 

If your .docx charts are based on some google spreadsheet, you might consider using the data module with the `googleSpreadsheetKey` to link your data: https://api.highcharts.com/highcharts/data.googleSpreadsheetKey 
https://www.highcharts.com/docs/working-with-data/data-module#loading-from-google-spreadsheets

Then use the exporting module to export charts as images: https://www.highcharts.com/docs/export-module/export-module-overview
