### ISSUE TITLE
IE cross site scripting error when trying to export

### ISSUE THREAD

**Issue by ghost** [highcharts/highcharts#1928]
Everytime when we try to export a chart it fails when using IE.
Every other browser accepts it and displays the output correctly but IE fails and shows a message about it modifieing the request to prevent cross site scripting.

I read something about setting up your own server but that is not an option in our project.

**Comment by cxytomo** [comment]
@TorsteinHonsi are you sure you can open http://jsfiddle.net/highcharts/QjJcW/2/show in IE8. JSfiddle doesn't work in IE8.
@anqsolutions did you resolve the problem in the end? I ran into the same problem.

**Comment by cxytomo** [comment]
@TorsteinHonsi  you are right, the generated SVG is wrong. 
@anqsolutions By turning off the IE xss filter(Tools -- Security tab--Internet zone--Custom level button--Enable XSS Filter option,then disable it). By doing this you will successfully redirect to http://export.highcharts.com/. If your SVG is wrong it will hint you.
Watch mine below
![image](https://cloud.githubusercontent.com/assets/2089688/12442880/b086f386-bf8e-11e5-83ea-a4045de5ad4c.png)

Mine is caused by scripts (html5shiv,respond) in order to display normally using bootstrap. svg and other tags are displaced.

**Comment by TorsteinHonsi** [comment]
I can't open that fiddle anymore, it seems like the show page itself no longer supports IE8. Additionally, IE8 doesn't support latest jQuery. Here's how to test it (and the export works for me):

1. Log into jsFiddle in a modern browser.
2. Open http://jsfiddle.net/highcharts/QjJcW/11/ and click _Run_ again.
3. Log into jsFiddle in IE8.
4. Open http://jsfiddle.net/draft.

**Comment by jon-a-nygaard** [comment]
Since we can not reproduce this issue, and it is pending reply, I am closing it. If anyone has further information relevant to this issue, please comment and/or reopen.
