### ISSUE TITLE
Fix to show connecting lines on Waterfall chart having few null data values on Highcharts version 10.3.3

### ISSUE THREAD

**Issue by amruta30** [highcharts/highcharts#19280]
#### Expected behaviour
Please suggest a fix for this issue since we cannot upgrade to latest Highcharts version right now.

#### Actual behaviour
On Highcharts version 10.3.3, if waterfall chart is plotted on data containing few null values, conencting lines are not shown for all valid cases. This issue seems to be fixed on latest Highcharts version(Referred: https://github.com/highcharts/highcharts/issues/18636)

#### Live demo with steps to reproduce
Conencting lines Issue on v10.3.3 : https://jsfiddle.net/rxq4vznj
Connecting lines seen on latest version : https://jsfiddle.net/rxq4vznj/1/

#### Product version
Highcharts version 10.3.3

#### Affected browser(s)
All

**Comment by bm64** [comment]
Hello @amruta30 

I tried putting together a workaround for v10.3.3 by adding in changes from #18636: https://jsfiddle.net/BlackLabel/bzn1583f/. Sadly, it turns out that the fix is just part of what's needed to get the connecting lines working right. After some digging, I found that https://github.com/highcharts/highcharts/commit/73ec1c8d9c9de85076482e463b6f52129c9a86e9, a part of https://github.com/highcharts/highcharts/pull/17796, is also needed (probably along with other changes from the PR). So, I can't give you a workaround for v10.3.3.

I've got to close this ticket because we use GitHub for feature requests and bug tracking, and this ticket doesn't really fit either of those. With any further questions please use one of our other support channels: https://www.highcharts.com/blog/support/
