### ISSUE TITLE
Setting `interpolation: true` on series of type `heatmap` may crash browser with RangeError

### ISSUE THREAD

**Issue by dmyronuk** [highcharts/highcharts#19309]
#### Expected behaviour
Setting `interpolation: true` on series of type `heatmap` should not crash browser.

#### Actual behaviour
Browser may crash when `interpolation: true` is set on heatmap series. 

Stack trace shows `RangeError offset is out of bounds` thrown here https://github.com/highcharts/highcharts/blob/f126dfff2db0dab53737287fdf7e3781860d2288/ts/Series/Heatmap/HeatmapSeries.ts#L647.

#### Live demo with steps to reproduce
Here is a reproduction using the official React wrapper.  This most closely reproduces the issue I ran into.
https://codesandbox.io/s/strange-nobel-4g3ndt?file=/src/App.js

Here is a reproduction using the jsfiddle template without React.  In this case a blank plot is rendered.
https://jsfiddle.net/dmyronuk/gp6wktzv/26/

#### Product version
```
"highcharts": "11.1.0",
"highcharts-react-official": "3.2.0"
```

#### Affected browser(s)
Firefox 115.0
Chromium Version 114.0.5735.198

**Comment by pawellysy** [comment]
Thanks for @dmyronuk for reporting the issue!

**Comment by karolkolodziej** [comment]
@MarkusBarstad. Would you be able to take a look at this? 
It looks like the `scaledPointPos` returns negative values, so the chart crashes.

**Comment by MarkusBarstad** [comment]
@dmyronuk Thank you for the bug-report and the concise demo, and thank you for sharing that workaround @wsoeltz!

After testing, I can see that the issue will actually be fixed by [a bugfix which is awaiting to be evaluated](https://github.com/highcharts/highcharts/pull/19120), hopefully by the end of the week or so.

I can try to figure out a workaround for you in the meantime, though I admit I am not so experienced with HC + React
