### ISSUE TITLE
tickInterval is not work currectly in negative logarithm

### ISSUE THREAD

**Issue by aliakbarazizi** [highcharts/highcharts#19322]
I'm using https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/yaxis/type-log-negative/ demo

But tickInterval is not same when I set allowNegativeLog to before

#### Expected behaviour

https://jsfiddle.net/ecn7sb3z/8/

It should be line on in yAxis in `1, 2, 4, 6, 8, 10, 20`

![image](https://github.com/highcharts/highcharts/assets/8492767/57246cb6-8186-4088-84eb-f9622bf82470)

#### Actual behaviour

https://jsfiddle.net/pxgcn79a/2/

It only show `10, 20` lines

![image](https://github.com/highcharts/highcharts/assets/8492767/e105bb5a-12df-4ef2-8d29-6ffc84452eeb)

#### Live demo with steps to reproduce
https://jsfiddle.net/pxgcn79a/2/

#### Product version
Last version

**Comment by karolkolodziej** [comment]
Hi @aliakbarazizi!

It looks like the logic handling values lower than 10 need some adjustments especially that `10-9`
```JS
if (result < 10) {
    result = (10 * (result - 1)) / (10 - 1);
}
```

If you comment that out it works properly- [demo](https://jsfiddle.net/BlackLabel/y6ncm5ze/).

**Comment by Vazonik** [comment]
If you comment out the lines as @karolkolodziej suggested, the scale on the axis will not match the chart data for values less than 10. The problem is that the tick setting logic for the logarithmic axis is not adapted to the occurrence of a value of 0 and less:
https://github.com/highcharts/highcharts/blob/559db482a420598a9db3e5fe8d49dc353f4ec5f4/ts/Core/Axis/LogarithmicAxis.ts#L236-L238
You can of course add this logic like in this [workaround](https://jsfiddle.net/BlackLabel/ywu3ad9e/).

The question is should we add this to [the demo](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/yaxis/type-log-negative/) or will it cause too much confusion in it? @TorsteinHonsi

**Comment by Vazonik** [comment]
Ok, then I will do it in the demo.
