### ISSUE TITLE
X-range: Tooltip loses default data formatting

### ISSUE THREAD

**Issue by madepiet** [highcharts/highcharts#19362]
#### Expected behaviour
After adding [API-compliant](https://api.highcharts.com/highcharts/series.xrange.data) properties like `name` the tooltip should not lose its default datatime formatting.

#### Actual behaviour
As you can see in the demo below, for data with a `name` set, the tooltip does not recognize `datatime` formatting, and for data without `name`, it formats the data correctly. It would be necessary to standardize this behavior also for the axis standard data type in the X-range series.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/ohxp34qt/

#### Product version
7.0.0

**Comment by karolkolodziej** [comment]
_Internal note:_
It happens because the `key` is replaced by the point `name`. Not saying that the fix should be here, probably not ;) 
https://github.com/highcharts/highcharts/blob/7b7bc1174e3f44be4ecb91fdff3dc0b45d0a0cab/ts/Core/Series/Point.ts#L611-L632

As a workaround, you can use a custom formatter.
