### ISSUE TITLE
Y-axis title that contains HTML is not displayed properly in the exported PNG 

### ISSUE THREAD

**Issue by FatimaZohraaa** [highcharts/highcharts#19413]
#### Expected behaviour
Y-axis title shown vertically read from bottom to top

#### Actual behaviour
Y-axis title is clipped and shown horizontally 

#### Live demo with steps to reproduce
 On JsFiddle: https://jsfiddle.net/highcharts/LLExL/

- add a title that contains HTML to the y-axis by adding this to the chart configuration :

  ```
  yAxis: {
        title: {
              text: 'initial value 10 <sup>3</sup>',
              useHTML: true
        }
  }
  ```
(at this point if you export the PNG, the superscript will be shown as plain text)

- add the following exporting configuration to allow showing HTML `<sup>` tag in the exported PNG:

  ```
    exporting: {
      allowHTML: true
      }
  ```
- Observe that the y-axis title is clipped and shown horizontally 

#### Product version

11.1.0

#### Affected browser(s)
Google Chrome Version 114.0

**Comment by jakubSzuminski** [comment]
Thanks for reporting @FatimaZohraaa!

As you can read in the [API](https://api.highcharts.com/highcharts/exporting.allowHTML):

> Disclaimer: The HTML is rendered in a `foreignObject` tag in the generated SVG. The official export server is based on PhantomJS, which supports this, but other SVG clients, like Batik, does not support it. This also applies to downloaded SVG that you want to open in a desktop client.

So that might happen with custom HTML elements in our current version of the Export Server.

However, recently we've released a beta version of `highcharts-export-server` which now uses **puppeteer** instead of **phantomjs**. You can read more about how to utilize the latest version here: https://github.com/highcharts/node-export-server#puppeteer-version-information

The new version has been deployed to our development server and from what I see everything works fine: https://jsfiddle.net/BlackLabel/3jx2hvtf/

It'll soon be deployed to the default server, but for now you can use the link I've provided in the demo. Please let me know if everything works as expected now.

**Comment by jakubSzuminski** [comment]
I'm closing this issue as it is related to `highcharts-export-server` so its place is rather there: https://github.com/highcharts/node-export-server

However, as I mentioned, this will be solved on the main server when we deploy from the `dev` to `main` which will likely happen in less than a month. For now, you could use the workaround I've provided here: https://jsfiddle.net/BlackLabel/3jx2hvtf/
