### ISSUE TITLE
Highmaps: Maps dont load on v10.3.3 if topology is set on Highcharts.maps and map name is set on chart.map

### ISSUE THREAD

**Issue by amruta30** [highcharts/highcharts#19468]
#### Expected behaviour
We want to know the changes done in library to support mapName in chart.map if topology is already set on Highcharts.map[mapName]. I have compared the map.js for v11.1.0 and v10.3.3. There is a comment that says - " _Default `mapData` for all series, in terms of a GeoJSON or TopoJSON
             * object. If set to a string, it functions as an index into the
             * `Highcharts.maps` array." Then its expected to work for v10.3.3 too.

#### Actual behaviour
We are currently using Highcharts v10.3.3, files - highcharts.js and map.js instead of highmaps.js. We want to support topoJsons and projection types. Earlier, we used to set the geoJson data on Highcharts.maps[mapName as string] and mapName string in chart.map, which worked fine. All maps were loaded successfully. However it is observed that for topoJson data, chart.map is expecting the entire topology(json data) instead of mapname for v10.3.3. Whereas mapName on chart.map works for v11.1.0.

#### Live demo with steps to reproduce
Latest Highcharts v11.1.0: https://jsfiddle.net/amrutaJgtp/s4pLqzjw/
Highcharts v10.3.3: https://jsfiddle.net/amrutaJgtp/s4pLqzjw/1/

#### Product version
v10.3.3

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Hi @amruta30 

This doesn't look like a bug report. If you have questions please contact technical support via Highcharts Forum or a Stack Overflow question tagged "highcharts".

The related reported bug is here: https://github.com/highcharts/highcharts/issues/18590
It was fixed here: https://github.com/highcharts/highcharts/pull/18609

> Why do we need to convert topoJson to geoJson if mapName is specified as string?

Because the conversion happens when TopoJSON content is provided and when a string is used the mapping was not covering TopoJSON format correctly - it was fixed in the PR linked above.
