### ISSUE TITLE
plotLine (html)label position is unpredictable 

### ISSUE THREAD

**Issue by gaunap** [highcharts/highcharts#19488]
#### Expected behaviour
The labels are horizotally aligned and the label fits into the drawing area.

#### Actual behaviour
Both labels have different alignment. The long label is cut-off even the width property is set.

#### Live demo with steps to reproduce
https://jsfiddle.net/stormtroopa/p9aznrjw/18/

#### Product version
11.1.0

#### Affected browser(s)
Chrome, FF, Safari

**Comment by karolkolodziej** [comment]
Hi @gaunap!

I agree, that the labels are positioned inconsitantly when the `useHTML` is enabled- [demo](https://jsfiddle.net/BlackLabel/opf2wnb5/).
Might be connected to the: https://github.com/highcharts/highcharts/issues/16377

_Internal note:_
Looks like it has been broken since v11.0.0 (10.3.3 is the last working version) - unable to bissect.

**Comment by TorsteinHonsi** [comment]
Bisected to d2a643474e6f91ed91035b9e39b25b7d70e0a405

**Comment by TorsteinHonsi** [comment]
The problem is that the font size is not correctly cascading at the time we are measuring the element. This did not matter in v10 because the fonts were pixels. Fix coming up soon.

#### Workaround
```js
Highcharts.wrap(Highcharts.PlotLineOrBand.prototype, 'renderLabel', function(proceed) {
    proceed.apply(this, Array.prototype.slice.call(arguments, 1));

    if (this.label) {
        const align = this.label.attr('align');
        this.label.attr({
            align: ''
        }).attr({
            align
        }).add();
    }
});
```

View it [live on jsFiddle](https://jsfiddle.net/highcharts/v3ogzcpr/).

**Comment by gaunap** [comment]
Thanks for providing the workaround! Works so far...

**Comment by cnrudd** [comment]
@TorsteinHonsi Hi, has this bugfix been released?  
I am using highstock v11.3.0.
I do not see it noted in the [changelog](https://www.highcharts.com/blog/changelog/) for any of the releases since August.
I am experiencing this bug on a vertical plotline.  Demo of bug: https://jsfiddle.net/2eac0rvo/2/

**Comment by TorsteinHonsi** [comment]
@cnrudd Yes it was fixed, but apparently we forgot to add it to the changelog.

Your vertical label aligns correctly if we add `textAlign: 'left'`: https://jsfiddle.net/highcharts/kmc34dwo/
