### ISSUE TITLE
noData value not updating when the state changes in React

### ISSUE THREAD

**Issue by Bipinmv** [highcharts/highcharts#19597]
#### Expected behaviour

 I have a state which holds the chart option. In that config I initialised value of noData with a value (actually wanted to initialise with an empty string to avoid showing "No data to display" for a moment before the original data gets plotted. But initialised with another value to illustrate the issue).

And in the useEffect I set the actual chart option with series data and other props values.

#### Actual behaviour

When there is no data, chart shows the initial value of noData. It should show the updated value. 
state is getting updated correctly but not the chart.

#### Live demo with steps to reproduce
https://codesandbox.io/s/cool-tesla-pqzqdd?file=/src/App.js

#### Product version
Highcharts - 10.3.2

**Comment by KamilKubik** [comment]
Simplified demo: https://jsfiddle.net/BlackLabel/kwtbzyp9/.

You can add the `immutable` option as a workaround using the React wrapper: https://codesandbox.io/s/suspicious-babbage-ztmmjl.

**Comment by Bipinmv** [comment]
1. In the first demo the value is not getting updated. It is showing the initial value.

2 .If I add the `immutable` option and if props or chart config changes then the chart shows initial values

**Comment by KamilKubik** [comment]
In general, the `lang` property should be set globally by the `setOptions` method: https://api.highcharts.com/highcharts/lang. The problem you encountered is setting it on the chart's instance, which is not officially supported, referring to our API. The mentioned `immutable` property creates a new chart instance based on the `options` currently provided to the wrapper, so you can see the effect as a new instance is created instead of updating the existing one. I can see a great explanation, and also a way you should handle it is provided here: https://stackoverflow.com/questions/76950607/nodata-value-not-updating-when-the-state-changes-in-react/76951864#76951864.

**Comment by Bipinmv** [comment]
I have tried `immutable={false}` and it is not working as expected when I actually have data.
Please check the example [https://codesandbox.io/s/festive-curie-wryzl-forked-fn7ycj?file=/src/App.js](https://codesandbox.io/s/festive-curie-wryzl-forked-fn7ycj?file=/src/App.js)

**Comment by KamilKubik** [comment]
All you need here is to define your series as an array of objects instead of an object: https://codesandbox.io/s/festive-curie-wryzl-forked-ldt49w.

**Comment by karolkolodziej** [comment]
Hi @Bipinmv! 

Your issue looks more like a question and as far as I see it was answered on the SO.
If there is anything new about this issue feel free to reopen it!
