### ISSUE TITLE
Ambiguous behavior of the axis labels/ticks calculation procedure

### ISSUE THREAD

**Issue by oleksiy-liulin** [highcharts/highcharts#19604]
#### Expected behaviour
Axis labels and ticks should not change unless the values that affect their calculation (chart size, font size, axis range etc..) remain constant.

For user/programmer it's expected that the tick interval calculation is provided by an internal Highcharts' procedure which gives an unkwonw in advance but the same distance between the ticks. That is, this distance must always be the same no matter in which way the axis is drawn - whether as a result of the initial chart appearance or after its update.
In other words, using the programmer's lexicon - the calculation procedure should be a "pure function" (one that always returns the same result with the same input arguments). 

#### Actual behaviour
Vertical axis labels and ticks changed.

#### Live demo with steps to reproduce
[demo:](https://jsfiddle.net/htk8oa20/2/)
1. Run the demo.
2. Note the vertical axis labels and ticks. They are **25/50/75**
![image](https://github.com/highcharts/highcharts/assets/134580491/6e6b6779-c832-4cf0-bfec-35e0d6a633fd)
4. Click the "Update" button to change series color.
5. Series color is changed from blue to green, but the vertical axis labels and ticks are also changed (recalculated). Now they are **20/40/60**
![image](https://github.com/highcharts/highcharts/assets/134580491/9a1e12cd-a1be-4a14-90bb-eb3d219539a0)

#### Product version
11.1.0

#### Affected browser(s)
Chrome 115.0

**Comment by bm64** [comment]
Hello @oleksiy-liulin and thanks for reporting the issue.

It looks like the bug was introduced along with `crossing` option in v11.0.1. Without the the option, update method doesn't make axis change the ticks:
https://jsfiddle.net/BlackLabel/hL69rp1j/

_Internal note:_
Bisected to: 0d2d431a385d2e2b0d7849ed76fbff55ce0024b2

**Comment by hubertkozik** [comment]
This issue is not related to `crossing` feature. It can be also reproduced without it, but with using `reserveSpace` options for axis labels.

**Demo:** https://jsfiddle.net/BlackLabel/k8g25bmL/

____

**Workaround**
I have prepared a workaround for that issue. If you want to use it in your project simply copy-paste the IIFE function.

**Live demo with a workaround:** https://jsfiddle.net/BlackLabel/5jgypm74/

**Comment by hubertkozik** [comment]
After some investigation, it comes, that this issue is not only related to the charts with small dimensions. It can be also reproduced in other charts, e.g. here: https://jsfiddle.net/BlackLabel/amu5k0er/ to reproduce simply click `Update` button, which fires the `series.update` method without any arguments and ticks are calculated and shown one more time.
