### ISSUE TITLE
When stacking is set as percent, series border at top is not visible

### ISSUE THREAD

**Issue by amruta30** [highcharts/highcharts#19613]
#### Expected behaviour
When series border is enabled, it should be applied to all series properly. Top border should also be visible.

#### Actual behaviour
When series stacking type is set to Percent , series border at TOP position. It is not visible as axis is set to 100% TOP border disappears.

#### Live demo with steps to reproduce
https://jsfiddle.net/amrutaJgtp/9r7a13jy/4/

#### Product version
All

#### Affected browser(s)
All

**Comment by bm64** [comment]
Hello @amruta30 and thanks from contacting us.

The behaviour you're experiencing is not specifically related to stacking with the 'percentage' option. It stems from two default Highcharts behaviors:

- The border is drawn on the shape edge, half inside and half outside the column.

- The column takes up the full plot area vertically because its value (100%) matches the max y-axis value (100%), leaving no space for the outside half of the border, which makes thin (1px width) borders hardly visible or not visible at all.

This behaviour is easier to observe in this demo: https://jsfiddle.net/BlackLabel/cxy9o0tv/ 

This is not a bug, more a configuration issue and to make border fully visible you can adjust the y-axis max value to display the full border: https://jsfiddle.net/BlackLabel/hantkovj/

**Comment by TorsteinHonsi** [comment]
_Internal note_
With the default 1px border width, and a black border, it looks like a bug: https://jsfiddle.net/highcharts/qsk8b4np/

If we were to round the column top down instead of up, we would get the full 1px black line within the plot area. However, the default border color is white, same as the background. With those defaults, it would appear as if the columns stopped 1px _below_ the 100% gridline, which would also look like a bug. So I agree we should leave this as is.


### Workaround
Use `clip: false` https://jsfiddle.net/highcharts/qsk8b4np/1/
