### ISSUE TITLE
All mapbubbles are stacked on top of other in Tilemap chart since 9.3.0

### ISSUE THREAD

**Issue by sagarv-vitara** [highcharts/highcharts#19670]
#### Expected behaviour
Bubbles should placed in appropriate locations based on *x* and *y* values

_Example:_
![image](https://github.com/highcharts/highcharts/assets/89578890/16549634-9210-4ecf-b11d-0a4dc12ef0ef)

#### Actual behaviour
All bubble are stacked on top of each other

*Example:*  
![image](https://github.com/highcharts/highcharts/assets/89578890/fde362c0-97cd-4a15-8b90-296249a22c0f)

#### Live demo with steps to reproduce
[https://jsfiddle.net/sagarv/cdw30neo/9/](https://jsfiddle.net/sagarv/cdw30neo/9/)

Go to the fiddle and you can see the bubbles are stacked on top of each other.

Now comment the imports of latest version and uncomment the imports of version _8.1.2_ and you can see the bubbles are perfectly placed in appropriate location.

#### Product version
9.3.0 to latest

#### Affected browser(s)
Tested on Chromium based Edge.

**Comment by bm64** [comment]
Hi @sagarv-vitara 

As you can read here: https://www.highcharts.com/docs/maps/latlon, https://www.highcharts.com/changelog/#highcharts-maps-v9.3.0
In version 9.3.0 axes in Highcharts Maps were replaced with MapView and cartesian coordinate system doesn't work anymore. Instead of using x and y values you need to use `lat`, `lon` coordinates to position bubbles on the map. Demo: https://jsfiddle.net/BlackLabel/2at4xfge/, https://jsfiddle.net/BlackLabel/sfqw4Lyj/

Because of that, what you reported is not a bug and if you want to create bubble chart where bubbles are positioned with x and y values, please consider using Highcharts and bubble series: https://jsfiddle.net/BlackLabel/j4zmxuno/
API reference: https://api.highcharts.com/highcharts/series.bubble

**Comment by ibeqiri-flexera** [comment]
But he is not trying to create bubble chart but a tilemap with mapBubbles positioned with x and y. @sagarv-vitara am I right?

I am having the same issue currently. My existing x/y coordinates are not working after upgrading to highcharts v11
