### ISSUE TITLE
Points are not updated in the tooltip formatter when using chart.update

### ISSUE THREAD

**Issue by hexagon06** [highcharts/highcharts#19722]
#### Expected behaviour
When using chart.update to change the data in the series I would expect the tooltip to reflect the changes. 
This should include the custom data.
When a property is no longer available on a indexed series data it should not be shown: 
```js
// setting the chart with data of series 1
var series1 = [{y:1, custom:{comment:'echo'}}, {y:2}]

// and updating the chart with data of series 2
var series2 = [{y:1}, {y:2, custom:{comment:'echo'}}]

should show a tooltip with the comment only on the second point
```

#### Actual behaviour
The tooltip is shown correctly initially.
When using chart.update the custom comment data is still shown on the first point tooltip.
The y value is still shown correctly

#### Live demo with steps to reproduce
https://jsfiddle.net/s3opuLjf/3/

use the button on top to change to set 2, you will see echo on both the first and the last point tooltips

#### Product version
Highcharts 10.2.1
With and without Highcharts/vue 1.4.0 (I know this lib is out of scope for this repo)

#### Affected browser(s)
Edge

**Comment by bm64** [comment]
Hello @hexagon06 and thanks for contacting us.

The issue is caused by data mutation. In JavaScript, modifying object references leads to mutations across instances. You have two options to resolve this:

1. Use deep copies of objects to prevent mutations on the original data.
2. Set Highcharts' `allowMutationData` property to false: https://jsfiddle.net/BlackLabel/Lgvqcwt3/ API reference: https://api.highcharts.com/highcharts/chart.allowMutatingData
