### ISSUE TITLE
[Highcharts v10.3.2] - tooltip does not disappear but x-axis crosshair disappears... 

### ISSUE THREAD

**Issue by LearnGrowAndShare** [highcharts/highcharts#19771]
#### Expected behaviour
Tooltip should be hidden just like x-axis crosshair when mouse is away from the point

#### Actual behaviour
 x-axis crosshair is hidden when mouse is away from the point, where as tooltip is displayed.

#### Live demo with steps to reproduce

https://jsfiddle.net/guestMe/9bgtm7ed/8/

Step to reproduce - 
1. Hover on any point, for example in screenshot, i hovered on 5th point from left. 
<img width="1091" alt="Screenshot 2023-09-16 at 12 28 49 PM" src="https://github.com/highcharts/highcharts/assets/12616063/21171222-78e7-43ab-a7cd-2b2bd4499def">

2. Now move mouse some pixel away from  point in between two point, in example screenshot, i have placed in between 5th and 6th point.
<img width="1140" alt="Screenshot 2023-09-16 at 12 29 02 PM" src="https://github.com/highcharts/highcharts/assets/12616063/5729b75f-2882-4c28-bbec-73eea87a0ab1">

Notice, the x-axis crosshair disappeared, but tooltip stays as it is..

#### Product version
highcharts -- version 10.3.2

https://code.highcharts.com/10.3.2/highcharts.js

#### Affected browser(s)
Chrome

**Comment by bm64** [comment]
Hi @LearnGrowAndShare 

This behaviour is intended and caused by `tooltip.split` option. See results with disabled: https://jsfiddle.net/BlackLabel/s6o4cgpd/
If you want to keep the option but still have the tooltip hidden when no point is being hovered, you need to hide the tooltip with `chart.tooltip.hide()` function on `mouseOut` event: https://jsfiddle.net/BlackLabel/3heyg1zm/
