### ISSUE TITLE
[Highstock v10.3.2] custom draggable plotline incorrect placement 

### ISSUE THREAD

**Issue by LearnGrowAndShare** [highcharts/highcharts#19773]
#### Expected behaviour
The point and crosshair should intersect at exact point,  for 11:19 the plotline and point should intersect.

#### Actual behaviour
The point and crosshair should intersect at exact point, where as in screenshot we can see, for 11:19 the line is little next to the point.

#### Live demo with steps to reproduce
https://jsfiddle.net/guestMe/orL5txs0/59/

<img width="1536" alt="Screenshot 2023-09-16 at 2 25 07 PM" src="https://github.com/highcharts/highcharts/assets/12616063/0c09b2cd-8154-4b3f-813a-5906c5358415">

Notice the console log, which says **point found**, but custom plotline is not exactly at 11:19..

Same is happening if moved point to 11:20, where as in console we can notice it says, 11:20

<img width="1728" alt="Screenshot 2023-09-16 at 2 32 42 PM" src="https://github.com/highcharts/highcharts/assets/12616063/a5dc9a6e-1b3d-4663-979e-bd15ce1f33d1">

And because of same reason, tooltip is also appearing little early or dragged past the point..

Is something wrong in below, or can you assist is wrong here,. ?
```

  let xValue = chart.xAxis[0].toValue(  e.chartX, false)

        		const latestDate = new Date(Math.floor(xValue)).setSeconds(0, 0)
            console.log('the x-axis value is ', new Date(latestDate).toString())
```

#### Product version
[Highstock v10.3.2]

#### Affected browser(s)
All, test on Chrome

**Comment by bm64** [comment]
Hi @LearnGrowAndShare 

Most likely, it behaves this way because your position calculations don't take into consideration shape width, this is easier to notice with slightly thicker line, see that its edge is always positioned at the cursor: https://jsfiddle.net/BlackLabel/4jvzanmb/
It can be adjusted by translating the element by half of its width: https://jsfiddle.net/BlackLabel/w79y0q3z/

This ticket is more a question about custom implementation, and we use github strictly for feature requests / bug tracking so with any further question about this case, please visit our other support channels: https://www.highcharts.com/blog/support/

**Comment by LearnGrowAndShare** [comment]
Thanks for the response... sure will use support channel for custom implementation... :)
