### ISSUE TITLE
Legend item gets confusing when area range chart has different fill color

### ISSUE THREAD

**Issue by fabiomargarido** [highcharts/highcharts#1982]
Hi there.

When you set up an area range chart with different line and fill colors, the corresponding legend item does not accurately represent the series and makes it confusing to look at.

Here's a fiddle which shows the issue: http://jsfiddle.net/aXXd2/2/

Thanks in advance.

**Comment by patryknut** [comment]
Hello,

I think the issue is still present.
Here is a little bit modified official Highcharts demo of arearange, with enabled legend and dashStyle changed to 'Dash':

https://codepen.io/anon/pen/vzymLB

The plot line is dash, but there is solid dot in legend symbol:

![image](https://user-images.githubusercontent.com/35264502/44836742-0ceffa80-ac38-11e8-971b-4104c013bbe7.png)

**Comment by oysteinmoseng** [comment]
Reopening for discussion.

I am not sure what we would expect in the legend here. Comments @TorsteinHonsi @jon-a-nygaard?

**Comment by pawelfus** [comment]
I think it's just another example why we should let users decide legend symbol - by default it uses rectangle symbol with marker color. Simple change for `drawLegendSymbol` to `drawLineMarker` resolves the "issue".

Demo: https://codepen.io/anon/pen/jvVYrE

Snippet: 
```
Highcharts.seriesTypes.arearange.prototype.drawLegendSymbol = Highcharts.LegendSymbolMixin.drawLineMarker;
```
