### ISSUE TITLE
When hover over a serie using boost mode, the second last point is not accessible

### ISSUE THREAD

**Issue by SophieSou** [highcharts/highcharts#19842]
#### Expected behaviour
A serie with two last points closed to each other, when the mouse hovers over the second last, this point should be accessible. (It is the case when the boost mode is disable)
<img width="692" alt="Capture d’écran 2023-09-27 à 15 29 16" src="https://github.com/highcharts/highcharts/assets/101882843/007026d5-73f1-4838-9c5f-0bd3c1f09cc9">

#### Actual behaviour
When the boost mode is enabled, the second last point is accessible only by zooming.
<img width="705" alt="Capture d’écran 2023-09-27 à 16 15 51" src="https://github.com/highcharts/highcharts/assets/101882843/e8104a79-4943-4569-a80e-10e9983d7682">

#### Live demo with steps to reproduce

https://jsfiddle.net/SophieSou/zfthod1q/2/

#### Product version

Highcharts JS v11.0.1 (2023-05-08)
#### Affected browser(s)
Tested on Chrome and Firefox

**Comment by bm64** [comment]
Hi @SophieSou

The behavior you're observing is not a bug but a limitation due to the pixel density of the chart. Your chart has 6,377 data points but only 800 pixels in width. When you move the mouse, you're hovering over full pixels. With more data points than pixels, it becomes inevitable that some points will be omitted from hover interactions.
