### ISSUE TITLE
Panning does not respect axis min/max values

### ISSUE THREAD

**Issue by hubertkozik** [highcharts/highcharts#19872]
#### Expected behaviour
After zooming into a chart with specified `yAxis.min` and `yAxis.max` values, the user should freely pan the chart with respecting min/max values.

#### Actual behaviour
After zooming into a chart with specified `yAxis.min` and `yAxis.max` values, panning does not respect min/max values.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/vjhzw71a/
1) Zoom into the bottom part of the points.
2) Click the shift key and pan in y direction -> yAxis.min and yAxis.max are not respected.

#### Product version
Highcharts v11.1.0

**Comment by hubertkozik** [comment]
I have prepared a workaround for that issue. If you want to use it in your project simply copy-paste the IIFE function with a workaround.

**Demo:** https://jsfiddle.net/BlackLabel/of6keb20/

**Comment by jakubjanuchta** [comment]
Whilst working on this issue, I found a test which has failed (Ordinal axis panning, when data is equally spaced). I think that the purpose of this test doesn't matter in this case, however something else does. 

**Demo:** https://jsfiddle.net/BlackLabel/9do0pfn1/

I'm not sure if this logic should be implemented like that when setting `axis.min` and `axis.max`. In the demo, when we set min and max with the new logic, the panning is correctly limited to that range, however, we can also modify this range with the navigator outside the range specified by previously set min and max. Also when we set the range using the navigator to one that is completely outside the range of min and max and try to pan, the range jumps to between them. 

I also discovered, that the exact same behavior is currently implemented for `mouse wheel zooming`, it also doesn't allow to zoom further than the set min and max and this can also be changed by navigator. 

I wanted to ask for your thoughts on this @TorsteinHonsi. Should I implement the behavior similarly to what we already have in mouse wheel zooming to panning or do we want any other behavior?  We can also limit the user not to pan further the set min and max only if e.g. `min < dataMin` so that they can extend the range with min and max but they can't limit it. If there is any other possibility for this, should we than also change it for mouse wheel zooming?

**Comment by TorsteinHonsi** [comment]
@jakubjanuchta We also have similar logic in the touch-pan code:

https://github.com/highcharts/highcharts/blob/88e38c16a4119536628ba60ec6c4466a9e4da147/ts/Core/Pointer.ts#L1396-L1407

I think mouse-panning should work the same way, so yes, `axis.options.min` and `max` are missing when computing `paddedMin` and `paddedMax`.

**Comment by TorsteinHonsi** [comment]
PS: at this point we shouldn't make changes to the touch-panning code, it is [being refactored](https://github.com/highcharts/highcharts/pull/20077).

**Comment by jakubjanuchta** [comment]
> @jakubjanuchta We also have similar logic in the touch-pan code:
> 
> https://github.com/highcharts/highcharts/blob/88e38c16a4119536628ba60ec6c4466a9e4da147/ts/Core/Pointer.ts#L1396-L1407
> 
> I think mouse-panning should work the same way, so yes, `axis.options.min` and `max` are missing when computing `paddedMin` and `paddedMax`.

Thanks @TorsteinHonsi, I'll implement the logic similarly to what is already done in touch panning.
