### ISSUE TITLE
Chart does not draw all flags when there are many flags

### ISSUE THREAD

**Issue by godfreya** [highcharts/highcharts#19928]
#### Expected behaviour
The chart should draw all flags in the series given to it.

#### Actual behaviour
The chart will stop drawing flags after a certain point, even if there is space for them. In this instance it only draws the first 10 in the blue series. Apparently this is due to certain flags, as deleting a few of the first 10 allows the rest of the blue series to be drawn.

#### Live demo with steps to reproduce
https://jsfiddle.net/5to7up3L/

#### Product version
Highstock latest

#### Affected browser(s)
Google Chrome

The chart should look something akin to this screenshot. As seen in the JsFiddle however, only the first 10 blue flags are drawn due to a bug. No error message is shown.

![Screenshot 2023-10-13 045251](https://github.com/highcharts/highcharts/assets/14304377/810fc785-453b-4d19-b7ee-693704c3d637)

**Comment by karolkolodziej** [comment]
Hi @godfreya! 

Thank you for creating this issue! I'm going to close it because [a similar one has been reported.](https://github.com/highcharts/highcharts/issues/10073)
You can try to apply the workaround provided by Pawel.

However, I will leave a simplified demo of yours because it is a very useful real-use case of the flag series- [demo](https://jsfiddle.net/BlackLabel/nusbkxz6/).
