### ISSUE TITLE
Bullet - pointStart property not behaving correctly

### ISSUE THREAD

**Issue by camcarley** [highcharts/highcharts#19955]
#### Expected behaviour
When setting the min value of my y-Axis, in the example below to -50, and set the pointStart value to in the series to the same value, I would expect the bar to start at -50. This is an attempt to have 0 values be visible, outside of setting minPointLength

#### Actual behaviour
When setting the min value of my y-Axis, in the example below to -50, and set the pointStart value to -50, the series still starts at 0. =

#### Live demo with steps to reproduce
https://jsfiddle.net/ccarley/46owyqrL/7/

#### Product version
Highcharts v11.1

#### Affected browser(s)
All

**Comment by bm64** [comment]
Hello @camcarley 

Most likely `threshold` property is what you're looking for, it allows you to define where point should start relatively to Y axis:  https://jsfiddle.net/BlackLabel/jv6qd4r9/

`pointStart` allows you to define, when no x values are given, where first series point should start relatively to X axis. Also `pointStart` and `minPointLength` should be set on series level rather than in specific point object.
API reference: https://api.highcharts.com/highcharts/series.bullet.threshold
https://api.highcharts.com/highcharts/series.bullet.minPointLength
https://api.highcharts.com/highcharts/series.bullet.pointStart
