### ISSUE TITLE
Jumping of the time period when we zoom in and out or when we shift to the right

### ISSUE THREAD

**Issue by krupali-clavier** [highcharts/highcharts#19976]
#### Expected behaviour
When we pinch in or out it should be work well.

#### Actual behaviour
Jumping of the time period when we zoom in and out or when we shift to the right

#### Live demo with steps to reproduce
https://jsfiddle.net/KrupaliClavier/7vea0Lfg/13/

#### Affected browser(s)
Web view in reactnative

https://github.com/highcharts/highcharts/assets/140229103/a21f52cd-9e99-4df2-97ff-20ecaaae1627

[jumping_to_right.webm](https://github.com/highcharts/highcharts/assets/140229103/7a3229bb-acae-431f-b1c9-7a356a380dab)

**Comment by karolkolodziej** [comment]
Hi @krupali-clavier!

Thank you for reporting the issue. Here is [the simplified demo.](https://jsfiddle.net/BlackLabel/tcj5usgm/)
It looks like the zoom doesn't work correctly with other series than lines. It scrolls the chart instead.

_Internal note:_
To recreate this issue, position the pointer at the beginning or the end of the plot area.
This might be a fault of the `toValue` method- which needs further investigation.

**Comment by TorsteinHonsi** [comment]
_Internal note_

The issue is caused by the column series having a non 0 `pointRange`. This adds a padding to the x-axis, that must be considered when handling positioning. Long story short, replacing this

https://github.com/highcharts/highcharts/blob/88e38c16a4119536628ba60ec6c4466a9e4da147/ts/Extensions/MouseWheelZoom/MouseWheelZoom.ts#L180-L181

with this:

```ts
    const mouseAxisRatio = (mousePos - axis.minPixelPadding - axis.pos) /
            (axis.len - 2 * axis.minPixelPadding),
```

...seems to do the trick

**Comment by krupali-clavier** [comment]
@TorsteinHonsi We've tried this already, but unfortunately it's not working for us.

**Comment by TorsteinHonsi** [comment]
@krupali-clavier Thanks for your patience! There may be some misunderstanding here, as you describe "pinch", but the fix we provided is about mousewheel zooming. Though your video doesn't seem to be of pinching on a mobile device. So let's clarify:

1. What kind of zooming on the chart are you doing? Pinching on a touch device, pinching on a track pad, or mousewheel zoom?
2. Can you test https://jsfiddle.net/highcharts/fto80y75/1/ and see if that behaves like expected?

**Comment by krupali-clavier** [comment]
@TorsteinHonsi  It doesn't work for us in mobile. it's working fine with web. Please guide us.

**Comment by TorsteinHonsi** [comment]
@krupali-clavier Ok, try this:

1. On your mobile phone, open https://jsfiddle.net/highcharts/fto80y75/1/show .
2. Click "Run this fiddle".
3. With two-finger movements, try zooming in and out on the two charts. Do you see anything not working as expected?

**Comment by Nigellooi** [comment]
@TorsteinHonsi,

I have tried the chart in jsfiddle, it is working fine on the mobile phone.

**Comment by TorsteinHonsi** [comment]
> I have tried the chart in jsfiddle, it is working fine on the mobile phone.

Great @Nigellooi , thanks for testing! Then this issue will be fixed by #20077 .

**Comment by Nigellooi** [comment]
Hi @TorsteinHonsi, when my developers @krupali-clavier applied the code to our application we have the following issue, when i zoom in to the latest data, the chart reacts weirdly, afterwhich the zoom does not seem to work as intended.


https://github.com/highcharts/highcharts/assets/108664489/1e079f02-ba01-4e75-b863-7113d9ff1bd1

**Comment by TorsteinHonsi** [comment]
@Nigellooi I'm afraid I'm going to need some help debugging here. Your chart is quite complex, and it is not clear to me what fails. Can your developers replicate the issue on jsFiddle? Start out with https://jsfiddle.net/highcharts/fto80y75/2/, then apply some of your own data or settings so that you are able to replicate it. Then save and send it back to us, including instructions on how to reproduce. You can also share it in other ways if you'd like, as long as we are able to reproduce it so we can start debugging.

**Comment by krupali-clavier** [comment]
@TorsteinHonsi  I've added our chart with our data.. Please check and help us to improve 
https://jsfiddle.net/KrupaliClavier/1r3ohe7a/3/

**Comment by TorsteinHonsi** [comment]
@krupali-clavier @Nigellooi Thanks so far!

Now I can see a chart, but it doesn't have data, so I am not able to reproduce. The point is that I have to be able to reproduce the same error as you see. Only then can I actually debug and fix the issue instead of guess what might be wrong.

No I get an error that socket is undefined, probably because of this path that points to a local file that doesn't exist:
`    <script src="/socket.io/socket.io.js"></script>`

If you are not able to add dynamic data to the jsFiddle, I recommend that you add some static data. As long as it reproduces your issue, it's fine.

**Comment by Nigellooi** [comment]
Hi @TorsteinHonsi,

We have started to push live data to the socket. The chart should be generating now.

**Comment by TorsteinHonsi** [comment]
@Nigellooi @krupali-clavier Thanks for the reproduction! I was now able to get further.

Turns out that `rangeSelector.selected` causes the glitch. If I remove that option, panning to the right works as expected. I also found that Highcharts throws an error 15 for unsorted data, so that is something you should address, preferable server-side. See https://jsfiddle.net/highcharts/sqygehox/ for fixed demo.

**Comment by TorsteinHonsi** [comment]
Now that the problem is isolated, I forked off a new and focused issue at https://github.com/highcharts/highcharts/issues/20327

**Comment by TorsteinHonsi** [comment]
@krupali-clavier We will prioritize the issue and come up with a drop-in fix if possible. 

> We can not remove rangeSelector.selected option as we've a requirement to show the latest 25 candle with the time interval of 5 seconds, So we need to keep it.

But when you set `rangeSelector.selected` to 0 it means that you pre-select the one _month_ button. Is that what you want?  You have some code that is commented out:

```js
                    buttons: [{
                         type: 'minute',
                         count: 125,
                         text: '125m',
                         visibility: 'hidden'
                    }]
```

If I uncomment that, your zooming and panning seems to work like expected, right? I can no longer see the issue here: https://jsfiddle.net/highcharts/sqygehox/2/

**Comment by krupali-clavier** [comment]
@TorsteinHonsi  Thank you for guidance, it has been almost improved.. Only thing left is that first zoom out it will jump back

Please guide us with this

Uploading SVID_20231220_020201_1.mp4…

**Comment by TorsteinHonsi** [comment]
@krupali-clavier Great! Your video is missing though...

**Comment by krupali-clavier** [comment]
https://github.com/highcharts/highcharts/assets/140229103/7e89135b-fc37-44f0-9e6d-18526f5524d3

@TorsteinHonsi  Sorry for missing reference...Please check

**Comment by TorsteinHonsi** [comment]
@krupali-clavier Looks like that issue is fixed by the ongoing refactoring in #20077 : https://jsfiddle.net/highcharts/sqygehox/4/

It is not released yet, and not finished, but will most likely be part of the next Highcharts release.

**Comment by krupali-clavier** [comment]
@TorsteinHonsi  Thank you for responding, When can we expect to get the solution of the issues. Please guide us.

**Comment by TorsteinHonsi** [comment]
@krupali-clavier The refactoring of the zooming feature is still in progress, but we expect a release some time in January.
