### ISSUE TITLE
Hichcharts treegraph export to png, crops parent nodes after interacting with it

### ISSUE THREAD

**Issue by karakostasi** [highcharts/highcharts#20006]
#### Expected behaviour
After a user interacts with the treegraph, f.e say minimizing some nodes, and then chose to export it (in our case to png), the expected result image, should match the one he created by interacting with the treegraph.

#### Actual behaviour
After a user interacts with the treegraph, f.e say minimizing some nodes, and then chose to export it (in our case to png), the exported image is cropped missing the first parent node, and also the minimized ones are expanded, so the user's actions get ignored

#### Live demo with steps to reproduce
the issue was reproduced straight at your site [https://www.highcharts.com/docs/chart-and-series-types/treegraph-chart]
and it is really easy to reproduce.

Steps:
1. open the link above
2. minimize some random nodes
3. try exporting to png. you ll see that the saved image is cropped.

#### Product version

"highcharts": "^11.1.0",
"@highcharts/map-collection": "^2.0.1",
"highcharts-react-official": "^3.2.1",

#### Affected browser(s)

all browsers

**Comment by bm64** [comment]
Hello @karakostasi

Thanks for reporting the issue. It doesn't work because it simply has never been implemented, so I'm labelling the issue as a feature request.

**Comment by karakostasi** [comment]
Thanks a lot for the response :) looking forward to it, and keep up the great work !

**Comment by cr1stimuresan** [comment]
Hello
Is there any timeline for this?
Thanks

**Comment by TorsteinHonsi** [comment]
_Internal note_

What may be missing, is to update the point [collapsed](https://api.highcharts.com/highcharts/series.treegraph.data.collapsed) option after expanding or collapsing a node. Note the difference between the `point.collapse` _property_, which is already updated, and the option. The export module uses options. At least this is where I would start debugging.

PS: And we need to set the `chart.height` in the chart configuration itself instead of in CSS. Otherwise the exported image is too crammed.
