### ISSUE TITLE
Navigator with boost on and dataGrouping disabled causes navigator series to not be displayed 

### ISSUE THREAD

**Issue by lukeheckman** [highcharts/highcharts#20143]
#### Expected behaviour
Turning boost on and dataGrouping off in the navigator should display the navigator series as if they were a normal chart series with boost on and dataGrouping off.

#### Actual behaviour
Turning boost on and dataGrouping off in the navigator causes the navigator to appear empty. The navigator series do not render.

#### Live demo with steps to reproduce
https://jsfiddle.net/lheckman/rp9jaz63/5/

#### Product version
Highstock v11.1.0 

#### Affected browser(s)
Chrome

#### Possibly related issue:
#18755

**Comment by pawelfus** [comment]
Hi @lukeheckman 

Thank you for reporting the issue! We had this bug in v11.1.0, but it should be fixed in v11.2.0. Could you try updating to v11.2.0? 

Note: In your demo, points are barely visible in the navigator because of the opacity. You can increase it to see them better: https://jsfiddle.net/BlackLabel/a2n5g4Le/ (with a large number of points it shouldn't be necessary). 

Closing as duplicate of #17820
