### ISSUE TITLE
Chart zooming issues in Firefox

### ISSUE THREAD

**Issue by nishikantparmariam** [highcharts/highcharts#20141]
#### Expected behaviour
In both Chrome and Firefox:
- Zooming only inside the chart should work as expected.
- Zooming till the very end of chart (slow or fast) should work without dropping any point.

#### Actual behaviour
This is in continuation of https://github.com/highcharts/highcharts/issues/15569 and https://github.com/highcharts/highcharts/issues/18863. We had added all fixes (the current fixes are present in reproducer below) and things worked perfectly for Chrome but in FireFox even normal zoom is unusable, so we reverted all of the fixes. 

Demo in Firefox:
![chart-zoom](https://github.com/highcharts/highcharts/assets/7736252/71026e5d-19a2-4f43-9a48-4e42e055e82c)

Would prefer if there are plugin based solutions as we are bit far from upgrading to v11. Thanks!

#### Live demo with steps to reproduce
**Open in FireFox** - https://jsfiddle.net/k5pjxn7q/2/

#### Product version
10.3.3

#### Affected browser(s)
Firefox 119.0

**Comment by bm64** [comment]
Hello @nishikantparmariam 

I have tried your demo on firefox, and indeed the zoom there seems to be broken, but it seems that the issue has already been fixed on master branch and should be released with next version. Could you confirm if it works for you too? https://jsfiddle.net/BlackLabel/3w1Lr02c/

**Comment by nishikantparmariam** [comment]
> Could you confirm if it works for you too?

Yes, it works for me. We are currently at 10.3.3, till we upgrade to 11.x, is it possible to get the issue fixed via some workaround plugin?

**Comment by bm64** [comment]
@nishikantparmariam the fix most likely was introduced with this commit: https://github.com/highcharts/highcharts/commit/bb45ed8dfc953acf7450358a96d2a1a64780a3be

As a workaround you can try to overwrite `isRequired` method: https://jsfiddle.net/BlackLabel/ckz1e3tg/
Let me know if it works for you.

**Comment by nishikantparmariam** [comment]
Hi @bm64 @karolkolodziej, while normal zooming in Firefox is working with https://github.com/highcharts/highcharts/issues/20141#issuecomment-1820857293 fix but it is still dropping the last point upon fast zooming in Firefox.

Please see https://github.com/highcharts/highcharts/issues/15569#issuecomment-1519520292 on why not dropping last set of points is important for financial charts.

In Chrome - Slow and fast zoom does not drop any point and works properly. 
In Firefox - Slow zoom works fine, fast zoom drops last points.

See below GIF (in Firefox) where June 30, 2019 is not present in zoomed chart whereas is should be. Link: https://jsfiddle.net/BlackLabel/ckz1e3tg/.

![last-point-dropping-in-firefox](https://github.com/highcharts/highcharts/assets/7736252/827da845-bfac-4d0f-89be-557bdfccfd83)

Can you please check as this is high priority for our users. Let me know if more details are required here. Thanks!

**Comment by karolkolodziej** [comment]
Hi @nishikantparmariam!

I'm able to recreate the issue in Firefox with the v10.3.3.
This is strange because I could display and use the chart properly with v11.2.0. I'm aware that you are not able to use this version yet but it made me think.

I was able to bisect to the: https://github.com/highcharts/highcharts/commit/298f295c499fd35aa0e82e128f012aa3c5901229
But, as far as I see, the changes are already included in your demo with all the workarounds. So there must be something else going on.

**Comment by TorsteinHonsi** [comment]
@nishikantparmariam I think I have a workaround for you. For some reason, the `Pointer.onContainerMouseLeave` extended function does not run in Firefox, only in Chrome. The gist of our `wrap` was to call `onContainerMouseMove` from `mouseleave` in order to capture the very last mouse position inside the container. So I applied it to the DOM directly:

```js
  addEvent(Chart, 'load', function () {
    this.container.addEventListener(
        'mouseleave',
        e => this.pointer.onContainerMouseMove(e)
    );
  });
```

This seems to work: https://jsfiddle.net/highcharts/xkj0hac5/

**Comment by nishikantparmariam** [comment]
Thanks @TorsteinHonsi this works well for Firefox and Chrome both.
