### ISSUE TITLE
Declaration file (like highcharts.d.ts) missing for custom packages

### ISSUE THREAD

**Issue by vier31** [highcharts/highcharts#20164]
#### Expected behaviour
After building a custom package as described here: [Documentation](https://www.highcharts.com/docs/getting-started/how-to-create-custom-highcharts-packages) I get type declarations just like using the regular package.

#### Actual behaviour
Instead, I get an error 
```
TS7016: Could not find a declaration file for module  @company/custom-highcharts .
/Users/.../packages/highcharts/code/es-modules/masters/custom.src.js
implicitly has an  any  type.
```

#### Product version

Highcharts 11.2.0

**Comment by karolkolodziej** [comment]
Hi @vier31!

Thank you for reporting the issue! 

The command described in the documentation `npx gulp scripts` only generates JS files. 
In order to also generate `.d.ts` files use `npx gulp --dts` command instead.

Altho it seems that **the declarations are not generated correctly for the `custom` file.**

_Internal note:_
Fix should be probably around `jsdoc -dts / -options / -namespace` file.

**Comment by vier31** [comment]
Happy new year.

Any updates on this?

**Comment by karolkolodziej** [comment]
Hi @vier31 🎇  

This issue is literally at the top of the prioritized tasks- you should expect some updates shortly!
