### ISSUE TITLE
exporting - chartOptions xaxis

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#2022]
In the example http://jsfiddle.net/FcnwT/8/ chartOptions with xAxis details are not included, (chart object works well).

**Comment by highslide-software** [comment]
Closed by 807c2a5fb89c89e1c6a2f3b8c543c00d779490c8

**Comment by KacperMadej** [comment]
If axes options are given in array format then old options are lost.
Edited demos:
- http://jsfiddle.net/FcnwT/13/
- http://jsfiddle.net/54wq80j3/10/

*Internal note/question:* Shouldn't the `merge` function be handling arrays? http://jsfiddle.net/7fnsa0ts/

**Comment by TorsteinHonsi** [comment]
> Internal note/question: Shouldn't the merge function be handling arrays? http://jsfiddle.net/7fnsa0ts/

We've chosen not to merge arrays because it is performance heavy and mostly in our use cases we want to handle them separately.

**Comment by 3Ue** [comment]
It seems the original solution from 807c2a5 was removed in the meatime so it doesn´t work anymore even if you define the xAxis options as an object not as an array. In the current version Highstock 7.1.1 the exporting chartOptions simply get merged into the new options.

```
getSVG: function (chartOptions) {
    ...
  // Copy the options and add extra options
  options = merge(chart.options, chartOptions);
```
That means that the xAxis options get an array like object that may look like this.

```
{ 
  xAxis: {
    0: {<old xAxis options>},
    labels: {<new xAxis options>}
  }
}
```

Afterwards chartCopy.update(collOptions); is called which I guess should merge the new xAxis options accordingly into the old xAxis array, but it doesn´t because during chart.update this is called:

`options = H.cleanRecursively(options, chart.options);`

and that removes the xAxis options since it thinks they don´t have changed.

(Re-)adding the following lines before generating the chartCopy in the getSVG method seems to fix the problem again.

```
                // Axis options must be merged in one by one, since it may be an array or an object (#2022)
                if (chartOptions) {
                  each(['xAxis', 'yAxis'], function (axisType, i) {
                    each(splat(chartOptions[axisType]), function (axisOptions) {
                      options[axisType][i] = merge(options[axisType][i], axisOptions);
                    });
                  });
                }
```

**Comment by sebastianbochan** [comment]
+1

**Comment by dabela** [comment]
+1

**Comment by KacperMadej** [comment]
Looks like setting options in an array works fine, so this could be used as a workaround - http://jsfiddle.net/BlackLabel/9tn4yumx/

If you have a demo of the problematic chart where the array format doesn't work, please share.

**Comment by dabela** [comment]
@KacperMadej There's still a problem with your example since on export the categories are lost - the title does get added however the category names have changed to numbers instead of the original ones on the chart. Ditto the alternate color band, these are removed on export.

**Comment by pawelfus** [comment]
In basic cases, we can workaround this easily: http://jsfiddle.net/BlackLabel/ad5f6rmb/

But when dynamic changes to an axis is possible, this won't work.

Instead for now we can update related x/yAxis when chart for exporting is generated: http://jsfiddle.net/BlackLabel/wnLgc5a7/
