### ISSUE TITLE
Fonts in exported images render as "Lucida Grande" when font-family starts with a number

### ISSUE THREAD

**Issue by KhalinaYuliia** [highcharts/highcharts#20273]
#### Expected behaviour
Charts render "72-Regular" font for export as an SVG/JPEG/PNG when fontFamily in export config is "72-Regular"

#### Actual behaviour
Charts render "Lucida Grande", "Lucida Sans Unicode" font for export as an SVG/JPEG/PNG when fontFamily in export config starts with a number such as "72-Regular"

#### Product version
Highcharts 10.3.11

**Comment by karolkolodziej** [comment]
HI @KhalinaYuliia!

Could you please explain how you apply the `font-family`? 
I was trying to recreate it but it always exports with the exact font.

**Comment by KhalinaYuliia** [comment]
Hi @karolkolodziej!
I add this json to exporting config
{
  "chartOptions": {
    "title": {
      "style": {
        "fontFamily": "72-Regular,Arial,Helvetica,sans-serif",
        "fontWeight": "bold",
        "fontStyle": "normal",
        "color": "#32363a",
        "fontSize": 21
      }
    }
  }
}
If I use any other font that doesn't start with a number, then it works

**Comment by karolkolodziej** [comment]
You are right! Thank you for the explanation.

[Simplified demo](https://jsfiddle.net/BlackLabel/a7sre6zn/)

**Comment by oysteinmoseng** [comment]
Internal note: May be related to which fonts are installed on the export server.

**Comment by magdalena-gut** [comment]
Internal note: The issue seems to be independent of the export server.

Working:
https://jsfiddle.net/BlackLabel/Lw9ysf67/
Not working:
https://jsfiddle.net/BlackLabel/wuvz6rag/

[Clearing the cache might be necessary to check.]

**Comment by magdalena-gut** [comment]
@KhalinaYuliia  This issue is related to the [CSS family-name syntax](https://www.w3.org/TR/css-fonts-4/#family-name-value):
_To avoid mistakes in escaping, it is recommended to quote font family names that contain white space, digits, or punctuation characters other than hyphens:_ `<body style="font-family: '21st Century', fantasy">`

Based on that, as the temporary workaround you can wrap the fontFamily value in extra quotes:

```
 chart: {
   style: {
      fontFamily: "'1customname'"
  }
}
```
Demo: https://jsfiddle.net/BlackLabel/ujeag452/

**Comment by magdalena-gut** [comment]
After the analysis, we reached the conclusion that setting fonts with special characters in double quotes directly within chart options is the optimal solution. This is because, according to the CSS syntax, some generic fonts require not to be wrapped at all, while others, such as those with special characters, require it. This may change over time and introduce some inconsistency in the core code. Therefore, the provided workaround before is the recommended solution.

Within the scope of this ticket, we updated the documentation with this information.
