### ISSUE TITLE
Toggling visibility of the first linked series behaves differently than toggling visibility of other linked series

### ISSUE THREAD

**Issue by MelissaVanDijk** [highcharts/highcharts#20296]
#### Expected behaviour
Situation: We have a bar chart with one series (without any data) and 4 linked series. 
When you turn of the visibility of any of the 4 linked series, the width of the other bars should increase in order to take up the space of the invisible series.

#### Actual behaviour
When you turn of the the visibility of the **first** linked series, the width of the other bars does not change, in contrast to turning off the visibility of any other linked series.

#### Live demo with steps to reproduce
https://jsfiddle.net/6j7sw0ep/3/

Repro:
- Turn off the visibility of either series 2, series3 or series 3 by clicking on any of the checkboxes
- The width of the bars is adjusted. This is good.
- Make sure all bars are visible again
- Turn off the visibility of series 1 (red)
- The width of the bars is not adjusted. This is not good.

#### Product version
Highcharts JS v11.2.0 (2023-10-30)

#### Affected browser(s)
at least Chrome & Firefox

**Comment by bm64** [comment]
Hello @MelissaVanDijk 

That behaviour is actually caused by stacking, and the fact that the first series is stacked with zero index series without data. Here is the simplified demo: https://jsfiddle.net/BlackLabel/ym93ufcv/  If you want other series to fill available space, you need to hide the zero index, empty data series as well: https://jsfiddle.net/BlackLabel/6d85vawf/

That behaviour is intended and can be clearly seen in this demo, where series without data still reserve the space:  https://jsfiddle.net/BlackLabel/t8x7ng40/

**Comment by MelissaVanDijk** [comment]
Thank you for your answer. 

Unfortunately we cannot hide the first (empty) series, because then it would hide all series, since they are linked to it. 
We use this empty series and link all other series to it, in order to have only one legend item for multiple series. 

Do you know if there is another way to link multiple series to one legend item, without linking the series?
