### ISSUE TITLE
Funnel chart not rendered properly when setting borderRadius

### ISSUE THREAD

**Issue by MRezaKarimi** [highcharts/highcharts#20319]
#### Expected behaviour
Germany slice should render properly

#### Actual behaviour
When I set borderRadius, "Germany" slice disappears!. However if I change Germany's value to a number other than 1, problem solves!

#### Live demo with steps to reproduce
[https://codesandbox.io/s/highcharts-bug-nf3wxs?file=/index.html](https://codesandbox.io/s/highcharts-bug-nf3wxs?file=/index.html)

#### Product version
Highcharts JS v11.2.0

#### Affected browser(s)
Chrome: Version 116.0.5845.110 (Official Build)

**Comment by bm64** [comment]
Hello @MRezaKarimi and thanks for reporting the issue.

Did you mean funnel or actually a pie chart? Because in the provided demo I can see a funnel chart which is broken anyway and the Germany point is not visible. It looks like the issue is located here (dividing by 0): https://github.com/highcharts/highcharts/blob/ec4c70ab75ea80cef0de817d6dc4976470551a81/ts/Series/Funnel/FunnelSeries.ts#L481
FYI @Vazonik

**Comment by Vazonik** [comment]
> It looks like the issue is located here (dividing by 0):

The issue does not result strictly from division by zero, but from division by 0 when `h` is 0 too, because `0/0` is `NaN` when `Infinity` is expected. The problem can be easily solved by something like this:
```ts
alpha = h !== 0 ? Math.atan(h / xSide) : Math.atan(Infinity);
```

**Comment by MRezaKarimi** [comment]
> Hello @MRezaKarimi and thanks for reporting the issue.
> 
> Did you mean funnel or actually a pie chart? Because in the provided demo I can see a funnel chart ...
> 
> @Vazonik

Yes you right. I said pie chart by mistake.
