### ISSUE TITLE
Zooming issues when rangeSelector.selected set to disabled button

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#20327]
#### Expected behaviour
Panning should preserve the current range

#### Actual behaviour
When the `rangeSelector.selected` option is set to a button that is disabled due to the range exceeding the data range, panning the chart will extend the range to the button instead of limiting it to the data range. 

#### Live demo with steps to reproduce
https://jsfiddle.net/highcharts/sm1o95uf/
* Drag the navigator => x-axis range is extended way outside data range

Or
* Zoom in by mousewheel
* Drag the navigator to the right => poof

Interestingly, if we use the navigator handles to zoom instead of the mouse wheel, then it works as intended

#### Product version
11.2

This issue is forked from https://github.com/highcharts/highcharts/issues/19976

**Comment by TorsteinHonsi** [comment]
Last working version is v11.0.1: https://jsfiddle.net/highcharts/sm1o95uf/3/

**Comment by krupali-clavier** [comment]
@TorsteinHonsi  We can not remove rangeSelector.selected option as we've a requirement to show the latest 25 candle with the time interval of 5 seconds, So we need to keep it.
Please guide us with this information

**Comment by TorsteinHonsi** [comment]
Bisected to https://github.com/highcharts/highcharts/commit/8ec07aca85f67a48c0023da2214f927b961dc4b2

**Comment by kamil-musialowski** [comment]
On `RangeSelector.init()`, because we set `rangeSelector.selected: 0` in the config, the `RangeSelector.clickButton()` gets fired, which then sets the `chart.fixedRange` to the value that is selected in config (1 month in that case). Then this incorrect `fixedRange` value is being used in the `NavigatorAxisComposition` in `toFixedRange` method, which messes everything up, since it's trying to add and subtract the fixedRange from actual extremes.

Therefore I would focus the fix on not setting the `fixedRange` to the incorrect value (larger than actual extremes).
