### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'Core/Chart/Chart.js') during Next.js static build

### ISSUE THREAD

**Issue by thisishadis** [highcharts/highcharts#20347]
I get following error during static next build (`output: 'export'):

TypeError: Cannot read properties of undefined (reading 'Core/Chart/Chart.js')

CodeSandbox:
https://codesandbox.io/p/github/thisishadis/spider-chart/main

#### Product version
    "highcharts": "^11.2.0",
    "highcharts-react-official": "^3.2.1",
    "next": "14.0.4",
    "react": "^18",
    "react-dom": "^18"

**Comment by bm64** [comment]
Hello @thisishadis 

The issue is most likely caused by next.js ssr process. To solve it you you can try to initialize Highcharts on the client side after the page loads, ensuring all modules are imported. Please try this demo and let me know if it works for you: https://codesandbox.io/p/github/thisishadis/spider-chart/csb-6pt8x9/draft/autumn-brook?file=%2Fsrc%2Fapp%2Fpage.tsx%3A8%2C46

**Comment by qsya** [comment]
you can use es-modules, like this:
`'use client'
// import Highcharts from 'highcharts'
// import Highcharts3D from 'highcharts/highcharts-3d'
// Highcharts3D(Highcharts)

import Highcharts from 'highcharts/es-modules/masters/highcharts.src'
import 'highcharts/es-modules/masters/highcharts-3d.src'`

**Comment by heiningair** [comment]
I am experiencing the same.. 

Did somebody find a workaround for this?

**Comment by heiningair** [comment]
just found the solution here:

https://github.com/highcharts/highcharts-react#highcharts-with-nextjs
