### ISSUE TITLE
Pie chart dataLabels overlap when distance is set to "-50%"

### ISSUE THREAD

**Issue by kamil-musialowski** [highcharts/highcharts#20355]
#### Expected behaviour
Pie chart should not change the amount of rendered dataLabels upon hover.

#### Actual behaviour
Once you hover over a chart and then go back, all dataLabels are rendered which causes them to overlap.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/cnvrm9f5/
1. Visually check the amount of dataLabels
2. Mouse over the chart
3. Mouse out
4. All labels are now rendered

#### Product version
HC 11.2.0

_Internal note: Worked in 11.1, however all dataLabels were rendered initially so I'm not sure if that was a correct behaviour_

**Comment by AmoghAnantha** [comment]
Hi Kamil,
Let me know if this satisfy your condition,
https://jsfiddle.net/fohp3gsc/

**Comment by TorsteinHonsi** [comment]
_Internal note_

Dealing with overlapping pie chart labels was implemented in https://github.com/highcharts/highcharts/commit/8adcce7237ec48125935812000d746c683e7e03a. 

The problem is that we have only the opacity to identify which labels are shown and which are hidden, and since the inactive state also sets the opacity, it doesn't distinguish between the hidden and the visible labels. Maybe we need some additional label property or class name.
