### ISSUE TITLE
Point events update does not work.

### ISSUE THREAD

**Issue by vazonik** [highcharts/highcharts#20435]
#### Expected behaviour
Even if the event has been triggered before, using `series.update` with the appropriate options (as in the demo) should update the event.

#### Actual behaviour
Once a function passed to the `series.point.events.mouseOver` option (or other, e.g. `click`, etc.) is called, it cannot be changed or removed by updating it.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/5ywL7zqv/
1. Open console
2. Click the button to add/remove an event; hover over points to see if the event is still working.

#### Product version
Highcharts v11.3.0

**Comment by Basts** [comment]
It seems that the bug still occurs - after updating the event it triggers twice - previous and current callback.

Demo from reported issue: https://jsfiddle.net/BlackLabel/Lpxrdmsj/ 
Demo from user: https://jsfiddle.net/BlackLabel/n8fzLk3w/

**Comment by hubertkozik** [comment]
You're right @Basts! New overlook related to updating of the event.

**Comment by shayded-exe** [comment]
Experiencing a regression where the point click handler gets called an additional time for every update.

Is there a workaround for this?

**Comment by hubertkozik** [comment]
@shayded-exe can you share a demo with the reproduced issue?

**Comment by jumperchen** [comment]
Hi @TorsteinHonsi,

I recently attempted to upgrade our product from v11.2.0 to v11.4.6 and encountered a side-effect related to this issue you fixed.

For example, in this JSFiddle - https://jsfiddle.net/hj5fcxkz/
you can see on line 26:

`    "mouseOver": () => console.log('hi~~') // this will break the drilldown click event.`

This line breaks the drilldown click event, which seems to be caused by the fix. Do you have any workaround to avoid this issue?

Note: if I downgrade the script version to v11.3.0, and it works as before.

**Comment by hubertkozik** [comment]
Hi @jumperchen! Thank you for reporting the issue, let's treat it as a regression. I've created a new GitHub ticket for that:
https://github.com/highcharts/highcharts/issues/21534

Let's continue the discussion there.
