### ISSUE TITLE
`rangeSelector.selected` not working when used with `Highcharts.chart` constructor

### ISSUE THREAD

**Issue by jedrzejruta** [highcharts/highcharts#20529]
#### Expected behaviour
Selected range is chosen on initial load of the chart.

#### Actual behaviour
Selected range isn't chosen and the extremes don't change.

#### Live demo with steps to reproduce

The issue happens only when using the `Highcharts.chart` constructor, with Highcharts Stock it works fine.
[https://jsfiddle.net/BlackLabel/L4q10dje/](https://jsfiddle.net/BlackLabel/L4q10dje/)

#### Product version
Regression introduced in Highcharts v11.3.0

_Internal note:_ Bisected to [999f29cc](https://github.com/highcharts/highcharts/commit/999f29cce6386948e471e0756754cd0e48e01f88)

**Comment by hubertkozik** [comment]
Hi @ConstantinCreations! Yes, this issue is still present in the current version of Highcharts v11.3.0. My colleague created a fix for this bug and now, as you can see in the linked Pull Request it is waiting for final code review and merge to the master branch. The issue will be resolved in the next release of Highcharts.

If you need to fix the issue in Highcharts v11.3.0, I have prepared a workaround for you. You can find it in the demo below. If you want to use it in your project simply copy-paste the IIFE function with a plugin.
**Live demo with a workaround:** https://jsfiddle.net/BlackLabel/gmanrwt8/
