### ISSUE TITLE
Issues with Weather Demo

### ISSUE THREAD

**Issue by jomar-honsi** [highcharts/highcharts#20535]
#### Expected behaviour

- Map points and data to show up after the application has loaded.
- Dashboards and Cypress tests to pass

#### Actual behaviour

- Application throws error: `“Connector not found (New York)“`
- Dashboards and Cypress tests fail

**Comment by TorsteinHonsi** [comment]
Thanks, the demo generally looks and works great!

Some feedback to the demo in general:

* [The main series name](https://github.com/highcharts/highcharts/blob/9577bec847d1fca5982d401e1ec84a91f5bcf74c/samples/dashboards/demo/live-weather/demo.js#L801). This date format will likely be [confusing](https://www.reddit.com/media?url=https%3A%2F%2Fi.redd.it%2Fd1odti6snwk01.jpg) to our friends in the US. For human readable strings, I prefer "January 29, 2024", or alternatively "2024-01-29" which is also unambiguous, but harder to digest for a human. 
* [tooltip.pointFormatter](https://github.com/highcharts/highcharts/blob/9577bec847d1fca5982d401e1ec84a91f5bcf74c/samples/dashboards/demo/live-weather/demo.js#L350-L354): use `tooltip.pointFormat` instead. Best practice is to keep chart configurations free of function callbacks as much as we can. The rationale is that this allows the config to be serialized as JSON, which in turn allows implementers to store the config, modify it through a GUI, and also guarantees an increased level of security (because functions by nature open up for XSS).
* [tooltip.formatter with series logic](https://github.com/highcharts/highcharts/blob/9577bec847d1fca5982d401e1ec84a91f5bcf74c/samples/dashboards/demo/live-weather/demo.js#L601-L616). Not a biggie, but instead of a common formatter for all series types, I would consider defining different configurations for `plotOptions.series.tooltip` and `plotOptions.windbarb.tooltip`. The latter will take precedence for the windbarb series. Then we could also possibly replace this formatter with a `format` string, unless the `activeParam` causes trouble.
* [xAxis.labels.formatter](https://github.com/highcharts/highcharts/blob/9577bec847d1fca5982d401e1ec84a91f5bcf74c/samples/dashboards/demo/live-weather/demo.js#L621-L623). This one is simple, just use `xAxis.labels.format = '{value:'%H:%M'}'`.
