### ISSUE TITLE
Zone Feature is not working on version 11.3(regression)

### ISSUE THREAD

**Issue by fariaNawrine** [highcharts/highcharts#20569]
#### Expected behavior
Zone Feature should work on version 11.3

#### Actual behavior
For line chart if we use zone feature, its displaying only one line instead of all series lines as expected.

#### Version 11.3(not working)
https://codepen.io/Faria-Nawrine-the-solid/pen/dyrmWQP

#### Version 11.2(working)
https://codepen.io/Faria-Nawrine-the-solid/pen/abMYWOj?editors=1010

#### Affected browser(s)
all

**Comment by hubertkozik** [comment]
Hi @fariaNawrine!
You have found another usage of the wrong code but with the same root cause as in https://github.com/highcharts/highcharts/issues/20440. After refactoring, the `zones` object copy on series was shallow, not deep, what creates an issue.

I've prepared a workaround for your issue, if you want to use it in your project, simply copy-paste the IIFE function.
**Live demo with a workaround:** https://codepen.io/hubertkozik/pen/gOEeJdM
