### ISSUE TITLE
styledMode false still uses styles on pie, bar and column

### ISSUE THREAD

**Issue by stevemb-fl** [highcharts/highcharts#20580]
#### Expected behaviour
styledMode: true to use styles
styledMode: false should not use styles

#### Actual behaviour
settings styledMode: false still uses styles on pie, bar and column charts.

#### Live demo with steps to reproduce

https://jsfiddle.net/91023nvw/

Change styledMode : true,
Change back to false
Change in css #container to #container1 so the style isn't referencing the container is the expected behaviour of styledMode: false

#### Product version

Latest release and Master

#### Affected browser(s)
all

**Comment by bm64** [comment]
Hello,

Thank you for reaching out. There seems to be a misunderstanding regarding the `styledMode` functionality. When `styledMode` is set to `false`, Highcharts does not prevent CSS styles from being applied to the chart. It simply means that the chart will not rely exclusively on CSS for styling. In this mode, Highcharts applies inline styles and presentational attributes directly to the SVG elements of the chart.

**Comment by stevemb-fl** [comment]
Please take a look at this fiddle.
https://jsfiddle.net/Lb8qwegn/
Toggle styledMode to false, you can see the colours switch.  
When styledMode: is true Norway is red.  When false it's yellow.

**Comment by bm64** [comment]
Hello @stevemb-fl 

The red colour comes from `highcharts-color-0` class, which is removed from series styles, when color is defined in chart configuration (like in provided demo), and the `styledMode` is disabled. On the other hand, the Norway point is red when `styledMode` is enabled because the,  `highcharts-color-0` is applied to the series group:
Please see group attributes with `styledMode` enabled:
![image](https://github.com/highcharts/highcharts/assets/55414726/36744fb2-e180-44b5-a40a-0847f3e76fe3)

And with `styledMode` disabled and defined colour in the chart configuration:
![image](https://github.com/highcharts/highcharts/assets/55414726/14db2b1a-d9ad-4d36-ae2f-e03ea48f048c)
