### ISSUE TITLE
Edge issue: "SVG elements can not be created with createElement; use createElementNS"

### ISSUE THREAD

**Issue by suarezana9** [highcharts/highcharts#20596]
#### Expected behaviour
There shouldn't be an error message.

#### Actual behaviour
In MS Edge, I'm getting an error or category "Other": SVG elements can not be created with createElement; use createElementNS"

#### Live demo with steps to reproduce
 template: https://www.highcharts.com/demo/highcharts/gauge-solid?redirect-to-codepen

#### Affected browser(s)
![image](https://github.com/highcharts/highcharts/assets/32943258/bb6dae47-148a-41fb-9eab-36575e9673cf)

**Comment by KacperMadej** [comment]
Hi @suarezana9 

Thank you for reporting the problem.
The issue reported in Edge developer tools is not checked correctly and is pointing to any function whose name matches the pattern and in this case the `o` in `o.createElement("stop")` points to the equivalent of `renderer.createElement('stop')` in the unmodified code. That function later runs the native code responsible for creating the element but is used as:
```js
this.element = nodeName === 'span' ?
                    createElement(nodeName) :
                    doc.createElementNS(this.SVG_NS, nodeName);
```
 I have checked all reported issues in Edge's dev tools and none points to `document` as far as I can verify. I have also checked all Highcharts source files and the usage of `createElement` or `createElementNS` is correct. This looks like a false positive due to the wrongly checked issue status by the browser. I am not able to recreate the problem on Chrome (also based on Chromium) so I would suspect this being an Edge-only problem visible in that browser and caused by that browser. Edge offers richer options to filter and display the issues tab, so maybe that is why the problem is isolated to Edge only.

If you wish to report the problem to Edge developers please free to link this site for more context.
