### ISSUE TITLE
Stateless functional components should not use 'this'

### ISSUE THREAD

**Issue by jessewriter** [highcharts/highcharts#20631]
#### Expected behaviour
expecting modern javascript like 
`formatter: ( val ) => {  ... }  // to be stateless`

#### Actual behaviour
```
function () {
// forced to call this to get point and color values
}
```
<img width="496" alt="stateless function issue" src="https://github.com/highcharts/highcharts/assets/16365134/3c14bc6d-f2cf-4261-aa83-8fc49552a038">

#### Product version

highcharts v 11.1
#### Affected browser(s)
all

**Comment by bm64** [comment]
Hello @jessewriter

The issue stems from Highcharts intentional design, utilizing `this` within functions to access chart, point, series properties, and more. This design choice leads to what appears as a false positive in linters designed to flag `this` usage outside class components, not recognizing the valid use case within Highcharts context. 

To address the linter warnings in these instances, consider disabling the rule locally:
`
// eslint-disable-next-line react/prefer-stateless-function
`
