### ISSUE TITLE
Show data labels for all levels in Treemap series.

### ISSUE THREAD

**Issue by bm64** [highcharts/highcharts#20691]
# Description of the feature
Data labels should be shown at all Treemap levels without overlap. Child labels should adjust within parent boundaries, avoiding overlap issues. 

User's original description:

> As we can see in the last image in proof-of-concept section, data labels are shown for all levels (including nested) like TECHNOLOGY, SOFTWARE INFRASTRUCTURE (in top-left) etc.
 We tried showing data labels - https://jsfiddle.net/1gv8cpot/117/ but it has following limitations -
The labels are just floating on the data points e.g. TECHNOLOGY label is overlapping on the data point MSFT, taking up MSFT's visible space. Ideally, if data labels are present for a parent then all children should be confined within it like [plotly's treemap](https://plotly.com/python/treemaps/) and last image's example thereby reducing some space for all children.
Above point leads to another issue that data labels for level 2 cannot be shown when we are at level 1, otherwise overlapping will be there - Reproducer - https://jsfiddle.net/12javhqu/ (Just commented the line 238)
Floating data labels for non-leaf nodes may overlap with data labels of leaf nodes.

# Library related to the feature
Highcharts

# Proof of Concept/Live example for the feature
![image](https://github.com/highcharts/highcharts/assets/55414726/d2ea6077-e5c5-4897-b846-d8dbd5ad8cbf)

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by TorsteinHonsi** [comment]
_Internal note_

This feature has been on our radar since we first implemented treemaps. In order to keep the node areas correct, we need to go in on the algorithm level and reserve a fixed space for the data labels. We can assume that the height of each data label is fixed. The width would be the same as the leaf or group. Then the rest of the layout would take this reserved area into consideration.

At the same time, it may make sense to consider padding or spacing between the nodes, which will make a nested layout more readable. This also complicates the computation of the areas, as each leaf not only contributes with its own area, but also that of the padding + heading:
<img width="389" alt="Skjermbilde 2024-02-22 kl  13 16 27" src="https://github.com/highcharts/highcharts/assets/227836/6aedaa42-00cf-4e33-a159-ecf11e6cb71f">

**Comment by TorsteinHonsi** [comment]
Duplicate of #17243
