### ISSUE TITLE
Dashboard layout and configuration change event

### ISSUE THREAD

**Issue by liorheber** [highcharts/highcharts#20756]
# Description of the feature
Currently the way edit mode works is that the user needs to commit changes.
If we set edit mode, we need to close the edit mode to export the state of the dashboard.
When the user edits or configures a widget, the also need to confirm the change to see the impact of their edit.

I think it would be a very good user experience if we were able to listen to change events so that we can persist them immediately.
Say a user resizes a widget, it would trigger an event where we could get the JSON representation of the dashboard.
Same if we drag a new widget, remove something or reconfigure something.

Finally, an extra layer to this event could also be to the chart configuration sidebar that instead of confirming changes we will be able to see the impact immediately on change.

# Library related to the feature
Dashboards

**Comment by karolkolodziej** [comment]
Hi @liorheber! 

Thank you for contacting us! 

1. We do have `resize` and `update` events for components that you can listen to [ see in the API.](https://api.highcharts.com/dashboards/#interfaces/Dashboards_Components_Component.Component.Options#events)
Wouldn't it be sufficient for this use case? 


2. When it comes to updating the components on the change this sounds like a good idea! Do you think the `confirm` button should be obsolete now? Or it should be required to save the changes otherwise clicking on the cancel or outside of the popup will not change the component.

**Comment by liorheber** [comment]
Hi,
Thank you for the response.

1. I think it's doable with the events on the components, that's a great idea!
The main downsides are that the resize event will spam my callback and not be called only onMouseUp, and drag and drop will also send multiple calls. I think they can all be mitigated with some debounce but it would have been nice to have a callback on the dashboard level that will execute only when the dashboard has settled the layout.

2. In the case that a component reacts to their configuration changes immediately I think the confirm button is un-needed. But there would need to be an event that tells the app that the configuration has changed so that it can be persisted somewhere later.


Thanks again for looking into this!

**Comment by karolkolodziej** [comment]
1. We can think of adding an event like `resizeByUser` that will be triggered only when the component size is changed in the edit mode. 
2. Thank you for the input!

**Comment by liorheber** [comment]
That would be great, thank you very much!
