### ISSUE TITLE
Not able to Zoom in to the chart 

### ISSUE THREAD

**Issue by TjeneBen** [highcharts/highcharts#20776]
I have a column chart and when I zoom in, I don't see the bars displaying. 

#### Expected behaviour

I should still see the Y-Axis and Dimension values.
#### Actual behaviour
![Screenshot 2024-03-04 at 3 17 17 PM](https://github.com/highcharts/highcharts/assets/92181086/368c70de-6ebe-4f3c-ac6b-0d6514e97460)

#### Live demo:
https://jsfiddle.net/u53jmxnq/1/

#### Product version
11.1.0

**Comment by hubertkozik** [comment]
Hi @TjeneBen!
When using the categorized x-axis, you shouldn't mix it up with points with names. If you remove categories or remove the `name` property from your points, everything will work correctly: https://jsfiddle.net/BlackLabel/3p05ejur/

The y-axis is hidden, because you set the chart's height to 480 px, but the CSS height style of the container div is set to 400px - it's not a bug, it's a misconfiguration.

If you need any help with Highcharts configuration feel free to reach out to our other [support channels](https://www.highcharts.com/blog/support/).
