### ISSUE TITLE
linkedTo on pie chart's data points (for e.g. setVisible())?

### ISSUE THREAD

**Issue by iweindesmedt** [highcharts/highcharts#2079]
Consider the Donut chart example from the Demos:
http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/pie-donut/

It would be an enhancement to be able to give the inner points an `id`, the outer a `linkedTo`, so that e.g. `setVisible()` on the 'parent' toggles the 'children' as well.

**Comment by mcr222** [comment]
+1 I'd like to be able to dynamically remove portions of the pie at any level. Therefore all child portions should be removed too to avoid wrong representations.

**Comment by hon2a** [comment]
+1 I'd like to show 2 pie charts side-by-side for comparison with just a single common legend (because they're both using the same categories. It should be possible to create linking between points on these two pies similar to that between bar chart series, so that hovering over a legend item would highlight points on both charts and clicking on the legend would toggle them both. (I know how to implement the toggling functionality myself, but I can't do the hover part, as there's no event for legend item hover.)

**Comment by sebastianbochan** [comment]
@hon2a You can use a workaround which hides legend items from second series. The next step is catching click event on a urrent legend item and find a related item in opposite series : 

http://jsfiddle.net/u7FQS/15/

**Comment by hon2a** [comment]
@sebastianbochan Yeah, I did that, but as I said above, the clicks are not all of it. The pie slices from both series should also be highlighted (with a halo as well if that's turned on) on legend item hover and there are no exposed events or APIs for that AFAICS.

**Comment by TorsteinHonsi** [comment]
@hon2a When there are no exposed events in the API you can always hook up events to the DOM elements directly: http://jsfiddle.net/highcharts/u7FQS/277/

**Comment by hon2a** [comment]
@TorsteinHonsi Putting aside how unwieldy that is when using Highcharts through a React adapter, I still don't see an API for toggling the hover state of the slice. (That's what's supposed to happen in place of those `console.log()` calls in your snippet to make the legend truly shared.)

**Comment by hon2a** [comment]
Ah, so there is an API (`setState()`), it's just undocumented :)

@TorsteinHonsi Thanks for the help.
