### ISSUE TITLE
Network graph - Moving a node also move another random one

### ISSUE THREAD

**Issue by kogratte** [highcharts/highcharts#20867]
#### Expected behaviour

I should be able to move a single node, without any impact on the other ones

#### Actual behaviour

Another node, which seems selected randomly, is moving.

**Comment by kogratte** [comment]
[Screencast_from_2024-03-18_09-05-12.webm](https://github.com/highcharts/highcharts/assets/1905621/753fcecf-8cb8-41ed-a305-44f46dbf0e0e)

**Comment by hubertkozik** [comment]
Hi @kogratte!
Can you reproduce the issue in the online editor? You can start here: https://jsfiddle.net/BlackLabel/8zL67bo1/ and send me a link to the forked demo.

**Comment by kogratte** [comment]
Of course.

Was straightforward :)

https://jsfiddle.net/ox5cj30g/

**Comment by hubertkozik** [comment]
Thank you for the demo @kogratte.

The described behaviour is not a bug. I think, that what you actually need is a Treegraph, not a Network Graph. While it's possible to draw a tree-like structure in a Network Graph, by the definition of the algorithm used in a Network Graph makes nodes behave like particles. Every particle in the Network Graph should shift another particle.

Also, we've got a bug in the Network Graph since v10.2.0: https://github.com/highcharts/highcharts/issues/20405)

Closing as not a bug. If you need any further help, please contact us through one of our [Support channels](https://www.highcharts.com/blog/support/).
