### ISSUE TITLE
Automatically drill back when open model based on children column

### ISSUE THREAD

**Issue by bhavya0901** [highcharts/highcharts#20897]
#### Expected behaviour
Not drill back to parent columns chart automatically when i open model based on children column click

#### Actual behaviour
-Step 1 :-  Drilldown to children column
-Step 2 :- Close opened model -> unfortunately chart drill back to parent column automatically but breadcrumbs button group showing like we're showing children chart 

#### Live demo with steps to reproduce
https://codesandbox.io/p/sandbox/react-bootstrap-5-forked-cqn5rq

#### Product version
- Issue with latest highchart version

#### Affected browser(s)
Chrome

**Comment by bhavya0901** [comment]
[Screencast from 20-03-24 04:57:26 PM IST.webm](https://github.com/highcharts/highcharts/assets/119096296/5e184a36-4a58-4d87-b0ef-1ecb3d42c4c1)

Issue has been occurred in above video 
I've open model when click on children column

**Comment by hubertkozik** [comment]
Hi @bhavya0901!

I think I'm missing something. The demo, which you provided in the first post works correctly for me. Can you describe what you mean by `open model when click`?

**Comment by hubertkozik** [comment]
Oh, you mean "modal" as a popup, not model - sorry for that.

This issue is not a bug and it is not related to Highcharts, but to your usage of state variables in React. After clicking the close button in modal popup you are changing the variable state and the component rerenders. Your chart options are declared as a static variable and simply it is rendered with that static value.

**Live demo:** https://codesandbox.io/p/sandbox/react-bootstrap-5-forked-thwdw6

I suggest to read through our `highcharts-react` documentation here: https://github.com/highcharts/highcharts-react?tab=readme-ov-file#optimal-way-to-update

If you need help with chart configuration feel free to reach out to our other [support channels](https://www.highcharts.com/blog/support/), for example [Highcharts forum](https://www.highcharts.com/forum/), where our support engineers will help you with the configuration of your chart.
