### ISSUE TITLE
Column Chart: DataGrouping: false causing the columns to overlap on each other.

### ISSUE THREAD

**Issue by iamgrawal** [highcharts/highcharts#20931]
#### Expected behaviour
Expecting the columns to be spaced equally, ignoring the gap between them.

#### Actual behaviour

For a column chart, whenever we try to have too many data points to show for a view that highcharts can't equally space, it overlaps the columns on each other causing the gaps(whitespace) to be inconsistent.

#### Live demo with steps to reproduce
<img width="659" alt="image" src="https://github.com/highcharts/highcharts/assets/14204344/5f176d41-b1b6-400a-9b5c-0cc74ffb02e6">
<img width="658" alt="image" src="https://github.com/highcharts/highcharts/assets/14204344/debb3ead-9e64-4c49-88a0-5110b7526446">
<img width="656" alt="image" src="https://github.com/highcharts/highcharts/assets/14204344/e6256fda-0898-488c-8a30-abc666622cdc">
<img width="658" alt="image" src="https://github.com/highcharts/highcharts/assets/14204344/c8695517-16a1-4ec8-9bb5-6ee7e9dbac9a">
<img width="659" alt="image" src="https://github.com/highcharts/highcharts/assets/14204344/895efdd9-e55c-4be7-9ea9-712a15e53d47">

JS Fiddle: https://jsfiddle.net/gauravArcana/r1u9kf4w/

#### Product version
Highstocks latest version (v11.4.0)

#### Affected browser(s)
All

**Comment by iamgrawal** [comment]
Also, one more issue is, why the column color is more brighter when the columns are dense but lighter when the columns are sparse.

**Comment by hubertkozik** [comment]
Hi @iamgrawal! There is no bug in the demo you provided. The uneven spacing between columns is caused by the crisp option.

I saw, that you've asked your question also on one of our Support Channels. We use GitHub as a bug tracker platform, so in case of future questions feel free to reach out to our other [support channels](https://www.highcharts.com/blog/support/), for example [Highcharts forum](https://www.highcharts.com/forum/), where our support engineers will help you with the configuration of your chart.
