### ISSUE TITLE
Cannot increase size of legend symbol without increasing size of series point

### ISSUE THREAD

**Issue by jfchickimon** [highcharts/highcharts#20977]
#### Expected behaviour
Upgraded from 10.2.1 to 11.4 and the legend style changed. I expect the legend to not change.

#### Actual behaviour
I can make adjustments for the font size/weight to make it look like it did previously (itemStyle: {'fontWeight': 'bold', 'fontSize': '0.9em'} ), but the symbol size seems to be only affected by the series/marker/radius value, which also changes the size of the series data points. We don't want the data point size to change, only the symbol size in the legend.

#### Live demo with steps to reproduce
I hijacked an existing demo to experiment.
https://stackblitz.com/edit/highcharts-angular-line?file=src%2Fapp%2Fapp.component.css,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

Update the demo with these chartOptions:
  chartOptions: Highcharts.Options = {
    series: [
      {
        type: 'line',
        data: [1, 2, 3, 4, 5],
        marker: {
          radius: 13                                // Example of how radius changes symbol size, but on both legend and the chart.
        },
      },
      {
        type: 'line',
        data: [3, 4, 1, 5, 4],
        marker: {
          radius: 1
        },
      },
    ],
    legend: {
      layout: 'horizontal',
      align: 'left',
      verticalAlign: 'top',
      x: 60,
      itemStyle: {'fontWeight': 'bold', 'fontSize': '0.9em'}      // Increases font size/weight to get previous style
    }
  };
  
Screen shot before (10.2.1)
![legend_before_upgrade](https://github.com/highcharts/highcharts/assets/166523914/f98dfeeb-f14c-486a-9f90-bca96089d1a4)

Screen shot after (11.4) - no programmatic adjustments
![legend_after_upgrade](https://github.com/highcharts/highcharts/assets/166523914/89973d4b-5543-47fd-a297-3f53a09d4ceb)
  

#### Product version
11.4

#### Affected browser(s)
Chrome, etc(?)

**Comment by hubertkozik** [comment]
Hi @jfchickimon!

Thanks for contacting us with your issue. In Hicharts v11.0.1 the `series.legendSymbol` option was introduced: https://api.highcharts.com/highcharts/series.scatter.legendSymbol That's why you are facing some differences.

If you set it in your demo to series: https://jsfiddle.net/BlackLabel/evnas1t7/ everything will work correctly and the legend symbol size will be changed by using `font-size` property.

If you have more problems feel free to reach out to our other [support channels](https://www.highcharts.com/blog/support/), for example [Highcharts forum](https://www.highcharts.com/forum/), where our support engineers will help you with the configuration of your chart.

**Comment by jfchickimon** [comment]
Thanks. And how do you get the symbol shape to match the shape used for the data points? Circle, square, diamond... The fiddle you shared shows circles in the legend, but one series has diamonds for the data points.

**Comment by hubertkozik** [comment]
@jfchickimon To show the marker you can configure `legendSymbol` as a `lineMarker`, then the whole symbol (line and symbol) size is based on font-size: https://jsfiddle.net/BlackLabel/wnmo15z6/

**Comment by jfchickimon** [comment]
Not really the same - the symbol is too small again (without increasing the font (words) to an obnoxious size). But if that's all you got, then I guess it is what it is.
