### ISSUE TITLE
Boosted Heatmap Zoom

### ISSUE THREAD

**Issue by ahansen1** [highcharts/highcharts#21042]
#### Expected behaviour
Zooming a boosted heatmap displays data

#### Actual behaviour
Zooming a boosted heatmap renders no data.  Note, some zooms will work, but others will not.  Zoom and then scroll and will find much of the data is no longer rendered.

#### Live demo with steps to reproduce
A copy of the large heatmap demo (https://jsfiddle.net/api/post/library/pure/ ) with zoom enabled:

https://jsfiddle.net/j42da65w/

#### Product version
11.4.1

#### Affected browser(s)
Chrome

**Comment by hubertkozik** [comment]
Hi @ahansen1! This issue is not related to the zooming feature. This demo contains the `turboThreshold` option, which disables boost, after removing this line, the heatmap is not showing up with the boost module: https://jsfiddle.net/BlackLabel/rb5op0a6/ This topic is a duplicate of https://github.com/highcharts/highcharts/issues/20456.

**Comment by reydoblas** [comment]
I am also experiencing this problem and surprised that this is marked as not planned. Boost feature is a very great feature but it will break the feature if zooming is not working.

I hope that more thoughts and prioritization will be put into this issue. A simple workaround will do for now and will be much appreciated.

**Comment by hubertkozik** [comment]
@reydoblas We treat duplicates as `not planned`. The thread is continued in the issue mentioned above.
