### ISSUE TITLE
Geomap - For orthographic projection with specific map location (USA), some data points are shown out of projection

### ISSUE THREAD

**Issue by sakshi1eQ** [highcharts/highcharts#21128]
#### Expected behaviour

All points should be visible within the projection.

#### Actual behaviour

Some points like US15 and US02 are seen outside the projection.

#### Live demo with steps to reproduce
https://jsfiddle.net/sakshiKorade/Ly4e5qma/6/

#### Product version
Latest Highmaps

#### Affected browser(s)
All browsers

**Comment by hubertkozik** [comment]
Hi @sakshi1eQ!

Here's the simplified demo of your problem: https://jsfiddle.net/BlackLabel/4pbx59zm/

The issue is related to the topology you are trying to use with graticule lines. You are trying to use USA topology, but you are rendering the graticule for the full world. If you want to render graticule, you should use world topology, set desired projection and everything will work correctly: https://jsfiddle.net/BlackLabel/anewmvrt/
