### ISSUE TITLE
Click and hover events pass through x-axis

### ISSUE THREAD

**Issue by fidian** [highcharts/highcharts#21136]
#### Expected behaviour

I have a scollable bar chart and there are items hiding under the x-axis. When I hover over the x-axis or click on the x-axis, the click should be ignored because the bars in that area are not visible.

#### Actual behaviour

Clicks trigger selections of rows (not shown in the demo). Hover events still trigger popups in the x-axis (shown in demo). Right-clicking in the spot shows the bar in the SVG as the topmost element.

![image](https://github.com/highcharts/highcharts/assets/428348/996a3d92-88cf-4fbe-9769-bbe5a0445280)

#### Live demo with steps to reproduce

https://jsfiddle.net/jo3vm6s1/

This does not implement selection of items, but does show how the cursor events are triggering things for bars that are not visible.

#### Product version

* Highcharts JS v11.4.1 (2024-04-04)

#### Affected browser(s)

Chrome.

**Comment by karolkolodziej** [comment]
Hi @fidian! Thank you for reaching out! 

You are right with `opacity: 1,` it doesn't make much sense- [see the simplified demo.](https://jsfiddle.net/BlackLabel/z1p42mtk/)
![image](https://github.com/highcharts/highcharts/assets/57004120/8f726734-dddb-4ec7-8729-bb41fef161e9)


But with a default one, it looks better but still, I'm not sure if this is correct.
![image](https://github.com/highcharts/highcharts/assets/57004120/c5e133e9-46d5-436f-b958-2cc7c9b2494e)


It has been working like this since the get-go, any comments @TorsteinHonsi?

**Comment by TorsteinHonsi** [comment]
@karolkolodziej I think it's a bug. It should be trivial (famous last words) to check the click coordinates or the target point for `chart.isInsidePlot`.
