### ISSUE TITLE
Boost with two yAxis - point flickers

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#21176]
#### Expected behaviour

No ghost point 👻 

![image (5)](https://github.com/highcharts/highcharts/assets/38281922/1a9da3cf-207f-4b40-8332-821d23a92517)

#### Actual behaviour

Boost with two yAxis - point flickers when hovering between series assigned to the different axes

#### Live demo with steps to reproduce

https://jsfiddle.net/BlackLabel/tvb3501m/

**Comment by bm64** [comment]
_Internal note:_ 
Used to work correctly in v7.2.1: https://jsfiddle.net/BlackLabel/hdur97zq/
Unable to bisect

**Comment by hubertkozik** [comment]
The bug is related to the fact, that there is only one `markerGroup` across multiple series with possible multiple axes, which position is set based only on first x-axis and first y-axis.

Related issue: https://github.com/highcharts/highcharts/issues/10464

A related part of code: https://github.com/highcharts/highcharts/blob/b1fcbf788c63f655cb29d1e7f872a353edb1aaf1/ts/Extensions/Boost/BoostChart.ts#L299-L311
