### ISSUE TITLE
Plotbands in the highstock navigator appear on the main chart

### ISSUE THREAD

**Issue by davidseverwright** [highcharts/highcharts#21274]
#### Expected behaviour
Plotbands defined in navigator.xAxis.plotBands should appear on the navigator regardless of if there are any series on the navigator.

#### Actual behaviour
The bands are drawn on the main chart if no series has showInNavigator:true

#### Live demo with steps to reproduce
https://jsfiddle.net/t794jcb5/1/
If you set showInNavigator:true, or change the version to 11.4.1 then it works as expected.

#### Product version
Broken in Highstock 11.4.3, works fine in Highstock 11.4.1

#### Affected browser(s)
Tested in Chrome & Firefox on Mac

**Comment by hubertkozik** [comment]
Hi! Thank you for reporting the regression.

_Internal note:_
Bisected to 4930aeffa13c21851df2ac9e1fb82b3e3a1aafbc FYI @DJTechnoo.

**Comment by hubertkozik** [comment]
Closing this issue should also include a fix for the following:

#### Expected behaviour
Adding a yAxis id should leave the navigator unaltered visibly.

#### Actual behaviour
Adding a yAxis id causes plot bands displayed on the main graph to also display on the navigator

#### Live demo with steps to reproduce
1. Navigate to this fiddle: https://jsfiddle.net/chris_kdd/7nv9u2je/
2. Observe that the plot band is not displayed on the navigator series.
3. Uncomment line 29 of the fiddle and run it.
4. Observe that the plot band is displayed on the navigator series.
