### ISSUE TITLE
Screen reader is not announcing the vertical label of the bar graph

### ISSUE THREAD

**Issue by msftedad** [highcharts/highcharts#21343]
#### Expected behaviour
Screen reader should also announce the vertical label information on the bar graph.

#### Actual behaviour
On the bar graph, screen reader is not announcing “1000 metric tones” vertical label information.

https://github.com/highcharts/highcharts/assets/93735775/95e5a8ca-f5f8-4031-a903-7e62bcc64cf7

#### Live demo with steps to reproduce

1. Open [URL](https://www.highcharts.com/demo/highcharts/column-basic?redirect-to-codepen) 
2. Navigate to the bar graph.
3. Observe screen reader announcement.

#### Product version

Highchart version: 3.1.0

#### Affected browser(s)

Platform: Win32/Chrome/Mac
OS Build: Windows 11
OS Version: 23H2 (OS Build 22631.3672)
Chrome version: 125.0.6422.176 (Official Build) (64-bit)

**Comment by hubertkozik** [comment]
Hi @msftedad! The reported issue is not a bug in Highcharts, this is a screen reader thing.

You can use this option: https://api.highcharts.com/highcharts/accessibility.point.valueDescriptionFormat to overwrite the default point description.

Here's a demo for you: https://jsfiddle.net/BlackLabel/k4w53jcf/
If you inspect the point, you will see I've added the text "metric tons" instead of (MT).
