### ISSUE TITLE
minPointLength not working for stacked column

### ISSUE THREAD

**Issue by nishikantparmariam** [highcharts/highcharts#21389]
#### Expected behaviour
[minPointLength](https://api.highcharts.com/highcharts/series.column.minPointLength) should work for stacked column as well

#### Actual behaviour
In the below example I've a stacked column as value 1, 1, and 84, but 1 is way less compared to 84 so I've set `minPointLength` to increase its height but it seems both the ones are overlapping. Notice that if data is 1, 84, 1 then it is rendered fine.

#### Live demo with steps to reproduce
https://jsfiddle.net/0fx69y1k/6/

#### Product version
Highcharts 10.3.3

#### Affected browser(s)
Chrome

**Comment by hubertkozik** [comment]
Hi @nishikantparmariam! That is a very problematic issue. Currently, the columns/bar overlap because the stacking functionality does not take into account the `minPointLength` option. If it were otherwise, the total value of the column would be incorrect.

You can see all discussions about this problem in this ticket: https://github.com/highcharts/highcharts/issues/1776

Closing as duplicate: https://github.com/highcharts/highcharts/issues/1776
