### ISSUE TITLE
Cannot select a line drawn using Stock Tools.

### ISSUE THREAD

**Issue by ddragula** [highcharts/highcharts#21501]
#### Expected behaviour
The line drawn using the stock tools can be selected.

#### Actual behaviour
Once a line is drawn on a chart using Stock Tools, it cannot be selected for editing or deleted.

#### Live demo with steps to reproduce
1. Draw a line using Stock Tools
2. Try to select the line

Demo: https://jsfiddle.net/BlackLabel/t837cku9/

#### Product version
Highcharts v11.4.6 (introducted in v11.4.4)
Bisected to: https://github.com/highcharts/highcharts/commit/ce54038006395214dba5c3d71bd35f66cefc432f (the fist bad commit)

**Comment by jedrzejruta** [comment]
Seems to work correctly on latest Firefox version

**Comment by pawelfus** [comment]
@hubertkozik any recommendations for the solution? `pointerevents = fill` won't work for elements without fill (eg annotations).

Core example (not a Stock chart related):
- https://jsfiddle.net/BlackLabel/hc60zbav/2/ - v10 works fine, it's possible to drag&drop the arrow
- https://jsfiddle.net/BlackLabel/hc60zbav/3/ - broken

**Comment by hubertkozik** [comment]
The bisected commit was only a temporary fix. I can see, that the bug in Chrome is now fixed, other Chrome users also confirm, that the issue got fixed in M126-126.0.6478.17 :https://issues.chromium.org/issues/337338049

As a workaround for now, we can set `pointer-events` to `auto` with `important` flag: https://jsfiddle.net/BlackLabel/fygmjvcn/

The temporary fix can be removed, we can treat this GH issue as a task to remove the temporary fix.
