### ISSUE TITLE
Error 1015 shows 

### ISSUE THREAD

**Issue by girijamedqpro** [highcharts/highcharts#21504]
#### Actual behaviour
Error 1015 is coming when dowloading the highchart graphs

**Comment by hubertkozik** [comment]
Hi @girijamedqpro! Error 1015 means, that you have been rate limited, probably due to too many requests per minute. Highcharts Export server is working correctly and this is our security thing.

If you need special server settings you can set up your own Highcharts Export Server, some docs: https://www.highcharts.com/docs/export-module/setting-up-the-server
