### ISSUE TITLE
Mouseover event doesn't work after upgrading from v11.4.3 to v11.4.4

### ISSUE THREAD

**Issue by jumperchen** [highcharts/highcharts#21548]
We encountered a bug that works only for Highcharts v11.4.3, but fails after upgrading to v11.4.4.

I found that the issue is caused by this fix: https://github.com/highcharts/highcharts/pull/21170/files

            // #21144, retest and remove in future version of Chrome
            pointerEvents: H.isChrome ? 'fill' : 'auto'

This line "pointerEvents" assigns "fill" to the root element, which prevents the rect element of "highcharts-plot-border" from passing the pointer events to the underlying elements, such as the g element of "highcharts-plot-lines-0".

#### Expected behaviour

When you mouse over a red line on the chart, it should print a console log as "works"

#### Actual behaviour

Nothing happens

#### Live demo with steps to reproduce
https://jsfiddle.net/kg1r703y/1/

#### Product version
Highcharts v11.4.4 and later.

#### Affected browser(s)
Chrome

**Comment by hubertkozik** [comment]
Hi @jumperchen! This issue is the same as in https://github.com/highcharts/highcharts/issues/21501.

As a workaround for now, you can set `pointer-events` to `auto` with important flag: https://jsfiddle.net/BlackLabel/fygmjvcn/

I am closing it as a duplicate, the issue will be fixed in the next release of Highcharts.
