### ISSUE TITLE
Plot lines events are not fired in Chrome

### ISSUE THREAD

**Issue by cmparsons** [highcharts/highcharts#21656]
#### Expected behaviour
Events like `xAxis.plotLines.events.click` and `xyAxis.plotLines.events.mouseover` should get fired as expected

#### Actual behaviour
The events are not fired

#### Live demo with steps to reproduce
Broken example: https://jsfiddle.net/ymqcg7L1/1/

#### Product version

Behavior seems to have been broken since 11.4.4. Works fine in Firefox and Safari but not Chrome

#### Affected browser(s)
Chrome 127.0.6533.100

**Comment by hubertkozik** [comment]
Hi @cmparsons! This issue has the same rootcause as https://github.com/highcharts/highcharts/issues/21501. The workaround for now is to set `pointer-events` to `auto` with important flag: https://jsfiddle.net/BlackLabel/yL6abj1h/

The fix is already merged into master branch, closing as a duplicate.
