### ISSUE TITLE
Legends come on my column bar chart after a certain number

### ISSUE THREAD

**Issue by aryanbhatt-0501** [highcharts/highcharts#21699]
#### Actual behaviour
![image](https://github.com/user-attachments/assets/dbc0e888-5ef6-4014-8d68-928ebe7c0a91)

#### Product version

"highcharts": "10.0.0",

```
{
            Highcharts.chart({
                chart: {
                    // height: height,
                    // width: width,
                    type: "column",
                    renderTo: renderDiv,
                    margin: [60, 60, 100, 60],
                    spacingTop: 1500,
                },
                title: {
                    text: 'Age',
                    align: 'left'
                },
                xAxis: {
                    categories: categories,
                    crosshair: true,
                    accessibility: {
                        description: 'Age group'
                    }
                },
                yAxis: {
                    min: 0,
                    title: {
                        text: 'percentage'
                    }
                },
                tooltip: {
                    valueSuffix: '^'
                },
                credits: {
                    enabled: false
                },
                series: series,
                legend: {
                    verticalAlign: 'bottom',
                    alignColumns: false,
                    padding: 5,
                    itemMarginTop: 5,
                    maxHeight: 100, // Limit legend height and allow scrolling if needed
                    navigation: {
                        enabled: true, // Enable scrolling if legends overflow
                        arrowSize: 10,
                        style: {
                            fontSize: '12px'
                        }
                    },
                },
                plotOptions: {
                    column: {
                        pointWidth: 5,
                        pointPadding: 0.2,
                    }
                },
            });
        };
```

**Comment by hubertkozik** [comment]
Hi @aryanbhatt-0501! I'm sorry but I think I'm missing something. Could you please shed a little bit more light on the matter to help me understand what the issue is?

Also, can you reproduce the issue in an online editor that I could work on? You can start here: https://jsfiddle.net/BlackLabel/nyvmjzou/ and send me a link to forked demo.

**Comment by aryanbhatt-0501** [comment]
The issue is when I have many legends which needs a scroll after maxHeight, they are come on top of my chart as you can see in the picture. I want to keep lets say 100px distance between the legend box and my column bar chart.

I went through the API and tried many things but I am not able separate things out.

**Comment by hubertkozik** [comment]
The legend is placed on the chart, because you specified a chart margins and spacings if you comment it out everything is working correctly, because the legend dimensions are calculated correctly and the legend max height is set to 100px: https://jsfiddle.net/BlackLabel/nw5xj947/

If you want to add a distance between the legend and the plot you can set `legend.margin` option to e.g. `100`px: https://jsfiddle.net/BlackLabel/nzr5pxav/

I don't see any bug here. Looks to me like a misconfiguration.

**Comment by aryanbhatt-0501** [comment]
You are right, thank you so much!
