### ISSUE TITLE
Highcharts/Highstocks minor grid lines disappeared if there is a break

### ISSUE THREAD

**Issue by g020807** [highcharts/highcharts#21749]
#### Expected behaviour
The minor grid lines should be displayed across the whole graph.

#### Actual behaviour
The minor grid lines disappeared when scrolling to the section with a break and reappear when there is no break.

#### Live demo with steps to reproduce

https://jsfiddle.net/BlackLabel/egL48m3u/

#### Product version

Latest?

#### Affected browser(s)
IE and Chrome

**Comment by hubertkozik** [comment]
Hi @g020807! Thank you for reporting the issue. I was able to reproduce the problem without using the Stock module: https://jsfiddle.net/BlackLabel/gqs2tpzk/ Using `breaks` makes minor grid lines disappear. Sadly for now I am not able to give you any workaround, but I'm adding this ticket to our backlog.

**Comment by marvin19** [comment]
The issue seems to occur only with the Stock module. All the `minorGridLines` disappear when the axis section with the break is visible while using the Navigator. In a demo with only Highcharts, the `minorGridLines` are drawn as expected, before and after the break.

_Internal note:_
It might be because of [minor ticks get too dense](https://github.com/highcharts/highcharts/blob/e8d81bd7f54cbca5230ccb8db203235313381645/ts/Core/Axis/Axis.ts#L1198-L1200)
