### ISSUE TITLE
Option to use Canvas instead of SVG for improved performance

### ISSUE THREAD

**Issue by musialny** [highcharts/highcharts#21800]
# Description of the feature
Currently, Highcharts uses SVG as the default rendering engine. I would like to request an option to use Canvas as the renderer instead of SVG. This would significantly improve performance, especially in use cases where a large number of points or complex visuals are rendered. The main performance bottleneck in the current implementation comes from manipulating the DOM. Using Canvas would help bypass this issue, offering smoother rendering and reduced computational overhead.

# Library related to the feature
Highcharts (potentially also Highcharts Stock / Highcharts Map)

# Proof of Concept/Live example for the feature
By switching to Canvas rendering substantial performance improvements could be applied to Highcharts, particularly in cases of complex data visualization.

----

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by hubertkozik** [comment]
Hi @musialny! For charts with large numbers of data points, we already have the Boost module in Highcharts. It enables faster rendering and smoother interactions by using WebGL for rendering, which is particularly beneficial when dealing with thousands or even millions of data points.  It renders the data using WebGL on a canvas inside the chart's SVG structure.

You can read more about this module here: https://www.highcharts.com/docs/advanced-chart-features/boost-module

Boost can be configured in chart configuration, so you can use `boost.enabled` option to use rendering with WebGL on a canvas instead of SVG.
