### ISSUE TITLE
buttons in rangeselector are disabled

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#2187]
I'm not sure why buttons are disabled:

Example: http://jsfiddle.net/Uk5GC/

**Comment by jochienabuurs** [comment]
same here... i  have series data that runs across a period of 3 months. Still, the 1 month button is disabled

**Comment by KacperMadej** [comment]
@jochienabuurs If the problem you described is not open here: https://github.com/highcharts/highcharts/issues/7458 then please add a minimal, live demo.

**Comment by mkulkarn** [comment]
Sorry not working with highcharts anymore

**Comment by sebastianbochan** [comment]
@mkulkarn Could you send us your example of data or replicate your example as live demo on the jsfiddle?

**Comment by richie50** [comment]
@TorsteinHonsi regarding the above comment 
_"Disables range selector buttons which range is below the X axis automatic or explicit minimum range." - This is the reason why the "1m" button is disabled."_

I can enabled all the buttons with allButtonsEnabled: true but when i click a specific button with the above changelog, it does not highlight the button even  though i have this config states: {
                            select: {
                                stroke: 'none',
                                fill: '#cd5806',
                                style: {
                                    color: 'white'
                                }
                            },
on the buttonTheme. I know its data related by how do I manually trigger this class **highcharts-button-pressed** as part of a requirement. In short , can we manually override this and get the class  **highcharts-button-pressed** on the selected range instead of the  **highcharts-button-normal**

**Comment by pawelfus** [comment]
Thanks @richie50 ! Created separate ticket for that: https://github.com/highcharts/highcharts/issues/14273

There's no perfect workaround for this issue. We can set manually state of the button after a short delay, like this: https://jsfiddle.net/BlackLabel/pb4cogL7/

**Comment by richie50** [comment]
@pawelfus Thanks a lot. You workaround is awesome. Hope this will be addressed for future release. 👍🏿
