### ISSUE TITLE
Scatter series and boost + multiple axes missing points

### ISSUE THREAD

**Issue by jiigen3343** [highcharts/highcharts#21897]
#### Expected behaviour
all of the points on the plot render correctly. this worked in 11.1.0 but does not work in 11.4.7. 

#### Actual behaviour
when the plot is boosted due to many series being present the symbols do not render but they are hit testable so the kd-tree is correct. I can only assume that the point feel they are clipped due to the scale range/positioning

#### Live demo with steps to reproduce
current version: https://jsfiddle.net/7fc8n46L/1/
11.1.0 version: https://jsfiddle.net/wfkrd5zq/

#### Product version
11.4.7

#### Affected browser(s)
chrome latest and safari

**Comment by karolkolodziej** [comment]
Hi @jiigen3343! 
Thank you for reporting this issue.

_Internal note:_
Bisected to https://github.com/highcharts/highcharts/commit/7b3d009f748ec4014eb7c2a3664f07506b5c5b93

**Comment by Eskils** [comment]
There seems to be an issue with rendering a scatter series that has only a single point using the Boost module. (See image)

This is being investigated.  

For now—if you need to use a more recent version of Highcharts—since each series only has a single point, using a line-chart `chart: 'line'` will produce the same result.


<img width="556" alt="Screenshot 2024-10-04 at 11 51 02" src="https://github.com/user-attachments/assets/7213d287-957d-48cc-916b-8f73c751d138">
