### ISSUE TITLE
reserveSpace in inverted chart

### ISSUE THREAD

**Issue by bemol** [highcharts/highcharts#21929]
#### Expected behaviour
When setting `reserveSpace: true` option on Y-axis in inverted chart I expect to have space reserved for labels in case the chart is empty (no data).

#### Actual behaviour
There is no space reserved.

#### Live demo with steps to reproduce
[Demo](https://jsfiddle.net/hfv4qxzm/6/)

#### Product version
Highcharts Core v 11.4.8

#### Affected browser(s)
All

**Comment by hubertkozik** [comment]
Hi @bemol! The described ticket is not a bug, it's a correct behaviour. Ticks are placed along an axis to show the units of measurement. Ticks are calculated based on the provided dataset. The axis labels can be found along the axis showing the value of the data it corresponds to. There is no way to reserve space for the axis labels if there is no data for the chart.

**Comment by bemol** [comment]
@hubertkozik You are right it does not work even for not inverted chart so it might be rather a feature request. `reserveSpace` can work the way that the artificial label is rendered, then measured and finally removed. That would be useful especially in case you have multiple charts that have common height and some of them have data and some not, today they are misaligned.

**Comment by hubertkozik** [comment]
Sadly, there is no possibility to create artificial labels, when there is no data for the chart because ticks and tick labels are generated based on actual data assigned to the axis. Based on the data there are a lot of possibilities for placing and rendering the labels, they can be rotated, hidden, squished etc., and without data, it is impossible to predict it.
