### ISSUE TITLE
Drilldown breadcrumb showing wrong label when scrollbar: enabled 

### ISSUE THREAD

**Issue by truejay** [highcharts/highcharts#22052]
#### Expected behaviour
After scrolling to the right then clicking on any item to drill down. it should show the proper label of the selected parent item.

#### Actual behaviour
After scrolling to the right then clicking on any item to drill down. it shows random label of the parent series.

#### Live demo with steps to reproduce
https://jsfiddle.net/ut3saxqy/2/

#### Product version
Highstock latest version

#### Affected browser(s)
All

**Comment by pawellysy** [comment]
Hi @truejay it is a bug. 

`Internal note` 
The index is selected wrong, by `series.options.data` instead of `series.data`
https://github.com/highcharts/highcharts/blob/2ec83de8d65f804ac613abed4fcc62d0a73bb5d3/ts/Extensions/Drilldown/Drilldown.ts#L460-L460


Unfortunately it's not so easy to workaround :(
