### ISSUE TITLE
setExtremes event for xAxis breaks when used on heatmap made with stock module

### ISSUE THREAD

**Issue by AndrzejBuleczka** [highcharts/highcharts#22067]
#### Expected behaviour
setExtrems event works as expected for heatmap created with stock chart module; chart is redrawn accordingly, including xAxis ticks 

#### Actual behaviour
After setting xAxis extremes with setExtremes event on heatmap chart constructed with stock module, display breaks. New min value is skipped if below current min value, chart is correctly extended to the new max value, the ticks can break.

#### Live demo with steps to reproduce
See how it works correctly with the line chart after clicking the button: https://jsfiddle.net/BlackLabel/new7fzr1/
See how it breaks with the heatmap example after clicking the button: https://jsfiddle.net/BlackLabel/ceq6rnfp/

#### Product version
Highcharts Stock

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
This is expected behaviour with [`xAxis.ordinal = true`](https://api.highcharts.com/highstock/xAxis.ordinal), which is the default in Stock. It does not matter if it's a heatmap or a line series. The `ordinal` option does not affect the series when there are two or fewer points. We will get the same result if we add one more point to the demo with the line series: https://jsfiddle.net/BlackLabel/new7fzr1/3/.
