### ISSUE TITLE
Pie chart label cut off when container has a particular height and multi-line data-labels are used

### ISSUE THREAD

**Issue by HendrikThePendric** [highcharts/highcharts#22100]
#### Expected behaviour
The data label is either be fully visible, or completely hidden.

#### Actual behaviour
There is an intermediate state when the data-label is partially visible and partially hidden (i.e. the label is cut off). 

In the screenshot below I show this intermediate state: the CHC label also has a number and percentage below it, but these are not visible / are cut off.
<img width="905" alt="Screenshot 2024-11-04 at 10 58 21" src="https://github.com/user-attachments/assets/a2322542-7e4b-421e-aa9b-4d585621000a">

#### Live demo with steps to reproduce
1. Go to my [JSFiddle](https://jsfiddle.net/yepfdb30/8/)
2. Increase/decrease the height of the container until the bottom data label becomes partially visible (this is around 170-180px)

#### Product version
Highcharts Core 11.4.8

#### Affected browser(s)
All

#### Additional notes
- I discussed this problem with a Highcharts support engineer (Michal) and he agreed that this was a bug although probably not very high urgency, because it only occurs under very specific circumstances
- I found a previous issue https://github.com/highcharts/highcharts/issues/17286 that seemed identical at fist glance, but I actually think in the end that case the problem was caused by a configuration error (rigidly setting the chart size to 100%).

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! I agree it's a bug. The data labels should not be allowed to go outside the plot area (silver line), at least not this far.

#### Minimal reproduction
https://jsfiddle.net/highcharts/nt0qa289/

**Comment by TorsteinHonsi** [comment]
After some digging, I concluded there are two problems:
1. The distribution inside the `plotHeight` does not work correctly. The lower label should stay within the bounds. The code in question is in the [drawDataLabels](https://github.com/highcharts/highcharts/blob/v11.4.8/ts/Series/Pie/PieDataLabel.ts/#L386-L390) function.
2. When we have large slices like this, with so much available space on the side, the label should gravitate towards the side rather than at the bottom. 

In the PR, I address the second issue. This will resolve most, but not all, manifestations of the first issue. View the [OP demo with the fix applied at jsFiddle](https://jsfiddle.net/highcharts/m4L5jd8w/) @HendrikThePendric .
