### ISSUE TITLE
Incorrect chart height under a flexbox with flex-direction: column

### ISSUE THREAD

**Issue by Dron007** [highcharts/highcharts#22148]
#### Expected behaviour
The chart should match the height of the `renderTo` element.

#### Actual behaviour
The chart's height defaults to 400px.

#### Live demo with steps to reproduce
Sandbox: https://stackblitz.com/edit/react-qqk1bd?file=index.js,ChartBar.js,BasicBar.js
1. The chart's height defaults to 400px
2. Switch `package.json` to Highcharts 11.4.7 and observe that the chart's height is correctly set to 180px.

It was challenging to create a minimal reproducible example, as it didn’t work with JSFiddle and CSS. This is likely because CSS attributes are applied too late, after the chart is already created. Some of the structure and rules may look unusual, but they are representative of a more complex page.

There is a workaround to wrap HighchartsReact with `<div style={{ height: '100%' }}>` (commented line in `BaseBar.js`), but I am unsure how universal this solution is.

#### Observations and Related Issues ####
This issue was introduced in version 11.4.8 and seems to be connected to the changes addressing this issue: https://github.com/highcharts/highcharts/issues/21510 .
Looking at the code I see that some strict rules were added to the code to check the parent element’s height. BTW, is it correct: `(enableDefaultHeight ? containerBox.height : 400)`? What exactly is meant by "default"? It seems this logic/naming should be inverted.

According to [Semantic Versioning](https://semver.org/), changes in a patch version should not introduce breaking changes. This fix appears to introduce a breaking change, which is typically expected in a major version. It would be helpful if any required code adjustments were documented to ensure smoother transitions.

This issue has been discussed in various places:

- [Highcharts forum post](https://www.highcharts.com/forum/viewtopic.php?p=195247#p195247) (no effective workarounds mentioned).
- [highcharts-react GitHub repo issue](https://github.com/highcharts/highcharts-react/issues/494). (confirmed to be a core library issue, working workaround mentioned).

#### Product version
Highcharts 11.4.8 (works correctly in 11.4.7)

#### Affected browser(s)
Chrome

**Comment by hubertkozik** [comment]
Hi @Dron007! I am very sorry, that you are facing some issues. This fix wasn't supposed to introduce breaking changes. Your demo from sandbox is reproducible in JSFiddle: https://jsfiddle.net/BlackLabel/tb6m19fz/

The implementation of strict rules was done in an effort to halt endless resizes influenced by the ResizeObserver. You can check the old issue here: https://jsfiddle.net/BlackLabel/cv08rwud/

You have accurately pointed that the designation in the added logic should be inverted. We appreciate you pointing this out and concur this should be `(enableDefaultHeight ? 400 : containerBox.height)`.

Your case is very complicated, as you admitted, it was even challenging to create a minimal reproducible example and it is easier and more common to use Highcharts like in the mentioned (fixed in v11.4.8) demo: https://jsfiddle.net/BlackLabel/cv08rwud/

The official solution for your problem would be to set `height: 100%` to the parent element and this should be the universal solution: https://jsfiddle.net/BlackLabel/y3fvw205/

Considering all this, we can treat this ticket as a path to refine the naming. The `getChartSize` method should seem like this demo: https://jsfiddle.net/BlackLabel/h8jmxfo1/

Can I ask for your @TorsteinHonsi viewpoint about this case?

**Comment by TorsteinHonsi** [comment]
@hubertkozik As far as I can see, Highcharts behaves exactly as announced in https://api.highcharts.com/highcharts/chart.height

If we remove the 100% height setting from the CSS, the container div renders at 0 px height: https://jsfiddle.net/highcharts/0867x1wh/

As expected, and as explained in the docs, adding a chart to this div renders it at 400px height: https://jsfiddle.net/highcharts/0867x1wh/1/
