### ISSUE TITLE
HIghcharts Editor

### ISSUE THREAD

**Issue by tomlinsonml** [highcharts/highcharts#22158]
#### Expected behaviour

//save proj
var projectStr = chartEditor.editor.chart.toProjectStr();

//load proj
chartEditor.editor.chart.loadProject(chartProjectJson);

my previously built chart should load just fine

#### Actual behaviour
Pulling project backup after saving a project results in formatter error:
TypeError: (c[(t.formatPrefix + "Formatter")] || c.formatter).call is not a function

 if i remove the formatter manually from my project json and load back into the editor everything works just fine.
        "formatter": "function(){let{numberFormatter:t}=this.series.chart;return\"number\"!=typeof this.y?\"\":t(this.y,-1)}",

#### Product version

editor 2.2 and highcharts version Highcharts JS v11.4.8 (2024-08-29)

#### Affected browser(s)
Chrome

**Comment by tomlinsonml** [comment]
Temporary quick fix before loading up the project json object in order to get this to work:

 for (var i = 0; i < chartProjectJson["options"]["series"].length; i++) {
                            var dataLabel = chartProjectJson["options"]["series"][i]["dataLabels"];
                            if (dataLabel.formatter != null) {
                                delete chartProjectJson["options"]["series"][i]["dataLabels"].formatter;
                            }
                        }

**Comment by hubertkozik** [comment]
Hi @tomlinsonml! This ticket should be addressed in the highcharts-editor repository: https://github.com/highcharts/highcharts-editor Sadly, I cannot transfer it there. Also, please be sure, that you using the latest version (next-gen) of Highcharts Editor https://lab.highsoft.com/editorv2/

I'll close this issue here. If you would like to continue the discussion, please create a ticket in the highcharts-editor repository mentioned above.

**Comment by tomlinsonml** [comment]
I have posted it in that repo, thanks!
