### ISSUE TITLE
HC.getStyle return wrong border value

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#22203]
#### Expected behaviour
The value should not be 0.

#### Actual behaviour
1. Run the example and console
2. Both values are 1
3. Zoom in page.
4. Run the jsfiddle again
5. `getStyle` return 0, `getComputed` style returns the correct value.

![zooming2](https://github.com/user-attachments/assets/99c86859-4903-4dda-8cba-c2e58526c8ba)

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/ru2a5wpx/6/

#### Product version
Highcharts Core

#### Affected browser(s)
Chrome

**Comment by karolkolodziej** [comment]
@TorsteinHonsi Do we need that conservative `parseInt` for the styling?
https://github.com/highcharts/highcharts/blob/6ea245f24769385ef1de07d3e7b3f09bdfaf7cfd/ts/Core/Utilities.ts#L1560

**Comment by TorsteinHonsi** [comment]
@karolkolodziej The `getStyle` function by default returns a number because it is mostly used for further calculation. There's a third argument though, where you can opt out and return the string value. See https://jsfiddle.net/highcharts/kLrovwhf/

https://github.com/highcharts/highcharts/blob/6ea245f24769385ef1de07d3e7b3f09bdfaf7cfd/ts/Core/Utilities.ts#L1508-L1512

**Comment by sebastianbochan** [comment]
What a mistake from my side, sorry for reporting it.
