### ISSUE TITLE
missingModuleFor: heatmap since a couple of days

### ISSUE THREAD

**Issue by nicolasdouziech** [highcharts/highcharts#22272]
Hello,

I'm using highcharts with a library named easychart on python. I deployed a streamlit app with docker months ago.
Since a couple of days, I got this error : "Highcharts error #17: www.highcharts.com/errors/17/?missingModuleFor=heatmap - missingModuleFor: heatmap"
I did not change anything in my python code neither requirements.txt with precise versions of libraries.

Is there any change in server side which can explain this error ?

Thank you
Nicolas

**Comment by hubertkozik** [comment]
Hi @nicolasdouziech! Your issue is probably related to Highcharts v12 changes, where we changed the default build system to webpack, allowing for tree shaking in the build process and smaller builds. It's hard to guess, without taking a look at your code, but now, when importing Highcharts as a node module, additional modules no longer requires initialization. See [comment on GitHub](https://github.com/highcharts/highcharts/issues/22251#issuecomment-2507396579).

**Changelog:** https://www.highcharts.com/changelog/
