### ISSUE TITLE
Chart redraw event not firing if explicitly redrawing a series

### ISSUE THREAD

**Issue by royalone** [highcharts/highcharts#22303]
#### Expected behaviour
call `.redraw()` on a series, then the `chart.events.redraw` callback fires:
https://api.highcharts.com/highstock/chart.events.redraw

#### Actual behaviour
Doesn't fire. However as the docs mention, if I were to instead update the series data with `redraw: true` flag, then the event would have fired. 

#### Live demo with steps to reproduce
https://jsfiddle.net/rt4w1njk/2/

^ modified the demo from the redraw docs linked above, just with an explicit series redraw

#### Product version
Current v12.0.2

#### Affected browser(s)
Edge current 131.0.2903.70

**Comment by hubertkozik** [comment]
Hi @royalone! The `series.redraw` method is not officially documented: https://api.highcharts.com/class-reference/Highcharts.Series, and it is used only internally in Highcharts. You shouldn't use this function in the same way as with `chart.redraw` method, because the redraw of the series is fired for specific conditions.

**Demo with `chart.redraw`:** https://jsfiddle.net/BlackLabel/kcyumb37/

**Comment by royalone** [comment]
ah ok no worries, thanks @hubertkozik
