### ISSUE TITLE
processedYData, processedXData is undefined

### ISSUE THREAD

**Issue by Makesh-Gmak** [highcharts/highcharts#22356]
#### Expected behaviour
Till 11.4.8, series[0].processedXData, series[0].processedYData were giving range of x or y-axis values as per the range selector

#### Actual behaviour
From 12.0.0 onwards, both are giving undefined

#### Live demo with steps to reproduce
Buggy : https://jsfiddle.net/pt1joqun/
Working one: https://jsfiddle.net/fq9xuc3n/
#### Product version
12.0.0 

#### Screenshot

![image](https://github.com/user-attachments/assets/eee9dbdf-1420-4b14-9b6a-85ec8f59e8cf)

**Comment by hubertkozik** [comment]
Hi @Makesh-Gmak! In Highcharts v12 the Series class was refactored to organize its data in a DataTable instead of parallel arrays. Due to that properties like `xData`, `yData`, `processedXData` and `processedYData` were removed, as well as some additional series-specific data arrays, in favor of `Series.dataTable`.

`Series.processedXData` is replaced by `Series.getColumn('x', true)`
`Series.processedYData` is replaced by `Series.getColumn('y', true)`

**Changelog:** https://www.highcharts.com/changelog/#highcharts-v12.0.0
