### ISSUE TITLE
When using tooltip formatter, Highcharts.time.dateFormat is using browser locale instead of graph locale

### ISSUE THREAD

**Issue by vancanneytsander** [highcharts/highcharts#22393]
#### Expected behaviour
Use the defined HTML 'lang' attribute

#### Actual behaviour
Using the browser locale

#### Live demo with steps to reproduce
https://jsfiddle.net/7r43wobp/1/

#### Product version
12.1

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

Since you set the `lang` attribute on the parent element of the chart, the `Highcharts.time` instance of `Time` isn't aware of it. Instead, you can use `chart.time` which is specific to that chart inside that container: https://jsfiddle.net/highcharts/0dxpvtwe/1/ .

That said, if we remove `lang="de"` from the container, I would expect the global `Highcharts.time` to pick up the language from the `html` tag, which in jsFiddle is `en`. But that doesn't happen. So in my Norwegian browser, if I get Norwegian formatting when calling `Highcharts.time.dateFormat` or `Highcharts.numberFormat`: https://jsfiddle.net/highcharts/bxovwhaq/

**Comment by TorsteinHonsi** [comment]
Turns out the global `numberFormat` function [does this correctly](https://github.com/highcharts/highcharts/blob/fe63b3dad54d7fe490d36c9b894e34eb0a1f5421/ts/Core/Templating.ts#L496), while `dateFormat` does not. 

#### Workaround
Set the default options to the `html` tag's `lang`.
```js
Highcharts.setOptions({
    lang: {
    	locale: document.body.closest('[lang]')?.lang
    }
});
```
[View it live on jsFiddle](https://jsfiddle.net/highcharts/9jvdfhkn/)

**Comment by daysleeperrr** [comment]
Thanks for improving Highcharts. A little concern though, I am using the hosted version of Highcharts. Since this update, i'm getting the following error, which might be related to this fix?

`Uncaught TypeError: Cannot read properties of null (reading 'closest')`

Caused by the following line:

`        t.pageLang = t.doc?.body.closest("[lang]")?.lang,`

Thanks!

**Comment by arenddeboer** [comment]
I'm getting a blank page on the hosted version with the same error as @daysleeperrr

**Comment by chicochaz** [comment]
Same issue here.

Uncaught TypeError: Cannot read properties of null (reading 'closest')
    at highcharts.js:8:898
    at highcharts.js:8:1778
    at highcharts.js:9:272787
    at highcharts.js:8:324
    at highcharts.js:8:329

**Comment by sjcliffe** [comment]
Same issue for me. Changed to specifically load v12.1.0 to get my charts working again.

**Comment by hubertkozik** [comment]
Thank you all for reporting the issues. The problem is fixed in the current version, which is Highcharts v12.1.2. Here's the related ticket: https://github.com/highcharts/highcharts/issues/22423
