### ISSUE TITLE
When using tooltip formatter this.x does not respect the set timezone for labels

### ISSUE THREAD

**Issue by vancanneytsander** [highcharts/highcharts#22406]
#### Expected behaviour
this.x in tooltip formatter should be the timestamp in respect to the set timezone of the graph (time: {timezone: 'Europe/Brussels'} ). Since timezoneOffset is deprecated in 12.x we can't just add the needed minutes to this.x to correct the labels when using formatter.

#### Actual behaviour
this.x in tooltip formatter contains the timestamp in UTC time, that way the time displayed in the tooltip is not the same as on the x-axis ticks.

#### Live demo with steps to reproduce
https://jsfiddle.net/48c1g9vm/

#### Product version
12.1

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

This setup is related to yesterday's issue, #22393. The problem in this configuration is that you're setting the `time.timezone` locally to one chart instance, while you're using the global `Highcharts.time.dateFormat` in the tooltip formatter. You need to either set the timezone globally, or use the local time object in the formatter.

* **Option 1: Set global time**. Move your `time.timezone` out to a `Highcharts.setOptions` call to make it apply to the global `Highcharts.time` object. https://jsfiddle.net/highcharts/w18vm7yn/
* **Option 2: Use local time in formatter**. Instead of calling `Highcharts.time.dateFormat`, call `tooltip.chart.time.dateFormat`: https://jsfiddle.net/highcharts/w18vm7yn/1/

I appreciate that this is somewhat unclear, I'll try to explain it better in the docs.
