### ISSUE TITLE
Issue with lang.thousandsSep and decimalPoint setting

### ISSUE THREAD

**Issue by AndrzejBuleczka** [highcharts/highcharts#22402]
#### Expected behaviour
Setting lang.decimalPoint and lang.thousandsSep works correctly and consistently

#### Actual behaviour
Setting lang.decimalPoint and lang.thousandsSep is not working conistently, in some scenarios they are swaped contrary to the setting

#### Live demo with steps to reproduce
https://jsfiddle.net/andrzej_b/hmdoq825/
The first point (decimal point only) is displayed correctly
The second point (thousands separator only) shows a comma instead of a dot
The third point (thousands separator + decimal point) shows a comma instead of a dot and a dot instead of a comma.

#### Product version
Highcharts Core

Regression, last working version: 11.4.8, bisected to [37e4f79
](https://github.com/highcharts/highcharts/commit/37e4f79097137bc30a9c3a7b9a0462b321e2b39a)
#### Affected browser(s)
all

**Comment by karolkolodziej** [comment]
As a workaround, you can set the `locale` like in the code snippet bellow-[ see in the demo.](https://jsfiddle.net/Lc29sz0a/)
```js
Highcharts.setOptions({
  lang: {
    locale: "en-GB"
  },
})
```
    

FYI @TorsteinHonsi

**Comment by TorsteinHonsi** [comment]
Thanks @AndrzejBuleczka, a fix is on its way. 

As a **workaround**, I would suggest using the new `lang.locale` option, although it comes with the side effect of also localizing dates unless otherwise specified in the `lang` options. But that's most likely what you want when you're using non-default formats: https://jsfiddle.net/highcharts/dhtbxmpg/
