### ISSUE TITLE
Highcharts Ganttchart multiple series data grid issue

### ISSUE THREAD

**Issue by ubaiy** [highcharts/highcharts#22412]
#### Expected behaviour
I want to add grid on the ganttchart which have multiple objects inside a series but I am not able to as when i am trying to do that the grid is getting crumbled but when I add only 1 column it is working fine so not sure that is happening here 

#### Product version

    "highcharts": "^11.4.1",
    "highcharts-angular": "^3.1.2",
    "highcharts-custom-events": "^3.0.10",

**Comment by karolkolodziej** [comment]
Hi @ubaiy. I don't fully understand what you are trying to achieve but if you take a look at [the examples here](https://www.highcharts.com/demo#highcharts-gantt-demo-highcharts-gantt) you can find some with multiple series.

If you still won't be able to figure this out, please contact [our support team ](https://www.highcharts.com/blog/support/)because we mostly use GH for bug and feature tracking.
