### ISSUE TITLE
Highcharts: exporting does not work, it gives 403 Forbidden

### ISSUE THREAD

**Issue by MrDiga** [highcharts/highcharts#22414]
# Description of the feature

# Library related to the feature

# Proof of Concept/Live example for the feature

----

**You can vote for this feature by adding a thumbs-up reaction to this post.**

**Comment by hubertkozik** [comment]
Hi @MrDiga! The HTTP 403 Forbidden client error response status code indicates that the server understood the request but refused to process it.

To ensure optimal performance for all users, we require that each request includes an identifiable referrer and user agent header. Requests missing these headers may be blocked by our system, so please verify that your requests include them.

Please note that due to the variability of traffic, there are no fixed limits on our service. Limits fluctuate in real time based on current traffic, complexity, and system load. Automated traffic - such as from bots, cron jobs, and event-driven processes—is given the lowest priority and may be restricted without prior warning when system load demands it.

If you're making automated or high-frequency requests, they may be subject to throttling or temporary restrictions. We recommend adjusting your usage accordingly.

You can check [our guidelines](https://www.highcharts.com/docs/export-module/privacy-disclaimer-export) for more detailed documentation.
