### ISSUE TITLE
highcharts_modules_exporting__WEBPACK_IMPORTED_MODULE_5___default

### ISSUE THREAD

**Issue by varunshine** [highcharts/highcharts#22451]
Hello I have update the version of highcharts and highcharts-react-official after updating pacakges my current application code is not working.

Give error like 
App.js:8 Uncaught TypeError: highcharts_modules_exporting__WEBPACK_IMPORTED_MODULE_3___default(...) is not a function
    at ./src/App.js (App.js:8:1)

Version for Highcharts
"highcharts": "^12.1.2",
"highcharts-react-official": "^3.2.1",

Code for App.js

import React from 'react';
import Highcharts from 'highcharts';
import HighchartsReact from 'highcharts-react-official';
import exporting from 'highcharts/modules/exporting';
import exportData from 'highcharts/modules/export-data';

// Initialize the modules
exporting(Highcharts);
exportData(Highcharts);

function App() {
  const options = {
    title: { text: 'Test in App.js' },
    series: [{ data: [1, 2, 3] }]
  };

  return (
    <div className="App">
      <HighchartsReact highcharts={Highcharts} options={options} />
    </div>
  );
}

export default App;;

I have removed the modules and reinstall it but the issue is still exist how can i solve this.

**Comment by hubertkozik** [comment]
Hi @varunshine! Since Highcharts v12.0.0 you don't have to initialize the modules, you can find the information under the "Upgrade notes" section in the changelog: https://www.highcharts.com/changelog/#highcharts-v12.0.0

**Live demo:** https://codesandbox.io/p/sandbox/highcharts-react-demo-forked-wqmfy9?workspaceId=ws_xDBBaab9YwVfsLwKBg7Xy
