### ISSUE TITLE
Stacking areaspline with different x-values

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#2285]
Example: http://jsfiddle.net/frcqR/52/
Master example: http://jsfiddle.net/frcqR/53/

As you can see, areaspline isn't stacked at all. The reason is mainly by different pointStart and pointInterval, but with irregular data for datetaime axis it would be problematic much more.

**Comment by TomasNilsson** [comment]
Here is an example with the desired behavior according to us when it comes to stacking with different x-values: http://jsfiddle.net/on4sm4zt/1/

The first chart shows that the stacking doesn't work if the x values for two series are not the same. Both series have data for the x values 1, 3, 4 and 5 and the stacking works correctly there. However, if there is a small offset for the x values (x=2 and x=2.2 in our example) the stacking doesn't work. 

Our goal is to visualize the sum of the two lines for an arbitrary x value even though they might not have  identical x values in their data sets. Is this possible to achieve with the current version of Highcharts/Highstock? Or would it be possible to fix?

Since the points are connected by a line it would make sense to use the interpolated value of the bottom line for x=2 and add the value of the upper line for x=2 in order to get the y-position of the blue line. We have tried to visualize what we mean by adding extra points in the second chart of our example. Ideally, you wouldn't have to add extra points to achieve this effect.

**Comment by likwifi** [comment]
Guys I still can't get why this bug still wasn't fixed?

**Comment by markalroberts** [comment]
I'd really like this too - the previous charting library were using (flot) enabled us to stack two sets sampled data (x axis = datetime) where sample times varied across the two sets. Highcharts doesn't seem to work

**Comment by TorsteinHonsi** [comment]
See also #5169 which explains what happens. The missing option is probably to be able to set `connectNulls` to `interpolate`.

**Comment by KacperMadej** [comment]
This issue is the same as #5169. That issue has more comments and was previously used to close other issues as duplicates, so I'm closing this one too, as a duplicate, in favor of #5169. Please continue with comments there.
