### ISSUE TITLE
Highcharts - y-axis data label missing in Firefox, browser inconsistency

### ISSUE THREAD

**Issue by ricksuggs** [highcharts/highcharts#2304]
The following chart is missing the data label on the stacked column furthest to the right. The label appears in latest version of Google Chrome, however the label does not appear in the latest version of Firefox.

Also to be noted. In Firefox, if you increase the height of the chart div by 50 pixels (400), the 1 will show. And in Chrome, if you decrease the height of the chart div by 15 pixels (335), the 1 will disappear. This does point to a cause being that when the bottom segment is too short for a label, it disappears. This does not happen when the upper segments get too small however.

http://jsfiddle.net/ricksuggs/eGW86/3/

Highcharts 3.0.5

Google Chrome 29.0.1547.76 m

Mozilla Firefox 21.0

Windows 7

**Comment by jon-a-nygaard** [comment]
__Regarding browser inconsistency__
Tested current version 4.2.5 in chrome 51 and firefox 47 and there is still an inconsitency between them regarding which data labels that are hidden. Probably caused by different handling of bounding box between browsers.
@TorsteinHonsi Is there something we can do about this?

@ricksuggs If you by any chance prefer consistency above usability then you can set the option [dataLabels.allowOverlap](http://api.highcharts.com/highcharts#plotOptions.series.dataLabels.allowOverlap) to true. Then data labels will be shown even if they collide.

__Regarding the unwanted visible data labels__
Considering this fixed as it does not appear using the latest version of Highcharts.

**Comment by TorsteinHonsi** [comment]
> @TorsteinHonsi Is there something we can do about this?

We could probably override what bounding box height is reported for a certain combination of font-family and font-size, but I think it is best to leave this up to the browsers. However there is one case where a browser reported a far too high bounding box, so [we saw the need to hard code](https://github.com/highcharts/highcharts/blob/v4.2.5/js/parts/SvgRenderer.js#L813-L816) it.

**Comment by jon-a-nygaard** [comment]
Considering this a browser issue and will thereby not fix it. Should anyone have further information about this issue, please comment and/or reopen.
