### ISSUE TITLE
Tooltip ignores transform: scale

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#2405]
When I use transform: scale, the tooltips ignore this. 
See http://jsfiddle.net/kzoon/v3aa8/
The mouseover on december points display the august tooltips

**Comment by Thirteen09** [comment]
I've run into this problem too. Do you have some kind of solution? 
Can you fasten fixing this bug? We use scale all over our application and have tool-tips show in wrong places all over it. The discussion at #1753 does not help in our case.

**Comment by kzoon** [comment]
I use this workaround:

    HighCharts.wrap(HighCharts.Pointer.prototype, 'normalize', function (proceed, event, chartPosition) {
        var e = proceed.call(this, event, chartPosition);
  
        var element = this.chart.container;
        if (element && element.offsetWidth && element.offsetHeight) {

            var scaleX = element.getBoundingClientRect().width / element.offsetWidth;
            var scaleY = element.getBoundingClientRect().height / element.offsetHeight;
            if (scaleX !== 1) {
                e.chartX = parseInt(e.chartX / scaleX, 10);
            }
            if (scaleY !== 1) {
                e.chartY = parseInt(e.chartY / scaleY, 10);
            }

        }
        return e;
    });

**Comment by oriko** [comment]
Hi 
How do you use this workaround? 
Where do I need copy this code to? I am using Highcharts JS v4.1.8 with angular (highcharts-ng).

Thanks,

**Comment by kzoon** [comment]
No. This fiddle  http://jsfiddle.net/0qppo7yr/ implements my workaround. There it works to prevent problems due to transform: scale(0.7) in the css

**Comment by dmitrygorbenko** [comment]
Hi guys,

any update on this thread ?
Can the patch provided by user kzoon be applied ?

thanks,
Dima

**Comment by TorsteinHonsi** [comment]
Yes, the drop-in fix seems to work well with the current version, but it will most likely fail with old browsers that don't implement the `getBoundingClientRect` API.

**Comment by dmitrygorbenko** [comment]
yes, you are right !

**Comment by kzoon** [comment]
Not solved in Highcharts 5. My workaround still works.

**Comment by KonstantinJahnel** [comment]
@kzoon your fix seems to work perfectly fine in Firefox and IE but i can't get it running in Chrome? 
Any idea why?

**Comment by starquake** [comment]
For me the fix works perfectly fine. Does the fiddle work?

What issues do you have?

**Comment by starquake** [comment]
@TorsteinHonsi The browsers that do not support getBoundingClientRect() also do not support transform: scale

Maybe knowing that helps to make a better fix.

**Comment by KonstantinJahnel** [comment]
@starquake im such a fool,
it has to be my mistake, tried the fiddle out and it works perfect.

Where should i implement the fix tho? 
right now it's $(...fix...); after my prototypes in the main.js

**Comment by starquake** [comment]
@KonstantinJahnel I can't possibly answer that without knowing more about your software. I'm sorry, I can't help you with that.

**Comment by balkarov** [comment]
Why did not fix it in highcharts?

**Comment by Llorx** [comment]
I'm thinking on 3 ways to fix this problem, being the last one the one I like most. Here they go:

To overcome this, I think that you can do getBoundingClientRect (which take into account the transformations) on each point after redrawing them, caching the result and using the cache as the bounding box to detect the collisions.

The other way will be to traverse through all the parents processing the getComputedStyle transforms of each element, and internally apply the scaling/translation to the mouse events. The problem here is to process the skew or 3d transformations.

And finally another performant way can be to getBoundingClientRect one time (on each redraw) the chart container and compare it to the actual chart size. With this you get the scale applied. Simply apply that scale to each mouse event. This method also don't takes into account skew or 3d transformations, but can be a fast fix to have scaling covered.

**Comment by Llorx** [comment]
Here you have a jsFiddle with a working PoC of the last fix I commented: http://jsfiddle.net/tnprxch5/8/

**Comment by balkarov** [comment]
Hello.

THis is does not work after rescale 
http://jsfiddle.net/gskm3dj2/

**Comment by sebastianbochan** [comment]
@balkarov,
The issue has been already reported there: https://github.com/highcharts/highcharts/issues/12489
