### ISSUE TITLE
Line/point calculations in Highstock

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#2406]
Example: http://jsfiddle.net/nywsa/8/

Zoom in on the chart. For example to see only last week. Lines are crossing in the middle, while shouldn't, values should go to:
- black: 190-206, while it's a full line (34-206)
- blue: 150-160, while it's 64-160

Related topic: http://forum.highcharts.com/highstock-usage/line-series-on-candlestick-chart-render-incorrectly-on-zoom-t27890/

This issue happens only when `ordinal=true` is set

**Comment by pawelfus** [comment]
+1

**Comment by nagin** [comment]
+1

**Comment by drbeep** [comment]
> The problem is that the trend lines are drawn with only two points - one in each end, and Highstock is unable to extrapolate the axis to draw the line in the right X positions

**Comment by drbeep** [comment]
+1 This problem (which also makes Ray/InfiniteLine annotations to be 99% useless) is still there, for 4 years by now.

**Comment by 3Ue** [comment]
+1 The problem affects all annotations that can be dragged so that one controlPoint gets outside the visible area.

**Comment by luu4** [comment]
Hello,
I see that a lot of issues are conntected to this. 
Is there any progress or plan for solving?

Thank you
Luu

**Comment by pawelfus** [comment]
Hi @luu4 

We will focus on this issue in the near future.

For some of the issues described above, setting [`series.getExtremesFromAll`](https://api.highcharts.com/highstock/series.line.getExtremesFromAll) should be enough: https://jsfiddle.net/BlackLabel/7Ljm0akn/

**Comment by luu4** [comment]
Hi @pawelfus,
thank you for your fedback.
You are right function getExtremesFromAll is helpful to solve the issue, the line is keeping the right position, that is perfect.

Unfortunatly when getExtremesFromAll is activated then 2 others issues are openned:
1. yAxis includes min and max of all data set, this caused the chart itself is flattened in yAxis and this don't looks good.
2. The performance is for large dataset is realy slow. When I deactivated function getExtremesFromAll  the performance is much better.

Luu

**Comment by pawelfus** [comment]
Hi @luu4 

Yes, that are the downsides of using `getExtremesFromAll`, performance and flattening the dataset. At this moment there are no better workarounds, so we want to focus on this issue in the nearest feature

**Comment by luu4** [comment]
Hi @pawelfus,
thank you.
What about use funtion getExtremesFromAll only for the stock tools?

Thanks.
Luu

**Comment by pawelfus** [comment]
Thank you for sharing the idea!
That would decrease the performance even worse (when using StockTools)

**Comment by luu4** [comment]
OK, I don't know about the inside logic , I just tried to think about it... :)

**Comment by karolkolodziej** [comment]
_Internal note after brainstorming session:_ 
**1. `val2lin` method**

- This function uses a linear approximation for the whole data set which in cases where points are declared with significantly different interval (seconds and hours for example) is not that accurate. 
This might be improved by replacing the `ordinal.slope` and `ordinal.offset` (parameters of the linear equation `y = a * x + b`) by parameters calculated exactly for the two points that are in the neighbourhood of the `val` we are looking for.
- Check if the `lin2val` method also needs that improvement.
- First `while` break doesn't work. We immediately go to the second loop no matter if we find a match.

**2. Annotation coordinates don't calculate correctly.**

- The `val2lin` method uses the `ordinalPositions` array in order to find the result. However, that array contains only ticks for the current extremes. In order to properly calculate the point coordinate, we need to also have points that are outside of the current zoom.
- Here, the `getExtendedPositions` method might be useful. With its help, we can calculate and cache the ticks for the whole data set including currently invisible points.
- Working with a slightly bigger array might have an impact on the performance. In order to limit that, add the condition that checks if the `val > axis.min && val < axis.max`, in cases like this we might use previous logic with the `ordinalPositions`.

**Comment by PaulJaker** [comment]
Hi,
I see some new informations realting this bug mention by karolkolodziej...can I solve this bug with this comment?
How could I implement it to the chart? 

Thank you
Paul

**Comment by pawelfus** [comment]
Hi @PaulJaker 

The comment above was just an internal note, summing up how to solve the issue. We want to fix this issue in the near future.
