### ISSUE TITLE
destroy()ing a chart doesn't remove it from Highcharts.charts

### ISSUE THREAD

**Issue by iweindesmedt** [highcharts/highcharts#2431]
what the title says

**Comment by dave-watts** [comment]
try	

Highcharts.charts = Highcharts.charts.filter(function(n){ return n != undefined });

**Comment by anagrius** [comment]
Would this not be a memory leak? If you keep old `undefined` values lying around, the array will just keep growing over time.

**Comment by TorsteinHonsi** [comment]
Yes, in theory, if you create and destroy hundreds of thousands of charts in the same page you could potentially see memory building up. But in that case I would consider whether the architecture is good. Alternatively, filter the `Highcharts.charts` array like shown above.

**Comment by jonranken** [comment]
In my app, I only ever show one plot. And after the view is changed, I want to just delete that plot. I accomplished this using array.splice() method.

if (Highcharts.charts[0] !== undefined) {
    Highcharts.charts[0].destroy();
    Highcharts.charts.splice(0, 1);
}

This will destroy the chart and then remove the undefined placeholder from the array. The 'if' statement is just so that if the array is empty (the first time this code section runs) then it will not try to run destroy() on undefined. This might be more elegantly done with some error handling, however.

**Comment by marcuus** [comment]
Had the same problem fixed by putting a try-catch around the destroy method

**Comment by dss010101** [comment]
I see this closed..im assuming this issue has never been resolved? correct.  its many years later and this is causing some problems when regenerating charts without reloading the page.

**Comment by hubertkozik** [comment]
Hi @dss010101! This issue is closed because the described behaviour is the expected one. More information here: https://api.highcharts.com/class-reference/Highcharts#.charts

> An array containing the current chart objects in the page. A chart's position in the array is preserved throughout the page's lifetime. When a chart is destroyed, the array item becomes undefined.
