### ISSUE TITLE
Areaspline strange colors and opacity

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#2695]
See  http://jsfiddle.net/kzoon/gAHTM/

if you toggle type between area and areaspline, you see that the colors and opacity of areaspline are different. It looks like series 1 is plotted behind series 2

**Comment by ncoquelet** [comment]
Hi,
Stacked area are little ugly if we don't apply opacity.
And areaspline are really awesome comparing simple area !

You don't implement true stacking for performance reason or simply because you don't address it yet ?
Thanks.

**Comment by ewino** [comment]
We also use the areaspline quite a bit in our Highcharts charts (our values tend to fall to a sine-like behavior) and our UI is looking great right now (due mostly to your areaspline charts).

Now that I have to implement a stacked chart, I would rather avoid having to revert to the simple area charts, but because of the graph's partial opacity the colors look weird when using it.

Is there any plan to fix the opacity problem? (as I see this issue is open for more than a year now...)

Also, many thanks for your work up until now!

**Comment by highslide-software** [comment]
I worked on this now, and created a patch for something that works perfectly with the initial sample above:

```
diff --git a/js/parts/AreaSeries.js b/js/parts/AreaSeries.js
index cd130c5..ee4e8e1 100644
--- a/js/parts/AreaSeries.js
+++ b/js/parts/AreaSeries.js
@@ -114,7 +114,10 @@ var AreaSeries = extendClass(Series, {
 			options = this.options,
 			segLength = segmentPath.length,
 			translatedThreshold = this.yAxis.getThreshold(options.threshold), // #2181
-			yBottom;
+			yBottom,
+			bottomSegments = [],
+			getPointSpline = this.getPointSpline,
+			spline;
 		
 		if (segLength === 3) { // for animation from 1 to two points
 			areaSegmentPath.push(L, segmentPath[1], segmentPath[2]);
@@ -131,9 +134,26 @@ var AreaSeries = extendClass(Series, {
 				// step line?
 				if (i < segment.length - 1 && options.step) {
 					areaSegmentPath.push(segment[i + 1].plotX, yBottom);
-				}
 				
-				areaSegmentPath.push(segment[i].plotX, yBottom);
+				} else if (getPointSpline) {
+					bottomSegments.push({
+						plotX: segment[i].plotX,
+						plotY: yBottom
+					});
+
+				} else {
+					areaSegmentPath.push(segment[i].plotX, yBottom);
+				}
+			}
+
+			if (getPointSpline) {
+				for (i = 0; i < bottomSegments.length; i++) {
+					spline = getPointSpline(bottomSegments, bottomSegments[i], i);
+					if (spline[0] === 'M') {
+						spline[0] = 'L';
+					}
+					areaSegmentPath = areaSegmentPath.concat(spline);
+				}
 			}
 
 		} else { // follow zero line back
```

This works with stacks that have the same amount of points on the same X values. Now the problem is with null points in either of the data series. Perhaps we can use the above code, but then we need to check first if there are nulls or loose ends on the series. A valid check may be if `xData.toString()` is equal on all series in the stack.

**Comment by ncoquelet** [comment]
Nice job @highslide-software !
Works like a charm with my data. 
I just needed to set closedStacks to false in AreaSplineSeries!

Happy to see it in next release.
Thanks

**Comment by myagoo** [comment]
Will the patch be released ?

**Comment by highslide-software** [comment]
@myagoo Not yet, as you see from my comment above there are still problems with it.

**Comment by mikegough** [comment]
I got around the problem by setting the opacity in my css file:

```
.highcharts-series-group {
    opacity:.85
}
```

**Comment by ncoquelet** [comment]
Looking at http://jsfiddle.net/kzoon/gAHTM/
It seems that this issue was resolved, isn't it ?

**Comment by TorsteinHonsi** [comment]
Yes, it has been fixed.
