### ISSUE TITLE
Formatting xAxis labels as quarterly labels shows labels out of order

### ISSUE THREAD

**Issue by julieknoll** [highcharts/highcharts#2865]
In this JS Fiddle you can see the first 3 labels on the xAxis appear as Q4, Q2, Q3 ... where it should be Q2, Q3, Q4. http://jsfiddle.net/MJCsw/1/

The code I'm using to format the quarters is:

```
Highcharts.dateFormats = {
    Q: function(timestamp) {
        var date = new Date(timestamp);
        switch(date.getMonth() + 1) {
            case 1: case 2: case 3: return 1;
            case 4: case 5: case 6: return 2;
            case 7: case 8: case 9: return 3;
            default: return 4;
        }
    }};
```

**Comment by pawelfus** [comment]
It looks fine at this moment, even without using `getUTCMonth`.

**Comment by dkoltg** [comment]
Hi, I have a similar case and your function Q helped a lot to solve. However, in my case, the tooltip displays the correct date (quarter and year), but on the x axis the labels are displaced (they should be shifted to the right).
See example in fiddle: https://jsfiddle.net/statistik_tg/xeqmbvds/2/ 

Does anyone has a solution for this problem?
Thanks for any contributions!

**Comment by pawelfus** [comment]
Hi @dkoltg 

The problem is in dates in your data, for example: `"2013/2/30"` or `"2013/5/30"`. Both dates are somewhere in the middle of Qx. xAxis always renders it's tick in the beginning of a period, not in the middle. That means Q1 will be rendered at 1st of Jan, Q2 will be rendered at 1st of April etc.

Additionally, I believe that quarters equal to three months, not four (your `tickInterval`).

Once you disable quarters-logic, you will be able to see all of this, take a look: https://jsfiddle.net/BlackLabel/9huwgbfp/1/

**Comment by dkoltg** [comment]
Hi Pawel,
Thanks for your hints and adapted code. This helps a lot!
