### ISSUE TITLE
Update serie - flags are wrong

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#2878]
In case when we update series, flags break navigator / extremes, in both exampes (on series or on axis).

http://jsfiddle.net/qbtrL/

**Comment by pawelfus** [comment]
It's not a problem with flags series only, but in general for non-ordinal series, for example scatter: http://jsfiddle.net/BlackLabel/qbtrL/1/

Actually it's caused by `xAxis.ordinal` option, when disabled we get proper chart: http://jsfiddle.net/BlackLabel/qbtrL/2/

**Workaround (for scatter series only):**
Use line series without line: http://jsfiddle.net/BlackLabel/qbtrL/4/
