### ISSUE TITLE
0 has both colors with negativeColor

### ISSUE THREAD

**Issue by iweindesmedt** [highcharts/highcharts#3021]
http://jsfiddle.net/wfcNS/4/

I don't think this is a bug, but it doesn't seem right

**Comment by oysteinmoseng** [comment]
This is still relevant, and does look a bit odd.

**Comment by tomasell** [comment]
Any updates about this issue? All lines around threshold have two colors..

**Comment by KacperMadej** [comment]
It's because part of the line is above and part of it is below, so it has 2 colors.

The case is labelled as undecided, so please let us know how are you expecting this to work @tomasell ? Will your suggestions of resolving the problem work also in a case like this: http://jsfiddle.net/wfcNS/39/

**Comment by tomasell** [comment]
Do you think it is possible to predict the trend? I try to explain better (sorry for my english).
First we have to discriminate if `step` property is :
- `false`: you should have to change line color,  keeping in mind line width (threshold +/- width). So [this](http://jsfiddle.net/wfcNS/43/) will be 
<img width="1072" alt="step_false" src="https://user-images.githubusercontent.com/3263675/40927480-1be228f4-681f-11e8-8a10-15f65a8eb9fd.png">

- `true`: you should have to set an intermediate value as threshold ( see [this example](http://jsfiddle.net/wfcNS/42/), but I'll expect to see when value changes (see attachment 
<img width="1063" alt="step_true" src="https://user-images.githubusercontent.com/3263675/40926486-9afd65c0-681c-11e8-9da5-88bad6e6b2d0.png"> ) because I know that there couldn't be possible intermediate values.
