### ISSUE TITLE
Browser freeze with series.setData() in 4.0.3 (regression from 3.x)

### ISSUE THREAD

**Issue by mcayland** [highcharts/highcharts#3260]
Hi all,

We are currently experiencing a performance issue with HighCharts 4.0.3 within our application where loading data asynchronously from multiple sources and then updating the series with setData() will cause the browser to freeze. This is something that we did not experience with the HighCharts 3.x series.

Based upon one of the HighCharts JSFiddles, I've create a demo application to demonstrate the issue loading 4 different series of 1000 data points. Using this application, I was able to analyse the page with a JS profiler in Firefox in order to determine where the time was being spent.

With 4 different series (each taking approx. 25% of the time to render), it could be seen that 21% of the total time time per series was being spent in Point.prototype.firePointEvent(). Drilling down further, there are 2 main hotspots in this area of code:

1) jQuery's .inArray() for checking parallel arrays in Point.prototype.update() (line 14511)

2) Series.prototype.getAttribs()

For 1) it seems that Point.prototype.update() has to re-scan the entire data series O(N) for each individual point - is there any reason why the point data cannot be directly referenced in the Point object, either directly or via an array index into the series data?

For 2) a casual glance shows that this is quite a complex function, however given that a single series is being updated at once, is there no way in which the result of Series.prototype.getAttribs() can be cached for use with point.applyOptions() when firing the point update event?

As this is one of the most important parts of our application, we are unable to update from HighCharts 3.x until this is resolved. Is this something that you can reproduce using the demo application, and if so do the strategies above go anywhere towards resolving this regression? I would think that resolving these issues would greatly improve the overall HighCharts 4 experience not just for our application but also for all HighCharts users.

Kind regards,

Mark.

(Attached below is a screen capture of the profiler - I'll upload the demo application separately)

![profile-hc](https://cloud.githubusercontent.com/assets/1729603/3597172/6046fd04-0cce-11e4-9ebf-a1d2ac257b98.png)

**Comment by redskate** [comment]
Hi, thank you for sharing.
I am using the the 3d bar chart of the ***current*** version of highcharts 4.1.8 . Looking very nice!
Soon I discovered that the chart should not vizualize more than 1000 nodes at a time. (...)

So I loaded 2 data series (each 200 points) and a name serie (x-axis). On the first load everything is fine.

When the program updates the data in the series and the x-axis it takes on a mac mini late 2012 i7 with 8GB and SSD "only" ***8-9 seconds***!  This cannot be true.  200 points must go (very) fast - even in a browser. (It seems that safari and chrome be slightly faster than firefox. )

The command I use to show another data is (each series):
	Highcharts.charts[0].series[1].setData(serie1data_200pt,false,false,false);
        Highcharts.charts[0].redraw();

So I suppose I have done my homeworks switchint off the options after the data. But the 3D bar chart update is definitely too slow to be updated...

Can you suggest my any solution please? Do I have each time to destroy and rebuild the chart?

Thank you in advance
Regards

**Comment by highslide-software** [comment]
Hi @redskate ! You didn't supply a live demo, but here's one based on your descriptions: http://jsfiddle.net/highcharts/e3r3o7zk/

On my machine the initial chart rendering takes ~300ms and updating takes ~100ms when the `updatePoints` option is true (as recommended). Updating takes ~250 ms when `updatePoints` is false, which means that all point objects are destroyed and new ones are generated instead of using the existing ones.

Can you modify my fiddle to reproduce your problem?

**Comment by redskate** [comment]
Hi Torstein

thank you for reacting. Unfortunately the application is working on sensible data, so I cannot - right now - put online a prototype. Probably the delays occur because the code is embedded inside other javascript code. I will do this in the next time - maybe you give me (please) your email address, so I can send the link privately? I have a certain respect for hackers… ;) 

Thank you
Fabio

-- 
GMAIL
Sent with Airmail

On 24 September 2015 at 10:38:21, Torstein Hønsi (notifications@github.com) wrote:

Hi @redskate ! You didn't supply a live demo, but here's one based on your descriptions: http://jsfiddle.net/highcharts/e3r3o7zk/

On my machine the initial chart rendering takes ~300ms and updating takes ~100ms when the updatePoints option is true (as recommended). Updating takes ~250 ms when updatePoints is false, which means that all point objects are destroyed and new ones are generated instead of using the existing ones.

Can you modify my fiddle to reproduce your problem?

**Comment by highslide-software** [comment]
Hi Fabio, just replace your data with mock data, as long as you reproduce the bug it is okay.
