### ISSUE TITLE
Hover text for shortened Axis labels is wrong hover text when using formatter.

### ISSUE THREAD

**Issue by gvaartjes** [highcharts/highcharts#3276]
When having long labels in combination with a formatter specified for rendering Axis labels. 

_expected behaviour_
The Axis label is shortened and ends with ... three dashes. When hovering over the label the whole label text is shown.
_the issue_ 
In [SVGElement.js L.964](https://github.com/highslide-software/highcharts.com/blob/master/js/parts/SvgRenderer.js#L964)

The DOM content specified by the formatter is set in the TITLE tag as textContent and displays a wrong hovertext

**copied from browser**

```
<text title='<div style="max-width:150px; white-space: nowrap; overflow:hidden; text-  overflow:ellipsis;">Financial, Investment &amp; Other Diversified Companies 
   </div>' style="cursor: default; font-size: 10px; font-family: arial, helvetica, sans serif; position: absolute; color: #222222; padding-left: 4px; padding-right: 4px; fill: #222222"
```

Client claims this is happening in IE11 in compatibility mode when running getSVG() 

Test with this fiddle: http://jsfiddle.net/8wBDh/4/

**Comment by derekm** [comment]
I have a graph example on jsfiddle that blows up the lines of code under concern in this bug (highcharts.src.js:2803) when using an axis labels formatter function: https://jsfiddle.net/oc92n27x/

The pick() function must be returning the function instead of the text returned by the function, hence no "replace" method to call.

Curiously, at this height, if I can 10 or more series, the graph renders as expected, but a 9 or fewer series, the graph blows up on line 2803. Similarly, if I comment out the "height" property in the highcharts config, allowing the graph to fill the entire div, then it renders as expected with the given series data.

This is probably a new bug/issue, but I wanted to report it here first, since the line in question is commented with this issue #.

Thanks!
