### ISSUE TITLE
Negative coordinates in geometry.

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#3314]
Example: http://jsfiddle.net/tzY3T/10/

Maps isn't displayed properly.

**Comment by irbian** [comment]
The zoom isn´t working either, does it?

**Comment by pawelfus** [comment]
Hi @irbian - could you provide a jsFiddle demo? Thanks!

**Comment by pawelfus** [comment]
@irbian - this is how it used to look like for the bug report: http://jsfiddle.net/BlackLabel/tzY3T/30/ (no map at all). Zoom is not available because map is to small. The same happens when coordinates are only positive: http://jsfiddle.net/BlackLabel/tzY3T/34/

**Comment by irbian** [comment]
what do you refere with "is too small"?

**Comment by pawelfus** [comment]
There's no need to zoom in further for you map, calculated values suggest we shouldn't zoom in. You can change that by setting `xAxis.minRange` and `yAxs.minRange`, demo: http://jsfiddle.net/BlackLabel/tzY3T/35/

**Comment by irbian** [comment]
perfect! it was exactly that

Just for clarification, In my case, I had a map with positive coordinates, and everything went well. Later, I change it for a map with negative coordinates and I was affected by this bug https://github.com/highcharts/highcharts/issues/5295

After applying the patch, I guess that with the change of coordinates it changed also the range, because I couldn´t zoom

Now, modifying the minRange, I´m able to zoom again
