### ISSUE TITLE
ignored zIndex of serie

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#3321]
As in topic.
Example: http://jsfiddle.net/4j7U6/

**Comment by TorsteinHonsi** [comment]
Here's a small snippet that adds the plot band in the `chart.seriesGroup` so that the z-indexes are resolved against series rather than other elements:

http://jsfiddle.net/highcharts/r3Lzjjz6/1/

**Comment by drmrbrewer** [comment]
@TorsteinHonsi I like the workaround.. very nice.  IMHO this should be the default behaviour but I'm happy if I can alter behaviour so that the `plotBand` elements operate within the same `zIndex` realm as the series.

How can this wrapper be extended to cover all other rendered elements, such as the image in the following example?

http://jsfiddle.net/eLjnjmr3/

The green line should (in my world) be above the symbol because it has a higher `zIndex`.

**Comment by pawelfus** [comment]
It can be changed in the same way, this part is the most important one:

    .add(chart.seriesGroup)

Add your image to the same group as series and zIndexes will be applied within this group, demo: http://jsfiddle.net/eLjnjmr3/1/

**Comment by drmrbrewer** [comment]
Ah OK thanks.  I understand the previous workaround a little better now, and the extra workaround in your new demo.  Many thanks.

**Comment by drmrbrewer** [comment]
@pawelfus on the theme of gaining full control over zIndex positioning, I've now added dataLabels into the mix.  In following example, I want the dataLabels for the blue line to be above the blue line but below the yellow plotBand, i.e. hovering only just above the line but not above other chart features that are intended to be above it:

http://jsfiddle.net/mhf7s78p/

But so far as I can tell, it's impossible to do that... by setting zIndex of the dataLabels to 2 you can make the labels go under the blue line (and under the plotBand), but that's not what I want.  I want to set it to 6.5 to put it above 6 (blue line) and below 7 (plotBand), but the labels must be in a different grouping... I want all chart features in the same group so that I can control zIndex relative to each other.

**Comment by pawelfus** [comment]
It is not possible, if you take a look into the DOM, you will notice dataLabels are in a separate group, just like plotBands, plotLines etc. Workaround is the same as with plotBands, put dataLabels group into the seriesGroup: http://jsfiddle.net/mhf7s78p/1/

It is possible to put plotBand on top of the dataLabels, you just need to remove the first workaround: http://jsfiddle.net/ndbdwoub/1/

**Comment by drmrbrewer** [comment]
Thanks once again @pawelfus ... I suspected that the workaround would be based on the same idea, and I did have a quick look at the highcharts sources, but wasn't really sure what I should be overriding in the case of dataLabels... your solution is very neat indeed... I think now I have all my chart elements working within the same zIndex regime so I'm happy :)

**Comment by drmrbrewer** [comment]
@pawelfus I'm just trying to iron out a little quirk I've spotted with these workarounds, as illustrated in the following example:

http://jsfiddle.net/444o5swb/

Basically, in my code I allow the user to set an integer zIndex for the various chart features, but not for the dataLabels... they are placed automatically at a zIndex of 0.5 above the associated line, so that the labels sit above the line but below any other feature the user might have placed at a zIndex of 1 above the line.

But when you put the image (sun symbol) also at the same zIndex as the line, the image actually sits *above* the labels for the line.

Is there a further workaround to fix this?

**Comment by pawelfus** [comment]
`zIndex` must be an integer, decimals are rounded :)

**Comment by drmrbrewer** [comment]
aaah :)  so the further workaround is to double each `zIndex` before use:

http://jsfiddle.net/2pLkj34k/

Yes it's an unnecessary workaround if the zIndexes are all set to integers in the first place, but actually in my case it is more intuitive for users if conceptually the labels (which aren't a feature whose zIndex they can control) sit at a *half-point* value above the line, so that an overlay feature can be placed one zIndex point above a line feature, with the line labels sitting in between, rather than having to separate them by two zIndex points to allow for the labels.

Thanks!

**Comment by bwojtyca** [comment]
@pawelfus As I understood with `zIndex`es Highcharts are trying to reproduce behavior known from `CSS` when in the same time keep grouped and "organized" structure in DOM. From 
[SVG specification](https://www.w3.org/TR/SVG2/render.html#RenderingOrder) we know that:
> The position on the z-axis defines the order that they (elements) are painted. 

So..., why series are not grouped by they `zIndex` configuration? From SVG structure perspective that solution will be even more "organized"...

Additionally - is it possible to change `zIndex`/position in DOM of that group with series from configuration level? Right now all series are placed with `zIndex : 3` and there is much space to organize other elements below that `zIndex`...

**Comment by pawelfus** [comment]
Hi @bwojtyca 

Series are rendered according to the `zIndex` property. The issue was reported that you can not mix elements from different [groups](https://www.w3.org/TR/SVG2/struct.html#GElement) (e.g. plotBands and series). zIndex option allows users to organize items **within** a group.

You can change zIndex of `seriesGroup` but not through config: `chart.seriesGroup.attr({ zIndex: newIndex });`. Note that series **are not** placed with `zIndex: 3`, but are placed in **a group** with `zIndex: 3` (from demo: https://www.highcharts.com/demo/line-basic ):

![screen shot 2019-02-05 at 18 18 15](https://user-images.githubusercontent.com/1453926/52291372-7b1cb400-2972-11e9-9965-41bfce3ccdf0.png)

**Comment by Philzen** [comment]
> Here's a small snippet that adds the plot band in the `chart.seriesGroup` so that the z-indexes are resolved against series rather than other elements:
> 
> http://jsfiddle.net/highcharts/r3Lzjjz6/1/

Thanks heaps for this. Would it break anything to include this as standard behaviour?

I just scratched my head for like an hour why this wouldn't work and from looking at the API reference it's not obvious that plotLines' zIndices don't line up with series' zIndices - so having this as out-of-the-box behaviour would make everything feel more intuitive (and save others potential bumps).

**Comment by pawelfus** [comment]
> Would it break anything to include this as standard behaviour?

This would break most of the existing charts (that use Highcharts from our CDN). At this moment, `zIndex` option works within a group (e.g. series, plotLines). Imagine we changed that and every dev, who configured one of zIndex options, now will get completely different layout - in a project closed years ago. I agree with you, we should improve our docs here at least.

**Comment by drmrbrewer** [comment]
@pawelfus or you could just have a new option with a default that kept the current behaviour but which enables the users to switch easily into what many would consider to be a more intuitive model where all elements are rendered within the same zIndex domain.  For me, the workaround is fine (and it enables other actions on the entire group of elements), but maybe it would be nice for other users to have a simple switch.

**Comment by pawelfus** [comment]
Yes, that's one possibility, to add new option + add description in all related zIndex options.
