### ISSUE TITLE
Polar chart does not have zoom

### ISSUE THREAD

**Issue by harssh** [highcharts/highcharts#3424]
Is there any specific reason polar chart does not have zoom feature or can you point me to any documentation where reason is specified ?

**Comment by fandomfilms** [comment]
Also need a zoom for polar chart.  We have portions of the chart that are too small to click on.

**Comment by Menighin** [comment]
Hi guys, just ran into the same situation which would be nice to have zooming in a polar chart. Does Highcharts have anything like this now?

Regards,

**Comment by pawelfus** [comment]
Zooming in polar chart is not supported at this moment.

**Comment by hosein** [comment]
Any chance of getting this added?

**Comment by TorsteinHonsi** [comment]
For now we don't have plans for it, but of course we may reconsider. As I see it we need two things:

- A mapping of mouse coordinates back to chart coordinates. We already have logic for this, as used by the tooltip.
- Render the selection box as an arc instead of a rectangle. This is not very complicated, but probably requires some rewriting/splitting up of the current logic so that it gets easier to plug in to.

**Comment by ChitraKanakavelu** [comment]
Has it been implemented now?

**Comment by pawelfus** [comment]
Hi @ChitraKanakavelu - issue is still open, so it's not implemented.

**Comment by bm64** [comment]
Feature added in v10.3.0: https://www.highcharts.com/samples/highcharts/chart/zoomtype-polar
Related PR: #16992

**Comment by unartcs** [comment]
I cannot make the zoom work on mobile, using Safari and Chrome. Am I missing something or is it unavailable yet?
`chart: {
        polar: true,
        type: 'line',
        panning: true,
        pinchType: 'xy', // Enable pinch zooming
        zoomType: 'xy'   // Enable zooming in both directions
    },`

**Comment by hubertkozik** [comment]
Hello @unartcs! Zooming on mobile is not working for polar charts. Pinch is not implemented for polar coordinates.
