### ISSUE TITLE
Use rtl in Highstock

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#3482]
Example: http://jsfiddle.net/t3doqcy4/2/

Range selector doesn't have `useHTML` option, so it's displayed improperly (in compare to the tooltip).

**Comment by Izothep** [comment]
+1

**Comment by repl-nitin-vasudevan** [comment]
Hi, Can you let us know if there is a plan to get this fixed sometime now so that we can plan accordingly? This is blocking our development work for now.

**Comment by TorsteinHonsi** [comment]
The problem is that `rtl` swaps the behaviour of the `text-anchor` attribute, so `text-anchor` start now means the text is anchored to the right side of the text.

This messes up the labeling rendering and placement in Highcharts. I fixed it by setting `dir="ltr"` on the chart container element, so the SVG elements will inherit that. Rtl text still works, it is just the text-anchoring that is affected.

Please let me know if this solution causes unforeseen problems.

* See the [demo with the fix applied](http://jsfiddle.net/highcharts/t3doqcy4/3/).
* [Arabic demo](http://jsfiddle.net/highcharts/ebqj2e19/33/) with the fix applied.
