### ISSUE TITLE
Size of chart plot is controlled by Axis Labels 

### ISSUE THREAD

**Issue by ohadPA** [highcharts/highcharts#3744]
In case axis labels are lengthened, plot size is diminished because it cannot be set independently. 
If it was an option, we could force its container to be scrollable, thus allowing to present all the information. The situation now compels us to cut the labels, which is not always acceptable.

JsFiddle example:
http://jsfiddle.net/2x6rsgtq/

**Comment by highslide-software** [comment]
So setting `chart.marginLeft` is not an acceptable option for you? 

> If it was an option, we could force its container to be scrollable

What would be scrollable - the plot area or the labels area?

**Comment by ohadPA** [comment]
I'm interested in making the plot area alone to be set to a fixed size, so I can have the container of the (whole) chart can be scrollable whenever the labels area is too big. 
In the current situation the plot's area is diminished due to enlarging of label area.
how can marginLeft help here? Please show me on my JsFiddle examle.

**Comment by highslide-software** [comment]
Okay I think I understand... You want the width of the chart vary with the length of the labels so that the plot area stays constant? So that if the labels take up 100px and the plot area 300px, the chart width should dynamically land on 400px?

I'm afraid that's not possible currently. The `marginLeft` setting will set a fixed width of the space to the left, where the labels are, which in turn makes the plot area fixed. But size of the chart itself will also be fixed to either the `chart.width` setting or to the available width of the container.

**Comment by ohadPA** [comment]
I see. I opened a feature request here, it could be very helpful
http://highcharts.uservoice.com/forums/55896-general/suggestions/6688418-allow-setting-min-width-specifically-to-plot-thus

Thank you

**Comment by jon-a-nygaard** [comment]
Closing this issue since it has been posted as feature request on our Uservoice channel.
