### ISSUE TITLE
Zooming issue in scatter plot chart

### ISSUE THREAD

**Issue by ajitkamathge** [highcharts/highcharts#3770]
The points on scatter chart disappear on zooming (sometimes on first zoom & sometimes on second zoom). This issue is reproducible on scatter chart given on Highcharts official demo page. 
Following is the fiddle for the same:
http://jsfiddle.net/b6pry9qw/

This issue can be reproduced by zooming on the following points in above fiddle:
1) Female: 147.2 cm, 49.8kg (Zoom twice and point disappears): Attached below screenshots for the same.
2) Male: 177.8 cm, 116.4 kg (Zoom once and point disappears)

NOTE: There seems to be some issue with Y-axis zoom.

![scenario1_chart_onload](https://cloud.githubusercontent.com/assets/10776605/5980572/a70c6f7e-a866-11e4-96be-d4beefe883a8.jpg)
![scenario1_chart_zoom1](https://cloud.githubusercontent.com/assets/10776605/5980579/c2efa724-a866-11e4-841c-6a79cc59c13a.jpg)
![scenario1_chart_zoom2_issue](https://cloud.githubusercontent.com/assets/10776605/5980580/c63f93c6-a866-11e4-8d63-d70888abc0c0.jpg)
![scenario1_chart_zoom2_zoomarea_select](https://cloud.githubusercontent.com/assets/10776605/5980581/c95a34bc-a866-11e4-8c39-e45e6300b35c.jpg)

**Comment by polarathene** [comment]
@ajitkamathge  Seems like a bug with the yAxis zooming, I've got some workarounds you can try in the meantime.

You can set a minRange on the yAxis, the female isn't displayed when zoomed because she is 49.8kg and the zoomed yAxis is showing a tick of 49.2kg. Similar with the male, the zoom yAxis is not showing the correct y range. minRange doesn't seem to work here, you can use `yAxis.max=120` for example.

Another option is to add to yAxis properties `endOnTick:true` and a `tickInterval:20`, this forces the ticks to increments of 20 instead of every 72 pixels taken from `tickPixelInterval` by default. You'll still need `minRange:2` for the female case though.

Just to note for anyone attempting to fix the issue setting the zoom to just `y` will zoom the yAxis correctly.

**Comment by pawelfus** [comment]
Another workaround is just to sort data points (`.sort(function(a,b) { return a[0] - b[0]; })`, see: http://jsfiddle.net/b6pry9qw/1/

**Comment by sebastianbochan** [comment]
Fixed since HV v5.0.11
