### ISSUE TITLE
multi-series column chart drilldown issue when clicking on an X axis label

### ISSUE THREAD

**Issue by philfreo** [highcharts/highcharts#3771]
http://jsfiddle.net/pypaq94t/9/

As you can see, clicking on particular bars works fine. However, when you click on the xAxis' label (e.g. California), the drilldown function is executed 3 times and there is a JavaScript error. In the loading message, the name from the last execution of the function prevails, whereas the drilled down chart corresponds to the data loaded via the first execution of the function).

There should be a param on e or on e.point that distinguishes a category click from a specific bar click. The drilldown function should only be executed once for a category click.

**Comment by highslide-software** [comment]
The drilldown event like it is defined today applies to one point, which kind of makes sense since a category click effectively drills down three points separately. 

A possible way out of this could be to add another event before it, something like drilldownByCategory. 

For now, I've added an event argument, `category`, so that you can detect the difference. It will be an integer if a category is clicked. You'll find the actual category name in `e.point.name`.

But the real problem is that when you call `chart.addSeriesAsDrilldown`, you trigger a redraw, which will mess up the next point drilldown. So what we do internally for category clicks is to call `chart.addSingleSeriesAsDrilldown`, then when all points are loaded, we run `chart.applyDrilldown`. You can see it demonstrated at http://jsfiddle.net/highcharts/pypaq94t/11/.

**Comment by andrewpaliga** [comment]
`addSeriesAsDrilldown` appears to be called twice in the highmaps [drill down demo](https://www.highcharts.com/maps/demo/map-drilldown). I had to add a condition ('if(e.point.name != null)') to avoid an error in my console.
