### ISSUE TITLE
Highmaps: setData - animation settings are not applied

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#3931]
Example: http://jsfiddle.net/L6mf6yfo/1/
1. Click "Set random data" button to set new data.
2. Animation is not being set as in setData argument.

**Comment by pawelfus** [comment]
Workaround: set `chart.animation`: http://jsfiddle.net/L6mf6yfo/2/

**Comment by jbasrai** [comment]
I'm not seeing the view update when the button is pressed even though the data does.

**Comment by TorsteinHonsi** [comment]
You're right, it doesn't update at all now. 

New fiddle with new easing definition: http://jsfiddle.net/highcharts/L6mf6yfo/4/

The last version where setData worked was Highmaps 1.1.9: http://jsfiddle.net/highcharts/L6mf6yfo/5/. Since 1.1.10, nothing happens on setData.

@oysteinmoseng , will you have a look?

**Comment by oysteinmoseng** [comment]
Offending commit: https://github.com/highcharts/highcharts/commit/d8705c1
