### ISSUE TITLE
Value overlap when plotting multiple series

### ISSUE THREAD

**Issue by bborowin** [highcharts/highcharts#3959]
Values on multiple axes align so that there is confusing overlap (eg, here: http://i.imgur.com/Qz5Xfat.jpg)

In above example, the green axis has is on a different scale than the black axis, but by coincidence there is perfect overlap between sections of the two curves / some datapoints.

**Comment by highslide-software** [comment]
Do you consider this a bug? How would you expect it to work?

**Comment by bborowin** [comment]
It would require some pre-processing, but I would expect the scales of the separate vertical axes to be chosen automatically so that there is no (visual) collision between data points / curve segments.

Currently, if data on one axis is [(2,4),(3,6),(4,8)] and the other is [(2,8),(3,12),(4,16)], the chart will auto-scale the vertical axes so that the lines will overlap. For this example, one solution would be to offset one of the vertical axes, or scale it by a non-unity factor. I understand that the hard part is not changing the scale or the offset, but detecting the collisions in the first place.

**Comment by KacperMadej** [comment]
The issue is possible to resolve using existing axis options like min, max, linkedTo, etc.

Please contact [Highcharts technical support](https://www.highcharts.com/support) for technical support.

To suggest a new enhancement idea please use [userVoice](https://highcharts.uservoice.com/forums/55896-general), the most popular ideas are getting implemented.
