### ISSUE TITLE
FIPS is No Longer Federal Information Standard

### ISSUE THREAD

**Issue by imasonaz** [highcharts/highcharts#3970]
FIPS was withdrawn as a standard back in 2012, and thus NIST will no longer make any updates to it. [Here is the link](http://www.nist.gov/itl/upload/FIPSCodesReplacementChart2012.pdf)
Standard 5-2 is what you use for states, and 6-4 is what you use for counties.

The new standards are INCITS 38-2009 (states) and INCITS 31-2009 (counties), [found here](https://www.fgdc.gov/standards/fgdc-endorsed-external-standards)

The link on that page refers to the 2010 census, which still uses FIPS, but that should change when the next census comes around (2020) This bug may be more just being correct to standards than anything else, and since everyone seems to prefer using FIPS, it my be easier to keep that, or have a way to set what code you're using.

**Comment by wergeld** [comment]
Working in the field that uses FIPS we have seen no change to federally designated areas for States or Counties in decades. FIPS codes for national areas, states, counties, and metropolitan areas are still actively in use. The Census through the OMB have released the **new** Metro Area definitions using the FIPs standard based on Census 2010 data. I cannot think of the last time a county or a state was added since FIPS was even started. Last county change I know of was a name change from some judge to a more appropriate Native American name.

You are not tied to using FIPS in highmaps. You can use any coding you want.

**Comment by imasonaz** [comment]
My point is that FIPS is no longer "official" the new term is INCITS, so although little to nothing may change between the name change, it is now incorrect to use "FIPS" as a title for counties, cities, or states.
It's like saying you're using HTML4, while still possible, and used by some, it is frowned upon and using HTML5 as a standard is "better"

**Comment by wergeld** [comment]
All federal data is still produced using FIPs codes.

**Comment by MonteShaffer** [comment]
I concur that "all federal data uses FIPS" as identifiers.  I was reviewing the highmaps example with counties and the raw json data:  https://cdn.rawgit.com/highcharts/highcharts/057b672172ccc6c08fe7dbb27fc17ebca3f5b770/samples/data/us-counties-unemployment.json

is an arbitrary identifier for each county.  The example should use something like "us-al-xxxx" where xxxx is the fips code, and the rest of the id can be interpreted by jquery to color-code the regions.  If you look at topojson they have a much smaller file for the US

The example posted in examples is quite laggy and with D3.js and leaflet.js playing in this space, I believe highcharts can do better, and I hope they will because I have hitched my wagon to this solution.
