### ISSUE TITLE
Tooltip decimals max value 9

### ISSUE THREAD

**Issue by CarlaTeo** [highcharts/highcharts#3994]
The parameter 'valueDecimals' of 'tooltip' only takes into account the first digit. If I try 10 decimals it only shows 1.

http://jsfiddle.net/juvcork7/

**Comment by highslide-software** [comment]
The issue lies in [this line](https://github.com/highslide-software/highcharts.com/blob/v4.1.4/js/parts/Utilities.js#L355) that looks only for a single digit for decimal count. It can be changed to `decRegex = /\.([0-9]+)/` to allow more digits, but I am a bit afraid it would break other formats.

As a workaround you can define your own `pointFormatter` callback which calls Highcharts.numberFormat.

```js
    tooltip: {
        pointFormatter: function () {
            return '<span style="color:' + this.color + '">\u25CF</span> ' +
                '<b> ' + this.series.name + '</b>: ' + Highcharts.numberFormat(this.y, 10) + '<br>';
        }
    },
```

[View live demo](http://jsfiddle.net/highcharts/juvcork7/1/).

**Comment by CarlaTeo** [comment]
Thanks, it is a good workaround.
