### ISSUE TITLE
Error on exporting after selection of a column.

### ISSUE THREAD

**Issue by Bewi** [highcharts/highcharts#3997]
First of all, thanks for the awesome product.

I am experiencing an issue when exporting a chart with a lot of data.

Steps to reproduce:
- Set the series with more than 1000 items.
- Select a bar.
- Try to export.

An 'undefined is not a function' exception is thrown.

Issues can also be reproduced using directly getSVG() function with same configuration as explained above.

Here is a live plunker that reproduce the issue : 
http://plnkr.co/edit/cvZ7L30BypFluBmTj2MP

Regards,
Bewi

**Comment by pawelfus** [comment]
Workaround: disable stacking, see: http://plnkr.co/edit/XJ8K7A4hP9VqJhQ1vR2j?p=preview

Looks like `stack.total` isn't calculated when using just one series with many points.

**Comment by pawelfus** [comment]
*Internal Note:*
Minified demo: http://plnkr.co/edit/ycs261Ec9DuEdtfRQNmM?p=preview - in short, configuration object instead of simple value cause this. This is caused by `turboThreshold` option, which didn't check for objects and produces that error. 

The problem is that we change config option for selected point, but that may exceed limitation of default 1000 value for a turboThreshold.

**Workaround:** (better than previous)
http://plnkr.co/edit/s0QVuWajuxWfQADg1EKv?p=preview - disable `series.turboThreshold`

**Comment by pawelfus** [comment]
Connected issue: #2798, however, I'm not sure about the idea behind "stacked columnrange"..

**Comment by abepetrillo** [comment]
Not sure if this helps, but the idea for me behind stacked columnrange is quite useful:

Given a document is created at any point in time, I return the timestamp with a count of one for instance:
```javascript
documents: [
  [1498335107561.1738,1],
  [1498335119284.9721,1],
]
```

Given the graph is over time, and the columns can be stacked different (by specifying the stack number). You would expect that the graph aggregates the documents into one bar with a count of 2, while other series could be stacked independently. An example of actual data can be found here:
http://jsfiddle.net/AbePetrillo/dvx6qaLz/1/

That fiddle was created to demonstrate a different issue where each instance of a series is overlapping eachother instead of showing parallel, but the data is real.

**Comment by pawelfus** [comment]
Hi @abepetrillo 

Maybe I'm missing something, but your chart is not a `"columnrange"` type. In your case, it's a column series with stacking. The issue here is about data format, which causes exporting to fail.
