### ISSUE TITLE
tickInterval is ignored when timezone is enabled

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4034]
Example: 
- http://jsfiddle.net/yk5w27yp/6/
- http://jsfiddle.net/yk5w27yp/7/

**Comment by highslide-software** [comment]
I'm not completely sure what you mean by "ignored", but what I can see that in the first fiddle (the one with `getTimezoneOffset`), we are crossing the DST switched, so actually there are two ticks in a row that fall on Oct 25. The first one on Oct 25 00:00 and the second on Oct 25 23:00. Which in turn means that the tickInterval is actually correct, what what we would expect is that the ticks fall on midnight.

**Comment by VilmaRamos** [comment]
I've found exactly the same problem that @sebastianbochan  described. I think issue #4951 created by @hugomrdias also refers to the same situation.
I understand that the ticks are being arranged in 24 * 3600 * 1000 milliseconds intervals, but when crossing the DST I was expecting that the intervals were adjusted. Since the labels don't display the hour I end up with two identical labels in the x axis. Is there a way to overcome this issue?

**Comment by TorsteinHonsi** [comment]
Thanks for elaborating, see the fix for #4951.
