### ISSUE TITLE
Highcharts series - Invalid negative value for <rect> attribute width

### ISSUE THREAD

**Issue by mmussio85** [highcharts/highcharts#4061]
Hi everyone, when I am trying to render points in a highcharts graphic using setData operation on a graphic wich has timestamps on the xAxis, I get the error that I wrote on the title. First of all I render a point with timestamp equal to now, and after that I want to render points with timestamps previously generated(a lot of years before) , using the sendData method. The problem is that I get an error in the chrome console although the points are shown correctly.

could you help me solve this problem
jsfiddle example http://jsfiddle.net/Yrygy/352/

Thanks
Marcos

**Comment by highslide-software** [comment]
Simplified demo: http://jsfiddle.net/Yrygy/365/

**Comment by highslide-software** [comment]
This seems to happen when the initial value is much lower than the new values.

Your initial X value is some time in 1970. Is that intentional?

**Comment by TaleMasinov** [comment]
I am getting the same error. I have data that spans 30-40 years ago.
Take this example: http://jsfiddle.net/np74kfvc/2/
I am plotting multiple series on two axis that are with irregular intervals. Couple of issues: the axis values do not correspond to the actual values of the data, the lower column chart is elevated for no reason.
If I plot, let's say, 15 series, I get the mentioned error with negative values.
My data can span from 1990 to 2015.

Thanks,
Trajche

**Comment by TaleMasinov** [comment]
Consider also this example: I don't see the errors but the values are not according to the axis.
https://jsfiddle.net/2a33u5kd/

**Comment by highslide-software** [comment]
@TaleMasinov All your series had `compare: "percent"` - was that intensional? So the Y axis on the lower axis was showing the percentwise change from the first value, which is 2. It seems to make more sense without the percentage comparison: https://jsfiddle.net/highcharts/2a33u5kd/3/.

**Comment by TaleMasinov** [comment]
Holy sh**, it works. 
From the examples/demos on the web site, the percent-wise change was shown in the tool tip, I had no idea that it will influence the lower Y axis. 
I was following the "Compare multiple series" example (hence the percentage comparison), and I wanted to combine it with another parallel column chart. I've misunderstood how compare is used.

To answer your question, yes, it was intentional. I wanted to show differences in medication levels at specific time instances.
Do you have an idea on how to show those differences?

Thanks for your help.
P.S. I apologize if I express myself in a wrong manner. I've just started playing with the library.

**Comment by highslide-software** [comment]
Nothing to apologize!

You should set the `compare` option on each series item, where you want them. In your case it would either be on each of the medication series, or generally for all line series using `plotOptions.line`. When setting `plotOptions.series` it applies to all series regardless of type.

**Comment by pawelfus** [comment]
Works fine in 4.2.6: http://jsfiddle.net/Yrygy/587/ and http://jsfiddle.net/np74kfvc/3/
