### ISSUE TITLE
bar chart panning

### ISSUE THREAD

**Issue by alkaabi** [highcharts/highcharts#4077]
I've run into a bug when enabling panning on a Bar chart. Zooming works fine but when holding shift to pan, the axis jumps to a huge value and pans the graph out of view. 

Best explained with the example here: http://jsfiddle.net/z7wz17r1/

**Comment by mhwlng** [comment]
I am trying 4.4.2

If I do this :

zoomType: 'xy',
panning: true,
panKey: 'shift',

now shift mouse drag -> pans up/down 
and mouse drag zooms in both x and y axis (as zoomtype defines).

but I need :

![test](https://cloud.githubusercontent.com/assets/1388886/12817596/13af5b36-cb53-11e5-8abb-a21b8aa174ac.png)

zoomType: 'y',
panning: true,
panKey: 'shift',

now mouse drag zooms only horizontally, across the time axis, which is what I want, so no problem.

But panning is supposed to pan in the same direction (horizontally).
but nothing happens when I do shift mouse drag (in any direction).
