### ISSUE TITLE
Bar chart does not display data label in a certain case

### ISSUE THREAD

**Issue by acki-m** [highcharts/highcharts#4155]
With the newest highcharts version the label of the first column bar is for unknown reason not shown.

TestCase: http://jsfiddle.net/highcharts/8t84oacy/2/
Browser: FireFox & Chrome (Windows 8.1)

Expected result: http://jsfiddle.net/8t84oacy/1/
This works with version 3.0.0

**Comment by highslide-software** [comment]
You can prevent that by adding the `allowOverlap` option: http://jsfiddle.net/highcharts/8t84oacy/6/

But there's another problem - these labels don't really overlap. You don't see it until you add a background: http://jsfiddle.net/highcharts/8t84oacy/6/. Maybe the overlap logic should ignore the padding when a background or border is not used.

**Comment by pawelfus** [comment]
Or maybe default padding should be smaller (or zero)? Adding conditions like "ignore padding, when background/border is not used" will lead to another bug reports.

**Comment by highslide-software** [comment]
> Or maybe default padding should be smaller (or zero)?
No, that would render the labels too close to (or on top of) the point: http://jsfiddle.net/highcharts/LLExL/4490/. The new option would have to be called `margin` or `closestDistance` or something like that, and relate to the box when a box is present, otherwise the bare text. A small thing is that we could tolerate a distance of 0 vertically, but not horizontally. So technically it would be best with an X and a Y component like `closestDistanceX` and `closestDistanceY`.

**Comment by pawelfus** [comment]
Isn't `dataLabels.y` suppose to work that way: http://jsfiddle.net/LLExL/4491/ ? 

Of course, `dataLabels.closestDistance` sounds cool too (like pie chart's `dataLabels.distance`).

**Comment by highslide-software** [comment]
Using `dataLabels.y` works in that case, but not in other cases like [negative columns](http://jsfiddle.net/highcharts/LLExL/4510/) or [inverted charts](http://jsfiddle.net/highcharts/LLExL/4511/). The padding works well for all of these cases.
