### ISSUE TITLE
Panning conflicts with startOnTick/endOnTick

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#4183]
Putting startOnTick/endOnTick on the x-axis conflicts with panning. The scale revers to the original minum/maximum value. 

See http://jsfiddle.net/kzoon/8h1a1gqk/1/
And http://jsfiddle.net/kzoon/hpmf1hvs/3/

**Comment by danieldunderfelt** [comment]
I am also seeing this. It is super-annoying as I need the last tick to be visible and I don't want to show all the data at once (using the `range` property on the xAxis). So once the user starts dragging, the chart slowly resets to showing all the data. Is this possible to fix?

**Comment by pawelfus** [comment]
Hi,

Thank you for your feedback. Problem with current implementation is that `startOnTick` and `endOnTick` options are looking for the next tick outside the range. That cause "snapping" to the higher extremes during panning. Maybe option like `showLastTick` and `showLastTick` would resolve that issue? Of course, that tick-labels won't be nicely rounded anymore.

The good thing: we can modify those tick positions using [`xAxis.tickPositioner`](http://api.highcharts.com/highcharts#xAxis.tickPositioner). For example: http://jsfiddle.net/5ahs8jo0/

The only problem with that solution is that we can not exactly say which labels/ticks should be hidden or those ticks will overlap. It's not an universal solution, but should work in most cases: if ticks is in a halfway to the next tick, it should be hidden (`distance = 0.5` param). You can modify that param to fit your requirements.

**Comment by danieldunderfelt** [comment]
Hi, thanks for the fiddle! It didn't really work though as it left gaps in the ticks. More on my use case:

My xAxis is of type datetime, and I'm using Highstocks. My graph shows analytics data, so this can go back quite some time, so I don't want to show everything at once. I can limit the visible data with the range setting, but when my graph is not scrolled, ie it is showing the newest data and can be panned to the left, the last tick is not visible. This is very annoying as the newest data point date is first of July, but "July" is not shown on the xAxis.

I am also using the xAxis labels for other things in my UI so it is crucial that the tick for the newest data point is visible. If the user scrolls the graph I don't care, but in an uninteracted state I really need it to show.

The issue is of course that using `endOnTick` screws up the panning, which I also really need. Why is Highcharts hiding the last tick if the data includes it?

**Comment by pawelfus** [comment]
Thank you for the detailed description. Unfortunately, in Highstock, [`startOnTick`](http://api.highcharts.com/highstock#xAxis.startOnTick) is always set to false (and the same for `endOnTick`), so even if this bug will be fixed, I can't promise behaviour change in Highstock. 

It's not like Highcharts/Highstock hides the last tick, but default tick positioner calculates nice (for humans) ticks positions, and last point may not be exactly on this "nice position". 

If you could create a jsFiddle with your use-case, then we may be able to provide a better `tickPositioner` for your case.

**Comment by danieldunderfelt** [comment]
Hmm, that's weird, as `endOnTick` definitely works if I enable it. It just messes up the axis range when panning. I'll try with some conditionals in `tickPositioner` to see if I can force the last tick to show only if the chart isn't panned or scrolled and act normally if the user does those interactions.

A related thing is that using the scrollbar doesn't mess up the axis range when `endOnTick` is enabled. So if panning could act like the scrollbar, or if there could be an API to enable programmatic panning/scrolling, that could solve my problems. Also, is there a way to get the current scroll position? Or some condition that I can check as outlined in the paragraph above?

Thanks for all your help!

**Comment by danieldunderfelt** [comment]
Yes, this tickPositioner works perfectly for my usecase:

```
tickPositioner(min, max) {
  const ticks = this.tickPositions
  const dataMax = this.dataMax

  if(max === dataMax && ticks[ticks.length - 1] !== max) {
    ticks.push(max)
  }
   return ticks
}
```

So if the max tick is equal to the last datapoint in my series, and if the tick isn't already in the array, add it. If not, don't bother.

It still feels like a hack, whereas `endOnTick` would be a perfect solution without the range resetting bug.

**Comment by WizardCM** [comment]
Ran into this issue myself too - panning automatically zooms out as you try and pan until the tick you've enabled fits in the view. Very unpleasant to use and defeats the point of both options.
