### ISSUE TITLE
Flags are not considered when laying out the chart

### ISSUE THREAD

**Issue by eolsson** [highcharts/highcharts#419]
When flag series are used in stock chart, only the anchor point of the flag is used when calculating the layout and padding, not the height of the flag. The result is that the flag is drawn outside of the chart or just at the edge.

As seen in this example: http://jsfiddle.net/highcharts/fdRmK/13/
Forum thread: http://highslide.com/forum/viewtopic.php?f=12&t=12112

**Comment by mykbaker** [comment]
This bug was reported in 2011 and I am still facing this issue today. When your user is determining the amount of text used in the flag it is very hard to work around this issue. Is there a plan to get this fixed? Is there some ability to wrap the content of the flag to give it a static size so you can work around this issue?

**Comment by pawelfus** [comment]
It is possible to set fixed width for a flag, but it won't directly help, take a look: http://jsfiddle.net/fdRmK/21/

Workaround: add a simple overflow method to check left/right edge and translate a flag, demo: http://jsfiddle.net/fdRmK/23/ (and http://jsfiddle.net/fdRmK/24/ )

**Comment by mykbaker** [comment]
This is great, I will try this. Thanks for the help!

**Comment by Izothep** [comment]
It looks that above example is moving the connector path as well. I have prepared another workaround that will move only point's label:
https://jsfiddle.net/BlackLabel/z98vo3fc/1/

**Comment by dev-katiyar** [comment]
Try this https://api.highcharts.com/highstock/plotOptions.flags.clip
