### ISSUE TITLE
Axis title cropped instead of wrapping

### ISSUE THREAD

**Issue by cvillemure** [highcharts/highcharts#4205]
See jsFiddle : http://jsfiddle.net/yj4q7t1s/

I have tried to inject HTML to force a wrapping whitout success. I have not seen any documentation related to that problem.

**Comment by highslide-software** [comment]
We could implement wrapping by adding this code at https://github.com/highslide-software/highcharts.com/blob/v4.1.5/js/parts/Axis.js#L1728.
```js
			if (!axisTitleOptions.rotation && !axisTitleOptions.style.width) {
				axis.axisTitle.css({ width: (axis.horiz ? chart.plotWidth : chart.plotHeight / 3) + PX });
			}
```

For a proper implementation, the following should be considered:
* It should also work well for vertical axis with rotation = 0. Currently it is wrapped correctly, but the text block is aligned too far to the right.
* Users should be allowed to override the wrap/ellipsis width by setting `style.width`.
* Users should be allowed to set `textOverflow: ellipsis`, but this doesn't work on horizontal axis, probably because a `width` is incurred.

**Comment by cvillemure** [comment]
The closest I got to something "acceptable" is the following :

**Comment by cvillemure** [comment]
After a few tests, with the width/height of the chart, it seems the -20 does not work for all conditions (very small charts with very long axis title)

**Comment by cvillemure** [comment]
I got a better implementation after a few more tests :
```
if (!axisTitleOptions.style.width && (!axisTitleOptions.rotation || (axisTitleOptions.rotation === 270 && !axis.horiz))) {
	var maxWidth = 0;
	
	if(axis.horiz) {
		maxWidth = chart.plotWidth - chart.axisOffset[3];
	} else {
		maxWidth = chart.plotHeight;
	}
	
	if(maxWidth && maxWidth > 0){
		axis.axisTitle.css({ width: maxWidth + PX });
	}
}
```

However when the y Axis title is wrapping it is pushed to the right, overlapping with the axis labels and creating a gap to the left of the chart...

**Comment by KacperMadej** [comment]
In (at least) version 6.1.4 the wrapping is implemented.

http://jsfiddle.net/yj4q7t1s/

Closing as resolved.
