### ISSUE TITLE
Unable to pull all points on same xAxis within tooltip

### ISSUE THREAD

**Issue by JamesDonnelly** [highcharts/highcharts#4263]
I've just asked the following question on Stack Overflow: http://stackoverflow.com/q/30646709/1317805. I figured it's possibly a bug though, and couldn't find anything similar here.

In short, if I have two points on a line chart on the same series which share the same xAxis value, Highcharts seems to ignore the existence of the former point. This bug is greatly amplified when enabling `allowPointSelect`, as this shows that it's impossible to even select the former point: http://jsfiddle.net/h11xfs5L/3/

![Example](http://i.stack.imgur.com/yVGVF.png)

**Comment by highslide-software** [comment]
It happens because line series indexes the tooltip positions by the X position, in order to be able to read the values of one series as you follow it along with the mouse, and also because shared tooltips look for points with the same X.

The workaround is to use a scatter series instead: http://jsfiddle.net/highcharts/h11xfs5L/19/

**Comment by pawelfus** [comment]
Since v5.0.10 this can be achieved by setting [`findNearestPointBy`](https://api.highcharts.com/highcharts/series.line.findNearestPointBy) to `"xy"`, demo: http://jsfiddle.net/BlackLabel/h11xfs5L/21/
