### ISSUE TITLE
Bubble: opacity of fillColor not applied for states when using rgba color format

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4278]
It is not possible to set opacity / alpha for fillColor in e.g. select state.
Example: http://jsfiddle.net/j0hoz4oz/

Only when marker fillOpacity is set to 1, then rgba colors can influence opacity.
Example: http://jsfiddle.net/j0hoz4oz/1/

**Comment by highslide-software** [comment]
Since there's an easy workaround (set fillOpacity to 1 and then apply all opacities on the fillColors), I think a fix is not urgent here. It is also a question of what option should take precedence over the other, so it is not clear that it's a bug. 

The same problem goes deeper and appears in other situations, for example with rgba color and fillOpacity on area charts: http://jsfiddle.net/highcharts/m4y3svxe/. So if we fix this, we should inspect all cases and make a general fix.
