### ISSUE TITLE
Highstock animation for multiple series with different x-values

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#4288]
Simply animation is missing: http://jsfiddle.net/yy9t04wd/3/

When using second dataset (the same x-values for **all** of the points), it works fine: http://jsfiddle.net/yy9t04wd/4/

**Comment by highslide-software** [comment]
It comes from the fix for #2998

**Comment by highslide-software** [comment]
The animation is stopped in Highstock's [overwrite of the Series.render method](https://github.com/highslide-software/highcharts.com/blob/v4.1.6/js/parts/StockChart.js#L587), where the series are redrawn.

The redraw is triggered by [this block in Scroller.js](https://github.com/highslide-software/highcharts.com/blob/v4.1.6/js/parts/Scroller.js#L318-L324), because the extremes of the union of all series is different than the initial extremes of the first series.

**Comment by pawelfus** [comment]
Works in 4.2.5+
