### ISSUE TITLE
Rendering issue when removing points from multiple series (Highstock)

### ISSUE THREAD

**Issue by kpau** [highcharts/highcharts#4312]
Hello,
I am using StockChart, with this data:

``` javascript
data: {
    firstRowAsNames: false,
    columns: [
        [Date.UTC(2014, 0), Date.UTC(2014, 1), Date.UTC(2014, 2), Date.UTC(2014, 3), Date.UTC(2014, 4), Date.UTC(2014, 5), Date.UTC(2014, 6), Date.UTC(2014, 7), Date.UTC(2014, 8), Date.UTC(2014, 9), Date.UTC(2014, 10), Date.UTC(2014, 11)],
        [-9, -5, -3, 1, 3, 6, 8, 8, 3, -2, -3, -16],
        [1, 6, 9, 11, 14, 18, 21, 22, 17, 11, 7, 1]
    ]
}
```

When I first remove data from one of the series, redraw, and after that remove data from the other series, there is a rendering issue.
If I remove data from both series and then call redraw(), there is no problem.

See the example: http://jsfiddle.net/eb05uycu/3/
After clicking 'Remove Data at the same time' everything is fine - the first 6 points from both series are removed, and the chart is correctly rendered.
When I click 'Remove Data individually', again the first 6 points from both series are removed, but the chart fails to render correctly. Series 1 is correctly rendered from July 2014 to Dec 2014, but Series 2 spans from Jan 2014 to Dec 2014. When I hover the points, the data seems correct, but not placed correctly. When I re-size the view, the chart is rendered correctly.

If I use regular Chart object (instead of StockChart) everything works fine.

Am I doing something wrong, or this is Highsock issue?

Best regards,
Kristiyan Nikolov

Edit: I found a workaround - adding `chart.setSize();` after the second `chart.redraw();` the issue is fixed. But still, I think there is a problem somewhere.

**Comment by vickychijwani** [comment]
Another workaround is to call `chart.reflow()` after the second `chart.redraw()`, as in http://jsfiddle.net/vickychijwani/eb05uycu/4/. But there definitely is an issue.

**Comment by pawelfus** [comment]
Funny fact: if base series for navigator is update as the last one, everything works properly: http://jsfiddle.net/eb05uycu/5/

Or disable `ordinal` axis: http://jsfiddle.net/eb05uycu/6/ - now navigator is one redraw behind, but we can predict what happens:

- base series (and navigator) removes points: navigator extremes won't change because of the second series (so far so good)
- second series is updated - extremes don't change because navigator is connected to the base (first) series which doesn't change, so extremes (unionExtremes) fails to update (and that's the reason why updating first series as last one prevents from the bug).
