### ISSUE TITLE
Tooltip is seen even after hiding series from interactive legends.

### ISSUE THREAD

**Issue by pawanvjadhav** [highcharts/highcharts#4375]
Please check URL : http://jsfiddle.net/pawanvjadhav/3oc8Lyca/5/
We have observed this only in case of 3D View. 
Step 1 Move mouse over the bar, it will show you tooltip.
Step 2 take mouse over legend. Tooltip is still available.
Step 3 hide series using legend. Tooltip is still available.

Tooltip should get hidden once you mouse over on Legend or when you hide bar using legend.

I tried to resolve this using hideDelay but couldn't

**Comment by pawelfus** [comment]
It's caused by shared tooltip, which finds closest point to the mouse position. Simple workaround is to set `shared: false`, demo: http://jsfiddle.net/3oc8Lyca/6/

**Comment by highslide-software** [comment]
It is probably the same case as [this demo](http://jsfiddle.net/highcharts/3oc8Lyca/7/), where the legend is covered by the tooltip and is totally unreachable.

**Comment by pawanvjadhav** [comment]
I want to keep shared:true as my charts contains multiple series and some of the charts are Stacked Bar Chart.

**Comment by sebastianbochan** [comment]
Workaround: 

When you disable shared, you can use formatter and loops inside to list all points with the same x. 
Example: http://jsfiddle.net/3oc8Lyca/9/

**Comment by pawelfus** [comment]
@highslide-software I think those are separate cases: one is unreachable legend, and one is visible tooltip **after** hiding series. [This line](https://github.com/highslide-software/highcharts.com/blob/f8baa47656bf50e3b3d281e79a5ca62022e4761a/js/parts/Interaction.js#L661) is responsible to hiding tooltip. 

I think in case of shared tooltip, we should refresh tooltip instead, otherwise we can see points from the series which are hidden after hiding the legend: http://jsfiddle.net/3oc8Lyca/10/
