### ISSUE TITLE
Datalabels - color

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4382]
Some colors like #ff0000 works properly, but for example: #58D58D enable shadow defaulty. Morever setting param shadow as false, has no influence.

Examples
- http://jsfiddle.net/mfyamr3z/1/ incorrect
- http://jsfiddle.net/mfyamr3z/2/ correct

Workaround: set useHTML as true.

**Comment by pawelfus** [comment]
It's not `dataLabels.shadow` but `dataLabels.style.textShadow` see: http://jsfiddle.net/mfyamr3z/3/

**Comment by sebastianbochan** [comment]
Anyway it should be stable, for all colors there should be shadow or not. 

Internal note: (for red color, there is shadow, but white)

**Comment by gvaartjes** [comment]
Apparently the drop shadow to make the datalabels more clear for colours with less contrast isn't checking the textShadow property.

**Comment by highslide-software** [comment]
The text shadow for http://jsfiddle.net/mfyamr3z/1/ is technically correct. Bright text color gives a dark shadow, and dark text color gives a bright shadow. As long as the text is either dark or bright, this makes the text more readable. The problem is with semi-dark colors. In the fiddle, it gives a black text shadow, which is semi-transparent and becomes gray, so it all becomes a mess.

In this case a tighter shadow would be better, but still a white one would be the best: http://jsfiddle.net/highcharts/mfyamr3z/4/

**Comment by KacperMadej** [comment]
Currently (version 5.0.10) is providing better contrasts and `textOutline` is the style options that should be used instead of `textShadow`, so the issue seems to be resolved. Please reopen in case of a bug.
