### ISSUE TITLE
Maps with multiple Y axes - incorrect datalabels position

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4462]
Example: http://jsfiddle.net/5oqnndm7/10/

**Comment by highslide-software** [comment]
Thanks for reporting, but please remember to strip down the demos more. By removing code, I quickly saw that the problem persists even after removing drilldown. The problem comes from defining y axis as an array: http://jsfiddle.net/5oqnndm7/11/. When defining it as an array, the merging gets wrong, and it is [not reversed as it should be](https://github.com/highslide-software/highcharts.com/blob/master/js/parts-map/Map.js#L153). 

####Workaround
Set `reversed: true` on all Y axes. [View live jsFiddle](http://jsfiddle.net/5oqnndm7/12/)
