### ISSUE TITLE
Highstock: setTitle overlays rangeSelector's buttons

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4466]
When setTitle is called, rangeSelector's buttons are not re-positioned - they are overlaying new title.
Example: http://jsfiddle.net/nL93ko7e/1/
Click button to setTitle.

**Comment by GeoffreyOfficial** [comment]
Hi, I already have an issue, in fact this is worst that before, what I have before:
![before](https://cloud.githubusercontent.com/assets/10940946/9269597/84a06ae0-426b-11e5-9d4e-ff79d2b65f88.PNG)

What I have after:
![after](https://cloud.githubusercontent.com/assets/10940946/9269598/84a3c438-426b-11e5-86ae-f439231be337.PNG)

**Comment by highslide-software** [comment]
I think the issue with the input elements may have been fixed earlier in the dev branch. Check out http://jsfiddle.net/highcharts/nL93ko7e/2/, and try the latest file from GitHub with your project.

**Comment by GeoffreyOfficial** [comment]
Ok ! but (always a but ^^). I have a context and custom button, I added it on your example, here what happend:
http://jsfiddle.net/nL93ko7e/3/
So what I did by myslef is change the rangeselector position like this:
http://jsfiddle.net/nL93ko7e/4/
This is cool ! but now try to add the title and see my problem :)

So maybe the issue is from exporting module

**Comment by highslide-software** [comment]
Okay, so there are two problems - first the range selector and then the exporting buttons.

The **range selector** in your case is fixed because you have set a specific y position, thereby overriding the dynamic default. In [this fiddle](http://jsfiddle.net/highcharts/nL93ko7e/5/) it is left to Highstock to decide.

The **exporting buttons** is a different story, they are not designed to respond to the title at all, as you can see in [this fiddle](http://jsfiddle.net/highcharts/nL93ko7e/6/). Probably you need to access them through the DOM or jQuery and move them programmatically.

**Comment by GeoffreyOfficial** [comment]
Ok this is sad then ... I don't have the skill for this, I think, maybe that I will create an UserVoice and hope.
Thank you for your support !

**Comment by highslide-software** [comment]
> I don't have the skill for this

Okay, I'll give it a try, hang on...

**Comment by GeoffreyOfficial** [comment]
ok thank you !

**Comment by highslide-software** [comment]
Is this something you can use? You may have to toggle the pixel positions a bit:  http://jsfiddle.net/highcharts/nL93ko7e/8/

**Comment by GeoffreyOfficial** [comment]
Wow you are a monster !
This is very good ! I just changed "+16" by "+13" for center the text's button with the range selector :)

In the beginning I didn't see that you added a theme .... ^^

Thank you very much

**Comment by highslide-software** [comment]
You're welcome, glad to help!

**Comment by GeoffreyOfficial** [comment]
Oh .... sorry finally there is an issue, because when I change the size of the window (you can see it also on jsfiddle), the buttons comeback on the default position :'(

I tried something like this, but this doesn't work ...
http://jsfiddle.net/nL93ko7e/9/

**Comment by GeoffreyOfficial** [comment]
I did something like that:
http://jsfiddle.net/nL93ko7e/10/
But this is not the best thing to do i guess :/

**Comment by GeoffreyOfficial** [comment]
Sory but I don't think that this is close but even if you don't look at the exporting buttons ... There is an issue when you add subtitle after that you added title, please take a look here:
http://jsfiddle.net/nL93ko7e/11/
Click Change, then click Change2

**Comment by highslide-software** [comment]
Yes, you're right.

1. Open http://jsfiddle.net/highcharts/nL93ko7e/12/
2. Click "change" multiple times.
3. Observe that the range selector only moves the first time

**Comment by GeoffreyOfficial** [comment]
Awesome support, waiting for the fix.
Thanks

**Comment by KacperMadej** [comment]
Working fine since 5.0.0.
Demo: http://jsfiddle.net/nL93ko7e/24/
