### ISSUE TITLE
Labels in a logarythmic xAxis overlay each other when custom label's format is set

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4467]
Examples: 
http://jsfiddle.net/hdsq6g9n/
http://jsfiddle.net/hdsq6g9n/1/

**Comment by highslide-software** [comment]
Probably the problem lies in the `Axis.unsquish` method, where the tickInterval used for determining collision is not the same as the smallest tick interval in a log axis (since the intervals are not consistent).

Here's a POC for a fix, which finds the smalles interval: http://jsfiddle.net/hdsq6g9n/2/

**Comment by GeoffreyOfficial** [comment]
Hi,
Thank you for your help, I get an error with this jsfiddle: "ReferenceError: Highcharts is not defined".
So I can't see the result of your method :(
Can you fix it, please ? =)

**Comment by highslide-software** [comment]
Here you go: http://jsfiddle.net/highcharts/hdsq6g9n/3/

**Comment by GeoffreyOfficial** [comment]
Hi, thanks, can be cool, but I have more issues now ^^

Please take a look of this jsfiddle: http://jsfiddle.net/rt1zjzdw/5/
1. You will see a bug, like there is not xaxis
2. Leave your axis.unsquish method
3. Refresh, you will see that there is no issues BUT, now try to zoom on the graph ... then the zoom is wrong
4. Firebug told me this: "Valeur Infinity inattendue lors de l'analyse de l'attribut x.", mean approximatly in english: "Unexpected infinity value when checking of the x attribut"

Any idea ?

**Comment by highslide-software** [comment]
There seems to be a bug with log axis and the minRange option. See #1227. You can remove your minRange option to work around it.

**Comment by GeoffreyOfficial** [comment]
Thank you for your awesome support, but I already get big issues. I left the minRange value, but like you can see here: http://jsfiddle.net/rt1zjzdw/7/
1. You will see a bug, like there is not xaxis
2. Zoom and Reset zoom
3. This is ok but apparently Axis.unsquish is doing nothing because I get overlay
4. Now Try to zoom, this is working !
5. Now reset zoom ... BUG !
6. Then try to zoom on this blank chart and reset zoom, the chart come back 


I don't know if this important but I already get "Unexpected infinity value when checking of the x attribute"

**Comment by highslide-software** [comment]
Yes, I think this demonstrates that my workaround for the unsquish is not a good approach... But the minRange issue persists.

**Comment by GeoffreyOfficial** [comment]
Ok thank you for your help for this issue, too.
I will wait for a fix, so =)

**Comment by GeoffreyOfficial** [comment]
I also post this uservoice yesterday... this is not exactly the same thing but there is a link, i guess
https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/9307287-range-selector-and-logarithmic-axis
