### ISSUE TITLE
Bubble chart - wrong negative color when hover

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4508]
1) run the example: http://jsfiddle.net/g1a1f3cj/
2) hover on negative value (gray)
3) gray point changes to blue, but should not

**Comment by pawelfus** [comment]
`Internal notes:`

- `point.negative` is wrong, because we should use `zoneAxis` or at least `z` value for checking this
- above will work after adding #3636 fix
- issue with border remain, and here is tricky part: we want this border color change only for bubble series? We would need to duplicate [this line](https://github.com/highslide-software/highcharts.com/commit/4e9821d610b2467f86cc15ed8029a7b9ee3dad35#diff-935901c6fb72a4ef40f8fc0977cb59bdR1154) to do the same for border..

**Comment by pawelfus** [comment]
Snippet for the second point (above): 

    diff --git a/js/parts-more/BubbleSeries.js b/js/parts-more/BubbleSeries.js
    index 75a08d9..8c96b4c 100644    

    --- a/js/parts-more/BubbleSeries.js
    +++ b/js/parts-more/BubbleSeries.js
    @@ -158,7 +158,8 @@ seriesTypes.bubble = extendClass(seriesTypes.scatter, {
                            data = this.data,
                            point,
                            radius,
    -                       radii = this.radii;
    +                      radii = this.radii,
    +                      threshold = this.options.threshold;
                
                    // Run the parent method
                    seriesTypes.scatter.prototype.translate.call(this);
    @@ -186,6 +187,7 @@ seriesTypes.bubble = extendClass(seriesTypes.scatter, {
                                        width: 2 * radius,
                                        height: 2 * radius
                                };
    +                          point.negative = point.z < (threshold || 0); // #4508
                        } else { // below zThreshold
                                point.shapeArgs = point.plotY = point.dlBox = UNDEFINED; // #1691
                        }

**Comment by sebastianbochan** [comment]
Fixed from v5.0.2.

http://jsfiddle.net/d9L0rmcz/
