### ISSUE TITLE
Highcharts.dateFormat support for timezone

### ISSUE THREAD

**Issue by stevesouders** [highcharts/highcharts#4548]
Highcharts.dateFormat("%T") does NOT return the timezone. I notice the documentation says "The format is a subset of the formats for PHP's strftime function". Unfortunately, dateFormats() is not a workaround since that is an epoch time so any timezone information is lost. Instead, it would be great if "%T" was supported.

**Comment by highslide-software** [comment]
Thanks for the input! As far as I know you can't set the timezone offset of a date object in JavaScript, so you're stuck with the time zone of the client machine. 

In order to provide that information we could extend the dateFormat function to take Date objects in addition to timestamps, but I'm not sure of the value since all dates have the client machine's timestamp?  Or am I missing something?

**Comment by jon-a-nygaard** [comment]
Closing this as it is pending a reply. Should anyone have further information on the issue, please give us a comment.
