### ISSUE TITLE
boost module - missing click event on point

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4569]
In case when tooltip is triggered on point (hover action) I think that click event should also be supported. But im not sure how this has influence on performance.

Example: http://jsfiddle.net/1an32kj8/

**Comment by pawelfus** [comment]
Workaround:

Make sure you have enabled `halo`, then make that halo clickable: 

        plotOptions: {
            series: {
                point: {
                    events: {
                        click: function () {
                            alert('a');
                        },
                        mouseOver: function() {
                            if(this.series.halo) {
                                this.series.halo.attr({
                                   'class': 'highcharts-tracker' 
                                }).toFront();   
                            }
                        }
                    }
                }
            }
        },

Demo: http://jsfiddle.net/1an32kj8/1/

**Comment by asdeepak49** [comment]
Hi,

I have seen your demo in the JSFiddle,Most of the time click event is not getting Called.

**Comment by pawelfus** [comment]
It is, just make sure you are clicking on the hovered point (halo).

**Comment by sebastianbochan** [comment]
Related with support click event, allowPointSelect seems that also not working.

**Comment by allanino** [comment]
I found this workaround doesn't work properly with multiple series. If at least one series have more than 5000 points, it will only fire events for the last series.

Here is a demonstration: http://jsfiddle.net/tch4qd2c/

**Comment by pawelfus** [comment]
Thanks, the problem is that every series is rendered on a separate canvas. Unfortunately, I don't see any better workaround at this moment. Disabling halo, and rendering your own halo may work (simple example [here](http://stackoverflow.com/questions/15152738/highcharts-highlight-mouse-position-within-a-range/15158110)).

**Comment by TorsteinHonsi** [comment]
We are not working on a rewrite of the Boost module - among other things we are drawing all series on one canvas. @cvasseng

**Comment by KacperMadej** [comment]
+1

**Comment by StefanJelner** [comment]
Ran accross the same problem. The halo-workaround didn't work for me, because i wanted to get the click event for the recently highlighted point, even if it is not directly clicked. Highcharts has the ability to highlight the nearest point if you point anywhere on the chart. My workaround is, to use the tooltip formatter to store the x value away and then use it on the global click event for the chart.

See the fiddle:

http://jsfiddle.net/n50vdvdv/8/

This should also work for Version 6.

**Comment by callumacrae** [comment]
@StefanJelner's approach of using the tooltip formatter combined with some algebra worked for me - would be really nice if this were fixed for multiple series though!

**Comment by burtyish** [comment]
I believe this is still unresolved.
Will posting here reopen the issue?

https://codepen.io/burtyish/pen/eYZzvzE?editors=1111
