### ISSUE TITLE
Erratic alignTicks behaviour

### ISSUE THREAD

**Issue by kzoon** [highcharts/highcharts#4580]
Using alignTicks on charts with a second y-axis regularly results in a too high max on both axes. In this fiddle http://jsfiddle.net/w4bLu5jf/6/ I plotted the same data on both y axes. 

With alignAxis set to false the max is 125 on both axes (as set in the options). 
With alignAxis set to true the max is 200 on both axes.

Weird thing is that the issue only exists when the max on both axes is set explicitly.

**Comment by highslide-software** [comment]
_Internal note_

This happens because when aligning ticks, we first set the `tickAmount` internally, then compute the ticks from there. 

One possible solution could be to allow more fine grained axis in case when tickAmount/alignTicks is set. So [the allowed multiples](https://github.com/highslide-software/highcharts.com/blob/v4.1.9/js/parts/Utilities.js#L459) can be dynamically extended to for example 
```js
multiples = [1, 1.2, 1.5, 2, 2.5, 3, 4, 5, 6, 8, 10];
```

We should also consider the `chart.alignTicks` option to default to a best guess, so that if there is a user setting for axis min, max, tickInterval, tickPixelInterval etc. it defaults to false. In that cases, gridLineWidth on secondary axes should default to 0.

**Comment by kzoon** [comment]
Any progress on this?

**Comment by TorsteinHonsi** [comment]
All right, time to put an end to this. I'll implement the suggestion above.
