### ISSUE TITLE
"no data to display" dosesn't hide after adding points to treemap

### ISSUE THREAD

**Issue by christopher-szu** [highcharts/highcharts#4631]
http://jsfiddle.net/vjpduav0/7/

the "no data to display" text does not hide after adding points to a initially empty treemap,

i've made the treemap transparent so it is easier to see the problem

in the original no-data-to-display demo with pie chart, the text does go away

http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/no-data-to-display/no-data-pie/

**Comment by highslide-software** [comment]
@jon-a-nygaard The no-data module gives each series type a `hasData` method. The tree map probably hasn't got the right one. 

PS: Remember to add a unit test for regression.

**Comment by jon-a-nygaard** [comment]
This issue will be fixed in an upcoming maintenance release. For those in need of a workaround can try the suggested below.

**Workaround:**
Open `no-data-to-display.src.js` and replace the following code which is located around line 55.
```javascript
// Replace this code
each(['pie', 'gauge', 'waterfall', 'bubble'], function (type) {
	if (seriesTypes[type]) {
		seriesTypes[type].prototype.hasData = hasDataPie;
	}
});

// With this code
each(['pie', 'gauge', 'waterfall', 'bubble', 'treemap'], function (type) {
	if (seriesTypes[type]) {
		seriesTypes[type].prototype.hasData = hasDataPie;
	}
});
```
Also remember to load the `no-data-to-display.src.js` after `treemap.src.js`
