### ISSUE TITLE
Datetime x-axis doesn't render correctly with horizontal line

### ISSUE THREAD

**Issue by JGulbronson** [highcharts/highcharts#4646]
Setting the xAxis type to "datetime" causes the ticks to be inconsistent. 

Example at http://jsfiddle.net/116kLwe4/

Remove the line that sets the type for the xAxis, and you'll see that the ticks are evenly spaced, as expected. However, if you don't, you'll see that January 1st is the only label displayed.

**Comment by pawelfus** [comment]
Possible workaround: http://jsfiddle.net/116kLwe4/1/ - set `minTickInterval`. Default value is the same as distance between two closest points, so in the case above, distance is the same as plotting width.

**Comment by JGulbronson** [comment]
Interestingly enough, setting `minTickInterval` to 0 fixes the problem as well, almost like it negates the fact it's a 'datetime' series

**Comment by highslide-software** [comment]
The responsible line is here: https://github.com/highslide-software/highcharts.com/blob/v4.1.9/js/parts/Axis.js#L1053.

The rationale is that if `minTickInterval` is not set explicitly, we do a best guess based on the distance between the point. Because for example when the implementer adds one point a month, he or she wouldn't expect ticks to appear every week. 

But I admit that in this specific case it doesn't work very well.
