### ISSUE TITLE
Height and width inside a flex container

### ISSUE THREAD

**Issue by antonpod** [highcharts/highcharts#4649]
When there's more than one element inside a flex container, width and height don't shrink when changing window size.
[flex-direction:row demo](http://jsfiddle.net/fk4Jr/13/)
[flex-direction:column demo](http://jsfiddle.net/fk4Jr/14/)

**Comment by highslide-software** [comment]
Apparently the fix for #1149, adding a 100% with for the inner container and the SVG, also works for flex box width, but not height: 
* [flex-direction:row fixed](http://jsfiddle.net/highcharts/fk4Jr/15/)

**Comment by leilanimng** [comment]
Is there a workaround for the height issue in the meantime?

**Comment by lwhorton** [comment]
I've had success putting `height: 0` on the parent that has something like `flex: 1 1 50%`, and making sure the chart-container has `overflow: hidden`.

```html
<div id="parent"> // flex-sized, but height 0
  <div id="chart-container"> // flex 1, overflow hidden, display flex
   <div id="chart"> // flex 1, overflow hidden
```
And this seems to work (in Chrome) in all cases. It gets really tricky when mixing flex and width/height, since they're not really meant to work together.

**Comment by leilanimng** [comment]
Thanks so much for your response!!! Could you provide an example on jsFiddle? I can't seem to get this to work.

**Comment by pedroteixeira** [comment]
I also had it working by using height:100% on the "chart-container", which was under a flexed item.

For some reason height:0 did not work for me (but I had to use width:0 for some cases so flex layout does not use the child content).

**Comment by astriskit** [comment]
Issue with the height came across when tested app in Chrome( latest 64.0 ). The highchart container won't fit inside the parent. It would just overflow (not like scrolling but grew bigger than parent container). The structure of html can be represented as follows (.flexed_item is a child of div with display set to flex) - 

.flexed_item{ width: 100%; height: 100%;} -> .chart-container{ width:100%; height:80%} -> .highchart

This thing was working fine in firefox. But not in chrome.
But as commented by @lwhorton , I changed it to ->

.flexed_item{ height: 0; width:100%; flex: 1 1 100%; display: flex; }-> .chart-container { flex:1; display:flex; } -> .highchart

And now it is working in both ( chrome and firefox ) finally.

**Comment by dabalyan** [comment]
I solved it using `absolutely` positioned `chart-container` and a `relatively` positioned parent with `flex-grow: 1`.  And there's no hack involved so it's cross-browser compatible
```html
<div id="row" style="display:flex">
    <div id="parent" style="display:flex; flex-direction: column;">
        <div id="chart-container-outer" style="flex-grow:1">
            <div id="chart-container" style="position:absolute; left:0; top: 0; bottom:0; right:0; overflow:hidden"></div>
        </div>
    </div>
    
    <div id="parent-sibling" style="display:flex"> // same height
    </div>
</div>
```

**Comment by KacperMadej** [comment]
@dabalyan 
Thank you for sharing your solution.
Using the above code seems to resolved the problem, so closing the issue for now.
If you would like to see this issue reopened please provide more info about the case.

**Comment by maitrivasa** [comment]
Hi,

I am having a similar issue and the above solutions dint work or I am not implementing those properly.
Here is a demo -->
https://stackblitz.com/edit/angular-wftxkw?embed=1&file=src/app/app.component.ts

Context: I am trying to create 3 charts on 1 row (each has a minimum width) such that on window resize, the charts should also resize and may go to the next row depending on the browser total width.

Problem: Currently, I am missing something in the CSS because the chart is overflowing within the demo container below. The tooltip looks fine, but only half of the chart is seen in the container and both the axes are also hidden. If the screen is not big enough, the charts can go to the next row. Also, on resize of the window, the highchairs should resize up to its minimum width

P.S. In the code below, highcharts-container is the inbuilt div that contains the charts. I am using the latest version of Highcharts and Angular 7.

**Comment by sebastianbochan** [comment]
Hi @maitrivasa,
I see that you created also a separate case here: https://github.com/highcharts/highcharts/issues/13303. 

ps. please do not duplicate your comments and subjects, because of confusing.

**Comment by maitrivasa** [comment]
I am sorry. I have removed my post now
