### ISSUE TITLE
Only first and last label is rendered when plotting big number of data

### ISSUE THREAD

**Issue by yplakosh** [highcharts/highcharts#4683]
The issue occurs on big number of data and certain viewport width.

Highcharts 4.1.9, viewport width 900px (problem - missing labels):
http://jsfiddle.net/wrhv2ym1/

Highcharts 4.1.9, viewport width 1500px (no issues - all labels are present):
http://jsfiddle.net/7Lsd578b/

Highcharts 4.1.8, viewport width 900px (different behavior - part of labels is still missing to prevent overlapping):
http://jsfiddle.net/yLs4bn88/

I would like all labels to be present for any viewport width. In this case I can control labels to be rendered with step option.

**Comment by pawelfus** [comment]
Responsible [commit](https://github.com/highslide-software/highcharts.com/commit/17f1dbd).

**Comment by highslide-software** [comment]
Simplified demo: http://jsfiddle.net/highcharts/wrhv2ym1/2/

**Comment by pawelfus** [comment]
Workaround for 4.1.9: use `xAxis.tickPositioner`, example: http://jsfiddle.net/wrhv2ym1/3/

            tickPositioner: function(min, max) {
                var ticks = [];
                
                while(min < max) {
                 	ticks.push(min);
                    min += 1;
                }
                
             	return ticks;   
            }

**Comment by highslide-software** [comment]
Connected to #3971

**Comment by highslide-software** [comment]
Apparently, the #3971 connection is just a side effect, the real issue is with [these lines](https://github.com/highslide-software/highcharts.com/blob/v4.1.9/js/parts/Axis.js#L1121-L1124):

```js
			// Too dense ticks, keep only the first and last (#4477)
			if (tickPositions.length > this.len) {
				tickPositions = [tickPositions[0], tickPositions.pop()];
			}
```

When the number of ticks gets higher than the number of pixels on the X axis, there is no use in showing them, so we remove it. 

The question is if this behaviour needs to be changed. You say you want to use the `step` setting to control the labels to be shown, but in this case you should rather use the `tickInterval` setting to save computing power for your readers. Step will draw all the tick marks, but skip the labels.

**Comment by dmitrygorbenko** [comment]
I think this can be a good idea to allow displaying all ticks. By this I mean to able to disable next logic by some config option:
```javascript
            // Too dense ticks, keep only the first and last (#4477)
            if (tickPositions.length > this.len) {
                tickPositions = [tickPositions[0], tickPositions.pop()];
            }
```
What do you think on this ?
