### ISSUE TITLE
Datalabels update color - works only for first point

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4719]
In the 4.1.9 and master branch, datalabels color update, works only for first point.
Example:
- http://jsfiddle.net/5erdmmua/20/

In the 4.1.7 works properly
Example:
- http://jsfiddle.net/5erdmmua/19/

I think that is related with fix here: https://github.com/highslide-software/highcharts.com/issues/4622

**Comment by highslide-software** [comment]
Fails since be73ff5

**Comment by highslide-software** [comment]
As the implementer is aware of, a column range adds two data labels. What happens since the failure is that the yellow one is hidden due to overlap. 

This can be worked around by setting a `yHigh` option so that the high data label is shifted off the screen: http://jsfiddle.net/highcharts/5erdmmua/21/

**Comment by pawelfus** [comment]
Works fine since 5.0.7+ demo: http://jsfiddle.net/tm23L9t6/
