### ISSUE TITLE
DateTime Axis - TickInterval is not working

### ISSUE THREAD

**Issue by pawanvjadhav** [highcharts/highcharts#4726]
I am trying to set tickinterval of 4 day. Check below url:

http://jsfiddle.net/pawanvjadhav/kno626bf/2/

I think, tickInterval is working in case of 1 day, 2day, 3day. After that, its not behaving as per expectation.

My expectation is:
If provided data contains lowest point as 2nd Feb 2010. and if we provide tick interval 4days.
It should create data as 2nd Feb, 6th Feb, 10th Feb...so on
Let me know, if some extra options needs to be set.

**Comment by KacperMadej** [comment]
As a workaround: you could add to a `axis.units`'s day your `tickInterval`, e.g. `4` - http://jsfiddle.net/8tdzybqx/
To show always only 4 day `tickInterval` leave only `['day': [4]]` in `axis.units` - http://jsfiddle.net/8tdzybqx/1/

**Comment by pawanvjadhav** [comment]
Its working for 4 but not for 10.

In our product, we have UI where user can specify interval value.

I tested your first solution for 10, but its not working :( :
http://jsfiddle.net/8tdzybqx/

**Comment by pawelfus** [comment]
I think this is the example Kacper had in mind: http://jsfiddle.net/8tdzybqx/3/ (set **only** `day` for units).

As I remember, this is improvement in 4.1.0 where we resigned from throwing an error (19) and instead hiding labels when there will to many of them. Otherwise you could set interval = 1sec and that will hang Chrome (imagine number of ticks and labels : ))

**Comment by pawanvjadhav** [comment]
thanks @pawelfus  and @KacperMadej 

This is giving expected result. will test more. 

Thanks.
