### ISSUE TITLE
Highmaps mapNavigation movement on resize

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#4740]
In Highmaps when chart is resized buttons are moving inside the plotBox.

example:
http://jsfiddle.net/izothep/g467d4rp/

As a workaround it is possible to set 
mapNavigation.buttonOptions.alignTo: 'spacingBox'.

example:
http://jsfiddle.net/izothep/co1u7o4t/1/

**Comment by KacperMadej** [comment]
*Internal note:*

Solution for this issue seems to depend on how important is [redering map navigation before chart is being rendered.](https://github.com/highslide-software/highcharts.com/blob/a00d94dd19fa7e4ecda52600e8aa82c8f7a1b7f9/js/parts-map/MapNavigation.js#L173-L174)

Not that important - move redering map navigation below [this proceed call](https://github.com/highslide-software/highcharts.com/blob/a00d94dd19fa7e4ecda52600e8aa82c8f7a1b7f9/js/parts-map/MapNavigation.js#L176)

Important enough - realign the buttons after chart is rendered like this:

	var alignedObjects = chart.renderer.alignedObjects;
	each([alignedObjects[0], alignedObjects[1]], function(button) {
		button.placed = false;
		button.align(button.alignOptions, false, button.alignTo);
	});

**Comment by highslide-software** [comment]
I'd go for option two, we don't want to compromise on rendering speed.

**Comment by KacperMadej** [comment]
+1

**Comment by TorsteinHonsi** [comment]
Reopening, the fix had too many side effects.
