### ISSUE TITLE
Updating 3d columns with z stacking fails

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#4743]
Demo: http://jsfiddle.net/highcharts/m69rbc9p/15/

The demo shows updating `showInLegend`, but it also applies to changing Y value etc.

**Comment by pawelfus** [comment]
I think this example shows better what happens: http://jsfiddle.net/m69rbc9p/16/ - all columns are placed with wrong `groupZPadding`.

**Comment by pawelfus** [comment]
Small debugging:

This is caused by [this line](https://github.com/highslide-software/highcharts.com/blob/5ca4d678dd9dea177affaa79c300c338f6c1b905/js/parts-3d/Column.js#L17) - `series._i` is wrong (?) when series are updated because of [this line](https://github.com/highslide-software/highcharts.com/blob/5ca4d678dd9dea177affaa79c300c338f6c1b905/js/parts/Series.js#L98). We can replace `series._i` with `series.index`, however, there will be still problem with zIndexes caused by [those line](https://github.com/highslide-software/highcharts.com/blob/5ca4d678dd9dea177affaa79c300c338f6c1b905/js/parts-3d/Column.js#L123-L126). When removing this part we get working code - all tests are passed, but I'm not sure what is the purpose of this part..

**Comment by highslide-software** [comment]
Okay, please feel free to provide a fix. As for the lines in Column.js, they point to #4062 so at least you need to check that.

**Comment by highslide-software** [comment]
... and otherwise try to replicate the conditions of those lines and see what it does.

**Comment by pawelfus** [comment]
I didn't found any case, when it fails. There is only one thing I am concerned about: zIndexes are floating point numbers, not integers - we had similar issue with pie chart a while ago, but I don't want to add more logic if this is not necessary. 

Additionally, I pushed test for #4062.
