### ISSUE TITLE
2 Series with gap between will not shown

### ISSUE THREAD

**Issue by GreenRover** [highcharts/highcharts#4747]
In this example you see 2 charts, each has 2 series.
Series 2012:  1 Jan - 16 Sept
Series 2013:  31 Dec (7 hours)

http://jsfiddle.net/2N52H/86/

1 Chart:
- Series 1: 2013 and Series 2: 2012
- Dont show the any series / Lines but shows point with tooltips.
- Only if you make the viewport smaller, by using the navigator, that only one series is visible.

2 Chart:
- Series 1: 2012 and Series 2: 2013
- Will shown like expected.

**Comment by pawelfus** [comment]
It looks like problem with `gapSize` - when removed works properly: http://jsfiddle.net/ux74929j/15/

**Comment by GreenRover** [comment]
@pawelus It seams you jsfiddle is not related to my question.

How can it be a problem of gapSize ? When i switch the series the it works.

**Comment by pawelfus** [comment]
Sorry, fixed url demo. What I want to say is that the issue is with `gapSize` option - looks like `closestPointRange` is taken from `xAxis` while probably should be used from `series` (some core stuff).

**Comment by GreenRover** [comment]
+1

**Comment by TorsteinHonsi** [comment]
I'm not sure what to do with this. In a way it makes sense that the gapSize is determined by the _axis_ closest point range, because it then takes all series into account when deciding whether to put in a gap for a weekend or night. On the other hand, in cases like this, the result is not predictable since the first series contains of exclusively gaps.

#### Workaround
Anyway, the workaround is to disable gaps for the low-resolution series: http://jsfiddle.net/highcharts/2N52H/98/

**Comment by GreenRover** [comment]
Would it be a posibility to let user give an series like in this example:

http://jsfiddle.net/2N52H/99/

For gap calculation?
Can this be an solution?

**Comment by GreenRover** [comment]
+1

**Comment by TorsteinHonsi** [comment]
> Can this be an solution?

But it doesn't help either, the series does not show...
