### ISSUE TITLE
Possibly memory leak

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4757]
jQuery 1.8.2 : http://plnkr.co/edit/lQ6n5Eo2wHqt35OVPh8S?p=preview

![eotjs](https://cloud.githubusercontent.com/assets/2115686/11272100/c7da8b5a-8eca-11e5-822a-7c33b913e4d7.png)

jQuery 2.1.4 : http://plnkr.co/edit/IC0pSaxFZHQzOzoJUD0e?p=preview

![nlxxh](https://cloud.githubusercontent.com/assets/2115686/11272103/cc3a1792-8eca-11e5-88fd-eda68a8ca162.png)

**Comment by ignaciovillaverde** [comment]
I have also tried without JQuery, using the standalone framework of Highcharts, and it also increases a bit slowly. Here is a plunker with it: http://plnkr.co/edit/EvXCBUgggx4H2YgGLvov?p=preview

This is important because Torstein Hønsi in this post: https://github.com/highslide-software/highcharts.com/issues/3342 says the following,

"The workaround is to use the Highcharts Standalone Framework instead."

**Comment by highslide-software** [comment]
Here's a jsFiddle with jQuery 2.1.3. Memory leaks seem to be reduced when turning off animation, so it may be connected to the new chart being initiated before animation has finished.
