### ISSUE TITLE
3D Column Chart - Plot band Label position issue

### ISSUE THREAD

**Issue by pawanvjadhav** [highcharts/highcharts#4787]
In case of 3D Column chart : Plot band labels align and verticalAlign attributes are not working properly,

http://jsfiddle.net/pawanvjadhav/L1fhcft7/2/

**Comment by TorsteinHonsi** [comment]
What you see is the data grouped into weeks:

![skjermbilde 2015-12-01 kl 15 38 55](https://cloud.githubusercontent.com/assets/227836/11503619/bd4c18ea-9841-11e5-90a7-2ac75016221d.png)

To get the unaltered data points, disable data grouping: http://jsfiddle.net/highcharts/njjp5y4d/

**Comment by pawelfus** [comment]
*Internal note:*

This is caused by path returned in wrapped `getPlotBandPath` method in 3D. There are additional `"L"` elements in the path, which fails later in aligning label (indexes are shifted)

**Comment by TorsteinHonsi** [comment]
> Can we make separate function for aligning label? 

Yes it's a good idea. The `PlotLineOrBand.render` function is too monolithic anyway.

**Comment by pawelfus** [comment]
The commit above moves out labels rendering and positioning. Let me know if this is fine. Then I can work on fixing the issue.

**Comment by TorsteinHonsi** [comment]
It's fine, go for it!

**Comment by pawelfus** [comment]
@TorsteinHonsi I'm not sure where it is in the commit above (it's missing?), but [this zIndex](https://github.com/highcharts/highcharts/commit/9bb09cec9b4e6ae7a7ce38f78739ee388ed00f0f#diff-5d3aad1ab4221eaad4e4ba17c165d2a7L6664) should be also removed. It was accidentally introduced in previous commit [here](https://github.com/highcharts/highcharts/commit/c1ed62d74d0db0ce3027b4e5f50a4341a04d405c#diff-3e1331939f01f8d5fc2b6b44e456c045R136) - linting otherwise will return error.

**Comment by TorsteinHonsi** [comment]
The master branch is linting now on my end, but just do what you need to do to make it behave.

**Comment by pawelfus** [comment]
`bugfix` is linting fine too, I mean that I don't see that change in my previous commit for `js/parts/PlotLineOrBand.js` file.
