### ISSUE TITLE
[Boost.js] Enable bubble chart support

### ISSUE THREAD

**Issue by brandonjacob** [highcharts/highcharts#4792]
I expect this will be a controversial request but I'm wondering whether you would consider enhancing the boost.js library to respect the size of bubble chart data points? 

You could legitimately argue that a bubble chart with hundreds of data points (never mind thousands of data points) is likely going to be a waste of time. The end result could just be one big smudge which would more than likely prevent any meaningful analysis.

Arguments for supporting bubble charts:
- It's _possible_ that the user might find some analytical value in the outliers. Of course that depends heavily on the shape of the dataset.
- Even if the end result is a big smudge without any analytical value, it can still serve as a visual cue to the user that they need to choose a different chart type or filter their dataset. That's arguably better than just showing the user a generic error message like "Too many data points for a bubble chart; filter your dataset or choose a different chart type".

I was able to whip up a crude hack in the boost.src.js file (patch attached to this post) to respect data point sizes for a bubble chart. It wasn't too difficult since bubble charts already inherit a lot of their functionality from scatter plot charts. It's more a Proof of Concept. If you agree with the idea of supporting bubble plot charts in boost (a _big_ assumption), then perhaps my crude hack could serve as an idea for a more refined solution.

[0001-Patch-boost.js-to-respect-bubble-chart-point-size.patch.txt](https://github.com/highcharts/highcharts/files/49438/0001-Patch-boost.js-to-respect-bubble-chart-point-size.patch.txt)

**Comment by TorsteinHonsi** [comment]
Hi Brandon, sorry for the late reply. Been busy with the new release.

Yes, I agree bubble charts with boost.js make sense. Just like scatter charts, you can apply a low opacity to each bubble, say 0.1, and given hundreds of thousands of bubbles, you will see a big smudge of data. But you will see a stronger color where the density is greater, so it will work almost like a heat map.

**Comment by TorsteinHonsi** [comment]
Brandon, did your patch run successfully? For me it doesn't run renderCanvas at all...

**Comment by ecehanece** [comment]
I implemented this patch and apply low opacity to each bubble and it worked. But there is one problem: I couldn't retrieve data labels. Any suggestions?

**Comment by Dams591** [comment]
Hi guys,

Just discovered the boost module today and it is magical !
My scatters are so fast now and my browser is not freezing like it was.

However I can't make it work with bubble, do I still need this patch with highchart v5 ? 

Thanks,

**Comment by TorsteinHonsi** [comment]
Thanks! Yes, we haven't implemented bubbles in the module yet. But we're investing time in the module now, so we should see some improvement in the weeks to come. @cvasseng FYI.

**Comment by Dams591** [comment]
Ok then. Do I have a way to patch the current boost right now ? I'm trying to understand the file that @brandonjacob gave but I can't figure out.

**Comment by Dams591** [comment]
@TorsteinHonsi  Any idea how to patch the boost v5 to handle bubble properly ? thanks.

**Comment by whipit** [comment]
I'm also interested in this patch.   I applied the patch by @brandonjacob, but haven't seen a noticeable difference in performance.    

@TorsteinHonsi....could you please give us an ETA for getting bubble for boost?   

We're currently evaluating some other alternatives as well, but would prefer to stick with high charts if this support is added soon.

Thanks!

Tim

**Comment by whipit** [comment]
I found that renderCanvas() was not being called - as @TorsteinHonsi mentioned above.   I had to set the "boostThreshold" property of the series to some number lower than the size of my data set before it can work.   This is because the canvas methods are only called if the size is greater than that threshold.  

Performance is now better (~140ms for 1500 data points vs. 300ms for 1500 data points).

However, I now have lost tooltip, and also my bubbles are not obeying opacity.

**Comment by TorsteinHonsi** [comment]
Implemented with a012a5e1a7e370eb4703ef9dfad120c9321ee17a. See it live at http://jsfiddle.net/highcharts/5v7z5ouh/.

Bubbles are not as fast as scatters because it still needs to go past the axis extremes logic and it needs to loop through it to get the bubble radii. We would be able to get it faster if we do the `getRadii` logic inline and hard set axis extremes as well as [zMin](http://api.highcharts.com/highcharts/plotOptions.bubble.zMin) and zMax. But as noted above, we are about to port the whole Boost concept to WebGL, so we will save the math for that.
