### ISSUE TITLE
Chart border - white extra pixel

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4798]
When border around chart is set, then one white pixel is printed as well.

Example: 
- http://jsfiddle.net/szq28ajc/5/

![zrzut ekranu 2015-12-03 o 12 59 33](https://cloud.githubusercontent.com/assets/2115686/11560020/bb97058c-99bd-11e5-814d-16f296a73890.png)

**Comment by pawelfus** [comment]
Note: that white pixels comes from inputs.

**Comment by primerano** [comment]
This issue still exists or maybe it returned in HC6.

http://jsfiddle.net/primerano/39q8rLw4/

moving the pixel -9em is not enough to get it out of view on out bootstrap layout.  
                    left: '-9em' // #4798

**Comment by pawelfus** [comment]
Thank you for letting us know. Let me reopen the issue.

**Comment by TorsteinHonsi** [comment]
I'm moving this to `top: -9999em` instead. Moving it to the left has the potential to break the page layout in rtl pages.

I'm not sure why we used `left` in the first place instead of just `display: none` or `visibility: hidden`, but I remember we have had some problems with the inputs in various browsers in the past, so I'm not brave enough to try.

**Comment by primerano** [comment]
Thanks for the fix.   What release will this be in 6.0.3?

**Comment by pawelfus** [comment]
It will be released in v6.0.3.
