### ISSUE TITLE
Labels overlapping for tickPositions

### ISSUE THREAD

**Issue by rinatio** [highcharts/highcharts#4806]
Labels drawn for each tickPosition started to overlap since 4.1.0: [jsfiddle1](http://jsfiddle.net/rinatio/n7y7Lafb/). Highcharts used to hide some intermediate labels before to avoid overlapping: [jsfiddle2](http://jsfiddle.net/rinatio/es9fx0so/). Not sure if it's by design or not.

![screen shot 2015-12-07 at 3 08 20 pm](https://cloud.githubusercontent.com/assets/426879/11626513/6d61009a-9cf4-11e5-9e65-33c511aa618f.png)

**Comment by TorsteinHonsi** [comment]
When using `tickPositions` or `tickPositioner`, Highcharts assumes that you have taken this into account. 

If however you only set the `tickInterval`, Highcharts will not go closer than the labels allow: http://jsfiddle.net/n7y7Lafb/2/.

The difference from HC 4.0 is that previously, the tick amount was the same but the labels were skipped in order to make room.
