### ISSUE TITLE
4.1.9 Now missing src files

### ISSUE THREAD

**Issue by ggrillone** [highcharts/highcharts#4815]
I recently re-installed version `4.1.9` via bower and the `highcharts.js` and entire `modules/` directory are both completely missing.

Upgrading to `4.1.10` gives me the new `lib/` directory with all the correct files, but `4.1.9` is unusable

**Comment by TorsteinHonsi** [comment]
Yes, the `highcharts` name on Bower is now pointing to the working repo (this repo), while previously it was pointing to `highcharts-release`. To continue using older versions with the same directory structure as previously, load `highcharts-release` in Bower. 

The good news is that we now have one official repo for Highcharts, Highstock and Highmaps, it is all just called `highcharts`, and that this is the same as the working repo. The shim repos (-release) will be marked deprecated soon.

**Comment by benmccormick** [comment]
@TorsteinHonsi Could you please reconsider this?  Making this change just broke all of the builds for my companies web app, since we rely on bower to pull in specific versions of repositories to keep things stable.  Swapping out the repository that a bower name is pointing to without warning is very bad form, especially for a library that we pay for.

I understand the desire to change the name, but please remember that people are actually using this in production.

**Comment by jawshooah** [comment]
Agreed with @benmccormick, this seriously screwed with our build process.

**Comment by pmacmillan** [comment]
Hit this in dev today, the *real* issue (imo) stems from bower's cache... everything *works* locally -- thanks to ~/.cache/bower -- and production keeps this cache too (in my case)...

I felt this when one of our devops guys was working on installing a new local dev version of our app... worked for me, worked in production... only when I wiped my cache with force was I led here.

This change was bad. Maybe good in the long term, but it deserved a more transparent announcement.

**Comment by jawshooah** [comment]
Why not register this as `highcharts-all` or some such? That wouldn't have caused any problems at all, and would have more clearly communicated the intent of the package.

**Comment by TorsteinHonsi** [comment]
I'm sorry about this inconvenience. We did this at the same time as announcing the `highcharts` npm package, and it makes sense in the long run to have it all under the same name and directory structure. GitHub, Bower and npm. 

Also, we have never really announced Bower as an official download strategy, like we do now on www.highcharts.com/download. Some other guy took the `highcharts` name on Bower, pointed it to our working repo, which didn't have the compiled files, then we had to come up with the release repos. 

In the mean time, we got hold of the `highcharts` name and pointed it temporarily to `highcharts-release` while working on a better solution. In hindsight I see we should have done something else.

**Comment by pmacmillan** [comment]
@TorsteinHonsi ; Thank you for the explanation.

:+1:

**Comment by philBrown** [comment]
@TorsteinHonsi 

> The shim repos (-release) will be marked deprecated soon.

Can you reconsider this? Bower is a distribution channel, not a means of checking out your source code (that's what git is for).

Either keep the shim repos or change your `bower.json` to ignore all the build / test code.

**Comment by TorsteinHonsi** [comment]
> Either keep the shim repos or change your bower.json to ignore all the build / test code.

As far as I can see, it is already ignored. This is the contents of the ignores in bower.json, I believe it has changed since last release:

```json
    "ignore": [
        "build",
        "copy-release.js",
        "errors",
        "exporting-server",
        "generate-changelog.js",
        "grunt-tasks",
        "gruntfile.js",
        "js",
        "vendor",
        "samples",
        "studies",
        "test",
        "tools",
        "utils",
        ".gitignore",
        "ant",
        "build.md",
        "build.properties",
        "build.xml"
    ]
```

**Comment by philBrown** [comment]
@TorsteinHonsi ok, I was looking in the tarball that bower downloads.

Can you please explain though how we're meant to use older versions of Highcharts? First you said

> To continue using older versions with the same directory structure as previously, load `highcharts-release` in Bower

but then you said

> The shim repos (-release) will be marked deprecated soon.

Replacing the older releases with the `bower-info.js` script was not a very nice thing to do.

    if (window.console) {
    	console.log('You are using the Highcharts Bower repo. This repo is for source and' +
    	' utilities and not optimized for production. Instead, use the official shim repos ' + 
    	' "highcharts-release", "highstock-release" or "highmaps-release".');
    }

**Comment by TorsteinHonsi** [comment]
Even if we deprecate the -release repos, you'll have access to older versions of Highcharts there. Deprecation is only a signal that you should move on to the new, official repo. 

But we will continue updating all repos for a while.

**Comment by philBrown** [comment]
Thanks for clarifying. When I read *deprecated*, I see that as a sign of imminent removal

**Comment by CleverCoder** [comment]
Please update documentation here to reflect the need to use "highcharts-release":
http://www.highcharts.com/docs/getting-started/install-from-bower

Also, this was not a very thoughtful change. Plus, it seems to be a nonstandard convention. Why not leave things alone, and introduce something like "highcharts-dev", leaving "highcharts" as the release.

The timing of this was terrible, but I'm glad there's an explanation.

Cheers!

**Comment by CleverCoder** [comment]
Sorry, but I would highly recommend completely removing the 4.1.9 "highcharts" package altogether, as what we get when we 'bower install highcharts#4.1.9 --save' is useless. That's a HUGE problem. If the package was just removed, then at LEAST we would have caught an error that could lead to determine the problem. I imagine there's a ton of dev teams scratching their heads currently, when they get a "Highcharts not found" in the console, when they changed nothing between builds.

**Comment by benmccormick** [comment]
I agree with @CleverCoder.  If you're going to change the contents, please just remove this package from the bower directory so that it errors and people can more easily understand whats going on.

(note that this should be removed completely, not just removing the version, since it's all old versions that have this problem, not just 4.1.9)

**Comment by TorsteinHonsi** [comment]
> Please update documentation here to reflect the need to use "highcharts-release":

On the contrary, you are recommended to use `highcharts` from now on. The only reason to use `highcharts-release` is if you depend on the __source__ files of __older__ releases.

**Comment by TorsteinHonsi** [comment]
Hi again guys, we decided to move the `highcharts` pointer back to the highcharts-release repo like it was, so you will have all the history intact.

**Comment by jwngr** [comment]
Just so you know, your decision to revert back just broke those of us who actually upgraded to the new directory structure for the `highcharts` npm package now for a second time, again without warning. I realize you were stuck between a rock and a hard place after your initial decision, but reverting it two weeks later does not help the situation. At the very least, you could have given a warning by commenting on this issue thread saying you were going to revert the change so that we knew what to expect before it happened.

As a maintainer of several packages on npm and Bower, I understand where you guys are coming from and that it's not an easy job. But please be wary of making any changes like this in the future as it always has a bigger impact on customers than you think it will.

Thanks for building Highcharts and have a happy holidays!

**Comment by TorsteinHonsi** [comment]
Yes, I'm sorry for this. 

> But please be wary of making any changes like this in the future

We won't make changes like this in the future, that's why we struggled so hard to get it perfect now.
