### ISSUE TITLE
highcharts 4.1.10 webpack not working 

### ISSUE THREAD

**Issue by Kepro** [highcharts/highcharts#4818]
highcharts is undefined if using webpack(not tested without) on 4.1.8 is working well

**Comment by TorsteinHonsi** [comment]
Did you see http://www.highcharts.com/component/content/article/2-news/188-highcharts-optimized-for-npm?

As you can see, we implemented CommonJS support in v4.1.10, so if you have workarounds from previously it may break. Does it work when you load it the way we describe in the article?

@jon-a-nygaard

**Comment by zeroedin-bill** [comment]
@Kepro @TorsteinHonsi I ran into this today as well. This is not really a suitable change for a patch release. This is a breaking change, and should be deferred to a major release IMO. 

The previous module format has been annoying as hell to work with, but I've got hacks in place in my build system to handle that. So does pretty much everyone else who uses highcharts via webpack or browserify. Deciding to completely change your module format in a *patch release* is not helping any of us who use webpack and browserify. Change the module format in a major release and we'll all be happy. Break my builds because you don't follow semver and I'll be unhappy.

Not that I don't love Highcharts. Highcharts is great. All except the module format. :stuck_out_tongue:

**Comment by TorsteinHonsi** [comment]
> This is not really a suitable change for a patch release.

Ideally we wanted to wait for HC5, but we thought it is too important to wait. The JS world pretty much turns around npm these days, so we couldn't live with a hackish solution.

**Comment by TorsteinHonsi** [comment]
FYI, see also #4817. We have concluded this is the right time to bake the
Standalone Framework into highcharts.js so it runs without dependencies.
Which means, after the next maintenance you can run require Highcharts in
its simplest form:
```js
var Highcharts = require('highcharts');
```
​

**Comment by thatcorey** [comment]
Is there a branch with it baked in already that I can try out?  I use webpack and I'm having no luck when following the examples using the require('highcharts')(highchartsadapter) type deal.  I get things like "each is not a function".  I was having way better luck using other peoples repos like commonjs-highcharts, but they aren't up to date.

**Comment by TorsteinHonsi** [comment]
> each is not a function

Yes, that's the issue we are addressing. It comes from the dataLabels anti-collision feature. Currently we don't have the development branch online.

**Comment by TorsteinHonsi** [comment]
Fixed with Highcharts 4.2.
