### ISSUE TITLE
Extra space after scrolling

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4846]
Example:
- http://jsfiddle.net/s2eL2j9n/

Steps to reproduce:
1) you have a series with 4 points
2) click on switch series
3) now you have a series with lot of points
4) place your cursor on the scrollbar, click and move a little bit on the right and a little bit on the left
5) click on switch series
6) the result is 4 points and a lot of empty space on the right

Workaround
- call setExtremes or zoomOut after addSeries,

**Comment by pawelfus** [comment]
Short explanation what happens:

When user drag&drop bottom scrollbar, it automatically sets extremes with `min` and `max`. And because navigator is disabled, user's `min` and `max` (`userMin` and `userMax`) have the highest priority on the xAxis, so we don't change them. I'm not convinced if we should change that behaviour..
