### ISSUE TITLE
gridlines overlap border

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4866]
On the right border, you can observe that gridlines are out of clipath.

http://jsfiddle.net/pj9c0Lnu/

**Comment by pawelfus** [comment]
Better use case: http://jsfiddle.net/pj9c0Lnu/2/

In general, border is rendered inside, but chart didn't reserve the space for it.

**Comment by TorsteinHonsi** [comment]
I'm not sure we want to change this - it will mess up the geometry of every chart that has a border. Also, it is probably not a very common use case with a border so wide that it overlaps content. And if a border like that is required, there are workarounds:

* Add a `spacing` that reflects the `borderWidth`. [View on jsFiddle](http://jsfiddle.net/highcharts/pj9c0Lnu/3/).
* Apply the border on the container div instad. Won't be part of the exported chart. [View on jsFiddle](http://jsfiddle.net/highcharts/pj9c0Lnu/4/)

**Comment by TorsteinHonsi** [comment]
The user sent us an image with a border of 1px, using the `dark-blue` theme. The difference from the themes to a default-themed Highcharts is that the tickWidth is set to 1 explicitly. Without this, the tick isn't normally enabled on a Y axis. This is what it looks like when the `tickWidth` is set to 1:

http://jsfiddle.net/highcharts/4rau595s/

The setup is the same as in a stock chart. Y axis is opposite, the labels are right aligned, and the axis text is disabled. The tick marks are not considered in the layout, so they are just placed relative to the plot area, like the [http://api.highcharts.com/#yAxis.tickPosition](tickPosition) option dictates.

Several options remain:
* Do nothing. Remove the `tickWidth` from the themes, to use the default settings. However this still feels buggy, as I would expect all ink to stay inside the bounds of the `chart.spacing`.
* Add the tick marks to the computation in `Axis.getOffset`, so that they are considered in the layout.
* Change the default value of `yAxis.tickPosition`, so that the ticks are drawn `inside` by default when the labels are inside. This means that labels.align = 'left' on an opposite y axis would lead to tickPosition: inside by default. 

@pawelfus, @sebastianbochan What do you think?

**Comment by sebastianbochan** [comment]
I think that the most convenient solution is set spacing value the same as borderWidth. Is easy to use.
