### ISSUE TITLE
toPixels in inverted chart

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#4867]
Example: http://jsfiddle.net/xw8mvegv/12/

Break is rendered in a wrong place.

**Workaround:**
Use `axis.translate(value, 0, 1, 0, 1);` instead. Demo: http://jsfiddle.net/xw8mvegv/11/

**Comment by TorsteinHonsi** [comment]
Actually the `toPixels` function returns the correct value. The problem arises because the path is added to an SVG group that is flipped by translation. So I will update our demo to use the workaround you suggest. Additionally, I have adapted the demo so that the break is visualized on the axis line: http://jsfiddle.net/highcharts/xw8mvegv/17/

**Comment by pawelfus** [comment]
I'm not sure about this.. compare examples:

- inverted: http://jsfiddle.net/xw8mvegv/19/
- non-inverted: http://jsfiddle.net/xw8mvegv/20/

**Comment by vijibalas** [comment]
+1

**Comment by TorsteinHonsi** [comment]
@pawelfus your inverted fiddle is wrong, because the X and they Y axes swap places in an inverted chart. So in order to get the `cx` attribute for the circle, you actually have to read the position on the __Y__ axis, and vice versa: http://jsfiddle.net/highcharts/xw8mvegv/21/

**Comment by pawelfus** [comment]
Of course, you are right! Sorry, I was blind.

**Comment by vijibalas** [comment]
is that true for an inverted chart too?

**Comment by pawelfus** [comment]
Type of the series doesn't matter in this case. columnrange type: http://jsfiddle.net/xw8mvegv/22/

**Comment by vijibalas** [comment]
thankyou @TorsteinHonsi 
how about https://github.com/highcharts/highcharts/issues/4868
is there a workaround for this other issue.
