### ISSUE TITLE
Adding long series won't trigger dataGrouping on (existing) short series

### ISSUE THREAD

**Issue by kejml** [highcharts/highcharts#4874]
I have a chart with series, that fits the container without data grouping. I have another series, that is so long, that it has to use data grouping to be displayed when zoomed out too much. In a case, when I have the short data series in chart and I add long data series dynamically (using  addSeries method) and zoom out, long data series is displayed with data grouping, but the short one isn't.

This causes problem, that when users hovers over series, on some places, he sees tooltips for both series, but on others, there is only one for the short series.

See example here: http://jsfiddle.net/x0ffrr8y/1/ When you click on "Add series" button and then click on "6m" button, the problem occurs. Series are noticeably different (because of approximation) and the points of short one are closer to each other (can be seen using too tips as described above).

![highcharts1](https://cloud.githubusercontent.com/assets/4223239/11978084/0aec36d6-a989-11e5-8321-20832c4f340d.png)
![highcharts2](https://cloud.githubusercontent.com/assets/4223239/11978083/0ae9dc06-a989-11e5-9796-ef4388571dfb.png)

**Comment by pawelfus** [comment]
I'm not sure if this is a bug. `dataGrouping` is calculated per series, it is not just one dataGrouping on the chart. If `dataGrouping` will be forced to use highest possible unit within the series, then your first series will become just one point. 

From the other hand, this is the way it works for column type series: http://jsfiddle.net/x0ffrr8y/2/ - we can achieve the same result by setting `dataGrouping.groupPixelWidth`. Demo: http://jsfiddle.net/x0ffrr8y/3/

Now the problem is that `rangeSelector` doesn't update button states, but this is caused by setting `selected: 3`, but initial series doesn't have enough data to enable that button. Without that option it works fine: http://jsfiddle.net/x0ffrr8y/4/

**Comment by kejml** [comment]
Correct me if I'm wrong, but as far as I understand the `groupPixelWidth` property, this behaviour is not correct. 

This is how I read the documentation: By default, grouping is not used, so when I want to draw 50 points in a container 200 px wide, points are just drawn as they are and connected with line. But when there is more points per `groupPixelWidth` pixels, data grouping starts and creates grouped points wide `groupPixelWidth`. So when I have 400 points in 200 px wide container, data grouping should kick in and create create group of four points every 2 pixels, containing 4 points of the original series each (when using default values). Am I right?

In my example, both series have same "points density" (number of points per time unit) so data grouping should trigger simultaneously, shouldn't it?

What's more, from my picture it seems to me like the black line is smoothed by approximation while it overlaps the blue line and is not when ovarlap ends.

On last thing is, that when you switch adding of the series (i.e. long one is in the chart on load and short one is added later by using `addSeries`) the result is different. The series perfectly overlap each other on all zoom levels and data grouping works same on both series - maybe this isn't a bug, but it seems to me like (confusing) inconsistency.

**Comment by pawelfus** [comment]
>Am I right? 

It is not exactly 4 points per group - remember that grouping is applied on a specific unit, from `units` array. So it depends on the distance between points. 

> In my example, both series have same "points density" (number of points per time unit) so data grouping should trigger simultaneously, shouldn't it?

If `xAxis.ordinal` would be set to `false` then I would agree - the same approximation should be used, because the same `groupPixelWidth` would be applied. With `ordinal = true` points are distributed evenly, so I am not sure of that should happen.  

> What's more, from my picture it seems to me like the black line is smoothed by approximation while it overlaps the blue line and is not when ovarlap ends.

It shouldn't end at the same place when `month` unit is used (my demo). Simply you have different dataset for series, and one series doesn't contain all datapoints for a full month, so approximated point's value may be different.

> On last thing is, that when you switch adding of the series (i.e. long one is in the chart on load and short one is added later by using addSeries) the result is different. (...)

Ok, for me that one is a bug :) It should be consistent and order of series shouldn't change anything.

*Internal note:*
I think we should consider improving `linkedTo` option which will connect not only series' state and visibility, but also should force linked series to use the same `dataGrouping`'s approximation?

**Comment by pawelfus** [comment]
Connected to #2102

**Comment by kejml** [comment]
> If xAxis.ordinal would be set to false then I would agree - the same approximation should be used, because the same groupPixelWidth would be applied. With ordinal = true points are distributed evenly, so I am not sure if that should happen. 

I wasn't aware of the `xAxis.ordinal` option, but setting it to false has no effect on my example. I don't know the internals of Highcharts, so maybe we should move this discussion to forum, but I still don't get it. In my example, I have two series with exactly same data points, only one of them is shorter (ends earlier). So the x-distances between neighbour points are the same. Still, each series uses different data grouping. From my point of view (as a user of the library), this seems wrong.

I see from your example that increasing `groupPixelWidth` helps in this example, but I actually don't know why and I'd like to keep the value as low as possible.

> It shouldn't end at the same place when month unit is used (my demo). Simply you have different datasets for series, and one series doesn't contain all datapoints for a full month, so approximated point's value is different.

What confuses me, is that while overlapping, the long series is smoothed while the short is not. After the overlap's end, the long series is no longer smoothed. It looks to me like the presence of short series affects rendering of the long series. This is correct? 
I would understand short series being smoothed while the long being not, but I don't understand result in my example.

**Comment by pawelfus** [comment]
I think you are right - this is confusing that series have different `dataGrouping`, that's why I suggested to improve logic or add new option to connect two series to apply always the same `dataGrouping`. 

>  It looks to me like the presence of short series affects rendering of the long series. This is correct? 

Yes, that's how it looks. In fact, first series affects all other series, while it shouldn't, I think. 

By the way, your example looks quite different with disabled `ordinal` option: http://jsfiddle.net/x0ffrr8y/5/

**Comment by kejml** [comment]
I see, I didn't get the _internal note_ you wrote before.

> By the way, your example looks quite different with disabled `ordinal` option: http://jsfiddle.net/x0ffrr8y/5/

You're right, I overlooked that drawn line is different, I just noticed it doesn't solve the problem with tool tip caused by data grouping.

I don't know how the development of Highcharts work in practice. Don't you have some idea how fast issues like this get solved? Weeks, months, depending on contributors? I might try to have a look, but I'm afraid I'll get confused by huge codebase I've never seen.

**Comment by pawelfus** [comment]
I can not promise anything. Now it's holidays time so it's hard to say.

For now, I suggest to use workaround  `groupPixelWidth` with value ~10px.

**Comment by kejml** [comment]
I see.

We have hundreds of charts at the moment, but I'll look for some compromise value of `groupPixelWidth` for now.

Anyway, thanks for your time.

**Comment by TorsteinHonsi** [comment]
I can confirm that the data grouping is supposed to be aligned, so that all series on one axis have one data grouping in common, and the shared tooltip displays all series. As defined in the [https://github.com/highcharts/highcharts/blob/v4.2.1/js/parts/DataGrouping.js#L489](Axis.getGroupPixelWidth) function, the axis should take the max groupPixelWidth defined on any of its series.

**Comment by kevin-coelho** [comment]
@pawelfus I'm having sort of a similar issue but not sure if it is due to this. When this "data grouping" occurs, does it empty the regular data array on the series? (I noticed after using addseries that some of my data arrays are empty, and the points have moved to groupedData) If so, does it copy properties over from original data?

My data points look like this: 
`
			{
				x: [some x],
				y: [some y],
				original: [some metadata],
			};
`

I noticed my metadata is disappearing somewhere, maybe this is it?

**Comment by pawelfus** [comment]
Hi @kevin-coelho 

This is expected behaviour, see [`Series.data`](https://api.highcharts.com/class-reference/Highcharts.Series#.data) docs.

Regarding `dataGrouping` and extra data: grouped points don't copy any extra properties to grouped points. You should create your own [`approximation`](https://api.highcharts.com/highstock/plotOptions.series.dataGrouping.approximation) function which will handle these properties.
