### ISSUE TITLE
Boost module - canvasToSVG this.image is undefined

### ISSUE THREAD

**Issue by hkostia** [highcharts/highcharts#4904]
https://jsfiddle.net/dbeaxfsv/

```
boost.js:6 Uncaught TypeError: Cannot read property 'attr' of undefined
c.extend.canvasToSVG @ boost.js:6
b @ boost.js:11
o @ highcharts.js:26
v @ boost.js:2
(anonymous function) @ boost.js:2
```

This happens when changing page fast in a SPA and the chart was not fully drawn before ```destroy()``` for the chart is called. Could there be additional ```if (this.image)``` check in ```canvasToSVG``` method?

**Comment by jon-a-nygaard** [comment]
@hkostia A possible solution as you mentioned is to add an additional if statement to silence the error. 
But the reason behind this issue was the eachAsync method which kept running even though the chart was destroyed. This is fixed in the latest version of the boost module which you can collect from this repository.
