### ISSUE TITLE
Chart not updating unless item is added to collection

### ISSUE THREAD

**Issue by ias0nas** [highcharts/highcharts#4910]
I have a pie chart that is getting updated using push notifications. When the y value is updated for a given item the chart is not updated. If a new item is added, the chart is updated.
The items need to be in a variable, hardcoding the values is working fine. 

Example below, the chart is only updated when a new name is added in the box or when resetting the data: 
https://jsfiddle.net/y0nov8ra/

I downloaded highcharts 4.1.8 and everything seems to work fine.

**Comment by TorsteinHonsi** [comment]
Can you eliminate the HTML form so that your demo shows only the Highcharts API? Otherwise this question belongs more to tech support than to the issue tracker.

**Comment by ias0nas** [comment]
Not sure which HTML form you are referring to? If you are referring to the supporting JS variables, I can't eliminate them and replace them with hardcoded values as this seem to work.

**Comment by TorsteinHonsi** [comment]
You have an input form above the chart. This should be eliminated so that we know for sure that the problem is with Highcharts, not with your application outside Highcharts.

**Comment by pawelfus** [comment]
This is a problem with using array of objects to store data and using the same array for Highcharts. Since, this is the reference, updating in `pathTotals` also updates data in `chart.series[0].options.data` so when Highcharts lib doesn't find any changes with original data, it won't update anything. 

This works fine ( https://jsfiddle.net/y0nov8ra/2/ ) :

    pathsChart.series[0].setData($.extend(true, [], window.pathTotals));

**Comment by ias0nas** [comment]
I see, thank you.
