### ISSUE TITLE
yAxis tick positions are changing on chart resize or series hide/show.

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#4925]
Adding series to chart with redraw set to false and redrawing a chart after adding all series can result in problem with yAxis tick positions. They are changing on chart resize or series hide/show. 

example:
http://jsfiddle.net/bepdpau5/1/ 

To recreate the issue hide blue series, then show it again.

Before hiding blue series:
![image](https://cloud.githubusercontent.com/assets/15050812/12328905/fbf21dce-badd-11e5-843d-95c69e3a7c08.png)

After hiding and showing blue series again:
![image](https://cloud.githubusercontent.com/assets/15050812/12328890/d984f626-badd-11e5-8dd9-fd605d19ceb2.png)

As a workaround it is possible to use tickInterval.

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! There are more cases where the tick layout is changed after interacting with the chart, and they are not necessarily bugs, since the API states the the [tickInterval](http://api.highcharts.com/highcharts#yAxis.tickPixelInterval) option dictates _approximately_ the pixel interval between ticks.

In this particular case, however, it seems like a bug. Apparently the height of the legend and the axis labels are not considered when laying out the ticks the first time. When you use the recommended pattern of adding initial series to the series option, it works as intended: http://jsfiddle.net/highcharts/bepdpau5/2/.

**Comment by bkirtika** [comment]
+1

**Comment by sebastianbochan** [comment]
It looks like fixed since v5.0

Reopen if problem will come again.
