### ISSUE TITLE
Highstock: Axis.breaks on yAxis

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4926]
Doesn't work for Highstock: https://jsfiddle.net/zzs9pcng/

Works for Highcharts: https://jsfiddle.net/zzs9pcng/1/

**Comment by TorsteinHonsi** [comment]
Keep in mind the broken-axis module is integrated in highstock.js. New demo: https://jsfiddle.net/highcharts/zzs9pcng/5/

**Comment by pawelfus** [comment]
*Internal note:*

Just a quick peek: 

`axis.doPostTranslate` is undefined, while should be set to true, this is caused by [this line](https://github.com/highcharts/highcharts/blob/bdd626599078ad2f52d7b5cfd47c163603e29af4/js/parts/OrdinalAxis.js#L276) - looks like flag `hasBreaks` is wrong (or maybe the variable name is misleading).

**Comment by TorsteinHonsi** [comment]
Thanks!

**Comment by geoff604** [comment]
Thanks, this fix works for us.
