### ISSUE TITLE
Pie Chart labels overlaps

### ISSUE THREAD

**Issue by natotech** [highcharts/highcharts#4937]
Labels on Pie charts are overlapping (see attached screenshot).
To reproduce, follow this steps to reproduce:
1. Go to https://jsfiddle.net/casilen/2kn0fsqf/ 
2. In this sample chart, there are multiple categories named A-M. Deselect A and then deselect B. Notice data labels are updated as you deselect categories.
3. Select B again and its label appear but overlaps with the others. Select A again and you will also see its label overlaps with other labels.

![2016-01-20 03_11_59-pie chart labels blocking - jsfiddle](https://cloud.githubusercontent.com/assets/1423194/12429489/75bee9c0-bf25-11e5-8c66-04467724eb2e.png)

**Comment by TorsteinHonsi** [comment]
_Internal note:_
This issue is fixed in the candidate for Highcharts 5, currently in the dev-label-distribution branch.

**Comment by sebastianbochan** [comment]
It seems that is fixed since v5.x

Demo:
- https://github.com/highcharts/highcharts/issues/4937

<img width="513" alt="zrzut ekranu 2017-06-29 o 15 52 26" src="https://user-images.githubusercontent.com/2115686/27690974-ff1de67e-5ce2-11e7-90b6-70ded31908e9.png">

Im closing the ticket, but please reopen if problem will come again.
