### ISSUE TITLE
boostThreshold causes dicrease of performance

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#4948]
When we set boostThreshold as 0 or 5000 works well, but declaring that value as 50, we can observe very low performance.

Example:
- http://jsfiddle.net/s2172kon/

**Comment by TorsteinHonsi** [comment]
It creates one canvas element for each series, so with multiple series and few points it is not optimal. The boost module is designed for real-world scenarios where we have a few series with lots of data each.

Is there a real-world case where we would add 1000 series? I mean, do we need to consider the series count in addition to the `boostThreshold` before deciding to go into boost mode?

**Comment by jpatel107369** [comment]
Yes, it's a real-world use case. Basically, it's pretty useless to view time series data with million of points spaning for long time. We break this long series by unit of work (ex. proecssign a part), and overlay them on the same point to see abnormality. In such case each portion of data for a given part becomes a series and you will endup with lots of series in the chart. We also have lots of user defained manipulations which requires diffrent colors/alighment etc of the series. I can provide more details if needed, but this is definately coming for real-word application for which we have performance issue using current HighChart control and we are starting look for alternative chart control which uses Canvas based charting as it can do this faster. we had discussion with sebastian to support canvas base fast charting last year and we saw boost.js update so we are trying it out in the product to see whether we can avoid replacing highcharts with this feature. Please let up know if you want to know more details. 
Note: Our engineer also tried to make minor changes in boose.js which improveds it's performance quite a bit for above usecase, but expectation is boost.js should support such usecase instead of we have to go and update it.  Please let up know ASAP if you are considering to support this in boost.js so we can proceed accordingly.

**Comment by TorsteinHonsi** [comment]
Okay, I accept that it's a real world case, no offence!

First off, let me say that I acknowledge the decrease of performance, but in the history of Highcharts, we have focused performance improvement on the number of points in a chart. I can't remember a case where the number of series was the bottleneck. That's just the background for why we haven't put so much effort into optimizing this part.

> When we set boostThreshold as 0 or 5000 works well.

When it is 0, is means disabled. This means that the boost module should be disabled when working with this amount of series. Actually I don't think rendering to canvas makes any difference, it is the JavaScript operations that take time. I did some profiling (without boost), and found the bottlenecks are the operations done on initiating each series. I did the following changes:

1. [Sorting the series](https://github.com/highcharts/highcharts/blob/v4.2.1/js/parts/Series.js#L100-L104). Commented out this block.
2. [The getAttribs function](https://github.com/highcharts/highcharts/blob/v4.2.1/js/parts/Series.js#L1060). I returned in the beginning of this function.
3. [Setting z-index to series groups](https://github.com/highcharts/highcharts/blob/v4.2.1/js/parts/Series.js#L1590). Commented out this line.

These changes made the rendering times go down from 4400ms to 1700ms on average using the OP fiddle. Then when I disable the legend, that doesn't seem to make too much sense with 1000 series, the rendering time drops to 950ms.
