### ISSUE TITLE
Stacking on bar chart

### ISSUE THREAD

**Issue by omemina** [highcharts/highcharts#4976]
When stacking on bar chart is set to 'normal' there is a small offset between vertical grid line and series rectangle.
JSfiddle without issue:
http://jsfiddle.net/3j2L2ms0/5/
http://i.imgur.com/yOJUXXP.png

JSFiddle with issue:
http://jsfiddle.net/3j2L2ms0/4/
http://i.imgur.com/1o9IAWR.png

The problem is noticable if you zoom the page.

**Comment by TorsteinHonsi** [comment]
This is the kind of rendering issue that depends on the width of the chart, since the bar layout is flexible. I tried replicating it with a 400px wide chart, but it looks correct in Chrome: http://jsfiddle.net/highcharts/3j2L2ms0/6/

![skjermbilde 2016-02-01 kl 09 40 43](https://cloud.githubusercontent.com/assets/227836/12712322/d9efc620-c8c7-11e5-9de7-2b9b9926c224.png)

What browser are you using? Can you set the explicit width of the chart to reproduce the issue?

**Comment by omemina** [comment]
I am using Chrome 47.0.2526.80 (64-bit) on Linux. Take a look at this JSFiddle:
http://jsfiddle.net/3j2L2ms0/8/
Hide values for series '2005' using legend. You should see the offset. Please take a look at this picture also:
http://i.imgur.com/X5DWAIQ.png

This looks fine on Chrome in Windows.

**Comment by TorsteinHonsi** [comment]
Weird. I'm running Chrome 48 on the Mac, it works well.

**Comment by oysteinmoseng** [comment]
I was unable to reproduce this on Chromium 44 on Linux, have not tested with Chrome.

**Comment by omemina** [comment]
Have you tested it with Chrome 47 on Linux?

**Comment by larsac07** [comment]
Same in Chrome 51 on Linux, but like @omemina said, only when zooming in.

**Comment by jon-a-nygaard** [comment]
Has probably something to do with the crispening logic. Similar issue: #5334

The problem is noticable in Chrome 51 on Windows as well.
Open [this link](http://jsfiddle.net/3j2L2ms0/4/show) and then zoom in on the chart.
You will see an offset which looks the same as this picture @omemina gave us:
![Image](http://i.imgur.com/1o9IAWR.png)
