### ISSUE TITLE
z-index of lines is not reflected on line markers

### ISSUE THREAD

**Issue by wojtekmaj** [highcharts/highcharts#4980]
Steps to reproduce:
1. Open http://jsfiddle.net/3mr05yLq/
2. Hover the 3rd point on a chart where the two lines cross

Expected output:
A line marker for the line on top shows up

Actual output:
A line marker for whichever line came first in series[] shows up.

![screenshot_16](https://cloud.githubusercontent.com/assets/5426427/12716741/0795c140-c8e3-11e5-87c2-4fc0d08ee9d2.png)

**Comment by pawelfus** [comment]
Actually, the series with highest **zIndex** is set on top, with all items corresponding to the series. For example reversed zIndexes: http://jsfiddle.net/3mr05yLq/1/

Anyway, for now, you can use halo to mimic behaviour you expect, for example: http://jsfiddle.net/3mr05yLq/3/

*Internal note:*
I think this is not simple to move marker on top of another series, since those are separate groups in SVG. Maybe instead, halo should contain copy of the marker and halo-path?

**Comment by TorsteinHonsi** [comment]
In previous versions, you were able to follow along a graph with the mouse pointer, and that series (the `hoverSeries`) would take precedence for the tooltip. See http://jsfiddle.net/3mr05yLq/5/. This feature may have been lost when we went over to k-d-tree tooltips.

**Comment by electricessence** [comment]
I'm having the same issue.
