### ISSUE TITLE
maxPadding is not working with 0 and negative values

### ISSUE THREAD

**Issue by brunocontreras** [highcharts/highcharts#4993]
Hi, it was working in version 2.1.6, which is the one i was using before updating.

In the fiddle example you can uncomment the old version to see how it worked

http://jsfiddle.net/csd5y23o/1/

Thnks!

**Comment by pawelfus** [comment]
This is caused by new option `softThreshold`. You can set this to `false`, take a look: http://jsfiddle.net/csd5y23o/2/

**Comment by brunocontreras** [comment]
Nice! it works. Maybe it should be explained in the maxPadding/minPadding documentation. Otherwise, I would have never found the connection between them.

**Comment by pawelfus** [comment]
I am not sure if this expected behaviour. Let's keep this open, okay?

**Comment by TorsteinHonsi** [comment]
I agree with the OP, it is hard to see the connection. I would expect that when I explicitly set a `maxPadding`, it would be respected. We should change the behaviour so that it only applies the `softThreshold` when the `maxPadding` is default. In terms of code, take the padding out of the defaultSettings and instead do a pick where it is applied.

**Comment by kjarnet** [comment]
This also (actually, in my case _only_) applies to minPadding. It would be really nice if this at least was documented in relation to these settings.

**Comment by TorsteinHonsi** [comment]
Thanks for commenting. I first tried fixing the actual behaviour, but it became apparent that it is not a good approach. Different axes have different default `minPadding` and `maxPadding` etc. So instead we keep the current order of precedence, but add information to the docs under `yAxis.minPadding` and `yAxis.maxPadding`.
