### ISSUE TITLE
 error when stacking Area charts 

### ISSUE THREAD

**Issue by mattwang75** [highcharts/highcharts#5010]
I created an example to reproduce it:  http://jsfiddle.net/a0yxuwx1/10/

Series are not rendered.  In Chrome, the console shows this error: "Uncaught TypeError: Cannot read property 'points' of undefined".

If you change the chart type from 'area' to some other type (such as 'line' or 'column'), then my example works fine.  What's so special about 'area' chart type that can't be stacked?

**Comment by TorsteinHonsi** [comment]
The problem here is that `new Date` returns a string, while [point.x expects a number](http://api.highcharts.com/highcharts#series<area>.data.x). It works by accident with line series, but you'll see that the X values are not what you expect.

Here's a sample where I call `.getTime()` on your date objects: http://jsfiddle.net/highcharts/a0yxuwx1/11/
