### ISSUE TITLE
yAxis type logarithmic breaks display of solidgauge

### ISSUE THREAD

**Issue by ajantiss** [highcharts/highcharts#5025]
While trying to have a logarithmic scale on my solidgauge I figured that I was loosing borders, labels and ticks,

see [fiddle](http://jsfiddle.net/q6ou6wdb/)

**Comment by pawelfus** [comment]
Thank you for reporting this! It looks like the bug is a bit deeper: http://jsfiddle.net/q6ou6wdb/1/ - default `gauge` series type doesn't work too.

**Comment by caboose014** [comment]
After playing around with this (I have been looking at Highcharts for a project) It looks like the issues seem to be related to the starting value. My gauge doesn't appear at all if I have the starting value set at 0, but if I set it to 1 it seems to be fine. However the Max value seems to want to max out at 10K rather than the number I specify. http://jsfiddle.net/h9sm75v1/

**Comment by pawelfus** [comment]
@caboose014 thank you for pointing out the issue with minimum! Of course, logarithmic axis can not render 0. It's connected to #5451 pull request.

As for workaround in your case, it may be tricky to render 200 on logarithmic axis, because of rounding numbers in JS, be here is an example for you: http://jsfiddle.net/h9sm75v1/2/
