### ISSUE TITLE
Scatter: mouseOver event of point is called twice

### ISSUE THREAD

**Issue by dou1985dou** [highcharts/highcharts#5046]
For Scatter type series: point's mouseOver event function is executed two times when hovering over a point. It is called one time only when over only one and the same point mouse is over.

the same as #4448

**Comment by pawelfus** [comment]
Thank you for reporting!
Could you update this jsfiddle: http://jsfiddle.net/zp775qfv/4/ to reproduce issue?

**Comment by dou1985dou** [comment]
Hi
add stickyTracking: false 
url:http://jsfiddle.net/dou1985dou/zp775qfv/7/

**Comment by pawelfus** [comment]
Thank you for the example!

**Comment by mzarud** [comment]
Hi @pawelfus,
Is there any update or timeline set out for this issue? I've recently encountered it as well. I also observed the same problem on the bubble chart.

**Comment by pawelfus** [comment]
Could you reproduce issue with bubble series? For me it works fine: http://jsfiddle.net/zp775qfv/9/ - there is another bug with bubble series in 5.0.11 (see: #6705 - where halo steals events from a point).

Regarding the main issue, possible workaround (or a solution):

    Highcharts.seriesTypes.scatter.prototype.directTouch = true;

Demo: http://jsfiddle.net/zp775qfv/10/

I am not sure how this change will affect other series, I need to check this.

**Comment by mzarud** [comment]
Thanks for your reply @pawelfus - here's a fiddle with the issue on the bubble chart:
https://jsfiddle.net/fcph046x/

I don't think issue #6705 is related because if I understand correctly that one refers to click events specifically.

I wanted to mention that in my app I also observed this same problem on the Line chart as well, though I can't seem to reproduce it in a JSfiddle. I debugged it and the root cause is the same - when stickyTracking is false there seems to be an extra event fired.

I'll look into the solution you suggested for now, thank you.

**Comment by pawelfus** [comment]
Thank you for demo, @mzarud. You see two (or even more if you want to) `mouseOver` events because you can actually hover on a marker(bubble) **and** a dataLabel. DataLabel also fires `mouseOver` event.

Maybe you have dataLabels enabled in your line charts and that's the reason why you can observe the same issue in your app.

**Comment by mzarud** [comment]
Hi @pawelfus - looks like you're right about that JSfiddle.

Unfortunately in my app the data labels are not the problem, I still see 2 events fired when they are hidden. I tried your suggestion of setting directTouch to true and it seems to fix this issue for me. It works for scatter, bubble, and line. 

I'm just wondering if you know whether directTouch might have an affect on any other functionality? Would it affect the touch screen interactions?

**Comment by TorsteinHonsi** [comment]
Reverted due to a regression in map point mouseout animation. Needs more work.
