### ISSUE TITLE
Firefox hangs - Highcharts with multiple points

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5048]
Example:
- http://jsfiddle.net/a5o1ohxk/

After chart init, try to edit code in jsfiddle.net. Isolated example (from jsfiddle), also behaves in the same way. 

The problem appears on in Firefox (ie 43.0.3) under OSX (10.11.1), on windows works properly.

Internal note: Error appears in that line: Uncaught TypeError: B[(intermediate value)(intermediate value)(intermediate value)] is not a function, but using new Highcharts.Chart does not solve this problem in FF.

**Comment by soetji** [comment]
I am having the same problem using Firefox 44.0.2 on OSX 10.11.2.

**Comment by TorsteinHonsi** [comment]
I believe this sluggishness comes from jsFiddle (or specifically CodeMirror), that is working on syntax hilighting the JavaScript code. If you run the jsFiddle show page alone, you'll see that it runs fine in Firefox: http://jsfiddle.net/a5o1ohxk/show/.

**Comment by soetji** [comment]
However, in the same jsfiddle & CodeMirror environment and with the same data, highcharts doesn't work but highstock does. So it doesn't look like the issue is with jsfiddle or CodeMirror per-se. Please try the following examples in OSX Firefox:

Highcharts: http://jsfiddle.net/x8rmayx6/1/
Highstock: http://jsfiddle.net/x8rmayx6/2/
