### ISSUE TITLE
dateTimeLabelFormats for Tooltip weeks is broken

### ISSUE THREAD

**Issue by brombomb** [highcharts/highcharts#5055]
While the xAxis correctly respects `week` the Tooltip does not.  I have two examples, one of it working, and one of it broken.

Working example:
http://jsfiddle.net/gt5s4uv6/
Correctly has a Tooltip of `Week of ...` (based on `week` formatter)

Broken Example:
http://jsfiddle.net/06oq4ess/
Incorrectly has a Tooltip of `...` (based on `day` formatter)

The only difference in between the 2 is the UTC Date.  In the first example it's 2013, which Jan 1 is a Tuesday and Jan 7th is a Monday (this also works for example in 2002).  In the second example (and every other year I've tried, that's not a Tuesday) it's set to 2014 which has Jan 1 on a Wed and Jan 7th on a Tuesday.

I am trying to format my tooltips with weekly data and the size of my first "week" may be less than 7 days. For example my Data set is `Last 90 Days`  which makes my first data set [2015-11-19, 2015-11-21]  as of today 2016-02-17, and my second set [2015-11-22, 2015-11-28]

**Comment by oysteinmoseng** [comment]
This is by design, as Highcharts only displays the week format in tooltips if the points are a week apart **and** the day is on the `xAxis.startOfWeek` setting. If you want to override this functionality and show weeks starting from other weekdays, you could either set the `xAxis.startOfWeek` option (also affects xAxis labels), or override the `getXDateFormat` method as follows, to always show weeks in tooltips: http://jsfiddle.net/08tt38zn.

If you want to show the actual start of week in tooltips, but keep the point on other weekdays - you would have to do logic in the tooltip formatter to calculate the last Monday from the point date and display that manually.

**Comment by brombomb** [comment]
The problem I'm running into is that my data series are dynamic based on user input.  Our default values include:

- Last Day (grouped by day)
- Last 15 days (day)
- Last 30 days (day)
- Last 60 days (week)
- Last 90 days (week)
- Last year (month)

So I don't can't override for all situations.  Using just tooltip formatter I have no way of knowing what the next point is to figure out what the range is between the two points.  This would work great if I could use `pointIntervalUnit` of `week` to force an override or `pointIntervalUnit Month` with a `pointInterval` of `.25`.  Also since my graph can be looked at from anyday of the week it seems wrong to set the `xAxis.startOfWeek` option since only my first data point may be short.

**Comment by oysteinmoseng** [comment]
I have to admit that I don't quite follow the details of your scenario, but using `point.series` and `point.index` you should be able to find the next/prev point in the tooltip formatter. If you still need assistance with this, feel free to contact our customer support since you appear to be needing help with a very specific case here.
