### ISSUE TITLE
Scatter plot legend symbols ignore symbol width/height/radius

### ISSUE THREAD

**Issue by brian428** [highcharts/highcharts#5056]
It appears that legend symbol size options are ignored for scatter plot charts.
http://jsfiddle.net/brian428/c6wwL02f/

**Comment by brian428** [comment]
FYI, I think drawLineMarker would need to be changed to correctly use a passed radius?
```
if (markerOptions && markerOptions.enabled !== false) {
    radius = legend.options.symbolRadius || markerOptions.radius;
    ...
```

**Comment by oysteinmoseng** [comment]
Are you looking to change the size of the dot (the marker symbol) in the legend? If so, this is related to issue #3275. 

`symbolHeight` and `symbolRadius` only affect rectangular symbols (see [API documentation](http://api.highcharts.com/highcharts#legend.symbolRadius)).

One possible workaround would be to set a default marker size on the series, and overriding it on each point: http://jsfiddle.net/bc1m1o6n/.

**Comment by brian428** [comment]
Yes, exactly.

I see what you're talking about from the API docs, but it seems strange that symbolRadius would deliberately affect only rectangular symbols. Is there some reason for that decision that isn't obvious? It doesn't make much sense, especially since all that seems to be needed to allow it to affect the scatter legend dots is a tiny change similar to what I showed above.

**Comment by brian428** [comment]
Also, the workaround you mentioned for modifying the points doesn't seem to be an option if the turboThreshold is exceeded, or if the boost module is used (since object-based points can't be used, only arrays).

**Comment by oysteinmoseng** [comment]
`symbolRadius` currently seems to be more of a `symbolBorderRadius`. I do not know the historical reason for this, and absoutely agree with you that we should have an option to change the actual radius in the legend as well.

**Comment by tycup** [comment]
Hey! Very interested in this feature + the ease of customising the legend symbols across chart types including control over dimensions and symbols. This is particularly valuable to design system teams who need to drive consistency across chart types and their designs.

Specifically to this issue, this problem is also present on your documentation site; https://www.highcharts.com/demo/highcharts/scatter-boost if you turn legend on, the legend icon is well, 1px in size and hardly visible. 

I'd like to reopen this issue - and in general, always happy to provide feedback from a design system perspective.

**Comment by oysteinmoseng** [comment]
Thanks a lot for the feedback, and please let us know if you think of other things as well! Any other use case where it's currently tricky to customise the legend symbols for example would be good to know.

Let's reopen this specific issue for starters. The way the current API works, I would expect `symbolHeight` to set the size of the marker (as myself 9 years ago noted above, `symbolRadius` is more of a `symbolBorderRadius`). That doesn't appear to change the legend marker symbol, though, which seems like a bug most likely.

Example: https://jsfiddle.net/db5qs2zj/ 

@TorsteinHonsi thoughts on this?

**Comment by TorsteinHonsi** [comment]
@oysteinmoseng I think it's a good idea, to be honest I have sometimes wanted more flexibility here myself. We probably need events around `drawLegendSymbol`, and also destructor events. Probably a little refactor is needed so that implementers can add as many SVGElements as they want, and make sure they are being colorized, destroyed etc.

**Comment by TorsteinHonsi** [comment]
> I would expect `symbolHeight` to set the size of the marker (as myself 9 years ago noted above

@oysteinmoseng The reason why that wouldn't work is because this legend symbol is only a marker, designed to match the size and shape of the series marker. To illustrate, take the vanilla line series with a marker: https://jsfiddle.net/highcharts/pd312yn0/ . Here the `symbolWidth` is default, but as we can see the symbol consists of more than just the marker, it also shows the line. So if we were to make the marker full `symbolWidth` and `symbolHeight`, we wouldn't see the line.

@tycup For that reason, the default legend symbol is probably not the best for the special boost case. If we change it to `rectangle` (which is rendered as a circle because of rounded corners), it provides more information: https://jsfiddle.net/highcharts/9Leohqwb/

**Comment by oysteinmoseng** [comment]
So after a bit of discussion we propose the following:

1. Offer some events to hook onto, as proposed by Torstein above.
2. Expand on the `series.legendSymbol` option to take not just a string (with predefined symbol types), but an object that also includes a subset of series options (such as `marker`).
```js
legendSymbol: {
  symbol: string, // Replacing today's legendSymbol string option

  // The rest would be a subset of series options
  lineWidth: number,
  color: ColorType,
  marker: {
    symbol: string,
    fillColor: ColorType
    ...
  }
}
```

This would make the legend symbol styling significantly more flexible, hopefully just reusing existing internal logic. For example, we would be able to set a higher color opacity on the legend symbol marker, which seems to be a recurring need.

Feel free to chime in with any thoughts.

**Comment by tycup** [comment]
Hey, 

Apologies for the delayed response.

+1 on setting color opacity. The above feels more like what I'd expect from the API and definitely increases the flexibility positively.

Thanks for addressing.

**Comment by AndrzejBuleczka** [comment]
Hi @tycup , as a quick update you can already set the color and opacity (if you pass rgba) of the legend symbol via this api option: https://api.highcharts.com/highcharts/plotOptions.series.legendSymbolColor
