### ISSUE TITLE
Activity Gauge - Outer bar gets cut when using 6 or more data points

### ISSUE THREAD

**Issue by Enviii** [highcharts/highcharts#5059]
Example: http://jsfiddle.net/dkarkar/rugqpt37/1/ (forked from the demo)

I've tried modifications to the margin and to the container width/height. If you can fix the top/bottom from being cut off, the left and right sides get cut off. There seems to be no way to get all 4 sides of the outer ring to show properly. 

I've tried 500 height/width and various margins from 50-150. The end result is there is at least one side that is always cut off. It makes no sense because when inspecting the element there is clearly enough space.

**Comment by oysteinmoseng** [comment]
This is because the `borderWidth` of the gauge series is hardcoded to 18.5, which in the case of a 400x400px container is too much for this amount of series. You could either [reduce the borderWidth](http://jsfiddle.net/rugqpt37/3/), or [increase the container size](http://jsfiddle.net/rugqpt37/2/).

**Comment by TorsteinHonsi** [comment]
Just a note for enhancement - it would be optimal if Highcharts did this by default, so that multiple points/series were laid out automatically.
