### ISSUE TITLE
Crosshair only appears when mouse is hovering over a point

### ISSUE THREAD

**Issue by tomascassidy** [highcharts/highcharts#5066]
http://jsfiddle.net/q5qw4wma/1/
This fiddle is just the demo from http://www.highcharts.com/maps/demo/mappoint-latlon with crosshairs enabled on xAxis/yAxis.

The crosshair is only appearing when the mouse is hovering over a mappoint.

Before the crosshair configuration was moved from tooltip to Axis, the crosshair would appear underneath the mouse pointer at all times when moving the mouse over the map.

**Comment by jon-a-nygaard** [comment]
Thanks for reporting. We will look into this as soon as possible.

**Comment by TorsteinHonsi** [comment]
It is not a specific Highmaps issue. [This fiddle](http://jsfiddle.net/highcharts/6tnhx61a/) shows the same problem with a vanilla column chart.

_Internal note_:
The bug lies in https://github.com/highcharts/highcharts/blob/v4.2.3/js/parts/Pointer.js#L235-L245. The code does not run `drawCrosshair` unless there is a hoverPoint or kdpoint. But when snap is false, it should run under any circumstance.
