### ISSUE TITLE
Highstock with only scrollbar is stuck until redraw

### ISSUE THREAD

**Issue by dugokontov** [highcharts/highcharts#5071]
When I create a highstock with only scrollbar and set a range that displays 4 or less points, scrollbar can't be panned. You can only click somewhere else on scrollbar to jump left or right. If you resize chart this behavior is fixed and everything works as expected.

I have tested this with highstock 4.2.3, Chrome 48.0.2564.116 (64-bit) on Linux.

Here is jsfiddle where you can see the bug:
http://jsfiddle.net/52seb35w

Also, I have forked your demo example and instead of 3 months range I set it to 4 days
http://jsfiddle.net/zLxn7jqz/

**Comment by pawelfus** [comment]
Hi,

Thank you for reporting. It looks like a problem with `xAxis.range` option. Works fine when setting `xAxis.min` and `xAxis.max`: http://jsfiddle.net/52seb35w/2/

**Comment by dugokontov** [comment]
@pawelfus this is nice workaround. thx!

**Comment by TorsteinHonsi** [comment]
Not really a fix here, but the problem is that the `range` option is smaller than the automatically calculated `minRange`, so the scrolling fails [here](https://github.com/highcharts/highcharts/blob/v4.2.3/js/parts/Scroller.js#L338-L341).

The __workaround__ is to set a lower `minRange`. [View it on jsFiddle](http://jsfiddle.net/highcharts/52seb35w/3/).

**Comment by pawelfus** [comment]
Works fine in 5.0.12
