### ISSUE TITLE
Pie: size and innerSize - unable to get same percent

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5083]
**Problem:** When setting size and innerSize in percent - not able to get same size.

size is relative to the plot area and innerSize is relative to the pie size. If size is set to `'100%'` I would expect relative to the pie will be same as relative to the plot area. 

**Example:** http://jsfiddle.net/6b7mkkzd/1/

( Advanced example: http://jsfiddle.net/Lggngyzu/2/ )

**Comment by TorsteinHonsi** [comment]
What you see is the 10 pixels reserved for slicing the pie, so when a pie is sliced, it will extend out to the plot area.

#### Workaround
Set `slicedOffset` to 0. [View it live on jsFiddle](http://jsfiddle.net/highcharts/6b7mkkzd/2/).

But I have to admit that this doesn't make sense in this case. Perhaps we should skip the reserved space when the width is explicitly set?

**Comment by alumni** [comment]
I have a similar issue with pie chart: the inner size of the bigger donut does not match the size of the smaller donut, even though they are set to the same value. It does not always happen, but there is an example below when it does. Setting `slicedOffset = 0` does not help.

**Example:** https://jsfiddle.net/78jwevz6/

**Comment by pawelfus** [comment]
Hi @alumni 

The problem is with `innerSize` - it's not related to the plot area, but to the `size`. For example `innerSize: 50%` means 50% of the `size` option, see [docs](https://api.highcharts.com/highcharts/series.pie.innerSize). You can calculate innerSize for the middle pie this way: https://jsfiddle.net/BlackLabel/637ywv48/
