### ISSUE TITLE
Tree /parent-child relationship structure in bar chart 

### ISSUE THREAD

**Issue by hrharshrathi** [highcharts/highcharts#5098]
Hello Team,
Please provide the **Tree /parent-child relationship structure in a bar cart.**
for reference please check attachment.
please provide sample code ASAP
**Thankyou**
![forum](https://cloud.githubusercontent.com/assets/16932060/13518515/ccafc9ba-e1f4-11e5-853e-f62b7cf2c229.jpg)

**Comment by TorsteinHonsi** [comment]
Hi, Thanks for your suggestion! This is our issue tracker. For feature requests, please see http://highcharts.uservoice.com.

**Comment by NidhiNagarro** [comment]
I have a similar requirement. do we any solution on this yet

**Comment by TorsteinHonsi** [comment]
@jon-a-nygaard This relates to the treegrid module doesn't it?

**Comment by jon-a-nygaard** [comment]
@TorsteinHonsi In some way it does, because it can very well utilize the same hierarchy logic as we use in Treemap and TreeGrid. We can probably create something like in the image below with the use of TreeGrid or Grid Axis, and Bar Chart.
I made some effort to create a simple demo of this, but ran into an issue with Grid Axis which will have to be fixed first.
![Image of a hierarchical bar chart](http://www.theinformationlab.co.uk/wp-content/uploads/2014/12/2-1-bar-chart-with-sales.png)

**Comment by adamcooper94** [comment]
@jon-a-nygaard Do you have a JSFiddle of that example chart?

**Comment by adamcooper94** [comment]
Great, that's exactly what I wanted. Thanks @jon-a-nygaard
