### ISSUE TITLE
Single point marker is not displaying 

### ISSUE THREAD

**Issue by stimcon-dev** [highcharts/highcharts#5099]
Hi,
I have set marker but it's not displaying when there is only single data available.
When we hover on chart then data point is displaying.
see sample fiddle here
http://jsfiddle.net/c4M6D/4/

Thanks in advance

**Comment by pawelfus** [comment]
Thanks for contacting us.
It is interesting case. Because of many points, Highcharts hides markers when there is to many of them. In fact most of the points are nullified, so theoretically we shouldn't do that. For example wider chart works fine: http://jsfiddle.net/c4M6D/7/

I suggest to set `marker.enabled` to true, see: http://jsfiddle.net/c4M6D/9/
