### ISSUE TITLE
Tooltip with documentation default style broke the element

### ISSUE THREAD

**Issue by xavadu** [highcharts/highcharts#5121]
Hello,

I wanted to change the z-index of the tooltip, i see in the documentation the _tooltip.style_ option will do what i trying to accomplish:  http://api.highcharts.com/highstock#tooltip.style

If i add a new css style values there, it overwrite the default values. So i wanted to copy the default values, to keep the toolip as it is, and add my extra styles, but i found that the default values are not correct, they broke the tooltip element.

Here is a jsfiddle http://jsfiddle.net/vnzzgvpc/

Thanks,
J.

**Comment by TorsteinHonsi** [comment]
Thanks for writing, but please keep in mind that this is our bug tracker. For general tech support, please see www.highcharts.com/support.

> I wanted to change the z-index of the tooltip, i see in the documentation the tooltip.style option will do what i trying to accomplish

I'm afraid it won't, because SVG doesn't support z-index by CSS.

> If i add a new css style values there, it overwrite the default values.

Not correct, it will be added in addition to the default ones.

> i found that the default values are not correct,

You tried to add a string, not an object. See http://jsfiddle.net/highcharts/vnzzgvpc/1/

**Comment by xavadu** [comment]
Oh, I see, the assignation was bad, i believe that it was a bug, 
Thanks.
