### ISSUE TITLE
Boost module area chart 

### ISSUE THREAD

**Issue by onemenny** [highcharts/highcharts#5136]
The boost module is been lacking area chart abilities since inception. It's kind of ridiculous to draw area chart without the line, and there seems to be no progress in this area. 

This is realy annoying when you have mixed charts: line + area, or column + area. In these situation the boost module is just unusable leaving no option but to keep using the slow SVG renderer 

What is the status of this

**Comment by TorsteinHonsi** [comment]
Thanks for your suggestion! We dropped the line on areas in order to increase performance, but if this is an important feature, we can always try to add it. We would have to do some changes in the Boost module then, because suddenly we are drawing with more than one stroke and fill in the same canvas.

Here's how you can work around it by adding a linked series: http://jsfiddle.net/highcharts/fvjev0az/

**Comment by onemenny** [comment]
I see where you are going, I dont want/think a workaround is a good solution since I already have a business logic for handling many (various) series inside a single chart. So adding an additional series and than handling it will add over complexity. More ever, Switching between SVG and boost will cause additional headache

**Comment by TorsteinHonsi** [comment]
We can't just do it the same way here, for example we need to consider gaps for null points. But probably the performance impact wouldn't be too heavy.

**Comment by onemenny** [comment]
More of a reason for this to be added to the boost module instead of drawing line+area, beside area should be a first class citizen it's very common...

**Comment by TorsteinHonsi** [comment]
On the other hand, one of the reasons why I left it out in the first place, is that the area line is not very useful in a plot with thousands of points. Take [this chart for instance](http://jsfiddle.net/highcharts/fvjev0az/), it would actually be more readable [without the line](http://jsfiddle.net/highcharts/fvjev0az/1/). Currently, the line appears when you zoom in below the `boostThreshold`, which makes sense because you can't distinguish the individual points until you zoom in anyway.

**Comment by onemenny** [comment]
@TorsteinHonsi you are right about the visibility, but in my use case, I set the threshold to 1 cause: 

1 - I don't want any glitches when switching to svg, many charts may zoom simultaneously, and I suspect that it would cause adding/removing elements from the DOM

2 -  I noticed (I may be wrong) that chart destroy operation is significantly faster when using canvas vs svg

3 - I suspect that if the chart holds many series (more than 20 lets say) canvas will preform faster than svg

What do you think?

**Comment by TorsteinHonsi** [comment]
1. I don't think it should be a problem, unless you have observed problems with it. In SVG mode, each marker is added as a separate element, but the performance overhead is neglectable until we start rendering thousands of markers.

2. Apparently you're right about that, see http://jsfiddle.net/3dxkuwhz/. With boost, the chart is destroyed in ~8ms, without boost it takes ~20ms. One series, 1000 points.

3. That's not correct, as we saw in a different issue (don't remember which). It turned out that with a lot of series, the Boost module actually is slower than in vanilla SVG mode.

**Comment by onemenny** [comment]
Thank you for your input @TorsteinHonsi,
We barely use markers on charts so this is not an issue for us, but consider that we display ~20-40 charts each with ~10-20 series (sometimes more) - We did notice that tooltip performance is much better in canvas even when each series is ~400 points. Considering the above and that you confirm the destroy overhead, my instincts would be using pure canvas without the threshold (threshold=1). So maybe we can go with a solution that once there are x points the line will render in area chart, as user config option? although this does not seem elegant as full implementation. 

Having said that, I do want to check point 3, if you have any reference I would appreciate it.  

Just to be clear, The boost threshold breaches if any of the series has more points than the threshold?
