### ISSUE TITLE
Long legends items require more than one click

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5141]
Long legends that have ellipsis require more than one click to toggle on
and off. 

Example: 
- http://jsfiddle.net/ocfmwyrv/

**Comment by TorsteinHonsi** [comment]
It also happens to shorter labels, as long as the `textOverflow: 'ellipsis'` is set in the first place: http://jsfiddle.net/highcharts/ocfmwyrv/1/

**Comment by pawelfus** [comment]
**Workaround:**

Demo: http://jsfiddle.net/p2tf4g5q/

Snippet:

    (function(H) {
      H.wrap(H.Legend.prototype, 'colorizeItem', function(p, item) {
        p.apply(this, [].slice.call(arguments, 1));
        if (item.legendItem) {
          item.legendItem.css(this.options.itemHoverStyle);
        }
      });
    })(Highcharts);

*Internal note:*

After some debugging:

- `click` event has this issue, but changing to `mousedown` resolves it (okay.. :) )
- looks like issue is in `colorizeItem` method. When disabling line: `legendItem.css({ fill: textColor, color: textColor }); // color for #1553, oldIE` everything goes right. 

I think this may be caused by rebuilding text with `ellipsis` style in `css()` method (we append new tspan's, while removing old ones). When we click on an item, `mouseover` is called first, then on the second click we get `click` event.

**Comment by sebastianbochan** [comment]
The issue seems to be fixed since 6.2.0. If problem will appear again, please reopen the ticket.
