### ISSUE TITLE
Highcharts pixel rounding width

### ISSUE THREAD

**Issue by 719media** [highcharts/highcharts#5153]
Hello

When creating a simple chart without specifying width (so that it just fills the parent container width), if the parent container width is subpixel (e.g. 100.5 pixels), the svg container just rounds the width (e.g. to 101 pixels).

For example:

https://jsfiddle.net/orz94ezc/5/

This normally happens when the width is desired to be 100%, but the height is variable, such that the width comes out at different pixel widths.

The overflow: hidden on the container means this usually just means that 0.5 pixels of the svg are hidden from view, but when doing things in flexbox, is causes wrapping issues. Regardless, even if it wasn't, we should have the svg match, no reason to have unusual rounding!

This causes two width:50% containers in my setup to be wrapped to different lines if the browser window happens to fit to a subpixel amount, as the 0.5 rounding up throws them off.

Please fix!

Thanks!!!!

**Comment by pawelfus** [comment]
I think this may be connected to the specific browser (and version). I just tested on latest Chrome (osx) and it works (rounds down): 

![screen shot 2016-03-25 at 16 10 54](https://cloud.githubusercontent.com/assets/1453926/14046841/4db6b6a8-f2a4-11e5-934c-46871f0be5da.png)

Maybe you could create example, with static width for the body container to mimic specific width of the browser, but with percentage width (instead of 400.5 pixels wide)? 

Btw, as I know, browsers truncate/round pixel widths anyway when using percentage width.

**Comment by 719media** [comment]
I've tried to make a little more verbose fiddle, and remove jquery so there's less to look at:

http://jsfiddle.net/orz94ezc/19/

What happens to me, in the latest Firefox 45.0.1 (on Mac) is the following in output the fiddle:

Container 1 width was: 200.5, now: 200.5, SVG width: 201
Container 2 width was: 200.5, now: 200.5, SVG width: 201 

On the latest Chrome 49.0.2623.108 (on Mac), I get

Container 1 width was: 200.5, now: 200.5, SVG width: 201
Container 2 width was: 200.5, now: 200.5, SVG width: 200
(note last svg width, interesting)

Both of these browsers are capable of "sub-pixel rendering", but even if they weren't, the problem is still present.

Now, in the fiddle above, the worst that happens is that the svg is some pixel amount < 1 larger than the parent container. Not a huge deal, but I think still an error nonetheless, and why not strive to make it correct if it can be, right?

However, if we are using flex with flex-wrap:warp, then it becomes a problem (in Firefox). See

https://jsfiddle.net/orz94ezc/18/

And then change the 401px width to 400px and notice the problem no longer persists.

The root of this issue is that the svg calculation is just rounding to the nearest pixel, when this is no longer sufficient in modern browsers.

So... what is the best solution? One solution might be use to boundingRect instead of whatever you are using to set the widths on the svg and container to get a more accurate pixel dimension. Other solutions?

**Comment by TorsteinHonsi** [comment]
#### Possible solution

Notes from #6823:
 * Use `getComputedStyle(el).width` (returns sub pixel size) instead of `el.offsetWidth` (rounds up to nearest integer) in js/parts/Utilities.js to get the correct width (and the same for height).
 * Setting overflow: hidden works around the problem in some cases but is not really a reliable solution
 * `el.getBoundingClientRect().width` should work also with the downside that it will take transforms into account
 * When the container has padding, the padding is substracted from the computed style.
 * The computed style is a string, need to cast to number.

**Comment by vbougay** [comment]
Spent a day today trying to figure out a root cause and then fix this issue. Luckily found that discussion thread finally. The solution with overflow: hidden for parent div worked for me.

It's a bug clearly and has to be fixed. Especially taking into account that fix is pretty straightforward.

**Comment by bemol** [comment]
I'm not sure if something has changed recently in the browsers that most of the people was satisfied with the solution included here https://github.com/highcharts/highcharts/commit/02b559d0de3dfcc86816fc526fe9e98b9f85bb5a, but this is is still not a valid solution and the problem still occurs.
I'm using grid with following setup:
```
.grid-column {
  grid-auto-flow: column;
  display: grid;
  grid-auto-columns: 1fr;
  grid-auto-rows: 1fr;
  gap: 8px;
}
```
I have two divs and their width is calculated to be `1215.5px`. Highcharts with current implementation rounds it down to `1215` and in my case it is not acceptable because I have different background colors and this `1px` makes difference. When I changed each necessary Highcharts element (`div.highcharts-container`, `svg`, `viewBox` and `rect.highcharts-background` to be `1215.5` everything seems to be fine.
![image](https://user-images.githubusercontent.com/2674705/166295483-acbc0b36-8553-48d5-b6bf-8a9c9610ccc0.png)
