### ISSUE TITLE
JPEG and PDF offline exporting

### ISSUE THREAD

**Issue by ulrik59** [highcharts/highcharts#5157]
The offline-exporting module is a great tool but unfortunately it only support PNG and SVG. Is there a possibility to add JPEG and PDF support ?
Also, adding offline-exporting module remove JPEG and PDF buttons... Could we add an options to display these buttons even if the exports is not offline ?

**Comment by pawelfus** [comment]
*Internal note:*

I am not sure about exporting anything, using JS, to PDF ([jsPDF](https://github.com/MrRio/jsPDF) ? looks problematic for SVG), but for JPEG, can we add type `canvas.toDataURL("image/jpeg")`, [ref](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL)?

**Comment by ulrik59** [comment]
I used to export with [highcharts-export-clientside](https://github.com/A----/highcharts-export-clientside) and it has PDF support with jsPDF.
Apparently there is a method `addImage()` where you can give a canvas in arguments but it's not documented...
Maybe add JPEG support and an option to display PDF button (PDF export will be done by the server) ?

**Comment by TorsteinHonsi** [comment]
* __JPEG:__ We are planning to add that as described by Pawel above. @oysteinmoseng

* __PDF:__ On an earlier occasion we investigated using jsPDF, but as noted above, it has poort support for SVG. The PDF suppport in "highcharts-export-clientside" is not optimal - it just sends a raster image that is embedded into PDF. In our opinion the point of exporting to PDF is to preserve the vector quality of the SVG graphics, so we didn't go that route. In order to include _vectorized_ PDF support, we would have to either create our own implementation, contribute to jsPDF or look for other similar solutions with SVG support.

@ulrik59 Here's how you can inject a server-based PDF export into the menu items: http://jsfiddle.net/highcharts/cw8j4nva/

**Comment by grahamscott** [comment]
>JPEG: We are planning to add that as described by Pawel above. @oysteinmoseng

Is there a proposed release for this enhancement?

**Comment by TorsteinHonsi** [comment]
@oysteinmoseng

**Comment by oysteinmoseng** [comment]
@grahamscott: I'll take a look at it this week, so it should be part of the next official release.

**Comment by grahamscott** [comment]
ah amazing, thank you 👍

**Comment by oysteinmoseng** [comment]
Closing this and moving PDF discussion to separate issue.
