### ISSUE TITLE
Navigator handles get stuck

### ISSUE THREAD

**Issue by alvarezguille** [highcharts/highcharts#5170]
Click and drag one of the handles outside of the chart so that mouseup happens outside the chart.
Can be tested in http://jsfiddle.net/alvarezg/rnxp4h8b/ by doing mouseup in css region of jsfiddle.

**Comment by TorsteinHonsi** [comment]
More precicely, it gets stuck when the the mouseup happens outside the _page_. In jsFiddle, this happens because the preview runs in an iframe. If it were all in the same page, it would work. 

#### Workaround
Add this snippet to listen for document mouseleave:
```js

	$(document).bind('mouseleave', function (e) {
    	Highcharts.each(Highcharts.charts, function (chart) {
        	if (chart && chart.scroller) {
            	chart.scroller.mouseUpHandler(e);
            }
        })
    });
```
View it [live on jsFiddle](http://jsfiddle.net/highcharts/rnxp4h8b/1/).

**Comment by alvarezguille** [comment]
You're right, it's when leaving the page.
The patch doesn't feel natural when leaving and coming back while holding the mouse button, since mouseleave is handled as mouseup, and I would expect it to continue dragging the handle in this case.
Thanks for the quick feedback!

**Comment by TorsteinHonsi** [comment]
> I would expect it to continue dragging the handle in this case.

You could add mouseup listeners to other windows/frames as well, but it would probably become ugly. And wouldn't work cross-site.

**Comment by Peppe** [comment]
Could you possibly do it with a mouseenter when mouse returns to page, and somehow still figure if the mouse button is down or not? Just thinking out loud..

**Comment by TorsteinHonsi** [comment]
That's a strong point! The `e.buttons` property, at least in Chrome, holds this information. Proof of concept: http://jsfiddle.net/highcharts/rnxp4h8b/2/

**Comment by nitinthewiz** [comment]
Regarding this issue - I've noticed this in nwjs as soon as the navigator is clicked. I suppose the way nwjs is made, there is some discord between the  original window/frame and what is visible. Because of this, I don't even need to drag the mouse out of the window. 

As soon as I click the navigator, the handle gets stuck to the mouse.
