### ISSUE TITLE
Unwanted gap of line series when using column series with pointRange

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#5183]
Hi,

It looks like when chart have more than one series, for example line and column series, setting pointRange parameter of column series affects line series as well. It can cause situation, when line series will end before the end of plotArea. 

Here you can see an example how it work:
http://jsfiddle.net/2b6s3dvq/2/

Here I have made an image of this issue:
![image](https://cloud.githubusercontent.com/assets/15050812/14287986/3d1d3542-fb55-11e5-8400-3709833a76c3.png)

The problem exists even when column series is hidden:
![image](https://cloud.githubusercontent.com/assets/15050812/14288005/572e23f6-fb55-11e5-9c79-ba26290e8299.png)

Kind regards.

**Comment by Ivan-Perez** [comment]
And the same occurs when you zoom in:

![zoom-in](https://cloud.githubusercontent.com/assets/3533970/14308567/3e3b617e-fbd7-11e5-903a-3723f6ac18dd.PNG)

The temperature line ends before the plot area, but the rainfall column is painted till the end.

**Comment by TorsteinHonsi** [comment]
Simplified demo: http://jsfiddle.net/highcharts/2b6s3dvq/5/

It is expected that the pointRange applies to all series, otherwise the plot area would cut off the columns. What is not necessary (in the simplified demo) is that the pointRange is added _when the other series exceeds the point range from the column series_.
