### ISSUE TITLE
In drilled down pie, chart, point object is always null in click event

### ISSUE THREAD

**Issue by nigamg** [highcharts/highcharts#5192]
Please see the following fiddles-
1. http://jsfiddle.net/gLkmxxu3/ (this one is with drilldown data and point object is always null).
2. http://jsfiddle.net/gLkmxxu3/1/ (this one is non drilldown and point object is always null).

I need to get parent slice while drilling down. Please let me know if I am doing something wrong as I checked almost all the forums and couldn't find the solution.

**Comment by TorsteinHonsi** [comment]
In your first fiddle, the `Point` object is there, but all the properties are nulled out (image below). It is because the click event fires after drilldown, which destroys the parent point. If you want to access information on the point, you can hook up to  the `chart.drilldown` event: http://jsfiddle.net/highcharts/gLkmxxu3/2/.

![skjermbilde 2016-04-08 kl 10 10 19](https://cloud.githubusercontent.com/assets/227836/14377836/32703fbc-fd72-11e5-87ea-02cdb2d34fa2.png)

**Comment by nigamg** [comment]
yeah, I realized that later and used drilldown event. Thank you though. 
You guys are doing awesome job, keep the good work going.

**Comment by TorsteinHonsi** [comment]
Thanks, and you're welcome!
