### ISSUE TITLE
Axis label SVG <title/> element text is repeated when label includes a <br /> tag and is truncated.

### ISSUE THREAD

**Issue by jbgarr** [highcharts/highcharts#5211]
If an axis label includes a `<br />` tag in it and the text is long enough to get truncated, then the SVG `<title/>` tag that is created includes repeated text. I have included a jsFiddle of an example here: http://jsfiddle.net/jbgarr/u4oc0x54/

In order to reproduce the issue make sure the browser window is skinny enough so that both lines of the Friday... label are truncated. In Chrome V49.0.2623.110 the title is then rendered as a tooltip that includes the repeated text. It can also be seen by inspecting the element in the dev tools.

**Comment by TorsteinHonsi** [comment]
**Normalized demo**
If we set the chart width to 350px it reproduces: http://jsfiddle.net/highcharts/u4oc0x54/5/

**Comment by jon-a-nygaard** [comment]
This issue will be fixed in the next maintenance release. For those in need of a workaround, have a look below.


__Workaround__
Open the source file e.g `highcharts.src.js` in a text editor. Search and locate the function `buildText` Look for the following part around [line 1600](https://github.com/highcharts/highcharts/blob/43661c2101d4e56c8157951645fe00bbc1477fdf/js/parts/SvgRenderer.js#L1600-L1602)
```javascript
if (wasTooLong) {
	wrapper.attr('title', wrapper.textStr);
}
```
and replace it with the following part
```javascript
if (wasTooLong && lineNo === 0) {
	wrapper.attr('title', wrapper.textStr);
}
```
