### ISSUE TITLE
Columns overlap with absolute x values

### ISSUE THREAD

**Issue by Theriault** [highcharts/highcharts#5219]
If I specify absolute x values inside the data, columns overlap even though it seems like they shouldn't.
#### Expected behaviour

http://jsfiddle.net/7r9p4aqa/ - adding a fake series with 2 null values causes the bars to not overlap - what I expect to happen without the fake series.
#### Actual behaviour

http://jsfiddle.net/re6yzyjL/1/ - bars overlap

**Comment by jon-a-nygaard** [comment]
_Internal note: Simplified demo http://jsfiddle.net/jon_a_nygaard/7r9p4aqa/1/_

**Comment by TorsteinHonsi** [comment]
It happens because when determining the column widths,  Highcharts only looks at the closest points for the series one by one instead of all together. 

Here's a drop in fix that modifies the X axis to look at all X data: 
http://jsfiddle.net/highcharts/7r9p4aqa/2/

The downside with this is that it would decrease performance on long data series, but perhaps we could add an option for it.

**Comment by pawelfus** [comment]
How about simply setting `series.pointRange`? For `categories` it should always be `1`, right? Demos:

- http://jsfiddle.net/re6yzyjL/3/
- http://jsfiddle.net/7r9p4aqa/3/

**Comment by TorsteinHonsi** [comment]
Yes, that's right.

**Comment by KoltonG** [comment]
@TorsteinHonsi I am still having an issue with this since when I change the pointRange to be 1 its changes all the width of my bar charts. Is there a fix in motion for this?

**Comment by TorsteinHonsi** [comment]
@KoltonG What's your use case? If you want different pointRange settings for each of your series, you can do that...
