### ISSUE TITLE
Polar chart data series are misaligned

### ISSUE THREAD

**Issue by ejain** [highcharts/highcharts#5220]
Noticed a display glitch in certain polar charts after upgrading to 4.2.4 (with the current version of Chrome, and Firefox looks similar).

![polar](https://cloud.githubusercontent.com/assets/1323903/14575895/d191e134-0319-11e6-8935-79a167ecb98c.png)

The following error is thrown at https://github.com/highcharts/highcharts/blob/v4.2.4/js/highcharts.src.js#L3268: Uncaught InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': '0' is not a valid attribute name.

**Comment by aledand** [comment]
I've noted the similar problem, so I comment here avoiding to open another issue.

My chart is dynamically updated every x seconds. At the first run data are assigned with setData and redraw and everything works fine. Since 4.2.4, when the same piece of code is called the second time I get the error reported by ejain and the polar is not re-drawn. If I comment the "polar:true" the error disappear and everything works smoothly.

**Comment by TorsteinHonsi** [comment]
@oysteinmoseng This is the same as the other one, right? Check for regressions, it's probably a new issue.

**Comment by oysteinmoseng** [comment]
http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/polar/

Steps to reproduce: 
1. Resize browser window until graphics are misaligned and error is thrown

**Comment by TorsteinHonsi** [comment]
Fails since d2b1113
