### ISSUE TITLE
Synchronized scatter series problem

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#5222]
Hi,

It looks like synchronized charts demo from Highcharts site doesn't work well with scatter series type. I think that synchronization should be similar to line/area type of series.

Actual behaviour is that sometimes wrong points are triggered. I think that this problem can be caused by searchPoint method.

Here I have made live example of this issue:
http://jsfiddle.net/7Lhsb00g/25/

To recreate issue, try to hover over second point on second chart and see the selected point of first chart.

Here I have made short gif showing this issue:

![animation](https://cloud.githubusercontent.com/assets/15050812/14583819/f9dc0d9e-042d-11e6-8706-48ebbe599ad6.gif)

Kind regards.

**Comment by TorsteinHonsi** [comment]
One of the differences between a line series and a scatter series is that the scatter series tooltip is shown on the _absolute closest_ point, which the line series tooltip is shown on the _closest point in the X dimension_. The rationale behind this difference is that a scatter series usually shows random, scattered data, while a line series usually shows linear, ordered data.

There are two possible ways to fix this.
1. Since in the demo above we are actually dealing with linear, ordered data, we can use a line series and set `lineWidth` to 0: http://jsfiddle.net/highcharts/7Lhsb00g/27/
2. Or, we can tell the scatter series to look for the closest point only in one (X) dimension: http://jsfiddle.net/highcharts/7Lhsb00g/26/ .

**Comment by Izothep** [comment]
Thanks for your help!
