### ISSUE TITLE
Highstock scrollbar issue with single point

### ISSUE THREAD

**Issue by stimcon-dev** [highcharts/highcharts#5228]
When only one point is plotted on graph than date range scroll is not working but still if i try to scroll at edge's it's changing the position of point in Graph.

Can I stop this changing the position of point in graph ?

check fiddle here [jsfiddle](http://jsfiddle.net/pxCsX/24/)

Thanks

**Comment by jon-a-nygaard** [comment]
@stimcon-dev Thanks for reporting. I am currently working on this issue and will come back to you as soon as I know some more.

_Internal note: [simplified demo](http://jsfiddle.net/jon_a_nygaard/oL9Lz78m/2/)_

**Comment by jon-a-nygaard** [comment]
This issue will be fixed in the next maintenance release. For those in need of an immediate fix, have a look at the workaround below.

__Workarounds__
Alternative 1: Drop in an override of getUnionExtremes before a chart is created, like in this [example](http://jsfiddle.net/jon_a_nygaard/oL9Lz78m/)

Alternative 2: Open you source file `highstock.src.js` in a text editor. Search for the function `getUnionExtremes` and replace it with the following code
```javascript
getUnionExtremes: function (returnFalseOnNoBaseSeries) {
	var baseAxis = this.chart.xAxis[0],
		navAxis = this.xAxis,
		navAxisOptions = navAxis.options,
		baseAxisOptions = baseAxis.options,
		ret;

	if (!returnFalseOnNoBaseSeries || baseAxis.dataMin !== null) {
		ret = {
			dataMin: pick( // #4053
				navAxisOptions && navAxisOptions.min,
				numExt(
					'min',
					baseAxisOptions.min,
					baseAxis.dataMin,
					navAxis.dataMin,
					navAxis.min
				)
			),
			dataMax: pick(
				navAxisOptions && navAxisOptions.max,
				numExt(
					'max',
					baseAxisOptions.max,
					baseAxis.dataMax,
					navAxis.dataMax,
					navAxis.max
				)
			)
		};
	}
	return ret;
}
```

**Comment by stimcon-dev** [comment]
@jon-a-nygaard  Thank you very much.
You guys are working superb.

**Comment by jon-a-nygaard** [comment]
@stimcon-dev Thanks, glad I could be of help.
