### ISSUE TITLE
Smaller pie size wit right aligned legend

### ISSUE THREAD

**Issue by dadza** [highcharts/highcharts#5229]
In 4.0.4, a pie chart with a top right legend displayed a tall pie, positioned towards the left:
http://jsfiddle.net/7appg60v/5/

In 4.1.0 and 4.2.4, the same chart displays a smaller (but horizontally centered) pie:
http://jsfiddle.net/7appg60v/6/
http://jsfiddle.net/7appg60v/7/

The layout of the chart in 4.0.4 seems better than the one in 4.1.0.

**Comment by TorsteinHonsi** [comment]
It happens since 769cc90.

You can see what happens if you enable a `plotBorderWidth`. 

* In 4.0, a legend in the corner of the chart would reserve space on the side: http://jsfiddle.net/highcharts/7appg60v/8/.
* Since 4.1, if the layout is "horizontal" (default), a legend in a corner will reserve space on the top or bottom: http://jsfiddle.net/highcharts/7appg60v/9/

You can control this by setting the `layout` to `vertical`: http://jsfiddle.net/highcharts/7appg60v/10/
