### ISSUE TITLE
Inverted polar chart points tracking issue

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#5237]
Hi,

It looks like when using inverted polar chart, wrong data points are hovered when mouse is over the plotArea. I think it may be the problem with tracking points. 

Here you can find live example of this issue:
http://jsfiddle.net/vp95hjcc/3/

To reproduce problem hover on points - for example near '270' label.

Here I have made gif showing this problem:

![animation](https://cloud.githubusercontent.com/assets/15050812/14756311/a07e6d5e-08e8-11e6-98ad-19d87f554240.gif)

Kind regards.

**Comment by TorsteinHonsi** [comment]
I'm not sure I have the fantasy to imagine what an inverted polar chart should look like :)

In cartesian charts, `inverted` means that the X axis and the Y axis swap places. That doesn't happen in this polar chart. A consequence of inverting a cartesian chart is that the X axis is reversed by default, and this _does_ happen in the polar chart.

Also, it seems that the tooltip behaves as expected if we don't set `chart.inverted`, but set `xAxis.reversed` instead: http://jsfiddle.net/highcharts/vp95hjcc/4/. Does this solve your problem?

In that case, the bug here is that a) the docs should state clearly that inverted doesn't apply to polar charts, and b) setting inverted should have no consequences on the axis.

**Comment by Izothep** [comment]
Hi,

Thank you for your help, I had the same problem with imagine how this chart should look like. :)
It looks like setting xAxis.reversed solve this small issue.  

I also agree that the main bug here is that inverted should have no consequences on the axis and it should be written in docs. 

Have a nice day!

**Comment by toshkent82** [comment]
Thank you guys. It was originally my problem. Now, I like Highcharts even more with such support :) 
I just add  pane.startAngle:90 option to your advice and the polar diagram looks like I really need.

Good luck!

**Comment by TorsteinHonsi** [comment]
You're welcome!

Docs updated: http://api.highcharts.com/highcharts#chart.inverted
