### ISSUE TITLE
Categories located at the ends disappear

### ISSUE THREAD

**Issue by luiza-cicone** [highcharts/highcharts#5246]
Hey everybody,

I have a stacked bar chart with categories.
When hiding the series, if a category doesn't have any more data AND if it is the first or last category, it disappears. But if the category is somewhere in the middle, it doesn't disappear. 
So there is a consistency problem.

Here is the demo of the issue
http://jsfiddle.net/lulylulu/8sf3uz5a/

When hiding the A series (by clicking in the legend) the category 1 disappears. But when I hide, B and C, the 2 category doesn't disappear. What I want is that the middle categories to disappear too (no more white space in the middle).

Is this a bug? So if it is, should all the category disappear when there is no data? Or otherwise?

Thanks!

**Comment by jon-a-nygaard** [comment]
@luiza-cicone Hi, I am afraid that hiding an empty category in between two visible ones are not possible. The end categories are being hidden because the min and max values of the axis is automatically calculated according to the visible data.  

A way to make it more "consistent" could be to set a permanent min and max to the xAxis which would keep it from hiding any categories: http://jsfiddle.net/8sf3uz5a/5/

**Comment by TorsteinHonsi** [comment]
For future (internal) reference: the preferable way to resolve this would probably be that each point had a `name` but not an `x` value, and only visible points be handled when adding the implied categories (`names` collection).
