### ISSUE TITLE
Point shrinks to default series size upon hover/select

### ISSUE THREAD

**Issue by mjsteichen** [highcharts/highcharts#5256]
#### Expected behaviour

When hovering over/selecting a point, the point will remain the size specified in the point config object.
#### Actual behaviour

The point shrinks to the default size for the series
#### Live demo of the issue

http://jsfiddle.net/msteichen/ho2mf9wu/
#### Steps to reproduce the behaviour

Hover over or select the point.
#### Affected browser(s)

Chrome

**Comment by TorsteinHonsi** [comment]
The problem comes from the [getAttribs function](https://github.com/highcharts/highcharts/blob/v4.2.4/js/parts/Series.js#L1072) where the `radiusPlus` option is applied to the general series radius, not the specific marker radius.

### Workaround
Apply a specific `marker.states.hover.radius`: http://jsfiddle.net/highcharts/ho2mf9wu/1/

**Comment by pawelfus** [comment]
It's fixed since 5.0.2: http://jsfiddle.net/ho2mf9wu/2/
