### ISSUE TITLE
plotOptions.column.colors is not respected

### ISSUE THREAD

**Issue by nip3o** [highcharts/highcharts#5262]
#### Expected behaviour

When setting `plotOptions.column.colors`, the color values are used for charts of that type, as documented in http://api.highcharts.com/highstock#plotOptions.column.colors
#### Actual behaviour

It uses the default color value.
#### Live demo of the issue

http://jsfiddle.net/788bfq8c/4/

Could this be related to #3881 ?

**Comment by TorsteinHonsi** [comment]
Thanks for writing! According to the docs, "A series specific or series type specific color set to apply instead of the global colors _when colorByPoint is true_."

So when we set [colorByPoint](http://api.highcharts.com/highcharts#plotOptions.column.colorByPoint) to true, we should expect everything to become red, which it does [for smaller data series](http://jsfiddle.net/highcharts/788bfq8c/6/). However for the original data series [something goes wrong](http://jsfiddle.net/highcharts/788bfq8c/7/)...

I'll investigate that.

**Comment by pawelfus** [comment]
I'm not sure if this will help, but when using zooming in and out, then part of the data (zoomed) is colored: http://jsfiddle.net/788bfq8c/8/ ;)

Workaround: set `turboThreshold: 0`, demo: http://jsfiddle.net/788bfq8c/10/

**Comment by KacperMadej** [comment]
Works fine in version 6.0.3 - I'm closing the issue.
Could reopen if more info will be provided.
