### ISSUE TITLE
Treemap color stop not working

### ISSUE THREAD

**Issue by ranair** [highcharts/highcharts#5265]
#### Expected behaviour
See JSFiddle. Look at the "White"  and Green tile.
I would expect it to be White and Green color.
But it is not.

It seem to work when the Red value and Green value are equi-distant from 0 (Something like -1, 1, or -2,2). 

#### Actual behaviour
colors are off

#### Live demo of the issue
http://jsfiddle.net/ranair/mqjzgg8y/

#### Steps to reproduce the behaviour
Use the above jsfiddle

#### Affected browser(s)
Tested on Chrome

**Comment by jon-a-nygaard** [comment]
@ranair Hi, the behavior of your color axis is due to the tickInterval is calculated to 50, and in combination with the startOnTick and endOnTick options, the range of your color axis is set to go from -100 to 50.
One way to avoid this is to set [startOnTick and endOnTick to false](http://jsfiddle.net/xhfwxoaL/).
Another one is to set a more fitting tickInterval.

You can read more about [colorAxis and its options like startOnTick, endOnTick, tickInterval in our API](http://api.highcharts.com/highmaps#colorAxis)

**Comment by ranair** [comment]
Thanks!
