### ISSUE TITLE
Boost module: series threshold of null is not working

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5268]
#### Behaviour

series threshold of null is not working
#### Live demo of the issue

http://jsfiddle.net/9m44zu20/

compare without boost:
http://jsfiddle.net/9m44zu20/1/

**Comment by webdevisme** [comment]
what do your expect to happen on threshold null?

**Comment by yonzzu** [comment]
It needs to be null when the y axis minimum value can be below zero.

From the api documentation:
"threshold: Number
The Y axis value to serve as the base for the area, for distinguishing between values above and below a threshold. If null, the area behaves like a line series with fill between the graph and the Y axis minimum. Defaults to 0."

**Comment by TorsteinHonsi** [comment]
> It needs to be null when the y axis minimum value can be below zero.

It doesn't need to be null - in most cases it makes more sense to leave it at 0, so that it is easier to distinguish positive from negative values: http://jsfiddle.net/highcharts/9m44zu20/2/

**Comment by yonzzu** [comment]
Gotta agree on that, but our situation is a bit different to most.

In our case we are drawing an altitude graph so it looks visually better and more easily understandable when we make the fill start from the yAxis bottom than from zero. The fill kind of represents ground. 

Otherwise values below zero would show the fill as inverted compared to what we are trying to achieve with it.

**Comment by KacperMadej** [comment]
+1
Series threshold is not working at all.
Demo: http://jsfiddle.net/9m44zu20/4/
