### ISSUE TITLE
Applying theme without refresh entire page leaves background image from "skies" theme

### ISSUE THREAD

**Issue by arnabk** [highcharts/highcharts#5272]
#### Expected behaviour
Themes should be applied properly without leaving effects of previous theme

#### Actual behaviour
"skies" theme's background image is retained with other themes

#### Live demo of the issue

htps://webtrader.binary.com/beta

#### Steps to reproduce the behaviour
Go to URL webtrader.binary.com/beta
Click Tools > Settings > Themes > Skies
Click Yes
Click Tools > Settings > Themes > Any other theme

#### Affected browser(s)
Chrome, FF, Edge, Safari, Opera

**Comment by TorsteinHonsi** [comment]
Demo: http://jsfiddle.net/highcharts/2dj2w771/.
Click the "Toggle theme" button.

The problem is that if the given option is not given in the second theme, it survives from the previous theme. The fix is to add the `plotBackgroundImage` setting to the second theme too: http://jsfiddle.net/highcharts/2dj2w771/1/

**Comment by arnabk** [comment]
I have similar issue with https://github.com/highcharts/highcharts/blob/master/js/themes/sand-signika.js

How do I remove this.container.style.background = 'url(http://www.highcharts.com/samples/graphics/sand.png)';

**Comment by TorsteinHonsi** [comment]
A theme is just a set of options applied through `Highcharts.setOptions`. So in order to go back to the "default", you need to reset each option of the theme. So in the case of the theme above, you would set the container background to `none` or `white` or something else depending on what you call default.
