### ISSUE TITLE
Add PDF support to offline exporting module

### ISSUE THREAD

**Issue by oysteinmoseng** [highcharts/highcharts#5278]
Ref discussion in issue #5157, we would like to support PDF export on the client side. [jsPDF](https://github.com/MrRio/jsPDF) has been suggested, but does not currently seem to support SVG as vector graphics.

**Comment by eggib** [comment]
What about using http://pdfkit.org/ ?

**Comment by TorsteinHonsi** [comment]
Looks like PDFKit doesn't support transforming a full SVG, see https://github.com/devongovett/pdfkit/issues/270.

jsPDF has primitive functions like `API.roundedRect`, `API.text` etc, so one possible solution for us could be to create an SVG parser that hooks on to these. But of course it would take quite a bit of work.

**Comment by JohnPortella** [comment]
Any news?

**Comment by oysteinmoseng** [comment]
@JohnPortella: No new libraries have come up that I am aware of, so the issue is still on hold

**Comment by TorsteinHonsi** [comment]
Copied from another issue:

On an earlier occasion we investigated using jsPDF, but as noted above, it has poort support for SVG. The PDF support in "highcharts-export-clientside" is not optimal - it just embeds a raster image into the PDF. In our opinion the point of exporting to PDF is to preserve the vector quality of the SVG graphics, so we didn't go that route. In order to include vectorized PDF support, we would have to either create our own implementation, contribute to jsPDF or look for other similar solutions with SVG support.

Here's a first draft on vectorized PDF support: http://jsfiddle.net/highcharts/wad3peww/. Key features like group translation, font styling and paths are missing.

Here's an experiment where I copied the svgToPdf source code over to jsFiddle and attempted to implement the `path` element using `pdf.lines`, but failed so far: http://jsfiddle.net/wad3peww/3/

**Comment by TorsteinHonsi** [comment]
I made some progress yesterday: 

*Demo*: 
1. Log into your account on jsFiddle.
2. Run http://jsfiddle.net/highcharts/wad3peww/7/show
3. Run jsfiddle.net/draft and view the PDF

*Achievements*
Simple path defininitions, font styling.

*To do*
* Apply group translate/transform. Possibly use the current transformation matrix (CTM) API of SVG and apply directly in jsPDF. It should also resolve rotation.
* Apply styling (specifically font-family) that Highcharts sets on the root svg element.
* Embedded images.

**Comment by mikecentiq** [comment]
I just enabled offline-exporting on my HighStock graph, as your export server is currently broken, and it seems to work, except the "PDF" option has disappeared altogether. I have server fallback enabled, so I would have expected it to still be an option, even if client side generation isn't currently possible... I'm using v4.2.6

**Comment by oysteinmoseng** [comment]
@mikecentiq That's a good suggestion. You can add server side PDF export to the chart by adding the following code before you create your chart:
```javascript
Highcharts.getOptions().exporting.buttons.contextButton.menuItems.push({
    textKey: 'downloadPDF',
    onclick: function () {
        this.exportChart({
            type: 'application/pdf'
        });
    }    		
});
```

[Example](http://jsfiddle.net/dr10h8ou/)

**Comment by mikecentiq** [comment]
That works perfectly. Thank you.
