### ISSUE TITLE
Gauge - multiple yAxis - wrong plotbands

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5283]
#### Actual behaviour
Plotbands for the second yAxis are missing (prints as shapes but incorrectly positioned).

#### Live demo of the issue
http://jsfiddle.net/a9vgopag/

#### Affected browser(s)
All browsers

**Comment by pawelfus** [comment]
**Workaround:**

Use two panes with different sizes to achieve the same result with correct axes: http://jsfiddle.net/mhxr2rgj/

**Comment by pawelfus** [comment]
*Internal note:*

It's fixed (or changed) only for positive values for `axis.offset`. Currently we use this bug/feature to render plotBands outside the pane (with negative offset). I think we don't want to change current behaviour because:

- it will change some our polar/gauge demos and user charts
- with negative offset it's easier to control thickness of the plotBand, so plotBand will end exactly at the tick length (see gauge-overshoot unit test as an example) - alternative (`pane.outerRadius`) won't work for percentage values (for a fixed size it's fine)
