### ISSUE TITLE
3D columns overlapping with high depth

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5297]
#### Behaviour

3D columns are overlapping each other when there is high depth set
#### Live demo of the issue

http://jsfiddle.net/0ggczp13/1/

**Comment by pawelfus** [comment]
It looks like the issue with using the same group for all series - which is fine in 2D, but cause rendering issues in 3D. Connected ticket:  #4369

**Comment by javiros** [comment]
Hi guys, is there a solution to this issue yet?

**Comment by Izothep** [comment]
As a workaround you should be able to modify SVGRenderer.prototype.cuboidPath and inside this method change an idea of calculating zIndex for columns. http://jsfiddle.net/4y3qgdmn/32/

In this case it is necessary to change where series is rendered. Instead of individual groups per series use just one group for all series’ points.
