### ISSUE TITLE
marker rotation is not  supported?

### ISSUE THREAD

**Issue by rubby1228** [highcharts/highcharts#5306]
Sometimes I want to change marker rotation.for example, when I draw dynamic wind direction in the chart series. so what can I do?

**Comment by TorsteinHonsi** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.

To answer your question, marker rotation is currently not an option. In order to achieve this, you need to draw custom markers, like for example http://www.highcharts.com/demo/combo-meteogram#https://www.yr.no/place/United_Kingdom/England/London/forecast_hour_by_hour.xml.
