### ISSUE TITLE
Highstock navigator + rangeSelector

### ISSUE THREAD

**Issue by pliasetski** [highcharts/highcharts#5307]
Hello,

When clicking 'YPD' in rangeSeletor navigator doesn't zoom.
#### Expected behaviour

Navigator should zoom according to rangeSelector
#### Actual behaviour

Navigator doesn't zoom
#### Live demo of the issue

https://jsfiddle.net/Pashe4ka/takyrn41/
#### Steps to reproduce the behaviour

You could check it in this video:
https://dl.dropboxusercontent.com/u/73896408/Highstock%20navigator%20bug.mp4
#### Affected browser(s)

Chrome 50

With best regards, Pavel Liasetski

**Comment by pawelfus** [comment]
Hi Pavel,

My apologies for a late reply. Could you tell us which version of Highstock you have? It works with versions 4.2.x: https://jsfiddle.net/peha8oqh/

**Comment by pliasetski** [comment]
Hello,
I'm using the latest version.
Data in chart zomms corretly, but scroll in navigator doesn't zoom. You could check it on attached video. At you example (https://jsfiddle.net/peha8oqh/) it doesn't work correctly too.
Thanks, Pavel

**Comment by pawelfus** [comment]
Hi Pavel,

It's interesting. It works for me, so it looks like the issue is connected to the width of the chart:

- 410px: https://jsfiddle.net/peha8oqh/2/ - works
- 310px: https://jsfiddle.net/peha8oqh/3/ - doesn't work

**Comment by pawelfus** [comment]
**Workaround:**
Set `minRange`:

    xAxis: {
    	minRange: 1
    },

Working demo: http://jsfiddle.net/q9uvpd86/

*Internal note:*

It's caused by [this condition](https://github.com/highcharts/highcharts/blob/2bba08ffe0ac1f90062885a1fd5856aae5229e05/js/parts/Scroller.js#L237-L239). Related to #2618 ticket. I think we can simply check `isDragged` flag? Or maybe the question is rather why `YTD` button is enabled in a first place (other buttons are disabled)? Or maybe detailed xAxis shouldn't zoom, just like navigator zooming is prevented by `xAxis.minRange`? @TorsteinHonsi
