### ISSUE TITLE
Highstock navigator scroll bug

### ISSUE THREAD

**Issue by pliasetski** [highcharts/highcharts#5308]
Hello,

When I'm scrolling in navigator area, console error appears: "Uncaught RangeError: Invalid array length"
#### Expected behaviour

Console error shouldn't appear.
#### Actual behaviour

Console error appears.
#### Live demo of the issue

https://jsfiddle.net/Pashe4ka/takyrn41/
#### Steps to reproduce the behaviour

You could check steps in this video:
https://dl.dropboxusercontent.com/u/73896408/Highstock%20navigator%20scroll%20bug.mp4
#### Affected browser(s)

Chrome 50

With best regards, Pavel Liasetski

**Comment by TorsteinHonsi** [comment]
Here's a controlled demo of the issue, with exact steps: http://jsfiddle.net/highcharts/takyrn41/4/

In the same demo, using the latest development code, the issue is fixed: http://jsfiddle.net/highcharts/takyrn41/5/.

We refactored the scrollbars since last release, so it turns out we have resolved this issue at the same time.

**Comment by pliasetski** [comment]
Thanks

**Comment by jordanmaslyn** [comment]
Seems like there may be a regression with this issue. I am able to replicate using the jsFiddles above. Any thoughts on how to resolve?

**Comment by pawelfus** [comment]
Hi @jordanmaslyn 
Thank you for letting us know! Let me reopen the issue. It looks like issue comes from `rangeSelector` now - when disabled, works fine: http://jsfiddle.net/BlackLabel/takyrn41/8/

Standalone error: `Highcharts.pad(Math.round(-190926719999.99954 % 1000), 3)`
