### ISSUE TITLE
Jumpy mouse tracking behaviour with multiple arearange & line series

### ISSUE THREAD

**Issue by olivergrimes** [highcharts/highcharts#5315]
#### Expected behaviour
Mousetracking/hover events to fire only when directly over a series using the appropriate `plotOptions.series.stickyTracking: false` and `tooltip.shared: false` options.

#### Actual behaviour
Tooltip & events firing for other series when not directly hovered over them.

#### Live demo of the issue
[JSFiddle](https://jsfiddle.net/zvj079xj/1/)
[StackOverflow question](http://stackoverflow.com/questions/37208391/highcharts-mouse-tracking-behaviour-with-multiple-arearange-line-series)

#### Steps to reproduce the behaviour
See [JSFiddle](https://jsfiddle.net/zvj079xj/1/)

#### Affected browser(s)
Only tested in Chrome

**Comment by TorsteinHonsi** [comment]
It happens because in line and arearange series, the tooltip finds the closest point and fires the tooltip over that. That's why hovering the gray area may actually trigger a tooltip on another series. Since the area ranges only have control points in the ends, they are not the closest points to the mouse when you hover in the middle. A workaround may be to add more points in between.

**Comment by olivergrimes** [comment]
Thanks for the response, I've taken your suggestion and created a function to interpolate `arearange` series.  Working example for reference: [https://jsfiddle.net/7czk7nvu/3/](url)

**Comment by pawelfus** [comment]
It's fixed in 4.2.7/5.0.0 versions: https://jsfiddle.net/sfgtju1u/
