### ISSUE TITLE
Pie chart with negative values renders incorrectly

### ISSUE THREAD

**Issue by alvarezguille** [highcharts/highcharts#5322]
#### Expected behavior 
Not sure what's the expected behavior, maybe ignore negatives

#### Actual behavior
![image](https://cloud.githubusercontent.com/assets/9820084/15357803/afb0ec2c-1d09-11e6-9654-ac5570e08fd7.png)

#### Live demo of the issue
http://jsfiddle.net/alvarezg/87v4w3fp/

#### Affected browser(s)
Latest chrome at least

**Comment by alvarezguille** [comment]
Looks like behavior changed between version 4.1.5 and 4.1.6

**Comment by jon-a-nygaard** [comment]
Thank you for reporting, this issue will be fixed in the upcoming maintenance release. For those in need of an immediate fix, have a look below.

__Workaround__
Open your source file e.g. `highcharts.src.js` in a text editor.
Locate the function `updateTotals` (around line 17650), and do the following replacement.
```javascript
// Replace the following code
for (i = 0; i < len; i++) {
	point = points[i];
	total += (ignoreHiddenPoint && !point.visible) ? 0 : point.y;
}

// With this code
for (i = 0; i < len; i++) {
	point = points[i];
	// Disallow negative values (#1530, #3623, #5322)
	if (point.y < 0) {
		point.y = null;
	}
	total += (ignoreHiddenPoint && !point.visible) ? 0 : point.y;
}
```

_Internal note: This issue was introduced in ec6f897._

**Comment by peacechen** [comment]
@jon-a-nygaard  Since we are pulling highcharts from npm, editing the source file isn't feasible on the CI server.  What's the anticipated release date for this fix?

For the time being I'll floor negative values to zero.  I'd like to update to the fixed version of Highcharts as soon as it's released though.

**Comment by jon-a-nygaard** [comment]
The next maintenance release won't be until our holiday season has ended, which is in the beginning of August.
