### ISSUE TITLE
Animation delay option

### ISSUE THREAD

**Issue by jbkunst** [highcharts/highcharts#5326]
There is something like `duration` but for the delay time to start to draw a series? Almost sure there isnt. What will be the approach to create this option? Is a plugin an alternative? (I'm not a JS master)

Regards,

**Comment by TorsteinHonsi** [comment]
That's a good idea, it could be implemented directly into the animation configuration object.

A possible, simple implementation would be to call Fx.run in a timeout, like in this drop-in snippet:
```js
Highcharts.wrap(Highcharts.Fx.prototype, 'run', function (proceed) {
	var fx = this,
    	args = arguments;
	setTimeout(function () {
		proceed.apply(fx, [].slice.call(args, 1));
    }, fx.options.delay || 0);
});
```
[View live demo](http://jsfiddle.net/highcharts/7r5220wb/).

A potential problem here may be if we do other things with the elements, like redrawing the chart, while the element is still waiting for animation. We would need to test the `stop` feature before implementing.

**Comment by frank-eisen** [comment]
Hi!

Your extension doesn't work nicely with 'line' or 'splines', so I wrote a function that takes the duration, delay and a timing_function as arguments and creates an animation object for highcharts. This function sets a longer duration for the animation (`duration + delay`) and creates an easing function that returns 0 for the delay for animation.

```javascript
/**
 * returns a highcharts animation object with an own easing-function
 * @param {number} duration
 * @param {number} delay
 * @param {function} timingFunction
 * @return {number|object}
 */
function highchartsAnimation(duration, delay, timingFunction)
{
  if(typeof duration === 'number' && typeof delay === 'number' && typeof timingFunction === 'function') {
    var delay_percent = delay / (duration + delay),
        perc = 1 - delay_percent;
    
    return {
      duration: duration + delay,
      easing: function(pos) {
        if(pos <= delay_percent) {
          return 0;
        }
        else {
          return timingFunction((pos - delay_percent) / perc);
        }
      }
    };
  }
  else {
    return 750;
  }
}
```

So that you can use like

`animation: highchartsAnimation(750, 1000, myTimingFunction)`

Live example (I rewrote @TorsteinHonsi example with that function):

http://jsfiddle.net/d2jvdjfz/

Feel free to use the getTimingFunction()-Function in that example.

**Comment by jbkunst** [comment]
@frank-eisen 

Thanks for sharing!
