### ISSUE TITLE
Incorrect range selector display in case first metric on chart ends earlier than any other

### ISSUE THREAD

**Issue by Dimgoncharov** [highcharts/highcharts#5342]
**Description:**
Range selector displayed incorrectly in case
1) there are more than one metric in the chart and
2) first metric ends earlier than any other metric
**BUG:** 
1) Range selector legend end value - the last value for first metric and differs from the last legend value for the chart
2) Range selector pointer displayed incorrectly
3) Navigation via range selector broken
**Live demo:** 
http://grabilla.com/06519-69af5842-2efe-4311-bfe5-8d7174b899e3.html
**Code examples:**
Open code example and switch to **1m** period
1) First metric ends earlier than second - **BUG**
https://jsfiddle.net/devror/7zf6um59/
2) Second metric ends earlier than first - **OK**
https://jsfiddle.net/devror/ez4yja42/

Affected browser(s): any

**Please, reply ASAP when this issue could be fixed**

**Comment by TorsteinHonsi** [comment]
The problem here is that the navigator.xAxis is ordinal by default. Since the data is only grabbed from the first series, this leaves all data after the first series crammed into a singular point. 

If we set ordinal to false it behaves better: https://jsfiddle.net/highcharts/7zf6um59/4/

Another, perhaps better solution, is to provide a separate [series for the navigator](http://api.highcharts.com/highstock#navigator.series). 

In Highstock 5.0, we will add support for multiple data series in the navigator.
