### ISSUE TITLE
About series<bar>.data in highcharts API

### ISSUE THREAD

**Issue by BinXia** [highcharts/highcharts#5362]
#### Expected behaviour
Based on the third format of data in http://api.highcharts.com/highcharts#series<bar>.data, we can use an array of objects with named values such as x, y, name, and color. However, it doesn't work.

#### Actual behaviour
Demo: http://jsfiddle.net/Kryolith/cogy4yex/4/
As shown in the demo, this kind format of data cannot be accepted by highcharts.

#### Live demo to fix this bug

Demo: http://jsfiddle.net/Kryolith/gh37zvLL/4/
We just need to remove the key 'x', and it can be fixed. I think API is a little misleading.

Actually, this kind of code is allowed in previous edition of highchars.js, but now, it doesn't work for any one in the past.

**Comment by jon-a-nygaard** [comment]
@BinXia You are correct that this format of data is not accepted by Highcharts for its x values, and it is not a bug, which you can see from our [documentation of series<bar>.data.x](http://api.highcharts.com/highcharts#series<bar>.data.x) the only accepted format is Number.

The reason why your code works as expected is because when the x value is not provided Highcharts makes a calculated guess. Your demo is equivalent to setting the correct x values explicitly, as [shown in this demo](http://jsfiddle.net/jon_a_nygaard/70n0nd8y/)

**Comment by TorsteinHonsi** [comment]
It fails since bd0f08e, where we fixed #5010.
