### ISSUE TITLE
hover -> marker -> enabled -> false is ignored

### ISSUE THREAD

**Issue by devenv** [highcharts/highcharts#5367]
#### Expected behaviour
symbols shouldn't show

#### Actual behaviour
they are shown

#### Live demo with steps to reproduce
http://jsfiddle.net/e8cqxh8k/

#### Affected browser(s)
chrome at least

**Comment by pawelfus** [comment]
It works on `series.marker.states.hover`, but not on `states.hover.marker`.

**Workaround:** http://jsfiddle.net/e8cqxh8k/1/

**Comment by jon-a-nygaard** [comment]
_Internal Note: issue is located in [Interaction.setState on L502](https://github.com/highcharts/highcharts/blob/master/js/parts/Interaction.js#L502). series.states.hover.marker should probably be merged in, but the question is which one has precedency. I believe `series.marker.states.hover` is more specific and therefore should have precedency._

**Comment by TorsteinHonsi** [comment]
Actually the problem lies in the docs, see http://api.highcharts.com/highcharts#plotOptions.series-states-hover-marker. This option was used in Highcharts 1.0, but haven't been active since the transition to SVG in HC2. It applied to all markers on the hovered series, in contrast to `series.marker.states.hover` that applies to the actual hovered marker. I've marked it deprecated in the API.
