### ISSUE TITLE
DataLabel in pie not drawn

### ISSUE THREAD

**Issue by akeblom** [highcharts/highcharts#5368]
I have a piechart with fixed size and in some cases certain dataLabels does not appear. It seems to have a relation to the size of my chart container. If I make it bigger all labels are shown. Is this a default behavior or is it a bug?

Here is a demo:
http://codepen.io/tobake/pen/JKowyN
counting from the top. Slice 7 and 12 gets no labels

**Comment by TorsteinHonsi** [comment]
In the current algorithm for label placement, each label is reserved a space corresponding to the largest height of any label. So when you have one or two labels that span two lines, basically we're wasting a lot of space because Highcharts thinks it needs to reserve two lines for every label. The workaround for you then would be to make sure the labels are shorter, either through the `dataLabels.formatter` or by shortening the point names themselves.

Luckily, we've written a completely new label distribution algorithm for Highcharts 5, so the labels will be laid out more organically: http://codepen.io/anon/pen/RRNvoO

**Comment by akeblom** [comment]
That is great news. Do you guys have release date on Highchart 5?

Thanks for a quick response!

**Comment by TorsteinHonsi** [comment]
Not yet, but we will probably release the Alpha by the end of June.

**Comment by akeblom** [comment]
Ok! thanks.

**Comment by akeblom** [comment]
Hi again. Do you have further info regarding highcharts 5. Is there an Alpha available?

**Comment by TorsteinHonsi** [comment]
Yes, there's a Developer preview, but the label distribution is not yet merged in. Actually I was going to start with that today.

**Comment by akeblom** [comment]
Great!
