### ISSUE TITLE
Highstock: not possible to set extremes for axis when chart has no series

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5406]
#### Expected behaviour
Task was possible in 4.2.4

#### Actual behaviour
Error in console.

#### Live demo with steps to reproduce
http://jsfiddle.net/y3w6mkao/
1. Press the button.

The case here is that series might be added later and if extremes are set for an axis before series is added, then after series is added only set range on axis should be visible.

**Comment by jon-a-nygaard** [comment]
Already fixed in the master branch as you can see from [this demo](http://jsfiddle.net/jon_a_nygaard/y3w6mkao/1/)

According to git bisect the commit that does the fix is 565e0ba

For those who need a workaround can either use the source file from our master branch, or apply the same changes that is shown in the commit 565e0ba to their own source file.
