### ISSUE TITLE
Column value disappears when the next/previous column has a similar value

### ISSUE THREAD

**Issue by ericmdantas** [highcharts/highcharts#5408]
#### Expected behaviour

Expected the values to be fit their columns.

#### Actual behaviour

One of the columns's value disappear.

#### Live demo with steps to reproduce

http://jsfiddle.net/bt5cksL5/

#### Affected browser(s)

All of them.

**Comment by jon-a-nygaard** [comment]
@ericmdantas This happen because the data labels collide and Highcharts by default chooses to hide one of the labels.  You can set [dataLabels.allowOverlap](http://api.highcharts.com/highcharts#plotOptions.series.dataLabels.allowOverlap) to true to ignore collision, like in [this example](http://jsfiddle.net/jon_a_nygaard/bt5cksL5/1/)

**Comment by ericmdantas** [comment]
Thanks, @jon-a-nygaard!
