### ISSUE TITLE
Gauge max label not showing with certain numbers [Reproducible]

### ISSUE THREAD

**Issue by vincentcox** [highcharts/highcharts#5419]
#### Expected behaviour
http://jsfiddle.net/hdp1L0o6/1/
<img width="328" alt="screen shot 2016-06-21 at 12 37 45" src="https://cloud.githubusercontent.com/assets/9286611/16226706/ffd520f2-37ac-11e6-864d-72d5eb58d185.png">

#### Actual behaviour
http://jsfiddle.net/hdp1L0o6/
<img width="315" alt="screen shot 2016-06-21 at 12 37 50" src="https://cloud.githubusercontent.com/assets/9286611/16226710/048cbe84-37ad-11e6-8d39-0043a9e494e1.png">

#### Difference
```
yAxis: {
	            min: 0,
	            max: 50,
	            title: {
	                text: 'Malicous requests vs normal requests'
	            }
	        },
```
VS
```
yAxis: {
	            min: 0,
	            max: 40,
	            title: {
	                text: 'Malicous requests vs normal requests'
	            }
	        },
```

#### Affected browser(s)
Chrome (verified)

**Comment by TorsteinHonsi** [comment]
It happens because Highcharts takes the `tickPixelInterval` setting and calculates the best approximation of tick distribution from it. It places ticks on round numbers like 0, 50, 100, but it will not by default create ticks for 0 and 40. One way to do it is to define `tickPositions` explicitly: http://jsfiddle.net/highcharts/hdp1L0o6/2/
