### ISSUE TITLE
Column range - Hide out of bounds data labels

### ISSUE THREAD

**Issue by ilpet** [highcharts/highcharts#5425]
If I have this chart https://jsfiddle.net/ilpet/hdL5m27x/, and I set new extremes, the series disappear, but the data labels remain.
#### Expected behaviour

Expected behaviour is for the labels to disappear.
#### Actual behaviour

But they remain on the left, while the series disappear.
#### Live demo with steps to reproduce

https://jsfiddle.net/ilpet/6t28so2z/

**Comment by pawelfus** [comment]
Thank you for reporting. Minimal example with issue: http://jsfiddle.net/sLv1h5n8/

**Comment by pawelfus** [comment]
*Internal note:*
It comes from [this logic](https://github.com/highcharts/highcharts/blob/445f2b74aff1f82b09fee0d9f37eda16aeace4be/js/parts/DataLabels.js#L749) - overshoot is very high (e.g. 900+) which cause later to:

- decrease `height`, making it negative (e.g. -900px)
- it happens only to the bottom label because of `alignTo.y += below ? alignTo.height : 0;` (=> `alignTo.y -= 900`).
