### ISSUE TITLE
HighCharts: Set different widths for each box in Box Plot

### ISSUE THREAD

**Issue by GaneshBChandgude** [highcharts/highcharts#5441]
Consider a scenario, where the width of box should indicate the number of data values in a group.If the number of data values is variable in different groups, the boxes should have different width.
#### Expected behaviour

In the following example, different colors are set for each box.
https://jsfiddle.net/48m0k3sL/16/
Is there any way to set different widths for each box?
#### Actual behaviour

pointWidth set in the series, applies the specified width to all the boxes.
https://jsfiddle.net/48m0k3sL/17/

**Comment by jon-a-nygaard** [comment]
Thank you for reporting. Currently it is not possible to set pointWidth on a point, and the only way to get around this today is by overriding [Highcharts.seriesTypes.column.prototype.translate](https://github.com/highcharts/highcharts/blob/master/js/parts/ColumnSeries.js#L191), if this is an option have a look at [Extending Highcharts](http://www.highcharts.com/docs/extending-highcharts/extending-highcharts).

We will discuss internally what to do with this issue, if we should support `point.pointWidth`, and come back to you when we have an update.

**Comment by pawelfus** [comment]
Possible workaround is to split series into separate series, and then connected them using `linkedTo` option. Simple example: https://jsfiddle.net/cx48ub3L/

**Comment by sagargurtu** [comment]
@pawelfus But when multiple series are to be shown, above workaround fails. https://jsfiddle.net/cx48ub3L/13/

Actually, I want to achieve variable box plot widths with multiple series plotted. Since it is a popular convention (see https://en.wikipedia.org/wiki/Box_plot#Variations), could you please implement this feature? Or for the time being, is there any other workaround possible?

**Comment by sagargurtu** [comment]
@pawelfus Also, in my case, the chart is re-sizable. So when chart is reduced to a smaller size, box plots start overlapping because pointWidth is in pixels. And when chart is enlarged, box plots are seen to be smaller in respect to plot size. Is there any way pointWidth can be given as a percentage w.r.t. the chart?

**Comment by pawelfus** [comment]
Hi @sagargurtu 

Thank you for the details! I suggest to post this idea on our [UserVoice](https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api) - as always, if the idea will gather some votes we will set a higher priority for this feature.

**Comment by sagargurtu** [comment]
@TorsteinHonsi Building on your fiddle, `grouping: true` does not work with the workaround. The box plots do not align properly with the x-axis markers.
https://jsfiddle.net/cx48ub3L/16/

**Comment by TorsteinHonsi** [comment]
It does, but since you have six series, each category is divided into 6 slots and the pointPadding applies within the slot. For what you want to do, you may need to set `grouping` to `false` and adjust the lateral position with [pointPlacement](https://api.highcharts.com/highcharts/plotOptions.series.pointPlacement).

**Comment by TorsteinHonsi** [comment]
Also, you should consider @jon-a-nygaard 's solution by creating your own series type. Here's a draft: http://jsfiddle.net/highcharts/reebwf4z/.
