### ISSUE TITLE
Column chart legend border doesn't match series.

### ISSUE THREAD

**Issue by Rashaine** [highcharts/highcharts#5444]
#### Expected behaviour

If a column chart series has a border, the legend marker/symbol should also have a border.
#### Actual behaviour

The legend symbol does not have a matching border to the series.
#### Live demo with steps to reproduce

http://jsfiddle.net/eq0mjy4p/

**Comment by pawelfus** [comment]
Hi Rashaine,

Thank you for reporting the issue. You are right, column's legend symbols don't support border. However, it can be achieved, please take a look: http://jsfiddle.net/2y3hwLLe/2/

*Internal note:*
It works for markers, because we use the same params from `markerOptions` [here](https://github.com/highcharts/highcharts/blob/46fe6c373b1dc69fa78cff6bf887594a1d077c08/js/parts/Legend.js#L78). We would need to check type of an item (area vs column) to add the border., in a similar way as in the workaround (don't forget about crisping the item).

**Comment by Rashaine** [comment]
Thank you, the work around will do.
