### ISSUE TITLE
Data label are missing for alternate rows in Windows Firefox and Chrome

### ISSUE THREAD

**Issue by mithusree** [highcharts/highcharts#5448]
#### Expected behaviour
All cells displays data labels

#### Actual behaviour
It works well in Linux Firefox/Chome and Windows Edge
But the in Windows Firefox/Chrome data labels are not displaying for alternate rows

#### Live demo with steps to reproduce

http://jsfiddle.net/mithun/v7y7mrwh/9/

![Correct rendeing in Linux Chrome](https://cloud.githubusercontent.com/assets/191043/16449562/d5ff9d06-3e15-11e6-877c-c685abc835ec.png)

#### Affected browser(s)
Windows Firefox
Windows Chome
![Actual in Winows Chrome](https://cloud.githubusercontent.com/assets/191043/16449577/f09ac7bc-3e15-11e6-9cef-30e600075965.png)

**Comment by jon-a-nygaard** [comment]
Hi @mithusree this happens because the data labels overlap, and Highcharts will then hide some of them by default. To avoid this set [dataLabels.allowOverlap](http://api.highcharts.com/highcharts#plotOptions.heatmap.dataLabels.allowOverlap) to true, like in [this example](http://jsfiddle.net/v7y7mrwh/10/).
 
The reason why this behaviour is different between browsers is because they calculate the size of the bounding box differently, and therefore in some browsers the data labels are considered bigger and will collide easier.

**Comment by mithusree** [comment]
@Jon You are correct, setting  dataLabels.allowOverlap to true solved the issue. Just wondering why this happened in Windows Chome/Firefox and not in Windows Edge?
