### ISSUE TITLE
Tooltip is not showing on hovering in Highstock, when series’ type is scatter and series’ markers are disabled.

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#5460]
Hi,
#### Behaviour

When hovering on points in Highstock chart, tooltip doesn't show up. This is happening when data is type of scatter and markers are disabled. It looks like markers not only are hidden, but completely gone, therefore mouse over point event doesn't work. In Highcharts everything works as expected.
#### Live demo with steps to reproduce

http://jsfiddle.net/53djmjjv/1/ - Highstock (not working)
http://jsfiddle.net/gbfpqvzq/2/ - Highcharts (working)
#### [EDIT]

Setting property ‘shared’ to false in a tooltip object causes that Highstock example works fine.

Best regards.

**Comment by oysteinmoseng** [comment]
Thanks for reporting, this is clearly a bug.

**Comment by oysteinmoseng** [comment]
Workaround: set `tooltip.shared` to `false`.

**Comment by TorsteinHonsi** [comment]
Simplified demo: http://jsfiddle.net/highcharts/0uqqgrLk/

In a scatter series with shared tooltip, we need to hover the marker itself to trigger the tooltip. It's because the scatter series is not sequencial (with ascending x values) like line series, and is set up to search for the closest point in both x an y directions.

**Comment by KacperMadej** [comment]
Working fine in Highcharts v7.0.0.
Closing as resolved.
