### ISSUE TITLE
XAxis Labels Rotation Weird behaviour

### ISSUE THREAD

**Issue by sagargurtu** [highcharts/highcharts#5463]
#### Expected behaviour

The rotation option for X-Axis Labels should work correctly for all valid angles.
#### Actual behaviour

When I put rotation value as 0, the labels are correctly aligned in horizontal position. But when I increase rotation to 1, the labels disappear, and as I increase the angle, labels start appearing.
#### Live demo with steps to reproduce

http://jsfiddle.net/9y3zs6ep/
#### Affected browser(s)

Chrome

**Comment by oysteinmoseng** [comment]
Thanks for reporting, this is clearly a bug.

**Comment by oysteinmoseng** [comment]
What happens is that the algorithm that spaces ticks by detecting label collision doesn't take the label length into account. It seems to just check how far it has to space the ticks for labels never to intersect (even with infinite length). It is being overridden by `showFirstLabel`/`showLastLabel` options, otherwise you would probably only see a single label with `rotation: 1`.

**Internal note**: The logic happens in the `Axis.unsquish` function, where the `spaceNeeded` argument to `getStep` is just whatever space is needed for the difference between labels to be more than label height.

**Comment by sgrg93** [comment]
@sebastianbochan gave a temporary solution to this on StackOverflow by setting step parameter as 1
http://jsfiddle.net/yu50fr3j/

**Comment by sgrg93** [comment]
A temporary solution is to set step attribute as 1
http://jsfiddle.net/yu50fr3j/

**Comment by sebastianbochan** [comment]
+1
