### ISSUE TITLE
Heatmap - Automatically calculate col/rowsize (like pointRange)

### ISSUE THREAD

**Issue by PrimozGodec** [highcharts/highcharts#5492]
#### Expected behaviour

When using heatmap it should be plotted inside the area defined by axis min and max, also it should be plotted inside the grid defined by data. Tooltip should be on mouse position.
#### Actual behaviour

Heatmap is plotted for area outside the defined bounds and axis have values outside the bounds. Tooltip is on wrong position. It seems that problem is connected with fact that there are huge rects in svg.
#### Live demo with steps to reproduce

http://jsfiddle.net/9mL8x9bc/
#### Affected browser(s)

I think the problem happens in any browser. I tried with Firefox and Chrome.

**Comment by pawelfus** [comment]
This is caused by default value of ['heatmap.colsize`](http://api.highcharts.com/highmaps#plotOptions.heatmap.colsize) and [`heatmap.rowsize`](http://api.highcharts.com/highmaps#plotOptions.heatmap.rowsize). Your data is closer than default `1`. I think, in your case values:

    	colsize: 0.029,
    	rowsize: 0.012,

Should be fine, take a look: http://jsfiddle.net/d92ga28a/ (it's closest distance in xAxis and yAxis).

*Internal note:*
Shouldn't `rowsize` and `colsize` behave more like `pointRange`? Which is calculated automatically by default?

**Comment by PrimozGodec** [comment]
Thanks it solved my the problem. 

`pointRange` calculated automatically would be nice solution.
