### ISSUE TITLE
Highcharts.maps - undefined, when using Highstock with Highmaps required as a plugin

### ISSUE THREAD

**Issue by Kamilius** [highcharts/highcharts#5509]
#### Expected behaviour

Highcharts.maps property is sat and has data in it.
#### Actual behaviour

Can't read property 'custom/world-continents' of undefined, using Highcharts.maps['custom/world-continents']
#### Live demo with steps to reproduce

Can't post a live demo because of:
1. For Highstock and Highmaps, highstock-release and highmaps-release npm packages are used.
2. App written with use of ES6 and WebPack/Browserify, and modules are being included as follows:

``` js
  import Highcharts from 'highstock-release';
  import 'highmaps-release/modules/map';
```

Highstock works great, chart is created via `new Highcharts.Chart(options)` with renderTo specified.

Highmaps, on the other hand, is being recognized, but fails during initialization, when tries to read madData specified as follows:

``` js
const options = {
  chart: {
    height: 485,
    plotBackgroundColor: '#f4f5f5',
    type: 'map',
  },
  series: [{
    mapData: Highcharts.maps['custom/world-continents'],
  }],
};
```

As result, getting error "can not read 'custom/world-continents' of undefined". During debug, checked 'maps' property value, and it actually is `undefined`, even though map method for maps creation appeared. 

Any tips on how get things working in this kind of configuration?
#### Affected browser(s)

Browser agnostic

**Comment by oysteinmoseng** [comment]
There are multiple reasons why this is not working. 

Firstly, the map collection is not loaded by just including the map module, you have to explicitly [download](http://code.highcharts.com/mapdata) and include the javascript map(s) that you want to use.

Secondly, in order to use the map module with node you will have to run the returned factory function, as follows:

```javascript
import Highcharts from 'highcharts/highstock';
import mapFactory from 'highcharts/modules/map';
mapFactory(Highcharts);
```

Finally, the map files are not designed for node, and will require some modification to work. Instead of `Highcharts.maps['map-code'] = {...` the file should start with `module.exports = {...`. You can then import the file as follows: 

```javascript
import myMap from './local/path/to/map';

...

    series: [{
        mapData: myMap
```

[A Gist to show the concept](https://gist.github.com/oysteinmoseng/99808bc853faa80294c3066e4da951cb)

**Comment by Kamilius** [comment]
@oysteinmoseng thanks a lot, omw on trying this 👍

**Comment by Kamilius** [comment]
@oysteinmoseng ok, got it working in the way, you've proposed, but with one slight issue. For some reason, when using this approach, credits.mapText and credits.mapTextFull are being used before being initialized. So in order to get this working, I've explicitly assigned following properties for chart options:

```js
const options = {
  credits: {
    mapText: '',
    mapTextFull: '',
  },
};

**Comment by Kamilius** [comment]
@oysteinmoseng after being able to initialize a map. There are issues with zooming in/out using scroll and it is impossible to drag map while zoomed. Should I import something for enabling this?

**Comment by oysteinmoseng** [comment]
@Kamilius: For drag and zoom, the [mapNavigation](http://api.highcharts.com/highmaps#mapNavigation.enabled) option needs to be enabled, but it should otherwise work as long as Highmaps is included. Is this the case? Regarding mapbubble series, it is also included in Highmaps, and should work out of the box. [Example](http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/maps/plotoptions/mapbubble-allowpointselect/).
