### ISSUE TITLE
Does highmaps zoom has a zoom level limitation

### ISSUE THREAD

**Issue by IEfucker** [highcharts/highcharts#5534]
#### Expected behaviour
All official demo of [highmaps](http://www.highcharts.com/maps/demo/all-maps) has no zoom level limitaiton

#### Actual behaviour
But my [test](http://jsfiddle.net/Jack_bay/nhf6awqa/5/) has failed when trying to zoom it, I check the api but get no answer. 
Does it has matter with the map data, when I defined as geojson there.

**Comment by TorsteinHonsi** [comment]
Is [minRange](http://api.highcharts.com/highmaps#xAxis.minRange) what you're looking for?

**Comment by jon-a-nygaard** [comment]
Closing this issue since it is pending a reply and considered inactive. Should anyone have further information about this issue, please give us a comment.

**Comment by IEfucker** [comment]
Thanks@TorsteinHonsi, that's what I need

**Comment by oysteinmoseng** [comment]
@IEfucker min/max padding should not affect zoom to my knowledge, but start/endOnTick could slightly affect it, see e.g. http://jsfiddle.net/6obvhg9s/. Here, `minRange` is set to 5, but because the axis must start/end on ticks, the actual minimum range typically ends up being 6 or 9. Regardless, you can rely on the axis range to always be greater than `minRange`.

Also, for Highmaps, min/max padding and start/endOnTick are disabled for the x and y-axes by default, so it probably does not matter for your use case.
