### ISSUE TITLE
Max value is not applied when tickAmount is set

### ISSUE THREAD

**Issue by richardm** [highcharts/highcharts#5566]
#### Expected behaviour
The chart min should be 0 and max should be 100 with 10 ticks of 10 each

#### Actual behaviour
The chart min is 0 but max is 180 with 10 ticks of 20 each

#### Live demo with steps to reproduce
http://jsfiddle.net/richardaptitude/2qmcd0v3/1/

#### Affected browser(s)
Chrome / Firefox

**Comment by TorsteinHonsi** [comment]
You need 11 ticks in order to mark every ten from 0 to 100: http://jsfiddle.net/2qmcd0v3/2/

With 10 ticks, the axis logic sees that it can't remove a tick (if it removes 100, the range becomes 0-90, which is less than the given min/max), so it doubles the tick interval and extends the axis until the given `tickAmount` is reached.

**Comment by richardm** [comment]
Thanks for the explanation. It makes sense why it takes 11 ticks, although it was not intuitive why it doubled the tick interval. I would recommend adding some additional detail to the documentation. My team spent a considerable number of hours on this last week (on a much more complex version of this scenario), and we couldn't figure out why highcharts would not use the values we specified.

**Comment by TorsteinHonsi** [comment]
Yes, we have [added this to the API docs](http://api.highcharts.com/highcharts#yAxis.max).
