### ISSUE TITLE
Offline exporting - in IE11 - after zoom series plot is visible outside of plot area

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5567]
#### Behaviour
Offline exporting - in IE11 - after zoom series plot is visible outside of plot area in exported image.

#### Live demo with steps to reproduce
http://jsfiddle.net/cmay2grr/2/
Steps:
0. use IE11
1. export to any format - image is with the issue visible

#### Affected browser(s)
IE11, Edge (export to SVG, other formats are not working)

**Comment by oysteinmoseng** [comment]
The issue also appears in PNG/JPEG export (which should work, by the way??).

The problem seems to be a rouge double quote in the SVG where the clip path is defined for the series.

`<g xmlns="http://www.w3.org/2000/svg" class="highcharts-series highcharts-series-0" clip-path="url(#highcharts-6&quot;)"`

This double quote is not present when exporting from other browsers.

**Comment by KacperMadej** [comment]
Just to refer to the commit comment - the issue is still visible in IE11.

**Comment by oysteinmoseng** [comment]
Strange, the SVG used for export now seems to be correct.

**Comment by KacperMadej** [comment]
IE11 - PNG and JPEG are not fixed while SVG is working fine.

In Edge all seems to be working fine now.

**Comment by oysteinmoseng** [comment]
This is apparently an issue with CanVG, also apparently fixed in the latest version.

Temporary workaround: Include the latest CanVG on your page, and the offline-exporting module will use that instead of the default one.

We will update the CanVG version auto-downloaded for Highcharts 5.0, so this will soon be a non-issue.
