### ISSUE TITLE
Highcharts JS v4.2.6 multiple export giving a blank page both in server side export and client side export.

### ISSUE THREAD

**Issue by vivek00711** [highcharts/highcharts#5570]
#### Expected behaviour
Highcharts JS v4.2.6 -- >Export all chart together.

#### Actual behaviour
Highcharts JS v4.2.6 -- >Not exporting any chart and giving a blank page.

#### Live demo with steps to reproduce

http://jsfiddle.net/highcharts/eatqca8n/
http://jsfiddle.net/highcharts/gd7bB/

#### Affected browser(s)
All major browser.

**Comment by TorsteinHonsi** [comment]
The same happens in our official fiddle as linked from our FAQ: http://jsfiddle.net/highcharts/gd7bB/

To do:
* Fix the problem
* Move the demo into our samples/highcharts/exporting section so that it is part of the automated test suite. 
* Update the link from the FAQ.
* Mention it in the exporting section of the docs (and the API?).

**Comment by oysteinmoseng** [comment]
Caused by hidden tooltip position now being `-9e9` instead of earlier `-9999`. Can be solved by changing to e.g. `-9e7`, but we should consider trying to do this with `display: none` styling instead.

**Comment by oysteinmoseng** [comment]
We could also strip out the tooltip from the export if it is hidden, to save a few bytes on exported file size.

**Comment by pawelfus** [comment]
@oysteinmoseng - there are cases, when tooltip is required by users, for example using `tooltip.refresh(point/points)`. I know that `refresh()` is not part of the API, but still it is used in our demos and commonly used. Just FYI.
