### ISSUE TITLE
Small markers are misaligned in export

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5571]
#### Expected behaviour

Aligned markers.
#### Actual behaviour

Markers are misaligned, not centered (like in the attachement)

![chart 4](https://cloud.githubusercontent.com/assets/2115686/17514835/2dbaa7b8-5e35-11e6-9726-a6b8434d8768.png)
#### Live demo with steps to reproduce
- https://jsfiddle.net/highcharts/yyav4qt0/1/
#### Affected browser(s)

All browsers

**Comment by TorsteinHonsi** [comment]
Thanks for the report. As you can see from the updated demo, it hasn't got to do with offline exporting. If I remove the offline exporting file, it looks exactly the same. Please remember to minimalize issue demos to eliminate sources of error! @pawelfus 

The real issue is probably related to rounding off path elements in order achieve crisp edges. Maybe this can actually be turned off in exporting for circle markers.
