### ISSUE TITLE
getSelectedPoints in drillupall event return empty array

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5583]
#### Expected behaviour

getSelectedPoints should return array of selected points in a main series - a top level.
#### Actual behaviour

An empty array is returned.
#### Live demo with steps to reproduce

http://jsfiddle.net/2mg7xf86/1/
1. Select point(s)
2. Drilldown into first category
3. Drillup via the 'Back to' button
4. In browser console an empty array is returned.
5. You could compare with the array with point(s) returned after the 'Get selected points' button click.
#### Workaround

setTimeout in drillupall for getSelectedPoints - http://jsfiddle.net/2mg7xf86/2/

**Comment by TorsteinHonsi** [comment]
It happens because in the event is [fired before the chart redraws](https://github.com/highcharts/highcharts/blob/v4.2.6/js/modules/drilldown.src.js#L354-L355), and the series.points array is not yet generated. We could probably call the event after redraw, but then we may introduce other problems. 

Also, the workaround is pretty straight forward.
