### ISSUE TITLE
Dynamically update chart with null data leads to weird extreme change

### ISSUE THREAD

**Issue by qingweibinary** [highcharts/highcharts#5591]
#### Expected behaviour
`series.setData` should not affect xAxis extremes

#### Actual behaviour
When series.setData is invoked with null data, `chart.redraw()` will change xAxis extremes involuntarily.

#### Live demo with steps to reproduce
Go to fiddle below, drag the navigator to the right a bit, then click `set new data` button. 
http://jsfiddle.net/8ahz6b2t/2/

#### Affected browser(s)
Chrome

**Comment by TorsteinHonsi** [comment]
It's a regression, it works correctly with Highstock 4.2.4.

**Comment by pawelfus** [comment]
Related commit: d120871

**Comment by qingweibinary** [comment]
@TorsteinHonsi I tried with 4.2.4,  
Part of it is fixed, still some issue

1. the xAxis min value is still being changed, is this the designed behaviour?
2. The chart gone blank

Fiddle: http://jsfiddle.net/fhh9skh5/1/

In my real use case, the issue is not fixed, I've attached a gif, not sure if it's useful to you guys

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/14971922/17760252/18bc61a0-6531-11e6-9c8c-fa8796dda280.gif)

Notice I drag the navigator, then when new data arrived (`setData` is called), the navigator shifted by itself.

**Comment by TorsteinHonsi** [comment]
After digging into this I'm not sure whether to call it a bug. The new minimum is calculated on [this line](https://github.com/highcharts/highcharts/blob/v4.2.6/js/parts/Scroller.js#L913). When a new maximum is set, the new minimum is calculated from the new max and the existing range. And since we have an ordinal X axis, we don't see clearly that all the points on the left are actually within a very small X range, so they fall outside the updated data range. Null values don't matter. See http://jsfiddle.net/highcharts/8ahz6b2t/4/. 

If we set ordinal to false it is clearer how we have a cluster of points to the left, and when we update the axis these fall outside the skewed range: http://jsfiddle.net/highcharts/8ahz6b2t/5/.

The only alternative way I can think of to deal with this would be that we preserve the actual pixel width of the navigator selection instead of the data range. 

@pawelfus Any opinions?

**Comment by pawelfus** [comment]
I agree, it's a good solution. In that way maybe we will be able to eliminate animation in the navigator (like here: http://www.highcharts.com/stock/demo/dynamic-update - left handler is oscilating ~2px left and right), but keep smooth animation on the detailed chart.

The only thing I'm worried about is live update and using width as a base range. Live data stock charts are quite popular and strange(r) things may happen during chart redraw and browser resize.

**Comment by TorsteinHonsi** [comment]
> The only thing I'm worried about is live update and using width as a base range

I guess it would need to be optional, the default behaviour would be like it is today.

**Comment by qingweibinary** [comment]
Hi ~ Is there any workaround I can use right now?

**Comment by TorsteinHonsi** [comment]
Yes, I found a workaround for you. Before you run `chart.redraw`, you can set `chart.scroller.fixedWidth = chart.scroller.range;`. 

[See it live](http://jsfiddle.net/highcharts/8ahz6b2t/6/).

**Comment by qingweibinary** [comment]
Thanks for the workaround, unfortunately it create some other issue, 

right after setting `chart.scroller.fixedWidth` the scroller at the bottom is locked and cannot be expand or shrink by mouse, it will back to normal after second attempt.

In my case this is unacceptable as we call redraw every 1 or 2 seconds.

**Comment by TorsteinHonsi** [comment]
What if you reset it to its original value (in this case `null`) after the redraw? http://jsfiddle.net/highcharts/8ahz6b2t/8/
