### ISSUE TITLE
Click events unreliable when multiple series are on a chart

### ISSUE THREAD

**Issue by sontek** [highcharts/highcharts#5622]
#### Expected behaviour
The click event defined on a point should fire when it is clicked on for at least the very top series (by zIndex/index?)

#### Actual behaviour
The click event does not fire.

#### Live demo with steps to reproduce
Try to click the point in April to see the issue:

http://jsfiddle.net/agnHV/22/

#### Affected browser(s)
Chrome, Safari

**Comment by sontek** [comment]
Now that I've looked at some of the other issues more closely, I believe this might be related or the exact same issue:

https://github.com/highcharts/highcharts/issues/5402
https://github.com/highcharts/highcharts/issues/4698

**Comment by sontek** [comment]
Here is an updated jsfiddle that shows the problem even more:

http://jsfiddle.net/agnHV/25/

You can see in April that if you click the points (2 stacked on top of each other) the one on bottom is triggered but the one on top is not.

**Comment by pawelfus** [comment]
*Internal note:*
Two things to mention:
- it still doesn't work for a polar type series, demo: http://jsfiddle.net/71ek1mn5/1/ - this is caused by using only `clientX` [here](https://github.com/highcharts/highcharts/blob/27f81b87229409146a146a110b6df62d53d8c703/js/parts-more/Polar.js#L26). Simple providing `plotY` or using `kdAxisArray: ['clientX', 'polarPlotY'];` doesn't resolve the issue. The problems are `dist` and `distX`, which are equall, so we hover top most series (always line-2). With 4.2.6 version it looks a bit better ( http://jsfiddle.net/71ek1mn5/2/ ) - but still, only "Line 2" series gets event callbacks.
- I refactored a bit `runPointActions` - now only one array is used `kdpoints`, which is sorted by distance, then sorted back to series order [here](https://github.com/highcharts/highcharts/blob/27f81b87229409146a146a110b6df62d53d8c703/js/parts/Pointer.js#L216-L218). I'm not sure if sorting again is a good idea, instead we can use another array, with just points for tooltip..
