### ISSUE TITLE
Zone colors affect candles too

### ISSUE THREAD

**Issue by borisyankov** [highcharts/highcharts#5630]
I am styling differently parts of my chart via zones.

Everything works great when I am in 'area' chart type.
When switching to candles, the positive candle has the custom style for zones applied, while the negative candle does not.

I would expect to be able to do one of these, or both:
1. Zones color do not affect any candle
2. Zones color do affect both candle.

Is that intended behaviour or a bug (or am I missing something)?

**Comment by TorsteinHonsi** [comment]
I can't see that the zone affects the candles at all - see http://jsfiddle.net/highcharts/crmrrg9x/

Can you make changes to that jsFiddle in order to demonstrate the problem?

From what you describe, it sounds like the [upColor](http://api.highcharts.com/highstock/plotOptions.candlestick.upColor) takes precedence over the zone color.

**Comment by borisyankov** [comment]
Hi @TorsteinHonsi 
I think the chart was configured incorrectly for the zones.
See the updated

http://jsfiddle.net/crmrrg9x/1/

**Comment by TorsteinHonsi** [comment]
Thanks for the demo!

The problem arises in [getAttribs](https://github.com/highcharts/highcharts/blob/v4.2.6/js/parts/OHLCSeries.js#L39-L60), where the _up_ points are given new color attributes based on the [upColor](http://api.highcharts.com/highstock/plotOptions.candlestick.upColor). 

One workaround is to borrow the column series' version of that function: http://jsfiddle.net/highcharts/crmrrg9x/2/
