### ISSUE TITLE
getExtremesFromAll insert all elements in DOM (slow performance)

### ISSUE THREAD

**Issue by marlonmleite** [highcharts/highcharts#5636]
#### Expected behavior

**getExtremesFromAll** should draw only the visible elements in the DOM as its off behavior, this functionality it should only calculate the range of minimum and maximum as the data provider. Never insert all elements in DOM.
#### Current behavior

With connected getExtremesFromAll, it inserts all the elements of the columns in the DOM and it can not, it is very bad and makes everything slow.
#### Live demo with steps to reproduce

http://jsfiddle.net/uc5jr3q9/

When analyzing the console with "getExtremesFromAll: true," the creation and use of the graphic is slow.

**Comment by TorsteinHonsi** [comment]
The problem is that when `getExtremesFromAll` is true, we don't crop the data in [Series.processData](https://github.com/highcharts/highcharts/blob/v4.2.6/js/parts/Series.js#L511-L527). And when the points are drawn we never check again whether it is inside the visible range, as a consequence all points are drawn.

In order to fix this we would need to split up this logic.
