### ISSUE TITLE
Smoothness of an animation

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#5655]
#### Behaviour
It seems that series animation enabled directly by animation property is not as smooth as animation by default. At some point animation just pauses and series is rendered immediately.

#### Live demo with steps to reproduce
http://jsfiddle.net/wefgo2qz/ - animation enabled by default
http://jsfiddle.net/wefgo2qz/1/ - animation enabled using animation property

#### Workaround
Set animation duration to 1000: http://jsfiddle.net/wefgo2qz/2/

**Comment by KacperMadej** [comment]
*Internal note:*

The animation ends in the middle and jumps to the final state. This is because if the `animation` option is set to `true`, then in [`animate`](https://github.com/highcharts/highcharts/blob/master/js/parts/Series.js#L884-L886) function of `Series.prototype` default option is used, but only in the scope of that function. Later on in code execution `render` function of `Series.prototype` is getting animation duration from the original option (that is set to `true`) using [`animObject`](https://github.com/highcharts/highcharts/blob/master/js/parts/Utilities.js#L931-L933) that returns `500` instead of default animation time which is `1000`.
