### ISSUE TITLE
stacked column border is not fully visible

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#5670]
There is a small issue connected with displaying stacked column series having borders.
I think that column borders should not be cropped for stacked column chart.  

Right now the part of border is not visible because of overlapping with different points borders:

![screen shot 2016-09-08 at 12 48 03](https://cloud.githubusercontent.com/assets/15050812/18346795/8bc4c132-75c2-11e6-87c1-dbe3852d7efa.png)

Live demo showing the issue:
http://jsfiddle.net/rvk0gc9r/3/

And here is more sophisticated example showing the issue: 
http://jsfiddle.net/rvk0gc9r/

**Comment by TorsteinHonsi** [comment]
It is designed this way because otherwise, with the default setting of 1px [borderWidth](http://api.highcharts.com/highcharts/plotOptions.column.borderWidth), we would get 2px borders between stacked columns.

If we do something about it, it needs to be as an option, where the default is the current behaviour. 

An equivalent in HTML/CSS is the [border-collapse](https://developer.mozilla.org/en-US/docs/Web/CSS/border-collapse) property.

**Comment by pawelfus** [comment]
**Workaround:**

Use your own rectangle, which will be rendered on top of the point on mouseover, demo: http://jsfiddle.net/LLo7324r/

Snippet:

- create a rectangle:

          chart: {
            type: 'column',
            events: {
            	load: function () {
              	this.haloRect = this.renderer.rect().attr({
                  'pointer-events': 'none',
                  'stroke-width': 10,
                  'stroke': 'black',
                  'fill': 'transparent',
                  'zIndex': 6
                }).add();
              }
            }
          },

- update on mouseover/mouseout:

              point: {
              	events: {
                	mouseOver: function () {
                  	var chart = this.series.chart,
                    	rect = chart.haloRect;
                    
                    rect.attr(this.shapeArgs).translate(chart.plotLeft, chart.plotTop).show();
                  },
                  mouseOut: function () {
                  	this.series.chart.haloRect.hide();
                  }
                }
              },

**Comment by TorsteinHonsi** [comment]
Another approach may be to modify the shape in an override of the `crispCol` function: http://jsfiddle.net/highcharts/rvk0gc9r/5/

**Comment by pawelfus** [comment]
Maybe changing width is also a good idea: http://jsfiddle.net/rvk0gc9r/6/

**Comment by krispy-visokio** [comment]
Hi,

This has been a big issue for us, and we have investigated a number of different approaches to solving it. We need to be able to show borders on individual stack elements as we allow users to click on the elements to select or de-select them. 

We tried several different approaches, with varying degrees of success.

In the end we managed to solve this issue by creating a copy of the SVG element that we want to highlight and applying the relevant styling to the copy. Because this is an independent SVG element we can ensure its shown in top of the other elements. I can post details of this solution and some fiddles showing it working if anyone is interested.

Chris
