### ISSUE TITLE
Error bar starts above column

### ISSUE THREAD

**Issue by danielflint** [highcharts/highcharts#5683]
#### Expected behaviour
Lower error bar should be below top of the column

#### Actual behaviour
Lower error bar is above the top of the column

#### Live demo with steps to reproduce
http://jsfiddle.net/h8ncujvj

#### Affected browser(s)
Chrome, IE Edge, Firefox

**Comment by pawelfus** [comment]
Hi @danielflint 

Thank you for reporting this issue. Actually, a column ends and an error bar starts in the same pixel, but columns have 1px white border by default, please take a look: http://jsfiddle.net/h8ncujvj/1/

I am not sure if we can (and should) somehow force bar 1px below, because we can't draw with a subpixel precision. Let's consider this example, by simple increasing height: http://jsfiddle.net/h8ncujvj/2/ - it works fine. However, what if change on y-value between column and error bar to be something like `0.000000...1` ? It's almost impossible to see that difference. 

Personally, I would enable zooming in the chart, so user will be able to zoom-in in a parts of data that is hard to distinguish, for example: http://jsfiddle.net/h8ncujvj/4/

**Comment by danielflint** [comment]
Hi,

I understand it is difficult to display decimal data using the integer representation that pixels are.

Adding the border is an option but it is better not to display borders around columns because it is then ambiguous to the viewer (who may know nothing about pixels) whether the value the bar represents is at the top of the border or at the point the body of the column and the border meet.

I can see how using the zoom will allow the chart data to be redrawn in a less ambiguous fashion but most users will not think to do this. Most users will think something is wrong with the data.

The problem is that to the viewer the error bar appears to begin after the column ends which is numerically impossible.

This is a fairly common issue when using error bars on small to medium size charts, you can even see it in HighCharts own demo here for Jul and Nov:
http://www.highcharts.com/demo/error-bar

Thanks

**Comment by pawelfus** [comment]
Thank you for your response! 

What I wanted to say is that columns have by default 1px white border, so I suggest to disable it or set border color to be the same as column, please take a look: http://jsfiddle.net/h8ncujvj/5/

Disabling border (`borderWidth: 0`) cause the same issue as you said, which for me is a bug.

> The problem is that to the viewer the error bar appears to begin after the column ends which is numerically impossible.

Of course you are right!

**Comment by danielflint** [comment]
Thanks, that's a very helpful explanation. Ideally we'd like the option for the column or bar border to be the same colour as the bar itself.

For our use case each bar in the data series is coloured red/amber/green according to whether or not it is different to the average value.

http://www.phoutcomes.info/public-health-outcomes-framework#page/7/gid/1000042/pat/6/par/E12000004/ati/102/are/E06000015

I think we will add a black border to these bars and that will allow us to display error bars that are unambiguous.
