### ISSUE TITLE
Highstock : A column serie added to a stockchart after the chart initialization disappears when user move the right handle of the chart navigator

### ISSUE THREAD

**Issue by Nalia** [highcharts/highcharts#5699]
#### Expected behaviour

User should change extremes with navigator handles even if a column serie is added to a stockchart after the chart initialization.

#### Actual behaviour

If a user add a column type serie to a stockchart after the chart initialization, then if user moves the right handle of the chart navigator, the column serie disappears.

It worked in Highstock version 4.2.4.

#### Live demo with steps to reproduce

http://jsfiddle.net/fq180r43/1/
Just play with the right handle in chart navigator to see that the column serie disappears.

#### Affected browser(s)

Chrome, Firefox, IE11, Edge

**Comment by pawelfus** [comment]
Hi @Nalia 

Thank you for reporting the issue! 

*Internal note:*
Fails after 472787c

**Comment by pawelfus** [comment]
**Workaround:**

Set series as dirty here:

    (function(H) {
      H.wrap(H.Axis.prototype, 'setScale', function(proceed) {
        proceed.call(this);
        H.each(this.series, function(series) {
          series.hasProcessed = false;
          series.isDirty = true;
        });
      });
    })(Highcharts);

Demo: http://jsfiddle.net/2vk70904/

*Internal note:*
The same way we can fix this, but the problem is deeper: [here](https://github.com/highcharts/highcharts/blob/2bba08ffe0ac1f90062885a1fd5856aae5229e05/js/parts/Scroller.js#L555-L557) and [here](https://github.com/highcharts/highcharts/blob/2bba08ffe0ac1f90062885a1fd5856aae5229e05/js/parts/Scroller.js#L702-L704) - do we need to use timeouts? Calling it directly in the stack works fine, without this issue.

**Comment by Nalia** [comment]
Hi @pawelfus,

Thank you for the workaround, it works well!

**Comment by TorsteinHonsi** [comment]
I'm not sure what the timeouts are there for, they seem to have been added when `liveRedraw` was first implemented. If it works fine without them, we should remove them.

**Comment by pawelfus** [comment]
*Internal note:*
After more digging, setTimeouts weren't culprits. On mouse up event, dataGrouping could change which caused destroying points, but not really recreating them (comment was old/misleading).

**Comment by TorsteinHonsi** [comment]
Great! Should you update the comment too?

**Comment by pawelfus** [comment]
Now that line does as comment says, so no changing comment :)
