### ISSUE TITLE
Highstock scrollbar not accept dynamic show/hide

### ISSUE THREAD

**Issue by marlonmleite** [highcharts/highcharts#5701]
#### Expected behaviour
I need show / hide scrollbar dynamic in javascript if issue https://github.com/highcharts/highcharts/issues/5700 is not 1 problem.

#### Actual behaviour
Not possible show/hide scrollbar in javascript methods.

#### Live demo with steps to reproduce
http://jsfiddle.net/44aft/164/

**Comment by pawelfus** [comment]
In Highcharts 5, there will be method `chart.update()` to update chart options, like scrollbar. Changing Highcharts inline options won't work.

At this moment, you can set scrollbar for an axis, instead of general one In that way, you are able to call `Axis.update()` with disabled scrollbar, please take a look: http://jsfiddle.net/8d4g8p22/1/

**Comment by marlonmleite** [comment]
Is perfect, thanks.
