### ISSUE TITLE
addPoint with a shift loses all data in the chart

### ISSUE THREAD

**Issue by Hammit** [highcharts/highcharts#5720]
#### Expected behaviour

I expect a new point to be added to the existing points in the chart
#### Actual behaviour

I lose all previous points and the new one is added in the middle
#### Live demo with steps to reproduce

https://jsfiddle.net/naqtkdLk/
#### Affected browser(s)

Chrome, FireFox (and presumably others)
#### Additional Notes

Works in 4.2.6, fails in latest version (4.2.7)

**Comment by Hammit** [comment]
Here is my [Stack Overflow Question/Post](http://stackoverflow.com/questions/39631105/highcharts-losing-all-data-when-addpoint-is-called) relating to this

**Comment by pawelfus** [comment]
Hi @Hammit 

Thank you for reporting the issue!

*Internal note:*
It's a regression, responsible commit: 56e5280

**Comment by TorsteinHonsi** [comment]
Reduced demo: http://jsfiddle.net/naqtkdLk/2/

**Comment by TorsteinHonsi** [comment]
#### Workaround
Instead of appending points with a `name` property, set the categories directly: http://jsfiddle.net/naqtkdLk/3/

**Comment by Hammit** [comment]
Thank you for the Workaround :)

**Comment by TorsteinHonsi** [comment]
The underlying problem here is that the  X axis initially is defined with a `categories` array, but then a point is pushed with a name/value pair as documented in `axis.type = 'category'`. This combination is currently not implemented in the [point.name logic](https://github.com/highcharts/highcharts/blob/v5.0.0/js/parts/Axis.js#L879-L939).
