### ISSUE TITLE
Highstock multiple series with big distan

### ISSUE THREAD

**Issue by qingweibinary** [highcharts/highcharts#5726]
Hi there ~

I am trying to allow my chart to show data in the future, like this

<img width="1150" alt="screen shot 2016-09-23 at 2 32 47 pm" src="https://cloud.githubusercontent.com/assets/14971922/18776280/a8b78ac0-819a-11e6-9a96-28ed09d99558.png">

Notice there's a plotline on the right side where there is no data.

I am not sure what is the best way to achieve such effects, so I tried to create an invisible series so that chart is aware of that empty region.

Now I am facing a problem which that if the 2nd series is too far from my main data series (eg. 3 months later), the chart will not work properly, check the fiddle below

#### Live demo with steps to reproduce
http://jsfiddle.net/588oqzfc/1/

**Comment by pawelfus** [comment]
Hi @qingweibinary 

The problem is which points you want to add. Consider this example: http://jsfiddle.net/588oqzfc/3/ - the only difference is disabled dataGrouping. Your data has a very low resolution, distance between points is around twelve seconds. And distance between first point and last point is 33minutes. Then you add a point 3 weeks later. DataGrouping is enabled so all your points are grouped into one point (you can see tooltip on the chart). 

If something is not clear, don't hesitate to contact us directly ( see [support info](http://www.highcharts.com/support)).

**Comment by qingweibinary** [comment]
Hi @pawelfus 

Thanks for pointing out the problem. It works great.
