### ISSUE TITLE
Series with softThreshold set to false should apply minPadding

### ISSUE THREAD

**Issue by khoomeister** [highcharts/highcharts#5732]
#### Expected behaviour

Series with softThreshold set to false should apply minPadding.
#### Actual behaviour

Series with softThreshold set to false and zoomed area with a line series on 0 won't apply minPadding on axis.
#### Live demo with steps to reproduce
1. http://jsfiddle.net/khoomeister/pLcf2tmj/14/
2. Drag zoom over straight blue line (i.e. right axis line), ensuring that zoomed in area only shows straight blue line.
   ![image](https://cloud.githubusercontent.com/assets/681288/18855544/8e86153e-8408-11e6-9112-188d9db727de.png)
3. Notice blue line on the bottom of the plot area whereas disabled softThreshold with default minPadding setting (0.5) should ensure there is some gap.
   ![image](https://cloud.githubusercontent.com/assets/681288/18855573/c3c65312-8408-11e6-9402-93bfcd2a7b4f.png)

**Comment by pawelfus** [comment]
Hi @khoomeister, thank you for reporting the issue. In fact, there are two problems: the range has only 0-value points, so yAxis is not able to calculate extremes: min = max, you can see what actually happens here: http://jsfiddle.net/jgv9e97d/1/ - when using just one series. The second is  [`chart.alignTicks`](http://api.highcharts.com/highstock/chart.alignTicks) (which is set to true by default) - that option forces an axis to set [`yAxis.tickAmount`](http://api.highcharts.com/highstock/yAxis.tickAmount), you can see the result for one axis here: http://jsfiddle.net/jgv9e97d/2/

I think the real issue here is how ticks are computed: probably `ticksAmount` should add not only higher ticks but also lower. 

*Internal note:*
Highcharts demo: http://jsfiddle.net/jgv9e97d/

**Comment by khoomeister** [comment]
I see, thx for the background info!

At this stage, I'll stick with having the line at the bottom for the time being - setting alignTicks: false with the messy grid lines is not great (and hiding them for an axis doesn't really work either from an eyeballing perspective).

Since my issue title only reflects the symptom, feel free to rename the issue, etc. to suit your purposes!
