### ISSUE TITLE
Dynamic chart rendering (addPoint)

### ISSUE THREAD

**Issue by rbc469003** [highcharts/highcharts#5741]
#### Expected behaviour

The Series.addPoint method should keep the existing points unless shift parameter is true. 
#### Actual behaviour

Only one point remains using version 4.2.7 while works as expected using version 4.2.6.
Also xAxis labels are wrong using 4.2.7.
#### Live demo with steps to reproduce

The following are exactly the same code using 4.2.6 & 4.2.7 respectively.
http://jsfiddle.net/hkuqqfgj/6/
http://jsfiddle.net/hkuqqfgj/7/
#### Affected browser(s)

Tested using Edge only.

**Comment by oysteinmoseng** [comment]
Offending commit: 56e5280. There have been some changes to the axis categories logic, introducing a new API option [xAxis.nameToX](http://api.highcharts.com/highcharts/xAxis.nameToX).

Workaround/Fix: Set `xAxis.type` to `category` instead of initializing with an empty categories array. [Example](http://jsfiddle.net/hkuqqfgj/8/)

@TorsteinHonsi is this a bug, or is an empty categories array supposed to fail?
