### ISSUE TITLE
Uneven pixel sizes / spacing with pointPadding

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5755]
#### Expected behaviour

Constant spacing between bars across all categories.
#### Actual behaviour

Sometimes it's 1 pixel, sometimes it's 0 pixels.
#### Live demo with steps to reproduce

http://jsfiddle.net/vjbjpka6/1/
#### Affected browser(s)

Best to view in Chrome, but the issue is a general one.

**Comment by TorsteinHonsi** [comment]
It is important to set `pointPadding` to 0 if you want to achieve tightly packed columns. If it is 0, columns will consider the next column when doing antialiasing. Otherwise, it will just round off to the nearest pixel: http://jsfiddle.net/highcharts/vjbjpka6/5/

**Comment by MiroLiska** [comment]
Hi Torstein. The problem is that I do not want to achieve tightly packed columns. I "simply" want that the columns (or bars) have always the same spacing between them. If some of the spaces are 0, and some 1 pixel wide like now, the chart looks buggy. The current rounding logic should be replaced by something more sophisticated. Please do not forget that the chart may be placed in a resizable container. I have no idea whether the spacing should be set to 0 or 5 pixels. The same way I do not care how wide are the columns (or bars) themselves, your algorithm should be calculating all of these things.

**Comment by TorsteinHonsi** [comment]
The current rounding logic was designed to make sure that all columns have the same width or spacing, but it looks like this too is broken now: http://jsfiddle.net/highcharts/8v85hbcg/

**Comment by TorsteinHonsi** [comment]
Consider the following example: http://jsfiddle.net/highcharts/8v85hbcg/1/

In this case, the data is laid out so that each column is ~1px wide, and the gap between them is also ~1px. If we are to normalize this, we need to put in an extra pixel from time to time. Currently this is done on the columns, and the result is unfortunately quite visible. Alternatively we could add it to the gaps, but it would be equally visible.

**Comment by MiroLiska** [comment]
Hi. My problem is actually the gap between individual series which is due to rounding "randomly looking". 
See the rounding effect in the current solution at http://jsfiddle.net/af1hvda0/ and my solution at http://jsfiddle.net/af1hvda0/1/ .

**Comment by TorsteinHonsi** [comment]
Yes, I know this. The problem is that we need to decide whether to go for
equal-size columns or equal-size gaps. We can't have both. Your case is
only one case out of many. My example is another case of the same basic
problem. We need a solution that works well for as many cases as possible.​

**Comment by MiroLiska** [comment]
Hi. I have programmed my plugin the way that all the columns are equal and all the gaps as well. Plugin will not react to columns narrower than 1 px, e.g. the examples with 500 columns displayed on the 300px container are handled as it was before. Please see http://jsfiddle.net/af1hvda0/2/  and try to create a normal use case where the plugin delivers worse results than the current solution.

**Comment by TorsteinHonsi** [comment]
Thanks for sharing! You're right, it probably won't give worse results, only fix some cases. Which is of course an improvement.

But in a case like this, http://jsfiddle.net/highcharts/af1hvda0/3/, the gaps are still uneven... Does your plugin only apply to multiple columns?

**Comment by MiroLiska** [comment]
Yes, my problem is that the gaps between series were "random" for quite standard looking charts.

    if (nuDone <= 1 || ret.width < 1) {
      return ret; // there is nothing to optimize
    }

**Comment by matixmatix** [comment]
I'm also having difficulties making my charts to have the same spacing (check the image below). Are there any near future plans to address this issue?
![image](https://cloud.githubusercontent.com/assets/273660/23292719/fb526a30-fa61-11e6-9f21-eee00dbfbd82.png)

**Comment by TorsteinHonsi** [comment]
The logic in question is in the [crispCol function](https://github.com/highcharts/highcharts/blob/v5.0.7/js/parts/ColumnSeries.js#L177). As you can see from the code, it rounds the edges to the nearest pixel in order to render crisp on screen.

This is how it looks by default: http://jsfiddle.net/uacuoybm/

And this is how it looks when overriding the crisping function: http://jsfiddle.net/uacuoybm/1/. As you see it is now equal spacing, but it looks more blurry. 

Perhaps we should just add an option for this? In some cases it may look better with a little blur than inequal spaces? What do you think?

**Comment by matixmatix** [comment]
@TorsteinHonsi I would be happy if I could opt into this behaviour! In my case, a little blur looks a lot better than uneven spacing.

**Comment by MiroLiska** [comment]
Hello Torstein

I have seen that you have closed this issue, now having the option 'crisp' for column charts. However, this option does not solve my problem at all. It may be a solution for a problem reported by matixmatix, I am not sure, but surely it does not do anything with the chart I have prepared on http://jsfiddle.net/vjbjpka6/1/ - that one still looks ugly when using 'crisp' set to false. I beg you to have a look at the solution I have presented here at http://jsfiddle.net/af1hvda0/2/ -it may not be the best one but I have not seen anything better until now.

Thanks in advance

Miro

**Comment by TorsteinHonsi** [comment]
Thanks for your suggestion Miro!

As I understand it your plugin aims for equal distance between the columns by analyzing neighbour columns? I think there are still some fail cases, like http://jsfiddle.net/highcharts/af1hvda0/5/ where it apparently doesn't analyze other columns in the same series. 

It's a nice concept, and it should probably be doable to make this work all over. There's one logic thing to be decided though - at some point we need to choose between equal distances or equal column widths. But we can do it the simple way and leave that as an option...

**Comment by MiroLiska** [comment]
Hi

This is not a fail case. I do not optimize this case at all, I leave your standard behavior in this case:

if (nuDone <= 1 || ret.width < 1) {
  return ret; // there is nothing to optimize
}

My problem were random gaps between series with a few values and not for charts with one series with hundreds of values - this was probably the problem of the other guy, but not mine. Please have again a look at http://jsfiddle.net/af1hvda0/2/ - this is chart which is definitively not going to extremes - it has just 3 series x 7 values. And it looks buggy with standard highcharts solution - the gaps between series are random.

My solution solves this case and even some extreme ones like http://jsfiddle.net/af1hvda0/6/ , although this is definitively not my goal.
