### ISSUE TITLE
Downsampling is not properly displaying graph with null values.

### ISSUE THREAD

**Issue by wheli** [highcharts/highcharts#577]
If you have a large data set with null values, highstocks will connect the graph in a misleading way when you are zoomed out all the way.  If you zoom in though, it seems to properly display the graph.

http://highslide.com/forum/viewtopic.php?f=12&t=13493

**Comment by drio** [comment]
I am running into this same issue. I have a data set with nulls included so HC shows gaps when rendering the chart. The problem is HC ignores the gap (connects the two points in between the gap) when the chart is resized and becomes small. 

I believe what is happening is the data density is high so the downsample kicks in and the nulls are removed.

I tried to follow the advice of using the approximation option to use my own downsample function to return null when the array to downsample contains nulls. Unfortunately, I run into this:

![gaps](https://cloud.githubusercontent.com/assets/17954/18186034/6c885f44-706e-11e6-9408-f98f739b6252.gif)

Notice how the line chart disappears as the chart has less area for drawing. 

As an alternative solution, I tried to reduce the `groupPixelWith` value. That solves the issue but then I run into other visual artifacts:

GPW = 5

![screen shot 2016-09-01 at 6 00 47 pm](https://cloud.githubusercontent.com/assets/17954/18186332/3ba300f8-7070-11e6-8a80-8fdcb721eaee.png)

GPW = 2

![screen shot 2016-09-01 at 6 00 38 pm](https://cloud.githubusercontent.com/assets/17954/18186312/2220fc48-7070-11e6-9712-7e0627bcbabc.png)

What's the best way to make sure HC respects the gaps at any size and also I avoid those visual artifacts?
