### ISSUE TITLE
Highcharts 5.0 - afterSetExtremes not triggered after Axis update

### ISSUE THREAD

**Issue by qingweibinary** [highcharts/highcharts#5773]
#### Expected behaviour
afterSetExtremes should be triggered everytime extremes changed

#### Actual behaviour
It is only trigger onload, and never trigger after that despite how I change extremes

#### Live demo with steps to reproduce
http://jsfiddle.net/uur9wr57/

1. open console
2. click the button
3. No message is log

#### Affected browser(s)
Only tested in chrome

**Comment by pawelfus** [comment]
Hi @qingweibinary - it should be `xAxis.events.afterSetExtremes`, not `xAxis.afterSetExtremes`, see working demo: http://jsfiddle.net/e6psyt40/

**Comment by qingweibinary** [comment]
Hi @pawelfus 

Really sorry for wasted your time, the bug is still there, but my method to reproduce was wrong

Here's an updated fiddle that illustrate it

http://jsfiddle.net/uur9wr57/2/

1. click button
2. try to move the extremes and now events is not triggered
3. from the console output, it seems calling `update` method remove the events options

**Comment by pawelfus** [comment]
Oh, now I see, thank you!

Highcharts demo: http://jsfiddle.net/qyg3ee7b/

Steps to reproduce the issue:

- drag&drop to zoom in: callback is executed
- click `Update xAxis`
- drag&drop to zoom in: callback is not executed anymore

**Comment by jschuler** [comment]
Also affects setExtremes event

**Comment by thewholuver94** [comment]
Hi,

I believe this bug needs to be reopened. The latest version of Highstock (probably Highcharts as well) still has this bug. The original chart.options object is mutated so that the callback function is removed from the config. You can work around this by adding the {event: callbackfunction} to the update call, but this creates unclean code.

Here is a fiddle showing log prints that after update, the `chart.options.xAxis[0].events` is deleted:
http://jsfiddle.net/axbc7m5r/5/

best

**Comment by pawelfus** [comment]
Hi @thewholuver94 

Thanks for reporting, but it looks right to me: http://jsfiddle.net/BlackLabel/yz4q5ts6/ - apart from missing `options.xAxis[0].events.<name>`, event is properly called.

**Comment by thewholuver94** [comment]
Hey @pawelfus , that's true, the event is properly called in the Fiddle.

In our implementation (legacy code that I can't really touch), we have decided to make dynamic changes to the chart.options object & when we want to redraw we destroy and construct a new chart each time using the options object. For users who do it this way, the event is not properly called because the event was erased from the options object. Another reason I can't just move to doing it the correct way using the Highcharts API is because we have to support Highstock 2.1.7 & Highstock 7.0.3 simultaneously & not all functionality is available in v2.1.7.

I've already given a workaround above (save the callback function & send it along with the update call), but I just thought I'd let you guys know in case mutating the original options object is unwanted behavior.

**Comment by slutske22** [comment]
@pawelfus  I am experiencing this bug again with highcharts 9.  Here is an example: https://codepen.io/slutske22/pen/MWrQdvQ?editors=1011

```js
  navigator: {
    height: 80,
    xAxis: {
      events: {
        afterSetExtremes: e => {
          console.log(e);
        },
      },
    },
  },
```

The `afterSetExtremes` function, or even the `setExtremes` function is only firing once, not every time the user makes a changes with the navigator handles.  Is this bug back?  Am I doing something wrong?  Is there a workaround I can use in the meantime?  The above jsfiddle links keep crashing for me.

**Comment by pawellysy** [comment]
Hello @slutske22!
You set the event to work on navigator axis, which has constant extremes so that the event only fires once. If you set the event to the main xAxis (which extremes are changed by navigator) everything works as expected. 

Check the following demo: https://jsfiddle.net/BlackLabel/9b1p5vkn/156/

**Comment by slutske22** [comment]
@pawelfus , yes!  That is exactly what I needed, thank you!
