### ISSUE TITLE
Bars look fuzzy in styled mode

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#5774]
Note - click the images to open then with 100% zoom.

#### Expected behaviour

![image](https://cloud.githubusercontent.com/assets/33569/19062223/fc769970-89ac-11e6-84ad-3207c4e9a2c8.png)
#### Actual behaviour

![image](https://cloud.githubusercontent.com/assets/33569/19062218/f0b350ec-89ac-11e6-9781-bab8d0c47fd7.png)
#### Live demo with steps to reproduce

http://jsfiddle.net/dandv/1wzh7fvz/
#### Affected browser(s)

Latest Chrome and Firefox

**Comment by TorsteinHonsi** [comment]
The problem is somehow related to the `borderWidth` setting for the columns. The borderWidth is set to 0 in the configuration, which affects the layout, but the `stroke-width` is set to 1px in the CSS. 

#### Workaround
Remove the `borderWidth` setting in the configuration. http://jsfiddle.net/highcharts/1wzh7fvz/1/

**Comment by dandv** [comment]
Thank you. Should [the example](http://www.highcharts.com/demo/column-basic) be updated to not include `borderWidth`?

Though I see the bug manifests in other examples that don't set borderWidth explicitly.

[Original](http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/stock/demo/candlestick-and-volume/) - [styled mode](http://jsfiddle.net/dandv/1mu7pm4s/1/).

**Comment by TorsteinHonsi** [comment]
_Internal note_:
The bug happens because we [compute the crisped shape](https://github.com/highcharts/highcharts/blob/v5.0.0/js/parts/ColumnSeries.js#L277-L282) arguments in the translate function. That's before we have access to the actual SVG element so we can read the rendered stroke width. 

In other aspects of the style mode, we first append the element, then read the computed stroke width, then apply the position. This may be a challenge for column charts because it breaks the current flow where we compute `shapeArgs` in the translate function and apply it in `drawPoints`. Perhaps it's time to drop the whole shapeArgs concept, that was designed for creating tracker overlays that we no longer use.

**Comment by TorsteinHonsi** [comment]
@dandv Another workaround is to set the `shape-rendering: crispEdges` property in CSS: 
```css
.highcharts-column-series rect {
    shape-rendering: crispEdges;
}
```
It will do the work for most cases, but it creates some overlap if you want tightly packed columns: http://jsfiddle.net/highcharts/1wzh7fvz/2/

**Comment by dandv** [comment]
@TorsteinHonsi: 9 months later, not sure I see the overlap in the fiddle above... has this been fixed, or should I look more closely?

**Comment by TorsteinHonsi** [comment]
Strangely enough I can't see any overlap either - not with the current version, and not with earlier releases of HC5.
