### ISSUE TITLE
Would like an option to create multichart like ChartDirector

### ISSUE THREAD

**Issue by joshuagenton** [highcharts/highcharts#5780]
#### Expected behaviour

Allow multiple charts to be created then added to one object where the y-axis is shared and the title.
Similar to the functionality of ChartDirector multiChart

I need to be able to create 3 charts:  day (daily values), week (avg of week), month (avg of month)
They can share y-axis, with the max being the max value of the three charts.

I can create the three charts separately and display them side by side but the y-axis and title on each chart disrupts the chart flow.
#### Actual behaviour

I have found code that shows an option to draw two charts on same chart but it has limited functionality.
#### Live demo with steps to reproduce

http://jsfiddle.net/jK6pb/5/  
example of multiple charts in highcharts

Will add a screenshot of the multichart from ChartDirector, when I can...
![ssmultichart](https://cloud.githubusercontent.com/assets/11083740/19096702/0b71f520-8a64-11e6-895d-7e1301aaa266.JPG)

**Comment by TorsteinHonsi** [comment]
This is a functionality we call _panes_ internally. We have been talking about a new feature where the user can define a pane, then assign axes to it, like we currently have with [polar charts and gauges](http://api.highcharts.com/highcharts/pane).

Unfortunately we don't have it currently. I think the best way to achieve this would be to inspect the data before it is added to Highcharts, in order to get the maximum, then share that between the series.

**Comment by pawelfus** [comment]
Actually, something similar can be achieved with just one xAxis and one yAxis, where xAxis is `category` type: http://jsfiddle.net/ram15m1q/ The only tricky part is to get exactly the same design as in ChartDirector, but I don't think we want do that..

**Comment by joshuagenton** [comment]
Thank you for the replies.  I managed to get the charts to appear as one.  I still need to inspect the values and assign a max to the y-axis, as Torstein suggested.  I like the fiddle, as well.
