### ISSUE TITLE
Handle in navigator has incorrect position

### ISSUE THREAD

**Issue by morganfree** [highcharts/highcharts#5800]
#### Expected behaviour

Left handle is on the left side of the navigator's outline, right handle is on the right side of the navigator's outlne.
#### Actual behaviour

Left handle is drawn on the right side of the outline. It caused by relatively big outlineWidth.
drawHandle() uses the same addition (halfOutline) for the left handle as for the right one: [L382](https://github.com/highcharts/highcharts/blob/master/js/parts/Scroller.js#L382)

It seems that the correction of 1.5 outlineWidth to the left does the work.
`scroller.drawHandle(zoomedMin - 1.5 * (outlineWidth - 1), 0);`
#### Live demo with steps to reproduce

http://jsfiddle.net/rrck76fe/1/

<br />
It seems also that a really big outlineWidth makes both handles' to be positioned incorrectly.
http://jsfiddle.net/rrck76fe/2/ It is a more general problem than the above one but I cannot think of any use case for such wide outline - so the priority for that case is rather low.

**Comment by TerjeBr** [comment]
The suggested fix would still not fix the problem.
The handles will be on the outside of the outline, right. But they will not be at the edges of the rectangle with the class "highcharts-navigator-mask-inside". And it seems to be that rectangle that determines where you can click to drag.

It would be a good fix if the click-able are was determined by the shapes of the handles instead of just the edge of that rectangle.

Also that recangles position is buggy, it starts on the inside of the outline on the left and extends to the outside of the outline on the right.

**Comment by pawelfus** [comment]
@TerjeBr 
Issue with click events is already fixed in 5.0.7 - we refactored events for navigator.

The commit above fixes also wrong outline position. Live demo with fix applied: http://jsfiddle.net/rrck76fe/6/

*Internal note:*
No unit-test. We would need to compare path with.. some hard-coded values (?), not really useful.

**Comment by TorsteinHonsi** [comment]
> No unit-test. We would need to compare path with.. some hard-coded values (?), not really useful.

@pawelfus In some cases, when dealing with graphics, it is best to just use auto-visual tests.

**Comment by pawelfus** [comment]
Ok, let me add auto-visual test then.
