### ISSUE TITLE
Docs: clarify that addPoint mutates the series data array

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#5807]
I'm reading points from a file and I was expecting the following code to add points from an array to the series, then terminate:

``` js
chart.series[0].setData(newPoints);
// ...
while (newPoints.length) {
  for (let i = 0; i < newPoints.length; i++) {
    chart.series[0].addPoint(newPoints[i], false, false, false);
    ...
  }
  // read more points from the file into newPoints
}
```

The problem is that newPoints grows with every addPoint, so the `for` loop never ends.

setData and addPoint deal with a reference to the array of points, not with a copy internal to the chart.

**Comment by pawelfus** [comment]
Thank you for reporting. Do you think it's possible to recreate issue in jsfiddle? 

I think this issue is related to #4259 and #5772.

**Comment by dandv** [comment]
http://jsfiddle.net/dandv/0jkoLn5m/

Two suggested doc changes:

1. setData sets the chart's data array to *point to* a given array; it doesn't copy that array internally
2. given the above, addPoint mutates that array

**Comment by TorsteinHonsi** [comment]
Thanks, a note is added to the docs.

**Comment by dandv** [comment]
Another suggestion for the [addPoint documentation](https://api.highcharts.com/class-reference/Highcharts.Series#addPoint): it would be great to hyperlink [series.data] to the actual place in the docs where Object points are explained (apparently not https://api.highcharts.com/class-reference/Highcharts.Series#.data). Same for https://api.highcharts.com/class-reference/Highcharts.Point.html#update - what are the "advanced options" mentioned?

**Comment by KacperMadej** [comment]
The series.<seriesType>.data should be referenced. General link to series.line.data and info about possibility of differences in other series types should work fine in here.

Suggestion for both docs references suggested by @dandv :

> If it is an object, advanced options as outlined under `series.<seriesType>.data` (e.g. [`series.line.data`](https://api.highcharts.com/highcharts/series.line.data)) are applied. The available options may vary depending on series type.

What do you think about this @TorsteinHonsi & @dandv ?

**Comment by dandv** [comment]
https://api.highcharts.com/highcharts/series.line.data is a good start, but can other Point properties listed at https://api.highcharts.com/class-reference/Highcharts.Point be passed to addPoint?

**Comment by KacperMadej** [comment]
@dandv 
The other properties can be passed, but might do nothing (because they will be overridden later or will not be used because are read only) or might break something (e.g. setting read only property that is used for further actions / calculations).

This is rather complex and individual for each property if it will work or not. In general, some of those will work just fine in most of the cases, but judging from the current documentation those are not supported - you cannot expect them all to work at all times or after even a minor version update.

Some of them shouldn't be changed unless you cover all internal functions that are using the properties, like `series`, `dataGroup`, `selected`, `visible`.

A good docs improvement could be to provide info for each of the methods - is it read only? can it be safely used with `point.update`?

**Comment by pawelfus** [comment]
I think this should be clarified as is, without any extra changes:

- [Highcharts.Point](https://api.highcharts.com/class-reference/Highcharts.Point) is internal **class**. Each `Point` can be accessed via `series.points`/`series.data`
- [`series.<type>.data`](https://api.highcharts.com/highcharts/series.line.data) is list of available **options for a point**

In other words, when you add a point: `series.addPoint(options, ...)`, you add options, not `new Highcharts.Point(options);`. I wouldn't add the reference to `Highcharts.Point()` there at all, I think this will cause more confusion.
