### ISSUE TITLE
Comparing percent, multiple series, none show if one has all zeros

### ISSUE THREAD

**Issue by jschuler** [highcharts/highcharts#5814]
#### Expected behaviour
With multiple series, if only one of them has y-axis values of 0, should still be able to see the other series on the chart.

#### Actual behaviour
With multiple series, if only one of them has y-axis values of 0, then no series display.

#### Live demo with steps to reproduce
http://jsfiddle.net/fqjLgcek/1/
No series display because the last series has only zeros for it's y-axis value.
Commenting out the code that overrides the last series displays all the series again.

#### Affected browser(s)
Tested in Chrome

**Comment by pawelfus** [comment]
Thank you for reporting.

It looks like the idea ( [docs](http://api.highcharts.com/highstock/plotOptions.series.compare)):

> Compare the values of the series against the first non-null, non-zero value in the visible range.

Is not enough. However, I'm not sure what should we do with that kind of series. 

What do you expect @jschuler to happen with a series where all values are equal to zero? Percent comparison doesn't make sense, since all values are zeros.
