### ISSUE TITLE
boost not enabled with pointStart in series

### ISSUE THREAD

**Issue by taf2** [highcharts/highcharts#5815]
#### Expected behaviour
the graph to be rendered via boost in a canvas tag

#### Actual behaviour
the graph uses svg rect elements and lots of memory

#### Live demo with steps to reproduce
http://jsfiddle.net/p9arwwp8/2/

#### Affected browser(s)
seems to be all

**Comment by oysteinmoseng** [comment]
The issue is not with pointStart, but actually that your series do not have enough points in them to trigger the boost optimiziations. The threshold is by default set to 5000 points, as if a series has fewer than this many points the performance is usually fine with regular SVG rendering. You can change this with the `series.boostThreshold` option if you want to use boost with fewer points as well. Example: http://jsfiddle.net/p9arwwp8/3/.

**Comment by taf2** [comment]
Ah that's exactly what I was looking for.  Been optimizing for rendering 50+ graphs with 1400+ bars e.g. 1 bar for every minute in a given day and noticing that in this case memory consumption without boost was around 4G with boost is around 1G - still optimizing on my end but this so far looks to help a lot.  The issue without using boost was I noticed a lot of svg <rect> elements being created when profiling.  Running profiler again now to see what else we can optimize.  Thanks again - highcharts is great!
