### ISSUE TITLE
Treemap textShadow of dataLabels

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#5849]
#### Behaviour

In Highcharts v5.0.0 text shadows of data labels in treemap exported to PNG, JPEG or PDF looks duplicated. When exporting to SVG shadow does not appear. In the previous version (v4.2.7) text shadows look normal. Probably related to #3649.
#### Live demo with steps to reproduce

http://jsfiddle.net/u1vud03h/ - v5.0.0
http://jsfiddle.net/u1vud03h/1/ - v4.2.7

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

It's not specific to tree maps, happens in general: http://jsfiddle.net/highcharts/m0no3exh/

It has probably got to do with PhantomJS and how it handles scaling the export. 

_Internal note_:
Under any circumstance, it will probably be a good idea, both because of performance and simplicity, to replace the text shadow polyfill with a simple, underlying text element with greater stroke. When we first implemented the text shadow polyfill we used more fuzzy shadows, so that was not an option.
