### ISSUE TITLE
No data labels for small columns if dataLabels.rotation is different than 0

### ISSUE THREAD

**Issue by stpoa** [highcharts/highcharts#5861]
#### Expected behaviour

Show data labels for all columns
#### Actual behaviour

Lack of data label on small column
#### Live demo with steps to reproduce

https://jsfiddle.net/4geq0zq6/

**Comment by oysteinmoseng** [comment]
Thank you for reporting.

**Comment by pawelfus** [comment]
I think this is caused by [`dataLabels.crop`](http://api.highcharts.com/highstock/plotOptions.series.dataLabels.crop) option. When disabled renders labels: https://jsfiddle.net/4geq0zq6/1/ - and we can see that label is rendered ~1px outside the plotting area.

The question is why [`dataLabels.overflow`](http://api.highcharts.com/highstock/plotOptions.column.dataLabels.overflow) doesn't work in this case.
