### ISSUE TITLE
chart.redraw in highstocks is slow for large data

### ISSUE THREAD

**Issue by shubhijain106** [highcharts/highcharts#5870]
#### Expected behaviour
I have a line chart highstock with approx 500 series and each series contains max 150 points. I need to change color of my series many times. Each time I dynamically update the color of the series, it takes 10-15 seconds, which is not desired.
I do chart.series[i].update({color:xxx},false) for many series together and then call chart.redraw(false).
But still the performance is really slow.
Is there any alternative to chart.redraw() or any other way i can improve the performance

**Comment by oysteinmoseng** [comment]
If all you are doing is updating the color of line series, you could try something like this: http://jsfiddle.net/oysteinmoseng/kcat1a9x/.

Also, for more optimizing tips see our [FAQ](http://www.highcharts.com/docs/getting-started/frequently-asked-questions#optimize-performance).

**Comment by TorsteinHonsi** [comment]
May I ask in what scenario you are using 500 series? When we designed Highcharts we focused on making it fast with many points in each series, but didn't imagine charts with 500 series. Any insight is valuable. Maybe we have a different solution.

**Comment by shubhijain106** [comment]
I am trying to draw a stringline chart

**Comment by nobletime** [comment]
I'm building an electrophysiology application for which I use 32 series X 10 (sec) X  256 (sampling rate) = 81,920 data points need to passed to setData functions on series, followed by chart.redraw(false). I find a delay about 1 second for data points to be rendered. Browsing through the file with having to wait 1 second at 10 sec window time produces a very poor performance. If I can reduce that delay by a factor of 2, my problem will be solved. any idea?

I also have scrollbar liveRedraw set to false (otherwise it would be very slow).

**Comment by oysteinmoseng** [comment]
@nobletime I recommend looking into the [Boost module](https://www.highcharts.com/news/175-highcharts-performance-boost/) for such applications. It will probably help with redraw speed. Also make sure you are calling `setData` with redraw disabled. In [this example](http://jsfiddle.net/62naw1hh/) I'm getting about 200-350ms for creating and updating the data. Non-stock charts are even faster.

**Comment by nobletime** [comment]
Thank you for your post - greatly appreciated. My data are two dimensional like [x,y] so data looks like [[x1,y1], [x2,y2], etc] where y is in second starting from 0. Could this cause the extra slowlyness? 

Redraw in my setData is false and I've tried boost but didnt see major improvement with speed. 

By non-stock chart do you mean if I use highchart rather than highstock it would be quicker?

**Comment by 212579878** [comment]
Issue 1 : I am using highstock, with dynamic data , multiple axis (maximum 8). I need to add a datapoint to each series (all 8 axes) every second. After adding points, I am calling chart.redraw(false). I have disabled animation for both chart and series. The CPU usage ranges between 25-35 %. I would like to avoid boost coz I have a functionality to update chart type dynamically , so area chart doesn't looks as expected if i enable boost.  Any suggestion on improving CPU performance ?

Issue 2 : One more thing, I need to display data only for last 1 hour , so I enable shift after adding 3600 points to the chart (1 hour = 3600 seconds) , but it doesn't seems to be working for me.when i click on ALL (Range selector). It shows data for more than an hour. I am sure the shift is working (I have tested with less number of datapoints and when i export data so initial data timestamp differs between consecutive download which depicts datapoints are shifting) . But I am not sure why is it accumulating datapoints more than 3600.
