### ISSUE TITLE
Changing fill color of series in styled mode

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#5882]
#### Behaviour
Applying a new fill color by setting a className to series does not take effect. In the first example posted below series receive only stroke color from custom CSS class while fill color remains unchanged. Only setting the same CSS class both to series and its points will result in change of fill and stroke (second example).

#### Live demo with steps to reproduce
http://jsfiddle.net/8gv1xmzv/
http://jsfiddle.net/8gv1xmzv/1/

**Comment by TorsteinHonsi** [comment]
The problem is that the `.highcharts-color-0` CSS rule that you have defined applies to the _points_, while the `.my-class1` CSS rule applies to the whole series group, which is one level up. The the first one is more specific and takes precedence. In order for your styles to take effect, you need to specify `.my-class2 .highcharts-point`.

[View live demo](http://jsfiddle.net/highcharts/8gv1xmzv/2/).
