### ISSUE TITLE
Doubled yAxis when exporting

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5888]
#### Expected behaviour

Correct number of yAxis
#### Actual behaviour

yAxis are duplicated.
#### Live demo with steps to reproduce
1. Example: https://jsfiddle.net/8rx79uqp/
2. Export to any format (i.e png)

As a result we receive 4 yAxis, instead of 2.

**Comment by pawelfus** [comment]
It's caused by adding axes and series in callback. Callback is also executed when exporting a chart, so we get multiple series and axes. Enabled legend shows multiple series too: https://jsfiddle.net/8rx79uqp/2/

Workaround/solution:

Check `chart.options.chart.forExport` flag and don't add series when chart is being exported: https://jsfiddle.net/8rx79uqp/1/

**Comment by KacperMadej** [comment]
+1

**Comment by Izothep** [comment]
+1

**Comment by Newan** [comment]
+1

**Comment by pawelfus** [comment]
*Internal note:*
Issue reported by @Newan is duplicate of #6423
