### ISSUE TITLE
valueSuffix not applied when specifying the number of decimal places on pointFormat

### ISSUE THREAD

**Issue by inad9300** [highcharts/highcharts#5906]
#### Expected behaviour

When using a format like `{point.y:.2f}` on the tooltip's `pointFormat` property, the `valueSuffix` should still be applied.

#### Actual behaviour

The `valueSuffix` is ignored when the floating-point format is present.

#### Live demo with steps to reproduce
http://jsfiddle.net/highcharts/ewyd8jak/ => Hover the points to see the tooltip.

#### Affected browser(s)

Observed in the latest Google Chrome, probably affecting others.

**Comment by oysteinmoseng** [comment]
Workaround: Add the valueSuffix to the format string http://jsfiddle.net/rqvy6dpz/

**Comment by TorsteinHonsi** [comment]
Common for both workarounds is to use either a format string or the options, but not to combine them.

*Workaround 1*
Add the `valueSuffix` to the format string http://jsfiddle.net/rqvy6dpz/

*Workaround 2*
Use the `valueDecimals` option instead of a format string: http://jsfiddle.net/highcharts/ewyd8jak/2/
