### ISSUE TITLE
Series.update is not working with series in navigator

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#5936]
#### Expected behaviour

Series update should work with series in navigator just like for normal series.

#### Actual behaviour
It looks like Series.update() is not working for navigator series, series is not updated and an error is visible in console.

#### Live demo with steps to reproduce

http://jsfiddle.net/6p5cfnLy/8/

Steps to reproduce: Click on the button in jsFiddle

It looks that Series.update was working correctly with 4.2.7 Highcharts version:

http://jsfiddle.net/6p5cfnLy/9/

**Comment by oysteinmoseng** [comment]
We need to rewrite the entire updating logic for navigator series. Related issue: #5846. Currently we rebuild the navigator series from scratch every time any series is updated. That obviously messes up `adaptToUpdatedData`, and it also apparently fails when we try to update one of the navigator series directly (lost references after destroying the old series).

Instead of destroying the navigator series, we should `update` them, and if a new series should be added, we create it. This will take some rewriting.
