### ISSUE TITLE
Dynamic inversion doesn't work with certain chart types.

### ISSUE THREAD

**Issue by Rashaine** [highcharts/highcharts#5938]
The new chart.update() method doesn't seem to work correctly for inversion in column/line/area charts. Previous techniques for dynamic inversion such as setting the chart.inverted option then doing a axis.update({}, false) also no longer work in Highcharts 5.0.

#### Expected behaviour
Using chart.update() to change the chart inversion should work.

#### Actual behaviour
Inverts the axis but the datapoints are translated off screen and not inverted.

#### Live demo with steps to reproduce
http://jsfiddle.net/dhq37ezs/

#### Affected browser(s)
Chrome

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

Our [own demo and test](http://jsfiddle.net/gh/get/jquery/1.7.2/highcharts/highcharts/tree/master/samples/highcharts/demo/chart-update/) does this correctly, it turns out to be because it also sets `polar:false`. 

So a preliminary **workaround** for you would be to set polar: http://jsfiddle.net/highcharts/dhq37ezs/2/
