### ISSUE TITLE
Axis labels: autoRotation doesn't work if units are set

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#5945]
#### Expected behaviour
To avoid label overlapping labels should be rotated.

#### Actual behaviour
autoRotation option is ignored

#### Live demo with steps to reproduce
http://jsfiddle.net/89t5ro36/

Workaround: rotation is working - http://jsfiddle.net/89t5ro36/1/

**Comment by TorsteinHonsi** [comment]
It happens because the `tickInterval` is not known at the time [when the rotation is handled](https://github.com/highcharts/highcharts/blob/v5.0.2/js/parts/Axis.js#L1717).

I am not sure how to approach it.

A **workaround** is to use the `tickInterval` option instead of units: http://jsfiddle.net/highcharts/89t5ro36/2/
