### ISSUE TITLE
Performance limiation of highchart when creating hunderds of lines in one chart

### ISSUE THREAD

**Issue by HackToday** [highcharts/highcharts#5948]
#### Expected behaviour
What's the reasonable time for such chart to be rendered ?

#### Actual behaviour

Try this 
http://www.highcharts.com/studies/performance.php?seriesType=line&markers=on&chartCount=1&seriesPerChart=32&pointsPerSeries=4000&chartWidth=250&libSource=http%3A%2F%2Fcode.highcharts.com%2Fhighcharts.js

it would use  3 seconds ,

My cases would like this:  each line chart has at least 100 ~  600 lines,  each line have  8000 points.  It looks for me I want to know what's the expected reasonable time for such chart to be rendered. (it seems not possible in several seconds)

**Comment by TorsteinHonsi** [comment]
Highcharts has mainly been optimized for showing a high number of points in each series, especially through the [Boost module](www.highcharts.com/news/175-highcharts-performance-boost).

A high number of series, however, is not that optimized, because in most real-world situations there are just a limited amount of series in each chart.

May I ask how a chart with 600 line series is used?

**Comment by HackToday** [comment]
@TorsteinHonsi  For example, I have one cluster, (this cluster have 600 machines) , and each machine , I will collect matrics, like CPU, Memory Disk metrics.

For each metric, for example CPU,  I'd like to compare the 600 machines CPU usage in one chart.(**which means 600 line series in one chart**) then I can see clearly which is more CPU hungry which is idle. Such is a common use cases, it seems to me.

What do you think ?

**Comment by TorsteinHonsi** [comment]
I think we definately need to look into this. I did some experiments with the boost module, and unsurprisingly it turns out that the process of creating 600 canvases and copying the contents over to SVG image elements is expensive. 

Instead, we need to at least create an option to operate with one single canvas that is shared between all the chart's series. This canvas should be added to the `chart.seriesGroup`. I created a [gist with the results so far](https://gist.github.com/TorsteinHonsi/b726b2656bb9edb4d66aff0e05d7cc11), but currently the last series overwrites all other series. But it shows a real performance gain.

**Comment by leeoniya** [comment]
Hi @HackToday,

i'm the author of [uPlot](https://github.com/leeoniya/uPlot). i ran a test of 600 series x 8000 points based on @TorsteinHonsi's jsFiddle and was able to render the chart in 1250 ms. i'm currently working on removing the assumption that the x-axis is unix timestamps, but other than that it performs quite well.

https://jsfiddle.net/1po5hdys/

i would be interested viewing this on the real dataset rather than simulated, though. ping me if interested.

uPlot's origin is also in server perf-log monitoring :)

https://leeoniya.github.io/uPlot/bench/uPlot.html

cheers!
Leon

**Comment by TorsteinHonsi** [comment]
Since my fiddle was created, we have fixed this issue by allowing Highcharts to render all series on the same WebGL canvas. It now renders in 500-600 ms, so it is no longer considered a problem.
