### ISSUE TITLE
Y axis label formatter breaks when there is only a single data point

### ISSUE THREAD

**Issue by suganya-sk** [highcharts/highcharts#5956]
#### Expected behaviour
Y axis labels are formatted depending on certain threshold values - eg. ' M' is added to millions
Fiddle - http://jsfiddle.net/grpo8sv5/23/

#### Actual behaviour
Y axis labels are not formatted when there is only a single data point
Fiddle - http://jsfiddle.net/grpo8sv5/22/

**Comment by pawelfus** [comment]
Hi @suganya-suvadi 

It looks like a duplicate of #4986 - the problem is the same: how to calculate extremes when there is only one point.

Workaround: http://jsfiddle.net/ubzc3ze4/ and snippet:

    (function(H) {
      var UNDEFINED;

      H.wrap(H.Axis.prototype, 'getSeriesExtremes', function(p) {
        var axis = this,
          valueString,
          len,
          high,
          pow10,
          diff;

        p.apply(axis, [].slice.call(arguments, 1));

        if (!axis.isXAxis && axis.dataMin === axis.dataMax && axis.dataMin > 1) {
          valueString = value.toFixed(0);
          len = valueString.length;
          high = parseFloat(valueString[0]);
          pow10 = Math.pow(10, len - 1);

          diff = (high + 1) * pow10 - axis.dataMin;

          axis.dataMin -= diff;
          axis.dataMax += diff;
        }
      });
    })(Highcharts)

Idea is to modify `dataMin` and `dataMax` when extremes are exactly the same. It applies not only to one point, but also to all points with the same value. It's not a perfect solution, though.

@TorsteinHonsi - it's a common issue, like #5404 and probably some others. Maybe we should try to improve that case. The problem will be with other issues, where users requested to render one single point in the middle of a chart..

**Comment by TorsteinHonsi** [comment]
Pawel, your fiddle causes an error, so I can't actually see what you did.

> The problem will be with other issues, where users requested to render one single point in the middle of a chart..

Yes, it actually brings us back to where we were before, when we substrated and added a small value to the extreme just to make the axis display something. http://jsfiddle.net/highcharts/grpo8sv5/28/

**Comment by pawelfus** [comment]
@TorsteinHonsi - fixed demo: http://jsfiddle.net/ubzc3ze4/1/ - thanks!
