### ISSUE TITLE
Zooming doesn't save the aspect ration 

### ISSUE THREAD

**Issue by royigoldi** [highcharts/highcharts#5958]
Hi,

I define line chart with xy zoom type.
I zoom-in but the aspect ratio change also. (please think i displayed on label above the line, the linear calculation and after the zoom my values for ax+b that I dispaly doesn't fit what the user see).

Thanks,
Royi

**Comment by TorsteinHonsi** [comment]
Hi, currently zooming handles X and Y separately, so the aspect ratio is not preserved.

**Comment by royigoldi** [comment]
so why this behaivor happend? see the attach pictures, it look like the slope of a straight line change:

1:
![image](https://cloud.githubusercontent.com/assets/20413250/20259809/8d66fd3a-aa5f-11e6-8948-cb88fc56216b.png)

after zooming:
![image](https://cloud.githubusercontent.com/assets/20413250/20259836/b4e6787c-aa5f-11e6-9e79-50570b820815.png)

**Comment by TorsteinHonsi** [comment]
Yes, that's because the aspect ratio is _not_ preserved.

**Comment by royigoldi** [comment]
Their is a way to solve it?

בתאריך 14 בנוב' 2016 11:47 AM,‏ "Torstein Hønsi" <notifications@github.com>
כתב:

**Comment by pixelnix** [comment]
One way I have worked around this is to use the axis event handler "afterSetExtremes" to watch for changes in one axis's extremes, and then force the other axis's extremes to a calculated value in order to preserve the axes' aspect ratio.

http://api.highcharts.com/highcharts/xAxis.events.afterSetExtremes

Here's some code I wrote that does this.  I would've assigned this property to xAxis.events.  "axisRatio" in this example was previously calculated as the ratio of (xaxis max-min) / (yaxis max-min), or the ratio of the x-axis range to the y-axis range; one way to handle that is to calculate it the first time the redraw() handler is called.

`afterSetExtremes: function (e) {`
`    var xExtent = this.getExtremes(),`
`        yExtent = this.chart.yAxis[0].getExtremes(),`
`        yRange = yExtent.max - yExtent.min,`
`        xRange = xExtent.max - xExtent.min,`
`        newYRange = xRange / axisRatio;`
`    this.chart.yAxis[0].setExtremes(yExtent.min, yExtent.min+newYRange, true);`
`}`
