### ISSUE TITLE
Flags - text inside shapes is not aligned properly

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#5980]
#### Expected behaviour
Text should be vertically centered.

#### Actual behaviour
Text is on edges of triangle. The issue is the most noticable in flags with a triangle-down symbol.

#### Live demo with steps to reproduce
Demo: https://jsfiddle.net/Lpzguonk/

#### Affected browser(s)
All browsers

**Comment by jon-a-nygaard** [comment]
Thanks for reporting.

Internal Note:
[Simplified demo](https://jsfiddle.net/jon_a_nygaard/cct7xu51/)

**Comment by sorb999** [comment]
Thanks @jon-a-nygaard Thanks for your quick reply. I am the one who reported this issue to Highcharts :).
If you need more information about this then you can see [link to here](http://stackoverflow.com/questions/40625395/highcharts-flag-text-position-issue-with-different-shapes)

**Comment by pawelfus** [comment]
Isn't text actually centered? I mean in the simplified demo:

- triangle height = 19px
- fontsize = 11px

So to vertically align the text we need to calculate: 19 / 2 + 11 / 2 -> 15 (or 14 when flooring subpixels). When checking the `text.y` position, I can see 14.

**Comment by jon-a-nygaard** [comment]
Thanks @sorb999
It appears I was a little bit too quick to label this as a bug, these shapes are not compatible to be used with text. The recommended shapes to use with flags series are `flag`, `squarepin` and `circlepin`.

An option for you is to create your own custom shape. The following is a very simplistic example, but it does at least show how you can do so. [Custom shape](http://jsfiddle.net/jon_a_nygaard/cct7xu51/)

@pawelfus Yes, you are right. The text is centered, except for an pixel offset due to crisping.
