### ISSUE TITLE
HTML pointFormat Tooltip series.color [ styled mode ] set as undefined

### ISSUE THREAD

**Issue by garybrain** [highcharts/highcharts#5981]
#### Expected behaviour
Series name should reflect Series Color

This works with the classic mode 5.0.2

#### Actual behaviour
Series Color is set to "Undefided"

using "styled mode" 5.0.2.

#### Live demo with steps to reproduce

http://jsfiddle.net/hs8yhL4p/

#### Affected browser(s)
All browsers.

**Comment by garybrain** [comment]
Similar Problem with the Maps where the color is not correctly showing. Again works fine in classic.

http://jsfiddle.net/7r9Lpk8y/1/

**Comment by oysteinmoseng** [comment]
Not sure if this is by design, as we are intentionally separating presentational attributes and the code using styled mode. @TorsteinHonsi

**Comment by TorsteinHonsi** [comment]
It's by design, you can use the `highcharts-color-{series.colorIndex}` in the formatters now. The color class names are pre-populated with `fill` and `stroke`, but as you are using HTML text, you need to add the `color` property too. 

* First demo: http://jsfiddle.net/highcharts/hs8yhL4p/1/

As for the map, I think it's a different problem.

**Comment by garybrain** [comment]
Perfect, thanks for the update.
