### ISSUE TITLE
Only one will show a tooltip when multiple y values share a single x value

### ISSUE THREAD

**Issue by kevin52408** [highcharts/highcharts#5983]
#### Expected behaviour
If a single x value, such as a date, has multiple y values each point will be hoverable to show a tooltip.

#### Actual behaviour
Only one of the y values will show a tooltip. Sometimes it is the lowest value, sometimes it is the highest value.

#### Live demo with steps to reproduce
http://jsfiddle.net/9c5ymg47/

#### Affected browser(s)
Tested in Chrome and Firefox.

**Comment by oysteinmoseng** [comment]
Markers are also gone.

Worked in `4.0.4`, fails since `4.1.0`.

**Comment by TorsteinHonsi** [comment]
It happens because the spline series tooltip only looks for the closest point in the X dimension, not in X and Y. To change that, you can set the `kdDimensions` to 2 in the prototype ([live demo](http://jsfiddle.net/highcharts/9c5ymg47/2/)). 

The reason why we made it like that can be seen in [this demo](http://jsfiddle.net/highcharts/9c5ymg47/3/). The spike has a tendency to attract tooltips from far away, while with the default behaviour, we can drag the mouse pointer across the chart and read values in succession.

**Comment by kevin52408** [comment]
Better functionality for the majority of cases and still allows for the edge cases. Makes sense. Thanks.
