### ISSUE TITLE
Log axis ticks values are not rounded

### ISSUE THREAD

**Issue by papiscript** [highcharts/highcharts#5984]
#### Expected behaviour

Log axis ticks values are displayed properly - in this case rounded.

#### Actual behaviour

Log axis ticks values sometimes are not rounded. Example provided below. 
i.e 
should be 999
is: 999.99999999

#### Live demo with steps to reproduce
http://jsfiddle.net/99w72efv/10/

You can set max also to some other values like 700 or 9999. 

#### Affected browser(s)
I've checked FF, Chrome and IE11. For IE11 999 is displayed fine. But it breaks at other values i.e 700, 9999 etc.

**Comment by pawelfus** [comment]
@PiotrekPaprocki - thank you for reporting the issue!

As workaround, I suggest to use `xAxis.labels.formatter` in this case, for example: http://jsfiddle.net/99w72efv/11/

*Internal note:*
yAxis extremes after translation are actually wrong because of JS rounding. For example: `chart.yAxis[0].lin2val(chart.yAxis[0].max)` returns already `998.999999999995`. We can see that `chart.yAxis[0].max = 2.99956548822598`. Do we have an option to represent 999 as logarithmic value at all?

Minified demo: http://jsfiddle.net/tm7d8xmc/ or just: `Math.pow(10, Math.log(900) / Math.LN10)`.

**Comment by PiotrekPaprocki** [comment]
Thx for the fast answer. It's working but label formatter overrides default lang:numericSymbols. 
I've made nasty workaround for this to prevent showing huge numbers (and also added formatting for first element):
```
formatter: 
  function ()
    if(this.value % 100 === 0 && this.value > 100) {
      return (this.value/1000) + 'k';
    } else if (this.isLast) {
      return this.axis.options.max;
    } else if (this.isFirst) {
      return this.axis.options.min;
    } else {
      return this.value;
    }
}
```

Is there any option to preserve default numeric symbols in this case? 

Thanks

**Comment by pawelfus** [comment]
Default formatter is not part of the API, but you can call it anyway: http://jsfiddle.net/99w72efv/15/

```javascript
labels: {
  formatter: function() {

    if (this.isLast) {
      this.value = this.axis.options.max;
    }

    if (this.isFirst) {
      this.value = this.axis.options.min;
    }

    return this.axis.defaultLabelFormatter.call(this);
  }
},
```

**Comment by PiotrekPaprocki** [comment]
Works great. Thanks.
