### ISSUE TITLE
allowHTML with offline exporting

### ISSUE THREAD

**Issue by morganfree** [highcharts/highcharts#5985]
#### Expected behaviour
With offline exporting, html elements in the chart are visible in the exported images.

#### Actual behaviour
HTML elements are not visible.

#### Live demo with steps to reproduce
http://jsfiddle.net/z4m4wmom/

#### Affected browser(s)
Tested in Chrome 54

**Comment by oysteinmoseng** [comment]
Thanks for reporting. We'll take a look as soon as possible.

**Comment by oysteinmoseng** [comment]
Neither canvas/CanVG nor svg2pdf support `foreignObject` and HTML rendering, so we have to fall back to online export for PNG, JPEG and PDF export. SVG support should now work, however, and it falls back gracefully for the other output types.

**Comment by ellier7** [comment]
Is there a way to style PDFs with client side exporting? If I set allowHTML to true and disable fallbackToExportServer, exporting does not work. I need to use offline exporting but PDFs are not styled nicely when exported

**Comment by oysteinmoseng** [comment]
@ellier7 There are limitations to what kind of HTML would be supported in PDF export, but colors etc should not be an issue. Do you have a demo of what you want to achieve?

**Comment by ellier7** [comment]
@oysteinmoseng It's mostly font style (size and family)

**Comment by oysteinmoseng** [comment]
@ellier7 I see. You should not need `allowHTML` for those (see e.g. http://jsfiddle.net/9rao0z3r/), but font styles can be problematic in PDF export regardless, because the conversion library doesn't seem to handle custom fonts very well. Presumably you are not looking to export to default fonts.

Is installing our node-based export server locally an option? There you would be able to install custom fonts and keep control of all aspects of the export.
