### ISSUE TITLE
Issue with logarithmic axis

### ISSUE THREAD

**Issue by pliasetski** [highcharts/highcharts#6021]
Hello,
Series that belongs for bottom axis is stucked to the left. Bottom axis is logarithmic. When it set it to linear it's workes correct.

#### Live demo with steps to reproduce
http://jsfiddle.net/Pashe4ka/xkx1mgtc/2/

#### Affected browser(s)
Latest version of Chrome

**Comment by pawelfus** [comment]
Hi @pliasetski 

Thanks, but I think you may have misconfigured the demo. Series 2 & 3 are connected to the yAxis = 1, which is the top yAxis. The scale is correct, because Series 3 has quite high values when comparing to the Series 2. If you hide Series 3, you will see the Series 2 rescaled.

Let me know if I missed something.

**Comment by oysteinmoseng** [comment]
I think I see the issue, looks like the bottom axis gets `NaN` for all ticks somehow. Simple example: http://jsfiddle.net/vm8xeg3s/.

Workaround: Set `chart.alignTicks: false` (http://jsfiddle.net/xkx1mgtc/3/)

**Comment by pliasetski** [comment]
Hi @pawelfus 
The problem is with Series 1. It is stucked to the left. It is only one Series that connected to the yAxis = 0, so why it isn't displayed on the entire chart.

**Comment by pawelfus** [comment]
Ha! @oysteinmoseng is right, I tested this in a small window, like this: http://jsfiddle.net/xkx1mgtc/4/ - when it works fine :) 

*Internal note:*
I guess, `alignToOthers()` should also consider axis type.
