### ISSUE TITLE
colorAxis.update still broken

### ISSUE THREAD

**Issue by radiolips** [highcharts/highcharts#6025]
#### Expected behaviour
Calling chart.colorAxis[0].update({key: value}) should update ONLY key, as defined in documentation.

#### Actual behaviour
Calling chart.colorAxis[0].update wipes information.

#### Live demo with steps to reproduce

Unfortunately I have not yet tracked down which of my axis properties is causing the issue, but the following is a screenshot of the broken colorAxis: https://www.dropbox.com/s/0vrme1v0mjina61/Screenshot%202016-11-23%2012.55.01.png?dl=0

This is directly related to this: https://github.com/highcharts/highcharts/commit/c4b0130f2b85a7576ef0a42fda76d2dac3cdf12b
and this closed ticket, where I have more information:
https://github.com/highcharts/highcharts/issues/5881

**Comment by oysteinmoseng** [comment]
Thank you for reporting this. It would be great if you could narrow down what causes the issue, as updating e.g. `stops` now seems to work fine: http://jsfiddle.net/slorenc/01bsb417.

The code block you are referring to in the other issue is part of `Axis.destroy`, and is supposed to destroy all properties as we are destroying and recreating the Axis with new options.

**Comment by radiolips** [comment]
Thanks. I know that `stops` works fine by itself and that the code block destroys `Axis` properties. I will continue to try to determine exactly what is causing the color axis to be translated too far down on the y axis. As I mentioned, I can say with confidence that my code, unchanged, continues to work on `5.0.2` but breaks with the axis change on `5.0.3`, and that commenting out the `delete` line causes the code to work as normal.

**Comment by swidge** [comment]
So I was able to recreate the issue that @radiolips was running into with `colorAxis[0].update`.

The issue only seems to crop up when you resize the chart after calling `colorAxis[0].update`. Here's a jsfiddle that demonstrates the issue: http://jsfiddle.net/6wap7x7h/4/. Once you run it, resize the demo window and you should see the following: https://www.dropbox.com/s/h6b7sswpx44fbdi/Screenshot%202017-01-06%2009.08.15.png?dl=0
In my example, instead of updating `stops`, I'm setting `reverse: true` which causes the same issue. Here's an example of the issue happening when updating `stops` instead: http://jsfiddle.net/9c4x1mk0/1/

It's also possible to recreate the issue using the jsfiddle that @oysteinmoseng provided if you resize the window after clicking the changeColorAxis button. Check out this version: http://jsfiddle.net/bnrfwhmm/. I removed the `max-height` attribute you had to make it more readily resizable if you're using a large monitor.

**Comment by radiolips** [comment]
@swidge thanks for that! @oysteinmoseng hopefully showing that the bug exists even in your jsfiddle is verification that this bug is real. Let me know if there's anything more I can offer.

**Comment by oysteinmoseng** [comment]
Excellent find! Minimal example using heatmap shows the same behavior: http://jsfiddle.net/ag00jg8o.

We'll take a look at it.

**Comment by oysteinmoseng** [comment]
Actually does not seem like this has ever worked properly.

**Comment by radiolips** [comment]
As I mentioned, this worked through `5.0.2` but does not work `5.0.3` and on.

**Comment by radiolips** [comment]
@oysteinmoseng Has there been any update on this? We are still locked to `5.0.2` until this has been resolved.

**Comment by TorsteinHonsi** [comment]
While waiting for v5.0.8, here's a drop-in fix that you can use on v5.0.7:

```js
	// Drop-in fix for #6025
	Highcharts.ColorAxis.prototype.keepProps.push('legendItemHeight', 'legendItemWidth');
```

[View it on jsFiddle](http://jsfiddle.net/highcharts/ag00jg8o/2/).

**Comment by radiolips** [comment]
Thank so much, @TorsteinHonsi . We'll test this today and verify the fix. Your fix follows what I had suspected as the cause, so I believe it'll work. Thanks again!

**Comment by radiolips** [comment]
@TorsteinHonsi Works great. Thanks so much!

**Comment by TorsteinHonsi** [comment]
You're welcome!
