### ISSUE TITLE
Bar threshold resets after chart reflow when stacking is enabled

### ISSUE THREAD

**Issue by stpoa** [highcharts/highcharts#6033]
#### Expected behaviour
After clicking reflow, resizing window or hiding and showing series chart should look the same as before (have the same bar threshold).

#### Actual behaviour
After clicking reflow, resizing window or hiding and showing series bar threshold equals 0.

#### Live demo with steps to reproduce
http://jsfiddle.net/5nc02mvd/

1. click reflow button.

**Comment by jon-a-nygaard** [comment]
Thanks for reporting!

**Comment by sebastianbochan** [comment]
_Internal note_
I think that it is more complex issue, related with area stacking which has influence on column.

I observed a few issues:
- problem is caused by the pick here: ```stack.points[pointKey] = stack.points[series.index] =
				[pick(stack.cum, stackThreshold)];```. When we switch order, then area chart is broken but column looks like fine. My idea is that we should add a condition which checks type of series and then run a correct stacking, but Im not sure if it is perfect. 
- http://jsfiddle.net/2a4ox4d5/ -> update series.color breaks stacking
- http://jsfiddle.net/2a4ox4d5/ -> threshold for area seems to working strange

What do you think @TorsteinHonsi ?
