### ISSUE TITLE
Tooltip giving wrong index of x point

### ISSUE THREAD

**Issue by srikodali-eruvaka** [highcharts/highcharts#6035]
Trying to show extra data on tooltip. Formed array and assigned to series variables.
Based on index of x point, want to show extra data. But x point index is giving -1. When we zoom data completely then it is giving correct index.

Want to get index of x point when not zoomed also and based on this want to show extra data in tooltip.

**Comment by srikodali-eruvaka** [comment]
Here x point is Datetime.

**Comment by jon-a-nygaard** [comment]
@srikodali-eruvaka Could you provide a replication if the issue, in for instance [JSFiddle](jsfiddle.net)?

**Comment by srikodali-eruvaka** [comment]
https://jsfiddle.net/sril/5peuh0c6/

**Comment by pawelfus** [comment]
It's caused by dataGrouping - when points are grouped, then `xData` doesn't relate 1:1 to the original dataset. For example points are grouped into 5sec groups, by grouping n-points. Additionally, x-values are not exactly the same as in the original dataset.

Demo with disabled dataGrouping: https://jsfiddle.net/5peuh0c6/1/

I don't recommend disabling dataGrouping because of the performance. Instead, I suggest to create your own approximation function, which groups your extra data too. See [docs](http://api.highcharts.com/highstock/plotOptions.series.dataGrouping.approximation) with demo.

**Comment by srikodali-eruvaka** [comment]
Hi,

I want to plot almost 3 lakhs points of data. So each time I want to load
50,000 and add to plot. For example,

1) For the first time will get 50,000 points from db and plot it
2) In second call get next 50,0000 points and want to add it to existing
graph and so on

I tried "setData" but it is overwriting the old data. I also tried
"addPoint", as there are many points it is getting slow.

Can you help me to find the correct solution.

**Comment by sebastianbochan** [comment]
@srikodali-eruvaka 
This is not related with the bug, so please use forum/stackoverflow or email for the [support](https://www.highcharts.com/support).
