### ISSUE TITLE
Point in Bubble Chart moving when hovered in some react environments

### ISSUE THREAD

**Issue by pierrecholhot** [highcharts/highcharts#6047]
Bubble Chart Point moves when hovering it in some react environments.

#### Expected behaviour
Point shouldn't translate on hover.

#### Actual behaviour
Point moves/jumps on hover, UI looks broken.

#### Live demo with steps to reproduce

The issue is visible on a pristine `create-react-app` repo. I created a sample project to illustrate the issue: https://github.com/pierrecholhot/highcharts-bubble-hover-issue-react

Note: I was unable to reproduce this bug in a fiddle (http://jsfiddle.net/v4veLo4o/1/) but it looks like it's still off by one pixel.

#### Affected browser(s)
Tested on: Chrome, FF, Safari

#### Screenshot
![Screenshot](https://raw.githubusercontent.com/pierrecholhot/highcharts-bubble-hover-issue-react/master/screenshot.png)

**Comment by pawelfus** [comment]
Hi @pierrecholhot 

I think the problem lies within package.json, here:

> "highcharts-more": "^0.1.2",

You load an old version of `highcharts-more`. `highcharts` package already contains `highcharts-more`, you simply need to include it. Note that `highcharts-more` package on the npm is not our product: https://www.npmjs.com/package/highcharts-more (vs https://www.npmjs.com/package/highcharts )

Could you check what version you have in `highcharts-more.js` file? It should be:

> @license Highcharts JS v5.0.4 (2016-11-22)

**Comment by pierrecholhot** [comment]
@pawelfus thanks for this prompt investigation and response! This was exactly it. 

Now using
```
require('highcharts/highcharts-more')(Highcharts)
```

instead of 
```
require('highcharts-more')(Highcharts)
```

Again, thanks!
