### ISSUE TITLE
Panning on touch screen broken?

### ISSUE THREAD

**Issue by drmrbrewer** [highcharts/highcharts#6052]
#### Expected behaviour

Panning left and right on a touch screen should work!

#### Actual behaviour

Panning left and right doesn't work.  Zooming in/out does.  Panning doesn't.

#### Live demo with steps to reproduce

Browse to these on your mobile device and try to pan left/right:

http://jsfiddle.net/vum1ufq3/1/embedded/result/  (panning works)
http://jsfiddle.net/vum1ufq3/2/embedded/result/  (panning doesn't work)

The former is based on the latest highcharts 5.0.0, the latter on 5.0.5.

Non embedded versions:

http://jsfiddle.net/vum1ufq3/1/  (panning works)
http://jsfiddle.net/vum1ufq3/2/  (panning doesn't work)

#### Affected browser(s)

At least Chrome (desktop and mobile)... quite likely all?

**Comment by drmrbrewer** [comment]
Update: I seem to have to go back to 5.0.2 to get it working again:

http://jsfiddle.net/vum1ufq3/5/embedded/result/
http://jsfiddle.net/vum1ufq3/5/

Whereas going one up to 5.0.3 breaks it:

http://jsfiddle.net/vum1ufq3/4/embedded/result/
http://jsfiddle.net/vum1ufq3/4/

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

We made a change in v5.0.3 to better separate zooming/panning from the `tooltip.followTouchMove` setting. The problem was that it was difficult to combine panning with followTouchMove, zoomType and pinchType. 

See http://api.highcharts.com/highcharts/chart.panning.

In short, you can disable `followTouchMove` to get the desired result: [View jsFiddle](http://jsfiddle.net/highcharts/vum1ufq3/6/).

**Comment by drmrbrewer** [comment]
Ah OK, thanks.  Therefore, it's not so much a bug but a change in default behaviour.  I'll set `followTouchMove` accordingly.
