### ISSUE TITLE
jQuery on click event does not work with Dynamic Tooltip HTML starting Highcharts 5.x

### ISSUE THREAD

**Issue by niranjanshukla** [highcharts/highcharts#6053]
#### Expected behaviour
In this Fiddle -- http://jsfiddle.net/8VTTH/57/ -- once you click a series point, you see the Tooltip with a dynamic link. Upon clicking the link, we should see an alert "clicked"

#### Actual behaviour
The above Fiddle stops giving Expected behavior once we update the Highcharts library version to 4.2.7 or above. The link when clicked does not show the alert

#### Live demo with steps to reproduce

http://jsfiddle.net/8VTTH/57/
1. Click on an series point
2. Click on the "comment" link which shows in the Tooltip
3. Change highcharts library version to 4.2.7 or above. Retest.

#### Affected browser(s)
1. Chrome
2. Safari

**Comment by pawelfus** [comment]
Hi @niranjanshukla 

Thank you for reporting the issue. It's caused by [`tooltip.style.pointerEvents`](http://api.highcharts.com/highcharts/tooltip.style), which by default is set to `'none'`. Changing this to `all` resolves the issue: http://jsfiddle.net/8VTTH/59/

Note: this is a fix for #1686 issue, so you may see issues with pie chart & tooltip as described in the ticket.
