### ISSUE TITLE
The cell border of heatmap is not a rectangle

### ISSUE THREAD

**Issue by hotohoto** [highcharts/highcharts#6064]
#### Expected behaviour
The cell border is supposed to be a rectangle.

#### Actual behaviour
Only bottom and top sides of the border are visible.

#### Live demo with steps to reproduce
http://jsfiddle.net/hotohoto/4uwu6nm1/1/

#### Affected browser(s)
I've tested it with Chrome.

**Comment by jon-a-nygaard** [comment]
Internal Note: Treemap had the same dilemma, which was solved by setting a higher zIndex when state is hover in [Point.setState](https://github.com/highcharts/highcharts/blob/master/js/modules/treemap.src.js#L903-L908)

**Comment by jon-a-nygaard** [comment]
Hi @hotohoto Here's a [workaround](http://jsfiddle.net/jon_a_nygaard/4uwu6nm1/2/)  that you can try out, let me know if this is an acceptable solution for you.

**Comment by hotohoto** [comment]
That is a great solution!
Thanks

**Comment by jon-a-nygaard** [comment]
You're welcome!

I added a change which will fix the issue with border color on points in hover state. But I will close this issue as a won't fix, because we do not see a proper way to accomodate borders on points in a normal state.
For instance, shrinking the size of the points to make room for the border size is an option we consider to be invalid, because the points would get incorrect dimensions.

Should anyone have further information on this issue, feel free to comment.
