### ISSUE TITLE
Highstock stacked area

### ISSUE THREAD

**Issue by pliasetski** [highcharts/highcharts#6106]
Hello,
Highstock stacked area chart works wrong if some series have negative values.

#### Actual behaviour
Only one series is displayed

#### Live demo with steps to reproduce
http://jsfiddle.net/d54zdmr4/2/

#### Affected browser(s)
Latest chrome version

**Comment by pawelfus** [comment]
Thanks for reporting!
Do you mean, that Highstock should render stacked areas in a different way than Highcharts? Compare: http://jsfiddle.net/d54zdmr4/3/

**Comment by pliasetski** [comment]
Hi @pawelfus,
Sorry, I didn't notice that Highcharts works in the same way. I mean that data for first series is reflected on "0" yAxis label, but it has values more than zero. Is it corrent behaviour?

**Comment by pawelfus** [comment]
Yes, that's how it works. Stacking for areas is calculated basing on the value from the previous series'. When values reduce to 0, then the point will be rendered on 0. The same happens when you have all positive values: http://jsfiddle.net/d54zdmr4/6/ - values are summed and even if value for the top series is Y, it is rendered on Y + all previous values.
