### ISSUE TITLE
Offline PDF export with many points not working

### ISSUE THREAD

**Issue by inad9300** [highcharts/highcharts#6108]
#### Expected behaviour
The PDF is downloaded when clicking the corresponding button.

#### Actual behaviour
The download prompt appears so that you are able to select the location of the file, but a message "download / Failed - Network error" is displayed after the download supposedly finishes.

#### Live demo with steps to reproduce
http://jsfiddle.net/inad9300/869ftho6/
To reproduce, click the "Export to PDF" button.

#### Affected browser(s)
Chrome 54.0.

I tested also the same on Firefox, and it is able to handle the download.

**Comment by inad9300** [comment]
I include a screenshot to better illustrate the error.

![download-error](https://cloud.githubusercontent.com/assets/3440331/21005744/5259fe60-bd36-11e6-8b6c-61c137a379a6.PNG)

**Comment by oysteinmoseng** [comment]
This turned out to be an issue with data URL lengths in Chrome, limited to ca 2MB. Changed the code to use Blob API if available for large files, will otherwise try to fall back to export server if enabled.

This issue will show up in PDF before the others because of the large size that comes with the format.

**Comment by inad9300** [comment]
Is there any plan to release this fix? I can see that with 5.0.6 the JSFiddle above is still failing (I don't remember the version I first used when created it).

**Comment by oysteinmoseng** [comment]
Version `5.0.7` - which includes this fix - is due this week actually, possibly today.

**Comment by inad9300** [comment]
Awesome! Waiting for it :)

**Comment by rodrigo-sntg** [comment]
I had the same problem with SVG download.
The problem was on the file "highcharts-export-clientside.js" on the download function.
They were creating the uri with the data content and putting it on a.href.
On google chrome, the maximum size to a uri is 2mb. 
So to solve the problem while it's not solved in highcharts, I have changed the code as bellow:
```
var b = new Blob([data.content], {
          type: 'text/svg'
      });
var obj = URL.createObjectURL(b);
a.href = obj;
//a.href = data.datauri || ('data:' + context.type + ';base64,' + window.btoa(unescape(encodeURIComponent(data.content))));
```
This works just fine.

**Comment by oysteinmoseng** [comment]
@rodrigo-sntg Are you still experiencing this issue with the latest version of Highcharts?
