### ISSUE TITLE
Column charts leaving 1px gaps between bars

### ISSUE THREAD

**Issue by dinubs** [highcharts/highcharts#6132]
#### Expected behaviour
Expect bars to have no gap between columns at all container sizes when the options below are set

```
pointPadding: 0,
groupPadding: 0,
borderWidth: 0
```

#### Actual behaviour
At certain container sizes there are 1px gaps between columns 

#### Live demo with steps to reproduce
http://jsfiddle.net/srq8zya6/

You'll see an empty gap between the columns at Jun and Jul respectively.

**Comment by pawelfus** [comment]
Thanks for reporting!

*Internal note:*
I see this issue only on an external monitor, results:
- build-in screen:
![screen shot 2016-12-13 at 11 55 39](https://cloud.githubusercontent.com/assets/1453926/21137720/19bc889a-c12b-11e6-93e5-400c182a40d7.png)
- external monitor:
![screen shot 2016-12-13 at 11 56 31](https://cloud.githubusercontent.com/assets/1453926/21137740/378274de-c12b-11e6-8525-80b44e303d40.png)

**Comment by gavindinubilo** [comment]
@pawelfus Would also like to note the in Chrome I see the issue in both the built in monitor (Macbook Pro retina) and on an external monitor.

![image](https://cloud.githubusercontent.com/assets/2745145/21156886/44c7785a-c12c-11e6-8190-735800985aaf.png)

when I manually resize my browser screen (testing in FF), I can make the possible rounding issue appear in differing columns.

I figure this has to do with distributing extra pixels throughout the chart instead of at the beginning or end paddings, _or_ possibly rounding issues. Ex: column-width: 10px, chart-width: 32px, would be nice to put the extra pixels on the end instead of in the middle.

**Comment by oysteinmoseng** [comment]
Seems to be fixed in master: http://jsfiddle.net/srq8zya6/1/

**Comment by oysteinmoseng** [comment]
Or not, according to @pawelfus..

**Comment by dandv** [comment]
I no longer see this issue on an external monitor in Chrome 69 on Linux.

**Comment by pawelfus** [comment]
Not anymore, tested all external monitors I have :) Closing the issue then.
