### ISSUE TITLE
In a chart with more than one Y-Axis, one of them disappears if the chart is wide enough

### ISSUE THREAD

**Issue by dgucwa** [highcharts/highcharts#6151]
#### Expected behaviour
On a chart with more than one y-axis, I expect to see both.

#### Actual behaviour
When the width of a chart is high enough, one of the axes disappears.

#### Live demo with steps to reproduce
http://jsfiddle.net/fhoxtnej/
1. Run the jsfiddle.
2. Scroll to the bottom of the javascript portion and uncomment the line that sets width to a lower value. Re-run the jsfiddle.

#### Affected browser(s)
Observed in Chrome and Firefox

**Comment by pawelfus** [comment]
Thank you for reporting the issue!

In case you want just a duplicated yAxis, you can use `linkedTo` - it seems to be working fine: http://jsfiddle.net/fhoxtnej/1/

**Comment by pawelfus** [comment]
*Internal note:*
With chart width 500, `redoHorizontal` is set to false: `redoHorizontal = tempWidth / chart.plotWidth > 1.1;` As an easy fix, we can change 1.1 to 1.05 - to be the same ratio as for height. That explains why width is important in this case.

However, the problem is also somewhere else: during the first rendering, `Axis.alignToOthers` returns undefined, because of the fix for #4442. So yes, this is kind of a regression.

**Comment by dgucwa** [comment]
Thanks, but unfortunately I have two different axes so `linkedTo` won't solve my issue, that example was just for demonstration.
