### ISSUE TITLE
Pie series addPoint without redraw appends points array

### ISSUE THREAD

**Issue by aaronrosenthal** [highcharts/highcharts#6177]
#### Expected behaviour

Calling addPoint should not append the points array for any series type when the redraw argument is set to false.

#### Actual behaviour

Pie series appends the added point to the points array before a call to redraw the chart is made.

#### Live demo with steps to reproduce
[http://jsfiddle.net/nLk1h3ca/1/](http://jsfiddle.net/nLk1h3ca/1/)

1. Click "Add point to pie". Message will read "0 before add, 1 after add".
2. Click "Add point to line". Message will always read "0 before add, 0 after add".

#### Affected browser(s)

All.

**Comment by pawelfus** [comment]
Hi @aaronrosenthal 

Thank you for reporting this issue! Pie chart points are rendered in legend and we need this for precalculation. I agree that it should be consistent between series or at least explained in the docs.

Related to #1329

**Comment by TorsteinHonsi** [comment]
I'm not sure. The `redraw` parameter only dictates whether the graphic representation of the chart should update, it doesn't say anything about the internal state.

**Comment by aaronrosenthal** [comment]
I can understand that. In that case, it would be nice if addPoint returned an object reference to the new point. That way I can update the point at a later time. Otherwise, I have to save the index number of the point and look into the points array using it. The inconsistency between pie and other series types makes this not straightforward.

**Comment by TorsteinHonsi** [comment]
Unfortunately the Point instance is not generated in the `addPoint` function, so we're not able to return it directly. Instead, the point options are registered to the `options.data` array, and the `Point` is generated in the `generatePoints` function. This is because the `Point` instances not always relate one to one to point options. The actual points may be cropped, or in Highstock data grouping may be applied before generating Points.
