### ISSUE TITLE
Highstock: navigator jumps back on drag to right edge

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#6187]
#### Expected behaviour
Navigator should move to the touched place.

#### Actual behaviour
It jumps back after a touch event ends.

#### Live demo with steps to reproduce
http://www.highcharts.com/stock/demo/candlestick-and-volume
1. Open on iPhone
2. Drag navigator (mask) to the center.
3. Drag navigator (mask) to right side of the navigator.
4. Navigator jumps back to the center position after the drag ends.

![img_4303 1](https://cloud.githubusercontent.com/assets/8960408/21545158/92280384-cdd5-11e6-8b30-017546398a7c.gif)

#### Affected browser(s)
Mobile: iPhone 7

**Comment by KacperMadej** [comment]
Another example:

![ezgif com-58fc0optym](https://cloud.githubusercontent.com/assets/8960408/21546144/16920ece-cddd-11e6-8b9b-04817470d05d.gif)

**Comment by sebastianbochan** [comment]
+1

**Comment by eldjuve** [comment]
This fix simply disregards mouseevents, meaning the navigator will not respond to mouse interaction on a computer with a touch screen. Could it not be fixed by simply preventing default on touchevents instead? Ref: https://developer.mozilla.org/en-US/docs/Web/API/Touch_events/Supporting_both_TouchEvent_and_MouseEvent

**Comment by TorsteinHonsi** [comment]
Reopened based on the comment above. Also I suspect that this caused #6457, that we haven't been able to reproduce, but comes with the same symptoms.
