### ISSUE TITLE
Navigator doesn't answer as expected when moved faster.

### ISSUE THREAD

**Issue by sergiomcunha** [highcharts/highcharts#6191]
#### Expected behaviour
When rendering a chart with the same chart at the navigator, if the navigator selection is moved fast and hover the minimum selection, it's expected that it will filter at the minimum selection value.

#### Actual behaviour
If the selection from navigator were moved fast, then the navigator will freeze in some cases and don't apply the proper selection. 
Also if there are more series in a chart, then the response is even slower.
(there are some movies to see the issue)
[example movies.zip](https://github.com/highcharts/highcharts/files/678552/movies.zip)

#### Live demo with steps to reproduce
- Slide the filter faster to the minimum points.
- See that the navigator doesn't apply the filter properly.
- Go back to the minimum selection (the 6 points per chart).
http://jsfiddle.net/yczmchey/

**Comment by pawelfus** [comment]
Thanks for the report!

*Internal note:*
It's probably caused by [this `if`](https://github.com/highcharts/highcharts/blob/a888515a0116eb15248f33f49f5901674010da50/js/parts/Scroller.js#L283). However, we should fixed this before so we will render minimum range, instead of not updating navigator at all.
