### ISSUE TITLE
Same font style is rendered differently in X-axis and Y-axis titles

### ISSUE THREAD

**Issue by sagargurtu** [highcharts/highcharts#6195]
#### Expected behaviour
When the same font style is applied to X Axis and Y Axis titles, the titles should be displayed with similar style.

#### Actual behaviour
As shown in the fiddle below, after applying the same font style, there is a difference in rendering style between the axis titles.

#### Live demo with steps to reproduce
http://jsfiddle.net/cwum3n80/

#### Affected browser(s)
Chrome

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

First, based on your jsFiddle, I assume you are refering to the axis _titles_, not the axis _labels_ in Highcharts terminology.

Second, I can't see any difference in how the two titles are rendered. I added `rotation:0` for clarity.  See http://jsfiddle.net/cwum3n80/1/ and the screenshot: 

![skjermbilde 2017-01-03 kl 15 01 17](https://cloud.githubusercontent.com/assets/227836/21609956/859d0ef4-d1c5-11e6-9e1c-0f75a0a4e562.png)

**Comment by sagargurtu** [comment]
Yeah I was referring to axis titles. On adding rotation:0, the titles do not have any difference. But if the y-axis title is oriented vertically, the font appears somewhat different. 

![capture](https://cloud.githubusercontent.com/assets/18263719/21611686/e04f6512-d1f3-11e6-8bae-289412249636.JPG)

![untitled](https://cloud.githubusercontent.com/assets/18263719/21611694/e9a02c3c-d1f3-11e6-8f9c-677ede05cd7c.png)

**Comment by TorsteinHonsi** [comment]
Below is an image where I took a screenshot of the two titles, then used Photoshop to rotate the Y axis title back to 0 rotation in order to compare to the X axis title. If you scale this up to 200% zoom you'll see that the antialiasing is slightly different, for example the 90 degree text has some grey pixels below the baseline. This is because of the font antialiasing rules in the browser.

![skjermbilde 2017-01-04 kl 09 19 06](https://cloud.githubusercontent.com/assets/227836/21635787/dc943968-d25f-11e6-8aad-c6dab5bf5706.png)
