### ISSUE TITLE
getContrast Function is broken

### ISSUE THREAD

**Issue by franktudor** [highcharts/highcharts#6216]
**Expected behaviour:**

When using style: {color:'contrast'} on datalabels we get white labels on lighter colors.

The function looks like this in Highcharts 5 (and Highstocks too)

`getContrast:function(a){a=q(a).rgba;return 510<a[0]+a[1]+a[2]?"#000000":"#FFFFFF"}`

**Looking at some of our older repos we found a prior function and replaced in our current Highcharts 5 dependancies and our labels worked:**

`getContrast:function(a){a=q(a).rgba;return a[0]+a[1]+a[2]>384?"#000000":"#FFFFFF"}`

**Live demo with steps to reproduce:**

http://stackoverflow.com/questions/40921776/color-contrast-setting-on-datalabels-style-parameter-using-highcharts-5-is-not-w

Even with the override provided by [Barbara Laird](http://stackoverflow.com/users/2588368/barbara-laird) depending on if we added custom colors at series level or where we placed the datalabel style handling it would ignore the override function and revert to the global function. So we changed the global function and our labels look much better.

**Comment by TorsteinHonsi** [comment]
Thanks for writing! Here's a little summary on what happened in HC5:

### Background
In HC4, the data labels would have a default `textShadow` that contrasted to the data label color, which in turn contrasted to the column itself. This `textShadow` was unreliable between browsers, and the shim that we used worked poorly with exported charts and zoomed page content. Also, a fuzzy color worked very badly with greyish labels. So we rewrote it to use a pseudo `textOutline` property, that by default draws a 1px contrasted outline around the text. At the same time, we moved the threshold for when to go to black and when to go to white, based on real world observations. On our [visual test](http://jsfiddle.net/highcharts/43soe9m1/) you'll see how it works with different backgrounds. There are some scenarios around the gray area that don't work optimally no matter where we set the threshold.

### Issue
So, to your actual case. 
I agree that the March and April columns are bright, and that the text in this case should be black:
![kok9g](https://cloud.githubusercontent.com/assets/227836/21761542/fd2cd458-d653-11e6-83bd-f3cbab797745.png)

So here's what happens when I set the threshold back to what it was in Highcharts 4. The March and April columns look good, but now the January and May column have poor contrast:
![skjermbilde 2017-01-09 kl 10 13 27](https://cloud.githubusercontent.com/assets/227836/21761610/6cbd5748-d654-11e6-9bc4-ffb7851723c7.png)

... but only until we leave Highcharts' [default textOutline property](http://jsfiddle.net/highcharts/98Ldn972/5/), then all labels are clearly readable: 
![skjermbilde 2017-01-09 kl 10 15 02](https://cloud.githubusercontent.com/assets/227836/21761649/a0a09e6c-d654-11e6-81e5-8ed899cefd95.png)

### Conclusion
We recommend leaving the default `textOutline`. There doesn't seem to be a simple black/white threshold that creates optimal readability for all of the default Highcharts colors. If we set it to 500 like proposed on SO, the January text is still poorly readable. It looks like blue backgrounds and black text is a bad combination, so perhaps we need to split color channels to get the optimal contrast. For example, [this dynamic weighting](http://jsfiddle.net/highcharts/98Ldn972/6/) seems to work well with all the default colors, possibly except April.

**Comment by franktudor** [comment]
Torstein, I appreciate the consideration on this. For my clients, the `textOutline` is a bit terse on designer (there are times it makes sense). We are bigger fans of that as an option not a default.

If you are still undecided, maybe consider going back to the old function as a interim (and simple) blanket solution because when I reverted to the Highcharts 4 `getContrast()` function it felt right to my eyes. I was sold that it was a better solution (but maybe not the best as you layout in your dynamic weighting approach...maybe some time the default orange you have could be lighter (or darker) depending if you ever go with a weighted approach...just thinking the solution could go both ways).

Its your call though, I was just happy on discovering something that made my clients happy.

Maybe also you could update the SO post I linked with your override solution. Others might find it useful.

Thanks,
Frank

**Comment by TorsteinHonsi** [comment]
For the records, turning the text outline off by default is not a good solution, as we need to make sure the text is readable regardless of background. A little tinkering with the configuration shows that we [don't always have control over the label background](http://jsfiddle.net/highcharts/98Ldn972/7/).

**Comment by franktudor** [comment]
Sure thing.  Thanks for considering.  I agree once you take a closer look it is not so straight forward, and even subjective because everyone has different color tuning on their monitors and if I use a projector to discuss things with others, its always a disaster on colors, font sizes, etc.  With the text outline in datalabels. The concern is handled. You can close this issue.
