### ISSUE TITLE
maxPadding has no effect with plotLine in place

### ISSUE THREAD

**Issue by drmrbrewer** [highcharts/highcharts#6243]
#### Expected behaviour

`maxPadding` should work as expected even with a `plotLine` in place

#### Actual behaviour

It doesn't!

#### Live demo with steps to reproduce

http://jsfiddle.net/som4yu4p/

See the comments in the fiddle code, reading from the top down, which explain what the issue is.

#### Affected browser(s)

Any, I assume.

**Comment by oysteinmoseng** [comment]
Thank you for reporting this.

**Comment by pawelfus** [comment]
I don't think this is a bug. This is the expected behaviour with [`series.softThreshold`](http://api.highcharts.com/highstock/plotOptions.series.softThreshold) set to true: not even one point crosses the `y=0` value, so chart will not render a plane without existing points.

When setting `softThreshold` to false it will apply `maxPadding`. Demo: http://jsfiddle.net/som4yu4p/1/

**Comment by drmrbrewer** [comment]
Hmm OK but I already have

**Comment by drmrbrewer** [comment]
OK @pawelfus but I already have `softThreshold` set to `false` everywhere (in my code).  Another relevant thing from my code which didn't make it's way into the jsfiddle demo was `threshold`...

So, now let's add a `threshold` of 0 (same place as default, just explicit now) to your fixed version, and it breaks again:

http://jsfiddle.net/som4yu4p/2/

**Comment by pawelfus** [comment]
It's interesting. I thought that `threshold` is set to `null` by default, not to 0 (I think it may be a bug in docs for line-type series, for [area type](http://api.highcharts.com/highstock/plotOptions.area.threshold) it is correct: `If null, the area behaves like a line series (...)` - it indicates that `null` is set for ` line` series), let's compare results:
- http://jsfiddle.net/som4yu4p/3/
- http://jsfiddle.net/som4yu4p/4/

It is exactly caused by `threshold` as you can see in the demos above. @TorsteinHonsi - what do you think?

**Comment by TorsteinHonsi** [comment]
I think the docs are correct actually - for a line series it doesn't have an effect on the axis extremes when we set it to 0. The docs say it only applies to the `negativeColor` option: http://jsfiddle.net/highcharts/uj5pnojg/.

**Comment by drmrbrewer** [comment]
@TorsteinHonsi but you agree that the current behaviour is not correct?

Compare this (all data happens to be below the `threshold`):

http://jsfiddle.net/som4yu4p/7/

With this (one data point sneaks above the `threshold`... but *nothing* else changes in the chart configuration):

http://jsfiddle.net/som4yu4p/8/

I want to be able to set a padding that has a consistent effect on the position of the line, regardless of where the threshold is (and in my case the threshold is the freezing point temperature, which needs to be set explicitly to a value which depends on the unit).

**Comment by TorsteinHonsi** [comment]
As far as I can see it behaves correctly...

With `threshold: 0` is should behave like an area series, which is to stick to one side of the threshold if all the data is on one side: http://jsfiddle.net/som4yu4p/7/

Now with `threshold: null` it completely disregards the zero level, which becomes just another value.

**Comment by drmrbrewer** [comment]
@TorsteinHonsi but surely setting `softThreshold: false` (as it is in the fiddle you linked) should allow the padding to take effect, regardless of the `threshold`?  I thought that was the point of [`softThreshold`](http://api.highcharts.com/highstock/plotOptions.series.softThreshold)?

> When this is true, the series will not cause the Y axis to cross the zero plane (or threshold option) unless the data actually crosses the plane.
>
> For example, if softThreshold is false, a series of 0, 1, 2, 3 will make the Y axis show negative values according to the minPadding option. If softThreshold is true, the Y axis starts at 0.
>
> Defaults to true.

**Comment by drmrbrewer** [comment]
@TorsteinHonsi so is this recognised as a bug or not?  For me, it's pretty debilitating, and I'm having to define my own custom tickPositioner just to achieve what I think should be pretty common behaviour, i.e. predictable and sensible padding for the line even when a threshold has been set.

**Comment by drmrbrewer** [comment]
@TorsteinHonsi any news on this one?

**Comment by drmrbrewer** [comment]
@TorsteinHonsi what is your view on this?  It's been labelled as "Bug" but you seem to think not?
