### ISSUE TITLE
Bubbles are now showing in v5.0.7 if plotOptions.series.marker.enabled set to false

### ISSUE THREAD

**Issue by mengyaow** [highcharts/highcharts#6264]
issue with latest release v5.0.7
Bubble chart is not drawing any bubbles.

my bubble charts are working fine with v5.0.6, but failed with v5.0.7
These 2 JSfiddle have exactly the same js code, only difference is the highchart version being using.
v5.0.6===> everything works fine:
http://jsfiddle.net/519vfcdr/4/
v5.0.7===> bubbles are not drawing:
http://jsfiddle.net/519vfcdr/5/

I try to debug , if I change  plotOptions.series.marker.enabled from false to true, then it can draw.
It's an inconsistant behavior in v5.0.7 vs v5.0.6

Affected in Chrome and Firefox

**Comment by TorsteinHonsi** [comment]
Thanks for reporting, it is a bug. We refactored bubbles in v5.0.7 in order to use the marker logic from scatter series. This allowed using [image symbol markers](http://jsfiddle.net/gh/get/jquery/3.1.1/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/bubble-symbol/) that was not possible before. 

_Reduced demo_: http://jsfiddle.net/highcharts/519vfcdr/6/ . The second bubble should be visible. With [scatter series](http://jsfiddle.net/highcharts/519vfcdr/7/) it works like expected.

**Comment by mengyaow** [comment]
I'm using v5.0.6 so the bubble is not a blocking issue, 
Thanks for the quick fix !!!!!
