### ISSUE TITLE
Chart.update() does not update parameters of data module

### ISSUE THREAD

**Issue by PaulDalek** [highcharts/highcharts#6268]
#### Behaviour
It seems that chart.update() does not update parameters of data module (for example googleSpreadsheetKey).

#### Live demo
https://jsfiddle.net/d_paul/m863jeyf/

**Comment by stpoa** [comment]
### Another example

#### Expected behaviour
When using data module with for example csv, after starting Chart.update with new data, data should get updated on the chart.

#### Actual behaviour
When using data module with for example csv, after starting Chart.update with new data, data does not get updated on the chart. (This behaviour does not seem to be noted in documentation)

#### Live demo with steps to reproduce
https://jsfiddle.net/617jfhrd/

1. Open example
2. Wait 2 seconds for data update
3. Notice no change in data on the chart

**Comment by laurencedorman** [comment]
I too have come across this problem. It would be good to have some feedback from Highsoft about this.

**Comment by TorsteinHonsi** [comment]
Thanks for your patience! Here's the demo with the fix applied: https://jsfiddle.net/highcharts/617jfhrd/1/

**Comment by laurencedorman** [comment]
Great, when can we expect this available on the CDNs and npm ?

**Comment by pawelfus** [comment]
New version should be released within a few weeks.
