### ISSUE TITLE
Timezone offset - missing ticks in DST

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#6278]
#### Expected behaviour
All ticks shoud be visible

#### Actual behaviour
The issue is when we have data which begins at non-equal hours. Ticks are missing.

#### Live demo with steps to reproduce
Demo:
 - http://jsfiddle.net/dLfL6ve5/ (missing ticks)
 - http://jsfiddle.net/ssxssdLz/ (equal hour)

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
I was able to fix it by substracting the timezone offset instead of adding it on [this line](https://github.com/highcharts/highcharts/blob/v5.0.7/js/parts/DateTimeAxis.js#L38).

`minDate = new Date(min + getTZOffset(min)),`
becomes:
`minDate = new Date(min - getTZOffset(min)),`

Which feels correct because it gives the correct minDate in this case. However, it breaks the test for `unit-tests/axis/datetime-ticks`, which I don't understand... Will continue to investigate.

**Comment by mcapewell** [comment]
Is there any update to this issue? We would like to fix this for our customers in an upcoming release of our software.
