### ISSUE TITLE
Multiple responsive rules apply almost randomly when in ascending order

### ISSUE THREAD

**Issue by stpoa** [highcharts/highcharts#6291]
#### Expected behaviour
After resizing charts container responsive rules should apply without problems.

#### Actual behaviour
After resizing charts container there are many problems with responsive rules. Sometime we see that no rule applies at all, sometimes we see that wrong rule is applied.

#### Live demo with steps to reproduce
https://jsfiddle.net/g0ryva91/

0. Look at responsive rules
1. Click `100px`, `200px`, `300px`, `400px`
2. Notice Chart.title change

**Comment by TorsteinHonsi** [comment]
It seems like rule matches from the last run survives and interferes with the rule order. If we click one button at the time, with reloading in between each, it is correct.

**Comment by TorsteinHonsi** [comment]
The problem lies in the `matchResponsiveRule` function. The rules are evaluated from top to bottom. Each rule either matches or not. If the rule matches, the chart is updated with its options, and the existing options are stored. If the rule fails but was applied earlier, the chart is updated with the stored options from the previous step.

And that's where it fails. Click `100px`, `300px` and `500px` in succession. When we click first 100px, the last rule that applies is the 400px rule, but at this point the title is 300px that was set by the previous rule, so this is the restore-option that is saved for 400px. So when we click 500px, the 400px rule no longer applies, and it sets the title back to 300px.

**Comment by mynameiswhat1** [comment]
Hello,
I've noticed some more erratic behaviour that maybe is related with this bug as described here:

http://forum.highcharts.com/highstock-usage/responsive-rules-working-very-strangelly-t37604/

Thank you very much.

**Comment by mynameiswhat1** [comment]
Hello again,
Is this also related: http://forum.highcharts.com/post131726.html#p131726 ?
Thank you very much.

**Comment by mynameiswhat1** [comment]
Hello,
Any news on this subject?
Thank you very much.

**Comment by TorsteinHonsi** [comment]
Will continue to work on it now.

**Comment by mynameiswhat1** [comment]
Thank you TorsteinHonsi.
Will this change also take effect on Highstock? 
Thank you very much.

**Comment by TorsteinHonsi** [comment]
You're welcome. Yes, Highstock uses the same code.
