### ISSUE TITLE
afterSetExtremes event is called two times

### ISSUE THREAD

**Issue by hopest** [highcharts/highcharts#6334]
#### Expected behaviour
A simple example of a standard demo
Highstock Demos › 1.7 million points with async loading
http://jsfiddle.net/gh/get/jquery/3.1.1/highslide-software/highcharts.com/tree/master/samples/stock/demo/lazy-loading/

#### Actual behaviour
When using the Navigator, if you put a small range, see afterSetExtremes event is called two times

#### Live demo with steps to reproduce

add console log
http://jsfiddle.net/hopest/xgg8n95j
view visual video https://youtu.be/f9vHzmFyXXc

**Comment by pawelfus** [comment]
Thank you for reporting. It works fine in 5.0.6 version.

*Internal note:*
Issue-by-commit leads to this: https://github.com/highcharts/highcharts/commit/3466009 But there is a high chance bug is located somewhere else.

**Comment by pawelfus** [comment]
Hi @hopest ,

Are you still able to recreate the issue? Now it works fine for me.

**Comment by pawelfus** [comment]
*Internal note:*
Event is actually called twice always, but with wider ranges extremes are exactly the same. We can observe the issue with smaller ranges because of floating point precision. Using `correctFloat()` won't resolve the issue because we have a huge range and we zoom into the very small portion of the chart. It's fixed in the navigator event as it makes more sense: don't proceed with mouseup event twice if don't need that.
