### ISSUE TITLE
Creating own Map type

### ISSUE THREAD

**Issue by bkozera** [highcharts/highcharts#6344]
This is not really a bug but more of a question and maybe a request to update docs. I would like to extend Map chart so I can use custom hover and select colors for each country. I can do it like so:

```
const originGetAttribs = Highcharts.seriesTypes.map.prototype.getAttribs;

Highcharts.seriesTypes.map = Highcharts.extendClass(Highcharts.seriesTypes.map, {
  getAttribs() {
    const result = originGetAttribs.call(this);

    /* eslint-disable no-param-reassign */
    this.points.forEach((point) => {
      if (point.hoverColor) {
        point.pointAttr.hover.fill = point.hoverColor;
      }
      if (point.selectColor) {
        point.pointAttr.select.fill = point.selectColor;
      }
    });
    /* eslint-enable no-param-reassign */

    return result;
  }
});
```

and then pass additional hover and select color in map data. 
However this feels wrong because I am changing the original Map chart type. 

How would I  go about creating my own map chart with this functionality?
I understand I need to add `myMap` to `Highcharts.seriesType` perhaps like so:

`Highcharts.seriesTypes.myMap = Highcharts.extendClass(Highcharts.seriesTypes.map, ...`

but I probably also need to create new constructor, something like `Highcharts.MyMap` based on `Highcharts.Map`, right?

Any help would be appreciated.

**Comment by TorsteinHonsi** [comment]
Hi, there are (at least) two ways to do this.

1. Create your own series type. See the [seriesType factory function](https://github.com/highcharts/highcharts/blob/v5.0.7/js/parts/Utilities.js#L1836-L1853). This function is new in Highcharts 5, and we will write a documentation article about it, but haven't come around to it yet.

2. Extend an existing series type, which is probably more relevant in your case, since you're just doing a simple modification. See [Extending Highcharts](http://www.highcharts.com/docs/extending-highcharts/extending-highcharts). In your case, it would be something like this:

```Highcharts.wrap(Highcharts.seriesTypes.map.prototype, 'getAttribs', function (proceed) {
    const result = proceed.call(this);
   
   // Do your stuff

    return result;
});
```

But please note that the `getAtttribs` function is no longer present in HC5, and replaced by the much simpler `pointAttribs` function that returns presentational attributes for an individual point.

Also, for the next time, keep in mind that you've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.

**Comment by bkozera** [comment]
Sorry for not using the support forum, didn't know about it.
Thanks a lot for your help, especially about HC5 differences, it will come in handy when we upgrade!
