### ISSUE TITLE
Support for custom log conversion functions that handle negative numbers

### ISSUE THREAD

**Issue by sfishel18** [highcharts/highcharts#6348]
I'm trying to create a visualization that has a logarithmic y-axis but can display both positive and negative y-axis values.  I have an implementation of the necessary conversion functions (log to linear, linear to log), and my initial approach was to replace the `Axis.prototype.lin2log` and `Axis.prototype.log2lin` respectively with my functions.  However, I'm running into issues where the negative values are not plotted.  Inspecting the code, there doesn't seem to be a clean way to handle those issues with a plugin.

What I'd like is to be able to pass in my own custom conversion functions with my axis options, and perhaps a flag that indicates that my logarithmic y-axis supports negative numbers.  Would you be open to a pull request along those lines?

Highcharts is great, keep up the good work!

**Comment by TorsteinHonsi** [comment]
Thanks!

We have had pull requests for negative log axes before, but so far they haven't been accepted because the haven't resolved the basic logic problem of crossing the zero plane when a log axis by definition never reaches zero. 

However, this is a frequently asked question, so a solution like you propose would be helpful for those who want their own way of handling this. We are open for suggestions. Maybe we can just make the error messages optional, then allow custom conversion functions.

**Comment by TorsteinHonsi** [comment]
Thanks for the PR!

The final implementation can be seen at http://jsfiddle.net/highcharts/1z001nhy/. I removed the switches from the options structure, and instead showed how the prototype itself can be overridden with custom functions. This made it a little bit more light-weight. Custom conversion functions could be provided as callbacks in the options structure at some point, but I feel that in that case they could be more general, not only applied to log axes.

**Comment by sfishel18** [comment]
That makes sense, thanks much!

**Comment by TJLanger** [comment]
I'm trying to do something similar to sfishel18, and I noticed an interesting behavior with the "allowNegativeLog" prototype. When you do not override the log2lin/lin2log prototypes, but set allowNegativeLog to true, values between 0 and 1 are not plotted. 

Example: https://jsfiddle.net/TLanger/n43u8qLv/2/

Can you please help me understand if I'm making a mistake somewhere? My goal is to use the custom log/linear conversions only when there are negative/zero values, and to use the default conversion otherwise, for better display in the >0 to +10 range. Thank you!

**Comment by sebastianbochan** [comment]
Hi @TJLanger,
The simplest way is extracting data to external array and then check the min value. If its <= 0 then apply `allowNegativeLog`.

Example:
- https://jsfiddle.net/BlackLabel/9vcugqo4/

**Comment by TJLanger** [comment]
@sebastianbochan , Thanks so much for the quick response! That's definitely a good workaround. I've been trying to incorporate that kind of check across all my charts, using the prototype wraps for onload and redraw, with only partial success. I don't have a good demonstration fiddle currently, but I'm getting undefined chart.yAxis[i].dataMin's. 

I mostly just wanted to share the behavior of 'allowNegativeLog' with values between 0 and 1, since I haven't been able to figure out where the value impacts the positive data, using the standard  lin2log/log2lin. 

Thanks again!

**Comment by plbertrand** [comment]
@TJLanger  and @sebastianbochan, I'm trying to achieve exactly this but your jsfiddle are not working anymore. Is there a supported way to do it or the API has changed for custom functions?

**Comment by TJLanger** [comment]
@plbertrand, I can't comment on the currently supported method. My last use of this was using version 6.2.0 , which you can see working in the fiddle by swapping in "<script src="https://code.highcharts.com/6.2.0/highcharts.js"></script>"

**Comment by plbertrand** [comment]
Thanks for the reply! For those looking for a working solution on the current version: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/yaxis/type-log-negative/
