### ISSUE TITLE
Polar chart : Issue with max Y axis value which is placed out of the graph

### ISSUE THREAD

**Issue by mddivalua** [highcharts/highcharts#6353]
**Expected behaviour**

Max Y axis value (4 in the live demo) should appear on the axis

**Actual behaviour**

See live demo, value "4" is not placed on the graph but at -9999 position...

**Live demo with steps to reproduce**

http://jsfiddle.net/4kan6o4z/

Thanks In Advance

**Affected browser(s)**

Google Chrome, Mozilla Firefox, Internet Explorer

**Comment by pawelfus** [comment]
Hi @mddivalua 

It's caused by default setting for [`Axis.showLastLabel`](http://api.highcharts.com/highcharts/yAxis.showLastLabel) - when it's set to `true` it works fine, please take a look: http://jsfiddle.net/4kan6o4z/2/ (by default, in radial axes/polar charts `showLastLabel` is set to false)

FYI: @TorsteinHonsi

**Comment by mddivalua** [comment]
Thank you for this answer, I did not find this property and it works very well ! 

Sorry for this disturbance.

**Comment by pawelfus** [comment]
No need to apologize! We should have this in our docs.

**Comment by TorsteinHonsi** [comment]
Thanks, it's added now.
