### ISSUE TITLE
Spline chart looks jagged when points are close to each other

### ISSUE THREAD

**Issue by jacywang** [highcharts/highcharts#6362]
#### Expected behaviour
Spline chart should look smooth

#### Actual behaviour
It looks jagged when there are a big amounts of data and points are close to each other. 

#### Live demo with steps to reproduce

[Example on jsfiddle](http://jsfiddle.net/L0wr6pzL/1/)

#### Affected browser(s)
Not related to browser

**Comment by pawelfus** [comment]
Hi @jacywang 

Thank you for this report. I think this chart is rendered correctly, it's just how the data is. Let's zoom in: http://jsfiddle.net/L0wr6pzL/3/ - as you can see, even with a small portion of the chart, it will look jagged. This is caused by using many points with the same value (~30 per value) and then changing slightly y-value.
