### ISSUE TITLE
Issue while updating series from 'CandleStick' to 'Line'

### ISSUE THREAD

**Issue by BDChaudhari90** [highcharts/highcharts#6374]
Hello Team,

We already raised issue to Support team and got reply with below GitHub link
highcharts/highcharts#2322

But still We are facing issue while updating series from 'Candlestick' to 'Line' and again from 'Line' to 'Line'.

Below are the exact steps to replicate issue.
Click on JsFiddle - http://jsfiddle.net/BDChaudhari90/97651yvn/10/

Here the chart will be loaded with candlestick type initially.
Now change it to Line by clicking on "change to line" button. (Chart will be changed to line.)
Now click on 'Again change to Line' button. (This is causing issue.)
Now again change to candlestick it will work.
If above GitHub link is the workaround for the same then how can we replace all the methods of the prototype object ?

**Comment by pawelfus** [comment]
Hi @BDChaudhari90 

Thank you for contacting us. This bug was fixed yesterday and we haven't released a new version yet. That means [current](http://code.highcharts.com/stock/highstock.js) version is not a fixed one. 

You can test our [master branch](http://github.highcharts.com/highstock.js), but don't use that on production - that version may cause unexpected issues.

**Comment by BDChaudhari90** [comment]
Thank you @pawelfus ...

I retested series.update and it seems issue has been resolved by using master branch version.

Can you please let me know when we will get a stable version so that I can integrate it on my production ??

**Comment by pawelfus** [comment]
Hi @BDChaudhari90 

Next version should be released within a few weeks.
