### ISSUE TITLE
After adding "pointIntervalUnit" to column chart, highcharts crashes tab with out of memory exception.

### ISSUE THREAD

**Issue by AntanasBarauskas** [highcharts/highcharts#6405]
#### Expected behaviour

After adding pointIntervalUnit property to plotOptions.series, browser tab results in out of memory exception. This behavior occurs in Chrome/FF/IE. Added jsFiddle example with crashing code.
 
#### Actual behaviour

Crashes with out of memory exception. 
NOTE: Changing "type":"datetime" results in freezing tab instead of out of memory exception.

#### Live demo with steps to reproduce
http://jsfiddle.net/720aboww/

#### Affected browser(s)

Chrome/FF/IE

**Comment by pawelfus** [comment]
Hi @AntanasBarauskas 

Thank you for this report. Could you post also a demo which doesn't crash the browser? It's a bit hard to debug.. :)

Thanks!

**Comment by AntanasBarauskas** [comment]
Hello @pawelfus 

Sure: https://jsfiddle.net/06b4kvge/ :)

**Comment by pawelfus** [comment]
Thanks!

The problem is setting `xAxis.categories`. That means Highcharts will try to render every category (`tickInterval = 1unit`, for a `datetime` axis unit is 1ms) for a given range. So, if you set `pointerInveralUnit` to one year, it means ~365*24*360*1000*number_of_points categories on xAxis.. :) 

After removing `xAxis.categories`, it works fine: https://jsfiddle.net/06b4kvge/2/

**Comment by AntanasBarauskas** [comment]
You're right, removed xAxis.categories and works like a charm!

Thanks.

**Comment by inoyakaigor** [comment]
@pawelfus Hi!
Yesterday I've got an out of memory error. I had wrong config (with xAxis.categories) and in this line browser throw exception.
https://github.com/highcharts/highcharts/blob/b9c683576110b58cedd46e09668e987053e74829/js/parts/Time.js#L745

It was happen because, I believe,  in `tickPositions` array had been containing ≈9 500 000 000 time numbers. Of course it is my mistake but if Highcharts notified me about potentially memory leak I'd save a lot of time.

Therefore I suggest to add warning in this line about big length of tickPositions array. As sample if length more than 10 000 000

**Comment by pawelfus** [comment]
Hi @inoyakaigor 

Thanks you for the suggestion! We used to throw `Highcharts Error 19` in v4.0.x (link: https://www.highcharts.com/errors/19). I'm not sure about the story behind removing this, probably users preferred removing additional ticks instead of the error.

@TorsteinHonsi 
bisect leads to https://github.com/highcharts/highcharts/commit/db6981ed09b879d37320867c2d4ae41c795e8dbf#diff-ca66923e4c3df841c40471c133bce754 (search for `factor19`) - anything to add here?

**Comment by TorsteinHonsi** [comment]
I'm not able to reproduce it from the description - can you make changes to http://jsfiddle.net/highcharts/arxqgy5e/5/ in order to showcase the issue?

**Comment by pawelfus** [comment]
@inoyakaigor - could you update the demo posted by Torstein?

**Comment by inoyakaigor** [comment]
@pawelfus yeah I will try but later

**Comment by pawelfus** [comment]
Can be related to #8026

**Comment by inoyakaigor** [comment]
http://jsfiddle.net/d9gu1eoj/5/ @pawelfus @TorsteinHonsi 

Chrome silent disconnect a devtools. Firefox write in console out of memory error
Mistake in xAxis.labels.step = 1

**Comment by pawelfus** [comment]
Thank you @inoyakaigor for the demo!

Simplified demo: http://jsfiddle.net/BlackLabel/twf2kqr9/ (or based on Torstein's demo: http://jsfiddle.net/BlackLabel/arxqgy5e/14/ )
Actually, removing `type: "datetime"` does not resolve the issue: http://jsfiddle.net/BlackLabel/twf2kqr9/2/

@TorsteinHonsi - how should we resolve this? Prevent categories to display when `datetime` type is set? But this is misconfigured on a label's level.

**Comment by TorsteinHonsi** [comment]
It also fails when the type is not _datetime_, except it doesn't crash immediately. Maybe we need to reintroduce error 19 for cases when `label.step` is set?

**Comment by pawelfus** [comment]
I think solution suggested by @inoyakaigor is super easy: simply when we have more than X ticks, show warning/error ?

**Comment by inoyakaigor** [comment]
I propose to add warning if count of ticks more than width of graph in pixels.

**Comment by TorsteinHonsi** [comment]
Done. I re-introduced the old logic that fires when the potential tick-interval is more than makes sense, but unlike before, added a more graceful degradation. The axis now render two ticks (min and max) instead of crashing the whole chart, and print a warning in the console. http://jsfiddle.net/highcharts/twf2kqr9/12/
