### ISSUE TITLE
Emtpy call to axis.update() change limits behavior.

### ISSUE THREAD

**Issue by Dunge** [highcharts/highcharts#6408]
Axis.update() in the doc mention is only merge the properties that changed. Passing an empty list seems to affect something anyway.

#### Expected behaviour
I actually expect the behavior to always be as after a call to update(), the limits to be cropped to the values set as min/max with no padding.

#### Actual behaviour
Without a call to update(), the axis is extended to show the cells full size. After a call to update(), the axis is cropped to the defined min/max.

#### Live demo with steps to reproduce
https://jsfiddle.net/q9km44x0/2/
Comment the "chart.yAxis[0].update({});" line near the end of the script to see the difference.

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @Dunge 

Thank you for reporting this bug. Workaround: set `axisPointRange` manually. Demo: https://jsfiddle.net/q9km44x0/4/ and snippet:
```javascript
  chart.yAxis[0].update({});
  chart.yAxis[0].axisPointRange = chart.series[0].options.rowsize || 1;

  chart.series[0].setData(data);
```

*Internal note:*
It's caused by setting `axisPointRange` in heatmap `series.init`. After `Axis.update()` that value is removed and not set back because series is not reinitialised.
