### ISSUE TITLE
select time range by moving navigator will drift for certain distance when y axis opposite false

### ISSUE THREAD

**Issue by fingerection** [highcharts/highcharts#6412]
#### Expected behaviour
set y axis opposite false, select time range by moving navigator, after data loaded, navigator position should not change

#### Actual behaviour
after data loaded, naviagtor will drift to left for certain distance

#### Live demo with steps to reproduce

http://jsfiddle.net/a9s7ah5q/

1. set zoom for 1y
2. move navigator to select range

then the range will change when data loaded

#### Affected browser(s)
chrome (Mac)

**Comment by pawelfus** [comment]
Hi @fingerection 

Thank you for reporting this bug. It's not only caused by `yAxis.opposite`, but in general by yAxis labels which are rendered outside the plotting area, for example: http://jsfiddle.net/a9s7ah5q/3/

If labels are inside the plotting area and `opposite` is set to false, it works too: http://jsfiddle.net/a9s7ah5q/4/
