### ISSUE TITLE
Drilldown 3d Piechart disappear after resize

### ISSUE THREAD

**Issue by harshpuidev** [highcharts/highcharts#6437]
Go to the fiddle below. Resize, increase the width of the container and then click on any part of the pie chart to drilldown for some reason pie chart disappear i can only see the labels.
![capture](https://cloud.githubusercontent.com/assets/16329252/23636486/7c108546-028a-11e7-94f9-cec81d2573a6.JPG)

![capture2](https://cloud.githubusercontent.com/assets/16329252/23636534/bf64a85e-028a-11e7-823d-92873c4eba68.JPG)

#### Live demo with steps to reproduce

http://jsfiddle.net/quickstep25/yhqqo2wv/
issue can be reproduce in chrome Browser

**Comment by pawelfus** [comment]
Hi @harshpuidev 

Thank you for reporting this bug.

*Internal note:*
It doesn't look like a regression - tested up to 4.1.x.

**Comment by KiranHundal** [comment]
Hi @pawelfus 

I am seeing the same issue with highcharts on my application as well. Could you please let me know when will you guys look into this. We are going to use highcharts extensively and this for sure is going to be a buggy problem.

**Comment by pawelfus** [comment]
I will look into it.

**Comment by pawelfus** [comment]
*Internal note:*
The problem was with animating after a resize [here](https://github.com/highcharts/highcharts/blob/35ce277248b2127bd865c724f06517183493a873/js/parts/PieSeries.js#L324). The method modified in the commit above caused `shapeArgs` to be (almost) empty, so drilldown module couldn't animate slices properly. Solution could to to merge options [here](https://github.com/highcharts/highcharts/blob/35ce277248b2127bd865c724f06517183493a873/js/parts-3d/SVGRenderer.js#L430), but instead of merging before method call, we can merge inside (we use that method only in two places, both should merge).

**Comment by KiranHundal** [comment]
Thanks a lot for fixing this bug. Could you please tell when will this fix be ready for us to use?

**Comment by pawelfus** [comment]
Hi @KiranHundal 

It will be part of the next release. Next release should be ready within a few weeks.

**Comment by harshpuidev** [comment]
Hi @pawelfus 

Thank you for the fix we have the application up and running. Our customers are begging us for the fix. it would helpful if you can tell us when would be the next release(a specify week or a day would be great)?

**Comment by pawelfus** [comment]
Unfortunately the date is not specified yet. I suggest modifying sources or using this workaround:

```javascript
    // Workaround for #6437
    Highcharts.wrap(Highcharts.SVGElement.prototype, 'animate', function (proceed, params, options, complete) {
        return proceed.call(this, Highcharts.merge(params), options, complete);
    });
```

Demo: http://jsfiddle.net/yhqqo2wv/11/

Note: I strongly recommend to update Highcharts once the release will be ready - the workaround above should be added only to the pages where issue appears. My apologies for the inconvenience!
