### ISSUE TITLE
Line-height not working in axis labels in CSS styled mode

### ISSUE THREAD

**Issue by ericpedia** [highcharts/highcharts#6443]
#### Expected behaviour
Setting a line-height value for `.highcharts-axis-labels` should affect line-height of axis labels that are broken onto multiple lines. 

(To get long labels to break onto multiple lines rather than being ellipsized, I am setting `xAxis.labels.style.textOverflow` to `'none'`, per https://github.com/highcharts/highcharts/issues/3941.)

#### Actual behaviour
Line-height is not affected.

#### Live demo with steps to reproduce
1. Create a chart with a category axis and long category names, long enough to cause line breaks in the axis labels.
2. Set `xAxis.labels.style.textOverflow` to `'none'` to prevent ellipsizing of the category names.
3. Set a `line-height` value in CSS in the `.highcharts-axis-labels` selector (or descendants of that selector, such as text or tspan). 

Setting a value for `xAxis.labels.style.lineHeight` in the JS options (on the assumption that it might have legacy support) doesn't have an effect either.

- **Demo:** http://codepen.io/ericpedia/pen/peNZML
- **Stackoverflow question:** http://stackoverflow.com/questions/42663155/how-to-adjust-line-height-ellipses-in-highcharts-axis-labels

#### Affected browser(s)
- Chrome
- Safari
- Not tested in others

**Comment by pawelfus** [comment]
Hi @ericpedia 

Thank you for reporting this issue. You are right, `lineHeight` is broken for CSS version. However it works fine for JS version: http://codepen.io/anon/pen/aJwmrP (note: `lineHeight` should be at least 1px).

*Internal note:*
It's caused by setting `lineHeight` [here](https://github.com/highcharts/highcharts/blob/f05172102aefc5f79a44c1282325a7ea6638c9fa/js/parts/SvgRenderer.js#L2036) and checking it later [here](https://github.com/highcharts/highcharts/blob/f05172102aefc5f79a44c1282325a7ea6638c9fa/js/parts/SvgRenderer.js#L2052) - this is of course undefined and always font size is taken into account when determining `dy` for a tspans.

**Comment by TorsteinHonsi** [comment]
I'm a bit confused - the OP demo has `useHTML: true`, so the code in `buildText` actually doesn't apply. 

Also, when I set it up in jsFiddle with pure CSS it seems to work well: http://jsfiddle.net/pqtjqqcw/1/

**Comment by pawelfus** [comment]
My mistake, I tested this without `useHTML` flag, demo: http://jsfiddle.net/pqtjqqcw/3/ (vs JS version: http://jsfiddle.net/pqtjqqcw/4/ )
