### ISSUE TITLE
Highstock click on zoomed area leaves two columns selected

### ISSUE THREAD

**Issue by ShMcK** [highcharts/highcharts#6445]
Using Highstock.

### Steps to Reproduce

1. Click on a column bar on the far left. 
2. Zoom in on the far right. 
3. Click on a bar within the zoomed in area. 
4. Zoom out.

#### Expected behaviour

One column to be highlighted.

#### Actual behaviour

The original column remains highlighted as well as selected bar, leaving two items selected.

Also the zoom animation is not performing as expected.

#### Example

![chart issue](https://cloud.githubusercontent.com/assets/4660659/23738647/0d730bc4-044f-11e7-92e7-ddca11150a00.gif)

#### Affected browser(s)

All

**Comment by jon-a-nygaard** [comment]
_Internal Note: [Simplified demo](http://jsfiddle.net/jon_a_nygaard/pnewwpfp/2/)_

**Comment by ShMcK** [comment]
An example: https://jsfiddle.net/ff4uwj4g/2/

Note that this issue is not related to "react-highcharts", and occurs when using just HighStock & JQuery.

**Comment by TorsteinHonsi** [comment]
The cause of the problem is that the series points array is cropped to the current viewing range. When running point.select, the method reads `getSelectedPoints` in order to unselect all other points, but this doesn't return the points that are outside the viewing range.

#### Workaround
Set the [cropThreshold](http://api.highcharts.com/highcharts/plotOptions.column.cropThreshold) higher and disable data grouping: http://jsfiddle.net/pnewwpfp/3/

**Comment by ShMcK** [comment]
Thank you, the workaround worked great.

**Comment by KacperMadej** [comment]
@TorsteinHonsi Only the test is added and the commit with the fix is not. Is there something wrong with the suggested fix?

**Comment by TorsteinHonsi** [comment]
Thanks for notifiying, it seems I didn't notice the fix itself.
