### ISSUE TITLE
Can't zoom when chart is embedded in IFRAME

### ISSUE THREAD

**Issue by LethArosii** [highcharts/highcharts#6446]
#### Expected behaviour

I want to share a single highcharts library among several iframes, so only one instance is loaded in the top window.

I reference this highcharts instance from nested iframes, the graphs draws perfectly, but zooming doesn't work.

#### Actual behaviour

It's possible to start marking a zoom area, but it's not possible to end the selection.

#### Live demo with steps to reproduce

http://jsfiddle.net/lethArosii/10Lb3q5f/

Try to zoom in the graph. 
#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting about the problem.
This is because `mouseup` event that ends the zoom selection is added to the document where highcharts.js is loading and not to the ownerDocument of chart's container.

For a far from perfect workaround you could wrap setDOMEvents function and addEvent for the proper document (ownerDocument of chart's container) - demo: http://jsfiddle.net/qh04tcey/1/
Please note that this will not work for automatic removing of events when destroying charts and might cause some memory leaks, so it's better to load Highcharts in the same frame as the chart's container is placed.

**Comment by LethArosii** [comment]
Thanks for the reply, i have found a couple of other issues with this approach (exporting and printing has errors), so i think i'll try to load Highcharts in all the frames that needs it and see how much memory it consumes, unfortunately that might be 20-30 frames depending on usage, but i might be able to reduce it.
