### ISSUE TITLE
Tooltip formatter gets wrong points in shared tooltip [5.0.8+]

### ISSUE THREAD

**Issue by stpoa** [highcharts/highcharts#6483]
#### Expected behaviour
After hovering point tooltip formatter should always indicate hovered point.

#### Actual behaviour
After hovering point tooltip formatter sometimes indicates point different from hovered one.

#### Live demo with steps to reproduce
https://jsfiddle.net/2p94dmcb/

1. Hover first then second and third column.
2. Notice "this" values in tooltip formatter (logged in console)

**Comment by yashhy** [comment]
@stpoa I think its broken after >5.0.8 release. As @jon-a-nygaard mentioned in his comment [here](https://github.com/highcharts/highcharts/issues/6456#issuecomment-286757030) it will be fixed in a Maintenance Release.

Here is the [workaround](https://jsfiddle.net/yashhy/2p94dmcb/1/) for you behaviour.

**Comment by sebastianbochan** [comment]
Fixed in v5.0.10.

Demo:
- https://jsfiddle.net/dmwL4zaw/
