### ISSUE TITLE
Highmaps - French Guiana (GF and GUF) iso a2 and iso a3 not showing

### ISSUE THREAD

**Issue by rlonka** [highcharts/highcharts#6486]
The French Guiana iso a2 code (GF) and iso a3 code (GUF) is not visualizing.
It is only shown when French code is used.  

http://jsfiddle.net/gx0oy8L0/

**Comment by oysteinmoseng** [comment]
This is by design, as the map you are using combines overseas areas with the sovereign country (for most countries).

We have had some requests for maps with other groupings, but it's tough to cover all possibilities. Generally we recommend customizing the map to your needs. This is easy to do, as explained [here](http://www.highcharts.com/docs/maps/custom-geojson-maps) and [here](http://www.highcharts.com/docs/maps/custom-maps).
