### ISSUE TITLE
SoftMin, SoftMax Ignored at smaller ratio

### ISSUE THREAD

**Issue by crazedmeph** [highcharts/highcharts#6493]
#### Expected behaviour
Using softMin and softMax being able to set the charts min and max tick value.

#### Actual behaviour
Charts start acting weird when you play with the width and height of the chart. If you make the chart super long in the x it still does not allow the softMin and softMax in either highcharts or stockcharts. Also if you make the x and y closer to a normal ratio but a little smaller... Ex. 282x180 then soft min and soft max are no longer honored.

#### Live demo with steps to reproduce
Highcharts
http://jsfiddle.net/afud9ggL/2/
You have to resize the browser to get it to size correctly... 

Also, does highstock have a softMin? 
http://jsfiddle.net/f0u0gbj2/1/
not sure why that soft min is not working, looks like it shows up in the api but does not work.

#### Affected browser(s)
Chrome and firefox were tested

**Comment by pawelfus** [comment]
Hi @crazedmeph 

This is caused by default value for [`yAxis.tickPixelInterval`](http://api.highcharts.com/highcharts/yAxis.tickPixelInterval) - when setting e.g. to 25px, softMin and softMax are applied: http://jsfiddle.net/afud9ggL/3/ (and Highstock: http://jsfiddle.net/f0u0gbj2/2/ ). 

A little longer explanation: Actually softMin and softMax are set, but extremes are extended according to [`endOnTick`](http://api.highcharts.com/highcharts/yAxis.endOnTick) and [`startOnTick`](http://api.highcharts.com/highcharts/yAxis.startOnTick) options, when disabled you can see range 20-80 in your chart: http://jsfiddle.net/afud9ggL/4/ In this demo, extremes are set according to softMin/softMax but we won't see ticks because of `tickPixelInterval`.

**Comment by crazedmeph** [comment]
Ahhh, interesting. So some of the defaults are just conflicting with what I am expecting. Thanks for explaining! Sorry for creating a bug request :).
