### ISSUE TITLE
setData not redrawing drilldown chart with new data

### ISSUE THREAD

**Issue by amit1911** [highcharts/highcharts#6506]
#### Expected behaviour
setData should redraw the drilldown chart with the new data.

#### Actual behaviour
It updates the data but doesn't redraw the chart. If you drillup and then drilldown, the chart is drawn with the new data.

#### Steps to reproduce

1. Drilldown.
2. Click on 'Ascend' button under the graph. This will sort the current data for the drilldown graph series.
3. Drillup.
4. Drilldown. The data is now sorted.

Note: If you call `chart.series[0].update({})` after `setData` then the chart is redrawn with the new data.

#### Live demo with steps to reproduce
https://jsfiddle.net/amit1911/7achzrpd/4/

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Thank you for reporting about the issue.

To make this work you should sort copy of the points instead of the points, so the chart structure won't be altered. Additionally you should make an update on source of the drilldown series data, but drilldown doesn't support dynamic changes - you should use [async drilldown](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/drilldown/async/) instead. However, it's possible to change chart options manually. Demo: https://jsfiddle.net/7achzrpd/5/

**Comment by amit1911** [comment]
thanks a lot @KacperMadej... this seems to be working, though I still need to test it with multiple series. Multiple series with multiple axis is giving me some problems when i drilldown. I opened an issue regarding that as well (#6505).
Anyways, though this fixes my issue, how would using Async Drilldown be any different? Won't I have to do the same thing when i need to sort the data?

**Comment by KacperMadej** [comment]
@amit1911 Not very different, but changing variable drilldowns in the drilldown function is better than playing with Highcharts chart config (as in my demo from previous comment), because this is not supported - might not be working after another version release if we choose to change internal logic and since it's not a part of API there won't even be notification about it in change log. In short: async drilldown should be safer solution.

**Comment by amit1911** [comment]
I found a bug in this. I created a new fiddle with 2 drilldowns.
https://jsfiddle.net/amit1911/7achzrpd/7/
 ### Steps to reproduce
1. Drilldown to level 2
2. Sort the data. Data will be sorted correctly
3. Drill down to level 3.
4. Sort the data. It will be sorted correctly.
5. Drill up to level 2.
6. Sort the data. It doesn't work. I see the error `Uncaught TypeError: Cannot read property 'setData' of undefined` in the console.

**Comment by amit1911** [comment]
Okay. I have implemented the sorting functionality using the Async drilldown but i am not sure if this is how you thought of doing it. Can you please take a look and tell me if I have implemented correctly.
Link to fiddle -> http://jsfiddle.net/amit1911/oLmxL6g9/2/

**Comment by KacperMadej** [comment]
@amit1911 Yes, this is roughly what I had on mind. If you are having any problems please use any available for you [support channel](http://www.highcharts.com/support). We are trying to keep github for bugs.

**Comment by amit1911** [comment]
okay. Thanks a lot for your help.
