### ISSUE TITLE
Boost module does not draw all series 

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#6520]
#### Expected behaviour
Draw all series

#### Live demo with steps to reproduce
In the demo: 
 - http://jsfiddle.net/w6ss3shx/ 
series 1 is draw, but not in the demo: 
 - http://jsfiddle.net/bboLs6vj/

**Comment by mlvn23** [comment]
I've also been looking at the Boost module and it seems like there's a lot of limitations, but this is to be expected since it's still under development. 

Instead of working on Boost, does it make sense to re-consider Canvas? I'm aware that HighCharts was first built on Canvas and then moved to SVG. But times has changed, and I'm wondering if it needs to be re-evaluated. 

Newer generation of libraries that was built on Canvas appears to be very successful. 

D3 v4 for example now supports Canvas while in v3 they only focus on SVG.

[TradingView](https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/) is also built on Canvas.

[ECharts](https://ecomfe.github.io/echarts-examples/public/index.html) is built on Canvas and [can plot 200K points in < 500ms](https://ecomfe.github.io/echarts-examples/public/editor.html?c=scatter-large).
