### ISSUE TITLE
Date picker showing current Date by default

### ISSUE THREAD

**Issue by sorb999** [highcharts/highcharts#6529]
#### Expected behaviour
It should show date selected in Range Selector 

#### Actual behaviour
Showing current Date on click on calendar.

#### Live demo with steps to reproduce

http://jsfiddle.net/sorb999/BWEm5/604/

#### Affected browser(s)
All browsers

**Comment by sorb999** [comment]
@sebastianbochan any solution you have??

**Comment by sebastianbochan** [comment]
The issue is not related with Highcharts but with datepicker. You should catch the beforeShow event in the plugin and then apply input's date in right format.

Demo:
- http://jsfiddle.net/nkgnze74/

For the further support questions, please contact with us by email, stackoverflow or forum (http://www.highcharts.com/support)
