### ISSUE TITLE
Boost module: Zooming below boost level on multi-series chart fails

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#6531]
#### Actual behaviour
All line graphs are hidden

#### Live demo with steps to reproduce
1. Open http://jsfiddle.net/highcharts/extb16tx/
2. Click Poof.

**Comment by cvasseng** [comment]
The issue seems to be with the culling when building points, since boost is always enabled when boosting on series-level. 

I'm pretty sure that what happens is that when zooming in to such a small range that there are no points inside the selected range (e.g. 50.002 - 50.004) all points are skipped, since the drawing logic does a `skip if this point is not inside the chart range, and if the next or previous point is not inside the range`.

Working on a fix.
