### ISSUE TITLE
Remove forEach from code.

### ISSUE THREAD

**Issue by 4p00rv** [highcharts/highcharts#6532]
Hi, 
I recently discovered that `Array.prototype.forEach` is very slow compared to `for`. Since, highcharts use it for iterating over various objects, it is  causing a memory leak in our project. You can check the performance of various ways to iterate over object here:
[https://jsperf.com/for-vs-foreach-vs-lodash-foreach](https://jsperf.com/for-vs-foreach-vs-lodash-foreach)

I suggest that the `Array.prototype.forEach` implementation is removed from highcharts. It can be found here: [https://github.com/highcharts/highcharts/blob/8ffd09bce9b44441d35c9d6528d43a5f4c7c79aa/js/parts/Utilities.js#L1542](https://github.com/highcharts/highcharts/blob/8ffd09bce9b44441d35c9d6528d43a5f4c7c79aa/js/parts/Utilities.js#L1542)

**Comment by TorsteinHonsi** [comment]
Thanks for your suggestion! You say it is causing a memory leak in your project - is that related to the speed?

**Comment by 4p00rv** [comment]
@TorsteinHonsi Yes it is related to the speed. I did improve the code in my project to quite an extent  in order get more stable performance but at times, when there are more than 3 series on chart, the page would crash, this happens rarely.

**Comment by TorsteinHonsi** [comment]
Consider this test: http://jsfiddle.net/highcharts/xzsnjtgb/

Although a pure for loop is faster in this case - once we wrap it and apply the callback to each item, the native `forEach` is faster.

We discussed it here in the office, and agreed that optimizations probably should be determined on more individual basis. In some cases, the `forEach` is the right choice. In other cases, a `for` or a `while` loop is better. As a rule of thumb, in Highcharts we usually use `for` or `while` when dealing with points, because those can be in the order of hundreds of thousands.

**Comment by 4p00rv** [comment]
Thanks for the fiddle, now I know that forEach` can be faster too. But I think there's one misplaced forEach in code that's causing the issue in my project.
![Memory](http://i.imgur.com/segyi5O.png).

It is taking upto 25% of time, can we replace this with `for`?

**Comment by TorsteinHonsi** [comment]
Yes that may be a good candidate for optimization. Can you use `highcharts.src.js` for debugging so that we can find the actual place to optimize?

Also, it may be that you can optimize how you set up Highcharts. For example, you should only use `addPoint` if you are adding points to an existing chart async. If you have the points ready when you initiate the chart, the points should be added through the `series.data` config option. Sorry if this is obvious, but it may be a caveat.

**Comment by 4p00rv** [comment]
As suggested here's a screenshot after using `highstock.src.js`. 
![Imgur](http://i.imgur.com/YmOR2GJ.png)

I noticed that redraw function uses a lot of `each` calls inside it. I suggest that we replace this with `for`.

**Comment by KacperMadej** [comment]
H.each is depreciated and we are using [].forEach everywhere, so closing this as resolved
