### ISSUE TITLE
WebGL Boost and WebGL context loss

### ISSUE THREAD

**Issue by brian428** [highcharts/highcharts#6539]
The new WebGL Boost module is a great new feature. However, it looks as if a separate WebGL context is used for each series. Since browsers have a maximum number of active WebGL contexts, anything more than 16 series (either on one chart, or across multiple charts on the same page) will result in loss of contexts, which breaks the charts. In addition, errors are logged to the console (`Too many active WebGL contexts. Oldest context will be lost.`).

Wouldn't it be possible to use one WebGL context for each chart, rather than each series? We'd still be limited to 16 charts on a page, but at least the number of series wouldn't be limited.

**Comment by TorsteinHonsi** [comment]
Thanks for writing!

There's an option for that, it's called `boost.seriesThreshold` and defaults to 10. When there are more series in the chart than this threshold, the context will be combined to a common chart context. 

You can see it in http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/samples/highcharts/boost/line-series-heavy/.

If you have a high number of charts in the page but each chart is below the threshold, you can probably lower the threshold to avoid your problem.

Also, we are in the process of revamping our API docs. Once we have finished that, we will come out with a full API and tutorial for the Boost module.

I'm closing this, please reopen if it doesn't resolve your problem.

**Comment by TorsteinHonsi** [comment]
@cvasseng

**Comment by brian428** [comment]
Out of curiosity, is there a reason why this isn't done by default? Is there some disadvantage to using a single WebGL context for each chart?

**Comment by cvasseng** [comment]
@brian428: the main reason that there's two different scopes in the boost (one per. series where the threshold is the number of points, and one on chart-level where the threshold is the amount of series) is to allow for combination charts where some series are boosted, and some are not. 

If everything used a single gl context always, it would be difficult to have a chart where series #1 and #3 is boosted, and series #2 is not, and at the same time have the z-index behave as expected since series #1 and #3 would effectively end up on the same z-plane.
