### ISSUE TITLE
Graph.zoomOut() documentation is missing

### ISSUE THREAD

**Issue by KoltonG** [highcharts/highcharts#6581]
#### Expected behaviour
Have the zoomOut function defined in http://api.highcharts.com/highcharts/Chart

#### Actual behaviour
No function defined in http://api.highcharts.com/highcharts/Chart. I only found out about it by looking at the graph object function.

#### Live demo with steps to reproduce
N/A

#### Affected browser(s)
N/A

**Comment by pawelfus** [comment]
Hi @KoltonG 

Thanks for the report. We have many methods in our classes that are not part of the official API. Remember you can reset zoom by setting extremes: `axis.setExtremes(null, null);`.

**Comment by amit1911** [comment]
@pawelfus `axis.setExtremes(null, null)` does zoom out but it doesn't hide the 'reset zoom' button. So I am using `chart.zoomOut()` instead of `setExtremes(null, null)` and it works fine. Is `zoomOut` function the correct way to do it? or should I use something else for this purpose?

**Comment by pawelfus** [comment]
If you need to hide zoom-out button automatically, then yes `zoomOut()` will work for you.

**Comment by amit1911** [comment]
Okay thanks

**Comment by dandv** [comment]
Please document how to zoom out. On mobile, users could [pinch out](https://english.stackexchange.com/questions/177077/does-pinch-have-an-opposite) (I haven't tried if this actually works), but on the desktop there's no clear guidance on how to zoom out. This is a common enough request that there's a [zoom out plugin](https://www.highcharts.com/products/plugin-registry/single/26/Zoom%20Out%20Selection) but I firmly believe that zooming out belongs among the core features of Highcharts, and especially Highstock. After all, what is the user supposed to do after zooming in? `setExtremes(null, null)` is a brute-force solution that zooms out to the *entire* interval, instead of going back to the previous zoom step.

**Comment by TorsteinHonsi** [comment]
Thanks, it's done. Exposed `Chart.zoomOut` in the API and added description to the docs.
