### ISSUE TITLE
Data Point and Series Hover Animation Stops Working After Resize

### ISSUE THREAD

**Issue by udeleng** [highcharts/highcharts#6582]
#### Expected behaviour
When you resize the chart, the slow fading animation effect you see when you hover out from a data point and a series should work.

#### Actual behaviour
Once the chart area has been resize, the fading animation effect no longer works.

#### Live demo with steps to reproduce

1. Hover over the data point and then hover out from the data point and notice that the point & halo fade slowly
2. Resize the JSFiddle results panel such that the white chart area resizes and repeat step 1. Observer that the data point marker and halo do not fade when you hover out.

http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/line-basic/

#### Affected browser(s)
Chrome, Firefox, IE11

**Comment by pawelfus** [comment]
Hi @udeleng, thank you for reporting the issue. 

**Workaround:**
Reset the animation after redraw, demo: http://jsfiddle.net/e16n2ufu/1/

```javascript
chart: {
  events: {
    redraw: function () {
      Highcharts.setAnimation(true, this);
    }
  }
},
```

*Internal note:*
It's caused by disabling global animation in reflow event [here](https://github.com/highcharts/highcharts/blob/c35fc5c5f5f01cdef5cb250e29c249f9575bfb05/js/parts/Chart.js#L883). Maybe we should simply add `halo.animation` object so it can be configurable?
