### ISSUE TITLE
Boost: High memory usage

### ISSUE THREAD

**Issue by Rashaine** [highcharts/highcharts#6583]
#### Expected behaviour
With the canvas based Boost I am able to render 19 million points in a scatter. With the WebGL version i'm only able to render 9M because of high memory consumption.

#### Actual behaviour
Can only render 9 million points

#### Live demo with steps to reproduce
Canvas version http://jsfiddle.net/g4muv8qx/3/
WebGL version http://jsfiddle.net/j5q3r880/

#### Affected browser(s)
Chrome

**Comment by Rashaine** [comment]
Is it possible to disable WebGL and use canvas in the latest Boost? Or was canvas support fully stripped out?

**Comment by cvasseng** [comment]
The reason for the extra memory usage is that the dataset is in effect duplicated when using boost because it needs to be converted into a different format prior to sending it to the GPU for rendering. We're looking into ways of getting rid of the extra footprint.

While the old canvas renderer is still there, and used as a fallback in cases where WebGL is unavailable/unsupported, it's not currently possible to manually disable the WebGL renderer, and instead use the canvas renderer.

Please bear in mind that the WebGL module is currently in its infancy. It's very much in a beta/experimental state, like the canvas renderer was too. So far the main objective has been getting a foundation up and running with feature parity with the canvas boost. Going forward, the priority will be further optimizations, both in terms of raw performance and memory consumption, as well as extended support for general Highcharts features.
