### ISSUE TITLE
HighStock: Series with "keys" from array data source doesn't render unless zoomed in

### ISSUE THREAD

**Issue by NathanWolf** [highcharts/highcharts#6590]
#### Expected behaviour

A complex line series will render at any zoom level. I am using a data series with one point per day over several years, but nothing will display unless you zoom in to a 1 year-or-so range.

#### Actual behaviour

If using a line series that takes OHLC data (such as [time, open, high, low, close]) and a "keys" property like ["x", "open", "high", "low", "y"] to select [time, closing price] the series will not render unless zoomed in.

I have tried adjusting turboThreshold, but that does not seem to help. Turning off dataGrouping does help, but probably not ideal for the number of data points in this series, I would like to be able to use the data grouping feature.

Omitting the "keys" property or using ["x", "y"] provides the expected behavior as well, but would require changing the way our data sources provide data.

I also see this issue when using an arearange series, in which case omitting the keys is not an option since it requires more than one y value.

#### Live demo with steps to reproduce

https://jsfiddle.net/NathanWolf/ywjnd6en/3/

The series is added dynamically to mimic our environment, but I don't believe that is necessary to reproduce the issue.

Note that the issue seems to be related to HighStock in particular, a similar example with just HighCharts works as expected:

https://jsfiddle.net/NathanWolf/jouddteq/1/

Though I think this may just be because dataGrouping is a HighStock feature.

#### Affected browser(s)

Chrome 57, Safari 10.1

**Comment by sebastianbochan** [comment]
Thank you for the reporting.

It's interesting thing, because scatter series with lineWidth works well.

Workaround:
- https://jsfiddle.net/06vxhnqh/

**Comment by pawelfus** [comment]
**Workaround:**
Demo: https://jsfiddle.net/15qhj9oy/2/ (added setting: `Highcharts.seriesTypes.line.prototype.pointArrayMap = ["open", "high", "low", "y"];` and changed approximation to `ohlc`. Of course, instead of `ohlc` it should be average from all of the arrays.

*Internal note:*
The problem is mismatching approximation. Default approximation for line series is "average", which generates only one array of data. Later that data is mapped to `open` value (first entry in `pointArrayMap` [here](https://github.com/highcharts/highcharts/blob/c35fc5c5f5f01cdef5cb250e29c249f9575bfb05/js/parts/Point.js#L143)). In the last phase, `y` is required to render a line, but only `open` value exists in points. Additionally, `pointArrayMap` doesn't exist in line series, so we need to copy the same array as `key` (except "x" of course).

@KacperMadej - can you consider this issue when working on #5479? Maybe we can find some synergy here. It will can an issue with technical-indicators on series too.

**Comment by KacperMadej** [comment]
The problem here should be resolved for the dataGrouping through the above commit.
However, a more general problem is now more visible - turbo mode is not respecting keys on data. 
Reported here: https://github.com/highcharts/highcharts/issues/6625

**Comment by TorsteinHonsi** [comment]
@KacperMadej Instead of swapping the key option I moved the check to where `keys` is actually used, which feels more like the right place. Your test still passes. Please review.

**Comment by KacperMadej** [comment]
@TorsteinHonsi Unfortunately this solution doesn't work for series types that are using `pointArrayMap` while changing view from grouped to grouped - demo: http://jsfiddle.net/yx3t921b/6/

To recreate the problem play with the navigator range.

Points are created [here in code](https://github.com/highcharts/highcharts/blob/master/js/parts/DataGrouping.js#L296-L299) and at that time series is having `hasGroupedData` flag set to `true`.

**Comment by TorsteinHonsi** [comment]
Okay, can you write a test and commit a new fix for it? Then I'll cherry-pick without breaking it hopefully :)
