### ISSUE TITLE
Charts are overlapping when data series is more than 9 when using boost.js

### ISSUE THREAD

**Issue by SrinivasGit049** [highcharts/highcharts#6600]
#### Expected behaviour
Column Charts should not overlap when data series is more than 9

#### Actual behaviour
Column Charts are overlapping when data series is more than 9

#### Live demo with steps to reproduce
Add a data series with more than 9 data series in below Column chart example as below
http://jsfiddle.net/bgybn2ok/

series: [{
       data: data
   },{
       data: data
   },{
       data: data
   },{
       data: data
   },{
       data: data
   },{
       data: data
   },{
       data: data
   },{
       data: data
   },{
       data: data
   },{
       data: data
   }]

var data = getData(10);

The charts will be overlapped now.
Now even after deselecting legends( i.e hiding some data series in legends)  the selected legend chart is getting overlapped and not re-rendering.
[Chart.zip](https://github.com/highcharts/highcharts/files/925539/Chart.zip)

###Version:
5.0.10

**Comment by cvasseng** [comment]
Hi @SrinivasGit049,

the reason you're seeing this after 9 series, is that by default, the boost kicks in if the total amount of series reaches 10 (in which case it will boost the entire chart) OR if the amount of points in any of the series reaches 5000 (in which case it will boost only the series reaching the threshold).

The idea behind the boost module is to increase performance when it's needed (i.e. when the number of series or points are very large), and then rely on the standard SVG renderer once e.g. the chart is zoomed in to such a level that boosting is no longer required. As such, to ensure high performance, a lot of functionality is bypassed when the boost module kicks in; such as grouping, and rendering columns/bars as rectangles. The use case in other words, is displaying thousands/hundreds of thousands/millions of points at once; where things like grouping or animation is much less relevant than when showing a couple dozen or a couple hundred points.

The solution to your issue is to use the series-level threshold rather than chart-level threshold. In other words, setting `series.boostThreshold` to a higher value, and instead relying on `boostThreshold` on individual series to control boosting: http://jsfiddle.net/06px3Lry/1/

This will have the boost kick in when it's more appropriate when you have less data, and will also make it so that the SVG renderer "takes over" when you zoom in to datasets with less than 5000 points. If you want the boost to kick in with more (or less) points than 5000, you can set the threshold on the series individually with the `boostThreshold` property (http://jsfiddle.net/06px3Lry/2/).

**Comment by SrinivasGit049** [comment]
Hello High Charts Team,


? The work around is working fine till data series is 28.Above 28 this issue starts coming again.Please do the needful on this.

Please find link for reference.


Thanks,

Srinivas

________________________________

**Comment by SrinivasGit049** [comment]
Hello High Charts Team,


? The work around is working fine till data series is 28.Above 28 this issue starts coming again.Please do the needful on this.

Please find link for reference.

http://jsfiddle.net/06px3Lry/1/?

Thanks,

Srinivas


________________________________

**Comment by SrinivasGit049** [comment]
Please find below the updated link.


http://jsfiddle.net/06px3Lry/6/?


Thanks,

Srinivas

________________________________

**Comment by cvasseng** [comment]
Hi, 

could you try resizing you browser window? Bars/colums will be culled away if there's no room for them, so make sure your chart area is large enough to fit them all.

![groupingresize](https://cloud.githubusercontent.com/assets/1998167/25992694/ac8c5f2c-3707-11e7-8728-bf0a0e7e8a7e.gif)

**Comment by KacperMadej** [comment]
Resolved through [`crisp`](https://api.highcharts.com/highcharts/series.column.crisp) option.
Demo: http://jsfiddle.net/BlackLabel/bgybn2ok/4/
