### ISSUE TITLE
Bar charts are not displaying correctly when data series is more than 9 when using boost.js

### ISSUE THREAD

**Issue by SrinivasGit049** [highcharts/highcharts#6602]
#### Expected behaviour
Bar charts are not displaying correctly 

#### Actual behaviour
Bar charts are should display displaying correctly 

#### Live demo with steps to reproduce
Add data series more than 9 as in below example and observe that charts are not displaying correctly when using boost.js
http://jsfiddle.net/19gf7rLx/2/
#### Affected browser(s)
Safari,Chrome,IE

**Comment by cvasseng** [comment]
Bar charts are not supported currently, but support is on the way.

You can use:

`chart: {
        type: 'column',
        inverted: true
    }`

In the meantime to achieve the same, but note that series stacking is not working correctly in boost, as described in #6600.

**Comment by suryamdv** [comment]
Even with column type chart is happening same, Instead of showing one beside another it is showing one over the other which is not the case with 9 or lower no of data series.

**Comment by cvasseng** [comment]
Yes, that's what I meant when I referenced #6600 which describes that issue. The reason why it works with less than 9 series is because the boost isn't active by default until you cross 9 series in total OR 5000 points in any given series.

In any case, my overall meaning was that bar charts are not currently supported at all in boost, but you can work around it by using an inverted column series. But again, #6600 is still in effect, and as such half of this issue is a duplicate of that, whereas the other part (bar support) isn't a bug, but rather something that's just not implemented at the moment, but that will be.

**Comment by SrinivasGit049** [comment]
Hi have go below work around from High charts team.

the reason you're seeing this after 9 series, is that by default, the boost kicks in if the total amount of series reaches 10 (in which case it will boost the entire chart) OR if the amount of points in any of the series reaches 5000 (in which case it will boost only the series reaching the threshold).
The idea behind the boost module is to increase performance when it's needed (i.e. when the number of series or points are very large), and then rely on the standard SVG renderer once e.g. the chart is zoomed in to such a level that boosting is no longer required. As such, to ensure high performance, a lot of functionality is bypassed when the boost module kicks in; such as grouping, and rendering columns/bars as rectangles. The use case in other words, is displaying thousands/hundreds of thousands/millions of points at once; where things like grouping or animation is much less relevant than when showing a couple dozen or a couple hundred points.
The solution to your issue is to use the series-level threshold rather than chart-level threshold. In other words, setting series.boostThreshold to a higher value, and instead relying on boostThreshold on individual series to control boosting: http://jsfiddle.net/06px3Lry/1/
This will have the boost kick in when it's more appropriate when you have less data, and will also make it so that the SVG renderer "takes over" when you zoom in to datasets with less than 5000 points. If you want the boost to kick in with more (or less) points than 5000, you can set the threshold on the series individually with the boostThreshold property (http://jsfiddle.net/06px3Lry/2/).

**But ​ the work around is working fine till data series is 28.Above 28 this issue starts coming again.Please do the needful on this.
Please find link for reference.
http://jsfiddle.net/06px3Lry/1/​**

**Comment by SrinivasGit049** [comment]
We tried the above work around for loading charts in iPad web view. The issue is resolved but we are observing the performance issue after this changes.The chart is taking too long time to load in iPad after adding below configuaration
 boost: {
    	seriesThreshold: 50
    }
Without this configuration it is taking around 35 secs to load charts with more than 25 series.
Same it is taking 2 mins with configuaration

**Comment by cvasseng** [comment]
When setting `seriesThreshold` to `50`, you're telling boost to activate once there are more than 50 series in the chart. That's why it's faster when you disable it; presumably you have less than 50 but more than the default value of 20. Meaning that when you remove that part of the configuration, boost is activated for your chart.

To have your cake and eat it too, you need to set `seriesThreshold` to a higher number than the amount of series in your chart, and then set `boostThreshold` on the `series` configuration objects to something that makes sense for the number of points you have. `boostTreshold` on the series level is the number of points that must exist in the series for the boost to activate. It takes zoom into consideration, which means that when you zoom in and the point density decreases, it will deactivate the boost and switch back to SVG rendering when the point count goes below the number you set. The number depends on your dataset, but try setting it to 1000 or so and increase it as necessary until you're happy with the appearance and the performance.

**Comment by SrinivasGit049** [comment]
The above work around only helping in displaying charts correctly  but breaking the real use of boost which is to improve the performance.

Do we have any work around where we can achieve both performance improvement and correct display of chart when boost is activated for our chart?

**Comment by cvasseng** [comment]
Yes - the latter part of previous my answer should give you both performance and expected results. You won't get grouping (i.e. no overlapping) when boost is enabled as this is not supported. So the key is to only enable boost when the point density is high, since the grouping is less important visually then, and instead using the fact that when the point density falls below the set threshold (`boostTreshold` on `series`), boost is deactivated. In other words, boost is disabled dynamically (and automatically if setting `boostThreshold`) when the user zooms. This will be performant since there will be less points to draw for the SVG renderer at that point, and grouping will look as you expect. 

You can see what this looks like in [this fiddle](https://jsfiddle.net/cvasseng/7dbsjLfb/1/): zoom by dragging the mouse vertically over the area you want to zoom into. You'll see that boost is disabled when there are less than 5000 points in the series (keep zooming - visually this transition happens when the bars are no longer 1 pixel wide). Notice the `boostThreshold` setting on series. 

It's worth noting that boost is made to deal with thousands/hundreds of thousands of points, or hundreds of data series. If your dataset has fewer points, your milage may vary. So if that's the case (e.g. if the fiddle in your OP is the full dataset), please post your full configuration including data, and we'll see if we can find another solution for you.

**Comment by SrinivasGit049** [comment]
We tried with following option
boost: {
		seriesThreshold: 20
	 },
 series: [{
		boostThreshold: 10									
		},
		]
Note:Our data value is passed dynamically for series.

We have more than 20 series in our chart and each data se/array is having more than 10 elements.
Now boost.js activated but graphs are not appearing properly

I tried 
boost: {
		seriesThreshold: 20
	 },
 series: [{
		boostThreshold: 1000									
		},
		]
But this also doesn't work i.e boost.js activated but charts are not coming properly

**Comment by cvasseng** [comment]
Both does configurations will activate the boost for the whole chart, i.e. zooming in etc. does not transition the chart into the svg renderer. `boostThreshold` sets it so that it's boosted when the amount of points exceeds the number set, in which case the boost is applied to that series only, while`seriesThreshold` sets it so that the whole chart is boosted once the number of series exceeds the number set. So if your data has more than 20 series always, and `seriesTreshold` is set to `20`, it will always boost regardless of what `boostTreshold` is set to. 

Try setting `seriesTreshold` to a number greater than the amount of series you have, and enabling zoom, while setting `boostTreshold` to e.g. 100 or 1000 depending on how many points you have. You want it to be set high enough that the SVG renderer takes over once the point density drops, but high enough that it boosts when it starts to hurt for your setup.

**Comment by SrinivasGit049** [comment]
But I wanted both Boost.JS to be activated and charts to display correctly.By your above solution charts will come properly but boost.js will not be activated so charts display performance is slow
