### ISSUE TITLE
Bug with 3d depth and frame showing

### ISSUE THREAD

**Issue by trittberg** [highcharts/highcharts#6628]
#### Expected behaviour
When the 3d depth value is changed with a frame showing, I expect only the chart depth to change.

#### Actual behaviour
When the 3d depth value is changed with a frame showing, the frame's "back" depth also stretches by depth.

#### Live demo with steps to reproduce

To the "Active Angles" fiddle at:
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/3d-column-interactive/

add the following code to the options3d object:
frame: { 
    bottom: { color: '#C0C0C0' },
    side: { size: 1, color: '#C0C0C0' },
    back: { size: 1, color: '#D0D0D0' }
}
Run the fiddle, then slide the "depth slider" and boom, a "thick brick" for a back frame.
It looks like the "frame.back.size" value is affected by the "options3d.depth" value.

#### Affected browser(s)
Edge, Chrome, Firefox.

**Comment by pawelfus** [comment]
Thank you for reporting this!

**Comment by Izothep** [comment]
Hi!

Thank you for reporting this issue. 

I don't think this is a bug with Highcharts-3d module - it looks to be related directly to small issue with our demo. 

Using  `this.value` will return a String instead of a Number. This affects depth calculation and is causing an effect of "too wide back side". It should be simple issue to fix, using parseFloat() or parseInt() methods.

Fixed demo: http://jsfiddle.net/grs6ctpk/
