### ISSUE TITLE
exporting error with IE8, Highcharts 5.0.10

### ISSUE THREAD

**Issue by zhy1stgg** [highcharts/highcharts#6643]
![snipaste_20170426_140551](https://cloud.githubusercontent.com/assets/6829290/25420238/c7c93b28-2a89-11e7-87e2-60b21887d174.png)

![snipaste_20170426_140948](https://cloud.githubusercontent.com/assets/6829290/25420241/cbff354e-2a89-11e7-88e0-ed1fa68a46db.png)

**Comment by KacperMadej** [comment]
Thank you for reporting about the issue. Here's more info about the problem:

****Behavior:****
Exporting throws multiple errors: `'element.ownerSVGElement' is null or not an object  highcharts.js, line 52 character 488` for `highcharts.src.js` the error is as: `  'element.ownerSVGElement' is null or not an object  highcharts.src.js, line 3643 character 21`. The problem is visible also when running Highcharts from master github branch.

****Demo:****
Could be recreate using Highcharts demo: https://www.highcharts.com/demo/line-basic

****Affected browsers:****
IE8

**Comment by TorsteinHonsi** [comment]
Closed by 89b8e2cdaa4ffd7c1a1455262af3c903eed17f6a
