### ISSUE TITLE
Plotband rendering behavior is different depending on Highcharts.js or Highstock.js

### ISSUE THREAD

**Issue by codechamploo** [highcharts/highcharts#6665]
#### Expected behaviour
The rendering is the same for both the highcharts and highstocks.
In the example fiddle(s), either the plotband renders across the whole entire chart or just the axis (the axis height is less than the chart height).

#### Actual behaviour
The example fiddle(s) show the plotband rendering exhibiting different behaviors.

#### Live demo with steps to reproduce
This one uses highcharts.js
http://jsfiddle.net/qu5ekcwu/

This one is the same as above but using highstocks.js
http://jsfiddle.net/a0ws7g7v/

#### Affected browser(s)
Chrome Version 58.0.3029.81 (64-bit)

**Comment by sebastianbochan** [comment]
Related with https://github.com/highcharts/highcharts/issues/6644

**Comment by TorsteinHonsi** [comment]
The demo uses the [yAxis.height](http://api.highcharts.com/highstock/yAxis.height) option, that is implemented for Highstock in order to display data in different panes. In Highcharts it is [not officially supported](http://api.highcharts.com/highstock/yAxis), though it mostly works. But the plot bands and plot lines is one area where it is not fully supported.
