### ISSUE TITLE
Boost: inverted chart with 10+ series causes an error

### ISSUE THREAD

**Issue by onemenny** [highcharts/highcharts#6669]
Boost module throws an error when drawing bar chart.

highcharts.src.js:855 Uncaught TypeError: Cannot create property 'moveTo' on boolean 'false'
    at H.wrap (https://code.highcharts.com/5.0.9/highcharts.src.js:855:25)

See this fiddle: https://jsfiddle.net/onemenny/d8sh8q5u/
If you remove the boost module importing, or set a high threshold - everything works. 

Expected - JS error should not be thrown

**Comment by KacperMadej** [comment]
Thank you for reporting about the problem.

The real problem here is as in the title I have edited - while using boost module inverted chart with 10+ series causes an error in browser console:
`VM1065 highcharts.src.js:900 Uncaught TypeError: Cannot create property 'moveTo' on boolean 'false'`
(for Highcharts version 5.0.11)

https://jsfiddle.net/d8sh8q5u/4/

**Comment by cvasseng** [comment]
The exception was fixed in 5.0.14. Note that bar charts are not directly supported in the current boost module - The workaround in master and `<=5.0.14` is to use `column` charts and to set `chart.inverted = true`.

Bar chart support was added in 912beba0e1b3c5eb5772547acf7899b78ff0ece6, which will be part of the next release.
