### ISSUE TITLE
Charts are broken because of explorting.js v5.0.11

### ISSUE THREAD

**Issue by sergey-alekseev** [highcharts/highcharts#6678]
I have `<script src="https://code.highcharts.com/modules/exporting.js"></script>` included into the HTML page.

#### Expected behaviour

Previously https://asoft.co/shopify-apps/store-analysis showed charts along with the exporting feature.

#### Actual behaviour

Now it's broken and every chart shows `Error Loading Chart: E is not a function`. 

```
Uncaught TypeError: E is not a function
    at t.Chart.A.renderExporting (https://code.highcharts.com/modules/exporting.js:26:193)
    at t.Chart.<anonymous> (https://code.highcharts.com/modules/exporting.js:26:322)
    at t.Chart.<anonymous> (https://asoft.co/assets/application-d4bea229d9a13f8e89d3a018946bea972df9a4f86b711960d07c443d895c882e.js:12:23715)
```

#### Live demo with steps to reproduce

https://asoft.co/shopify-apps/store-analysis

#### Affected browser(s)

Mac OS X 10.12.4 64-bit:
- Opera 44.0.2510.1218 
- Chrome 58.0.3029.96
- Safari 10.1 (12603.1.30.0.34)
- Firefox 45.0.2

Charts are rendered without errors if I remove `<script src="https://code.highcharts.com/modules/exporting.js"></script>`.

**Comment by TorsteinHonsi** [comment]
Thanks for writing!

You're loading the export module for Highcharts v5.0.11, but you're probably not loading Highcharts.js version 5.0.11. However I can't tell, because your bundler has removed the license headers in https://asoft.co/assets/application-d4bea229d9a13f8e89d3a018946bea972df9a4f86b711960d07c443d895c882e.js. 

To comply with our license, please set up your bundler to preserve license headers. To fix the issue, make sure highcharts.js and exporting.js are the same version.

**Comment by sergey-alekseev** [comment]
@TorsteinHonsi got it, thanks.
