### ISSUE TITLE
Bubble Charts Click Events

### ISSUE THREAD

**Issue by avinashara** [highcharts/highcharts#6705]
#### Expected behaviour
Click Event should be fired on click  of bubbles in bubbles chart in plotOptions.
```js
plotOptions: {
    series: {
      cursor: 'pointer',
      events: {
        click: function(event) {
          alert("Bubble Chart event fired!!");
        }
      }
    }
  }
```
#### Actual behaviour
Click event is not working.

#### Affected browser(s)
Google Chrome Version 57.0.2987.133 (64-bit)

**Comment by KacperMadej** [comment]
Thank you for reporting about the issue.
This is a regression (was working in version 5.0.10) caused by a halo blocking events. Demo: http://jsfiddle.net/jew5hhtu/2/

Steps: click on point's halo and in point, but out side of the halo to see the difference

Workaround: disable halo - http://jsfiddle.net/jew5hhtu/3/
or use the last working version 5.0.10 - http://jsfiddle.net/jew5hhtu/4/
