### ISSUE TITLE
Unexpected navigator in IE8

### ISSUE THREAD

**Issue by zhy1stgg** [highcharts/highcharts#6725]
#### Actual behaviour
![snipaste_20170515_101219](https://cloud.githubusercontent.com/assets/6829290/26040313/ba9c54cc-3956-11e7-8a3a-09be12f94421.png)

#### test case 
demo download from you zip file

#### Affected browser(s)
IE6, IE7, IE8

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting about the problem.

The issue is with VML and the `highcharts-navigator-mask-outside` class of a shape not being transparent. 

If the visibility of the element is toggled (as in the image below) then events for the element are lost, so this is not a good solution.
![oldie_vml_stock](https://cloud.githubusercontent.com/assets/8960408/26054480/fadb8434-396c-11e7-8b8b-a924f9bb5f4c.jpg)

**Comment by zhy1stgg** [comment]
thanks
