### ISSUE TITLE
X-Axis Labels format changes on zoom

### ISSUE THREAD

**Issue by kirtiesl** [highcharts/highcharts#6731]
http://jsfiddle.net/jugal/gwamsh77/
Referring to this example if I set zoomType: 'x' , zooming chart adds random points after month names.Please suggest how to resolve this issue

**Comment by pawelfus** [comment]
Hi @kirtiesl 

Thank you for reporting this issue. If you have fixed number of categories, you can set `xAxis.min` and `xAxis.max` to prevent zooming outside the extremes. Demo: http://jsfiddle.net/gwamsh77/11/

**Comment by kirtiesl** [comment]
My categories are not fixed. It depends upon the json data we get from server

**Comment by pawelfus** [comment]
Another workaround is to use `categories: []` instead of `type: 'category'`, demo: http://jsfiddle.net/gwamsh77/13/

**Comment by TorsteinHonsi** [comment]
It's a bug, `type: 'category` should be treated the same as `categories: []`. Debugging so far points to the `adjustForMinRange` function, where the `axis.minRange` on [this line](https://github.com/highcharts/highcharts/blob/v5.0.11/js/parts/Axis.js#L879) is true in one case and false in the other.

**Comment by kirtiesl** [comment]
Will this bug be resolved soon or any other workaround is possible?

**Comment by TorsteinHonsi** [comment]
Thanks for your patience! The fix will be part of the next maintenance release, scheduled next week.

**Comment by suganya-suvadi** [comment]
Hi, I still see the issue using version 5.0.12 - https://jsfiddle.net/xu7Ltt6d/2/. Could you let me know if there is an option I am missing?

![category x-axis](https://user-images.githubusercontent.com/19615498/27693191-57d870d6-5d06-11e7-841d-6f8bce3ab40c.gif)

(Just to be confirm - my x-values are strings though they look like dates) 

The labels are also messed up on zooming out to the original limits. And thanks, @pawelfus! Setting "categories" does fix this. I was wondering if we can expect a fix for when the x values are fed in through data and xAxis.type is set to be "category".

**Comment by gmorris2** [comment]
I am having the same issue as @suganya-suvadi with zooming in/out breaking the axis labels and causing data to disappear. I updated the fiddle to look at the latest version (6.0.4) to demonstrate the issue is still occurring.

https://jsfiddle.net/v4cek779/1/

I am using drilldown in my charts as well so setting the categories causes further issues I'd like to avoid if possible. Is there another workaround for this?

**Comment by pawelfus** [comment]
Hi @gmorris2 

It's a separate issue, reported as #5857 - could you set `cropThreshold` to a higher value, like suggested in the #5857 issue?

**Comment by gmorris2** [comment]
@pawelfus That solved my issue! I am using AJAX-retrieved JSON data to fill my series so I simply set `cropThreshold` to `data.length` and my issue disappeared. Thanks!

**Comment by digambargurav** [comment]
Issue is still there.
Step to reproduce:
Zoom the chart at extreme level.
make legends off from x-axis.
now again zoom the chart, the random values are coming on x-Axis.

**Comment by pawelfus** [comment]
Hi @digambargurav 

Could you recreate issue in jsFiddle? Does setting the `cropThreshold` options resolve the issue?

**Comment by saqebkhan** [comment]
<img width="846" alt="image" src="https://github.com/highcharts/highcharts/assets/86913676/671766c7-8340-4e72-a0d4-0e4dd08732b5">

The issue is regarding the xAxis labels, they are overlapping each other, the xAxis in my case of dates, I also have Zooms in my app, when we select some filters for example the 90-day chart the first date is forced to come in without interval definition.

**Comment by karolkolodziej** [comment]
Hi @saqebkhan! Could you please elaborate and share your example so I can work on it?
