### ISSUE TITLE
Boost.js crashes with 10+ ohlc series

### ISSUE THREAD

**Issue by DamianoPantani** [highcharts/highcharts#6753]
#### Expected behaviour
Highcharts should display more than 9 ohlc / candlestick series when using boost.js

#### Actual behaviour
It crashes at 'translate' function, acts like it couldn't invoke parent's (column) translate function.

#### Live demo with steps to reproduce
http://jsfiddle.net/obfrgvax/
See console log for stack trace. It starts to working when you:
- remove boost.js
- comment out one of serie (leaving less than 10)
- don't use ohlc / candlestick series at all (e.g. if there are 12 line series and one ohlc it crashes same way)

#### Affected browser(s)
Pretty much each one.

**Comment by cvasseng** [comment]
Boost does not support OHCL/Candlestick series at this time. 

It fails after 9 series because >9 is the default threshold for when the boost kicks in. So the boost, in your case, is not active until you reach 10 series.

Add:
    
    boost: {
       seriesThreshold: 999 // Number of series before boosting the whole chart
    },
    series: [{
        boostThreshold: 99999 // Number of points before boosting on a series-level
     },
     ...
    ]

To the chart in question to disable boost for it if you have more charts on a given page, and want to boost some of the charts. We'll be adding a cleaner way to disable boost on a chart-to-chart basis in an upcoming version.

**Comment by TorsteinHonsi** [comment]
Wouldn't it make more sense if only the boost-enabled series counted towards the seriesThreshold?
