### ISSUE TITLE
Updating fill opacity on chart with many series is slow

### ISSUE THREAD

**Issue by Rashaine** [highcharts/highcharts#6757]
#### Expected behaviour
Updating the series fill opacity in an area chart should be doable without needing to redraw the series and therefore should only take a few milliseconds.

#### Actual behaviour
Updating the series opacity via series.update({fillOpacity:value}) is very slow(2 seconds) when many series(100+) are being updated. However updating the elements by directly setting the fill on the DOM element is very fast(10 ms). e.g. series.area.element.setAttribute("fill", "rgba(127, 127, 125, .5"). I can perform this optimization outside of Highcharts however it requires reaching into the series object and this seems like something that Highcharts should do.

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Please set redraw flag as false (in the update function) and then redraw whole chart only one time (chart.redraw()).

Demo:
- http://jsfiddle.net/7expwu65/

Time: 820ms in Chrome.

If problem still appears, please update my demo with your code for the further debugging.

**Comment by Rashaine** [comment]
Right, i'm doing the delayed redraw just forgot to specify in my code snippet. 820ms is way too slow and updating the element directly takes less than 1ms. I updated the snippet to match our use case. 

http://jsfiddle.net/7expwu65/2/

set the useDirectUpdate flag to true to directly update the element, or set it to false to update through series.update(). Note that updating through series.update is very slow and choppy while updating the element directly is very fast and fluid.

**Comment by TorsteinHonsi** [comment]
The problem is the whole architecture of `Series.update` - in order to make sure all options are updated correctly, it destroys the series item and creates a new one, with new graphics, paths and everything.

In situations like this it would ideally pick just the SVG attribute it needed to change, and do that. The problem is that this would require a much more complicated implementation, in order to determine how much we needed to change for each and every option, in addition to how each option affected others.

For now, when performance is critial, I recommend that you stick with the workaround.
