### ISSUE TITLE
Tooltip shape that changes size has strange shape when hovering over points.

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#6775]
#### Expected behaviour
No strange line.

#### Actual behaviour
Strange line pointing nowhere shows while hovering over different points when tooltip size changes.

#### Live demo with steps to reproduce
http://jsfiddle.net/y2ta0gpt/

Hover between points to see the strange tooltip while it moves from one point to another.

![tooltip-bad-shape](https://cloud.githubusercontent.com/assets/8960408/26546428/38dcaf58-446a-11e7-9715-837ee2d6d1c9.jpg)

**Comment by TorsteinHonsi** [comment]
The connector appears in the callout symbol when the anchor point is not directly perpendicular to any of the sides of the box: http://jsfiddle.net/y2ta0gpt/1/

In case of the tooltip, this appears during animation.

**Comment by sebastianbochan** [comment]
I think that the problem is that callout draw an extra line when move between points, but user would like to keep "arrow" in each point.

![calout](https://user-images.githubusercontent.com/2115686/27796046-dc817df0-6008-11e7-8f6e-924cbe9ad05a.gif)

As a workaround, you can disable arrow by setting shape as rect.

Demo:
- http://jsfiddle.net/xta8ukx5/

**Comment by TorsteinHonsi** [comment]
This [simple connector](https://github.com/highcharts/highcharts/blob/v5.0.12/js/parts/SvgRenderer.js#L3170-L3178) was added together with split tooltips, to better visualize which point the label belonged to. It looks like we should have a mechanism or extra option to make sure it is not applied when animating, or maybe on the non-split tooltip.
