### ISSUE TITLE
Heatmap extra lines in the chart.

### ISSUE THREAD

**Issue by yoisel** [highcharts/highcharts#6783]
I was considering **not** using boost with heatmap as a workaround for [an issue with firefox](https://github.com/highcharts/highcharts/issues/6751), then I realized that even without boost the heatmap chart does not render properly on this browser.

#### Expected behaviour
Heatmap should display the chart the same way in all browsers

#### Actual behaviour
In Firefox, heatmap is adding extra lines to the chart

#### Live demo with steps to reproduce
https://jsfiddle.net/f64zc7rv/2

#### Affected browser(s)
Firefox (tested on Linux and Windows)

**Comment by pawelfus** [comment]
The same result on Firefox (OSX). Setting `shapre-rendering` to be for example `optimizedSpeed` will give the same results: https://jsfiddle.net/f64zc7rv/3/

```
.highcharts-point {
  shape-rendering: optimizeSpeed
}
```

**Comment by KacperMadej** [comment]
For styled mode `stroke-wdith` in CSS must be used instead of `borderWidth`. It's zero anyway, so no change here.

Minimal demo (tested on FF/Win10): https://jsfiddle.net/ko23wjx1/

Workaround set `borderWidth` to 1. Example for testing: https://jsfiddle.net/ko23wjx1/1/

For styled mode this workaround will not work because colorAxis is not setting `stroke`. Workaround for styled mode with additional wrapper to overcome that problem: https://jsfiddle.net/3a2j89k7/

**Comment by Denyllon** [comment]
Also reproduced on Chrome browser (v69.0.3497.92) and OSX (v10.13.6).

**Comment by pawelfus** [comment]
*Internal note:*
Works fine for me on Chrome (Version 69.0.3497.92 (Official Build) (64-bit)) + OSX (10.13.6) (FF still looks broken).

**Comment by TorsteinHonsi** [comment]
I think it is a case of subpixel rendering inside iframes in Firefox. It is and old issue that we haven't found a workaround for. The good new is that it happens only inside frames. In a standalone page it looks good: https://jsfiddle.net/ko23wjx1/show

Related comment:
https://github.com/highcharts/highcharts/blob/f5bbfee12d24fee1f0f063941d649d80eec04c9e/js/parts/SvgRenderer.js#L2581-L2587
