### ISSUE TITLE
x-axis category with string doesn't draw line chart correctly

### ISSUE THREAD

**Issue by MartinJLee** [highcharts/highcharts#6812]
#### Expected behaviour
With x-axis category number
https://jsfiddle.net/75z1f46r/2/

#### Actual behaviour
with x-axis category with string
https://jsfiddle.net/75z1f46r/1/

#### Live demo with steps to reproduce
https://jsfiddle.net/75z1f46r/1/

#### Affected browser(s)
not relate to browser compatibility

**Comment by pawelfus** [comment]
Hi @MartinJLee 

Thank you for the report! However, shouldn't this be the expected behaviour: https://jsfiddle.net/75z1f46r/3/ ? All categories are different, so each category should be created separately and second series should be rendered after the first one. Your first demo has strict `categories` but points don't have `x`-values, so `x`-values are incremented automatically. From [docs](http://api.highcharts.com/highcharts/xAxis.type):

> In a category axis, the point names of the chart's series are used for categories, if not a categories array is defined.

In your case, it's the best to use `categories: []` **with** `x` values to indicate which point belongs to which category, for example: https://jsfiddle.net/75z1f46r/4/

**Comment by MartinJLee** [comment]
Hi @pawelfus 

Thank you for the suggestion,
It seems your suggestion is a workaround for the issue.
I believe this is valid issue that need to be address, if we compare behavior with single series and multiple series

single series
https://jsfiddle.net/gzbLqqLu/2/

single series with categories commented out
https://jsfiddle.net/gzbLqqLu/3/

mutiple series
https://jsfiddle.net/gzbLqqLu/1/

I am expecting
all x-axis categories are plotted and series x value with string should map correctly to the plotted x-axis.

**Comment by KacperMadej** [comment]
Currently available features are presented and explained in Paweł's comment.
If you need a different functionality, then you could suggest an enhancement idea using userVoice.
https://highcharts.uservoice.com/forums/55896-general
The most popular ideas are getting implemented.
You could also contact technical support and ask for help with parsing data, so the chart will render as you want with data format you have. https://www.highcharts.com/support
