### ISSUE TITLE
First value of percent compare chart

### ISSUE THREAD

**Issue by slawekkolodziej** [highcharts/highcharts#687]
Open this demo: http://www.highcharts.com/stock/demo/compare when you change active range you can see, that the first values are not always 0%.

**Comment by sebastianbochan** [comment]
+1

**Comment by TorsteinHonsi** [comment]
> Looks like problem still appears.

Please provide a controlled reproduction. Fixed chart width and hard code X axis extremes to demonstrate the issue.

**Comment by giorgiosca** [comment]
http://www.highcharts.com/stock/demo/compare

This should work as it follows: when I click on YTD, the starting point (the one with the 0.0%) should be the closest day (with data) **before** the 1st of January. Not the 4th of Jan, as it is now.

Generally speaking, if I choose a date on the calendar (for example: 16.04.2016), and for that date there's no data (because it's a saturday/sunday/etc..), the chart should: 

1. pick up the closest day BEFORE the date entered in the calendar (for example friday), 

1. positioning itself on the leftmost part of the chart (i.e. no plotting at all before that point)

1. start plotting/comparing since that day.

The following is the current situation, showing the error:
![image](https://cloud.githubusercontent.com/assets/19406187/15318515/a196c410-1c26-11e6-8ffb-a6a2e722a53a.png)

Is there a way to accomplish this?

Thank you very much

**Comment by TorsteinHonsi** [comment]
A quick look at some other stock chart solutions indicates that what you describe is the standard way of showing comparison. 

Currently this isn't possible without extending/modifying Highstock. The logic for finding the comparison base is currently found in the [StockChart.js file](https://github.com/highcharts/highcharts/blob/v4.2.5/js/parts/StockChart.js#L511-L534). Instead of looking at the `processedYData` array we could look at the raw data starting with `cropStart`, but data grouping would pose a potential problem as we don't run grouping outside the data view.

**Comment by Tomefa** [comment]
I was stuck with this problem and all the performance calcul were wrong on YTD and some other one.

I modify directly the files highstock.src.js to correct the problem, here is my modification.
Before on line 24465:
`
            for (i = 0; i < length; i++) {
                compareValue = keyIndex > -1 ? 
                    processedYData[i][keyIndex] :
                    processedYData[i];
                if (isNumber(compareValue) && processedXData[i] >= series.xAxis.min && compareValue !== 0) {
                    series.compareValue = compareValue;
                    break;
                }
            }`
Patch :
`
            for (i = 0; i < length; i++) {
                compareValue = keyIndex > -1 ?
                    processedYData[i][keyIndex] :
                    processedYData[i];
                // Correctif to start the calcul with the first processedYData element. @tom
                if (isNumber(compareValue) && compareValue !== 0) {
                    series.compareValue = compareValue;
                    break;
                }
            }`

Can someone check if this will not break something in the past ?
Thanks

**Comment by TorsteinHonsi** [comment]
Yes, the xAxis.min test is there for a reason. It will break cases where there is more data to the left of the axis minimum, when the data is not cropped.

**Comment by Tomefa** [comment]
Ok but it resolve the problem on the demo when the data use for the pourcent calcul is on the left of the axis. Do you have on idea to make it work more properly by keeping the xAxis.min test but also by taking the right processedXData[i] data ?

**Comment by TorsteinHonsi** [comment]
I think this issue has a really simple fix now that we've agreed on how it is supposed to behave. Instead of checking that `processedData[i]` is above `xAxis.min`, we break out if `processedData[i + 1]` is above. If there is no more data to the left, it uses the first value. It works with grouped or ungrouped data. Fix coming up.

**Comment by iVibe** [comment]
Looks like problem is back for the last version (5.0.10)

**Comment by pawelfus** [comment]
Hi @iVibe, could you setup live demo with the issue? Or could you tell me the range I should choose in this demo: http://jsfiddle.net/231Lcj7k/ ?

**Comment by iVibe** [comment]
Hello @pawelfus, may be the Highstock initial behavior has changed and it is ok, when the first value in the chart with compare type 'percent' isn't 0%, because in the demo [ http://jsfiddle.net/231Lcj7k/](url) the series' first value isn't 0%. It behaves this way no matter range is set.

**Comment by pawelfus** [comment]
I think the first post is a bit misleading. [This post](https://github.com/highcharts/highcharts/issues/687#issuecomment-219674385) pretty well explains how it behaves at this moment. There used to be "0%" values in some cases.

Maybe you want the same result as #5748 ?

**Comment by iVibe** [comment]
In older version it behaved differently, that is why I was confused. Now I see, that this behavior is correct. Thank you @pawelfus for your answers and your time!

**Comment by romanukas** [comment]
@giorgiosca was right: "when I click on YTD, the starting point (the one with the 0.0%) should be the closest day (with data) before the 1st of January. Not the 4th of Jan, as it is now.

This is still not fixed...

**Comment by julindra** [comment]
Since version 6.0.0 there is an option 'compareStart' to set the first point of the visible range to be 0%.
check this out https://api.highcharts.com/highstock/plotOptions.series.compareStart
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/plotoptions/series-comparestart/
