### ISSUE TITLE
Errors because of Content Security Policy

### ISSUE THREAD

**Issue by maxvektor** [highcharts/highcharts#6884]
#### Expected behaviour
no csp violation

#### Actual behaviour
When I set csp rule to `style-src 'self'` i receive a bunch of errors in console
![2017-06-21_11-07-52](https://user-images.githubusercontent.com/5228778/27373684-ea2df9c4-5671-11e7-9fb2-6ccca7f4914c.png)

The issue is  inline styling in `buildText` and `css` functions. 
#### Live demo with steps to reproduce

jsfiddle has no CPS. Demo has no sense.

#### Affected browser(s)
I think it is all modern browsers. Checked in Chrome and Safari.

Is there a possibility to avoid a problem on my side?

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting about the problem.

Please check that you are using styled mode version of Highcharts as explained here: https://www.highcharts.com/docs/chart-design-and-style/style-by-css

Please create a minimal demo in JSFiddle, because we could check manually if there are any inline styles applied or we could apply CPS on the code you provide. This will be very useful for finding a source of the problem and further fix tests.

**Comment by maxvektor** [comment]
I am using highcharts: "^5.0.12" with react-highcharts: "^12.0.0".
Is there a way to include this styled mode via npm?

My steps to reproduce (one case):
1. Open a page with chart
2. Hover over any point on the line
3. Wait for popup

There is an open call stack:
![2017-06-21_19-58-48](https://user-images.githubusercontent.com/5228778/27397346-a2158c90-56be-11e7-816e-938f37b16ce1.png)

As you can see, it trows an error on chain textSetter -> buildText -> H.attr ([link to the line in highcharts code](https://github.com/highcharts/highcharts/blob/ad892cbe83a1b08628e6dc3761f1a80c835e58ad/js/parts/Utilities.js#L635)). In chrome devtools I see a property with value: `"style":"font-size: 10px"`. I think this is it. It is prohibited by `style-src 'self'` CSP rule.

Unfortunately as I've said JSFiddle has no SCP rules so any example is totally useless. But the situation itself without an error message is reproducible even on the example from the official site:
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/series-marker-enabled-false/

Leads to same changing of style attribute:
![2017-06-21_20-32-46](https://user-images.githubusercontent.com/5228778/27398051-2cf60acc-56c1-11e7-890e-be0f84348089.png)

I have also checked the examples from the link you have provided. It works indeed! Style attribute is never changed from code. So my main question is how to get it via npm?

**Comment by KacperMadej** [comment]
Styled mode files are in the same NPM package ('highcharts') as other files. To load styled mode you could use code like:

`import * as Highcharts from 'highcharts/js/highcharts';`

See in the node_modules/highcharts/js for other available files, like Highstock or Highmaps in minified (.js) or not compressed (.src.js) versions.

**Styled mode requires CSS**, so the basic styles are in node_modules/highcharts/css/highcharts.css - without this file (or other way provided styles for chart elements) everything will be painted black, so you will end up with a black rectangle in place of a chart.

Only styled mode is designed to pass SCP, so if you will have issues with the styled mode and SCP please let us know and the issue will be reopened.

**Comment by fernandops26** [comment]
@KacperMadej now the error with csp only is when drawing an label on hover a point.
See:
![error on hover](https://user-images.githubusercontent.com/11939055/29281303-16c8eefc-80e4-11e7-989c-ce6a444b476f.png)

**Comment by TorsteinHonsi** [comment]
@fernandops26 Thanks for reporting!

I set up this example and tried to look for inline styles in the generated SVG, but found none: http://jsfiddle.net/highcharts/pzyL4wxx/

Also, your error message indicates it may come from `fonts.googleapis.com`. Can you check out that? Does it still happen if you remove the Google Fonts from your web page?

**Comment by fernandops26** [comment]
@TorsteinHonsi font.googleapis.com also is allowed in the CSP configuration, but I have found in another issue your comment with a workaround, this I worked just fine for me.
https://github.com/highcharts/highcharts/issues/6173#issuecomment-276905452

**Comment by bbenezech** [comment]
This is very easy to fixed. `styledMode` sucks a bit for line charts customization.

Rational here: https://stackoverflow.com/a/57633533/264514

```
  Highcharts.wrap(SVGElement.prototype, "setAttribute", function(proceed, ...args) {
    if (args[0] !== "style") return proceed.apply(this, args);

    args[1]
      .split(";")
      .filter(Boolean) // remove empty strings
      .forEach((cssRuleString: string) => {
        const [ruleKey, ruleValue] = cssRuleString.split(":");

        switch (ruleKey) {
          case "font-family":
            this.style.fontFamily = ruleValue;
            break;
          case "font-size":
            this.style.fontSize = ruleValue;
            break;
          case "font-weight":
            this.style.fontWeight = ruleValue;
            break;
          case "fill":
            this.style.fontWeight = ruleValue;
            break;
          case "cursor":
            this.style.fontWeight = ruleValue;
            break;
          case "color":
            this.style.fontWeight = ruleValue;
            break;
          case "display":
            this.style.fontWeight = ruleValue;
            break;
          default:
            console.warn(`Could not set style ${ruleKey}, add me to the list`);
            break;
        }
      });
  });
```

**Comment by sebastianbochan** [comment]
Thank you for the suggestion.

**Comment by denchen** [comment]
Sorry to revive a closed topic, but I managed to get @bbenezech 's solution working, albeit more generally without needing `case` statements by converting the dasherized key into camelCase:

```jsx
Highcharts.wrap(SVGElement.prototype, 'setAttribute', function (
  proceed,
  ...args
) {
  if (args[0] !== 'style') return proceed.apply(this, args);

  args[1]
    .split(';')
    .filter(Boolean) // remove empty strings
    .forEach(cssRuleString => {
      const [key, value] = cssRuleString.split(':');
      const keyCamelCase = key.replace(/(-[a-z])/gi, function (_s, group1) {
        return group1.toUpperCase();
      });

      this.style[keyCamelCase] = value;
    });
});
```

And this solution _mostly_ works without having to go to Styled Mode, which I found too cumbersome to use, since I have a lot of dynamic styling that I apply to the charts (for instance, colors determined at runtime).

I just found one area this solution doesn't cover, which is the markers within a tooltip. I believe it's this function that's in violation:
https://github.com/highcharts/highcharts/blob/228b86df31ea1221965ee11a5587debd53bf4e71/js/parts/Html.js#L273-L281
My browser marked the `innerHTML` call as being the culprit.

I'm currently at a loss as to how to do a similar workaround as the `setAtttribute()` override above. Any thoughts?

**Comment by bbenezech** [comment]
Shunt the function with `wrap`, that's your only option.
I've had tons of CSP issues with `scrollingContainer`, I fixed them all manually like that.

Like you said "styled mode" doesn't cut it with dynamic colours and is therefor useless unless you are using static data.
Big industry players needs CSP + dynamic colors.
This ticket needs reopened and given a real afterthought.

**Comment by pawelfus** [comment]
Thanks! You are right, reopening the issue.

**Comment by bbenezech** [comment]
Hi @pawelfus !

If you want to tackle this :

Add strict CSP tag in test pages' `heading` : `<meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self';base-uri 'self';form-action 'self'" />`
Test

1. Fix all `setAttribute("style", <unallowed_style_string_that_needs_eval'ing>)` calls
2. Fix all `SVGElement#insertBefore(svgElement: SVGElement)` calls with `svgElement` containing style attributes on top node or descendants nodes (breaks on Firefox only)
3. Fix all `HTMLElement#appendChild(svgElement: SVGElement)` calls with `svgElement` containing style attributes on top node or descendants nodes (breaks on Firefox only)

(1) happens everywhere, and is easily fixed with my hack, and are probably very easy to fix throughout the codebase.
(2) and (3) happened to me on Firefox esp. when using `scrollablePlotArea`. https://github.com/highcharts/highcharts/blob/af5fdee7fecda154d0bec897788f17d6ee1aa477/ts/parts/ScrollablePlotArea.ts#L242 and https://github.com/highcharts/highcharts/blob/af5fdee7fecda154d0bec897788f17d6ee1aa477/ts/parts/ScrollablePlotArea.ts#L286 try to move dom elements containing style and cannot be fixed properly. You will need to build the dom right the first time instead of changing it later on with `appendChild` and `insertBefore`.

There are probably other problems that I did not encounter. Basically try all plugins with strict headers in Firefox (Chrome is more lenient, not sure if by design or Firefox off-spec ?) and fix all calls.

Good luck.

**Comment by pawelfus** [comment]
Thanks for all details @bbenezech ! Really appreciated.

FYI @TorsteinHonsi

**Comment by TorsteinHonsi** [comment]
Thanks. After a bit of debugging, it seems like skipping this code block prevents most of the warnings:

https://github.com/highcharts/highcharts/blob/c7e1976467a3b0e1620d44a414af2470716732b9/ts/parts/SVGElement.ts/#L1429-L1442

This code block takes care of serializing the CSS and applying it as an attribute for SVG element. The funny thing is that this itself seems to be a fix for a CSP issue, see [my comment two years ago](https://github.com/highcharts/highcharts/issues/7633#issuecomment-360120233). However, it seems like adding an element to the DOM after setting styles this way, still will trigger the error. As said above, "You will need to build the dom right the first time". And if we're not allowed to modify styling at run time, we would have to set up some trickery to cache the styles and apply them on add.

> Like you said "styled mode" doesn't cut it with dynamic colours and is therefor useless unless you are using static data.

@bbenezech You're aware of the `colorIndex` option set, right? The only thing styled mode can't do is actually tweening colors.

**Comment by bbenezech** [comment]
@TorsteinHonsi Worded simply, you definitely **can** apply styling at runtime (using `elem.style['attr'] = "value"`, instead of `elem.style = "attr: value;"` that needs runtime evaluation), but you **can't** move those elements after (Firefox will complain and remove the `style` attributes).

I personally can't easily use `colorIndex` because I need stable colors for an indeterminate number of series.

**Comment by TorsteinHonsi** [comment]
> I personally can't easily use colorIndex because I need stable colors for an indeterminate number of series.

Well if you have _n_ series you could have your script spit out CSS classes `.highcharts-color-{n}` and combine that with `colorIndex` and [colorCount](https://api.highcharts.com/highcharts/chart.colorCount), though it is obviously not the simplest solution.

**Comment by ivango1998** [comment]
> Fix
> 
> Rational here: https://stackoverflow.com/a/57633533/264514
> 
> ```js
>   Highcharts.wrap(SVGElement.prototype, "setAttribute", function(proceed, ...args) {
>     if (args[0] !== "style") return proceed.apply(this, args);
> 
>     args[1]
>       .split(";")
>       .filter(Boolean) // remove empty strings
>       .forEach(cssRuleString => {
>         const [ruleKey, ruleValue] = cssRuleString.split(":");
> 
>         switch (ruleKey) {
>           case "font-family":
>             this.style.fontFamily = ruleValue;
>             break;
>           case "font-size":
>             this.style.fontSize = ruleValue;
>             break;
>           case "font-weight":
>             this.style.fontWeight = ruleValue;
>             break;
>           case "fill":
>             this.style.fill = ruleValue;
>             break;
>           case "cursor":
>             this.style.cursor = ruleValue;
>             break;
>           case "color":
>             this.style.color = ruleValue;
>             break;
>           case "display":
>             this.style.display = ruleValue;
>             break;
>           default:
>             console.warn(`Could not set style ${ruleKey}, add me to the list`);
>             break;
>         }
>       });
>   });
> ```

Hello, hope you are doing great. Quick question, how do you know which style you should access. For example, in my console, i got a lot of error regarding the CSP header, but how do I know which property should I be editing through using the code above? Sorry I am new to highcharts and also CSP headers, thank you in advance :D

**Comment by KacperMadej** [comment]
Hi @ivango1998 

For technical support please see https://www.highcharts.com/blog/support/

Please create a live demo and describe the problem(s) you have in the chart. Make sure that you have set [styledMode](https://api.highcharts.com/highcharts/chart.styledMode) to `true`.

**Comment by Sherif-Ahmed** [comment]
Hello,
I also faced an issue regarding csp once I added the 3d javascript file

here is a  [demo fiddle](https://jsfiddle.net/SherifAhmedMahmoud/sry701bx/2/)
when I add the https://code.highcharts.com/highcharts-3d.js script 
there is a style added to the svg defs which fires the csp issue

![image](https://user-images.githubusercontent.com/6043905/146643680-a14de183-33d7-49af-b170-541f94888a29.png)

**Comment by KacperMadej** [comment]
Workaround - delete the problematic event: https://jsfiddle.net/BlackLabel/u12tn8qL/
Side effect: 3d columns will not have shaded sides.

**Comment by TorsteinHonsi** [comment]
I have created a draft PR for this in https://github.com/highcharts/highcharts/pull/16871. 

Inspected the cases above, but due to the complexity of the setup I am not sure every case is covered. It would be great if you would be able to test it. 

Files can be loaded from github.highcharts.com, like https://github.highcharts.com/bugfix/6884-csp/highcharts.js

**Comment by aashayjoshi** [comment]
Thanks. We will try to test these changes for all our usage of highcharts.

**Comment by mmerezhko-hv** [comment]
Hello everyone,
Do you have any plans to make this lib less noisy for the strict CSP?
I encountered one of the problems described above, namely the assignment of inline-styles for [Scatter plot](https://www.highcharts.com/demo/highcharts/scatter).

Examples of dangerous assignments are:
- class="highcharts-container" style="position: relative; ...."
- class="highcharts-root" style="font-family: ..."

Let me know

**Comment by TorsteinHonsi** [comment]
Hi @mmerezhko-hv, thanks for writing!

Can you share a setup where you encounter these problems? Here's a HTML page with CSP enabled, but it works without warnings:

```html
<html
<head>
	<title>Highcharts General Study</title>
	<script src="https://code.highcharts.com/highcharts.js"></script>
	<meta http-equiv="Content-Security-Policy" content="
	trusted-types
		highcharts
		default
		'allow-duplicates';
	require-trusted-types-for
		'script';
	style-src
		'nonce-highcharts';
">

</head>
<body>
	<div id="container"></div>
	<script>
		// Create the chart
		Highcharts.chart({
			chart : {
				renderTo : 'container'
			},

			series : [{
				data: [3,6,4,8,5,3]
			}]
		});

	</script>
</body>
</html>
```

**Comment by mmerezhko-hv** [comment]
Hi @TorsteinHonsi ,
Unfortunately, I can only reproduce locally. I tried to create a sandbox, but it doesn't apply the CSP rules correctly.
Here is jsfiddle output: The policy has been ignored.
https://www.highcharts.com/demo/highcharts/scatter?redirect-to-jsfiddle
Codesandbox simply does not display meta tags:
 https://codesandbox.io/p/sandbox/csp-meta-style-src-highcharts-wtt4y4?file=%2Fsrc%2Findex.mjs
