### ISSUE TITLE
Update marker symbol to null doesn't remove the symbol

### ISSUE THREAD

**Issue by royigoldi** [highcharts/highcharts#6908]
#### Expected behaviour
when update point marker with symbol null the symbol should disappear and regular marker should display.

#### Actual behaviour
nothing happened

#### Live demo with steps to reproduce
http://jsfiddle.net/7jupm0f9/3/

**Comment by JllyGrnGiant** [comment]
In your jsfiddle you have the line:
`chart.series[0].data[0].update({marker:{enabled:true,symbol:null}},true);`
You need to remove the `data[0]` portion because you set the symbol option on series, not the first data item.

So if you change it to
`chart.series[0].update({marker:{enabled:true,symbol:null}},true);`
it works.

Hope this helps.

**Comment by royigoldi** [comment]
no, i want to remove the symbol for specific point and continue display the symbol for other points.

**Comment by JllyGrnGiant** [comment]
Ah. My mistake.
The only way I was able to update the marker that way was to explicitly specify a shape, like:
`chart.series[0].data[0].update({marker:{enabled:true,symbol:'circle'}},true);`

Looking at the [documentation](http://api.highcharts.com/highcharts/series%3Cline%3E.data.marker.symbol) it says: 
> When null, the symbol is pulled from options.symbols.

I'm not sure what they mean by "options.symbols", but I wonder if it means that it looks at the value of series.marker.symbol when series.data.marker.symbol is set to null.

Sorry I couldn't help. I'll let someone else answer.

**Comment by sebastianbochan** [comment]
The simplest solution is disable marker, because finally it is your goal.

Demo:
- http://jsfiddle.net/d60v4h62/

**Comment by pawelfus** [comment]
@sebastianbochan I think the idea is to revert to the **default** marker, not to disable it. I am not sure if this is a bug, this is the order:

`point.marker` -> `series.marker` -> if still nullified, take symbol from default symbols

In other words, if `series.marker` will not be defined (or it will be null), then it will work fine with the upcoming version (5.0.13): http://jsfiddle.net/7jupm0f9/5/ But if `series.marker` will be defined, then it will be picked first.

I am not sure if this is a bug because for me it's more intuitive case: http://jsfiddle.net/7jupm0f9/6/ -
 all points should have symbol X, except for specific points, and setting `symbol` to null should restore **my symbol** not one of the default symbols.

**Comment by TorsteinHonsi** [comment]
I agree with Pawel it's not a bug. When setting the marker to null on the whole series, it works as expected: http://jsfiddle.net/7jupm0f9/7/
