### ISSUE TITLE
Series className is not applied for points

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#6910]
#### Actual behaviour
The classname is not applied for points, as a result we need to define className for each point to apply color.

#### Live demo with steps to reproduce
Demo:
- http://jsfiddle.net/gooxw3s1/

#### Affected browser(s)
All

**Workaround:**
Apply styles also for rects.

```
.redClass , .redClass > rect {
	fill: red;
	stroke: red;
}

```

**Comment by TorsteinHonsi** [comment]
This is how it is intended. There is no need to give each point the same class name, as we can target the points by the parent group. This is what "cascading" is "cascading style sheets" is about:

```css
.redClass .highcharts-point {
	fill: red;
	stroke: red;
}
```
http://jsfiddle.net/gooxw3s1/1/

**Comment by ihilgefort** [comment]
Hello Torstein, Sebastian,

this bug listed above was created based on an issue that I had raised with the support team, but not sure if the outlined details above are actually outlining the problem correct.

We are using HighCharts 5 and we tried to use a CSS to then overwrite the standard values from the HighCharts.css.

Scenario:
- Highcharts is loaded with the default highcharts.css
- we would like to change items - so we have a second CSS that is being loaded after the default.
- we then tried to overwrite the values using the classes in the second CSS file, but we noticed that it would only work when we do this:

.highcharts-series-1 *{
fill: #0080c0;
stroke: #7cb5ec;
}

As you can see we have to add the "*" - otherwise it is not working.

any advice ?

Regards
Ingo Hilgefort

**Comment by KacperMadej** [comment]
@ihilgefort There's no `.highcharts-series-1` in https://code.highcharts.com/css/highcharts.css, so the series are targeted differently. Here's a [demo for color change](http://jsfiddle.net/gh/get/jquery/1.7.2/highcharts/highcharts/tree/master/samples/highcharts/css/colors/) taken from [this documentation section](https://www.highcharts.com/docs/chart-design-and-style/style-by-css) - look for `.highcharts-color-{n}`

If you are not sure that a problem is a bug please contact support first - https://www.highcharts.com/support

**Comment by ihilgefort** [comment]
Hello everyone,

I will respond here as well as so far support has not been very helpful.

As outlined above already the .highcharts-series-1 is very clearly documented as part of the "Style by CSS" options. Just take the link you mentioned yourself and keep scrolling down and you will see the documentation for Style by CSS - but the classes are not in the CSS.

but far more important:
When we load a custom CSS after the HighChart.css we have to add the "*" in front of the CSS part - otherwise it is not working for highcharts classes and that should not be the case.

Can someone please look into this and actual give a proper response ?

Regards
Ingo Hilgefort

**Comment by pawelfus** [comment]
I think it works as described, let's take this example: http://jsfiddle.net/br3fv5nv/ as a base demo.

Color per rect is set on a rect element by `.highcharts-color-{color_index}` as @KacperMadej  said, not by `.highcharts-series-{series_index}`. That means setting color on `.highcharts-series-{series_index}` will not change anything that is set on a lower level (point/rect in this case).

Setting color as `.highcharts-series-0 .highcharts-point` [demo](http://jsfiddle.net/br3fv5nv/2/) or `.highcharts-series-0 rect` [demo](http://jsfiddle.net/br3fv5nv/2/) will work because it has the same priority as `.highcharts-color-{color_index}` and it was added later.

It's just how CSS works, consider this example: http://jsfiddle.net/br3fv5nv/3/ - if you change path `.box` -> `.box *` it will change the color too: http://jsfiddle.net/br3fv5nv/4/

**Comment by ihilgefort** [comment]
Here is the description from the "Style by CSS" area

.highcharts-color-{n}
**Colors used for series, or individual points** when colorByPoint is set, typically for pie charts etc. Each such color rule sets the fill and stroke to a default color in highcharts.css, then these properties may be overridden my more specific rules, for example for a common stroke on pies. The best place to set your own custom colors is by modifying highcharts.css/highcharts.scss, otherwise the strokes and fills must be set more specifically. Replaces colors.


.highcharts-series
General styling for all series. To apply styling to only a specific series type, you can define CSS rules for .highcharts-{type}-series, for example .highcharts-area-series or .highcharts-bar-series. **To make specific styling for one single series, you can define CSS rules for .highcharts-series-{n}** where n is the index, or give the series a className option.

So according to this, I should be able to use highcharts-series-0 or highcharts-color-0 but both should impact the series in the chart.

On the "*" topic - that not only applies to the series class but also other items and assuming we are using the same class, then that should not be necessary.

**Comment by pawelfus** [comment]
@ihilgefort let me quote you from `.highcharts-color-{n}`:

> The best place to set your own custom colors is by modifying highcharts.css/highcharts.scss, otherwise the strokes and fills must be set more specifically

This is how CSS works and how it's designed.

**Comment by KacperMadej** [comment]
@ihilgefort The code works correctly. This could be a misleading documentation, but now it's been explained, so this shouldn't be a problem for you. We'll try to improve the documentation. Thank you for providing quotes for the misleading documentation.

**Comment by ihilgefort** [comment]
@KacperMadej  @pawelfus  Changing highcharts.css is not an option in the scenario. There will be highcharts.css and then after that there will be a custom CSS that will use the same classes but different values.
For example : instead of using black it would use blue for the Title font.
so why do I then have to use the "*" to make it work.

**Comment by KacperMadej** [comment]
@ihilgefort Please read Paweł's comment again: https://github.com/highcharts/highcharts/issues/6910#issuecomment-318403748 I am not sure if this could be explain clearer. I wasn't suggesting changing the file highcharts.css but was informing you that to change styles from that file you need to provide a specific enough selector as Paweł explained. "so why do I then have to use the "*" to make it work." - please read Paweł's comment again and let us know if anything is unclear.

**Comment by ihilgefort** [comment]
Good morning @KacperMadej  @pawelfus 

here a few more details to proof my point that with the current GA release - which is what as a customer I am using - the CSS Style is not working / has issues.

I hope that his is now enough proof here that the CSS style is not working correct and that this is getting fixed quickly.


**Example 1:**

http://jsfiddle.net/gh/get/jquery/1.7.2/highcharts/highcharts/tree/master/samples/highcharts/css/colors/
refers with the source url to the development version - https://code.highcharts.com/js/highcharts.js 
This works fine - see the tooltip color being changed.

The GA for Highcharts JS v5.0.13, is https://code.highcharts.com/highcharts.js

When we replace the source url with the above (GA Release) on (replaced on http://jsfiddle.net/nsdevaraj/6fcgj8ux/) then It doesn't work fine (see Tooltip for Avocados).

**Example 2**

When you take this example you will also notice that on the first data series the CSS class is not highcharts-color-0 but instead it shows as highcharts-color-undefined (see attached image)

Working fine with their Dev Version:
http://jsfiddle.net/nsdevaraj/6fus0fgb/

Doesn't work with their GA Version:
http://jsfiddle.net/nsdevaraj/6fus0fgb/1/


regards
Ingo Hilgefort


![css_class](https://user-images.githubusercontent.com/16467677/28721106-136e6e04-7364-11e7-9647-d5ea91f8f326.png)

**Comment by TorsteinHonsi** [comment]
Hi Ingo,

The fundamental point here is that all of these are GA and v5.0.13. The file structure is as follows:

#### Styled mode
In styled mode, you need both a JavaScript file and a CSS file, because the inline styles are stripped away from the JS. Therefore, the files are served from a `/js` and `/css` directory respecively:
* https://code.highcharts.com/js/highcharts.js
* https://code.highcharts.com/css/highcharts.css

#### Non-styled mode
In this classic mode, you need only a JavaScript file, because the CSS is added inline. It should _not_ be combined with the CSS file from styled mode. The JS file is loaded from root:
* https://code.highcharts.com/highcharts.js

> When we replace the source url with the above (GA Release) on (replaced on http://jsfiddle.net/nsdevaraj/6fcgj8ux/) then It doesn't work fine (see Tooltip for Avocados).

So that happens because you combine the JS file from non-styled mode with a CSS file from styled mode.
