### ISSUE TITLE
Zones - wrong color of line series for specific yAxis extremes.

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#6928]
#### Expected behaviour
Zones should change both line and marker color. 

#### Actual behaviour
For some yAxis extremes (when line series is "squeezed") and for small zones values, zones change only marker color. It looks to be some rounding problem.

#### Live demo with steps to reproduce
http://jsfiddle.net/mcr6edhg/7/

Working example (chart with different yAxis extremes):
http://jsfiddle.net/mcr6edhg/8/

**Comment by TorsteinHonsi** [comment]
It is because of how the zones on the graph are implemented. We don't split the graph into segments and apply colors to each segment. Instead, we simply apply clipping rectangles on the coordinate system. This results in the graph being split in two colors if it renders along a zone border. You can see it clearer here: http://jsfiddle.net/mcr6edhg/10/.

_If_ we were to change this, we would have to do an entirely different approach to zones of the graph. Instead of applying copies of the whole graph with each clipping rectangle, we would have to compute the graph's subsections falling into each zone. This could potentially be complicated, especially for splines, but there may also be simple algorithms for it. On the upside, we would have a solution that worked equally for inverted charts and even polar charts.

**Comment by pawelfus** [comment]
@sharpau you can also try [Multicolor series](https://github.com/blacklabel/multicolor_series) plugin.
