### ISSUE TITLE
Bold button range selector

### ISSUE THREAD

**Issue by olivierscheffler** [highcharts/highcharts#6936]
#### Expected behaviour
All button from the range selector should be bold when selected.

#### Actual behaviour
When you active allButtonsEnabled : true, if one of the button is not automatic enable, it will not be in bold when selected.

#### Live demo with steps to reproduce
template: http://jsfiddle.net/6wxzju13/1/
This fiddle have in comment allButtonsEnabled. You see that 1Yr is not available.
If you remove comment from allButtonsEnabled and put in true, you will see that when you select 1Yr it will not be in bold.

#### Affected browser(s)
Chrome and Firefox and surely safari

**Comment by pawelfus** [comment]
Hi @olivierscheffler 

This is expected behaviour, buttons are highlighted/selected only when you have requested range available on the chart. [`allButtonsEnabled`](http://api.highcharts.com/highstock/rangeSelector.allButtonsEnabled) as per docs, gives a possibility to load more data than initially loaded, which can be used in [lazy-loading](https://www.highcharts.com/blog/news/48-loading-millions-of-points-in-highcharts/) charts.
