### ISSUE TITLE
How to publish after forking?

### ISSUE THREAD

**Issue by amit1911** [highcharts/highcharts#6942]
Hi, i forked this project and I would like to publish it to npm. Can someone tell me how can I do that? Is there any build script included in this project?

**Comment by pawelfus** [comment]
@jon-a-nygaard

**Comment by jon-a-nygaard** [comment]
Hi @amit1911 

> Is there any build script included in this project?

Since you have forked the project, you can build your own custom version of Highcharts by doing the following:
1. Install dependencies by running `npm install` and `npm install -g gulp`
2. Run `gulp scripts` to build all Highcharts distribution files
3. When build task is complete, the distribution files can be located in the `code` folder

> I would like to publish it to npm

We use a [seperate repository named highcharts-dist](https://github.com/highcharts/highcharts-dist) for distributing to npm.
In case you have not already found it, these official distributed files are published to a npm package named [highcharts](https://www.npmjs.com/package/highcharts).
To publish your own npm packages, you can find the process by looking at [npm's own documentation](https://docs.npmjs.com/getting-started/publishing-npm-packages)
