### ISSUE TITLE
Can't update axis events?

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#6943]
#### Expected behavior

Calling xAxis[0].update({ events: { ... } }); should update the event handlers such as afterSetExtremes.

#### Actual behavior

Event handlers don't change. In the demo, the original afterSetExtremes persists after we set `events` via `Axis.update`.

#### Live demo with steps to reproduce

http://jsfiddle.net/by3hryj1/

**Comment by sebastianbochan** [comment]
It looks like similiar issue like: https://github.com/highcharts/highcharts/issues/6538

**Comment by TorsteinHonsi** [comment]
Although probably a bug, it seems more logical to me to use `Highcharts.addEvent` directly when dealing with dynamic event handlers:

http://jsfiddle.net/by3hryj1/1/

**Comment by dandv** [comment]
Maybe I'm confused by the example, but `addEvent` *adds* the event handler, correct? As opposed to replacing it, as I'd expect `update` to do. I've modified [the example](http://jsfiddle.net/by3hryj1/2/) a bit and it shows that both the current event handler and the "removed" one are executed.

What I'm looking for is a way to completely replace an event handler.

**Comment by olejorgenb** [comment]
This bit me too. `update` adds the events, but doesn't unbind the previous ones. Created a nasty performance surprise :)

**Comment by TorsteinHonsi** [comment]
> Maybe I'm confused by the example, but addEvent adds the event handler, correct? As opposed to replacing it, as I'd expect update to do. 

Yes I agree that makes sense. But it seems to be in direct contradiction to #8161. Any thoughts @sophiebremer ?

Smaller sample: http://jsfiddle.net/highcharts/tewpcz8s/

**Comment by sophiebremer** [comment]
@TorsteinHonsi 
You should be able to remove the previous event by `Axis.update({events:{afterSetExtremes: undefined}});`, but it is not working (anymore).

**Comment by KacperMadej** [comment]
It looks like current behavior is to fire both old and new events. Master branch doesn't change anything as far as we (I use more "we" in this comment - I usually mean @pawelfus and me) could test this.

This is a bigger problem for wrappers for Angular / Vue / React where chart.update is used with all options each time. cleanRecursively could help in this case, but it looks like it will break more then it will fix - it changes new options object. cleanRecursively should create a new object - work more like a diff.

Currently updating a chart with defined axis events add new event over and over again on each update and is a potential leak memory issue.
@TorsteinHonsi

**Comment by bre1470** [comment]
@KacperMadej If we can not find a simple solutions for this, we have to implement the old behaviour and may not use test templates for unit tests with events (similar to cases with overloads). But this also means that you can **not** add additional series with events after the initial chart options, because existing ones get destroyed at the same time.

**Comment by pawelfus** [comment]
@bre1470 Could you create an example? For example in jsFiddle? The more details about the issue, the better solution later. Thanks!

**Comment by bre1470** [comment]
@pawelfus Sorry, I can not anymore. In the unit tests are no event tests using templates, so I have no idea, what exactly was going wrong back then. If you think events should be removed during an update, then an undo is fine for me. Just do not use the template system then. It relies on a proper update behaviour.

**Comment by KacperMadej** [comment]
`cleanRecursively` is added in v7.0.0 and is causing problems for Angular wrapper - removes unchanged options when full chart options are being passed. It took some time to find why chart options are vanishing because it caused errors in Angular that happened in HTML files. Anyway, just wanted to put this comment somewhere to save someone in the same situation as mine some time.

@TorsteinHonsi For now I could add some code that will create a copy of new options before options are passed into `chart.update` if you want to keep `cleanRecursively` as is. That way `cleanRecursively` will be pointless from Angular wrapper point of view, so an option to disable it could be nice. I understand that in normal usage most of the options are expected to be used in an update, but in case of wrappers for Angular/React/Vue all chart options are passed even for a smallest options change. Maybe this is a topic for discussion about a bigger change in the wrappers.

**Comment by TorsteinHonsi** [comment]
> in case of wrappers for Angular/React/Vue all chart options are passed even for a smallest options change.

Then it sounds to me like `cleanRecursive` is useful, as it saves us from processing and redrawing items that haven't changed.

> For now I could add some code that will create a copy of new options before options are passed into chart.update if you want to keep cleanRecursively as is. That way cleanRecursively will be pointless from Angular wrapper point of view, so an option to disable it could be nice.

I don't think it is pointless, because as said above, it saves processing time and resources if nothing changed. Probably the best approach is that you pass a merge of the options? Alternatively that we merge the new options internally instead of mutating the passed options. What do you think?

**Comment by KacperMadej** [comment]
@TorsteinHonsi 
Now when I read my last comment it looks like I have edited it to much before posting and removed important part that might have caused some confusion. Basically I wanted to run some sort of `cleanRecursive` that would create a copy of all options that should be updated instead of altering given options by deleting some of them, so after this the real `cleanRecursive` would be redundant.

`cleanRecursive` is altering passed options by deleting them. Full set of chart options is passed for any update for the wrappers, so the `cleanRecursive` would be great solution and very optimal if it were not removed unchanged options from `chart.update`'s `options` (to update) parameter. 

Let's give it a context: I have chart options with set chart's title and 2 series. I'm updating the chart options to add new series. Next Angular wrapper takes all chart options and passes it internally to `chart.update`. Title haven't changed, so it is removed. Later on I'm trying to change title.text, but title is undefined and I'm getting an error like `unable to access "text" of undefined"` in Angular with source pointing me (in this case) to HTML file that I cannot debug step by step to see what went wrong.

The options I can think of are:
1. Change the wrappers, so they will pass a copy of chart options into `chart.udpate` and Highcharts core will remain as is. (This is "pass a merge of the options")
Pro: No change in core,
Con: Required copy will hold all chart options, including series data and will be done for each and every update.

2. Change in the wrappers, so they will create a copy of chart options for reference and will run a variant of `cleanRecursive`, but it will produce a new options set that should be used for update.

```js
cleanR2(newOptions, oldOptions) {
   ... /* merge new into old and detect changes */ ...
   return diff_between_new_and_old_to_be_used_for_chart_update;
}
```
Pro: No change in core,
Con: Merging full options set on each udpate, & original `cleanRecursive` is not used, but still runs.

3. Provide an additional parameter for `chart.update` (that will be also passed into `series.update` and all functions where `cleanRecursively` will be used) to swap `cleanRecursively` with a merge or any other function that will not change `options` (to update) passed into `chart.udpate` - maybe something like code in No.2, but without merge.
Pro: More flexibility in core,
Con: ?

No. 3 is a variant of "merge the new options internally instead of mutating the passed options", but this would be options and controlled through function argument.

**Comment by dandv** [comment]
Looks like there's been some progress on this, though the internals of the discussion went over my head :)

In my original fiddle, the alert, which I had commented as "never triggers", does trigger, in fact multiple times - one time for each time the extremes have changed - as if the event handler is never removed.

**Comment by bre1470** [comment]
Triggering multiple times when providing callback functions is the originally behaviour, that was removed with Highcharts 7.0.0 and restored with Highcharts 7.0.3. We still have not figured out a solid way to cover both scenarios to replace existing callbacks and adding additional ones.

**Comment by TorsteinHonsi** [comment]
After reading this again, I realized that Axis does not behave like Series. In Series, events set by options are _replaced_, while events set on the class or the instance are not affected. PR coming up.
