### ISSUE TITLE
rgba colors, wrong alpha channel

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#6947]
#### Expected behaviour
rgba(0,0,0,0.) should be the same color as rgba(0,0,0,0.0) and rgba(0,0,0,0)

#### Actual behaviour
rgba(0,0,0,0.) applies black color on background instead of transparent.

#### Live demo with steps to reproduce
Demos (wrong):
- http://jsfiddle.net/957xu976/
- http://jsfiddle.net/nfd14Lok/

Native CSS (correct):
- https://jsfiddle.net/pncj5o2n/
- https://jsfiddle.net/uc8ge7e8/

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
I am not sure if this is a bug. `rgba(0,0,0,0.)` is an invalid CSS color. We could also use `rgbXXX(something)+else` and the result would be the same: http://jsfiddle.net/957xu976/1/ (according to the report, color should be solid red, it's "transparent" instead).

Solid black is default for SVG when color is invalid.

Native examples above 'work' because CSS color is not applied, it's simply filtered out by browser.

**Comment by sebastianbochan** [comment]
After deep debuging indeed it does not look like a bug, but I think that we should consider if transparent color should be applied, instead of black.

**Comment by TorsteinHonsi** [comment]
> I think that we should consider if transparent color should be applied, instead of black.

I agree that would be nice, but it also adds complexity because then we need to make absolutely sure the browser doesn't understand the color before we fall back to `none` or `transparent`. What we do now is to simply pass the string on for SVG to handle it, and it handles it by painting it black: http://jsfiddle.net/BhZjV/576/.
