### ISSUE TITLE
Stack labels not positioned properly on 3d column chart.

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#6959]
#### Expected behaviour
Stack labels should be aligned to the tops of the columns.

#### Actual behaviour
They stay in the same positions as they were on 2d chart.

#### Live demo
http://jsfiddle.net/scr2g8sz/

#### Affected browser(s)
All

**Comment by Izothep** [comment]
Thank you for reporting your issue. 

It looks to be related to: https://github.com/highcharts/highcharts/issues/3946

This issue is already solved on our developer branch. Example:
http://jsfiddle.net/scr2g8sz/2/

**Comment by davidarul** [comment]
Thank you for solved the issue.

But I have another issue with your fixes. Which is shows below image,
http://jsfiddle.net/scr2g8sz/3/

[url]https://image.prntscr.com/image/HqJQfDOGQfCrZWKOmEuFjQ.png[/url]

**Comment by Izothep** [comment]
Hi @davidarul, 

Thank you for information about your problem. I think that your issue is related to new "**hiding overlapped stackLabels**" feature (available on our github version). It should be possible to disable this feature using stackLabels.allowOverlap parameter.

Example:
http://jsfiddle.net/scr2g8sz/4/
