### ISSUE TITLE
boost - no tooltip for column

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#6974]
#### Actual behaviour
The tooltip is missing in main chart. When we zoom multiple times, it works.
Tooltip works properly with line series.

#### Live demo with steps to reproduce
Example:
- https://jsfiddle.net/rdnLgf35/

**Comment by TorsteinHonsi** [comment]
The underlying cause is that (normal, unboosted) column series have event handlers attached to the column elements themselves, which trigger the tooltip. But in boost mode there are no elements. So when entering boost mode we need to use the k-d-tree to trigger the tooltip.

@jon-a-nygaard @cvasseng

**Comment by pawelfus** [comment]
Works fine since v6: https://jsfiddle.net/BlackLabel/rdnLgf35/1/
