### ISSUE TITLE
Highcharts error #15 with polygon series added to HighStocks chart

### ISSUE THREAD

**Issue by pmalouin** [highcharts/highcharts#6989]
#### Expected behaviour
By nature, series of type 'polygon' cannot have their data sorted in an ascending order (over time). I do not expect to receive any warning/errors. But, the HighStocks chart seems to require that their series be sorted (see https://github.com/highcharts/highcharts/blob/a9f067ec111e0fd5a2229ef34f7cafd222d017d7/js/parts/DataGrouping.js#L565).

#### Actual behaviour
When loading the chart, a large number of errors are output to the console:
`Highcharts error #15: www.highcharts.com/errors/15`

This affects the performance of the page (large number of console.log statements). The polygon seems to be rendered correctly though and I have not seen any problem with using them in a HighStocks chart.

#### Live demo with steps to reproduce
https://jsfiddle.net/eyxj0c5z/1/

Look at the console, multiple errors are logged.

#### Affected browser(s)
At least Firefox and Chrome.

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting about the problem.

To make this issue more general: the problem is the same for scatter or any other series with sorting not required.

Minimal demo for scatter: https://jsfiddle.net/vLtc9xLx/

**Workaround**: do not use `stockChart` constructor and set series type in navigator to the same type as the main series (or other series that doesn't require sorting). 
Demo: https://jsfiddle.net/Lbnhb8nd/
