### ISSUE TITLE
JS error on writing new chart to a node that was originally detached.

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#7014]
#### Live demo with steps to reproduce

http://jsfiddle.net/hxqz2unk/1/

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
Regression since 5800b1b626149ca7518c7b09b336125a946b0b9a

**Comment by tpeyrard** [comment]
Hi,

just to let you know that this fix https://github.com/highcharts/highcharts/commit/c92a4d6618f26358d75516c89c8f1489bf54a957 (or the https://github.com/highcharts/highcharts/commit/5800b1b626149ca7518c7b09b336125a946b0b9a)  prevents users to use Highcharts in some Polymer elements because it plays with the DOM without taking into account the shadow doms...

It works fine with version 5.0.12.

**Comment by TorsteinHonsi** [comment]
Thanks for letting us know! I'm not too familiar with Polymer, can you help me demonstrate the issue so we can find a workaround? I tried this... https://jsfiddle.net/highcharts/2q3fqehz/178/

**Comment by tpeyrard** [comment]
I edited the script. I got the error #13
https://jsfiddle.net/2q3fqehz/179/

I don't know whether it can be fixed at the Polymer level.

**Comment by TorsteinHonsi** [comment]
Thanks, but that also fails with v5.0.12... https://jsfiddle.net/highcharts/2q3fqehz/180/

**Comment by TorsteinHonsi** [comment]
Here's a demo with Shadow DOM without Polymer. It works with the latest Highcharts, v5.0.14: http://jsfiddle.net/highcharts/cjxjp9ok/
