### ISSUE TITLE
Scrollbar - click on arrow wrong yAxis extremes

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#7015]
#### Live demo with steps to reproduce
Demo:
- http://jsfiddle.net/6zm1y8e2/

Steps to reproduce
1. click left arrow to the first point
2. click right arrow to the last point
3. do step 1.
4. negative value is not displayed, due to wrong dataMin parameter in yAxis.

![scrollbar](https://user-images.githubusercontent.com/2115686/28713555-c32e8862-738f-11e7-90dc-c6df036d64ae.gif)

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
*Internal note:* xAxis extremes at point 4 are min: 0, max: 5.999999999988 and points at x === 6 are out of visible range. Another demo - extremes are slightly over or under x values of edge points causing them to be visible, but not included in extremes calculations: http://jsfiddle.net/6zm1y8e2/1/

**1st problem:** after scrollbar manipulations the initial x axis range is altered due to rounding errors

**2nd problem:** due to column additional axis padding or point placement some points are in visible range, but are not included in extremes calculations (http://jsfiddle.net/6zm1y8e2/1/)
