### ISSUE TITLE
Tooltip stuck on first category when one series contains single value

### ISSUE THREAD

**Issue by magnushenning** [highcharts/highcharts#7016]
The issue occurs when one series of multiple series contains a single non-null value.

#### Expected behaviour
Tooltip should be able to follow the cursor along xAxis, across multiple series, with shared tooltip enabled.

#### Actual behaviour
Tooltip is stuck on first category on xAxis, refusing to follow cursor along xAxis. 

#### Live demo with steps to reproduce
http://jsfiddle.net/qco5vn8u/2/

#### Affected browser(s)
Chrome, Others?

![2017-07-28_14-44-35](https://user-images.githubusercontent.com/10730968/28717789-7b26cd36-73a3-11e7-872a-82d242f0106c.jpg)

**Comment by KacperMadej** [comment]
Hi,

This doesn't look like a bug because you are adding a custom code and the demo was not designed to work with multiple series in each chart. You could check if points are found to avoid the console error: http://jsfiddle.net/qco5vn8u/3/

In case tooltip is not shared first series will be active and used regardless of hovered chart part. In case of shared tooltip closes point in each series will be hovered, so first and only point of column series will be constantly visible in tooltip regardless of hovered chart part.

For questions, please use our other [support channels](https://www.highcharts.com/support). We use github as a bug tracker.

**Comment by magnushenning** [comment]
Thank you for a quick answer.

@TorsteinHonsi: In my opinion this is still an issue. Reading [this thread](https://forum.highcharts.com/highcharts-usage/sychronized-charts-2-lines-instead-on-1-for-each-graph-t33438/#p117427) one would get the impression that synced charts with multiple series should work. 

By modifying the example data on the first series (nulling out all but the first value) and simply removing the fixed tooltip positioning you instantly hit the issue: http://jsfiddle.net/7Lhsb00g/58/

I think a possible workaround could be to set the index of each series so that the first series always is the one with highest index of non-null xAxis value, still this is not an ideal approach.

**Comment by TorsteinHonsi** [comment]
As Kacper says, this is not an issue with the Highcharts core, but with how the synchronized charts are set up.
