### ISSUE TITLE
3D scatter chart incorrectly shows big values.

### ISSUE THREAD

**Issue by SergeyBorI** [highcharts/highcharts#7018]
#### Expected behaviour
Line connecting small positive value and next huge positive value should 'disappear' in the upper part of the chart. 

#### Actual behaviour
I intentionally set max of Y-axis to 10 to better show 'small' values,
but in this case huge positive values looks like huge negative values.

#### Live demo with steps to reproduce
https://jsfiddle.net/sergeybor/19cy050w/3/

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting about the problem. This might be caused by line series not being supported in 3D - a scatter type series with set line width is very similar to a line type series.

Another demo: http://jsfiddle.net/fof5nvnj/

Line for scatter series could be seen outside of any axis range.
