### ISSUE TITLE
Issue colors (api documentation)

### ISSUE THREAD

**Issue by pinkynrg** [highcharts/highcharts#7023]
I downloaded and imported HighCharts API on my db. Options "colors" should have `isParent == true` since it is a root element. To my knowledge isParent is set to false.

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting about the problem. `isParent` is set to false because the option is not a parent to any other settings. For example `plotOptions.column` has a parent (`plotOptions`) and is a parent (to column series options).

This doesn't look like a bug or a mistake. Could you provide more info or my explanation is enough to close the issue?

**Comment by TorsteinHonsi** [comment]
It is correct like it is, `isParent = false`. It doesn't have any children.

**Comment by pinkynrg** [comment]
Ok thanks I believe I might have confused the meaning (i thought it was meant like "isRoot" option opposite of "hasParent").

Thanks
