### ISSUE TITLE
Heatmap - Hovering over null values doesn't work with boost module on versions above 5.0.7

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#7048]
#### Expected behaviour

After hovering on point with null value tooltip should appear.

#### Actual behaviour

Nearest not-null point's tooltip apperars.

#### Live demos

v5.0.8 - Doesn't work: http://jsfiddle.net/kkulig/4utbqp93/
v5.0.7 - Does work: http://jsfiddle.net/kkulig/wvLwL7f0/

Current release version:
Does work without the boost module: http://jsfiddle.net/kkulig/tuy56brn/
Doesn't work with it: http://jsfiddle.net/kkulig/dh7xcb5f/

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting. The issue was clearly fixed, because it works with the current version.

**Comment by TorsteinHonsi** [comment]
According to the Highmaps API, the `nullInteraction` option is `false` by default, so we shouldn't see a tooltip unless we set it to true... http://jsfiddle.net/highcharts/tuy56brn/3/

**Comment by KacperMadej** [comment]
@TorsteinHonsi `nullInteraction` is only a part of Highmaps and the problem is visible in HC+heatmap+boost and not in HC+heatmap, so there's probably something in the boost, but I am unable to find the source.

**Comment by sebastianbochan** [comment]
+1

**Comment by cvasseng** [comment]
Including boost no longer breaks tooltips for heatmap in `bugfix` (ce210e06026b6d39b0bf8d54807e08bb84ca462c) - http://github.highcharts.com/bugfix/modules/boost.js.

They still do not work properly when actually boosting - still looking into that; but it no longer breaks unboosted heatmaps.

**Comment by raf18seb** [comment]
+1

**Comment by TorsteinHonsi** [comment]
We’ll have a closet look at this tomorrow.

**Comment by tommy19524** [comment]
Hello dear highcharts-dev team,

I was asked to share additional information since this bug has been forwarded from the highcharts forum. I'll put the preview jsFiddles here and the links to the initial forum posts below.

not-working fiddle example: 
https://jsfiddle.net/L90e3cbo/

including property for nullinteraction: 
https://jsfiddle.net/ju8cs1ka/

yesterdays forum post: 
https://www.highcharts.com/forum/viewtopic.php?f=9&t=41511&sid=80701ef48639897fbefe762b6f444b6c

initial forum post from november 2018: 
https://www.highcharts.com/forum/viewtopic.php?f=9&t=41253&p=144234&hilit=heatmap+null#p144234

Thank you very much in advance. Please let me know if you need further information.

Kind regards,

tommy19524

**Comment by TorsteinHonsi** [comment]
It's fixed now, please see https://jsfiddle.net/highcharts/7mzsvkrp/ for your demo with the fix applied.

**Comment by tommy19524** [comment]
Thank you very much!
