### ISSUE TITLE
Vanishing Column in bar chart when use setData

### ISSUE THREAD

**Issue by AnatolyPruchay** [highcharts/highcharts#7060]
Greetings!
I had a problem - when I call the setData method, one of the columns disappears in my bar chart.

https://jsfiddle.net/Pierre_Cardi/7wqrrd8h/

Could you tell me how to solve this issue?

**Comment by pawelfus** [comment]
Hi @AnatolyPruchay 

It doesn't work, because format for `setData(data)` is wrong. It looks like you copied over `series` config, but `setData()` requires `data` object from series. For example: https://jsfiddle.net/7wqrrd8h/1/

If you have any other questions, please contact with out [support](https://www.highcharts.com/support). We are using github issues as bug reports.

**Comment by AnatolyPruchay** [comment]
thanks
