### ISSUE TITLE
Polar: column series - pointWidth has rad value

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#7102]
#### Expected behaviour
Pixel precision for pointWidth or info in docs that for polar this is calculated differently.

#### Actual behaviour
The value is in rad.

#### Live demo with steps to reproduce
http://jsfiddle.net/kfgcj215/1/

**Comment by TorsteinHonsi** [comment]
Pixel precision in this case doesn't make sense, since it will be narrower near the center of the polar chart. 

The current behaviour is accidental, but useful I think. The only problem is that it uses radians, where other options like `startAngle` and `endAngle` uses degrees.

So the fix here will be to make `pointWidth` accept degrees in polar charts, and to add that information to the API docs.
