### ISSUE TITLE
Adjust navigator handles to be more flexible for styling

### ISSUE THREAD

**Issue by Ragazzo** [highcharts/highcharts#7124]
As for now, there is no way to fully customize navigator handles, since they are represented only with one `path` object. For example: I want my handles to be have 2 different colors, depending on what designer can draw. My suggestion is to add simple property for navigator cofiguration:

```javascript
{
    navigator: {
        handlesElementCount: 3, // any valid integer number
    },
}
```
Expected behavior:
Highcharts will create several `path` objects inside parent `path` object. For example now we have this:

```html
<path class="highcharts-navigator-handle highcharts-navigator-handle-left"></path>
```
After implementing this feature and taking into account for example `handlesElementCount: 3` we will have this:

```html
<path class="highcharts-navigator-handle highcharts-navigator-handle-left">
<path class="path-0"></path>
<path class="path-1"></path>
<path class="path-2"></path>
</path>
```
With this way we can style handlers much easier.

**Comment by pawelfus** [comment]
Hi @Ragazzo 

Thank you for sharing the idea! In Highstock 6, handles can be rendered as images (separately for left and right). You will be able to change not only the colors but also shapes.

**Comment by Ragazzo** [comment]
@pawelfus yep, I saw some plugins for Highstock4, but I am not really a big fan of using images, especially when you need really good customization. Can we also implement somethink alike this solution? Ofcourse this is only a proof of concept, but anyway, you got the idea :)

**Comment by pawelfus** [comment]
I am not talking about plugin, but a build-in feature.
 
Instead of image you could also use [SVG shape](http://jsfiddle.net/y6gkawx7/) (still, just one path), but aren't images more easier in use and customization (e.g. http://jsfiddle.net/y6gkawx7/1/ )? I don't think it will get into Highstock 6, but you can post your idea on [our UserVoice](https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api). If your idea will gather enough votes it may be implemented in the future.

**Comment by Ragazzo** [comment]
yep, I customized default path via css and `d` attribute. Well, it depends on the designer, anyway, lets see what we will have on Highstock6 in the end. Thanks for your feedback :)
