### ISSUE TITLE
useHTML: true VS useHTML: false

### ISSUE THREAD

**Issue by schneckentempo** [highcharts/highcharts#7126]
Some followup to #7092 
that was worked around with useHTML everywhere where text was used and lead to #7114 
which now is causing tooltips to be overlayed by data labels

Actually we do not want to use useHTML anywhere if evitable, but we now have to work around workarounds. I like to ask for a revisit of the special character and html tag handling when useHTML is actually false (default)

#### Expected behaviour
case without useHTML:
looking at name it should simply display whatever is put into the text - `& &amp; &lt;text 1&gt; <text 2>`

case with useHTML:
in my opinion when this option is set to true the input should be decoded if `&lt;`, `&gt;` or `&amp;` is used but also should display `&`, `<` and `>`. Text between `<` and `>` should be interpreted as html tag, while between `&lt;` and `&gt;` should not

#### Actual behaviour
case without useHTML:
looking at name  `&` and `&amp;` are shown correctly. `&gt;` and `&lt;` are decoded and `<text 2>` gets hidden because of interpretation as a tag

case with useHTML:
`&` and `&amp;` get displayed both as `&`, again `&gt;` and `&lt;` are decoded and `<text 2>` is also hidden

#### Live demo with steps to reproduce
with useHTML: http://jsfiddle.net/c392mf1q/2/
without useHTML: http://jsfiddle.net/c392mf1q/3/

**Comment by TorsteinHonsi** [comment]
Thanks, but I'm not sure I follow. I would expect this to work equally with or without `useHTML` so that switching between shouldn't affect how things are rendered:
* `&` renders as `&`.
* `&amp;` renders as `&`. 
* `&lt;` and `&gt;` are rendered as `<` and `>`.
* `<text in tag>` is interpreted as a tag and hidden.

This is how it works after the fix for #7092: http://jsfiddle.net/highcharts/c392mf1q/4/

**Comment by schneckentempo** [comment]
I would expect `<text in tag>` to be **not** interpreted as a tag and hidden if `useHTML: false`

**Comment by TorsteinHonsi** [comment]
Why would you expect different behaviour? To me that is counterintuitive, the ultimate goal should be that the SVG pseudo-HTML behaves identical to true HTML.

**Comment by schneckentempo** [comment]
But semantically a prop named `useHTML: false` indicates, that there is (no matter what) no html rendered, while `useHTML: true` indicates to me I have to take care about what I put in

**Comment by pawelfus** [comment]
Explanation of `useHTML` and general formatting rules can be found in our [docs](https://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting#html).

I agree with @TorsteinHonsi, the output should be consistent, it doesn't matter if we set `useHTML` or not. I am pretty sure it will be reported as bug shortly after the release if we change that.

**Comment by schneckentempo** [comment]
> The following tags are supported: <b>, <strong>, <i>, <em>, <br/>, <span>

I do understand, that this behaviour may be wanted, but not for definitely non html tags eg.:
`a < b and c > d` which would output `a  d` - this can't be a desired behaviour

**Comment by TorsteinHonsi** [comment]
> this can't be a desired behaviour

As far as I can see, `a < b` renders correctly in both cases: http://jsfiddle.net/highcharts/c392mf1q/7/

**Comment by schneckentempo** [comment]
http://jsfiddle.net/c392mf1q/9/

**Comment by TorsteinHonsi** [comment]
I've [fixed this case now](http://jsfiddle.net/highcharts/c392mf1q/10/). If you come across more cases of bad parsing please note them here and we'll consider them, but also keep in mind that we're not rebuilding a perfect HTML parser. For example, in true HTML the code `a <b and c> d` makes the `d` bold. Our HTML parser doesn't do that because it expects a closing `</b>`.
