### ISSUE TITLE
Tooltip missing in Boost column chart

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#7149]
#### Live demo with steps to reproduce
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/samples/highcharts/boost/column/

Regression since 3b4afbbde

**Comment by jon-a-nygaard** [comment]
Caused by `column.stickyTracking: false`, in combination that there seems to be no hover events on series in boost mode. (Will have to check if this is a fact).
In general, it might be a good idea to enforce `stickyTracking: false` in boost mode.

Potential workaround: set stickyTracking to be false, http://jsfiddle.net/jon_a_nygaard/vm7q4au6/

Also noticed that the default value of `plotOptions.column.stickyTracking`  is currently incorrect in the api (should be false): http://api.highcharts.com/highcharts/plotOptions.column.stickyTracking

**Comment by cvasseng** [comment]
I suggest we force it to be `true` - getting proper mouse events on boost is... not easy. @TorsteinHonsi?

**Comment by TorsteinHonsi** [comment]
Yes, that's fine.
