### ISSUE TITLE
Axis ticks change unexpectedly after Series.update() 

### ISSUE THREAD

**Issue by paulo-raca** [highcharts/highcharts#7151]
#### Expected behaviour
When I change the series, but don't modify the data range, the Axis ticks should stay at the same positions.

#### Actual behaviour

The tick interval changes unexpectedly.

#### Live demo with steps to reproduce

http://jsfiddle.net/59xfuepf/
- Click the button
- The tick interval on Y will change from `2` to `2.5`

I was only able to reproduce it with a ColorAxis, but it might be a random coincidence.

#### Affected browser(s)

Chrome 60

**Comment by TorsteinHonsi** [comment]
This happens in some cases. It is because each axis needs to take the other into account - so we draw the axes in one or two iterations. For example, if we first lay out the ticks of the X axis, then the Y axis, the Y axis may have very long ticks that make the X axis shorter, so we need to lay out the X axis again to respect the `tickPixelInterval`.

In this particular case, the Y axis is first laid out in a temporary length where it doesn't know that the X axis has a title. So when you click Update, it has actually become shorter.

This logic is handled in https://github.com/highcharts/highcharts/blob/v5.0.14/js/parts/Chart.js#L1729-L1755

Particulary, we redo the horizontal or vertical layout if the axis length changes with a certain factor. By reducing that factor it fixes your case, but the penalty is poorer performance.

**Comment by TorsteinHonsi** [comment]
A possible solution would be to make those thresholds configurable, though I think even that wouldn't solve the issue completely.

**Comment by paulo-raca** [comment]
Maybe loop until they become stable? (I guess there is the risk that they'll never be stable?)

Thanks for looking into it. If you think  this is how it is supposed to work, feel free to close.

**Comment by TorsteinHonsi** [comment]
> Maybe loop until they become stable?

That would make them consistent, but it would also come at a performance cost. Maybe as an option though...

**Comment by KacperMadej** [comment]
Looks stable in version 6.1.4 - at least for the provided demo.
Closing as resolved.

If you have more info or a live demo showing the problem then please post a comment with more info and the issue will be reopened.
