### ISSUE TITLE
Map zooming very laggy with scroll wheel

### ISSUE THREAD

**Issue by callumacrae** [highcharts/highcharts#7165]
#### Expected behaviour

When you scroll, the map should zoom in or out smoothly without delay.

#### Actual behaviour

Scrolling is very, very laggy. Especially when zooming out, it can take a second or two to even start zooming.

#### Live demo with steps to reproduce

http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/demo/all-maps/

#### Affected browser(s)

Latest chrome

**Comment by TorsteinHonsi** [comment]
I can't see any lag... Tested with Chrome on Mac and virtual Windows.

Could it be that the animation makes it appear laggy? In that case we need to do something with the default animation. What does it look like to you if we turn off animation and increase the `mouseWheelSensitivity`? http://jsfiddle.net/highcharts/8vL6Lkt1/

**Comment by callumacrae** [comment]
Hm, not really sure how I can demonstrate the problem. I'm using Chrome on OS X with a trackpad, but it's still laggy with Chrome on Windows and with a mouse (it's worse with a trackpad, though).

It looks way better with the animation turned off! What does the animation do? The fiddle looks pretty animated - possible because of smooth scrolling?

**Comment by pawelfus** [comment]
Using touchpad, os x, with enabled animation: 
![mapzoom](https://user-images.githubusercontent.com/1453926/30642252-5d6bb57c-9e0a-11e7-8d03-1b71d443e340.gif)

With disabled animation:
![mapzoom_no_anim](https://user-images.githubusercontent.com/1453926/30642659-03f982d8-9e0c-11e7-8af8-e5a278647ff9.gif)

**Comment by callumacrae** [comment]
![](https://thumbs.gfycat.com/CrazyMixedCowrie-size_restricted.gif)

video: https://gfycat.com/gifs/detail/CrazyMixedCowrie

**Comment by KacperMadej** [comment]
The problem is also visible on Windows 10 when using a touchpad - zoom starts only after the gesture (like in the gif in the above comment) is finished. Pages scrolling through the same gesture is being done gradually and during the gesture, so chart's behavior is not consistent with default scrolling.

**Comment by sebastianbochan** [comment]
**Internal note**
@oysteinmoseng

**Comment by TorsteinHonsi** [comment]
@KacperMadej can you do some debugging? Is it the event itself that is delayed until the gesture is finished, or is it Highcharts?

The code in question: https://github.com/highcharts/highcharts/blob/v7.0.1/js/parts-map/MapNavigation.js#L186-L196

**Comment by KacperMadej** [comment]
`chart.pointer.onContainerMouseWheel(e);` is fired multiple times when scrolling, but only border of elements is changing it's width in real time and zooming in or out starts only after dragging stops.

**Comment by TorsteinHonsi** [comment]
Hmm. Are you able to come up with a proposal for a fix? It may be that the zooming itself is delayed because it needs to run the computation which is not fast enough to follow the frequently fired events.

**Comment by KacperMadej** [comment]
The problem is visible in Chrome and Edge - zoom starts when drag stops with animation enabled
and is not visible in Firefox - however, with or without animation it's a bit "jumpy".

While scrolling on touchpad `wheelEvent` is fired over 30 times per second, sometimes with interval under 20ms. In such cases disabled animation will be no different that with animation (tested with disabled animation and zoom is smooth or unchanged (FF)).

I would suggest adding a check that will call `chart.redraw()` with animation set to false as an argument when zoom is minimal or with minimal time intervals. Sometimes axes are not updated - like a redraw with false animation is not redrawing the chart. I'll try to debug this further.

**Comment by TorsteinHonsi** [comment]
Thanks! One problem is that when one event fires we don't know when the _next_ event will fire. Ideally we should run without animation if the next event happens very soon. One pattern that we have used in these scenarios is to defer the zoom. You could try out something like this:

* The first event sets a timeout in for example 50ms to do the zoom with animation.
* If a new event comes along within these 50ms, it clears the first timeout and runs the zoom _without_ animation.
* Now these two steps could probably be repeated over and over. In a fast sequence it will lead to every second event actually trigger a redraw, and in the end possibly a 50ms delayed redraw.

A potential downside is that the 50ms may be perceived as a noticeable delay if we're only running one event, so we need to experiment and find the right delay.

**Comment by callumacrae** [comment]
Unless there's other factors making things slower, 50ms shouldn't be perceivable - it's generally accepted that everything below 150ms feels instant
