### ISSUE TITLE
Publish native ES6 modules

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#7186]
With [native ES6 imports support having landed in Chrome and Safari](https://jakearchibald.com/2017/es-modules-in-browsers/) a few months ago, and [Node v8.5.0 adding experimental support for ES6 modules](http://2ality.com/2017/09/native-esm-node.html) last week, it would be great to publish native ES6 modules for HighCharts and HighStock.

Publishing them at https://code.highcharts.com/ would make it very easy to use from browsers without any bundlers, solving (at least for compatible browsers) long-standing issues like #4994.

**Comment by jon-a-nygaard** [comment]
@TorsteinHonsi This has been technically ready for a while through our build script. What we need to discuss first is a good location for the files. E.g code.highcharts.com/es6 and code.highcharts.com/js/es6, could be an option.

Also quality check that the final structure works for all our distribution platforms, code.highcharts.com, zip folders, and highcharts-dist.

**Comment by jon-a-nygaard** [comment]
*Internal Note: Landed on folder structure `code.highcharts.com/es-modules` and `code.highcharts.com/js/es-modules`*

**Comment by jon-a-nygaard** [comment]
The ES modules will be published in the next maintenance release v6.0.8.

**Comment by jon-a-nygaard** [comment]
Hi @netaisllc,

Apologies for the late reply.

The ES-modules is released since v6.1.0, release v6.0.8 was bumped to v6.1.0.
You can find the es-modules located at `/es-modules` for classic mode, and the styled mode under `/js/es-modules`.
For instance the highcharts master file can be found on our DNS at https://code.highcharts.com/es-modules/masters/highcharts.src.js

The publish of our ES modules was not mentioned in the release article, only briefly in the [changelog](https://www.highcharts.com/documentation/changelog) of v6.1.0.

Best regards
Jon

**Comment by dandv** [comment]
Thanks @jon-a-nygaard. I've submitted a [PR to document how to load Highcharts from CDN as an ES module](https://github.com/highcharts/highcharts/pull/8827). I was going to also add how to dynamically import it, but ran into [this issue](https://github.com/basarat/typescript-book/issues/422). Any chance to avoid `export default`? More reasons:

1. https://basarat.gitbooks.io/typescript/docs/tips/defaultIsBad.html
2. https://blog.neufund.org/why-we-have-banned-default-exports-and-you-should-do-the-same-d51fdc2cf2ad
3. https://github.com/airbnb/javascript/issues/1365

**Comment by ljharb** [comment]
`export default` should be preferred, not avoided.

**Comment by jon-a-nygaard** [comment]
@dandv Currently we only export to default, and I do not know a way to get around it with our latest version.
I do agree that we should provide named exports as well, and this should not conflict with those using the default export since we can provide both. So I believe this part should be fairly simple to achieve.

However we might need to do some work on our [highcharts-assembler](https://github.com/highcharts/highcharts-assembler) should the support of named exports extend to our UMD pattern used in our ES5 distributed files (non ES modules, e.g http://code.highcharts.com/highcharts.src.js).

**Comment by chriszrc** [comment]
Just double checking, with the new es6 modules in highcharts/es-modules, should we be using this for importing? (In this case, I just want highmaps)

```
import Highcharts from 'highcharts/es-modules/masters/highmaps.src.js';
```

**Comment by jon-a-nygaard** [comment]
@chriszrc Yes, that should be correct when loading Highmaps.
