### ISSUE TITLE
New API tree (old dump.json) have different format

### ISSUE THREAD

**Issue by pinkynrg** [highcharts/highcharts#7227]
I used to find the following very useful attributes for every element in those old APIs dump.json:

http://api.highcharts.com/highcharts/option/dump.json	http://api.highcharts.com/highstock/option/dump.json
http://api.highcharts.com/highcharts/object/dump.json
http://api.highcharts.com/highstock/object/dump.json

id
fullname
return_type
since
description
demo
deprecated
parent_id
is_parent
context
title
values
see_also
defaults
root_id
api_source

Is it still possible to find these value somewhere or they are gone forever? They were super useful!

In the mean time, is it still possible to find those old dumps somewhere?

Thanks!

**Comment by pinkynrg** [comment]
You guys linked the wrong file in the api web page.

Instead of http://api.highcharts.com/highcharts/tree.json
should have linked:
instead of http://api.highcharts.com/highcharts/dump.json

Same think for Highstock

**Comment by cvasseng** [comment]
@TorsteinHonsi do we have a dump for the Objects/Methods?

The old dump for the options is still located at http://api.highcharts.com/highcharts/dump.json, but we're phasing out this format in favor of the new one which is now linked to (tree.json).

That said, we don't have any immediate plans of removing the old format (dump.json) completely. If there are missing fields in the old format, we'll be sure to add them.

**Comment by pinkynrg** [comment]
There used to be a series--type that now is not there anymore (There are only dumps such as series<line>--type, of series<spline>--type).

Why has it been removed?

**Comment by cvasseng** [comment]
It wasn't removed on purpose, we'll look into getting it back in.

For now, the same information can be found by looking at `series<*>.type` on any of the series types.

**Comment by TorsteinHonsi** [comment]
@cvasseng We don't currently have a dump for the objects and methods. It is built with jsdoc with different templates than the options structure.

**Comment by pinkynrg** [comment]
@cvasseng agreed! The thing is that I'm fetching that file in order to have better UX on my application (I do understand the api itself is still there though). I was just wondering if it was going to be missing forever or it was only a mistake coming from the new version of the software.

Just letting you know all "series.*" are missing.

Good that these records are coming back!

Thanks

**Comment by cvasseng** [comment]
Sorry - I meant straight on `series<*>` (e.g. series<line>.values).

If you depend on the meta data, I'd really recommend you take a look at the new format - it's much more structured, and contains several additional fields not found in the old-style meta.

**Comment by pinkynrg** [comment]
I see. Isn't the dump.json a flatten version of the tree.json? I'm going to look into it, thanks for the advice. Since we are talking about it, is the `{meta: {filename: ..., line: ..., lineEnd: ...}}` only for internal use, correct? Also, what's the root part of the link for the "sample.value" (such as highcharts/plotoptions/series-marker-symbol/)? 

I see what you mean when you say more structured, since being a tree it is showing right away parent/children.

**Comment by cvasseng** [comment]
The old-style dump isn't a 1:1 flattened version of the new format. It's meant to be backwards compatible, but we won't add anything to it that wasn't there in the old system. The new format has a few more options, in addition to being more structured (not only in the sense that it's a tree; individual options are also more well-formed, e.g. `samples` is an array, as is `products`, types are exploded rather than being a `|` separated string, and so on).

The new documentation system generates the documentation based on the code itself. The stuff in `meta` is parsed directly from the source code. In regards to `filename`/`line/`/etc. it's very useful, at least in some use cases (such as ours), to have a direct pointer to the source code where the thing being documented was defined.  

The root part for all the sample links is `http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples`.
