### ISSUE TITLE
Legend box is not being resized when dynamically adding/removing series

### ISSUE THREAD

**Issue by YusselPP** [highcharts/highcharts#7260]
#### Expected behaviour
Adjust legend box size when dynamically adding or removing series.

Note: Before version 6 this was the behaviour

#### Actual behaviour
The legend box doesn't change its size when series are added or removed.

#### Live demo with steps to reproduce

[See demo.](http://jsfiddle.net/4x7f7bn9/)

#### Affected browser(s)
All.

**Comment by pawelfus** [comment]
Hi @YusselPP 

Thank you for reporting the issue! It looks like a regression after c4fef24 commit.

**Comment by TorsteinHonsi** [comment]
The bug comes down to `SVGRenderer.crisp`, that is called [when animating the box](https://github.com/highcharts/highcharts/blob/v6.0.1/js/parts/Legend.js#L691-L696). It alters the wrapper cached value of the properies, so when the animators try to read them, they are already set to the animation target, and the `to === from` test accidentally passes.
