### ISSUE TITLE
Highcharts “shared” tooltip gets ignored when tooltip is triggered via keyboard (thru accessibility module)

### ISSUE THREAD

**Issue by richfinelli** [highcharts/highcharts#7261]
#### Expected behaviour
When using "shared" tooltip AND the accessibility module, keyboard focus should land on ALL data points and not a single data point. 

#### Actual behaviour
When using "shared" tooltip AND the accessibility module, keyboard focus lands on single data points, thus tooltip only shows 1 data point instead of all data points. 

#### Live demo with steps to reproduce
https://jsfiddle.net/richfinelli/xme65xj3/25/

#### Affected browser(s)
Tested in Chrome (assuming all)

#### Screen shot
![highcharts-accessible-tooltip](https://user-images.githubusercontent.com/2308509/31475663-1ab8777a-aed0-11e7-8ec0-d83220ea76cf.png)

**Comment by pawelfus** [comment]
@oysteinmoseng

**Comment by TorsteinHonsi** [comment]
@oysteinmoseng , also talk to @jon-a-nygaard regarding how to trigger a shared tooltip from the pointer. Specifically, unlike earlier, `point.onMouseOver` now brings up the shared tooltip: http://jsfiddle.net/highcharts/khqbmeje/.

**Comment by primerano** [comment]
@TorsteinHonsi  @oysteinmoseng I thought this was working as designed.  

When I have a 3 lines on a chart the keyboard walks each line showing only the data for that series.  Now it shows data for all 3 series.  Maybe in this mode it should only walk one series since the data is the same in all 3.   after you have walked the 1st line you have seen everything.   but this might break the aria-labels on each point that have data specific to that point.

**Comment by oysteinmoseng** [comment]
@primerano This was added based on feedback that keyboard-only users should be able to take advantage of the shared tooltip as well. If the chart creator has determined that a shared tooltip is beneficial for the particular chart, I think it makes sense to also show this for keyboard navigation.

With the current code, the keyboard navigation for points should always wrap around at the end of the chart (use TAB to move to next section). This seems to not have made it into the master branch, though.
