### ISSUE TITLE
Marker not at the center of the point

### ISSUE THREAD

**Issue by artem78** [highcharts/highcharts#7273]
I`m using markers with custom images. The bug is that they placed with offset of the point. I noticed that this is happening when I use marker enabled parameter:
```
    plotOptions: {
        series: {
            marker: {
                enabled: false
            }
        }
    },
```
![h_1507893506_8577037_a76f242a80](https://user-images.githubusercontent.com/8585304/31544533-f38b95ce-b023-11e7-9b82-351a28153d8e.png)

Without this param all looks fine:
![h_1507893444_7440525_0451dc9184](https://user-images.githubusercontent.com/8585304/31544904-bc212e44-b025-11e7-83d9-232c39bea080.png)
 
Demo: http://jsfiddle.net/crazzzy/7mug981a/
I see this issue in both my browsers Firefox and Chrome.

**Comment by pawelfus** [comment]
Hi @artem78 

Thanks! 

**Workaround:**
Set `marker.radius = -2`, demo: http://jsfiddle.net/7mug981a/1/

*Internal note:*
It's caused by default value for radius (4) which is cleaned up here: https://github.com/highcharts/highcharts/blob/b39922516cdad8a880a7b8dbe13c23b4427deeb8/js/parts/Series.js#L3676-L3678

But only for series with enabled markers: https://github.com/highcharts/highcharts/blob/b39922516cdad8a880a7b8dbe13c23b4427deeb8/js/parts/Interaction.js#L647-L649

**Comment by TorsteinHonsi** [comment]
@pawelfus The test for https://utils.highcharts.local/samples/#test/unit-tests/series/marker doesn't pass in Firefox. Will you have a look?
