### ISSUE TITLE
HighStock gapUnit breaks navigator

### ISSUE THREAD

**Issue by alsikora** [highcharts/highcharts#7279]
#### Expected behaviour
Navigator always display overview for chart.

#### Actual behaviour
When I'm using gapSize with gapUnit 
`plotOptions: {
       	line: {
               gapSize: 24*60*60*1000,
               gapUnit: 'value'
            }
       }`

 navigator is broken. Data on the chart are display correctly but overview (navigator) is empty. 

#### Live demo with steps to reproduce

https://jsfiddle.net/pdhtpntw/

**Comment by pawelfus** [comment]
Hi @alsikora 

Navigator is not broken, it simply inherits options from the main series. Point are there, just distance between each point is one week, because of the dataGrouping. You can observe the same issue when you click `All` button in the rangeSelector - main series exists (you can hover points) but `gapSize` causes all points are separated. 

Solution: disable `gapSize` (or `dataGrouping`) for the navigator series, demo: https://jsfiddle.net/pdhtpntw/1/
