### ISSUE TITLE
Scatter chart tooltip limit?

### ISSUE THREAD

**Issue by willifordj** [highcharts/highcharts#7288]
We use large datasets in Highcharts scatter charts, and have found that tooltip formatting fails to work correctly when a series has more than 4999 points.

Tooltip format OK with 4999 points in each series where “UEC” has a 4 character string displayed:
http://jsfiddle.net/adkkqkwm/25/

Tooltip changes to “undefined” when series are 5000 points:
http://jsfiddle.net/adkkqkwm/26/

Can this be fixed so that it will work correctly with series as large as 20,000 – 30,000 points?

**Comment by TorsteinHonsi** [comment]
What happens at 5000 points is that you go over the [boostThreshold](http://api.highcharts.com/highcharts/plotOptions.series.boostThreshold), so the chart goes into boost mode. In this mode, processing on the data points is kept to a minimum, and as much as possible passed directly on to the WebGL renderer. When rendering 20-30k points, I wouldn't recommend changing this threshold.

The problem in your tooltip comes from this logic in the formatter: 
`this.series.options.extra[this.series.data.indexOf(this.point)]`

In boost mode, `this.point` is a mock point object created just for the tooltip, so it is not part of the `this.series.data` array. Instead of having the `extra` array as a parallel array to the data, I would recommend you to index it by the x values so you can look up directly, something like this:
`this.series.options.extra[this.point.x]`

**Comment by willifordj** [comment]
Thank you!
