### ISSUE TITLE
Sankey / link-dataLabels overlapping

### ISSUE THREAD

**Issue by RHCautomation** [highcharts/highcharts#7295]
Hi,

I'm glad that sankey has finally been released for highcharts. 

I have to use dataLabels for the links, but unfortunately all labels will automatically be aligned at the same x-position and so a lot of them are overlapping. 

see jsfiddle:
https://jsfiddle.net/RHCautomation/5yk3c19f/1/

Is there any solution for smart label-positioning to prevent overlapping?

**Comment by pawelfus** [comment]
Hi @RHCautomation 

You can hide overlapping labels using `allowOveral: false`. 

If you need more sophisticated solution, then please vote for this on our [UserVoice](https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/15960472-collision-detection-for-data-labels) - we are trying to implement most popular ideas.

**Comment by RHCautomation** [comment]
Hi,

I think you meant `allowOverlap: false`

False is the default value of this parameter and with this unset there will only be a few dataLabels shown, because most of them are crossing in the middle of the links. It would be much better, if the dataLabels wouldn't be aligned in the middle of the links but near the beginning of a link.

**Comment by TorsteinHonsi** [comment]
Thanks for your request, it's a good suggestion.

There are some things to sort out. We could make it so that `dataLabels.align: 'left'` make the link labels align to the left, but that would also make the node labels align left, plus it wouldn't translate well to inverted charts. Probably we would need options like `dataLabels.linkPlacement` that could be `start`, `middle` or `end`. But then we also need to set an alignment that applies only to the links, plus a margin to get clear of the node. 

For now, you can use this snippet: 

```js
Highcharts.wrap(Highcharts.seriesTypes.sankey.prototype, 'translate', function (proceed) {
	proceed.call(this);
    
    Highcharts.each(this.points, function (point) {
    	point.dlBox.x = point.shapeArgs.d[1] + 15;
        point.dlBox.y = point.shapeArgs.d[2];
    });
});
```

[View it live on jsFiddle](https://jsfiddle.net/highcharts/5yk3c19f/2/).

**Comment by rvmladenov** [comment]
Yeah but if you change the dataLabels format to: **format: "{point.name}"** ... it will overlap the labels again

**Comment by MightyPork** [comment]
Is this really fixed in some newer version, or just the bot closing still active bugs? That's not a good way to manage a bugtracker...

allowOverlap is false by default, adding it manually is not doing anything for me either.

```
plotOptions: {
          sankey: {
            nodePadding: 1,
            nodeWidth: 10,
            dataLabels: {
              // vertex
              nodeFormat: '<span style="font-size:12px">{point.name}</span>',
              // link
              format: null,
            },
          },
        }
```

![Screenshot_20210212_114133](https://user-images.githubusercontent.com/2041118/107758520-4c870000-6d27-11eb-9fc6-6c6a0cbabc6d.png)

**Comment by KacperMadej** [comment]
Hi @MightyPork 
The bot closed the issue due to the reason provided by the bot's comment.

I am unable to recreate the problem: https://jsfiddle.net/BlackLabel/cxftrva3/1/
Please add a live demo for the problem, so we could confirm it and reopen the issue.

**Comment by MightyPork** [comment]
Alright, you made me look at it closer, and you're right! The issue was fixed in highcharts 9, we are using version 7.

Here's the test case with Highcharts 7 showing the problem: https://jsfiddle.net/4v8gac7d/1/
