### ISSUE TITLE
data label not showing with large length data

### ISSUE THREAD

**Issue by eakkasit** [highcharts/highcharts#7299]
#### Expected behaviour
I want to show data label always range
![20-10-60 9-41-44](https://user-images.githubusercontent.com/7508045/31803122-2d8be104-b57c-11e7-9298-b6429962309c.png)

#### Actual behaviour
but ! when I zoom out  hightcharts is remove my data label . How to can fix data label showing always.
![20-10-60 9-44-38](https://user-images.githubusercontent.com/7508045/31803161-6478b1ba-b57c-11e7-863a-c1987aa87e04.png)

#### Live demo with steps to reproduce

https://jsfiddle.net/l3east/wLyr0ow4/3/

**Comment by pawelfus** [comment]
Hi @eakkasit 

This is caused by `dataGrouping`, when disabled, you will see the dataLabel: https://jsfiddle.net/wLyr0ow4/4/

DataGrouping disregards all options for points, only values that are approximated are passed onto the new point. DataGrouping applies to all series if at least one series should be grouped (so all features will work, like `shared` tooltip).

**Comment by eakkasit** [comment]
Thx @pawelfus 
But I have a problem with data label in dynamic chart. When create custom tooltip for data label click is not showing  becuase of svg is new rendering every minute. How to fix svg not render data label?

**Comment by pawelfus** [comment]
@eakkasit , or support related questions, please contact with out [support](https://www.highcharts.com/support) team.
