### ISSUE TITLE
click all button, data display error, as picture

### ISSUE THREAD

**Issue by EagleWolf** [highcharts/highcharts#7304]
#### Actual behaviour

click all button, data display error，

![image](https://user-images.githubusercontent.com/4488399/31849943-70269c00-b67d-11e7-9a42-9dd4c9faabc1.png)

#### Live demo with steps to reproduce

http://jsfiddle.net/3vtk3grs/1/

#### Affected browser(s)

chrome

**Comment by EagleWolf** [comment]
please，please，please

**Comment by pawelfus** [comment]
Hi @EagleWolf 

It is caused by [`dataGrouping`](https://api.highcharts.com/highstock/plotOptions.series.dataGrouping): you show values from your own array in tooltip, but points in chart are grouped - the correct value is `204`. Default approximation for columns is `sum`.

Demo with disabled dataGrouping: http://jsfiddle.net/3vtk3grs/2/

If something is not clear, please contact with our [support](https://www.highcharts.com/support) team.
