### ISSUE TITLE
Bars outside xAxis visible region when one bar per category

### ISSUE THREAD

**Issue by gedrox** [highcharts/highcharts#7346]
When we have 3 categories with one data sample in each one in different "x" points, the bars in the sides are not visible. E.g. 
* CatA has value in x=1
* CatB has value in x=2
* CatC has value in x=3

In this case CatA and CatC bars will be outside the chart visible area.

#### Expected behaviour
Three bars should be shown.

#### Actual behaviour
Center bar is visible, bars on sides are outside the visible area.

#### Live demo with steps to reproduce
https://jsfiddle.net/gcgayzzu/2/

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @gedrox 

Thanks for reporting the issue. It's caused by using separate series: each series has just one point, so we are unable to calculate distance required per one series. This can be fixed it two ways:
- if you have categories, use `yAxis.type="category"`: https://jsfiddle.net/gcgayzzu/3/
- if know the distance, use `series.pointRange=value`: https://jsfiddle.net/gcgayzzu/4/

Just a side note: I'm not sure if this is expected, but in your demo columns are translated to make space for another columns within the same series. If you have only one point per series, then you may want to set `series.grouping=false`, please take a look: https://jsfiddle.net/gcgayzzu/5/

**Comment by gedrox** [comment]
In fact we have `datetime` xAxis type (with HighStack option xAxis.ordinal) and this is just a data corner case we have problems with; usually there will be values for all categories.

**Comment by pawelfus** [comment]
Thank you for the details!

**Comment by gedrox** [comment]
This is the example for that: https://jsfiddle.net/gcgayzzu/6/.

**Comment by pawelfus** [comment]
Thanks again. We really appreciate this. Just in case, setting `pointRange` resolves the issue: https://jsfiddle.net/gcgayzzu/7/ 

*Internal note:*
Simple idea to concat data from all series, then calculate closest range is not that simple: https://jsfiddle.net/3f57soLr/ (panning is broken).
