### ISSUE TITLE
Tooltip is not shown anymore if tooltip is larger than the chart

### ISSUE THREAD

**Issue by orangecoding** [highcharts/highcharts#7347]
I'm using HighStockCharts and recently upgraded to v6.0.3. Since then, the tooltips won't be shown anymore as soon as the tooltip is higher than the actual chart. See the minimum example which I've provided.

#### Expected behaviour
The tooltip should be shown.

#### Actual behaviour
The tooltip is not shown if the tooltip (the height) is larger than the actual chart.

#### Live demo with steps to reproduce
http://jsfiddle.net/n1h3q3sr/
Uncomment the part `testString += "<br/> NOT WORKING ANYMORE"` to make the tooltip visible.

#### Affected browser(s)
Chrome / Firefox and most probably IE too

EDIT: Works in 5.0.14, is broken since 6.0.0 as it seems.

**Comment by pawelfus** [comment]
Hi @orangecoding 

Thank you for using Highstock. This is expected change in Highstock v6. In previous versions we used to have `shared: true`, now it's `split: true` by default. Split tooltip hides labels that don't fit the plotting area. You can disable this: http://jsfiddle.net/n1h3q3sr/1/

Just in case, you can see tooltip overflows plotting area:
![screen shot 2017-11-02 at 16 16 20](https://user-images.githubusercontent.com/1453926/32333922-58450f70-bfe9-11e7-9760-911d568c0c06.png)

**Comment by orangecoding** [comment]
wouldn't it be much easier to at least show the tooltip until it reaches the bottom? The way it currently is, it looks broken to me and my colleagues..

**Comment by pawelfus** [comment]
The idea behind `split` tooltip is to show short info directly to points, like we do in [multiple series](https://www.highcharts.com/stock/demo/compare) or [technical indicators](https://www.highcharts.com/stock/demo/macd-pivot-points). If you have just one series on a chart, then `split` should be turned off - design of your tooltip suggests `shared` would work better for you.

**Comment by TorsteinHonsi** [comment]
I'm not sure what to do with is - the current behaviour with split tooltip is that it is allowed to be placed within the plot area, but hidden if it overflows. That's mainly because we need the "header" to sit on the X axis. But in this case there is no header because the formatter returns a single formatted string, so we could let the tooltip use the entire chart height.

But there's also a problem with the old version - if the tooltip height exceeds the full chart height, it is clipped at the top in an ugly way. But at least then the user can read some of the content.
