### ISSUE TITLE
(.Net Wrapper) Incorrect settings to create a Pareto chart

### ISSUE THREAD

**Issue by GertVen** [highcharts/highcharts#7368]
Apologies if this has been reported before. I suspect I might have found two errors with the .Net Wrapper, specifically when creating a Pareto chart. Both errors refer to this line of code (VB.Net):

`series.Add(New ParetoSeries() With {.YAxis = 1, .ZIndex = 10, .Type = ParetoSeriesType.Line})`

1.) I cannot find the "baseSeries" property which prevents me from linking the paretto to a previously defined series. I have tried the "LinkedTo" property but that does not seem to work. Is this property indeed missing or is it located somewhere else?

2.) The "YAxis" property is of type string, whereas the Javascript would like an integer. Using the property as it is now inserts a Javascript value of "1", where Highcharts would like an integer.

Please let me know if the functionality is indeed there and I'm simply looking in the wrong place. I am using Highcharts .Net Version 6.0.6512.25591

Thanks!

**Comment by pawelfus** [comment]
Hi @GertVen 

Thank you for using Highcharts wrapper and for reporting these issues! 

1) You are right, it's a bug caused by missing [baseSeries](https://api.highcharts.com/highcharts/series.pareto.boostThreshold) in our API docs. Let me fix this.

2) At this moment, .Net wrapper supports only String, but this shouldn't be a problem because JS version can use both, Number and String, see [docs](https://api.highcharts.com/highcharts/series.pareto.yAxis). Of course that means you need to first set an [Id for yAxis](http://dotnet.highcharts.com/Help/Highcharts/html/class_highsoft_1_1_web_1_1_mvc_1_1_charts_1_1_y_axis.html#a686fde4ee5144c0724417f20cd1fac1a). We are working on a solution to allow use both types in the wrapper.

**Comment by GertVen** [comment]
Hi Pawel

Thank you for the quick reply. I completely forgot about the yAxis ID. I've implemented the change and it works perfectly
