### ISSUE TITLE
&amp; displayed in toolip in Firefox browser when accessibility module included

### ISSUE THREAD

**Issue by ff-sgupta** [highcharts/highcharts#7383]
#### Expected behaviour
Chart title set as "A&B", svg title should be set to "A&B"

#### Actual behaviour
svg title is set to "A&amp;B"

#### Live demo with steps to reproduce
http://jsfiddle.net/hogztz4o/

Access the above link in Firefox browser.
Hover over the chart. Observe tooltip displayed as "A&amp;B" since svg title has text "A&amp;B"

#### Affected browser(s)
Firefox

**Comment by pawelfus** [comment]
Hi @ff-sgupta 

Thank you for reporting the bug. I was able to replicate the issue in Firefox 56.0.2, attaching screenshot:

![screen shot 2017-11-09 at 11 26 57](https://user-images.githubusercontent.com/1453926/32600787-0457c62a-c541-11e7-830c-e7330043b86c.png)

@oysteinmoseng

**Comment by pawelfus** [comment]
@oysteinmoseng

**Comment by oysteinmoseng** [comment]
This is a combination issue, firstly of encoding the characters in the title element, and secondly we need a method for configuring this text. I have suggested a fix for this, and we should have this solved by the next release.

With the suggested fix you can set the `lang.accessibility.svgContainerTitle` option to empty to disable the title entirely. We also have modified the encoding logic so that `&` isn't shown as `&amp;`.

**Comment by ff-sgupta** [comment]
Thank you
