### ISSUE TITLE
[Highcharts Accessibility] Edge + Narrator, keyboard navigation does not set focus on svg element

### ISSUE THREAD

**Issue by SummerLi** [highcharts/highcharts#7422]
#### Expected behaviour
With combination of Edge and Narrator, keyboard navigation should work.

#### Actual behaviour
With combination of Edge + Narrator, using arrow keys to navigate through Highcharts series, svg element is not focused, so series description is not announced, only "left arrow" is announced.

#### Affected browser(s)
Edge, IE

**Comment by SummerLi** [comment]
FYI @oysteinmoseng

**Comment by SummerLi** [comment]
Previous reply from Øystein Moseng

Some weird behavior in Edge. It seems like tab focus won’t work on the SVG when Javascript is involved. Example: http://jsfiddle.net/oysteinmoseng/4ngyowkx/10/show/.
 
Notice that I’ve added an onfocus event that displays the tooltip when a point is focused. This works for me in Chrome, but in Edge the points don’t seem to be in the tabindex list. I’ve tried to detach events from the point elements, but that does not seem to help. The interesting thing is that it works even in Edge when copying the SVG only: https://jsfiddle.net/dm04p8Lp/show/. So when there is no Javascript, the points are picked up properly.
 
Do you have any pointers towards what might be causing this? If so, we can probably work around it on our side.

**Comment by oysteinmoseng** [comment]
Pending reply from Edge team here

**Comment by SummerLi** [comment]
Attach the zip file of my demo resources.

[Accessibility_v6.0.2.zip](https://github.com/highcharts/highcharts/files/1488794/Accessibility_v6.0.2.zip)

**Comment by oysteinmoseng** [comment]
Update: Programmatically setting focus to SVG elements is not supported yet in Edge. Example: https://jsfiddle.net/oysteinmoseng/a7k2ak16/. This presumably breaks Narrator support when navigating using the keyboard, and also causes several bugs with the keyboard navigation itself. Trying to tab to the legend and then shift-tab backwards in [this demo](http://jsfiddle.net/gh/get/jquery/1.7.2/highcharts/highcharts/tree/master/samples/highcharts/accessibility/accessible-line/) for example, fails. Since we are not setting focus to the SVG elements as we move, the browser keydown events are sent to the wrong elements, and as a result we are unable to keep track of the navigation cursor. This issue can be worked around, but the Narrator issue remains.

To fix this we will need some means of focusing SVG elements in Edge programmatically.

**Comment by oysteinmoseng** [comment]
I have added workarounds for the navigation bugs, but the narrator problem still stands.

**Comment by oysteinmoseng** [comment]
Programmatic focus support should be coming in one of the next releases of Edge, according to Edge team members. That should hopefully solve this issue with no further code changes on our end.
