### ISSUE TITLE
[Highcharts Accessibility] Highcharts chart in High contrast mode is not supported

### ISSUE THREAD

**Issue by SummerLi** [highcharts/highcharts#7424]
#### Expected behavior
It would be helpful that Highcharts provide some default High Contrast theme / color palette, then Highcharts library consumers can benefit from this, by simply picking a theme instead of implementing one themselves.

#### Actual behaviour
Go to windows settings -> High contrast -> Select a High Contrast Theme. The Charts rending in IE and Edge is not applying any High contrast colors. Per discussion with @oysteinmoseng , this is not supported yet.

#### Affected browser(s)
Edge, IE (Windows OS)

**Comment by SummerLi** [comment]
FYI @oysteinmoseng

**Comment by oysteinmoseng** [comment]
Here is a codepen showing how we can apply High Contrast colors to e.g. a pie chart: https://codepen.io/oysteinmoseng/pen/ydywWQ
![High contrast](https://user-images.githubusercontent.com/5276642/59354512-908d5a80-8d25-11e9-8415-1af205e5861d.png)

This will be added to the core so that the applied High Contrast colors also apply to the charts.

We will add an option for controlling this, so that it is possible to customize or disable.
