### ISSUE TITLE
Tooltip Connector changes style when title text is null

### ISSUE THREAD

**Issue by sagargurtu** [highcharts/highcharts#7427]
#### Expected behaviour
The connector for tooltip callout should be consistent for every data point.

#### Actual behaviour
When title text is set to null (as is the use case), the tooltip connector for the second data point changes shape from an arrow ^ to a line | (Refer below fiddle)

#### Live demo with steps to reproduce
http://jsfiddle.net/t5b8uhwv/

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @sagargurtu 

Thank you for reporting this issue. Tooltip is always rendered within the container. If a point is in the corner, and we don't have enough space to position the tooltip, then a connector is rendered instead of an arrow. This is directly connected to #5784 issue - I tried to use plugin posted there (http://jsfiddle.net/t5b8uhwv/1/) - but it looks like issue with missing arrow still exists.

Fixed the issue: http://jsfiddle.net/t5b8uhwv/3/ - it was caused by rendering arrow (negative path values) outside it's container. Added extra offset in the fiddle above.

**Comment by sagargurtu** [comment]
![tooltip](https://user-images.githubusercontent.com/18263719/33119142-157c19da-cf94-11e7-9119-a6266d21aadc.png)

Hi @pawelfus 
Is there any way other than using the plugin? Moreover. it seems there actually is enough space for the arrow to render (see image)

**Comment by pawelfus** [comment]
Hi @sagargurtu 

Yes, you can also set `tooltip.distance`: http://jsfiddle.net/t5b8uhwv/5/
