### ISSUE TITLE
Chart Y Axis minimum does not always apply

### ISSUE THREAD

**Issue by GertVen** [highcharts/highcharts#7430]
#### Expected behaviour
Chart minimum will be set at 4000

#### Actual behaviour
Chart minimum is not set

#### Live demo with steps to reproduce
http://jsfiddle.net/sr7ujdey/

#### Affected browser(s)
Google Chrome
Mozilla Firefox

I am not sure if I'm doing something wrong as the chart minimum does set in some cases, see http://jsfiddle.net/huoqge45/ for an example where it works

Code generated via official Highcharts wrapper

Thanks!

**Comment by pawelfus** [comment]
Hi @GertVen 

Thank you for reporting this issue. In general, ticks are rounded to display the best guess for tick interval. This is caused by [`startOnTick`](https://api.highcharts.com/highcharts/yAxis.startOnTick) which, by default, is set to true. When disabled we get: http://jsfiddle.net/sr7ujdey/1/ - yAxis starts from 4k, but the first tick is 5k.  

In case when build-in tick-positioner doesn't meet your requirements, you can use:

- [`tickPositions`](https://api.highcharts.com/highcharts/yAxis.tickPositions) - if you know exactly how ticks should be places (e.g. data is always within 4k-20k)
- [`tickPositioner`](https://api.highcharts.com/highcharts/yAxis.tickPositioner) - where you have access to calculated by Highcharts ticks (by `this.tickPositions`) and you can modify them

**Comment by GertVen** [comment]
Hi @pawelfus

Thank you for the quick response, I will play around with the "startOnTick" and see if that solves my problem

**Comment by TorsteinHonsi** [comment]
This is mentioned in the docs for https://api.highcharts.com/highcharts/yAxis.min

> If the startOnTick option is true (default), the min value might be rounded down.
