### ISSUE TITLE
Incorrect ticks on datetime axis type while using global.timezone

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#7432]
#### Expected behaviour

Ticks on xAxis should be created basing on processed points values.

#### Actual behaviour

There are ticks of the day before real point datetime on xAxis.

#### Live demo with steps to reproduce

[JSFiddle](http://jsfiddle.net/daniel_s/1h1tc8o2/)

#### Affected browser(s)

All browsers

#### Workaround

[JSFIddle](http://jsfiddle.net/daniel_s/h186d9vq/)
Positioning ticks basing on series x values, when the chart is loaded.

**Comment by droiddk** [comment]
+1

**Comment by TorsteinHonsi** [comment]
> Ticks on xAxis should be created basing on processed points values.

That is not how the datetime axis works - it is designed to look at the min and max range and then lay out time ticks according to `tickPixelInterval`. To add one-to-one ticks, use a _category_ axis instead.

Nevertheless, there seems to be a bug here since the datetime axis lays out the ticks on 23:00 instead of midnight: http://jsfiddle.net/highcharts/1h1tc8o2/1/

**Comment by TorsteinHonsi** [comment]
It looks like the problem only applies when the first data point is October 29 - using any other date will make the tick fall on midnight. http://jsfiddle.net/highcharts/1h1tc8o2/2/

**Comment by droiddk** [comment]
Hi Torstein

I came to the same conclusion, I did a lot of testing:
https://jsfiddle.net/droiddk/rk7txu31/
https://jsfiddle.net/droiddk/4pqwd413/
https://jsfiddle.net/droiddk/mLLfm9vy/
https://jsfiddle.net/droiddk/qm0yaLLp/
https://jsfiddle.net/droiddk/rgxx23q0/

Maybe its related to the DST-change when using global "timezone" and "getTimezoneOffset".

Kind Regards

**Comment by DamianoPantani** [comment]
The same thing is with navigator. Setting minTickInterval somewhat fixes main xAxis' labels but not in navigator's case:

https://jsfiddle.net/rgxx23q0/7/

**Comment by TorsteinHonsi** [comment]
I found the bug, it seems to happen only when the data min and the computed (extended) axis min falls on different sides of the DST crossover. Demo with the fix applied: http://jsfiddle.net/highcharts/1h1tc8o2/3/

@DamianoPantani I suspect your case is different because you set `useUTC` to false. So the X axis labels display differently depending on where in the world the user is.

**Comment by droiddk** [comment]
Hi Torstein 

Yes that fixes the bug. Thanks!

Regards
