### ISSUE TITLE
Swapping the axis of a histogram gives weird graph

### ISSUE THREAD

**Issue by Munksgaard** [highcharts/highcharts#7435]
#### Expected behaviour

I would think that swapping the order of the xAxis and yAxis lists and changing the corresponding indexes in the histogram series shouldn't change the resulting graph.

#### Actual behaviour

The resulting graph does not make sense.

#### Live demo with steps to reproduce

[Without changing the axes](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/histogram/)

[With axes changed](http://jsfiddle.net/mfj97own/2/)

#### Affected browser(s)

Chrome and firefox

**Comment by pawelfus** [comment]
Hi @Munksgaard 

Thank you for reporting this issue. This is caused by binding all series to the same yAxis and yAxis. By default, all series are linked to the first axis in yAxis/xAxis arrays. That means extremes are calculated for all series. If you set `yAxis: 1`+`xAxis: 1` for the scatter series, you will get the same result as in the first demo: http://jsfiddle.net/mfj97own/5/

**Comment by Munksgaard** [comment]
Hi @pawelfus,

Thank you for clarifying that for me, your fix works perfectly!
