### ISSUE TITLE
Default options set on plot in navigator

### ISSUE THREAD

**Issue by josteinkjellsen** [highcharts/highcharts#7453]
#### Expected behaviour
When adding a new plot to the chart, it will get the correct color on the series that is set in the navigator, but the other options should also be set based on the main series unless they are undefined, then they can use default

It used to work in earlier versions like 5.0.12: http://jsfiddle.net/3mf5dv56/28/

![image](https://user-images.githubusercontent.com/22935050/33174075-c62c7e7e-d056-11e7-93fe-e649045f3251.png)

#### Actual behaviour

In latest version it does not work like this any more: http://jsfiddle.net/3mf5dv56/29/

Now it always uses area plot and other settings set on main plot are ignored.

![image](https://user-images.githubusercontent.com/22935050/33173915-348df0e2-d056-11e7-802f-267968af8cad.png)

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Hi,

If you have technical questions please use other support channel - this one is for bugs only.
https://www.highcharts.com/support

When contacting technical suport please remember of adding a live demo. I do not understand what is the question's about - please try to rephrase it.

**Comment by josteinkjellsen** [comment]
Oh, it’s definitely a change of behavior from earlier versions. I will update the bug so you can reopen it.

Mvh Jostein Sand Kjellsen

**Comment by josteinkjellsen** [comment]
@KacperMadej Hi, see update bug report. Can you reopen this?

**Comment by pawelfus** [comment]
Hi @josteinkjellsen 

Thank you for the details! Let me reopen the issue.

@oysteinmoseng

**Comment by oysteinmoseng** [comment]
@josteinkjellsen This is by design, and is how the behavior used to be, even in 5.0.12 (notice the faint blue fill of the navigator series, easier to see if you move the navigator): http://jsfiddle.net/oysteinmoseng/3mf5dv56/30/. There were however some bugs in 5.0.12 that masked this behavior in the example you show. 

The reason for this design is that we want to visually distinguish the navigator series from the base series by default. Note that the fill opacity of the arearange by default is very small (5% only), but since you are not using a hex color (just using the named color "green") this fill opacity setting is not applied. It looks more sensible with hex colors by default: http://jsfiddle.net/oysteinmoseng/3mf5dv56/33/.

Of course the behavior can be overridden by setting the type of the navigator series explicitly. http://jsfiddle.net/oysteinmoseng/3mf5dv56/32/

It could be debated whether or not we want to keep this design of course. Do you have a use case where this behavior is inconvenient?

**Comment by josteinkjellsen** [comment]
I was not aware of the option to override the navigatorOptions when adding the series. This should solve my case. 

I do understand the reason for the current behaviour as it looks better, and is probably the preferred behaviour from users that have a bit less complex usage than we have.

Thanks again for your help @oysteinmoseng! You can close this.

Mvh Jostein Sand Kjellsen
