### ISSUE TITLE
Wrong text position in annotations labels - only on Firefox

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#7466]
#### Expected behaviour
Text should be centered on all browsers. 

![screen shot 2017-11-28 at 15 45 23](https://user-images.githubusercontent.com/22988131/33331580-3feab01e-d462-11e7-9c06-59a52f182aa8.png)

#### Actual behaviour
There is more space between text and lower border than between text and upper border of the label.

![screen shot 2017-11-28 at 17 29 24](https://user-images.githubusercontent.com/22988131/33331568-39696e74-d462-11e7-8ed6-75b1ba04d78b.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/ppotaczek/hckhLpo1/

#### Affected browser(s)
Only Mozilla Firefox (tested v. 57) - on Windows

**Comment by TorsteinHonsi** [comment]
The demo can be reduced to using only the `SVGRenderer`: http://jsfiddle.net/highcharts/hckhLpo1/3/

The issue comes down to the browsers reporting different bounding boxes for the same font. Some fonts are more consistent than others, for example Helvetica seems to vary only ~2px between browsers and systems: http://jsfiddle.net/highcharts/hckhLpo1/5/
