### ISSUE TITLE
Misplaced plot line label

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#7468]
#### Expected behaviour
Image should always be placed on the plot line:
![image](https://user-images.githubusercontent.com/13188589/33382082-0f2bcdf0-d520-11e7-9a96-6ca6ad8fba40.png)

#### Actual behaviour
Sometimes the label has an offset (it's not **on** the line):
![image](https://user-images.githubusercontent.com/13188589/33382117-24fa86bc-d520-11e7-85fb-e91ee7694bb2.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/kkulig/4qk1osmj/

On the first load the label should be rendered incorrectly. However if it rendered properly then do a force refresh of the cache (Shift key + refresh button of the browser on Windows). Then do a regular browser refresh. The label should be properly positioned.

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Looks like the width is no calculated properly because chart would have to wait for the image to be loaded.
Instead of waiting for the image you can set width using e.g. inline styles - demo: http://jsfiddle.net/BlackLabel/4qk1osmj/11/

I doubt we would like to wait with all chart rendering for the image to be loaded.
If the delay is noticeable then the chart would freeze - compare with the fix and without while loading image with deelay.me - time without the image would be time of frozen chart:
- with fix: http://jsfiddle.net/BlackLabel/4qk1osmj/12/
- no fix: http://jsfiddle.net/BlackLabel/4qk1osmj/13/
