### ISSUE TITLE
Bar chart: some xAxis labels don't display in certain case

### ISSUE THREAD

**Issue by kulaeff** [highcharts/highcharts#7471]
#### Expected behaviour
http://jsfiddle.net/eywruqnc/

#### Actual behaviour
http://jsfiddle.net/6m4cL6wo/

#### Affected browser(s)
Tested on Chrome, Firefox and Edge

I noticed that this behavior only occurs if yAxis labels rendered at an angle and if the height of a chart is less than some value (as far as i undestood this value approximately equals to 'number of values in a serie * height of one bar')

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting.

Axis units are not used for day probably because ticks are recognized as too dense.

**Workaround:** 
set weeks multiple to desired amount of days - http://jsfiddle.net/BlackLabel/6m4cL6wo/1/ 
or use tick positioning options - like [tickPositioner](https://api.highcharts.com/highcharts/xAxis.tickPositioner)

*Internal note:* limits should be checked, because units stops at week in this case even if days array is changed to support more day multiples - http://jsfiddle.net/BlackLabel/6m4cL6wo/2/

**Comment by TorsteinHonsi** [comment]
Actually I don't think this is more complicated than the fact that the default [tickPixelInterval](https://api.highcharts.com/highcharts/xAxis.tickPixelInterval) for the X axis is 100. The typical bar chart has a category axis, that's why we haven't seen this case often. 

Simply lowering the `tickPixelInterval` will give the expected behaviour: http://jsfiddle.net/highcharts/6m4cL6wo/3/

I don't think we should fix this either - a fix would imply a smaller default tickPixelInterval for a _vertical datetime_ axis. Linear axis I think would not benefit from denser ticks. So I'm afraid we would add more confusion instead of simplifying.
