### ISSUE TITLE
axis label overflow set to false doesn't prevent last label from being adjusted

### ISSUE THREAD

**Issue by danielehrhardt** [highcharts/highcharts#7475]
#### Expected behaviour
the Last number (7) should be centered under the line

#### Actual behaviour
It is a bit positioned to the left

This is how i fixed it. Is there a other solution for this?
```
.highcharts-axis-labels{
                text:last-child {
                    transform: translate(4px, 0);
                }
            }
```

#### Live demo with steps to reproduce
http://jsfiddle.net/r3hkqL3j/

**Comment by KacperMadej** [comment]
Hi @danielehrhardt ,

It's positioned to the left to fit inside of the axis because default labels.overflow option does that.

This should be possible to resolve through setting the mentioned option to false, but it doesn't help.

I will change the issue title to reflect better the problem found unless you have more information about the case or would suggest something else.

Demo: http://jsfiddle.net/r3hkqL3j/1/

**Comment by danielehrhardt** [comment]
okay, yes the problem is only when you have one digit.

No i don't have a better suggest.
