### ISSUE TITLE
Heatmap legend enabled render error

### ISSUE THREAD

**Issue by xcqwan** [highcharts/highcharts#7490]
#### Expected behaviour
![1512469345090](https://user-images.githubusercontent.com/3190247/33602146-665abdc0-d9e9-11e7-9b11-417aaabe9754.jpg)
#### Actual behaviour
![1512469447314](https://user-images.githubusercontent.com/3190247/33602180-80a21a7a-d9e9-11e7-8756-43a14f8d1ec7.jpg)
then draw to resize, called: 
```
this.chart.update({
            legend: {
                enabled: false,
            },
        }, [ false ])
```
result: 
![1512469561622](https://user-images.githubusercontent.com/3190247/33602275-c48e3a48-d9e9-11e7-9058-072e040c5437.jpg)

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting about the problem. Please remember about adding a live demo in the future.

Live demo: http://jsfiddle.net/BlackLabel/wn1bno4m/
Steps: wait for 1.5sec to see updated chart

*Internal note:* On master branch the bug is less visible, but hover over points to see the black triangle moving in top left corner: http://jsfiddle.net/BlackLabel/wn1bno4m/1/

**Comment by xcqwan** [comment]
@KacperMadej Thank you for your complement
