### ISSUE TITLE
Click event on legend in pie chart doesn't work

### ISSUE THREAD

**Issue by pliasetski** [highcharts/highcharts#7501]
Hello,
Click event on legend in pie chart doesn't work

#### Live demo with steps to reproduce
http://jsfiddle.net/Pashe4ka/7o7ekwyz/

#### Affected browser(s)
Chrome latest version

**Comment by oysteinmoseng** [comment]
As documented [here](https://api.highcharts.com/highcharts/plotOptions.pie.events.legendItemClick) this event does not apply to pies, as the legend displays points rather than the full series. Try using [point.events.legendItemClick](https://api.highcharts.com/highcharts/plotOptions.pie.point.events.legendItemClick) instead
