### ISSUE TITLE
Plot run up & down beyond y-axis in StockChart while dragging navigator

### ISSUE THREAD

**Issue by TaurusD** [highcharts/highcharts#7503]
#### Expected behaviour
Expect plot can be stable corresponding to y-axis grids.

#### Actual behaviour
Plots go up&down while dragging the navigator selector. Sometimes a 90% point goes below the 50% gridline. The way a plot move should be relevant to the position of the left end of navigator selector. 
And if I set a secondary y-axis, the plots for different y-axis may not stay in one chart but locate separately from each other beyond the chart area. 
Reference question: https://stackoverflow.com/questions/47686931/plot-float-up-down-beyond-y-axis-in-stockchart-while-dragging-navigator

#### Live demo with steps to reproduce

https://jsfiddle.net/ghqyvo0x/

#### Affected browser(s)
Chrome (version 62.0.xxx)

**Comment by pawelfus** [comment]
Hi @TaurusD 

Thank you for reporting the issue. As Daniel answered you on StackOverflow, it's caused by `compare: 'value'`. By setting this option, you display **change** of the value over a time, not the real value (still, tooltip displays the real value). For example:

- starting point: `y=50`
- nth-point: `y=10`

That will render nth-point on yAxis with `y=-40`, but tooltip still will display `value=10`. Removed `compare` option: https://jsfiddle.net/ghqyvo0x/6/ - is this a chart you expected? 

Regarding multiple yAxes - could you elaborate? For example: https://jsfiddle.net/ghqyvo0x/7/ - this looks fine.

**Comment by TaurusD** [comment]
Hi @pawelfus 

Thank you for your solution! It does help me on my problem. 

There is another little problem: https://jsfiddle.net/paw5444c/

I cannot fix the starting point of the secondary y-axis to be 100%. Sometimes the black plot flies up from the base gridline while dragging navigator. If I cancel the `reverse: true` in y-axis, I still cannot fix the highest point to be 100%, though I have `max: 100` in my config.

**Comment by pawelfus** [comment]
Hi @TaurusD 

I think in your case it's the best to use [`tickPositioner`](https://api.highcharts.com/highcharts/yAxis.tickPositioner) - you will have full access to the tick positions and you can decide what should be displayed.

For more details, please contact with out [support](https://www.highcharts.com/support). We are trying to keep github for bug reports only.
