### ISSUE TITLE
Sunburst chart - Drill To Node feature is not working properly if parent node values are set explicitly in data

### ISSUE THREAD

**Issue by amruta30** [highcharts/highcharts#7517]
#### Expected behaviour
Drill to node feature should work correctly, even if the summed values are set explicitly for the parent nodes.

#### Actual behaviour
Refer following JS Fiddle, that has values present at leaf level nodes only.
 JS fiddle:  http://jsfiddle.net/amrutaJgtp/wbfvvxc8/2/
Drill to node feature is working correctly. Here, you can observe that the sum of leaf level nodes is seen in series data labels on respective parent nodes.
Example: Click "Europe". Refer attached screenshot1.
![screenshot1](https://user-images.githubusercontent.com/7830487/33878286-f8472ad6-df50-11e7-8d2b-5785c7256aab.PNG)

However, if we explicitly set the parent values(sum of child nodes - observe the series data labels are same as above), drill to node feature does not work correctly.
JS Fiddle: http://jsfiddle.net/amrutaJgtp/wbfvvxc8/3/
Example: Click "Europe". Refer attached screenshot2.
![screenshot2](https://user-images.githubusercontent.com/7830487/33878287-f883214e-df50-11e7-990d-d73566a6c6a8.PNG)

NOTE: All the data values in both the fiddles are the same.

**Comment by pawelfus** [comment]
Hi @amruta30 

Thank you for reporting this bug.

FYI @jon-a-nygaard

**Comment by arekik** [comment]
I havea similar  problem when i set the value of the parent i have this chart (chart1) is ok 
value1 = value2 + value3 + value4 + value5  (the white value is ok because the sum is not equals to value 1)

chart1:
![cap_with_center_value](https://user-images.githubusercontent.com/2358304/34035778-6e4ad5f0-e183-11e7-90a8-9c70e4058ebb.PNG)

but when i access to a child element the chart is not correct i don't understand why i have a white space 
![cap_with_center_value_error_child](https://user-images.githubusercontent.com/2358304/34035805-7f658c54-e183-11e7-8baf-7d3fe9a15ee7.PNG)

value5 = value6 + value 7


When i dont set the value of the parent element value1, i have this chart that dose not represent my data because i must have a white zone because the sum is not equals to value1

![cap_without_center_value](https://user-images.githubusercontent.com/2358304/34035895-c35f7262-e183-11e7-8f50-8d135a08549a.PNG)


But when i click in value5 i have a correct chart

![cap_with_center_value_ok_child](https://user-images.githubusercontent.com/2358304/34035906-d00384ae-e183-11e7-8ec5-1562c0837846.PNG)

**Comment by jon-a-nygaard** [comment]
A pull request with a fix for this issue has been created at https://github.com/highcharts/highcharts/pull/7566
