### ISSUE TITLE
Point.color doesn't work on column chart with a lots of data

### ISSUE THREAD

**Issue by ArnaudGeorges** [highcharts/highcharts#7539]
#### Expected behaviour
The chart created is a column type with the highstock JS with lots of data.
The 20 first columns are supposed to be fill with a grey color (#5c5c61) with the point.color (see the data array).

#### Actual behaviour
None of these 20 first columns are grey, the default blue color is still used by highcharts. 
But when i enlarge the preview window (like 1200px), the grey color shows up... 

Is this behaviour wanted ?

#### Live demo with steps to reproduce
See http://jsfiddle.net/bu3tm30n/ 

#### Affected browser(s)
Firefox 57
Chrome 63

**Comment by pawelfus** [comment]
Hi @ArnaudGeorges 

Thank you for reporting this issue. It's caused by [`dataGrouping`](https://api.highcharts.com/highstock/plotOptions.series.dataGrouping), when disabled you can see colors again: http://jsfiddle.net/BlackLabel/bu3tm30n/1/  DataGrouping applies to **values** only (as per approximation algorithm), other properties (like color) are not calculated.
