### ISSUE TITLE
xrange chart - series not centered when using multiple axes

### ISSUE THREAD

**Issue by semmel87** [highcharts/highcharts#7573]
#### Expected behaviour
When using multiple, stacked y-axes in a xrange chart the rectangles are displayed centered for each category.

#### Actual behaviour
The rectangles are not displayed vertically centered.

#### Live demo with steps to reproduce
http://jsfiddle.net/s3kj03se/7/

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting - it looks like yAxis difference is not detected, but I'm not sure if the feature is implemented. If you have more info please share - otherwise it looks more like an enhancement suggestion than a bug.

This can be resolved by setting `grouping` to false - demo: http://jsfiddle.net/BlackLabel/s3kj03se/8/

**Comment by semmel87** [comment]
Hi, thanks for the solution
