### ISSUE TITLE
Combo graph: columns are superposed with pie

### ISSUE THREAD

**Issue by sempremkacha5** [highcharts/highcharts#7577]
#### Expected behaviour
Ideally, the pie graph position is automatically calculated to avoid superposition with columns

#### Actual behaviour
Columns are superposed with pie.
![screenshot_1](https://user-images.githubusercontent.com/5056375/34306117-c903f314-e741-11e7-985d-3b77a123616f.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/LLExL/8315/

#### Affected browser(s)
All.

**Comment by pawelfus** [comment]
Hi @sempremkacha5 

Thank you for contacting us.  This is expected behaviour, from the pie config:

```javascript
      {
        type: 'pie',
        name: 'Total consumption',
        data: [ ... ],
        center: [50, 80], // <=== center position
        size: 100,
        showInLegend: false,
        dataLabels: {
            enabled: true
        }
    }]
```

You can see that pie position is hardcoded. If you think this should be added to the library (as a core feature, or an official plugin), then please create your idea on our [UserVoice](https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api) - we are trying to implement the most popular ones.
