### ISSUE TITLE
Opposite multi-line y-axes won't align properly

### ISSUE THREAD

**Issue by pepijnolivier** [highcharts/highcharts#7612]
#### Expected behaviour
> When adding two y-axes, one left, and one right (opposite), they should both behave in the same way with the same config.

#### Actual behaviour
> The axis on the right (opposite) is not positioned correctly

#### Live demo with steps to reproduce
http://jsfiddle.net/f5hrL6za/1/

#### Affected browser(s)
All browsers
Highcharts 6

**Comment by pawelfus** [comment]
Hi @pepijnolivier 

Thank you for reporting this issue. This is caused by different rotation - config is not the same, for the left yAxis, `title.rotation` is **270** and for the right yAxis, default rotation is **-270**.  I think you should set `"textAlign": "left"`: http://jsfiddle.net/f5hrL6za/5/ to get text inside the container.

**Comment by pepijnolivier** [comment]
@pawelfus Thank you !
