### ISSUE TITLE
setExtremes before redrawing is ignored if data is changed

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#7632]
#### Expected behaviour
After clicking the button extremes should be set by setExtremes (1 - 4).

#### Actual behaviour
Method setExtremes is ignored, extremes is set to dataMin and dataMax (1 - 2).

#### Live demo with steps to reproduce
Go to: http://jsfiddle.net/BlackLabel/3ddhgnsq/1/
Click '1 - 4' button

#### Affected browser(s)
All browsers

**Comment by TorsteinHonsi** [comment]
When we disable the navigator and the scrollbar it works as expected: http://jsfiddle.net/3ddhgnsq/2/

**Comment by pawelfus** [comment]
*Internal note:*
It's an issue with `modifyBaseAxisExtremes`: 

https://github.com/highcharts/highcharts/blob/10e70a55871f0d473f8250ea5c730b98c71b8cc9/js/parts/Navigator.js#L1849-L1852

Where `stickToMin` and `stickToMax` use `dataMin` and `dataMax`. In this case, `setExtremes(min, max)` has `max` > `dataMax`, so it's changed. Possible solution is to disable this sticking to min/max when `setExtremes()` is called:

```
			unmutable = baseXAxis.eventArgs &&
				(
					baseXAxis.eventArgs.trigger === 'rangeSelectorButton' ||
					baseXAxis.eventArgs.type === 'setExtremes'
				);
```

@oysteinmoseng - what do you think?

**Comment by oysteinmoseng** [comment]
@pawelfus Agree, I don't think stickToMin/Max makes sense for a setExtremes case. But I don't know if we somewhere rely on sticking to also work when calling setExtremes internally, so we would need to test it extra well. This should maybe be refactored, really. Logic is getting a bit messy here.

**Comment by pawelfus** [comment]
@oysteinmoseng maybe the other way around: `stickToMin` and `stickToMax` should be applied only when changing/adding the dataset, right? But I think following this way can cause more issues.. 

Internally `setExtremes()` called in (just checked `highstock.src.js`):

Highcharts:
- `chart.zoom`
- `chart.pan`

Highstock only:
- on `scrollbar.changed` event
- on `navigator.shades.mousedown` event
- on `mouseUp` (e.g. releasing navigator's shades)
- on `rangeSelector.click`  event (already resolved by `unmutable` variable)
- on rangeSelector's input change

**Comment by oysteinmoseng** [comment]
@pawelfus I don't think calling `setExtremes` should implicitly alter the extremes that are being set, I think it is cleaner then to call `setExtremes` with corrected (sticky) extremes. But maybe I am misunderstanding something.

@TorsteinHonsi Any thoughts?

**Comment by TorsteinHonsi** [comment]
The intention of this logic is:

* When the navigator is all the way to the right and new data is appended, stick to the max.
* When the navigator is all the way to the left and new data is appended, stick to the min.
* Otherwise, adapt to the extremes.

So, in short, it is only intended for updating data, not setting extremes.

**Comment by TorsteinHonsi** [comment]
I had to revert this now right before releasing v6.0.5, because it broke a sample:

* Load [stock/demo/dynamic-update](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/dynamic-update/)
* Drag the navigator window all the way to the left.
* The window width should now be constant, but instead the max is fixed, so eventually it shrinks into zero and the data disappears.

I haven't been able to capture this scenario in unit tests though, so when committing a new fix, that case should be added to tests.

**Comment by LaniMoo** [comment]
Any plans on fixing this?

**Comment by pawelfus** [comment]
Hi @LaniMoo 

No ETA for this issue at this moment. Fixing this issue causes other errors, so we need to look for an alternative solution..

**Comment by LaniMoo** [comment]
So is the following the most optimal workaround in the meantime?

1. Set extremes
2. Redraw
3. Update data
4. Redraw

Or are there other suggestions?

**Comment by KacperMadej** [comment]
@LaniMoo 
1. update data with redraw
2. set extremes with redraw
http://jsfiddle.net/BlackLabel/3ddhgnsq/59/
