### ISSUE TITLE
Polar chart y-axis label remains visible when all data series are hidden

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts#7661]
#### Expected behaviour

All text elements of the polar chart (except for the legend) should be hidden if no data series is displayed anylonger

#### Actual behaviour

The y-axis label remains visible

#### Live demo with steps to reproduce
https://www.highcharts.com/demo/polar-wind-rose

Hide all data series and you'll notice that the y-axis label remains visible

#### Product version

Highcharts current version

#### Affected browser(s)

All

![bildschirmfoto 2018-01-13 um 09 23 48](https://user-images.githubusercontent.com/12996815/34904325-e97310a4-f843-11e7-93d5-e6daf8e90a90.png)

**Comment by pawelfus** [comment]
Hi @skuske 

This is caused by default setting for [`yAxis.showEmpty`](https://api.highcharts.com/highcharts/yAxis.showEmpty). Set this option to `false`: http://jsfiddle.net/61mk6te4/1/ (note: label comes from `yAxis` but line comes from `xAxis`, so both `showEmpty` options are set to false in my demo).
