### ISSUE TITLE
WorldCloud fontSize change after recreating the chart

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#7682]
#### Expected behaviour
FontSize should be constant with the same data and container size 

#### Actual behaviour
After recreating the chart fontSize is changing. 

#### Live demo with steps to reproduce
http://jsfiddle.net/y7mt22q2/3/

Try to recreate the chart few times by clicking on the button.

#### Product version
Highcharts 6.0.4

#### Affected browser(s)
All

**Comment by stegmai** [comment]
Is there any time schedule available for this bug?

**Comment by KacperMadej** [comment]
@stegmai 
There's no ETA for the fix for now.

How urgent is the problem for you? We could try preparing a workaround for you before the official fix will be implemented in the core, so if you would like that and have any more info for the case please reply.

**Comment by stegmai** [comment]
For a reliable reporting, this is very crucial for us. At least a sustainable workaround would help us a lot. I think the requirements are well defined - do you need further input?

**Comment by jon-a-nygaard** [comment]
Hi @stegmai,

The issue was caused by [`getRotation` which is using `Math.random`](https://github.com/highcharts/highcharts/blob/dc3bb38fc21767507aad02b365176d5f2ca566b0/js/modules/wordcloud.src.js#L228) to decide the rotation of a point. Different rotations will alter the position of the points, thus making the scaling of the visualization different between each rendering.
This unfortunate behaviour will likely be updated and removed in next maintenance release.

In the mean time the following workaround should solve the problem:
[Workaround using a custom placementStrategy](http://jsfiddle.net/d6jcx8jL/)

Please let us know should you need anything else.

Best regards
Jon
