### ISSUE TITLE
Ignored spacingBottom after update in highstock

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#7684]
#### Expected behaviour
The chart should look like in case without update.

#### Actual behaviour
The legend keep the right position, but the rest of the chart elements do not.

#### Live demo with steps to reproduce
https://jsfiddle.net/ppotaczek/paukpyjs/

#### Product version
Master branch, (6.0.4)
#### Affected browser(s)
All

**Comment by pawelfus** [comment]
It's a regression since 6.0.0, in v5 it used to work fine: https://jsfiddle.net/BlackLabel/paukpyjs/1/

@sebastianbochan

**Comment by TorsteinHonsi** [comment]
Fails since 7d293dbb5, which kind of makes sense since that commit deals with `extraBottomMargin`.

**Comment by TorsteinHonsi** [comment]
The problem is that the range selector defines its own wrap for `chart.update`, and modifies the margin and spacing options.

https://github.com/highcharts/highcharts/blob/2afa6288e2e5a79a70ff27e00d7a2e08cb46964e/js/parts/RangeSelector.js#L1392-L1424

It is not recommended to mutate the options, as this issue demonstrates. The `Chart.update` function is designed to look for `update` functions on each of the chart objects, so the recommended approach would be to add a `RangeSelector.update` function. Then all `Chart.update` calls having the `rangeSelector` property would be channeled there. Also the purpose of mutating `marginBottom` and `spacingBottom` is not clear. Probably the whole logic should be refactored so that we can find the margin and spacing when we need it, regardless of whether it is after an update or not.

@sebastianbochan Any comments?

**Comment by sebastianbochan** [comment]
The update is wrapped for situation when we update rangeselector and move from top to the bottom.
I agree that we need to refactor it in the closest future.

**Comment by TorsteinHonsi** [comment]
I'm afraid not - @sebastianbochan have you had time to look at this?

**Comment by sebastianbochan** [comment]
Unfortunately not yet, cause I fixed some other issues.

**Comment by jb3-2** [comment]
Hi all, is there any timeline for fixing this? I need to plan upgrading to Highcharts 6, and this is a showstopping problem for us. Thank you guys for all your excellent work!

**Comment by sebastianbochan** [comment]
@TorsteinHonsi 
It seems that replace merge with `chart.setSize()` solves the problems. 

`
addEvent(Chart, 'update', function (e) {

	var chart = this,
		options = e.options,
		rangeSelector = chart.rangeSelector,
		verticalAlign;

	this.extraBottomMargin = false;
	this.extraTopMargin = false;

	if (rangeSelector) {

		rangeSelector.render();

		verticalAlign = (options.rangeSelector && options.rangeSelector.verticalAlign) || 
						(rangeSelector.options && rangeSelector.options.verticalAlign);

		if (!rangeSelector.options.floating) {
			if (verticalAlign === 'bottom') {
				this.extraBottomMargin = true;
			} else if (verticalAlign !== 'middle') {
				this.extraTopMargin = true;
			}
		}

	}
	chart.setSize();

});
`

Let me know if its acceptable or should I find better solution.

**Comment by jb3-2** [comment]
Hi, is this already in production in the current version 6.0.7? Thanks! J.

**Comment by KacperMadej** [comment]
Hi @jb3-2 

No, it will be added to next release. You can test current next release candidate using `https://github.highcharts.com/highstock.js`

Demo: https://jsfiddle.net/BlackLabel/paukpyjs/5/ (and OP's demo works too, since it uses the github's master - next release candidate - code)

**Comment by jb3-2** [comment]
Thanks, fixed in 6.1.0.
