### ISSUE TITLE
First Week duplication in Gantt Charts

### ISSUE THREAD

**Issue by amber-workxpress** [highcharts/highcharts#7695]
#### Expected behaviour

Weeks in the calendar should only appear once and be correctly labeled; all days should be the same size

#### Actual behaviour

Some weeks appear to be incorrectly duplicated. In my example, Week Five (the first week where there are any tasks) is duplicated. This appears to be a labeling issue, as it does correctly go from Monday (02/05/2018) to the Friday of the next week (02/16/2018).  It is difficult to immediately tell if the second task displays appropriately (it is supposed to run from 02/19/2018 to 03/02/2018), as the actual date is not displayed in the chart, only the week of the year (which does not seem to match up to either date.)

As an additional comment: I notice that in the official example for Gantt charts given, the actual start and end days appear when hovering over the bar, but in my replicated example, it does not. I'm unclear as to why. Our setup involves Gantt charts generated from dynamic data, and our date processing is done internally using momentjs. However, my understanding is that the dates are expected to be passed in as a Unix ms timestamp, which these values match up to; I am unsure why they are not being displayed appropriately.

Beyond that, the Monday box of the first Week 5 instance is oddly squished; the rest of the boxes have a consistent size, but this one does not.

#### Live demo with steps to reproduce
[https://jsfiddle.net/amber_workxpress/upubLLpm/1/](https://jsfiddle.net/amber_workxpress/upubLLpm/1/)

#### Product version
Highcharts Gantt Alpha

#### Affected browser(s)

Google Chrome

**Comment by KacperMadej** [comment]
Hi @amber-workxpress,

Thank you for reporting. I'm not sure that this is a bug.

Axis is adjusted to data, so you can add more options to chart to change this.
One option is to set `min` or `max` for axis.
Another option is to use `minPadding` or `maxPadding`.

Here's a demo with both - `min` set on axis to show full day and `maxPadding` added to show more space on right side of the chart: https://jsfiddle.net/BlackLabel/n1hw5u8a/

**Comment by pawelfus** [comment]
Hi @amber-workxpress 

Thank you for using Highcharts Gantt! And for the issues you reported.

Let me start explanation with the tooltip issue. Official demo uses points that start and end at 00:00:00, which indicates full days. You data points start at 15:00:00 and end at 23:00:00. In that case, tooltip chooses the format for dates to be hour-based. You can modify what is displayed in the tooltip using `dateTimeLabelFormat`: https://jsfiddle.net/BlackLabel/upubLLpm/2/

That also explains this issue:

> Beyond that, the Monday box of the first Week 5 instance is oddly squished; the rest of the boxes have a consistent size, but this one does not.

Point starts at 15:00:00, so Monday is not fully displayed. Actually Fridays (Week 8) is also squashed a bit, because ends at 23:00:00.

Regarding week number, I think week numbers have offset, for example: 

> `> Highcharts.dateFormat('%W', 1517842800000);`
> `> 5`

And using solution from [this SO question](https://stackoverflow.com/questions/6117814/get-week-of-year-in-javascript-like-in-php):
> `> getWeekNumber(new Date(1517842800000))`
> `> [2018, 6]`

So this one looks like an issue @TorsteinHonsi

**Comment by amber-workxpress** [comment]
Thank you for the clarifications! I hadn't found any of that in the documentation, so I wasn't sure if it was correct behavior. Thank you as well for confirming that the week duplication does appear to be the result of an issue.

**Comment by oysteinmoseng** [comment]
This seems to be working as expected now, so closing this. Feel free to reopen if there are still issues.
