### ISSUE TITLE
Solidgauge arc path's fill attribute is 'none' if no colours are defined in yAxis stops in styled mode (no fill in SVG export)

### ISSUE THREAD

**Issue by RainerSchwarze** [highcharts/highcharts#7703]
#### Expected behaviour

SVG export of solidgauge chart should show filled arc in styled mode (when yAxis stops is not used)

#### Actual behaviour

SVG export of solidgauge shows no arc (fill is none) in styled mode (when yAxis stops is not used)

#### Live demo with steps to reproduce

http://jsfiddle.net/n3o6k5cq/1/
- (this has yAxis stops disabled)
- right click on blue arc
- select "Inspect Element"
- note how the fill attribute of the path element is set to 'none'

http://jsfiddle.net/n3o6k5cq/
- (this has yAxis stops enabled and the fill is there)

#### Product version

- Highcharts v5 and latest v6

#### Affected browser(s)

tested in latest Chrome

#### Notes

In solid-gauge.src.js `toColor` is initialized from yAxis and subsequently set from point.color or series.color (if these are there). Since in styled mode, none of these are set, toColor turns out to be 'none' and further down is set like this.

The SVG export inlines styles, but does not override the fill 'none' attribute.

**Comment by pawelfus** [comment]
Hi @RainerSchwarze 

Thank you for reporting this bug - or actually bugs! With enabled `yAxis.stops` it gets even better: http://jsfiddle.net/BlackLabel/n3o6k5cq/2/ - exported image has proper colors, but interactive chart still use blueish color. I said bugs, because we have two:

1. Issue with mismatching colors exporting vs generated image (see note below)
2. Issue with `none` fill for gauge

**Workaround:**
If chart doesn't have live updates, or animations are disabled, then we can replace attribute with css style: http://jsfiddle.net/BlackLabel/n3o6k5cq/3/ and http://jsfiddle.net/BlackLabel/n3o6k5cq/4/

```javascript
(function(H) {
  H.wrap(H.seriesTypes.solidgauge.prototype, 'drawPoints', function(p) {
    var ret = p.apply(this, Array.prototype.slice.call(arguments, 1));

    H.each(this.points, function(point) {
      if (point.graphic) {
        var color = this.yAxis.toColor(point.y, point);

        point.graphic.element.removeAttribute('fill');

        if (color !== 'none') {
          point.graphic.css({
            fill: color
          });
        }
      }

    }, this);

    return ret;
  });
})(Highcharts);
```

*Internal note:*
First issue is a problem with attributes vs styles precedence: 

- (lowest) attributes
- general styles
- (highest) inline styles

**Comment by RainerSchwarze** [comment]
@pawelfus Thanks - especially for the workaround.

(While we're at solid gauge: While looking into this I noticed, that the demo at https://www.highcharts.com/demo/gauge-solid fills the rounded attribute up with NaN: `<path ... rounded="NaNNaN..."`. Right click on the arc, inspect element and observe the rounded attribute of the path element.)

**Comment by pawelfus** [comment]
Thanks! Note: Setting `rounded: false` resolves the issue, so probably we have an error with default value: http://jsfiddle.net/BlackLabel/mzb7ymtg/
