### ISSUE TITLE
Browser freezing when tickInterval and label step are set using arearange

### ISSUE THREAD

**Issue by mir3z** [highcharts/highcharts#7706]
#### Expected behaviour
Working arearange chart with tick on each day and label on every 5th tick.

#### Actual behaviour
I'm using arearange chart. What I want to achieve is:
* show tick every single day
* show label every 5th tick

This is the relevant part of the config I'm using:
```
    xAxis: {
        type: 'datetime',
        labels: {
        	step: 5
        },
        tickInterval: 1
    }
```

Browser is freezing or crashing ("Aww, snap" page in Chrome) when `xAxix.labels.step` and `xAxis.tickInterval = 1` are set.

#### Live demo with steps to reproduce
http://jsfiddle.net/8zw39e0L/3/ - uncomment `xAxis.labels.step` property

#### Product version
Latest, 5.0.4

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Hi @mir3z 

`step` is based not on datetime values, but on integers, so for datetime type axis it uses milliseconds.
Setting `step` to `5` will tell chart to try show every 5th millisecond and you might not have enough CPU to handle this. Even bigger values demand calculating smaller steps, so it's not useful for datetime type axis.

Instead of `step` use [`units`](https://api.highcharts.com/highcharts/xAxis.units) and minorTicks. Demo: http://jsfiddle.net/BlackLabel/yovowkxg/.

**Comment by mir3z** [comment]
Thanks for clarification. It works fine!

**Comment by mir3z** [comment]
Ok, but is there a way to keep labels always in the same positions? 

![image](https://user-images.githubusercontent.com/1816692/35392363-ea6bfb40-01e1-11e8-91b4-02016a9bc435.png)

![image](https://user-images.githubusercontent.com/1816692/35392408-0e66deb6-01e2-11e8-9930-cc77e4351a3b.png)

Now they seems to be placed randomly. On the first screenshot they are on each wednesday, and on the second - on each monday. I would labels starts always from the 5th tick for instance.

**Comment by KacperMadej** [comment]
@mir3z 
It's possible to set `tickInterval` to `1` day and then use `labels.step` set to `5`. Demo: http://jsfiddle.net/BlackLabel/6ccz7e0w/
