### ISSUE TITLE
Heatmap in Firefox: Enabled data labels are hidden for odd row numbers

### ISSUE THREAD

**Issue by andi1984** [highcharts/highcharts#7733]
#### Expected behavior

All labels in all rows should be shown when `dataLabels.enabled` is set to true.

#### Actual behaviour

Just the labels in the even rows are shown

#### Product version
6.0.4

#### Affected browser(s)
Firefox 58, 59

![screen shot 2018-01-26 at 12 10 40](https://user-images.githubusercontent.com/1077917/35437352-52285020-0292-11e8-8789-c866a1954c5c.png)

![screen shot 2018-01-26 at 12 14 50](https://user-images.githubusercontent.com/1077917/35437404-8f56d462-0292-11e8-8fc5-5eede576cf89.png)

**Comment by andi1984** [comment]
It seems that the height of the cells is causing it. When I increase the visual height of each cell the values are shown again. But I don't see why there should be a potential overlapping or layout issue when rendering the numbers in the same size on the odd rows as they fit fine in the even rows as well. Can you check your conditionals _when exactly_ you decide to hide the labels? Seems not optimal too me.

**Comment by pawelfus** [comment]
Hi @andi1984 

Thanks for reporting this issue. Labels are hidden because of the [padding](https://api.highcharts.com/highcharts/plotOptions.series.dataLabels.padding) - which by default is set to 5. You can decrease this padding, or even set it to 0, and overlapping algorithm will render more labels. Actually you can even disable this algorithm: https://api.highcharts.com/highcharts/plotOptions.series.dataLabels.allowOverlap

**Comment by andi1984** [comment]
@pawelfus Thanks for the fast feedback. I just don't know why it just not works in FF, but e.g. with Chrome with the same Highchart settings. So I guess there is some difference in this algorithm based on the browser. So maybe you can check that.

**Comment by pawelfus** [comment]
This is caused by different browsers engines which returns different heights for the same text element, for example: http://jsfiddle.net/BlackLabel/ntswst9z/1/ - on my machine Chrome reports 20px, but FF 21px.
