### ISSUE TITLE
setData breaks order of column chart grouping

### ISSUE THREAD

**Issue by igorrKurr** [highcharts/highcharts#7734]
#### Expected behaviour
When I change data by remove first item for first serie and use `setData` to update, I should see 
corresponding column for first item of second serie on the same position as it was before change.
#### Actual behaviour
When I change data by remove first item for first serie, I see corresponding column for first item of second serie moved to the end of the chart, initial data order is broken.

#### Live demo with steps to reproduce
http://jsfiddle.net/q7wr4zmg/4/

#### Product version
Highcharts v6.0.4
#### Affected browser(s)
Chrome Version 66.0.3331.0
Chrome Version 63.0.3239.132
Firefox 50.0

**Comment by pawelfus** [comment]
Hi @igorrKurr 

I think this works as expected. First element in the first dataset starts with "b" category, so this category is first on the chart. If you change order of the series: http://jsfiddle.net/BlackLabel/q7wr4zmg/5/ you will get the same order as initially, because first point in the series has "a" category.

You can control easily which category's position by setting `xAxis.categories` and setting `x` value for each point, demo: http://jsfiddle.net/BlackLabel/q7wr4zmg/6/

**Comment by igorrKurr** [comment]
Hi @pawelfus 

Thanks for your answer, you're absolutely right. It works as expected, I just mixed some different cases and missed what data was passed in example.
