### ISSUE TITLE
Broken chart with Google Chrome when data is defined in a HTML table and a label contains a number greater than 31

### ISSUE THREAD

**Issue by htrex** [highcharts/highcharts#7752]
With Firefox and Edge there's no problem, while using Chrome 64.0.x on 3 different hosts (Linux, Windows, OSX) I'm seeing a broken chart.

Please, have a look at this link http://jsfiddle.net/L6q2wztm/
it contains an exact copy of the Highcharts example "LOADING FROM A HTML TABLE",
except for the first data label, which I've changed from "Apples" to "Apples 2016".
That page uses https://code.highcharts.com so the libraries are the latest versions.

On Chrome 64.0.x, it seems that adding a number to the label triggers something that forces the series to be interpreted as time based, except when the number is 31 or smaller. Adding a number greater than 31 preceded from a space character to the label triggers the bug, if I add an _ character after the number workarounds the bug.

Seems something that needs to be fixed.
For the moment, can please someone suggest if there's an Highcharts option to force it not interpreting the data as time based?

**Comment by htrex** [comment]
I've found the workaround, needed to add 
```
{
    xAxis: {
            type: 'category'
    }
}
```

**Comment by pawelfus** [comment]
Hi @htrex 

Thank you for reporting the issue. It's caused by `Date.parse` implementation in browsers, for example:

- Chrome:

  - `new Date('Apples 2016')` returns `Fri Jan 01 2016 00:00:00 GMT+0100 (CET)`
  - `new Date('Apples 16')` returns `Invalid Date`

- Firefox:

  - `new Date('Apples 2016')` returns `Invalid Date`
  - `new Date('Apples 16')` returns `Invalid Date`

If you won't set `xAxis.type` explicite, then Highcharts will try to guess, based on data, what your data contains. Well, since Chrome says `new Date('Apples 2016')` is a correct Date format, I'm not sure if we should argue with that ;)

**Comment by htrex** [comment]
Hi @pawelfus, I've submitted the bug to the chromium project here https://bugs.chromium.org/p/chromium/issues/detail?id=807270 let's see how it goes.
