### ISSUE TITLE
PDF offline export issue

### ISSUE THREAD

**Issue by MuraliKaliappan** [highcharts/highcharts#7774]
#### Expected behaviour
When exporting.customButton.symbol is provided with url image, download pdf should use jspdf.js and svg2pdf.js provided in libURL path instead of highcharts export server.

#### Actual behaviour
When offline-exporting is used with libURL, download pdf is still using highcharts export server instead of using jspdf.js and svg2pdf.js provided in libURL. This happens only when custom button is provided in exporting option with symbol pointing to url image. When symbol:'circle' is given it is working as expected.

#### Live demo with steps to reproduce
https://jsfiddle.net/MuraliKaliappan/77pcbvph/3/

#### Product version
highstock 6.0.4,exporting 6.0.4 ,offline-exporting 6.0.4

#### Affected browser(s)
chrome

**Comment by oysteinmoseng** [comment]
@MuraliKaliappan Your jsFiddle does not seem to be available, but I think this is an issue with using HTML in offline exporting. Because this requires use of the <foreignObject> SVG tag, we fall back to the online export server. This is due to both CanVG and svg2pdf failing on <foreignObject> tags.

CanVG doesn't seem to want to implement support for this (https://github.com/canvg/canvg/issues/149), and svg2pdf has a similar attitude (https://github.com/yWorks/svg2pdf.js/issues/15).

Is running your own export server locally an option? This is made easy with our new node export server, and would give you full exporting capabilities without using our hosted server: https://www.highcharts.com/docs/export-module/setting-up-the-server

**Comment by MuraliKaliappan** [comment]
check out this https://jsfiddle.net/MuraliKaliappan/rs88kLw3/1/

**Comment by oysteinmoseng** [comment]
@MuraliKaliappan This is actually not a problem with `<foreignObject>`, but a similar issue with image tags with base64 sources in svg2pdf. We block charts with embedded images from being exported offline, as svg2pdf struggles a bit with these, particularly with transparent backgrounds. You can force basic offline export like this: http://jsfiddle.net/2578sz52/.

Note that the exporting buttons are never included in the exported chart.
