### ISSUE TITLE
Candlestick bars and gaps have apparently random width while zooming in

### ISSUE THREAD

**Issue by dandv** [highcharts/highcharts#7782]
#### Expected behaviour

When I zoom into the [lazy loading example](https://www.highcharts.com/stock/demo/lazy-loading), I expect the bar size to stay more or less the same. Or perhaps the bars could get wider as I zoom in, but they shouldn't go from _narrow_ to _wide_ back to _narrow_, because the data is uniformly spaced in time ("history by the minute").

#### Actual behavior

![candlestick bar width varies while zooming in](https://user-images.githubusercontent.com/33569/35722611-dc824b9a-07ab-11e8-9308-952c5caae8c1.gif)

#### Live demo with steps to reproduce
http://jsfiddle.net/b4ne51ta/9/

The behavior is reproduced both with `dataGrouping: { enabled: false }` and without it.

If this is expected, I'd like to understand the reason, and whether a workaround exists. Thanks!

**Comment by pawelfus** [comment]
Hi @dandv 

Yes, this is expected behaviour. If you look closer to the x-values in the tooltip you will see that before zoom, monthly data is loaded. After 1-2x zoom, data granularity is changed to one day, then to one hour and zooming even further, you will see that point base on a minute distance. For example zooming from eight hours into one hour will change resolution from hour to minute as it would make no sense to display just one point. 

Check also our [article](https://www.highcharts.com/blog/news/48-loading-millions-of-points-in-highcharts/): 

>  In the event handler we show a loading screen, then send off the new extremes to the server. The server then chews through this information, decides which resolution it should go for, selects the data and sends it back. Client receives it, hides the loading screen and sets new data to the series.
