### ISSUE TITLE
SVG renderer text disappears when useHTML is true

### ISSUE THREAD

**Issue by NeuwenWolf** [highcharts/highcharts#7812]
#### Expected behaviour with useHTML at default (false)
http://jsfiddle.net/tovzk88u/8/
"A QUICK&nbsp;TEST" should appear on the chart (and it does).
#### Actual behaviour with useHTML set to true
http://jsfiddle.net/tovzk88u/9/

#### Product version
current stable (6.05)

#### Affected browser(s)
only tested in Chrome

#### Additional notes
It's possible I'm simply misunderstanding the documentation, if so, please let me know where I'm going wrong.

**Comment by pawelfus** [comment]
Hi @NeuwenWolf 

Thank you for reporting this bug. It's a regression since v6.0.5, with version v6.0.4 this works fine: http://jsfiddle.net/BlackLabel/tovzk88u/11/

**Workaround:**
Set `translateY` for the text: http://jsfiddle.net/BlackLabel/tovzk88u/12/

*Internal note:*
It's related (or even duplicate) to #7787

**Comment by NeuwenWolf** [comment]
Thanks for the workaround!
