### ISSUE TITLE
No export to PDF on IE11 in iframe

### ISSUE THREAD

**Issue by oysteinmoseng** [highcharts/highcharts#7824]
Following up from #6256.

There appears to be issues with exporting to PDF (and other formats?) when the chart is inside an iframe on IE11.

Quote @KacperMadej: 

> I was able to recreate the problem with basic exporting - not the offline-exporting, just exporting module. It looks like the form is not submitted correctly when called from an iframe. In the JSFiddle a demo is not working, but exporting works well with the same chart placed on highcharts.com/demo. Nothing happens when trying to export. When debugging - all runs fine, no error, submitting the form does nothing. (IE11.125.16299.0 / Win 10)

I was unable to reproduce the issue with IE 11.0.9600.18349.

Demo: http://jsfiddle.net/nbcqcfxq/

**Comment by KacperMadej** [comment]
I have used a simpler demo (https://jsfiddle.net/BlackLabel/ok7p60s8/).
JSFiddle throws some errors about loaded scripts that are not related to the issue, but this might be related to IE11 Internet options / security.

Tested on localhost and if the chart is loaded in iframe, then exporting sends request, server sends proper reply (tested on export.highcharts.com and on local node-exporting-server), communication ends with status 200, all is fine, but file save pop up doesn't show and file is not saved.

Also recreated on Win 8.1 / IE11 version 11.0.9600.18894 - for the simple HTML site with iframes, but not when using JSFiddle demos.

I will try to check with MS if there's any browser / OS option that might cause this problem.

**Comment by tarunchopra91** [comment]
Any update ?

**Comment by KacperMadej** [comment]
I have suggestions to change internet security, browser options (full debugging - on all errors, log into developer tools console at all times, etc.), but I see no difference. Problem is there, no error is seen, file is not loaded - no dialog window shows to ask about saving or opening the file.

To make sure you have the same problem please try exporting from the demo site here: https://www.highcharts.com/demo/line-basic

The issue is only with iframe, so e.g. [the JSFiddle demo](https://jsfiddle.net/BlackLabel/ok7p60s8/) when using IE11 (other IE version not tested).

I'll add another comment here if I will have more related info, or a solution, or if MS support will give up on me.

**Comment by tarunchopra91** [comment]
The demo link "https://www.highcharts.com/demo/line-basic" works fine, as the chart is not in any iframe. But in my case the chart is in a iframe.

Any update so far for. ?

**Comment by sebastianbochan** [comment]
Hi @tarunchopra91,
Could you point me out how we can replicate your scenario? Is it possible to supply is a live demo? Without that we are not able to reprocude the issue and find a reason.

**Comment by rajeshdanabal** [comment]
Is there any update in this issue or workaround?

**Comment by KacperMadej** [comment]
No update for the issue - I have not received any useful information from MS support. Resetting everything doesn't help.
A workaround is to don't use iframes in IE11 if you want to export files.
