### ISSUE TITLE
Annotations are displaying incorrectly after zooming a chart.

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#7826]
#### Expected behaviour

Annotations which aren't in current selection range should be invisible.

#### Actual behaviour

Annotations which should be invisible after zoom to certain selection, instead they are moved to the edge of plotArea (shapes on the left side, labels on the right).

It occurs only when there is a big amount of data points.

#### Live demo with steps to reproduce
[http://jsfiddle.net/BlackLabel/jzqdmvwt/](http://jsfiddle.net/BlackLabel/jzqdmvwt/)
1. Zoom chart.

#### Occurence

**v6.0.4** and below
From **v6.0.5** all annotations are **hidden**.

**Comment by KacperMadej** [comment]
The problem with wrong display out of visible range was resolved in 6.0.5 version.

**About current (6.0.6 version):**
Markers needs to be enabled to show the annotations in the current (6.0.6) version.
http://jsfiddle.net/BlackLabel/jzqdmvwt/1/

Is the limitation to an existing marker intentional? If yes, docs should be updated. If no, then this is a bug. @morganfree ?

**Comment by morganfree** [comment]
@KacperMadej, it's a regression bug. I will fix it.

**Comment by manometer114** [comment]
Thank you everybody for the quick fix!
