### ISSUE TITLE
bug with group by year

### ISSUE THREAD

**Issue by Shaidulint** [highcharts/highcharts#7827]
#### Expected behaviour
Column stockchart with grouping data ( by days, weeks, months, years) implemented using rangeSelector

#### Actual behaviour
First click on button Year for group by year makes chart empty.
Second click add one column by 2017 year and empty column (without data) by 2018 year.
I do not transfer data for 2018 to incoming data

#### Live demo with steps to reproduce
http://jsfiddle.net/upm6uckL/4/

#### Product version
highstock 6.0.6

#### Affected browser(s)
Chrome, IE

**Comment by KacperMadej** [comment]
Hi @Shaidulint 

Thank you for reporting about the problem.

Clicking the 'year' button again resolved the problem. The time range is set from Aug 1, 2017 to Now 1, 2017 after clicking the 'year' button - might be something wrong in the extremes calculations.

**Comment by pawelfus** [comment]
Note: We have two issues here:

- On the first click, column is missing: this is a bug and will be fixed.
- On the second click, we have 2018 label on the chart: this issue is related to the given dataset, let's consider: http://jsfiddle.net/BlackLabel/upm6uckL/49/ - now data is inside Q2 instead of Q4 and 2018 year does not show up. In general, what we see on the chart with just one point is basically a range: 01.01.2017 - 18.04.2017. But we need to remember that column type series adds extra padding on the left and right sides. If last point in the dataset will be near end of 2017 (like in the original dataset: 01.11.2017)) and we add some extra space, then 01.01.2018 will be inside the current view. Actually, bug here is 2018 label **not showing up** on the first click. I think `xAxis.labels` should be filtered out by [`xAxis.tickPositioner`](https://api.highcharts.com/highstock/xAxis.tickPositioner) or [`xAxis.labels.formatter`](https://api.highcharts.com/highstock/xAxis.labels.formatter).
