### ISSUE TITLE
no-data-to-display plugin works on Highcharts, breaks on Highstock.

### ISSUE THREAD

**Issue by httpete** [highcharts/highcharts#7830]
#### Expected behaviour

If I do: 

import * as Highcharts from 'highcharts';
all is fine.
if I do:

import * as Highcharts from 'highcharts'/highstock;
the no data to display breaks (no .hcData)
#### Product version

6.0.6
#### Affected browser(s)
all

**Comment by TorsteinHonsi** [comment]
Here's a functioning jsFiddle with Highstock and no-data: http://jsfiddle.net/5Lqmj6we/

**Comment by httpete** [comment]
I am using ES6 imports and Typescript to compile to ES5/commonjs. I don't know if this should make a difference, but I see it working great and not work as I show in the original ticket.

**Comment by jon-a-nygaard** [comment]
Hi @httpete,

One thing I noticed in your example is that you are using `require` statements to include `no-data-to-display` and `highcharts-more`. This caused problems for me, so I switched them out so that `import` statements are used for all includes.

Using the following setup and webpack as a bundler worked fine for me.

Should this not work for you, perhaps you could provide us with the TypeScript config you are using?

**src/app.ts**
```javascript
import * as Highcharts from 'highcharts/highstock';
import * as hcnd from 'highcharts/modules/no-data-to-display';
import * as hcmore from 'highcharts/modules/no-data-to-display';
hcnd(Highcharts);
hcmore(Highcharts);
Highcharts.stockChart('container', {
    series: [{
        data: [],
        type: 'column'
    }]
});
```

**tsconfig.json**
```javascript
{
    "compilerOptions": {
        "outDir": "./dist/",
        "module": "commonjs",
        "target": "es5",
        "allowJs": true
    },
    "include": [
        "./src/"
    ]
}
```

> It would be good if Highcharts starts distributing multiple module formats as other libs do. umd and esm would be good for certain.

Highcharts is already supporting the UMD module format, and has been since v5.
Regarding ES modules please follow #7186 for more information.

**Comment by jon-a-nygaard** [comment]
Closing this issue since it is inactive and we are unable to reproduce it. Should anyone have further information on the issue please let us know and we will consider reopening it.
