### ISSUE TITLE
inconsistent rangeselector

### ISSUE THREAD

**Issue by faststare** [highcharts/highcharts#7844]
### expected behavoir
candlestick weekly or 3 year chart should be weekly candlestick data
### actual behavoir
weekly or 3 year chart parsed in daily data. even all parsed in daily data
### code
https://pastebin.com/AJcN49Li

#### Product version
latest version

**Comment by pawelfus** [comment]
Hi @faststare 

Thanks for reporting the issue. It may be the same issue as #7823 - could you set dataGrouping options to indicator series?

Could you explain what exactly is inconsistent in rangeSelector? From your options:

```javascript
        rangeSelector: {
            selected: 3,
            buttons: [
                { type: 'month', count: 1,  text: "1M"},
                { type: 'month', count: 3,  text: "3M"},
                { type: 'month', count: 6,  text: "6M"},
                { type: 'month', count: 12, text: "D"},
                { type: 'year',  count: 3,  text: "W"},
                { type: 'ytd', text: "YTD"},
                { type: 'all', text: "ALL"}
            ]
        },
```

These buttons don't set anything related to dataGrouping, only *range on the chart* is controlled by them. For example `{ type: 'year',  count: 3,  text: "W"},` -> this will render button with text "W", and after clicking this button, will show three years of data. I mean `text: 'something'` is just displayed text, not applied dataGrouping. 

See code in action: http://jsfiddle.net/BlackLabel/90x2d56f/2/ - button "W" (three years) groups data weekly, which is even more confusing - because that's what you need, right?

**Comment by KacperMadej** [comment]
Hi @faststare 

Thank you for reporting about the problem.
This is related to or a duplicate of the issue #7823 

Live demo for the problem:
http://jsfiddle.net/BlackLabel/vw15fLfn/1/

Resolved through [Paweł's fix](https://github.com/highcharts/highcharts/issues/7823#issuecomment-364110067):
http://jsfiddle.net/BlackLabel/vw15fLfn/2/

**Comment by faststare** [comment]
yeah but I need "D" button to parse daily data of candlestick instead of weekly data based on your example. is not allowed to parse to that options?

**Comment by faststare** [comment]
update issue. it needs to forced of datagrouping in plotOptions arguments. thanks
