### ISSUE TITLE
windbarbs interfering with xAxis

### ISSUE THREAD

**Issue by Craicerjack** [highcharts/highcharts#7875]
#### Expected behaviour
Charts with the same xAxis start at the same position 

#### Actual behaviour
Charts with a windbarb component do not have the same starting position as charts without even though data and xAxis object are the same

#### Image highlighting problem
![Image of issue](https://i.imgur.com/HmMwbFf.png)

#### Product version

Highcharts 6.04

#### Affected browser(s)
all

**Comment by pawelfus** [comment]
Hi @Craicerjack 

Thank you for reporting the issue. You are correct, xAxis size is different when windbarb series is added. It's caused by arrows - if we don't add space on the left and right sides of the chart, then first/last marker can be rendered outside the plotting area.

You can prevent this by setting `series.pointRange: 1`.

If this won't help, please recreate issue in jsFiddle (you can start with this demo: http://jsfiddle.net/rgbnusr6/4/ )

**Comment by Craicerjack** [comment]
Works a charm. Thank you.
