### ISSUE TITLE
Setting categories change the width of chart

### ISSUE THREAD

**Issue by nicovak** [highcharts/highcharts#7879]
#### Expected behaviour

Define categories on xAxis should keep the same tooltip placement as default

#### Actual behaviour

Define categories change the width of chart (areaspline) even if it's the same values as default

#### Live demo with steps to reproduce

With categories, the chart doesnt fit the div

[demo](http://jsfiddle.net/sKV9d/381/)

Without categories, the chart fit the div

[demo](http://jsfiddle.net/sKV9d/382/)

#### Product version

Hightcharts 6.0.3

#### Affected browser(s)

Tested on Firefox, but I guess it is occuring for all browsers

#### Current workarround

Using tooltip `formatter` function to show it like this `categorie : value`

```js
var categories_chart = ["0", "1", "2", "3"];
var chart = new Highcharts.Chart({
  tooltip: {
    formatter: function() {
      return categories_chart[this.x] + ' : <b>' + this.y + '</b>';
    }
  },
```

**Comment by pawelfus** [comment]
Hi @nicovak 

Thank you for reporting the issue. This is expected behaviour, please take a look: http://jsfiddle.net/sKV9d/386/ - as you can see, points are centered over the categories. If you use linear xAxis, points are rendered on a tick: http://jsfiddle.net/sKV9d/387/

Alternative solution: use `tooltip.headerFormat`/`tooltip.pointFormat` and get property from a point: http://jsfiddle.net/sKV9d/394/
