### ISSUE TITLE
In boost mode points are not on the chartline on some zoom levels

### ISSUE THREAD

**Issue by benzmarkus** [highcharts/highcharts#7893]
#### Expected behaviour
On all zoom levels the points are on the chartline

#### Actual behaviour
Some points are not on the chart line.

#### Live demo with steps to reproduce
template: https://jsfiddle.net/var86693/

1) zoom to the point in this image: https://pasteboard.co/H8x70tkQ.png. Graph should be drawn in canvas mode. In SVG everthing works fine.
2) Hover over the points

If you zoom deeper the graph switch to svg and then everything is fine: https://pasteboard.co/H8x7cHM.png

#### Product version
Highcharts 6.0.7

#### Affected browser(s)
Only checked in Chrome

**Comment by benzmarkus** [comment]
useGPUTranslations is required by the customer because performance is better

**Comment by cvasseng** [comment]
It won't work correctly with `useGPUTranslations = true` unless you trim your x-axis data to not include the year (i.e. so that the values are not as high). The misalignment you're experiencing has to do with floating point precision. Because the x-axis values are very large, details are lost in rounding errors when sending the data to the GPU to be rendered. We're limited to using floating points due to WebGL, so there's no way around this. This is also documented in the [API doc entry for `useGPUTranslations`](https://api.highcharts.com/highcharts/boost.useGPUTranslations).

If you tell us more about the specific use case you have, we might be able to suggest other ways of improving your performance.

**Comment by benzmarkus** [comment]
We fixed the data on the x-axis and then it worked. Thx for the fast help!
