### ISSUE TITLE
API documentation is mum about includeInCSVExport

### ISSUE THREAD

**Issue by ghost** [highcharts/highcharts#7895]
#### Expected behaviour
includeInCSVExport is mentioned in API documentation

#### Actual behaviour
nothing there

#### Live demo with steps to reproduce
1. open https://api.highcharts.com/highcharts/
2. type includeInCSVExport into the search field
3. result: no search results

#### Product version
Highcharts

**Comment by KacperMadej** [comment]
Hi @cosycode 

Thank you for reporting about the problem.

_Internal note:_ [includeInCSVExport](https://github.com/highcharts/highcharts/blob/master/js/modules/export-data.src.js#L295) is not documented

**Comment by TorsteinHonsi** [comment]
@cosycode This option is a relic from the origin of the `export-data.js` module, when it was a plugin called `export-csv`. Before documenting it, it should be renamed `includeInDataExport` because it also applies to HTML table, ExCel and possible other types of data export.

Before we rename it and risk breaking something, where did you see it in use?

**Comment by cosycode** [comment]
I was looking myself for it, because it may have been handy for an user issue.

**Comment by cosycode** [comment]
I suggest that we rename and document it properly with Highcharts version 7.0.0.

**Comment by KacperMadej** [comment]
...right, looks like we missed this one.
How about 7.1.0 ? @bre1470
