### ISSUE TITLE
Drillup button with long text is not properly positioned in Highcharts v6

### ISSUE THREAD

**Issue by DanielRLevine** [highcharts/highcharts#7898]
#### Expected behaviour
When given the settings
```
drillUpButton: {
    relativeTo: 'spacingBox',
    position: {
        x: 0,
        y: 30
    }
```
drillup button should appear fully within the window.
#### Actual behaviour
In Highcharts v5, drillup button DOES appear fully within the window.  In Highcharts v6, drillup button overflows out of the window when its text is long.

#### Live demo with steps to reproduce
http://jsfiddle.net/LLExL/9038/

To reproduce:

1. Click on United States of America
2. Click on any state
3. The drillup button will overflow out of the window

#### Product version
Highcharts: v6.0.7
Maps Module: v6.0.7
Drilldown Module: v6.0.7

#### Affected browser(s)
Reproduced in Chrome, Firefox, and Safari.

Thank you!!!

**Comment by KacperMadej** [comment]
Hi @DanielRLevine 

Thank you for reporting about the problem.

As a workaround you could use a wrapper added in this demo: http://jsfiddle.net/BlackLabel/LLExL/9066/
The workaround is based on removing a fix for another problem that was resolved quite long ago, so it's hard to be sure if the workaround will break something important for you - pleas test it.

Related issue with the problem for which the fix is removed in the workaround: https://github.com/highcharts/highcharts/issues/7166

_Internal note:_ offending commit https://github.com/highcharts/highcharts/commit/c4fef24

**Comment by pawelfus** [comment]
Hi @DanielRLevine 

Thank you for reporting this bug. It looks like a regression, in v5 it works fine: http://jsfiddle.net/BlackLabel/LLExL/9069/
