### ISSUE TITLE
Pie / Donut charts - Connector lines get missed out on some dense chart areas

### ISSUE THREAD

**Issue by ananth-imagin** [highcharts/highcharts#7907]
#### Expected behaviour

Connector lines should be visible for all pie / donut segments.

#### Actual behaviour

Connector lines are not drawn for segments that are too small, existing in between densely populated data segments.

![image](https://user-images.githubusercontent.com/22594074/36544001-5c1ef69a-180b-11e8-90b9-bb832ce0b280.png)

#### Live demo with steps to reproduce

http://jsfiddle.net/FKawc/65/

#### Product version

6.0.7

#### Affected browser(s)

Chrome, Firefox, IE, Edge, ... (All browsers).

**Comment by pawelfus** [comment]
Hi @ananth-imagin 

Thank you for reporting the issue. This is expected behaviour. If we don't have enough space for the labels then we don't render them. Labels with the lowest values are hidden first - this can be controlled by [`point.labelrank`](https://api.highcharts.com/highcharts/series.pie.data.labelrank).

We can increase the distance to make more space for labels: http://jsfiddle.net/BlackLabel/FKawc/67/ - but it depends on the dataset.

**Comment by KacperMadej** [comment]
Additionally: the function responsible for the dataLabels distribution is Highcharts.distribute. You can override it and provide better logic if you have one. Here's a demo with simple modification (JS line 42) that changes size of the labels (when used in calculations):
http://jsfiddle.net/BlackLabel/9f5orgn4/

**Comment by ananth-imagin** [comment]
Hi @pawelfus & @KacperMadej ,

Thank you very much for the solutions!
Greatly appreciate your help.

Thanks,
Ananth
