### ISSUE TITLE
Data exporting ignores axes' `max/min` values when number of points is fewer than 301

### ISSUE THREAD

**Issue by AleksueiR** [highcharts/highcharts#7913]
#### Expected behaviour
When a `.csv` file is exported or the data table is rendered, it should include only points between `min` and `max` values specified on corresponding axes.

#### Actual behaviour
If the total number of points is 300 or fewer, exported data includes all the chart points, ignoring `max/min` values set on axes.

#### Live demo with steps to reproduce
Correct behaviour (301 points): https://jsfiddle.net/ouroborosDragon/d2gu8vn5/13/
Incorrect behaviour (300 points): https://jsfiddle.net/ouroborosDragon/Lb5qdt4c/8/

- check the table underneath the chart and compare it to the points displayed on the chart
- generate a `.scv` file and compare it to the points displayed on the chart

#### Notes
Image exports are not affected and always display only points between `min` and `max`.

#### Product version
Highcharts: 6.0.7

#### Affected browser(s)
Likely, all browser, but I checked only Chrome and IE Edge.

**Comment by pawelfus** [comment]
Hi @AleksueiR 

Thank you for reporting the issue. This is caused by [`series.cropThreshold`](https://api.highcharts.com/highcharts/series.line.cropThreshold) option. If you have more points than default 300, then only visible range is returned. If you have less points, all points are rendered and returned. Demo: https://jsfiddle.net/BlackLabel/Lb5qdt4c/9/

**Comment by AleksueiR** [comment]
Hey, @pawelfus 

Thanks for the explanation. I did look through the release notes and saw this new option, but didn't think it would affect the exporting functionality. 

Is this the intended behaviour or a side effect? If it's intended, it would be useful to mention this in the description of this option.

**Comment by pawelfus** [comment]
I think that exporting to csv should have a separate option to decide if we want to export all points or just the visible range.

**Comment by AleksueiR** [comment]
This sounds good to me.

**Comment by TorsteinHonsi** [comment]
The fix above makes the export-data module consistently return all the points (regardless of axis extremes). We can implement an option like @pawelfus suggested in addition, but now at least the behaviour is consistent.

**Comment by AleksueiR** [comment]
@TorsteinHonsi With this fix, is it possible to constrain the export-data output at all? I need to export only the visible range (when using chart zoom).

**Comment by TorsteinHonsi** [comment]
This fix only makes it consistent, we didn't implement filtering by data range. Here's a snippet you can plug in to get the desired effect:

```js
// Plugin to only run export-data on the visible range
(function(H) {
    H.wrap(H.Chart.prototype, 'getDataRows', function(proceed, multiLevelHeaders) {
        var rows = proceed.call(this, multiLevelHeaders),
            xMin = this.xAxis[0].min,
            xMax = this.xAxis[0].max;

        rows = rows.filter(function(row) {
            return typeof row.x !== 'number' || (row.x >= xMin && row.x <= xMax);
        });

        return rows;
    });

}(Highcharts));
```

See it in action at https://jsfiddle.net/d2gu8vn5/26/

**Comment by nikolas** [comment]
@AleksueiR I was also frustrated by this. This behavior is different that highcharts 5.0.x, and since all data was being returned, it was too big for Chrome to download, causing a network error. Really annoying to debug.

My fix was to change a line in `export-data.src.js`:
https://github.com/highcharts/highcharts/blob/master/js/modules/export-data.src.js#L343

Upstream version:
```
// Export directly from options.data because we need the uncropped
// data (#7913), and we need to support Boost (#7026).
            each(series.options.data, function eachData(options, pIdx) {
```

My version:
```
// Export directly from options.data because we need the uncropped
// data (#7913), and we need to support Boost (#7026).
            each(series.points, function eachData(options, pIdx) {
```

This is how the old export-csv.js works: https://github.com/highcharts/export-csv/blob/master/export-csv.js#L94
