### ISSUE TITLE
Animation for dashed line

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#7927]
#### Expected behaviour
The animation should run without additional effects.

#### Actual behaviour
The dashed line looks like it has "moving" animation.

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/7zfhqLa4/

#### Product version
All

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
It's a tough one, and I'm not sure it's worthwhile. I see two options:

 * In animation, instead of moving the leftmost point closer to the next point, move it left together with the animation. It will preserve the starting point of the `stroke-dasharray`. But it may also have side effects for all other graph animations.
* Animate `stroke-dashoffset` to always stick to the first common X value.
