### ISSUE TITLE
seriesTypeDescriptions are missing types and descriptions 

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#7940]
URL: https://api.highcharts.com/highcharts/lang.accessibility.seriesTypeDescriptions

Description is not that important, but type is required for our extensions.

**Comment by TorsteinHonsi** [comment]
@oysteinmoseng There's also a problem that the default values and types are not picked up because the string span multiple lines.

@cvasseng Is there something we can do about that to make the parser pick up multiline strings? This is a common pitfall for option defaults. Alternatively we should make the parser warn about it.

**Comment by cvasseng** [comment]
I've added support for multi-line defaults in the plugin.

Pull request: https://github.com/highcharts/highcharts/pull/7966

**Comment by cvasseng** [comment]
(also note that the `type` is correct after the plugin fix, so I think this issue is actually resolved)
