### ISSUE TITLE
Boost: Render Glitch Fill Color

### ISSUE THREAD

**Issue by tisba** [highcharts/highcharts#7964]
#### Expected behaviour

![screen shot 2018-03-06 at 19 27 45](https://user-images.githubusercontent.com/75156/37050733-f221b9c6-2174-11e8-8f4b-8b53bbae7dab.png)

(note that this is the same graph as in "Actual behaviour", but zoomed)

#### Actual behaviour

![screen shot 2018-03-06 at 19 21 06](https://user-images.githubusercontent.com/75156/37050730-eec2fa88-2174-11e8-8954-a9440b6a5b36.png)

#### Product version
Highcharts: 6.0.4

#### Affected browser(s)

Chrome: 64.0.3282.186

I'm sorry for not providing a live example, but I'm having a very hard time to simplify our charts and generate data that triggers this problem. I'm hoping that someone has some idea, how to debug this issue.

**Comment by cvasseng** [comment]
Judging from the screenshot, this may be intended behavior. Area/bar/column charts are currently drawn as vertical lines rather than as a tessellated area. This is for performance reasons. 

The idea is that `series.boostThreshold` should be set to a value that makes the SVG renderer "take over" when the point density becomes low enough for the vertical lines to be visible. 

It would be very helpful if you could post a screenshot of the issue with the x-axis labels visible, so we can get an idea on how many points are rendered when zooming in - this will help us confirm that this is indeed the issue.

On a related note, the rendering approach may change in the future to do actual areas, but there are no current plan or ETA for it.

**Comment by tisba** [comment]
The x-axis is a datetime, so it will be hard to tell the points from :)

The unzoomed (bottom) graph should be ~7200 data points. The rendering issue (I know, intended but still not desired, I'd say), seems to happen around 1000 data points. We currently have set `boostThreshold` to `1000` so that would make sense. The `boostThreshold` setting is quite old though, I believe the new default is `5000` which should at least reduce the impact a bit.

If I understand you correctly then the only workaround would be to switch to another type (e.g. line) in case boost kicks in, right?

**Comment by cvasseng** [comment]
The `boostThreshold` option specifies at what point count the boost module kicks in at. So if it's  set to`1000', it boosts when there are more than 1000 points. When the point count falls below this, the SVG renderer will take over.

So the solution is to leave the series type as-is, and instead increase `boostThreshold` so that the SVG renderer "takes over" before the zoom level reaches a point where the boost module would result in visible lines. `5000` is a good value in most cases, which is, as you said too, the current default value.

**Comment by tisba** [comment]
The default is the zoomed out version which will trigger the `5000` threshold in this case. But that won't be the case for all charts, since often times they have a lot less points.

But thank you for your input. At least I now know where too look at and what my options are.
