### ISSUE TITLE
Bubbles cut off when use logarithmic axis

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#8003]
#### Expected behaviour
The bubbles should not be cut off, the chart should behave as with other types of axes:
http://jsfiddle.net/BlackLabel/4qvja36k/2/

#### Actual behaviour
If 'logarithmic' axis type is used, the size of plotArea is not adapted to bubbles.

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/4qvja36k/

#### Product version
Highcharts v6.0.7

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
On linear axes, padding is added to the axes to make room for the extent of the bubbles. The problem comes from this line, where we decide not to apply padding to logarithmic axes because the translation is not linear:

https://github.com/highcharts/highcharts/blob/d889a2fb7bf359ceea3a55af6ce908fd405cd204/js/parts-more/BubbleSeries.js#L540

I tried making it work by instead of simply adding/substracting pixels, translate the axis value to pixels, then add/substract, then translate back to values. It create some small pixel changes to existing bubble charts that we can live with. It should theoretically work for log axes too, but currently fails. This is how far I got today:

```js
	if (activeSeries.length && range > 0) {
		pxMax -= axisLength;

		if (pick(axis.options.min, axis.userMin) === undefined) {
			axis.min = axis.toValue(
				axis.toPixels(axis.min) +
				(axis.horiz ? 1 : -1) * pxMin
			);
		}
		if (pick(axis.options.max, axis.userMax) === undefined) {
			axis.max = axis.toValue(
				axis.toPixels(axis.max) +
				(axis.horiz ? 1 : -1) * pxMax
			);
		}
	}
```

**Comment by jwh2018** [comment]
As an FYI, this works in Highcharts version 5.0.10.

**Comment by TorsteinHonsi** [comment]
Thanks for the info!

The positioning was the same in v5.0.10, but the difference is that we now clip overflowing bubbles by default. You can set the `clip` option to false though, if you accept that they overflow the plot area (plot border added to highlight the plot area): http://jsfiddle.net/highcharts/4qvja36k/7/

Another workaround would be to add a `minPadding` and a `maxPadding` to the axis, though you can't be sure how much is needed: http://jsfiddle.net/highcharts/4qvja36k/10/
