### ISSUE TITLE
Extending world.js map by several regions.

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#8006]
There is no Jersey, Bermuda islands and Hong Kong regions included in _world.js_ map.
Jersey and Bermuda are separate countries, so they should be placed on the world map. Regarding Hong-Kong it isn't simple question, but it could be qualified as a region on world map.

**EDIT:**
Also, there is no Cayman Islands, British Virgin Islands, Channel Islands and Curacao.

**Comment by KacperMadej** [comment]
The map of world is not a map of countries, so it should be possible to add some regions as long as they are not a part of the bigger region that has it's own map - then a drilldown could be used. Like with USA or German states. This is the case for Hong Kong.

We have multiple versions of world map and if this would be an optional map like we have for Palestine areas, then will that be a single map like "World with Jersey, Bermuda Islands and Hong Kong"?

Alternatively we could include all [crown dependencies](https://en.wikipedia.org/wiki/Crown_dependencies) as separate regions in all world maps and add new "World with Hong Kong".

Are there other options? What do you think about all this @oysteinmoseng @TorsteinHonsi ?

**Comment by oysteinmoseng** [comment]
I think the world maps should reflect what users want and need. Our current base-world map is a mostly a map of sovereign areas, except Greenland is separate. We try to keep a balance between including everything and keeping the map uncluttered.

Jersey is a crown dependency and not part of UK, so it makes sense to add it to all world maps.

Bermuda is part of the UK British Overseas Territories, so if we add this it should be part of the UK point (so that it is consistent with e.g. Falkland Islands). If we want to split UK into individual points, that would be a new map.

Hong Kong is technically part of China, so a map with Hong Kong separate would be a new map as well.

Of course if we want a version of the world map for every possible combination (With Hong Kong, but without Palestine, and with India with disputed territories, but with UK combined...) we will quickly end up with 100 world map versions. Ideally we would have a way to pick and choose in a sort of world map builder.

**Comment by Denyllon** [comment]
In this case I recommend to solve the problem in other way.  If user don't need to have some high resolution of map, there is possible to add separate series with points which has _lat_ and _lon_ parameters included inside their definitions. It can be called a workaround in my opinion. Here is the live example of how to achieve that:
[http://jsfiddle.net/BlackLabel/htofq9s8/1/](http://jsfiddle.net/BlackLabel/htofq9s8/1/)

**Comment by oysteinmoseng** [comment]
@Denyllon Good point, I am sure that is a perfectly acceptable solution for many users.

Note that as long as we keep the map projection the same, picking and choosing points between maps would be possible. So a user could in theory get a `world-parts.js` and add in each country they want. It should not be hard to build a simple interface on top of this if we want to prioritize it.

**Comment by jon-a-nygaard** [comment]
We have created a seperate repository for the map collection, and we are transfering the issues related to the map collection to this new repository.

Please continue the discussion and follow the future development of this issue at highcharts/map-collection-dist#20
