### ISSUE TITLE
Drill up in Sunburst demo results in top level button at the top level

### ISSUE THREAD

**Issue by ghost** [highcharts/highcharts#8037]
#### Expected behaviour

Drill up to "The World" and see no drill up button in the top right corner.

#### Actual behaviour

Drill up to "The World" and notice the drill up button for "The World" in the top right corner.

#### Live demo with steps to reproduce

1. Open https://www.highcharts.com/demo/sunburst in your browser
2. Click on Africa
3. Click on the Africa button
4. You are now in "The World" top level. Click on "The World" button and the button disappears.

#### Product version
Highcharts 6.0.7

#### Affected browser(s)
Chrome, possibly all

**Comment by jon-a-nygaard** [comment]
I understand that this behaviour looks weird, but this is expected behaviour with this dataset.
Since the first node "The World" in the visualization has no siblings, there is no visual difference by drilling down to "The World" compared to before drilling down. 

It becomes clear what is happening if we add a sibling to the world as in this example: http://jsfiddle.net/grhg9qos/2/

**Comment by cosycode** [comment]
Okay, I understand the technical reason, but for the user it is unexpected. Maybe the demo should be changed in a way, that this does not happen anymore.

**Comment by TorsteinHonsi** [comment]
Agree with @cosycode , it feels counterintuitive, so maybe we should set up the demo in a way that avoids it....................
