### ISSUE TITLE
Unable to scroll after zoom in React Native

### ISSUE THREAD

**Issue by FonDorn** [highcharts/highcharts#8053]
Hello, I use highcharts version **6.0.2** in WebView on React Native (iOS). It works perfectly, but after I zoom by X axis, scroll left/right don't work on chats, but **work** when I scroll by axis. Also this bug don't is not present in highcharts version **5.0.2** - in this version scroll work fine. Here's a capture to help understand what I'm talking about. Thanks!
![zoom_bug](https://user-images.githubusercontent.com/778724/37701683-95af6e06-2cf8-11e8-9e5c-2ac887629b21.gif)

**Comment by pawelfus** [comment]
Hi @FonDorn 

Thank you for reporting this issue. Could you share your code so we can recreate issue? From the gif, it looks like you scroll the container (I see small scrollbar at the bottom?) not the chart, is that correct? If that's the case, then I expect this issue related to #5840 and #4210). This is expected result of this change: we don't want to disable scrolling functionality on a page, unless user zooms in and wants to scroll the chart. Instead of scrolling the page, enabled panning on chart itself: [`chart.panning`](https://api.highcharts.com/highcharts/chart.panning).

**Comment by FonDorn** [comment]
@pawelfus Thanks a lot. I did not know what can move chart with two fingers after zoom in. Can you tell how touch-drag with one finger?

**Comment by pawelfus** [comment]
@FonDorn 

From [`chart.panning`](https://api.highcharts.com/highcharts/chart.panning): 

> On touch devices, when the [`tooltip.followTouchMove`](https://api.highcharts.com/highcharts/tooltip.followTouchMove) option is `true` (default), panning requires two fingers. To allow panning with one finger, set followTouchMove to `false`.

**Comment by FonDorn** [comment]
Thanks!

**Comment by varunsdcet** [comment]
I am unable to zoom Can you please help
  var k =  {

                series: [{
                   showInLegend: false,
                    data: se,
                    tooltip: {
      pointFormat: ''
    },
                }],



                xAxis: {

                        categories: date,
                        type: 'datetime',

                        labels: {
                            rotation: -65,

                        },


                    },
                    title: {
       text: 'Trend Analysis',
       align: 'center',
       y: 20 //  this to move y-coordinate of title to desired location
   },





                    yAxis: {
              allowDecimals: true,
              min: 0,
              max: 100,
              title: {
                  text: ischeck == true ? "Percentage":"Audit Score"
              }
          },
            }

this.setState({chartOptions:k})

**Comment by KacperMadej** [comment]
For technical support see https://www.highcharts.com/blog/support/
