### ISSUE TITLE
When line charts are stacked then points don't render in correct position 

### ISSUE THREAD

**Issue by webXtended** [highcharts/highcharts#8063]
#### Expected behaviour
In the 2 line charts shown in the fiddle, the fist point of line B is (-0.2, 49) and the second point is (0.8, 5)

Since there is no point 1 in line C, the 2nd point of line B is rendering above the 1st point, giving an impression that its value is higher that the 1st value.
When a value is added to 1st point in line C, then the line renders correctly.

#### Live demo with steps to reproduce
http://jsfiddle.net/qPqCW/87/

**Comment by sebastianbochan** [comment]
Hi @webXtended 
Thank you for the reporting.

It looks like the reason of it is using 0.8 instead of 1 (second point).

**Workaround:**
Use pointPlacement and move series to the left.
Demo:
- http://jsfiddle.net/BlackLabel/kcc3mma6/

**Comment by webXtended** [comment]
If the numbers don't have decimals and are just integers, still the same issue exists.
Try doing the same with x values as 1, 2, and 3

**Comment by pawelfus** [comment]
Hi @webXtended 

This is how stacking works: next point in a stack is rendered above the previous one with cumulative value. First point has value=49, second point has value=5+71.5 so it should be rendered above. The same happens when first point in "C" has value=0, see: http://jsfiddle.net/BlackLabel/qPqCW/102/ (first point in B is below the second point). Are you sure you want to use stacking on line series? See: http://jsfiddle.net/BlackLabel/qPqCW/103/
