### ISSUE TITLE
Adding and removing series dynamically on multi-axis chart causes redraw error

### ISSUE THREAD

**Issue by gbenthomas** [highcharts/highcharts#8075]
#### Expected behaviour
Adding and removing series with separate yAxis should work properly in the following steps:

1. Create yAxis1 and series1. Set series1.yAxis = 1 (index of yAxis1)
2. Update all yAxis offsets
3. Create yAxis2 and series2. Set series2.yAxis = 2 (index of yAxis2)
4. Update all yAxis offsets
5. Remove yAxis1 (and corresponding series)
6. Update all yAxis offsets
7. Create yAxis3 and series3. Set series3.yAxis = 2 (index of yAxis3 since yAxis1 was removed)
8. Update all yAxis offsets
9. Remove yAxis3 (and corresponding series)

#### Actual behaviour

In step 7 above, series3 gets associated with yAxis2 **and** yAxis3 which should not happen.
Subsequently, in step 9, redrawing causes the error (in Chrome):
Uncaught TypeError: Cannot read property 'isDirty' of undefined

Note that removing step 6 prevents this error so it seems to be related to the yAxis.update() call.

#### Live demo with steps to reproduce
http://jsfiddle.net/nrh3o8cr/

Click on the "Add/Remove Series" button which executes the steps listed above.

#### Product version
Highstock 6.0.7

#### Affected browser(s)
Chrome, Firefox, IE

**Comment by pawelfus** [comment]
Hi @gbenthomas 

Thank you for reporting this bug! 

*Internal note:*
Not related to Highstock, general issue: http://jsfiddle.net/BlackLabel/nrh3o8cr/32/

**Workaround:**
Reset indexes after each operation: http://jsfiddle.net/BlackLabel/nrh3o8cr/35/

```javascript
Highcharts.addEvent(Highcharts.Chart.prototype, 'redraw', function() {
  Highcharts.each(this.yAxis, function(axis, i) {
    axis.userOptions.index = axis.options.index = i;
  });
});
```

**Comment by jace1976** [comment]
I have done further research on the above solution and also tested other possible solutions but all these do is move the error to another part of the Highcharts update process. I think that this is largely caused by our internal code used to determine if the difference axis can be displayed. I believe in the scenario that Matt has provided that the NUMOD charting logic is incorrectly determining if a difference line can be displayed. I will need to look into this further as I am not currently sure why this is.

**Comment by jace1976** [comment]
I have found the underlying issue and it is caused by the Target variables units being incorrectly defined as "%-" rather than "%". This results in the chart expecting to display 2 series axis yet as we are also expecting to display the difference series the 2nd series axis is removed. I need to alter our code so the difference series display option checks the total axes in use and if >1 then does not allow the difference line to be plotted.

**Comment by jace1976** [comment]
I will also need to fix the logic that determines the series units as it is actually this that is causing the unexpected - to be appended. It appears that the code checks for a null and returns an empty string that is always concatenated to the unit. This has not caused an issue before as previously we did not show differences for same db comparisons and alternate db comparisons would yield the same incorrect units for both series. I will not fix this issue until I have got the chart handling multi-axis usage correctly.
