### ISSUE TITLE
Wordcloud renders different cloud everytime on refresh or reflow. 

### ISSUE THREAD

**Issue by msathis** [highcharts/highcharts#8081]
#### Expected behaviour
It should render with same details every time regardless of the chart size. 

#### Actual behaviour
It's rendering everytime with different cloud formation.

#### Live demo with steps to reproduce
http://jsfiddle.net/vpsjLraw/3/

#### Product version
6.0.7

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @msathis
Thank you for the reporting

@jon-a-nygaard

**Comment by KacperMadej** [comment]
Default internal functions used are based on getting a random place and chart size. The first can be overridden like in this demo: http://jsfiddle.net/BlackLabel/xkv06kae/ If the chart will have the same size, then placement should be always the same.

**Comment by msathis** [comment]
@KacperMadej This seems to be working as expected. Shouldn't this be the default behaviour?

**Comment by jon-a-nygaard** [comment]
This issue is an duplicate of #7682.

It has been fixed in the master branch as can be seen by this [example using latest from github.highcharts.com](https://jsfiddle.net/v2s1gLsv/).

The fix will be available in our upcoming maintenance release.
Please see the referenced issue for more information.
