### ISSUE TITLE
Zooming is choppy when using xAxis.startOnTick and endOnTick

### ISSUE THREAD

**Issue by pmccauley1** [highcharts/highcharts#8093]
The pan/zoom example referenced below works great!  However, if I add the "startOnTick: true" and "endOnTick: true" properties to the xAxis, the mousewheel zoom becomes choppy.

#### Expected behaviour
Smooth zoom in using the mouse wheel

#### Actual behaviour
Choppy zoom

#### Live demo with steps to reproduce
Start with this jsFiddle:

https://jsfiddle.net/highcharts/6etwu5b4/

Change the "xAxis" definition to this:
            xAxis: {
                type: 'datetime',
                startOnTick: true,      //new line to recreate the problem
                endOnTick: true        // new line to recreate the problem
            }

Working example here:

https://jsfiddle.net/63bcLkah/1/

#### Product version

6.0.4, 6.0.7

#### Affected browser(s)
Google chrome (at least)

**Comment by pawelfus** [comment]
Hi @pmccauley1 

Thank you for reporting the issue. As you noticed this is caused by `startOnTick` and `endOnTick` - with these options you extend extremes to nearest full tick. For example if you just zoom in a bit, then these options again will extend to the nearest tick which cause no zooming at all. If we zoom further we will see this choppy/laggy zoom because we jump into another set of nearest ticks. This is how `startOnTick` and `endOnTick` options work, I'm not sure if we can do something about this..
