### ISSUE TITLE
Bubble chart - low performance 

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#8099]
#### Expected behaviour
Performance like in scatter

#### Actual behaviour
Low performance

#### Live demo with steps to reproduce
There is performance issue with parsing data for bubble series.

Lets compare:
- bubble - rendering time: 8s 
  - https://jsfiddle.net/BlackLabel/x829uvum/

- scatter - rendering time: 0.6s 
   - https://jsfiddle.net/BlackLabel/jutu08s8/

#### Product version
6.0.7

#### Affected browser(s)
Chrome 65

**Comment by pawelfus** [comment]
This is caused by animation: each bubble has radius animation so running ~5k of animations is not performant (scatter is not animating radius, only clipping rect). Disable animation and compare results:

- bubble with animation: https://jsfiddle.net/BlackLabel/x829uvum/ ~10s
- bubble without animation: https://jsfiddle.net/BlackLabel/jutu08s8/7/ ~0.5s
- scatter with animation: https://jsfiddle.net/BlackLabel/jutu08s8/ ~0.8s
- scatter without animation: https://jsfiddle.net/BlackLabel/jutu08s8/8/ ~0.7s
