### ISSUE TITLE
Exporting image and pdf, not as same as generated plot chart

### ISSUE THREAD

**Issue by MuraliKaliappan** [highcharts/highcharts#8108]
#### Expected behaviour
wanna to get export image and pdf as displayed in plot area
#### Actual behaviour
while exporting the chart the pane overlap one with another, and displayed clutter

#### Live demo with steps to reproduce
http://jsfiddle.net/Murali_Kaliappan/Ldaeo1ve/111/

#### Product version
Highcharts JS v6.0.7 (2018-02-16) 

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @MuraliKaliappan 

Thank you for reporting the issue. This is caused by default width and height for the exported image (600x400) when size of the container is set in % (e.g. width: 100%), see details: https://www.highcharts.com/docs/export-module/export-module-overview

You can set fixed width for the exported chart by setting [`exporting.sourceWidth`](https://api.highcharts.com/highcharts/exporting.sourceWidth), demo: http://jsfiddle.net/Ldaeo1ve/120/

Let us know if you have any questions, you can contact us directly by email: https://www.highcharts.com/support

**Comment by MuraliKaliappan** [comment]
its okey no pblm thank you for your contribution @pawelfus
