### ISSUE TITLE
Class attribute in label formatter not applied to wrapped lines

### ISSUE THREAD

**Issue by robbertbrak** [highcharts/highcharts#8127]
Have a look at http://jsfiddle.net/9L5f73r8/14/. As you can see, the first data point has a very long name that wraps around at some point. I use a label formatter to add a class attribute to the label, so that I can apply some css styling on hover. However, when I hover the label, the css styling is only being applied to the first line:

![selection_527](https://user-images.githubusercontent.com/734581/38363113-a9efa264-38d3-11e8-86aa-c05e64236790.png)

I would have expected the css styling to apply to the entire label.

**Comment by robbertbrak** [comment]
Note: I suspect that this is a bug (which needs to be fixed), but in the meantime I would also be interested in workarounds. For example: is it possible to *prevent* the wrapping from occurring? This seems to happen automatically depending on the height of the bars (http://jsfiddle.net/9L5f73r8/17/), but can I prevent it somehow?

**Comment by pawelfus** [comment]
Hi @robbertbrak 

Thanks for reporting this bug! 

**Workaround:**
Apply styles on a higher level: http://jsfiddle.net/9L5f73r8/20/ - I know it's not a perfect solution, but right now only inline styles are fine, class it not applied to all lines. The problem is `:hover` pseudo class, which can not be set inline.. 

Alternative workaround: use [custom-events](https://github.com/blacklabel/custom_events) plugin and add CSS on mouseOver/mouseOut: http://jsfiddle.net/9L5f73r8/25/

Snippet:

``` javascript
  xAxis: {
    categories: ['Africa is a great continent with a long history and a long name that will wrap around at some point', 'America', 'Asia'],
    labels: {
      formatter: function() {
        return '<b class="underline">' + this.value + '</b>';
      },
      events: {
        mouseenter: function(e) {
          e.target.style['text-decoration'] = 'underline';
        },
        mouseleave: function(e) {
          e.target.style['text-decoration'] = 'none';
        }
      }
    }
  },
```

*Internal note:*
Related to #390 - simplified demo with test: http://jsfiddle.net/sq5my/18/
