### ISSUE TITLE
Wrong position of the legend labels for big chart sizes when useHTML is true

### ISSUE THREAD

**Issue by manuwhs** [highcharts/highcharts#8128]
#### Expected behaviour
The relative position of the symbol and the text of a legend item should be aligned, they should appear at the same y-axis position. This works for small and average chart sizes and when useHTML is false.

#### Actual behaviour
For chart sizes over 600px of width, the relative y-position of the symbol goes up. This only happens if useHTML is true. 

The relative alignment between the symbol and the text of a legend items works properly for chart size of up to 600px of width, if you keep increasing the size, then the symbol moves to the upper-left corner. For sizes of 1200px the appearance is already too distorted.

#### Live demo with steps to reproduce

I attach a picture with the cropped legend for 3 different chart widths, the font sizes have been scaled in each case to the chart width. It can be appreciated how the relative position of the symbol goes up.
![bug](https://user-images.githubusercontent.com/19417254/38363235-33daaa0a-38d4-11e8-8060-7a3802dd855f.png)

#### Product version

 Highcharts JS v6.0.7 (2018-02-16)

#### Affected browser(s)
Google Chrome, Internet Explorer, Edge.

**Comment by pawelfus** [comment]
Hi @manuwhs 

Thank you for reporting the issue. Could you recreate this in **jsFiddle**? It looks fine with default settings: http://jsfiddle.net/z9rbdooc/ You mention font-scalling but all the fonts look pretty the same. It's hard to debug the issue from the screenshot only.

**Comment by manuwhs** [comment]
Cześć
​ Paweł,

I have been conducting further experiments and I think the error happens *due
to the font-size* of the legend text rather than the size of the chart; it
is just that in my code, the font-size is a function of the chart width,
that is why in the picture they appear to be the same.

Furthermore the error is a little more complicated so I will elaborate,
there is another component I did not describe. The graph is rendered using
Rotativa <https://github.com/webgio/Rotativa>, which renders the HTML and
JS code through WebKit <https://en.wikipedia.org/wiki/WebKit> and it
appears that sometimes thiscreates some differences respect to what you
would obtain if you rendered it directly on the browser yourself.

I created this fiddle http://jsfiddle.net/u0sryg66/15/ to try to generate
the same bug and I also did it in the UI of the MVC application I am
working on. In both situations the bug does not appear, it is only when
using the WebKit.

Other behaviours that I have observed that are different between rendering
with the WebKit and directly on the browser is that: If I use
"useHTML:false", the special characters such as "ø, æ, å" are rendered with
HTML code numbers such as "&#229" (when using  "useHTML:true", the
characters are rendered properly but I have the issue with the positioning
of the symbol). I append an example image when the special characters are
not rendered properly. If I use a browser without WebKit, the speical
characters are rendered properly in every situation,so definetly there are
differences when using WebKit. Maybe there is different parsing of special
characters and that could also affect other parts of the code ?

I can imagine this is a very specific scenario and I do not know if it
brings information for you to develop on Highcharts, have you ever
encounter this situation ?
Sorry for the inconvenience and thank you very much for your time.

Kind Regards.

**Comment by pawelfus** [comment]
Thank you @manuwhs for the details. Unfortunately, I haven't seen this issue before. I have some ideas, but I'm afraid it's a problem with Rotativa (or rather wkhtmltopdf, see below). Anyway, could you try:

- split `itemStyle.font` to `itemStyle.fontSize` and `itemStyle.fontFamily`: 

      itemStyle: {
        fontSize: '40px',
        fontFamily: 'Arial',
      },

- use CSS version of Highcharts, instead of JS: https://www.highcharts.com/docs/chart-design-and-style/style-by-css

If this won't solve the issue, then problem may be with Rotativa. It looks like you generate image/pdf from the HTML then provide it to your app (that's what Rotative does, right?). Rotativa uses wkhtmltopdf internally (https://github.com/webgio/Rotativa/search?utf8=%E2%9C%93&q=wkhtmltopdf&type=) which has some issues with SVG (and HTML in this case) (https://github.com/wkhtmltopdf/wkhtmltopdf/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+svg) - that may be the real issue here..

We can check (I hope) if generated SVG is correct - before sending chart to Rotativa, could you get the generated SVG? Include our `exporting.js` module and use `chart.getSVG()` to get the SVG in string format and post here - we will check the SVG.

**Comment by manuwhs** [comment]
Hi Paweł,

I
s​
p
​litted the itemStyle.font to itemStyle.fontSize and itemStyle.fontFamily
into separate elements and now everything works ! :). Sorry for not
answering before but the project I am working on is a Student Job project
and I only go to work Wednesdays and Thursdays.

Thank you very much for your high quality support :). Is there anything I
should do regarding the issue I opened ?

Kind Regards.​


2018-04-05 19:14 GMT+02:00 Paweł Fus <notifications@github.com>:
