### ISSUE TITLE
Solid Gauge - Label alignment problem

### ISSUE THREAD

**Issue by renatod** [highcharts/highcharts#8186]
#### Expected behaviour
The start label should be rendered properly, bellow of the arch, just like the right label.

#### Actual behaviour
The start label position is wrong

#### Live demo with steps to reproduce
https://jsfiddle.net/renatod/qrw8kvsx

#### Product version
The problem happens in the versions <= 6.0.3
Version 5.0.14 in my case.

#### Affected browser(s)
All browsers

**Comment by pawelfus** [comment]
Hi @renatod 

Thank you for reporting the issue. This was fixed in v6.0.4 by this commit: 4b0f2e30d - please upgrade your Highcharts to v6.

Alternatively, if you can not upgrade, you can apply changes from the commit above in the source code. 

Note: It works fine with v5 if you set `yAxis.min = 0` instead of `yAxis.min = 1`, demo: https://jsfiddle.net/BlackLabel/qrw8kvsx/20/
