### ISSUE TITLE
Problem with offline exporting other formats than SVG with allowHTML

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#8226]
#### Expected behaviour
Export of all available formats should work.

#### Actual behaviour
Only SVG format is exported.
Error: `Uncaught Fallback to export server disabled`

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/prtL122o/

#### Product version
Highcharts 6.1.0

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
@oysteinmoseng On a side note, we should use the `Highcharts.error` system, so implementers can catch these errors consistently. Also in the error messages we can give a more detailed explanation for _why_ it happens.

**Comment by oysteinmoseng** [comment]
This fails on purpose, because both CanVG and svg2pdf choke on `<foreignObject>`. It needs to be documented properly though. I'll add proper `H.error`s for all of the offline exporting exceptions, and also add a word about it [in the API](https://api.highcharts.com/highcharts/exporting.fallbackToExportServer).

Do we also need to document it in docs?
