### ISSUE TITLE
DataLabels color only kicks in after resize event

### ISSUE THREAD

**Issue by Menighin** [highcharts/highcharts#8236]
#### Expected behaviour
The data labels to have the same color as the point

#### Actual behaviour
Data labels are shown in black and when we resize the window, the color takes place.

#### Live demo with steps to reproduce
https://codepen.io/anon/pen/erzLRR?editors=0010

Resize the chart window

#### Product version
Latest

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @Menighin 

Thank you for reporting this issue. This is caused by using gradient colors, solid colors are fine: https://codepen.io/anon/pen/rvWmyd?editors=0010

*Internal note:*
This issue is related to `toString()` method for gradient colors. This is defined after added to DOM (<defs>). We should probably add colors earlier so `toString()` returns actual reference (`fill: url(...)`) not `object object`.
