### ISSUE TITLE
Shared tooltip not working in scatter when points are aligned in x axis.

### ISSUE THREAD

**Issue by arisliang** [highcharts/highcharts#8239]
#### Expected behaviour
Tooltip is shared for scatter, if the points are aligned in x axis.

#### Actual behaviour
Tooltip is not shared. Noted that scatter won't share when x value don't match (#1431), which makes sense, but this is when x value is matched.

#### Live demo with steps to reproduce

https://jsfiddle.net/4bvddpg1/

#### Product version

Highcharts v6.1.0

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @arisliang 

This is expected behaviour, docs: https://api.highcharts.com/highcharts/tooltip.shared

You can achieve scatter-like tooltip in line series, simply disable [`lineWidth`](https://api.highcharts.com/highcharts/series.line.lineWidth) and [`lineWidthPlus`](https://api.highcharts.com/highcharts/series.line.states.hover.lineWidthPlus) to hide the line: https://jsfiddle.net/BlackLabel/4bvddpg1/1/

If you really need to use `scatter` type, you can force this series to show in shared tooltip by setting `Highcharts.seriesTypes.scatter.prototype.noSharedTooltip = false;` , demo: https://jsfiddle.net/BlackLabel/4bvddpg1/2/
