### ISSUE TITLE
Tooltip :shape vs followpointer

### ISSUE THREAD

**Issue by nithyavanig** [highcharts/highcharts#8293]
#### Expected behaviour
tooltip:
followPointer: true,      
    shape: "callout"

The tooltip shape should be "callout".
#### Actual behaviour
The tooltip shape is actually "rectangle", when the followpointer option is set to true.

#### Live demo with steps to reproduce
http://jsfiddle.net/td7bo0c0/
#### Affected browser(s)
Chrome

**Comment by TorsteinHonsi** [comment]
It is because the tooltip doesn't have an anchor point when `followByPointer`, because the callout would point to the mouse cursor rather than the element itself.  The relevant code is here:

https://github.com/highcharts/highcharts/blob/88c0013b0d8a1447fe477af151e64002f59f0ecf/js/parts/Tooltip.js#L216

You could override this by temporarily setting `this.followPointer` to false:
```js
Highcharts.wrap(Highcharts.Tooltip.prototype, 'move', function (proceed) {
	var followPointer = this.followPointer;
    this.followPointer = false;
    proceed.apply(this, Array.prototype.slice.call(arguments, 1));
	this.followPointer = followPointer;
});
```
[View it live on jsFiddle](http://jsfiddle.net/td7bo0c0/1/).

As you can see, in some cases the tooltip pointer is not on the same element as the cursor.
