### ISSUE TITLE
AddPoint in Highstock faster than animation keeps up causes errors

### ISSUE THREAD

**Issue by oysteinmoseng** [highcharts/highcharts#8295]
#### Expected behaviour
`series.addPoint` should force existing animation to complete.

#### Actual behaviour
It seems there are issues where it conflicts with animation.

#### Live demo with steps to reproduce
https://jsfiddle.net/b64pfmkj/1/
The demo fails after a while, logging SVG errors to console. Disabling animation, or reducing animation duration, solves the issue.

#### Product version
Highstock 6.1

**Comment by TorsteinHonsi** [comment]
I did a test with simplifying the path definitions in the last step before being applied to the DOM. It fixes this issue. 

Here it is applied to 10k points: To my surprise, it actually runs _faster_ in Chrome, probably because the definition is simpler and/or shorter. In Firefox and the rendering times are equal, in Edge slightly longer, but not significantly. 

Positive side effects are smaller exported SVG file sizes and easier debugging. 

Can you verify these performance observations @pawelfus ? I'll also do some regression tests.

**Comment by pawelfus** [comment]
The same results here:

- Chrome ~30% faster
- Firefox and Safari without noticeable difference
