### ISSUE TITLE
tickAmount breaks the behavior of autoRotate

### ISSUE THREAD

**Issue by BernardoFBBraga** [highcharts/highcharts#8299]
#### Expected behaviour
Setting tickamount should have no effect on autorotating the labels in an axis

#### Actual behaviour

Setting tickAmount has the side effect that the labels no longer rotate

#### Live demo with steps to reproduce
(template is broken, btw)

http://jsfiddle.net/xzjzzq3s/2/

drag the slide to the minimum, you'll see that the labels rotate
now remove the comment on tickAmount and if you do the same, you'll see the labels turn into ellipsis and then vanish

#### Product version

latest

#### Affected browser(s)
Chorme, Firefox

**Comment by TorsteinHonsi** [comment]
The auto-rotate feature not only rotates the labels, it also removes every `n`´th tick if they become too dense, thereby conflicting directly with the `tickAmount` setting. 

So the auto-rotate is explicitly left out here:

https://github.com/highcharts/highcharts/blob/75f41454173102919e34ca155ff959153811b135/js/parts/Axis.js#L3186-L3189

If we remove that condition, we risk having overlapping labels: 
![skjermbilde 2018-05-09 kl 10 47 03](https://user-images.githubusercontent.com/227836/39805360-f27f189e-5376-11e8-8384-c672c77e1caa.png)

In order to fix this, we would have to run the `unsquish` function, but instead of modifying the tickInterval simply hide overlapping labels or set something similar to the `step` option.
