### ISSUE TITLE
drillUp. Cannot set property 'length' of undefined

### ISSUE THREAD

**Issue by balkarov** [highcharts/highcharts#8324]
`Cannot set property 'length' of undefined` when call `drillUp()` after `chart.applyDrilldown();`
Screenshot:
![error](https://user-images.githubusercontent.com/6030335/39923531-b67041ae-552c-11e8-9bad-e7747b8a5962.PNG)

#### Expected behaviour
Not error

#### Actual behaviour
Error

#### Live demo with steps to reproduce
https://jsfiddle.net/jus3gc2n/

#### Product version
Highcharts version 6.1.0

#### Affected browser(s)
Chrome 66.0.3359.139

**Comment by sebastianbochan** [comment]
Hi @balkarov,
Thank you for the reporting. The issue is caused by missing `ddDupes` in the chart object. The solution is call `point.doDrilldown()` before applyDrilldown.

**Internal note**
Should we add `doDrilldown()` in `applyDrilldown()` ?

**Comment by muodov** [comment]
Calling `doDrilldown()` triggers the `drilldown` event, which kinda breaks the async drilldown flow.

Normal async flow:
1. user click triggers `drilldown` event
1. event listener starts some async work and eventually calls `addSeriesAsDrilldown()`
1. `addSeriesAsDrilldown()` calls `addSingleSeriesAsDrilldown()` and `applyDrilldown()` but doesn't call `doDrilldown()` to avoid another `drilldown` event.

Programmatic flow (as suggested above):
1. call `addSingleSeriesAsDrilldown()` and `applyDrilldown()` but also call `doDrilldown()` to fix the exception, but also trigger `drilldown` event as a side-effect.

Now, if I need to support both programmatic and user-click events, it becomes annoying because I will have to cancel the next `drilldown` event handler after a programmatic drilldown.

I looked through the code, and I believe the absence of `ddDupes` is just a mistake introduced in https://github.com/highcharts/highcharts/commit/ada67c7aaa32f0f6a028053420254ebd14381eb5#diff-1d9d9d6b74edd8331bf8f425ab1d7f42. It specifically handled this situation in `doDrilldown()` but not in `drillUp()`. Before that change "dupes" were always initialized: see the original fix here https://github.com/highcharts/highcharts/commit/b633bb9b5840e204326fb2330daf96a2521364b7

So, it feels like calling `doDrilldown()` is a bit of an overkill with unnecessary side effects. Why not just add a check in `drillUp()` similar to https://github.com/highcharts/highcharts/blob/master/js/modules/drilldown.src.js#L1087?

Or, maybe just initialize `ddDupes` in constructor and clear it inside `destroy()` to keep https://github.com/highcharts/highcharts/issues/3990 fixed?

**Comment by muodov** [comment]
As a workaround, I'm currently just adding these lines after a programmatic drilldown:
```javascript
if (!chart.ddDupes) { // https://github.com/highcharts/highcharts/issues/8324
   chart.ddDupes = [];
}
```

**Comment by balkarov** [comment]
Hello. Why you close this issue? Did you fix it? What’s the release?

**Comment by sebastianbochan** [comment]
Hi @balkarov,
We use auto-closer bot for the oldest issues. Im reopening the issue.

**Comment by balkarov** [comment]
Hello. Why you close this issue? Did you fix it? What’s the release?
