### ISSUE TITLE
Tooltip doesn't refresh during points navigation using JAWS Screen Reader. 

### ISSUE THREAD

**Issue by Denyllon** [highcharts/highcharts#8347]
#### Expected behaviour

Tooltip should change with actual selected point, as it is when the JAWS is turned off.

#### Actual behaviour

When navigating between the points (using keyboard arrows), the  tooltip doesn't change at all. There is always the first point's tooltip displayed on the chart, although other point is 'highlighted' by JAWS. It just occurs when the JAWS Reader is enabled.

#### Live demo with steps to reproduce
All of the demos from this site: https://www.highcharts.com/a11y.html

#### Product version
All versions

#### Affected browser(s)
All browsers

**Comment by KacperMadej** [comment]
_Internal note:_

Arrows left and right trigger going letter by letter of the currently selected text.
Up and down arrows toggle single point, but Highcharts selection marker is not toggled and tooltip is not changing.

@oysteinmoseng

**Comment by oysteinmoseng** [comment]
Screen readers highjack keyboard events, so this is not something that we can easily fix at the moment.

What we can do, is introduce a mode where we go into `role="application"` mode for the chart, meaning that we take responsibility for all keystrokes. The screen reader shortcuts will then not work, and we will have to deal with them ourselves. The downside is that users will not be able to use the keyboard shortcuts that they are familiar with from their screen reader. This is potentially a big obstacle for users, which is why we have not implemented this yet.

**Comment by oysteinmoseng** [comment]
Closing as this is a JAWS issue, and adding role="application" would cause too much user confusion.

Note that by using pass-through keys you can work around it (making JAWS pass through the arrow keys).
