### ISSUE TITLE
Why is highstock not compatible with Safari browsers?

### ISSUE THREAD

**Issue by yyb1994** [highcharts/highcharts#8368]
#### Expected behaviour
For example, highstock.js is wrong in Safari running

#### Live demo with steps to reproduce
https://jsfiddle.net/n9au023g/2/

#### Affected browser(s)
![](https://s7.postimg.cc/mzu1w2z17/image.png)

**Comment by sebastianbochan** [comment]
Hi @yyb1994,
Thank you for contacting us. The reason of the problem is your parser and using `new Date()`.
In the Chrome it returns correct data when we run:
`new Date('2018-05-21 15:00');`
but in Safari and FF not.
It is related with Javascript function, not Highcharts.

Ps. You should use split function, extract all date's elements and use `Date.UTC()` to convert string into timestamp.
