### ISSUE TITLE
Pattern export fails

### ISSUE THREAD

**Issue by baljeetkalsi** [highcharts/highcharts#8391]
It is displayed in graph but Output  JPEG and PNG file doesn't show this pattern.
It give a blank output.

**Comment by KacperMadej** [comment]
Hi @baljeetkalsi 

If this is a bug then please add a live demo for the problem.

If this is a technical support questions - pleas use [any other support channel](https://www.highcharts.com/support), because we are trying to keep github issues for bugs only.

**Comment by pawelfus** [comment]
Thank you for the example! 

This is interesting:

- https://jsfiddle.net/xa8weufd/31/ - broken (both points the same x-value)
- https://jsfiddle.net/xa8weufd/32/ - fine (different x-values)
- https://jsfiddle.net/xa8weufd/33/ - broken (both points the same y-value)

Which leads to solution:

**Workaround:**
Use column range series instead of line series: https://jsfiddle.net/xa8weufd/35/

*Internal note:*
I think we had similar problem with horizontal/vertical radial gradient, maybe it's the same issue?

**Comment by TorsteinHonsi** [comment]
> I think we had similar problem with horizontal/vertical radial gradient, maybe it's the same issue?

Yes I believe so too. See #1677.

**Comment by baljeetkalsi** [comment]
Hello @pawelfus ,
It helped me a lot.
