### ISSUE TITLE
Plot bands rendered on top of all series

### ISSUE THREAD

**Issue by v-kabanov** [highcharts/highcharts#8392]
#### Expected behaviour
Plot bands by default used to remain under data series, especially if their zIndex was lower.

#### Actual behaviour
Bands are plotted over data series regardless of zIndex.

#### Live demo with steps to reproduce
https://jsfiddle.net/6zc79tcr/8/ 
Click the "Update bands" button repeatedly. See also https://stackoverflow.com/questions/50502086/highcharts-plot-bands-rendered-on-top-of-all-series .
#### Product version
Highstock 6.1.0

#### Affected browser(s)
Chrome v66, Firefox v60

**Comment by KacperMadej** [comment]
Hi @v-kabanov 

Thank you for reporting about the problem.

Here's a simpler demo: https://jsfiddle.net/BlackLabel/6zc79tcr/9/
After update (on a button click) axis elements are in front - also grid lines.

It happens when accessibility and exporting modules are loaded.

_Internal note_: addPlotBand and removePlotBand seems to be affected too.
Problematic: http://jsfiddle.net/BlackLabel/mudqbp3m/
Standard (working): http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/members/axis-addplotband/

**Comment by TorsteinHonsi** [comment]
The issue only happens when the export SVG items are added to the `chart.exportSVGElements` array. If we comment out the following line, it works as expected:

https://github.com/highcharts/highcharts/blob/e8b924209bb08091e7639e93606ce68100eb34f2/js/modules/exporting.src.js#L1503

The `exportSVGElements`  array is later only used in the accessibility module, so the issue must lie there @oysteinmoseng .
