### ISSUE TITLE
f.xAxis is undefined using tooltip.split on multiple series rendering as pie charts

### ISSUE THREAD

**Issue by Visualq** [highcharts/highcharts#8418]
#### Expected behaviour
The expected behaviour would be a tooltip appearing on all the corresponding points the piecharts.

#### Actual behaviour
The tooltip is stuck in the top left corner when hovering and a JavaScript error is thrown: 

Firefox: `f.xAxis is undefined`
Chrome: `Uncaught TypeError: Cannot read property 'pos' of undefined`

#### Live demo with steps to reproduce
Hover over a slice and the error will appear.
https://jsfiddle.net/Visualq/4o1uyazr/13/

#### Product version
Highcharts 6.10

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @Visualq 

Thank you for reporting the issue. Actually, the bug here is that `split` changes anything for pie series. `split` option is strictly connected to the cartesian order series types (line, column etc.) and should not affect pie-series (just like [shared tooltip](https://api.highcharts.com/highcharts/tooltip.shared)). In other words, fix would be to remove `split` option from docs for pie/variablepie series and remove this error, with that result: https://jsfiddle.net/BlackLabel/4o1uyazr/15/

However, I agree, `split` in multiple pie charts makes sense. What do you think @TorsteinHonsi ?

**Comment by TorsteinHonsi** [comment]
It does make sense, but we have no logic for connecting the points or positioning the tooltip elements across the series. In a cartesian chart, they're connected using their plot X position. But at the least, we should expect this to work like a non-split tooltip.
