### ISSUE TITLE
Uneven Circle

### ISSUE THREAD

**Issue by ASHK01** [highcharts/highcharts#8422]
#### I want to find a xy coordinates lie inside a circle or not. But somehow the circle drawn by highchart is not uniform. as in : [image](https://i.stack.imgur.com/wS06j.png)
It should look like this
![image](https://user-images.githubusercontent.com/8465378/40872149-48295cca-6667-11e8-996d-34372dee1ddd.png)
The circle is 3 unit wide on both X and Y axis. 

#### Live demo with steps to reproduce
[fiddle link](http://jsfiddle.net/g3ut4e9d/)

#### Product version
Current

For more details : https://stackoverflow.com/questions/50654636/highchart-uneven-circle

**Comment by TorsteinHonsi** [comment]
I'm not sure I understand your question correctly, but there's nothing in you chart indicating that the X and Y axis should have the same translation. You translate the radius into X coordinates, but the Y axis doesn't have the same scale.

`var pixelR = chart.xAxis[0].toPixels(circleR) - chart.xAxis[0].toPixels(0); `

In order to have the same scale on the X and Y axis, you will have to hard code some dimensions: http://jsfiddle.net/highcharts/g3ut4e9d/1/
