### ISSUE TITLE
A bigger Highcharts SVG doesn't render but a small one does

### ISSUE THREAD

**Issue by IvoPereira** [highcharts/highcharts#8424]
#### Expected behaviour
Highcharts SVG charts should be rendered despite its size.

#### Actual behaviour
Highcharts SVG charts look like being rendered based on their size. Only small SVG charts seem to get rendered.

One of the things I've noted is that pie charts render correctly, while spline ones doesn't. This has worked before and I am afraid that perhaps a Highcharts new version may have messed something in the SVG build process?

#### Live demo with steps to reproduce

Highcarts SVG correctly rendering demo:
http://jsbin.com/vemuvozaha/1/edit?html,js,console,output

Highcharts SVG not rendering demo
http://jsbin.com/lowolicugu/edit?html,js,console,output

#### Product version

Highcharts 4.0.4

#### Affected browser(s)

Mac OS X Chrome 67.0.3396.56 beta

**Comment by KacperMadej** [comment]
Hi @IvoPereira 

You have provided demos for creating images based on Highcharts code. If you have technical questions please contact support. https://www.highcharts.com/support

This doesn't look like related to Highcharts or caused by it, because your demo doesn't include Highcharts. Please check with newer versions of Highcharts if the problem is visible and pleas provide a demo that is using Highcharts directly.

**Comment by IvoPereira** [comment]
Hello @KacperMadej,

While I was recreating the example with Highcharts, I've been able to discover that for some reason when using 

```js
        exporting: {
            buttons: {
                contextButton: {
                    symbol: 'url(URL_TO_IMAGE_HERE)'
                }
            }
        },
```

in chart options, the exported SVG appears to be invalid.

To be honest, I don't know what caused this, because the exact same steps would produce a correct output and a correct chart to SVG conversion.

Anyway, I don't really need to be using this property, so, issue closed.


Thanks for your support.
