### ISSUE TITLE
Navigator data reset after unrelated series update

### ISSUE THREAD

**Issue by nhitchins** [highcharts/highcharts#8430]
#### Expected behaviour
Calling series.update on unrelated series shouldnt affect navigator chart

#### Actual behaviour
Navigator chart loses it's data after dynamic update of unrelated series.
Issue appears when chart is created with *navigator.series.data = []*  (but works as expected by omitting the data attribute or setting to null/undefined)

#### Live demo with steps to reproduce
https://jsfiddle.net/dwbae6zj/1/

#### Product version
HighStock 6.1.0

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @nhitchins 

Thank you for reporting this bug. This looks strange, for example using static series instead of dynamic one: https://jsfiddle.net/BlackLabel/dwbae6zj/7/ - and we will get correct result.

Broken since v5.0.0: https://jsfiddle.net/BlackLabel/dwbae6zj/9/

*Internal note:*
Probably we have somewhere wrong reference (this series in the navigator is connected to the first series in `chart.series`, which is .. itself when creating chart with an empty array for series: `series: []` - of course this link shouldn't exist).
