### ISSUE TITLE
Navigator applies incorrect data grouping

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#8433]
#### Expected behaviour
Data grouping should remain the same after moving the navigator handle.

#### Actual behaviour
Changing the position of the navigator handle changes data grouping to 1 day event though this piece of code is present in options:

```
  plotOptions: {
  	series: {
    	dataGrouping: {
      	forced: true,
        units: [
          ['week', [1]]
        ]
      }
    }
  },
```

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/xa8ozfmL/
Move any of the navigator handles.

#### Product version
Highstock 6.1.0

**Comment by pawelfus** [comment]
*Internal note:*
Debugging leads to: https://github.com/highcharts/highcharts/blob/3444c46e8461ed1541138286d4752758df288767/js/parts/RangeSelector.js#L499-L514

Why it's needed to **remove** dataGrouping options on setExtremes? If buttons are configured to set dataGrouping then shouldn't we keep this config unless user selects another button? Tests are passed without errors even if that part is removed. @TorsteinHonsi

**Comment by TorsteinHonsi** [comment]
When we drag the handle, the button is also unselected, so it is not valid anymore. I assume that is the rationale behind this behaviour. I'm not sure how to handle it otherwise.... I agree this is counterintuitive if the primary function of the button is to set the data grouping, but the button also sets the range of the X axis. Maybe we need an option on the button itself to preserve the grouping? In that case it should also stay selected until another button is clicked.
