### ISSUE TITLE
Regression: Missing x values not inferred when calling series.setData(data)

### ISSUE THREAD

**Issue by oluwasayo** [highcharts/highcharts#8462]
#### Expected behaviour
Missing X values should be inferred as described in https://api.highcharts.com/highcharts/series.line.data
This _somewhat works_ in Highcharts 5 (doesn't work if the length of the array is the same).

#### Actual behaviour
Data points with missing X values are ignored

#### Live demo with steps to reproduce
http://jsfiddle.net/8cm3od5g/33/

1. Run Fiddle
2. Click on Set New Data to observe the behavior in Highcharts 6
3. Comment/uncomment sections as described in the Fiddle
4. Rerun Fiddle and click on Set New Data
5. Make different combinations of step 3 above

#### Product version
Highcharts/Highstock 6

#### Affected browser(s)
All browsers

**Comment by pawelfus** [comment]
Hi @oluwasayo 

Thank you for reporting the issue.

Just a side note: you have errors in console, because your dataset is not correct:

```
var myData = [
  ['Seun', 10], // x => 0, x++
  ['Tolu', 20], // x => 1, x++
  [1, 30], // x => 1, duplicate
  [3, 40], // x => 3
  ['Simbi', 50] // x => 2, x++ <-- wrong data point
];
```

I need to ask, what is the point of using different formats (`[x, y]` vs `[name, y]`)? For example, categorized data looks fine: http://jsfiddle.net/BlackLabel/8cm3od5g/59/ (Note: I use **copy** of the data, not the original array. Highcharts store **reference** to the dataset, so any change like `myData[1][1] = 50` is already applied to the dataset. Because original point did not change when comparing to the "new" options in `setData()`, change is not visible.)

*Internal note:*
Bisect leads to 7a741669d

**Comment by oluwasayo** [comment]
> Just a side note: you have errors in console, because your dataset is not correct

Yes I am aware of this. This is a contrived example, the original issue still remains.

> I need to ask, what is the point of using different formats ([x, y] vs [name, y])?

As shown in the Fiddle, the issue is also present when using an array of objects where only a few have the `x` property. This could be useful for large datasets where only a few points need to be absolutely positioned at certain places on the x-axis. This for example could be used to create spaces between points as done in this [column chart for example](http://jsfiddle.net/8cm3od5g/75/).

I'm not so concerned about how HC treats this dataset, I'm only concerned about the difference when setting dataset initially in JSON configuration vs when setting via `setData`.
