### ISSUE TITLE
No space for rotated labels with multiple xAxis

### ISSUE THREAD

**Issue by david97j** [highcharts/highcharts#8489]
#### Actual behaviour
When multiple xAxis, if the labels of the first xAxis overlap the other xAxis. Doesn´t matter if chart type is column.

#### Live demo with steps to reproduce
https://jsfiddle.net/kw861s0L/12/

#### Product version

Highcharts 6.0.3
#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @david97j 

Thank you for reporting this bug.

*Internal note:*
It looks like `labelOffsetPadded` is incorrect here: 

https://github.com/highcharts/highcharts/blob/0f08eb1243d1456f89f8e137362e34828e21aba1/js/parts/Axis.js#L4427-L4439

`axis.tickRotCorr.y` is applied, but maybe something like `labels.padding` should be used here too? I guess this is `directionFactor * 8` part.

**Comment by sebastianbochan** [comment]
**Internal note**
I debugged the issue and it looks like: 

```
labelOffsetPadded += (labelOptions.padding || 0) + directionFactor * (
                horiz ?
                    pick(
                        labelOptions.y,
                        axis.tickRotCorr.y + directionFactor * 8
                    ) :
                    labelOptions.x
            );
```

fixed the issue. All tests are also passed.

Only what bothering me is that it requires the padding declaration by user. If we set i.e default value as 5, a few tests (x-range, bubble, boxplot) are broken.

@TorsteinHonsi what do you think?

**Comment by sebastianbochan** [comment]
Unfortunately there is reference to highcharts from local and I dont see the difference. Any hint?

**Comment by TorsteinHonsi** [comment]
Here's with .com: https://jsfiddle.net/highcharts/rq5ojp8h/6/ . The point is, even when the labels are not rotated, the distance is too small.

**Comment by sebastianbochan** [comment]
Sorry for my misunderstood, now I know what you mean.

**Comment by sebastianbochan** [comment]
**Internal note**

@TorsteinHonsi 

It looks like the `getLabelSize` function ignores default (or defined by user) label padding. We can solve it by add it.

```
    getLabelSize: function () {
        var options = this.axis.options,
            labelOptions = options.labels,
            labelPadding = labelOptions.padding || 5; // default margin

        return this.label ?
            labelPadding + this.label.getBBox()[this.axis.horiz ? 'height' : 'width'] :
            0;
    },
```

The problem is that three tests fails:
- xrange
- candlestick
- timezone (dst)

I verified all of them and seems that look fine from the visual perspective. The fault is caused by adding padding and some strings are shorter.

My idea is create PR / commit, you will decide if it makes sense.

**Comment by TorsteinHonsi** [comment]
With this change, almost all the visual tests fail because the axis layout has changed. The `xAxis.labels.padding` option is described as "The pixel padding for axis labels, to ensure white space between them". By redefining this to create padding up and down from the labels, we fix the issue in this thread, but we also change the layout of every single-axis chart. What we want to do is to add space _between_ axes in the cases where we have multiple axes. So I think we need something that checks if the axis is next to another axis in the same position, and adds the margin only then. I'll have a look at it.

**Comment by TorsteinHonsi** [comment]
Demo with the fix applied: https://jsfiddle.net/highcharts/n2kdsLqo/

And without rotation, and title applied: https://jsfiddle.net/highcharts/75xja61o/
