### ISSUE TITLE
Wrong India Map

### ISSUE THREAD

**Issue by SumitBalia** [highcharts/highcharts#8493]
When i am using INDIA map using 'map: 'countries/in/in-all'', it is not showing half of the Jammu & Kashmir.

If we are using this incomplete INDIA map it's **illegal** and we can't use this MAP.
Please go through below link,

[https://timesofindia.indiatimes.com/india/7-year-jail-Rs-100-crore-fine-for-wrong-depiction-of-India-map/articleshow/52133221.cms](https://timesofindia.indiatimes.com/india/7-year-jail-Rs-100-crore-fine-for-wrong-depiction-of-India-map/articleshow/52133221.cms    )

[http://www.dnaindia.com/india/report-wrong-depiction-of-india-s-map-can-land-you-in-jail-up-to-7-years-or-rs-100-cr-fine-2209607](http://www.dnaindia.com/india/report-wrong-depiction-of-india-s-map-can-land-you-in-jail-up-to-7-years-or-rs-100-cr-fine-2209607)

**So, please update DATA of INDIA MAP**
![screen-shot-2018-06-18-at-6 52 40-pm](https://user-images.githubusercontent.com/17902951/41538704-841b75c8-7329-11e8-91da-986f18eac53b.png)

**Comment by SumitBalia** [comment]
#

**Comment by sebastianbochan** [comment]
Hi @SumitBalia,
Thank you for the reporting. We will fix this as soon as possible.

Meanwhile, you can edit map by QGIS tool and adapt the map to the right shape.

Docs:
- https://www.highcharts.com/docs/maps/custom-geojson-maps

**Comment by siphr** [comment]
The map is correct. You only see half of Kashmir, because India controls that half. Although all of Kashmir is disputed territory, The other half is controlled by Pakistan.

**Comment by CANCICAVALLO** [comment]
With all due respect, half of Kashmir is still controlled by Pakistan. You can't change basic geography because it doesn't satisfy your sentiments of Indian nationalism.

**Comment by SumitBalia** [comment]
Ok got it, Thank you for clarifying my doubts. I'll close this issue. 
Thank you @siphr @CANCICAVALLO @sebastianbochan

**Comment by HK1811** [comment]
@sebastianbochan @SumitBalia  

The map is like this because its the international boundary, India doesn't control the entirety of Jammu and Kashmir, Pakistan controls roughly 1/3 and China controls some as well (Aksai Chin), India's government may refuse to use the international boundary due to an ego issue and hide it from their citizens however that doesn't mean we should change international boundaries due to our sentiments.

**Comment by GANTZ02** [comment]
@hk1811 


There is no international border between the 2 Kashmir region, there only is a line of control , if you put a fence 2km in/out of the current loc , then that's the new border . That's why its armed & monitored by the U.N. 


In cases like these companies use dotted lines to dipict the disputed regions from the controlled one 


Also this map is ridiculous , where is the Andaman & Nicobar islands ? If it were acl country it would be the 164/196 biggest country in the world.

**Comment by HK1811** [comment]
@GANTZ02  

Line of Control has been the same since 1948/49, again its the international boundary and I'm fine with a dotted line on this map but I don't see why an international map should be changed because Indians have an ego issue, the fact of the matter is India has no jurisdiction/control/influence in Azad Jammu and Kashmir, Gilgit Baltistan and Aksai Chin so I don't why they should be included. If this were an Indian website then I could see why but it isn't.

**Comment by GANTZ02** [comment]
@hk1811

No , it is not a international border. That alone shows you are clueless on the topic .

 Loc stops at  point nj9842 , India controls siachen glacier
