### ISSUE TITLE
Highcharts Wordcloud Export JPG/PNG overlaps words 

### ISSUE THREAD

**Issue by snoh8** [highcharts/highcharts#8496]
#### Expected behaviour
Highcharts Export JS allows me to to capture the wordcloud without the words overlapping in a jpg or png form. 

#### Actual behaviour
All of the words tend to crowd and overlap one another and it is difficult to read. 

#### Live demo with steps to reproduce

![screen shot 2018-06-18 at 7 44 22 pm](https://user-images.githubusercontent.com/38966861/41569324-4c9ef8ac-7330-11e8-9791-d4bf37e59691.png)
This is the way it looks in the chart. 
![chart 7](https://user-images.githubusercontent.com/38966861/41569354-6b6f96e2-7330-11e8-87c5-3d976f9fd049.jpeg)
This is how it looks when exporting into jpeg. 
I was wondering how I could get an accurate depiction of the chart results in jpg or png form. Thank you!

**Comment by pawelfus** [comment]
Hi @snoh8 

Thank you for reporting the issue. Could you provide live demo (e.g. jsFiddle)? Thanks!

**Comment by TorsteinHonsi** [comment]
This happens because the fonts on our export server are not the exact same as on the client.

Live demo: http://jsfiddle.net/highcharts/erjwqb67/1/

#### Workaround 1:
Use a well-known font family that is install across users' browsers as well as on the export server, for example Arial: http://jsfiddle.net/highcharts/erjwqb67/2/

#### Workaround 2:
Use local export so that the client font is used for the export. http://jsfiddle.net/highcharts/erjwqb67/4/

@jon-a-nygaard We should probably change the default font for word clouds.

**Comment by jon-a-nygaard** [comment]
I thought this was fixed by 0c79782 when default font-family was changed to sans-serif? 🤔
Potential duplicate of #7314.


This seems to be working fine in the example provided by @TorsteinHonsi which uses current version.

I suspect it might be an older version of wordcloud.js or perhaps font-family specified to be an font type which is not supported by the export server.

A live demo from you @snoh8 would be very appreciated just to confirm or debunk any suspicions :)

**Comment by pawelfus** [comment]
@jon-a-nygaard I can recreate issue using this demo http://jsfiddle.net/highcharts/erjwqb67/1/

**Comment by jon-a-nygaard** [comment]
That is strange @pawelfus, http://jsfiddle.net/highcharts/erjwqb67/1/ is working as I would expect when I try it. I'll check if it might be some browser/device differences.

**Comment by sebastianbochan** [comment]
@jon-a-nygaard 
For me it still does not work (i.e export to .png).

Chrome:  67.0.3396.87
MacOSX: Sierra 10.12.4 (16E195)

![chart](https://user-images.githubusercontent.com/2115686/41598124-9870ed18-73cf-11e8-9dbf-45557cd22b49.png)

**Comment by TorsteinHonsi** [comment]
@jon-a-nygaard, `sans-serif` means different things in different systems, so the safest way around the problem is to find the font-family that is most likely to be installed on most systems. Arial is a good candidate.

**Comment by pawelfus** [comment]
Hi @snoh8 

Yes, the overlapping is caused by font. When exporting chart, SVG is sent to our exporting server. The font applied on a chart may not exist on our exporting server, or like `san-serif` can affect text sizes. Mentioned `Arial` works fine for me, demo: http://jsfiddle.net/BlackLabel/kwp3admx/

**Comment by snoh8** [comment]
Thank you, I understand now.  It seems that Arial is working much better for me so far!

**Comment by Civile** [comment]
@TorsteinHonsi workaround 1 worked fine for me
