### ISSUE TITLE
Sunburst - drilldown levels are incorrect

### ISSUE THREAD

**Issue by sebastianbochan** [highcharts/highcharts#8504]
#### Actual behaviour
1. Click on Equitity -> got to level 1
2. Click Equitiy button and you are not at the top level as you should, but on Wealth Creation

#### Live demo with steps to reproduce
- https://jsfiddle.net/BlackLabel/8qLfuzor/

#### Product version
6.1

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
+1 @jon-a-nygaard

**Comment by sebastianbochan** [comment]
still valid in 6.1.1

**Comment by jon-a-nygaard** [comment]
When clicking on "Equitiy" it drills down to its level (3 not 1) and when clicking on the button "Equity" it drills up to its parent which is "Wealth Creation".
To me this looks like the expected behaviour.

If you want to always drill back to the root of the sunburst when clicking on the button, then it can be achieved by overriding the drillUp function: https://jsfiddle.net/jon_a_nygaard/8qLfuzor/68/
