### ISSUE TITLE
bellcurve module fails

### ISSUE THREAD

**Issue by ddoice** [highcharts/highcharts#8506]
#### Expected behaviour
Highcharts + BellCurve module to create a histogram.

#### Actual behaviour
Scatter plots nicely but histogram module fails on binning and frecuency count doesnt match, missing columns.

I have patched our own version, file histogram-bellcurve.src.js adding in line 307:

`
          if (frequencies[x] === undefined) {
            frequencies[x] = 0;
          }
`

#### Live demo with steps to reproduce
https://jsfiddle.net/tq0wpL4y/
24 samples, adding all columns = 10, 14 missing.

#### Product version
highcharts 6.1

#### Affected browser(s)
all

**Comment by KacperMadej** [comment]
The path presented as a wrapper  - temporary workaround: https://jsfiddle.net/BlackLabel/x5ren8Lo/

_Internal note:_
The problem here is caused by floating point math imprecision not handled good enough in `histogram-bellcurve` module - some edge cases causes wrong bin detection while setting bins and different bin sort for values.
