### ISSUE TITLE
Labels outside the area

### ISSUE THREAD

**Issue by balkarov** [highcharts/highcharts#8508]
Cases:
1) Open example on [jsfiddle ](https://jsfiddle.net/zdcLp1n8/)
2) Click CTRL + F5 (or clean cashe in browser)
3) See result _(screenshot 1)_:

![default](https://user-images.githubusercontent.com/6030335/41710989-ac39d5a4-754f-11e8-9ac9-45c0637ef29e.PNG)

If you click "Run code" again labels will show in two line _(screenshot 2)_:

![2](https://user-images.githubusercontent.com/6030335/41711183-317cc53c-7550-11e8-980a-3af3e18dba92.PNG)

#### Expected behaviour
Full label with word wrap (screenshot 2)

#### Actual behaviour
Label outside the area (screenshot 1)

#### Live demo with steps to reproduce
https://jsfiddle.net/zdcLp1n8/

#### Product version
Highcharts version 6.1.0

#### Affected browser(s)
Chrome 67.0.3396.87

**Comment by pawelfus** [comment]
Hi @balkarov 

Thank you for reporting this issue. This happens because of async loading of fonts. When chart is rendered we calculate bounding boxes of text elements to measure the space required for labels. Browser reports correct numbers, but later applies fonts and size changes. Check this demo not related to Highcharts: https://jsfiddle.net/2pLqrau6/ and compare width+height

**Comment by balkarov** [comment]
@pawelfus  Thank you for your answer!
