### ISSUE TITLE
Gantt: Inverted chart fails

### ISSUE THREAD

**Issue by oysteinmoseng** [highcharts/highcharts#8525]
We have use cases for inverted gantt charts. Currently this fails.

#### Live demo with steps to reproduce
http://jsfiddle.net/m3u1bghy/1/

**Comment by jon-a-nygaard** [comment]
**Internal Note:** The inverted yAxis (`type: ['treegrid', 'category]`) actually works as "expected", but it looks off due to `yAxis.staticScale: 50`

**Comment by jon-a-nygaard** [comment]
After a series of fixes I believe we can close this issue.

The following has been fixed:
- Label positioning in grid axis
- borderWidth, lineWidth, and tickWidth behaves the same accross horizontal and vertical axes.
- tickSize could sometimes return wrong length of tick line, causing a gap in the grid cell.

The reproduction demo still looks a bit off, but that is due to `yAxis.staticScale` is defaulting to `50`.
