### ISSUE TITLE
Sunburst chart: Unnecessary outlines are seen for dangling parents having null children

### ISSUE THREAD

**Issue by amruta30** [highcharts/highcharts#8553]
#### Expected behaviour
Sunburst chart series outline/border should only be applied to the data nodes having value.

#### Actual behaviour
For a sunburst chart plotted such that data value of some parent nodes is greater that the data value of children, in such case unnecessary outlines are displayed for dangling parents where data is not present. 

#### Live demo with steps to reproduce
http://jsfiddle.net/amrutaJgtp/e325Lpkg/

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @amruta30 

Thanks for reporting the issue. It looks like `null` points are treated as `0`-value points (we can see this in tooltip):
![screen shot 2018-06-29 at 17 07 29](https://user-images.githubusercontent.com/1453926/42100227-eb54f1a8-7bbf-11e8-948a-2306906a8099.png)



**Workaround:**
Demo: http://jsfiddle.net/BlackLabel/du9523mw/

Snippet:

```javascript
(function(H) {
  H.wrap(H.seriesTypes.sunburst.prototype.pointClass.prototype, 'draw', function(p) {
    this.isNull = this.isNull ? this.isNull : !H.isNumber(this.options.value, true);

    return p.apply(this, Array.prototype.slice.call(arguments, 1));
  });
})(Highcharts)

```

*Internal note:*
@jon-a-nygaard - is this expected behaviour? That `null`-value leafs are treated as `0`?

**Comment by jon-a-nygaard** [comment]
@pawelfus No, that is not expected. Currently working on a fix for the issue.
