### ISSUE TITLE
Only showing first x axis when there are multiple x axes

### ISSUE THREAD

**Issue by stutrek** [highcharts/highcharts#8557]
#### Expected behaviour
All x axes are visible

#### Actual behaviour
only the first x axis is visible, layout does not account for subsequent ones.

#### Live demo with steps to reproduce

https://jsfiddle.net/ryhv49n1/6/

#### Product version

Highcharts 6.1.1

#### Affected browser(s)
Firefox, Chrome

**Comment by sebastianbochan** [comment]
Hi @stutrek,
The second xAxis does not have labels, because reference to series or other axis is missing. As a result extremes (and ticks) can not be calculated. 

The solution is linking both xAxis.

**Demo:**
- https://jsfiddle.net/BlackLabel/h56z3v8y/

**Docs:**
- https://api.highcharts.com/highcharts/xAxis.linkedTo

**Comment by stutrek** [comment]
This is problematic for me because the user may be graphing two series with significantly different mins and maxes. My example is more like this, the label of the first two series has been doubled:

https://jsfiddle.net/h56z3v8y/7/

Is there a better way to do this than saving all my labels outside of the graph then accessing them by index in the formatter function?

**Comment by pawelfus** [comment]
@stutrek 

If you have a series bound to an axis, then extremes are rendered. If xAxis is empty, then labels are not rendered because we simply don't know what should be rendered. As @sebastianbochan said, you can link axes, and extremes from main will be rendered on the second one. Another example: https://jsfiddle.net/BlackLabel/ryhv49n1/8/ - one series is linked to the second xAxis so labels are rendered. I don't understand the question about formatter, maybe you want to use [`xAxis.categories`](https://api.highcharts.com/highcharts/xAxis.categories)?
