### ISSUE TITLE
Bubble chart not seen properly when z param is not set in datapoint

### ISSUE THREAD

**Issue by amruta30** [highcharts/highcharts#8608]
#### Expected behaviour
In earlier Highchart versions, bubble chart was plotted correctly even when the z param was not set in datapoint. Backward compatibility should be supported.

#### Actual behaviour
Consider a case of plotting bubble chart where z param is not set in datapoints.
Example: https://jsfiddle.net/amrutaJgtp/hmvfrwa9/
Above JS fiddle shows that bubbles are not seen.

However, in Highcharts v6.0.6 - z param in bubble chart datapoint was optional.
Example: https://jsfiddle.net/amrutaJgtp/hmvfrwa9/1/

#### Product version
v6.1.1

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @amruta30 - thank you for reporting this regression!

*Internal note:*
Bisect leads to a79b27f96

**Comment by sebastianbochan** [comment]
Hi @amruta30,
I prepared you a workaround for it here, but it can be limited.
- https://jsfiddle.net/BlackLabel/h9qLx4gf/

Please note that it reverts the fix for another issue (https://github.com/highcharts/highcharts/issues/8402). 

When Im testing the current workaround, all works properly (for both demos), but could you test too? It will allow me to be ensured that all is solved properly and then I will commit my changes.
