### ISSUE TITLE
Boost.js - marker border is not supported

### ISSUE THREAD

**Issue by tejaspchordiya** [highcharts/highcharts#8613]
Scatter chart without boost. Here, marker points are plotted:
https://jsfiddle.net/tejaspchordiya/mvan0gko/7/

Scatter chart with boost. Here, marker points are not plotted:
https://jsfiddle.net/tejaspchordiya/mvan0gko/9/

**Comment by KacperMadej** [comment]
Hi @tejaspchordiya 

The problem is more about lack of border for markers in boosted scatter series, because if you change color from white you will see the markers: https://jsfiddle.net/BlackLabel/mvan0gko/11/

If you disagree @tejaspchordiya please let me know and if not then we should rename the issue to make it more clear what's it about.

**Comment by tejaspchordiya** [comment]
Yes, I disagree with you, because there can be a case where user wants to apply border when scatter series is boosted with fill color as white.

**Comment by pawelfus** [comment]
@tejaspchordiya  - thank you for the clarification, let me change the title. @cvasseng FYI
