### ISSUE TITLE
Highcharts overlapping category labels

### ISSUE THREAD

**Issue by smokedog2** [highcharts/highcharts#8632]
#### Expected behaviour
Axis labels should never overlap

#### Actual behaviour
the category axis labels overlap

#### Live demo with steps to reproduce
http://jsfiddle.net/bkmgoct6/13/
![image](https://user-images.githubusercontent.com/37169979/42794392-1b5c8a88-89b1-11e8-9b7e-0f22591baed6.png)

http://jsfiddle.net/bkmgoct6/15/
![image](https://user-images.githubusercontent.com/37169979/42794400-25d9cd68-89b1-11e8-8566-2c4beb09f590.png)

#### Affected browser(s)
Chrome

**Comment by sebastianbochan** [comment]
Hi @smokedog2,
The issue is caused by setting `step: 1`, the parameter draws all labels and when you do not have spaces (in text label), labels overlap.

Workarounds:
- use `rotation`: http://jsfiddle.net/BlackLabel/xo0pys67/4/
- set `useHTML` as true and add CSS styles: http://jsfiddle.net/BlackLabel/k0qfLvyc/

**Comment by smokedog2** [comment]
Sorry,my english is so bad,maybe i can not expressed myself clearly.
I have provided two examples, why the first one overlaps, they have the same xAxis.

**Comment by pawelfus** [comment]
Hi @smokedog2 

When reporting bugs, please set fixed width for charts, otherwise it may be hard to spot the issue. For example, changed width in your demos, both have the same issue:

- http://jsfiddle.net/BlackLabel/bkmgoct6/19/
- http://jsfiddle.net/BlackLabel/bkmgoct6/20/

When you remove `step` option, as @sebastianbochan said:

- http://jsfiddle.net/BlackLabel/bkmgoct6/21/
- http://jsfiddle.net/BlackLabel/bkmgoct6/23/

**Comment by AmmyXu** [comment]
Hi @pawelfus
We had meet the same problem, the tags were stacked horizontally  when the tag text was long, but what we wanted is that it can rotate automatically.

If use the rotation method mentioned above to solve this problem, a strategy is need to determine whether the label should be rotated, which seems to be troublesome. Is there a better way?

demo: http://jsfiddle.net/kw34jb9b/57/

**Comment by pawelfus** [comment]
I'm not sure what to do about this case. I mean, labels are very long where simply word is very long. Ellipsis sounds reasonable, but you may not see full labels (e.g. exporting) - and it's disabled by `textOverflow`(works fine when enabled: http://jsfiddle.net/BlackLabel/kw34jb9b/74/ ). @TorsteinHonsi Do I miss an obvious solution here?

**Comment by AmmyXu** [comment]
We want the label to be full, with no ellipsis.

This requirement is actually achievable. When the label is tilted 45 degrees, the text does not overlap. However, it seems that HC currently determines whether the label is tilted based on its columnar width, rather than on text. I think the latter is a more reasonable strategy.

So what I'm asking is, is there any way to meet our needs? Is that something you want to improve?
![image](https://user-images.githubusercontent.com/29430746/44581081-f6c4e300-a7ce-11e8-8da8-d7f665c8888b.png)

**Comment by TorsteinHonsi** [comment]
As I understand the case, the option you're looking for is [autoRotationLimit](https://api.highcharts.com/highcharts/xAxis.labels.autoRotationLimit). Here's the demo with a higher `autoRotationLimit`, as far as I can see it gives the output you require: http://jsfiddle.net/highcharts/kw34jb9b/81/.

The rationale behind this default setting is that when the text strings are longer than this, it is likely that they consist of many words so they can be split up across multiple lines.

**Comment by AmmyXu** [comment]
Thank you very much. That's what I want.
