### ISSUE TITLE
Error: Uncaught (in promise): TypeError: Cannot read property 'forExport' of undefined

### ISSUE THREAD

**Issue by carlos808** [highcharts/highcharts#8643]
#### Live demo with steps to reproduce
https://stackblitz.com/edit/angular-9nkrgd-ncqpu6

Click on Welcome Page link and read instructions to reproduce.

#### Product version
highcharts: 6.1.1, angular: 6.0.5, angular-highcharts: 6.2.3

#### Affected browser(s)
Only tested on Chrome.

**Comment by pawelfus** [comment]
Hi @carlos808 

This looks like angular-highcharts bug. Could you recreate issue using our [angular package](https://github.com/highcharts/highcharts-angular), or at least without this third-party package? I see that bug was reported on the package github: https://github.com/cebor/angular-highcharts/issues/190 but not acknowledged.

**Comment by KacperMadej** [comment]
Hi @carlos808 

Please use:
```ts
import Highcharts from 'highcharts';
import HC_exporting from 'highcharts/modules/exporting';
HC_exporting(Highcharts);
```

Demo: https://stackblitz.com/edit/angular-9nkrgd-uccwqn?file=src/app/new-page.component.ts

**Comment by carlos808** [comment]
Hi @KacperMadej 

Perfect, all working with export, will drop the 3rd party package.

Many thanks.

**Comment by sanderzz91** [comment]
I encountered the same error and I don't use angular-highcharts or highcharts-angular (because my application lets a enterprise customers add their own visualization scripts). In conclusion: the 'Cannot read property 'forExport' of undefined' error is reproduced by:

1. having the following scripts added in the page header (at runtime, don't know if this matters, I guess not):

'https://code.highcharts.com/stock/highstock.js'
'https://code.highcharts.com/highcharts-more.js',
'https://code.highcharts.com/modules/series-label.js',
'https://code.highcharts.com/modules/solid-gauge.js',
'https://code.highcharts.com/modules/boost.js'

2. adding a StockChart on the page
3. calling chart.destroy() on that StockChart in the ngOnDestroy() method of the  component that displays the stock chart
4. navigating away from the component with the stock chart.

**Comment by sebastianbochan** [comment]
Hi @sanderzz91,
Could you simplify and replicate your example as live demo? It will allow us to debug and find a fix.

**Comment by sanderzz91** [comment]
Hi @sebastianbochan, strange - it seems you can forget about it. I can't reproduce it anymore, not with a reduced example (https://stackblitz.com/edit/destroy-highchart-stockcharts), nor on my complete project.

**Comment by sebastianbochan** [comment]
Hi @sanderzz91,
If you will be able to reproduce the issue, please reopen the ticket and supply some details.

**Comment by paithalmi** [comment]
Hi i am getting the same issue. Using angular 6, highcharts 6.1.1.

```
import { ChartModule, HIGHCHARTS_MODULES } from 'angular-highcharts';
import * as exporting from 'highcharts/modules/exporting.src';
First i was using import * as exporting from 'highcharts/modules/exporting.src'; 
```

Then tried with
```
import HC_exporting_ from 'highcharts/modules/exporting.src';
const HC_exporting = HC_exporting_;
HC_exporting(Highcharts);

Able to export the chart but after if i try to update the chart data then i am getting the error: ERROR TypeError: Cannot read property 'forExport' of undefined
    at a.Chart.destroy (highcharts.js:272
```

**Comment by KacperMadej** [comment]
@paithalmi 
`angular-highcharts` is not our product.
For official Angular wrapper and information about using Highcharts with Angular please see:
https://github.com/highcharts/highcharts-angular/

**Comment by paithalmi** [comment]
Hi tried with this highcharts-angular. This issue is not there. But one problem how can i show the loading overlay(showLoading/hideLoading)with this product.
`import { Component } from '@angular/core';

import Highcharts from 'highcharts';
import HC_exporting from 'highcharts/modules/exporting';
HC_exporting(Highcharts);

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';

  constructor() {
  }

  Highcharts = Highcharts;
  chartOptions = {
    series: [{
      data: [1, 2, 3, 6, 9]
    }],
    exporting: {
      enabled: true
    }
  };

  updateFromInput = false;

  update_chart() {
	this.chartOptions.series = [{
    data: [10, 20, 30]
    }];
    this.updateFromInput = true;
  }`


template:
```
<highcharts-chart [Highcharts]="Highcharts" [options]="chartOptions" [(update)]="updateFromInput"
      [oneToOne]=true style="width: 100%; height: 400px; display: block;"></highcharts-chart>

Update Chart<button (click)="update_chart()">Update Chart</button>
```

**Comment by pawelfus** [comment]
Hi @paithalmi 

This is our bug tracker, if you have questions, please contact our support: https://www.highcharts.com/support

**Comment by jdwillemse** [comment]
I have this same problem and I'm not using Angular or any wrapped form of Highcharts. It is actually reproducible in the demo @KacperMadej posted above: 
https://stackblitz.com/edit/angular-9nkrgd-uccwqn?file=src/app/new-page.component.ts

In the demo click 'new page' and then click 'welcome' to see the error described above.

I'm using React and this happens when I'm trying to destroy an instances on page change.

**Comment by pawelfus** [comment]
@jdwillemse 

Demo works fine for me, no errors:

![screen shot 2018-10-10 at 11 28 23](https://user-images.githubusercontent.com/1453926/46726892-a40c9100-cc7f-11e8-98f6-1fce15b57650.png)

**Comment by jdwillemse** [comment]
Sure about that @pawelfus?
![screen shot on 2018-12-11 at 14 48 44](https://user-images.githubusercontent.com/1798297/49808231-f6d3f900-fd53-11e8-8d99-da136bd2bc43.png)

**Comment by pawelfus** [comment]
@jdwillemse 

This is part of your HTML code, console is on the left side.. See attached screenshot (line no. 4):

![screen shot 2018-12-11 at 15 55 12](https://user-images.githubusercontent.com/1453926/49808603-38b56d00-fd5d-11e8-902f-67f60448479b.png)
