### ISSUE TITLE
Sankey: valueSuffix not working in Tooltip 

### ISSUE THREAD

**Issue by imjeffp** [highcharts/highcharts#8645]
#### Expected behaviour
```
tooltip: {
          valueSuffix: " million tons"
      },
```
Should append " million tons" to the value shown in the tooltip.

#### Actual behaviour
No effect

#### Live demo with steps to reproduce
https://codepen.io/imjeffp/pen/BPLZyL
lines 88-92
(note that pointFormat and nodeFormat DO work as a workaround)

#### Product version
Highcharts JS v6.1.1 (2018-06-27)

#### Affected browser(s)
Safari, Chrome, Firefox

**Comment by sebastianbochan** [comment]
Hi @imjeffp,
Thank you for the reporting.

@jon-a-nygaard

**Comment by sebastianbochan** [comment]
Hi @imjeffp,
Thank you for the reporting.

**Workaround**
Add suffix in the `pointFormat`

```
tooltip: {
      pointFormat: '{point.fromNode.name} \u2192 {point.toNode.name}: <b>{point.weight}</b> million tons<br/>'
    },
```

Demo:
- https://jsfiddle.net/BlackLabel/p0mant76/



@jon-a-nygaard

**Comment by KacperMadej** [comment]
**Workaround**:
Could be resolved by defining `pointArrayMap` for the **sankey** series.
```Highcharts.seriesTypes.sankey.prototype.pointArrayMap = ['weight', 'sum'];```

Demo: https://jsfiddle.net/BlackLabel/p0mant76/4/

_Internal note:_
`valueSuffix` is for values - `weight` and `sum` should work for **sankey**, since `y` doesn't make much sense here - `{point.weight}` and `{point.sum}` are used in default `nodeFormat` and `pointFormat` of **sankey**.
