### ISSUE TITLE
Word cloud does not render in IE11

### ISSUE THREAD

**Issue by philclaridge** [highcharts/highcharts#8652]
#### Expected behaviour
Render workclound

#### Actual behaviour
Graph title rendered but not wordcloud.

#### Live demo with steps to reproduce
Navigate to your highcharts demos https://www.highcharts.com/demo/wordcloud in IE11 - see screenshots - wordcloud not rendered

Validated error using IE11 using multiple sites including MS test image at:
Microsoft IE11 / Win 7 test image at https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ 

![ie11](https://user-images.githubusercontent.com/126126/42956664-7ced3982-8b78-11e8-84ed-3603bd053e7a.png)

Tested using free account for IE9 (but is IE11?): at https://www.browserling.com/

![ie9](https://user-images.githubusercontent.com/126126/42956571-38089776-8b78-11e8-8e99-c5ea59c01f0f.png)

#### Product version
Highcharts current

#### Affected browser(s)
IE11. Other IE versions not tested.

**Comment by KacperMadej** [comment]
Hi @philclaridge 

Thank you for reporting about the problem.

The issue happens on any IE, because IE doesn't support `Number.MIN_SAFE_INTEGER` nor `Number.MAX_SAFE_INTEGER` used by `getBoundingBoxFromPolygon` @jon-a-nygaard 

https://github.com/highcharts/highcharts/blob/e9082f1ed28e2df2e3b04f1998a5a3227247b4ac/js/mixins/polygon.js#L168-L171

**Comment by KacperMadej** [comment]
**Workaround:**
Add a polifill like:

```js
// polifill
Number.MAX_SAFE_INTEGER = 9007199254740991;
Number.MIN_SAFE_INTEGER = -9007199254740991;
```

**Demo:** https://codepen.io/anon/pen/GBNwdo
