### ISSUE TITLE
Scatter chart update lost marker

### ISSUE THREAD

**Issue by vpckso** [highcharts/highcharts#8655]
#### Live demo with steps to reproduce
https://jsfiddle.net/vebntr80/15/

no problem if uncomment the color in update()

**Comment by pawelfus** [comment]
Hi @vpckso 

Thank you for reporting this bug. This is a bug in `setData()` which is internally called to update points. When you set color, then the series is recreated.

*Internal note:*
Simplified demo: https://jsfiddle.net/BlackLabel/vebntr80/22/

**Comment by sebastianbochan** [comment]
Hi @vpckso,
Let's consider two steps.
1) Run the demo: https://jsfiddle.net/BlackLabel/p2j50hs8/ all 6 markers are animated and visible
2) Run your demo https://jsfiddle.net/BlackLabel/yg2a7nq0/ after your setTimeout, 6 markers are visible too.

The scatter series updates all points, because all of them are visible. In the first step you have the feeling that only two of them should be updated. Its related with fact that you call update, faster then init animation ends.

**Comment by KacperMadej** [comment]
Works fine since version 6.1.4
Related to #8995
Closing as resolved
