### ISSUE TITLE
数据重合了，有办法把其中两条折线设置一点偏移吗

### ISSUE THREAD

**Issue by tabtang** [highcharts/highcharts#8656]
数据重合了，有办法把其中两条折线设置一点偏移吗
![image](https://user-images.githubusercontent.com/6836470/42997579-d8001f52-8c49-11e8-8e97-d59c12f244a5.png)

**Comment by sebastianbochan** [comment]
Hi @tabtang,
Thank you for contacting us. Could you elaborate your question in English language? It will be helpful for us in the understanding problem.

**Comment by tabtang** [comment]
@sebastianbochan The data is the same on some dates. Is there any way to set one of the two broken lines off a bit? Overlapping lines are not a good plan

**Comment by sebastianbochan** [comment]
Hi @tabtang,
This is default and mathematical logic to draw series in this way.
If you data are not zero-points, you can use [stacking]() and draw series without overlapping.

Demo:
- https://jsfiddle.net/BlackLabel/jahpf461/

**Comment by tabtang** [comment]
@sebastianbochan Using stacking:'normal', there are two problems: 1, how to adjust the distance between the broken lines; 2, why the color of the text becomes white.
![image](https://user-images.githubusercontent.com/6836470/43177095-2a71bd10-8ff9-11e8-881c-b4b0cb3a45d5.png)

**Comment by sebastianbochan** [comment]
Hi @tabtang,
Let me introduce `stacking` parameter. When its enabled, the option adds series 1 values to series 2 etc. As a result the line is draw according to summed points' values and cannot be adjusted. 

You also cannot disable "overlapping" lines, because Highcharts draws points according to point's values, so when two points has the same x/y then are placed in exactly the same place. When we move one of them, then point will be positioned incorrectly (wrong yAxis value).
