### ISSUE TITLE
Highstock chart with two panes overlap when Window is resized

### ISSUE THREAD

**Issue by nagin** [highcharts/highcharts#8660]
#### Expected behaviour
Highstock chart with two panes , when window is resized, then both pane should be resized in proportion

#### Actual behaviour
Highstock chart with two panes  when window is resized, then both pane  overlap each other.
#### Live demo with steps to reproduce
 In this demo chart. 
https://www.highcharts.com/stock/demo/advanced-stock-chart

1. First resize both pane slightly up or down using pane handle. 
2. resize window 
3. You will see series in both pane are not correctly placed. these pane overlap.  

#### Product version
Highstock 6.1.1 (currrent version)
#### Affected browser(s)

![image](https://user-images.githubusercontent.com/7149834/43067666-9b024d9e-8e85-11e8-8ac8-cd8a99dcd82b.png)

**Comment by KacperMadej** [comment]
Hi @nagin 

Thank you for reporting about the problem.

After panes are changed through `drag-panes` module the axes `top` and `height` options are being set in pixels. Next, if window resize changes layout of the rangeSelector buttons and inputs (making 2 lines instead of a single line) plot area size (height) is changed. Pixel values for axes are kept while plot area height is limited causing the overlap.

To prevent this you could prevent such changes in plot area height - e.g. disable rangeSelector.

I'm marking this as enhancement, so `drag-panes` could in the future work based on **percentage or pixel** values - depending what was set in chart options.

**Comment by KacperMadej** [comment]
After further investigation (thank you @pawelfus & @sebastianbochan ) - this is a bug, not an enhancement.
