### ISSUE TITLE
Flags tooltip broken when tooltip.outside set to true

### ISSUE THREAD

**Issue by nhitchins** [highcharts/highcharts#8669]
#### Expected behaviour
Flag tooltip should contain full border regardless of 'tooltip.outside' option

#### Actual behaviour
Tooltip border (right and bottom) is clipped on flag series when tooltip.outside=true

#### Live demo with steps to reproduce
http://jsfiddle.net/kjLh6zbn/

#### Product version
Highstock 6.1.1

#### Affected browser(s)
Chrome 67

**Comment by sebastianbochan** [comment]
Hi @nhitchins,
Thank you for the reporting.

_Internal note:_
Simplyfied demo:
- http://jsfiddle.net/BlackLabel/pdLcwfq8/

**Comment by pawelfus** [comment]
**Workaround:**

Set `tooltip.distance = 12` for flags, demo: http://jsfiddle.net/BlackLabel/uo4n9Lhb/

Snippet:
```javascript
    plotOptions: {
      flags: {
        tooltip: {
          distance: 12
        }
      }
    }
```

**Comment by pawelfus** [comment]
General demo: https://jsfiddle.net/BlackLabel/qkw9scbe/

The issue comes from using two different `distance` options for series. The first hovered series sets translation in label, which later is inaccessible: 

The snippet below is called only when initializing `tooltip.label`
https://github.com/highcharts/highcharts/blob/93d9d51f652a7dce148fb1c7260682be82c9ed59/js/parts/Tooltip.js#L288-L299
