### ISSUE TITLE
Vertical color axis doesn't adjust to the height of the chart

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#8716]
#### Expected behaviour
Color axis should be responsive (it should adjust its height to the height of the chart).

#### Actual behaviour
It's not. It always has the same size and unwanted pagination is applied if there's no enough space to draw it (see the demo).

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/bhx7wyLr/

#### Product version
6.1.1

**Comment by pawelfus** [comment]
**Note:**
This is directly caused by `legend.symbolHeight`, changing height to e.g. 150 resolves the issue: https://jsfiddle.net/BlackLabel/61uvkz2d/ Default height for `colorAxis` is 200px.

I agree, it would be useful to define colorAxis height as relation to the plotting area internally (`plotHeight/plotWidth < 200 ? plotHeight/plotWidth : 200`).

Related code:
https://github.com/highcharts/highcharts/blob/df3eadbddb51500f1c3f5ab89720e3806f465542/js/parts-map/ColorAxis.js#L494-L495
