### ISSUE TITLE
Label on exported graph image

### ISSUE THREAD

**Issue by RononDex** [highcharts/highcharts#8721]
#### Expected behaviour
When you export a data to jpg, the label for the series should be displayed as following (screenshot from web browser)
![image](https://user-images.githubusercontent.com/2249071/43580028-44e7c714-9654-11e8-879f-ed481fb8cde8.png)

#### Actual behaviour
What actually happens is, the black box around the label of the timeseries is too small, and the text overlapps the box in the jpg export (might be due to very long series name)
![image](https://user-images.githubusercontent.com/2249071/43580035-49d805b8-9654-11e8-97ea-85d1b2c0fd56.png)

#### Product version
 Highstock JS v6.0.5 (2018-01-31)

#### Affected browser(s)
Since its jpg export, not browser specific

**Comment by pawelfus** [comment]
Hi @RononDex  - please recreate issue in jsFiddle. Thanks!

**Comment by TorsteinHonsi** [comment]
@RononDex Most likely this happens because you're using a font in your chart setup that is not present on our export server. The extent of the black border is calculated in the browser based on the font that is used. However, on the server, the font is not present so it falls back to another font, but the extent of the frame is still the same, since it was calculated on the client. There are at least two possible workarounds:

1. Use another font face, like the default font, or a very common one like Arial.
2. Use the [client side export](https://www.highcharts.com/docs/export-module/client-side-export).
