### ISSUE TITLE
Some of stackLabels are not displayed when dataLabels are

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#8742]
#### Expected behaviour
**All** stackLabels should be displayed independently from dataLabels.

#### Actual behaviour
Some stackLabels are not displayed when dataLabels are displayed.

#### Live demo
https://jsfiddle.net/BlackLabel/rht1j40w/

#### Product version
6.1.1

#### Workaround 
Set yAxis.stackLabels.allowOverlap to true.

Looks like regression after commit ae932768305de4824ae0d1584f96d3343fb9bc4c

**Comment by sebastianbochan** [comment]
**Internal note**
Regression since 6.1.1.

In the 6.1.0 worked properly
- https://jsfiddle.net/BlackLabel/10wgytkh/

**Comment by babycannotsay** [comment]
@sebastianbochan hi,this problem still exists in bar.
can see <https://jsfiddle.net/gzxsc54m/1/>

**Comment by pawelfus** [comment]
Hi @babycannotsay 

Thanks for pointing this out!

**Workaround:**
Decrease `dataLabels.labelrank`: https://jsfiddle.net/BlackLabel/qa9yxb1g/

*Internal note:*
For inverted charts, `plotWidth` should be taken instead of `plotHeight`:

https://github.com/highcharts/highcharts/commit/5e32ec7facc56d3952112cdff581d1f812836da2#diff-ab2057e2acad2e59110a7bb3938a9707R107

**Comment by babycannotsay** [comment]
@pawelfus Thank you for your answer.
I have a question about labelRank which commented as follows
```
// Prevent a situation in a gradually rising slope, that each label will
// hide the previous one because the previous one always has lower rank.
```
Is there a demo?

**Comment by pawelfus** [comment]
I'm not sure what do you mean.. In general this is the case: https://jsfiddle.net/BlackLabel/wf6hg1qL/ - as you can see, one label has higher priority, so it's displayed (label =150).
