### ISSUE TITLE
Stock Chart - Data points don't get accumulated in dynamic stock chart

### ISSUE THREAD

**Issue by tejaspchordiya** [highcharts/highcharts#8758]
#### Expected behaviour
Older data points should get accumulated when new data gets added to the dynamic stock charts.

#### Actual behaviour
Older data points are getting lost if any new point gets added to the chart. Neither there is any mechanism to view the older data points once they are lost.

#### Live demo with steps to reproduce
[Highstock Dynmaic Chart Demo](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/dynamic-update/)
NOTE: In the above demo, oldest data points are getting lost. And once these are lost, they cant be viewed again by user.

**Comment by pawelfus** [comment]
Hi @tejaspchordiya 

This is caused by `shift` argument in `addPoint(point, redraw, shift, animation)` function. Set it to false to change this behaviour: https://jsfiddle.net/BlackLabel/mf47crh2/

More details can be found in our API: https://api.highcharts.com/class-reference/Highcharts.Series.html#addPoint

**Comment by tejaspchordiya** [comment]
Got it! Thanks for the help..
