### ISSUE TITLE
Screen readers (NVDA and JAWS) don't read aloud point's description in IE11 and Edge.

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#8814]
NVDA - https://www.nvaccess.org/
JAWS - https://www.freedomscientific.com/Downloads/JAWS

Both programs (and propably other screen readers too) can't read aloud point's description when you navigate using keyboard.

#### Live demo with steps to reproduce
Install one of the programs above.
https://codepen.io/jharri/full/OwYZyy/
Use TAB to navigate and find point. In modern browsers screen reader reads point's description as expected, but in IE11 and Edge does not.

#### Product version
6.1.1

#### Affected browser(s)
IE11, Edge

**Comment by sebastianbochan** [comment]
@oysteinmoseng any comments?

**Comment by oysteinmoseng** [comment]
This is strange, but there seems to have been some recent changes to how Edge handles SVG accessibility.

The issue with IE11 is that it doesn't support `focus` calls on SVG elements, so it is not picking up that you are moving between elements. There is little we can do to fix this. We have discussed implementing a different solution where we would be taking over all keyboard navigation, effectively disabling the screen reader for the chart, and just sending manual updates to the screen reader (`role="application"`). The downside is that the screen reader user would have to learn our keyboard shortcuts, and not be able to use the familiar keyboard shortcuts from the screen reader. This is a major disadvantage, and currently stops us from relying on a solution like this. It seems modern browsers and screen readers are instead moving towards better support for accessible SVG, and a solution like this should not be necessary.

Edge used to have the same issue as IE11 with lacking support for `focus`, but implemented support after we contacted them. This means that in theory, Edge users should be able to use our keyboard navigation and still have the screen reader announce the data points, as long as the screen reader is not blocking the keystrokes. It seems JAWS 2018 is not picking up on the focus change, however. With a minimal SVG demo I am able to make JAWS pick up focus changes in Edge, but not in our charts. Hopefully this is something that changes with a future JAWS or Edge update. From our side, all we are doing is setting focus to the active element as you are navigating to it, and in most browsers this works fine.

Note that due to most screen readers blocking keystrokes and using them for their own keyboard shortcuts, it is generally easier to navigate our charts using the screen reader shortcuts. For JAWS you can move through the chart using down and up arrow, and use regions/landmarks to switch between series.

**Comment by oysteinmoseng** [comment]
Closing this for now, feel free to reopen if new information surfaces.
