### ISSUE TITLE
Shared tooltip in boost mode, all series not included

### ISSUE THREAD

**Issue by TorsteinHonsi** [highcharts/highcharts#8818]
#### Expected behaviour
All points to display at all times. All series have equal X values.

#### Actual behaviour
Random series display

#### Live demo with steps to reproduce
https://jsfiddle.net/highcharts/8ydq59hw/119/

#### Product version
6.1.0

**Comment by KacperMadej** [comment]
Still an issue with mixed (or mixed findNearestPointBy option) series types - https://jsfiddle.net/BlackLabel/8ydq59hw/177/

**Comment by KacperMadej** [comment]
+1
@cvasseng boost issue

**Comment by cvasseng** [comment]
Fixed (again) in 9da4e43. The issue was a rounding error causing the points to end up on different x-values in the boost Kd-tree. It only impacted `column` series as far as I could tell.

Demo of fix: https://jsfiddle.net/Lqge6j10/

[PR has been submitted](https://github.com/highcharts/highcharts/pull/9545).

Will be part of the next release.
