### ISSUE TITLE
3d + zooming - yAxis highlighted when we click and drag over it

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#8867]
When 3d and zooming are enabled in a column chart and we start dragging out of the plot area (over y-axis), the y-axis is being highlighted.

![y-axis selection](https://user-images.githubusercontent.com/23310742/44865953-1901a980-ac84-11e8-92de-e3b346f62499.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/b2g6j0ax/

#### Product version
6.1.1

#### Affected browser(s)
All

**Comment by Izothep** [comment]
I think the same, for now zooming suppose to be disabled in 3D charts, because zoomed area is not calculated correctly from the mouse coordinates. However, the idea of creating the fully supported 3D zooming sounds really good.

Related topic: https://github.com/highcharts/highcharts/issues/3131

_Internal note:_ 
To calculate the correct coordinates we may need to create the function that will be the opposite of the internal perspective function. I have started working on this idea during some tests related to 3D charts, for now good idea may be to leave enhancement label.
