### ISSUE TITLE
[Highstock]Zooming while dynamically changing candlestick value => Mess

### ISSUE THREAD

**Issue by george77** [highcharts/highcharts#889]
In the example at http://jsfiddle.net/ckXaz/8/ ,
I have a candlestick chart whose last candlestick is dynamically updated every second.
If you try to change the zoom (either by using the mouse on the chart or on the navigator in the bottom), everything gets messed up and there seem to be generated more than one copies of the series.
Is there a workaround to this or is this a bug?
I posted also on the forums but got no help.
Thanks

**Comment by ashrafsarhan** [comment]
Any update regarding this issue!

**Comment by TorsteinHonsi** [comment]
I can't see a problem with the original jsFiddle now. Can provide detailed steps to reproduce based on http://jsfiddle.net/highcharts/ckXaz/52/?

**Comment by ashrafsarhan** [comment]
@TorsteinHonsi 
Thanks for your quick response, I'm using [AngularJS directive for Highcharts] (https://github.com/pablojim/highcharts-ng) and I think that this issue with it and not with the original Highcharts library
Sorry for inconvenient but I thought that my issue was due to this bug as it's still opened!

**Comment by TorsteinHonsi** [comment]
Ok, no problem!
