### ISSUE TITLE
xAxis.showEmpty: false not working in highstock

### ISSUE THREAD

**Issue by jay2452** [highcharts/highcharts#8917]
#### Expected behaviour
The xAxis title and labels should get removed after clicking on legend.

#### Actual behaviour
After clicking on legend, the xAxis labes and title is not getting removed from the chart area.

#### Live demo with steps to reproduce

![highstock issue disable legend- 2](https://user-images.githubusercontent.com/8395843/45295356-0c027700-b51c-11e8-9f39-88ce633cd395.png)

http://jsfiddle.net/jayantt/aLj3xur4/1/
#### Product version

Highstock 6.1.0

**Comment by pawelfus** [comment]
Hi @jay2452 

Thank you for reporting the issue. This is expected behaviour as per #705 - as long as extremes are defined (with navigator, those are always defined) the `showEmpty` option does not affect an axis.

Workaround works for this case too: http://jsfiddle.net/BlackLabel/aLj3xur4/3/

Related issues: #6190 and #705

**Comment by pawelfus** [comment]
Fixed since v7.1.0: http://jsfiddle.net/BlackLabel/aLj3xur4/6/
