### ISSUE TITLE
Bubble chart display labels for bubbles that are out of range in y-axis

### ISSUE THREAD

**Issue by peterlacko** [highcharts/highcharts#8923]
#### Expected behaviour
Bubble's label should not be shown when bubble is hidden by min option on y-axis.

#### Actual behaviour
Bubble's label is still visible, see bubble "Hungary" in provided demo, down-left, that should not be visible at all. Doesn't happen on x-axis

#### Live demo with steps to reproduce
https://jsfiddle.net/7vgs0fd4/3/

#### Product version
Highcharts v6.1.2

#### Affected browser(s)
Latest Chrome and Firefox, others likely as well

**Comment by pawelfus** [comment]
I think it makes sense to render this bubble. Changing extremes just a bit to get center inside the extremes and we have half bubble: https://jsfiddle.net/BlackLabel/7vgs0fd4/28/

**Comment by sebastianbochan** [comment]
_Internal note_
It make sense but in that option we should use something like "snap" around the `plotArea` to render points close to border. Im afraid that it can be tricky due to performance reasons.

At this moment filtering dataLabels seems to be simpler and more efficient solution. 

@TorsteinHonsi @pawelfus do you agree ?
