### ISSUE TITLE
minPointLength support for sankey chart

### ISSUE THREAD

**Issue by shiliangdn** [highcharts/highcharts#8927]
#### Expected behaviour
We need to add  support for this attribute in sankey chart to avoid dataLabel overlap.

#### Actual behaviour
Right now, this attribute will be ignore in sankey chart.

**Comment by pawelfus** [comment]
Hi @shiliangdn 

Thank you for your suggestions. Could you attach a demo where it's needed? It will help us to provide better solution. Thanks!

**Comment by calsupik** [comment]
I am looking for this enhancement as well. It is currently ignored in sankey charts. In my below demo, the node 'No Next Step' has a very small weight, and no paths after it, therefore the node is extremely small (I understand it is by design). It would be beneficial in my specific use case to have a minimum height for that node so that the label fits fully inside of the node. I believe supporting minPointLength would be able to satisfy this. Let me know if there is any other way to currently set a minimum height for sankey nodes.
 
https://jsfiddle.net/tvwr8fd3/193/

**Comment by mkpasala** [comment]
@pawelfus here is the link to the scenario http://jsfiddle.net/Lmn6gjby/24/ . Can I move the node text up/down, its always appearing in the middle of the link.
