### ISSUE TITLE
Different min and max values after applying setExtremes() with same values on two box plots

### ISSUE THREAD

**Issue by kapikapi** [highcharts/highcharts#8952]
I am aplying setExtremes() at x axis for two box plots with the same min and max values.
 
#### Expected behaviour
Plots have exactly the same borders, as min and max are the same.

#### Actual behaviour
Plots have different min and max values.

![image](https://user-images.githubusercontent.com/5765509/45484672-90900800-b75d-11e8-8c56-b87c6fa08f3f.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/2hvsczwr/27/
Press 'Set extremes' button and see different min and max points for two plots.

#### Product version
Highcharts 6.1.1 is used.

#### Affected browser(s)
Checked on Chrome.

**Comment by pawelfus** [comment]
Hi @kapikapi 

Thank you for reporting the issue. This is expected behaviour, because boxes on charts have different width and different amount of space may be needed to prevent cutting off boxes. 

You can sync this behaviour by setting [`pointRange`](https://api.highcharts.com/highcharts/series.boxplot.pointRange) for all boxplot series: https://jsfiddle.net/BlackLabel/4k76dp3g/
