### ISSUE TITLE
Highboost Rendering issue

### ISSUE THREAD

**Issue by nsdevaraj** [highcharts/highcharts#9064]
#### Expected behaviour
Columns should appear proper

#### Actual behaviour
It's not rendering properly when data is more than a thresold

#### Live demo with steps to reproduce

http://jsfiddle.net/nsdevaraj/sfbzvw97/ works fine 

Just by adding one more series it doesn't render proper
http://jsfiddle.net/nsdevaraj/sfbzvw97/1
#### Product version

6.1.3
#### Affected browser(s)
All Browsers

**Comment by TorsteinHonsi** [comment]
Thanks for reporting, but the two fiddles look the same to me...

**Comment by nsdevaraj** [comment]
![screenshot_20180927-124408__01](https://user-images.githubusercontent.com/274062/46129103-4164cf80-c253-11e8-9ed8-e1f9df64d694.jpg)
This is the output i got for http://jsfiddle.net/nsdevaraj/sfbzvw97/1

**Comment by pawelfus** [comment]
Hi @nsdevaraj 

For me too, both charts looks exactly the same. This is my output partial:

<img width="655" alt="screen shot 2018-09-27 at 12 09 29" src="https://user-images.githubusercontent.com/1453926/46139422-c699b580-c24e-11e8-9c1c-8ccf11dca723.png">

Please, set fixed width for the chart and provide more detailed description. At this moment we don't know what exactly is not rendered properly.

**Comment by nsdevaraj** [comment]
Can you please try removing some data in series. Then it produced proper output

**Comment by nsdevaraj** [comment]
https://jsfiddle.net/nsdevaraj/sfbzvw97/ expected output

**Comment by TorsteinHonsi** [comment]
Just a random thought here @cvasseng: In cases where the column width is likely to be more than 1px, for example if the number of points is smaller than the plotWidth, we could run the columns through the regular translation and then use `point.shapeArgs` to draw them on the WebGL canvas. We can do this because we don't have a great number of point instances to handle in the first place in this case, so performance is not an issue.

The alternative (if we want to support wider columns at all), is to recreate the whole stacking/grouping/padding logic again in Boost, which is probably not a good idea.
