### ISSUE TITLE
Memory usage of version 6 is much higher than version 5, causing idle tabs to crash upon revisit

### ISSUE THREAD

**Issue by negarn** [highcharts/highcharts#9066]
#### Expected behaviour
Revisiting idle tabs after upgrading highcharts from version 5.0.14 to 6.1.3 will update the chart with the missed data points and continue as before

#### Actual behaviour
Revisiting idle tabs causes memory outage when trying to update all the missed data points and causes the page to freeze

#### Live demo with steps to reproduce
1. open a tab with https://jsbin.com/wirazuh/edit?js,output(version 6.1.3)
2. open a tab with https://jsbin.com/pizoyor/edit?js,output (version 5.0.14)
3. position them side by side so you can see both streaming charts and use a tool such as task manager in chrome to see the memory usage. The tab with version 5.0.14 will always be using much less memory.
4. leave both tabs streaming for some minutes, the memory increases in the new version much more than the old version. This is a simplistic example that might not show the page crashing, but in the more complex real-life usage it does.

#### Product version
6.1.3 versus 5.0.14

#### Affected browser(s)
All browsers

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

In order to rule out memory issues with JSBin or the console, I took your chart configuration and added to two files, the reference and the candidate. Sped up the sitTimeout to 250 ms and let it run for some minutes several times. Also added a fixed width for the container to make sure they are rendering the same amount of elements.

![skjermbilde 2018-09-28 kl 12 42 43](https://user-images.githubusercontent.com/227836/46204152-8274e680-c31c-11e8-941f-a2c8aa5f42bc.png)

I'm not able to see a memory issue - in fact, most of my attempts had lower memory consumption on the candidate (the newer release), although not significantly.

**Comment by negarn** [comment]
That's strange, since we can consistently reproduce it. I will close it then, we will just keep using the older version.
