### ISSUE TITLE
Highstock multiple series zoom reset on adding point

### ISSUE THREAD

**Issue by muddymess** [highcharts/highcharts#9075]
When zooming into a HighStock multi-series line chart with navigator, the zoom resets or jumps to start of series when adding a new point but only if current zoomed area is missing full data from that series.

What should happen is the same behavior as when all series have data in current zoomed area; the zoomed area stays the same.

Example:
http://jsfiddle.net/7qtbfwu4/10/
To trigger issue: select zoom range lower than all, then drag navigator off secondary series (or until zoomed area contains secondary series start point).

Issue exists up to HighStock v6.1.1 (latest tried)

**Comment by TorsteinHonsi** [comment]
Thanks for reporting!

**Comment by muddymess** [comment]
Possibly related issue: when main serie is lacking data but zoomed area is at leading edge (automatically scrolling), it will zoom to fit main series regardless of if secondary series has data for entire span.

Example:
http://jsfiddle.net/7qtbfwu4/12/
Trigger by clicking 15M/30M range.

Should I open a new issue for this?

**Comment by pawelfus** [comment]
Hi @muddymess 

It looks like the same issue: when displaying multiple series in navigator (with different extremes) automated sticking to last point is broken.

*Internal note:*
It's broken since v5 (introducing multiple series in navigator): http://jsfiddle.net/BlackLabel/7qtbfwu4/15/ 

**Workaround:**
Show only the longest series in navigator: http://jsfiddle.net/BlackLabel/7qtbfwu4/17/ and http://jsfiddle.net/BlackLabel/7qtbfwu4/20/
