### ISSUE TITLE
Invalid column order with nagative values (column chart)

### ISSUE THREAD

**Issue by stepankoci** [highcharts/highcharts#9113]
#### Expected behaviour
Column chart should respect series order when values are negative.

#### Actual behaviour
Chart columns has different order than series.

#### Live demo with steps to reproduce
https://jsfiddle.net/ezbtnfcw/

#### Product version
Highcharts 6.1.4

#### Affected browser(s)
Google Chrome, 69.0.3497.100

**Comment by stepankoci** [comment]
Here is demo with `index` properties: https://jsfiddle.net/zsbpanef/

**Comment by pawelfus** [comment]
Hi @stepankoci 

This is expected behaviour. In column series, you have two stacks: negative and positive. Both stacks start indexing from value "0", consider this example: https://jsfiddle.net/BlackLabel/ezbtnfcw/1/ - all stacks starts with green series. If you change just one point in a stack ( https://jsfiddle.net/BlackLabel/ezbtnfcw/4/ ) - then it will render in a different stack (you can see separate stackLabel for Grapes category).

**Comment by stepankoci** [comment]
Hi @pawelfus 
thank a lot for your fast answer! And apologise for my late response.
Now I understand, but we have still issue with chart and column ordering. I will try write a better description (i'll create new issue).
Thank you!
