### ISSUE TITLE
Data labels sometimes overlap total lable

### ISSUE THREAD

**Issue by DK-Unit4** [highcharts/highcharts#9119]
#### Expected behaviour
The labels do not overlap the totl label

#### Actual behaviour
in many cases the algorithm correctly hides one or another, but still sometimes they overlap

#### Live demo with steps to reproduce
https://jsfiddle.net/Kumlander/adwtLqrn/5/
here the width is auto if you will move the width to be wider or narrower then t certain sizes the total label will be overlapped with the individual data one.

#### Product version
Highcharts 6.1.4

#### Affected browser(s)
at least chrome
![capture](https://user-images.githubusercontent.com/38954233/46425265-daa85000-c743-11e8-9ae3-946565a578d7.PNG)

**Comment by pawelfus** [comment]
Hi @DK-Unit4 

Thank you for reporting the issue.

Simplified demo: https://jsfiddle.net/BlackLabel/25m4npsc/

**Workaorund:**
Disable padding for dataLabels: https://jsfiddle.net/BlackLabel/adwtLqrn/10/

*Internal note:*
Collision is caused by padding - we subtract padding from width and height, but we don't reflect  this in x/y positions: https://github.com/highcharts/highcharts/blob/806c78bf3758ba4651d32e16b1df44ab714dbe7e/js/modules/overlapping-datalabels.src.js#L137-L142
