### ISSUE TITLE
Crosshair disappears after zooming (Chrome)

### ISSUE THREAD

**Issue by raf18seb** [highcharts/highcharts#9130]
#### Actual behaviour
Crosshair disappears after zooming and isn't visible before we move the mouse.

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/amz0d5h2/

#### Product version
6.1.4

#### Affected browser(s)
Works in Edge and Firefox, doesn't work in Chrome 69.0.3497.100 (64-bit)

**Comment by pawelfus** [comment]
Could your provide detailed steps to recreate the issue? This looks fine for me:

![akqpsakcpy](https://user-images.githubusercontent.com/1453926/46486562-51a21f00-c7fe-11e8-9b0f-bd0e89734914.gif)

**Comment by raf18seb** [comment]
This issue affects only Chrome browser.

**Comment by KacperMadej** [comment]
Problem visible on Win 10: Chrome / IE11. 
(FF / Edge work fine)

**Comment by wiola111** [comment]
has there been any update on this?

**Comment by KacperMadej** [comment]
I did some debugging and the problem seems to be going down to a Chromium + Windows issue reported here: https://bugs.chromium.org/p/chromium/issues/detail?id=161464
and here: https://bugs.chromium.org/p/chromium/issues/detail?id=721341

In short: `mousedown > mousemove> mouseup` action chain triggers an additional `mousemove` that clears the crosshair under some conditions - namely using Chrome and possibly Windows.

**Comment by KacperMadej** [comment]
The problem is caused by OS and/or browser. We could workaround the problem because we cannot fix any of the mentioned two sources, or we could wait for a fix to be done by OS/browser maintainers/creators. I'm not sure if we are willing to add a fix in Highcharts code (@TorsteinHonsi ?), but here's a demo with workaround added:

http://jsfiddle.net/BlackLabel/amz0d5h2/1/

The workaround ignores events that are triggered by an event with no movement.

_Internal note:_ Unknown if a filter like this would influence any automated tests run in our Utils or in pre-commit tests run in headless.

**Comment by TorsteinHonsi** [comment]
In principle I think we should be pragmatic and add workarounds for browser issues when necessary. But I agree with Kacper that a filter like this is risky. We should try to find a workaround closer to the crosshair logic to eliminate the risk of side effects.

**Comment by wiola111** [comment]
Has there been any update on the above? Is a better workaround possible? Thanks

**Comment by sebastianbochan** [comment]
Hi @wiola111,
Intead of build-in crosshair, you can draw them on your own by renderer. Catch `mouseOver` and `mouseOut` events and draw correct lines.

Demo:
- https://jsfiddle.net/BlackLabel/pzhyotm3/

**Comment by wiola111** [comment]
The code draws crosshairs in the wrong positions if module series.label is not present. Having it present displays series name which is not a desirable effect. See fiddle: https://jsfiddle.net/t5domh9b/

**Comment by pawelfus** [comment]
Hi @wiola111 
Could you attach a screenshot of the issue? Thanks!

**Comment by wiola111** [comment]
Thanks for response, attaching... This is what happens after zoom (can be reproduced using fiddle above). Crosshair should be over point 2 on x axis where the tooltip is.
![2019-02-07_16h14_55](https://user-images.githubusercontent.com/8726265/52425270-8ba86800-2af3-11e9-9924-eca9863918bd.png)

Also this is reproducible on this chart (and I think any of them) that do not contain series-label.js module. See: https://jsfiddle.net/dgqabh2w/2/ and then include the module - crosshair correctly appears.

Help appreciated, thanks !

**Comment by pawelfus** [comment]
Thanks! Then a bit improved solution would be: https://jsfiddle.net/BlackLabel/c7o38w1t/3/ - it renders crosshair also after zooming in/out.

**Comment by wiola111** [comment]
Thank you
