### ISSUE TITLE
Wrong xAxis values with datetime

### ISSUE THREAD

**Issue by ghost** [highcharts/highcharts#9143]
Hi,

I have a simple chart bound with one datetime in category as follow

http://jsfiddle.net/3e3xqv7e/235/

You can see that both in tooltip and in xAxis the value of my category is 1577826000000

Once I add another datetime value in category at least the first xAxis label is changed to 1577836800000 instead of 1577826000000, tooltip value remains correct though.

http://jsfiddle.net/3e3xqv7e/237/

Also on the second link category tick doesn't seems to be centered anymore.

Am I doing something wrong here ?

**Comment by sebastianbochan** [comment]
Hi @Dams591,
Thank you for contacting. By default Highcharts returns timestamp in `this.value` and you should use `Highcharts.dateFormat` to convert timestamp into user-friendly format.

Demo:
- http://jsfiddle.net/BlackLabel/0w5uL3dh/

Docs:
- https://api.highcharts.com/class-reference/Highcharts#.dateFormat

**Comment by Dams591** [comment]
Hi @sebastianbochan 
Formatting is not this issue, well it might be but the issue is that the tooltip value is different from the x axis value once you have more than one category doesn't matter if you've formatted it or not.
I've updated your fiddle when you can clearly see the issue, here's a screenshot too.

http://jsfiddle.net/0w5uL3dh/2/

![image](https://user-images.githubusercontent.com/12731716/46721076-79680b80-cc72-11e8-8d74-0bcb0f55e3b9.png)

Thanks.

**Comment by pawelfus** [comment]
Hi @Dams591 

Thank you for the clarification!

Let me explain what happens: you have points at 21:00, but xAxis ticks (for days) are always rendered at 00:00. That means 31-12-2019 00:00:00.000 is outside the visible xAxis range, so first daily tick is rendered at 01-01-2020 00:00:00.000. There's not direct relation one point=one tick. However we can achieve this using [`xAxis.tickPositioner`](https://api.highcharts.com/highcharts/xAxis.tickPositioner). 

Demo: http://jsfiddle.net/BlackLabel/3e3xqv7e/243/

**Comment by Dams591** [comment]
@pawelfus make sense ! Thanks !!
