### ISSUE TITLE
Export data (CSV, XLS) on iOS Safari does not work

### ISSUE THREAD

**Issue by syd-mlp-sean** [highcharts/highcharts#9156]
#### Expected behaviour
When using the offline/export data plugin in Highcharts, clicking Download CSV or XLS on an iOS device should open the exported format.

#### Actual behaviour
Nothing happens when selecting to Download CSV or XLS on iOS.

#### Live demo with steps to reproduce

https://www.highcharts.com/demo/funnel
http://jsfiddle.net/highcharts/cqjvD/show

Open a demo page using the export-data plugin and try to use a download link from the menu.

#### Product version
Highcharts current version

#### Affected browser(s)
iOS browsers Safari, Chrome

**Comment by sebastianbochan** [comment]
Hi @syd-mlp-sean,
By default all iOS browsers do not save file but open in a tab. You can try to use workaround which shows CSV as right content (instead of blank page) like here:
- http://jsfiddle.net/BlackLabel/6z1reb7t/

If it is still not enough, you should use external libraries to it. I.e `FileSaver`, `FileReader`, `Blob`

Related topic:
- https://stackoverflow.com/questions/29134418/how-to-download-a-blob-file-from-chrome-ios-in-javascript

**Comment by oysteinmoseng** [comment]
CSV/XLS downloads should now open in a new tab on iOS, and can be downloaded from there
