### ISSUE TITLE
xAxis values are not rendered properly on zoom

### ISSUE THREAD

**Issue by nagdevbharat** [highcharts/highcharts#9157]
#### Expected behaviour
when zooming the chart and using range selector button the xAxis values should be properly rendered

#### Actual behaviour
after zooming multiple times and using range selector the xAxis values are either blank or not getting updated on click

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/xd1vzojh/  -used one of the fiddles from the answers
1. change the zoom type to xy
2. zoom the chart multiple times
3. click on reset zoom
4. apply 1 hour range selector then 1 day , 1 month and so on

some times values will be updated sometimes it will be blank or not rendered at all

#### Product version
Highcharts 6.1

#### Affected browser(s)
All browsers

**Comment by pawelfus** [comment]
Hi @bharatnagdev 

Thank you for reporting the issue! This is result of forced dataGrouping. With disabled dataGrouping (recommended for async loading of data) it works as expected: https://jsfiddle.net/BlackLabel/oqn6u3y5/

Forced dataGrouping can group points into higher groups (e.g. one day of data -> one data point) so you will see only one point on a chart. I couldn't recreate issue with no points at all.

**Comment by bharatnagdev** [comment]
Hi @pawelfus 

Thanks for the update but the issue is not about points on plot area. what actually i wanted to highlight is the xAxis labels shown while performing the steps given above.
please look into the highlighted area in a screenshot shared
![highcharts demo jsfiddle](https://user-images.githubusercontent.com/43880269/46804597-ac98c080-cd80-11e8-8bda-0fcc7e5bca3e.png)

**Comment by pawelfus** [comment]
Hi @bharatnagdev 

Thank you for the clarification! Sorry, I misread the issue. Still this is the same issue with enabled dataGrouping - dataGrouping should be disabled when async loading is in use (see my demo). It's a different method for performance optimisation.

**Comment by bharatnagdev** [comment]
Hi @pawelfus 
Thank you for the explanation however i am using 'approximation' in dataGrouping.
Can you please help me to resolve it?
P.S.: Sorry couldn't generate fiddle for that one.

**Comment by pawelfus** [comment]
Hi @bharatnagdev 

I don't see any better solution than disabling dataGrouping. Could you explain why you need `approximation` and `dataGrouping`? Maybe you don't need `approximation` method, but something simpler.

**Comment by bharatnagdev** [comment]
Hi @pawelfus 
I am having a user interface in which user has the ability to select the grouping method as per the data user wants.
anything else you can just for the same?

**Comment by pawelfus** [comment]
Yes @bharatnagdev I think I can: instead of using build-in dataGrouping, request new data from server with specified grouping. For example request params would be not only `start` and `end` but also `approximation` which would return grouped points according to the dataGrouping.

If you don't want to group points in the backend with different approximations, then manually group points **before** setting new data in `setData()`.
