### ISSUE TITLE
Scatter chart update plots inconsistent data points

### ISSUE THREAD

**Issue by sgibson53** [highcharts/highcharts#9184]
I have a scatter plot (data points connected with a series line). Page load consistently plots correctly, but updating with new series data brings unexpected data points in the graph.

#### Expected behaviour
Plot consistently when updating with new series data

#### Actual behaviour
Inconsistent data points show up depending on previous series data.

#### Live demo with steps to reproduce
http://jsfiddle.net/g8uxne36/2/

#### Product version
Highcharts JS v6.1.4

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @sgibson53 

Thank you for reporting the issue. It's a problem when updating data with the same amount of points. Instead of `chart.update()` use [`series.setData()`](https://api.highcharts.com/class-reference/Highcharts.Series#setData) and set `updatePoints =false`. Demo: http://jsfiddle.net/BlackLabel/g8uxne36/6/

Closing as duplicate of #9037 (please check alternative workaround there).

**Comment by sgibson53** [comment]
Thanks @pawelfus  for the quick reply and workaround. I'll give that a try here soon. 
Please note that the data sets do **not** have the same amount of points.  I can't remember their exact numbers, but I know they are not the same data sets with altered point values.
