### ISSUE TITLE
Bug: Negative border on area with incorrect color due chart height

### ISSUE THREAD

**Issue by merakmarey** [highcharts/highcharts#9198]
#### Expected behaviour
Negative border on area chart should show in red color (defined by negativeColor prop)

#### Actual behaviour
Negative border on area chart shows in green color, inherited from color for positive area.

#### Live demo with steps to reproduce
http://jsfiddle.net/0srqapLz/

#### Product version
Highstock JS v6.1.4 (2018-09-25)

#### Affected browser(s)
Chrome latest version

**Comment by pawelfus** [comment]
Hi @merakmarey 

Thanks for reporting this bug. It looks like broken when using `setData()`. When initializing chart with data it works fine: http://jsfiddle.net/BlackLabel/0srqapLz/1/

**Workaround:**
Instead of `setData()` use `update()` with reapplied `negativeColor`: http://jsfiddle.net/BlackLabel/0srqapLz/2/

*Internal note:*
Minified demo: http://jsfiddle.net/BlackLabel/mcr6edhg/15/

**Comment by merakmarey** [comment]
Will do. What really intrigues me is why and how is related to chart height. If chart is a little taller and I use setData it will work well. Thanks anyway.

**Comment by pawelfus** [comment]
Thanks for the remarks! I agree, that's really strange that height does matter..
