### ISSUE TITLE
Zooming doesn't scale Y axis if setExtremes() was called

### ISSUE THREAD

**Issue by kfir124** [highcharts/highcharts#9229]
#### Expected behaviour
Zooming shall ignore setExtremes(), I would want the Y axis to scale like it would if setExtremes() wasn't called

#### Actual behaviour
After you call setExtremes() zooming the chart will not scale the Y axis at all, after you reset the zoom it returns to the previous scale (ignoring the setExtreme)

#### Live demo with steps to reproduce
http://jsfiddle.net/dqnm6ry0/
Try to zoom (select range) in the chart, you can see the Y axis will scale accordingly.
Reset zoom.
Now click setExtremes().
Now zoom.
You can see the Y axis is constant and not scaling at all.

#### Product version
Highcharts all

#### Affected browser(s)
All

#### What I ended up doing
I hooked into the zooming event (selection) and before the zooming happens I remove the setExtremes(null, null) and after it happens I return the setExtremes again (with the cached extremes from before the zoom)

**Comment by pawelfus** [comment]
Hi @kfir124 

Thanks for reporting the issue, but I'm not sure if the expected behaviour is really expected. In short:
- `yAxis.setExtremes()` modifies only yAxis extremes
- `zoomType: x` modifies only xAxis extremes
- if yAxis **has no extremes set**, then yAxis rescales, no matter the reason (`addPoint()`, zooming/panning, resizing browser's window etc.)
- reset zoom button resets extremes on all axes

I would be surprised if I call `yAxis.setExtremes()` and then I need to call it every time anything on a chart changes, like browser size.

The solution you have is something I would expect to write in your case - resetting extremes in [`chart.events.selection`](https://api.highcharts.com/highstock/chart.events.selection) event.
