### ISSUE TITLE
Second call to chart.destroy fails

### ISSUE THREAD

**Issue by fiantsev** [highcharts/highcharts#9232]
#### Expected behaviour
Multiple invocations to destroy method of chart should be safe

#### Actual behaviour
the second and any further invocations will be failed

![image](https://user-images.githubusercontent.com/25036176/47300809-16895380-d626-11e8-8c36-e373fc15942e.png)

#### Live demo with steps to reproduce
[demo](https://jsfiddle.net/gorjy0x1/2/)
Steps:

1. Load the demo
2. Open the console

#### Product version
Highcharts 6.2.0, 6.1.1, maybe others

#### Affected browser(s)
Chrome Version 69.0.3497.100 (Official Build) (64-bit)

#### additional info
i saw [similar issue here](https://github.com/highcharts/highcharts/issues/8643) - now its closed but maybe its relevant.

**Comment by pawelfus** [comment]
Hi @fiantsev 

Thanks for reporting the issue. I'm not sure if we should place everywhere sanity checks if chart was destroyed - personally I would be really confused (and angry while debugging) that destroyed element is not throwing errors when operation within this object was performed. What do you think @TorsteinHonsi ? It would require additional checking in every public API method. Alternatively, we can modify prototype by removing API methods, so it will throw an error or do nothing (happy debugging).

PS: I recommend you to destroy chart as: `if (chart) { chart = chart.destroy() }`, otherwise you may be accidentally performing actions on a chart that doesn't exists. Multiple `chart.destroy()` calls suggest you may as well call any API methods (e.g. `chart.addSeries()`) which may fail silently.

**Comment by fiantsev** [comment]
@pawelfus 
i didn't propose to add sanity checks everywhere. The only thing i meant is to add one conditional check at the beginning of the destroy method like this:
```javascript
destroy() {
    if (this.alreadyDestroyed)
        /*do nothing*/;
    else
        /*do destroying stuff*/;
}
```

**Comment by pawelfus** [comment]
@fiantsev not everywhere, but every API method, for example `chart.addAxis()`: https://jsfiddle.net/BlackLabel/gorjy0x1/18/ `setSize()`, `setTitle()`, `showLoading()`, `update()` etc. - all of them otherwise will throw error, while `destroy()` not which will be confusing.

**Comment by rriixx** [comment]
@pawelfus 
> PS: I recommend you to destroy chart as: `if (chart) { chart = chart.destroy() }`, otherwise you may be accidentally performing actions on a chart that doesn't exists. Multiple `chart.destroy()` calls suggest you may as well call any API methods (e.g. `chart.addSeries()`) which may fail silently.

I faced the same exception being thrown while calling `chart.destroy()` twice.
Just checking `if (chart) { chart = chart.destroy() }` is not enough.
After the chart is destroyed call `destroy()` again and `chart` is giving you an empty object `a.Chart {}` which results in a truthy condition.

**Comment by pawelfus** [comment]
Hi @rriixx 
It's not, `destroy()` returns undefined not an empty object. See: https://jsfiddle.net/BlackLabel/gorjy0x1/20/

Maybe you did `if (chart) { chart.destroy() }` not `if (chart) { chart = chart.destroy() }`
