### ISSUE TITLE
Error when switching graphic types (Line vs Column)

### ISSUE THREAD

**Issue by engagex** [highcharts/highcharts#9243]
#### Expected behaviour
Display the same information in each date for different graphic types.

#### Actual behaviour
Depending on the type of graphic selected (line and column), the following happens:
1) the date range differs (initial and end date)
2) the values get screwed up, just by looking at the graphic scale (using the ALL zoom). In the line version, the scale on the right is 400%, in the column version, it is 1500% (and the data feeded to both graphics are exactly the same)
3) If you look in individual points in the grapgic (for instance, they change values and variation)
4) when you resize the column bar graphic, it messes up with the data as well.

#### Live demo with steps to reproduce
https://jsfiddle.net/mmsdiego/uxm2kw9f/8/

#### Product version
Highstock 6.2.0

#### Affected browser(s)
Chrome (probably all)

#### Obversations

Could you help me find out? apparently the line graphic behaves well with this dataset, but the column does not. Are we making any mistakes configuring it? 

Thanks, 
@dtiziani

**Comment by pawelfus** [comment]
Hi @engagex 

Thanks for reporting the issue. This is expected behaviour when [`dataGrouping`](https://api.highcharts.com/highstock/series.line.dataGrouping.enabled) is used. Columns require more space as per [`groupPixelWidth`](https://api.highcharts.com/highstock/series.line.dataGrouping.groupPixelWidth) option so you see grouped columns, while non-grouped line series. You can disable `dataGrouping` and the result will be the same: https://jsfiddle.net/BlackLabel/uxm2kw9f/11/ or set the same `groupPixelWidth` to match it with series type.
