### ISSUE TITLE
plotOptions.pie.minSize is gone/not working

### ISSUE THREAD

**Issue by totszwai** [highcharts/highcharts#9249]
#### Expected behaviour
Expected minSize on pie chart to work

#### Actual behaviour
minSize on pie chart does not work... 

#### Live demo with steps to reproduce
http://jsfiddle.net/totszwai/xr7wqpn1/

The code or variable related to minSize is completely gone??
https://github.com/highcharts/highcharts/blob/aa70c5786/js/parts/PieSeries.js#L284-#L294

**Comment by pawelfus** [comment]
Hi @totszwai 

[`minSize`](https://api.highcharts.com/highcharts/series.pie.minSize) option is available and is `80px` as docs says: 

> The minimum size for a pie in response to auto margins. The pie will try to shrink to make room for data labels in side the plot area, but only to this size.

Note this `minSize` is not about minimum size for the container, but for the pie to not decrease pie size more than 80px when dataLabels are **enabled**. Take a look: http://jsfiddle.net/BlackLabel/xr7wqpn1/11/

**Comment by totszwai** [comment]
Shouldn't be the same behavior then for when legend is there? `minSize` is not working for legends.
https://jsfiddle.net/totszwai/s57t0x93/

**Comment by pawelfus** [comment]
@totszwai legend decreases plotting area in a chart, while `minSize` limits pie chart only for dataLabels within the plotting area. `minSize` was added when we decided to decrease pie size to make some space for dataLabels - with `minSize` we could limit how small pie chart should be because of the dataLabels.
