### ISSUE TITLE
treemap render emtpy-string label wrong

### ISSUE THREAD

**Issue by xcqwan** [highcharts/highcharts#9258]
#### Actual behaviour
https://jsfiddle.net/gc3rx9fo/

#### Product version

6.2.0

**Comment by TorsteinHonsi** [comment]
_Internal note_:
Since v6.2.0 we give each point an `id` internally. This conflicts with the default data label formatter: https://github.com/highcharts/highcharts/blob/v6.2.0/js/modules/treemap.src.js#L174

@jon-a-nygaard Does it make sense at all to use the `point.id` in the datalabel? If so, we could use `point.options.id`, otherwise remove it.

**Comment by TorsteinHonsi** [comment]
#### Workaround
Set an explicit `dataLabel.format`: https://jsfiddle.net/highcharts/gc3rx9fo/1/

**Comment by jon-a-nygaard** [comment]
@TorsteinHonsi If I remember correctly, it was done as a conveniece to avoid having to set both `id` and `name`. However I believe this was a mistake, and it is probably better to just look for only `name`, especially after the recent changes.

Will submit a PR soon to correct it.
