### ISSUE TITLE
variwide drilldown to treemap error

### ISSUE THREAD

**Issue by yunhyel** [highcharts/highcharts#9267]
I want to see treemap chart after drilldown in variwide chart.
is this error related to axis? How can I fix it...?

my code is here
https://jsfiddle.net/c2dtqfn3/9/

**Comment by sebastianbochan** [comment]
Hi @rriixx,
Thank you for contacting us. This is our bug tracker so for general support questions please use forum / stackoverflow or forum.

**Comment by sebastianbochan** [comment]
Hi @rriixx,
Thank you for contacting us. This is our bug tracker so for general support questions please use forum / stackoverflow or forum.

ps. The error appears, because you refer to xAxis:1 and yAxis:1. Both option mean that you declared array for each axis and you have at least two axis for x and y (axis are indexed from 0). I fixed it here: https://jsfiddle.net/BlackLabel/v8fdLe9n/ but in this specific scenario, you shoud destroy chart and create new one with new series (treemap).
