### ISSUE TITLE
Arearange with dashStyle - Low performance after zoom

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#9276]
#### Expected behaviour
The chart should work efficiently with all dash styles.

#### Actual behaviour

http://jsfiddle.net/BlackLabel/s5k7wmop/

Try zooming few times and tooltip will work slower and slower.

#### Product version
Highcharts v6.2.0

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
The low performance is probably due to the complexity of the path itself.

#### Workaround
Set a lower [cropThreshold](https://api.highcharts.com/highcharts/plotOptions.arearange.cropThreshold) so that the browser doesn't have to render data that is outside the plot area: http://jsfiddle.net/highcharts/qhbajx4r/7/
