### ISSUE TITLE
Problem with updating series on multiple charts with the same data

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#9294]
#### Expected behaviour
Both chart should behave the same.

#### Actual behaviour
Only the first chart is updated.

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/96c5jvot/

1. Click on 'First Data' button.
2. Click on 'New Data' button.

#### Product version
Highcharts v.6.2

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
After debugging, turns out that: the same options object are being used for series update, the object is shared. Next, during second update first chart runs fine - same points length, so points are updated and series options are updated too. However, this means that options in second chart are changed too, so when second update is running in second chart old points values are taken from series options that are already updated.

Solution - do not use the same objects, because of possible unexpected behavior such as this one.

I'm not convinced that this is a bug, but I'm not convinced either that my comment is enough to close this issue.

Maybe this issue could be resolved through documentation - by adding more info?

**Comment by TorsteinHonsi** [comment]
> I'm not convinced that this is a bug

I agree. Currently the `options.data` object is mutated. The rationale is that copying it would increase memory usage on data-heavy charts, since in the majority of cases the data is not changed, and we would need two arrays in memory keeping the same data. Think thousands or tens of thousands of data points.
