### ISSUE TITLE
Points are wider than tick interval on sparse dataset

### ISSUE THREAD

**Issue by alexberazouski** [highcharts/highcharts#9295]
#### Expected behaviour
http://jsfiddle.net/7scyp3v6/6/

When the tick interval is defined, I would like the point be not wider. That's why I have to define `maxPointWidth` in pixels. This value can be different depending on the scale and dataset size. So I cannot rely on that.

#### Actual behaviour
Point's width is too big
http://jsfiddle.net/7scyp3v6/5/

#### Product version
Tested on Highstock 4.2.6 and the latest 6.2.0

**Comment by KacperMadej** [comment]
Hi @alexberazouski 

Automatically calculated point range is wrong for you data, axis type, series type. You could resolve this through manually setting the pointRange for series - demo: http://jsfiddle.net/BlackLabel/7scyp3v6/7/

Or by providing points in expected density, or at least two points next to each other - if you have no data for such points then you could use null points - demo: http://jsfiddle.net/BlackLabel/7scyp3v6/8/

This is not a bug and because we are trying to keep GitHub issues for bug tracking please use any other support channel: https://www.highcharts.com/support for technical support.

**Comment by alexberazouski** [comment]
@KacperMadej thank you! `pointRange` is really what I needed.
Closing the issue
