### ISSUE TITLE
Highmaps: Add support for null values in Legend

### ISSUE THREAD

**Issue by cscgrad** [highcharts/highcharts#9348]
#### Expected behaviour
Allow legend to display data class for null values and have legendItemClick functionality work

#### Actual behaviour
legendItemClick functionality does not work, the null value map regions are always visible

                dataClasses: [{
                    from: null,
                    to: null,
                    name: "No Data",
                    color: "000000"
                },{

#### Live demo with steps to reproduce
https://jsfiddle.net/5rwgjoch/4/

#### Product version
Highmaps 6.1.3

#### Affected browser(s)
IE, Chrome

**Comment by KacperMadej** [comment]
Hi @cscgrad 

Thank you for reporting about the problem.

Nulls are not supported for dataClasses more than it looks like from you demo. See with set color for the null data class - https://jsfiddle.net/BlackLabel/7y34ez6d/ - the color is not applied, so it looks like the points are not in the class and because of that are not controlled by data class.

Null points have nullColor used for coloring and are not included in colorAxis at all.

However, later in code we are using
```js
if (
    (from === undefined || value >= from) &&
    (to === undefined || value <= to)
) {
```

so, if you have (and in your demo this is the case) `0` in another group, then `null` will be accepted (and [here's why](https://blog.campvanilla.com/javascript-the-curious-case-of-null-0-7b131644e274)).

**Workaround**: use a wrapper in the demo and do not use `0` in any other class. Demo: https://jsfiddle.net/BlackLabel/7y34ez6d/2/

**Comment by cscgrad** [comment]
Thanks @KacperMadej, I've read the referenced JavaScript article and I do understand why its happening, but from a statistical point of view, zero and null (missing) are different. Zero implies you have the data and the value is 0. Null implies the data is missing and it could be any value. As such, it's important to make this distinction visually. 

I realize I can loop through the points and set null to -1 or some value I determine to indicate missing, but that affects performance for a large number of data points. I'll play around with the Highmaps source code you've identified above to see if I can tweak it for my use case. I'll let you know the results.

**Comment by cscgrad** [comment]
Sorry, accidentally closed the issue, re-opening...

**Comment by cscgrad** [comment]
Got it working by overriding the toColor function, adding the following conditions (along with the wrapper you provided):

                    if (
                        ((from === undefined || (value >= from))
                         && (to === undefined || (value <= to))
                         && (value !== null))
                        || (from === null && to === null && value === null)
                    ) {

Demo:
https://jsfiddle.net/1p9z70yo/

**Comment by KacperMadej** [comment]
Thank you @cscgrad for sharing your solution.
