### ISSUE TITLE
 'area' series treated as 'bar' when more than 29 series of 'area' w/ boost module

### ISSUE THREAD

**Issue by geoffreyfloyd** [highcharts/highcharts#9352]
#### Expected behaviour
Render stacked area series as an area when using more than 29 series of data

#### Actual behaviour

Rendering as thin stacked bars

#### Live demo with steps to reproduce

30 series w/ boost (y u no work?)
https://jsfiddle.net/gbL2c19h/3/

29 series w/ boost (works as expected)
https://jsfiddle.net/gbL2c19h/4/

30 series no boost (works as expected)
https://jsfiddle.net/gbL2c19h/5/ (edited)

#### Product version
HC 6.2.0

#### Affected browser(s)
Chrome 70, FF 62, and IE 11

**Comment by TorsteinHonsi** [comment]
Area series in boost are designed to render only when there is a large number of points, so we're assuming that each point doesn't need more than 1px width.

In your chart you have set the [boost.seriesThreshold](https://api.highcharts.com/highcharts/boost.seriesThreshold) to 30, that's why you see the shift here. 

This is currently a limitation of the boost module, but we are considering an enhancement to draw true filled areas. FYI @cvasseng .
