### ISSUE TITLE
Sparkline Graph Export Issue

### ISSUE THREAD

**Issue by rizwansultan88** [highcharts/highcharts#9353]
As per your'e live example that graph generated Sparkline
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/sparkline/

Now what should I do I add exporting feature
https://jsfiddle.net/ukjp76br/ 
check that fiddle link expecting output it should export complete package in single file but what exporting feature showing export against all items instead of exporting in single package or png file along with complete data.

Please correct me if anything I'm doing wrong in that fiddle link 

Thanks

**Comment by KacperMadej** [comment]
Hi @rizwansultan88 

In sparkline each column cell has a single chart in it, so you could try exporting multiple charts as explained here: https://www.highcharts.com/docs/getting-started/frequently-asked-questions#export-multiple

We are using GitHub issues for bug reports and this issue is not a bug.
You can contact us through any other support channel - e.g. e-mail:support@highcharts.com.
More info at https://www.highcharts.com/support

**Comment by rizwansultan88** [comment]
Question is that we are showing that as type of Graph on website that is Sparkline Graph so it should export in  single and it should be export complete data in single file.
By the way I already saw multi export example but I don't think that complete data export work with that feature as well.
https://www.screencast.com/t/9OO1TXu8 
By the way thanks for prompt response.

**Comment by KacperMadej** [comment]
I understand what you require, but that feature is currently not available because each cell has a single chart in it. Sparkline is just an optimized large set of charts.

Let's keep this issue open as an enhancement suggestion - to add exporting (as full table with all charts) to sparkline chart.
