### ISSUE TITLE
Bubble width isn't actually width

### ISSUE THREAD

**Issue by andymule** [highcharts/highcharts#9371]
#### Expected behaviour
If using sizeby:'width', I expect a circle's diameter to be drawn as the exact size specified by the point's z value. 

#### Actual behaviour
Currently sizes drawn are unpredictable based on a large number of hidden variables. This makes it incredibly difficult to use bubble charts to represent actual distances or any kind of linear visual comparison of data.

To prevent breaking changes, I propose a third mode 'diameter' where users can expect a bubble's z value to drawn as such on the graph. 

#### Live demo with steps to reproduce
Here's a simple demo showing how widths are never drawn to size. These circles widths should be drawn as 5, 10, and 20:
https://jsfiddle.net/arckex/fybsqtpd/

Here is a forum page talking about different aspects of this issue, with more fiddles:
https://forum.highcharts.com/highcharts-usage/accurately-sizing-bubbles-t41238/

#### Product version
Highcharts v6.2.0

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
It is important to understand that `z` is a _value_, it is not the _pixel size_ of the bubble.

As an analogy, your points have `y` values of 5 and 10, but that doesn't mean they should be drawn 5 or 10 _pixels_ from the zero plane.

In order to translate the `z` value directly to pixels, the `minSize` and `maxSize` should be set as numbers. This seems to work: https://jsfiddle.net/highcharts/2rjxo4a3/.

But since bubbles are inteded to represent `z` values rather than rendered pixels, a more flexible solution I think is to just use a scatter series with individual marker radii: http://jsfiddle.net/highcharts/h7kLjqsx/

**Comment by andymule** [comment]
It's not pixel size I think matters, but it's the distances drawn on the graph. To go off of your analogy, my `y` value IS drawn at a value of 5 on the graph, in the same way that I would assume something called a `width` to be drawn across an equal distance across the graph...

**Comment by TorsteinHonsi** [comment]
Ok, if I understand you correctly, this setup provides what you want: https://jsfiddle.net/highcharts/fybsqtpd/24/. It has  `zMin: 0` and `minSize: 0`.

Now before clicking the buttons, the two bubbles are 28px and 56px in diameter, proportional to their relative values (5 and 10).

After adding the point, the bubbles are 14px, 28px and 56px, also proportional to the updated relative values (5, 10 and 20).

**Comment by andymule** [comment]
But the bubbles never span a distance on the graph of their values, 5 and 10. 

This is how I expect something called "width" to behave, where the value of the point is the "width". 
Here is how I made it work:
https://jsfiddle.net/arckex/2gw83yus/

This is why I say it's problematic for representing any actual measurements, because it's really hard to make the values actually equal the graphing distances.

**Comment by TorsteinHonsi** [comment]
Oh, I see, you want the bubble width to match the _Y axis values_!

A slightly easier setup would be to use `zMin` and `zMax` instead of making a dummy series with those extremes.

But there is no connection between the Z scale and the Y axis (or the X axis for that matters), so this has to be manually set up.
