### ISSUE TITLE
Y axis ticks Auto display units are different for yaxis type linear and logarithmic

### ISSUE THREAD

**Issue by amruta30** [highcharts/highcharts#9401]
#### Expected behaviour
Auto display units of y axis tick labels should be the same irrespective of the axis as linear or logarithmic, since incase of Auto the display units are decided depending on the data.
Why is it so that mixed display units are applied incase of logarithmic scale only?

#### Actual behaviour
Consider a column chart is plotted where Auto display unit is applied to the Yaxis tick labels depending on the data.
Refer following JS fiddle where Auto display unit applied as "G" 
https://jsfiddle.net/amrutaJgtp/7arq3t5f/3

Now, change the type of Yaxis as "logarithmic". 
It is observed that mixed display units are applied as "G" and "M"
https://jsfiddle.net/amrutaJgtp/7arq3t5f/2

#### Product version
Observed on v6.0.6, reproduced on latest version also.

#### Affected browser(s)
All

**Comment by KacperMadej** [comment]
Hi @amruta30 

The mixed display is intentional as 0.001G will look bad, but if you feel like it would look good then you could set up label [format](format) or [formatter](https://api.highcharts.com/highcharts/xAxis.labels.formatter).

This is not a bug. For technical support please contact [Highcharts technical support](https://www.highcharts.com/support).

**Comment by amruta30** [comment]
@KacperMadej Thank you for replying!
