### ISSUE TITLE
Changing scaleX for Font Awesome icon

### ISSUE THREAD

**Issue by amocarski** [highcharts/highcharts#9402]
#### Expected behaviour
Stretch fa-minus icon using scaleX or whatever.

#### Actual behaviour
How to actually modify icon attributes. In order to change icon position I'm doing something like this:

```javascript
let svgElem = this.text(text, x, y + h)
          .attr({
            translateY: h - 6,
            translateX: -2
          })
          .css({
            fontFamily: 'FontAwesome',
            fontSize: h * 2
          });
```
Trying to do something like this doesn't change anything
`transform: scaleX(2)
`
#### Live demo with steps to reproduce
To load FA icon I'm using this method
http://jsfiddle.net/robschmuecker/yc3Tg/1/

#### Product version
Highcharts 6.1.4

**Comment by KacperMadej** [comment]
Hi @amocarski 

Thank you for contacting us.

This is our bugtracker, so for general support cases, please use stackoverflow / forum or email. https://www.highcharts.com/support

P.S.
In your demo you have used xAxis and yAxis twice for each - see yellow warnings in by the related lines in your demo. Please try to create a minimal example showing the problem when contacting support.

P.P.S.
font-size (or set through JS fontSize) should have unit - like 'px' appended. It wasn't working in Chrome due to lack of unit when I tested it. `attr` works fine for proper options - demo: http://jsfiddle.net/BlackLabel/fmjs50bp/
