### ISSUE TITLE
Boost and styled mode

### ISSUE THREAD

**Issue by Basts** [highcharts/highcharts#9407]
#### Expected behaviour

As we know, the styled mode doesn't work when boost is kicked in. But when we zoom in and reset zoom colors will stay, despite boost. 

#### Live demo with steps to reproduce

[DEMO](https://jsfiddle.net/Bastss/a93t7qv8/)

#### Product version

 Highcharts 6.2.0

#### Affected browser(s)

all

**Comment by silhouettepoms** [comment]
Original reporter (from the forum) here, thanks for reporting this! 

I made a slight modification to the fiddle, adding chart.redraw() at the end, if you uncomment that line you will see it does work if you call redraw (which is probably why zooming out works) immediately after creating the chart.

https://jsfiddle.net/39atu6qm/1/

Also note: when the chart is initially drawn all 3 series are rendered on one PNG (all in black). After calling redraw (or zooming out) they are rendered on 3 separate PNGs, each with the correct color for their series. Perhaps this is a clue to the issue.

Our team would like to know if this is intended to work and just broken or if we should not count on having the boost feature work with styled mode in the future. We require styled mode for some of our other features.

**Comment by KacperMadej** [comment]
Hi @Basts 

Thank you for reporting about the issue.

@cvasseng - boost module issue, any comment?

**Comment by cvasseng** [comment]
That it works after calling `redraw` (or zooming back into boost mode after being in SVG mode) is a happy accident - presumably styled mode will read the color values from the CSS in SVG mode, and this read value is "stuck" as the series color property which boost uses. 

Boost has not really been tested with styled mode at all, as it's one of the earlier defined limitations of the module. Hence mixing boost and styled will lead to undefined behavior. For more straight-forward configurations it looks like just redrawing as proposed by @silhouettepoms would work fine as a workaround (or short-term fix), but if getting fancy with the CSS I suspect things could break pretty easily. For that reason, styled mode is likely to remain unsupported (at least beyond basic support) even if we add support for this particular use case in the module itself.

@silhouettepoms the chart is drawn as an aggregated image initially because the chart itself enters boost (which can happen for several reasons, e.g. if `boost.seriesThreshold` is crossed, or if all series are boostable and one series crosses the `series.boostThreshold`). It's all black because boost will not read the series colors when in styled mode. When zooming out after being in SVG mode (or calling `redraw` as you've found), the SVG renderer will have mutated the series properties with e.g. colors read from the CSS, which boost will pick up on. I'm not entirely sure why it doesn't do full chart boosting after coming out of SVG mode - that part seems to be a bug, but it's not related to style mode. There does however seem to be an issue when styled mode is enabled where series rendering will be skipped in some cases. 

Also - if using a `redraw` workaround, beware of full-chart boosting as that will stop the side effect of reading the colors from CSS from happening. In other words - make sure `boost.allowForce = false` and `boost.seriesThreshold > [your series count]`.

**Comment by silhouettepoms** [comment]
Thanks, that all makes sense. I guess if we choose to use boost we just need to beware that a future update might result in the full-chart-boost being used even after redraw which would break our work-around. Since apparently that is a bug that just happens to work in our favor.

Hope sometime in the future boost with styled mode is fully supported as it has some nice features we need for other reasons.

**Comment by TorsteinHonsi** [comment]
This only fails when we're rendering multiple series in one canvas.

If we only draw one series, that series creates its own `markerGroup`, and if in styled mode, we read the computed fill for that and apply it to the line: https://jsfiddle.net/highcharts/capgvLdu/

However when we add more series, the whole chart goes into boost mode, so the series no longer have individual marker groups with class names that dictate the styles applied. Instead there is only one common canvas and marker group.

### Bug
@cvasseng I would expect that I could set `boost.seriesThreshold` very high to avoid the series to be combined into a common canvas, but that doesn't do the trick: https://jsfiddle.net/highcharts/capgvLdu/5/. However, if I resize the iframe, the colors are correctly rendered. This ambiguity can be traced back to this block: 

https://github.com/highcharts/highcharts/blob/91aed0345c950d66ae4b4905c215fb469586ed8f/js/modules/boost.src.js#L3433-L3452

On the first render, `chart.isChartSeriesBoosting()` returns `true`, which it shouldn't. Subsequently, on redraws, it returns `false`, which I expect. Then the individual markerGroups are correctly rendered with class names and all, and the colors are applied to the graphs.

**Comment by cvasseng** [comment]
@TorsteinHonsi: you need to combine a large series threshold with `boost.allowForce: false` - https://jsfiddle.net/g2qzdpL3/. `allowForce` will completely ignore the `seriesThreshold` setting (as it's a secondary chart-wide boosting strategy). It's one of those things that makes sense in the vast majority of use cases, but that has adverse effects in a few edge cases like this one.
