### ISSUE TITLE
load function of highcharts is not working as expected

### ISSUE THREAD

**Issue by swethasappati** [highcharts/highcharts#9489]
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/events-load/

http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/chart/events-redraw/

Please run above jsfiddle links, In one link LOAD function is calling after chart image is rendered, but in other, before chart image is rendered.

Could anyone please look into it.

**Comment by KacperMadej** [comment]
Hi @swethasappati 

This is our bug tracker. For technical support see - https://www.highcharts.com/support

P.S. The demos you have posted are working fine. When contacting support please explain what do you mean by "chart image", because your comment is not precise enough to understand (at least for me) what is the problem that you have.
