### ISSUE TITLE
Graph disappear when comparing (percent) and series start with 0

### ISSUE THREAD

**Issue by eolsson** [highcharts/highcharts#951]
1. Start with this example: http://jsfiddle.net/bJhgm/
2. Click the 'All' button

Result: The graph disappers. The tooltip is still there but shows NaN as percentage value.
Expected: Not sure... percent comparing with 0 will result in infinity for all other values

Note: The example have 0 in the first row but all other values are != 0

**Comment by briask** [comment]
Just because the initial values are zero should not mean a chart does not appear for the percentages that can be calculated. Also if there are multiple series on the chart but only 1 has initial values of zero, all the other series should display, currently none of the series will. See http://jsfiddle.net/briask/d6cuq90x/3/ for a simple example, Sample2 series should chart no matter what  issues Sample1 data has.

**Comment by TorsteinHonsi** [comment]
I fixed this issue by ignoring 0 values, so using the first non-null, non-zero value as the base of comparison.

**Comment by pawelfus** [comment]
I think it would be good idea to mention that in the docs.

**Comment by TorsteinHonsi** [comment]
Yes, I updated the [docs](http://api.highcharts.com/highstock#plotOptions.area.compare) too:

> Compare the values of the series against the first non-null, non-zero value in the visible range.

**Comment by abali96** [comment]
This appears to still be an issue. I'm on version 6.0.3.
![image](https://user-images.githubusercontent.com/5098093/34749160-e6b3f974-f56d-11e7-8da0-ea331f8d3a1c.png)

**Comment by KacperMadej** [comment]
@abali96 

Please post a live demo for the problem. It looks like the data set is important for recreating the problem.
