### ISSUE TITLE
Chart animation no longer working after updating data model

### ISSUE THREAD

**Issue by ramelllamar** [highcharts/highcharts#9583]
#### Expected behaviour
Chart should load w/ respected data based on chart configuration, and series data provided.

#### Actual behaviour
Chart animation/ values not loading when page loads  

#### Live demo with steps to reproduce
Here is a link to the issue the chart animation issue that we've been experiencing.
https://bw1-my.sharepoint.com:443/:v:/g/personal/ramell_lamar_bwdesigngroup_com/EerC6I_51y1KlMbER7PqsYYBTkfyxuBEs5Ci77yEbAHuEw?email=support%40highcharts.com&e=edlqCE.

#### Affected browser(s)
All browsers

**Comment by cvasseng** [comment]
Hi @ramelllamar,

I had a look at your video, and I see one thing that could explain this. It looks like in the version that's not working, the data is strings rather than numbers.

Note here how there are quotes in your data values on the right side:
![screen shot 2018-12-05 at 15 48 12](https://user-images.githubusercontent.com/1998167/49521205-35c20480-f8a5-11e8-81a4-fbe9c4e42f89.png)

Could you try converting your values to numbers either before passing the data to the frontend or by calling `parseFloat` when transforming the data on the frontend and see if that helps?

**Comment by ramelllamar** [comment]
That was the issue. After I updated the chart values to integers, the charts started working as expected. Thanks so much!!

**Comment by cvasseng** [comment]
No problem! Happy to hear that you got it working! :)
