### ISSUE TITLE
wrong range when i use rangeselector

### ISSUE THREAD

**Issue by huanglijun19** [highcharts/highcharts#9595]
#### Expected behaviour
1.when i use rangeselector show right range 
for example when i select "3M" the right range is 2018.9.3 to 2018.12.3  I want the chart draw data from 2018.9.3 to 2018.11.3

2.the start point is the origin
for example when i select "3M" the right range is 2018.9.3 to 2018.12.3  I want the chart start from origin
#### Actual behaviour
1.when i use rangeSelector, the rangeSelector show the range should be  2018.9.3 to 2018.12.3,but the chart show 2018.9.4to 2018.12.3,usually it will be one day later
2.the first data need to show on the origin,but the data just very close to the origin
![image](https://user-images.githubusercontent.com/42329917/49452847-e637f600-f81c-11e8-9550-33c1885f1a98.png)

#### Live demo with steps to reproduce
http://jsfiddle.net/cp5m2df9/

**Comment by pawelfus** [comment]
Hi @huanglijun19 

Thank you for reporting issues. This is expected behaviour. Let me explain with this demo (the same as yours, but `xAxis.ordinal` is set to false): http://jsfiddle.net/BlackLabel/x67o9bd4/

- First issue:

![screen shot 2018-12-05 at 12 46 27](https://user-images.githubusercontent.com/1453926/49511570-cdb2f480-f88b-11e8-9cf3-4be927c02e83.png)

As you can see, there is some space on the left side of hovered point which means current range start at 04.09.2018 but can start for example at 04.09.2018 15.30:

>  `> new Date(Highcharts.charts[0].xAxis[0].getExtremes().min)`
> `< Tue Sep 04 2018 15:30:00 GMT+0200 (Central European Summer Time)`

And default rangeSelector displays only date, without time.

- Second issue:
This is configurable through [`series.compareStart`](https://api.highcharts.com/highstock/series.line.compareStart) option.
