### ISSUE TITLE
BUG: Adding a series dynamically and changing the top/heigth offset goes to the zoom "chart" instead.

### ISSUE THREAD

**Issue by merakmarey** [highcharts/highcharts#9607]
#### Expected behaviour
Adding a series dynamically and offsetting the top should show 2 separated series plus the navigator zooming control. The expected result should show something similar to 

http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/candlestick-and-volume/

#### Actual behaviour
Adding a series dynamically and offsetting the top goes to the zoom "chart" instead 

#### Live demo with steps to reproduce
https://jsfiddle.net/190nw74e/

#### Product version
Highstock JS v6.2.0 (2018-10-17)

#### Affected browser(s)
Chrome, Android, iOS

**Comment by pawelfus** [comment]
Hi @merakmarey 

Thank you for reporting this issue. Actually we have two minor issues here:

- wrong order of adding series and updating chart: if you add a series to `yAxis: 1`, then you actually add this series to.. navigator. When creating Stock chart (with navigator) under the hood we create these additional axes (xAxis and yAxis). The same happens when you create a chart without `yAxis: [{ ... }]` -> we create a yAxis for you
- when you call chart.update with `yAxis: [{}, {}]` you actually update first yAxis and navigator yAxis. Instead you should place more yAxes. Simply create one more yAxis: https://jsfiddle.net/BlackLabel/0pmLjs13/

Extra note: `chart.update()` by default **does not add series/points/axes** unless `oneToOne` is not set: https://api.highcharts.com/class-reference/Highcharts.Chart#update 

PS: x-values should be **numbers** not strings (see my demo above).

**Comment by merakmarey** [comment]
Hi @pawelfus 

Thank you for the prompt response. However, this is not precisely a solution, at least for me. See, the situation is that the second series is added by demand, so I cannot set offsets/heights before hand because I do not know if the user will request the second series. So, if I do follow your logic I will end up with half of the chart area just empy.

The desired effect is to have a normal full chart, with navigator, and with a click, add a second series to the main chart.

Is this possible?

Thanks

**Comment by merakmarey** [comment]
@pawelfus 
Question from the top of my mind..
Is there any way to just delete all series and re-create them dynamically?
If so, then I could just get the data from the primary series, delete all, and then set the axis and follow the steps of your solution..

Thanks

**Comment by pawelfus** [comment]
Hi @merakmarey 

I understand. You should simply call `chart.update()` when you want to add a second series. See: https://jsfiddle.net/BlackLabel/0pmLjs13/5/

**Comment by merakmarey** [comment]
@pawelfus  Superb! Thanks!
