### ISSUE TITLE
(Case 61474)Performance issue with chart.redraw() method in IE browser

### ISSUE THREAD

**Issue by yuyamash** [highcharts/highcharts#9639]
#### Expected behaviour
chart.redraw() method should take < 0.5 seconds to complete rendering in IE browser.
If chart object is reinitialized or chart.destroy() method is called then it should take < 0.3 seconds to complete.

#### Actual behaviour
chart.redraw() method takes > 1.2 seconds to complete rendering in IE browser.
If chart object is reinitialized or chart.destroy() method is called then it takes > 1.3 seconds to complete.

#### Live demo with steps to reproduce
https://jsfiddle.net/mxdhzpso/71/

Scenrario: 4 charts are being drawn in one page. 
These charts can have data up to 40,000 points in each scatter chart. It is divided in 4 different series in example code.
There are 3 polygon series also drawn over charts.
We are also using the boost module to improve performance.
In the example, all the libraries which we are using are used.

#### Product version
 - Highchart version 6.0.7

#### Affected browser(s)
Internet Browser

**Comment by sebastianbochan** [comment]
Hi @yuyamash,
Thank you for reporting. I tested it and the problem with boost appears.

**Internal note**
What is interesting, when we refresh website a 4/5 times, the browser crashes.

Browser:
IE: 11.407.17134.0
Win10

@cvasseng

**Comment by cvasseng** [comment]
It's hard to pinpoint what the issue here actual is. I'm getting performance of ~120ms in IE11 and ~60ms in Firefox according to the debug timing outputs (jsfiddle with timings enabled here: https://jsfiddle.net/r68tofx3/). 

However, most of the time in IE11 is lost to series processing (ie. data transforms), which can be explained by IE11 being significantlly less performant in general. The actual rendering and buffer copy is ~40ms in IE vs. ~35ms in FF here. I am getting a significant lag in IE11 apart from the additional setup time though, but it doesn't seem to stem from the boost module. The KD building is much slower in IE, but that's async and doesn't freeze up the UI thread while it's processing

It would be interesting to see what numbers you're getting in the console when using this: https://jsfiddle.net/r68tofx3/

**Comment by yuyamash** [comment]
Hi Team,

Thank you for analyzing.

Below are updates from our side:
--------------
>>At this point I'm honestly not sure if this is just a case of IE being less performant in general, or an actual issue. 
>>Did this start happening for you recently?

We are facing the same performance from long time (from Version: 5 we observed this problem. Before versions not checked). 
Presently we are using Version 6.0.7. And in this version also same problem exist.
--------------

--------------
>> It would be interesting to see what numbers you're getting in the console when using this: 
>> https://jsfiddle.net/r68tofx3/
We are getting almost same performance numbers in our original post written on 2018/Dec/11
chart.redraw() method still takes > 1.2 seconds.
---------------

As per our observations:
- IE11 has less performance in general compared to other browsers but in this case it is giving very poor performance. 
- Chrome is taking around 1.6 seconds and IE11 is taking more than 10 seconds for loading all 4 charts shared in the original post demo. 

So can you please check, why is there this much big performance issue?

**Comment by cvasseng** [comment]
From the profiling I've done, IE11 has (comparatively) poor performance across the board rather than being limited to a handful of specific constructs. The issue seems to be in the processing step, which is fairly optimized for performance already, and I can't identify any single place that would result in a significant speed increase for IE11.

The WebGL implementation in it is also generally behind the one in FF, Edge, and Chrome, but it's not significant enough that further optimization would make much difference.

This makes it quite difficult to optimize specifically for performance increases in IE11. 

I'd still be interested in seeing a copy/paste from the dev console output in the fiddle I posted (https://jsfiddle.net/r68tofx3/), as it outputs complete timing information for different stages of rendering.
