### ISSUE TITLE
High CPU utilization on Chrome 71

### ISSUE THREAD

**Issue by mlehmann-sys** [highcharts/highcharts#9645]
#### Expected behaviour
You should be able to add points by looping through an array without the CPU utilization going through the roof on Chrome 71.

#### Actual behaviour
When you update from Chrome 70 to 71, addPoint seems to break.  There is something in that method that is causing the page to halt and CPU use to skyrocket.  
Does not happen on Chrome 70 but does on 71.

#### Live demo with steps to reproduce

http://jsfiddle.net/6xkfvbnt/3/
Clock "Add Points" and watch your Chrome task manager.

#### Product version

Highstock v7.0.0
https://code.highcharts.com/stock/highstock.js

#### Affected browser(s)
Chrome 71

**Comment by pawelfus** [comment]
Hi @lehmannsystems 

Thank you for reporting the issue. You are right it looks like issue with Chrome, we will debug and see if we can workaround/solve this internally.

**Workaround:**
I suggest to use `setData()` instead of `addPoint()`, demo: http://jsfiddle.net/BlackLabel/5daq7ork/

Additionally, it's recommended to use `boost.js` module when dealing with huge number of points, demo: http://jsfiddle.net/BlackLabel/5daq7ork/2/

**Comment by lehmannsystems** [comment]
Awesome, thanks @pawelfus !  I am using boost on my app but noticed it did the same without it so I didn't put it in the jsfiddle to simplify things.  
I am using addPoint because the data is returned in chunks from the backend and was having a hard time using setData to add data as chunks are returned.  
The workaround I am doing is just building an array as the chunks come through and then using setData once all chunks have been returned and it is time to display the chart.

**Comment by pawelfus** [comment]
Thanks @lehmannsystems  for the details! `setData()` is much simply faster than adding point one-by-one. During tests I realized you have 600k of points there (!). That's a really huge number of points. Using only 30k of points, I have checked what happens exactly in `addPoint()` and (if I'm correct) it's caused by native methods (e.g. `Array.splice()`, `Array.slice()`) which we must call anyway, because somehow we need to place each new point in the existing dataset. When you use `setData()` we don't need to make these calls for every point..

Redraw itself takes less than 300ms which is fine.

I'm going to compare demos and results between Chrome v70 and v71 now

**Comment by lehmannsystems** [comment]
OK so maybe I am doing it better now anyway using setData @pawelfus .  Some of my charts will have millions of points to plot.  It was very interesting that the slowness only started after the upgrade to Chrome 71.

**Comment by pawelfus** [comment]
*Internal note:*
Comparison of v70 and v71 in CPU profiles:

- v70 (bottom orange blocks = garbage collector) - 300ms (63ms of GC, 8% of time):
![screen shot 2018-12-12 at 15 36 14](https://user-images.githubusercontent.com/1453926/49876565-ef7c2080-fe23-11e8-9671-b7172580b142.png)

- v71 (bottom grey blocks = garbage collector) - 3000ms (800ms of GC, 20% of time (!) ):
![screen shot 2018-12-12 at 15 36 53](https://user-images.githubusercontent.com/1453926/49876564-ef7c2080-fe23-11e8-8d79-bccd409f0fca.png)

Need to create a standalone demo and compare results.

**Comment by pawelfus** [comment]
Standalone, not related to Highcharts, demo: http://jsfiddle.net/BlackLabel/2w7ujsp4/ Results:
- v70: ~100ms
- v71: ~1500ms

Snippet (does nothing actually, just a showcase):
```
document.getElementById('button').addEventListener('click', function() {
  var data = [];
  
  console.time('xxx');
  for (var i = 0; i < 30000; i ++) {
    Array.prototype.splice.call(data, 0, 0, 0);
  }
  console.timeEnd('xxx');
});
```

I don't think we can workaround this issue - rather something is broken in Chrome v71..

**Comment by lehmannsystems** [comment]
Interesting... so something is leaking in Chrome when using Array splice.

**Comment by pawelfus** [comment]
Reported: https://bugs.chromium.org/p/chromium/issues/detail?id=914395&can=2&q=splice&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by KacperMadej** [comment]
Chrome v71.0.3578.98 - the issue is still visible
