### ISSUE TITLE
Custom world map not working in Highcharts 6.2 with RequireJS

### ISSUE THREAD

**Issue by cmkshaw** [highcharts/highcharts#9657]
#### Expected behaviour

When using highcharts + requireJS, map should render as shown here with highcharts v5
http://jsfiddle.net/8g2onp47/

#### Actual behaviour

When using highcharts + requireJS, error thrown 
`Uncaught ReferenceError: Highcharts is not defined
    at world.js:1`

#### Live demo with steps to reproduce
http://jsfiddle.net/82pdbt3j/

#### Product version
Highcharts JS v6.2.0 (2018-10-17)
 Highmaps JS v6.2.0 (2018-10-17)

#### Affected browser(s)
Chrome 70

#### Fix

I was able to fix this in my project by turning the world.js file into a module for requireJS, following clues from requirejs/highcharts info [here](https://github.com/highcharts/highcharts#load-highcharts-as-an-amd-module). 
Maybe some documentation would be helpful here for the maps specifically?

**Comment by sebastianbochan** [comment]
Hi @cmkshaw,
Thank you for the suggestion. It is great idea to add it to our docs.

@mekhatria What do you think?

**Comment by jon-a-nygaard** [comment]
Yes, I believe this is a good idea to improve our docs with an example of loading the map-collection with requireJS.

I also believe this issue should be solved by adding a UMD pattern to our JS files in the map-collection. This has been in discussion for a little while, and I have submitted an issue at the map-collection repository to keep track of it: https://github.com/highcharts/map-collection-dist/issues/29

**Comment by vincentwinkel** [comment]
Highcharts/highmaps is great but working with it using requirejs is a nightmare. v6.12+/v7 don't work, we need to fallback to v6.11, then adding a module is pretty impossible.
I'm stuck since 4days trying to use highcharts + highmaps + custom world map.
So yeah, please add some docs about requirejs. Your jsfiddle demos never use requirejs.

**Comment by oysteinmoseng** [comment]
@vincentwinkel We do not yet support AMD with the map collection, so for now we recommend loading the `geo.json` versions of our maps when using RequireJS with Highmaps.

Example of using AMD with modules: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/amd/simple/

Example of using GeoJSON as map input: https://www.highcharts.com/maps/demo/geojson

If you still encounter issues, don't hesitate to get in touch with our [support team](https://www.highcharts.com/blog/support/).

**Comment by vincentwinkel** [comment]
Thanks @oysteinmoseng but once again, your requirejs example is without Highmaps and the Highmaps example is without requirejs and jquery.
I do use Highcharts with requirejs, but it seems impossible to add Highmaps itself. About `world/custom` I already got the json that I call on my own.

Based on this context, it would be awesome to have an accurante example using Highcharts + Highmaps + jquery: https://jsfiddle.net/pvfqyjx6/1/

By "accurate example" I mean a snippet doing exactly its job, not some incomplete pieces of code and random links from around the web like I find since 4days.

**Comment by oysteinmoseng** [comment]
@vincentwinkel As it turns out, this goes a bit deeper than a documentation issue. Because there is a discrepancy between the file structure for our node packages and our CDN, there is a potential conflict with the module paths. The maps module is registered under `highcharts/modules/map`, but on our CDN the file path is `code.highcharts.com/maps/modules/map`. We will look into this.

For now, you can work around it by pointing the highcharts package to `code.highcharts.com/maps`. That will also let you load the map module the way you tried it: https://jsfiddle.net/1bzfgkux/ 

Apologies for the long winded road to get to this point. Let us know if you have any further issues.

**Comment by vincentwinkel** [comment]
Thank you @oysteinmoseng . It works well with the URLs, it doesnt work with my local files (maybe I mix the files up, maybe as you said the file structure is not correct).
Also, it works with the Germany map (using geojson), but the Europe one returns a 504, and my local file doesn't seem working neither.
I'll try to post my final config when everything will work (I see I'm clearly not the only one trying to do that), but if you have any clue about the world map, it would be great.

**Comment by oysteinmoseng** [comment]
@vincentwinkel Great to hear that you got it to work. With the right configuration you should still be able to use local files, however.  Feel free to get in touch with our support team to get the details of your particular setup figured out.

**Comment by jon-a-nygaard** [comment]
> it doesnt work with my local files (maybe I mix the files up, maybe as you said the file structure is not correct)

@vincentwinkel Would just like to mention that looking at https://github.com/highcharts/highcharts-dist may be of help, as it has the same file structure as our AMD dependencies expects.
