### ISSUE TITLE
Highstock - wrong yAxis position after chart update

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#9671]
#### Expected behaviour
The chart should look like before the first update.

#### Actual behaviour
The second yAxis is placed incorrectly.

#### Live demo with steps to reproduce

1. Open jsfiddle: http://jsfiddle.net/BlackLabel/hkbrLmqx/
2. Wait 2 seconds

#### Product version
Highcharts 7.0.0

#### Affected browser(s)
All

**Comment by sebastianbochan** [comment]
Hi @ppotaczek,
The issue is caused by indexing and length of yAxis array. 

Let me explain why:
**Scenarios**
1. 
yAxis 0 and 1 -> data
yAxis 2 -> navigator

2.
yAxis 0 -> data
yAxis 1 -> navigator

now indexes are different

3. 
yAxis 0 -> data
yAxis 1-> navigator

As a workaround you can add extra axis.

**Internal note:**
Extra axis should be added, instead of upgrading navigator axis.

**Comment by pawelfus** [comment]
Additional demo: https://stackblitz.com/edit/react-op9awl

A bit different scenario, but it's the same issue: yAxis from navigator is taken into account when updating chart and takes options from userOptions. 

*Internal note:*
Maybe before `update()` we should filter internal instances (series, yAxis, xAxis)? Those options in general have a separate config (e.g. `series.navigatorOptions` or `navigator.xAxis/yAxis`) so we don't need to update them from `series/xAxis/yAxis` arrays.

**Comment by sebastianbochan** [comment]
Unstale
