### ISSUE TITLE
Can't select any point to update when data exceedes a certain range

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [highcharts/highcharts#9675]
Hi, 

it's been since yesterday and I can't find this in your documentation.

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/intraday-candlestick/

console.log(chart.series[0].data); < empty array. can't select a point to update data.
Can't select a point to do .update() 

I need this especially to draw on top of a point: 

 function (chart) {

    var point = chart.series[0].data[8], <<<<<<< THIS POINT DOESNT EXIST so i cant render on it.
        text = chart.renderer.text(
            'Max',
            point.plotX + chart.plotLeft + 10,
            point.plotY + chart.plotTop - 10
        ).attr({
            zIndex: 5
        }).add(),
        box = text.getBBox();

    chart.renderer.rect(box.x - 5, box.y - 5, box.width + 10, box.height + 10, 5)
        .attr({
            fill: '#FFFFEF',
            stroke: 'gray',
            'stroke-width': 1,
            zIndex: 4
        })
        .add();
});

**Comment by KacperMadej** [comment]
Hi, thanks for contacting us! You've posted to our issue tracker. For general tech support, please see www.highcharts.com/support.

P.S.
This is caused by dataGrouping and is working as expected.
Please docs and comments for more info:
- https://api.highcharts.com/class-reference/Highcharts.Series
- https://api.highcharts.com/class-reference/Highcharts.Series#data

You could add an id to the point and then find it using [chart.get](https://api.highcharts.com/class-reference/Highcharts.Chart#get) to update it.
