### ISSUE TITLE
Tap on the chart opens keyboard on mobile devices

### ISSUE THREAD

**Issue by karpovn** [highcharts/highcharts#9696]
#### Expected behaviour
The keyboard doesn't open by tapping on the chart

#### Actual behaviour
The keyboard opens if you tap on the chart right after the page is loaded. If you tap somewhere else then all the next taps on the chart won't open the keyboard. 

#### Live demo with steps to reproduce
[Codepen demo](https://codepen.io/nkarpov/pen/jXroaX)

1. Open the demo on the smartphone
2. Tap on the chart
3. See the keyboard is visible

#### Product version
Highcharts JS v7.0.0 (2018-12-11)

#### Affected browser(s)
Safari 12, Chrome 71

**Comment by sebastianbochan** [comment]
Hi @karpovn,
Thank you for reporting. When I run the demo in my iOS (iphone 6s), I am not able to replicate it.
Could you supply me details about your device and OS (including full number of version) ?

**Comment by karpovn** [comment]
Hi @sebastianbochan,
Thank you for the reply.
My device is Samsung Galaxy S7 with Android 6.0
I also tested it on iPhone X and Galaxy S9 in [Browserstack](https://www.browserstack.com/)
Regarding iOS - I could reproduce it by double tapping on the chart.

**Comment by sebastianbochan** [comment]
Hi @karpovn,
Thank you for the feedback. I tested the demo also on different devices and it turned out that the problem is related with codepen, not with Highcharts. 

When I run the same demo in jsfiddle service here: https://jsfiddle.net/BlackLabel/b8L549dq/1/ all works properly. Could you test and confirm ?

**Comment by karpovn** [comment]
Hi @sebastianbochan
I'm not sure this problem is related to codepen since I have the same issue on the project I'm currently working on.

As for the jsfiddle demo, this bug is not reproducible for me there. I guess I can't replicate it since the chart is not in the viewport right after the document is loaded. I have to scroll to it and only then I am able to click on it.

It might sound weird, but the keyboard opens only when you click on the chart right after the page is loaded. Any other action (scroll, click on another element) performed before the clicking on the chart will prevent keyboard opening.

**Comment by KacperMadej** [comment]
@karpovn 
How about here? https://jsfiddle.net/BlackLabel/b8L549dq/1/show
Are you clicking the chart during initial animation or after it to recreate the problem?

**Comment by karpovn** [comment]
@KacperMadej thanks for the fullscreen demo. The issue is not reproducible there for me. So it's getting weirder.

As for your question: I can reproduce this problem on the codepen and my project by clicking the chart after initial animation.

**Comment by sebastianbochan** [comment]
Hi @karpovn,
Are you able to simplify your project and send us to support ? Maybe we it will allow us to find a reason of problem.

**Comment by KacperMadej** [comment]
I can recreate the problem in the original codepen demo (Android 7/Chrome), but it seems to be caused by the editor, because the problem is not visible in full view demo: https://codepen.io/nkarpov/full/jXroaX

In the original demo (https://codepen.io/nkarpov/pen/jXroaX) you could click in top section first, so keyboard will open. Next close the keyboard and click on the chart. Keyboard will reopen and you will be able to edit the top part of the demo - the part with code. This looks like a problem with codepen.

**Comment by KacperMadej** [comment]
Thank you for the demo. It's caused by not loosing focus. Demo in JSFiddle: https://jsfiddle.net/BlackLabel/pmbfnv79/
