### ISSUE TITLE
high chart (Bar) issue with snapping

### ISSUE THREAD

**Issue by vkadri** [highcharts/highcharts#9699]
1. Open the attached html file  

Expected behavior: The bar should snap to line 10 (exactly at 10) and no gap should be seen. 

Actual behavior : little gap is noticed between the bar and line 10. That is bar doesn't snap to line 10 completely. (Please note that this issue is only noticed on line 10 and if you drag the bar on other lines, then we don't see this issue) 

**Note:** that in the stand alone page you are not able to drag the points (since this is functionality added by TestNav and doesn't affect the main issue).

#### 
[charts_issue.zip](https://github.com/highcharts/highcharts/files/2687731/charts_issue.zip)

**Comment by sebastianbochan** [comment]
Hi @vkadri,
Thank you for reporting. The problem is related with calculating edges, which by default, are rounded to its nearest pixel in order to render sharp on screen. 

**Workaround**
Set the `borderWidth` as 1 and declare a color of series.

Demo:
- https://jsfiddle.net/BlackLabel/5pb960vu/ 

**Internal note**
The crisp option does not solve the problem and when we increase the size of `gridLineWidth` the problem is more visible.

Simplified demo:
- https://jsfiddle.net/BlackLabel/8zrpa92m/
