### ISSUE TITLE
Highcharts.chart('container', config) mutate `config` parameter

### ISSUE THREAD

**Issue by monopieces** [highcharts/highcharts#9732]
#### Expected behaviour
Should not mutate `config`

#### Actual behaviour
- Toggle checkbox, change chart to percentage, yAxis value change to percentage
- Toggle checkbox again, change chart back to normal,  yAxis value still remain percentage

#### Live demo with steps to reproduce
https://jsfiddle.net/pieces/o74n9pmh/53/

#### Product version
7.0.1

**Comment by TorsteinHonsi** [comment]
Highcharts dynamic operations mutate the data options array deliberately, see related issues like #5807. We do this in order to save memory and CPU usage, which becomes more critical when dealing with thousands or even hundreds of thousands of points.

This means your program should be designed a bit different, see for example https://jsfiddle.net/highcharts/o74n9pmh/59/.

I'll add notes about this in appropriate places in the docs.
