### ISSUE TITLE
ohlc / candlestick groupAll + zoom doesnt calculate correctly

### ISSUE THREAD

**Issue by SloUrby** [highcharts/highcharts#9738]
#### Expected behaviour
When zoomed and moving left/right chart should include all points in grouping and data shouldnt change once grouped. When moving left / right points shouldnt change at all.

#### Actual behaviour
When moving every point is changing its values. Also xAxis date and actual points are not aligned once zoomed in and moving to far right. 

#### Live demo with steps to reproduce
groupAll: true (all points in zoomed area are changing)
http://jsfiddle.net/79jdzhtw/

groupAll: false (only first and last points in zoomed area are changing)
http://jsfiddle.net/79jdzhtw/4/

Also i tested with both ohlc and candlestick types and same problem. With other types it works as expected.

#### Product version
Highstock 7.0.1 (>=6.1.0)

#### Affected browser(s)
Chrome 71.0.3578.98 (Official Build) (64-bit)

**Comment by KacperMadej** [comment]
Hi @SloUrby 

Thank you for reporting about the problem.

**Comment by pawelfus** [comment]
**Workaround:**
Instead of `series.groupAll` use `series.getExtremesFromAll`: http://jsfiddle.net/BlackLabel/5g42u8th/

*Internal note:*
It looks like cropping data causes this. Need to verify if correct points are grouped.

**Comment by 3Ue** [comment]
The option `series.getExtremesFromAll` is not always possible to use, because it also changes the axis extremes. With a small change in the following line the groupAll option seems to work fine:

https://github.com/highcharts/highcharts/blob/master/js/parts/DataGrouping.js#L222

Instead of 
`var index = series.cropStart + i`

use
`var index = series.options.dataGrouping.groupAll ? i : series.cropStart + i`

However not sure if that´s the correct solution.
