### ISSUE TITLE
When I use the boost module and allowForce is true, there is a connection in the middle.

### ISSUE THREAD

**Issue by 52flutter** [highcharts/highcharts#9757]
When I use the boost module and allowForce is true, there is a connection in the middle.
#### Expected behaviour

No connection in the middle
#### Live demo with steps to reproduce

![image](https://user-images.githubusercontent.com/11569655/50464344-41e44200-09cb-11e9-8b94-75db6a22bd9c.png)

**Comment by KacperMadej** [comment]
Hi @YinRenjie1993 

This is probably limitation of boost module, but to be sure we need to check a live demo or at very least chart's configuration and recreate the problem.

**Comment by YinRenjie1993** [comment]
Hi, @KacperMadej This is a demo;[https://jsfiddle.net/yinrenjie/trgp9x78/](url)
![image](https://user-images.githubusercontent.com/11569655/50481930-2dca3000-0a1f-11e9-93f6-a070e56b01a0.png)

**Comment by pawelfus** [comment]
Hi @YinRenjie1993 

I don't see a connection between series in your second screenshot, neither in the jsfiddle demo. Are you sure it's the same demo as in your first screenshot? In your first screenshot it looks like you use only one series (the same color), but in jsfiddle - multiple series (different colors). If that's the case, then it's expected behaviour.

**Comment by pawelfus** [comment]
Hi @YinRenjie1993 

Thanks for pointing this out! We will take a look after this holidays.

@cvasseng FYI - issue looks familiar to the other one, I thought it was fixed, could you check this?

**Comment by cvasseng** [comment]
It looks to be related to floating point precision. 

It works when using CPU translations (i.e. setting `boost.useGPUTranslations = false`), so that would be a good workaround while we investigate further (https://jsfiddle.net/2Lyco1t9/). 

However, if it turns out that it is related to floating point precision, we can't do much about it due to limitations in WebGL 1.0. We will look into utilizing a newer version which may make this possible/easier to fix properly once it's more broadly supported.
