### ISSUE TITLE
updating data label not working (line chart)

### ISSUE THREAD

**Issue by fridlinimrod** [highcharts/highcharts#9771]
#### Expected behaviour
when dynamically updating a point's data label like this:

`series.data[series.data.length-1].update({dataLabels: [{enabled: false}]} );`
I expect the chart to update constantly with new points and be able to move the navigator normally and without errors in the console

#### Actual behaviour
points are added, but I can see (multiple) "Uncaught TypeError: dataLabel.attr is not a function" in the console, and when moving the navigator - it malfunctioning (not recognizing mouse up)

#### Live demo with steps to reproduce

the original Highcharts example:
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/dynamic-update/

my tiny addition is in line 15-16:
https://jsfiddle.net/JimmyBoy/qgeynv6L/1/

#### Product version

highstock 7.0.0 (in the fiddle using latest from github)

#### Affected browser(s)
only tried on chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by sebastianbochan** [comment]
Hi @fridlinimrod,
Thank you for contacting us. The problem is not a bug, but related with two issues:
-  `dataLabels` is object type instaed of array. So you should use `series.data[series.data.length-1].update({dataLabels: {enabled: false}} );` instead of `series.data[series.data.length-1].update({dataLabels: [{enabled: false}]} );` 
- The `series.update()` and `addPoint` call the animation / redraw and at the same time. The solution is disable redraw in the `series.update()` and run only one redraw.

Fixed demo:
- https://jsfiddle.net/BlackLabel/pk4gL569/

**Comment by fridlinimrod** [comment]
Hi @sebastianbochan ,
in the official documentation - `Since v6.2.0, multiple data labels can be applied to each single point by defining them as an array of configs. ` [https://api.highcharts.com/highstock/series.line.dataLabels](url)

anyways, even if I change my calls to use object and not array, and diusableing the animation / redraw for the first call - it still happens.

I took your example and removed the H.wrap part and it is reproduced.
I will appreciate if you reconsider closing it as "not a bug" :)

here is your fiddle without the wrap part:

`https://jsfiddle.net/JimmyBoy/nbyhk451/`

**Comment by fridlinimrod** [comment]
one more thing,
in your fiddle, **with the wrap part**  - try to play with navigator and you will see many console errors.
something is wrong there :-/

**Comment by sebastianbochan** [comment]
Hi @fridlinimrod,
Thank you for the feedback. You are absolutely right. Lets consider my wrap only as workaround. The reason of errors (in the console) is `forEach` on connectors. When I replaced with the `objectEach` it works. 

**Demo:**
- https://jsfiddle.net/BlackLabel/6y19jgts/

Please be aware that its only workaround.

**Comment by pawelfus** [comment]
Actually it's a duplicate of #9770. Marking the issue then.

**Comment by fridlinimrod** [comment]
Thanks @sebastianbochan,
just to let you know, then when you try to move with the navigator - you will still see errors and things will stop working.
however, since this issue as marked as duplicated - I think we no longer need to worry about this one.
Thanks for taking another look and commenting.
not taken as granted.

**Comment by KacperMadej** [comment]
This was a duplicate, but the original case was resolved only for grouped points.
It should be cleaner to reopen this issue.

Short summary:
Point update for dataLabels creates new labels and old ones are not cleared due to name collision on point - dataLabels as an option is not the same as the dataLabels array in point that stores references to all dataLabels created for the point.
