### ISSUE TITLE
Exporting not using correct colors

### ISSUE THREAD

**Issue by alons1** [highcharts/highcharts#9780]
#### Expected behaviour
Chart is exported with correct colors when using className attribute

#### Actual behaviour
Chart is exported with default colors

#### Live demo with steps to reproduce
https://jsfiddle.net/sectioni/tcmbjfur/1/

#### Product version
Highcharts 7.0.1

**Comment by sebastianbochan** [comment]
Hi @alons1,
Thank you for reporting. In the case when you apply colors by css styles, you should use the Highcharts Styled mode.

Demo:
- https://jsfiddle.net/BlackLabel/8z79gmbu/

@TorsteinHonsi should we consider it as a bug?

**Comment by alons1** [comment]
@sebastianbochan 

You are using a version 6.2.0 in your demo.
I was using 7.0.1. Your @import makes no difference there..

**Comment by pawelfus** [comment]
@alons1, @sebastianbochan 

Since v7, to enable `styledMode`, we need to set [`chart.styledMode`]() to true. Then set CSS is used in exporting too. Since v7, styled mode is part of the official `highcharts.js`, no more confusion with `js/highcharts.js`.

Demo: https://jsfiddle.net/BlackLabel/8z79gmbu/28/
