### ISSUE TITLE
Highstock x-axis datetime display bug

### ISSUE THREAD

**Issue by csigmanek** [highcharts/highcharts#9785]
#### Expected behaviour
When chosing a fixed zoom, x-axis should always look similar

#### Actual behaviour
when scrolling to the very left or right the chart seems broken as it trys to put everything in one place

#### Live demo with steps to reproduce
https://jsfiddle.net/m1uaLtdn/2/

Try to zoom using the navigator. This way you get a fixed zoom area. Move through the values and observe. Everything looks great except for the very beginning and the very ending.

![grafik](https://user-images.githubusercontent.com/25263374/50638961-dfa5b700-0f5f-11e9-8ab4-e3bb474ff4e7.png)
![grafik](https://user-images.githubusercontent.com/25263374/50638971-ea604c00-0f5f-11e9-9874-f7d25dd26b3e.png)
![grafik](https://user-images.githubusercontent.com/25263374/50639004-0663ed80-0f60-11e9-8404-046fcba5d6f4.png)

This also happens when having less values in series than its range. Combined with multiple series, you see Very big bars and the screwed x-axis legend. I. e. you cannot determine to what date two bars point, even if they have the same x value.

I could not reproduce it with small x values (< 100 000)

#### Product version
latest (7.01)

#### Affected browser(s)
All, jsfiddle created in FF

**Comment by KacperMadej** [comment]
Hi @csigmanek 

This is due to almost lack of data in that range - Highstock cannot guess right pointRange, so it should be set for series to prevent issues like that. Demo: https://jsfiddle.net/BlackLabel/3srbz4p8/
This will also eliminate the problem with random column widths.

Alternative solution is to force dataGrouping - demo: https://jsfiddle.net/BlackLabel/3srbz4p8/1/
This resolved the problem because dataGrouping creates null points for groups that lack points and pointRange is calculated based on grouped data.

**Comment by csigmanek** [comment]
Thank you. I did not know about pointRange. Great help!
