### ISSUE TITLE
[Remove all space] How to remove all space of  area chart

### ISSUE THREAD

**Issue by henrytom1703** [highcharts/highcharts#9790]
Hello, I want remove all space of area char. How to do it?
#### Expected behaviour
![selection_011](https://user-images.githubusercontent.com/38415727/50647896-61bbcd00-0fac-11e9-87b9-9f00f55ae368.png)

Config used
```
export default {
  name: "CardInfo",
  data() {
    return {
      options: {
        chart: {
          spacingTop: 0,
          spacingRight: 0,
          spacingBottom: 0,
          spacingLeft: 0,
          plotBorderWidth: 0,
          margin: [0, 0, 0, 0]
        },
        xAxis: {
          lineWidth: 0,
          visible: false,
          startOnTick: false,
          endOnTick: false,
          minPadding: 0,
          maxPadding: 0
        },
        yAxis: {
          lineWidth: 0,
          visible: false,
          startOnTick: false,
          endOnTick: false
        },
        title: {
          margin: 0,
          text: null
        },
        credits: {
          enabled: false
        },
        exporting: {
          enabled: false
        },
        legend: {
          enabled: false,
          itemDistance: 0,
          reversed: true
        },
        chart: {
          type: "area"
        },
        tooltip: {
          enabled: false
        },
        series: [
          {
            name: "USSR/Russia",
            data: [100, 120, 130, 140, 130, 120, 110, 100],
            groupPadding: 0,
            pointPadding: 0,
            minPadding: 0,
            maxPadding: 0,
            color: "#fab1a0",
            marker: {
              enabled: false
            },
            dataLabels: {
              enabled: false
            }
          }
        ],
        plotOptions: {
          series: {
            groupPadding: 0
          },
          area: {
            marker: {
              enabled: false,
              symbol: "radius",
              radius: 1,
              states: {
                hover: {
                  enabled: false
                }
              }
            }
          }
        }
      }
    };
  }
};
</script>
```

**Comment by Izothep** [comment]
Hi @henrytom1703!

Thank you for contacting us with information about your issue. 

It looks that your issue is more the support question than the bug report. In case of any support questions, please contact us on our support channels, like Highcharts forum, StackOverflow or using an e-mail support@highcharts.com.

More information about possible support channels:
https://www.highcharts.com/blog/support/

It seems that you are setting the chart options two times in returned object. Overriding parameters set in your first object may cause the problem with existing spacing on both left and right side of the graph.

In case of spacing on the top of your chart, it might be caused by the default yAxis extremes calculation algorithm - which is leaving the space for the cleaner graph view. You should be able to change it by setting the yAxis.max parameter to your max data value.
