### ISSUE TITLE
[wordcloud] series.data.selected not working

### ISSUE THREAD

**Issue by ramakrishnan3** [highcharts/highcharts#9794]
#### Live demo with steps to reproduce
live demo: https://jsfiddle.net/ramakrishnan3/Lb386c7g/1/
version: v7.0.1

**Comment by pawelfus** [comment]
Hi @ramakrishnan3 

Thanks for reporting! You are right, it looks like `selected` state (and `hover` too) are not implemented. It's probably a bug in documentation.

**Workaround:**
For `selected` point, set initial color. For points-selection (bu user) use `select` and `unselect`events to change CSS styles: https://jsfiddle.net/BlackLabel/e7tg9jsd/

*Internal note:*
I think it would be a great feature to support hover & select states. On hover we could (by default) animate border/shadow and on select we could simply set color (like in columns). It doesn't work at this moment, because states are applied on marker (which a wordcloud series obviously doesn't have).

FYI @jon-a-nygaard

**Comment by ramakrishnan3** [comment]
Hi @pawelfus,

Thanks for the prompt reply it really did help saving the time.

Regards,,
Ram
