### ISSUE TITLE
Docs: chart.type has incomplete list of values

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#9810]
#### Expected behaviour
Listed all series types or no list at all.

#### Actual behaviour
`validvalue`  list is limited to only some of series types. Many are missing - all technical indicators, new series added in v7, etc.

#### Live demo with steps to reproduce
https://github.com/highcharts/highcharts/blob/7c5431802/js/parts/Options.js#L1242-#L1264

#### Product version
7.0.1

Also listed as values on the tree.json - https://api.highcharts.com/highcharts/tree.json
(search for `"values":"[\"line\"` to find it there)

**Comment by TorsteinHonsi** [comment]
We would need a separate list for each product (Highcharts, Highstock, Highmaps and Highcharts Gantt).

**Comment by KacperMadej** [comment]
btw. where is the `tree.json` defined? or on what is it based? @TorsteinHonsi

**Comment by bre1470** [comment]
The `tree.json` file is created by JSDoc with `./tools/jsdoc/plugins/highcharts.jsdoc.js` plugin and is based on the doclets in the `./js` directory.

**Comment by sebastianbochan** [comment]
I think that @KacperMadej means the output of the script and final `tree.json` with all generated doclets.

**Comment by bre1470** [comment]
Regarding the issue I see several problems with it.

- First we lack everywhere support for product-specific valid values (jsdoc plugin, api-docs, generator, wrapper).

- Secondly we miss use cases where you combine several products and also third party series types.

My suggestion is therefor to remove the validvalues tag from the related doclet, because I do not see how it can be satisfying all use cases and instead create a explanation that references the series type tree for our products like this:
```
The value can be the name of one of the possible [series types](series) or the name of an additional series type provided by a loaded module.
```

**Comment by sebastianbochan** [comment]
I will also ask our iOS / Android and .NET developers about using this param.

**Comment by bre1470** [comment]
If it is in use somewhere, there it should imho replaced with the child keys of the `plotOptions` or `series` node.

**Comment by sebastianbochan** [comment]
FYI: Nobody uses the `validvalue` value.
