### ISSUE TITLE
series-label.js too slow 

### ISSUE THREAD

**Issue by rishadali** [highcharts/highcharts#9815]
#### Expected behaviour
https://jsfiddle.net/rishad/vn5Lk16z/
Without series label the chart loads fine 

#### Actual behaviour
https://jsfiddle.net/rishad/vn5Lk16z/4/
But with the series-label on, it takes too long to load.

**Comment by pawelfus** [comment]
Hi @rishadali 

Thank you for reporting the issue! 

*Internal note:*
Loading chart takes ~0.3s, rendering labels takes ~5s. It's probably caused by huge amount of points (8 series x 1000points) - where label positions are based on points' positions.

**Comment by TorsteinHonsi** [comment]
See the demo with the fix applied: https://jsfiddle.net/highcharts/38xm72ac/. The time for generating series labels is now down from ~5s to ~0.2s.

I did three changes to improve performance:
* A regression caused the series label initialization to happen in the middle of the first series animation, causing the series animation to stop and pause half-way through. Fixed that, so now it doesn't start computing until after the series has animated in.
* Spline series have their own interpolation for finding the path to avoid. With dense series it was ineffective because the native `node.getPointAtLength` is quite slow. Fixed it by skipping the spline logic if the point density is high, reverting to treating the series like a line series. Performance improved to ~2s for the original demo.
* Finally, the line series interpolation in this case (with dense points), added all the points. Implemented a simple culling algorithm for `[plotX, plotY]`, so we only add one point per grid cell of 8x8 in the plot area. Now the crash-test algorithm has considerably less points to consider.
