### ISSUE TITLE
Datetime column chart with single point, min, max shows no padding

### ISSUE THREAD

**Issue by adhesivewombat** [highcharts/highcharts#9881]
#### Expected behaviour
![image](https://user-images.githubusercontent.com/8271385/51206682-a9a8f100-18d6-11e9-8e9e-98850fe39afa.png)
A series with a single point and a min/max daterange should show the xAxis with padding on both sides
https://jsfiddle.net/20tjz1Lf/6/
^ this example has two points, the second point is null

#### Actual behaviour
![image](https://user-images.githubusercontent.com/8271385/51206809-099f9780-18d7-11e9-975c-7303ad7aa214.png)

https://jsfiddle.net/20tjz1Lf/5/

There is no padding on either side of the xAxis

**Comment by KacperMadej** [comment]
Hi @adhesivewombat 

Thank you for contacting us.

The problem is caused by Highcharts not being able to guess correctly [pointRange](https://api.highcharts.com/highcharts/series.column.pointRange) with a single point, so you should set it in series option - demo: https://jsfiddle.net/BlackLabel/e8L1jw5f/
