### ISSUE TITLE
Improving Force Directed Graph algorithm

### ISSUE THREAD

**Issue by Izothep** [highcharts/highcharts#9914]
In current version, Force Directed Graph has showing small oscillations during the initial animation with specific data sets. To avoid the oscillations and improve the animation smoothness, changes in algorithm are needed.

**Comment by pawelfus** [comment]
To remove oscillations, Verlet integration was implemented (instead of Euler integration).

Related branch: https://github.com/highcharts/highcharts/tree/feature/networkgraph-verlet

Samples: 
- cloth simulation: [utils](http://utils.highcharts.local/samples/#view/highcharts/series-networkgraph/cloth), [jsfiddle](https://jsfiddle.net/BlackLabel/q6z7egwL/)
- cuboids: [utils](http://utils.highcharts.local/samples/#view/highcharts/series-networkgraph/cuboids), [jsfiddle](https://jsfiddle.net/BlackLabel/2wvtehog/)
- disconnected graph: [utils](http://utils.highcharts.local/samples/#view/highcharts/series-networkgraph/dicsonnected-graphs), [jsfiddle](https://jsfiddle.net/BlackLabel/nofwubv1/)

New issue: Displayed layout is different from the v7.0 one, which, depending on a dataset, is a good or a bad thing (left: v7.0, right: v7.1 candidate):

![screen shot 2019-01-17 at 12 56 30](https://user-images.githubusercontent.com/1453926/51317324-91141480-1a57-11e9-9aa1-d348b2099d8a.png)
![screen shot 2019-01-17 at 12 56 15](https://user-images.githubusercontent.com/1453926/51317325-91141480-1a57-11e9-94ac-29ea423b65d0.png)
![screen shot 2019-01-17 at 12 55 26](https://user-images.githubusercontent.com/1453926/51317326-91141480-1a57-11e9-9c19-e4af0c329cbb.png)
![screen shot 2019-01-17 at 12 55 46](https://user-images.githubusercontent.com/1453926/51317328-91141480-1a57-11e9-9a11-ec7cf666352d.png)
![screen shot 2019-01-17 at 12 57 54](https://user-images.githubusercontent.com/1453926/51317329-91acab00-1a57-11e9-82f2-533c920088d2.png)

**Comment by pawelfus** [comment]
It's done and merged to v7.1 branch.
