### ISSUE TITLE
Zooming doesn't scale Y-Axis if ticks are explicitly set

### ISSUE THREAD

**Issue by seremel** [highcharts/highcharts#9925]
#### Expected behaviour
Both X and Y axes are scaled when zooming even if ticks are set with tickPositions property.

#### Actual behaviour
X axis is scaled.
Y axis is not scaled.

#### Live demo with steps to reproduce
template: http://jsfiddle.net/8rq3s9xw/

#### Product version
Highcharts 7.0.1

#### Affected browser(s)
All

JS to reproduce:
$(function () {
        $('#container').highcharts({
            
            chart: {
                type:'line',
                zoomType:'xy'
            },
            
            title: {
                text: 'Y-Axis not scaling demo'
            },
            
            xAxis: {
                tickPositions: [1, 3, 5, 7, 9, 11]
            },
            
            yAxis: {
                tickPositions: [0, 200, 400, 600]
            },
            
            tooltip: {
                headerFormat: '<b>{series.name}</b><br />',
                pointFormat: 'x = {point.x}, y = {point.y}'
            },
            
            series: [{            
                data: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512],
                pointStart: 1
            }]
        });
    });

**Comment by KacperMadej** [comment]
Hi @seremel 

Thank you for contacting us about the problem.

This is caused by an axis (x or y) having `startOnTick` and `endOnTick` set to true (this is by default done for yAxis) - the problem in a demo (both axes blocked) http://jsfiddle.net/BlackLabel/qm03a5xw/

Resolved through setting mentioned options to false. Additionally you could use min and max to keep axis extremes aligned with set ticks. Demo: http://jsfiddle.net/BlackLabel/qm03a5xw/1/

This doesn't look like a bug.
Is your problem resolved?

**Comment by seremel** [comment]
Hi Kacper
Now it looks like a feature. Yes, the problem is solved. 
Also it would be helpful to have it documented somewhere here:
https://www.highcharts.com/docs/chart-concepts/zooming

**Comment by KacperMadej** [comment]
Good idea - marking the issue as a docs issue.
