### ISSUE TITLE
Logarithmic axis has wrong values when values aren't spread

### ISSUE THREAD

**Issue by TheGreatYamcha** [highcharts/highcharts#9945]
#### Expected behaviour
The ticks on the logarithmic axis should increase by 10 fold. 

#### Actual behaviour
see demo.

#### Live demo with steps to reproduce
https://jsfiddle.net/j8rfwq16/1/

#### Product version
Latest

#### Affected browser(s)
Tested in chrome

**Comment by KacperMadej** [comment]
Hi @TheGreatYamcha 

Thank you for contacting us about the problem.

With such scale plot would be flattened making the data not readable. There's no reason for the axis scale to be forced to show only such values - only requirement is to use the logarithmic "shape" of the scale and with the data in your demo the "shape" is not noticeable due to used range.

You could control how ticks are placed using axis options like tickPositioner, tickPositions, min, max, startOnTick, endOnTick, etc.

This doesn't look like a bug.

**Comment by TorsteinHonsi** [comment]
It's not a bug. The axis is logarithmic, but the range is so close that it looks linear. If we add a different yAxis minimum we will get the desired effect: https://jsfiddle.net/highcharts/5zow7xu1/3/

**Comment by TheGreatYamcha** [comment]
I don't understand. This is a non logarithmic axis with a min specified:
https://jsfiddle.net/bvkq24u3/
And it looks identical to the logarithmic one:
https://jsfiddle.net/j8rfwq16/1/

**Comment by KacperMadej** [comment]
Math checks out - this is how logarithmic scale works. This part of the logarithmic scale is (after rounding to full pixels for sharp rendering) is rendered the same as linear axis in this zoom. Load a chart with greater height, so you will see the difference. `30000px` of height produces few pixels offset in top part of the chart -
https://jsfiddle.net/BlackLabel/h9azbjvm/
vs
https://jsfiddle.net/BlackLabel/udqsrm80/
