### ISSUE TITLE
Cropped points mismatch across series with different cropThreshold

### ISSUE THREAD

**Issue by ogorobets** [highcharts/highcharts#9947]
Hello,
#### Expected behaviour
Expected behaviour: I think that proper behaviuor of Highstock.js library would be to display candle of candlestick chart and bar of volume chart to the most right/left of chart when respective points of SMA and MACD indicators are shown. Or hide points of SMA and MACD indicators to the most left/right of chart if respective points of candlestick and volume charts are not visible.

#### Actual behaviour
Actual behaviour: When user pans chart, candle of candlestick chart and bar of volume chart to the most left (https://prnt.sc/m9snqp) and to the most right (https://prnt.sc/m9sny7) of chart are not shown when respective points of SMA and MACD indicators are shown. But actual points of candlestick and volume chart to the left/right of the chart do exist they are just not shown. So when user pans chart for example a bit more to left or right those extreme points become visible. 

#### Live demo with steps to reproduce

1. Try to zoom chart to level as in screenshots above
2. Try to pan chart to left and/or right and reproduce issue as in screenshots above

Live demo: http://jsfiddle.net/ogorobets/ph12jvx8/51/

#### Product version

Product version: Highstock JS v6.1.1
 
#### Affected browser(s)
Testing  was done in Google Chrome browser (version 69.0.3497.100), macOS Mojave (v. 10.14)

Best regards,
Oleksandr Horobets

**Comment by KacperMadej** [comment]
Hi @ogorobets 

Thank you for reporting about the problem.

Minimal demo: https://jsfiddle.net/BlackLabel/4od3p10j/1/
Steps:
1. Drag navigator window to scroll horizontally the chart and see that only a single column is displayed while extremes are changing.

_Internal note:_
The problem in my demo is resolved by disabling dataGrouping, but this is not the case for the original demo, so maybe there's an important difference there.

**Comment by KacperMadej** [comment]
Hi @ivan0071 

Current status has not changed lately, but I'll investigate the case further.
There's nothing we can't handle, but there's no ETA for the fix at this moment.

After more debugging the problem is not connected to indicators - a indicators-free demo: https://jsfiddle.net/BlackLabel/4od3p10j/2/

I'll try to check this problem even further, to find more useful info about the issue.

**Comment by KacperMadej** [comment]
This is not a Highstock issue ([demo in HC](https://jsfiddle.net/BlackLabel/4od3p10j/4/)). The problem is caused by points exceeding [`cropThresold`](https://api.highcharts.com/highcharts/series.line.cropThreshold). As a solution you could increase the `cropThreshold` for all series to prevent hiding of columns and ohlc/candlestick points.

`plotOptions: {series: {cropThreshold: 5000}},`

Demo: http://jsfiddle.net/BlackLabel/ckegj4a5/

This might affect performance, so another solution could be to increase `cropShoulder` for column series type (ohlc/candlestick will inherit).

`Highcharts.seriesTypes.column.prototype.cropShoulder = 1;`

Broken: https://jsfiddle.net/BlackLabel/4od3p10j/4/
Fixed: https://jsfiddle.net/BlackLabel/4od3p10j/5/
