### ISSUE TITLE
API Docs are broken

### ISSUE THREAD

**Issue by NathanKleekamp** [highcharts/highcharts#9997]
#### Expected behaviour
I can search the API docs (https://api.highcharts.com) and load the documentation.

#### Actual behaviour
I can't search the API docs or load any the docs

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
We have changed our search provider, @bre1470 can probably give some more detail.

**Comment by bre1470** [comment]
Yes, I uploaded the documentation with the v7.0.2 branch in combination with our new search in the api-docs repository. For about two hours between 18 and 20 UTC the website would not show the content because an error in the api.js could not handle the changed menu items. The server files were not in sync at that time frame.

@NathanKleekamp 
Can you confirm that the issue is gone now?

**Comment by NathanKleekamp** [comment]
Yup, working now. Thanks a bunch, all!
